### ISSUE TITLE
Cannot retrieve reports via sfdx force:source:retrieve -m Report

### ISSUE THREAD

**Issue by robcowell** [forcedotcom/cli#10]
### Summary

Trying to pull Reports down from a Dev Sandbox (i.e., non Scratch org) with the command

sfdx force:source retrieve -m Report

gives no results returned, when there are definitely reports in the Org.  No package.xml used in this scenario and I've been made aware that the metadata API doesn't support wildcarding for reports, which could be a factor here.

### Steps To Reproduce:

1.  Targetting a non-Scratch org which contains reports, run the sfdx command indicated above

### Expected result

Report metadata is retrieved from the Org

### Actual result

Message - No Results Returned

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**:

sfdx-cli/6.49.0-8edc6e0f5d (windows-x64) node-v8.9.4

**Comment by clairebianchi** [comment]
@robcowell Reports are created Private by default and therefore are ignored in retrieve. Make your report public and it should work

**Comment by brianedwardsaunders** [comment]
This is not a solution.

**Comment by abychat** [comment]
Hi @clairebianchi this is not working for public reports either. I saved a report in the ootb public reports folder and I couldn't retrieve anything.

**Comment by beeeegaaa** [comment]
Including the folder name lets you retrieve an individual report 

sfdx force:source:retrieve -m Report:ReportFolderName/Report_Name

**Comment by madlantern** [comment]
Hey @robcowell I just struggled through the same issue... saved my report in a public folder, tried to retrieve it using sfdx, and the response in the terminal was that the report was not found. When I checked the file structure, though, I found that it had actually pulled down the report. Maybe check to see if the files did actually get pulled and it just reported incorrectly..?

**Comment by brianedwardsaunders** [comment]
Try this https://www.npmjs.com/package/sfdx-ext (ext:mdapi:retrieve to retrieve everything you need)

**Comment by gontoracq** [comment]
> Including the folder name lets you retrieve an individual report
> 
> sfdx force:source:retrieve -m Report:ReportFolderName/Report_Name

I got my report using this. This is the correct solution even though it says nothing has retrieved.

**Comment by JimBTek** [comment]
How is it ok behavior to ignore some metadata?  this makes it really frustrating to do full metadata backups, and do find/replace operations when deprecating fields

**Comment by jmhoskinson** [comment]
> How is it ok behavior to ignore some metadata? this makes it really frustrating to do full metadata backups, and do find/replace operations when deprecating fields

This is my issue - I'm trying to deprecate fields and we have to tell users that they are on their own for broken private reports
