### ISSUE TITLE
force:source:convert ignores custom fields on custom settings and custom objects

### ISSUE THREAD

**Issue by gonardfreeman** [forcedotcom/cli#100]
### Summary

Hi! 
when converting source to mdapi format cli ignores custom fields at objects and at custom settings (as far as they are in the same folder).
### Steps To Reproduce:

1.  Create custom object
2.  Create custom field (in my case it was long text area with pretty long name `content_gate_object_settings__c`
3. execute `sfdx force:source:convert` (with or without specifying source and output folder).
4. go to generated  folder and then to generated object

### Expected result
Object file have inside fields tag
### Actual result
Object file havent inside fields tag

### Additional information
After some additional research I found out that it ignores only files with long names `content_gate_object_settings__c.field-meta.xml` is long enough to ignore

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.8.1-8f830784cc darwin-x64 node-v10.15.3
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.16.0 (core)
├─ force-language-services 45.12.0 (core)
└─ salesforce-alm 45.18.0 (core)

sfdx-cli 7.8.1 (core)
**macOS v.10.14.5**:

**Comment by mshanemc** [comment]
closed internally, see thread on W-6196127.  Closing on github for consistency, please reopen if still replicable
