### ISSUE TITLE
Missing features in new Scratch Orgs

### ISSUE THREAD

**Issue by w-andre** [forcedotcom/cli#1000]
### Summary

If I create a new scratch org using `sfdx force:org:create` sometimes features are missing.

### Steps To Reproduce:

**Repository to reproduce:** [sfdx-org-create](https://github.com/w-andre/sfdx-org-create)

1. Create a new sfdx project
2. Add the following features to the scratch org definition file:
   ```json
   "features": [
       "EnableSetPasswordInApi",
       "LightningSalesConsole",
       "LightningServiceConsole",
       "SalesUser",
       "ServiceCloud",
       "ServiceUser"
     ]
   ```
1.  Create a new scratch org with the following command:
   `sfdx force:org:create --durationdays=30 --setdefaultusername --definitionfile=config/project-scratch-def.json --dev-debug`
1. Open the org and navigate to Setup --> Apps --> App Manager

### Expected result
"Sales Console" and "Service Console" apps should always be available.

### Actual result
Sometimes "Sales Console" and/or "Service Console" are missing.  
In the following screenshot the "Service Console" app is missing:
![image](https://user-images.githubusercontent.com/12671470/116983035-e2e51500-acc9-11eb-8696-7fbc229e288d.png)
  
The debug output of the `sfdx force:org:create` command can be found [here](https://github.com/w-andre/sfdx-org-create/blob/master/logs/sfdx-force-org-create-output.log).

**SFDX CLI Version**
`sfdx-cli/7.99.0 linux-x64 node-v15.14.0`

**SFDX plugin Version**
```
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.3 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.10.0 (core)
├─ apex 0.1.21 (core)
├─ data 0.4.6 (core)
├─ limits 1.0.6 (core)
├─ custom-metadata 1.0.12 (core)
├─ org 1.6.3 (core)
├─ schema 1.0.6 (core)
├─ templates 51.3.1 (core)
├─ user 1.2.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.16 (core)
sfdx-cli 7.99.0 (core)
telemetry 1.1.2 (core)
```
**OS and version**:
VS Code Dev Container with this image: `salesforce/salesforcedx`

**Comment by w-andre** [comment]
**Update**
The "Service Console" app is now available in the scratch org:  

![image](https://user-images.githubusercontent.com/12671470/116984957-23459280-accc-11eb-93f4-b1a374d371bc.png)

As you can see in the `Last Modified Date` column the "Service Console" app was added (?) 17 minutes after the org was created.

This is problematic in CI/CD scenarios where you push sources directly after org creation.

**Comment by WillieRuemmele** [comment]
Hi @w-andre I'm not sure if you're using an org shape, but there was this [issue](https://github.com/forcedotcom/cli/issues/753) which _might_ be related. If you are, it sounds like deleting `/tmp/shape.zip` will fix your problem

**Comment by w-andre** [comment]
Hi @WillieRuemmele,
thanks for your reply.

We tried using an [org shape](https://developer.salesforce.com/docs/atlas.en-us.228.0.sfdx_dev.meta/sfdx_dev/sfdx_dev_shape_intro.htm) but this did not change anything.  
The behavior stays the same: Some features are *sometimes* not instantly available upon scratch org creation.

If I understand the related issue correctly than this is not related to this issue and not related to using an org shape. In #753 the locally and temporarily created org shape defining the scratch org to be created is not cleared on an additional run with a different scratch org definition file and the contents get mixed together.

We only use one definition file and the referenced output log and screenshots were created from a newly created dev container, so it is not possible that any remaining files in a temp folder were involved.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9234219](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000L86oYAC/view)

**Comment by w-andre** [comment]
Thanks for your response. As suggested I have created an official Salesforce support case.

**Comment by shetzel** [comment]
Closing this as it's being tracked by the support case.
