### ISSUE TITLE
(Relatively) recent regression with force:source:retrieve where LWC meta.xml file is named "*.css-meta.xml"

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#1001]
When working in source format projects, IC2 uses the CLI to move metadata back and forth (among other things). Recently I had a couple of users report that some LWC components were being retrieved with the `meta.xml` file associated with the `.css` bundle file instead of the `.js` bundle file. After some debugging, I'm now able to reproduce this, and it's admittedly a rather corner case behavior, but still broken.

Let me first explain that when a user executes the "retrieve for merge" action in IC2, the `force:source:retrieve` action is executed such that the retrieval occurs into a temporary directory. It does this by setting the executed process' working directory to be the temporary directory while still executing the process from the project directory. This has always worked very well until recently, and it still works well except for the very specific instance of retrieving an LWC bundle that has both a `.js` file and a `.css` file in which case it ends up associating the retrieved `meta.xml` file with the `.css` file. To be specific, the CLI is executed as follows:

```
sfdx force:source:retrieve -u <username> -x /path/to/tempDir/manifest/temp_package.xml --json
```

with a working directory of `/path/to/tempDir`. Again, the CLI itself is executed from the context of the actual project, so there's no `RequiresProjectError` when this command is executed. It has the full project context. The working directory is specified so that the retrieved files are deposited into `/path/to/tempDir` instead of directly into the project.

This is done via Java as follows:

```java
Process process = Runtime.getRuntime().exec(sfdxCommandLine, sfdxEnvironment, tempWorkingDirectory);
```

and to reiterate, this has worked flawlessly since these commands were first integrated into IC2 years ago...until recently, and they still work flawlessly except for this one instance of retrieving such an LWC bundle which yields the following result:

```json
{
  "status": 0,
  "result": {
    "inboundFiles": [
      {
        "state": "Add",
        "fullName": "issue1876\\issue1876.css",
        "type": "LightningComponentBundle",
        "filePath": "force-app\\main\\default\\lwc\\issue1876\\issue1876.css-meta.xml"
      },
      {
        "state": "Add",
        "fullName": "issue1876\\issue1876.html",
        "type": "LightningComponentBundle",
        "filePath": "force-app\\main\\default\\lwc\\issue1876\\issue1876.html"
      },
      {
        "state": "Add",
        "fullName": "issue1876\\issue1876.css",
        "type": "LightningComponentBundle",
        "filePath": "force-app\\main\\default\\lwc\\issue1876\\issue1876.css"
      },
      {
        "state": "Add",
        "fullName": "issue1876\\issue1876.js",
        "type": "LightningComponentBundle",
        "filePath": "force-app\\main\\default\\lwc\\issue1876\\issue1876.js"
      }
    ],
    "warnings": []
  },
  "warnings": []
} 
```

As you can see in the first of the `inboundFiles`, the `meta.xml` file is incorrectly named based on the `.css` file and not the `.js` file.

Hopefully this errant behavior makes sense. Please let me know if not and I'll be happy to provide more details and/or even a simple Java-based driver app for the CLI invocation that reproduces the behavior consistently.

**Comment by mshanemc** [comment]
merge with https://github.com/forcedotcom/cli/issues/761
