### ISSUE TITLE
Close execute anonymous immediately after executing piped command

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#1002]
**Is your feature request related to a problem? Please describe.**
I find it quite useful to use these quick apex snippets to clear out database between tests, but don't want to create apex files for them.
```
echo "delete [select id from lead limit 2000];" | sfdx force:apex:execute
```
If Apex executes in about 5 seconds, the actual shell command takes another ~55 seconds to complete (I think apex times out). Perhaps there can be a flag added that terminates command immediately?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9226395](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000KyYXYA0/view)

**Comment by shetzel** [comment]
This seems more like a bug to me.  Thanks for posting this.

**Comment by sjurgis** [comment]
This has been fixed at some point
