### ISSUE TITLE
Broken JSON output for force:package:version:create

### ISSUE THREAD

**Issue by aly76** [forcedotcom/cli#1003]
### Summary

`sfdx force:package:version:create --json` is leaking log statements to the console, in JSON mode.

### Steps To Reproduce:

1. Create package version with `--json` flag 

### Expected result

Only the JSON output should be printed to the console.

### Actual result

❯ sfdx force:package:version:create -p mypackage  -w 120 --definitionfile config/project-scratch-def.json --json -x --skipvalidation -v devhub
**Dependency on package A was resolved to version number 1.0.4.2, branch null, 04t.
Dependency on package B was resolved to version number 1.0.2.2, branch null, 04t.
Dependency on package B was resolved to version number 1.0.4.2, branch null, 04t.**
{
  "status": 0,
  "result": {
    "Id": "08c4",
    "Status": "Success",
    "Package2Id": "0Ho4",
    "Package2VersionId": "05i",
    "SubscriberPackageVersionId": "04t",
    "Tag": null,
    "Branch": null,
    "Error": [],
    "CreatedDate": "2021-05-05 16:24",
    "HasMetadataRemoved": false
  }
}

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
7.99.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
51.10.0

**OS and version**:
macOS 10.15.7

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9228829](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000L1ZdYAK/view)

**Comment by gsbasso** [comment]
Once again a CLI update has broken our CI process. What is the ETA for a fix (or at least an option to suppress the additional verbiage)? We need to assess whether we need to spend time devising a workaround on our own. Thanks.

**Comment by azlam-abdulsalam** [comment]
@gsbasso  We use a docker image to counter this and test through all commands before an update

**Comment by fl43** [comment]
Things like this should not happen. It looks like there are no proper unit tests in place.

**Comment by shetzel** [comment]
The fix is in the release candidate from last week Thursday.  It will be promoted tomorrow.  Apologies for the regression!

**Comment by mshanemc** [comment]
fixed in latest release
