### ISSUE TITLE
When executing force:project:create, `.eslintignore` doesn't contain "*.app"

### ISSUE THREAD

**Issue by zaki-yama** [forcedotcom/cli#1004]
### Summary

When I create a project by `sfdx force:project:create`, the generated .eslintignore doesn't contain `*.app` which represents Lightning(Aura) Application.

### Steps To Reproduce:

**Repository to reproduce:** https://github.com/zaki-yama-labs/standard-sfdx-project

1.  Create a project by `sfdx force:project:create --projectname=standard-sfdx-project`
1.  `cd standard-sfdx-project`
2. Open `.eslintignore`

### Expected result

I think `.eslintignore` should contain `**/aura/**/*.app` same as other aura-related resources.

### Actual result

It doesn't contain `**/aura/**/*.app`.

### Additional information

The problem is, if there are Lightning Application files (`*.app`) locally, then run `npm run lint:aura`, it raises an error.

```
$ npm run lint:aura

> salesforce-app@1.0.0 lint:aura /Users/yamazaki/repos/github.com/zaki-yama-labs/standard-sfdx-project
> eslint **/aura/**


/Users/yamazaki/repos/github.com/zaki-yama-labs/standard-sfdx-project/force-app/main/default/aura/TestApp/TestApp.app
  1:1  error  Parsing error: Unexpected token <

✖ 1 problem (1 error, 0 warnings)
```

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

```
$ sfdx --version
sfdx-cli/7.94.3-a4e7c7955b darwin-x64 node-v14.15.4
```

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

```
$ sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.5.1 (core)
config 1.2.7 (core)
generator 1.1.5 (core)
salesforcedx 51.6.0 (core)
├─ data 0.4.3 (core)
├─ limits 1.0.4 (core)
├─ schema 1.0.4 (core)
├─ apex 0.1.4 (core)
├─ templates 51.3.0 (core)
├─ org 1.6.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.11 (core)
├─ salesforce-alm 51.6.6 (core)
└─ user 1.2.1 (core)
sfdx-cli 7.94.3 (core)
telemetry 1.1.1 (core)
```

**OS and version**:
macOS Big Sur 11.3

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9229019](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000L1nuYAC/view)

**Comment by WillieRuemmele** [comment]
Hi @zaki-yama this was merged and will be released soon. Thanks for pointing that out 👍

**Comment by zaki-yama** [comment]
@WillieRuemmele 
Thank you for the quick fix!
