### ISSUE TITLE
Error: HTTP 403: Invalid channel cli when updating sfdx cli

### ISSUE THREAD

**Issue by halldor-kaptio** [forcedotcom/cli#1006]
### Summary

I am unable to update CLI due to a "HTTP 403: Invalid channel cli" error.
I've tried reinstalling the CLI
I've tried reinstalling "Salesforce Extension Pack" in VS Code 
I've tried running the update as admin (sudo)

### Steps To Reproduce:

I don't know. The only thing I've done today related to CLI prior to this happening is updating VS Code to version 1.56.0

1. Run "sfdx update cli" in terminal

### Expected result

CLI should update to the latest version

### Actual result

When updating the CLI it flickers "Getting Manifest" and I then get the following result almost instantly: 
`sfdx-cli: Updating CLI... !
Error: HTTP 403: Invalid channel cli`

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.99.0 darwin-x64 node-v14.9.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.3 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.10.0 (core)
├─ data 0.4.6 (core)
├─ apex 0.1.21 (core)
├─ custom-metadata 1.0.12 (core)
├─ limits 1.0.6 (core)
├─ org 1.6.3 (core)
├─ user 1.2.8 (core)
├─ schema 1.0.6 (core)
├─ templates 51.3.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.16 (core)
sfdx-cli 7.99.0 (core)
telemetry 1.1.2 (core)

**OS and version**:
Mac OS Big Sur, 11.3.1

**Comment by WillieRuemmele** [comment]
Hi @halldor-kaptio the command should be `sfdx update` not `sfdx update cli` let me know if that fixes it 👍

**Comment by halldor-kaptio** [comment]
@WillieRuemmele That works, Thanks :) 

It's strange, I've been using the other command with success but now looking at docs I don't see it anywhere. Perhaps older versions ignored the extra parameter
