### ISSUE TITLE
SFDX is throwing a timeout error when using Zscaler

### ISSUE THREAD

**Issue by anaeliag** [forcedotcom/cli#1007]
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/38703810/117320350-c378f400-ae51-11eb-97db-1376530beb99.png)

### Summary

Hi Github team,

A new Bamboo instance more secure has been setup in my team that uses Zscaler to handle the external traffic, previously our instance was setup to connect to internet without using a proxy, so we had no issues to deploy the code with SFDX, but after the new instance was setup we started to get timeout errors for all the SFDX plans, so, wanted to check if there is a timeout parameter that I can increase in my configuration for SFDX, I checked with the Salesforce support team and they asked me to check on this with you, please share with me any thoughts you may have to fix this error.

0-Apr-2021 11:43:00 ERROR: Error: read ETIMEDOUT
30-Apr-2021 11:43:00 Unhandled rejection Error: read ETIMEDOUT
30-Apr-2021 11:43:00 at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)

This is how the new instance was setup:

SF instance -> Proxy Server -> Zscaler -> internet

Thank you.

### Steps To Reproduce:

The repo is private so, I cannot share it, but we deploy 5292 components and 678 apex tests

1. To test all the components with SFDX through Bamboo
2. Before the build is completed, and near to the 4000 component the disconnection happens and got the above error.

### Expected result

Build must be succesfull

### Actual result

The test is continue working on the Salesforce side correctly but in Bamboo the process hung up and the rest of the stages cannot be completed.

### Additional information

0-Apr-2021 11:43:00ERROR: Error: read ETIMEDOUT30-Apr-2021 11:43:00Unhandled rejection Error: read ETIMEDOUT30-Apr-2021 11:43:00 at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/38703810/117319345-d212db80-ae50-11eb-8dd1-b79520bd0a6d.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.0 (core)
├─ schema 1.0.1 (core)
├─ salesforce-alm 50.7.0 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.82.0 (core)

**OS and version**:
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

**Comment by shetzel** [comment]
Hi - can you try using the `--wait` parameter on the command to increase the wait time?

**Comment by himanshu-IN** [comment]
@shetzel I am Facing the same issue. How to add this `--wait` parameter in automated commands dynamically ?

**Comment by AjManoj** [comment]
Hi 

By default node uses HTTP_PROXY and HTTPS_PROXY environment variables to connect internet behind corporate proxy.Try setting that to your proxy server with creadentials.


As per  [jsforce corporate proxy bug](https://github.com/jsforce/jsforce/issues/1)

There is [merge request](https://github.com/jsforce/jsforce/pull/581) which let us set corporate proxy and connection is successful. Can we allow setting this paramater as sfdx cli command parameters, which will allow us to use sfdx behind corporate proxy.

**Comment by mshanemc** [comment]
the mentioned PR is going to make deployments more tolerant of network error problems.  It won't help the current `force:mdapi:deploy` but will be part of the upcoming `force:mdapi:beta:deploy`

If you can use `source:deploy` you'll get the improvement, too.

**Comment by tehnrd** [comment]
This is pretty much a Zscaler issue. FWIW I disabled the Internet Security option in Zscaler, and it resolved the issue. 

Probably something in the payload is setting off a false positive in Zscaler, and it is killing the connection.
