### ISSUE TITLE
Cannot Deploy KnwoledgeSettings using GitLab CI

### ISSUE THREAD

**Issue by jcarmignani** [forcedotcom/cli#1008]
### Summary

Deployment fails when I deploy KnowledgeSettings from GitLab CI. I have tried with VS Code using same Knowledge.settings-meta.xml file and it is working fine.

![image](https://user-images.githubusercontent.com/11173517/117352897-cd314480-aeaf-11eb-823d-a43e64b3656f.png)

### Steps To Reproduce:

Retrieve KnowledgeSettings from VS Code using Salesforce CLI with following Manifest:
`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">

    <types>
        <members>Knowledge</members>
        <name>Settings</name>
    </types>

    <version>51.0</version>
</Package>`

Then Version the code in Git and deploy using GitLab CI

### Expected result

KnowledgeSettings should deploy on the target org successfully

### Actual result

Got a weird error message with error message = "enableKnowledgeAgentContribution"

### Additional information

I have tried to deploy on the Target org using VS Code and it is working fine

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
(GitLab CI) sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3
(VS Code) sfdx-cli/7.94.3-a4e7c7955b win32-x64 node-v14.15.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
(GitLab CI)

`@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.0 (core)
├─ schema 1.0.1 (core)
├─ salesforce-alm 50.7.0 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.82.0 (core)`

(VS Code)
`@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.3 (1.4.3)
config 1.2.7 (core)
generator 1.1.5 (core)
odaseva-dx 0.0.0
salesforcedx 51.7.1 (latest-rc)
├─ salesforce-alm 51.6.10
├─ data 0.4.3
├─ custom-metadata 1.0.11
├─ apex 0.1.21
├─ limits 1.0.5
├─ org 1.6.1
├─ schema 1.0.5
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ templates 51.3.0
└─ user 1.2.8
sfdx-cli 7.94.3 (core)
telemetry 1.1.1 (core)`

**OS and version**:
(GitLab CI) 
gitlab-runner 13.0.1
Using Docker executor with image node:latest 

(VS Code)
![image](https://user-images.githubusercontent.com/11173517/117353619-9f98cb00-aeb0-11eb-80ab-6e46ede9a2e8.png)

**Comment by jcarmignani** [comment]
I have updated the link to retrieve SFDX TAR archive but I stll have the issue while deploying. I have run the test with version 7.100 in GitLab.

**Comment by shetzel** [comment]
Hi - this will be fixed when the source plugin we're working on makes its way to the production CLI.

**Comment by jcarmignani** [comment]
Hi @shetzel - Great news! Do you have an idea when the fix will be available?

**Comment by shetzel** [comment]
@jcarmignani - I assumed the problem was that it wasn't yet supported in the CLI but after trying to reproduce the problem now in the CLI I don't see that problem.  I'm able to deploy KnowledgeSettings just fine from the CLI.  Is this more a matter of the gitlab environment versus non-gitlab?  I'm not very familiar with the KnowledgeSettings type but from the error message it seems like something isn't setup properly.  When you're comparing vs-code to the CLI for deploys, are you using the same org?

**Comment by jcarmignani** [comment]
@shetzel I am not using exactly same Profile from VS Code (System Administrator) vs from GitLab (Custom Profile with View All Data to deploy Active Flows but not Modify All Data).

I am able to deploy PathSettings and ExperienceSettings using this config with the GitLab profile in Salesforce.

I have checked the documentation related [KnowledgeSettings](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_knowledgesettings.htm) and I have not seen any additional User Permission that I should grant. 

Do you know if I need to grant Knowledge permissions to be capable to deploy this metadata? (Or any other permission)

**Comment by jcarmignani** [comment]
@shetzel I have been able to fix the issue. The error was due to missing user permission "Manage Salesforce Knowledge" that is required to be capable to deploy this metadata type

**Comment by shetzel** [comment]
@jcarmignani - glad you were able to fix the issue!
