### ISSUE TITLE
force:package:version:create should not require --package/--path flags when default specified

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#101]
### Summary

The `force:package:version:create` command requires that either the `--package` flag or the `--path` flag be specified.   The reason for this is obvious -- it allows the CLI to determine which of `packageDirectories` is the one to use for package version creation.

However, the [Salesforce DX Developer Guide -- "Project Configuration File for Packages" section](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev2gp_config_file.htm) states that the `default` parameter in the `packageDirectory` entry will "...indicate which is the default package directory."

In other words, the CLI is not respecting the `default` parameter designation.

### Steps To Reproduce:

1.  Create a SFDX project with a packageDirectory designated as default = true.
1.  Execute `force:package:version:create` without the --package/--path flag.

### Expected result

Because the sfdx-project.json file has a packageDirectory designated as the default, the CLI should use that value when --package/--path flags are not specified.

### Actual result

The default entry in the sfdx-project.json is not honored by the CLI and the command fails.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):  sfdx-cli/7.8.1-8f830784cc darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.16.0 (core)
├─ force-language-services 45.12.0 (core)
└─ salesforce-alm 45.18.0 (core)
sfdx-cli 7.8.1 (core)

**OS and version**:
MacOS v10.14.5

**Comment by clairebianchi** [comment]
@sfdc-db-gmail can you please take a look at this? it looks like a packaging bug

**Comment by sfdc-db-gmail** [comment]
@ImJohnMDaniel - I have added this to my backlog. It is a relatively low priority item as far as I see as there is a very easy workaround :-)

@clairebianchi
