### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by doug-kells** [forcedotcom/cli#1012]
### Summary
Throughout this week, our team has been experiencing intermittent issues with CLI commands failing with an error "getaddrinfo EAI_AGAIN". This is intermittently happening with any sfdx CLI command, from force:org:create, force:user:permset:assign, force:source:push, force:source:pull, and force:package:install.

### Steps To Reproduce:
**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)
This may be difficult to intentionally reproduce, as any command may or may not work at any given moment. I've also not been able to reproduce this outside our work environment (the same commands work consistently without error from my home computer with the same overall configuration) but our network technicians have been unable to determine a cause or come to a resolution.

From the Dreamhouse repository.
1. sfdx force:org:create -s -f config/project-scratch-def.json -a dreamhouse
2. sfdx force:source:push

### Expected result
Source pushed to new scratch org.

### Actual result
sfdx force:source:push
*** Deploying with SOAP ***
Job ID | 0Af1700001en4uFCAQ
SOURCE PROGRESS | ████████████████████████████████████████ | 86/86 ComponentsERROR:  Error: getaddrinfo EAI_AGAIN momentum-site-5413-dev-ed.cs22.my.salesforce.com
Unhandled rejection Error: getaddrinfo EAI_AGAIN momentum-site-5413-dev-ed.cs22.my.salesforce.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26)

Similar result if installing package into scratch org:
sfdx force:package:install -w 20 -p 04t3h000004smn8AAA
Error: getaddrinfo EAI_AGAIN momentum-site-5413-dev-ed.cs22.my.salesforce.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'momentum-site-5413-dev-ed.cs22.my.salesforce.com'
}
ERROR running force:package:install:  getaddrinfo EAI_AGAIN momentum-site-5413-dev-ed.cs22.my.salesforce.com
Error: getaddrinfo EAI_AGAIN momentum-site-5413-dev-ed.cs22.my.salesforce.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:69:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'momentum-site-5413-dev-ed.cs22.my.salesforce.com'
}

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.100.0 win32-x64 node-v16.0.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.3 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.11.0 (core)
├─ apex 0.1.21 (core)
├─ data 0.4.6 (core)
├─ custom-metadata 1.0.12 (core)
├─ limits 1.1.0 (core)
├─ user 1.2.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ org 1.6.4 (core)
├─ schema 1.0.6 (core)
├─ templates 51.3.1 (core)
└─ salesforce-alm 51.6.18 (core)
sfdx-cli 7.100.0 (core)
telemetry 1.2.0 (core)

**OS and version**:
Windows 10 Enterprise, version 1909

**Comment by shetzel** [comment]
This was likely due to a DNS issue that affected many instances.  It has now been resolved.  Are you still seeing these errors?

**Comment by doug-kells** [comment]
Hi Steve, 

Thanks for getting back to me We had considered that it could be related to yesterday's outage. Unfortunately, it has persisted throughout the day today, so it is ongoing.

**Comment by maggiben** [comment]
Have you tried `sfdx force:source:deploy` ?

**Comment by doug-kells** [comment]
Hello, sfdx force:source:deploy is among the commands that occasionally returns this error. Basically, any sfdx command may or may not return this error. 

I should point out that the execution of the command may or may not work even though the response has this error. Example: if I run sfdx force:package:install -w 5 -p 04t... it may immediately fail without starting the installation process. 

Or it may successfully start installing and being displaying "Waiting for the package install request to complete. Status = IN_PROGRESS" and then fail at any point during during the wait while the cli is checking the status of the installation. In that case, the installation does succeed and you find out when the scratch org emails us.

**Comment by daveespo** [comment]
According to this, someone at SF is looking into this:

https://trailblazers.salesforce.com/0D54S00000A6gjs

**Comment by doug-kells** [comment]
Hi David, Thanks for finding that thread. I'm at least relieved that isn't just me. 

I will let the Salesforce employee as part of this decide on a preference as to whether to keep this issue open or whether to close it and just pay attention to trailblazer community.

**Comment by olafure** [comment]
@shetzel there is still an serious intermittent DNS outage as of now.

If you create a scratch org, try doing a `dig` on the hostname. Something like
`dig customization-enterpris-40f-dev-ed.cs68.my.salesforce.com`
Sometimes you'll get an answer, sometimes not.

![mxtoolbox report](https://user-images.githubusercontent.com/830918/118152045-2e0ad080-b40c-11eb-80f6-cac843f78dcb.png)

**Comment by shetzel** [comment]
@olafure @doug-kells - The DNS team has been urgently working on this.  That last update I saw minutes ago was that they think it's now fixed.  Since this is not a CLI issue I will close this.  Please use the trailblazer link above for more updates.  Thank you for reporting and apologies for the service interruption!
