### ISSUE TITLE
New Release objects cause errors in pull command

### ISSUE THREAD

**Issue by Dane1986** [forcedotcom/cli#1014]
### Summary

It's not possible to do a pull from a developer sandbox after the new release is installed, errors show Listview not found for several new standard objects. For example Work Plan. This happens with every new release. Workaround can be adding these objects to the force ignore file but that for me is not a workaround. When there is a new object, sfdx should recognize the whole object as new and should pull accordingly.

### Steps To Reproduce:

1.  Do a full retrieve of the production org to create a (git) full sandbox project
2.  Create a new developer sandbox
3.  Perform pull -f command

### Expected result

Pull with or without changes.

### Actual result

The following error occurs:
ERROR running force:source:pull:  Source conflict(s) detected.
ERROR running force:source:pull:  Entity of type 'ListView' named 'WorkPlanTemplate.My_WorkPlanTemplates' cannot be found
Entity of type 'ListView' named 'WorkPlanSelectionRule.My_WorkPlanSelectionRules' cannot be found
Entity of type 'ListView' named 'WorkPlan.All_WorkPlans' cannot be found
Entity of type 'ListView' named 'WorkPlan.My_WorkPlans' cannot be found
Entity of type 'ListView' named 'WorkStepTemplate.My_WorkStepTemplates' cannot be found
Entity of type 'ListView' named 'WorkPlan.My_RecentWorkPlans' cannot be found
Entity of type 'ListView' named 'WorkPlanSelectionRule.My_RecentWorkPlanSelectionRules' cannot be found
Entity of type 'ListView' named 'WorkPlanTemplate.My_RecentWorkPlanTemplates' cannot be found
Entity of type 'ListView' named 'WorkStepTemplate.My_RecentWorkStepTemplates' cannot be found
Entity of type 'ListView' named 'WorkPlanTemplate.All_WorkPlanTemplates' cannot be found
Entity of type 'ListView' named 'WorkStepTemplate.All_WorkStepTemplates' cannot be found

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.101.0-5e36989

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): 50.12.0

**OS and version**: Windows 10 latest updates

**Comment by maggiben** [comment]
Hi Dane1986, Im doing a `sfdx force:source:pull -f` on a scratch or and works fine, maybe its something to do with sandboxes specifically ?, can your you create a barebones org for us to test ?

**Comment by shetzel** [comment]
What does the generated package.xml and pulled metadata look like for the pull request?  You can inspect it more easily if you set the `SFDX_MDAPI_TEMP_DIR` env var to a known location, do the pull, then inspect the contents.

**Comment by Dane1986** [comment]
The problem occurs when you have a full org git repo, the new standard objects are not in de objects folder which is sort of a logical issue. But after retrieving the new standard objects to the repo and redeploying them to the sandbox (somehow the listviews that are retrieved are then "Created" again, which is strange because I retrieved them from that sandbox) I still get the Listview error for the "MyRecent...." listviews for those objects. I changed the opening post to add the step of creating a full org project.

When the object is in the project and I do a pull, then I still get these errors:
ERROR running force:source:pull:  Entity of type 'ListView' named 'WorkPlan.My_RecentWorkPlans' cannot be found
Entity of type 'ListView' named 'WorkPlanSelectionRule.My_RecentWorkPlanSelectionRules' cannot be found
Entity of type 'ListView' named 'WorkPlanTemplate.My_RecentWorkPlanTemplates' cannot be found
Entity of type 'ListView' named 'WorkStepTemplate.My_RecentWorkStepTemplates' cannot be found

**Comment by mshanemc** [comment]
Does it happen on anything besides these WorkPlan* objects? And also, I second Steve's question about what's happening in the package.xml (via the temp dir)

**Comment by Dane1986** [comment]
I will try to do the analyses on SFDX_MDAPI_TEMP_DIR today. @mshanemc We had this before with ShiftTemplate objects. We work with a developer sandbox for each feature and my guess is that this does happen when we create a new sandbox from production (which doesn't have these objects yet) and Salesforce then "installs" the new features in the creation process. The new stuff is then not properly flagged as created in changes. It is not seen as a new object/listview, but sfdx gives an error.

**Comment by jh480** [comment]
For anyone interested, this seems to be a metadata-API feature with "pre-installed" listviews that are localised (change user language => listview name changes too).
These listviews are visible via listMetadata, but cannot be retrieved on their own, only via the whole CustomObject.
Deploying them will create a new double entry with the same fullname (both visible in listMetadata), but with static (English) label, which then can also be retrieved on its own (though, with mdapi, retrieval of the whole object and another deployment will fail with a duplicate-name error).
Best course of action would be to add any such listviews to [.forceignore](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm).
