### ISSUE TITLE
We're removing the `salesforcedx` aggregator plug-in soon

### ISSUE THREAD

**Issue by jshackell-sfdc** [forcedotcom/cli#1016]
We plan to remove the `salesforcedx` plug-in from Salesforce CLI in the coming months. Don’t worry, we’re not removing any functionality! The `salesforcedx` plug-in doesn’t do much; it simply aggregates other ones that contain the commands for creating scratch orgs, deploying source, and so on. The CLI itself is already an aggregator plug-in. So in the spirit of simplicity, we’re removing the unnecessary `salesforcedx` plug-in. 

To prepare for this change:

- If you previously installed a tagged version of `salesforcedx` in your CLI, such as with the `sfdx plugins:install salesforcedx@latest-rc` command, remove that version with this command:

    `sfdx plugins:uninstall salesforcedx`

    If you want to install and test the release candidate, run this command instead:

    `sfdx update stable-rc`

- Remove the `sfdx plugins:install salesforcedx` command from your scripts.  

Until we completely remove `salesforcedx` from Salesforce CLI, you'll still see it in your list of plug-ins, such as in the `sfdx plugins --core` output. We'll announce the exact date we plan to remove it, after which you'll no longer see it listed.  

We're also updating the [Salesforce CLI Setup Guide](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_intro.htm) to no longer mention the `salesforcedx` plug-in.

**Comment by yippie** [comment]
In the new install method, how do I install a specific version?

In CI we do `sdfx plugins:install salesforcedx@51.1.1` to ensure a stable would the syntax just be `sfdx update 51.1.1` ?

**Comment by mshanemc** [comment]
@yippie 
npm-based installs have it easy `npm install -g sfdx-cli@x.x.x` and that's what I'd recommend for CI.  Those numbers are on the weekly release notes.

We're working on a way to make it simpler to find older versions of the CLI installers/tarballs so you can install exactly what you want that way, too.

**Comment by yippie** [comment]
We don't use npm install because we have been burned by it badly in the past. Typically it is behind, which for this use case isn't a big deal. But more importantly it did not properly pin its dependencies causing ALL versions to break in out CI, with no work around, when a dependency published a breaking version update.

Pinning the tar to a specific version of both the cli and salesforcedx plugin set would be ideal because we have also had issues where the latest cli version had issues that installing a version of salesforcedx plugin did not work around

**Comment by mshanemc** [comment]
@yippie and others...please see this week's release notes for details about using older versions.  Those files are live now, and we'll get them added to the dev guide soon.
https://github.com/forcedotcom/cli/tree/main/releasenotes#51140-may-27-2021---cli-71030
