### ISSUE TITLE
Empty Differences

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#1017]
For last few months, I have been getting empty differences with files between my org and when retrieved from CLI using Mac Terminal even when there are no differences. No matter what I do, I keep getting these differences in 100s files. When I retrieve the same file from VS Code, it doesn't show any differences.

sfdx-cli/7.101.0 darwin-x64 node-v16.0.0

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.3 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.12.0 (core)
├─ apex 0.2.0 (core)
├─ org 1.6.5 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ schema 1.0.6 (core)
├─ user 1.2.10 (core)
├─ custom-metadata 1.0.12 (core)
├─ limits 1.2.0 (core)
├─ salesforce-alm 51.6.23 (core)
├─ templates 51.3.1 (core)
└─ data 0.4.6 (core)
sfdx-cli 7.101.0 (core)
telemetry 1.2.0 (core)

MacOS BigSur 11.4

![image](https://user-images.githubusercontent.com/65677387/118722344-abaa5400-b7f1-11eb-9577-74a2e704349d.png)

![image](https://user-images.githubusercontent.com/65677387/118722357-b1079e80-b7f1-11eb-97cb-882b56abbc6f.png)

![image](https://user-images.githubusercontent.com/65677387/118722370-b664e900-b7f1-11eb-9009-ceb5d7a6fd26.png)

**Comment by maggiben** [comment]
Hi Ram, are all these spaces and new-line differences ? doesn't look like the code is affected, is it ?

**Comment by shetzel** [comment]
I'm assuming you're retrieving with `force:source:retrieve` versus pull or mdapi:retrieve.  If this is the case, it's because VS Code recently changed to a new library for doing deploys/retrieves and writing the files to disk.  The CLI will be switching to the same library very soon so the white space differences should go away.  In the meantime you can adjust your git settings to ignore white space changes.

**Comment by ghost** [comment]
> I'm assuming you're retrieving with `force:source:retrieve` versus pull or mdapi:retrieve. If this is the case, it's because VS Code recently changed to a new library for doing deploys/retrieves and writing the files to disk. The CLI will be switching to the same library very soon so the white space differences should go away. In the meantime you can adjust your git settings to ignore white space changes.

This makes sense, thanks. Any expected date on when CLI will be switching to this? Also, I have tried many ways to ignore whitespaces in Git settings, but nothing seems to work. Do you have any suggestion on how ignore these whitespaces in Git settings?

**Comment by shetzel** [comment]
I'm hopeful that the source plugin will be made available to the public within a few weeks for testing and feedback (a beta of sorts).

As for git settings I would just continue to search online docs and try things.
