### ISSUE TITLE
Permissions to run force:apex:test:run

### ISSUE THREAD

**Issue by jcarmignani** [forcedotcom/cli#1019]
### Summary

I want to run all Apex Tests part of a CI pipeline. For that I have a CI User using with a custom CI Profile with the following User Permissions as specified [here](https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/code_sample_java_prereqs.htm):
- API Enabled (I have also set use Any Client API in addition)
- Apex Author
- Push Topis object: Read/Create/Edit/Delete
- Streaming API is enabled on my Org

### Steps To Reproduce:

- Open VS Code
- Run the following command: sfdx force:apex:test:run

### Expected result

Run all the Tests successfully

### Actual result

Despite all of the permissions, I get the following error message when I run the Apex Tests from the CLI:
![image](https://user-images.githubusercontent.com/11173517/118958047-5725e680-b961-11eb-90d6-6c8ac5db761a.png)

### Additional information

![image](https://user-images.githubusercontent.com/11173517/118959663-d2d46300-b962-11eb-8709-97eba7c38366.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.101.0 win32-x64 node-v16.0.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.4.3 (1.4.3)
config 1.2.8 (core)
generator 1.1.5 (core)
odaseva-dx 0.0.0
salesforcedx 51.13.0 (latest-rc)
├─ salesforce-alm 51.6.23
├─ custom-metadata 1.0.12
├─ data 0.4.6
├─ org 1.6.6
├─ apex 0.2.0
├─ templates 51.4.0
├─ limits 1.2.1
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ schema 1.0.7
└─ user 1.2.11
sfdx-cli 7.101.0 (core)
telemetry 1.2.0 (core)

**OS and version**:
![image](https://user-images.githubusercontent.com/11173517/118958466-be439b00-b961-11eb-8b1f-e2f32aaa2437.png)

**Comment by mshanemc** [comment]
One suggestion I got from the apex team: 

Check if your tests are using `System.runAs()` as another user, that **that user** also has the streaming permissions you listed.

**Comment by jcarmignani** [comment]
> One suggestion I got from the apex team:
> 
> Check if your tests are using `System.runAs()` as another user, that **that user** also has the streaming permissions you listed.

@mshanemc Yes we are using lots of System.runAs() statements that run codes as Overage Authenticated Website users. Does it mean I cannot launch the tests this way?

For info I have launched the tests from VS Code using a System Admin user and it is working fine so I think he can work even with the Site users with my Custom CI profile no?

**Comment by mshanemc** [comment]
That's my understanding from what the apex team said.  If you can find some way to give the OAW user access to the needed permissions (may not on the profile, but maybe assign a permset during the test execution or setup) then it might work.

**Comment by jcarmignani** [comment]
Thanks for following up @mshanemc 

I have made additional tests today and I have seen that it works when I add the "Debug Apex" permission which also grant the Modify All Data permission. I have created a Permission Set and assign it temporary during the execution of the script. 

I will communicate my findings with Support team so they can enrich the Knowledge Base if they wish

**Comment by mshanemc** [comment]
also, please send links to any documentation that you used and think should be changed

**Comment by jcarmignani** [comment]
@mshanemc Initially I have used the [Prerequisite](https://developer.salesforce.com/docs/atlas.en-us.api_streaming.meta/api_streaming/code_sample_java_prereqs.htm) section of Streaming API Developer Guide so maybe you could add infos there.

It would be great to enrich Salesforce CLI Command Reference with the following sections for each command for people as me that are trying to give only minimum permissions to CI profile:
1. Required Permissions to run the command
2. Known/Common issues and how to deal with them

In parallel of this issue I had raised a case on Salesforce support for the [force:community:publish](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_community.htm#cli_reference_force_community_publish) command. I was able to deploy the Community using my CI profile but I was not able to publish it using the CLI:
![image](https://user-images.githubusercontent.com/11173517/119406470-21775980-bce3-11eb-82b3-afa3d8a2a6f5.png)

Here the issue was not linked with Profile permissions, my profile was having Create and Set Up Experiences permission but with the fact that the CI profile was not a member of my Community (Administration > Members > Selected Profiles > Community Publisher custom profile):
![image](https://user-images.githubusercontent.com/11173517/119407082-022cfc00-bce4-11eb-9180-23fd5ff9b9bf.png)

When you fix the membership issue you are able to publish the Community (I have not found that anything related to that in Salesforce docs, maybe I have not looked enough):
![image](https://user-images.githubusercontent.com/11173517/119407327-5b952b00-bce4-11eb-9152-cb882ce81aa6.png)
