### ISSUE TITLE
force:package:version:create:report command with --json flag returns array of statues

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#102]
### Summary

If you execute the `force:package:version:create:report` with the `--json` flag, the result will be something like the following.
```
{
  "status": 0,
  "result": [
    {
      "Id": "08c1O000000fxTTQAZ",
      "Status": "InProgress",
      "Package2Id": "0Ho1O000000GmaESAP",
      "Package2VersionId": null,
      "SubscriberPackageVersionId": null,
      "Tag": null,
      "Branch": null,
      "Error": [],
      "CreatedDate": "2019-06-01 06:10"
    }
  ]
}
```
The issue is that the `result` attribute is showing as a JSON Array and not a JSON Object.  The implication is that there can be multiple package version create processes.

This was originally reported in [January 2018 on the "Unlocked Packages and Managed 2GPs" Trailblazer Group](https://success.salesforce.com/0D53A00003OTsAD).  Bug ticket W-4621618 was opened for this issue.

I can confirm that it is still occurring and needs to be fixed.

### Steps To Reproduce:

1.  See summary above

### Expected result

JSON attribute `result` should be a JSON Object

### Actual result

JSON attribute `result` is returned as a JSON Array

**Comment by ImJohnMDaniel** [comment]
It should be noted that the `force:package:version:create` command with the `--json` flag produces the same type of JSON object for the package version create process but the result attribute of the overall response in this command is simply the package version create process response JSON object and not a JSON array containing the package version create process response.

```
{
  "status": 0,
  "result": {
      "Id": "08c1O000000fxTTQAZ",
      "Status": "InProgress",
      "Package2Id": "0Ho1O000000GmaESAP",
      "Package2VersionId": null,
      "SubscriberPackageVersionId": null,
      "Tag": null,
      "Branch": null,
      "Error": [],
      "CreatedDate": "2019-06-01 06:10"
    }
}
```

**Comment by clairebianchi** [comment]
@sfdc-db-gmail can you please take a look at this issue? I think it is a packaging bug.
