### ISSUE TITLE
scratch org failed with error code: VR-0003

### ISSUE THREAD

**Issue by basavaiahravi** [forcedotcom/cli#1022]
Hi,

I am running into this error with new release. I updated SFDX and it is version 52.
I signed up with Pre rlease org (GS0)

$ sfdx force:org:create -f config/project-scratch-def.json --durationdays 30 -a PreviewOrg -v DevHub release=Preview

WARNING: apiVersion configuration overridden at "52.0"

ERROR running force:org:create:  The request to create a scratch org failed with error code: VR-0003.

### Steps To Reproduce:

1. Sign up with Pre release org (GS0)
2. Enable DevHub
3. Create VS Code Project
4. Create scratch

### Expected result

Scratch org should create with latest release

### Actual result

ERROR running force:org:create:  The request to create a scratch org failed with error code: VR-0003.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.102.0 darwin-x64 node-v16.1.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
auth 1.5.4 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.12.0 (core)
├─ data 0.4.6 (core)
├─ custom-metadata 1.0.12 (core)
├─ org 1.6.5 (core)
├─ apex 0.2.0 (core)
├─ user 1.2.10 (core)
├─ schema 1.0.6 (core)
├─ limits 1.2.0 (core)
├─ salesforce-alm 51.6.23 (core)
├─ templates 51.3.1 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.102.0 (core)
telemetry 1.2.1 (core)

**OS and version**: Mac OS Big Sur - 11.3.1 (20E241)

**Comment by mshanemc** [comment]
see https://github.com/forcedotcom/cli/issues/272

The best mental model for this is to think about Preview _**from the hub's perspective**_.  You might think of summer21 as the preview because that's how your production org would see it, but from a gs0 hub, it's already on summer21 so preview means Winter22 which doesn't exist yet.  

For gs0 orgs, it's never preview since they get it on day 0.
