### ISSUE TITLE
sfdx force:source:deploy returns cursor inside the output

### ISSUE THREAD

**Issue by PalGenadich** [forcedotcom/cli#1023]
### Summary

When executing sfdx force:source:deploy in terminal (tested PowerShell, Git Bash and cmd) the command executes successfully but returns the cursor inside the output.
See the screenshot attached. The cursor was returned at the undelined point.
![Screenshot](https://i.imgur.com/CA3kuww.png)

### Steps To Reproduce:
1.  Execute sfdx force:source:deploy command that produces a sizeable output, e.g. with running all tests.
1.  Observe cursor position after the command execution. You may press Enter a couple of times to easily spot the cursor position inside the output.

### Expected result

Cursor is returned after the end of output.

### Actual result

Cursor is returned inside the output.

### Additional information

**SFDX CLI Version**: sfdx-cli/7.94.3-a4e7c7955b win32-x64 node-v14.15.4

**SFDX plugin Version**

> @oclif/plugin-autocomplete 0.3.0 (core)
> @oclif/plugin-commands 1.3.0 (core)
> @oclif/plugin-not-found 1.2.4 (core)
> @oclif/plugin-plugins 1.10.0 (core)
> @oclif/plugin-warn-if-update-available 1.7.0 (core)
> @oclif/plugin-which 1.0.3 (core)
> @salesforce/lwc-dev-server 2.10.0
> ├─ @oclif/plugin-update 1.3.10
> └─ @oclif/plugin-help 2.2.3
> @salesforce/sfdx-trust 3.6.0 (core)
> alias 1.1.8 (core)
> auth 1.5.1 (core)
> config 1.2.7 (core)
> generator 1.1.5 (core)
> salesforcedx 51.14.0 (latest-rc)
> ├─ data 0.4.8
> ├─ limits 1.2.1
> ├─ apex 0.2.0
> ├─ custom-metadata 1.0.12
> ├─ templates 51.4.0
> ├─ org 1.6.6
> ├─ schema 1.0.7
> ├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
> ├─ user 1.3.0
> └─ salesforce-alm 51.6.26
> sfdx-cli 7.94.3 (core)
> telemetry 1.1.1 (core)

**OS and version**: Windows 10 Enterprise 64 bit 20H2 19042.928

**Terminals tested**: PowerShell, Git Bash, cmd

**Comment by mshanemc** [comment]
wow.  Few questions:
do you see this on any deploy, or is it something specific to the territory example you gave?
Are the things it's displaying as a cursor consistent? (is that an apex test there? is it always an apex test?)
Does not running the tests change the error?

**Comment by PalGenadich** [comment]
Ran a couple more tests.
I could notice the issue in these cases:

- when running any deployment validation (--checkonly) with or without tests. Here's an example deploying a single apex class. Notice that last output line is overwritten and should say something like "Successfully validated the deployment". And cursor is expected on the following line.
![image](https://user-images.githubusercontent.com/1927405/119362916-d0b23180-bcdf-11eb-8146-aed0c9ec8857.png)

- when running a deployment with tests. It seems that **Deployed Source** output section overwrites the previous **Test Success** output section. This is again because of the wrong cursor position when outputting the **Deployed Source** section, so final view depends on the content of the deployment/number of tests but the issue happens every time. Example below. 
![image](https://user-images.githubusercontent.com/1927405/119364238-47036380-bce1-11eb-9622-7cee8552449f.png)

Let me know if I can help with more info.

**Comment by mshanemc** [comment]
If you're still up for helping debug, can you see if the problem happens in the newer windows terminal / powershell7?
https://github.com/microsoft/terminal

Our one windows user on the CLI team uses that.

**Comment by PalGenadich** [comment]
Sure, happy to help.
I installed this https://github.com/PowerShell/PowerShell/releases/tag/v7.1.3
And this https://www.microsoft.com/en-sg/p/windows-terminal/9n0dx20hk701?rtc=1&activetab=pivot:overviewtab
Both are PowerShell 7.1.3.
Result is exactly the same as before.
Here's a gif
![Animation](https://user-images.githubusercontent.com/1927405/119515725-b1330b80-bda8-11eb-9b3c-450f28e8235d.gif)

**Comment by shetzel** [comment]
fwiw, I don't think this is OS specific.  I've seen this in some cases when canceling in progress deploys on Mac.  I don't see this in the new source plugin we're working on which will hopefully be ready for public testing very soon (end of the month or early June).

**Comment by mshanemc** [comment]
gonna close since this is now in the new plugin.  Please open a new issue if you still see it
