### ISSUE TITLE
Breaking Change: All usernames from auth saved in lower case. 

### ISSUE THREAD

**Issue by jjulicher** [forcedotcom/cli#1027]
A recent change was introduced that now saves all user names in lower case. 

In CI/CD pipelines it is common to specify user names used either in any caps. But also there are plugins that use this functionality. 

We currently use the sfpowerkit plugin to authorise using username/password in our development workflows so that we don't have to do any setup in our CI/CD pipelines to authorise to new Sandboxes. It passes the logins back to SFDX CLI which then saves the user name. Previously it would save the file using whatever CAPS you supplied in the username. Now it saves it all in lower case.  It also allowed you to set an alias, however the alias does not get saved in lowercase. 

So there are now 2 scenarios that are broken. 

1. You can now set an alias with CAPS in it. e.g. mylogin=someone@username.com.SANDBOX which is now not a valid combination.
2. when specifying the username it will not work if you then specify someone@username.com.SANDBOX . 

Granted, when using the alias in the SFDX command it works as expected

The code for authorisation in SFPOWERKIT is here: https://github.com/Accenture/sfpowerkit/blob/main/src/commands/sfpowerkit/auth/login.ts

At the bottom it has:

``` javascript
if (this.flags.alias) {      
  const aliases = await Aliases.create(        
        ConfigGroup.getOptions("orgs", "alias.json")      
  );
  aliases.set(this.flags.alias, this.flags.username);      
  await aliases.write();
}


```

I would expect (as the API to create AuthInfo does) for the Aliases API to convert everything to lower case as usernames which include upper case are no longer supported.

**Comment by mshanemc** [comment]
@jjulicher When did you see this starting?  Last few days?

**Comment by jjulicher** [comment]
Yeah Monday or Tuesday.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9332288](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000N3VMYA0/view)
