### ISSUE TITLE
ERROR running force:user:create:  Error authenticating with JWT config due to: user hasn't approved this consumer

### ISSUE THREAD

**Issue by stoevie** [forcedotcom/cli#1028]
### Summary

Within our CI/CD pipeline we get the error 'ERROR running force:user:create:  Error authenticating with JWT config due to: user hasn't approved this consumer'

### Steps To Reproduce:

1.  login to devhub using JWT:
     sfdx auth:jwt:grant --clientid $(Key) --jwtkeyfile "$KEYFILE" --username $(dev_hub_username) --setdefaultdevhubusername --setalias $(dev_hub_alias)    
     
2.  authorize a scratch org using JWT:
     sfdx auth:jwt:grant --clientid "$KEY" --jwtkeyfile "$KEYFILE" --username "$USERNAME" --instanceurl https://test.salesforce.com --setalias "$ORGNAME"

3.  create test user with given profile:
     sfdx force:user:create --setalias testadmin@test.com.tst --definitionfile config/users/user-test.json -u ${ORGNAME}

user-test.json:
{
    "Email": "tester@test.com",
    "Alias": "tadmin",
    "TimeZoneSidKey": "Europe/Amsterdam",
    "LocaleSidKey": "en_US",
    "EmailEncodingKey": "UTF-8",
    "LanguageLocaleKey": "en_US",
    "FirstName": "System Administrator",
    "LastName": "Test",
    "CommunityNickname": "SystemAdministrator User Test",
    "profileName": "System Administrator",
    "generatePassword": true,
    "UserPermissionsSFContentUser": true
}

### Expected result

user created and has the correct profile

### Actual result

- Metadata correct deployed
- creation of the users failed with error: ERROR running force:user:create:  Error authenticating with JWT config due to: user hasn't approved this consumer

### Additional information

In the scenario with the error we first create a couple of scratch org during the night. Later that day we start a CI CD pipeline and go through the steps as described in the problem. When we create a scratch org in the same script as where we create the user no error appears.

Steps:
1.  login to devhub using JWT:
     sfdx auth:jwt:grant --clientid $(Key) --jwtkeyfile "$KEYFILE" --username $(dev_hub_username) --setdefaultdevhubusername --setalias $(dev_hub_alias) 
     
2.  create an org:
     sfdx force:org:create -f config/project-scratch-def-ent.json -a "${ORGNAME}" --durationdays 1 --setdefaultusername

3.  create test user with given profile:
     sfdx force:user:create --setalias testadmin@test.com.tst --definitionfile config/users/user-test.json -u ${ORGNAME}

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
7.101.0, 7.102.0, sfdx-cli/7.103.0 linux-x64 node-v12.22.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@provartesting/provardx 0.3.1
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
auth 1.6.0 (core)
config 1.2.8 (core)
generator 1.1.7 (core)
salesforcedx 51.14.0 (core)
├─ data 0.4.8 (core)
├─ apex 0.2.0 (core)
├─ custom-metadata 1.0.12 (core)
├─ limits 1.2.1 (core)
├─ org 1.6.6 (core)
├─ schema 1.0.7 (core)
├─ templates 51.4.0 (core)
├─ user 1.3.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.26 (core)
sfdx-cli 7.103.0 (core)
sfpowerkit 2.9.2
telemetry 1.2.1 (core)

**OS and version**:
Ubuntu-18.04

**Comment by mshanemc** [comment]
> In the scenario with the error we first create the scratch org and in a later session we deploy the config.
> When you create the scratch org in the same session and go through the same steps no error appears.

Given that additional info, can you help revise the repro steps to be more precise?
1. have a devhub auth'd via jwt
2. create a scratch with `force:org:create` _but don't do anything else_?
2. _how long do we wait before moving on to the next step?  Do we need to `auth:logout` from it to reproduce?  If not, how do we get a different "session"?_
4. auth to the scratch org from step 2 using JWT.  _Can you share the exact command/flags you use for this, particularly the instanceurl?_
5. deploy metadata (profiles/objects/permissionsets)
6. attach additional permissionsets to admin
7. create test users with given profile and attach permissionsets

**Comment by stoevie** [comment]
Hi Shane,

I have updated the problem description.
Kr,
Gert

**Comment by stoevie** [comment]
Hi Shane, is there maybe a workaround which I can try?

**Comment by kevanmoothien** [comment]
Hi, 
I am also having same kind of issue. 
I have a script which 
1. generate a scratch org
2. reset the password to have one so that we can login using browser

It is upon doing the reset or simply doing a grant to renew the acces token that this error occurs. What I noticed is that upon doing a grant, the sfdx-cli deletes the file <scratch_org_username>.json and rewrite a new one when successful. But if the error below occurs, it does not recreate the file, hence all my process for the CI fails. 

```
{"name":"sfdx","hostname":"812d2cf8-f622-47ba-a444-aa641c7a1f10","pid":27,"log":"Grant","level":50,"msg":"[\n  'ERROR running auth:jwt:grant: ',\n  \"We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Error authenticating with JWT config due to: user hasn't approved this consumer\"\n]","time":"2021-06-21T14:51:33.616Z","v":0}
```

Has anyone found any workaround yet for this ?

**Comment by kevanmoothien** [comment]
Hello. Any solution for this?

**Comment by iowillhoit** [comment]
Hello, we are cleaning up old issues. I just tried to replicate the steps provided in the description and Kevan's comment from 2021. I am not seeing any issues with either. If you are still seeing this problem with the latest version of the `sf` cli (currently `2.26.10`), please open a new issue with a repository that reproduces the issue. Provide the exact commands with flags to run against the repro. [Dreamhouse](https://github.com/trailheadapps/dreamhouse-lwc/) can be used as a starting point. Thank you.
