### ISSUE TITLE
Add --wait flag to force:package:installed:list command

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#103]
**Is your feature request related to a problem? Please describe.**
I have series of CI jobs.  They execute the `force:package:installed:list` command as part of the process.  Periodically, they timeout and the CLI command currently has no way to extend that timeout

**What are you trying to do**
Execute the `force:package:installed:list` command in a manner that will extend timeout 

**Describe the solution you'd like**
I would like a new flag added to the `force:package:installed:list` command called `--wait` and have it operate in a similar manner to the other wait flag for other commands

**Describe alternatives you've considered**
n/a

**Comment by clairebianchi** [comment]
@sfdc-db-gmail can you please take a look at this issue? I think it is a packaging bug.

**Comment by sfdc-db-gmail** [comment]
@ImJohnMDaniel - I will add this to my backlog.
@clairebianchi
