### ISSUE TITLE
Windows terminal moving to background process when authenticating

### ISSUE THREAD

**Issue by adammyhre** [forcedotcom/cli#1033]
### Summary

When authenticating an org from cmd or git bash terminal, the terminal process will move to run in the background as soon as the browser is opened.  The org will successfully authenticate, but the user will not be able to see the success message, nor access the terminal process again.

If the user does not complete the authentication process, the terminal will continue to listen for a response from the background and the user will be unable to authenticate again without terminating the now hidden console.

> Kill the process running on port 1717 or use a custom connected app and update OauthLocalPort in the sfdx-project.json file.

### Steps To Reproduce:

1. Open cmd on a system running Windows 10
2. Authenticate an org using `sfdx auth:web:login` or `sfdx force:auth:web:login`

### Expected result

Terminal window should remain in the foreground and output a success (or fail) message such as "Successfully authorized <user> with org ID 123456789"

### Actual result

Console process moves to become a Background Process as soon as the browser is launched.  It cannot be moved to the front again.  It cannot be closed other than terminating the process using a system tool such as Task Manager or Process Explorer.  If the authorization was not completed, it continues to listen for a response and future authorizations on that port will be unsuccessful.

### Additional Information

We have experienced this bug since upgrading to v7.103 and also in v7.104.

The bug affects all users when authorizing using Windows cmd.  It has also been reported for some Windows users in git bash.

**Comment by adammyhre** [comment]
Further testing has shown that we can replicate this bug in v7.102

Downgrading to v7.101.0 does not have the bug.  We have isolated the issue to specifically be related to the package dependency change between these 2 versions for the open module which changed from v7.4.2 to v8.0.8

Installing to the latest version of the cli but downgrading the open module to v7.4.2 also resolves the issue.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9425348](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000OCRgYAO/view)

**Comment by mshanemc** [comment]
we're on open 8.4.2 these days.  Closing this issue as not reproducible since https://github.com/sindresorhus/open/releases/tag/v8.0.9
