### ISSUE TITLE
`yarn prepack` results in error "Cannot find name 'queueMicrotask'"

### ISSUE THREAD

**Issue by fransflippo** [forcedotcom/cli#1038]
### Summary

Generating a new plugin and running `yarn prepack` results in an error from the Typescript compiler.

### Steps To Reproduce:

1. Generate a new plugin with `sfdx plugins:generate`
1. `cd` into the directory that is created
1. run `yarn prepack`

### Expected result

Compilation is successful.

### Actual result

Error is displayed:

    yarn run v1.22.10
    $ rm -rf lib && tsc -b && oclif-dev manifest && oclif-dev readme
    node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:11:28 - error TS2304: Cannot find name 'queueMicrotask'.
    
    11     queueMicrotask: typeof queueMicrotask;
                                  ~~~~~~~~~~~~~~
    
    
    Found 1 error.
    
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Additional information

**SFDX CLI Version**: sfdx-cli/7.103.0 darwin-x64 node-v14.17.0

**OS and version**: MacOS 10.14.6

**Node version**: v13.2.0

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9368257](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000NkfZYAS/view)

**Comment by peternhale** [comment]
@fransflippo Thank for bring this issue to our attention. We are working on a permanent fix for this issue. In the mean time try this workaround.

```
yarn remove @types/node
yarn add @types/jsforce -D
yarn prepack
```

**Comment by simonwatson** [comment]
Thanks @peternhale, I had the same issue with a newly-generated plugin and your suggested workaround fixed it for me :-)

**Comment by fransflippo** [comment]
Thank you @peternhale , that works!

**Comment by marshallvaughn** [comment]
> @fransflippo Thank for bring this issue to our attention. We are working on a permanent fix for this issue. In the mean time try this workaround.
> 
> ```
> yarn remove @types/node
> yarn add @types/jsforce -D
> yarn prepack
> ```

This worked for me, thanks!

**Comment by gjtorikian** [comment]
This problem still appears. After much finagling, I came across this error: `The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "14.5.0"`.

Judging by that, I upgrade my Node version from 14.5 to 14.13.1, and was able to run `yarn prepack`.
