### ISSUE TITLE
force:source:retrieve is not extracting profiles (sfdx-cli/ version 7.103.0)

### ISSUE THREAD

**Issue by arorard** [forcedotcom/cli#1039]
### Summary

The current CLI (7.103.0) is not retrieving profile. It was working a few weeks ago before I upgraded SLI to the latest version.

### Steps To Reproduce:

Use a custom class, custom field , custom object in the package.xml and use sfdx force:source:retrieve to extract profile from the org.
1) Form a package.xml as 

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>AUtils</members>
		<name>ApexClass</name>
	</types>
	<types>
		<members>contentdoc_ref__c.LeadRefNum_fileupload__c</members>
		<members>contentdoc_ref__c.contentdocumentid__c</members>
		<name>CustomField</name>
	</types>
	<types>	
		<members>contentdoc_ref__c</members>
		<name>CustomObject</name>
	</types>	
	<types>		
		<members>Admin</members>
		<members>Applicant</members>		
		<name>Profile</name>
	</types>	
	<version>51.0</version>
</Package>	`

2) Use SFDX command to extract

sfdx force:source:retrieve -u DEV2 --manifest .\manifest\package.xml

### Expected result

There should be a "profiles" subfolder under force-app/main/default , but it is not created

### Actual result

No profiles subfolder is created.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.103.0 win32-x64 node-v14.17.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) - N/A

**OS and version**: windows10 
[](url)

**Comment by peternhale** [comment]
@arorard I tried to reproduce the error you are seeing, but cannot. I believe I reproduced the metadata properly, pushed it to a scratch org and then in a new sfdx-project (from force:project:create) to ensure the correct empty state. I ran the force:source:retrieve with the package.xml below and the profile metadata was fetched properly.

The names of the custom files are a bit different, but that should not affect the outcome.

I am using sfdx version "sfdx-cli/7.105.0 win32-x64 node-v14.16.0" and running again SO on "Spring '21"

package.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types>
    <name>ApexClass</name>
    <members>AUtils</members>
  </types>
  <types>
    <name>CustomObject</name>
    <members>contentdoc_ref__c</members>
  </types>
  <types>
    <name>CustomField</name>
    <members>contentdoc_ref__c.LeadRefNum_fileupload__c</members>
    <members>contentdoc_ref__c.contentdocumentid__c</members>
  </types>
  <types>
    <name>Profile</name>
    <members>Admin</members>
    <members>Applicant</members>
  </types>
  <version>51.0</version>
</Package>
```

Command results on Windows
```
sfdx force:source:retrieve  -u <redacte> --manifest ..\issue1039\fromsource\package.xml
=== Retrieved Source
FULL NAME                                   TYPE          PROJECT PATH
──────────────────────────────────────────  ────────────  ───────────────────────────────────────────────────────────────────────────────────────────────
contentdoc_ref__c                           CustomObject  force-app\main\default\objects\contentdoc_ref__c\contentdoc_ref__c.object-meta.xml
contentdoc_ref__c.LeadRefNum_fileupload__c  CustomField   force-app\main\default\objects\contentdoc_ref__c\fields\LeadRefNum_fileupload__c.field-meta.xml
contentdoc_ref__c.contentdocumentid__c      CustomField   force-app\main\default\objects\contentdoc_ref__c\fields\contentdocumentid__c.field-meta.xml
AUtils                                      ApexClass     force-app\main\default\classes\AUtils.cls-meta.xml
AUtils                                      ApexClass     force-app\main\default\classes\AUtils.cls
Admin                                       Profile       force-app\main\default\profiles\Admin.profile-meta.xml
Applicant                                   Profile       force-app\main\default\profiles\Applicant.profile-meta.xml
```

**Comment by arorard** [comment]
@peternhale 

Thanks for responding.  

The cli version I have is "sfdx-cli/7.105.0 win32-x64 node-v14.17.0" , and I used package.xml against SP'21 and SU'21 sandboxes, it doesn't retrieve the profiles. The differences are - i) version v14.17.0 ( v14.16.0 at the end)  and ii) sandbox (v/s scratch org)

Not sure if any other factors are causing the issue.

**Comment by peternhale** [comment]
@arorard I don't think the minor version difference in node would cause the missing profiles. Could you try using `sfdx force:mdapi:retrieve`? I just want to see if there is a difference or not in the retrieve MD.

**Comment by arorard** [comment]
@peternhale 
I tried sfdx force:mdapi:retrieve and that extracted profiles.  MD format command works.

**Comment by peternhale** [comment]
@arorard I also tried an scratch org with --nonamespace option and it worked.

I will need to acquire a sandbox org  to give a try. Would you consider using MD commands as a suitable workaround for the time being and then use mdapi:convert and soruce:convert to move between the different formats.

**Comment by arorard** [comment]
@peternhale 

Thanks so much for looking into it.

I can use mdapi as workaround. 
I reinstalled CLI also but it didn't make any difference.

Let me know if you find the root cause.

**Comment by arorard** [comment]
@peternhale 

When I used --loglevel Error and --verbose, it is showing the following error message -

ERROR running force:source:retrieve:  The specified metadata type is unsupported: [C]

But package.xml does not have any type called "C".

**Comment by WillieRuemmele** [comment]
Hi @arorard have you checked the `.forceignore` file to verify that it's not accidentally being ignored?

We're about to announce a new beta plugin for some of the 'source' commands, including deploy.

you can run `sfdx plugins:install @salesforce/plugin-source` to get the beta version, and `sfdx plugins:uninstall @salesforce/plugin-source` to remove it. If you do that let me know how it goes 👍

**Comment by WillieRuemmele** [comment]
Check out the beta [source](https://github.com/forcedotcom/cli/issues/1057) commands
