### ISSUE TITLE
Add "0Ho" package id to the force:package:installed:list command

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#104]
**Is your feature request related to a problem? Please describe.**
Most, if not all, of package related commands show packages as the "0Ho" second generation package id.  Based on comment from [Kevin Cripps of Salesforce, the "0Ho" id is the package id that is scoped to the DevHub](https://success.salesforce.com/0D53A00004Osn3t).  Some packages are third-party in nature and would not have an "0Ho" id, but it would be helpful when processing CI related use cases to see the "0Ho" id in addition to the "033" package id.  This will allow us to better reconcile when the package version may have branch attributes and reconcile if a package dependency is "non-pinned".

**What are you trying to do**
I am trying to reconcile the output of `force:package:installed:list` command to the output of the `force:package:version:list` command.  The latter only deals with "0Ho" ids while the former deals with "033" record ids

**Describe the solution you'd like**
Change the `force:package:installed:list` JSON output to add an additional JSON attribute to show the "0Ho" record id ....when it is available. 

**Describe alternatives you've considered**
n/a

**Comment by clairebianchi** [comment]
@sfdc-db-gmail can you please take a look at this issue? I think it is a packaging bug.

**Comment by sfdc-db-gmail** [comment]
@ImJohnMDaniel - I have added this to the product backlog.
@clairebianchi

**Comment by PadhmaPriya** [comment]
Is this bug fixed? Can I able to get the 0Ho id? If not, Can you please let me know how I can get the 0Ho id? I'm trying to update the package version which has all the necessary details in the config json. However, when I try to create a package version, it reports as: The provided package ID '0HoXXX' is invalid. Am I missing anything? Below is my command:

sfdx force:package:version:create --package "<packageName>" -a Test-0.5 -n 0.1.0.0 -d force-app 
--definitionfile config/project-scratch-def.json --installationkey test1234 --wait 20

Thanks in advance!

**Comment by sylvain-priser** [comment]
> Is this bug fixed? Can I able to get the 0Ho id? If not, Can you please let me know how I can get the 0Ho id? I'm trying to update the package version which has all the necessary details in the config json. However, when I try to create a package version, it reports as: The provided package ID '0HoXXX' is invalid. Am I missing anything? Below is my command:
> 
> sfdx force📦version:create --package "" -a Test-0.5 -n 0.1.0.0 -d force-app
> --definitionfile config/project-scratch-def.json --installationkey test1234 --wait 20
> 
> Thanks in advance!

Hi PadhmaPriya, did you find out how to get this 0ho Id with one of the sfdx force:package command ? I'm stuck at the same point as you ..

**Comment by mobilizer** [comment]
Since this feature request seems to be still open: 

Has anybody an idea where to find the "0Ho"-ID of a managed package? 

Especially I am looking for the CPQ 0Ho Id (033A0000000PgEfIAK  / 04t4N000000GkMQQA0).
