### ISSUE TITLE
Unexpected file error when attempting deploy to a sandbox

### ISSUE THREAD

**Issue by pjain4161** [forcedotcom/cli#1040]
I am trying  to deploy code to sandbox which is where I am encountering this error. Can you please help? 
<img width="1434" alt="Screen Shot 2021-06-07 at 5 05 35 PM" src="https://user-images.githubusercontent.com/13646730/121088337-96529500-c7b3-11eb-8b11-22590e70e504.png">

**Comment by peternhale** [comment]
@pjain4161 Would you post the contents of your sfdx-project.json file please?

**Comment by peternhale** [comment]
@pjain4161 I believe the problem with your example is the value provide for sourcepath. A value of "./" tells the command that everything in that path is valid source that can be deployed. Please try with "-p ./force-app", which is the root directory for source in your project.
