### ISSUE TITLE
Scratch org: Missing template for edition "Developer" ?

### ISSUE THREAD

**Issue by nvuillam** [forcedotcom/cli#1041]
**Edit: This is a known issue.  Please follow the status there:  https://trailblazer.salesforce.com/issues_view?title=scratch-org-creation-getting-failed-with-an-error-error-running-force-org-create-we-couldn-t-find-a-template-with-the-id-specified-in-the-scratch&Id=a1p4V000001aEAX**

original issue report below the line
---

### Summary

Everything was working fine, we didn't change our project-scratch-def.json or sfdx-cli version, and now we are unable to create a new scratch org

Error processing command
{"status": 1,"name": "RemoteOrgSignupFailed","message": "We couldn't find a template with the ID specified in the scratch org definition. If you’re sure the ID is correct, contact Salesforce Support."

### Steps To Reproduce:

Create a scratch org with the following project-scratch-def.json

```shell
sfdx force:org:create --setdefaultusername --definitionfile ./config/project-scratch-def.json --setalias SampleAlias --targetdevhubusername DevHub_Sample -d 30 --json
```

```json
{
  "orgName": "Demo company",
  "edition": "Developer",
  "features": [
    "ContactsToMultipleAccounts",
    "DeferSharingCalc",
    "DevelopmentWave",
    "EnableSetPasswordInApi",
    "LiveAgent",
    "SalesUser",
    "SocialCustomerService",
    "WavePlatform",
    "WorkThanksPref"
  ],
  "settings": {
    "accountSettings": {
      "enableAccountTeams": true
    },
    "chatterSettings": {
      "allowRecordsInChatterGroup": true,
      "enableChatter": true
    },
    "enhancedNotesSettings": {
      "enableEnhancedNotes": true
    },
    "languageSettings": {
      "enableTranslationWorkbench":  true,
      "enableEndUserLanguages": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    },
    "nameSettings": {
      "enableMiddleName": true,
      "enableNameSuffix": true
    },
    "quoteSettings": {
      "enableQuote": true
    },
    "workDotComSettings": {
      "enableWorkThanksPref": true,
      "enableProfileSkills": true
   }
  },
  "objectSettings": {
    "opportunity": {
      "sharingModel": "private"
    },
    "account": {
      "sharingModel": "private"
    },
    "contact": {
      "sharingModel": "private"
    },
    "case": {
      "sharingModel": "private"
    }
  }
}

```

### Expected result

Scratch org created

### Actual result

Scratch org not created

### Additional information

![image](https://user-images.githubusercontent.com/17500430/121335028-82757300-c91a-11eb-98c8-74de64cdde30.png)

**SFDX CLI Version**: 7.104.0

**OS and version**: Same on Windows locally or in CI using alpine linux

**Comment by konradkaras** [comment]
I'm facing the same issue.
This issue is somehow related to the Summer21 release update.
Yesterday we were able to create scratch orgs with option release=Preview (our dev hub is still on Spring21) but today the error mentioned by op occurs. 
As a workaround I had requested for a pre-release developer org. I enabled Dev Hub feature and tried to create a new scratch based on that pre-release org - resulted with same issue.

**Comment by mshanemc** [comment]
The team that owns org creation has been notified.  I'm going to leave this issue open until it's resolved since this will affect lots of users.

**Comment by nvuillam** [comment]
thanks @mshanemc :)

**Comment by FabienTaillon** [comment]
Same here. I tried with other editions and I'm getting the same error for all of them, so it's not linked to Developer edition only.
Also, using the same command/scratch definition file with another DevHub not yet on Summer '21 does work.

**Comment by mshanemc** [comment]
FYI, there's now a Known Issue for this you can follow: https://trailblazer.salesforce.com/issues_view?title=scratch-org-creation-getting-failed-with-an-error-error-running-force-org-create-we-couldn-t-find-a-template-with-the-id-specified-in-the-scratch&Id=a1p4V000001aEAX

**Comment by nvuillam** [comment]
I tried the workaround `"release": "Preview"` in project-scratch-def and for now it works

**Comment by peternhale** [comment]
This issue has been resolved, closing. Please re-open if this reoccurs.
