### ISSUE TITLE
force:source:deploy -x command deletes all __test__ files from the source repository

### ISSUE THREAD

**Issue by vnehess** [forcedotcom/cli#1044]
### Summary

$ sfdx force:source:deploy
when run with a manifest ( -x ) will delete all of the JEST tests in my source tree.

since upgrading to sfdx-cli/7.105.0, I have discovered that the command 
worked on 7.102

### Steps To Reproduce:
I have a repro using dreamhouse

reference:  salesforce Case 30155862

1. download the dreamhouse repo
2. create a scratch org, set it as the default
3. add the following package.xml file under ./manifest. ( note this is an incomplete package.xml file, but demonstrates the issue)
 
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types>
    <members>GeocodingService</members>
    <name>ApexClass</name>
  </types>
  <types>
      <members>brokerCard</members>
      <members>errorPanel</members>
      <name>LightningComponentBundle</name>
</types>
<version>49.0</version>
</Package>

```

4.  in a source repository which contains LWC tests ( `__test__/**` )  run the command
sdfx force:source:deploy -x manifest/package.xml

### Expected result

source code does deploy

### Actual result

source code begins to deploy after deleting LWC `__test__/**`  files

see : 
![Screen Shot 2021-06-14 at 10 22 54 AM](https://user-images.githubusercontent.com/263249/121933098-7e6e9a00-ccfa-11eb-824e-42d371a2770e.png)

### Additional information

this line of code is actually deleting the source code

![Screen Shot 2021-06-14 at 9 05 18 AM](https://user-images.githubusercontent.com/263249/121925096-68101080-ccf1-11eb-86f3-8f5cfa23857c.png)

the comments indicate it is a temp directory, however, as you can see in the screenshot it is my actual source tree that is unlinked.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.105.0 darwin-x64 node-v15.8.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
auth 1.6.1 (core)
config 1.2.8 (core)
generator 1.1.7 (core)
salesforcedx 51.16.0 (core)
├─ data 0.4.10 (core)
├─ apex 0.2.2 (core)
├─ org 1.6.6 (core)
├─ user 1.3.0 (core)
├─ schema 1.0.7 (core)
├─ limits 1.2.1 (core)
├─ custom-metadata 1.0.12 (core)
├─ templates 51.5.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.26 (core)
sfdx-cli 7.105.0 (core)
telemetry 1.2.1 (core)

**OS and version**:
macos Catalina
10.15.7

**Comment by peternhale** [comment]
@vnehess I just the repro but cannot reproduce the removal of the tests. Not sure what might be going on here. Any additional details that you might be able to provide?

**Comment by isaackehle** [comment]
We are having the same issue.  It took us a few days to figure out that this was what was happening in our Jenkins builds.  I saw it once locally, and another team member had the problem repeating.  I'll see if I can find a situation/configure that fully replicates the issue.

**Comment by WillieRuemmele** [comment]
Check out the beta [source](https://github.com/forcedotcom/cli/issues/1057) commands!

**Comment by GH4Arlene** [comment]
Am having a similar problem ( __tests__ folder deleted ) when using sfdx force:source:deploy --sourcepath _filename_.  The problem occurs consistently on a machine with CLI version 7.105 and never on a machine with 7.91.  Can provide additional version information if that would be helpful.

**Comment by WillieRuemmele** [comment]
Hi @GH4Arlene checkout my announcement above for the beta `source` commands, check them out. They should fix this issue 🤞 👍

**Comment by GH4Arlene** [comment]
Thank you @WillieRuemmele!  The `__test__` folders are no longer deleting.
