### ISSUE TITLE
Support for ARM M1 Mac within SFDX-CLI

### ISSUE THREAD

**Issue by thomasheuberger** [forcedotcom/cli#1045]
I just installed SFDX-CLI (latest version from https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx.pkg, ) on my M1 MacBook Pro

`sfdx-cli/7.105.0 darwin-x64 node-v14.9.0`

and get

`~ % sfdx -v
/usr/local/bin/sfdx: line 44: /usr/local/lib/sfdx/bin/node: Bad CPU type in executable`

Is there a native M1 version of SFDX-CLI without installing rosetta? If so, where's the download?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9474596](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Ol7AYAS/view)

**Comment by peternhale** [comment]
@thomasheuberger we are aware of the need to support Apple M1. Nodejs has yet to release a version that supports M1 w/o Rosetta. I located this [issue](https://github.com/nodejs/build/issues/2474) that seems to be tracking progress for this effort.

**Comment by touzoku** [comment]
Nodejs supports M1 chips as of version 16. SFDX comes with a version 12 bundled. The fix is simple: just delete the outdated nodejs version and link a recent one as shown below.

Salesforce engineers do not have M1 macs anyway, so this fix might take forever.

```
rm -f /usr/local/lib/sfdx/bin/node
link -s /opt/homebrew/bin/node /usr/local/lib/sfdx/bin/node
```

**Comment by RodEsp** [comment]
We actually do have support for M1 but only as tarballs for now.
You can download the latest version at https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-darwin-arm64.tar.gz and install it using the installation instructions for tarballs found [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux).
