### ISSUE TITLE
Salesforce CLI Experiences - Request for feedback

### ISSUE THREAD

**Issue by preddivari** [forcedotcom/cli#1048]
Hello Salesforce CLI users,

I am the new product manager on the Platform Developer Tools and Experiences team at Salesforce with a focus on the Salesforce CLI. I am thrilled to virtually meet you all here. 
I would love to learn more about your experiences with the Salesforce CLI. 
If open to it, please feel free to put some time on my calendar. 
I look forward to our conversations!
[Schedule Now](https://calendly.com/preddivari/15min
)

Thanks,
Pooja Reddivari

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9483286](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Ovk1YAC/view)
