### ISSUE TITLE
force:source:deploy fails with RunSpecifiedTests

### ISSUE THREAD

**Issue by kromol** [forcedotcom/cli#1049]
### Summary

Deploy to sandbox fails with `RunSpecifiedTests` even though tests pass and the error message is unclear. Deploying without tests works properly.

### Steps To Reproduce:

Run 
```
sfdx force:source:deploy --targetusername cicd --metadata ApexClass --testlevel RunSpecifiedTests --runtests LuhnAlgorithmTest --verbose
```

### Expected result

Should deploy

### Actual result

Fails with the error: ` Deploy failed`. Complete output:
```
*** Deploying with SOAP ***
Job ID | 0Af0Q00001Ugq0aSAB
SOURCE PROGRESS | ████████████████████████████████████████ | 21/21 Components
=== Test Success [3]
NAME               METHOD
─────────────────  ─────────────────────
LuhnAlgorithmTest  TestInValidFiscalCode
LuhnAlgorithmTest  TestValidFiscalCode
LuhnAlgorithmTest  TestValidVATNumber

=== Apex Code Coverage
NAME           % COVERED  UNCOVERED LINES
─────────────  ─────────  ───────────────
LuhnAlgorithm  100%

Total Test Time:  179.0

FULL NAME  TYPE  PROJECT PATH  PROBLEM  LINE NUMBER  COLUMN NUMBER
─────────  ────  ────────────  ───────  ───────────  ─────────────
                               Unknown
ERROR running force:source:deploy:  Deploy failed.

```
### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**: `sfdx-cli/7.106.3 darwin-x64 node-v12.18.3`

**OS and version**: ` macOS 11.4`

**Comment by aheber** [comment]
@kromol Have you looked inside the org deployments list to see why that deploy failed? In my experience this is often a coverage based failure. I thought there was an open issue that coverage errors are not displayed in the output of that command but I can't find it, maybe I imagined it.

I think if you use the `--json` flag on your command there is a lot more information and it includes the coverage data and associated errors.

**Comment by kromol** [comment]
@aheber you are right, it's because of the coverage, thanks for the hint. It actually makes sense, because I deploy everything and run only specific tests. 

I saw another opened issue to improve error message, so I close this one.

Btw `--json` flag does not give other details except the stack trace.
