### ISSUE TITLE
Filtering Package Version List by Alias failingº

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#105]
### Summary

In Unix systems (I've tried in WSL ubuntu on windows 10 and dockerized ubuntu). When running listing all the available versions of some packages, filtering by a name, in some cases returns no results.

I've tried running this command in windows, with the same devhub, to filter for the same package and I get the desired results, also, in ubuntu filtering by package id, also returns results, and filtering by other alias returns the desired result

Sfdx plugin is in last currently available version: sfdx-cli/7.8.1

### Steps To Reproduce:

1.  In my case, create a package
1.  Create a version
1. Try to filter for that version

### Expected result

Return the correct version

### Actual result

Returns nothing

### Additional information

![sfdx-packageFilter](https://user-images.githubusercontent.com/10410852/58865721-5da8ee00-86b7-11e9-9c50-24da575a3156.gif)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.8.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): 
```
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.16.0 (core)
├─ force-language-services 45.12.0 (core)
└─ salesforce-alm 45.18.0 (core)

sfdx-cli 7.8.1 (core)
```

**OS and version**: windows 10 1809 and Ubuntu

**Comment by clairebianchi** [comment]
@sfdc-db-gmail can you please take a look at this issue? I think it is a packaging bug.
