### ISSUE TITLE
sfdx force:source:retrieve extremely slow

### ISSUE THREAD

**Issue by renanlq** [forcedotcom/cli#1050]
### Summary

Since last Summer '21 Release, we noticed that some features are being really slow.

### Steps To Reproduce:

**Repository to reproduce**: private company repository.
**Steps**: 
1. go to default path 
`
cd \force-app\main\default
`
2. run command retrieves from org
`
sfdx force:source:retrieve -p .\applications,.\aura,.\classes,.\experiences,.\flexipages,.\layouts,.\networks,.\networkBranding,.\objects,.\pages,.\profiles,.\roles,.\settings,.\sites,.\siteDotComSites,.\sharingRules,.\tabs --loglevel fatal
`
3. waiting for the result

### Expected result

Usually, this command runs about 3-5 minutes at most.

### Actual result

The command is taking more than an hour to achieve the result.

### Additional information

**Salesforce Instance**: NA82
**Environment**: Production
**SFDX CLI Version**: sfdx-cli/7.105.0 win32-x64 node-v14.17.0
**SFDX plugin Version**: 
`
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
auth 1.6.1 (core)
config 1.2.8 (core)
generator 1.1.7 (core)
salesforcedx 51.16.0 (core)
├─ data 0.4.10 (core)
├─ custom-metadata 1.0.12 (core)
├─ apex 0.2.2 (core)
├─ limits 1.2.1 (core)
├─ user 1.3.0 (core)
├─ org 1.6.6 (core)
├─ schema 1.0.7 (core)
├─ templates 51.5.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.26 (core)
sfdx-cli 7.105.0 (core)
telemetry 1.2.1 (core)
`
**OS and version**:  Windows 10 Enterprise x64

**Comment by WillieRuemmele** [comment]
Hi @renanlq are you still seeing this issue?

**Comment by renanlq** [comment]
Is taking more than usual, but today we could do it, but not 100%, see on the attached image:
![image](https://user-images.githubusercontent.com/15347353/122837733-fcb6d780-d2ca-11eb-9aea-0c93f411a3d6.png)

**Comment by WillieRuemmele** [comment]
hmmm interesting. We haven't changed those commands for sometime, we've been working on rewriting them to use a faster library.

you can checkout the soon-to-be-announced beta source plugin by installing it with `sfdx plugins:install @salesforce/plugin-source` , and uninstalling it with `sfdx plugins:uninstall @salesforce/plugin-source` that should make things a little faster. Let me know if you try the new plugin 👍

**Comment by WillieRuemmele** [comment]
Hi @renanlq circling back - is it faster now? how's the new plugin?

**Comment by renanlq** [comment]
Hi @WillieRuemmele, 

Since our last messages, our org seems to be more stable ... so that we were able to run the source retrieve command without any problem. So that think that we would close this issue.

Additionally, thanks for the plugin, we are testing it now.
