### ISSUE TITLE
Better plugin documentation on using metadata types / Introducing a metadata types package

### ISSUE THREAD

**Issue by fransflippo** [forcedotcom/cli#1051]
**Is your feature request related to a problem? Please describe.**

I want to create a plugin that creates a connected app. By looking at https://forcedotcom.github.io/sfdx-core/index.html I concluded that I could use `connection.metadata.create()`. However, the second argument to `create` is a `MetadataInfo` and I cannot find a `ConnectedApp` sub-interface of it anywhere.

Are plugin developers expected to create their own types? It seems like this would be part of the standard types available to plugin developers since metadata types are a limited set (not regarding custom metadata here).

The documentation on https://forcedotcom.github.io/sfdx-core/index.html is quite sparse, e.g. most functions have no documentation as to what they do exactly and how they are to be used.

**What are you trying to do**

Build a plugin that creates a `ConnectedApp`.

**Describe the solution you'd like**

A reusable types package that contains types for all metadata types, basically mirroring the SOAP API's `http://soap.sforce.com/2006/04/metadata` namespace.

If this is unfeasible for whatever reason, introduce better documentation on how plugin developers are expected to work with metadata in their plugins.

**Describe alternatives you've considered**

Creating my own `ConnectedApp` `class` in my plugin code.
Not creating a plugin at all but rather a shell script.

**Additional context**

I think the above summarizes it.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9487581](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000P0y8YAC/view)

**Comment by WillieRuemmele** [comment]
hey @fransflippo sorry for the delayed response.

that code is just wrapping around `jsforce`, you can find types for `ConnectedApps` on the `2.0` branch [here](https://github.com/jsforce/jsforce/blob/2.0/src/api/metadata/schema.ts#L1804) hopefully that'll get you what you're looking for
