### ISSUE TITLE
SFDX Plugin: SaveResult type lacks 'errors' property

### ISSUE THREAD

**Issue by fransflippo** [forcedotcom/cli#1052]
### Summary

The Metadata `SaveResult` type is defined in `metadata.ts` as:

    interface SaveResult {
        success: boolean;
        fullName: string;
    }

However, in the SOAP API WSDL, the type has a third field `errors` which is an array of `Error`. There is now no typesafe way of reading the errors from `Metadata.create` call.

### Steps To Reproduce:

Do any `Metadata.create` call that fails, e.g. (in a plugin) :
    
    const saveResult: SaveResult|SaveResult[] = await conn.metadata.create('ConnectedApp', { fullName: 'Invalid Name' });
    if (!Array.isArray(saveResult)) {
      console.log(saveResult);
    }

This will output:

    {
      errors: {
        fields: 'DeveloperName',
        message: 'Name: The Connected Application API Name can only contain underscores and alphanumeric characters. It must be unique, begin with a letter, not include spaces, not end with an underscore, and not contain two consecutive underscores.',
        statusCode: 'FIELD_INTEGRITY_EXCEPTION'
      },
      fullName: 'Invalid Name',
      success: false
    }

If I add 

    console.log(saveResult.errors);

the code doesn't compile and the compilers gives an error:

    error TS2339: Property 'errors' does not exist on type 'SaveResult'
    
         console.log(saveResult.errors);

### Expected result

I can use `saveResult.errors` to inspect the errors returned from the create call *or* the `create` call throws an exception that I can catch and that contains the errors.

### Actual result

The `create` call doesn't throw an exception and the `SaveResult` type only gives me `fullName` and `success`.

### Additional information

**SFDX CLI Version**: sfdx-cli/7.103.0 darwin-x64 node-v14.17.0

**SFDX plugin Version**: `"@salesforce/core": "^2.1.6"`, `"@types/jsforce": "^1.9.29"`

**OS and version**: N/A

**Comment by WillieRuemmele** [comment]
do you have a link to the `metadata.ts` file? Or know which repository that the type is coming from? `@types/jsforce` and `@salesforce/core` are both OSS repositories that are accepting PRs if you want to contribute and make a change!

**Comment by fransflippo** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jsforce/api/metadata.d.ts

I'll submit a PR to DefinitelyTyped.

Thanks,
Frans

**Comment by fransflippo** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53971

**Comment by WillieRuemmele** [comment]
Looks merged/published in @types, nice job! closing this issue
