### ISSUE TITLE
Broken link to logger documentation

### ISSUE THREAD

**Issue by fransflippo** [forcedotcom/cli#1053]
https://forcedotcom.github.io/sfdx-core/classes/logger.html links to https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_log_messages.htm, which just shows "Sorry, the document you are looking for doesn't exist or could not be retrieved.".

More generally, the documentation seems lacking about how a plugin should do (debug) logging and how this interacts with the `--loglevel` parameter specified on the CLI command line would be useful. It's not clear from reading the documentation how I can write debug statements that would output to the console when `--loglevel=debug` (or `trace`) is used, but not when a higher log level is specified.

Is the Bunyan logging affected by `--loglevel` at all? 
What does `this.debug` (or `this.ui.debug`) do in a plugin?

**Comment by WillieRuemmele** [comment]
Hi @fransflippo the first link is working for me, the second link is broken. [Here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_log_messages.htm)'s an updated link to the second one

You can specify the log level in either the `Logger`'s constructor, or with the [setLevel](https://forcedotcom.github.io/sfdx-core/classes/logger.html#setlevel) method. It takes an enumerated value, you can learn more from these [docs](https://forcedotcom.github.io/sfdx-core/enums/loggerlevel.html)

>More generally, the documentation seems lacking about how a plugin should do (debug) logging

When we're developing new plugins, we usually add any debug output around any complicated processes or places where things might go wrong. It's helpful when debugging to see when values are changing, what's changing them.

> What does this.debug (or this.ui.debug) do in a plugin?

If you have a specific example I'm more than happy to explain. I'm assuming it's just accessing a `Logger` in a base class, or some other inherited property.

**Comment by fransflippo** [comment]
Hi @WillieRuemmele,

I gave the first link because it's the page that links to the second link, which is broken. I think it would be helpful for people visiting https://forcedotcom.github.io/sfdx-core/classes/logger.html  if it was updated to link correctly to https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_log_messages.htm instead of to the broken link https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_log_messages.htm.

Happy to update it with a PR but I'm not sure where to do that.


Perhaps my second question wasn't clear: the base `SfdxCommand` gives you a `--loglevel` switch, but no matter what value I pass to it -- `DEBUG` or `TRACE` -- any output I produce with`this.debug` is never shown.

Maybe my assumption is wrong, but I would assume there would be some standard way I could get a logger to which the log level supplied by `--loglevel` has already been applied such that messages logged at a lower level than the level requested by `--loglevel` are not printed out.

What I tried:

1. Generate a new plugin
2. Change `requiresUsername` to `false`
3. Replace the `run` method body with:
```
      this.debug('DEBUG');
      this.log('LOG');
      this.ux.warn('WARN');
      this.ux.error('ERROR');
      this.ux.log('LOG');
      return null;
```
4. Run `yarn prepack`
5. (Per the workaround suggested on https://github.com/forcedotcom/cli/issues/1038 run `yarn remove @types/node
&& yarn add @types/jsforce -D && yarn prepack`
6. Run the plugin with different values for `--loglevel` e.g. `bin/run hello:org --loglevel=TRACE` or `bin/run hello:org --loglevel=ERROR`

No matter what value I supply for `--loglevel`, I always get the following output:

    LOG
    WARNING: WARN
    ERROR
    LOG

What's the point of having a `--loglevel` switch when it doesn't do anything?

How can I add trace or debug statements to my code that are only printed when the loglevel specified with the `--loglevel` switch is `TRACE` or `DEBUG`?

Thanks,
Frans

**Comment by WillieRuemmele** [comment]
I've already created a PR https://github.com/forcedotcom/sfdx-core/pull/425 fixing the broken URL in the docs. 

ahhh, I understand your question and I agree it's a little confusing. The `--loglevel` flag only changes the output written to the log file (`~/.sfdx/sfdx.log`), not to stdout. 

If you're linking this plugin to the sfdx cli, you can use the `--dev-debug` flag which enables ALL levels of logging and prints it to stdout
