### ISSUE TITLE
Salesforce CLI and v52 compatibility

### ISSUE THREAD

**Issue by firatesmer** [forcedotcom/cli#1054]
### Summary
Salesforce CLI can't deploy v52 (latest version) related items to org when you right click and select deploy on VS Code. I tried to create package but the version of the package was 51 but the version in package.xml was 52.0. I did try "SFDX_API_VERSION=52.0" as well but no luck.

### Steps To Reproduce:
1. Update package.xml version to 52
2. Right click and select "SFDX: Deploy Source in Manifest ro Org"
3. Doesn't work.

Salesforce CLI version: sfdx-cli/7.105.0 win32-x64 node-v14.17.0
OS version: Windows 10 21H1 (19043.1055)

**Comment by WillieRuemmele** [comment]
Hi @firatesmer if you run the command via the CLI directly does it succeed? Or is this only an issue when using VSCode?

**Comment by WillieRuemmele** [comment]
Hey @firatesmer have you had a chance to try it out with the CLI directly? you can also try the new [beta source plugin](https://github.com/forcedotcom/cli/issues/1057)

**Comment by firatesmer** [comment]
Hey @WillieRuemmele,
Sorry for delay. 

Yes, I've tried with CLI and the result is still version v51 even command prints out 
`WARNING: apiVersion configuration overridden at 52.0`

**Comment by WillieRuemmele** [comment]
Hi @firatesmer and what if you run `sfdx config:list` or get a list of environment variables with `echo %PATH%` (on windows) and look for `SFDX_API_VERSION` being set. If any of those are set it will override. Let me know how it goes 👍

**Comment by firatesmer** [comment]
Hi @WillieRuemmele,

`sfdx config:list` =>

WARNING: apiVersion configuration overridden at "52.0"

| Name      | Value   | Location |
| ---------- | ------- | --------- |
| apiVersion     | 52.0  | Global  |

But still prepares the package with v51.

**Comment by rajesh-kemisetti** [comment]
I am having exactly this same issue. For me the version during deployment is always 50 no matter what I do. I even uninstalled CLI and re-installed to see if there would be any impact and no luck. I have even tried to set 52 version globally but except for this WARNING: apiVersion configuration overridden at 52.0 nothing has changed. 

I am now on sfdx-cli/7.109.0-fc6b854

**Comment by mshanemc** [comment]
are you still seeing version issues with more recent CLIs?  Anyone else been able to reproduce this?

FWIW, more recent deploy commands will tell you what version they're using during the deploy or beta:push

**Comment by firatesmer** [comment]
Hey @mshanemc,

I've just updated the CLI and it works as expected now, no more error.

CLI Version : sfdx-cli/7.130.1 win32-x64 node-v16.13.1
