### ISSUE TITLE
Einstein-" WaveComponent" is not supporting CLI source command

### ISSUE THREAD

**Issue by amethkm** [forcedotcom/cli#1056]
Hello, Team!

Could you please let us know when the CLI source command will be supported by Einstein- "WaveComponent"?
We hear that the salesforce team is already working on CLI command enhancements ( SFDX CLI registry update) to support source command for waveComponents . Is there a time frame we can expect?

.Regards,
Anagha

**Comment by WillieRuemmele** [comment]
Check out the beta [source](https://github.com/forcedotcom/cli/issues/1057) command announcement with expanded metadata type support

**Comment by WillieRuemmele** [comment]
Hi @amethkm have you had a chance to checkout the beta plugin?
