### ISSUE TITLE
Getting Error "Unexpected file found in package directory "blacklistedConsumers"

### ISSUE THREAD

**Issue by asagarwal** [forcedotcom/cli#1059]
Hi, I am trying to deploy the following in package.xml. This is just a simple Apex Class  

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>AA_SampleClass</members>
        <name>ApexClass</name>
    </types>
    <version>52.0</version>
</Package>`

 But when trying to deploy it through the following command, I am getting the error. The command is  
 
 `sfdx force:source:deploy -x manifest/package.xml`

 And the error I am getting is  

`ERROR running force:source:deploy: Unexpected file found in package directory: c:\salesforce\force-app\main\default\blacklistedConsumers\BlacklistedConsumer155969236210464.blacklistedConsumer-meta.xml
`

The thing is I am not even deploying what it is complaining about. And when I try to deploy it manually from VS Code, by right clicking on package.xml and choosing ‘SFDX: Deploy Source in Manifest to Org’, it works fine.  Any pointers will greatly be appreciated

**Comment by WillieRuemmele** [comment]
Hi @asagarwal have you tried the new [source](https://github.com/forcedotcom/cli/issues/1057) beta? Try it with those new commands, it should hopefully fix this bug!

**Comment by asagarwal** [comment]
Hi @WillieRuemmele, I haven't tried the new source beta but was able to find a workaround. Just added the following line in .forceignore file and didn't get the error any more

`force-app/main/default/blacklistedConsumers`

**Comment by WillieRuemmele** [comment]
oh ok great! If you have time, check out the new beta commands. I'll close this issue for now
