### ISSUE TITLE
VS Code reports success on 'SFDX: Set a Default Org' even when the command fails

### ISSUE THREAD

**Issue by allileong** [forcedotcom/cli#106]
### Summary

VS Code reports that `SFDX: Set a Default Org`successfully ran even though the underlying `sfdx force:config:set` command failed and the default org was not able to be set. 

### Steps To Reproduce:

1.  You must have at least two orgs in your environment. For example: `org1` and `org2`
1. Set `org1` to be the default org in your VS Code workspace
1. Find the *.json file that contains the info for `org2` in your ~/.sfdx directory and clobber the `accessCode` and `refreshToken` values.
1. Click on the `org1` button at the bottom of the VS Code window. When the org list dropdown appears, select `org2` to be your new default org. 

### Expected result: 
VS Code notifies the user that an error has occurred during `SFDX: Set a Default Org`
### Actual result:
An error occurs when VS Code runs the `sfdx force:config:set defaultusername=org2` command, but VS Code still outputs a success message for the command. 

### Additional information
![screen shot 2019-02-01 at 3 35 57 pm](https://user-images.githubusercontent.com/1639375/52156112-7b9c0e80-2643-11e9-87f1-80ea0d97867b.png)
**VS Code Version**:
45.1.0

**Comment by dcarroll** [comment]
@allileong  What is the bug here? Is it that the CLI is reporting an error and returning a success code?

**Comment by allileong** [comment]
Hey @dcarroll, without setting up the CLI+vscode to reproduce, that looks to be the case. The CLI failed to set the defaultusername, but returned exit code 0

**Comment by tnoonan-salesforce** [comment]
That actually looks like the encryption key for the auth files changed to me. Maybe a local test run overwrote the key for this user? Assuming the user was @allileong.

**Comment by amphro** [comment]
I can't reproduce in the lastest version of the CLI.
