### ISSUE TITLE
Doing a force:source:pull return "No results found" when a template had been exported

### ISSUE THREAD

**Issue by pacafuentes** [forcedotcom/cli#1062]
### Summary

Doing a force:source:pull return "No results found" when a template had been exported.

We ship a template to create a community in our package, when the template needs to be changed we just make changes in the template, export it, and then `sfdx force:source:pull` to add the files affected by the change in our package.

But after changing the template `sfdx force:source:pull` returns "No results found"

### Steps To Reproduce:

1. A new scratch is created, push my code ok, next I create a Community and made a pull. I get:

`=== Pulled Source
No results found `

(Which is the expected result)

2.  I create a tab, try pull again, it works:
`=== Pulled Source
STATE    FULL NAME             TYPE      PROJECT PATH
───────  ────────────────────  ────────  ───────────────────────────────────────────────────────────────────────
Add      CommunityApi__c.All1  ListView  force-app/base/objects/CommunityApi__c/listViews/All1.listView-meta.xml
Changed  Admin                 Profile   force-app/components/default/profiles/Admin.profile-meta.xml`

3. Create a community in the scratch org, [export the template](https://help.salesforce.com/articleView?id=sf.community_builder_export_template.htm&type=5)
4. Run `sfdx force:source:pull` , got "No results found" when it should retrieve the exported template

### Expected result

Exported template files should be retrieve

### Actual result

`=== Pulled Source
No results found `

### Additional information

Scratch org dev file:

`{
    "orgName": "MuleSoft Scratch",
    "edition": "Developer",
    "hasSampleData": "true",
    "country" : "US",
    "features": ["Communities", "ServiceCloud", "Sites", "PlatformCache", "Knowledge", "LightningServiceConsole"],
    "settings": {
        "knowledgeSettings": {
            "enableKnowledge": true,
            "enableLightningKnowledge": true
        },
        "lightningExperienceSettings": {
            "enableS1DesktopEnabled": true
        },
        "communitiesSettings": {
            "enableNetworksEnabled": true,
            "enableOotbProfExtUserOpsEnable": true
        },
        "apexSettings": {
            "enableCompileOnDeploy" : true
        }
    }
}`

Running sfdx force:source:retrieve  doesn't get the community metadata either.

I manageed to do a force:pull of just one file. I did the following:

- Downgrade sfdx-cli to 7.99.0
- Added the name file I wanted to be downloaded to : my-sfdx-project/.sfdx/sourcePathInfos.json
- The metadata files of the community created acctually were in my-sfdx-project/.sfdx/maxRevision.json  , I changed lastRetrievedFromServer for the file to 0
- Did a force:pull and the file was downloaded

> The metadata files of the community created acctually were in my-sfdx-project/.sfdx/maxRevision.json

This was weird for me, it seems sfdx get notices about the new metadata files, but for some reason the lastRetrievedFromServer  and  serverRevisionCounter where the same number, which means source:pull won't fetch the last changes

On sfdx log file I could see: 
`{"name":"sfdx", "log":"RemoteSourceTrackingService","level":40,"msg":"Polling for SourceMembers timed out after 26s and 12 attempts","time":"2021-06-15T16:19:01.167Z","v":0}`

It seems like Polling SourceMembers timed out.

**SFDX CLI Version**: sfdx-cli/7.106.3 darwin-x64 node-v15.12.0

**OS and version**: OSX Catalina 10.15.7

**Comment by WillieRuemmele** [comment]
Hi @pacafuentes it sounds like you discovered a timeout... there's the environment variable [`SFDX_SOURCE_MEMBER_POLLING_TIMEOUT` ](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm) which you can set to avoid this error. You can also run the `force:source:tracking:*` commands to help recover your local source tracking when you know what you should see.

**Comment by pacafuentes** [comment]
Hi @WillieRuemmele I set the variable `SFDX_SOURCE_MEMBER_POLLING_TIMEOUT ` to 10 minutes and got the same result

**Comment by WillieRuemmele** [comment]
ok, just to verify - 10 mins = 600s. So `SFDX_SOURCE_MEMBER_POLLING_TIMEOUT=600`

there's also `SFDX_DISABLE_SOURCE_MEMBER_POLLING` which will disable source member polling, so your source tracked results might be wrong (seeing a remote change, when it's already pulled) That's what the `source:tracking:*` commands are for

Have you tried to `force:source:retrieve` the metadata? There's a new [beta source plugin](https://github.com/forcedotcom/cli/issues/1057) that fixes a lot of these metadata related issues.

**Comment by pacafuentes** [comment]
Hi! Sorry for the delay.

I used `SFDX_SOURCE_MEMBER_POLLING_TIMEOUT=600`  and `SFDX_DISABLE_SOURCE_MEMBER_POLLING` with the same result. 

I tried `force:source:retrieve` and nothing happened. 

If there's any useful info I can provide, let me know.

Thanks!

**Comment by pacafuentes** [comment]
Same behaviour when a Custom Object is created in the org, when doing `force:source:pull` the metadata of the Custom Object isn't pull

**Comment by jrod9904** [comment]
Same behaviour when a Custom Object is created in the scratch org, when using force:source:pull the metadata of the Custom Object isn't pull

**Comment by WillieRuemmele** [comment]
Hi @pacafuentes @jrod9904 sorry to leave you radio silent for 2+ years 😦 ... are you still experiencing these source tracking issues on the latest CLI versions? Have you found any workarounds?
