### ISSUE TITLE
Improve sfdx force:user:permset:assign to accept Permission Set Groups

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1066]
**Is your feature request related to a problem? Please describe.**
No

**What are you trying to do**
Assign permission set groups using `sfdx force:user:permset:assign`

**Describe the solution you'd like**
Improve `sfdx force:user:permset:assign` to accept permission set groups, or create a new command or flag

**Describe alternatives you've considered**
I can pass a list of permission sets to the current command

**Additional context**
N/A

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9517915](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Pa5wYAC/view)

**Comment by docbill** [comment]
Unfortunately the work item requires a salesforce employee login to view.

Can you let us know the status of this?

I'm working in a devbox designing a brand new implementation of our org.  One of our best practices is for the 95% usage cases, assign permission groups to users, not permission sets.   I'm trying to create a few hundred inactive users to test out our territory structure.   Is there a way with the tool yet to do this?  Or do I have to do something more tranditional like a workbench csv file load.

I would prefer to use the sfdx type solution, as my script could be reusable for scratch orgs and such in the future.

**Comment by docbill** [comment]
Obviously you'd want a brand new flag.  As a permission set, and permission group may have the same name.

**Comment by mkhokhlov** [comment]
It appears you can pass a permission set _group_ name to force:user:permset:assign and it just works. I just did so with sfdx-cli 7.146.1.

**Comment by AllanOricil** [comment]
Maybe they have implemented it already. Good to know. Thanks for sharing

**Comment by douglascayers** [comment]
> It appears you can pass a permission set _group_ name to force:user:permset:assign and it just works. I just did so with sfdx-cli 7.146.1.

Hrmm.. I get an error if I specify a permission set group name.

I'm using `sfdx-cli/7.166.1 darwin-x64 node-v16.17.0`

```shell
$ sfdx force:user:permset:assign -u test@example.com -n PermSetGroupName

=== Failures

 Username         Error Message                                             
 ──────────────── ───────────────────────────────────────────────────────── 
 test@example.com entity type cannot be inserted: Permission Set Assignment

**Comment by AllanOricil** [comment]
![Screenshot_20221202_195647](https://user-images.githubusercontent.com/55927613/205403544-c9e3dbd1-93f8-4d95-92fc-7a9925c6eeb5.jpg)

**Comment by RodEsp** [comment]
Hey everyone, just chiming in here to say that this should be possible.

We just ran a quick test by creating a new permission set group and passing it into `sfdx force:user:permset:assign -n <permsetGroup>` and it worked just fine.

This was on version `7.179.0` of `sfdx`.

@AllanOricil if you can give us more info about what you're seeing maybe we can figure out if there's a bug or something else going on.

**Comment by AllanOricil** [comment]
> Hey everyone, just chiming in here to say that this should be possible.
> 
> We just ran a quick test by creating a new permission set group and passing it into `sfdx force:user:permset:assign -n <permsetGroup>` and it worked just fine.
> 
> This was on version `7.179.0` of `sfdx`.
> 
> @AllanOricil if you can give us more info about what you're seeing maybe we can figure out if there's a bug or something else going on.

@RodEsp I actually did not test it again. But If you say it works, I belive in you 👍

**Comment by douglascayers** [comment]
Confirmed, the CLI supports assigning users to **permission set groups** and **permission sets**. I last tried several weeks ago and it wasn't working but seems to be working now. Thanks!

`sfdx-cli/7.179.0 darwin-x64 node-v18.12.1`
