### ISSUE TITLE
ERROR running force:source:push:  Flag --wait expects a value 

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1067]
### Summary

When I run `sfdx force:source:push -f -u vodafone_dev -w ` I get the following error message `ERROR running force:source:push:  Flag --wait expects a value `

But it should be a valid command because the description says that the `-w` flag has a default value of 33 minutes

![image](https://user-images.githubusercontent.com/55927613/123630341-c9ed7180-d7eb-11eb-871e-70bcbca993cf.png)

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1 - run  `sfdx force:source:push -f -u ORG_ALIAS -w`

### Expected result

 `sfdx force:source:push -f -u ORG_ALIAS -w` should be valid

### Actual result

 `sfdx force:source:push -f -u ORG_ALIAS -w` throws an error saying -w requires a value, even when it already has a default value

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.94.3-a4e7c7955b win32-x64 node-v14.15.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.5.1 (core)
config 1.2.7 (core)
generator 1.1.5 (core)
org 1.6.7
salesforcedx 51.6.0 (core)
├─ data 0.4.3 (core)
├─ schema 1.0.4 (core)
├─ limits 1.0.4 (core)
├─ templates 51.3.0 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ user 1.2.1 (core)
└─ salesforce-alm 51.6.6 (core)
sfdx-cli 7.94.3 (core)
telemetry 1.1.1 (core)

**OS and version**: windows 10

**Comment by WillieRuemmele** [comment]
Hi @AllanOricil, the `--wait` param defaults to 33 minutes if it isn't specified or past in with the command. By adding the flag, and no value it's not sure how to handle it - and tells you to provide a value. By adding a flag, you are overriding the default, and by providing a flag without a value, you are overriding the default with undefined.

`sfdx force:source:push` defaults to 33 minutes
`sfdx force:source:push -w 3` is set to 3 minutes

**Comment by AllanOricil** [comment]
Oh I see. Sorry for the confusion @WillieRuemmele 
I thought something different.

`sfdx force:source:push -u ALIAS -w` => lock my terminal and wait for the process to finish up to 33 minutes
`sfdx force:source:push -u ALIAS -w 3` => lock my terminal and wait for the process to finish up to 3 minutes
`sfdx force:source:push -u ALIAS` => not lock my terminal and the result/output would only be seen from the Salesforce Setup
