### ISSUE TITLE
Getting an EPERM error when trying to deploy multiple components at the same time.

### ISSUE THREAD

**Issue by danyliuche** [forcedotcom/cli#1072]
### Summary

I am using a remote desktop to access VS Code. I don't have administrator permissions.
I was able to successfully deploy to my sandbox one component or multiple of the same type (e.g. 'aura' folder). But I am getting an EPERM error when trying to deploy the whole project at the same time.

### Steps To Reproduce:

1. Right-click on the folder with the project.
2. Select 'SFDX: Deploy source to org'.

### Expected result

The project is successfully deployed.

### Actual result

After some time I am getting an error:
Error: EPERM: operation not permitted, open 'C:\Users\Username\AppData\Local\Temp\54\sdx_sourceDeploy_pkg_1625150843570\aura\SomeComponent\SomeComponentController.js'

The file that is listed in the error changes after each try.

**SFDX CLI Version**:
sfdx-cli/7.107.0 win32-x64 node-v14.17.1

**SFDX plugin Version**:
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.2 (core)
auth 1.6.1 (core)
config 1.2.8 (core)
custom-metadata 1.0.12 (core)
data 0.4.12 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.6.7 (core)
salesforce-alm 52.0.2 (core)
schema 1.0.7 (core)
sfdx-cli 7.107.0 (core)
telemetry 1.2.2 (core)
templates 52.0.0 (core)
user 1.3.0 (core)

**OS and version**:
Windows Server 2019 Standard

**Comment by mshanemc** [comment]
The new version of deploy doesn't use temporary directories, where I think the errors is arising.  Let us know if you can still get the perm error on a more recent CLI version.

Preferably, use force:source:deploy instead of the VSCode extension (since that's not part of the CLI).  And if you do have a problem, include the output of `sfdx version --verbose` in your response.
