### ISSUE TITLE
[New Source Plugin] Could not infer a metadata type on botVersion

### ISSUE THREAD

**Issue by aheber** [forcedotcom/cli#1076]
### Summary

Using the `force:source:retrieve` or `force:source:deploy` commands with the new Source Plugin (#1057) throws 
>ERROR running force:source:deploy:  C:\...\force-app\core\main\default\bots\AM_SMS_Bot\v1.botVersion-meta.xml: Could not infer a metadata type

### Steps To Reproduce:

I haven't tried to build an isolated project to reproduce this yet. If that is needed please let me know and I can try and distil it from my existing project.

### Expected result

Metadata should have deployed or retrieved.

### Actual result

Command failed with the above error message

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.108.0 win32-x64 node-v14.17.1`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.2 (core)
auth 1.7.0 (core)
config 1.2.9 (core)
custom-metadata 1.0.12 (core)
data 0.4.12 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.6.7 (core)
salesforce-alm 52.0.2 (core)
schema 1.0.7 (core)
sfdx-cli 7.108.0 (core)
sfdx-devops 0.4.3
sfdx-heber 0.0.2
sfdx-typegen 0.6.2
sfpowerkit 3.1.6
shane-sfdx-plugins 4.43.0
├─ @mshanemc/sfdx-sosl 1.1.0
└─ @mshanemc/plugin-streaming 1.1.7
source 0.1.22
telemetry 1.2.2 (core)
templates 52.0.0 (core)
user 1.3.0 (core)
```

**OS and version**:
Windows 10

**Comment by WillieRuemmele** [comment]
Thanks for reporting this @aheber we've already noticed this and I'm working on a fix now

**Comment by hassanalamibmx** [comment]
I'm also facing the same issue. Thank you.

**Comment by shetzel** [comment]
Thanks for using the source plugin beta and reporting this issue everyone!  The fix was made to the source-deploy-retrieve library here: https://github.com/forcedotcom/source-deploy-retrieve/pull/372 and will be included in the next release of that library this week and will also be consumed within the source plugin beta (also this week).

Based on the number of issues the source plugin beta solves and the slow rate of incoming issues with it we are planning to promote the source plugin as a core plugin to the production cli next week Thursday, July 22nd.  Unless something major happens to prevent the promotion, this is the plan.

Thanks again!

**Comment by aheber** [comment]
@shetzel, great! I'll get this installed once it is available. I have a mild concern about releasing on the 22nd only because I haven't been able to do much testing because the new source plugin hasn't been able to successfully run on my metadata yet.

As long as I can build a fresh scratch org with it once it has been updated then I suspect I'll be good to go.

**Comment by shetzel** [comment]
@aheber - good to know.  It's very possible that date could slip based on new bugs found and their fixes.  Thanks!

**Comment by aheber** [comment]
I think is fixed in the current version. Closing.

**Comment by hassanalamibmx** [comment]
I am using `sfdx-cli/7.112.0 win32-x64 node-v16.4.1` (installed using npm) and I'm facing the same issue again.

Should I open a new issue?
