### ISSUE TITLE
Problem converting page layout from source to metadata format

### ISSUE THREAD

**Issue by yeanchiat** [forcedotcom/cli#1081]
### Summary

Try converting a custom object's page layout from source to metadata format, but all other page layouts of that particular custom object get converted as well.

### Steps To Reproduce:

1.  Specify a custom object's page layout (just 1 page layout) in manifest (package.xml)
1.  Run _sfdx force:source:convert -d mdapi -x force-app\main\default\package.xml_

### Expected result

Expect to see 1 page layout (the one specified in manifest) being converted in the output directory.

### Actual result

All other page layouts (including the one specified in manifest) related to the custom object being converted into metadata format and appear in the output directory.

### System Information

{
        "cliVersion": "sfdx-cli/7.109.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.17.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.0 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.2 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.12 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.4.12 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.6.7 (core)",
                "salesforce-alm 52.0.4 (core)",
                "schema 1.0.7 (core)",
                "sfdx-cli 7.109.0 (core)",
                "sfdx-run-script 0.1.0 (link) C:\\Users\\3683xj\\WYC\\Salesforce\\Repos\\Post-Refresh\\sfdx-deployment-scripts-runner\\scriptrunner",
                "telemetry 1.2.2 (core)",
                "templates 52.1.0 (core)",
                "user 1.3.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19042"
}

### Additional information

This situation doesn't seem to affect standard object's page layout.

<img width="576" alt="page-layout2" src="https://user-images.githubusercontent.com/76905501/125766993-00850915-778c-4079-bd57-09e9a2b63333.png">

**Comment by chernyy-svyat** [comment]
Have the same issue
sfdx-cli/7.86.3 darwin-x64 node-v14.15.5

**Comment by WillieRuemmele** [comment]
Hi @yeanchiat @chernyy-svyat have you guys tried the [beta source plugin](https://github.com/forcedotcom/cli/issues/1057) it fixes a lot of metadata issues like this

**Comment by mshanemc** [comment]
closed due to no response.
