### ISSUE TITLE
Replace tslint with eslint

### ISSUE THREAD

**Issue by goto-dev-null** [forcedotcom/cli#1086]
**Is your feature request related to a problem? Please describe.**
TSLint has been deprecated in favor of ESLint, so obviously it should aimed at being replaced. I didn't see an issue open or closed for it, so here it is.

I should give the context that for me this is more relevant for developing a custom SFDX plugin, and I just assume that the place to file an issue would be here.

**What are you trying to do**
N/A

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
Installing tslint gives a link to this issue:
https://github.com/palantir/tslint/issues/4534

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9626297](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000RfjmYAC/view)

**Comment by cristiand391** [comment]
Closing this, both sfdx and sf plugin templates use `eslint` for linting.
