### ISSUE TITLE
[New Source Plugin] Static Resource ZIP Compression doesn't seem to be as tight, "static resource cannot exceed 5MB"

### ISSUE THREAD

**Issue by aheber** [forcedotcom/cli#1098]
### Summary

When deploying my static resources I get the error "static resource cannot exceed 5MB" for a single resource where I've dealt with size issues in the past. If I uninstall the new Source plugin then static resources deploy correctly.

### Steps To Reproduce:

I don't have a set of files I can share publicly but could share the Static Resource contents private on request.

### Expected result

Static Resource should have deployed. The current SFDX (non-Source plugin) packs to a ZIP file that comes in at 4.92MB where the Source-Plugin version packs to 5.13MB.

### Actual result

Static resource exceeded the 5MB file size limit and failed to deploy only when using the Source plugin.

### System Information

{
	"cliVersion": "sfdx-cli/7.110.0",
	"architecture": "win32-x64",
	"nodeVersion": "node-v14.17.3",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.2 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.0 (core)",
		"@oclif/plugin-update 1.4.0-3 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"@salesforce/sfdx-trust 3.6.0 (core)",
		"alias 1.1.10 (core)",
		"apex 0.2.2 (core)",
		"auth 1.7.1 (core)",
		"config 1.2.13 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.5.2 (core)",
		"generator 1.1.7 (core)",
		"limits 1.2.1 (core)",
		"org 1.6.7 (core)",
		"salesforce-alm 52.1.0 (core)",
		"schema 1.0.8 (core)",
		"sfdx-cli 7.110.0 (core)",
		"sfdx-devops 0.4.3",
		"sfdx-heber 0.0.2",
		"sfdx-typegen 0.6.2",
		"sfpowerkit 3.1.6",
		"shane-sfdx-plugins 4.43.0",
		"?????? @mshanemc/plugin-streaming 1.1.7",
		"?????? @mshanemc/sfdx-sosl 1.1.0",
		"telemetry 1.2.2 (core)",
		"templates 52.1.0 (core)",
		"user 1.3.1 (core)"
	],
	"osVersion": "Windows_NT 10.0.19042"
}

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9679677](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000SdaUYAS/view)

**Comment by mshanemc** [comment]
@aheber nice catch, thanks for reporting!

**Comment by tfuda** [comment]
I too am hitting this after updating to version 7.112 today; It only seems to happen if I use force:source:deploy to deploy my static resources. I can push the same static resource bundle to scratch orgs using force:source:push with no problem. In my case, the problematic resource is 4,552,560 bytes in my scratch org after force:source:push, but the same static resource bundle cannot be deployed using force:source:deploy because it is exceeding 5 MB.

**Comment by daveespo** [comment]
@mshanemc -- Will this get addressed in this week's CLI release? This is a blocker for CI/CD
