### ISSUE TITLE
Add support for dev hub based on the project

### ISSUE THREAD

**Issue by jefersonchaves** [forcedotcom/cli#11]
**Is your feature request related to a problem?**
It is a feature. Consultants and other service providers that work with multiple customers need to switch between dev hubs.

**What are you trying to do**
Would like to have multiple projects and have the default dev hub saved inside the project similar to default scratch org.

**Describe the solution you'd like**
Store the dev hub on project file along to default scratch org.

**Comment by aheber** [comment]
@jefersonchaves isn't this already available?

While in a project you should be able to run `sfdx force:config:set defaultdevhubusername=[devhub@project.com]` and that should set the value in the `.sfdx/sfdx-config.json` and be scoped just to that specific project.

I just did that today so it should work...

**Comment by jefersonchaves** [comment]
@aheber: fantastic, that is exactly what I needed. I will play around that.

Now I found on [force:config doc](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_config.htm) but I guess it can be improved.
