### ISSUE TITLE
Reset source tracking to state after last successful push

### ISSUE THREAD

**Issue by TREX1-JR** [forcedotcom/cli#1100]
**Is your feature request related to a problem? Please describe.**

I have to either run `sfdx force:source:push` or `sfdx force:source:pull` to get sourcePathInfos.json into the correct state - even if the org is already mostly in sync with my local. E.g. after running `sfdx force:source:tracking:reset -p`, or after running `sfdx force:source:deploy` (this seems to clear source tracking), or after connecting to an org with existing metadata

**What are you trying to do**

A way to quickly get sourcePathInfos.json from the cleared state into the correct state so that the subsequent `sfdx force:source:push` only pushes up files that are different between the org & local.

**Describe the solution you'd like**

A way to connect to a scratch org that already contains metadata & update my source tracking without having to wait for a sfdx force:source:push or sfdx force:source:pull.

Maybe add a hash field to the SourceMember table. Add a new option to `sfdx force:source:tracking:reset` that then updates states in sourcePathInfos.json by comparing the hash on the latest SourceMember to the current hash of the file?

**Describe alternatives you've considered**

Something like the below works to go from no source tracking to only pushing up changed files, but it still requires waiting for the pull.

`sfdx force:source:pull -f && git reset --hard && sfdx force:source:push -f`

Adding the `orgs/` folder into version control might also work but would add a lot of noise to diffs.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9681643](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000SfwPYAS/view)

**Comment by mshanemc** [comment]
source deploy and retrieve now have the `-t` option to have those commands update tracking files when the operation completes.  That's designed as a way to get things straight.

There's ALSO the new `project deploy start|resume` that lets you "resume" your recent deploy (or any other deploy via jobId).  Resume includes getting the tracking information from the deployment updated locally.
