### ISSUE TITLE
npm install fails due to Husky version needs bumping

### ISSUE THREAD

**Issue by nathanhall-dev** [forcedotcom/cli#1103]
### Summary

When creating a new sfdx project with the standard template, and running npm install - husky dependency fails due to this issue:
https://github.com/typicode/husky/issues/1003
https://github.com/typicode/husky/issues/1003#issuecomment-874667232

(For my version of sfdx template - Husky is installed as v^6.0.0)

Because .git file is not initiated when you're creating SFDX Template Project - npm instlal fails to run.

Husky needs to be installed as v^7.0.1 to resolve this

### Steps To Reproduce:
1. Create sfdx project
`mkdir sfdx-project`
`sfdx force:command:create sfdx-project`
'npm install'

Add the following engine configurations (most recent stable versions of npm / node).
Engine configuration:
  "engines": {
    "npm": "7.2.3", 
    "node": "16.6.1"
  },

### Expected result

npm install should run correctly

### Actual result

npm install fails - due to Husky issue: https://github.com/typicode/husky/issues/1003

### System Information
$ sfdx version --verbose -json
 CLI Version :
        sfdx-cli/7.110.0

 Architecture:
        win32-x64

 Node Version :
        node-v14.17.3

 Plugin Version:
        @oclif/plugin-autocomplete 0.3.0 (core)
        @oclif/plugin-commands 1.3.0 (core)
        @oclif/plugin-help 3.2.2 (core)
        @oclif/plugin-not-found 1.2.4 (core)
        @oclif/plugin-plugins 1.10.0 (core)
        @oclif/plugin-update 1.4.0-3 (core)
        @oclif/plugin-warn-if-update-available 1.7.0 (core)
        @oclif/plugin-which 1.0.3 (core)
        @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
        @salesforce/sfdx-trust 3.6.0 (core)
        alias 1.1.10 (core)
        apex 0.2.2 (core)
        auth 1.7.1 (core)
        config 1.2.13 (core)
        custom-metadata 1.0.12 (core)
        data 0.5.2 (core)
        generator 1.1.7 (core)
        limits 1.2.1 (core)
        org 1.6.7 (core)
        salesforce-alm 52.1.0 (core)
        schema 1.0.8 (core)
        sfdx-cli 7.110.0 (core)
        telemetry 1.2.2 (core)
        templates 52.1.0 (core)
        user 1.3.1 (core)

 OS and Version:
        Windows_NT 10.0.19042

### Additional information

_Feel free to attach a screenshot_.

**Comment by WillieRuemmele** [comment]
Hi @nhall97 I'm a little confused, you mention a `sfdx force:command:create` command, which is not an official salesforce cli command, it could be brought in by another plugin you've installed, in which case you should let the owners of that plugin know. 

good news, I was able to `npm install` inside of a new project using official commands
```
sfdx force:project:create -n sfdx-project
cd sfdx-project
npm install
```
without any errors

**Comment by nathanhall-dev** [comment]
Thanks @WillieRuemmele for confirming no template errors.

I'll try and recreate tomorrow and if issues persist, update my comments

**Comment by nathanhall-dev** [comment]
@WillieRuemmele can't seem to replicate - will write it off and close!
