### ISSUE TITLE
force:source:deploy fails with An object 'themeLibrary' of type LightningComponentBundle was named in package.xml, but was not found in zipped directory

### ISSUE THREAD

**Issue by loter** [forcedotcom/cli#1107]
### Summary

After installing .112, failed to force:source:deploy -p force-app

Error getting:
 themeLibrary		0	0	An object 'themeLibrary' of type LightningComponentBundle was named in package.xml, but was not found in zipped directory

Also sfdx cli is not displaying the issue, just says deploy failed

sh-3.2$ sfdx force:source:deploy -u INT -p force-app
WARNING: apiVersion configuration overridden at "52.0"
*** Deploying with SOAP API ***
Deploy ID: 0Af4C00000pW0AJSA0
SOURCE PROGRESS | ████████████████████████████████████████ | 625/625 Components

=== Component Failures [0]
Type  Name  Problem
────  ────  ───────

ERROR running force:source:deploy:  Deploy failed.

### Steps To Reproduce:

1.  Install latest sfdx
2. have themeLibrary forceignored
3.   force:source:deploy -p force-app

### Expected result

This worked with prev version of sfdx - should deploy

### Actual result

fails to deploy

### System Information

```
sh-3.2$ sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.112.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v14.17.4",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.3 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.14 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.0 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.6.7 (core)",
                "salesforce-alm 52.2.2 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.112.0 (core)",
                "source 1.0.6 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Darwin 20.6.0"
}
```

**Comment by WillieRuemmele** [comment]
Hey @loter this will be fixed asap. Is the `themeLibrary` lwc populated? does it have files in that directory, or is it empty?

**Comment by loter** [comment]
we have the following files in the folder:

![image](https://user-images.githubusercontent.com/2570305/128406510-47c7611d-9848-4437-b3f6-7bbc760dde24.png)

where I said themeLibrary it's actually prmThemeLibrary

**Comment by WillieRuemmele** [comment]
Thank you, I'm looking into reproducing this now

**Comment by anderg4** [comment]
We're also getting this on loads of design elements during our code pipeline deployment using SFDX CLI on latest version.  Minor code change to a couple of apex classes, and it's now failing with 100s of copies of different design elements:

retrieved version from:
`https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz`

command:
```
sfdx auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile /tmp/server.key --username $USERNAME --instanceurl $URL
sfdx force:source:deploy --wait 30 --manifest ./manifest/package.xml --testlevel RunLocalTests --targetusername $USERNAME --json
```

An object 'Case.Case Assignment' of type AssignmentRule was named in package.xml, but was not found in zipped directory
An object 'Account.AddrCountryIso__pc' of type CustomField was named in package.xml, but was not found in zipped directory
An object 'Account.AddrLine1__pc' of type CustomField was named in package.xml, but was not found in zipped directory
An object 'AccountOpening/PublicDashboards' of type Dashboard was named in package.xml, but was not found in zipped directory

etc

**Comment by anderg4** [comment]
@WillieRuemmele, we've reverted to sfdx-cli/7.110.0 and it's working as expected

**Comment by steals** [comment]
Have the same issue on the latest cli, majority of errors related to the reports.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9719017](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000TOIBYA4/view)

**Comment by WillieRuemmele** [comment]
Hi @loter I haven't been able to reproduce this with a valid LWC, I'm using an LWC like  
<img width="297" alt="lwc" src="https://user-images.githubusercontent.com/23369140/128568619-f54816d0-d0ec-4bd4-84d6-8ba44f5814fb.png">
and using `plugin-source 1.0.6` it deploys.

if I remove the `.js` `.html` `.js-meta.xml` files like yours it will error, but that is not a valid LWC. According to the [docs](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/create_components_define) LWCs require those files

I'm more curious about the `prmLibraryTheme.scss` file, it has a dropdown like a directory. does it contain any map files? Looking at some [StackOverflow](https://salesforce.stackexchange.com/questions/267446/using-sass-scss-with-lightning-web-components) questions it seems like that might cause an error

I'm not sure how this was even working on `7.110.0`... I'm trying with an LWC matching yours and only get this error 
```
 ➜  sfdx force:source:deploy -p force-app/main/default/lwc/mycomponent 
ERROR running force:source:deploy:  Unexpected file found in package directory: /XXXXX/ebikes-lwc/force-app/main/default/lwc/mycomponent/_colors.scss
```

**Comment by WillieRuemmele** [comment]
Hi @loter checkout Steve's [comment](https://github.com/forcedotcom/cli/issues/1106#issuecomment-894571663) on the other issue thread about following best practices... deploying invalid LWCs may not be supported going forward - I still don't understand how it was working for you before this
