### ISSUE TITLE
Getting Error while running config:set:  No AuthInfo found for name

### ISSUE THREAD

**Issue by pradnyadesaiSFDC** [forcedotcom/cli#1109]
### Summary

Getting Error while running config:set:  No AuthInfo found for name

### Steps To Reproduce:

**Repository to reproduce:** Gitlab

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1. Create Variable in  Settings->CI-CD
1.  This is step 2. Run following from gitlab.yaml for deployment
2.  local alias_to_set=$1
        local org_auth_url=$2
        local org_auth_url_backup=$3
    
        local file=$(mktemp)
        echo $org_auth_url > $file
        local cmd="sfdx force:auth:sfdxurl:store --sfdxurlfile $file --setalias $alias_to_set --json" && (echo $cmd >&2)
        local output=$($cmd)
    
        sfdx force:config:set defaultusername=$alias_to_set
        sfdx force:config:set defaultdevhubusername=$alias_to_set

### Expected result

$ authenticate UAT $UAT_AUTH_URL
65sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/tmp.CFnmGvVgw1 --setalias UAT --json
66=== Set Config
67Name             Value  Success
68───────────────  ─────  ───────
69defaultusername  UAT    true
70=== Set Config
71Name                   Value  Success
72─────────────────────  ─────  ───────
73defaultdevhubusername  UAT    true

### Actual result

$ authenticate UAT $UAT_AUTH_URL
56sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/tmp.NnXpGt8wQz --setalias UAT --json
57=== Set Config
58Name             Value  Success
59───────────────  ─────  ───────
60defaultusername  UAT    false
61ERROR running config:set:  No AuthInfo found for name UAT

### System Information

Run `sfdx version --verbose --json` and paste the output here.

### Additional information

_Feel free to attach a screenshot_.

**Comment by mshanemc** [comment]
does `/tmp/tmp.CFnmGvVgw1` exist in your gitlab environment?  I assume it's in an environment variable somewhere before writing to that tmp file?

https://gitlab.com/sfdx/sfdx-cicd-template

And if you ran `sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/tmp.CFnmGvVgw1 --setalias UAT --json` you should be able to see an error message if it's not authenticating (which it's not, based on `org:list`, which would run on gitlab if you had any orgs auth'd there)

**Comment by pradnyadesaiSFDC** [comment]
/tmp/tmp.CFnmGvVgw1 Should be present, as we are creating that file from command local file=$(mktemp).
I do not see error logs for command sfdx force:auth:sfdxurl:store. But sfdx force:config:set is failing. 
Moreover this .yaml work fine with existing branch. Newly created branches are having issues.
Do you think it could be permission issue?

$ authenticate UAT $UAT_AUTH_URL
56sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/tmp.NnXpGt8wQz --setalias UAT --json
57=== Set Config
58Name Value Success
59─────────────── ───── ───────
60defaultusername UAT false
61ERROR running config:set: No AuthInfo found for name UAT

**Comment by mshanemc** [comment]
It **looks** like you have some script named `authenticate` that's running `sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/tmp.NnXpGt8wQz --setalias UAT --json`

If you run that command `sfdx force:auth:sfdxurl:store --sfdxurlfile /tmp/tmp.NnXpGt8wQz --setalias UAT --json` directly you should see the error happening.

`config:set` is failing because the auth didn't happen.

**Comment by pradnyadesaiSFDC** [comment]
Thanks @mshanemc 
I run store command directly. Got below error:
{
65  "status": 1,
66  "name": "INVALID_SFDX_AUTH_URL",
67  "message": "Invalid sfdx auth url. Must be in the format `force://<clientId>:<clientSecret>:<refreshToken>@<loginUrl>`. The instanceUrl must not have the protocol set.",


I have generated urls using following command:
sfdx force:org:display --targetusername <username> --verbose

Sample url looks like : force://PlatformCLI::***********@panelsfd--qa2.my.salesforce.com

**Comment by pradnyadesaiSFDC** [comment]
Note: I have followed these steps earlier to setup CI-CD. It was working fine. But now it's not working with new environments.

https://gitlab.com/sfdx/sfdx-cicd-template

**Comment by mshanemc** [comment]
the regex we're using to check the auth url is [here](https://github.com/forcedotcom/sfdx-core/blob/66881eae2f30215c862ea398bfc1630d9a5898fe/src/authInfo.ts#L477)
```js
const match = sfdxAuthUrl.match(
      /^force:\/\/([a-zA-Z0-9._-]+):([a-zA-Z0-9._-]*):([a-zA-Z0-9._-]+={0,2})@([a-zA-Z0-9._-]+)/
    );
```
  
Can you test your AuthUrl with that (browser console will work) to see if there's something wrong?  In particular, does the refresh token match that 3rd capture group `([a-zA-Z0-9._-]+={0,2})`?

Also be sure to check for trailing whitespace to be trimmed if you're copy-pasting, or parsing stdout

**Comment by pradnyadesaiSFDC** [comment]
Thanks Shane. 

I guess issue is with some permission. Looks like there is some permission issue. Newly created branches are not able to read the variables, where as old branches can access the same urls.
Thanks again for your help and guidance.

**Comment by cristiand391** [comment]
Seems this can be closed, please reopen this issue if you need help.
