### ISSUE TITLE
package.xml file is not getting generated after Source Plugin beta

### ISSUE THREAD

**Issue by vjs9** [forcedotcom/cli#1111]
Summary

Issue with generating the sdx_sourceDeploy_pkg_*** after the beta plugin update

Steps To Reproduce:
1.Initate a build
2. navigate to C:\Windows\TEMP 

### Expected result

There should be a temporary file "sdx_sourceDeploy_pkg_***" generated with the components getting deployed along with package.xml under C:\Windows\TEMP folder

### Actual result

no package.xml file nor the .zip 

### System Information

SFDX CLI Version(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.107.0 win32-x64 node-v14.17.1

### Additional information

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-scanner 2.9.2
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.2 (core)
auth 1.6.1 (core)
config 1.2.8 (core)
custom-metadata 1.0.12 (core)
data 0.4.12 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.6.7 (core)
salesforce-alm 52.0.2 (core)
schema 1.0.7 (core)
sfdx-cli 7.107.0 (core)
source 1.0.6
telemetry 1.2.2 (core)
templates 52.0.0 (core)
user 1.3.0 (core)

<img width="769" alt="package_issue" src="https://user-images.githubusercontent.com/88673776/128736582-dc7d41a7-8c46-45a9-8a06-017da97ea8af.PNG">

**Comment by shetzel** [comment]
@vjs9 - The new source plugin uses a library called `@salesforce/source-deploy-retrieve` and that library no longer writes to the file system by default, so this is intended and not a bug.   For better performance, deploys and retrieves stream data instead.  If you want something similar to the old behavior you can set the `SFDX_MDAPI_TEMP_DIR` environment variable to a directory and it will write files and the manifest to that location.
