### ISSUE TITLE
Cannot delete package or package version

### ISSUE THREAD

**Issue by MitchHeath-DD** [forcedotcom/cli#1116]
### Summary

Using `sfdx force:package:delete` I cannot delete a package or package version with alias (e.g. XXX@0.1.0-1) or 0Ho/04t ids.

### Steps To Reproduce:

1. Have packageDirectories and packageAliases contain package info
e.g. 
`"path": "a-path",
            "package": "a-unlocked",
            "versionName": "ver 0.1",
            "versionNumber": "0.1.0.NEXT",
            "default": false`

and 
`"a-unlocked": "0HoXXX",
            "a-unlocked@0.1.0-1": "04tXXX"`

2. Run any variation:
For Package Versions:
sfdx force:package:delete --noprompt -p "a-unlocked@0.1.0-1"
sfdx force:package:delete --noprompt -p "04tXXX"

For Packages
sfdx force:package:delete --noprompt -p "a-noversions"
sfdx force:package:delete --noprompt -p "0HoXXX"

### Expected result

> Successfully deleted the package version. 04tXXX

### Actual result

> ERROR running force:package:delete:  The Package Id: 04tXXXXXX isn't defined in the sfdx-project.json. Add it to the packageDirectories section and add the alias to packageAliases with its 0Ho ID.

### System Information

{
        "cliVersion": "sfdx-cli/7.112.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.17.4",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "apex 0.2.3 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.14 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.0 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.6.7 (core)",
                "salesforce-alm 52.2.3 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.112.1 (core)",
                "source 1.0.6 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.18363"
}

### Additional information

Other notes:

- It worked for other packages and package versions
- All packages in sfdx-project.json belong to this DevHub (sfdx force:package:list)
- packageDirectories have correct info (no empty paths)
- Tried using aliases and ids

Thanks for any help

**Comment by mshanemc** [comment]
Are you able to share your full `sfdx-project.json` (it's ok to mask the 04t/0Ho like you're doing)?
Was this working previously and suddenly stopped, or is it a new package project?

We have a test using real orgs that does package create, version create, install, uninstall, version delete, then package delete for every change/release, so I'm wondering if there's something wonky with the file structure that it can't find it (case sensitivity, 15 v 18 digit IDs, etc)

**Comment by MitchHeath-DD** [comment]
```
{
    "packageDirectories": [
        {
            "path": "base-unlocked",
            "package": "a-unlocked",
            "versionName": "ver 0.1",
            "versionNumber": "0.1.0.NEXT",
            "default": true
        }
    ],
    "namespace": "XXX",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "52.0",
    "packageAliases": {
        "a-unlocked": "0Ho",
        "a-unlocked@0.1.0-1": "04t",
        "a-unlocked@0.1.0-2": "04t",
        "a-unlocked@0.1.0-3": "04t",
        "a-unlocked@0.1.0-4": "04t",
        "a-unlocked@0.1.0-5": "04t",
        "a-unlocked@0.1.0-6": "04t"
    }
}
```
All ids are 18 digits

Running: `sfdx force:package:delete --noprompt -p  alpha-unlocked@0.1.0-6`

Returns: The Package Id: 04t (correct ID for beta 6) isn't defined in the sfdx-project.json. Add it to the packageDirectories section and add the alias to packageAliases with its 0Ho ID.

I did have another package but after trying again it happily deleted now..
