### ISSUE TITLE
missing param "checkonly" for force:source:deploy --checkonly

### ISSUE THREAD

**Issue by jsullivanlive** [forcedotcom/cli#112]
### Summary

The documentation at https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_build_mdapi_production.htm shows the command `sfdx force:source:deploy --checkonly --sourcepath force-app --targetusername production-org 
--testlevel RunLocalTests` but it doesn't work in the latest version of the sfdx cli.

Further, this documentation page [ https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm ] shows an argument "--checkonly" or "-c" but that argument is not shown when doing `sfdx force:source:deploy --help`

### Steps To Reproduce:

1.  `npm i -g sfdx-cli`
1.  Auth to a sandbox
1.  Try running `sfdx force:source:deploy --checkonly`
1.  Get argument error:

    ERROR running force:source:deploy:  Unexpected argument: --checkonly
    See more help with --help

### Expected result

Check deployment without committing changes

### Actual result

Exits with error

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

    sfdx-cli/7.8.1 darwin-x64 node-v11.9.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

```
$ sfdx plugins --core
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.16.0 (core)
├─ force-language-services 45.12.0 (core)
└─ salesforce-alm 45.18.0 (core)

sfdx-cli 7.8.1 (core)

```

**OS and version**:

macOS 10.14.5 (18F203)

**Comment by shetzel** [comment]
@jsullivanlive - you are looking at the docs for the pre-release version of the CLI, not the current production release.  If you install the pre-release version, those new command parameters are there.  Alternatively, if you wait a week, a new major version of the salesforcedx plugin (46.0.1 is the likely version number) will be released and those command params will be available in production.
