### ISSUE TITLE
Non-standard project layout causes issues

### ISSUE THREAD

**Issue by WillieRuemmele** [forcedotcom/cli#1122]
@AndrewRayCode

https://github.com/forcedotcom/cli/issues/1112#issuecomment-896134845
I found my first issue, which was that there are *.cls files inside an object folder. After moving those, I'm now getting
> Expected source files for type 'EmailTemplate'

https://github.com/forcedotcom/cli/issues/1112#issuecomment-896154715

https://github.com/forcedotcom/cli/issues/1112#issuecomment-896326206

https://github.com/forcedotcom/cli/issues/1106#issuecomment-894577252

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9749128](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000TxSVYA0/view)
