### ISSUE TITLE
Provide instructions for how to view telemetry data sent to Salesforce

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#1124]
It has recently come to our attention that a bad actor plugin, taking queues from sfdx, sends local environment variables to their own telemetry server. This is a security risk.

I need to audit the sfdx telemetry data to verify that it also doesn't send any env variables. Please provide instructions on how to view all telemetry events that sfdx logs.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9749280](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000TxeRYAS/view)

**Comment by mshanemc** [comment]
telemetry plugin is here: https://github.com/salesforcecli/plugin-telemetry
which uses this library: https://github.com/forcedotcom/telemetry

You can opt out of our telemetry https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_telemetry.htm

**Comment by AndrewRayCode** [comment]
That's closed source. We have disabled telemetry but need to confirm historical use. Can you both show how to log what's sent to salesforce, and also confirm that **no** environment variables of any kind are sent as part of telemetry, which would mean you're potentially vacuuming up secrets from sfdx users by default?

**Comment by mshanemc** [comment]
https://github.com/forcedotcom/telemetry was supposed to be a public repo.  It's public now.

Previous iterations are here if you want to review historical behavior: https://github.com/forcedotcom/cli-packages/tree/main/packages/telemetry

> and also confirm that no environment variables of any kind are sent as part of telemetry

Plugin-telemetry sends some environment variables.  You can review that behavior here:
https://github.com/salesforcecli/plugin-telemetry/blob/58a4206fc6537e26dc2e390100ffa3b3fba52635/src/commandExecution.ts

The readme for https://github.com/salesforcecli/plugin-telemetry has example code of how to set up telemetry debugging
