### ISSUE TITLE
We can’t retrieve the specified metadata object: PicklistValue.

### ISSUE THREAD

**Issue by MeiwesSopra** [forcedotcom/cli#1130]
Salesforce sfdx force:source:pull is not working

**Comment by WillieRuemmele** [comment]
Hi @MeiwesSopra can you please follow the bug template that should've been provided when creating this issue. You can find the template [here](https://github.com/forcedotcom/cli/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)
