### ISSUE TITLE
force:source:retrive removing translation comments?

### ISSUE THREAD

**Issue by jmratel** [forcedotcom/cli#1131]
**Summary**
With version 7.113.0 the force:source:retrive behavior changed for translations of custom fields and search layout.
For translations it used to be the case that a comment would hold the default value if not translated event in english. I'm giving a random example of one of the fields but you can reproduce that with any custom field (giving en_US and es as an example)
![image](https://user-images.githubusercontent.com/58741970/129364248-08de85c6-4eca-49d0-9cc9-3e0821a5953c.png)
![image](https://user-images.githubusercontent.com/58741970/129364278-e68b0524-ffda-44f1-a7d6-1ecc4286a5cb.png)

For search layout it was self closing if it was empty and is not anymore
![image](https://user-images.githubusercontent.com/58741970/129364472-4830e97b-67cc-4171-9b6a-9536948a5a72.png)

I've looked at the notes and nothing mentions that. My question is: is this the new intended behaviour or will it go back to what it was with the comments in the translations and self closing tags? If more detail is needed please let me know

**Comment by WillieRuemmele** [comment]
Hi @jmratel yes, this is new behavior. In this release we used the same deploy/retrieve library that VScode has been using for the past few months

**Comment by jmratel** [comment]
Thanks for confirming the new behaviour
