### ISSUE TITLE
Authorise a Dev Hub from GitHub Codespace

### ISSUE THREAD

**Issue by rsindall** [forcedotcom/cli#1134]
When I try and authorise a Dev Hub from VSCode when its cloud hosted in Codespace, it does the OAuth redirect back to localhost rather than the Codespace address.

How do I make it redirect back to the codespace?

**Comment by mshanemc** [comment]
@rsindall are you using username/password login or JWT or a AuthUrl?

**Comment by rsindall** [comment]
username/password login via web direct

**Comment by rsindall** [comment]
FYI 

https://salesforce.stackexchange.com/questions/354187/how-to-authentication-a-dev-hub-from-a-vs-code-hosted-via-github-codespaces/354201#354201

**Comment by zerkz** [comment]
I found using the new `auth:device:login` method to be best for getting auth on codespaces.

**Comment by FabienTaillon** [comment]
Actually if you use the Command Palette to Authorize a Dev Hub directly from GitHub Codespace:

<img width="619" alt="auth" src="https://user-images.githubusercontent.com/2465122/143482696-1ba67709-9f33-4b29-a67e-ed1b7ca5f20f.png">

the Salesforce Extensions for VS Code is already clever enough to use the `sfdx force:auth:device:login`:

<img width="679" alt="device" src="https://user-images.githubusercontent.com/2465122/143482727-6d69d50a-7006-4fdf-b18c-3fb10ab69589.png">

So to me it's already working correctly.

**Comment by mshanemc** [comment]
closing, since this seems to be working for other people
