### ISSUE TITLE
FieldTranslation not deploy

### ISSUE THREAD

**Issue by barouchk** [forcedotcom/cli#1135]
when pulling from sandbox object translation with package:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
        <members>Expert_Consulting__c</members>
        <name>CustomObject</name>
    </types>
	<types>
        <members>Expert_Consulting__c-iw</members>
        <name>CustomObjectTranslation</name>
    </types>
	<version>52.0</version>
</Package>
```

It retrieve all fieldTranslation as well

But when performing deploy with the same package.xml, the field translation not deployed.

This issue happened with version: sfdx-cli/7.112.1

**Comment by WillieRuemmele** [comment]
Hi @barouchk could you paste the output of `sfdx plugins --core`, can you try the deploy again with  the `--dev-debug` flag? That'll enable logging and can be very useful to us. What sort of errors are you seeing?

**Comment by barouchk** [comment]
Hi Willie,

There are no errors when deploying, the issue is that I can see that the field translation has been deployed.
If I'm deploying the full folder, the fieldTrnalstion is deployed,
but with the sfdx command, it retrieving the fieldTranslation but not deploying it.

**the logs for sfdx plugins --core are:**

`@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.3 (core)
auth 1.7.1 (core)
config 1.2.14 (core)
custom-metadata 1.0.12 (core)
data 0.6.0 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.6.7 (core)
salesforce-alm 52.2.3 (core)
schema 1.0.8 (core)
sfdx-cli 7.112.1 (core)
source 1.0.6 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
user 1.4.0 (core)`

**The logging for --dev-debug are:**

`FULL NAME                                   TYPE                     PROJECT PATH
──────────────────────────────────────────  ───────────────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Expert_Consulting__c.Agent_Calling__c       CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Agent_Calling__c.field-meta.xml
Expert_Consulting__c.Agent_Carring__c       CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Agent_Carring__c.field-meta.xml
Expert_Consulting__c.Case__c                CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Case__c.field-meta.xml
Expert_Consulting__c.Consulting_Name__c     CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Consulting_Name__c.field-meta.xml
Expert_Consulting__c.Consulting_Subject__c  CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Consulting_Subject__c.field-meta.xml
Expert_Consulting__c.Description__c         CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Description__c.field-meta.xml
Expert_Consulting__c.Main_Subject__c        CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Main_Subject__c.field-meta.xml
Expert_Consulting__c.Primary_Info_Topic__c  CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Primary_Info_Topic__c.field-meta.xml
Expert_Consulting__c.Result__c              CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Result__c.field-meta.xml
Expert_Consulting__c.Second_Subject__c      CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Second_Subject__c.field-meta.xml
Expert_Consulting__c.Status__c              CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Status__c.field-meta.xml
Expert_Consulting__c.Timeline_Name__c       CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/Timeline_Name__c.field-meta.xml
Expert_Consulting__c.To_Display__c          CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/To_Display__c.field-meta.xml
Expert_Consulting__c.To_Display_delete__c   CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/To_Display_delete__c.field-meta.xml
Expert_Consulting__c.URL__c                 CustomField              force-app/main/default/objects/Expert_Consulting__c/fields/URL__c.field-meta.xml
Expert_Consulting__c                        CustomObject             force-app/main/default/objects/Expert_Consulting__c/Expert_Consulting__c.object-meta.xml
Expert_Consulting__c-iw                     CustomObjectTranslation  force-app/main/default/objectTranslations/Expert_Consulting__c-iw/Expert_Consulting__c-iw.objectTranslation-meta.xml
Expert_Consulting__c.All                    ListView                 force-app/main/default/objects/Expert_Consulting__c/listViews/All.listView-meta.xml
Expert_Consulting__c.Prevent_Reopening      ValidationRule           force-app/main/default/objects/Expert_Consulting__c/validationRules/Prevent_Reopening.validationRule-meta.xml
  sfdx:Deploy INFO [
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Agent_Calling__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Agent_Calling__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Agent_Carring__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Agent_Carring__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Case__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Case__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Consulting_Name__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Consulting_Name__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Consulting_Subject__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Consulting_Subject__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Description__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Description__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Main_Subject__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Main_Subject__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Primary_Info_Topic__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Primary_Info_Topic__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Result__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Result__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Second_Subject__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Second_Subject__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Status__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Status__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Timeline_Name__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/Timeline_Name__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.To_Display__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/To_Display__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.To_Display_delete__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/To_Display_delete__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.URL__c',
  sfdx:Deploy     type: 'CustomField',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/fields/URL__c.field-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c',
  sfdx:Deploy     type: 'CustomObject',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/Expert_Consulting__c.object-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c-iw',
  sfdx:Deploy     type: 'CustomObjectTranslation',
  sfdx:Deploy     state: 'Changed',
  sfdx:Deploy     filePath: 'force-app/main/default/objectTranslations/Expert_Consulting__c-iw/Expert_Consulting__c-iw.objectTranslation-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.All',
  sfdx:Deploy     type: 'ListView',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/listViews/All.listView-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   },
  sfdx:Deploy   {
  sfdx:Deploy     fullName: 'Expert_Consulting__c.Prevent_Reopening',
  sfdx:Deploy     type: 'ValidationRule',
  sfdx:Deploy     state: 'Unchanged',
  sfdx:Deploy     filePath: 'force-app/main/default/objects/Expert_Consulting__c/validationRules/Prevent_Reopening.validationRule-meta.xml',
  sfdx:Deploy     height: 1
  sfdx:Deploy   }
  sfdx:Deploy ] `

**Comment by svenfinitiv** [comment]
Hi @WillieRuemmele ,

just dropping in to let you know we're also affected and could narrow down the issue exist since 7.120.0. When we use 7.110.0, the field translations (field label and picklist value labels) get deployed correctly.

We already opened a case (#41205450), because it's blocking our automated deployment pipeline.

Cheers, Sven

**Comment by WillieRuemmele** [comment]
Thanks @barouchk we'll take a look at this as quickly as we can!

Hi @svenfinitiv the `7.112.0` release had a lot of changes in it - unfortunately it didn't go as smoothly as anyone would've liked.

to unblock your pipeline you can always pin to a specific version of the sfdx cli. Either with the installers by pointing to the correct OS/version [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_olderversions.htm) or if you're using an npm install you can  `npm install sfdx-cli@7.110.0`

**Comment by svenfinitiv** [comment]
Hi @WillieRuemmele,

thanks, yes, the npm version was our manual workaround for the production deployment today and we have an eye on further translations that might need to be deployed, but didn't want to change the pipeline that much for now (we don't use npm there). Sadly, the SFDX_AUTOUPDATE_DISABLE flag is ignored (when set to true) when using the direct download and we always end up with the most recent version.

In the call with the support we discovered that using the old metadata format of the objectTranslation-meta.xml file actually worked (including the field labels there instead of the fieldTranslation-meta.xml file).

Cheers, Sven

**Comment by svenfinitiv** [comment]
Hi @WillieRuemmele ,

I tried to find the place where the mapping from the directory / file structure to metadata takes place, but didn't find it. I'm not a skilled node developer, but would try to figure something out if I just knew where to start. Can you give me a hint in which repository I would need to look?

Cheers, Sven

**Comment by WillieRuemmele** [comment]
Hi @svenfinitiv [here](https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/registry/registry.json) is where define metadata behaviors, but this bug is actually getting fixed in [this](https://github.com/forcedotcom/source-deploy-retrieve/pull/444) PR

**Comment by svenfinitiv** [comment]
Ah, that's cool, I hope it get's merged soon :)
