### ISSUE TITLE
ERROR running force:source:retrieve: Cannot read property 'id' of undefined after CLI Update to 7.113

### ISSUE THREAD

**Issue by hemantjain0206** [forcedotcom/cli#1138]
I am trying to retrieve the Salesforce metadata in VS Code with the below command,

`sfdx force:source:retrieve -x ./manifest/package.xml`
This was working fine for version 7.110, but suddenly I have started getting the below error after update to version 7.113:

`ERROR running force:source:retrieve: Cannot read property 'id' of undefined`

I have recreated the project repository and tried this again, but no success.

**Comment by WillieRuemmele** [comment]
Hi @hemantjain0206 could you run the following commands directly from a terminal and paste the output

- `sfdx plugins --core`
- add the `--dev-debug` flag to the retrieve command - this should produce a stack trace, that's all we need from this output

**Comment by hemantjain0206** [comment]
`sfdx plugins --core output`
```
oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.3 (core)
auth 1.7.1 (core)
config 1.2.23 (core)
custom-metadata 1.0.12 (core)
data 0.6.0 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.6.9 (core)
salesforce-alm 52.2.4 (core)
schema 1.0.8 (core)
sfdx-cli 7.113.0 (core)
source 1.0.7 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
user 1.4.0 (core)
```

`--dev-debug output`

`ERROR running force:source:retrieve:  Cannot read property 'id' of undefined*** Internal Diagnostic *** TypeError: Cannot read property 'id' of undefined    at ComponentSet.simpleKey (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\collections\componentSet.js:303:116)    at ComponentSet.has (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\collections\componentSet.js:237:58)    at MetadataResolver.getComponentsFromPathRecursive (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\resolve\metadataResolver.js:81:49)    at MetadataResolver.getComponentsFromPathRecursive (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\resolve\metadataResolver.js:96:37)    at MetadataResolver.getComponentsFromPathRecursive (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\resolve\metadataResolver.js:96:37)    at MetadataResolver.getComponentsFromPathRecursive (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\resolve\metadataResolver.js:96:37)    at MetadataResolver.getComponentsFromPathRecursive (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\resolve\metadataResolver.js:96:37)    at MetadataResolver.getComponentsFromPath (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\resolve\metadataResolver.js:43:25)    at Function.fromSource (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\collections\componentSet.js:67:46)    at Function.<anonymous> (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\source-deploy-retrieve\lib\src\collections\componentSet.js:95:49)Outer stack:    at Function.wrap (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\plugin-source\node_modules\@salesforce\command\node_modules\@salesforce\core\lib\sfdxError.js:171:27)    at Retrieve.catch (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\plugin-source\node_modules\@salesforce\command\lib\sfdxCommand.js:248:67)    at async Retrieve._run (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@salesforce\plugin-source\node_modules\@salesforce\command\lib\sfdxCommand.js:85:13)    at async Config.runCommand (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@oclif\config\lib\config.js:173:24)          at async SfdxMain.run (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@oclif\command\lib\main.js:27:9)    at async SfdxMain._run (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\node_modules\@oclif\command\lib\command.js:43:20)    at async Object.run (C:\Users\myusername\AppData\Local\sfdx\client\7.113.0-1159219\dist\cli.js:162:47)******`

Let me know in case more details are required. Thanks in advance

**Comment by guyberes** [comment]
Thanks for raising. Have also observed this issue.

**Comment by WillieRuemmele** [comment]
Hi @guyberes @hemantjain0206  this should be fixed in the latest-rc build of the cli 1.115.0, you can get it by either sfdx update stable-rc or npm install sfdx-cli@latest-rc --global depending on your preferred install method.

Please let us know if you're still seeing this in 1.115.0 of the CLI

**Comment by mfullmore** [comment]
Hi @WillieRuemmele `sdfx update` on my Git Bash terminal on Windows 10 is saying .114.0 is the latest. About how long does it take for 115.0 to be available?

**Comment by WillieRuemmele** [comment]
you have to specify stable-rc, `sfdx update stable-rc`

**Comment by mfullmore** [comment]
@WillieRuemmele I am not getting the error on `1.115.0` thanks for the fix.

**Comment by WillieRuemmele** [comment]
wooohoo 😄

**Comment by hemantjain0206** [comment]
Thanks @WillieRuemmele
