### ISSUE TITLE
mdapi convert is failing while processing aura folder path

### ISSUE THREAD

**Issue by bugude** [forcedotcom/cli#114]
### Summary

mdapi conversion of the retrieved package is failing.

I am in the process of extracting the metadata (via package.xml), convert into SFDX format.

I was able to retrieve the code via package.xml but encountering error at Aura folder during conversion.

### Steps To Reproduce:

1.  Authorize the Org
1.  Retrieve the metadata using package.xml
1.  unzip the extracted metadata
1.  execute mdapi:convert command of SFDX

### Expected result

The extracted metadata must be converted to SFDX project format

### Actual result

ERROR running force:mdapi:convert:  An error was encountered processing path: <Path>\Documents\VS_Code_Projects\SampleProject\mdapipkg\unpackaged\aura

### Additional information

debug log attached

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
Computer MINGW64 <Path>/VS_Code_Projects/SampleProject
$ sfdx plugins --core
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.16.0 (core)
├─ force-language-services 45.12.0 (core)
└─ salesforce-alm 45.18.0 (core)

sfdx-cli 7.8.1 (core)

**OS and version**:
Windows

[sfdx_mdapi_convert_issue.txt](https://github.com/forcedotcom/cli/files/3267251/sfdx_mdapi_convert_issue.txt)
[package.zip](https://github.com/forcedotcom/cli/files/3267253/package.zip)

**Comment by nramyasri-sf** [comment]
@bugude , please make sure to specify the rootdir as the directory that contains the metadata you retrieved, in this case it should be : mdapipkg\unpackage. Let me know if you still face issues after modifying the root dir. Thanks.

**Comment by mshanemc** [comment]
cf W-6219639
