### ISSUE TITLE
ERROR running force:source:deploy:  Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by hcr7-pge** [forcedotcom/cli#1140]
Hi All, 

For this new version of SFDX sfdx --version
sfdx-cli/7.113.0 win32-x64 node-v14.17.4

While running the deploy command we are getting this error. 

ERROR running force:source:deploy:  Cannot read property 'id' of undefined

I tried to downgrade to the lower version 7.110 and its complains about "System cannot find the path specified"

Any help will be much appreciated.

**Comment by WillieRuemmele** [comment]
Hi @hemrag07 we're already working on fixing this issue. I know that error message isn't helpful at all, but it usually indicates something is organized wrong in your project. For example, this will happen when organizing your `ApexClass`es underneath an object, like `force-app/main/default/objects/<MyObject>/classes/myApexClass.cls` I would check the following things to hopefully get you passed this issue

- project layout is correct (as mentioned above)
- run the deploy with `--json` sometimes there will be more helpful information
- check the `Deploy Status` in the Org's Setup page

**Comment by chriskarpyszyn** [comment]
I wonder if I'm getting the same error. I'm basically getting a simple error as a first error

`Variable does not exist: ret (84:6)`

Which does exist. Followed by a cascade of errors that are either signalling that a different variable does not exist or a dependent class needs recompiling. 

Strange enough `sfdx force:source:push` works fine, but deploy does not. 

Looking at the JSON output, I'm getting an error that still doesn't make sense. 

`    "details": {
      "componentFailures": {
        "changed": "false",
        "columnNumber": "66",
        "componentType": "CustomObject",
        "created": "false",
        "createdDate": "2021-08-20T18:02:05.000Z",
        "deleted": "false",
        "fileName": "objects/CustomObjectName__c.object",
        "fullName": "CustomObjectName__c",
        "lineNumber": "414",
        "problem": "Error parsing file: The entity name must immediately follow the '&' in the entity reference.",
        "problemType": "Error",
        "success": "false"
      },`
      
      My custom object XML does not have 414 lines.

**Comment by WillieRuemmele** [comment]
Hi @chriskarpyszyn I've been trying to reproduce this same error `The entity name must immediately follow the '&' in the entity reference.` for some time now. One thing I [read](https://developer.salesforce.com/forums/?id=906F000000094eOIAQ) was that changing `&` to `&amp;` might fix the problem, but haven't been able to verify it myself... does your file have a `&` in it? Can you try that fix and let me know how it goes? 

It seems like there's an issue parsing the `.xml` file somewhere, if that fix works, could you share the problem line in hopes that I can reproduce it too?

UPDATE: I created a custom object and custom field, I named the custom field `my & field`, and retrieved it. Then I ran a `force:source:convert` and then manually changed the generated `&amp;` to `&` and reproduced the error, so if this is coming from a `source:deploy` something must not be encoding that value correctly... could you set `SFDX_MDAPI_TEMP_DIR` and look at the custom object file to see what metadata type isn't correctly encoding this value

**Comment by chriskarpyszyn** [comment]
@WillieRuemmele Will do. There are no ampersands in my XML file though so I don't know why the convert might be creating it. 

EDIT: Just ran convert and it's probably tripping up on validation rules on some of my fields that have `&&` in them. I'm calling it a night but I'll come back here and update if that works.

**Comment by chriskarpyszyn** [comment]
@WillieRuemmele I was able to fix it by escaping the `&`  with `&amp` in my custom object validation rules XML files. While this is probably best practice to always escape the ampersand, this didn't fail in previous versions of the CLI.
