### ISSUE TITLE
error deploying big object indexes

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#1141]
opened a new issue on behalf of @scwells72 

I've seen this issue as well, and I've isolated it to an index on a BigObject, e.g., objects/MyBigObject/indexes/MyFieldIndex.indexe-meta.xml. 

If I remove that from my package directory, the deployment goes fine; if I add it back, it fails with TypeError - Cannot read property 'id' of undefined.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9771788](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000UO2hYAG/view)

**Comment by WillieRuemmele** [comment]
https://github.com/forcedotcom/cli/issues/1112#issuecomment-900818114

**Comment by WillieRuemmele** [comment]
Hi @SCWells72 this should be fixed in the latest-rc build of the cli 1.115.0, you can get it by either sfdx update stable-rc or npm install sfdx-cli@latest-rc --global depending on your preferred install method.

Please let us know if you're still seeing this in 1.115.0 of the CLI

**Comment by Asreepathi** [comment]
Hey Guys, I am facing similar issue. 

When i deploy the BigObject using Git Pipeline I see the following

`ERROR running force:source:deploy:  Unexpected file found in package directory: /home/runner/work/Prizm-SFS/Prizm-SFS/force-app/main/default/objects/Asset_Account__b/indexes/Account_Index.index-meta.xml`

I think Github Pipeline setup is not able to recognize index file. 
Pleas help me with this. 

Note: I am able to deploy my BigObject related code to Salesforce using VS code with no issues, but i only see above mentioned issue when i try to validate my code using Github pipeline setup via yml. 

`

**Comment by zhou059** [comment]
I'm seeing this same issue as well, same error as Asreepathi

**Comment by Asreepathi** [comment]
> I'm seeing this same issue as well, same error as Asreepathi

I fixed the issue by just renaming the file to `Account_Index.indexe-meta.xml`. 
You can append just 'e' at the end of the text -->index. (you can add any text really)
That way Github doesn't know its actually index file and our logic still works. Hope it helps

**Comment by zhou059** [comment]
that's good to know, thanks Asreepathi!
