### ISSUE TITLE
Issue with sfdx force:source:convert command.

### ISSUE THREAD

**Issue by kravuri1987** [forcedotcom/cli#1142]
### Summary
When sfdx force:source:convert command ealier version used create a metadata folder and stores converted files.
Currently it is creating files without containing in a folder and failing with this Error:ERROR running force:source:convert:  Component conversion failed: Cannot read property 'parent' of undefined.

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:
Try to convert SFDX source to metadata format version:sfdx-cli/7.113.0

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened_.

### System Information

Run `sfdx version --verbose --json` and paste the output here.

### Additional information

_Feel free to attach a screenshot_.

**Comment by WillieRuemmele** [comment]
Hi @kravuri1987 did you use the dreamhouse-lwc project to reproduce this? I know these errors are very frustrating and not helpful at all - and we're working on fixing as many as we can. 

These errors usually occur when something in your project is structured incorrectly, like putting ApexClasses under a custom object directory, or something like that. I would verify that your project is organized correctly. I would try converting different metadata types at a time to narrow it down to the problem type

**Comment by WillieRuemmele** [comment]
Hi @kravuri1987  this should be fixed in the latest-rc build of the cli 1.115.0, you can get it by either sfdx update stable-rc or npm install sfdx-cli@latest-rc --global depending on your preferred install method.

Please let us know if you're still seeing this in 1.115.0 of the CLI

**Comment by kravuri1987** [comment]
@WillieRuemmele  this issue is resolved. But when I tried to convert objects ,all the fields are getting this extra info tag: <fields xmlns="http://soap.sforce.com/2006/04/metadata">.Can you please look into this issue.

**Comment by WillieRuemmele** [comment]
I'm a confused on what the new information is. I don't believe it was transcribed in your comment. Could you please share the old and new tags?

**Comment by kravuri1987** [comment]
`Earlier it is <fields> now it is showing as <fields xmlns="http://soap.sforce.com/2006/04/metadata">`

**Comment by WillieRuemmele** [comment]
Hi @kravuri1987 thanks for getting back to me! While this is a new behavior, is this causing `mdapi:deploy` errors? Or any errors for that matter?

**Comment by kravuri1987** [comment]
@WillieRuemmele  It is not failing so far but to see the `xmlns="http://soap.sforce.com/2006/04/metadata"` for every tag it is not readable. Please Help.
For Example: 

```
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <label>Account</label>
    <fields xmlns="http://soap.sforce.com/2006/04/metadata">
  
    </fields>
    <fields xmlns="http://soap.sforce.com/2006/04/metadata">

    </fields>
    <fields xmlns="http://soap.sforce.com/2006/04/metadata">

    </fields>
</CustomObject>
```
```

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9803903](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000000smuCYAQ/view)
