### ISSUE TITLE
Error running auth:sfdxurl:store

### ISSUE THREAD

**Issue by soneill909** [forcedotcom/cli#1145]
I'm receiving the following error:

ERROR running auth:sfdxurl:store:  Invalid sfdx auth url. Must be in the format `force://<clientId>:<clientSecret>:<refreshToken>@<loginUrl>`. The instanceUrl must not have the protocol set.

I initially ran `sfdx force:org:display -u [MyOrg] --verbose --json > authFile.json` and then ran `sfdx auth:sfdxurl:store -f authFile.json` to receive the above error.

**Comment by WillieRuemmele** [comment]
Hi @soneill909 what's the output of `sfdx version --verbose`? 

I just ran 
```
 ➜  sfdx force:org:display --verbose --json > authfile.json; sfdx auth:sfdxurl:store -f authfile.json
Successfully authorized <username> with org ID <org id>
``` 
successfully.

Have you verified that that file contains the correct url, in the correct format? Is the current org authorized?

**Comment by Hazyzh** [comment]
@WillieRuemmele I encounter the same issue, here is my version info.
![image](https://user-images.githubusercontent.com/21355783/130537915-04544471-9196-48c6-a838-1df6698b36f1.png)

Actually, when I rollback npm package `sfdx-cli`'s version from 7.114.0 to 7.68.0, it will auth successfully.

![image](https://user-images.githubusercontent.com/21355783/130538049-1c7e7ede-1f94-4265-abbd-fea066cd9125.png)

**Comment by WillieRuemmele** [comment]
Hi @Hazyzh `7.68.0` is a _very_ old version of the CLI. Have you compared the generated `authFile.json`s to see if there's a difference?
