### ISSUE TITLE
force:org:list doesn't (consistently) include the namespaces for scratch orgs that have them

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#1146]
I need to have reliable access to the namespaces for orgs included in `force:org:list` (via JSON output). I've noticed that they're not included reliably for scratch orgs, though. The missing namespaces are displayed properly in `force:org:display`, in the results of `SELECT Id, NamespacePrefix FROM Organization` against that org, and in the `ScratchOrgInfo` objects in the dev hub from which the scratch org was created.

After a brief Slack discussion with @mshanemc, it sounds like the namespace prefix just needs to be propagated here:

https://github.com/salesforcecli/plugin-org/blob/3a49bbee29123c7b591bf760fa663a31809d4931/src/shared/orgListUtil.ts#L263

I haven't tested that, but if it is that simple--and hopefully safe to add--it'd be wonderful if that could be addressed in short order.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9788406](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000UhgzYAC/view)

**Comment by SCWells72** [comment]
@WillieRuemmele thanks for the SUPER fast turnaround on this! Will the change be included in this week's CLI build? If not, any ETA for when it will be available to CLI users who are on the latest build?

**Comment by WillieRuemmele** [comment]
Hi @SCWells72 yes, it's in the current `latest-rc` tag build of the cli, scheduled for promotion to latest on Thursday

**Comment by SCWells72** [comment]
@WillieRuemmele / @mshanemc 

FYI, the end result here isn't quite what I'd have expected. Before this change, non-scratch orgs would have a property called `namespacePrefix` that included the namespace. With this change, that's still the case, but for scratch orgs that property is called `namespace`. Now there are two properties that could contain the namespace for an org in the output of `force:org:list`. I'm assuming that wasn't intentional and consistency is desired?
