### ISSUE TITLE
License for binary distributions?

### ISSUE THREAD

**Issue by byjrack** [forcedotcom/cli#115]
So I am just trying to connect the binary dists of sfdxcli to an open source work which has an OSI license.  After the install I see the BSD-3 in the path (though would be nice to see that on the Download page), but just trying to connect those products to a public repo if possible.  I see sdfx-core, but was not 100% cli was based solely on that repo.

**Comment by clairebianchi** [comment]
@thejrack Would you give us more details on what you are trying to do? What download pages are you referring to specifically?

**Comment by byjrack** [comment]
https://developer.salesforce.com/tools/sfdxcli is the download page.  Not a clean map back to the OSS projects that I could find.  The BSD-3 is in the archive itself, but trying to connect the distributable to the OSS project codebase.

**Comment by mshanemc** [comment]
@byjrack the CLI is made up of a LOT of repos, some but not all of which are open source (yet)

Here's the public-facing list of ingredients 
https://github.com/salesforcecli/status

We'd like to get them all into the open.  Here's a blog about the process, which has more background.
https://developer.salesforce.com/blogs/2021/02/open-sourcing-salesforce-cli-update-feb-2021.html
