### ISSUE TITLE
Different SFDX Report Outcomes

### ISSUE THREAD

**Issue by MGarfOppLoans** [forcedotcom/cli#1152]
### Summary

Running `sfdx force:source:deploy` provides different outcomes

### Steps To Reproduce:

Run `sfdx force:source:deploy` in nodejs with execSync with a broken (Create a uncompilable apex class and attempt to deploy it. In the following scenarios

In Windows 10  use `sfdx-cli/7.94.3-a4e7c7955b win32-x64 node-v14.15.4`  (running sfdx update says its the latest version)

In Github Actions use `sfdx-cli/7.114.0 linux-x64 node-v14.17.1` or docker image `salesforce/salesforcedx:latest-full`

In windows it throws a javascript error (sends a error signal in exec) and you have to process the outcome in stdout. In Github Actions no error is thrown and you process it in stdout. These should be identical and one of these outcomes is a bug.

### Sample Nodejs Script

```
const util = require('util');
const { execSync, exec } = require('child_process');
const execAwait = util.promisify(exec);

(async () => {
    console.log('a');
    try {
        await execAwait('sfdx force:source:deploy -p force-app');
    } catch (e) {
        console.log('e');
    }
    console.log('b');

    try {
        const { stdout, stderr } = await execAwait('sfdx force:source:deploy:report --json')
        console.log('aa')
        console.log(stdout);
        console.log('bb');
        console.log(stderr);
        console.log('cc');
    } catch (e) {
        console.log('ee');
        // console.log(e);
        if (e.stdout && e.stdout.startsWith('{')) {
            console.log(JSON.parse(e.stdout));
        }
        console.log('ee2');
    }
})()
```

**Comment by WillieRuemmele** [comment]
Hi @MGarfOppLoans what's the output of `sfdx version --verbose` on the windows machine? `7.114.0` is the latest release of the CLI. This can happen when you pin a specific plugin, the command above will tell us that. You might have to uninstall/reinstall the CLI to get onto the newer version

**Comment by MGarfOppLoans** [comment]
that just returns `sfdx-cli/7.94.3-a4e7c7955b win32-x64 node-v14.15.4` 

ran `sfdx plugins` and it spit out

@oclif/plugin-autocomplete 0.3.0
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-scanner 2.11.0
evergreen 0.34.0
└─ evergreen-build 0.20.2

**Comment by MGarfOppLoans** [comment]
This is what happens when i run update
```
sfdx-cli: Updating CLI... already on latest version: 7.94.3-a4e7c7955b
warning "@salesforce/lwc-dev-server > @rollup/plugin-alias@3.1.1" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
warning "@salesforce/lwc-dev-server > request-promise-native@1.0.8" has unmet peer dependency "request@^2.34".       
warning "@salesforce/lwc-dev-server > request-promise-native > request-promise-core@1.1.3" has unmet peer dependency "request@^2.34".
sfdx-cli: Updating plugins... done
```

**Comment by WillieRuemmele** [comment]
can you run `sfdx version --verbose` it's a different command with more information

**Comment by mshanemc** [comment]
it's caused by a bug in `lwc-dev-server` that keeps the CLI on a super old version.  Try uninstalling that and then updating?

**Comment by shetzel** [comment]
@MGarfOppLoans - Please reopen if you are still seeing an issue with the latest CLI.
