### ISSUE TITLE
SFDX force:source:pull command is not pulling initialSubmissionActions from scratch orgs

### ISSUE THREAD

**Issue by jayherman** [forcedotcom/cli#1157]
### Summary

When entering Initial Submission Actions in an Scratch Org's Approval Process, the sfdx force:source:pull command is not pulling the initialSubmissionActions information down for the *.approvalProcess-meta.xml file.

### Steps To Reproduce:

1.  Create a scratch org.
2.  Create an approval process on any object in Salesforce. 
2.  Add an Initial Submission Action like a field update. 
3.  Save the approval process. 
4.  Use sfdx force:source:pull to pull the meta data.

### Expected result

The *.approvalProcess-meta.xml should have a section for initialSubmissionActions, like so: 

```
<initialSubmissionActions>
    <action>
        <name>Update_Name</name>
        <type>FieldUpdate</type>
    </action>        
</initialSubmissionActions>
```

### Actual result

The initialSubmissionActions section is missing from the metadata.

### System Information

sfdx-cli/7.94.3-a4e7c7955b win32-x64 node-v14.15.4

### Additional information

Creating the section manually is a valid workaround.

**Comment by mshanemc** [comment]
I followed your steps and got this result from those steps (using an email alert).  What type of submission action did you use?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ApprovalProcess xmlns="http://soap.sforce.com/2006/04/metadata">
    <active>false</active>
    <allowRecall>false</allowRecall>
    <allowedSubmitters>
        <type>owner</type>
    </allowedSubmitters>
    <approvalPageFields>
        <field>Name</field>
        <field>Owner</field>
    </approvalPageFields>
    <approvalStep>
        <allowDelegate>false</allowDelegate>
        <assignedApprover>
            <approver>
                <name>test-fjelowob6amr@example.com</name>
                <type>user</type>
            </approver>
            <whenMultipleApprovers>FirstResponse</whenMultipleApprovers>
        </assignedApprover>
        <label>Step 1</label>
        <name>Step_1</name>
    </approvalStep>
    <enableMobileDeviceAccess>false</enableMobileDeviceAccess>
    <finalApprovalRecordLock>true</finalApprovalRecordLock>
    <finalRejectionRecordLock>false</finalRejectionRecordLock>
    <initialSubmissionActions>
        <action>
            <name>Test</name>
            <type>Alert</type>
        </action>
    </initialSubmissionActions>
    <label>Test</label>
    <processOrder>0</processOrder>
    <recordEditability>AdminOnly</recordEditability>
    <showApprovalHistory>true</showApprovalHistory>
</ApprovalProcess>
```
<img width="1504" alt="Screen Shot 2021-09-27 at 10 52 18 AM" src="https://user-images.githubusercontent.com/4261788/134942505-2bcd6057-8043-45cc-87f4-b096dc362174.png">

I'm also on a more recent CLI, which might be worth trying.
