### ISSUE TITLE
Restriction Rules not supported in Source format

### ISSUE THREAD

**Issue by jhawk-4** [forcedotcom/cli#1158]
### Summary

We are trialing Restriction Rules (beta in v52.0).  The metadata coverage report indicates that this metadata is supported both the Metadata API and Source Tracking.  When attempting to convert from source format to mdapi format, the metadata is treated as a `ModerationRule` instead of `RestrictionRule`.

### Steps To Reproduce:

**Repository to reproduce:** [Sample Repo](https://github.com/jhawk-4/restriction-rules)

1.  Clone the sample repo
1.  run `sfdx force:source:convert -d ./mdapi`

### Expected result

Source is converted to metadata API format with a `restrictionRules` folder and the `package.xml` should reference the `RestrictionRule` metadata type.

### Actual result

Source is converted to metadata API format with a `moderation` folder instead of `restrictionRules`. The `package.xml` file also defines the metadata type as `ModerationRule` instead of `RestrictionRule`.

### System Information

```json
{
        "cliVersion": "sfdx-cli/7.114.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v14.17.5",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-diff 0.0.6",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.7 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.23 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.0 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.6.9 (core)",
                "salesforce-alm 52.2.5 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.114.0 (core)",
                "source 1.0.9 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Darwin 20.5.0"
}
```

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9833678](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000002gvDnYAI/view)

**Comment by shetzel** [comment]
Super easy fix.  Should be in the next CLI release candidate.

Edit: Also, thanks for the repo and all the details.  That definitely contributed to the speed of the fix.  👍
