### ISSUE TITLE
Separate each Custom Label entry on its own file when working with the "Source" format

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1159]
**Is your feature request related to a problem? Please describe.**
Yes, it is really hard to track changes in the Custom Labels metadata file while reviewing PRs in any Git tool. It is hard to read changes in XML files in general.

**What are you trying to do**
Achieve better DX by improving the way we track changes to Custom Labels in GIT tools. This will reduce errors and will cut down time while reviewing PRs with Custom Labels changes.

**Describe the solution you'd like**
Separate each Custom Label entry on its own file when working with the "Source" format

This

````xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomLabels xmlns="http://soap.sforce.com/2006/04/metadata">     
    <labels>
        <fullName>MyLabelApiName1</fullName>
        <categories>Community</categories>
        <language>en_US</language>
        <protected>false</protected>
        <shortDescription>MyLabelApiName1</shortDescription>
        <value>MyLabelApiName1</value>
    </labels>
    <labels>
        <fullName>MyLabelApiName2</fullName>
        <categories>Community</categories>
        <language>en_US</language>
        <protected>false</protected>
        <shortDescription>MyLabelApiName2</shortDescription>
        <value>MyLabelApiName2</value>
    </labels>
</CustomLabels>
````

Would become something like this

![image](https://user-images.githubusercontent.com/55927613/131338949-6574341b-6f8b-4482-a23b-1cc90983364c.png)

**Describe alternatives you've considered**

Right now every developer is appending new labels to the end of the file to make PR reviews easier and faster. This way we can clearly see what has been changed while reviewing PRs.

**Additional context**
It is impossible to review PRs when working with packages, such as Vlocity, that creates an enourmous number of Custom Labels. Git shows some labels were removed just because they moved down some lines, which is not true. This can lead to lots of errors.

![image](https://user-images.githubusercontent.com/55927613/131339942-676fefd3-619e-4bda-8768-0ff681e15d28.png)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9830776](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000002ZTIwYAO/view)

**Comment by AllanOricil** [comment]
@mshanemc 
couldn't this be a built in pre deploy|push|versio creation|retrieve hook in sfdx?
Sfdx could support separate xml files for each label when working with the source format. And before running any of those commands, sfdx would create a "CustomLabels.xml" joining the separate files that are in the labels folder. When retrieving custom labels, sfdx would retrieve it as a whole, and then break it into separate files, one for each custom label.


Custom Labels are versioned as separate files

````shell
labels
    a.xml
    b.xml
````

While running sfdx comamnds, the CustomLabels.xml file would be generated joining a.xml and b.xml files

````shell
labels
    CustomLabels.xml
`````

**Comment by AllanOricil** [comment]
This can help to avoid mistakes when reviewing diffs in xml files
https://marketplace.visualstudio.com/items?itemName=semanticdiff.semanticdiff

**Comment by mshanemc** [comment]
Related discussion: https://github.com/forcedotcom/cli/discussions/2544

**Comment by AllanOricil** [comment]
Turns out this became a feature 😄
I have good ideas sometimes 😌
