### ISSUE TITLE
sfdx force:source:retrieve --manifest  xxx error

### ISSUE THREAD

**Issue by aitiancai** [forcedotcom/cli#116]
Starting SFDX: Retrieve Source from Org

14:27:51.109 sfdx force:source:retrieve --manifest c:\soft\vs\poj\XinAn2\manifest\package.xml
ERROR running force:source:retrieve:  The "path" argument must be of type string. Received type undefined
14:28:25.667 sfdx force:source:retrieve --manifest c:\soft\vs\poj\XinAn2\manifest\package.xml ended with exit code 1

sfdx version
sfdx-cli/7.8.1-8f830784cc win32-x64 node-v10.15.3

![image](https://user-images.githubusercontent.com/26561757/59479246-d87bc100-8e8e-11e9-8740-5b4c89400b54.png)
![image](https://user-images.githubusercontent.com/26561757/59479266-f812e980-8e8e-11e9-87b9-c3450d17dea3.png)

**Comment by aitiancai** [comment]
sfdx version
sfdx-cli/7.8.1-8f830784cc win32-x64 node-v10.15.3

**Comment by nramyasri-sf** [comment]
@aitiancai , would be able to provide a few more details eg: the metadata types you are attempting to retrieve or if possible provide the project/package.xml so we can further take a look. Thank you.

**Comment by shetzel** [comment]
Please retest with the latest CLI.  This should be fixed.  If it's still broken please reopen.
