### ISSUE TITLE
Error when creating scratch org

### ISSUE THREAD

**Issue by calvinle1** [forcedotcom/cli#1160]
### Summary

Error thrown when attempting to create a scratch org, appearing as of this morning.

### Steps To Reproduce:

1.  Executing: sfdx force:org:create -f config/project-scratch-def.json -a 'ScratchOrg' -v 'DevHub' -d 1

### Expected result

Scratch org is created successfully

### Actual result

Error is thrown:

npx sfdx force:org:create -f config/project-scratch-def.json -a 'ScratchOrg' -v 'DevHub' -d 1
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/6c28d0a9-4acd-4c4c-bfdf-0a465d8ed7bb.sh
    Error: Cannot find module 'lodash'
    Require stack:
    - /home/vsts/work/1/s/node_modules/@oclif/core/lib/config/config.js
    - /home/vsts/work/1/s/node_modules/@oclif/core/lib/config/index.js
    - /home/vsts/work/1/s/node_modules/@oclif/core/lib/command.js
    - /home/vsts/work/1/s/node_modules/@oclif/core/lib/index.js
    - /home/vsts/work/1/s/node_modules/salesforce-alm/node_modules/@salesforce
    /command/lib/exported.js
    - /home/vsts/work/1/s/node_modules/salesforce-alm/dist/commands/force/org/
    create.js
    - /home/vsts/work/1/s/node_modules/@oclif/config/lib/plugin.js
    - /home/vsts/work/1/s/node_modules/@oclif/config/lib/config.js
    - /home/vsts/work/1/s/node_modules/@oclif/config/lib/index.js
    - /home/vsts/work/1/s/node_modules/@oclif/command/lib/command.js
    - /home/vsts/work/1/s/node_modules/@oclif/command/lib/index.js
    - /home/vsts/work/1/s/node_modules/sfdx-cli/dist/cli.js
    - /home/vsts/work/1/s/node_modules/sfdx-cli/bin/run
    Code: MODULE_NOT_FOUND

### System Information

SFDX Version: 7.115.1

### Additional information

_Feel free to attach a screenshot_.

**Comment by maggiben** [comment]
Hi, this is a very weird error, maybe an incomplete of corrupt installation ? 
Can you try upgrading to the `latest-rc` to see if this error still continues ? `npm install -g sfdx-cli@latest-rc`

**Comment by mshanemc** [comment]
@calvinle1 I think this may have been related to some of the problems from `sf`

https://github.com/forcedotcom/cli/issues/1174 and/or
https://github.com/forcedotcom/cli/issues/1175 

Any chance you can try this with version `7.118.1` which works in those scenarios?  We definitely haven't tested using npx like that.
