### ISSUE TITLE
Unknown type CustomFieldTranslation when retrieving and deploying CustomObjectTranslation metadata

### ISSUE THREAD

**Issue by colin-jarvisSFDC** [forcedotcom/cli#1161]
### Summary

Unknown type CustomFieldTranslation when retrieving and deploying CustomObjectTranslation metadata.

### Steps To Reproduce:

1.  Customize standard field labels for account field.
1.  Attempt to retrieve custom object translations using `sfdx force:source:retrieve -m CustomObjectTranslation`.
1.  Attempt to deploy existing sources using `sfdx fource:source:deploy -p force-app/main/default/objectTranslations`.

### Expected result

No error.

### Actual result

Error during retrieval:

```
FILE NAME               PROBLEM
──────────────────────  ────────────────────────────────────────────────
unpackaged/package.xml  Entity type: 'CustomFieldTranslation' is unknown
```

Fatal error during deployment:

> Unknown type name 'CustomFieldTranslation' specified in package.xml

![Screen Shot 2021-09-01 at 2 24 43 PM](https://user-images.githubusercontent.com/1087625/131723895-32f8b4a2-cb58-4236-99d0-6ed0e0e49144.png)

### System Information

```
{
        "cliVersion": "sfdx-cli/7.115.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.1.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.7 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.24 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.0 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.1 (core)",
                "org 1.7.0 (core)",
                "salesforce-alm 52.2.6 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.115.1 (core)",
                "sfdx-manifest-plugin 0.0.0 (link) /Users/colin.jarvis/code/sfdx/plugins/manifest",
                "source 1.0.10 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Darwin 20.6.0"
}
```

**Comment by maggiben** [comment]
Hi it's a known bug, we've a PR for it should be out in out next rc release

**Comment by shetzel** [comment]
This PR to the SDR library fixes the issue.  A new version of the source plugin will be published  later today that consumes this fix.
https://github.com/forcedotcom/source-deploy-retrieve/pull/444

**Comment by Raspikabek** [comment]
I've been able to workaround this issue using a previous version like 7.114.0

**Comment by grand-wazoo** [comment]
So I've been having this issue since version 115 came out last Thursday. Created a lot of churn for us. I downgraded to CLI version 114 and 112 and I was still seeing this issue, so I thought it was a salesforce problem, but it does look like its a CLI thing after all. Why does downgrade not work?

This is sfdx version (downgraded):
PS C:\SRC\Exam_Component> sfdx --version
sfdx-cli/7.112.0 win32-x86 node-v14.17.5

I am running this command:

sfdx force:source:deploy -p force-app\main\default --targetusername XXX --wait 20

I get this error:

changed : false
componentType :
created : false
createdDate : 2021-09-01T19:51:05.000Z
deleted : false
fileName : package.xml
fullName :
problem : Unknown type name 'CustomFieldTranslation' specified in package.xml
problemType : Error
success : false

**Comment by colin-jarvisSFDC** [comment]
I kinda figured the bug was introduced by one of the npm dependencies being upgraded.  I downgraded to 7.114.0 and that didn't help, but when I switched to an older installation that was 7.114.0 that had never been upgraded, it worked.

**Comment by grand-wazoo** [comment]
That's what I thought too, but couldn't find the culprit. Downgraded to version 112, hoping that would surely downgrade the dependencies too, but no dice. OK, will test today's build, when it comes out

**Comment by grand-wazoo** [comment]
Looks like 7.116.2 has fixed this, as promised. Thx

**Comment by trentchilders** [comment]
We are still seeing this issue on our deployments. CLI is using 7.116.2. Anyone else?

**Comment by dxenonb** [comment]
I am seeing this too still, with `7.116.2` and `7.115.1`.

This was not an issue for me on `7.112.1-b99fa53`.

**Comment by colin-julien** [comment]
The issue is still there with the `7.116.2`

**Comment by colin-jarvisSFDC** [comment]
This is fixed for me with 7.116.2 as well.  Not sure why others are still having reporting the same issue.

**Comment by thomasminney** [comment]
I am still seeing this on `7.116.2` with force:source and force:mdapi deployment commands:
- `sfdx force:source:deploy -m CustomFieldTranslation` (payload error Unknown type name 'CustomFieldTranslation' specified in package.xml)
- `sfdx force:source:convert -m CustomFieldTranslation` && `sfdx force:mdapi:deploy -d metadataPackage_1630915926740` (payload error Unknown type name 'CustomFieldTranslation' specified in package.xml)
-  `sfdx force:source:deploy -p force-app/main/default/objectTranslations` (fatal error Unknown type name 'CustomFieldTranslation' specified in package.xml)

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.8 (core)
auth 1.7.1 (core)
config 1.2.24 (core)
custom-metadata 1.0.12 (core)
data 0.6.1 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.7.0 (core)
salesforce-alm 52.3.1 (core)
schema 1.0.8 (core)
sfdx-cli 7.116.2 (core)
source 1.0.12 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
user 1.4.0 (core)

**Comment by thvd** [comment]
Same here with 7.116.2, still broken:

```json
{
	"cliVersion": "sfdx-cli/7.116.2",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v14.17.5",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.2 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.4.0-3 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"@salesforce/sfdx-trust 3.6.0 (core)",
		"alias 1.1.10 (core)",
		"apex 0.2.8 (core)",
		"auth 1.7.1 (core)",
		"config 1.2.24 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.1 (core)",
		"generator 1.1.7 (core)",
		"limits 1.2.1 (core)",
		"org 1.7.0 (core)",
		"salesforce-alm 52.3.1 (core)",
		"schema 1.0.8 (core)",
		"sfdx-async-alert-plugin 0.0.0 (link) /Users/theodoorvandonge/workspace/sfdx-async-alert-plugin",
		"sfdx-cli 7.116.2 (core)",
		"source 1.0.12 (core)",
		"telemetry 1.2.3 (core)",
		"templates 52.1.0 (core)",
		"user 1.4.0 (core)"
	],
	"osVersion": "Darwin 20.6.0"
}
```

Can we reopen? Or create a new issue?

**Comment by ZboiiZammy** [comment]
We have the same issue! with 7.116.2

Need a fix asap :(

**Comment by colin-jarvisSFDC** [comment]
@cristiand391
Can this be re-opened?  Several users are reporting that the problem is not fixed for them.

**Comment by mbilalkhawar** [comment]
We are also facing the same issue - it doesn't appear to be fixed yet.
We are currently using 7.114.0 version as it appears to be stable and doesn't throw the fatal error.

**Comment by kauravmayur** [comment]
We are also facing same issue(**Unknown type name 'CustomFieldTranslation' specified in package.xml**)

Currently using **sfdx-cli/7.116.2 win32-x64 node-v14.17.5** version

**Comment by togu09** [comment]
Also seeing this issue, running 7.116.2

**Comment by terry-ward-sasktel** [comment]
Also seeing this issue with 7.116.2.  Tried working around with older versions as far back as 7.110.0 but no luck.

**Comment by mshanemc** [comment]
fixed in yesterday's release (hopefully...if not, let us know!)

**Comment by terry-ward-sasktel** [comment]
I've found this to only partially be resolved with 7.117.0.  I continue to to get the "Unknown type CustomFieldTranslation when retrieving and deploying CustomObjectTranslation metadata" error when deploying via mdapi deploy.  It works without issue if I deploy as source.

**Comment by shetzel** [comment]
@terryward1520 - the mdapi commands would be a different issue as those are still in the salesforce-alm plugin, not the source plugin (`sfdx which force:mdapi:deploy`).  However, what is the exact command you're using and the manifest contents?  If your manifest has a CustomFieldTranslation entry then it would cause this error too.  CustomFieldTranslation is not individually supported by the metadata API.

**Comment by bruno-force** [comment]
Facing the same issue on version: 7.117.0-b5a8ac9
Using sfdx force:source:retrieve/deploy

**Comment by amazipangu** [comment]
I had the same problem.
