### ISSUE TITLE
Deploying all Settings metadata type produces error "Cannot specify the wild card and specific Settings entities together in the manifest."

### ISSUE THREAD

**Issue by aheber** [forcedotcom/cli#1163]
It seems the SDR library is creating an invalid package.xml file when deploying all of the Settings metadata type. Including both `<members>*</members>` and another specific member, such as `<members>Org</members>` produces this error in deploy "Cannot specify the wild card and specific Settings entities together in the manifest."

If you take a clean project, create a fresh scratch org, retrieve the Org Settings (`sfdx force:source:retrieve -m Settings:Org`), and deploy all settings back (`sfdx force:source:deploy -m Settings`) then the erroneous wildcard entry is added.

This seem to be included as a catch-all and I didn't see this behavior when I was using the beta version of the plugin. (I recently updated our deployment environments that build scratch orgs). I have no idea how many other Metadata Types might have this limitation.

* As a note, I tried to pull the library onto my machine and get setup to build a PR. Trying to `npm install` appears to fail due to being unable to resolve dependency versions. Aside from that I'm on Windows and the package commands don't appear to be Windows friendly.

`sfdx-cli/7.115.1 win32-x64 node-v14.17.5`

```
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.7 (core)
auth 1.7.1 (core)
config 1.2.24 (core)
custom-metadata 1.0.12 (core)
data 0.6.0 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.7.0 (core)
salesforce-alm 52.2.6 (core)
schema 1.0.8 (core)
sfdx-cli 7.115.1 (core)
sfdx-devops 0.4.3
sfdx-heber 0.0.2
sfdx-typegen 0.6.2
sfpowerkit 3.2.2
shane-sfdx-plugins 4.43.0
├─ @mshanemc/plugin-streaming 1.1.7
└─ @mshanemc/sfdx-sosl 1.1.0
source 1.0.10 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
user 1.4.0 (core)
```

**Comment by shetzel** [comment]
@aheber - this could be a recent regression with the SDR library.  I think for most types this doesn't matter but for settings it does.  I'll try to clean this up with some current work in progress I have but also create a separate issue for tracking.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9852745](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000003hFIDYA2/view)

**Comment by aheber** [comment]
Thank you!

**Comment by shetzel** [comment]
This is fixed now.  Thanks @aheber!
