### ISSUE TITLE
Cannot find module '@salesforce/source-deploy-retrieve' while using salesforce/salesforcedx:latest-slim docker image

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/cli#1166]
### Summary

Our CI is using the salesforce/salesforcedx:latest-slim docker image, and today the build started to fail with the error `Cannot find module '@salesforce/source-deploy-retrieve'`:    

![image](https://user-images.githubusercontent.com/2465122/132018933-b40f0138-5477-4cd3-9905-6b7927db64bf.png)

### Steps To Reproduce:

* Create a CI config that runs on the salesforce/salesforcedx:latest-slim docker image
* Run a `sfdx force:source:deploy` command

### Expected result

The source commands should work.

### Actual result

We're getting a `Cannot find module '@salesforce/source-deploy-retrieve'` error.

**Comment by cristiand391** [comment]
@FabienTaillon Thanks for reporting!

This is a known bug in `v7.116.0`, we released `v7.116.2` shortly after we noticed it but it seems our docker images didn't get the hotfix release.

While we update our docker images, you can switch to `salesforce/salesforcedx:7.117.0-slim` which should work.

**Comment by Dhanielk** [comment]
Hi @cristiand391, would it be possible for such errors to throw Exit 1 or complete JSON status? Since we have CI deployment setup on this and it completely flew under our radar, because pipelines were reporting success.

We have switched to docker image, because somehow CLI update took unnecessary too long (reason unknown).

**Comment by cristiand391** [comment]
@Dhanielk yes, it does return exit code 1:
```
➜  ~ docker run -it salesforce/salesforcedx:7.116.0-slim bash
root@dcbb6f5252a0:/# sfdx force:source:deploy
    Error: Cannot find module '@salesforce/source-deploy-retrieve'
    Require stack:
    - /usr/local/sfdx/node_modules/@salesforce/plugin-source/lib/commands/force/source/deploy.js
    - /usr/local/sfdx/node_modules/@oclif/config/lib/plugin.js
    - /usr/local/sfdx/node_modules/@oclif/config/lib/config.js
    - /usr/local/sfdx/node_modules/@oclif/config/lib/index.js
    - /usr/local/sfdx/node_modules/@oclif/command/lib/command.js
    - /usr/local/sfdx/node_modules/@oclif/command/lib/index.js
    - /usr/local/sfdx/dist/cli.js
    - /usr/local/sfdx/bin/run
    Code: MODULE_NOT_FOUND
root@dcbb6f5252a0:/# echo $?
1
root@dcbb6f5252a0:/#
```

When using the `--json` flag the exit code is included in the output for all commands but since this was an issue with npm dependencies `sfdx` failed before even processing json output.

**Comment by maggiben** [comment]
Hi, if you don't want to pin to a specific version but want to try the rc `v7.117.0` pull the latest-rc docker image: `docker pull salesforce/salesforcedx:latest-rc-slim`

**Comment by Dhanielk** [comment]
@cristiand391 I see. Since we're piping it directly to JQ, Pipelines doesn't registered it as failure.

Thanks!

**Comment by mshanemc** [comment]
@FabienTaillon is this still happening after yesterday's release?
