### ISSUE TITLE
7.116.2 force:package:install:  Can’t install package install key

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#1167]
### Summary

Starting in 7.116.2, if an install key is provided but not needed (package does not require a key) it now fails to install with error:

`Can’t install package. This package doesn’t require an installation key. Install the package without specifying an installation key.: Password`

This is a problem for us as our packages depend on a bunch of other packages, some require a key and others are from the app exchange and do not. Our scratch org setup scripts and CI scripts automatically install all dependencies specified in the sfdx-project.json file using a single install key. Now our script to do this will need to be updated to be much more manual by requiring targeting the key only to the packages that need it.

### Steps To Reproduce:

1.  Get the version Id of a managed or unlocked package that does not require an install key
1.  Run `sfdx force:package:install --package "${packageIdentifier}" -k "${installKey}"`

### Expected result

Package to install like it did in previous versions

### Actual result

`Can’t install package. This package doesn’t require an installation key. Install the package without specifying an installation key.: Password`

### System Information

{
        "cliVersion": "sfdx-cli/7.116.2",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v14.17.5",
        "pluginVersions": [
                "@mavens/mic-cli-plugin 9.0.0-0 (link) /Users/kaiamundsen/workspace/MedInfoCloud-CLI-Plugin",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.8 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.24 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.7.0 (core)",
                "salesforce-alm 52.3.1 (core)",
                "schema 1.0.8 (core)",
                "sfdmu 3.10.5 (3.10.5)",
                "sfdx-cli 7.116.2 (core)",
                "source 1.0.12 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Darwin 20.6.0"
}

**Comment by mshanemc** [comment]
The packaging owns the packaging commands, and they don't take issues on github.  You'll probably need to open a real support case.

[advice: you probably want to redo your scripts.]
