### ISSUE TITLE
Metadata API request failed: read ECONNRESET

### ISSUE THREAD

**Issue by IVerkhosh** [forcedotcom/cli#1169]
### Summary

Running sfdx force:source:retrieve ended with "Error: read ECONNRESET"

### Steps To Reproduce:

1. Execute - sfdx force:source:retrieve -x ./manifest/PACKAGE_FILES/Reports_package.xml

### Expected result

All reports in the package.xml file retrieved from the sandbox.

### Actual result
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
ERROR running force:source:retrieve:  Metadata API request failed: read ECONNRESET
### System Information

{
        "cliVersion": "sfdx-cli/7.116.2",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.17.5",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.8 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.24 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.7.0 (core)",
                "salesforce-alm 52.3.1 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.116.2 (core)",
                "source 1.0.12 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.18363"
}

### Additional information

sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.8 (core)
auth 1.7.1 (core)
config 1.2.24 (core)
custom-metadata 1.0.12 (core)
data 0.6.1 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.7.0 (core)
salesforce-alm 52.3.1 (core)
schema 1.0.8 (core)
sfdx-cli 7.116.2 (core)
source 1.0.12 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
user 1.4.0 (core)

**Comment by IVerkhosh** [comment]
I got the similar error today 3 times in a row.
C:\GIT_REPOS\ENERGY_SFDX>sfdx force:source:retrieve -x ./manifest/PACKAGE_FILES/Reports_package.xml
Error: socket hang up
    at connResetException (internal/errors.js:628:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}
ERROR running force:source:retrieve:  Metadata API request failed: socket hang up

**Comment by JohanJohanson** [comment]
I am encoutering similar issues here also using a package.xml. But I'm getting the issues for deployment.
`sfdx force:source:deploy -u <env> -x <foo/bar/foobar.xml>`

### Version info 
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.4 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 1.1.22 (core)
apex 0.3.0 (core)
auth 1.7.5 (core)
config 1.2.41 (core)
custom-metadata 1.0.12 (core)
data 0.6.4 (core)
generator 1.2.1 (core)
limits 1.2.2 (core)
org 1.9.0 (core)
salesforce-alm 53.1.2 (core)
schema 1.0.10 (core)
sfdx-cli 7.125.0 (core)
sfdx-git-delta 4.9.1
source 1.3.1 (core)
telemetry 1.2.8 (core)
templates 52.4.0 (core)
trust 1.0.11 (core)
user 1.5.2 (core)

### Additional Info
Error: socket hang up
    at connResetException (internal/errors.js:628:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}

**Comment by shetzel** [comment]
This is the error you'll see with network connection interruptions server hangups and as long as the CLI returns an exit code of non-zero it is behaving as expected.

The only thing the CLI can do is introduce retry logic when this happens.  We have an item in our backlog to address this but it's not a simple feature and requires multiple low-level libraries being swapped out.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10216902](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000RfrtiYAB/view)

**Comment by stoevie** [comment]
Hello, it would be nice if the retry functionality is included in the tool. In recent weeks I have seen this message appear more often in combination with sfdx force:source:deploy within our ci-cd environment.

**Comment by thvd** [comment]
We see this happening daily on our build environment on Azure Devops.

**Comment by arafesthain** [comment]
Same thing here, I can see this error multiple time a day (Azure DevOps and locally)

**Comment by robgoodberry** [comment]
We are also seeing this in our CI/CD.

**Comment by shetzel** [comment]
**UPDATE:**
Upon connection errors the most recent CLI (7.135.0) will retry for these commands:

1. force:source:deploy
2. force:source:deploy:report
3. force:source:retrieve
4. force:source:beta:push
5. force:source:beta:pull
6. force:mdapi:beta:deploy
7. force:mdapi:beta:deploy:report
8. force:mdapi:beta:retrieve
9. force:mdapi:beta:retrieve:report
10. force:org:beta:create (in the release candidate available later today, 1/27/2022)

Please try the beta commands as they will soon have the `beta` topic removed and the non-beta versions will have a `legacy` topic added.

**Comment by jmccotter** [comment]
Is there any plan to implement the retry logic for the legacy push command?  The connection errors are a significant hinderance in our development process on our large package that requires multiple pushes.  We figured out how to do multiple pushes and keep the source tracking intact, but that does not work with the beta push source tracking because it is unable to handle pushing fieldsets or other object metadata in an object folder in later pushes without redeploying the object-meta.xml file.  Are the source tracking and connection tolerance issues inextricably linked or was it just decided to abandon fixes for the legacy push command?

**Comment by mshanemc** [comment]
> Is there any plan to implement the retry logic for the legacy push command?

@jmccotter no, we can't fix this in the legacy:push command.  We *would* like issues opened about anything that's preventing you from using the new push command!

**Comment by mshanemc** [comment]
Closing--this is resolved in the new versions of these commands.
