### ISSUE TITLE
Unable to deploy with package.xml

### ISSUE THREAD

**Issue by NYGman98** [forcedotcom/cli#117]
I am unable to deploy to my salesforce sandbox using package.xml. This is how I am attempting to deploy to my sandbox:
![Capture](https://user-images.githubusercontent.com/24832599/59456269-980f3b00-8ddb-11e9-886f-d01f4b54710d.PNG)

This is my version:
![Capture](https://user-images.githubusercontent.com/24832599/59456332-b8d79080-8ddb-11e9-999f-200119fbde38.PNG)

And finally this is what my package.xml looks like
![Capture](https://user-images.githubusercontent.com/24832599/59456377-d0167e00-8ddb-11e9-85d7-187179af3e12.PNG)

**Comment by mshanemc** [comment]
closed 1/15/2020 cf W-6236577
