### ISSUE TITLE
sfdx force:mdapi:deploy - unhandled rejection TypeError: Cannot read property 'result' of null

### ISSUE THREAD

**Issue by Salesforce-JK** [forcedotcom/cli#1172]
### Summary

When calling CLI from our CI server for validation we receive after 20 minutes an error
Unhandled rejection TypeError: Cannot read property 'result' of null
10:35:11       at /usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/api/metadata.js:53:16
10:35:11       at tryCallOne (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/promise/lib/core.js:37:12)
10:35:11       at /usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/promise/lib/core.js:123:15
10:35:11       at flush (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/asap/raw.js:50:29)
10:35:11       at processTicksAndRejections (internal/process/task_queues.js:79:11)

### Steps To Reproduce:

we just call sfdx force:mdapi:deploy --wait -1 --deploydir ./src --checkonly

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

### Expected result

job should end with success of error based on validation result

### Actual result

job never ends, even the deploy is finished

### System Information

Run `sfdx version --verbose --json` and paste the output here.

### Additional information

![image](https://user-images.githubusercontent.com/57418531/132194870-091c45b1-2c54-4a67-8b9a-2ddc755f50eb.png)

**Comment by maggiben** [comment]
Hi, can you please post the output of `sfdx version --verbose --json` and also try a deploy with the flag `--dev-debug` and paste the output here ?

**Comment by Salesforce-JK** [comment]
I am sorry you can close it, actually moving on latest version seems solved
my issue.

**Comment by mshanemc** [comment]
thank you!
