### ISSUE TITLE
Give clearer indication of which component is causing error on deploy

### ISSUE THREAD

**Issue by britishboyindc** [forcedotcom/cli#118]
**Is your feature request related to a problem? Please describe.**
I am deploying several LWC via SFDX in a single push. One has an error in the markup - and the error I get is this:
LightningComponentBundle/null: ERROR at line 1, column 1 - LWC1078: <p> has no matching closing tag.

**What are you trying to do**
Identify which component is causing the error, since there are several in the push

**Describe the solution you'd like**
In other circumstances, I get shown the name of the file/component throwing the error - but in this case, I have to look through all my components to find the one at fault. And in the case of this error, the markup is technically correct, but LWC is not allowing it, so the code editor is not flagging the bad markup for me

**Describe alternatives you've considered**
The only option right now is to comment out code in each component until you can track down the one at fault

**Additional context**
Full error message:
Pushed 0/2 components to ebikes-lwc in 32 s 69 ms with status 1.

Failures
========
• LightningComponentBundle/null: ERROR at line 1, column 1 - LWC1078: <p> has no matching closing tag.

**Comment by ghost** [comment]
Hello @britishboyindc, 
I've began to work on fixing this but I'm unable to reproduce it. Could you help me by providing maybe an example of your technically correct code that was causing the error, or some more steps to reproduce it?

Thank you

**Comment by britishboyindc** [comment]
@williamruemmele-sf

So you can see some more commentary on this twitter thread:
https://twitter.com/britishboyindc/status/1139195590120812545

But the issue in this case was that I was trying to embed a lightning form in a <p> tag that was part of a Lightning Card, which is not valid HTML, but the IDE wasn't flagging it as invalid HTML

So when I push this 'bad' component with a few others, I couldn't easily work out which component was at fault, since the IDE showed no error, and the error code only referred the component by number, not name. So ideally, when the error was thrown, it would have said 'component name xx' rather than 'LWC1078'

**Comment by ghost** [comment]
@britishboyindc so it seemed like your issue was due to a missing closing 'p' tag right? I made an LWC and in the .html I added only an opening 'p' tag and when I tried to deploy I got this error message which diagnosed my issue for me... 
```PROJECT PATH                                           ERROR
─────────────────────────────────────────────────────  ─────────────────────────────────────────
force-app/main/default/lwc/helloworld/helloworld.html  LWC1078: <p> has no matching closing tag.
ERROR running force:source:deploy:  Deploy failed.
``` 

Maybe this has already been fixed but I wasn't able to produce a null file name like in your description

**Comment by britishboyindc** [comment]
Not a missing tag - illegal markup within the tag. Just tried now, and got same result. See this gist:
https://gist.github.com/britishboyindc/5c0ba99c1bc27ee30740a5725897e48b

Create a brand new component with this markup and push - I get the same error (with the /null) - what's I'd like is the class name or something, even though it has never been deployed (but I realize that might be why the name is null?)

Pushed 0/1 components to ebikes-lwc in 14 s 30 ms with status 1.

Failures
========
• LightningComponentBundle/null: ERROR at line 1, column 1 - LWC1078: <p> has no matching closing tag.

**Comment by ghost** [comment]
hmmm... interesting. What method/commands are you using to deploy/push?

**Comment by britishboyindc** [comment]
I use the Illuminated Cloud IDE, so just doing a push as far as I know - let me see what happens if I do a push via CLI

**Comment by britishboyindc** [comment]
Same issue when pushing via CLI for new (i.e. never deployed component): 
$ sfdx force:source:push -u ebikes-lwc
PROJECT PATH  ERROR
────────────  ─────────────────────────────────────────
N/A           LWC1078: <p> has no matching closing tag.
ERROR running force:source:push:  Push failed.

**Comment by ghost** [comment]
that's so strange. and you're on the newest version of the CLI? 

```$ sfdx --version
sfdx-cli/7.23.1 darwin-x64 node-v10.16.0```

or run 

```sfdx update

to update if you're not
what OS are you using?
could you provide me with your steps to reproduce, maybe I'm missing a step.

**Comment by britishboyindc** [comment]
$ sfdx version
sfdx-cli/7.25.3-16d54c01ee win32-x64 node-v10.15.3

So Win 10 and Iluminated Cloud + Webstorm

Steps:
Create new empty LWC
Add Markup to HTML, JS and Meta as contained in GIST above
Push to scratch org either via CLI or IC Menu Option

**Comment by ghost** [comment]
It seems to be a windows specific issue, I'll start working on a fix right away. Thank you for helping me troubleshoot.

**Comment by mshanemc** [comment]
I named my component `Test` and it shows the name in the error.

<img width="841" alt="Screenshot 2023-04-05 at 9 19 08 PM" src="https://user-images.githubusercontent.com/4261788/230255917-798686be-5bbc-42ac-a094-cfc4efd55547.png">
