### ISSUE TITLE
cmp files not deployed/updated with force:mdapi:deploy and destructiveChanges in winter'22

### ISSUE THREAD

**Issue by Raspikabek** [forcedotcom/cli#1184]
### Summary

When deploying to a target org in Winter '22 with `sfdx force:mdapi:deploy` including destructiveChangesPre.xml and destructiveChangesPost.xml the Aura Components cmp file does not get deployed, however JS Controllers, helper and CSS files get updated correctly.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1. Clone dreamhouse-lwc repository
2. Generate a Scratch Org with Release Preview (will create a Scratch Org with Winter '22)
3. Push your code `sfdx force:source:push` into the new Scratch Org
4. Verify via Developer Console the component `auraPropertyListMap` exists and contains the proper html
5. Modify locally `auraPropertyListMap` by adding:
  * `auraPropertyListMap.cmp` file: Add `hello world` somewhere in the file
  * `auraPropertyListMapController.js` file: add a `console.log('hello world'); ` in any method
6. Run `sfdx force:source:convert -d temp_metadata -p force-app/`
7. Create a `destructiveChanges.xml` file and include it in `temp_metadata` folder _(you can use the template provided below, this is what I've used for testing)_
8. Run `sfdx force:mdapi:deploy -d temp_metadata -l NoTestRun -w 100 -g`
9. Refresh Developer Console and re-open the component `auraPropertyListMap`. Controller file will have the `console.log('hello world')` line but the `cmp` file will remain with no `hello world` text.

#### Destructive Changes file:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>52.0</version>
    <types>
        <members>DummyApexClass</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>DummyComponent</members>
        <name>AuraDefinitionBundle</name>
    </types>
</Package>
```
NOTES: 

I've tested the following scenarios with destructiveChanges:
* Only 1 `destructiveChanges.xml` file --> cmp file is **not** updated
* 2 files `destructiveChangesPost.xml` and `destructiveChangesPre.xml` --> cmp file is **not** updated
* Only 1 `destructiveChangesPost.xml` --> cmp is updated
* Only 1 `destructiveChangesPre.xml` --> cmp is **not** updated

`temp_metadata` folder contains the changes I want to apply.

This does not happen with `sfdx force:source:deploy` since this command does not apply destructiveChanges at the same time.

### Expected result

`cmp` files are updated in the target org

### Actual result

`cmp` files are NOT updated in the target org.

### System Information

Run `sfdx version --verbose --json` and paste the output here.

```
{
        "cliVersion": "sfdx-cli/7.117.0",
        "architecture": "linux-x64",
        "nodeVersion": "node-v14.17.6",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.8 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.28 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.7.0 (core)",
                "salesforce-alm 52.3.2 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.117.0 (core)",
                "source 1.0.12 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Linux 5.10.61-1-MANJARO"
}
```
Tested with sfdx-cli versions: `7.116.2` and version `7.117.0` (I installed the stable-rc just in case too)

This happens with own images too: https://hub.docker.com/r/pexlify/sfdx-cli/tags?page=1&ordering=last_updated

### Additional information

Apparently only happens with Winter '22 organizations (Scratch orgs and Sandboxes).

If this requires a Salesforce Support Case too please say. I'll link this issue if you guys are able to reproduce it. I've been able to reproduce it in all my org Sandboxes + Scratch Orgs from different orgs (scratch orgs from Free Developer Orgs)

**Comment by Raspikabek** [comment]
On top of this error, any other component with dependency on the components or their interfaces; like a Flow, Community Page or Flexipage, the validation/deployment operation will fail since the `cmp` file is not being deployed and a error is returned in form of:
```
=== Component Failures [2]
TYPE   FILE                                                   NAME                PROBLEM
─────  ─────────────────────────────────────────────────────  ──────────────────  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  temp_metadata/flexipages/Broker_Record_Page.flexipage  Broker_Record_Page  The c:myAwesomeComponent component isn't allowed in the detailTabContent region. The component doesn't implement any of the region's allowed interfaces.
Error  temp_metadata/flows/SampleFlow.flow  SampleFlow  test (Screen Component) - The c:myIncredibleComponent component doesn't implement any marker interface that's supported for flows of type Flow.
```

when these interfaces were implemented correctly.

In other builds I had tons of lines with just a generic message like:

`Error  temp_metadata/                                                                       Unable to build Bundle source`
+ 2 errors at the end with 2 interfaces wrongly implemented (due to error previously described)

not sure what exactly is the root cause of this, or might be the case I've tons of components failing for the interface error and simply just blows up.

I've reported this exact issue in a Salesforce Support Case, not sure if could be a Server side error with Winter '22 or how sfdx-cli works with the destructive changes.

**Comment by mshanemc** [comment]
Yeah, open a case.  We have not done any recent changes to the `mdapi` commands, so it the metadata API itself is behaving differently across releases (and there's nothing in the release notes?) then a support case is the best way to get their attention.

Be sure to make it clear that this isn't a CLI issue...sometimes they see the repro commands and say, "oh, CLI!".

**Comment by Raspikabek** [comment]
Thanks @mshanemc for the update :) I agree. I've already reported this and linked all the ifnormation.

On top of this, I've found out that aura events are affected by this error as well.

When deploying a new `Aura Event` in a org with no such event + destructiveChanges, the returned error is:

```
Error  temp_metadata/                                   Unable to build Bundle source
```

**Comment by Raspikabek** [comment]
In the scenario anybody else finds this issue. This is the latest I got from Salesforce:

* Known issue in Winter '22 version: 234 and they're working on this issue.

I'll be reporting back here once resolved in the scenario somebody else is following this issue.

**Comment by Raspikabek** [comment]
Here's the official SF Link of the issue:

https://trailblazer.salesforce.com/issues_view?id=a1p4V00000245RQQAY

Please track the status of the problem in this link. Thanks!
