### ISSUE TITLE
Cannot obtain the report from the deployment

### ISSUE THREAD

**Issue by kamilporwitaccenture** [forcedotcom/cli#1188]
### Summary

I am trying to obtain report from the deployment in the Azure DevOps PowerShell task (v2.190.0)
 via `sfdx:force:source:deploy:report` command right after running `sfdx force:source:deploy command`. Unfortunately, the report command returns an error:
"MissingRequiredParameter: A required parameter [jobid] is missing."

In the documentation I can find tha `-i` flag (jobid) is optional and if not specified, the default value is the ID of the most recent metadata deployment you ran using Salesforce CLI. It works normally when I will provide deployment ID.

### Steps To Reproduce:

1. Create any validation on any org via `sfdx force:source:deploy -c -l RunLocalTests -u ${TARGETORGALIAS} --apiversion ${APIVERSION}`
2. Deploy the changes with the id from the validaiton from step 1 via: `sfdx force:source:deploy -q ${DEPLOYMENTID} -u ${TARGETORGALIAS} --apiversion ${APIVERSION}`
3. Try to obtain the report from deployment via: `sfdx force:source:deploy:report -u ${TARGETORGALIAS}  --apiversion ${APIVERSION} --json`

$DEPOYMENTID is the ID obtained from step 1, $TARGETORGALIAS is the alias for the org and $APIVERSION is set to 52.0

### Expected result

Obtain the output with the deployment status in a JSON format.

### Actual result

The error: "MissingRequiredParameter: A required parameter [jobid] is missing." occurs. All logs can be found in the attachment:
[tasklog_15.log](https://github.com/forcedotcom/cli/files/7154910/tasklog_15.log)

### System Information

 {
 	"cliVersion": "sfdx-cli/7.110.0",
 	"architecture": "linux-x64",
 	"nodeVersion": "node-v14.17.6",
 	"pluginVersions": [
 		"@oclif/plugin-autocomplete 0.3.0 (core)",
 		"@oclif/plugin-commands 1.3.0 (core)",
 		"@oclif/plugin-help 3.2.3 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
 		"@oclif/plugin-plugins 1.10.1 (core)",
 		"@oclif/plugin-update 1.4.0-3 (core)",
 		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
 		"@oclif/plugin-which 1.0.3 (core)",
 		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
 		"@salesforce/sfdx-trust 3.6.0 (core)",
 		"alias 1.1.10 (core)",
 		"apex 0.2.2 (core)",
 		"auth 1.7.1 (core)",
 		"config 1.2.13 (core)",
 		"custom-metadata 1.0.12 (core)",
 		"data 0.5.2 (core)",
 		"generator 1.2.0 (core)",
 		"limits 1.2.1 (core)",
 		"org 1.6.7 (core)",
 		"salesforce-alm 52.1.0 (core)",
 		"schema 1.0.8 (core)",
 		"sfdx-cli 7.110.0 (core)",
 		"sfdx-heineken 0.0.0 (link) /home/vsts/work/r1/sfdx-heineken-plugin",
 		"sfpowerkit 3.2.3",
 		"telemetry 1.2.2 (core)",
 		"templates 52.1.0 (core)",
		"user 1.3.1 (core)"
 	],
 	"osVersion": "Linux 5.8.0-1040-azure"
 }

### Additional information
Screenshot of the Azure DevOps task (I removed Out-File cmdlet to get the error):
![obraz](https://user-images.githubusercontent.com/57448943/133099611-e7b1a3f7-10bb-49d2-97dc-8a42ec2e5fa1.png)

**Comment by shetzel** [comment]
You are on an older version of the CLI and plugins.  Please update to the latest CLI version and you should no longer see this.
