### ISSUE TITLE
force:source:status not adhereing to specific forceignore rules

### ISSUE THREAD

**Issue by toddhalfpenny** [forcedotcom/cli#119]
### Summary

Remote metadata (e.g. custom fields, list views) are not being ignored for `force:source:status` in the same way that they are for `force:source:pull` when they are specifically mentioned. They show as remote changes for `status` even when they will not be pulled by `pull`, but they are not shown when for example ignoring with `Account**` or `*.listView` 

### Steps To Reproduce:

1.  Create new list view called _All_ on account on a scratch org.
1.  Run `force:source:status`, you will see the remote change (correct)
1. Add `Account.All` into .forceignore file
1.  Run `force:source:status`, you will still see the remote change (incorrect)
1. Add `*.listView` into .forceignore file
1.  Run `force:source:status`, you will *not* still see the remote change; it is ignored correctly
1. Remove `*.listView` from .forceignore file
1.  Run `force:source:pull`, you will *not* still see the remote change pulled down; it is ignored correctly

### Additional information

[Video](https://www.youtube.com/watch?v=XUxmusUe1Ns&feature=youtu.be) of the issue being reproduced.

**SFDX CLI Version** - sfdx-cli/7.11.2-4a5bf6aa97 linux-x64 node-v10.15.3:

**SFDX plugin Version**
```
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.1.5 (core)
├─ force-language-services 46.3.0 (core)
└─ salesforce-alm 46.3.0 (core)
```

**OS and version**:
Linux - Ubuntu 18.04

**Comment by nickmorozov** [comment]
Can confirm, I've encountered this before.

**Comment by dcarroll** [comment]
@clairebianchi @amphro  Does anyone on the CLI team know about this issue?

**Comment by mshanemc** [comment]
@toddhalfpenny is this still true?  When I create a list view in the org, it doesn't show up in source:status

**Comment by dcstuff** [comment]
@mshanemc Confirmed this is still happening! Fresh scratch org. I had modified some listviews on some _custom_ objects.

First errors came down that it could not find certain listviews on some wacky standard objects which I had never heard of -- exactly this person's issue, dated Jan 11: https://developer.salesforce.com/forums/?id=9062I000000IWO4QAO

The only workaround that worked was adding the following to my .forceignore.
```
ProductServiceCampaignItem.All_ProductServiceCampaignItems
ProductServiceCampaignItem.My_ProductServiceCampaignItems
ProductServiceCampaignItem.My_RecentProductServiceCampaignItems
ShiftTemplate.My_RecentShiftTemplates
ShiftTemplate.My_ShiftTemplates
ShiftTemplate.All_ShiftTemplates
```

**Comment by mshanemc** [comment]
Here's the plan for this: 

What if we showed them in `status` output, but mark that they are subject to ignoring (that way, you **could** use `source:status` to ask the server what's changed and realize you need to update your .forceignore) vs. just wondering why it's not there.

Then you'd be able to know what would be pulled before you run pull.

@W-9805809@

**Comment by mshanemc** [comment]
closed with new commands GA
