### ISSUE TITLE
lwc not converted when it's under the folder that is the subfolder of the lwc folder

### ISSUE THREAD

**Issue by Xu-Stefan** [forcedotcom/cli#1190]
I have below lwc components under some folders:

> force-app
>> main
>>> default
>>>> lwc
>>>>> subfolder1
>>>>>> lwc
>>>>>>> cmp1
>>>>>>> cmp2 

>>>>> subfolder2
>>>>>> lwc
>>>>>>> cmp3
>>>>>>> cmp4

when I convert to source format by `sfdx force:source:convert --outputdir temp` command.
I got:
> temp
>> lwc
>>> subfolder1
>>>> lwc
>>>>> cmp1
>>>>> cmp2

>>> subfolder2
>>>> lwc
>>>>> cmp3
>>>>> cmp4

but I expect:
> temp
>> lwc
>>> cmp1
>>> cmp2
>>> cmp3
>>> cmp4

And package.xml is not correct yet, 
```
<types>
    <members>subfolder1</members>
    <members>subfolder2</members>
    <name>LightningComponentBundle</name>
</types>
```

Is that any way can do this?

**Comment by mshanemc** [comment]
all component bundles should be the direct child of the /lwc folder.

✅  lwc/myComponent
❌  lwc/subfolder/MyComponent

**Comment by Xu-Stefan** [comment]
Hi @mshanemc 

I see the `sfdx force:source:push` and `package:version:create` commands support these folder structure.

> all component bundles should be the direct child of the /lwc folder.
> 
> ✅ lwc/myComponent
> ❌ lwc/subfolder/MyComponent
