### ISSUE TITLE
Regression: unsignedPluginWhiteList.json stopped working in 7.118.1

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#1193]
Prior to sfdx-cli/7.118.1, the ability to whitelist an unsigned plugin was possible by creating a file `$HOME/.config/sfdx/unsignedPluginWhiteList.json`

This is documented in https://developer.salesforce.com/blogs/2017/10/salesforce-dx-cli-plugin-update and has worked for years

Starting in sfdx-cli/7.118.1, the underlying CLI NPM module that verifies plugins was changed and now it appears to expect `unsignedPluginAllowList.json`

The new code that's checking the whitelist is over here:

https://github.com/salesforcecli/plugin-trust/blob/cdbecd507fed9afba257118efb69174f1c269eb1/src/lib/installationVerification.ts#L24

It looks like it was this commit that did it:

https://github.com/salesforcecli/plugin-release-management/commit/24c2a3c0d28f842b3d939a24a74b91dd79f95719

This results in the plugins failing to install in a CI run -- instead, the CLI prompts for interactive approval of the plugin installation 

`This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: `

Here we are again .. another Thursday .. and another broken CI pipeline. No mention of this change in the Release Notes .. not deprecation warning about the old filename. 

I guess you just assume that we like a thrill to start our day when all of our pipelines are broken and we are facing a missed deadline as a result? This is sloppy and unacceptable. 

### System Information
```
sfdx-cli/7.118.1 linux-x64 node-v14.17.6
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.3 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 1.1.10 (core)
apex 0.2.8 (core)
auth 1.7.1 (core)
config 1.2.34 (core)
custom-metadata 1.0.12 (core)
data 0.6.1 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.7.0 (core)
salesforce-alm 52.3.3 (core)
schema 1.0.8 (core)
sfdx-cli 7.118.1 (core)
source 1.0.15 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
trust 1.0.5 (core)
user 1.4.0 (core)
```

**Comment by maggiben** [comment]
Hi, sorry to hear that, we warned users about the deprecation of the old filename a until Jan 11 when we removed the message in this [commit](https://github.com/salesforcecli/plugin-trust/pull/7/files ), though the functionality remained unchanged until now.
The documentation you're linking says: 

> To add an entry to the allowlist, create a file named unsignedPluginAllowList.json at the correct location for your operating system...

We sorry for the inconvenience.
