### ISSUE TITLE
Windows Script Host - Jscript compilation error during install sfdx plugin - sfdx version 7.118.1

### ISSUE THREAD

**Issue by stoevie** [forcedotcom/cli#1198]
### Summary

When I try to install a new plugin with sfdx version 7.118.1 I get a windows script host error.
![image](https://user-images.githubusercontent.com/51631119/134528365-7d1b866f-364e-4529-b2f7-58211b24d5f8.png)

### Steps To Reproduce:

Step1: Install latest sfdx version (7.118.1) in c:\tools\sfdx
Step 2: run sfdx plugins:install sfpowerkit  -> error appears

### Expected result

sfpowerkit plugin succesfull installed

### Actual result

WIndows Script Host error
![image](https://user-images.githubusercontent.com/51631119/134529027-0c96d581-8c9b-47fa-ac21-c3178b3dbc9f.png)

sfdx plugins:install sfpowerkit
    Code: ShellExecError

### System Information

sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.118.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.17.6",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.8 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.34 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.7.0 (core)",
                "salesforce-alm 52.3.3 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.118.1 (core)",
                "source 1.0.15 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "trust 1.0.5 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19043"

### Additional information

- No problem with older versions of sfdx, the release candidate has the same problem.
- When you install sfdx in c:\program files\sfdx and run sfdx plugins:install sfpowerkit the jscript error does not appear but then the error is: 

sfdx plugins:install sfpowerkit
    ShellExecError: 'C:\Program' is not recognized as an internal or external command,
    operable program or batch file.

    Code: ShellExecError

**Comment by shetzel** [comment]
Thanks for reporting.  We are aware of this issue and the fix will be in the next CLI release candidate scheduled for tomorrow.

**Comment by mshanemc** [comment]
shipped on 9/24 release
