### ISSUE TITLE
Refresh metadata failure: The specified metadata type is unsupported: [sharingguestrule]

### ISSUE THREAD

**Issue by dobias** [forcedotcom/cli#1199]
### Summary

_Trying to refresh the org metadata, including the sharingRules, but this does not work: Get the SfdxError - The specified metadata type is unsupported: [sharingguestrule]_.

### Steps To Reproduce:

Add SharingGuestRule metadata type to the refresh scope and perform refresh command

### Expected result

_Metadata refresh performed._.
![image](https://user-images.githubusercontent.com/2144760/134677166-54e41873-233d-4269-9ec3-fc458875b2e6.png)

### Actual result

_Get error that sharingguestrule is not supported_.

### System Information
{
        "cliVersion": "sfdx-cli/7.118.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.17.6",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.8 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.34 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.1 (core)",
                "org 1.7.0 (core)",
                "salesforce-alm 52.3.3 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.118.1 (core)",
                "source 1.0.15 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "trust 1.0.7 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19042"
}

### Additional information

_Feel free to attach a screenshot_.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9951980](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000AxAowYAF/view)

**Comment by iowillhoit** [comment]
This has been fixed and released in `7.122.1`. See release notes [here](https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx#71221-oct-14-2021)
