### ISSUE TITLE
force:source:deploy no longer displays line level error

### ISSUE THREAD

**Issue by Confirm4Crit** [forcedotcom/cli#120]
### Summary

A change in the CLI seems to have removed line errors from error reporting on source:deploy.

### Steps To Reproduce:

Run force:source:deploy or VS Code command palette deploy against a file with an error in it. 

### Expected result

Error response normally contained a line number, which VSCode extensions picked up.

### Actual result
It does not.
`
sfdx force:source:deploy --sourcepath /Users/robson/Documents/Salesforce Scratch Org Projects/SFDXMilesFull/salesforce/src/main/default/classes/Account_BatchDeleteFeedItem.cls --json --loglevel fatal ended with exit code 1`

### Additional information

This works fine on
VERSION
  sfdx-cli/7.8.1 darwin-x64 node-v12.4.0

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.11.2 darwin-x64 node-v12.4.0
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.1.5 (core)
├─ force-language-services 46.3.0 (core)
└─ salesforce-alm 46.3.0 (core)

sfdx-cli 7.11.2 (core)
sfdx-essentials 0.4.5
**OS and version**:
MacOS Mojave 10.14.3

**Comment by Confirm4Crit** [comment]
Wanted to update this, seems like it's just with the --json param, so this might actually be an issue with the VSCode extensions only.
Is it intended for --json param to not display line level errors?

**Comment by tsalb** [comment]
Can confirm this affects me as well. My environment which does **not** work when using **SFDX: Deploy This Source to Org**

macOs Mojave: 10.14.5
VSCode: Version 1.35.1
VSCode Salesforce Ext Pack: 46.1.0

SFDX CLI: Managed via npm sfdx-cli:
sfdx-cli/7.11.2 darwin-x64 node-v11.9.0

I needed to the revert npm sfdx-cli back to use **force:source:deploy**:
sfdx-cli/7.8.1 darwin-x64 node-v11.9.0

**Comment by MGarfOppLoans** [comment]
Effects me as well through the VSCode extension

**Comment by agm1981** [comment]
Duplicate of Issue 120
