### ISSUE TITLE
Object metadata is not retrieved if field metadata is already retrieved (custom settings)

### ISSUE THREAD

**Issue by pfrandsen** [forcedotcom/cli#1201]
### Summary

Running the command "sfdx force:source:retrieve --loglevel fatal -m CustomObject:xyz" fails to retrieve xyz.object-meta.xml if a field on the object has already been retrieved.

### Steps To Reproduce:

1.  Create a new custom setting "AMLAlarmConfiguration" (AMLAlarmConfiguration__c).
1.  Create a new field "CreateAlarmCase" (CreateAlarmCase__c) on AMLAlarmConfiguration__c
1.  Execute "sfdx force:source:retrieve --loglevel fatal -m CustomField:AMLAlarmConfiguration__c.CreateAlarmCase__c" to retrieve the field.
1. Execute "sfdx force:source:retrieve --loglevel fatal -m CustomObject:AMLAlarmConfiguration__c" to retrieve the object.
1. Verify that "AMLAlarmConfiguration__c.object-meta.xml" has not been rtetrieved.

### Expected result

The object metadata "AMLAlarmConfiguration__c.object-meta.xml" should have been retrieved from the org.

### Actual result

"AMLAlarmConfiguration__c.object-meta.xml" is not present.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.112.1 win32-x64 node-v14.17.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.3 (core)
auth 1.7.1 (core)
config 1.2.14 (core)
custom-metadata 1.0.12 (core)
data 0.6.0 (core)
generator 1.1.7 (core)
limits 1.2.1 (core)
org 1.6.7 (core)
salesforce-alm 52.2.3 (core)
schema 1.0.8 (core)
sfdx-cli 7.112.1 (core)
sfdx-git-delta 4.8.1
source 1.0.6 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
user 1.4.0 (core)

**OS and version**:

Windows 10

**Comment by iowillhoit** [comment]
Hey @pfrandsen, I am unable to replicate this issue. I've tried with CLI versions `7.112.1` and `7.119.2` (latest) on a Mac and `7.119.2` on Windows. Try updating your CLI and try again. If that doesn't work, it's possible it depends on the specific settings of the Custom Setting you are using, you could share more details on how it's configured.

<img width="1874" alt="Screen Shot 2021-09-27 at 12 27 36 PM" src="https://user-images.githubusercontent.com/1715111/134969652-05ff506a-1f3a-4dea-85ec-e2f0810a9528.png">
<img width="1275" alt="Screen Shot 2021-09-27 at 12 29 33 PM" src="https://user-images.githubusercontent.com/1715111/134969673-99d61780-5772-4ede-9021-eb5757a3bbf2.png">
