### ISSUE TITLE
Running SFDX Update gives an 404 error

### ISSUE THREAD

**Issue by MGarfOppLoans** [forcedotcom/cli#1202]
### Summary

Running SFDX update gives an 404 error

### Steps To Reproduce:

Run `sfdx update`

### Actual result

`sfdx update`
sfdx-cli: Updating CLI... !
    Error: HTTP Error 404 for GET https://developer.salesforce.com/wsl-x64

### System Information

Run `sfdx version --verbose --json` and paste the output here.

{
        "cliVersion": "sfdx-cli/7.117.0",
        "architecture": "wsl-x64",
        "nodeVersion": "node-v14.17.6",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.8 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.28 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.7.0 (core)",
                "salesforce-alm 52.3.2 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.117.0 (core)",
                "source 1.0.12 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Linux 5.10.16.3-microsoft-standard-WSL2"
}

**Comment by mshanemc** [comment]
This is the interesting part: `"architecture": "wsl-x64",`
How did you install the CLI on WSL?  does it use the linux version of the installers or the windows one?

We normally map the architecture to the URLs, but we don't seem to have one specific for WSL.  It comes from here: https://nodejs.org/api/os.html#os_os_arch

Any chance that you're setting process.arch or have something else in the environment?

**Comment by MGarfOppLoans** [comment]
i used the linux install, unzipped added to path etc.... Not setting the process arch but wouldnt be surprised if windows does for wsl

**Comment by mshanemc** [comment]
Can you try setting an environment from WSL that would equal whatever your installation file for linux used (it should be stated on the file and match one of the valid nodejs options.  You can also look here to see what architectures are supported: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_olderversions)

**Comment by MGarfOppLoans** [comment]
i can try that, i think based on the above - the fix for SFDX would be to alias this arch as a linux arch

**Comment by mshanemc** [comment]
We don't officially support WSL, so I'm wanting to avoid hacking up the oclif update command to maintain mappings for things we're not actively testing.  Because eventually WSL is going to change it again.  I'm hoping there's some config you can do to get around that.

**Comment by MGarfOppLoans** [comment]
ok will close this out then
