### ISSUE TITLE
CLI sfdx-cli/7.119.2 - sfdx force:user:permset:assign executed correctly run but exitcode 1

### ISSUE THREAD

**Issue by stoevie** [forcedotcom/cli#1204]
### Summary

Bash script with command 'sfdx force:user:permset:assign -n <permset> -u <orgname>' stops without error and exitcode = 1

### Steps To Reproduce:
1.  deploy permset 'abc' to scratch org
2. run script: fixadmin.sh <scratchorgname>

fixadmin script:

#!/bin/bash
set -e

ORGNAME=$1
sfdx force:user:permset:assign -n abc -u ${ORGNAME}
echo 'exitcode: ' $?

### Expected result

permset added and echo'exitcode: 0'

### Actual result
permset added but no 'exitcode: 0' echo.
No message at all because the 'set -e' means the script should stop after an error.

When set +e the result is:
permset added 
'exitcode: 1' echo.

### System Information
{
        "cliVersion": "sfdx-cli/7.119.2",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.17.6",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.8 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.34 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.7.0 (core)",
                "salesforce-alm 52.3.3 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.118.1 (core)",
                "source 1.0.15 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "trust 1.0.5 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19043"

### Additional information

Same Issue with sfdx-cli/7.118.1, no problems with 7.116.2

**Comment by mshanemc** [comment]
Interesting.  Does running the command with `--json` give you a `0` status?

**Comment by stoevie** [comment]
> Interesting. Does running the command with `--json` give you a `0` status?

Hi Shane, no, with --json parameter also exitcode: 1

{
  "status": 0,
  "result": {
    "successes": [
      {
        "name": "test-ewgqsgsw9p10@example.com",
        "value": "abc"
      }
    ],
    "failures": []
  }
}
exitcode:  1

**Comment by iowillhoit** [comment]
How are you running this script? Are you using Git Bash? WSL?

**Comment by iowillhoit** [comment]
I just noticed that your cliVersion (`7.119.2`) is different than the sfdx-cli version in the pluginVersions section (`sfdx-cli 7.118.1 (core)`). Not sure how that would have happened. Can you try doing a fresh install of the CLI to see if that makes any difference?

**Comment by stoevie** [comment]
Hi Willhoit, sorry, I accidentally mixed up data. The cli info was from cli 7.118.1.

I am using Git Bash.

I did several times a fresh install but that didn't work. The last time I did an uninstall and after that I checked the sfdx installation directory. The directory was not empty and I couldn't remove the directory because it was still in use.
After logoff/login I was able to remove the directory and did a fresh install (7.119.2). After that install the problem went away.

You can close the ticket.
