### ISSUE TITLE
Salesforce CLI Error when run list org with --skipconnectionstatus param

### ISSUE THREAD

**Issue by kateluu-comdev** [forcedotcom/cli#1207]
### Summary

Hi team, 
I am facing to an error when try to run  below command,
`sfdx force:org:list --skipconnectionstatus`

Here is the error 
**ERROR running force:org:list:  Unexpected argument: --skipconnectionstatus
See more help with --help**

### Steps To Reproduce:

Step1: Open cmd
Step2: Authenticate to development environment
Step3: Run command 
         sfdx force:org:list --skipconnectionstatus
Step4: Got error
ERROR running force:org:list:  Unexpected argument: --skipconnectionstatus
See more help with --help

### Expected result

I expect receive a list of connections

### Actual result

ERROR running force:org:list:  Unexpected argument: --skipconnectionstatus
See more help with --help

### System Information

Run `sfdx version --verbose --json` and paste the output here.

{
        "cliVersion": "sfdx-cli/7.120.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.17.3",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.9 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.35 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.1 (core)",
                "org 1.8.0 (core)",
                "salesforcedx 48.10.1 (48.10.1)",
                "├─ salesforcedx-templates 48.8.0",
                "├─ salesforce-alm 48.10.0",
                "└─ @salesforce/sfdx-plugin-lwc-test 0.1.5",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.120.0 (core)",
                "sfdx-git-delta 4.6.1",
                "source 1.2.0 (core)",
                "telemetry 1.2.4 (core)",
                "templates 52.2.0 (core)",
                "trust 1.0.8 (core)",
                "user 1.5.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.18363"
}

**Comment by iowillhoit** [comment]
Hey @kateluu-comdev, pretty sure that this is happening because you are using `salesforce-alm` through the `salesforcedx` plugin. This plugin has been deprecated. You should be able to pull in `salesforce-alm` on it's own by running:

`sfdx plugins:uninstall salesforcedx ` and then `sfdx update`

See [these release notes](https://github.com/forcedotcom/cli/tree/main/releasenotes#71063-june-17-2021) for more details

**Comment by kateluu-comdev** [comment]
Hi @iowillhoit , thank for the suggestion. I tried to uninstall salesforcedx and then update sfdx, but I am facing the issue with 

```
SSL Error: SELF_SIGNED_CERT_IN_CHAIN".
sfdx-cli: Updating plugins... !
```

try to set [ strict-ssl false ] in yarn.lock file , but still not luck.  Can not update sfdx

Cheers,

**Comment by kateluu-comdev** [comment]
@iowillhoit , 
I tried npm to update sfdx, it worked for me. The issue is troubleshooted now. Thank for your information. Cheers
`npm install --global sfdx-cli`

**Comment by iowillhoit** [comment]
Fantastic, glad it's working now! Going to close this issue. Cheers
