### ISSUE TITLE
Unable to install 7.120.0

### ISSUE THREAD

**Issue by sfrycertinia** [forcedotcom/cli#1208]
### Summary

The latest release fails to install via npm requiring GitHub credentials, via basic authentication.

### Steps To Reproduce:

1.  npm install --global sfdx-cli@7.120.0

### Expected result

npm package installed in global node_modules.

### Actual result

npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/developer/.npm/_logs/2021-10-01T09_39_12_505Z-debug.log

### System Information

Linux x64

Fails on both Node 12 LTS and Node 14 LTS default npm versions.

**Comment by sfrycertinia** [comment]
Relevant lines from the log.

703 http fetch GET 401 https://github.com/salesforcecli/Inquirer.js/tarball/github_release 318ms
704 silly fetchPackageMetaData error for inquirer@https://github.com/salesforcecli/Inquirer.js/tarball/github_release Unable to authenticate, need: Basic realm="GitHub"

**Comment by peternhale** [comment]
Hi @sfryffdc. I am sorry you ran into this problem. We were wondering if you have the env var  `SFDX_NPM_REGISTRY` set?

**Comment by sfrycertinia** [comment]
@peternhale yes we do actually. We use an in house npm registry.

**Comment by peternhale** [comment]
@sfryffdc Is it safe to assume that auth for that registry is set to always?

**Comment by sfrycertinia** [comment]
Yes that is correct.

**Comment by sfrycertinia** [comment]
@peternhale unsetting SFDX_NPM_REGISTRY makes no difference to the error.

**Comment by peternhale** [comment]
@sfryffdc is your internal registry displayed when you run `npm config list -g`?

I just ran the install against a registry that requires auth and did not have an issue with installer failing.

**Comment by sfrycertinia** [comment]
> @sfryffdc is your internal registry displayed when you run `npm config list -g`?
> 
> I just ran the install against a registry that requires auth and did not have an issue with installer failing.

Yes it is showing in the global config list.

**Comment by sfrycertinia** [comment]
We install thousands of npm packages with this configuration, both our developers and our CI processes and we have never seen this kind of error before.

**Comment by peternhale** [comment]
@sfryffdc I understand. That one dependency that is resolved via a github location, rather than a published npm module. Here is the [npm feature](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#github-urls) that we are relying on.

Could you try `npm install --global sfdx-cli@7.120.0 --registry https://registry.npmjs.org/` This will override npm config.

**Comment by sfrycertinia** [comment]
Looks like this will be an issue for everyone using npm v6 and a private registry. https://github.com/npm/npm-registry-fetch/issues/12

Yes, we can do as you suggest, but this means a lot of work for us to clean up.

**Comment by peternhale** [comment]
@sfryffdc I am not suggesting that your organization use the workaround as a solution to this issue. I was asking that you can confirm that the install works when bypassing internal registry.

Have you tried with npm v7? Is upgrading to npm 7 a viable option for your organization?

**Comment by sfrycertinia** [comment]
@peternhale sorry to show frustration. In answer yes I can confirm that the install works without our registry present.

Moving npm versions isn't really an immediate option to solve this for us I'm afraid.

**Comment by peternhale** [comment]
@sfryffdc Yes, I did anticipate your response. We are discussing a fix.

**Comment by sfrycertinia** [comment]
Thanks, much appreciated.

**Comment by peternhale** [comment]
@sfryffdc are you in a position to use the previous version of sfdx-cli, while we correct this issue?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9976179](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000CMuJCYA1/view)

**Comment by sfrycertinia** [comment]
> @sfryffdc are you in a position to use the previous version of sfdx-cli, while we correct this issue?

Yes we have our own definition of the official company version that is used on CI servers, we are just in the process of trying to bring things up to tracking the latest release. That project is what has highlighted this for us so quickly. However I expect we will start getting issues logged by developers next week who like to install latest.

**Comment by peternhale** [comment]
@sfryffdc We have applied a fix to sfdx-cli. It is available in the `latest-rc` package `7.121.2`. This version will be promoted next Thursday. If resolving this is more urgent, then please use `sfdx-cli@7.119.3` until next week.

**Comment by sfrycertinia** [comment]
@peternhale great! Thanks for the quick response.
