### ISSUE TITLE
push command keep failing with ... at GetAddrInfoReqWrap.onlookup

### ISSUE THREAD

**Issue by niv-goldenberg** [forcedotcom/cli#1209]
### Summary

Hello, I'm getting the following error when trying to push our source to a new scratch org:

> sfdx force:source:push -f --ignorewarnings --loglevel debug *** Deploying with SOAP *** Job ID | 0Af0E00002EzLLdSAN SOURCE PROGRESS | █████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 222/1864 ComponentsError: getaddrinfo ENOTFOUND inspiration-velocity-3254.cs89.my.salesforce.com   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {  errno: -3008,  code: 'ENOTFOUND',  syscall: 'getaddrinfo',  hostname: 'inspiration-velocity-3254.cs89.my.salesforce.com' } (node:399016) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND inspiration-velocity-3254.cs89.my.salesforce.com   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) (Use `node --trace-warnings ...` to show where the warning was created) (node:399016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:399016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have tried several scratch orgs. This is new and wasn't introduce few days ago (my R&D team is creating scratch orgs all the time on a daily basis).

### Steps To Reproduce:

1.  sfdx force:source:push -f --ignorewarnings --loglevel debug

With the following scratch def:
`{
  "edition": "enterprise",
  "features": [
    "addcustomapps:30",
    "addcustomtabs:30",
    "chatteranswersuser",
    "cloudtocloud",
    "commonprm",
    "communities",
    "contactstomultipleaccounts",
    "contractapprovals",
    "custobjchangeowneremail",
    "customercommunity",
    "einsteinarticlerecommendations",
    "einsteinbuilderfree",
    "einsteinsearch",
    "einsteinsearchpersonalization",
    "entitlements",
    "flowsites",
    "fsccomprehensive",
    "interaction",
    "lightningdomainspropagated",
    "macros",
    "offlineuser",
    "pardotadvanced",
    "partnercommunity",
    "personaccounts",
    "s2xallowaftereos",
    "salesforcecontentuser",
    "servicecloud",
    "sfoallowaftereol",
    "lightningsalesconsole",
    "lightningserviceconsole",
    "serviceuser",
    "salesuser"
  ],
  "settings": {
    "accountSettings": {
      "enableAccountTeams": true,
      "enableContactHistoryTracking": true
    },
    "actionsSettings": {
      "enableThirdPartyActions": true
    },
    "chatterSettings": {
      "enableInviteCsnUsers": true,
      "unlistedGroupsEnabled": true
    },
    "communitiesSettings": {
      "enableCommunityWorkspaces": true,
      "enableCspNotesOnAccConPref": true,
      "enableNetworksEnabled": true,
      "enablePRMAccRelPref": true
    },
    "contentSettings": {
      "enableFilesUsrShareNetRestricted": true,
      "enableSiteGuestUserToUploadFiles": true
    },
    "currencySettings": {
      "enableMultiCurrency": true
    },
    "emailAdministrationSettings": {
      "enableEmailToSalesforce": true,
      "enableSendViaExchangePref": true
    },
    "emailIntegrationSettings": {
      "doesGmailStayConnectedToSalesforce": true,
      "enableOutlookIntegration": true
    },
    "enhancedNotesSettings": {
      "enableEnhancedNotes": true
    },
    "flowSettings": {
      "enableFlowFieldFilterEnabled": true,
      "enableFlowPauseEnabled": true
    },
    "forecastingSettings": {
      "enableForecasts": true
    },
    "languageSettings": {
      "enableEndUserLanguages": true,
      "enableTranslationWorkbench": true
    },
    "leadConfigSettings": {
      "doesHideOpportunityInConvertLeadWindow": true,
      "doesSelectNoOpportunityOnConvertLead": true,
      "doesTrackHistory": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true,
      "enableUsersAreLightningOnly": true
    },
    "pathAssistantSettings": {
      "canOverrideAutoPathCollapseWithUserPref": true,
      "pathAssistantEnabled": true
    },
    "quoteSettings": {
      "enableQuote": true
    },
    "sharingSettings": {
      "enableManagerGroups": true,
      "enableManualUserRecordSharing": true
    },
    "userEngagementSettings": {
      "enableScheduledSwitcher": true
    },
    "userInterfaceSettings": {
      "enableCollapsibleSideBar": true,
      "enableProfileCustomTabsets": true
    },
    "userManagementSettings": {
      "enableNewProfileUI": true
    }
  }
}
`

### Expected result

A successful push command.

### Actual result

A fail push command without source tracking.

### System Information

{
        "cliVersion": "sfdx-cli/7.120.0",
        "architecture": "linux-x64",
        "nodeVersion": "node-v14.17.6",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.9 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.35 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.1 (core)",
                "org 1.8.0 (core)",
                "salesforce-alm 52.3.5 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.120.0 (core)",
                "source 1.2.0 (core)",
                "telemetry 1.2.4 (core)",
                "templates 52.2.0 (core)",
                "texei-sfdx-plugin 1.11.0",
                "trust 1.0.8 (core)",
                "user 1.5.0 (core)"
        ],
        "osVersion": "Linux 5.13.19-200.fc34.x86_64"
}

#### NOTES 

The deployment itself is completed successfully, but since the push command is failing there isn't any source tracking in the process - which mean I can't actually keep working, since DX thinks I haven't pushed anything into the scratch org.

In addition, I have tried several suggestions from other issues (examples below) but this didn't worked as well:
export SFDX_DISABLE_DNS_CHECK=false
export SFDX_DNS_TIMEOUT=100
export SFDX_DNS_RETRY_FREQUENCY=10

**Comment by mshanemc** [comment]
We've got a rewrite of the push command in progress, so we're not going to fix it to handle these DNS failures better in the old version.  It'll be more fault tolerant of these intermittent connectivity issues.

From what it looks like, this is working for a while (deploying a few hundred components) and then one of the polling calls fails to resolve domain.  If you're behind a proxy (?), make sure your DNS is stable, solid and reachable.

**Comment by niv-goldenberg** [comment]
The workaround here: https://github.com/forcedotcom/cli/issues/1181
both the implicit setting of the api version and the env variable (SFDX_DISABLE_DNS_CHECK=true), seems to have worked for us at the moment if applied together.

We are not behind any proxy and we have a very stable 100/100 connection, this is the first time we encounter this issue and we are using SFDX in our R&D team for around a year (we had a lot of other issues but not this one).

So just to make it clear for me, you are saying there is some sort of issue related to DNS lookup that will be addressed in a far-future-refactoring-major-release of the Push command? if yes that sounds awesome!

 Thanks
