### ISSUE TITLE
sfdx force:org:list working with cmd but not working with powershell

### ISSUE THREAD

**Issue by meddany** [forcedotcom/cli#1213]
I have weird issue. 
i am trying to execute this command.

    sfdx force:org:list

this command is working fine in cmd.exe but it fails in powershell 

in cmd.exe

    == Orgs
         ALIAS  USERNAME                                   ORG ID              CONNECTED STATUS
    ───  ─────  ─────────────────────────────────────────  ──────────────────  ─────────────────────
    (U)  MyDomain  myAccount@Myaccont.com  XXXXXXXXXXXXXXX  Connected
    
    No active scratch orgs found. Specify --all to see all scratch orgs
    
    C:\Users\webapp>

but in powershell 
C:\Users\webapp>sfdx force:org:list

    Error: connect ETIMEDOUT XX.XX.XX.XX:443
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
      errno: -4039,
      code: 'ETIMEDOUT',
      syscall: 'connect',
      address: 'XX.XX.XX.XX',
      port: 443
    }
    WARNING: Starting in API version 52, the JSON output of this command no longer returns the property connectedStatus for scratch orgs.
    === Orgs
         ALIAS  USERNAME                                   ORG ID              CONNECTED STATUS
    ───  ─────  ─────────────────────────────────────────  ──────────────────  ────────────────
     (U)  MyDomain  myAccount@Myaccont.com                   XXXXXXXXXXXXXXX  ETIMEDOUT
    
    No active scratch orgs found. Specify --all to see all scratch orgs
    
    C:\Users\webapp>

i am working behind a proxy. otherwise i cant access the internet.
but i applied this command.

    set HTTP_PROXY=http://xx.xxx.xx.xx:8000
    set HTTPS_PROXY=http://xx.xxx.xx.xx:8000

any idea why this happen ?

**Comment by iowillhoit** [comment]
We occasionally see DNS timeout issues when working with proxies. Try setting `SFDX_DNS_TIMEOUT` to something higher (defaults to 3).

**Comment by meddany** [comment]
the weird thing it is always success in cmd. and fails in powershell. event if i executed the commands at the same time side by side.
in cmd it success with no delay. and in powershell fails with mentioned error. seems that powershell doesnt listen to the proxy

**Comment by meddany** [comment]
the weird thing 

> We occasionally see DNS timeout issues when working with proxies. Try setting `SFDX_DNS_TIMEOUT` to something higher (defaults to 3).

i changed it using set SFDX_DNS_TIMEOUT=6 . and the same issue

**Comment by iowillhoit** [comment]
Have you confirmed that the PROXY env vars are set in powershell? You need to set env vars a little differently in PS:

For the session it's:
`$env:VAR_NAME=VALUE`
to set it permanently it's:
`[System.Environment]::SetEnvironmentVariable('VAR_NAME','VALUE')`
