### ISSUE TITLE
Bug in new sf retrieve command

### ISSUE THREAD

**Issue by msrivastav13** [forcedotcom/cli#1216]
### Summary

sf retrieve command mandates one of these flags: manifest, metadata, source-dir.

There is one more scenario where none of these flags are needed. This is when we retrieve the metadata by **package name** like below

`sf retrieve metadata -n "<package name>"`

I get an error as below

> RequiredOneOfFlagsMissingError: This command expects one of the following flags manifest, metadata, source-dir 
    to be provided.
    Code: RequiredOneOfFlagsMissingError

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1. Find a developer org that has a package.
2. Retrieve the metadata by package name using `sf retrieve metadata -n "<package name>"`

### Expected result

The validation should be enhanced to allow command execution if --package-name or n flag is provided.

### Actual result

Error

> RequiredOneOfFlagsMissingError: This command expects one of the following flags manifest, metadata, source-dir 
    to be provided.
    Code: RequiredOneOfFlagsMissingError

### System Information

``` json
 {
        "cliVersion": "sfdx-cli/7.120.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v14.18.0",
        "pluginVersions": [
                "@muenzpraeger/sfdx-plugin 0.5.0",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/analytics 0.30.0",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-scanner 2.12.0",
                "alias 1.1.10 (core)",
                "apex 0.2.9 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.35 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.1 (core)",
                "org 1.8.0 (core)",
                "salesforce-alm 52.3.5 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.120.0 (core)",
                "source 1.2.0 (core)",
                "telemetry 1.2.4 (core)",
                "templates 52.2.0 (core)",
                "trust 1.0.8 (core)",
                "user 1.5.0 (core)"
        ],
        "osVersion": "Darwin 20.6.0"
}
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9986800](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000DFfQ9YAL/view)

**Comment by RodEsp** [comment]
Thanks for reporting this @msrivastav13. We'll be adding this to our coming sprint and will update this when we have a fix out. You can still use the `sfdx force:source:retrieve --packagenames <packagename>` command in the meantime.

**Comment by mdonnalley** [comment]
This is fixed in the latest version of sf (1.1.5)

**Comment by msrivastav13** [comment]
@mdonnalley Currently doing `sfdx update` does not update it to 1.1.5? Is there any other command to update it?

**Comment by RodEsp** [comment]
@msrivastav13 there's a fix going out today in `stable-rc` for a bug that was preventing `sfdx update` from updating `sf`.

You can also just run `npm install @salesforce/cli -g` to install the latest of `sf` for now.

**Comment by msrivastav13** [comment]
ok `sfdx update` does not do an update. But just did a `npm install @salesforce/cli -g`
