### ISSUE TITLE
Can't Auth after updating the CLI for Sandbox spinup

### ISSUE THREAD

**Issue by MGarfOppLoans** [forcedotcom/cli#1217]
### Summary

It looks like you can't run force:org:status on a sandbox if your already authenticated. This by design adds a good amount of overhead cause you need to check if your authenticated before you do anything. This should be able to handle that internally. I logged this as a defect as historically it did exactly that but now it throws an error

### Steps To Reproduce:

Create Sandbox
Run `force:org:status` on the sandbox

### Expected result

Successfully authenticate against the org

### Actual result
```
ERROR running force:org:status:  Cannot create an AuthInfo instance that will overwrite existing auth data. 

Create the AuthInfo instance using existing auth data by just passing the username.  E.g., AuthInfo.create({ username: 'my@user.org' });
Error: Command failed: sfdx force:org:status -n plsdelete -u sandboxmanager@opploans.com -a plsdelete -w 90
```

### System Information

Run `sfdx version --verbose --json` and paste the output here.

```
{
	"cliVersion": "sfdx-cli/7.119.2",
	"architecture": "linux-x64",
	"nodeVersion": "node-v14.17.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.3 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.1.10 (core)",
		"apex 0.2.8 (core)",
		"auth 1.7.1 (core)",
		"config 1.2.35 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.1 (core)",
		"generator 1.2.0 (core)",
		"limits 1.2.1 (core)",
		"org 1.7.0 (core)",
		"salesforce-alm 52.3.5 (core)",
		"schema 1.0.8 (core)",
		"sfdx-cli 7.119.2 (core)",
		"source 1.1.0 (core)",
		"telemetry 1.2.4 (core)",
		"templates 52.1.0 (core)",
		"trust 1.0.8 (core)",
		"user 1.4.0 (core)"
	],
	"osVersion": "Linux 5.8.0-1041-azure"
}
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by mshanemc** [comment]
Why would you want to run that command if you're already connected to the sandbox (that is, you know it finished and is able to be logged into?)

**Comment by MGarfOppLoans** [comment]
Timeout issues, retries, are the most common issues.

For example sometimes we are polling a sandbox and it timeouts and we restart. not having to check if we are authed make it super simple to ensure stability in our CI/CD pipeline.

Its somewhat common in other SDKs such as Firebase SDK to reduce overhead in having to check before authing. Essentially they work by when calling the function it checks internally if its already authed and returns that instance else it creates a new auth instance.

**Comment by MGarfOppLoans** [comment]
@mshanemc just wanted to check in and see if you had any other questions on this concern or anything more I can provide to convince that making this change would be beneficial?

**Comment by shetzel** [comment]
@MGarfOppLoans - The new org commands listed below should provide the behavior you are expecting (particularly `org resume sandbox`).  Please reopen this if they don't so we can address it.
`sf org create sandbox`
`sf org resume sandbox`
`sf org delete sandbox`
