### ISSUE TITLE
force:source:status shows Remote Changed for Apex Class after force:source:push

### ISSUE THREAD

**Issue by mslomka-polsource** [forcedotcom/cli#122]
### Summary

```force:source:status``` shows Remote Changed for Apex Class after ```force:source:push```.

### Steps To Reproduce:

1.  $ sfdx force:source:status
=== Source Status
    No results found
1.  change the class
1. $ sfdx force:source:status
=== Source Status
STATE          FULL NAME    TYPE       PROJECT PATH
─────────────  ───────────  ─────────  ────────────────────────────────────────────────────
Local Changed  SomeClass  ApexClass  force-app\main\default\classes\SomeClass.cls

1. $ sfdx force:source:push
=== Pushed Source
STATE    FULL NAME    TYPE       PROJECT PATH
───────  ───────────  ─────────  ────────────────────────────────────────────────────
Changed  SomeClass  ApexClass  force-app\main\default\classes\SomeClass.cls

### Expected result

```
$ sfdx force:source:status
=== Source Status
No results found
```

### Actual result
```
$ sfdx force:source:status
=== Source Status
STATE           FULL NAME    TYPE       PROJECT PATH
──────────────  ───────────  ─────────  ─────────────────────────────────────────────────────────────
Remote Changed  SomeClass  ApexClass  force-app\main\default\classes\SomeClass.cls
Remote Changed  SomeClass  ApexClass  force-app\main\default\classes\SomeClass.cls-meta.xml
```

### Additional information
The problem occurs only when the class has a dependency on some package.

```<?xml version="1.0" encoding="UTF-8"?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>41.0</apiVersion>
    <packageVersions>
        <majorNumber>1</majorNumber>
        <minorNumber>47</minorNumber>
        <namespace>somePackage</namespace>
    </packageVersions>
    <status>Active</status>
</ApexClass>
```

**SFDX CLI Version**:
sfdx-cli/7.12.3-bfc421fa08 win32-x64 node-v10.15.3

**SFDX plugin Version**:
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.2.3 (core)
├─ force-language-services 46.7.0 (core)
└─ salesforce-alm 46.6.0 (core)

sfdx-cli 7.12.3 (core)

**OS and version**:
Microsoft Windows [Version 10.0.17763.557]

**Comment by nramyasri-sf** [comment]
@mslomka-polsource , have a few follow up questions here as I am unable to reproduce this from my end. 
 Is this something that happens every time you modify your apex class and do a source:push? 
What kind of package dependencies are you referring to in this scenario.
What is the edition of the org you are using.
Would be able to share some sample code/repo or more detailed steps for reproduction.
Thank you!
