### ISSUE TITLE
Winter '22 Org Snapshot Scratch Orgs Failing during Create

### ISSUE THREAD

**Issue by brandbarr** [forcedotcom/cli#1222]
### Summary

Since the Winter '22 release went into our production org, scratch orgs consistently fail with error code `T-0004` when created using Org Snapshot. 

### Steps To Reproduce:

I don't have a public way of reproducing this without getting a test org assigned to the Snapshots Pilot group. Happy to do so if I could get an org. 

### Expected result

Snapshot scratch orgs should generate properly on Winter '22 when using Snapshot.

### Actual result

Since Winter '22 release, scratch orgs generated from a snapshot have failed every time with the below error:
```
》 sfdx force:org:create -f config/scratch-def-org-snapshot.json -a bb-dev-org -w 10
ERROR running force:org:create:  The request to create a scratch org failed with error code: T-0004.
```

The config file is simple:
```
{
  "orgName": "Dev Org",
  "snapshot": "DevOrg_100421"
}
```

### System Information

```
{
        "cliVersion": "sfdx-cli/7.120.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v14.15.5",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/lwc-dev-server 2.5.1",
                "├─ @oclif/plugin-help 2.2.3",
                "└─ @oclif/plugin-update 1.3.10",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.9 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.35 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.2.0 (core)",
                "hutte 0.0.47",
                "limits 1.2.1 (core)",
                "org 1.8.0 (core)",
                "salesforce-alm 52.3.5 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.120.0 (core)",
                "sfdx-git-delta 4.7.2 (4.7.2)",
                "source 1.2.0 (core)",
                "telemetry 1.2.4 (core)",
                "templates 52.2.0 (core)",
                "trust 1.0.8 (core)",
                "user 1.5.0 (core)"
        ],
        "osVersion": "Darwin 20.6.0"
}
```

### Additional information

Things I have tried on through my own debugging.
- Normal scratch orgs work fine
- Org Shapes based scratch orgs work fine
- I thought it could be related to a mismatch in org version between the snapshot and the hub org.
  - I generated a Winter '22 scratch org.
  - Updated all installed manage packages to the latest public version. 
  - Deployed our code and and confirmed functionality.
  - Made a new snapshot
  - Still receiving the the same error.

**Comment by mshanemc** [comment]
I'm asking our scratch org signups friends what a T-0004 is.  That one is new to me.

**Comment by mshanemc** [comment]
OK, they know about it and are working on a fix.  There's not a KnownIssue link you can subscribe to since it's still in pilot.

@W-9996591@

**Comment by rasmuszimmer** [comment]
@mshanemc where is it tracked then - is it somewhere I can go and see for myself?

**Comment by brandbarr** [comment]
@rasmuszimmer - I think this tracked internally. `@W-9996591@` looks like a Salesforce record name. 

@mshanemc - Any updates on if this fix is progressing?

**Comment by rasmuszimmer** [comment]
Snashot PO has announced that the issue is fixed and that the fix will be deployed over the coming days

**Comment by warnakuw** [comment]
Any updates on how this issue is progressing ?

**Comment by mshanemc** [comment]
the scratch org folks marked W-9996591 as closed, so I'm guessing this is all good now.
