### ISSUE TITLE
Unable to install sfdx@7.121.4 with npm

### ISSUE THREAD

**Issue by alanjaouen** [forcedotcom/cli#1224]
### Summary

can't install sfdx@7.121.4 with npm

![image](https://user-images.githubusercontent.com/14994179/136434371-8ae86d8a-526f-44de-80d7-f12ef79828cc.png)

### Steps To Reproduce:

`{
  "dependencies": {
    "sfdx-cli": "7.121.4"
  }
}`

just npm i with this file

### Expected result

sfdx should be installed

### Actual result

sfdx is not installed

### System Information

there is no sfdx

**Comment by RodEsp** [comment]
Hi @alanJaouen there is a major outage happening with `npm` right now. Because of this installing any `npm` package, not just `sfdx` will likely fail right now.

Please check their status page for more info: https://status.npmjs.org/

**Comment by RodEsp** [comment]
If you'd like to install `sfdx` without `npm` please use the installers provided [here](https://developer.salesforce.com/tools/sfdxcli).

You can also use the tarballs linked in our [install documentation](https://developer.salesforce.com/docs/atlas.en-us.234.0.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux).

**Comment by alanjaouen** [comment]
thank you for your Lightning fast answer, i will keep an eye on it
