### ISSUE TITLE
Inconsistent empty tag behavior when converting metadata format to source format and retrieving source from org 

### ISSUE THREAD

**Issue by joeythomaschaske** [forcedotcom/cli#1227]
When retrieving metadata through the cli and converting it using `sfdx force:mdapi:convert -r path/to/metadata` the tags are self-closing. This has been committed to source control.

After the metadata is converted to source format and new features are added we run `sfdx force:source:retrieve -p path/to/source` the tags are not self-closing which causes all files to show as a diff in source control:

There are hundreds of file changes with these self-closing tags.

<img width="893" alt="Screen Shot 2021-10-07 at 5 55 46 PM" src="https://user-images.githubusercontent.com/7061638/136474088-d9735ae1-ef41-43b7-9efc-44bf1d6ddca7.png">

The cli should handle these tags consistently

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10007500](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000EYsCRYA1/view)

**Comment by mshanemc** [comment]
this is now corrected (tested using project convert mdapi, with your same repro suggestion (customObject searchLayouts property)

<img width="1196" alt="Screenshot 2023-06-22 at 12 28 09 PM" src="https://github.com/forcedotcom/cli/assets/4261788/cda93873-f97b-4607-9ac7-fb2376f0f4bd">
