### ISSUE TITLE
SFDC CLI does not deploy Standard SObject workflow elements - not found in zipped directory

### ISSUE THREAD

**Issue by JavierCarvajalLBS** [forcedotcom/cli#1228]
I have created this bug from [(https://github.com/forcedotcom/cli/issues/707)] even it seems to be related because it is closed.

**Summary**
Salesforce CLI appears to be unable to deploy workflow elements for Standard objects when those workflow elements are specified in the package.xml as individual metadata elements (i.e. WorkflowRule, WorkflowAlert, WorkflowFieldUpdate, etc.) and not as a whole workflow metadata element (i.e. Workflow).

**Steps To Reproduce:**
Create a workflow rule with a workflow email alert and workflow rule on the Opportunity object
Create a package.xml file listing each of the elements individually in WorkflowRule, WorkflowAlert metadata types.
Retrieve the metadata. (this works correctly)
Deploy the workflow to another org. (Failure point)

**Expected result**
The workflow elements should be deployed to the target org

**Actual result**
No deployment occurs. The error seen is:

```
An object XXXXXXXX of type WorkflowRule was named in package.xml, but was not found in zipped directory
An object XXXXXXXX of type WorkflowAlert was named in package.xml, but was not found in zipped directory

```
**Additional information**
SFDX CLI Version(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.119.2 win32-x64 node-v14.17.6

SFDX plugin Version(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.3 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 1.1.10 (core)
apex 0.2.8 (core)
auth 1.7.1 (core)
config 1.2.35 (core)
custom-metadata 1.0.12 (core)
data 0.6.1 (core)
generator 1.2.0 (core)
limits 1.2.1 (core)
org 1.7.0 (core)
salesforce-alm 52.3.5 (core)
schema 1.0.8 (core)
sfdx-cli 7.119.2 (core)
source 1.1.0 (core)
telemetry 1.2.4 (core)
templates 52.1.0 (core)
trust 1.0.8 (core)
user 1.4.0 (core)

OS and version:
Windows 10.0.18362

**Comment by cristiand391** [comment]
@JavierCarvajalLBS I've been trying to reproduce this with `sfdx 7.119.2` and `7.122.1`, can retrieve from one org and deploy to another scratch org, no error.

Do you still see this error? If so, do you have a repo to reproduce this? Thanks.

**Comment by itaishmida** [comment]
I am also facing this problem
With sfdx CLI I can easily get the WorkflowRule with the `sfdx force:source:retrieve -m` command, but when trying to deploy it with the `sfdx force:source:deploy -m` command, I get this error:
Error  myObject__c.myWorkflowRuleName  An object 'myObject__c.myWorkflowRuleName' of type WorkflowRule was named in package.xml, but was not found in zipped directory

**Comment by dwaipayanpal** [comment]
I am facing the same issue

**Comment by ghost** [comment]
I think the parent object's workflow needs to be in the package.xml, too. This is what I did:

1. At first, I only included Flow and WorkflowAlert in my package.xml.
2. When I tried to deploy, I got an error: "WorkflowAlert was named in package.xml, but was not found in zipped directory."
3. I added Workflow to my package.xml and kept Flow and WorkflowAlert in there, too.
4. I'm able to deploy the WorkflowAlert now.
