### ISSUE TITLE
List-based Custom Settings Issues when Source Pulling and Package-Version Creation

### ISSUE THREAD

**Issue by SalesforcePetr** [forcedotcom/cli#1231]
### Summary

List-based Custom Settings Issues (force:source:pull, force: package:version:create)

### Steps To Reproduce:

1. Create a scratch org
2. Enable "Manage list custom settings type" under Schema Settings
3. Create a public list-based custom settings object
4. Create two text fields there: A and B, where B is marked as unique
5. Try to force:source:pull and you'll get an error similar to this:
```
sfdx force:source:pull -u cedev
We can’t retrieve the specified metadata object: CustomIndex. Certain metadata types, like <<redacted>>__c.B__c are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
=== Pulled Source
No results found
```

### Expected result

Custom settings and both fields pulled.

### Actual result

Error above

### System Information

```
sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.121.8",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.18.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.21 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.2 (core)",
                "config 1.2.40 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.2 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.2 (core)",
                "org 1.8.1",
                "salesforce-alm 52.5.0 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.121.8 (core)",
                "source 1.2.2 (core)",
                "telemetry 1.2.6 (core)",
                "templates 52.3.0 (core)",
                "trust 1.0.8 (core)",
                "user 1.5.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19042"
}
```

### Additional information

This is the best I could get so far. I'd say this could be a root cause for why a package version (unlocked) can't be created that references such a custom-settings object.

**Comment by jkentjnr** [comment]
I am also having this problem.  It seems the most recent release has changed how the cli works with Custom Settings.  I am also having problems publish my source into a new scratch org; had to hand craft the settings to push the source successfully.  Just mentioning as an FYI as may be linked.  Will raise an issue if it happens when I next try.

**Comment by cristiand391** [comment]
@SalesforcePetr @jkentjnr thank you for reporting!
I was able to reproduce this with `sfdx v7.121.8`, after looking at the plugin where these commands live [(`salesforce-alm`)](https://www.npmjs.com/package/salesforce-alm) I found that this was fixed in the latest version.

We will get a new latest-rc later today with the fix, will let you know when is out.

**Comment by cristiand391** [comment]
@SalesforcePetr @jkentjnr latest-rc `7.123.0` has been released last week! It should contain the fix, you can upgrade to it by running `sfdx update stable-rc` and then `sfdx update stable` to return to the current release.
We will keep the issue open until it gets promoted next Thursday.
