### ISSUE TITLE
`sf` command cannot be ran when a user profile has a space in it on Windows

### ISSUE THREAD

**Issue by mattisdada** [forcedotcom/cli#1232]
### Summary

If there is a space in the user profile / path, `sf` will not execute and generate the following error:
```cmd
:: User path is C:\Users\Matt Work\...
> 'C:\Users\Matt' is not recognized as an internal or external command, operable program or batch file.
```

### Steps To Reproduce:

**Repository to reproduce:** 

1. Create a Windows user with a space in the path
2. Login as that user
3. Attempt to run `sf` (arguments do not matter)

### Expected result

`sf` command executes

### Actual result

```cmd
:: User path is C:\Users\Matt Work\...
> 'C:\Users\Matt' is not recognized as an internal or external command, operable program or batch file.
```

### System Information

```json
{
        "cliVersion": "sfdx-cli/7.121.8",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.18.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "alias 1.1.21 (core)",
                "auth 1.7.2 (core)",
                "config 1.2.40 (core)",
                "data 0.6.2 (core)",
                "generator 1.2.0 (core)",
                "org 1.8.1 (core)",
                "salesforcedx 51.0.2 (pre-release)",
                "├─ schema 1.0.3",
                "├─ user 1.1.0",
                "├─ limits 1.0.3",
                "├─ apex 0.1.4",
                "├─ salesforce-alm 51.0.1",
                "├─ custom-metadata 1.0.11",
                "├─ templates 51.1.0",
                "└─ @salesforce/sfdx-plugin-lwc-test 0.1.7",
                "sfdx-cli 7.121.8 (core)",
                "source 1.2.2",
                "telemetry 1.2.6 (core)",
                "trust 1.0.8 (core)"
        ],
        "osVersion": "Windows_NT 10.0.22000"
}
```

**Comment by mattisdada** [comment]
This is a common issue with `cmd` commands that do not wrap paths in quotation marks which is what I imagine has happened here

**Comment by mshanemc** [comment]
Possibly unrelated to your issue, but you really need to uninstall the `salesforcedx` plugin.

**Comment by RodEsp** [comment]
Hey @mattisdada sorry about that. We actually just made [a change](https://github.com/salesforcecli/sfdx-cli/pull/282) to how `sf` is installed when running `npm install sfdx-cli -g` which should fix your issue.

This was just released under the `latest-rc` tag and you'll be able to install it by running:
1. `npm uninstall sfdx-cli -g`
2. `npm install sfdx-cli@latest-rc -g`

Please let us know if that fixes your problem and we'll go ahead and close this issue.
`latest-rc` will be released under `latest` next Thursday per our normal release schedule.

**Comment by mattisdada** [comment]
Hmm,, I didn't have it installed via npm, I used the Windows installer....  So that may have issues as well?

But I'll give it a crack when I can return back to my work machine and install RC and uninstall the old plugin and let you know if that fixed it <3

**Comment by mattisdada** [comment]
Can confirm the plugin `salesforcedx` was not a contributing factor and have removed it. It appears I couldn't installed `sfdx-cli@latest-rc` globally, [Volta](https://volta.sh) couldn't find the executable.

```
+ sfdx-cli@7.123.0
added 1599 packages from 738 contributors in 230.412s
Volta error: Could not determine the name of the package that was just installed.
```

I guess I'll wait until the stable release on Thursday and update this issue accordingly.

**Comment by mattisdada** [comment]
This is still an issue in `7.123` when installed via Windows Installer package sadly :( 

```powershell
> sfdx update
sfdx-cli: Updating CLI from 7.122.1-5e1c7e6 to 7.123.0-ebc9b0f... done
sfdx-cli: Updating CLI... done
sfdx-cli: Updating plugins... done
> sf
'C:\Users\Matt' is not recognized as an internal or external command,
operable program or batch file.
```

```powershell
> get-command sfdx

CommandType     Name                 Version    Source
-----------     ----                 -------    ------
Application     sfdx.cmd             0.0.0.0    C:\Program Files\Salesforce CLI\bin\sfdx.cmd

> get-command sf

CommandType     Name                 Version    Source
-----------     ----                 -------    ------
Application     sf.exe               0.0.0.0    C:\Users\Matt Work\AppData\Local\Volta\bin\sf.exe
```

**Comment by cristiand391** [comment]
@mattisdada can you check if `sf` was updated when you ran `sfdx update`?
It should be v1.1.0:
```
sf --version
@salesforce/cli/1.1.0 darwin-x64 node-v14.18.1
```

**Comment by mattisdada** [comment]
No, the command cannot be executed :) . I checked the `sf-cli` files at `%LOCALAPPDATA%\sfdx\client\7.123.0-ebc9b0f\sf-cli\bin` and they were last modified `2021-10-15` and the files at `dist` were last modified on `2021-10-22`.

If I execute the `run.cmd` that is in `bin` I get:

```
❯ .\run.cmd --version
@salesforce/cli/1.0.7 win32-x64 node-v14.18.1
```

So it looks like `sfdx --update` isn't updating it. I'll try and install the full Windows installer package again and update here.

**Comment by mattisdada** [comment]
After manually installing the package and running `sfdx --update` (which didn't perform any update), it still appears that the `sf-cli` is still at 1.0.7

**Comment by mattisdada** [comment]
I think this can be closed and I think the problem may be being caused by Volta. So I'll close this off for now. 

If anyone else runs into this issue:
https://github.com/volta-cli/volta/issues/1010#issuecomment-952376220

**Comment by RodEsp** [comment]
Thanks for the follow up @mattisdada. We've had reports of other issues when users are using Volta that are unfortunately out of our control. Usually I recommend using https://github.com/coreybutler/nvm-windows on Windows and https://github.com/nvm-sh/nvm for Mac/Linux to manage node versions.

**Comment by mattisdada** [comment]
I've had nothing but issues with `nvm` on both Windows and Linux :( 

I've had much fewer issues with Volta, although this space issue is a pain. I regret creating a profile with a space in it, many *nix tools have issues....
