### ISSUE TITLE
A project created with the empty template should still include a package.json file for LWC (and maybe some other files)

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#1235]
This came up in a recent discussion with some folks and I thought I'd log it here for consideration. When you create an SFDX project as follows:

```
sfdx force:project:create -d dir -n name -t empty
```

you end up with the following files in the new project:

```
config/project-scratch-def-json
README.md
sfdx-project.json
.forceignore
```

When you create an SFDX project as follows:

```
sfdx force:project:create -d dir -n name -t standard
```

you end up with the following files in the new project:

```
config/project-scratch-def.json
README.md
sfdx-project.json
.husky/pre-commit
.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
force-app/main/default/lwc/.eslintrc.json
force-app/main/default/aura/.eslintrc.json
scripts/soql/account.soql
scripts/apex/hello.apex
.eslintignore
.forceignore
.gitignore
.prettierignore
.prettierrc
jest.config.js
package.json
```

That seems like too much of a gap, with the empty project missing some things that are actually required for productive development, specifically `package.json` which includes the dependencies for LWC development in ES6, but also the .

Now perhaps instead of adding to the "empty" template, there should be another template that represents a midpoint between the current "empty" and "standard" templates, specifically the following that can be used by other tooling to support a more complete developer experience:

```
force-app/main/default/lwc/.eslintrc.json
force-app/main/default/aura/.eslintrc.json
.eslintignore
jest.config.js
package.json
```

All of those files provide guidance to the tooling associated with Salesforce development--specifically LWC--about how to behave without assuming the use of specific tooling such as VS Code, Git, Prettier, etc. Perhaps this could be a template called something like "minimal"?

Thoughts?

**Comment by mshanemc** [comment]
4 things:

1. Makes total sense to me, but
1. That's owned by the VSCode folks, and
1. They're open to PRs ([link to that project templates](https://github.com/forcedotcom/salesforcedx-templates/tree/develop/packages/templates/src/templates)), OR
1. They're also working on a "bring-your-own-templates-repo" feature so teams can make up their own templates/boilerplate/standards/linters and use those in `sfdx create` commands (that repo is not just project, but classes, lwc, etc)

Y'all can decide if your template is half-empty or half-full.  😄

**Comment by SCWells72** [comment]
Thanks @mshanemc. I think until the BYOT option is available, what I'll do is add a new pseudo-template to IC2 called `recommended` that uses `default` when generating the project, then removes things that aren't applicable before handing control over to the user. Of course, `default` will still be an available template option alongside `empty` and `analytics`, but this pseudo-template will also be included, and in fact will be the default for IC2 (though it retains the last option used as well).
