### ISSUE TITLE
SDR forceignore error on matchingContentFile types

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#1238]
### Summary
When doing source:retrieve, SDR throws from [here](https://github.com/forcedotcom/source-deploy-retrieve/blob/ad4883b6e68a5a8530c3918d795181b07d1608da/src/resolve/adapters/matchingContentSourceAdapter.ts#L48) if you are

1. retrieving at least one apex class
2. have at least one apex class in your forceignore that's also trying to be retrieved

I have not tried this with 
### Steps To Reproduce:
1. Create an empty project and scratch org
2. Create two apex classes in an org (via ui, dev console, etc) `Class1` and `Class2`
3. Put on in the forceignore like this `**/Class1.cls`
4. `sfdx force:source:retrieve -m ApexClass`

### Expected result
retrieves nonIgnored Class2

### Actual result
`ERROR running force:source:retrieve:  Metadata API request failed: ApexClass types require source to be present and unpackaged/classes/Class1.cls is forceignored.`

### System Information

```json
{
        "cliVersion": "sfdx-cli/7.121.4",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v14.18.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.21 (core)",
                "apex 0.2.9 (core)",
                "auth 1.7.2 (core)",
                "config 1.2.40 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.2 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.2 (core)",
                "org 1.8.1 (core)",
                "release-management 2.2.2",
                "└─ trust 1.0.8",
                "salesforce-alm 52.6.0 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.121.4 (core)",
                "sfdx-migration-automatic 4.2.1",
                "shane-sfdx-plugins 4.43.0",
                "├─ @mshanemc/plugin-streaming 1.1.7",
                "└─ @mshanemc/sfdx-sosl 1.1.0",
                "source 1.2.2 (core)",
                "telemetry 1.2.5 (core)",
                "templates 52.3.0 (core)",
                "user 1.5.0 (core)"
        ],
        "osVersion": "Darwin 19.6.0"
```

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10037181](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000Gf1gbYAB/view)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10037182](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000Gf5LuYAJ/view)
