### ISSUE TITLE
Private Class does not change to Public

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1239]
### Summary

I created a Private class, deployed it with success. Then I decided to change it to Public. Deployed it again, received a success message, but the class did not change to Public. 

Obs: Maybe it is an API issue and not caused by sfdx

### Steps To Reproduce:

1 - Create Private Class
2 - Deploy it 
3 - Verify you got a Success Message
4 - Change it to Public
5 - Deploy it
6 - Verify you got a Success Message
7 - Open the class in Salesforce and Verify it did not change to Public

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

### Expected result

Sfdx should overwrite the class no matter what are the changes

### Actual result

sfdx did not changed the class

### System Information

![image](https://user-images.githubusercontent.com/55927613/137524006-8864df0b-e118-4153-a64f-bc33f06d450b.png)

**Comment by cristiand391** [comment]
```apex
// Foo.cls
public with sharing class Foo {
    public Foo() {

    }
    private class Bar {
    
    }
}
```
Created class locally, then deployed it:
`sfdx force:source:deploy --metadata=ApexClass:Foo`

I can see it as private in my org, after that I change `Bar` to `public`, deploy it again and can see it has been updated.

Are you able to reproduce this again or in another org? I've tried a few times and with `sfdx-cli/7.122.1` but always get the same result.
