### ISSUE TITLE
Error "Unexpected child metadata" with "force:source:retrieve" command when I try to retrieve any component 

### ISSUE THREAD

**Issue by JavierCarvajalLBS** [forcedotcom/cli#1241]
Recently, when I try to execute a **force:source:retrieve** command in VS Code to get any component from the SFDC connected org, I receive the error message:

_Unexpected child metadata [<local-root>\Activity-bg\Activity_Group__c.fieldTranslation-meta.xml] found for parent type [CustomObjectTranslation]_

![image](https://user-images.githubusercontent.com/71261684/137722918-cdd35172-440c-4d68-931d-3f93b634e13e.png)
![image](https://user-images.githubusercontent.com/71261684/137722939-9c30858c-7df8-40ab-89b3-db19b263a9c4.png)

It is received using a package.xml, or specifying the specific component to be retrieved, and even when neither object Activity, nor Activity Group field nor any object translation is involved in the retrieve command.
If I delete that CustomObjectTranslation from local, the same error message is received but from a different field from the Activity object. If I delete the Activity object from local, I receive the same error message, but from a different object.

I guess it is some kind of error related to the project structure local, but I can´t find the reason because the error message is not helping.

**Comment by cristiand391** [comment]
This seems like a duplicate of https://github.com/forcedotcom/cli/issues/1241

Regarding other errors when you delete the Activity object, did you start to see these recently after an update or are you still reorganizing your project structure?

**Comment by JavierCarvajalLBS** [comment]
It is not a duplicate, actually it is #1241

I don´t want to delete the Activity object. I have all my SF org in the repository and all was working fine (in fact I could execute the retrieve for all the components without any problem), but suddenly I received that error message when I tried to retrieve again some components that were been updated in the SF UI.

I just can use the source:force:retrieve command with the --sourcepath but I need to have the component already in my project to use it and I can´t retrieve more than one component at a time. If I try to use with --manifest to use a package.xml or with -m to retrieve just one component, I receive the Unexpected child metadata error message.

**Comment by JavierCarvajalLBS** [comment]
I´m still investigating this issue and I can see that in my force-app\main\default\objectTranslations folder I have objectTranslation-meta.xml files and fieldTranslation-meta.xml files.

- objectTranslation XML files contain a CustomObjectTranslation element with different elements inside the object (fieldsets, recordtypes, validationrules,...)
- fieldTranslation XML files instead contain a CustomFieldTranslation element with the different elements inside the field (label, name, picklistvalues,...)

It is normal? Because the error message is saying that it has found an unexpected child metadata fieldTranslation XML for parent type CustomObjectTranslation, and maybe it is because the objectTranslations folder just can have objectTranslation XML files.
My concern is because that folder structure was created retrieving the metadata from the SF org using a package.xml file generated with the SF package.xml generator tool.

**Comment by JavierCarvajalLBS** [comment]
I think I´ve found the reason for this problem.

The main cause is because in some objectTranslation folders there isn´t an objectTranslation XML file.
If I add an objectTranslation XML file in the folder which is raising the error, that error disappears.
My main concern is why some objectTranslation folders contain an objectTranslation XML file but other folders do not.

I use the Salesforce Package.xml Generator plugin in VSC and I know that I have to include in the package.xml the objects that I want to retrieve the translation from, and I included all the objects, and fields in the same package.xml which contains the objectranslations so I don´t know why some objects have the objectTranslation file but other objects do not.

**Comment by cristiand391** [comment]
Sorry, I pasted the wrong link, dup: https://github.com/forcedotcom/cli/issues/1233.

This started to happen after this PR: https://github.com/forcedotcom/source-deploy-retrieve/pull/461

> If I add an objectTranslation XML file in the folder which is raising the error, that error disappears.

Yes, as other user has commented in the issue above, that's the current workaround 👍🏼

**Comment by JavierCarvajalLBS** [comment]
Does nobody know how to avoid this problem?
Because if I´ve tried to retrieve all the translations from my SF org, and the objectTranslation files are still missing.

**Comment by IVerkhosh** [comment]
Have the same issue, after updating to version 7.120 and 7.123

**Comment by WillieRuemmele** [comment]
Hi @IVerkhosh @JavierCarvajalLBS thanks for the patience. This issue has been addressed [here](https://github.com/forcedotcom/source-deploy-retrieve/pull/485) and will be released the `latest-rc` v7.125.0 release of the CLI later today

**Comment by DonAnam** [comment]
Still having this issue after updating to latest-rc: 7.125.0 Anyone knows how to get this resolved?

**Comment by MorganMarchese** [comment]
This is still not fixed, 11/10/2021. Still happening when retrieving or pushing metadata using a package.xml file.

**Comment by shetzel** [comment]
@MorganMarchese - what is the output of `sfdx version --verbose`?  Do you have a repo (with sample package.xml) we can use to reproduce this issue?  What is the stack trace when you append `--dev-debug` when running the command?

**Comment by firatesmer** [comment]
I have the same issue. I have a folder in my project called `objects` and raising the error and when I change the name of the folder, the error goes away.

sfdx-cli/7.126.0 win32-x64 node-v16.13.0
Error message: `Unexpected child metadata [\force-app\main\default\classes\enums\objects\cardPaymentMethod\CardPaymentMethodCategory.cls-meta.xml] found for parent type [CustomObject]`

**Comment by emrealtan-osf** [comment]
Same here for sfdx-cli/7.124.0 win32-x64 node-v14.18.1

**Comment by karlamartinezh** [comment]
Hello!! same error with the version sfdx-cli/7.127.0 win32-x86 node-v16.13.0 , any solution? 

In my case this was the error "**Unexpected child metadata [\force-app\main\default\objectTranslations\Activity-pt_PT\Accepted_Information__c.fieldTranslation-meta.xml] found for parent type [CustomObjectTranslation]**"

**Comment by mgrygielSii** [comment]
> Sorry, I pasted the wrong link, dup: #1233.
> 
> This started to happen after this PR: [forcedotcom/source-deploy-retrieve#461](https://github.com/forcedotcom/source-deploy-retrieve/pull/461)
> 
> > If I add an objectTranslation XML file in the folder which is raising the error, that error disappears.
> 
> Yes, as other user has commented in the issue above, that's the current workaround 👍🏼

**WORKAROUND:** As stated above, just create a OBJECT_NAME.objectTranslation-meta.xml in the folder that is causing problem.

**Example:**
Starting SFDX: Retrieve Source from Org
Unexpected child metadata [\force-app\main\default\objectTranslations\Opportunity-en_US\amount_opportunity.fieldTranslation-meta.xml] found for parent type [CustomObjectTranslation]

The current folder structure:
/objectTranslations
--/Opportunity-en_US
----/amount_opportunity.fieldTranslation-meta.xml

A desired folder structure:
/objectTranslations
--/Opportunity-en_US
----/amount_opportunity.fieldTranslation-meta.xml
----/Opportunity-en_US.objectTranslation-meta.xml <- create this file with basic XML

After creating the main obj Translation file, SFDX behaves as expected.

Hope somebody will benefit from this.
Thx, Marek.

**Comment by hhssuuyyaa** [comment]
> I have the same issue. I have a folder in my project called `objects` and raising the error and when I change the name of the folder, the error goes away.
> 
> sfdx-cli/7.126.0 win32-x64 node-v16.13.0 Error message: `Unexpected child metadata [\force-app\main\default\classes\enums\objects\cardPaymentMethod\CardPaymentMethodCategory.cls-meta.xml] found for parent type [CustomObject]`

This worked for me too. Weird issue, hope this gets fixed in latest cli.

**Comment by shetzel** [comment]
Seems there are multiple issues being reported here.

1. Unexpected child metadata for CustomObject.  This will happen when you have metadata that is not part of a CustomObject within a directory containing "objects" in the path.  In the examples reported above there are apex classes inside an objects directory.  The way the SDR library's metadata file parsing currently works, when trying to categorize the metadata file into a type it will first check if the path matches a well known directory name such as "objects" and if it does, it uses it to determine the type classification.  To fix this problem you can remove the "objects" directory from the path.  There is an item in the backlog to change the type detection logic to first look at the file suffix to determine the type and that would fix this issue.  That fix will come within a few weeks.
2. Unexpected child metadata for CustomObjectTranslation.  This shouldn't happen anymore with recent (7.125.0 and later) CLI plugins.  If it does, we're looking for a repro.  A CustomFieldTranslation should never exist without a CustomObjectTranslation.  If it does, then however that retrieve happened is where the bug is.  I've seen in the posts above that this might be happening from VS Code so maybe it's a bug for that action but not the CLI.  If someone has a way to reproduce this only in the CLI please post here.  Without a repro, nothing is being done to fix this.

**Comment by JavierCarvajalLBS** [comment]
@shetzel I´m still having the same issue today:

Metadata API request failed: Component conversion failed: Unexpected child metadata [\force-app\main\default\objectTranslations\efl__EFL_Child_Objects_List__c-en_US\efl__Object_Name__c.fieldTranslation-meta.xml] found for parent type [CustomObjectTranslation]

I´m using a package.xml with all the CustomObject included and using the wildcard * in the CustomObjectTranslation component (I need to retrieve all the components in the org).

After investigation, this issue is just with one managed-package component (component efl__EFL_Child_Objects_List__c from the managed package Enhanced Files List). If I remove the component of the list of CustomObject elements in the package.xml, no issue is raised. If the object is in the list, a CustomObjectTranslation file is created during the retrieve and the error raises. The main problem is that I can´t remove the object name because we have to retrieve all the custom objects in the org using the wildcard (*) and, in that case, the error always raises

And it is my system configuration:
{
"cliVersion": "sfdx-cli/7.127.0",
"architecture": "win32-x64",
"nodeVersion": "node-v16.13.0",
"pluginVersions": [
"@oclif/plugin-autocomplete 0.3.0 (core)",
"@oclif/plugin-commands 1.3.0 (core)",
"@oclif/plugin-help 3.2.3 (core)",
"@oclif/plugin-not-found 1.2.4 (core)",
"@oclif/plugin-plugins 1.10.1 (core)",
"@oclif/plugin-update 1.5.0 (core)",
"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
"@oclif/plugin-which 1.0.3 (core)",
"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
"alias 1.1.22 (core)",
"apex 0.3.0 (core)",
"auth 1.7.5 (core)",
"config 1.2.47 (core)",
"custom-metadata 1.0.12 (core)",
"data 0.6.4 (core)",
"generator 1.2.1 (core)",
"limits 1.2.3 (core)",
"org 1.9.0 (core)",
"salesforce-alm 53.4.2 (core)",
"schema 1.0.10 (core)",
"sfdx-cli 7.127.0 (core)",
"source 1.4.0 (core)",
"telemetry 1.2.8 (core)",
"templates 52.6.0 (core)",
"trust 1.0.10 (core)",
"user 1.5.2 (core)"
],
"osVersion": "Windows_NT 10.0.18362"
}

**Comment by JavierCarvajalLBS** [comment]
More investigation on the issue:

1. If I generate a package.xml with just the CustomObject efl__EFL_Child_Objects_List__c inside, the retrieve command works fine and **retrieves the CustomObject metadata file and a CustomField metadata file**.
2. If I generate a package.xml with just the CustomObjectTranslation efl__EFL_Child_Objects_List__c-en_US inside, the retrieve command works fine but **it doesn´t retrieve anything**.
3. If I generate a package.xml with both, the CustomObject and the CustomObjectTranslation inside, the retrieve command **retrieves the CustomObject metadata file, a CustomField metadata file, a fieldTranslation metadata field, and raises the error**.

**Comment by mshanemc** [comment]
Thanks for the help in narrowing this down do the CustomObjectFieldTranslation (my least favorite metadata type), especially that last investigation.  I'm mentioning them here so those issues link to this one.

https://github.com/forcedotcom/cli/issues/1262
https://github.com/forcedotcom/cli/issues/1233

**Comment by estrng** [comment]
Does anyone have information about when this issue will be fixed? I'm having some problems with my Project Sprint to the end of the year.

**Comment by WillieRuemmele** [comment]
Hi @estrng this is in our current sprint, however, due to the holidays we won't be releasing until the 6th. At the earliest, it would be in the `latest-rc` build then. There are workarounds mentioned above

**Comment by estrng** [comment]
> Hi @estrng this is in our current sprint, however, due to the holidays we won't be releasing until the 6th. At the earliest, it would be in the `latest-rc` build then. There are workarounds mentioned above

Thank you.

**Comment by dpuza-formativ** [comment]
> Seems there are multiple issues being reported here.
> 
> 1. Unexpected child metadata for CustomObject.  This will happen when you have metadata that is not part of a CustomObject within a directory containing "objects" in the path.  In the examples reported above there are apex classes inside an objects directory.  The way the SDR library's metadata file parsing currently works, when trying to categorize the metadata file into a type it will first check if the path matches a well known directory name such as "objects" and if it does, it uses it to determine the type classification.  To fix this problem you can remove the "objects" directory from the path.  There is an item in the backlog to change the type detection logic to first look at the file suffix to determine the type and that would fix this issue.  That fix will come within a few weeks.

@shetzel We're getting the #1, "Unexpected child metadata ... found for parent type [CustomObject]", but it's on this pattern:
\force-app\main\default\objects\X__c\listViews\Y.listview-meta.xml

It appears that if we delete these legitimate files, the errors go away...

**Comment by JavierCarvajalLBS** [comment]
Today I´ve received the same error message again using a package.xml file:

_Metadata API request failed: Component conversion failed: Unexpected child metadata [\force-app\main\default\objectTranslations\efl__EFL_Child_Objects_List__c-en_US\efl__Object_Name__c.fieldTranslation-meta.xml] found for parent type [CustomObjectTranslation]_

If I remove the CustomObjectTranslation type (that previously had the * member inside) from the package.xml file the retrieve operation is successful.

**Comment by klouisin** [comment]
I had the same error. If you have installed extension Salesforce CLI Integration latest version wich is 53.12.0 (or a recent one) you may have this issue. I solved the problem installing an older version : 53.0.0.
Regards

**Comment by shetzel** [comment]
The fix is in the latest CLI release published today.  sfdx version 7.133.0

**Comment by joaomrsilvaa** [comment]
I had the same issue, the problem for me was Uppercase sensitivity as I wrote FieldTranslation-meta.xml instead of fieldTranslation-meta.xml.

After this change, error disappear when I run sfdx retrieve command.

**Comment by cleverlemming** [comment]
I have the same issue trying to update OpportunityLineItem from my org. SFDX, VSCode, and extensions were all updated to latest version today but this made no difference. Error occurs when trying to download metadata for OpportunityLineItem. I think this defect needs to be reopened. 

`Unexpected child metadata [\src\Objects\OpportunityLineItem\fields\OpportunityLineItem.object-meta.xml] found for parent type [CustomObject]`

**Comment by cristiand391** [comment]
@cleverlemming this issue was about `CustomObjectFieldTranslation` which was already fixed. Can you please create a new one?

https://github.com/forcedotcom/cli/issues/new/choose

**Comment by wfsanchez** [comment]
I had got the same error. 

`Unexpected child metadata [random-file.xml] found for parent type [CustomObject]`

The problem was that someone misspell the name of the objects folder (Objetcs). After renamed it, all works fine.
