### ISSUE TITLE
Docker full images missing

### ISSUE THREAD

**Issue by jhgihub0** [forcedotcom/cli#1249]
On https://hub.docker.com/r/salesforce/salesforcedx/tags, where are the full images for 7.124.0 and 7.123.0?  I only see 7.124.0-slim and 7.123.0-slim.

Thank you.

**Comment by WillieRuemmele** [comment]
Hi @jhgihub0 we've had a few issues publishing the `full` build lately - I think we've ironed out all of the bugs and will have one up this Thursday

**Comment by jhgihub0** [comment]
Thank you
