### ISSUE TITLE
Error 'The action type "Outbound Messages" can't be used in flows with the process type "Autolaunched Flow"' when trying to deploy Record Triggered Flows using  sfdx force:source:deploy command

### ISSUE THREAD

**Issue by rajeswarr1** [forcedotcom/cli#1253]
### Summary

As part of the new feature released as part of Winter '22 release,  ( https://www.salesforceben.com/salesforce-flow-winter-22/ ), we were able to create a Record Triggered Flow flow using Action as a Workflow Outbound Message, in our Salesforce Org. But we are getting error while trying to deploy the same using _sfdx force:source:deploy_ command to another Org. 

### Steps To Reproduce:

1. Retrieve the Flow component using _sfdx force:source:retrieve_ command.
2. Deploy the same Record Triggered Flow component having action as Workflow Outbound message, using the  sfdx force:source:deploy command.

We are getting the below error when trying to deploy the Flow.

=== Component Failures [1]
TYPE   FILE                                                           NAME             PROBLEM
─────  ─────────────────────────────────────────────────────────────  
Error  sdx_sourceDeploy_pkg_1635177192290/flows/Sample_Flow.flow  Sample_Flow  outboundmsg (Action) - The action type "Outbound Messages" can't be used in flows with the process type "Autolaunched Flow".

We are able to deploy the same component using Change Set or Force Migration Tool, but not using sfdx cli plugin.

### Expected result

Component should get successfully deployed

### Actual result

Deployment Failed with above error. 

### System Information

{
        "cliVersion": "sfdx-cli/7.123.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.18.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "alias 1.1.22 (core)",
                "auth 1.7.3 (core)",
                "config 1.2.41 (core)",
                "generator 1.2.0 (core)",
                "salesforcedx 51.16.0 (51.16.0)",
                "├─ data 0.4.10",
                "├─ apex 0.2.2",
                "├─ custom-metadata 1.0.12",
                "├─ schema 1.0.7",
                "├─ limits 1.2.1",
                "├─ @salesforce/sfdx-plugin-lwc-test 0.1.7",
                "├─ org 1.6.6",
                "├─ user 1.3.0",
                "├─ templates 51.5.0",
                "└─ salesforce-alm 51.6.26",
                "sfdx-cli 7.123.0 (core)",
                "source 1.2.4 (core)",
                "telemetry 1.2.8 (core)",
                "trust 1.0.8 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19043"
}

### Additional information

![image](https://user-images.githubusercontent.com/61693173/138752280-c403b97a-675b-466b-a340-e0ebe3fa5d8a.png)

**Comment by WillieRuemmele** [comment]
you'll need to uninstall the `salesforcedx` plugin with `sfdx plugins:uninstall salesforcedx` to get the latest versions of commands. That command should print something like 
```
{
	"cliVersion": "sfdx-cli/7.123.1",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v12.20.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.3 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.1.22 (core)",
		"apex 0.3.0",
		"auth 1.7.3 (core)",
		"command-reference 1.3.4",
		"config 1.2.41 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.3 (core)",
		"generator 1.2.1 (core)",
		"limits 1.2.2 (core)",
		"org 1.8.3 (core)",
		"salesforce-alm 53.0.0 (core)",
		"schema 1.0.10 (core)",
		"sfdx-cli 7.123.1 (core)",
		"source 1.2.4 (core)",
		"telemetry 1.2.8 (core)",
		"templates 52.4.0 (core)",
		"trust 1.0.10 (core)",
		"user 1.5.2 (core)"
	],
	"osVersion": "Darwin 19.6.0"
}

```

**Comment by rajeswarr1** [comment]
Thanks for your reply @WillieRuemmele  
Tried the above command and we are still getting the same error.
![image](https://user-images.githubusercontent.com/61693173/138923237-57a409af-2232-4722-a86e-a4250acfaae8.png)

Below is the plugin version details. 

```
{
    "cliVersion": "sfdx-cli/7.123.0",
    "architecture": "win32-x64",
    "nodeVersion": "node-v14.18.1",
    "pluginVersions": [
        "@oclif/plugin-autocomplete 0.3.0 (core)",
        "@oclif/plugin-commands 1.3.0 (core)",
        "@oclif/plugin-help 3.2.3 (core)",
        "@oclif/plugin-not-found 1.2.4 (core)",
        "@oclif/plugin-plugins 1.10.1 (core)",
        "@oclif/plugin-update 1.5.0 (core)",
        "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
        "@oclif/plugin-which 1.0.3 (core)",
        "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
        "alias 1.1.22 (core)",
        "apex 0.3.0 (core)",
        "auth 1.7.3 (core)",
        "config 1.2.41 (core)",
        "custom-metadata 1.0.12 (core)",
        "data 0.6.3 (core)",
        "generator 1.2.0 (core)",
        "limits 1.2.2 (core)",
        "org 1.8.3 (core)",
        "salesforce-alm 53.0.0 (core)",
        "schema 1.0.10 (core)",
        "sfdx-cli 7.123.0 (core)",
        "source 1.2.4 (core)",
        "telemetry 1.2.8 (core)",
        "templates 52.4.0 (core)",
        "trust 1.0.8 (core)",
        "user 1.5.2 (core)"
    ],
    "osVersion": "Windows_NT 10.0.19043"
}
```
The difference as compared to your response, is in the cli version and while trying to update the sfdx version it gives me the below response. Please advise. 

![image](https://user-images.githubusercontent.com/61693173/138923896-1e8998bb-8560-4500-b232-57139c94ef9e.png)

**Comment by WillieRuemmele** [comment]
Thanks @rajeswarr1 did this problem start happening after a certain CLI release?  I'm not 100% sure that this is a CLI issue, if it was able to `retrieve` the metadata type, it _should_ be able to `deploy` it too, unless the org you're deploying too doesn't support it. Are you setting any api version configs or environment variables?

you mentioned you can Change Sets or the Force Migration Tool, are you targeting the same org regardless of tool used to deploy it?

Can you try `force:source:convert`ing the metadata and then using an `mdapi:deploy`? If that still fails then that points to issues in the org setup.

**Comment by rajeswarr1** [comment]
I tried few things based on your comment and I found the cause of the issue.

Going by your suggestion, I used `force:source:convert` command to convert the metadata component and then deploy using  `mdapi:deploy`. While deploying I found below two observations:
1. With api version as 52.0 in the package xml the component deployment was throwing same error as above.
2. With api version as 53.0 in the package xml the component deployment went through fine. (guessing by the fact that this is a new feature as part of Winter '22 release)

The same was the case with deploying using Force Migration Tool, where I had initially specified the version as 53.0 leading to successful deployment of the component.

While reading through other docs I came across that, though i specify api version as 53.0 in `force:source:deploy` command, I still had to update the api version in _sfdx-project.json_ file

**sfdxproject
├─ force-app
└─ sfdx-project.json**

![image](https://user-images.githubusercontent.com/61693173/138931286-b6f19d3a-997b-4a41-9d96-a4e672434490.png)

The `sourceApiVersion `inside the _sfdx-project.json_ file was found to be v52.0 and post updating the version to 53.0, I was able to successfully deploy the component.

Apart from updating the version manually in the  _sfdx-project.json_ file, is there a way to update the version programmatically using sfdx commands, since we are in the process of automating the deployment scripts and updating manually under all sfdx projects would be an overhead.

Thanks again for your response.

**Comment by WillieRuemmele** [comment]
@rajeswarr1 I'm glad you fixed your issue 🎉 

yes, unfortunately, `sourceApiVersion` and `apiVersion` are two different things. I don't know any programmatic way to set that.

I did a little googling and found [this](https://github.com/muenzpraeger/sfdx-plugin/blob/master/README.md) plugin which _might_ set it, it's hard to tell from the docs. 

You can always write your own cli-plugin to read that file and set it accordingly too 👍

**Comment by rajeswarr1** [comment]
Thank you @WillieRuemmele I will try those out. But would really appreciate if _sfdx plugin_ can have a command to handle that, since it will come in handy especially when using multiple Orgs, whose version are not the same (lower vs higher Org).
