### ISSUE TITLE
ERROR running force:lightning:lwc:test:create:  No corresponding HTML file found

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1254]
### Summary

I have a component which does not have .html. 
It is a component that extends a Base/Parent component that takes care of the rendering.

### Steps To Reproduce:

1 - Create a Base component
2 - Create a Child component that extends the base
3 - Delete the child's html file
4 - run `sfdx force:lightning:lwc:test:create` or use the vscode command `SFDX: Create Lightning Web Component Test` to create a test spec for your component
5 - verify you get this error message: `ERROR running force:lightning:lwc:test:create:  No corresponding HTML file found for `
6 - create .html for your component
7 - repeat step 4
8 - verify that the test spec was created and no error message was displayed

### Expected result

`sfdx force:lightning:lwc:test:create` should not care about if there is or not a .html file. 

### Actual result

`sfdx force:lightning:lwc:test:create` does not allow us to create test spec because the component does not have .html

### System Information

sfdx-cli/7.122.1 win32-x64 node-v14.18.0

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10093476](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000JmH5jYAF/view)

**Comment by AllanOricil** [comment]
@WillieRuemmele why it was labeled with "owned by other team" if it is a sfdx bug?

**Comment by WillieRuemmele** [comment]
Hi @AllanOricil the bug has been assigned to the team that owns that command. SFDX is comprised of many teams
