### ISSUE TITLE
Running sf deploy uses v52.0 platform version even thought I set my apiVersion to 53.0

### ISSUE THREAD

**Issue by msrivastav13** [forcedotcom/cli#1255]
### Summary

I am using the new `sf deploy` to deploy application metadata to a Scratch org. The command uses **v52.0** instead of the latest version **v53.0**

### Steps To Reproduce:

1.  Clone the repo https://github.com/dreamhouseapp/dreamhouse-lwc
2.  Authorize using `sf login`
3. Deploy the force-app/main/default folder using `sf deploy`
4. Watch that the deployment is using v52.0 as the deployment fails

### Expected result
Deployment should succeed and it does with `sfdx force:source:deploy`

### Actual result

Deployment fails due to version used to deploy is v52.0 and the metadata in the repo is not compatible with v52.0 as it is upgraded to v53.0

### System Information

```
sf version
@salesforce/cli/1.0.2 darwin-x64 node-v14.17.0
```
```

@oclif/plugin-help 5.1.1 (core)
@oclif/plugin-not-found 2.2.0 (core)
@oclif/plugin-plugins 2.0.0 (core)
@salesforce/cli 1.0.2 (core)
config 2.2.6 (core)
deploy-retrieve 1.0.2 (core)
deploy-retrieve-metadata 1.0.1 (core)
env 1.0.0 (core)
functions 1.0.2 (core)
generate 1.0.1 (core)
login 1.0.0 (core)
telemetry 1.2.4 (core)
```

**Comment by mdonnalley** [comment]
@msrivastav13 can you try updating to the latest version of `sf` (1.1.5) and let us know if you still see this issue?

**Comment by msrivastav13** [comment]
@mdonnalley How do I update the sf? An `sfdx update` says I am on latest and` sf --version` says I am on @salesforce/cli/1.0.2

**Comment by mdonnalley** [comment]
you can use `npm install -g @salesforce/cli` to get the latest

**Comment by msrivastav13** [comment]
This works now but note `sfdx update` does not update `sf` at this point. I had to  do `npm install -g @salesforce/cli` to get latest `sf` executable
