### ISSUE TITLE
ERROR running auth:jwt:grant:  We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Torsen** [forcedotcom/cli#1257]
### Summary

ERROR running auth:jwt:grant:  We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Unexpected end of JSON input

### Steps To Reproduce:

1. Generate a Self signed Certificate:

` openssl genrsa -des3 -passout pass:SomePassword -out server.pass.key 2048

Generating RSA private key, 2048 bit long modulus
.............+++
..........................................................+++
e is 65537 (0x10001)

 
openssl rsa -passin pass:SomePassword -in server.pass.key -out server.key

writing RSA key
 
openssl req -new -key server.key -out server.csr

You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) []:ES
State or Province Name (full name) []:Barcelona
Locality Name (eg, city) []:Barcelona
Organization Name (eg, company) []:Aigues de Barcelona
Organizational Unit Name (eg, section) []:
Common Name (eg, fully qualified host name) []:aiguesdebarcelona.cat
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:

 daniel.vazquez  ~/JWT  openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.crt

Signature ok
subject=/C=ES/ST=Barcelona/L=Barcelona/O=Aigues de Barcelona/CN=aiguesdebarcelona.cat
Getting Private key`

1. Create a Connected App in salesforce and set the certificate (server.crt)
1. Approve your user to use it
1.  sfdx force:auth:jwt:grant -i CONNECTED_APP_ID -f server.key -r INSTANCE_URL -u USERNAME -a jwtTest

### Expected result

JWT Granted login

### Actual result

{
  "status": 1,
  "name": "JwtGrantError",
  "message": "We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Unexpected end of JSON input",
  "exitCode": 1,
  "commandName": "Grant",
  "stack": "JwtGrantError: We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Unexpected end of JSON input\n    at Function.create (/Users/daniel.vazquez/.local/share/sfdx/client/7.123.0-ebc9b0f/node_modules/@salesforce/plugin-auth/node_modules/@salesforce/core/lib/sfdxError.js:160:16)\n    at Grant.run (/Users/daniel.vazquez/.local/share/sfdx/client/7.123.0-ebc9b0f/node_modules/@salesforce/plugin-auth/lib/commands/auth/jwt/grant.js:31:36)\n    at async Grant._run (/Users/daniel.vazquez/.local/share/sfdx/client/7.123.0-ebc9b0f/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/Users/daniel.vazquez/.local/share/sfdx/client/7.123.0-ebc9b0f/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/Users/daniel.vazquez/.local/share/sfdx/client/7.123.0-ebc9b0f/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/Users/daniel.vazquez/.local/share/sfdx/client/7.123.0-ebc9b0f/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/daniel.vazquez/.local/share/sfdx/client/7.123.0-ebc9b0f/dist/cli.js:162:47)",
  "warnings": []
}

### System Information

{
	"cliVersion": "sfdx-cli/7.123.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v14.18.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.3 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-diff 0.0.6",
		"@salesforce/sfdx-scanner 2.12.0",
		"alias 1.1.22 (core)",
		"auth 1.7.3 (core)",
		"config 1.2.41 (core)",
		"generator 1.2.0 (core)",
		"salesforcedx 52.0.0",
		"├─ limits 1.2.1",
		"├─ custom-metadata 1.0.12",
		"├─ @salesforce/sfdx-plugin-lwc-test 0.1.7",
		"├─ apex 0.2.2",
		"├─ templates 51.5.0",
		"├─ user 1.3.0",
		"├─ salesforce-alm 52.0.0",
		"├─ org 1.6.6",
		"├─ data 0.4.11",
		"└─ schema 1.0.7",
		"sfdx-cli 7.123.0 (core)",
		"source 1.2.4 (core)",
		"telemetry 1.2.8 (core)",
		"trust 1.0.8 (core)"
	],
	"osVersion": "Darwin 20.6.0"
}

### Additional information

Screen of my terminal
![Screenshot 2021-10-28 at 12 54 32](https://user-images.githubusercontent.com/2922027/139242236-b94ccf4a-e0c1-49e0-9c13-23238b684424.png)

**Comment by mshanemc** [comment]
Please uninstall salesforcedx `sfdx plugins:uninstall salesforcedx` and try again.

**Comment by ar-srinivas** [comment]
@Torsen @mshanemc @WillieRuemmele is this issue resolved?
I am using 7.134 and facing exactly the same issue with jwt command.

{
  "status": 1,
  "name": "JwtGrantError",
  "message": "We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Unexpected end of JSON input",
  "exitCode": 1,
  "commandName": "Grant",
  "stack": "JwtGrantError: We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Unexpected end of JSON input\n    at Function.create (/home/ubuntu/7.134/node_modules/@salesforce/core/lib/sfdxError.js:160:16)\n    at Grant.run (/home/ubuntu/7.134/node_modules/@salesforce/plugin-auth/lib/commands/auth/jwt/grant.js:31:36)\n    at async Grant._run (/home/ubuntu/7.134/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/home/ubuntu/7.134/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/home/ubuntu/7.134/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/home/ubuntu/7.134/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/home/ubuntu/7.134/dist/cli.js:162:47)",
  "warnings": [
    "apiVersion configuration overridden at \"54.0\""
  ]
}

**Comment by nzhdanova-intellective** [comment]
Any idea how it can be resolved? I have the same error: 
{
  "status": 1,
  "name": "JwtGrant",
  "message": "We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Unexpected end of JSON input",
  "exitCode": 1,
  "context": "Grant",
  "stack": "JwtGrant: We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Unexpected end of JSON input\n    at Messages.createError (C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\core\\lib\\messages.js:446:16)\n    at Grant.run (C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\plugin-auth\\lib\\commands\\auth\\jwt\\grant.js:35:28)\n    at async Grant._run (C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:102:40)\n    at async Config.runCommand (C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\core\\lib\\config\\config.js:272:25)\n    at async run (C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\core\\lib\\main.js:76:5)",
  "warnings": [],
  "commandName": "Grant"
}
