### ISSUE TITLE
source tracking commands crashing with "unable to generate complete component set for"

### ISSUE THREAD

**Issue by WillieRuemmele** [forcedotcom/cli#1265]
Summary
Short summary of what is going on or to provide context.

Steps To Reproduce:
Check out a mpd repo with multiple packages of a medium size project
Utilize sfdx force:source:beta:push -u
Notice the command generates an error ERROR running force:source:beta:push: unable to generate complete component set for
Expected result
The command will be able to successfully push all metadata into the org

Actual result
The command fails to execute push/pull

Additional information
Adding log levels provide with no additional context.

VS Code Version:

SFDX CLI Version:
7.125.0

OS and version:
Mac OS

created on behalf of @azlam-abdulsalam from [here](https://github.com/salesforcecli/plugin-source/issues/279)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10120357](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000LePi0YAF/view)
