### ISSUE TITLE
Is it possible to not require a --manifest when using the --predestructive flag on the source:deploy command

### ISSUE THREAD

**Issue by jbc329** [forcedotcom/cli#1266]
**Is your feature request related to a problem? Please describe.**

When we use the source deploy command without the new destructive changes flag, the command is intelligent enough to not require a package.xml. It would be terrific if we did not need to maintain one. 

**What are you trying to do**
A description of the outcome you are hoping to achieve 
Use the source:deploy command with the --predestructivechanges flag and not needing to provide a --manifest package.xml. Without using the --predestructive flag, we can deploy using --sourcepath. There is no need to 

Ideally, we would not need a pacakge.xml at all for the source:deploy command while using --predestructive. 

**Describe the solution you'd like**

Ideally, we would not need a pacakge.xml at all for the source:deploy command while using --predestructive.  Instead, allow us to use the --predestructive flag with --sourcepath.

**Describe alternatives you've considered**
The alternative for me is to use the mdapi convert command to dynamically create a package.xml and then steal the package.xml. This is somewhat feels like an unnecessary step. We want to deploy everything we are giving you in the force-app directory. 

**Additional context**
Thank you for your time and consideration. This tool is incredible.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10127033](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000LzyUhYAJ/view)

**Comment by WillieRuemmele** [comment]
Hi @jbc329 
>The alternative for me is to use the mdapi convert command to dynamically create a package.xml and then steal the package.xml. This is somewhat feels like an unnecessary step. We want to deploy everything we are giving you in the force-app directory.

we introduced the `force:source:manifest:create` command to get around this exact problem. It can also create destructive change manifests too :D `sfdx force:source:manifest:create --help`

**Comment by jbc329** [comment]
@WillieRuemmele you guys have thought of everything. I'll give the manifest:create command a try. Thank you for the idea about allowing the command to create the destructive files too, I really like that. Too often we see teams add a component to the destructiveChanges.xml, but they leave the file in the src directory. 

I sincerely appreciate your help.

**Comment by gdman** [comment]
I think this issue should be re-opened. I see there is a workaround but the command should actually be fixed too. It should be either --sourcepath **OR** --manifest are required when using the --destructiveChangesX arguments. Fundamentally, the --manifest argument shouldn't be required for using the destructive changes arguments.

**Comment by WillieRuemmele** [comment]
Hi @gdman 

yes, you're correct. The command _should_ support either `-p` or `-x` when using the destructive manifest flags. However, the manifest [parsing logic](https://github.com/forcedotcom/source-deploy-retrieve/blob/03f008a3810003ba409286fb76415cec28963924/src/collections/componentSet.ts#L196) is only exposed when using `-x`. At the time we thought using the `force:source:manifest:create` command with the `-p` parameter was a viable enough workaround.
