### ISSUE TITLE
Spellchecking of command options not working

### ISSUE THREAD

**Issue by randi274** [forcedotcom/cli#1268]
### Summary

So I fat-fingered the word version when trying to get the sfdx version, and a helpful prompt of `Warning: --verison is not a sfdx command.` appeared. But then the prompt to correct it followed, and no matter how many times I tried to agree with the new spelling, it wouldn't fix my error for me. How rude! 😆

### Steps To Reproduce:

1.  Type `sfdx --verison` or `sfdx verison` (or whichever misspelling of **version** you might prefer)
1.  Receive error `Did you mean version? [y/n]:`
1.  Type y
1.  Endless loop

### Expected result

When typing `y`, the correct command is populated. Or just tell me I'm wrong, and don't ask what I meant.

### Actual result

Endless loop.

### System Information

{
        "cliVersion": "sfdx-cli/7.124.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.10.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.22 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.4 (core)",
                "config 1.2.41 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.3 (core)",
                "generator 1.2.1 (core)",
                "limits 1.2.2 (core)",
                "org 1.8.4 (core)",
                "salesforce-alm 53.1.1 (core)",
                "schema 1.0.10 (core)",
                "sfdx-cli 7.124.0 (core)",
                "source 1.2.5 (core)",
                "telemetry 1.2.8 (core)",
                "templates 52.4.0 (core)",
                "trust 1.0.10 (core)",
                "user 1.5.2 (core)"
        ],
        "osVersion": "Darwin 20.6.0"
}

### Additional information

<img width="868" alt="Screen Shot 2021-11-04 at 1 21 12 PM" src="https://user-images.githubusercontent.com/9795193/140388327-11607635-2964-460c-8ba9-79dc35d90075.png">

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10133476](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000MMMOfYAP/view)

**Comment by cristiand391** [comment]
The linked WI above has been closed a few months ago.
Once `sfdx` finishes the migration to `@oclif/core` this shouldn't be a problem anymore 👍🏼
