### ISSUE TITLE
Extract recursive relations

### ISSUE THREAD

**Issue by mhumpolec** [forcedotcom/cli#127]
**Is your feature request related to a problem? Please describe.**
We want to be able to extract a hierarchy of records - imagine account and parent accounts.

**What are you trying to do**
We tried to insert the parent (or child) into the query, but it failed with error about overriding data

**Describe the solution you'd like**
Finish with import of the whole structure of accounts would be awesome

**Describe alternatives you've considered**
We thought about the standard soql export and bulk import using external key, but we don't have the external key available in this instance (and don't want to create extra fields for it)

**Comment by aheber** [comment]
@mhumpolec Have you looked at the `force:data:tree:...` commands?
Something like this could likely pull your data out in a way that it can easily be re-imported.
`sfdx force:data:tree:export -q "SELECT Id, Name, (Select Id, Name FROM ChildAccounts) FROM Account WHERE ParentId = null"`
This would likely break if you have hierarchies more than one parent level deep. You'll likely need to add the `--plan` and `--outputdir` parameters to this command to store it in a way that you can use it later.

**Comment by mhumpolec** [comment]
Yes, we just did it the other way around, your solution supports only two levels

Martin
From mine clever phone

3. 7. 2019 v 17:58, Heber <notifications@github.com>:

**Comment by WillieRuemmele** [comment]
https://github.com/forcedotcom/cli/discussions/2359?converting=1
