### ISSUE TITLE
SFDX always returning exit status as 1

### ISSUE THREAD

**Issue by Govina01SFDC** [forcedotcom/cli#1270]
### Summary

SFDX always returning exit status as 1

### Steps To Reproduce:

We have an automated script to deploy the source files to a sandbox. 

### Expected result

There are multiple sub scripts and all the scripts should complete with out any error. 

### Actual result

There are multiple sub scripts and after the first script, the execution stops with the status as 1 (echo $?)

### System Information

SFDX Version: sfdx-cli/7.124.0 win32-x64 node-v14.18.1

![image](https://user-images.githubusercontent.com/93937289/140787838-3c7c82c6-89a9-4242-b0b4-190208aa79e9.png)

**Comment by maggiben** [comment]
Hi, can you provide the full command, also It would be helpful to know what types of files are you trying to deploy.
Where you able to perform these actions before the last release ?

**Comment by Govina01SFDC** [comment]
Hi Thanks for the quick update. Do you need the file contents for sandboxDeploy script or which command are you looking for? In my case it never worked for earlier versions so I upgraded to latest version to see if the issue is resolved. I do see some of my colleagues are able to execute the complete script without any issue. I am not sure if this is a setting issue or genuine bug. Please advise.

**Comment by Govina01SFDC** [comment]
Just to add whenever I execute "sfdx force:source:deploy", it should return a 1 when the deployment succeeds. Even though there is no actual error, the output still returned is 1.

**Comment by cristiand391** [comment]
@Govina01SFDC it seems you are using git bash on windows, so it could be either `sfdx` or the script that it's returning exit code 1.
 
Can you add the json flag `--json` to the sfdx command in the script and make it print the output of the command? Then when you run the script again you should be able to see `sfdx` exit code in json.

**Comment by Govina01SFDC** [comment]
Hi Team,

Thanks for the quick update. I executed a sample command. Below are the details. 

GoviNa01@BCTGOVINA01-WXL MINGW64 ~/Documents/Naveen SF Dev/atlas (feature/ATLASSVC-1874)
$ sfdx force:source:deploy --json -p force-app/main/default/settings/Account.settings-meta.xml
{
  "status": 0,
  "result": {
    "checkOnly": false,
    "completedDate": "2021-11-09T16:27:54.000Z",
    "createdBy": "0056g000005TY7x",
    "createdByName": "Naveen Govindaraju",
    "createdDate": "2021-11-09T16:27:53.000Z",
    "details": {
      "componentSuccesses": [
        {
          "changed": "true",
          "componentType": "",
          "created": "false",
          "createdDate": "2021-11-09T16:27:53.000Z",
          "deleted": "false",
          "fileName": "package.xml",
          "fullName": "package.xml",
          "success": "true"
        },
        {
          "changed": "false",
          "componentType": "AccountSettings",
          "created": "false",
          "createdDate": "2021-11-09T16:27:53.000Z",
          "deleted": "false",
          "fileName": "settings/Account.settings",
          "fullName": "Account",
          "success": "true"
        }
      ],
      "runTestResult": {
        "numFailures": "0",
        "numTestsRun": "0",
        "totalTime": "0.0"
      }
    },
    "done": true,
    "id": "0Afe000000xix9hCAA",
    "ignoreWarnings": false,
    "lastModifiedDate": "2021-11-09T16:27:54.000Z",
    "numberComponentErrors": 0,
    "numberComponentsDeployed": 1,
    "numberComponentsTotal": 1,
    "numberTestErrors": 0,
    "numberTestsCompleted": 0,
    "numberTestsTotal": 0,
    "rollbackOnError": true,
    "runTestsEnabled": false,
    "startDate": "2021-11-09T16:27:53.000Z",
    "status": "Succeeded",
    "success": true,
    "deployedSource": [],
    "outboundFiles": [],
    "deploys": [
      {
        "checkOnly": false,
        "completedDate": "2021-11-09T16:27:54.000Z",
        "createdBy": "0056g000005TY7x",
        "createdByName": "Naveen Govindaraju",
        "createdDate": "2021-11-09T16:27:53.000Z",
        "details": {
          "componentSuccesses": [
            {
              "changed": "true",
              "componentType": "",
              "created": "false",
              "createdDate": "2021-11-09T16:27:53.000Z",
              "deleted": "false",
              "fileName": "package.xml",
              "fullName": "package.xml",
              "success": "true"
            },
            {
              "changed": "false",
              "componentType": "AccountSettings",
              "created": "false",
              "createdDate": "2021-11-09T16:27:53.000Z",
              "deleted": "false",
              "fileName": "settings/Account.settings",
              "fullName": "Account",
              "success": "true"
            }
          ],
          "runTestResult": {
            "numFailures": "0",
            "numTestsRun": "0",
            "totalTime": "0.0"
          }
        },
        "done": true,
        "id": "0Afe000000xix9hCAA",
        "ignoreWarnings": false,
        "lastModifiedDate": "2021-11-09T16:27:54.000Z",
        "numberComponentErrors": 0,
        "numberComponentsDeployed": 1,
        "numberComponentsTotal": 1,
        "numberTestErrors": 0,
        "numberTestsCompleted": 0,
        "numberTestsTotal": 0,
        "rollbackOnError": true,
        "runTestsEnabled": false,
        "startDate": "2021-11-09T16:27:53.000Z",
        "status": "Succeeded",
        "success": true,
        "deployedSource": [],
        "outboundFiles": []
      }
    ]
  }
}

GoviNa01@BCTGOVINA01-WXL MINGW64 ~/Documents/Naveen SF Dev/atlas (feature/ATLASSVC-1874)
$ echo $?
1

GoviNa01@BCTGOVINA01-WXL MINGW64 ~/Documents/Naveen SF Dev/atlas (feature/ATLASSVC-1874)
$

**Comment by ghost** [comment]
We are experiencing the same issue when using Gitbash. I was able to reproduce by using the latest Salesforce Cli installer. Upon running the force:org:create, the scratch org is created, the json status is 0 but the command exit code is 1.

**Comment by stoevie** [comment]
I had this problem also. Workaround is to install by example sfdx version 7.61.0.0.
Execute after the installation 'sfdx update' to upgrade to the latest version.

**Comment by Govina01SFDC** [comment]
Thanks a lot for the update @stoevie. This indeed resolved my issue (although I didnt follow the above solution completely but this really helped). 

I uninstalled sfdx completely and reinstalled sfdx-cli@7.123.1 and the issue was fixed. The issue seems to have addressed in some recent releases.

**Comment by stoevie** [comment]
> Thanks a lot for the update @stoevie. This indeed resolved my issue (although I didnt follow the above solution completely but this really helped).
> 
> I uninstalled sfdx completely and reinstalled sfdx-cli@7.123.1 and the issue was fixed. The issue seems to have addressed in some recent releases.

Hi @Govina01SFDC,

My experience was that a clean install worked for a while and then the same problem again. Only installing an old version and running sfdx update worked for me.

Kr,
Gert

**Comment by Govina01SFDC** [comment]
> > Thanks a lot for the update @stoevie. This indeed resolved my issue (although I didnt follow the above solution completely but this really helped).
> > I uninstalled sfdx completely and reinstalled sfdx-cli@7.123.1 and the issue was fixed. The issue seems to have addressed in some recent releases.
> 
> Hi @Govina01SFDC,
> 
> My experience was that a clean install worked for a while and then the same problem again. Only installing an old version and running sfdx update worked for me.
> 
> Kr, Gert

Thanks a lot @stoevie. I will make a note and follow the solution you shared.
