### ISSUE TITLE
package:create:version with the Translation causes error Not available for deploy for this organization

### ISSUE THREAD

**Issue by kevinautomation** [forcedotcom/cli#1272]
### Summary

When using the 2GP via the following command (`sfdx force:package:version:create`), the version creation failed with the error "Not available for deploy for this organization".  However, the sfdx-project.json has the definitionFile attribute to project-scratch-def.json which contains the workbench settings.  The `package:create:version` command should validate correctly.  However, when running the command with --skipValidation, the app is packaged and the app is installed successfully.

### Steps To Reproduce:
1. Run command `sfdx force:package:version:create -p "App Name" -f project-scratch-def.json -w 20 -c -x --loglevel=DEBUG`

project-scratch-def.json
{
    "packageDirectories": [
        {
            "path": "force-app",
            "package": "App Name",
            "versionName": "ver 3",
            "versionDescription": "description",
            "versionNumber": "3.1.2.0",
            "ancestorVersion": "3.1.1.0",
            "default": true,
            "postInstallScript": "PostInstallScript",
            "definitionFile": "config/project-scratch-def.json"
        }
    ],
    "namespace": "Test",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "50.0",
    "packageAliases": {
        "App Name": "0Ho3i000000Kxxxxxx",
        "App Name@3.0.0-0": "04t3i000002Wxxxxxx",
        "App Name@3.1.0-0": "04t3i000002Wxxxxxx",
        "App Name@3.1.1-0": "04t3i000002Wxxxxxx",
    }
}

config/project-scratch-def.json
{
    "orgName": "Company Name",
    "edition": "Developer",
    "features": [],
    "settings": {
        "languageSettings": {
            "enableTranslationWorkbench": true,
            "enableEndUserLanguages": true,
            "enablePlatformLanguages": true
        },
        "lightningExperienceSettings": {
            "enableS1DesktopEnabled": true
        }
    }
}

### Expected result

The package validation should pass and the packaging should work.  If there is an incorrect configuration, more details information should be available to resolve the problem.  Currently, it is very difficult to understand what is not working.

### Actual result

The package is failing at verifying stage and unable to proceed to package the application.

Request in progress. Sleeping 30 seconds. Will wait a total of 1200 more seconds before timing out. Current Status='Queued'
Request in progress. Sleeping 30 seconds. Will wait a total of 1170 more seconds before timing out. Current Status='Initializing'
Request in progress. Sleeping 30 seconds. Will wait a total of 1140 more seconds before timing out. Current Status='Verifying metadata'
Request in progress. Sleeping 30 seconds. Will wait a total of 930 more seconds before timing out. Current Status='Verifying metadata'
ERROR running `force:package:version:create`:  Multiple errors occurred:
(1) ko: Not available for deploy for this organization
(2) es: Not available for deploy for this organization
(3) de: Not available for deploy for this organization

### System Information

sfdx-cli/7.124.0 win32-x64 node-v16.13.0

### Additional information

![image](https://user-images.githubusercontent.com/68876325/141007771-3db4cf32-0b24-43ce-8205-503e13b57f22.png)

**Comment by kevinautomation** [comment]
Problem solved.

**Comment by ranizi** [comment]
how was it solved please?

**Comment by syunyama** [comment]
@kevinautomation 
Please write how you solved.

**Comment by kevinautomation** [comment]
To resolve this, we increased the minor of the version number for adding the translation.  The error message is quite incompetent to indicate anything useful.

**Comment by acodebreaker** [comment]
where did you increase the version @kevinautomation
