### ISSUE TITLE
sfdx force:source:deploy | Inconsistent JSON being returned on error (status 1).

### ISSUE THREAD

**Issue by pagner** [forcedotcom/cli#1274]
When a deployment fails (status 1)

result.details.componentFailures is either an object or an array depending on the count of failures. If there is one failure, it's an object, if there are multiple failures it's an array. If there are no errors, it's gone altogether! This makes it difficult to parse and violates a plethora of coding best practices, patterns etc. Just plain ugly!

expected behavior:

Always an Array with a count >= 0;

**Comment by mshanemc** [comment]
componentSuccess/componentFailures is verbatim the output from the metadata API.  A lot of tooling and code exists around that output, so we preserved it.

You didn't say what version you're on, but the newer ones that use `plugin-source` have a `deployedSource` property that will always be an array and you can filter it by its `state` property.

Did that help?

**Comment by pagner** [comment]
@mshanemc Thanks for your quick reply. I am on the latest version: sfdx-cli/7.125.0.

I do see your point about preserving what came before in an effort to not break dependent applications. Your suggestion is a good one. I will go that route. 

b.t.w I met you once at Forcelandia 2018 I believe it was. We talked about the oclif plugins we had both created for workarounds with sfdx; which was in it's infancy at the time. Deployments for non tracked orgs were only available using mdapi at that time. You had a talk in which you showcased your plugin that pulled source from github, spun up a scratch and pushed the metadata.

take it easy.. closing...
