### ISSUE TITLE
Update sourceApiVersion of sfdx-project.json to 53.0

### ISSUE THREAD

**Issue by PeterLin888** [forcedotcom/cli#1278]
### Summary

Update sourceApiVersion of sfdx-project.json to 53.0
The current generated version is 52.0.

### Steps To Reproduce:

**Repository to reproduce:** N/A

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  sfdx force:project:create -n testversion -t empty -x

### Expected result

1.  Open sfdx-project.json: "sourceApiVersion": "53.0"
1.  Open manifest\package.xml <version>53.0</version>

### Actual result

1.  Open sfdx-project.json: "sourceApiVersion": "52.0"
1.  Open manifest\package.xml <version>52.0</version>

### System Information
Windows 10 Version 1909 (OS Build 18363.1854)

sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.125.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.18.1",
        "pluginVersions": [
                "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.7.1",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@provartesting/provardx 0.3.1",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.22 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.5 (core)",
                "config 1.2.41 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.4 (core)",
                "generator 1.2.1 (core)",
                "limits 1.2.2 (core)",
                "org 1.9.0 (core)",
                "salesforce-alm 53.1.2 (core)",
                "schema 1.0.10 (core)",
                "sfdmu 4.9.5",
                "sfdx-cli 7.125.0 (core)",
                "sfpowerkit 3.3.2",
                "shane-sfdx-plugins 4.43.0",
                "├─ @mshanemc/sfdx-sosl 1.1.0",
                "└─ @mshanemc/plugin-streaming 1.1.7",
                "source 1.3.1 (core)",
                "telemetry 1.2.8 (core)",
                "templates 52.4.0 (core)",
                "texei-sfdx-plugin 1.11.1",
                "trust 1.0.11 (core)",
                "user 1.5.2 (core)"
        ],
        "osVersion": "Windows_NT 10.0.18363"
}
### Additional information

_Feel free to attach a screenshot_.

**Comment by maggiben** [comment]
Hi, I can confirm I was able to reproduce this bug, we'll investigate why the generator is picking the wrong version, I've however tried a workaround: setting env var: `SFDX_API_VERSION=53` and seemed to work, can you please try and confirm the workaround is able to set `sourceApiVersion` equal to 53 ?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10169144](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000OYhSyYAL/view)

**Comment by maggiben** [comment]
PR: https://github.com/forcedotcom/salesforcedx-templates/pull/408

**Comment by shetzel** [comment]
The fix for this issue is now in SFDX CLI v7.134.0 published today.
See https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71340-jan-20-2022-stable
