### ISSUE TITLE
sfdx force:lightning:lint and eval() 

### ISSUE THREAD

**Issue by Szandor72** [forcedotcom/cli#128]
### Summary

When using eval() in a aura javascript file, sfdx force:lightning:lint raises two errors:
- secure-window (Invalid SecureWindow API, eval was blacklisted)
- no-eval (eval can be harmful) 

Developer Console does not raise the same issues. Since Summer18 I'd expect the linter not to automatically error all usages of eval. Cf. https://salesforce.stackexchange.com/questions/228679/lightning-support-for-eval-in-summer-18

We are using lightning:linter as part of our CI process. I wouldn't want to patch a workaround for eval errors. 

### Steps To Reproduce:

1.  Create any Aura Javascript file.
2.  add an eval() statement 
3. run `sfdx force:lightning:lint "path/to/file/" --files file.js --json`

### Expected result

No linting errors as in Developer Console. 

### Actual result
```JSON
"result": [
            {
                "ruleId": "secure-window",
                "severity": 2,
                "message": "Invalid SecureWindow API, eval was blacklisted",
                "line": 493,
                "column": 20,
                "nodeType": "CallExpression",
                "source": "            return eval(mergeFieldCalculationString);"
            },
            {
                "ruleId": "no-eval",
                "severity": 2,
                "message": "eval can be harmful.",
                "line": 493,
                "column": 20,
                "nodeType": "CallExpression",
                "source": "            return eval(mergeFieldCalculationString);"
            }
        ]
    }
]
```

### Additional information

sfdx-cli/7.12.3-bfc421fa08 win32-x64 node-v10.15.3

@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.2.3 (core)
├─ force-language-services 46.7.0 (core)
└─ salesforce-alm 46.6.0 (core)

sfdx-cli 7.12.3 (core)
shane-sfdx-plugins 3.19.0

Win10, current

**Comment by Szandor72** [comment]
@clairebianchi Understood. So should I go pester Greg? :) What's your suggestion?

**Comment by clairebianchi** [comment]
I have reached out to the team and they are looking at your issue. I am leaving it open till they have a chance to take a look and comment.

**Comment by KrisGraySFDC** [comment]
Hey Christian, good to talk to you again.

We've identified this rule didn't get updated, so we're updating it now.

Aiming for next patch of sfdx

**Comment by Szandor72** [comment]
Awesome! Thanks.

**Comment by Szandor72** [comment]
No issues with latest release. thank you.

**Comment by KrisGraySFDC** [comment]
Excellent!

Glad it worked well, let me know if I broke anything. :)
