### ISSUE TITLE
Error with "force:source:convert" command when using latest sfdx cli version

### ISSUE THREAD

**Issue by karlamartinezh** [forcedotcom/cli#1280]
### Summary

Hello, we're using a script for devops, and today it stopped working (12/11/21) yesterday was working fine. We're using the last version of SFDX CLI and the error that appears is:  ERROR running force:source:convert:  Component conversion failed: Cannot read properties of undefined (reading 'addChild')

The following is the scripts

`[0KRunning with gitlab-runner 14.4.0 (4b9e985a)[0;m
[0K  on spotrunner SEzyaKc-[0;m
section_start:1636735462:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m[0;m
[0KUsing Docker executor with image node:latest ...[0;m
[0KPulling docker image node:latest ...[0;m
[0KUsing docker image sha256:803ad17a604bc6eee9f85ee6bf46ec76d1423a0ac945e5f99a9a0fe33c771296 for node:latest with digest node@sha256:fb256ef025424b407fb806a9828b105d82aac93c7168a1a8bc156bc82996b939 ...[0;m
section_end:1636735463:prepare_executor
[0Ksection_start:1636735463:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner-sezyakc--project-1278-concurrent-0 via aefef63c56c9...
section_end:1636735464:prepare_script
[0Ksection_start:1636735464:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mFetching changes with git depth set to 50...[0;m
Reinitialized existing Git repository in /builds/XXXXXXX/XXXXX-repo/.git/
[32;1mChecking out f478f677 as preproduction...[0;m
Removing sfdx/

[32;1mSkipping Git submodules setup[0;m
section_end:1636735466:get_sources
[0Ksection_start:1636735466:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:803ad17a604bc6eee9f85ee6bf46ec76d1423a0ac945e5f99a9a0fe33c771296 for node:latest with digest node@sha256:fb256ef025424b407fb806a9828b105d82aac93c7168a1a8bc156bc82996b939 ...[0;m
[32;1m$ # Function to install the Salesforce CLI. # collapsed multi-line command[0;m
[32;1m$ install_salesforce_cli[0;m
[0msfdx installed to [38;5;104m/usr/local/bin/sfdx[0m
sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3
sfdx-cli: Updating CLI...
sfdx-cli: Updating CLI from 7.82.0-3d0c527ac6 to 7.94.3-a4e7c7955b... done
sfdx-cli: Updating CLI... fetching manifest

sfdx-cli: Updating CLI from 7.94.3-a4e7c7955b to 7.126.0-eb014a2... done
sfdx-cli: Updating CLI... fetching manifest
sfdx-cli: Updating CLI... done
sfdx-cli: Updating sf... done
sfdx-cli/7.126.0 linux-x64 node-v16.13.0
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.3 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 1.1.22 (core)
apex 0.3.0 (core)
auth 1.7.5 (core)
config 1.2.46 (core)
custom-metadata 1.0.12 (core)
data 0.6.4 (core)
generator 1.2.1 (core)
limits 1.2.3 (core)
org 1.9.0 (core)
salesforce-alm 53.4.1 (core)
schema 1.0.10 (core)
sfdx-cli 7.126.0 (core)
source 1.3.1 (core)
telemetry 1.2.8 (core)
templates 52.6.0 (core)
trust 1.0.10 (core)
user 1.5.2 (core)
[32;1m$ sfdx force:source:convert -r force-app/main/default -d src[0;m
ERROR running force:source:convert:  Component conversion failed: Cannot read properties of undefined (reading 'addChild')
section_end:1636735560:step_script
[0Ksection_start:1636735560:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1636735561:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m`

### Steps To Reproduce:
RUN the command sfdx force:source:convert -r force-app/main/default -d src

**Repository to reproduce:** N/A

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

Execute the script 

### Actual result

Failing ERROR  -> ERROR running force:source:convert:  Component conversion failed: Cannot read properties of undefined (reading 'addChild')

### System Information

N/A

**Comment by maggiben** [comment]
Hi, can run the command with flags `--dev-debug` as a workaround have you tried downgrading ? and if so, does the previous version work correctly ?

**Comment by trentchilders** [comment]
Hey. Just want to pipe in that we started seeing some weirdness today as well. The force:source:convert does run but when it begins to run a deployment, there are far fewer 'components' than there were yesterday. Yesterday, the deployment included 5978 components, today there are only 765.

**Comment by shetzel** [comment]
I wasn't able to reproduce this with an npm install of 7.126 but with an installer update to 7.126 I saw the error.  That leads me to believe that a bad version of SDR (the source deploy retrieve library) was included in the installers for 7.126.  I updated to the stable-rc version and I no longer see the error.

Can you please update to the release candidate version and see if that fixes the issue?  `sfdx update stable-rc`

Alternatively you can install from npm and try it.  I understand that updating scripts is probably not practical to test a fix so I'm asking if manually updating and running the commands results in the correct behavior.

**Comment by trentchilders** [comment]
@shetzel I tried `sfdx update stable-rc` and I got 
```
+ sfdx update stable-rc
--
2 | sfdx-cli: Updating CLI... !
3 | ›   Warning: Attempting to contact update site...
4 | ›   Error: S3 host is not reachable.
```
This gets run in our Drone instance and was not installed using npm, unfortunately

**Comment by shetzel** [comment]
do you happen to have SFDX_S3_HOST env var set?  Unset it if so.  Appending `--dev-debug` to the command might provide some insight as well.

**Comment by trentchilders** [comment]
Here is the readout with `--dev-debug` it looks like I'm getting an access denied error. It doesn't look like we have SFDX_S3_HOST env var set in our Drone secrets file
https://gist.github.com/trentchilders/c70a6634e497bead5120b8dca8da183e

**Comment by karlamartinezh** [comment]
Hello community @shetzel 


I ran the  --dev-debug in the VS Code and seems to be in the file 'xmlstr2xmlnode.js' line 300 
![image](https://user-images.githubusercontent.com/36207781/141755178-9dfe2c7d-d762-4645-9f7c-e4de43488f89.png)


I ran before the command sfdx update stable-rc and the CLI version is 7.127.0-f33b8ac

I'm still having the same error, not sure what it can be, that file haven't been touched. 

Any suggestion?


![Execution in Pipeline ](https://user-images.githubusercontent.com/36207781/141775191-35640ca4-5b02-4a5e-b636-5172ddf3c7e9.png)
![Execution in VS Code](https://user-images.githubusercontent.com/36207781/141775196-faefcd54-f996-4350-bfff-0c61ade915bd.png)
[SFDX Error .txt](https://github.com/forcedotcom/cli/files/7538317/SFDX.Error.txt)

**Comment by shetzel** [comment]
@trentchilders - I noticed this in your debug output: `sfdx-cli/7.49.1-2b6ba86a25 linux-x64 node-v10.15.3`
That is a very old version of the CLI.  I think what's happening is that it's trying to update from the wrong manifest location.  I would completely uninstall the CLI and install from scratch.  I think you'll have better results after that.

@karlamartinezh - that error looks like it's parsing a metadata xml file expecting a certain structure but encountering something unexpected for that metadata type.  It would be helpful to know the type and the exact file it's having a problem with.  I can't see the entire stack trace but if you look at the file of the line beginning with:
`at SourceComponent.getChildren()`
in your stack, then add a console.log in that function to find out the file and the type, you can then make sure the type is being interpreted correctly and the contents of the file are correct.  Let me know what the file path is, the type, and the file contents (masking any sensitive data) and we can fix the code.
