### ISSUE TITLE
Cannot Migrate Dependent Metadata from Unlocked Packages

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#1281]
### Summary

The SFDX Developer Guide [states](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_unlocked_pkg_migrate_metadata.htm):

> To move production metadata from package A to package B, follow these steps.
> 1.  Identify the metadata to be moved from package A to package B.
> 2.  Remove the metadata from package A, create a version, and release the package.
> 3.  Add the metadata to package B, create a version, and release the package.
> 4.  In your production org, upgrade package A.
> 5.  In your production org, install package B.
>
> Your metadata is now a part of package B in your production org.

However, if anything in package A depends on package B, this does not work.  We would like to extract some common utility classes from our package.  It's working fine for building new scratch orgs but we cannot deploy the changes to existing orgs

### Expected result

It should be possible to extract some metatdata from Package A into new Package B, and then to install both to an existing org that has a prior release of Package A.

### Actual result

Because Package A (`collections-app`) will depend on Package B (`core-apex-utils`), it is a declared dependency in Package A's `sfdx-project.json`.  Trying to install the new version of package A fails:

> ERROR:  Encountered errors installing the package!,Installation errors: 
> 1) Invalid Upgrade., Details: The package you're installing depends on package 'core-apex-utils', version '1.0'. Install package 'core-apex-utils' in the target org before you install package 'collections-app'.

We cannot remove the dependency from package A's `sfdx-project.json`, because then the package version create will fail.

We also cannot install Package B first, because the components from Package A will not have been Deprecated yet, and the system won't let us overwrite them:

> ERROR:  Encountered errors installing the package!,Installation errors: 
> 1) Cannot add component of type:ApexClass named:FLSUtil subjectId:01pP000000D9Tf5 to another package because it is an installed component., Details: package.xml: Cannot add component of type:ApexClass named:FLSUtil subjectId:01pP000000D9Tf5 to another package because it is an installed component.

### System Information

```
{
        "cliVersion": "sfdx-cli/7.123.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v14.18.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.22 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.3 (core)",
                "config 1.2.41 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.3 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.2 (core)",
                "org 1.8.3 (core)",
                "salesforce-alm 53.0.0 (core)",
                "schema 1.0.10 (core)",
                "sfdx-cli 7.123.0 (core)",
                "sfdx-fmz-plugin 1.1.0 (1.1.0)",
                "sfpowerkit 3.3.2",
                "source 1.2.4 (core)",
                "telemetry 1.2.8 (core)",
                "templates 52.4.0 (core)",
                "trust 1.0.8 (core)",
                "user 1.5.2 (core)"
        ],
        "osVersion": "Darwin 18.7.0"
}
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by maggiben** [comment]
Hi, can you please run the command with `--dev-debug` flags and post the output ? also have you tried updating the CLI to a newer version ? what was the latest version you where able to perform this actions ? Im trying to discard any regressions. thanks.

**Comment by azlam-abdulsalam** [comment]
@jclark-dot-org  Its what we call the refactoring dance. The easiest option is to remove the lock of the components from the org (no api support and has to be done manually or through ui automation) for the components in Package A back to the org. Then install Package B with the components moved from A.  Now you can deprecate the components from Package A and install.

Its the nature of the lock mechanism rather than the CLI and is something the 'bundled' package deployment will fix

**Comment by jclark-dot-org** [comment]
@azlam-abdulsalam That makes sense; can you point me at any public info on the 'bundled' package deployment which I'm guessing is a work in progress?

How does one remove the lock in the UI?  I wasn't aware that was an option.  It's possible our component count is low enough to make this practical in this case.

**Comment by azlam-abdulsalam** [comment]
- Navigate to Installed Packages -> Click on Package -> Click on View Components -> Click on Remove

There is also one more option 
- You could also create a new version of Package A with these components removed and install using deprecate mode (--deprecate flag rather than mixed) as well

**Comment by azlam-abdulsalam** [comment]
@jclark-dot-org  Here is the link to package bundles
https://youtu.be/eYqhPE2O66k

Though it describes for managed package, it is coming in for unlocked as well.

**Comment by jclark-dot-org** [comment]
@azlam-abdulsalam Thanks for your help. I tried to "remove from package" the 47 components I identified, and pushed my new package (Package B) again.  I think it nearly worked; it failed with only one error message, due to a custom label that is still owned by (the original version of) Package A.

I checked the View Components page for Package A in the target org... and it appears the Custom Labels to not appear there, so I cannot remove them.  Since I only move 4 custom labels, I'm considering simply renaming them so I can move on, but is there any way to actually remove them?

**Comment by jclark-dot-org** [comment]
@azlam-abdulsalam just a followup to note that renaming the 4 custom labels in Package B that originally came from Package A allowed me to successfully install Package B into an existing org with "original" Package A.  After which, I was able to install "new" Package A successfully.  Bundled Packages will make this so much better, but at least I'm unblocked.

A note for anyone who needs to do the same thing - if you remove items from the installed package in Lightning Experience, every time you remove one, you are returned to the Package overview page and have to click "View Components" again.  However, if you use Classic, you are returned to the Component List after each removal.  This is significantly quicker if you have to remove more than a couple items.

**Comment by shetzel** [comment]
Thank you @azlam-abdulsalam!  That was very helpful.

@jclark-dot-org - is this an acceptable resolution to your issue?  If so, please close at your convenience.  Also, thanks for the helpful comments for others who want to do the same thing.

**Comment by ctmarxen** [comment]
@azlam-abdulsalam https://github.com/forcedotcom/cli/issues/1281#issuecomment-972370836 if you don't own the package you want to remove the metadata from (so upgrading and deprecating is not an option), is it true that the only way is to manually remove via UI?
