### ISSUE TITLE
No matching version found for prettier-plugin-apex@^1.10.1.

### ISSUE THREAD

**Issue by carlthress** [forcedotcom/cli#1284]
### Summary

When running npm install in my project folder, I encounter the following error:

npm ERR! code ETARGET
npm ERR! notarget No matching version found for prettier-plugin-apex@^1.10.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

When I go to the npm site for prettier-plugin-apex, the latest version there is 1.10.0.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Open the project in VS Code.
2.  Run npm install in the terminal.
3.  Installer runs, then errors out with the above message

### Expected result

The process should have completed without an error.

### Actual result

The above mentioned error occurred.

### System Information

{
        "cliVersion": "sfdx-cli/7.127.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.13.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-diff 0.0.6",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.22 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.5 (core)",
                "config 1.2.47 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.4 (core)",
                "generator 1.2.1 (core)",
                "limits 1.2.3 (core)",
                "org 1.9.0 (core)",
                "salesforce-alm 53.4.2 (core)",
                "schema 1.0.10 (core)",
                "sfdmu 4.10.2",
                "sfdx-cli 7.127.0 (core)",
                "source 1.4.0 (core)",
                "telemetry 1.2.8 (core)",
                "templates 52.6.0 (core)",
                "trust 1.0.10 (core)",
                "user 1.5.2 (core)"
        ],
        "osVersion": "Windows_NT 10.0.18363"
}
### Additional information

_Feel free to attach a screenshot
[2021-11-18T21_52_46_951Z-debug.log](https://github.com/forcedotcom/cli/files/7566461/2021-11-18T21_52_46_951Z-debug.log)
_

**Comment by abhishekalekar** [comment]
I am also getting same issue.

**Comment by gonardfreeman** [comment]
@carlthress @abhishekalekar  1.1.10 will work fine

**Comment by carlthress** [comment]
How do I get the command "npm update" to look for 1.1.10 instead of 1.1.11? I'm literally just typing two words in to the command line. npm is doing the rest. Is there a file/script somewhere I can edit? This is preventing me from installing a package I need to complete a trailhead (Lightning Web Components Tests) I need to complete in order to unlock the "Lightning Web Components Specialist" superbadge, which is a prerequisite for taking the JavaScript Developer I certification test. It's pretty frustrating.

**Comment by hrafven** [comment]
@carlthress you can edit the package.json file to change the line `"prettier-plugin-apex": "^1.10.1"` to `"prettier-plugin-apex": "^1.10.0"`

**Comment by carlthress** [comment]
Perfect! Thank you so so much @Hrafven. You're a life-saver.

**Comment by Nik6204** [comment]
@carlthress can u please give me complete solution/command for this. I am facing same issue with the same trailhead.

**Comment by carlthress** [comment]
@Nik6204 - follow the advice given by @Hrafven. Edit the prettier version number in the package.json file for your project (in the root level of the project in VS Code).

In `package.json` file, replace the highlighted text below: 

![image](https://user-images.githubusercontent.com/25539093/144322357-4af5bd9e-0119-40ab-afed-b8c1c254fff7.png)

With the highlighted text here:
![image](https://user-images.githubusercontent.com/25539093/144322588-6627fbec-3aa2-4ed3-a1dd-2a19783d453c.png)

**Comment by awalia123** [comment]
> @carlthress you can edit the package.json file to change the line `"prettier-plugin-apex": "^1.10.1"` to `"prettier-plugin-apex": "^1.10.0"`

please check @Hrafven whether God's post is available!? your solution worked like a charm!
