### ISSUE TITLE
listmetadata returning no metadata for for type ListView

### ISSUE THREAD

**Issue by ctewell** [forcedotcom/cli#1285]
sfdx force:mdapi:listmetadata -m ListView -u username 
is returning "No metadata for type: ListView" starting with version 7.127.  This worked fine in 7.126.

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

Step 1. Upgrade CLI to 7.127.0-f33b8ac
Step 2 do this command 
sfdx force:mdapi:listmetadata -m ListView -u username

### Expected result

json for metdata will be listed

### Actual result

The following is output:
No metadata found for type: ListView in org: ctewell@...............

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- Paste the output here
sfdx --version --verbose --json

{
        "cliVersion": "sfdx-cli/7.127.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.13.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.22 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.5 (core)",
                "config 1.2.47 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.4 (core)",
                "generator 1.2.1 (core)",
                "limits 1.2.3 (core)",
                "org 1.9.0 (core)",
                "salesforce-alm 53.4.2 (core)",
                "schema 1.0.10 (core)",
                "sfdx-cli 7.127.0 (core)",
                "source 1.4.0 (core)",
                "telemetry 1.2.8 (core)",
                "templates 52.6.0 (core)",
                "trust 1.0.10 (core)",
                "user 1.5.2 (core)"
        ],
        "osVersion": "Windows_NT 10.0.14393"
}
### Additional information

_Feel free to attach a screenshot_.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10203090](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000QgrYzYAJ/view)

**Comment by shetzel** [comment]
I moved this command from the salesforce-alm plugin to the source plugin in the 7.127.0 release.  Turns out the bug is due to a very slight difference in how the jsforce list call is made:
working:
`connection.metadata.list({ type: ListView }, undefined)`
non-working:
`connection.metadata.list({ type: ListView, folder: undefined }, undefined)`

The fix will be in the next release candidate.  Sorry for the regression.

**Comment by shetzel** [comment]
Fixed with https://github.com/salesforcecli/plugin-source/pull/309

**Comment by frankpeleato** [comment]
@shetzel Experiencing this same problem with the flag `-m Layout`.  I'm on version 7.127.0

**Comment by shetzel** [comment]
The fix isn't specific to ListView.  Layouts should also be fixed.  There's no release this week so it'll be next week.  Alternatively you could link the source plugin branch with the fix to your CLI to get the fix sooner.

**Comment by frankpeleato** [comment]
> The fix isn't specific to ListView. Layouts should also be fixed. There's no release this week so it'll be next week. Alternatively you could link the source plugin branch with the fix to your CLI to get the fix sooner.

@shetzel Thank you for the update! I will wait for your release.

**Comment by rajeswarr1** [comment]
@shetzel Facing the same issue with other components like _AssignmentRule, AutoResponseRule, WorkflowAlert, WorkflowTask, WorkflowFieldUpdate, SharingOwnerRule, SharingCriteriaRule, CustomField, ValidationRule, Weblink_ etc....

Whereas _sfdx force:mdapi:listmetadata_ works for _AssignmentRules, AutoResponseRules, Workflow, SharingRules, CustomObjects_ .

Basically all the metadata (sub) components which are inside a component file are not getting listed.

Hope the fix would resolve for above metadata component types as well.

**Comment by shetzel** [comment]
@rajeswarr1 - all types should be fixed.  The code is now making the exact same request as the legacy plugin.

**Comment by rajeswarr1** [comment]
Thank you @shetzel 
Just noted another observation that for SharingRules and SharingCriteriaRules the number of components retrieved is lesser when using `sfdx force:mdapi:listmetadata` command with v 7.127.0.

The number of components displayed in v7.126.0 seems to be accurate. Would the fix applied also resolve the above discrepancy.

**Comment by frankpeleato** [comment]
Still happening as of version `7.129.0`.

**Comment by bryan-b-johnson** [comment]
@shetzel This does not appear to be fixed in version `7.129.0`. Is there a specific version we can expect this change? Thanks!

**Comment by mshanemc** [comment]
I see it working in 7.130.1 (currently RC).

**Comment by cristiand391** [comment]
This should be fixed  in latest sfdx v7.130.1 🎉 
Release notes: https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx#71301-dec-9-2021-stable
