### ISSUE TITLE
Unable to use force:source:deploy -c with NotificationTypeConfig metadata type

### ISSUE THREAD

**Issue by AFS-llc** [forcedotcom/cli#1287]
Unable to use sfdx force:source:deploy -c with NotificationTypeConfig metadata type 
The check deploy for the NotificationTypeConfig will fail. The retrieve and deployments work fine using a * manifest, however the -c option on deploy will fail with "Invalid notification type specified"

**Comment by shetzel** [comment]
I was able to deploy/retrieve and check deploy without an error with the latest CLI and plugins.  E.g., `sfdx force:source:deploy -m NotificationTypeConfig -c` was successful.

You didn't provide your CLI details.  `sfdx version --verbose`
Also, what was the exact command and all parameters?
Do you have a repo and/or org that I can use to reproduce this issue?
