### ISSUE TITLE
Retrieving LWC causes import of metadata to be __c - fails when (re)deploying

### ISSUE THREAD

**Issue by briank73** [forcedotcom/cli#1288]
### Summary

Having an LWC importing fields from a metadata type; when retrieving this metadata type becomes __c instead of __mdt, making the file undeployable.

### Steps To Reproduce:

Having:
- An LWC
- A custom metadata type
- Import metadata type in LWC, e.g.:
	- `import FALC_MDT_MASTER_LABEL_FIELD from '@salesforce/schema/FinancialAccountListColumn__mdt.MasterLabel';`

Steps:
1. Deploy
	- `sfdx force:source:deploy --loglevel fatal -m LightningComponentBundle:financialAccountList2`
1. Retrieve
	- `sfdx force:source:retrieve --loglevel fatal -m LightningComponentBundle:financialAccountList2`
	- the import now looks:
		- `import FALC_MDT_MASTER_LABEL_FIELD from '@salesforce/schema/FinancialAccountListColumn__c.MasterLabel';`
1. Deploy:
	- `sfdx force:source:deploy --loglevel fatal -m LightningComponentBundle:financialAccountList2`
	- fails:
		`Error  financialAccountList2 Invalid reference FinancialAccountListColumn__c.MasterLabel of type sobjectClass in file financialAccountList2.js`

### Expected result

Should be able to deploy just retrieved LWC :-).
I.e. metadata type should have postfix __mdt instead of __c.

### Actual result

Fails:
`Error  financialAccountList2 Invalid reference FinancialAccountListColumn__c.MasterLabel of type sobjectClass in file financialAccountList2.js`

### System Information

`sfdx-cli/7.125.0 win32-x64 node-v16.13.0`
(also fails for version 126 (on mac os))
(Also fails from VS Code)

**Comment by shetzel** [comment]
Thanks for reporting.  This isn't a CLI issue.  It's an issue for the Lightning Web Components team.  I'll let them know about it but you might want to open a case with support for that team for faster results.

**Comment by shetzel** [comment]
I'm going to close this since it's not a CLI issue and it's not supported LWC behavior.  Looks like the proper way to do this is by using `getRecord`.  See this for more: https://salesforcediaries.com/2019/12/13/custom-metadata-in-lightning-web-component-without-apex/
