### ISSUE TITLE
Add flag to disable the output of the mdapi convert

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#1290]
**Is your feature request related to a problem? Please describe.**

Similarly to the sfdx force:source:deploy, add an option to reduce the output of the conversion. In my case, it takes more that 10 seconds to output all the converted elements

**What are you trying to do**

Reduce output of the conversion result

**Describe the solution you'd like**

By default dont output and have and option like the --verbose option in sfdx force:source:push to print this results

**Describe alternatives you've considered**

Maybe the opposite, have a --no-verbose option

**Additional context**

![image](https://user-images.githubusercontent.com/10410852/143020453-40e96784-87c8-4782-85db-680b5bb8d37f.png)

1m 27s printing whole output
1m 14s just redirecting stdout to /dev/null

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10219193](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000RpT23YAF/view)

**Comment by shetzel** [comment]
@mnunezdm - you could also use the `--json` flag and it won't output to the console.

**Comment by mshanemc** [comment]
The new project:convert:source command just provides a success message, not all the details
