### ISSUE TITLE
Error with "force:source:convert" command

### ISSUE THREAD

**Issue by PabloArrietaL** [forcedotcom/cli#1292]
**Summary**
Running command "force:source:convert" with latest version of sfdx cli (7.127.0) results in an error:

![Screenshot_1](https://user-images.githubusercontent.com/24515451/143150542-39505ba3-09b7-40dc-be17-b6b1669a6808.png)

Steps To Reproduce:

1. install latest sfdx cli version (sfdx-cli/7.127.0)
2. Run "force: source:convert" command

Expected result
Successful deployment

Actual result
Error with "force:source:convert" command failing

**Comment by mshanemc** [comment]
@PabloArrietaL can you provide some more information about 
- the output of `sfdx version --verbose`
- what flags you used on `force:source:convert` 
- what your source folder looks like (including where that `.eslintignore` file is located)...some way that we can reproduce it

**Comment by PabloArrietaL** [comment]
@mshanemc 

- `sfdx version --verbose`

CLI Version :
        sfdx-cli/7.127.0

 Architecture:
        win32-x64

 Node Version :
        node-v14.17.3

 Plugin Version:
        @oclif/plugin-autocomplete 0.3.0 (core)
        @oclif/plugin-commands 1.3.0 (core)
        @oclif/plugin-help 3.2.6 (core)
        @oclif/plugin-not-found 1.2.4 (core)
        @oclif/plugin-plugins 1.10.2 (core)
        @oclif/plugin-update 1.5.0 (core)
        @oclif/plugin-warn-if-update-available 1.7.2 (core)
        @oclif/plugin-which 1.0.3 (core)
        @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
        alias 1.1.22 (core)
        apex 0.3.0 (core)
        auth 1.7.5 (core)
        config 1.2.47 (core)
        custom-metadata 1.0.12 (core)
        data 0.6.4 (core)
        generator 1.2.1 (core)
        limits 1.2.3 (core)
        org 1.9.0 (core)
        salesforce-alm 53.4.2 (core)
        schema 1.0.10 (core)
        sfdx-cli 7.127.0 (core)
        source 1.4.0 (core)
        telemetry 1.2.8 (core)
        templates 52.6.0 (core)
        trust 1.0.11 (core)
        user 1.5.2 (core)

 OS and Version:
        Windows_NT 10.0.19043

- This is the command I'm using `sfdx force:source:convert -x manifest/package.xml -d src`
- Folder structure:
![image](https://user-images.githubusercontent.com/24515451/143269815-d3fa13cd-8a5a-4fd5-97b6-ffb336909b50.png)

**Comment by mshanemc** [comment]
Does it reproduce with dreamhouse, or any other public repo that I can try? 

Can you confirm that the `.eslintignore` at the top of your project is the only one, that there isn't a `C:\.eslintignore` like the error says?

**Comment by mshanemc** [comment]
also, did you generate the `package.xml` with `force:source:manifest:create` ?  And was this working on previous versions or is this new?

**Comment by iowillhoit** [comment]
@PabloArrietaL Did you figure out what the issue was here? We've gotten another report of this error. Thanks!
