### ISSUE TITLE
SFDX installation error on githubaction

### ISSUE THREAD

**Issue by gsinha-atrium** [forcedotcom/cli#1293]
### Summary

while executing the  following command in the GitHub action 

`npm install --global sfdx-cli`
getting the following message 
************************************
shell: /usr/bin/bash -e {0}
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1386 packages, and audited 1644 packages in 2m

67 packages are looking for funding
  run `npm fund` for details

70 vulnerabilities (58 moderate, 12 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
/home/runner/work/_temp/95d208ad-f094-4288-834d-65a97eda105f.sh: line 2: node_modules/sfdx-cli/bin/run: No such file or directory
Error: Process completed with exit code 127.************************************

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Have node installed in the GitHub action
1.  This is step 2. All steps should start with '1.'
2. jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event_name == 'push'
    - uses: actions/setup-node@v1
      with:
        node-version: '=16'
        check-latest: true
   
    - name: Install Salesforce CLI
      run: |
        npm install --global sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core

### Expected result

SFDX should be isntalled

### Actual result

error as mention above

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- Paste the output here
### Additional information

_Feel free to attach a screenshot_.

**Comment by gsinha-atrium** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/63996961/143201509-331f772c-8a81-4975-898f-fbc4f81e8215.png)

**Comment by AllanOricil** [comment]
@gsinha-atrium 
Don't do this way. You will spend lots of minutes intalling sfdx over and over again. Build a docker image and use it in your jobs. This will you will reduce the amount of time for your job to run, and you will he sure sfdx is available during your job.

Search for the job.container entry.

**Comment by ankurklient** [comment]
I also getting the same issue. I want to know that if this resolve or investigating stage.
error same as above.

**Comment by mshanemc** [comment]
@ankurklient I can't replicate this at all.  We run dozens of jobs/day that install the `sfdx-cli` via npm on github actions.

the only weird thing I see is the `setup-node` action being on v1 (v3 is latest and that's what we use)

If you've got a replication, please open a new issue.
