### ISSUE TITLE
Enable sfdx force:source:deploy to return code coverage

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1294]
**Is your feature request related to a problem? Please describe.**
I was wondering if it is possible to add a new flag to `sfdx force:source:deploy -c -l RunLocalTests` to return the current code coverage after the deployment validation.

This [article](https://help.salesforce.com/s/articleView?id=000335222&type=1) shows how to do it accurately, but it would be nice to have SFDX doing that for us.

**What are you trying to do**
Return codeCoverage when running `sfdx force:source:deploy`

**Describe the solution you'd like**
Add a new flag to `sfdx force:source:deploy` to output the code coverage

**Describe alternatives you've considered**
I was thinking about automating the steps from this article https://help.salesforce.com/s/articleView?id=000335222&type=1

**Additional context**
N/A

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10226933](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000SMlDAYA1/view)

**Comment by AllanOricil** [comment]
this can already be done. my bad
