### ISSUE TITLE
sfdxAuthUrl not present when running sfdx force:org:display --verbose --json

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1297]
### Summary

In the [docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_auth_sfdxurl.htm#cli_reference_auth_sfdxurl_store) it says that I can use an org that is already authorized to get sfdxAuthUrl and save it to a file using this command:

`sfdx force:org:display -u <DevHub> --verbose --json > authFile.json`

I have several orgs connected to sfdx that were authorized using `sfdx auth:jwt:grant`, and when I try the above command with those, my outputs are generated but with no `sfdxAuthUrl` attribute.

My hypothesis is that it only shows this attribute if my org was authorized using `sfdx auth:web:login`
Because I have an org that I authorized with `sfdx auth:web:login` and the `sfdxAuthUrl` attribute is present when I use `--verbose`.

### Steps To Reproduce:

1 - connect an org using `sfdx auth:jwt:grant`
2 - run `sfdx force:org:display -u <ORG_ALIAS> --verbose --json > authFile.json`
3 - verify that authFile.json does not contain `sfdxAuthUrl`
4 - delete the org from sfdx
5 - connect the same org to sfdx usign `sfdx auth:web:login`
6 - run `sfdx force:org:display -u <ORG_ALIAS> --verbose --json > authFile.json`
7 - verify that authFile.json contains `sfdxAuthUrl`

### Expected result

As described in the Docs, `sfdxAuthUrl` should be available when running  `sfdx force:org:display -u <ORG_ALIAS> --verbose --json > authFile.json`

### Actual result

`sfdxAuthUrl` is not available when the org was authorized using jwt

### System Information

````bash
#18 [13/16] RUN sfdx --version
#18 0.724 sfdx-cli/7.129.0 linux-x64 node-v17.1.0
````

````bash
#19 [14/16] RUN sfdx plugins --core
#19 0.792 @oclif/plugin-autocomplete 0.3.0 (core)
#19 0.792 @oclif/plugin-commands 1.3.0 (core)
#19 0.792 @oclif/plugin-help 3.2.7 (core)
#19 0.792 @oclif/plugin-not-found 1.2.4 (core)
#19 0.792 @oclif/plugin-plugins 1.10.3 (core)
#19 0.793 @oclif/plugin-update 1.5.0 (core)
#19 0.793 @oclif/plugin-warn-if-update-available 1.7.2 (core)
#19 0.793 @oclif/plugin-which 1.0.3 (core)
#19 0.793 @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
#19 0.793 alias 1.1.22 (core)
#19 0.793 apex 0.3.0 (core)
#19 0.793 auth 1.7.6 (core)
#19 0.793 config 1.2.48 (core)
#19 0.793 custom-metadata 1.0.12 (core)
#19 0.793 data 0.6.5 (core)
#19 0.794 generator 1.2.1 (core)
#19 0.794 limits 1.2.3 (core)
#19 0.794 org 1.9.2 (core)
#19 0.794 salesforce-alm 53.4.5 (core)
#19 0.794 schema 1.0.10 (core)
#19 0.794 sfdx-cli 7.129.0 (core)
#19 0.794 sfdx-git-delta 4.11.0 (link) /usr/local/lib/node_modules/sfdx-git-delta
#19 0.794 source 1.5.3 (core)
#19 0.794 telemetry 1.3.0 (core)
#19 0.794 templates 52.6.0 (core)
#19 0.794 trust 1.0.11 (core)
#19 0.794 user 1.5.3 (core)
````

### Additional information

N/A

**Comment by AllanOricil** [comment]
@amphro @azlam-abdulsalam @mshanemc  could you help here?

**Comment by AllanOricil** [comment]
It is indeed lack of proper documentation. I found in another page that auth url is only available if the authentication has been done through the web:login command

https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_view_info.htm

"...However, --verbose displays the Sfdx Auth Url only if you authenticated to the org using auth:web:login and not auth:jwt:grant...."

Could you guys please specify this in the page that talks about the sfdx auth url command?

**Comment by mshanemc** [comment]
You figured it out.  I'll mark this as a doc request.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10236143](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000Tox4DYAR/view)

**Comment by mshanemc** [comment]
fixed here https://github.com/salesforcecli/plugin-auth/pull/305

going out in RC today.

That'll update the docs eventually (maybe next week)
