### ISSUE TITLE
Add packageId to force:package:version:report response

### ISSUE THREAD

**Issue by fischerp** [forcedotcom/cli#13]
**Is your feature request related to a problem? Please describe.**
I need to get the packageId when executing the following command.
`sfdx force:package:version:report -p "myPackage" --json`
or
`sfdx force:package:version:report -p "04t50000000AbcD" --json`

**What are you trying to do**
I want to get the package id from a specific attribute called packageId. Currently the Id is available on the message, but there is no easy way to extract it.

**Describe the solution you'd like**
I want to execute `sfdx force:package:version:report -p "myPackage" --json` or `sfdx force:package:version:report -p "04t50000000AbcD" --json` and I want to have an easy way to get the ID from the response.

Current return:
`{"message":"The Subscriber Package Version Id 04t50000000AbcD is invalid, ... `

Expected result:
`{"packageId":"04t50000000AbcD","message":"The Subscriber Package Version Id 04t50000000AbcD is invalid, ... `

**Describe alternatives you've considered**
A poor alternative would be extract it from specific parts to the current response or by reading the _sfdx-project.json_ file to get the ID.

**Comment by clairebianchi** [comment]
@sfdx-db-gmail, Please take a look at this feature request for Packaging

**Comment by sfdc-db-gmail** [comment]
@fischerp - can't you parse force:package:version:list and get the 04t from there? Cc @clairebianchi

**Comment by fischerp** [comment]
Thanks @sfdc-db-gmail and @clairebianchi, I'm parsing the response and extracting the ID, but I don't think it's a good solution because I would be relying on a message. 
The real problem is that I didn't find any native way to list packages and aliases from local "sfdx-project.json", for sure there is work around to get the Alias and Id.
The feature proposed by @jefersonchaves (https://github.com/forcedotcom/cli/issues/12) would do the trick, but that one is a new implementation, while this one requires the exposure of an extra variable.

**Comment by mshanemc** [comment]
If you're trying to get information out of a command, instead of parsing the message, use --json for a structured result (and one that should should be stable where we can't remove properties)

That should be easily parseable with something jq https://jqlang.github.io/jq/
