### ISSUE TITLE
sfdx force:source:deploy does not give progress updates on wait

### ISSUE THREAD

**Issue by MGarfOppLoans** [forcedotcom/cli#130]
When running `sfdx force:source:deploy` it does not provide status updates on the deploy. Instead the CLI hangs unitl its finished.

**Comment by clairebianchi** [comment]
If you add `--wait 0` you will get async mode, see the help output:

![image](https://user-images.githubusercontent.com/41926844/60921218-d539e200-a24e-11e9-8bfe-aa054c95bef5.png)

**Comment by MGarfOppLoans** [comment]
yep but that doesn't provide status updates you have then build a custom polling mechanism to get the progress. @clairebianchi

**Comment by pbergner** [comment]
Not sure why this one was closed out @clairebianchi ? Skipping it by going async isn't really addressing the issue that there is no progress indicator or data logged out while its running

**Comment by shetzel** [comment]
By default, `force:source:deploy` uses the progress bar so the original post is out of date.

If you run `force:source:deploy -w 0` that will make the command async.  You would then use `force:source:deploy:report` to get the progress.

**Comment by pbergner** [comment]
I won't hijack OPs request but I'm migrating from force.com migration tool to sfdx in CircleCI and the ant tool logged out the status of the deployment and test results every few seconds. I understand based on your comment I can write something to do it, unfortunately I'm not great at shell scripts. Would be nice if it was handled internally, unless I'm missing something.

**Comment by shetzel** [comment]
Typically, CI and scripts would append `--json` to the commands to get JSON parsable response objects that include a status or exit code as well as the deployment results.  That does not give incremental updates but why does CI care about those updates?  It would be an additional step, but an alternative would be to run `force:source:convert` followed by `force:mdapi:deploy` and that will provide progress updates.  Hope this helps you.
