### ISSUE TITLE
Metadata API request failed: connect ETIMEDOUT 160.8.252.85:443

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1301]
### Summary

This issue is happening quite often. Maybe sfdx should try the connection again up to N times. N could be an env variable with a default value of 2. This way we don't need to control it by ourselves.

````bash
Error: connect ETIMEDOUT 160.8.252.85:443
    at TCPConnectWrap.afterConnect [as oncomplete*** (node:net:1161:16) ***
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '160.8.252.85',
  port: 443
***
***
  "status": 1,
  "name": "MetadataTransferError",
  "message": "Metadata API request failed: connect ETIMEDOUT 160.8.252.85:443",
  "exitCode": 1,
  "commandName": "Deploy",
  "stack": "MetadataTransferError: Metadata API request failed: connect ETIMEDOUT 160.8.252.85:443\n    at MetadataApiDeploy.pollStatus (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/client/metadataTransfer.js:78:27)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Deploy.deploy (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-source/lib/commands/force/source/deploy.js:94:37)\n    at async Deploy.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-source/lib/commands/force/source/deploy.js:37:9)\n    at async Deploy._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/node_modules/sfdx-cli/dist/cli.js:162:47)\nDUE TO:\nError: connect ETIMEDOUT 160.8.252.85:443\n    at TCPConnectWrap.afterConnect [as oncomplete*** (node:net:1161:16)\nOuter stack:\n    at Function.wrap (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at Deploy.catch (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:248:67)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Deploy._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/node_modules/sfdx-cli/dist/cli.js:162:47)",
````
### Steps To Reproduce:

Happens randomly and with a high frequency. It can't be reproduced.

### Expected result

If a ETIMEDOUT happens, sfdx should try again up to N times. N could be an Env Variable.

### Actual result

sfdx doesnt seem to try again when a connection can't be stablished with the server

### System Information

````bash
#18 [13/16] RUN sfdx --version
#18 0.689 sfdx-cli/7.129.0 linux-x64 node-v17.1.0
#18 DONE 0.8s

#19 [14/16] RUN sfdx plugins --core
#19 0.601 @oclif/plugin-autocomplete 0.3.0 (core)
#19 0.601 @oclif/plugin-commands 1.3.0 (core)
#19 0.601 @oclif/plugin-help 3.2.9 (core)
#19 0.601 @oclif/plugin-not-found 1.2.4 (core)
#19 0.602 @oclif/plugin-plugins 1.10.4 (core)
#19 0.602 @oclif/plugin-update 1.5.0 (core)
#19 0.602 @oclif/plugin-warn-if-update-available 1.7.3 (core)
#19 0.602 @oclif/plugin-which 1.0.3 (core)
#19 0.602 @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
#19 0.602 alias 1.1.22 (core)
#19 0.602 apex 0.3.0 (core)
#19 0.602 auth 1.7.6 (core)
#19 0.602 config 1.2.48 (core)
#19 0.602 custom-metadata 1.0.12 (core)
#19 0.602 data 0.6.5 (core)
#19 0.602 generator 1.2.1 (core)
#19 0.602 limits 1.2.3 (core)
#19 0.602 org 1.9.2 (core)
#19 0.602 salesforce-alm 53.4.5 (core)
#19 0.602 schema 1.0.10 (core)
#19 0.602 sfdx-cli 7.129.0 (core)
#19 0.602 sfdx-git-delta 4.11.0 (link) /usr/local/lib/node_modules/sfdx-git-delta
#19 0.602 source 1.5.3 (core)
#19 0.602 telemetry 1.3.0 (core)
#19 0.602 templates 52.6.0 (core)
#19 0.602 trust 1.0.11 (core)
#19 0.602 user 1.5.3 (core)
#19 DONE 0.7s
````

### Additional information

N/A

**Comment by mshanemc** [comment]
First, come context: 
we see about **50 of this error per day** across the entire CLI (>2 million executions per day)  => **0.0025%**

So when you say `This issue is happening quite often` and `Happens randomly and with a high frequency` I wonder if this is a network problem unique to your location/CI or wherever these errors come from (or something between you and where your orgs live).

---
I'm not saying we can't try to write better exception handling logic into jsforce's `Connection` code but that you might have a different problem.

Are you getting this on source `deploy` or `retrieve` or both?

[deploy we'd be able to retry--you could recover from it by asking the mdapi for the same deployment's ID.  Retrieve are "gone" after they finish, so there's less we could do if it completed during the "timeout"--the retry would still result in an error

**Comment by mshanemc** [comment]
@W-5657753@

**Comment by AllanOricil** [comment]
> First, come context: we see about **50 of this error per day** across the entire CLI (>2 million executions per day) => **0.0025%**
> 
> So when you say `This issue is happening quite often` and `Happens randomly and with a high frequency` I wonder if this is a network problem unique to your location/CI or wherever these errors come from (or something between you and where your orgs live).
> 
> I'm not saying we can't try to write better exception handling logic into jsforce's `Connection` code but that you might have a different problem.
> 
> Are you getting this on source `deploy` or `retrieve` or both?
> 
> [deploy we'd be able to retry--you could recover from it by asking the mdapi for the same deployment's ID. Retrieve are "gone" after they finish, so there's less we could do if it completed during the "timeout"--the retry would still result in an error

The command I'm getting this problem is `sfdx force:source:deploy` and it is executed on Github Action servers. 

update: and it does not happen with high frequency. I did not run tests to conclude that for sure. Sorry for the missinformation.

**Comment by mshanemc** [comment]
Do the times where the error happens coincide with the recent issue with github actions (see their status history for timestamps)

**Comment by AllanOricil** [comment]
@mshanemc no, I had this issue after their services recovered*

**Comment by ShriyanshBain** [comment]
I am also facing same issue

**Comment by mshanemc** [comment]
I'm opening up a PR for this in SDR...that'll at least solve some of these for deployments and other metadata operations.

**Comment by ssk42** [comment]
Is there a workaround before the PR is fully in?

**Comment by mshanemc** [comment]
> Is there a workaround before the PR is fully in?

Not that I can think of.
