### ISSUE TITLE
Deployment Failing for Reports with Record Type filter 

### ISSUE THREAD

**Issue by Janani-26** [forcedotcom/cli#1302]
### Summary

When we retrieve reports with record type filters, the deployment fails with the error "Required field is missing: RecordType"

### Steps To Reproduce:

1.  Retrieve Reports that has record type Filter and built upon Report type that has more than one Related Objects.
2.  Try to deploy the report to target org 
3. There is a comma(,) added after we retrieve the Report in the Criteria Items Metadata
4.  If the (,) is removed and trying to deploy it it is successful

### Expected result

(,) should not be appended in the filter Criteria <value> tag after we retrieve and Report deployment should be successful.

        <criteriaItems>
            <column>Account.Object2_r$RecordType</column>
            <columnToColumn>false</columnToColumn>
            <isUnlocked>true</isUnlocked>
            <operator>equals</operator>
            <value>Object2__c.Record_Type1,Object2__c.Record_Type2,Object2__c.Record_Type3</value>
        </criteriaItems>

### Actual result

There is a (,) appended in the filter Criteria <value> tag  and causing Report deployment failure.

       <criteriaItems>
            <column>Account.Object2_r$RecordType</column>
            <columnToColumn>false</columnToColumn>
            <isUnlocked>true</isUnlocked>
            <operator>equals</operator>
            <value>,Object2__c.Record_Type1,Object2__c.Record_Type2,Object2__c.Record_Type3</value>
        </criteriaItems>

### System Information

 {
        "cliVersion": "sfdx-cli/7.129.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.15.5",
        "pluginVersions": [
                "@dxatscale/sfpowerscripts 9.3.12",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.9 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.4 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.22 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.6 (core)",
                "config 1.2.48 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.5 (core)",
                "generator 1.2.1 (core)",
                "limits 1.2.3 (core)",
                "org 1.9.2 (core)",
                "salesforce-alm 53.4.5 (core)",
                "schema 1.0.10 (core)",
                "sfdmu 4.10.3",
                "sfdx-cli 7.129.0 (core)",
                "sfpowerkit 3.3.4",
                "source 1.5.3 (core)",
                "telemetry 1.3.0 (core)",
                "templates 52.6.0 (core)",
                "trust 1.0.11 (core)",
                "user 1.5.3 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19042"
}

**Comment by mshanemc** [comment]
You should open a support case for this one--it's coming like that from the metadata API, not the CLI.
