### ISSUE TITLE
Some users getting `Unexpected argument: --skipconnectionstatus` from `sfdx force:org:list` even when seemingly on up-to-date CLI installs

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#1304]
This has actually been happening for a while, but after chatting with @mshanemc about it, it seems that an issue here is warranted. IC2 runs `sfdx force:org:list --skipconnectionstatus` (most of the time, at least) when listing connections to avoid what can be extremely long-running CLI processes just to list CLI-based connections. That argument has been in place for a long, long time, but I still have users semi-regularly report the command failing with `Unexpected argument: --skipconnectionstatus`. What's really strange, though, is that this occurs even after those users run `sfdx update` and show evidence that their CLI install is completely up-to-date, at least at a superficial level. The only thing that actually "fixes" it is a full uninstall/reinstall of the CLI. For what it's worth, this has happened twice in the past week (with the most recent instance being about an hour ago), so it's very much an active issue.

As you can imagine, because this seems to occur only when the CLI is some particular state, I can't provide steps to reproduce. What I can do, though, is ask the next user(s) who encounter it to run `sfdx version --verbose` (and anything else that might be useful for diagnostic purposes) to get more information about these stuck CLI installs.

It's also worth noting that while this is a specific example of a bad CLI install state, it's not the only one I've encountered. Unfortunately I don't have specifics off the top of my head, but there have been quite a few other times that the CLI (as executed by IC2) has behaved VERY strangely for users, and ultimately only a full uninstall/reinstall would resolve those issues. I'll be happy to let you know the specifics of those when I see them again, but I think the takeaway is that it does seem that that CLI can get into a bad state over time after repeated in-place updates.

Let me know if there's any other useful info I can provide, and as stated previously, once I have useful diagnostic info from an install exhibiting these issues, I'll add it here.

**Comment by mshanemc** [comment]
I dug around in the telemetry for these errors, and they have a few things in common--they're coming from a really old version the `salesforce-alm` plugin.

If that's the case, you need to uninstall it via either `sfdx plugins:uninstall salesforcedx` (how most people get themselves in this predicament) or `sfdx plugins:uninstall salesforce-alm` if you ever installed that one manually.

**Comment by mshanemc** [comment]
the slightly longer-term solution for this is to add a warning that a user has the old `salesforcedx` installed with a link to the deprecation release note and what to do about it.

**Comment by SCWells72** [comment]
@mshanemc I was actually thinking earlier today that it might be worthwhile to do exactly that if it's possible. It seems like enough people are on a weird offshoot install that can present non-obvious issues that it's worth giving them some guidance when they try to update that install.
