### ISSUE TITLE
No retrieving publishBehavior field for platform event

### ISSUE THREAD

**Issue by jpsturla** [forcedotcom/cli#1306]
I’m having a problem with CLI when retrieving platform event. When doing this the file for the object itself is being retrieve with then “publishBehavior” field missing. 

In this first shot you can see that before retrieving, the file has "<publishBehavior>PublishAfterCommit</publishBehavior>".

![Screen Shot 2021-12-02 at 11 35 38](https://user-images.githubusercontent.com/3305862/144442624-b9837f95-bd5b-4f37-8a74-5995e2f87cb7.png)

I'm doing the retrieve in this way:

sfdx force:source:retrieve -u jpsturla@trilogyed.com.dmrefactor -x /Users/juanpablosturla/Downloads/package.xml

where package.xml contains the following only:

`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Financial_Event__e</members>
        <name>CustomObject</name>
    </types>
    <version>45.0</version>
</Package>
`

I this second shot you can see the command run and at the top the file updated with the field “publishBehavior” removed the file after the retrieve.

![Screen Shot 2021-12-02 at 11 39 31](https://user-images.githubusercontent.com/3305862/144443339-c04a2d79-9e3f-4066-ba68-88d246ce471e.png)

**Comment by mshanemc** [comment]
That one also is coming from the metadata API like that.  We can't fix it from the CLI.

[if you can't open a case, let me know and I can try to get the proper team's attention, though it gets more visibility with a case from outside the company.]. Nice repro, though.
