### ISSUE TITLE
Unsupported metadata type: CustomIndex

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#1307]
### Summary

We can’t retrieve the specified metadata object: CustomIndex. Certain metadata types, like MyObject__c.Test__c are not currently supported by the CLI.

### Steps To Reproduce:

1. Create a text field
2. Mark field as an external ID field which will make the field Indexed

### Expected result

The field should extract when using the pull command

### Actual result

Received an error
We can’t retrieve the specified metadata object: CustomIndex. Certain metadata types, like MyObject__c.Test__c are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type

### System Information

{
	"cliVersion": "sfdx-cli/7.129.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.13.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.3 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"alias 1.1.22 (core)",
		"auth 1.7.6 (core)",
		"config 1.2.48 (core)",
		"generator 1.2.1 (core)",
		"salesforcedx 52.0.0",
		"├─ data 0.4.11",
		"├─ limits 1.2.1",
		"├─ schema 1.0.7",
		"├─ org 1.6.6",
		"├─ custom-metadata 1.0.12",
		"├─ user 1.3.0",
		"├─ templates 51.5.0",
		"├─ apex 0.2.2",
		"├─ @salesforce/sfdx-plugin-lwc-test 0.1.7",
		"└─ salesforce-alm 52.0.0",
		"sfdx-cli 7.129.0 (core)",
		"sfdx-git-delta 4.11.0",
		"source 1.5.3 (core)",
		"telemetry 1.3.0 (core)",
		"trust 1.0.10 (core)"
	],
	"osVersion": "Darwin 21.1.0"
}

**Comment by mshanemc** [comment]
`sfdx plugins:uninstall salesforcedx`

background:  https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71063-june-17-2021

reopen if that doesn't solve it for you.

**Comment by timpaulaskas-ds** [comment]
I uninstalled as suggested, but still receive the same error:
{
	"cliVersion": "sfdx-cli/7.129.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.13.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.3 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.1.22 (core)",
		"apex 0.3.0 (core)",
		"auth 1.7.6 (core)",
		"config 1.2.48 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.5 (core)",
		"generator 1.2.1 (core)",
		"limits 1.2.3 (core)",
		"org 1.9.2 (core)",
		"salesforce-alm 53.4.5 (core)",
		"schema 1.0.10 (core)",
		"sfdx-cli 7.129.0 (core)",
		"sfdx-git-delta 4.11.0",
		"source 1.5.3 (core)",
		"telemetry 1.3.0 (core)",
		"templates 52.6.0 (core)",
		"trust 1.0.10 (core)",
		"user 1.5.3 (core)"
	],
	"osVersion": "Darwin 21.1.0"
}

**Comment by mshanemc** [comment]
did you run `sfdx update` afterward?

**Comment by timpaulaskas-ds** [comment]
I sure did.
<img width="2198" alt="Screen Shot 2021-12-02 at 2 00 52 PM" src="https://user-images.githubusercontent.com/85636164/144510258-205e652b-3b64-4b57-961b-52202e054ba1.png">

However, I still get the error:
ERROR running force:source:pull:  Entity type 'WaveDataset' is not available in this organization
<img width="2198" alt="Screen Shot 2021-12-02 at 2 01 38 PM" src="https://user-images.githubusercontent.com/85636164/144510346-91cd635b-3190-41a9-8bdd-90eb753569e7.png">

To get around it I have to run the tracking:reset command which isn't ideal.

**Comment by ghost** [comment]
Sorry I'm mixing up the 2 errors. This issue is resolved with the fix, the WaveDataset isn't. I'll put the comment on that issue.
