### ISSUE TITLE
Entity type 'WaveDataset' is not available in this organization

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#1308]
### Summary

My sandbox has WaveDataset showing as Remote Add and the CLI will not ignore it and errors stating that it is not supported in this organization.

### Steps To Reproduce:

1. Create a sandbox from an production instance that has Einstein Analytics enabled
2. Wait a couple of days
3. Run status and you should see WaveDataset showing as Remote Add
4. Run pull command
5. You will get an error

### Expected result

If the WaveDataset is not available then I would expect the status and pull command to ignore it

### Actual result

ERROR running force:source:pull:  Entity type 'WaveDataset' is not available in this organization

### System Information

{
	"cliVersion": "sfdx-cli/7.129.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.13.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.3 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"alias 1.1.22 (core)",
		"auth 1.7.6 (core)",
		"config 1.2.48 (core)",
		"generator 1.2.1 (core)",
		"salesforcedx 52.0.0",
		"├─ data 0.4.11",
		"├─ limits 1.2.1",
		"├─ schema 1.0.7",
		"├─ org 1.6.6",
		"├─ custom-metadata 1.0.12",
		"├─ user 1.3.0",
		"├─ templates 51.5.0",
		"├─ apex 0.2.2",
		"├─ @salesforce/sfdx-plugin-lwc-test 0.1.7",
		"└─ salesforce-alm 52.0.0",
		"sfdx-cli 7.129.0 (core)",
		"sfdx-git-delta 4.11.0",
		"source 1.5.3 (core)",
		"telemetry 1.3.0 (core)",
		"trust 1.0.10 (core)"
	],
	"osVersion": "Darwin 21.1.0"
}

### Additional information

_Feel free to attach a screenshot_.

**Comment by mshanemc** [comment]
same solution as https://github.com/forcedotcom/cli/issues/1307

**Comment by ghost** [comment]
After doing removing the plugin and updating the CLI I still get this error.
<img width="2198" alt="Screen Shot 2021-12-02 at 2 00 52 PM" src="https://user-images.githubusercontent.com/85636164/144510740-97653c89-a7a2-4905-a0de-52eb1372e1e8.png">

<img width="2198" alt="Screen Shot 2021-12-02 at 2 01 38 PM" src="https://user-images.githubusercontent.com/85636164/144510761-8d4433e2-465f-4de9-bf37-7dce1e37605a.png">

**Comment by mshanemc** [comment]
Do you have any idea what's happening during this step that I could replicate?
> Wait a couple of days

Is someone/something creating the dataset (ex: an automated process, perhaps?)
If not, does it happen if I go in the the Analytics UI and just create a dataset?

One more idea--can you try it with `force:source:beta:pull`? (you'll need a new project for that to keep your existing tracking files).  If that works OK, we're unlikely to fix it in the current `pull`.

**Comment by ghost** [comment]
Hi Shane,

My guess is that we have Einstein Analytics running in production and therefore these WaveDataset are getting updated in the sandbox on some sort of recurring schedule.

So here is what I just did:
1. sfdx force:project:create -n WaveTest
2. cd WaveTest
3. sfdx force:source:beta:status -u ALIAS
4. (Verified that the are several WaveDataset that show as Remote Add)
5. sfdx force:source:beta:pull -u ALIAS

After several minutes the process completed and the WaveDataset was listed as warning and didn't prevent it from completing.

=== Retrieved Source Warnings
FILE NAME               PROBLEM
──────────────────────  ───────────────────────────────────────────────────────────────────────────────────────────────
unpackaged/package.xml  Entity type 'WaveDataset' is not available in this organization


So it appears that the beta is handling WaveDataset already. I can use the beta as a work-around until it goes GA.

**Comment by mshanemc** [comment]
closed with new commands GA
