### ISSUE TITLE
Push Error 'Invalid type: AccountContactRelation'

### ISSUE THREAD

**Issue by bluewave-js** [forcedotcom/cli#1309]
We are migrating our customers source to scratch orgs and the customer is using Contacts to Multiple Accounts. We have observed a consistent error message when trying to deploy any of their existing functionality referencing the standard AccountContactRelation junction object which is a hard blocker preventing us from moving to scratch orgs. 

**Steps to recreate the issue**
1.) generate a scratch org with Contacts to Multiple Accounts enabled. We used org shape but you could set it manually as a post-initialization step. Our scratch def file only contains variables for “orgName” and “sourceOrg.” Since the customer is using this setting in prod, we believe the setting is carried over. The Contacts to Multiple Accounts setting is definitely enabled in our scratch orgs, we checked in the UI. 
2.) create a test class that references the standard AccountContactRelation junction object
3.) add this single test class to a package file running api 47 or higher
4.) use the sfdx force:source:push command to deploy the package to a scratch org
Expected Result: deployment is successful
Actual Result: deployment fails with 'Invalid type: AccountContactRelation ERROR running force:source:push: Push failed.'

Subsequently, we also tried to create this single test class directly from the dev console of the target scratch org and it failed with the same error.

Attaching our test class. We are using sfdx-cli 7.126.0
[TestAccountContactRelation.cls.txt](https://github.com/forcedotcom/cli/files/7648019/TestAccountContactRelation.cls.txt)
[TestAccountContactRelation.cls.meta.txt](https://github.com/forcedotcom/cli/files/7648020/TestAccountContactRelation.cls.meta.txt)

**Comment by mshanemc** [comment]
I created a scratch org with this 

```
"features": [
    "EnableSetPasswordInApi",
    "ContactsToMultipleAccounts"
  ],
```

It had the feature enabled in the setup (I checked in the UI), and then I pushed your class via `sfdx force:source:push`.

Are you only able to hit the problem when using the results of `org:shape` ( that is, you have a `"sourceOrg": "00Dxxxxxxxxxxxx"` in your definition file?

sfdx-project.json contains
`"sourceApiVersion": "52.0"`

and the apexClass is also `<apiVersion>52.0</apiVersion>`

**Comment by bluewave-js** [comment]
Thanks so much for your prompt response. Yes, we initially hit this error using org:shape. Leave it with us, we will run a few additional tests tomorrow explicitly declaring the ContactsToMultipleAccounts setting in the scratch def file.

**Comment by bluewave-js** [comment]
Hi Shane, 

We have run further tests including the one you proposed above. I am attaching our test results. There's an issue enabling the ContactToMultipleAccounts feature in AccountSettings in the mdapi. We're guessing this issue extends to org shape as we experience the same error via both methods. 

Unfortunately, using the scratch definition file without org shape is not a viable option for us at this time because of the amount of effort required for us to determine the right combination of features and settings to accurately match customers existing prod orgs. Instead, we are manually disabling and reenabling the ContactToMultipleAccounts feature directly in the scratch org UI (Setup) which resolves the issue. However, this is not a long-term solution for the likes of CI/CD. We will look into node.js and puppeteer as a last resort to automate these manual steps. Ideally, this issue would be resolved within the mdapi so that we can successfully enable ContactToMultipleAccounts using AccountSettings. We assume but cannot be sure that this would also fix the same error resulting from org shape.

[CLI Issue 1309 Test Results.docx](https://github.com/forcedotcom/cli/files/7669474/CLI.Issue.1309.Test.Results.docx)

**Comment by mshanemc** [comment]
How close is this issue to what you see?  It reports it working intermittently: https://github.com/forcedotcom/cli/issues/901

**Comment by bluewave-js** [comment]
Hi Shane,

Thanks again for your input. [Issue #901](https://github.com/forcedotcom/cli/issues/901) looks be be describing the same bug however what's unique for them was that '_The issue seems to present itself randomly_.' For us, that is not the case. We have not experienced any discrepancy in behavior over the course of our testing and the generation of dozens of scratch orgs over the last week. Perhaps, it is too small a sample size but we have only had one outcome using the mdapi or org shape and that is the invalid type error. 

Per the bot's comment above we have also opened a Salesforce Support Case #41737346.

Would you be able to point us in the direction of the Salesforce PM for the mdapi so we can chase down a status/roadmap for this bug? We'd like to do our part to draw attention to it on behalf of our customers.

**Comment by mshanemc** [comment]
I'd try PM Austin Tam, but that's a bit of a guess

**Comment by ceeweed** [comment]
Sorry if this is the wrong place for this but @bluewave-js did you ever receive the answers you were looking for? We're experiencing the intermittent version of this problem I was hoping you had some advice or a workaround.

**Comment by bluewave-js** [comment]
Hi @ceeweed, The Salesforce product team is aware of the issue however there is no ETA or commitment to a resolution at this time. As a result, I am forced to handle this as a manual step in the scratch org creation process each time before I force deploy any metadata. Ugly, I know. It prevents me from easily achieving an automated CI process. I really hope Salesforce will resolve this mdapi bug in the near future. Please report and follow the relevant known issues below:

>> https://trailblazer.salesforce.com/issues_view?id=a1p4V000001s8OlQAI&title=contactstomultipleaccounts-feature-intermittently-fails-to-enable-during-the-scratch-org-signup-using-the-orgshape
>> https://trailblazer.salesforce.com/issues_view?id=a1p4V000001plFDQAY

**Comment by ceeweed** [comment]
Thanks for the info @bluewave-js!

I've had success adding [this workaround](https://salesforce.stackexchange.com/a/360103) to my scripts for creating scratch orgs for developer use but haven't figured out how to avoid this problem when calculating code coverage during package version creation. Agreed I hope this does get fixed soon. Looks like it's org dependent packages for us in the meantime!

**Comment by sikkrasmus** [comment]
Any updates or possible workaround for this?

**Comment by shetzel** [comment]
Looking at the known issue mentioned above and the internal work items associated with it, it appears that this is no longer an issue.  If anyone sees this issue (the `ContactsToMultipleAccounts` feature not being applied during org signup) please contact support.  There is nothing the CLI can do about it.
