### ISSUE TITLE
Beta `status` command needs flag to omit ignored files

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#1312]
**Is your feature request related to a problem? Please describe.**

The [beta source tracking][1] ticket explains,

> The output of `force:source:beta:status` shows all changes but indicates which ones, if any, are covered by your .forceignore file (and therefore won’t be part of push/pull).  

This is a big deviation from the prior behavior, and it would be useful to have a flag which removes the IGNORED column and omits all ignored files, producing similar output to the original-recipe `status` command

[1]: https://github.com/forcedotcom/cli/issues/1258

**What are you trying to do**
I work on a project with a large DX repo.  There are a lot of files which are in the repo but are normally included in `.forceignore`.  This is generally because we never want changes to these files to inadvertently be deployed to production, but we do want the original sources tracked (and we need them for scratch org builds, see below).  This can lead to a lot of extraneous output.

As an aside:  We have a scratch org build script (and automation pipeline) which temporarily replaces our standard `.forceignore` with a scratch-build-specific version, allowing many of those items to be deployed to a new scratch.  

**Describe the solution you'd like**

A switch to `force:source:beta:tracking` to exclude the IGNORED column and all ignored metadata components.

**Describe alternatives you've considered**

None found.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10271553](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000VoTD4YAN/view)

**Comment by shetzel** [comment]
The `concise` flag should now be available for use in SFDX CLI v7.134.0
