### ISSUE TITLE
Source tracking problems with non-packaged metadata of unlocked package Custom MDT

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#1313]
### Summary

Given a custom metadata type (MDT) installed by an unlocked package, non-packaged metadata of that type are not correctly tracked by `force:source:pull/status`, nor by `force:source:beta:pull/status`.

### Steps To Reproduce:

1. Install an unlocked package containing a custom metadata type.   We created an unlocked package of (our slightly modified version of) [Salesforce Labs' Enhanced Lightning Grid][1], which contains the Custom Metadata Type `SDGDefaults__mdt`.
2. In a scratch org, create a new metadata entry of the custom metadata type.
3. `sfdx force:source:status`

[1]: https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000EVK8iUAH

### Expected result

The new metadata should be listed as a remote change.

### Actual result

No change is shown.  This can also be tested with `pull` instead of `status`; the new metadata is not pulled.  

Note that if you have a metadata record in your local source (`force-app/main/default/customMetdata/MDTName.DeveloperName.md-meta.xml`) and push source, it will be correctly pushed.  Once that's done, any edits made in the org will NOT appear in `force:source:status`.

### System Information
```
{
	"cliVersion": "sfdx-cli/7.127.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.13.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.3 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.1 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.1.22 (core)",
		"apex 0.3.0 (core)",
		"auth 1.7.5 (core)",
		"config 1.2.47 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.4 (core)",
		"generator 1.2.1 (core)",
		"limits 1.2.3 (core)",
		"org 1.9.0 (core)",
		"salesforce-alm 53.4.2 (core)",
		"schema 1.0.10 (core)",
		"sfdx-cli 7.127.0 (core)",
		"sfdx-fmz-plugin 1.1.0 (1.1.0)",
		"sfpowerkit 3.3.4",
		"source 1.4.0 (core)",
		"telemetry 1.2.8 (core)",
		"templates 52.6.0 (core)",
		"trust 1.0.10 (core)",
		"user 1.5.2 (core)"
	],
	"osVersion": "Darwin 18.7.0"
}
```
### Additional information

We have been using this model for some time with another unlocked package, and this appears to be a recent change.  We aren't sure how long it has been changed, but we know this issue didn't exist a few months ago.

One workaround is to disassociate the Custom MDT from the unlocked package.  Setup > Installed Packaged > [package name] > View Components > [Click Remove link next to the Custom MDT].  Once this is done, any subsequent edits to existing Metadata records or adds of new Metadata are reported by `force:source:status`, but prior edits/adds are not reported.

I reinstalled the unlocked package (to restore the association to the MDT), and tested this with the [beta][1] source tracking commands, with mixed results.  I tested as follows:
1. `sfdx force:source:tracking:clear` to prep for the switch to beta tracking
2. `sfdx force:source:beta:push -f` to push all local source.
3. `sfdx force:source:beta:status` then revealed new Metadata records I had created previously and which have not been pulled yet; This is good.
4. Created another new Metadata record in my scratch and ran `beta:status`; the new metadata was not reported.  This is bad.
5.  Just to close the loop, I ran `sfdx force:source:tracking:beta:clear` followed by `sfdx force:source:push -f` to return to original-recipe source tracking, but `status` reports none of the new Metadata records.

[1]: https://github.com/forcedotcom/cli/issues/1258

**Comment by shetzel** [comment]
@jclark-dot-org - I know this is a super old issue but we're trying to clean up these issues as best we can so apologies for not getting an update from us on this for so long.  I just tested this with the latest CLI and it's working correctly.  I installed a package with a custom metadata type, then created a new record of that type, ran `sf project retrieve preview` and it listed the new CustomMetadata.  I also ran `sf project retrieve start` and it retrieved it.
