### ISSUE TITLE
sfdx force:source:deploy failed trying to deploy a Flow with error message "Required field is missing: name" 

### ISSUE THREAD

**Issue by wajdifejjari** [forcedotcom/cli#1315]
### Summary
I'm trying to deploy a Flow to a Sandbox using  "sfdx force:source:deploy" but I'm getting this error message saying that there is a missing field within the flow metadata XML 
Here is a screenshot of the error 
![Screenshot 2021-12-08 at 12 06 26](https://user-images.githubusercontent.com/91482863/145205867-b6be1948-cfc5-4e4a-baef-5f2260720fca.png)

This Is a snapshot from the Flow Metadata XML file: I highlighted Line 168 which caused the issue 

![Screenshot 2021-12-08 at 12 12 24](https://user-images.githubusercontent.com/91482863/145206653-9e483d85-0d3d-4894-bcbf-69a2b9e88017.png)

### Steps To Reproduce:
The flow that is causing the issue is a record triggered flow and I'm using the Auto Layout.
I used the Include a Run Asynchronously feature which create a new Asynchronous path  that caused the error displayed in the previous screenshot 
Here are some screenshots of the flow : 
 

![Screenshot 2021-12-08 at 12 24 17](https://user-images.githubusercontent.com/91482863/145208134-1c735a45-cd6f-4241-9297-81142b855e2e.png)

![Screenshot 2021-12-08 at 12 26 44](https://user-images.githubusercontent.com/91482863/145208372-1a5bc1ad-6c41-478f-af90-3f68edcd7add.png)

![Screenshot 2021-12-08 at 12 28 21](https://user-images.githubusercontent.com/91482863/145208594-da65f84b-66d2-4e42-b32b-53ec8be2bddb.png)

### Expected result
The only workaround that worked for me is to delete the Run Asynchronously path and deploy then put it back after deployment but that's not very helpful if as I have more flows of the same type to deploy.
This looks like a DX bug to me, please help

**Comment by mshanemc** [comment]
The issue template asks some important questions about your version/plugins (that you run `sfdx version --verbose`).  Please do that so we can see what version of the CLI and plugin-source you're on.

Can you also provide your `sfdx-project.json`'s `sourceApiVersion` ?  This could be a metadata API error, but it could be a mismatch between different API versions of your Flow.

**Comment by wajdifejjari** [comment]
Thank you @mshanemc here are the details you requested :
sfdx version --verbose ==> 
CLI Version : 
        sfdx-cli/7.119.2
 Architecture: 
        darwin-x64
 Node Version : 
        node-v14.17.6
 Plugin Version: 
        @oclif/plugin-autocomplete 0.3.0 (core)
        @oclif/plugin-commands 1.3.0 (core)
        @oclif/plugin-help 3.2.3 (core)
        @oclif/plugin-not-found 1.2.4 (core)
        @oclif/plugin-plugins 1.10.1 (core)
        @oclif/plugin-update 1.5.0 (core)
        @oclif/plugin-warn-if-update-available 1.7.0 (core)
        @oclif/plugin-which 1.0.3 (core)
        @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
        alias 1.1.10 (core)
        apex 0.2.8 (core)
        auth 1.7.1 (core)
        config 1.2.35 (core)
        custom-metadata 1.0.12 (core)
        data 0.6.1 (core)
        generator 1.2.0 (core)
        limits 1.2.1 (core)
        org 1.7.0 (core)
        salesforce-alm 52.3.5 (core)
        schema 1.0.8 (core)
        sfdx-cli 7.119.2 (core)
        source 1.1.0 (core)
        telemetry 1.2.4 (core)
        templates 52.1.0 (core)
        trust 1.0.8 (core)
        user 1.4.0 (core)
 OS and Version: 
        Darwin 20.6.0
-------------------------------
**"sourceApiVersion": "53.0",**

**Comment by mshanemc** [comment]
Interesting.  Looking at the Flow mdapi docs https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_visual_workflow.htm#FlowStart
I don't see your scheduledPaths at all on any apiVersion (it's likely the docs have't been updated).

I'd suggest changing the sourceApiVersion to `53`.  If you still have an org where this flow exists, try retrieving (so that it's v53) just in case the metadata API had a bug in v52.  If not, it'd be worth creating one and doing a retrieve of this flow.  

There's a related question here from StackExchange with a comment about possibly needing `pathType` tag, too.
https://salesforce.stackexchange.com/questions/361345/how-to-resolve-required-field-is-missing-name-when-deploying-flow

**Comment by wajdifejjari** [comment]
Thank you very much, @mshanemc. I tried redeploying with the sourceApiVersion V53, but the same error occurred.
Note : When using **sfdx force:mdapi:deploy**, the flow is correctly deployed.

**Comment by mshanemc** [comment]
More recent versions of plugin-source will output, during the deploy, what version of the mdapi they're using.  Example:
`*** Deploying v52.0 metadata with SOAP API v53.0 connection ***`

We added that for scenarios like this where you may have a settings somewhere that's causing it to not use the version you'd expect it to.

Your CLI is a few months old so you might have better luck with a new one.  Also run your `deploy` command with `--dev-debug` appended to the end--that'll give a LOT more detail about what version it's using.

> Note : When using sfdx force:mdapi:deploy, the flow is correctly deployed.
That sentence makes me 99% sure this is a metadata API version problem, but I'm not sure why it's not using the correct one.

You can also use the same --dev-debug on the `mdapi:deploy` command to see what version that's using, in case (for whatever reason) it only succeeds on certain API versions.

**Comment by SuperBardziej** [comment]
There is some problem with cli deploy/retrieve when we indicate concrete --apiversion from command line.
Details are described here: [How to resolve "Required field is missing: name" when deploying Flow?](https://salesforce.stackexchange.com/a/367854/110315)

@mshanemc below you can find the crucial part of debug logs you asked for.
It's the same for both use cases:
1. "Required field is missing: name" - when pathType is missing in Flow metadata in <scheduledPaths> tag.
2. "Property 'pathType' not valid in version 51.0" -  when pathType has been added properly.

configuration:
`sfdx-project.json` file with `"sourceApiVersion": "51.0"`
command:
`sfdx force:source:deploy -p force-app\flows\ --apiversion 53.0`

--dev-debug results:
```
ERROR running force:source:deploy:  Deploy failed.
*** Internal Diagnostic ***

DeployFailed: Deploy failed.
    at DeployResultFormatter.display (\npm\node_modules\sfdx-cli\node_modules\@salesforce\plugin-source\src\formatters\deployResultFormatter.ts:81:13)
    at Deploy.formatResult (\npm\node_modules\sfdx-cli\node_modules\@salesforce\plugin-source\src\commands\force\source\deploy.ts:212:17)       
    at Deploy.run (\npm\node_modules\sfdx-cli\node_modules\@salesforce\plugin-source\src\commands\force\source\deploy.ts:117:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Deploy._run (\npm\node_modules\sfdx-cli\node_modules\@salesforce\plugin-source\node_modules\@salesforce\command\lib\sfdxCommand.js:81:40)
    at async Config.runCommand (\npm\node_modules\sfdx-cli\node_modules\@oclif\config\lib\config.js:173:24)
    at async SfdxMain.run (\npm\node_modules\sfdx-cli\node_modules\@oclif\command\lib\main.js:27:9)
    at async SfdxMain._run (\npm\node_modules\sfdx-cli\node_modules\@oclif\command\lib\command.js:43:20)
    at async Object.run (\npm\node_modules\sfdx-cli\dist\cli.js:162:47)
******
```

**Comment by shetzel** [comment]
apiversion vs. sourceapiversion:
setting `sourceApiVersion: 51.0`  tells the org that the source is in a format that matches API version 51.0.  The CLI generates a package.xml with a version field value of 51.0.  Setting `--apiversion=53.0` tells the CLI to communicate with the org using API version 53.0 SOAP/REST.  The org uses the version from the manifest (sourceapiversion) over the apiversion set on the command.  This is as designed from the beginning of SFDX.

**Comment by lakhanmeghani** [comment]
When I tried from Branch to Prod deployment, I got the same error but when I tried to deploy from Preprod to prod, it worked 
Not sure but something wrong with DX

**Comment by kmojczi** [comment]
@shetzel --apiversion=53.0 from the command overrides sourceApiVersion: 51.0 from the sfdx-project.json. You said opposite

**Comment by shetzel** [comment]
@kmojczi - it shouldn't.  See https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_apiversion.htm

If `sourceApiVersion` is set in the project file it will use that over an `apiversion` set by the command when talking about the `version` field used in the package.xml.
