### ISSUE TITLE
force:source:pull fails because of custom labels

### ISSUE THREAD

**Issue by fenixjke** [forcedotcom/cli#1317]
### Summary

sfdx force:source:pull works incorrectly because of custom labels, fullName of whose can be treated as booleans

### Prerequisites

1. Dev Hub created
1. Standard sfdx project created without metadata
1. Scratch org created

### Steps To Reproduce

1. Open scratch org
1. Create custom label and populate "true" value in the required fields
1. Create custom label and populate "false" value in the required fields
1. Perform sfdx force:source:pull in sfdx project
1. Validate the custom labels are retrieved
1. Open scratch org
1. Create custom label and populate "another" value in the required fields
1. Perform sfdx force:source:pull in sfdx project

### Expected result

Pull should retrieve metadata

### Actual result

Exception occurs "ERROR running force:source:pull:  fullName.trim is not a function"

### System Information

CLI Version : 
        sfdx-cli/7.129.0

 Architecture: 
        darwin-x64

 Node Version : 
        node-v16.13.0

 Plugin Version: 
        @oclif/plugin-autocomplete 0.3.0 (core)
        @oclif/plugin-commands 1.3.0 (core)
        @oclif/plugin-help 3.2.3 (core)
        @oclif/plugin-not-found 1.2.4 (core)
        @oclif/plugin-plugins 1.10.1 (core)
        @oclif/plugin-update 1.5.0 (core)
        @oclif/plugin-warn-if-update-available 1.7.0 (core)
        @oclif/plugin-which 1.0.3 (core)
        @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
        @salesforce/sfdx-scanner 2.12.0
        alias 1.1.22 (core)
        apex 0.3.0 (core)
        auth 1.7.6 (core)
        config 1.2.48 (core)
        custom-metadata 1.0.12 (core)
        data 0.6.5 (core)
        generator 1.2.1 (core)
        limits 1.2.3 (core)
        org 1.9.2 (core)
        salesforce-alm 53.4.5 (core)
        schema 1.0.10 (core)
        sfdx-cli 7.129.0 (core)
        source 1.5.3 (core)
        telemetry 1.3.0 (core)
        templates 52.6.0 (core)
        trust 1.0.10 (core)
        user 1.5.3 (core)

 OS and Version: 
        Darwin 20.6.0

### Additional information

Exception:
![image_1340291505](https://user-images.githubusercontent.com/20062691/145468017-f9017091-58c2-41e3-90b3-f1c2f6a9a916.jpeg)

It seems like the issue is in the nonDecomposedElementsIndex.json file
Other fullNames of custom labels has string type, but the custom label with fullName "true" becomes boolean in that file
The custom label with fullName equals to "false" isn't reflected in that file at all
![image_1340291506](https://user-images.githubusercontent.com/20062691/145468921-1f9df5d3-adbf-485c-aa79-3d50ce08e9bf.jpg)

**Comment by mshanemc** [comment]
We're replacing all of that code for pull with what's in the new [source:beta](https://github.com/forcedotcom/cli/issues/1258)

Can you try using that to see if the error is the same?

**Comment by fenixjke** [comment]
source:beta:pull retrieved such custom labels without errors. However it's not something which is ready to be used in production workflows, is it correct?

**Comment by fenixjke** [comment]
One observation. If I repeat source:beta:pull after it's already executed the result of the command execution still says the metadata is created. Using source:pull version it says that there is nothing to retrieve. Is this behavior expected? 
![n](https://user-images.githubusercontent.com/20062691/146045642-1e557e61-6452-4ec5-a3c2-58d35bdec56f.jpg)

**Comment by mshanemc** [comment]
Oh, nice catch on `source:beta`.

Did you change the label on the server in between, then pull again, and you're saying it should say `Updated`?  OR did it pull the change the first time, and then think the change needed to be pulled again.

**Comment by fenixjke** [comment]
In the previous example I executed the command sequentially, without making changes in the custom labels in my scratch
In this situation I expected that CustomLabels should be considered as unchanged and should be skipped in "pull" call

I made one more test when I changed custom labels between the source:pull executions and the information in the console for the second execution still says `Created` but I expected `Updated`.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10322335](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000YPAdRYAX/view)
