### ISSUE TITLE
Issues with installing sfdx-plugins - JavaScript heap out of memory

### ISSUE THREAD

**Issue by calvinle1** [forcedotcom/cli#1319]
# Resolved:

The oclif patch was tested and released.  You should be able to install plugins and update the CLI now.

## Response from the Salesforce CLI team:

Quick synopsis...this is bigger than `sfdx` because the error is happening in oclif.  The team is aware and working on a fix.

For sfdx plugins, the best current workaround is to use our installer-based (not npm) install method on `7.130.1` (currently tagged as `stable` channel)

From that, you can successfully install CLI plugins.

The release candidate (7.131.0) picked up the broken oclif version yesterday and suffers from the same problem.

You may have problems running `sfdx update` due to the issue.

### Details

oclif uses yarn for installing plugins.  Yarn has an open bug that's the root cause of this: https://github.com/yarnpkg/yarn/issues/8734

original issue below the line

---

### Summary

There is currently an issue with installing sfdx-plugins. It appears to be apparent across all sfdx-plugins

### Steps To Reproduce:

**$ sfdx plugins:install json-bourne-sfdx
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
warning "sfpowerkit > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".**

<--- Last few GCs --->

[5088:000001B1C427ACA0]   204262 ms: Mark-sweep 8058.1 (8233.9) -> 8049.3 (8231.9) MB, 1060.7 / 0.0 ms  (average mu = 0.110, current mu = 0.039) allocation failure scavenge might not succeed
[5088:000001B1C427ACA0]   204815 ms: Mark-sweep 8065.1 (8231.9) -> 8049.1 (8232.4) MB, 518.4 / 0.0 ms  (average mu = 0.093, current mu = 0.063) allocation failure scavenge might not succeed

<--- JS stacktrace --->

**FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory**
 1: 00007FF6355030AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511
 2: 00007FF635492216 DSA_meth_get_flags+65542
 3: 00007FF6354930CD node::OnFatalError+301
 4: 00007FF635DC4B6E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF635DAF09D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF635C5268C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF635C5F339 v8::internal::Heap::PublishPendingAllocations+1129
 8: 00007FF635C5C30A v8::internal::Heap::PageFlagsAreConsistent+2842
 9: 00007FF635C4EF89 v8::internal::Heap::CollectGarbage+2137
10: 00007FF635C4D140 v8::internal::Heap::AllocateExternalBackingStore+2000
11: 00007FF635C71A76 v8::internal::Factory::NewFillerObject+214
12: 00007FF6359A4CB5 v8::internal::DateCache::Weekday+1797
13: 00007FF635E52541 v8::internal::SetupIsolateDelegate::SetupHeap+494417
14: 00007FF635E0F220 v8::internal::SetupIsolateDelegate::SetupHeap+219184
15: 00007FF635E74B3A v8::internal::SetupIsolateDelegate::SetupHeap+635210
16: 000001B1C6174E46
Installing plugin json-bourne-sfdx... failed

### Expected result

Plugins can be installed

### Actual result

Error is thrown:

**FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6355030AF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112511**

### System Information

$ sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.130.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.13.1",
        "pluginVersions": [
                "@dxatscale/sfpowerscripts 8.5.3",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.10 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.6 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.4.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.0 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.6 (core)",
                "generator 1.2.1 (core)",
                "info 1.1.2 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.6.0 (core)",
                "schema 1.1.0 (core)",
                "sfdmu 4.5.10",
                "sfdx-cli 7.130.1 (core)",
                "sfpowerkit 3.3.2",
                "source 1.6.2 (core)",
                "telemetry 1.4.0 (core)",
                "templates 52.6.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19043"
}

### Additional information

_Feel free to attach a screenshot_.

**Comment by calvinle1** [comment]
This currently impacts our CI/CD pipelines given we have sfdx-plugins through out them.

**Comment by dcstuff** [comment]
+1 to this issue, for any and all plugins. I discovered this after I noticed that **_all of my plugins have seemingly been uninstalled._** I can't say with any certainty when that happened, except that over time, I had installed a slew of plugins: isvte; sfdx-scanner; Shane's **great** plugin; etc... and at some point in the recent past, it appears they've all been removed! `no plugins installed` Womp-womp.

**Comment by ttomaszewski** [comment]
+1 This also impacts our CI/CD pipeline. 

Error occurs not only when installing plugins but sfdx-cli via yarn: `yarn add sfdx-cli --dev`

**Comment by fyang-nextdc** [comment]
+1 We have been running version 7.69.0 to install JSON Bourne with no errors up until yesterday. 

Then, we have checked the IDE which is running on 7.126.0 version but the issue is still occurring. 

Then we updated sfdx version to 7.130.0 still the same issue. 

This is not only failing for json bourne installation, dxb installation also failed for similar reason between [3/4] Linking dependencies...Installing plugin json-bourne-sfdx... and [4/4] Building fresh packages...Installing plugin json-bourne-sfdx...

**Comment by calvinle1** [comment]
Yep, the issue is apparently across all sfdx-plugins.

**Comment by stoevie** [comment]
Hello, we have the same problem in combination with sfpowerkit plug-in. It has maybe a relation with this bug: https://github.com/oclif/command/issues/299
Kr,
Gert

**Comment by patrykacc** [comment]
Same issue happens for me when running `sfdx plugins:install auth@latest`

**Comment by sfrycertinia** [comment]
This is a massive issue for us. All our CI pipelines are now broken. Please treat this as a priority.

If it helps we are using a private npm registry (Artifactory).

**Comment by patrykacc** [comment]
Stack trace:

sfdx plugins:install auth@latest 
Polling for new version(s) to become available on npm
attempt: 1 of 300
done
Successfully validated digital signature for @salesforce/plugin-auth.
Finished digital signature check.
Installing plugin auth... yarn add v1.22.17
Installing plugin auth... info No lockfile found.Installing plugin auth... [1/4] Resolving packages...Installing plugin auth... [2/4] Fetching packages...Installing plugin auth... [3/4] Linking dependencies...Installing plugin auth... failed
warning @salesforce/plugin-auth > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @salesforce/plugin-auth > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
warning @salesforce/plugin-auth > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
<--- Last few GCs --->
[654:0x5369f00]    56996 ms: Scavenge 2025.8 (2075.1) -> 2022.5 (2076.3) MB, 5.3 / 0.0 ms  (average mu = 0.366, current mu = 0.365) allocation failure 
[654:0x5369f00]    57019 ms: Scavenge 2027.0 (2076.3) -> 2024.3 (2079.1) MB, 4.5 / 0.0 ms  (average mu = 0.366, current mu = 0.365) allocation failure 
[654:0x5369f00]    57042 ms: Scavenge 2029.8 (2079.1) -> 2026.7 (2097.1) MB, 6.7 / 0.0 ms  (average mu = 0.366, current mu = 0.365) allocation failure 
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb00d90 node::Abort() [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
 2: 0xa1823b node::FatalError(char const*, char const*) [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
 3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
 4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
 5: 0xea6105  [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
 6: 0xeb57dd v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
 7: 0xeb84de v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
 8: 0xe7990a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
 9: 0x11f2f06 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
10: 0x15e7819  [/root/.local/share/sfdx/client/7.130.1-fe4ce6c/bin/node]
    Error: yarn add @salesforce/plugin-auth@latest --non-interactive 
    --mutex=file:/root/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/root/.cache/sfdx/yarn --check-files exited with 
    code null
 Error when executing command: sfdx plugins:install auth@latest

**Comment by akdasari** [comment]
This also  imacting our ci/cd pipelines as we have regular deployments.
A Quick workaround or fix would be appreciated.
we are using 
`sfdx plugins:install sfdx-git-delta`

and the error in pipeline is 
`+ sfdx --version
sfdx-cli/7.130.1 linux-x64 node-v14.17.1
[Pipeline] sh
+ echo y
+ sfdx plugins:install sfdx-git-delta
You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements.

This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: Finished digital signature check.
Installing plugin sfdx-git-delta... yarn add v1.22.17
Installing plugin sfdx-git-delta... info No lockfile found.Installing plugin sfdx-git-delta... [1/4] Resolving packages...Installing plugin sfdx-git-delta... [2/4] Fetching packages...Installing plugin sfdx-git-delta... [3/4] Linking dependencies...Installing plugin sfdx-git-delta... failed
warning sfdx-git-delta > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sfdx-git-delta > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
warning sfdx-git-delta > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

<--- Last few GCs --->

[126:0x5a00c50]   140181 ms: Scavenge 4066.5 (4096.3) -> 4062.9 (4096.3) MB, 15.8 / 0.0 ms  (average mu = 0.336, current mu = 0.332) allocation failure 
[126:0x5a00c50]   140224 ms: Scavenge 4067.7 (4096.3) -> 4065.2 (4096.3) MB, 19.2 / 0.0 ms  (average mu = 0.336, current mu = 0.332) allocation failure 
[126:0x5a00c50]   140269 ms: Scavenge 4070.6 (4112.3) -> 4067.4 (4113.1) MB, 17.2 / 0.0 ms  (average mu = 0.336, current mu = 0.332) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa24ed0 node::Abort() [/usr/local/lib/nodejs/bin/node]
 2: 0x966115 node::FatalError(char const*, char const*) [/usr/local/lib/nodejs/bin/node]
 3: 0xb9acde v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/lib/nodejs/bin/node]
 4: 0xb9b057 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/lib/nodejs/bin/node]
 5: 0xd56ea5  [/usr/local/lib/nodejs/bin/node]
 6: 0xd57a2f  [/usr/local/lib/nodejs/bin/node]
 7: 0xd65abb v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/lib/nodejs/bin/node]
 8: 0xd68175 v8::internal::Heap::HandleGCRequest() [/usr/local/lib/nodejs/bin/node]
 9: 0xd0e657 v8::internal::StackGuard::HandleInterrupts() [/usr/local/lib/nodejs/bin/node]
10: 0x107fdb3 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/usr/local/lib/nodejs/bin/node]
11: 0x1427099  [/usr/local/lib/nodejs/bin/node]
    Error: yarn add sfdx-git-delta@latest --non-interactive 
    --mutex=file:/root/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/root/.cache/sfdx/yarn --check-files exited with 
    code null
[Pipeline] echo
Exception occurred: hudson.AbortException: script returned exit code 1`

**Comment by monsterboom** [comment]
the same problem... When to fix it

**Comment by dhbahr** [comment]
Another one bites the dust, we have pipelines failing for a few running projects due to this issue.

**Comment by azlam-abdulsalam** [comment]
One temporary solution is checkout the source of the plugin repository, and do a npm i  or yarn (depending on what the plugin uses) and do a sfdx plugins:link. This is probably due to the recent update

https://github.com/oclif/command/issues/299

https://github.com/Accenture/sfpowerkit/issues/603

**Comment by patrykacc** [comment]
> One temporary solution is checkout the source of the plugin repository, and do a npm i or yarn (depending on what the plugin uses) and do a sfdx plugins:link. This is probably due to the recent update
> 
> [oclif/command#299](https://github.com/oclif/command/issues/299)
> 
> [Accenture/sfpowerkit#603](https://github.com/Accenture/sfpowerkit/issues/603)

Did it work for you? Which version if so

**Comment by yippie** [comment]
Happening to all of our CI on my company across all projects.

We version pin node version, sfdx CircleCI orb, sfdx cli version, and plugin versions to exact versions.

And it is still happening to us.

How did you manage to fatally break previous versions of the CLI? This needs to be fixed ASAP and changes put in place so new releases don't break previous versions

**Comment by ibabiankou** [comment]
Having the same memory issue in our CI.
CLI and plugin versions on the failing builds:
```
sfdx-cli/7.127.0 linux-x64 node-v16.13.0
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.9 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.4 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 1.1.22 (core)
apex 0.3.0 (core)
auth 1.7.5 (core)
config 1.2.47 (core)
custom-metadata 1.0.12 (core)
data 0.6.4 (core)
generator 1.2.1 (core)
limits 1.2.3 (core)
org 1.9.0 (core)
salesforce-alm 53.4.2 (core)
schema 1.0.10 (core)
sfdx-cli 7.127.0 (core)
source 1.4.0 (core)
telemetry 1.2.8 (core)
templates 52.6.0 (core)
trust 1.1.0 (core)
user 1.5.2 (core)
```
Last green build has the only difference: trust plugin has version 1.0.11
However nothing stands out in [the changes](https://github.com/salesforcecli/plugin-trust/compare/v1.0.11...v1.1.0)

**Comment by sfrycertinia** [comment]
This is a recurring problem caused by not using shrink-wrapping of an end user cli tool.

https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json

Please introduce immutable npm releases.

We are reengineering our build agents to use Docker images that now give us this immutability, but this is not yet complete so this kind of issue is still impacting us.

**Comment by sagarhinsu** [comment]
This seems the workaround. 
https://github.com/oclif/command/issues/299#issuecomment-990866422
I am gonna try this and let you know if it works

**Comment by ImJohnMDaniel** [comment]
+1 on this issue.  All of our CI jobs are failing at the moment

**Comment by RodEsp** [comment]
Hi everyone, please see https://github.com/oclif/oclif/issues/757#issuecomment-991030813 for a workaround. We are currently working on fixing the issue.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10293564](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000Wt6FNYAZ/view)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10293566](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000WtEfpYAF/view)

**Comment by mshanemc** [comment]
I'm re-opening this to keep it visible in case y'all are checking your CI logs this morning and seeing what happened.

**Comment by sfrycertinia** [comment]
Doesn't appear to be fixed for me.

**Comment by mshanemc** [comment]
@sfryffdc what are you not able to do?  Can you share your setup (os, how you installed, what versions you're on, etc) so we can figure out what's not working?

**Comment by sfrycertinia** [comment]
@mshanemc Hi! I am just installing sfdx-cli@latest globally with a blank global node modules, then trying to install our in house sfdx plugin.

I just get a JavaScript heap out of memory error.

I get the same error with.

```bash
sfdx plugins:install @salesforce/sfdx-plugin-lwc-test
```

Debian/buster 
Node  v14.15.4

**Comment by sfryffdc** [comment]
Same error trying 

```bash
sfdx plugins:install @salesforce/sfdx-plugin-lwc-test
```

**Comment by mshanemc** [comment]
@sfryffdc  I built a fresh npm install and installed that and several other plugins successfully.  Is it possible that you're using an npm proxy or have some sort of cache between you and the public npm registry?

**Comment by sfrycertinia** [comment]
@mshanemc we are using our own Artifactory as our registry with npmjs as a remote.

**Comment by mshanemc** [comment]
`npm view @oclif/command` should say latest is 1.8.13

**Comment by ldeveber** [comment]
Can confirm a fresh build is succeeding for us now, thanks so much!

**Comment by ImJohnMDaniel** [comment]
@mshanemc, things are working again.  Thanks for the team's quick help on this.

**Comment by akdasari** [comment]
Looks like things are working now.

**Comment by sfrycertinia** [comment]
@mshanemc apologies, I was too impatient. Must have been a caching issue in our Artifactory. Looks good now. Thanks!

**Comment by calvinle1** [comment]
Things are good now. Thanks!

**Comment by CostaRonaro** [comment]
Hi 
I fix this bug doing a downgrade sfdx cli from` sfdx-cli/7.172.0` to `sfdx-cli/7.142.1`
