### ISSUE TITLE
count() fails with no field argument given (e.g. count(Id))

### ISSUE THREAD

**Issue by jungar** [forcedotcom/cli#1320]
### Summary

When using the builtin count() function in a SOQL query via sfdx, an error message similar to the below will be thrown unless a specific field is used as an argument to the function, e.g. count(Id) (see Steps To Reproduce for a complete, specific example)

```
(node:33946) Warning: The query result is missing 25300 records due to a 999999 record limit. Increase the number of records returned by setting the config value "maxQueryLimit" or the environment variable "SFDX_MAX_QUERY_LIMIT" to 25300 or greater than 999999.
(Use `node --trace-warnings ...` to show where the warning was created)
```

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Log in to any SFDC Org from sfdx:  ` sfdx force:auth:web:login`
2.   `sfdx force:config:set defaultusername` (if necessary)
3. Run a SOQL query on any object and use the count() function with no field argument, e.g.:  ` sfdx force:data:soql:query -q "SELECT count() FROM PermissionSetAssignment WHERE PermissionSetId='0PS6T0000024uYe'"`

### Expected result

A count of all records should be returned, as per other tools which make similar SOQL API calls, and not an error.

Additonally, the error messaging "The query result is missing **_n_** records due to a **_y_** record limit" and "... **_n_**  or greater than **_y_**" is pretty silly for values of  y>=n ...

### Actual result

Error message(s). See Summary, above.

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
	
	
	`jungar@jungar-ltm1 aloha_sfdx % sfdx version --verbose --json | jq
{
  "cliVersion": "sfdx-cli/7.130.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.13.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 0.3.0 (core)",
    "@oclif/plugin-commands 1.3.0 (core)",
    "@oclif/plugin-help 3.2.10 (core)",
    "@oclif/plugin-not-found 1.2.4 (core)",
    "@oclif/plugin-plugins 1.10.6 (core)",
    "@oclif/plugin-update 1.5.0 (core)",
    "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
    "@oclif/plugin-which 1.0.3 (core)",
    "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
    "alias 1.2.0 (core)",
    "apex 0.4.0 (core)",
    "auth 1.8.0 (core)",
    "config 1.3.0 (core)",
    "custom-metadata 1.0.12 (core)",
    "data 0.6.6 (core)",
    "generator 1.2.1 (core)",
    "info 1.1.2 (core)",
    "limits 1.3.0 (core)",
    "org 1.11.0 (core)",
    "salesforce-alm 53.6.0 (core)",
    "schema 1.1.0 (core)",
    "sfdx-cli 7.130.1 (core)",
    "source 1.6.2 (core)",
    "telemetry 1.4.0 (core)",
    "templates 52.6.0 (core)",
    "trust 1.1.0 (core)",
    "user 1.7.0 (core)"
  ],
  "osVersion": "Darwin 19.6.0"
}`

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10294697](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000Ww6IkYAJ/view)
