### ISSUE TITLE
Org Create fails with Unrecognized option: cookiesAllowAllPaths

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#1323]
### Summary
As of 30 min ago, all attempts at org creation are failing with the error `ERROR running force:org:create: Unrecognized option: cookiesAllowAllPaths` in CI

### Steps To Reproduce:

1.  Do a fresh install of SFDX
1.  Create a scratch org using the Org:create command

### Expected result

Org created successfully

### Actual result

Creation fails with the error `ERROR running force:org:create: Unrecognized option: cookiesAllowAllPaths`

### System Information

sfdx-cli/7.108.0 linux-x64 node-v14.16.1

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.17 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.10 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.10 (core)
apex 0.2.2 (core)
auth 1.7.0 (core)
config 1.2.9 (core)
custom-metadata 1.0.12 (core)
data 0.4.12 (core)
generator 1.2.1 (core)
limits 1.2.1 (core)
org 1.6.7 (core)
salesforce-alm 52.0.2 (core)
schema 1.0.7 (core)
sfdx-cli 7.108.0 (core)
telemetry 1.2.2 (core)
templates 52.0.0 (core)
user 1.3.0 (core)

**Comment by mshanemc** [comment]
7.108.0 is *definitely* not a "fresh install" of the CLI.  That's from about 5 months ago.

Does it happen on a recent CLI (I'm guessing not since we removed all that awful streamingClient stuff https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71200-sept-30-2021)

**Comment by yippie** [comment]
@mshanemc It is a fresh install in that we are installing it from nothing. It is a CI environment which means it is built and installed on demand.

I am trying to use newer versions but hitting other errors. We are using the sfdx orb for CircleCI (circleci/salesforce-sfdx@2.1.1) and specifying our cli version of 7.108.0. If I try a newer version, then the SFDX CLI itself fails to install with the error:

`npm ERR! syscall mkdir
npm ERR! path /root/.npm/_cacache/tmp
npm ERR! errno EACCES
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.`

**Comment by mshanemc** [comment]
yeah, we've seen CI systems where the way we bundled `sf` doesn't allow install via npm.  And since you're using that orb (not from us) there's not an easy way to make it not-an-npm-install.

Can you try version `7.131.0` where we've removed `sf` from npm based installs?

**Comment by yippie** [comment]
with 7.131.0 the CLI appears to install but SFDMU plugin install fails with `TypeError: HelpClass is not a constructor`

**Comment by yippie** [comment]
So it appears that the sfdmu plugin is installing just fine. But any calls to --help (or we were doing `sfdx` just to verify our install) breaks with the typeerror.

That type error is happening even on 7.130.1 and means we cannot use --help for any command anymore.

**Comment by mshanemc** [comment]
yep, thanks for opening a separate issue--looks like that broke in the last couple hours.

**Comment by MRASoft** [comment]
FYI, this is happening when we tried to do a build through Jenkins calling the SF DX org create. This did not happen two days ago with the same versions. Here are more details.

Create scratch org events
[Pipeline] echo
Script sfdx force:org:create --definitionfile config/project-scratch-def.events.json --json --setdefaultusername --durationdays 1 --setalias "master/crm-events/PR-12" --wait 10
[Pipeline] sh
+ sfdx force:org:create --definitionfile config/project-scratch-def.events.json --json --setdefaultusername --durationdays 1 --setalias master/crm-events/PR-12 --wait 10
 ›   Warning: sfdx-cli update available from 7.110.0 to 7.123.1.
{
  "status": 1,
  "name": "Error",
  "message": "Unrecognized option: cookiesAllowAllPaths",
  "exitCode": 1,
  "commandName": "OrgCreateCommand",
  "stack": "Error: Unrecognized option: cookiesAllowAllPaths\n    at module.exports (/usr/local/lib/node_modules/sfdx-cli/node_modules/faye/src/util/validate_options.js:8:13)\n    at klass.initialize (/usr/local/lib/node_modules/sfdx-cli/node_modules/faye/src/protocol/client.js:40:5)\n    at new klass (/usr/local/lib/node_modules/sfdx-cli/node_modules/faye/src/util/class.js:13:28)\n    at Object.getCometClient (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/status/streamingClient.js:363:28)\n    at new StreamingClient (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/status/streamingClient.js:127:55)\n    at Function.create (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/creatable.js:56:26)\n    at OrgCreateCommand.signupOrgWithStreaming (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/org/scratchOrgCreateCommand.js:208:68)\n    at async OrgCreateCommand.execute (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/org/scratchOrgCreateCommand.js:315:32)\n    at async OrgCreateCommand.execLegacyCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/ToolbeltCommand.js:149:29)\n    at async OrgCreateCommand._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/node_modules/sfdx-cli/dist/cli.js:162:47)\nOuter stack:\n    at Function.wrap (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at OrgCreateCommand.catch (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/ToolbeltCommand.js:253:46)\n    at async OrgCreateCommand._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/node_modules/sfdx-cli/dist/cli.js:162:47)",
  "warnings": []
}

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10315739](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000Y85BxYAJ/view)
