### ISSUE TITLE
sfdx force:source:deploy --apiversion 53.0 doesn't override sfdx-project.json 51.0 API version

### ISSUE THREAD

**Issue by olektymchenko** [forcedotcom/cli#1324]
### Summary

Hello, during the pipeline configuration's I was asked to dynamically override API version during the deployment, but unfortunately command 
**sfdx force:source:deploy -x package/package.xml  --targetusername aaaa@aaaa.com -g --apiversion 53.0** 
Doesn't override sfdx-project.json API version.
 So I have an information in console that API version was overridden, but in real, deploy is proceed with old API version.
![image](https://user-images.githubusercontent.com/58951697/146054537-aee2a1d8-a600-4ba8-ba99-d033a9442bbd.png)

### Steps To Reproduce:

1.  Retrieve Experience Bundle with sfdx-project.json API version 53.0;
2.  Change sfdx-project.json API version  to 51.0;
3. Execute deploy command with overriding API number, for example
sfdx force:source:deploy -x package/package.xml  -g --apiversion 53.0

### Expected result

Experience bundle is successfully deployed.

### Actual result

Error  [ExperienceBundleName]  An unexpected error occurred. Please include this ErrorId if you contact support: 2019876028-152733 (-73208994)
### System Information

"cliVersion": "sfdx-cli/7.130.1",
	"architecture": "linux-x64",
	"nodeVersion": "node-v14.17.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.14 (core)",
		"@oclif/plugin-not-found 1.2.5 (core)",
		"@oclif/plugin-plugins 1.10.10 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.2.0 (core)",
		"apex 0.4.0 (core)",
		"auth 1.8.0 (core)",
		"config 1.3.0 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.6 (core)",
		"generator 1.2.1 (core)",
		"info 1.1.2 (core)",
		"limits 1.3.0 (core)",
		"org 1.11.0 (core)",
		"salesforce-alm 53.6.0 (core)",
		"schema 1.1.0 (core)",
		"sfdx-cli 7.130.1 (core)",
		"sfdx-git-delta 4.11.0",
		"source 1.6.2 (core)",
		"telemetry 1.4.0 (core)",
		"templates 52.6.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.0 (core)"
	],
	"osVersion": "Linux 5.4.92-flatcar"

**Comment by mshanemc** [comment]
the only way to change the source api version (the version of the metadata API that's used) is by changing it in `sfdx-project.json`.

It'll still deploy on a v53 connection, but that doesn't do what you're thinking it should.
