### ISSUE TITLE
SFDX --help broken

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#1325]
### Summary

as of 7.130.1 i can no longer use any --help commands. They fail with `TypeError: HelpClass is not a constructor`

### Steps To Reproduce:

1.  install sfdx via `npm install sfdx-cli --global`
1.  run `sfdx --version` appears to work
2. run `sfdx` or `sfdx force --help`

### Expected result

Help documentation should be displayed

### Actual result

`TypeError: HelpClass is not a constructor`

### System Information

 sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.130.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.18 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.10 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.4.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.0 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.6 (core)",
                "generator 1.2.1 (core)",
                "info 1.1.2 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.6.0 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.130.1 (core)",
                "source 1.6.2 (core)",
                "telemetry 1.4.0 (core)",
                "templates 52.6.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Darwin 21.1.0"
}

**Comment by mshanemc** [comment]
we're on it.  It's likely from https://github.com/oclif/plugin-help/pull/350

**Comment by mshanemc** [comment]
OK, that's fixed now.  You should be able to re-install and run `--help`

Seriously, you caught that one at the perfect time.  

Given this, and https://github.com/forcedotcom/cli/issues/1319 we're exploring ways to stabilize the version of the oclif dependencies in each release so these off-cycle changes from oclif don't break all of you using npm for the CLI.
