### ISSUE TITLE
force:source:pull does not pull scheduled path of a Record-Triggered Flow

### ISSUE THREAD

**Issue by dalden1981** [forcedotcom/cli#1326]
### Summary

I created a Record-Triggered flow in a scratch org.  It has both a "Run Immediately" path and a scheduled path.  When I run force:source:pull, the CLI pulls the flow.  The "Run Immediately" is pulled in its entirety, the scheduled path is missing, but the actions in that path are included in the .flow-meta.xml file.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)
1.  Create a Record-Triggered Flow
1.  Add a Scheduled Path 
1.  Add an action to the scheduled path
1.  Save/Save As
1.  sfdx force:source:pull

### Expected result

The metadata for the flow should pull with the scheduled path included.

### Actual result

The metadata for the flow pulls without the scheduled path.  The action from the scheduled path is included but is unattached.

### System Information

{
"cliVersion": "sfdx-cli/7.130.1",
"architecture": "win32-x64",
"nodeVersion": "node-v16.13.1",
"pluginVersions": [
"@oclif/plugin-autocomplete 0.3.0 (core)",
"@oclif/plugin-commands 1.3.0 (core)",
"@oclif/plugin-help 3.2.18 (core)",
"@oclif/plugin-not-found 1.2.6 (core)",
"@oclif/plugin-plugins 1.10.10 (core)",
"@oclif/plugin-update 1.5.0 (core)",
"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
"@oclif/plugin-which 1.0.4 (core)",
"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
"alias 1.2.0 (core)",
"apex 0.4.0 (core)",
"auth 1.8.0 (core)",
"config 1.3.0 (core)",
"custom-metadata 1.0.12 (core)",
"data 0.6.6 (core)",
"generator 1.2.1 (core)",
"info 1.1.2 (core)",
"limits 1.3.0 (core)",
"org 1.11.0 (core)",
"salesforce-alm 53.6.0 (core)",
"schema 1.1.0 (core)",
"sfdx-cli 7.130.1 (core)",
"source 1.6.2 (core)",
"telemetry 1.4.0 (core)",
"templates 52.6.0 (core)",
"trust 1.1.0 (core)",
"user 1.7.0 (core)"
],
"osVersion": "Windows_NT 10.0.19042"
}

**Comment by WillieRuemmele** [comment]
I would verify that your api versions are correct. There's been a few instances of this causing similar [issues](https://github.com/forcedotcom/cli/issues/1253)

**Comment by dalden1981** [comment]
That was it.  Thank you.
