### ISSUE TITLE
force:data:record:update returns generic error when validation rule fails

### ISSUE THREAD

**Issue by dalden1981** [forcedotcom/cli#1327]
### Summary

When using the force:data:record:update command, if the data violates a validation rule; the system returns Failed to update record with code FIELD_CUSTOM_VALIDATION_EXCEPTION. Fields: [] instead of the provided validation rule error message.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  sfdx:force:data:record:update 

### Expected result

When submitting invalid data, the resulting error message should contain the validation rule's error message.

### Actual result

Failed to update record with code FIELD_CUSTOM_VALIDATION_EXCEPTION. Fields: []

### System Information

- If you are using `sfdx`
{
        "cliVersion": "sfdx-cli/7.130.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.13.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.18 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.10 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.4.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.0 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.6 (core)",
                "generator 1.2.1 (core)",
                "info 1.1.2 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.6.0 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.130.1 (core)",
                "source 1.6.2 (core)",
                "telemetry 1.4.0 (core)",
                "templates 52.6.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19042"
}

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10322646](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000YPqspYAD/view)

**Comment by WillieRuemmele** [comment]
Hi @dalden1981 can you provide an example command used against the dreamhouse-lwc project that will return this error?

**Comment by dalden1981** [comment]
@WillieRuemmele ,
To recreate the issue in dreamhouse-lwc:
1. I added a validation rule. In my case I added "Name_Cannot_Start_with_X" on Account (formula `LEFT(Name, 1) = "X"`).
1. Then I added an account `sfdx force:data:record:create -s Account -v "Name=Test" -u dreamhouse`
1. I noticed that it only happens on update, so I ran `sfdx force:data:record:update -s Account -v "Name=Xavier" -u dreamhouse -i 001...`

Received error "_ERROR running force:data:record:update:  Failed to update record with code FIELD_CUSTOM_VALIDATION_EXCEPTION. Fields: []._"

FYI, when I ran `sfdx force:data:record:create -s Account -v "Name=Xavier" -u dreamhouse` I got the error "_ERROR running force:data:record:create:  Name cannot begin with X_"

**Comment by WillieRuemmele** [comment]
https://github.com/salesforcecli/plugin-data/pull/249

**Comment by mshanemc** [comment]
QA Notes: 
✅  tested with multiple validation rules (only the first one shows up).  
✅ fields is populated only when the error isn't top of page...otherwise it's an empty array `[]`

**Comment by maggiben** [comment]
Fixed in `sfdx-cli/7.133.0`
![image](https://user-images.githubusercontent.com/2845947/148611921-c339071f-dd97-4239-b0b4-2ae4429af95d.png)

**Comment by shetzel** [comment]
The fix is in the latest CLI release published today.  sfdx version 7.133.0
