### ISSUE TITLE
SFDX update is not removing old version

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/cli#1332]
### Summary

Old version of sfdx is not removed after update. I am always using ```sfdx update``` command.

### Steps To Reproduce:

1. Update sfdx with ```sfdx update```
2. check folder ```C:\Users\UserName\AppData\Local\sfdx\client``` if contains old versions

### Expected result

Old version is removed after a successful update.

### Actual result

Old versions are not removed and take disk space.

### System Information

Windows 10 21H2

### Additional information

![image](https://user-images.githubusercontent.com/5740564/146548327-fae5d8e3-3948-4e6e-94a6-a090ead63aa2.png)

**Comment by WillieRuemmele** [comment]
Hi @PawelWozniak This is actually working as designed. OCLIF has an `update --from-local`[option](https://github.com/oclif/plugin-update/blob/main/src/commands/update.ts#L17). After a certain amount of [time](https://github.com/oclif/plugin-update/blob/main/src/update.ts#L278), if that version hasn't been used, it will go back through and delete it. These old versions should be cleaned up automatically.
