### ISSUE TITLE
CLI will not update to 7.126.0 or higher but warns that an update is available

### ISSUE THREAD

**Issue by abakyr** [forcedotcom/cli#1333]
![update failed](https://user-images.githubusercontent.com/19559786/146593691-e28a6c73-aab8-4243-b4f3-9b0e4afdb371.jpg)

**Comment by WillieRuemmele** [comment]
Hi @abakyr we've seen this issue from time to time, and it seems that the easiest solution is just to uninstall and reinstall the latest version of the CLI. let me know how it goes

**Comment by abakyr** [comment]
Hi @WillieRuemmele thanks for your reply. I did as you suggested. I think we can close the case.
