### ISSUE TITLE
force:source:beta:push ignores metadata when .gitignore present

### ISSUE THREAD

**Issue by kjonescertinia** [forcedotcom/cli#1335]
### Summary

If there is a .gitignore file in a package directory, metadata that is ignored is not pushed. We use .gitignore files for generated metadata that should be pushed but not checked in to git.

### Steps To Reproduce:

See https://github.com/nawforce/sfdx-test/tree/main/nested-classes

### System Information

{
	"cliVersion": "sfdx-cli/7.131.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.6.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.2.0 (core)",
		"apex 0.5.0 (core)",
		"auth 1.8.0 (core)",
		"config 1.3.2 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.6 (core)",
		"generator 1.2.1 (core)",
		"info 1.1.4 (core)",
		"limits 1.3.0 (core)",
		"org 1.11.0 (core)",
		"salesforce-alm 53.6.0 (core)",
		"schema 1.1.0 (core)",
		"sfdx-cli 7.131.0 (core)",
		"sfpowerkit 3.3.3 (link) /Users/kevin/Projects/sfpowerkit",
		"source 1.6.2 (core)",
		"telemetry 1.4.0 (core)",
		"templates 52.6.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.0 (core)"
	],
	"osVersion": "Darwin 21.1.0"
}

**Comment by mshanemc** [comment]
For clarification, you have multiple `.gitignore` files not at the top-level, but (potentially) in any or each pkgDir?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10338491](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000ZIITrYAP/view)

**Comment by kjonescertinia** [comment]
Yep, the ones that caused trouble are inside the pkg dirs at arbitrary depths. Likely they could be lifted to outside to workaround but it's not ideal as some will be coming from other projects so would make it harder to modularise.

**Comment by nawforce** [comment]
@mshanemc sfdx-cli/7.133.0 has resolved this but I have hit a related. Sample is over at https://github.com/nawforce/sfdx-test/tree/main/nested-classes2. 

This differs from the original in the package directory is below the .gitignore. Problem is the same, beta:push ignores the class due to the .gitignore file.

**Comment by mshanemc** [comment]
ahh, we were trying to save some computation cycles but not looking for gitignore **outside** of pkgDir unless they were at the top-level.  

but yeah, we'll just crawl the whole project.

thanks for the excellent repros

**Comment by nawforce** [comment]
No problem, I should have spotted we had this type of use in the repo as well.
