### ISSUE TITLE
force:source:beta:push can deploy metadata from outside the package directories

### ISSUE THREAD

**Issue by nawforce** [forcedotcom/cli#1336]
### Summary

If you have a directory which has a name which starts with the same string as a package directory, e.g. 'force-app-extra' where 'force-app' is a package directory, then metadata will be deployed from it even though it is not a package directory in sfdx-project.json. 

### Steps To Reproduce:

See https://github.com/nawforce/sfdx-test/tree/main/extra-classes.

### System Information

"cliVersion": "sfdx-cli/7.131.0",
"architecture": "darwin-x64",
"nodeVersion": "node-v16.6.0",
"pluginVersions": [
"@oclif/plugin-autocomplete 0.3.0 (core)",
"@oclif/plugin-commands 1.3.0 (core)",
"@oclif/plugin-help 3.3.1 (core)",
"@oclif/plugin-not-found 1.2.6 (core)",
"@oclif/plugin-plugins 1.10.11 (core)",
"@oclif/plugin-update 1.5.0 (core)",
"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
"@oclif/plugin-which 1.0.4 (core)",
"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
"alias 1.2.0 (core)",
"apex 0.5.0 (core)",
"auth 1.8.0 (core)",
"config 1.3.2 (core)",
"custom-metadata 1.0.12 (core)",
"data 0.6.6 (core)",
"generator 1.2.1 (core)",
"info 1.1.4 (core)",
"limits 1.3.0 (core)",
"org 1.11.0 (core)",
"salesforce-alm 53.6.0 (core)",
"schema 1.1.0 (core)",
"sfdx-cli 7.131.0 (core)",
"sfpowerkit 3.3.3 (link) /Users/kevin/Projects/sfpowerkit",
"source 1.6.2 (core)",
"telemetry 1.4.0 (core)",
"templates 52.6.0 (core)",
"trust 1.1.0 (core)",
"user 1.7.0 (core)"
],
"osVersion": "Darwin 21.1.0"
}

**Comment by mshanemc** [comment]
Nice catch!

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10338484](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000ZIHUUYA5/view)

**Comment by shetzel** [comment]
The fix for this issue is now in SFDX CLI v7.134.0 published today.
See https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71340-jan-20-2022-stable
