### ISSUE TITLE
Ability to run post-install anonymous scripts on unlocked packages

### ISSUE THREAD

**Issue by wspringe** [forcedotcom/cli#1338]
**Is your feature request related to a problem? Please describe.**
Currently, we are only able to run post-install anonymous scripts for 2GP managed packages.

**What are you trying to do**
Execute anonymous scripts after the install of an unlocked package, so we can automate some action like record creation after the package is installed. We want the setup and record creation for an unlocked package to be fully automated from an SFDX command so that we can avoid missing manual steps after an unlocked package installation.

**Describe the solution you'd like**
Ability to specify one or multiple anonymous scripts in the sfdx-project.json file of an SFDX project that is an unlocked package, and the script(s) will execute after the unlocked package is installed into a Salesforce org.

**Describe alternatives you've considered**
SFDX plugin, internal wrapper CLI solution, manually executing scripts after package installation

**Additional context**

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10346855](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000ZdHRUYA3/view)

**Comment by yippie** [comment]
Yes pease, this would be super helpful

**Comment by kyle-chiu** [comment]
This is a great idea!

**Comment by Slgrande** [comment]
We really need this!

**Comment by madhankumargi** [comment]
Much needed for automating CICD process

**Comment by pravirpal** [comment]
much needed, awaiting this feature.
