### ISSUE TITLE
sfdx force:data:tree:import doesn't provide errors

### ISSUE THREAD

**Issue by deb761** [forcedotcom/cli#134]
I just installed the latest sfdx tools and ran tree:import.  The command failed, but didn't provide any error information until I used the --json parameter.

**Versions:**
CLI 7.13.0-27dbcb37d3
Microsoft Windows 10 Pro version 1803

**Comment by mshanemc** [comment]
@deb761 we've made some substantial updates to the `force:data` commands.  Instructions on how to preview those are here. 

Can you try your issue using the new version and see if it solves your problem?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9036370](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000008m5sYAA/view)

**Comment by deb761** [comment]
I believe I have seen errors from the tree:import command with later releases.  Will close.
