### ISSUE TITLE
force:source:retrieve -p for new item metadata in org

### ISSUE THREAD

**Issue by renanlq** [forcedotcom/cli#1340]
**Is your feature request related to a problem? Please describe.**
I don't think is an issue, but the scenario is a little bit annoying. Every time we have new items in our org, I need to run from SFDX extension or from manifesto to get new items from our org, using: 
```
sfdx force:source:retrieve -p force-app/main/default/triggers
```
Do not download new items created from sandbox.

**What are you trying to do**
Retrieve new items using force:source:retrieve -p <path>

**Describe the solution you'd like**
source:retrieve command run as manifesto and VSCode Salesforce extensions.

SFDX Version:
```
{
        "cliVersion": "sfdx-cli/7.125.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.13.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.22 (core)",
                "apex 0.3.0 (core)",
                "auth 1.7.5 (core)",
                "config 1.2.41 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.4 (core)",
                "generator 1.2.0 (core)",
                "limits 1.2.2 (core)",
                "org 1.9.0 (core)",
                "salesforce-alm 53.1.2 (core)",
                "schema 1.0.10 (core)",
                "sfdx-cli 7.125.0 (core)",
                "source 1.3.1 (core)",
                "telemetry 1.2.8 (core)",
                "templates 52.4.0 (core)",
                "trust 1.0.8 (core)",
                "user 1.5.2 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19042"
}
```

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10349938](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000ZnmykYAB/view)

**Comment by mshanemc** [comment]
can you use `sfdx force:source:retrieve -m ApexTrigger` ?

That would download your triggers.  If you use `-p` then it's looking in that folder to see what to download.

**Comment by mshanemc** [comment]
Closing.

`-p` is for pointing at local files as the "what to retrieve" and won't retrieve things that aren't in that path

If you want to retrieve all the ApexTrigger, use `-m ApexClass` OR create a manifest with * for ApexTrigger and use `-x`
