### ISSUE TITLE
Incident Management Feature/Setting Not Automatically Enabled In Scratch Orgs

### ISSUE THREAD

**Issue by dafyddjohns** [forcedotcom/cli#1341]
### Summary

When creating a scratch org from an org shape, the Incident Management feature/setting is not enabled, even though it is in the org from which the shape was defined (and was defined at the creation of the org shape too). 

There is no documented alternative to enable this feature/setting in the scratch org definition file.

This is problematic for automated scratch org creation and deployments.

### Steps To Reproduce:

1.  Enable 'Incident Management' in an org, _Org 1._
1.  Extract some metadata with reference to an Incident Management object like _Problem_ 
1.  Create an org shape from _Org 1_ where Incident Management was enabled, using the beta sfdx force:org:shape:create command.
1.  Create a scratch org _Scratch Org 1_ using the org shape defined in the prior step.
1.  Try to push metadata to _Scratch Org 1_ that includes references to Incident Management objects like _Problem_.

### Expected result

Push to _Scratch Org 1_ should succeed, as it is assumed "Incident Management" should be enabled.

### Actual result

Push to _Scratch Org 1_ fails.

### System Information

{
	"cliVersion": "sfdx-cli/7.130.1",
	"architecture": "linux-arm64",
	"nodeVersion": "node-v17.2.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.19 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"@salesforce/sfdx-scanner 2.12.0 (link) /usr/local/lib/node_modules/@salesforce/sfdx-scanner",
		"alias 1.2.0 (core)",
		"apex 0.4.0 (core)",
		"auth 1.8.0 (core)",
		"config 1.3.0 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.6 (core)",
		"generator 1.2.1 (core)",
		"info 1.1.2 (core)",
		"limits 1.3.0 (core)",
		"org 1.11.0 (core)",
		"salesforce-alm 53.6.0 (core)",
		"schema 1.1.0 (core)",
		"sfdx-cli 7.130.1 (core)",
		"source 1.6.2 (core)",
		"telemetry 1.4.0 (core)",
		"templates 52.6.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.0 (core)"
	],
	"osVersion": "Linux 5.10.76-linuxkit"
}
### Additional information

_Feel free to attach a screenshot_.

**Comment by WillieRuemmele** [comment]
Hi @dafyddjohns are you able to "Enable 'Incident Management' in an org" via the scratch definition file, or in a programmatic way?

**Comment by dafyddjohns** [comment]
There are no documented ways of enabling it via the scratch org definition file, so I was hoping the org shape would help. If the other shape has limitations then this should be documented, otherwise it’s a “similar shape”, not identical - a shape just like the source org except little bits cut out.

One possible workaround could to use automated UI script to enable it, but org shape and the scratch org definition file was created for this very reason.

**Comment by WillieRuemmele** [comment]
I agree with your points. I've reached out to the internal team responsible for Incident Management and I'm waiting on a response.

**Comment by WillieRuemmele** [comment]
Hi @dafyddjohns - I've heard back from the team that owns Incident Management. It should be available as part of the Spring release, so approx. 1-1.5 months away.

**Comment by zhou059** [comment]
Hi, looking for how to enable incident management as well in a scratch org, what may be the feature to get this going since spring release is here now. Don't see anything in documentation yet

**Comment by gabesumner** [comment]
This appears to have worked for me...

```
{
  "orgName": "company",
  "edition": "Developer",
  "features": ["ServiceCloud","EnableSetPasswordInApi","ServiceUser"],
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    }
  }
}
```
The **Incidents** object should now be inherited from the ServiceCloud/ServiceUser features.
