### ISSUE TITLE
Flow failing to be deployed when involved in both pre destructive changes and deploy

### ISSUE THREAD

**Issue by tiagonnascimento** [forcedotcom/cli#1343]
### Summary

If a flow is specified in destructiveChanges.xml, which is used as predestructivechanges, and the same flow is in a package.xml, it will not be deployed to the target org. 

### Steps To Reproduce:

1.  Define a flow
1.  Include it into a destructiveChanges.xml and in a package.xml
1. run `sfdx force:source:deploy --manifest manifest/package.xml --targetusername sfdc --testlevel RunLocalTests --predestructivechanges destructive/destructiveChanges.xml -g`

### Expected result

Flow to be applied with a new version

### Actual result

On deployedSource output from the command, the end state will be deleted, as per the following:

```
2021-12-30T13:50:12.0675042Z       {
2021-12-30T13:50:12.0675353Z         "fullName": "SimpleFlow",
2021-12-30T13:50:12.0675717Z         "type": "Flow",
2021-12-30T13:50:12.0676539Z         "filePath": "/home/vsts/work/1/force/main/default/flows/SimpleFlow.flow-meta.xml",
2021-12-30T13:50:12.0677002Z         "state": "Deleted"
2021-12-30T13:50:12.0677258Z       }
```

### System Information

sfdx-cli/7.132.0 linux-x64 node-v16.13.1

**Comment by maggiben** [comment]
Hello, sorry to hear that, can you please mock the simplest flow that would trigger the error and post it here so we can try reproduce it ?

**Comment by tiagonnascimento** [comment]
Hi @maggiben , sure thing. 

Repo with sample/mock is in here: https://github.com/tiagonnascimento/issue-salesforcecli-1343

Execution log of source:deploy is here:

```
% sfdx force:source:deploy --manifest manifest/package.xml --predestructivechanges destructive/destructiveChanges.xml -g -w 10 -u demo-build
*** Deploying v52.0 metadata with SOAP API v53.0 connection ***
Deploy ID: 0Af5w00000lT8g6CAC

=== Deleted Source
FULL NAME   TYPE  PROJECT PATH
──────────  ────  ─────────────────────────────────────────────────────
SimpleFlow  Flow  force-app/main/default/flows/SimpleFlow.flow-meta.xml 
```

**Comment by maggiben** [comment]
Im getting this error: `insufficient access rights on cross-reference id` is that the same error you see ?
![image](https://user-images.githubusercontent.com/2845947/148267004-d057eb49-68fd-4224-90f4-747cbc08c717.png)
