### ISSUE TITLE
We can’t retrieve the specified metadata object: EmailTemplateFolder

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/cli#1345]
### Summary

While saving a Lightning Email Template in a custom folder with `Folders and Enhanced Sharing` enabled, pulling changes displays the following warning:
```
We can’t retrieve the specified metadata object: EmailTemplateFolder. Certain metadata types, like MyFolder are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
```
Being obedient, I'm filing a bug as requested ;-)

Not sure if this is a 100% issue with the CLI, if so is it something I could fix myself via a PR ? Or does it need any internal validation about the source format for this file (is it decomposed or not, file name etc) ?

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1. Enable `Folders and Enhanced Sharing` in `Setup`/`Lightning Email Templates` or ad the following setting to your `project-scratch-def.json` file:
```
"emailTemplateSettings": {
      "enableTemplateEnhancedFolderPref": true
}
```
2. Go to the Contact tab, create one
3. In the Activity section, select Email
4. Enter a random subject
5. Below body field, click on the `Insert, create, or update template` button and select `Save as new template...`
6. Click on `Select Folder` and then `New Folder`
7.  Create a new folder, and save your template in it
8.  Pull everything

### Expected result

Email Template and Email Template Folder should be pulled.

### Actual result

Only Email Template is pulled, and a warning is displayed about Email Template Folder:
```
We can’t retrieve the specified metadata object: EmailTemplateFolder. Certain metadata types, like MyFolder are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
```

### System Information
```
{
        "cliVersion": "sfdx-cli/7.132.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.13.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.15 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.10 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.2 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.6 (core)",
                "generator 1.2.1 (core)",
                "info 1.1.4 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.7.0 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.132.0 (core)",
                "source 1.6.2 (core)",
                "telemetry 1.4.0 (core)",
                "templates 52.7.0 (core)",
                "texei-sfdx-plugin 1.14.0",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.18363"
}
```

### Additional information

In case it's not easy to find, here is the button to click to save your Lightning Email Template:
![saveastemplate](https://user-images.githubusercontent.com/2465122/148081862-a8554196-2e33-411f-aa5e-e121ff5846ed.jpg)

**Comment by maggiben** [comment]
I created an email template + folder and I was able to retrieve them despite the warning message: 
![image](https://user-images.githubusercontent.com/2845947/148130396-196aafc4-ca98-48dc-b4fd-38fe39a563c6.png)
Also uploaded the results [here](https://github.com/maggiben/dreamhouse-lwc/tree/main/force-app/main/default/email/MyEmailTemplateFolder) If this is not what you need please let me know.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10385112](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000cikfhYAA/view)

**Comment by FabienTaillon** [comment]
Thank you @maggiben for your answer.

What you're getting here is the EmailTemplate itself, but not the metadata for the containing folder.
If you try to create a new scratch org from this metadata, you'll get an error on push saying that the folder can't be found:

![error](https://user-images.githubusercontent.com/2465122/148360755-2a6aa5bb-2ed8-4893-99eb-e2fa222debeb.jpg)

If you do the same thing for a metadata being supported, let's say a report folder, you can see that in addition to the report itself, there is a metadata file for the report folder:

![report](https://user-images.githubusercontent.com/2465122/148361388-2f800c87-d810-4fc9-93cb-7b81a42565e8.jpg)

This is what's missing here and prevent us to recreate a new scratch org without having to manually create the email template folder first.

**Comment by mshanemc** [comment]
What I'm seeing is that EmailTemplate now has 2 potential parent types (EmailFolder, similar to ReportFolder which it's always had and now a new type called EmailTemplateFolder).

Gotta figure out how to handle that possibility.

**Comment by FabienTaillon** [comment]
@mshanemc looks like EmailFolder is for Classic Email Template, and EmailTemplateFolder for Lightning Email Template.

I was able to retrieve it with a package.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>MyLightningFolder</members>
        <members>MyLightningFolder/My_Lightning_Template_1641477219455</members>
        <name>EmailTemplate</name>
    </types>
    <version>53.0</version>
</Package>
```

This gives me a `MyLightningFolder-meta.xml` metadata file which content is different from a regular EmailFolder file (root tag is EmailTemplateFolder instead of EmailFolder, includes a folderShares tag etc...), but if I copy/paste it as is under force-app/main/default/email and change the file extension to match the other EmailFolder files (`MyLightningFolder.emailFolder-meta.xml`), it works.

I'm able to push to a new Scratch Org again, and folder is created correctly as a Lightning Email Template folder.
So retrieving it like a regular EmailFolder and saving it at the same place and with the same extension should work.

**Comment by mshanemc** [comment]
This is quite a nasty problem.  We're gonna get a response from the metadata owners before deciding how to fix it. 

Thanks for reporting, though!
