### ISSUE TITLE
Can no longer deploy Permission Set Groups

### ISSUE THREAD

**Issue by jcarmignani** [forcedotcom/cli#1346]
### Summary

I get an error while deploying Permission Set Groups since a couple of days/weeks:
Property 'hasActivationRequired' not valid in version 51.0

### Steps To Reproduce:

1. Deploy Permission Set group with CLI configured as following: "*** Deploying v51.0 metadata with SOAP API v53.0 connection ***" using GitLab
2. See error message in Gitlab job logs

### Expected result

I should be able to deploy a Permission Set Group since it is not linked to a metadata version

### Actual result

I get the following error message in the GitLab Job logs:
Error  SFDC_Minimum_Access                       Property 'hasActivationRequired' not valid in version 51.0
Error  SFDC_Support_Provisioning                 Property 'hasActivationRequired' not valid in version 51.0
Error  SFDC_Support_Tier_1                       Property 'hasActivationRequired' not valid in version 51.0
Error  SFDC_Support_Tier_2                       Property 'hasActivationRequired' not valid in version 51.0

_Describe what actually happened_.

### System Information
`$ sfdx --version
sfdx-cli/7.132.0 linux-x64 node-v16.13.1
$ sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.15 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.10 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 1.2.0 (core)
apex 0.7.0 (core)
auth 1.8.0 (core)
config 1.3.2 (core)
custom-metadata 1.0.12 (core)
data 0.6.6 (core)
generator 1.2.1 (core)
info 1.1.4 (core)
limits 1.3.0 (core)
org 1.11.0 (core)
salesforce-alm 53.7.0 (core)
schema 1.1.0 (core)
sfdx-cli 7.132.0 (core)
source 1.6.2 (core)
telemetry 1.4.0 (core)
templates 52.7.0 (core)
trust 1.1.0 (core)
user 1.7.0 (core)
$ echo "Connecting to $CI_ENVIRONMENT_NAME"
Connecting to qa5
$ openssl aes-256-cbc -d -md md5 -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.`

### Additional information
I have noticed that now there is a new header before deployment that indicates the version in the package.xml '53.0' compared to metadata version '51.0' (Not sure where 51.0 is coming from and how I can customize it)

![image](https://user-images.githubusercontent.com/11173517/148186480-9f4a5479-bd89-4f37-bee4-e5f3b920e2f1.png)

![image](https://user-images.githubusercontent.com/11173517/148186438-2bbcd172-1cc2-4cbf-bca5-3204babb47b9.png)

**Comment by jcarmignani** [comment]
Current workaround is to remove the tags hasActivatedSessionRequired from the Permission Set Group metadata:
`<hasActivationRequired>false</hasActivationRequired>`
![image](https://user-images.githubusercontent.com/11173517/148187259-2f9c7abf-b738-483b-9a75-dc8ce7aa0f5c.png)

**Comment by mshanemc** [comment]
`v51.0 metadata` comes from sourceApiVersion in `sfdx-project.json`.

**Comment by jcarmignani** [comment]
Thanks @mshanemc . I have updated the sfdx-project.json with the v.53.0. Looks like the issue is fixed but now I have another issue with Experience Bundles: 
![image](https://user-images.githubusercontent.com/11173517/148367903-1f7c58f3-777e-4863-8156-f80832123e48.png)

A similar issue is open on another Github project since August: 
https://github.com/forcedotcom/salesforcedx-vscode/issues/3462

Do you have any iidea hhow to fix this issue?

**Comment by mshanemc** [comment]
ExperienceBundle tends to have breaking changes to its json structure across each major release.

The only good solution I've seen is to deploy it to an org using the previous version, then flip your `sfdx-project.json` sourceApiVersion to the new version, then retrieve the experieneBundle to that you get the new version of the metadata.
