### ISSUE TITLE
sfdx force:org:create Error Hang

### ISSUE THREAD

**Issue by Kevmo92** [forcedotcom/cli#135]
### Summary

There's some additional information on this salesforce community post as well,
https://success.salesforce.com/0D53A00004QzY4k

We're hitting an inconsistent error with the `sfdx force:org:create` command.

```
ERROR running force:org:create:  We encountered a problem while attempting to configure and approve the Connected App for your org. Verify the Connected App configuration with your Salesforce admin
```

The error we're getting back seems like an inconsistent API error, but when the sfdx cli receives this error the cli is just hanging without returning an exit code. This is the error I'd like to discuss.

We first noticed the API error with version 7.11.2 of the sfdx cli, but even reverting to 7.8.1 or upgrading to 7.14.0 we see the same behavior. 

### Steps To Reproduce:

It's difficult to reproduce the inconsistent error API error, it seems specific to a user, but if you're able to reproduce an error you'll experience this:

1.  Step 1. sfdx force:org:create -f config/file.json -s
1.  Step 2. command returns error and session hangs. Only way to break the session connection is by escaping it.

### Expected result

If a sfdx cli command receives an error from an API call such as the one above the sfdx cli should return an exit code that breaks the session.

### Actual result

When a sfdx cli command receives the error above the command never exits and needs to be escaped manually. 

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.11.2 darwin-x64 node-v8.16.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.1.5 (core)
├─ force-language-services 46.3.0 (core)
└─ salesforce-alm 46.3.0 (core)

sfdx-cli 7.11.2 (core)

**OS and version**:
Experienced on macOS Mojave and Debian docker image

**Comment by mshanemc** [comment]
I'm closing this because it's super old.

Pretty much all the code (the command, and the library underneath for org creation ) has been worked.  
Very specifically, the org creation process no longer relies on the streaming API ( which was a known source of some hangs).
There's also a `org resume scratch` to recover from a process that you ctrl-c once the request has made it to the hub, so it's more "recoverable".

If you've got a way to repro it on the new `org:create:scratch` command, please open a new issue
