### ISSUE TITLE
ECONNRESET error when running force:data:soql:query from bash script

### ISSUE THREAD

**Issue by jamangini** [forcedotcom/cli#1350]
### Summary

I'm running a query that stores a large amount of FederationId values (read: email addresses) into a bash script variable, and then executes a subsequent query with that data as an *IN* filter, and receive the following error.

`Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}`

### Steps To Reproduce:

1.  create a new text file on your local computer
2. add this to the new text file
3. 'sam@salesforce.com',
'ken@salesforce.com',
'roger@salesforce.com',
'danny@salesforce.com'
4. save that text file as contact_data.txt
5. create a new bash file
6. add this in
```
#!/bin/bash
cleanSupportforceData=$(cat contact_data.txt)

sfdx force:data:soql:query -q "SELECT Id, Name, Email, FederationIdentifier, IsActive, Username FROM User WHERE FederationIdentifier IN ($cleanSupportforceData)"
```
7. save that file as bashQuery.sh
8. run that shell script
9. receive an error

### Expected result

My naive expectation is for this to run, as it's <100,000 SOQL character limit

### Actual result

The error denoted above:
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

### System Information

- Paste the output here
```
{
	"cliVersion": "sfdx-cli/7.132.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v17.0.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.2.0 (core)",
		"apex 0.7.0 (core)",
		"auth 1.8.0 (core)",
		"config 1.3.2 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.6 (core)",
		"generator 1.2.1 (core)",
		"info 1.1.4 (core)",
		"limits 1.3.0 (core)",
		"org 1.11.0 (core)",
		"salesforce-alm 53.7.0 (core)",
		"schema 1.1.0 (core)",
		"sfdx-cli 7.132.0 (core)",
		"source 1.6.2 (core)",
		"telemetry 1.4.0 (core)",
		"templates 52.7.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.0 (core)"
	],
	"osVersion": "Darwin 19.6.0"
}
```
### Additional information

_Feel free to attach a screenshot_.

**Comment by maggiben** [comment]
Hi, can you upload a demo org that we can use to perform the `force:data:soql:query` ? maybe [dreamhowse-lwc](https://github.com/trailheadapps/dreamhouse-lwc)

**Comment by jamangini** [comment]
Hey @maggiben I'm fairly certain that this can be done without any demo org at all - you just need Step 3 to have a large amount of values (~1,000), and they don't need to be unique.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10427080](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000epnZ7YAI/view)

**Comment by maggiben** [comment]
I tried +2500 items in the query and it failed as you described, It might not be a bug in the CLI itself but even if that's not the case a more descriptive error message would be nice to have.

![image](https://user-images.githubusercontent.com/2845947/149234943-ba53cc19-04df-463e-8bce-a77d289a363d.png)
