### ISSUE TITLE
Ability to retrieve / pull profiles with standard behavior in source tracked sandbox and scratch orgs.

### ISSUE THREAD

**Issue by rom116** [forcedotcom/cli#1351]
**Is your feature request related to a problem? Please describe.**
Currently, in source tracked sandbox and scratch orgs, when we retrieve / pull profiles, it retrieves permissions for components in the package.xml **PLUS** all other components that are currently tracked.  

Reference: https://developer.salesforce.com/docs/atlas.en-us.232.0.sfdx_dev.meta/sfdx_dev/sfdx_dev_source_tracking_source_tracking_profiles.htm

We would also like the option to override this behavior to retrieve/pull the "standard" way.

**What are you trying to do**
There are times when we want to retrieve the profile permissions for components that are ONLY listed in the package.xml or changeset from source tracked sandbox & scratch orgs.

**Describe the solution you'd like**
A parameter where we can override the default behavior
sfdx force:source:retrieve -x package.xml --profilestandardretrieve true  
sfdx force:mdapi:retrieve -p ChangeSetName --profilestandardretrieve true  

This will retrieve the profile permissions for only components that are listed in the package.xml or changeset/package.

**Describe alternatives you've considered**
Nothing elegant at this point.

**Additional context**
See Salesforce Reference Docs for current behavior in source tracked sandbox and scratch orgs.
https://developer.salesforce.com/docs/atlas.en-us.232.0.sfdx_dev.meta/sfdx_dev/sfdx_dev_source_tracking_source_tracking_profiles.htm

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10395490](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000d9Ih2YAE/view)

**Comment by WillieRuemmele** [comment]
Hi - we've looked into supporting profiles in that way, and found it wasn't possible without a lot of hazardous rewrites https://github.com/forcedotcom/cli/discussions/1785#discussioncomment-4722761
