### ISSUE TITLE
Generate manifest file based on force:source:status local, remote, and both.

### ISSUE THREAD

**Issue by rom116** [forcedotcom/cli#1352]
**Is your feature request related to a problem? Please describe.**
Use case - in source tracked sandbox & scratch orgs, hundreds of changes were made.
We only want to retrieve / pull a subset of these changes.
Sometimes, having the option to manipulate a package.xml file is much quicker.
I.e.) 100 custom fields spread across multiple custom objects.  Editing a package.xml to target what we want to retrieve/deploy is much easier.

**What are you trying to do**
The ability to generate a manifest file (package.xml) based on force:source:status of local, remote, or both.

**Describe the solution you'd like**
sfdx force:source:status -p -r  --manifestname myNewManifest  // generates a package.xml for remote changes.
sfdx force:source:status -p -l   --manifestname myNewManifest  // generates a package.xml for local changes
sfdx force:source:status -p  --manifestname myNewManifest   // generates a package.xml for both local and remote changes.

--manifestname  // optional, default is package.xml
-p // optional, only used to generate a package.xml from force:source:status response

**Describe alternatives you've considered**
Nothing elegant so far.    

**Additional context**
N/A

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10395526](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000d9VO8YAM/view)

**Comment by mshanemc** [comment]
you might be interested in this design discussion https://github.com/forcedotcom/cli/discussions/2040
