### ISSUE TITLE
In-place upgrade stuck for `sf` CLI `env list` command

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#1353]
This is going to sound similar to a bug I logged previously where in-place upgrades of the `sfdx` CLI weren't getting things to the latest state, but whereas that one was specific to the `sfdx` CLI and presumably the source of the installed plugin(s), this one is specific to the `sf` CLI and minimally the `env list` command.

A few weeks ago I noticed that the `sf env list` command was once again including information about Salesforce Functions compute environments as the pre-GA removal of the `sf env list --compute` variant. Well, at least it does when you're properly authenticated for functions. And I guess that technically that information was there in previous builds but kind of munged with other environment information vs. being more explicit now. But I digress...

This allowed me to restore some functionality in IC2's support for Functions where IC2 can query the current project's compute environment information to be used when executing other CLI commands for functions integration. However, while testing that on a few of my smoke test environments (Windows, Mac x64, Mac M1, and Linux), I noticed that one environment (Mac M1) was still returning the old output from `sf env list` that doesn't include compute environments. Specifically, the output should look like the following now:

```json
{
  "status": 0,
  "result": {
    "salesforceOrgs": [
      ...
    ],
    "scratchOrgs": [
      ...
    ],
    "computeEnvs": [
      ...
    ]
  },
  "warnings": []
}
```

but instead it still looked like:

```json
{
  "status": 0,
  "result": [
    ...
  ]
}
```

Note the lack of distinction between the various environment types in the latter.

I first just tried to ensure that I was on the latest version using:

```
sf plugins # showed "functions 1.3.0"
sf plugins update
sf plugins # still showed "functions 1.3.0"
```

And of course the output was the same. I then tried to reinstall the `functions` plugin explicitly using:

```
sf plugins uninstall functions
sf plugins install functions
```

Unfortunately that didn't fix it either (which makes me think that perhaps the `env` command is "core" and not part of the `functions` plugin?). Ultimately I had to do a full uninstall/reinstall of the Salesforce CLI after which it produced the newer output. Again, this only occurred on my Mac M1 test machine and not in any of my other environments, but it has me concerned about CLI plugins/commands getting into a wedged state over time as a result of in-place upgrades resulting in hard-to-diagnose issues when integrating those CLI commands into another tool.

Also unfortunately, I no longer have any environment in this state, so I'm unable to provide additional hands-on diagnostic information based on a reproduction of the problem. If I do see it again, whether myself or via an IC2 user, I'll update this issue so that diagnostics can be gathered.

**Comment by mshanemc** [comment]
I believe this happened.  Have seen other similar reports.  

Closing the WI because of the env list (command is deprecated/gone, Functions is EOL) and the very old sf version.   We need a way to cause the "stuck" upgrade problem to figure out why it happens
