### ISSUE TITLE
Error when pulling the ConnectedApp metadata.

### ISSUE THREAD

**Issue by geospatialqueryapi** [forcedotcom/cli#1355]
### Summary

I'm using scratch org.
Created ConnectedApp.

Trying to pull the metadata.
Received an error.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

sfdx force:source:pull -u MyTestOrg

### Expected result

pulling the ConnectedApp metadata.

### Actual result

Entity of type 'Document' named 'ConnectedApp_Resources/TemporaryLogoName1' cannot be found
Entity of type 'Document' named 'ConnectedApp_Resources' cannot be found

### System Information
MacOS

cliVersion": "sfdx-cli/7.129.0

**Comment by maggiben** [comment]
Hi, can you try upgrading to the latest CLI version ?
Also, what steps you performed in the Org in regards to the Connected App ? se we can reproduce it in dreamhouse-lwc.
Thanks.
