### ISSUE TITLE
We can’t retrieve the specified metadata object: UserProfileSearchScope

### ISSUE THREAD

**Issue by manaspatro** [forcedotcom/cli#1360]
While doing a PULL there was a warning at the top about specific metadata not being able to be pulled, but it did not error. The next test was if I could push that source code to our scratch org. That unfortunately failed still, but I wonder if it’s related to the warning I got. Please see the output below:

sfdx force:source:pull output

We can’t retrieve the specified metadata object: UserProfileSearchScope. Certain metadata types, like UserProfileSearchScopeDefault are not currently supported by the CLI.

**Comment by maggiben** [comment]
Hi can you please paste the output of `sfdx version --verbose` ? thanks !
