### ISSUE TITLE
ERROR Stopping *** "status": 1, "name": "Domain Not Found", "message": "The org cannot be found"

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1361]
### Summary

This error is new. It is probably a salesforce service issue. But I think sfdx could retry before throwing this error.

![Screenshot 2022-01-14 at 08 02 09](https://user-images.githubusercontent.com/55927613/149505311-835bb987-6522-4e31-bd5f-0b1c55d880e2.png)

### Steps To Reproduce:

1 - validate metadata in an org and store the validaiton id to use in step 2
2 - run `sfdx force:source:deploy -u $orgAlias -q $quickDeploy -w 80 --json`

### Expected result

Quick deploy should be scheduled without a problem.

### Actual result

Quick deploy isnt scheduled because a connection problem

### System Information

sfdx: 1.32.0

### Additional information
![Screenshot 2022-01-14 at 08 02 09](https://user-images.githubusercontent.com/55927613/149505311-835bb987-6522-4e31-bd5f-0b1c55d880e2.png)

**Comment by mshanemc** [comment]
That does have retries wrapped around it.
`SFDX_DNS_TIMEOUT` defaults to 3 seconds of retrying, but you can set it higher if it helps.  

code here as an FYI 
https://github.com/forcedotcom/sfdx-core/blob/70632d739ddf05be4733182bc8d8128690b2426b/src/status/myDomainResolver.ts#L67

**Comment by AllanOricil** [comment]
@mshanemc thanks for helping. I will try that
