### ISSUE TITLE
Deploy fails when case of file name is changed

### ISSUE THREAD

**Issue by dxenonb** [forcedotcom/cli#1362]
### Summary

Source push fails when changing the case of a file name (observed with Apex classes) and its metadata file.

### Steps To Reproduce:

**Repository to reproduce:** [case-sensitive-rename](https://github.com/dxenonb/case-sensitive-rename)

1.  Create an org and push the contents of the `case-sensitive-rename` repo
1.  Rename: `force-app/main/default/classes/{badCase.cls => BadCase.cls}` and the corresponding `.cls-meta` file
2.  Push again - the push should fail

### Expected result

The push to succeed and the class to get renamed in the scratch org.

> Caveat: I would expect/tolerate this could be problematic when deploying to production. But this should probably(?) work in scratch orgs, when you may have not committed anything or deployed to an environment without source tracking.

### Actual result

```
TYPE   PROJECT PATH                                PROBLEM
─────  ──────────────────────────────────────────  ───────────────────────────────────────────
Error  force-app/main/default/classes/BadCase.cls  File name mismatch with class name: badCase
ERROR running force:source:push:  Push failed.
```

The push fails.

If you change the name of the class in the file to UpperCamelCase `BadCase`, the error is slightly different:

```
TYPE   PROJECT PATH                                         PROBLEM
─────  ───────────────────────────────────────────────────  ─────────────────────────────────────────────────────
Error  force-app/main/default/classes/BadCase.cls-meta.xml  Must specify both the source file & the metadata file
Error  force-app/main/default/classes/badCase.cls-meta.xml  Must specify the metadata file
ERROR running force:source:push:  Push failed.
```

But the work around is the same:

### Work Around

In `sourcePathInfos.json`, if I change the file paths to reflect the new case, the push can succeed.

### System Information

```
{
        "cliVersion": "sfdx-cli/7.133.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.14 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.1 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.7.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.133.0 (core)",
                "source 1.7.0 (core)",
                "telemetry 1.4.0 (core)",
                "templates 52.7.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Darwin 20.5.0"
}
```

### Additional information

I would expect the behavior of this may differ on windows (case insensitive) and mac/linux (case sensitive). I am on mac.

**Comment by mshanemc** [comment]
I'm closing this in favor of a higher-level discussion about how we want this to work.  That's here.

https://github.com/forcedotcom/cli/discussions/2682
