### ISSUE TITLE
Source tracking not updated for main package when unpackagedMetadata push fails.

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#1364]
### Summary

When pushing source with `sfdx force:source:push` in a project that uses `unpackagedMetadata`, if the primary push succeeds but the `unpackagedMetadata` push fails, the primary push is not rolled back yet the primary package's source tracking is updated.  The next push will report conflicts requiring the `-f` flag.

### Steps To Reproduce:

**Repository to reproduce:** Use any repo configured to create an unlocked package.

1.  If the repo does not already use `unpackagedMetadata`, configure an `unpackagedMetadata` directory (per the [Developer Guide][1]) and move a unit test into the unpackaged folder.
2. Create a new scratch org and push all code to confirm everything works.
3. Check `sfdx force:source:status` and confirm no differences.
4. Make a valid change to a file in the main package (add a comment to an Apex Class)
5. Make an invalid (non-compilable) change to a file in the `unpackagedMetadata` directory (e.g., assign to an undeclared variable).
6. Attempt to push with `sfdx force:source:push`.  Observe that the package push succeeds but the unpackaged push fails.
7. Run `sfdx force:source:status` again and observe that the file changed in step 4 is now reported as a conflict.

[1]: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_unlocked_pkg_unpackaged_md.htm

### Expected result

The successful push (main package) should have source tracking updated.

### Actual result

No source tracking is updated, and conflicts are incorrectly reported.

### System Information

{
        "cliVersion": "sfdx-cli/7.133.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v17.2.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.14 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.1 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.7.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.133.0 (core)",
                "source 1.7.0 (core)",
                "telemetry 1.4.0 (core)",
                "templates 52.7.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Darwin 21.1.0"
}

**Comment by maggiben** [comment]
Dear user, this issue has been fixed in the latest version of the `source-tracking` library which can be accessed via these commands:
```
$ sfdx force:source:beta --help
new versions of source tracking commands

USAGE
  $ sfdx force:source:beta:COMMAND

TOPICS
  force:source:beta:tracking  new versions of source tracking commands

COMMANDS
  force:source:beta:pull    pull source from the scratch org to the project
  force:source:beta:push    push source to a scratch org from the project
  force:source:beta:status  list local changes and/or changes in a scratch org
```
