### ISSUE TITLE
destructive deployment

### ISSUE THREAD

**Issue by nikhileshmishra** [forcedotcom/cli#1367]
We are using sfdx git delta plugin. Its working fine.
When there is any deletion  , I can see the changes in destructiveChanges/destructiveChanges.xml file ,
But when we r deploying ,it shows
MDAPI PROGRESS | ������������������������������������������������������������������������������������������������������������������������ | 

0/0 Components
MDAPI PROGRESS | ������������������������������������������������������������������������������������������������������������������������ |
 0/0 Components

the deployment log shows 0/0 .Is it correct ? Even in sandbox we could see it shows 0/0
How can we check if its doing its destructive change
My question is , when we deploy the destructive components ,what can we expect to see in logs & sandbox ?

In my logs , i could see  0/0 . Is it correct ?
or it should show the actual number of components deleted.

**Comment by shetzel** [comment]
The sfdx-git-delta plugin is not a core CLI plugin owned by Salesforce.  You'll have to post an issue for them.
