### ISSUE TITLE
Deployment of source-tracked profiles extra fields.

### ISSUE THREAD

**Issue by rom116** [forcedotcom/cli#1369]
### Summary

When retrieving profiles from source-tracked sandbox, it retrieves permissions for all tracked changes. For example, 20 custom fields were created.  We only want to deploy 15 of these fields and their related FLS.  When we deploy the profile changes to our pipeline sandboxes, we receive an error because the profile included all 20 fields' FLS, when we only need the 15 fields.

### Steps To Reproduce:

When retrieving profiles from source-tracked sandbox, it retrieves permissions for all tracked changes. For example, 20 custom fields were created.  We only want to deploy 15 of these fields and their related FLS.  When we deploy the profile changes to our pipeline sandboxes, we receive an error because the profile included all 20 fields' FLS, when we only need the 15 fields.

### Expected result

Ability to retrieve profiles permissions according to manifest file.

### Actual result

Profiles include all permissions for all source tracked changes.
https://developer.salesforce.com/docs/atlas.en-us.232.0.sfdx_dev.meta/sfdx_dev/sfdx_dev_source_tracking_source_tracking_profiles.htm

**Comment by mshanemc** [comment]
the link you supplied says this, which sounds like it's working-as-design.  There's a lot of confusion around this topic, and you can debate whether it's actually an awful design, but it's not a bug.

```
With source tracking, retrieving profiles returns profile information pertaining to anything else specified in the package.xml file plus any components getting tracked by source tracking. That includes any entity for which a change exists between your local project and the org.
```

**Comment by kngo-esba** [comment]
@mshanemc - What would be the recommendation for retrieving only a subset of fields (15 fields) and only their relevant profile FLS in a source-tracked sandbox that is now tracking 20 field changes along with all 20 profile FLS changes? 

1. Manually and surgically edit the profile XML file to remove the 5 field FLS?

2. Generate the manifest for the 15 fields and profile, then loop through and delete the SourceMember records, and then retrieve using the generated manifest file.  Though we lose the option of retrieving, commiting, and deploying the other 5 fields and FLS at a later time.

Much friction for this use case.


Thanks!

**Comment by rom116** [comment]
Thanks @mshanemc !

What would be the recommendation for retrieving only 15 custom fields (along with their 15 profile FLS) via a manifest file in a source-tracked sandbox that is now tracking 20 fields / 20 profile FLS?

1. Use the manifest file to retrieve 15 custom fields and 20 profile FLS.  And then manually (surgically)  edit the profile xml file to remove the 5 FLS xml blocks.

2. Or generate a manifest file for the 15 custom fields and profile.  Then loop through and delete all the SourceMember records.  And then, retrieve the 15 custom fields / 15 profile FLS using the generated manifest file.  Though we lose tracking of the other 5 fields and their FLS to be retrieved, committed, and deployed at a later time.

Much friction for a source-tracked sandbox that may involve working on multiple features that we don't always retrieve every associated tracked profile changes to commit to source and/or deploy to other envs.

Thanks!
