### ISSUE TITLE
Cant pull EntitlementProcess with Uppercase names

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#137]
### Summary

Yesterday I experienced this issue when trying to `force:source:pull` an entitlement process from a scratch org, I noticed that when performing a `force:source:retrieve` of the same EntitlementProcess, the name was being downcased

I changed the value to all lowercase and seems to work well.

I have seen that this issue is already tracked here https://success.salesforce.com/issues_view?id=a1p3A0000003cqwQAA

### Steps To Reproduce:

1.  Create a scratch org with entitlements enabled
1.  Create an entitlement process with name `TestEntitlementProcess`
1. See error

### Expected result

SFDX should not edit the name nor fail on retrieving an entitlement process with uppercase letters

### Actual result

It fails on pulling, and renames on retrieving

### Additional information

![image](https://user-images.githubusercontent.com/10410852/60985987-cb8fa780-a33e-11e9-90a2-a24878bef683.png)

![image](https://user-images.githubusercontent.com/10410852/60985695-355b8180-a33e-11e9-8ee9-9c42b11d44c8.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli 7.14.0 (core)

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```shell
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.4.0
├─ force-language-services 46.9.0
└─ salesforce-alm 46.8.0
```
**OS and version**: Windows 10 and WSL

**Comment by clairebianchi** [comment]
This issue is known and owned by another team at Salesforce. We have informed the team that you are seeing this problem, the internal work item is W-6284828. I am closing this one here
