### ISSUE TITLE
Unable to find JOB ID in jenkins logs

### ISSUE THREAD

**Issue by nikhileshmishra** [forcedotcom/cli#1374]
I am running sfdx cli command in my jenkins pipeline .
Deployment is working fine .  But I am unbale to see the JOB ID in Jenkins log.
I am referring to the same deployment ID which reflects in Sandbox mentioned below.

![image](https://user-images.githubusercontent.com/89146067/150752932-20b5b7d8-37aa-4be9-994d-d64229a86b62.png)

Please guide if we need to add any extra parameters in deploy command  which can reflect  the ID .
So that this ID can be extracted and used for quick deploy within jenkins using below command after validation.
sfdx force:source:deploy -q (ID)

If we have any other way to get the ID,please share

**Comment by shetzel** [comment]
In a scripting environment such as Jenkins, I would append `--json` to your commands so you can easily parse the return results and use them in your scripts.  `jq` is a very useful library for this purpose.  I would read this blog: https://developer.salesforce.com/blogs/2020/02/using-salesforce-cli-output-and-scripting

If this solves your issue, please close this.
