### ISSUE TITLE
sfdx force:source:deploy -x ./manifest/package.xml (This command not deploying all components

### ISSUE THREAD

**Issue by rahulkapoor83** [forcedotcom/cli#1377]
### Summary

Deploying via Command -- "sfdx force:source:deploy -x ./manifest/package.xml" is not deploying all components. Ideally the package i am installing should install 8000 components but its just installing around 2921. 

Next interesting part is executing sfdx update shows that update is completed but still i don't see the latest version still. Not sure why. Stuck in Salesforce-cli@7.118.1. Please suggest how to upgrade. 

### Steps To Reproduce:

--Same as Summary--

### Expected result

It should install 8400 Components

### Actual result

Its deploying only 2921.

### System Information
»   Warning: sfdx-cli update available from 7.118.1 to 7.133.0.
{
        "cliVersion": "sfdx-cli/7.118.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.17.6",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.3 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.1 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.8 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.34 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.1 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.7.0 (core)",
                "salesforce-alm 52.3.3 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.118.1 (core)",
                "source 1.0.15 (core)",
                "telemetry 1.2.3 (core)",
                "templates 52.1.0 (core)",
                "trust 1.0.5 (core)",
                "user 1.4.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.17763"
}

**Comment by rahulkapoor83** [comment]
I was able to upgrade CLI to latest version but still facing the same issue

**Comment by terry-ward-sasktel** [comment]
I am also seeing this issue.  Running sfdx-cli/7.134.0 linux-x64 node-v12.22.9.  In trying to diagnose the issue I've limited the package.xml down to a single object (an Opportunities list view).  The list view is never deployed.  Instead 3 custom fields and 2 validation rules that aren't listed in package.xml are deployed instead.

**Comment by mshanemc** [comment]
If either of y'all could share a repo or zip file that will reproduce the error, that would help a lot.

It'd be worth checking your `.forceignore` file via `sfdx force:source:ignored:list` to make sure that you're not accidentally ignoring something.

You can also try running `force:source:convert` (it uses the same logic as `source:deploy` but you'll be able to see what's in the deployment metadata) to compare what's being skipped to look for patterns.

**Comment by rahulkapoor83** [comment]
I had a production release so I had to degrade Salesforce CLI to a lower version. Not planning to upgrade it back now.
