### ISSUE TITLE
sfdx info:releasenotes:display not working behind a proxy (on WSL)

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#1378]
### Summary

When running in my corporate network, I am unable to launch the new `info:releasenotes:display` command

### Steps To Reproduce:

1.  Connect to a corporate network
1.  Configure proxy (env variable HTTP_PROXY)
1. Run `sfdx info:releasenotes:display `

### Expected result

Correct result

### Actual result

```bash
sfdx info:releasenotes:display
ERROR running info:releasenotes:display:  connect ECONNREFUSED 185.199.109.133:443
```

### System Information

```json
{
        "cliVersion": "sfdx-cli/7.135.0",
        "architecture": "wsl-x64",
        "nodeVersion": "node-v16.13.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/analytics 1.0.1",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.15 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.1 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.7.5 (core)",
                "schema 1.1.0 (core)",
                "sfciutils 1.2.2",
                "sfdx-cli 7.135.0 (core)",
                "sfdx-codescan-plugin 1.0.7",
                "sfpowerkit 3.2.2",
                "source 1.5.3 (1.5.3)",
                "telemetry 1.4.0 (core)",
                "templates 53.1.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Linux 5.4.72-microsoft-standard-WSL2"
}
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by mshanemc** [comment]
Yep...we'll have to fix that.

Thanks for reporting!

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10493241](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000iqJjbYAE/view)

**Comment by mnunezdm** [comment]
Hi

After updating to the latest-rc

```shell
$ sfdx --version && sfdx info:releasenotes:display
sfdx-cli/7.138.0 wsl-x64 node-v16.13.0
ERROR running info:releasenotes:display:  Socket is closed
```

**Comment by iowillhoit** [comment]
Hey @mnunezdm, sorry I missed your new comment. Could you confirm you are setting both `HTTP_PROXY` and `HTTPS_PROXY`? Also we just released a new RC today, could you try that as well? Thanks

**Comment by mnunezdm** [comment]
Hello @iowillhoit !!

I have both env variables configured

```bash
$ echo $HTTPS_PROXY && echo $HTTP_PROXY && sfdx info:releasenotes:display
http://****
http://****
ERROR running info:releasenotes:display:  Socket is closed
```

**Comment by iowillhoit** [comment]
Cool, thanks for checking @mnunezdm. Have you had proxy issues with any other commands?

**Comment by iowillhoit** [comment]
I also wonder if this could have something to do with WSL. Could you try installing `sfdx` and running the command in CommandPrompt and seeing if you have the same issue?

**Comment by mnunezdm** [comment]
@iowillhoit 

I normally use sfdx + wsl + proxy with no problem, just this command I think.

I will try to check other commands and I reach you back.

Also, I'm installing sfdx in windows.

**Comment by mnunezdm** [comment]
I have tried with no proxy issues the following commands

```
sfdx force:source:deploy/retrieve
sfdx force:mdapi:deploy/retrieve
sfdx force:source:deploy:report
sfdx force:user:display
sfdx force:schema:sobject:list
sfdx force:schema:sobject:describe -s WorkOrder
sfdx force:apex:execute -f ./test.apex
sfdx force:limits:api:display
sfdx force:user:display
sfdx force:user:permset:assign
```

**Comment by iowillhoit** [comment]
@mnunezdm were you able to try this in CommandPrompt?

**Comment by mnunezdm** [comment]
# Windows

Running in windows without VPN (I assusme this is a problem with the antivirus) (normally disabling ssl verification allows me to fetch this, i assume it is impossible right now to do this in sfdx)

```shell
$ sfdx --version ; sfdx info:releasenotes:display
sfdx-cli/7.138.1 win32-x64 node-v16.14.0
ERROR running info:releasenotes:display:  unable to get local issuer certificate
```

Running in Windows with VPN & HTTP_PROXY & HTTPS_PROXY configured

```shell
$ sfdx --version ; sfdx info:releasenotes:display
sfdx-cli/7.138.1 win32-x64 node-v16.14.0
ERROR running info:releasenotes:display:  Client network socket disconnected before secure TLS connection was established
```

Running in Windows with VPN & just HTTP_PROXY configured

```
$ sfdx --version ; sfdx info:releasenotes:display
sfdx-cli/7.138.1 win32-x64 node-v16.14.0
ERROR running info:releasenotes:display:  Timeout awaiting 'request' for 3000ms
```

# WSL

Running in WSL without VPN (I assusme this is a problem with the antivirus) (normally disabling ssl verification allows me to fetch this, i assume it is impossible right now to do this in sfdx)

```shell
sfdx --version && sfdx info:releasenotes:display
sfdx-cli/7.139.0 wsl-x64 node-v16.13.0
ERROR running info:releasenotes:display:  unable to get local issuer certificate
```

Running in WSL with VPN & HTTP_PROXY & HTTPS_PROXY configured

```shell
$ sfdx --version && sfdx info:releasenotes:display
sfdx-cli/7.139.0 wsl-x64 node-v16.13.0
ERROR running info:releasenotes:display:  Socket is closed
```

Running in WSL with VPN & just HTTP_PROXY configured

```
$ sfdx info:releasenotes:display
ERROR running info:releasenotes:display:  Socket is closed
```

**Comment by mshanemc** [comment]
we shipped this Feb 2022 (adding proxy support for these callouts) so it should be working now unless something is weird with WSL (which is technically unsupported).

https://github.com/salesforcecli/plugin-info/pull/75
