### ISSUE TITLE
force:source:retrieve doesn't include Custom object's standard fields

### ISSUE THREAD

**Issue by mateuszzw** [forcedotcom/cli#1381]
### Summary

I believe this is a bug - while trying to retrieve Custom Object via CLI, standard fields are not included. I tried both with package.xml and specifying Custom objects name with 
```bash
sfdx force:source:retrieve -m CustomObject:
```
as well as with specifying the field I want to retrieve
```bash
sfdx force:source:retrieve -m CustomField:
```

### Steps To Reproduce:

1.  Run any of the aforementioned retrieve commands on the target org, specifying a custom object

### Expected result

Custom fields are retrieved along the custom ones.

### Actual result

Only custom fields are retrieved.

### System Information

```json
{
        "cliVersion": "sfdx-cli/7.134.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/lwc-dev-server 2.10.0",
                "├─ @oclif/plugin-help 3.3.1",
                "└─ @oclif/plugin-update 1.3.10",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.14 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.1 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.7.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.134.0 (core)",
                "sfdx-git-delta 4.2.0",
                "source 1.8.0 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.1.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Darwin 21.2.0"
}
```
### Additional information

_Feel free to attach a screenshot_.

**Comment by shetzel** [comment]
Do you have reproducible steps?  This seems to be working as designed with our sample projects (ebikes-lwc and dreamhouse-lwc)
Please note the docs relevant to this: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm

**Comment by mateuszzw** [comment]
Hi,
The scenario I'd like to present is following:
1. Edit Owner field help text on a Custom Object
2. Retrieve Owner field via sfdx CLI

Neither do I have any issues with retrieving standard fields on standard objects nor with the REST API or the workbench (REST API, describe). Is it a limitation of the sfdx CLI or metadata api?

**Comment by shetzel** [comment]
Thanks for the repro.  I understand what you're saying now.  I suspect it's not possible via the Metadata API but I've asked that team for clarity.  I'll post here with the response.

**Comment by shetzel** [comment]
@mateuszzw - unfortunately I couldn't get any clarity from the owning team.  Can you please open a support case and have them direct the case to the Custom Schema team?

**Comment by fracarma** [comment]
@mateuszzw Have you found a workaround? I have the same issue.

**Comment by pgonzaleznetwork** [comment]
You should be able to retrieve the standard field using sfdx force source retrieve -m customfield:standardfieldname

Did you try this?
