### ISSUE TITLE
`sfdx force:source:convert` produces invalid Metadata API source when object translations are present

### ISSUE THREAD

**Issue by davidmreed** [forcedotcom/cli#1383]
### Summary

When recent versions of SFDX execute `force:source:convert` in the presence of object and/or field translations, invalid Metadata API source is produced. The Metadata API source directory includes a spurious `fields` subdirectory which contains only `*.fieldTranslation` files.

### Steps To Reproduce:

[**Repository to reproduce:** [EDA](https://github.com/SalesforceFoundation/EDA)
]

1. Check out the EDA repository linked above
1. Execute `sfdx force:source:convert`.
1. Inspect the generated MDAPI directory. Note the presence of the `fields` subdirectory.

Optionally, update to `sfdx-cli@7.123`, remove the generated directory, and re-run the same command. Observe that the `fields` subdirectory is not present.

We do not know which version introduced this issue, only that it is after 7.123 and before or equal to 7.130.

### Expected result

Valid MDAPI source is generated.

### Actual result

Invalid MDAPI source is generated.

### System Information

Note that this is an example of one impacted version but is not the only impacted version, and the latest 7.135 exhibits the same behavior.

```
{
	"cliVersion": "sfdx-cli/7.130.1",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v17.4.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"@salesforce/sfdx-scanner 2.12.0",
		"alias 1.2.0 (core)",
		"apex 0.4.0 (core)",
		"auth 1.8.0 (core)",
		"config 1.3.0 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.6 (core)",
		"generator 1.2.1 (core)",
		"info 1.1.2 (core)",
		"limits 1.3.0 (core)",
		"org 1.11.0 (core)",
		"salesforce-alm 53.6.0 (core)",
		"schema 1.1.0 (core)",
		"sfdx-cli 7.130.1 (core)",
		"source 1.6.2 (core)",
		"telemetry 1.4.0 (core)",
		"templates 52.6.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.0 (core)"
	],
	"osVersion": "Darwin 19.6.0"
}
```

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10501883](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000jF8ZeYAK/view)
