### ISSUE TITLE
Add a possibility for a opening a visualforce page (preview) directly from sfdx

### ISSUE THREAD

**Issue by fodilo** [forcedotcom/cli#1386]
**What are you trying to do**
- I want to have a command for previewing a visualforce page directly from sfdx.
for example having this command : 
```sfdx force:source:open -f path/to/myvfpage --visualforce```
the result will preview directly a visualforce page on the browser in the next url :
```https:myorg:/apex/myvfpage```

**Describe the solution you'd like**
- Modify the already existed command with adding a flag (--visualforce) and the path should be pointed to a visualforce page.

**Additional context**
- for future use it could be used directly from VS code visualforce extension.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10514651](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000jzDmRYAU/view)

**Comment by mshanemc** [comment]
I haven't heard that request before.  The code for the source:open command is [here](https://github.com/salesforcecli/plugin-source/blob/main/src/commands/force/source/open.ts) (it only does flexipages today, but you could add vf). 

You'll see it's checking the type from the filepath, so you wouldn't need to specify `--visualforce` 

Alternatively, `sfdx force:org:open -p apex/myvfpage` gets you pretty close.

**Comment by iowillhoit** [comment]
This has been released in the latest (stable) release!
