### ISSUE TITLE
maxRevision.json requires manual updating after adding sandbox

### ISSUE THREAD

**Issue by leahkennedy** [forcedotcom/cli#1387]
I'm needing to manually update the maxRevision.json file for sandbox orgs prior to being able to retrieve metadata. It looks like it's a deleted or renamed BigObject that is causing the issue. How can we get this to stop showing up in the maxRevision file?

Error Message
`ERROR running force:source:pull:  Cannot retrieve translation for object:Omnii_Campaig`

Snippets from maxRevision.json that needs to be removed
`     "CustomObjectTranslation__Omnii_Campaig-en_US": {
      "serverRevisionCounter": 6713,
      "lastRetrievedFromServer": null,
      "memberType": "CustomObjectTranslation",
      "isNameObsolete": false
    },`

**Comment by mshanemc** [comment]
what does `after adding sandbox` mean?

Also, can you try this with `sfdx force:source:beta:pull` ?  We're planning to switch those commands over in the next couple of weeks and it would be helpful to know if it works (we're not likely to fix it in the current `pull` command)

**Comment by leahkennedy** [comment]
@mshanemc "after adding sandbox" means connecting to a source tracking enabled sandbox org
and using the beta command seems to fix the issue! I use -f and`sfdx force:source:beta:pull -f` will pull changes and show me a warning about the failed metadata, whereas the standard command fails with the error. Marking this as closed.
