### ISSUE TITLE
Salesforce retrieval through generated package.xml retrieves part of the file

### ISSUE THREAD

**Issue by cbsp101** [forcedotcom/cli#139]
On VSCode, when tried to retrieve profiles from a salesforce org, 2 issues are encountered:

Issue 1: when retrieved the profiles via sfdx Package.xml generator:Choose metadata components around 300+ lines of the file were missing from the retrieved file

Issue 2: The sequence of code lines are changed while retrieve from Salesforce sandbox

**Comment by mshanemc** [comment]
Is this still happening since we changed the `force:source` commands?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10054326](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000HiqQyYAJ/view)
