### ISSUE TITLE
force:org:create:  A fatal signup error occurred.

### ISSUE THREAD

**Issue by patrykacc** [forcedotcom/cli#1390]
### Summary
It started to happen today, during scratch org creation I am receiving the following error which is a blocker for our development process, take a look pls with urgency, thanks.

### Steps To Reproduce:

After successful authentication using JWT - sfdx force:auth:jwt:grant
My CI/CD process tries to create scratch org:   sfdx force:org:create

### Expected result

scratch org should have been created successfully.

### Actual result

The following error is displayed:

ERROR running force:org:create: A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance.
Try this:
See https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_signuprequest.htm for information on error code C-9999.

### System Information

SFDX version:
sfdx-cli/7.136.2-860c1a0 linux-x64 node-v12.18.3

**Comment by mshanemc** [comment]
@patrykacc can you share a few things: 
1. the full output of `sfdx version --verbose` so we can check plugin versions
2. the scratch def file
