### ISSUE TITLE
Sandbox force:org:create should have a fully async option

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#1391]
**Is your feature request related to a problem? Please describe.**
I can't kick start sandbox creation without having to wait for an arbitrary minimum timeout.

**What are you trying to do**
I'm working on kicking off developer sandbox creation at the end of a production org deployment, so that we have sandboxes in a clean state for the next round of feature development.

**Describe the solution you'd like**
sfdx force:org:create --nowait (or something of that nature) returns immediately

**Describe alternatives you've considered**
A custom plugin replicating the sandbox creation code, but without the polling.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10542398](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000lKX81YAG/view)

**Comment by cristiand391** [comment]
Hey, sorry for the late reply.

Last year we shipped a new command in the `sf` cli that supports async sandbox creation, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_env_commands_unified.htm#cli_reference_env_create_sandbox_unified
