### ISSUE TITLE
Profile Extraction

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#1396]
### Summary

When modifying a profile (e.g the description) and using the force:source:pull command the profile is stripped of vital information

### Steps To Reproduce:

1.  Use an existing profile that is in source control that has full information (FLS, Layouts, etc) ideally one that is really large (100k+ lines)
1.  Ensure package.xml is update with customObject and profile (see script)
1.  Open sandbox
1.  Modify the description of the profile
1.  sfdx force:source:pull

script:
file_out="manifest/package.xml"
api_version="53.0"
sbx="mySandbox"
echo '<?xml version="1.0" encoding="UTF-8" ?>' > $file_out
echo '<Package xmlns="http://soap.sforce.com/2006/04/metadata">' >> $file_out
echo '   <types>' >> $file_out
while IFS=$',' read -r -A arry
do
echo '       <members>'${arry[1]}'</members>' >> $file_out
done < <(sfdx force:mdapi:listmetadata -m CustomObject --json -u $sbx | jq -r '.result|sort_by(.fullName)|.[].fullName')
echo '       <name>CustomObject</name>' >> $file_out
echo '    </types>' >> $file_out
echo '    <types>' >> $file_out
echo '        <members>*</members>' >> $file_out
echo '        <name>Profile</name>' >> $file_out
echo '    </types>' >> $file_out
echo '<version>'$api_version'</version>' >> $file_out
echo '</Package>' >> $file_out

### Expected result

The profile should get extracted with all existing information (FLS, Layouts, etc) as it does using the command: sfdx force:source:retrieve -x manifest/package.xml

### Actual result

The profile contains only basic information (userPermissions, classAccesses, loginIpRanges and description). Any existing information regarding FLS, Layout, Record Types, etc was removed.

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- {
	"cliVersion": "sfdx-cli/7.137.1",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.13.2",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 1.2.0",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 1.2.1 (core)",
		"apex 0.8.0 (core)",
		"auth 1.8.1 (core)",
		"config 1.3.19 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.8 (core)",
		"generator 1.2.2 (core)",
		"info 1.2.0 (core)",
		"limits 1.3.0 (core)",
		"org 1.11.1 (core)",
		"salesforce-alm 53.9.0 (core)",
		"schema 1.1.0 (core)",
		"sfdx-cli 7.137.1 (core)",
		"sfdx-git-delta 4.12.1",
		"source 1.8.11 (core)",
		"telemetry 1.4.0 (core)",
		"templates 53.5.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.1 (core)"
	],
	"osVersion": "Darwin 21.3.0"
}

### Additional information

Case #41733470

**Comment by mshanemc** [comment]
That's an unfixable problem with the way the underlying metadata API handles profiles, see https://developer.salesforce.com/docs/atlas.en-us.210.0.api_meta.meta/api_meta/meta_profile.htm.

In summary, it only includes parts of the profile that are also in your retrieve operation.

So if you do a retrieve of the full manifest, it's retrieving all your object/fields and classes, so the Profile contains object/field and class info.

During a pull, the CLI only retrieves what's changed (the Profile) but not all the other stuff, so then the Profile doesn't contain that info.

**Comment by ghost** [comment]
Currently when I do a full extra to pull out a profile it takes about 20 minutes. And because it pulls out so many files I have to do it in a directory that doesn't have Git initialized or my Git extension in VS Code bugs out.

And if the source pull only pulls out the changes, then it's still a painful process of copying back the removed parts to reassemble the profile back to completeness.

It would seem that if a profile was broken down into smaller parts that might be a more manageable solution. We have dozens of profiles that are over 130k+ lines worth of information. So removing unnecessary information, splitting it into parts or just having a process to extract the full profile without extracting all the other information would be greatly appreciated.

This profile weirdness seems to be an achilles heel to source tracking.

**Comment by mshanemc** [comment]
We're looking at some options, but it's gonna be a while if any of them even work.

**Comment by ghost** [comment]
Ok. We will continue using the customObjects + profiles extraction process for now. Thanks for confirming.
