### ISSUE TITLE
sfdx force:org:create command fails with error The requested resource does not exist

### ISSUE THREAD

**Issue by ar-srinivas** [forcedotcom/cli#1397]
sfdx force:org:create command fails with error The requested resource does not exist

sfdx version:
sfdx-cli/7.136.2 win32-x64 node-v16.13.2

sfdx plugins:
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 1.2.0 (core)
apex 0.8.0 (core)
auth 1.8.1 (core)
config 1.3.15 (core)
custom-metadata 1.0.12 (core)
data 0.6.8 (core)
generator 1.2.1 (core)
info 1.2.0 (core)
limits 1.3.0 (core)
org 1.11.1 (core)
salesforce-alm 53.7.6 (core)
schema 1.1.0 (core)
sfdx-cli 7.136.2 (core)
source 1.8.9 (core)
telemetry 1.4.0 (core)
templates 53.3.0 (core)
trust 1.1.0 (core)
user 1.7.0 (core)

Command:
sfdx force:org:create -a dxclifeb9 -v <xxx> -d 7 edition=Developer --apiversion=53.0 --json

Error:
{
  "status": 1,
  "name": "NOT_FOUND",
  "message": "The requested resource does not exist",
  "exitCode": 1,
  "commandName": "OrgCreateCommand",
  "stack": "NOT_FOUND: The requested resource does not exist\n    at HttpApi.getError (C:\\Program Files\\sfdx\\client\\node_modules\\jsforce\\lib\\http-api.js:250:13)\n    at C:\\Program Files\\sfdx\\client\\node_modules\\jsforce\\lib\\http-api.js:95:22\n    at tryCallOne (C:\\Program Files\\sfdx\\client\\node_modules\\promise\\lib\\core.js:37:12)\n    at C:\\Program Files\\sfdx\\client\\node_modules\\promise\\lib\\core.js:123:15\n    at flush (C:\\Program Files\\sfdx\\client\\node_modules\\asap\\raw.js:50:29)\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)\nOuter stack:\n    at Function.wrap (C:\\Program Files\\sfdx\\client\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\n    at OrgCreateCommand.catch (C:\\Program Files\\sfdx\\client\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:248:67)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async OrgCreateCommand._run (C:\\Program Files\\sfdx\\client\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:85:13)\n    at async Config.runCommand (C:\\Program Files\\sfdx\\client\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async SfdxMain.run (C:\\Program Files\\sfdx\\client\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async SfdxMain._run (C:\\Program Files\\sfdx\\client\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Program Files\\sfdx\\client\\dist\\cli.js:162:47)",
  "warnings": [
    "apiVersion configuration overridden at \"53.0\""
  ]
}

**Comment by mshanemc** [comment]
That's usually a sign that either
1. you're not hitting a DevHub (`sfdx config:list` will show you what your `defaultdevhubusername` is on that project.  Alternatively, add `-v` to use a known, good, permissioned devHub)
2. you are hitting a DevHub, but don't have permissions to create scratch orgs (check that)

**Comment by ar-srinivas** [comment]
Thank you for the response!
I have enabled the devhub and I am able to create the scratch orgs with 7.129 version and the same is failing with 7.134 and 7.136 versions.
**To my surprise, though the command is giving an error response scratch orgs being created in the dev hub and  can see the list in Active Scratch Orgs in devhub.**

**One more observation is, with 7.136 version when we pass the clientid parameter in the command it is giving a success response but this prompting for client secrete which is not possible to provide in the automation. Clientid is not a required parameter in the create:org command**

**Comment by cristiand391** [comment]
Hey @ar-srinivas, sorry for the delayed response, are you still experiencing this issue?

If so, could you try updating to latest `sfdx` and use the `force:org:beta:create` command to see if it's fixed there? This beta command will replace the current `org:create` in future releases.

**Comment by sairabit** [comment]
![image](https://user-images.githubusercontent.com/39585096/170424700-2763860b-6533-4e7c-88af-f60458424425.png)
This still exist even in beta commands
