### ISSUE TITLE
*.profile-meta.xml files are not pulled after object deletion

### ISSUE THREAD

**Issue by sauloefo** [forcedotcom/cli#14]
### Summary

After custom object deletions in a scratch org, files related to profile are not updated by `sfdx force:source:pull` command.

### Steps To Reproduce:

1.  Create a new scratch org.
1.  Open the new scratch org.
1.  Create a new Custom Object.
1.  Retrieve modified metadata with `sfdx force:source:pull`
1.  Verify the profile files are referencing, for instance, the new custom object layouts.
1.  In the scratch org, delete the created Custom Object
1.  Retrieve the metadata using `sfdx force:source:pull` again

### Expected result

The *.profile-meta.xml files doesn't contain any reference to deleted custom object assets.

### Actual result

The *.profile-meta.xml files keeps references to deleted custom object assets. This will cause failure to any upcoming `sfdx force:source:push` execution.

### Additional information

Created Object:
<img width="1671" alt="screenshot 2019-01-27 at 3 00 29 p m" src="https://user-images.githubusercontent.com/5004899/51802866-12cd2480-2246-11e9-9824-05f0ad8980df.png">

Retrieved metadata using `sfdx force:source:pull`
<img width="1667" alt="screenshot 2019-01-27 at 3 01 27 p m" src="https://user-images.githubusercontent.com/5004899/51802867-22e50400-2246-11e9-8679-0e726b05a7fe.png">

Retrieved metadata after custom object deletion.
<img width="1402" alt="screenshot 2019-01-27 at 3 02 55 p m" src="https://user-images.githubusercontent.com/5004899/51802879-3c864b80-2246-11e9-990e-dc47fcdf38ac.png">

Content of profile-meta.xml files after custom object deletion and pulling of scratch org source code. 
<img width="339" alt="screenshot 2019-01-27 at 3 06 09 p m" src="https://user-images.githubusercontent.com/5004899/51802886-4f991b80-2246-11e9-865e-43f8b85dbb3f.png">

ERROR: result of `sfdx force:source:push -f` into a new scratch org with the last pulled source code version:
<img width="1676" alt="screenshot 2019-01-27 at 3 10 59 p m" src="https://user-images.githubusercontent.com/5004899/51802900-7ce5c980-2246-11e9-9157-1599e5d780b4.png">

**SFDX CLI Version**: sfdx-cli/6.50.0-9817aece8a (darwin-x64) node-v8.9.4

**OS and version**: darwin18 (MacOS Mojave)

**Comment by clairebianchi** [comment]
@sauloefo thank you for the feedback, we are aware of the issue and are planning to fix it in Summer '19, our internal work item is W-5234377. I will leave this bug open till we have made the change

**Comment by sauloefo** [comment]
> @sauloefo thank you for the feedback, we are aware of the issue and are planning to fix it in Summer '19, our internal work item is W-5234377. I will leave this bug open till we have made the change

Hi Claire! Great to know it will be solved soon! If you believe this would be good for a first issue collaboration please let know. I'd be glad to help solve it.

**Comment by clairebianchi** [comment]
@sauloefo Thank you for the offer, but sadly this part of our codebase is not currently public.

**Comment by mshanemc** [comment]
Follow-up note--this isn't a problem with the pull command.  It's a problem with SourceMembers for the profile not getting updated when the Object is deleted.  

So that profile change from the deleted object won't show up in `status` and there's nothing on the server to `pull`.

And that's not going to be something the CLI team can fix.  Created @W-10287607@ to get the server issues corrected.

```
➜  gh14 sfdx force:data:soql:query -t -q "select id, IsNameObsolete, MemberIdOrName, MemberName, MemberType, RevisionCounter from SourceMember"
ID                  ISNAMEOBSOLETE  MEMBERIDORNAME      MEMBERNAME           MEMBERTYPE    REVISIONCOUNTER
──────────────────  ──────────────  ──────────────────  ───────────────────  ────────────  ───────────────
0MZ0t00000PDzXZGA1  false           00e0t000000wnnnAAA  Admin                Profile       1
0MZ0t00000PDzXaGAL  true            00h0t000003gbMwAAI  Test__c-Test Layout  Layout        5
0MZ0t00000PDzXbGAL  true            01I0t000001qkK6EAI  Test__c              CustomObject  4
Total number of records retrieved: 3.
Querying Data... done
```

**Comment by RupertBarrow** [comment]
Hi @mshanemc , this bug is pretty frightening, especially since the issue is still open more than 1 year after you found the cause. When can we hope this to be fixed ?

**Comment by mshanemc** [comment]
I don't expect this one to get fixed.  The more cases, the better chance.

**Comment by RupertBarrow** [comment]
Disappointing.
You should probably close this issue and mark it "Wont Fix".

**Comment by mshanemc** [comment]
If I close it here, it closes it in GUS (the internal tracking system) so I won't.  Also, eternal optimist and all that.

**Comment by iowillhoit** [comment]
@RupertBarrow @sauloefo, unfortunately the linked issue was "nevered" as a "Bug without a Case" by the owning team. The best way for this to get fixed is to open a Support Case and link back to this Github Issue and also "W-10287607". 
Closing this issue here.
