### ISSUE TITLE
sfdx force:source:retrieve --manifest throws fileName of undefined in MAC

### ISSUE THREAD

**Issue by rkathir** [forcedotcom/cli#140]
### Summary
Installed SFDX CLI in mac
Created SF project in VS Code
Authorized against sandbox
Wants to download existing metadata from Org, keep getting this error..

sfdx force:source:retrieve --manifest .manifest/package.xml 
ERROR running force:source:retrieve:  Cannot read property 'fileName' of undefined

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:

**Comment by rkathir** [comment]
sfdx version
sfdx-cli/7.8.1-8f830784cc darwin-x64 node-v10.15.3

**Comment by rkathir** [comment]
$ sfdx plugins --core
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.16.0 (core)
├─ force-language-services 45.12.0 (core)
└─ salesforce-alm 45.18.0 (core)

sfdx-cli 7.8.1 (core)

**Comment by rkathir** [comment]
Any update to this issue?

**Comment by tnoonan-salesforce** [comment]
Can you add --dev--debug? Include the stack trace?

**Comment by rkathir** [comment]
It is related to https://github.com/forcedotcom/cli/issues/39

If I remove AuraDefinitionBundle then works fine..

**Comment by rkathir** [comment]
is it fixed now with last night release?

**Comment by clairebianchi** [comment]
I think the bug fix we pushed will not fix this issue. can you please run with --dev --debug and we can look more into this issue?
