### ISSUE TITLE
Minor:  Misleading Release Notes text on Package Ancestor

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#1405]
### Summary

Misleading text in the 7.137.2 release notes imply that all packages require an ancestor, when only 2GP Managed Packages require it.

### Steps To Reproduce:

View the Release Notes here: [7.137.2 (Feb 10, 2022) [stable]](https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71372-feb-10-2022-stable)

Note the text:
> NEW: You're now required to set a package ancestor when you create a package version. To make it easier to increment your package ancestor version number, we added two keywords to the `packageDirectories section` of the `sfdx-project.json` file. We also added a parameter to the `force:package:version:create` command to override this requirement: `--skipancestorcheck`. Get all the details [here](https://help.salesforce.com/s/articleView?id=release-notes.rn_packaging_ancestor_enhancements.htm&type=5&release=236) and [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_config_ancestors.htm).

### Expected result

This implies that all package versions (including unlocked packages) carry this new requirement.  The linked documents clarify that only 2GP managed packages actually require package ancestor

### Actual result

I misunderstood 😁

**Comment by iowillhoit** [comment]
Hey Jason, thanks for opening an issue for this! I'll look into this and update the Release Notes.

**Comment by jshackell-sfdc** [comment]
Thanks for the feedback!  I made it clear that this is for 2GP packaging. https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71372-feb-10-2022-stable

**Comment by iowillhoit** [comment]
Thanks again Jason, closing the issue 💯
