### ISSUE TITLE
package:version:create requires ancestor on unlocked packages

### ISSUE THREAD

**Issue by jhawk-4** [forcedotcom/cli#1409]
Ancestors are now required for second-generation managed packages.  When attempting to create a new package version on an unlocked package, we are getting the following error

> Can’t create package version. The ancestor version [undefined] you specified isn’t the highest released package version. Set the ancestor version to 1.0.0, and try creating the package version again. You can also specify --skipancestorcheck to override the ancestry requirement.

If you try to set the `ancestorVersion` or `ancestorId` values in the `sfdx-project.json` file, and then run the package version create command again, you are greeted with this error

>Can’t create package version. Specifying an ancestor is available only for second-generation managed packages. Remove the ancestorId or ancestorVersion from your sfdx-project.json file, and then create the package version again.

The only workaround that we were able to do is to use the `--skipancestorcheck` while creating the package version.

Should this be required when developing non-managed packages?

**Comment by iowillhoit** [comment]
Hey @jhawk-4, this is a bug. I am currently working on getting the fix into a new release candidate of the cli. I am going to close this issue and I'll post on https://github.com/forcedotcom/cli/issues/1403 once it's out. Thanks!
