### ISSUE TITLE
Deploy layout to org

### ISSUE THREAD

**Issue by vichpetr** [forcedotcom/cli#141]
Hi,

I have tried to deploy files from folder `layouts` (full path is `force-app/main/default/layouts/Account-Account Layout.layout-meta.xml`). 

The problem is the filename contains space and I get the error: 
**`ERROR running force:source:deploy:  Unexpected argument: Layout.layout-meta.xml`**

The command what I used: 
`sfdx force:source:deploy -p force-app/main/default/layouts/Account-Account Layout.layout-meta.xml -u myOrg`

Thank you for your help.
Petr

**Comment by tnoonan-salesforce** [comment]
Did you try with quotes?

sfdx force:source:deploy -p "force-app/main/default/layouts/Account-Account Layout.layout-meta.xml" -u myOrg
