### ISSUE TITLE
ENNOENT on most commands

### ISSUE THREAD

**Issue by kajkacz-foss** [forcedotcom/cli#1416]
Summary : 
The deploy and retrieve commands keep failing with simmilar error messages: 
`ERROR running force:source:retrieve:  ENOENT: no such file or directory, lstat 'C:\.eslintignore'`

**Comment by iowillhoit** [comment]
@kajkacz-foss what version of the CLI are you using (see below)? Are you having issues with any other commands?

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`

**Comment by kajkacz-foss** [comment]
Heres the output : 
{
        "cliVersion": "sfdx-cli/7.138.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.14.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.1 (core)",
                "apex 0.8.0 (core)",
                "auth 1.8.1 (core)",
                "community 1.1.4 (core)",
                "config 1.3.19 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.9 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.1 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.1 (core)",
                "salesforce-alm 53.10.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.138.1 (core)",
                "source 1.8.11 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.5.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}


It's a new project and I mostly tried the deploy/retireve commands, org commands work without issues, I haven't tried much besides that

**Comment by iowillhoit** [comment]
Thanks @kajkacz-foss, looks like we've [seen this once before](https://github.com/forcedotcom/cli/issues/1292) but unfortunately didn't get a resolution (I've asked for a follow up). I've got a few more questions:

- How did you create this new project? Did you use `sfdx force:project:create`?
- Do you get the same error when you use this sample project: [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc)
- What flags are you passing to your deploy/retrieve commands?
- Did you generate the package.xml with `sfdx force:source:manifest:create`?

**Comment by laszlo-foldi-attentioncrm** [comment]
I'm having the same issue.  When i try to retrieve via the VS Code "Org Browser" feature I get the following error:
13:03:56.323 Starting SFDX: Retrieve Source from Org

ENOENT: no such file or directory, stat 'd:\.eslintignore'

Then I created the file in my D root. After this I got the following error:
13:04:43.340 Starting SFDX: Retrieve Source from Org

ENOENT: no such file or directory, stat 'd:\.forceignore'

It seems like to CLI thinks my project is in my D drive root.

Also I have the following versions:
{
  "cliVersion": "sfdx-cli/7.201.6",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\foldi\\AppData\\Local\\sfdx\\client\\7.201.6-4edd82d",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.2.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 3.0.1 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.14 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.20 (core)",
    "apex 2.2.17 (core)",
    "auth 2.7.15 (core)",
    "community 2.2.11 (core)",
    "custom-metadata 2.1.20 (core)",
    "data 2.3.16 (core)",
    "deploy-retrieve 1.8.20 (core)",
    "info 2.6.10 (core)",
    "limits 2.3.14 (core)",
    "org 2.8.2 (core)",
    "packaging 1.16.11 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.6 (core)",
    "signups 1.4.15 (core)",
    "source 2.10.7 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.13 (core)",
    "trust 2.4.16 (core)",
    "user 2.3.10 (core)",
    "sfdx-cli 7.201.6 (core)"
  ]
}
