### ISSUE TITLE
Building docker images fails

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/cli#1418]
### Summary

Building docker images fails

### Steps To Reproduce:

1.  checkout salesforcecli/sfdx-cli from Github
2.`yarn install`
3. `yarn pack:docker:full`

### Expected result

Should build the docker image with errors

### Actual result

Error message : 
...
8ebe67b91a0b: Waiting
c3bc0ba3a03b: Waiting
denied: requested access to the resource is denied
/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/common.js:110
  if (config.fatal) throw new Error(logEntry);
                          ^

Error: exec: denied: requested access to the resource is denied

    at Object.error (/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/common.js:110:27)
    at execSync (/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/exec.js:120:12)
    at Object._exec (/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/exec.js:223:12)
    at Object.exec (/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/common.js:335:23)
    at /Users/rupert/Downloads/sfdx-cli-main/scripts/docker-publish-full.js:36:9
error Command failed with exit code 1.

### System Information

% sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.138.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.14.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.1 (core)",
                "apex 0.8.0 (core)",
                "auth 1.8.1 (core)",
                "community 1.1.4",
                "config 1.3.19 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.9 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.1 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.1 (core)",
                "salesforce-alm 53.10.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.138.1 (core)",
                "shane-sfdx-plugins 4.43.0",
                "├─ @mshanemc/plugin-streaming 1.1.7",
                "└─ @mshanemc/sfdx-sosl 1.1.0",
                "source 1.8.11 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.5.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Darwin 20.6.0"
}

### Additional information

This error is already present when building the docker images in the https://github.com/forcedotcom/salesforcedx-docker recently deprecated repository.

Here is the full error log : 
% yarn pack:docker:full
yarn run v1.22.17
$ ./scripts/docker-publish-full.js
Using Salesforce CLI Version 7.139.0
#1 [internal] load build definition from Dockerfile_full
#1 sha256:71c79b122a40763e7a04a40cf7202fe81b51c28682b89b20740aa07419efa5a6
#1 transferring dockerfile: 1.10kB 0.0s done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:1b44ebec6bb399d29c059bf9195db44a675260e92b8d497cf04198bdab027453
#2 transferring context: 259B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/heroku/heroku:18
#3 sha256:35a47f6138a01d2192d767832c1075231b6df2f6610b9ca68d8b4602ef23fdfe
#3 ...

#4 [auth] heroku/heroku:pull token for registry-1.docker.io
#4 sha256:69951e98d07738825b98d3e9a448955c173e2b10eff199cedfe1f47bff07f009
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/heroku/heroku:18
#3 sha256:35a47f6138a01d2192d767832c1075231b6df2f6610b9ca68d8b4602ef23fdfe
#3 DONE 2.3s

#11 [1/7] FROM docker.io/heroku/heroku:18@sha256:5b66d2704e0994e6b30275b2c7899d71d1f78cd8c8447fdf8d905e779117d5e2
#11 sha256:6f15393c5f2433d870b749b38671ac8b9bc00309c290344fe1cc3666c67c07e9
#11 CACHED

#5 [2/7] RUN echo 'a0f23911d5d9c371e95ad19e4e538d19bffc0965700f187840eb39a91b0c3fb0  ./nodejs.tar.gz' > node-file-lock.sha   && curl -s -o nodejs.tar.gz https://nodejs.org/dist/v16.13.2/node-v16.13.2-linux-x64.tar.gz   && shasum --check node-file-lock.sha
#5 sha256:9e870548b3be2fdfbbc70c3a6c8824c68de1280decd59d68ed8fccf508a0f71f
#5 29.70 ./nodejs.tar.gz: OK
#5 DONE 29.7s

#6 [3/7] RUN mkdir /usr/local/lib/nodejs   && tar xf nodejs.tar.gz -C /usr/local/lib/nodejs/ --strip-components 1   && rm nodejs.tar.gz node-file-lock.sha
#6 sha256:73fdf50565bc09e9ec4435f0050661e43c2fb01ec40f2aea4a5de6c7119374cc
#6 DONE 2.0s

#7 [4/7] RUN npm install --global sfdx-cli@7.139.0 --ignore-scripts
#7 sha256:063bb413b6b894c694be157a2bfedb88591da35cb43b52e5ce85d78b629c4481
#7 314.0 npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
#7 314.8 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
#7 315.0 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
#7 317.0 npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
#7 319.6 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#7 323.4 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#7 351.9 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#7 352.4 npm WARN deprecated cli-ux@5.6.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#7 352.5 npm WARN deprecated cli-ux@5.6.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#7 353.1 npm WARN deprecated cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#7 353.3 npm WARN deprecated cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#7 353.3 npm WARN deprecated cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#7 353.4 npm WARN deprecated cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#7 353.4 npm WARN deprecated cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
#7 378.9 
#7 378.9 added 1316 packages, and audited 1574 packages in 6m
#7 378.9 
#7 378.9 66 packages are looking for funding
#7 378.9   run `npm fund` for details
#7 379.0 
#7 379.0 51 vulnerabilities (17 moderate, 34 high)
#7 379.0 
#7 379.0 To address issues that do not require attention, run:
#7 379.0   npm audit fix
#7 379.0 
#7 379.0 To address all issues possible (including breaking changes), run:
#7 379.0   npm audit fix --force
#7 379.0 
#7 379.0 Some issues need review, and may require choosing
#7 379.0 a different dependency.
#7 379.0 
#7 379.0 Run `npm audit` for details.
#7 379.0 npm notice 
#7 379.0 npm notice New minor version of npm available! 8.1.2 -> 8.5.1
#7 379.0 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.1>
#7 379.0 npm notice Run `npm install -g npm@8.5.1` to update!
#7 379.0 npm notice 
#7 DONE 379.4s

#8 [5/7] RUN npm install --global @salesforce/cli@latest-rc
#8 sha256:2dcbb354921ceba785ba8ae6db41aba2336f5da308d87c1f224ff98c403ce1c0
#8 141.7 
#8 141.7 added 1199 packages, and audited 1200 packages in 2m
#8 141.7 
#8 141.7 86 packages are looking for funding
#8 141.7   run `npm fund` for details
#8 141.8 
#8 141.8 52 vulnerabilities (14 moderate, 38 high)
#8 141.8 
#8 141.8 To address issues that do not require attention, run:
#8 141.8   npm audit fix
#8 141.8 
#8 141.8 Some issues need review, and may require choosing
#8 141.8 a different dependency.
#8 141.8 
#8 141.8 Run `npm audit` for details.
#8 DONE 142.2s

#9 [6/7] RUN apt-get update && apt-get install --assume-yes openjdk-11-jdk-headless jq
#9 sha256:b230fd21790ad2de86078bd22f8b0efb4e84f3b1a1da75885776b46ffac2ab78
#9 1.154 Get:1 http://apt.postgresql.org/pub/repos/apt bionic-pgdg InRelease [110 kB]
#9 1.163 Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
#9 1.510 Get:3 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
#9 1.719 Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
#9 1.819 Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
#9 2.051 Get:6 http://apt.postgresql.org/pub/repos/apt bionic-pgdg/main amd64 Packages [417 kB]
#9 3.057 Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
#9 10.07 Get:8 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2596 kB]
#9 11.61 Get:9 http://archive.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1474 kB]
#9 12.33 Get:10 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2252 kB]
#9 13.62 Get:11 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3035 kB]
#9 17.00 Fetched 23.0 MB in 16s (1404 kB/s)
#9 17.00 Reading package lists...
#9 19.19 Reading package lists...
#9 21.07 Building dependency tree...
#9 21.48 Reading state information...
#9 21.86 The following additional packages will be installed:
#9 21.86   ca-certificates-java java-common libasound2 libasound2-data libjq1 libnspr4
#9 21.86   libnss3 libpcsclite1 openjdk-11-jre-headless
#9 21.87 Suggested packages:
#9 21.87   default-jre libasound2-plugins alsa-utils pcscd openjdk-11-demo
#9 21.87   openjdk-11-source libnss-mdns fonts-dejavu-extra fonts-ipafont-gothic
#9 21.87   fonts-ipafont-mincho fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic
#9 21.98 The following NEW packages will be installed:
#9 21.98   ca-certificates-java java-common jq libasound2 libasound2-data libjq1
#9 21.99   libnspr4 libnss3 libpcsclite1 openjdk-11-jdk-headless
#9 21.99   openjdk-11-jre-headless
#9 22.11 0 upgraded, 11 newly installed, 0 to remove and 6 not upgraded.
#9 22.11 Need to get 260 MB of archives.
#9 22.11 After this operation, 407 MB of additional disk space will be used.
#9 22.11 Get:1 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 java-common all 0.68ubuntu1~18.04.1 [14.5 kB]
#9 22.20 Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 libnspr4 amd64 2:4.18-1ubuntu1 [112 kB]
#9 22.30 Get:3 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 libnss3 amd64 2:3.35-2ubuntu2.13 [1220 kB]
#9 23.03 Get:4 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libasound2-data all 1.1.3-5ubuntu0.6 [38.5 kB]
#9 23.05 Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libasound2 amd64 1.1.3-5ubuntu0.6 [360 kB]
#9 23.34 Get:6 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpcsclite1 amd64 1.8.23-1 [21.3 kB]
#9 23.34 Get:7 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 openjdk-11-jre-headless amd64 11.0.13+8-0ubuntu1~18.04 [37.2 MB]
#9 47.78 Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 ca-certificates-java all 20180516ubuntu1~18.04.1 [12.2 kB]
#9 47.78 Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libjq1 amd64 1.5+dfsg-2 [111 kB]
#9 47.78 Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 jq amd64 1.5+dfsg-2 [45.6 kB]
#9 47.78 Get:11 http://archive.ubuntu.com/ubuntu bionic-security/main amd64 openjdk-11-jdk-headless amd64 11.0.13+8-0ubuntu1~18.04 [220 MB]
#9 224.9 Fetched 260 MB in 3min 21s (1290 kB/s)
#9 225.0 Selecting previously unselected package java-common.
(Reading database ... 19653 files and directories currently installed.)
#9 225.1 Preparing to unpack .../00-java-common_0.68ubuntu1~18.04.1_all.deb ...
#9 225.1 Unpacking java-common (0.68ubuntu1~18.04.1) ...
#9 225.1 Selecting previously unselected package libnspr4:amd64.
#9 225.1 Preparing to unpack .../01-libnspr4_2%3a4.18-1ubuntu1_amd64.deb ...
#9 225.1 Unpacking libnspr4:amd64 (2:4.18-1ubuntu1) ...
#9 225.2 Selecting previously unselected package libnss3:amd64.
#9 225.2 Preparing to unpack .../02-libnss3_2%3a3.35-2ubuntu2.13_amd64.deb ...
#9 225.2 Unpacking libnss3:amd64 (2:3.35-2ubuntu2.13) ...
#9 225.4 Selecting previously unselected package libasound2-data.
#9 225.4 Preparing to unpack .../03-libasound2-data_1.1.3-5ubuntu0.6_all.deb ...
#9 225.4 Unpacking libasound2-data (1.1.3-5ubuntu0.6) ...
#9 225.5 Selecting previously unselected package libasound2:amd64.
#9 225.5 Preparing to unpack .../04-libasound2_1.1.3-5ubuntu0.6_amd64.deb ...
#9 225.5 Unpacking libasound2:amd64 (1.1.3-5ubuntu0.6) ...
#9 225.6 Selecting previously unselected package libpcsclite1:amd64.
#9 225.6 Preparing to unpack .../05-libpcsclite1_1.8.23-1_amd64.deb ...
#9 225.6 Unpacking libpcsclite1:amd64 (1.8.23-1) ...
#9 225.6 Selecting previously unselected package openjdk-11-jre-headless:amd64.
#9 225.7 Preparing to unpack .../06-openjdk-11-jre-headless_11.0.13+8-0ubuntu1~18.04_amd64.deb ...
#9 225.7 Unpacking openjdk-11-jre-headless:amd64 (11.0.13+8-0ubuntu1~18.04) ...
#9 231.1 Selecting previously unselected package ca-certificates-java.
#9 231.1 Preparing to unpack .../07-ca-certificates-java_20180516ubuntu1~18.04.1_all.deb ...
#9 231.1 Unpacking ca-certificates-java (20180516ubuntu1~18.04.1) ...
#9 231.2 Selecting previously unselected package libjq1:amd64.
#9 231.2 Preparing to unpack .../08-libjq1_1.5+dfsg-2_amd64.deb ...
#9 231.2 Unpacking libjq1:amd64 (1.5+dfsg-2) ...
#9 231.2 Selecting previously unselected package jq.
#9 231.2 Preparing to unpack .../09-jq_1.5+dfsg-2_amd64.deb ...
#9 231.2 Unpacking jq (1.5+dfsg-2) ...
#9 231.3 Selecting previously unselected package openjdk-11-jdk-headless:amd64.
#9 231.3 Preparing to unpack .../10-openjdk-11-jdk-headless_11.0.13+8-0ubuntu1~18.04_amd64.deb ...
#9 231.3 Unpacking openjdk-11-jdk-headless:amd64 (11.0.13+8-0ubuntu1~18.04) ...
#9 245.0 Setting up libpcsclite1:amd64 (1.8.23-1) ...
#9 245.0 Setting up libasound2-data (1.1.3-5ubuntu0.6) ...
#9 245.0 Setting up java-common (0.68ubuntu1~18.04.1) ...
#9 245.0 Setting up libnspr4:amd64 (2:4.18-1ubuntu1) ...
#9 245.0 Setting up libasound2:amd64 (1.1.3-5ubuntu0.6) ...
#9 245.1 Setting up libjq1:amd64 (1.5+dfsg-2) ...
#9 245.1 Setting up jq (1.5+dfsg-2) ...
#9 245.1 Setting up libnss3:amd64 (2:3.35-2ubuntu2.13) ...
#9 245.1 Setting up ca-certificates-java (20180516ubuntu1~18.04.1) ...
#9 245.1 Setting up openjdk-11-jre-headless:amd64 (11.0.13+8-0ubuntu1~18.04) ...
#9 245.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/java to provide /usr/bin/java (java) in auto mode
#9 245.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
#9 245.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/keytool to provide /usr/bin/keytool (keytool) in auto mode
#9 245.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
#9 245.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmiregistry to provide /usr/bin/rmiregistry (rmiregistry) in auto mode
#9 245.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
#9 245.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
#9 245.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
#9 246.3 Setting up openjdk-11-jdk-headless:amd64 (11.0.13+8-0ubuntu1~18.04) ...
#9 246.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jar to provide /usr/bin/jar (jar) in auto mode
#9 246.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jarsigner to provide /usr/bin/jarsigner (jarsigner) in auto mode
#9 246.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/javac to provide /usr/bin/javac (javac) in auto mode
#9 246.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc to provide /usr/bin/javadoc (javadoc) in auto mode
#9 246.3 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/javap to provide /usr/bin/javap (javap) in auto mode
#9 246.4 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jcmd to provide /usr/bin/jcmd (jcmd) in auto mode
#9 246.4 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jdb to provide /usr/bin/jdb (jdb) in auto mode
#9 246.4 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jdeprscan to provide /usr/bin/jdeprscan (jdeprscan) in auto mode
#9 246.4 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jdeps to provide /usr/bin/jdeps (jdeps) in auto mode
#9 246.4 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jfr to provide /usr/bin/jfr (jfr) in auto mode
#9 246.4 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jimage to provide /usr/bin/jimage (jimage) in auto mode
#9 246.4 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jinfo to provide /usr/bin/jinfo (jinfo) in auto mode
#9 246.4 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jlink to provide /usr/bin/jlink (jlink) in auto mode
#9 246.4 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jmap to provide /usr/bin/jmap (jmap) in auto mode
#9 246.5 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jmod to provide /usr/bin/jmod (jmod) in auto mode
#9 246.5 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jps to provide /usr/bin/jps (jps) in auto mode
#9 246.5 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jrunscript to provide /usr/bin/jrunscript (jrunscript) in auto mode
#9 246.5 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jshell to provide /usr/bin/jshell (jshell) in auto mode
#9 246.5 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jstack to provide /usr/bin/jstack (jstack) in auto mode
#9 246.5 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jstat to provide /usr/bin/jstat (jstat) in auto mode
#9 246.5 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jstatd to provide /usr/bin/jstatd (jstatd) in auto mode
#9 246.5 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmic to provide /usr/bin/rmic (rmic) in auto mode
#9 246.5 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/serialver to provide /usr/bin/serialver (serialver) in auto mode
#9 246.6 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jaotc to provide /usr/bin/jaotc (jaotc) in auto mode
#9 246.6 update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jhsdb to provide /usr/bin/jhsdb (jhsdb) in auto mode
#9 246.6 Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
#9 246.8 Processing triggers for ca-certificates (20210119~18.04.2) ...
#9 246.9 Updating certificates in /etc/ssl/certs...
#9 247.6 0 added, 0 removed; done.
#9 247.6 Running hooks in /etc/ca-certificates/update.d...
#9 247.7 
#9 248.0 done.
#9 248.0 done.
#9 DONE 248.5s

#10 [7/7] RUN apt-get autoremove --assume-yes   && apt-get clean --assume-yes   && rm -rf /var/lib/apt/lists/*
#10 sha256:c6b9ecd061ce624e701a15d87e4e2074da109ac7aa66c66faf1fd5e7312f9028
#10 0.412 Reading package lists...
#10 2.315 Building dependency tree...
#10 2.643 Reading state information...
#10 3.046 0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
#10 DONE 3.1s

#12 exporting to image
#12 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#12 exporting layers
#12 exporting layers 24.4s done
#12 writing image sha256:d7f0f6d6a338d038750ec05251aa780143193ba5406e1b0465e334341fc8300d
#12 writing image sha256:d7f0f6d6a338d038750ec05251aa780143193ba5406e1b0465e334341fc8300d done
#12 naming to docker.io/salesforce/salesforcedx:7.139.0-full done
#12 DONE 24.4s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
The push refers to repository [docker.io/salesforce/salesforcedx]
7e83f828125f: Preparing
e8ed7f22be2f: Preparing
9c5c0603be8b: Preparing
06dc4972cd21: Preparing
bcff03bd8ac3: Preparing
946bd89e4731: Preparing
c3bc0ba3a03b: Preparing
8ebe67b91a0b: Preparing
1dc52a6b4de8: Preparing
946bd89e4731: Waiting
1dc52a6b4de8: Waiting
8ebe67b91a0b: Waiting
c3bc0ba3a03b: Waiting
denied: requested access to the resource is denied
/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/common.js:110
  if (config.fatal) throw new Error(logEntry);
                          ^

Error: exec: denied: requested access to the resource is denied

    at Object.error (/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/common.js:110:27)
    at execSync (/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/exec.js:120:12)
    at Object._exec (/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/exec.js:223:12)
    at Object.exec (/Users/rupert/Downloads/sfdx-cli-main/node_modules/shelljs/src/common.js:335:23)
    at /Users/rupert/Downloads/sfdx-cli-main/scripts/docker-publish-full.js:36:9
error Command failed with exit code 1.

**Comment by iowillhoit** [comment]
Hey @RupertBarrow, this script is used internally to [publish new docker images](https://github.com/salesforcecli/sfdx-cli/blob/main/scripts/docker-publish-full.js#L36-L45). It is failing because you do not have access to our Docker Hub. If you want to build images locally (without failure) you can set the `NO_PUBLISH=true` env var to [skip the publish steps](https://github.com/salesforcecli/sfdx-cli/blob/main/scripts/docker-publish-full.js#L33). 

If case you are not aware, we publish new `latest` and `latest-rc` images every Thursday. You can pull these instead of building them yourself. ([Salesforce docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_docker.htm), [Docker Hub](https://hub.docker.com/r/salesforce/salesforcedx/tags))

Let me know if you have more questions!

**Comment by RupertBarrow** [comment]
Thanks for the quick answer.
I will follow your suggestion and keep you informed.
BTW, I am trying to create a Docker image for Cumulus CI, based on the salesforce/salesforcedx image.

**Comment by iowillhoit** [comment]
You bet @RupertBarrow! I am going to go ahead and close this, but feel free to reopen if you have any issues. Good luck
