### ISSUE TITLE
 RemoteOrgSignupFailed: A fatal signup error occurred.

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/cli#142]
### Summary

_Short summary of what is going on or to provide context_.

Creating scratch org using sourceOrg (shape) feature.

### Steps To Reproduce:

1.  This is step 1.
{
  "orgName": "HMI Scratch",
  "sourceOrg": "00DD0000000rch3MAA",
  "features": ["MultiCurrency","StateAndCountryPicklist","Communities", "DebugApex", "Pardot"],
  "settings": {
  "orgPreferenceSettings": {
  "networksEnabled": true,
  "s1DesktopEnabled": true
  }
  }
  }

 sfdx force:org:create -f config\project-scratch-def.json --setalias HMIPRODCOPY7/16 --durationdays 30 --setdefaultusername --json --loglevel fatal
1.  This is step 2. All steps should start with '1.'

### Expected result
Create new scratch org
_Describe what should have happened_.

### Actual result
PS C:\SalesforceDX\HMI DX\HMIPROD> sfdx force:org:create -f config\project-scratch-def.json --setalias HMIPRODCOPY7/16 --durationdays 30 --setdefaultusername --json --loglevel fatal
{
    "status": 1,
    "name": "RemoteOrgSignupFailed",
    "message": "A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance.",
    "exitCode": 1,
    "commandName": "OrgCreateCommand",
    "stack": "RemoteOrgSignupFailed: A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance.\n    at signup.retrieveScratchOrgInfo (C:\\Users\\sattir\\AppData\\Local\\sfdx\\client\\7.13.0-27dbcb37d3\\node_modules\\salesforce-alm\\dist\\lib\\org\\scratchOrgInfoApi.js:312:21)",
    "warnings": []
}
_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.
![shape](https://user-images.githubusercontent.com/93057/61309521-f901a880-a7b7-11e9-901c-c116ea633238.JPG)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
V46.0
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
PS C:\SalesforceDX\HMI DX\HMIPROD> sfdx --version
sfdx-cli/7.13.0-27dbcb37d3 win32-x64 node-v10.15.3
PS C:\SalesforceDX\HMI DX\HMIPROD> sfdx plugins --core
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.3.0 (core)
├─ force-language-services 46.8.0 (core)
└─ salesforce-alm 46.7.0 (core)

sfdx-cli 7.13.0 (core)
**OS and version**: Windows

**Comment by tnoonan-salesforce** [comment]
This issue was resolved yesterday. This was due to a configuration issue in production.
