### ISSUE TITLE
Component conversion failed: Cannot read properties of undefined (reading 'tagName')

### ISSUE THREAD

**Issue by LeoCordiuS** [forcedotcom/cli#1420]
Before the huge deployment process, I am getting error log as below
`*** Deploying with SOAP API v53.0 ***
ERROR running force:source:deploy:  Component conversion failed: Cannot read properties of undefined (reading 'tagName')`

Command that I am running is
`sfdx force:source:deploy -p force-app/main/default -c -l NoTestRun -w 300`

While running more verbose version 
`sfdx force:source:deploy -p force-app/main/default -c -l NoTestRun -w 300 --verbose --json`
`{
  "status": 1,
  "name": "ConversionError",
  "message": "Component conversion failed: Cannot read properties of undefined (reading 'tagName')",
  "exitCode": 1,
  "commandName": "Deploy",
  "stack": "TypeError: Cannot read properties of undefined (reading 'tagName')\n    at exports.validate (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/fast-xml-parser/src/validator.js:109:33)\n    at SourceComponent.parseAndValidateXML (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/sourceComponent.js:200:63)\n    at SourceComponent.parseXml (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@salesforce/source-deploy-retrieve/lib/src/resolve/sourceComponent.js:88:25)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async RecompositionFinalizer.recompose (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@salesforce/source-deploy-retrieve/lib/src/convert/convertContext.js:78:26)\n    at async RecompositionFinalizer.finalize (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@salesforce/source-deploy-retrieve/lib/src/convert/convertContext.js:40:38)\n    at async ConvertContext.executeFinalizers (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@salesforce/source-deploy-retrieve/lib/src/convert/convertContext.js:278:17)\n    at async ComponentConverter._flush (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@salesforce/source-deploy-retrieve/lib/src/convert/streams.js:108:30)\nOuter stack:\n    at Function.wrap (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at Deploy.catch (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@salesforce/command/lib/sfdxCommand.js:248:67)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Deploy._run (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at async Config.runCommand (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/obidjonkomiljonov/.local/share/sfdx/client/7.139.0-cb77bf7/dist/cli.js:162:47)",
  "warnings": []
}`

**Comment by shetzel** [comment]
Please provide the output of `sfdx -v --verbose`.  It would also be helpful to narrow down the conversion problem to a specific type or file using `sfdx force:source:convert` pointing to individual directories until the see the error.

**Comment by LeoCordiuS** [comment]
We have find the error reason. It was Layout metadata. It would be better if CLI prints out the name of corrupted XML file 🙂

**Comment by MayTheSForceBeWithYou** [comment]
I encountered this error message when trying to deploy an ApexClass that lacked the -meta.xml file
