### ISSUE TITLE
sfdx force:cmdt:record:insert --namecolumn DeveloperName not auto-generating underscore for spaces in VSCode

### ISSUE THREAD

**Issue by DerekHanson100** [forcedotcom/cli#1425]
### Summary

Having an issue where my force:cmdt:record:insert command only auto-generates an underscore for the first space in a Label which makes it error when I try to deploy

### Steps To Reproduce:

(https://github.com/ApolloV1010/force-cmdt-record-insert-ticket)

1.  This is step 1. Run this command in VSCode terminal: sfdx force:cmdt:record:insert --filepath "- \CCSCountyCodes_dhEdit_SC_TESTCOPY.csv" --typename County_Code__mdt --namecolumn DeveloperName

1.  This is step 2. VSCode creates the metadata.

### Expected result

Expect VSCode to create the metadata naming with underscores for spaces. For example, 'BIG DOG EAT' should become 'BIG_DOG_EAT.md-meta.xml'

### Actual result

VSCode only autogenerates an underscore for the first space in the text. 'BIG DOG EAT' becomes 'BIG_DOG EAT.md-meta.xml'. This will error when trying to deploy to org

### System Information

{
        "cliVersion": "sfdx-cli/7.139.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.14.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.1 (core)",
                "apex 0.9.0 (core)",
                "auth 1.8.1 (core)",
                "community 1.1.4 (core)",
                "config 1.3.19 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.9 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.1 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.1 (core)",
                "salesforce-alm 53.10.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.139.0 (core)",
                "source 1.8.12 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.6.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}

### Additional information

Attaching screenshot IssuePic1
![IssuePic1](https://user-images.githubusercontent.com/69818907/156256567-be1f8ecd-5d1b-408b-b061-cefd3462f2ce.PNG)

**Comment by alexia-osf** [comment]
Did you find any solution? I'm struggling with this situation now, even almost 1 year pass

**Comment by mshanemc** [comment]
We did some changes to how the developer names are being generated (https://github.com/salesforcecli/plugin-custom-metadata/pull/481)

Can you try it on a recent CLI version to see if it fixes your issue.
