### ISSUE TITLE
Remove "--targetusername" flag from force:org:create command

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#143]
The `force:org:create` command lists the flag "--targetusername" as one of the options.  There is no use for that flag on this command.

Recommendation is to simply remove the flag from the command.

Just to be clear.... there is no actual blocking issue with this... it is just an inconsistency that needs to be cleaned up.

Thanks for the help.  You guys are awesome!!!!

Cheers!

**Comment by amphro** [comment]
According to the `--help`, "When creating scratch orgs, —targetdevhubusername (-v) must be a Dev Hub org. When creating sandboxes, the --targetusername (-u) must be a production org with sandbox licenses."

**Comment by ImJohnMDaniel** [comment]
Sounds good. I wasn’t thinking about sandbox creation when I opened this ticket.  Thanks for the reply.  Cheers!
