### ISSUE TITLE
ERROR running force:package:version:create

### ISSUE THREAD

**Issue by revathikalai** [forcedotcom/cli#1435]
Our current package version is 1.1. We tried to create a new package with 1.2 with security enhancements for the Security review resubmission. During the package version creation, getting an error
" ERROR running force:package:version:create:  Can’t create package version. The ancestor version [undefined] you specified isn’t the highest released package version. Set the ancestor version to 1.1.0, and try creating the package version again. You can also specify --skipancestorcheck to override the ancestry requirement."
CLI version: 7.141 (it was 7.140 so updated to 7.141 and tried the same but no luck).
Recent Released Package Version: Please see the attached image.
Current Package Version: 1.1.0.1 and No ancestor for it.
Tried the CLI with the below:  
{ "default": true, "path": "force-app", "package": "NTeli Mind", "versionName": "ver 1.2", "versionNumber": "1.2.0.NEXT", "ancestorVersion": "HIGHEST" / "1.1.0.1" / "NONE" }
And tried to skip the Ancestor in the command --skipancestorcheck,but it automatically increase the version 1.1.0.2,1.1.0.3 not 1.2.0.1
All the time CLI shows the same error.This is the blocking issue for us to do the Security review resubmission.
Please let us know if we missed any, that would be helpful. 
Thank you
![Screen Shot 2022-03-09 at 12 11 43 PM copy](https://user-images.githubusercontent.com/30404020/157397806-8012d613-f60c-4f70-9419-e9ee58c77f88.jpg)
Revathi

**Comment by revathikalai** [comment]
Thank you for the response.
Once you are a Parent,You know the Golden Value Of Your Parent 

    On Wednesday, April 27, 2022, 08:25:41 PM GMT+5:30, github-actions[bot] ***@***.***> wrote:  
 
 


We have determined that the issue you reported exists in code owned by another team that uses only the official support channels. To ensure that your issue is addressed, open an official Salesforce customer support ticket with a link to this issue. We encourage anyone experiencing this issue to do the same to increase the priority. We will keep this issue open for the community to collaborate on.

**Comment by shetzel** [comment]
@revathikalai - There have been lots of bug fixes applied to the latest packaging plugin and library.  Is this still a problem or are you able to create package versions with the latest?

**Comment by revathikalai** [comment]
We created the version 1.3 and released. Thank you.
