### ISSUE TITLE
ERROR running force:source:deploy: Component conversion failed: Cannot create property 'CustomObject' on string ''

### ISSUE THREAD

**Issue by willianmatheus98** [forcedotcom/cli#1438]
### Summary

_When deploying custom fields and custom object the deployment failed with this strange message_.

### Steps To Reproduce:

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Retrieve your custom fields
1.  Try to deploy them with the `sfdx force:source:deploy -x manifest/package.xml --targetusername devUserNameAlias --checkonly --verbose`

### Expected result

_Deploy with success_.

### Actual result

`*** Deploying with SOAP API v52.0 ***
ERROR running force:source:deploy:  Component conversion failed: Cannot create property 'CustomObject' on string ''`

### System Information
`sfdx-cli/7.136.2 linux-x64 node-v14.6.0
`
### Additional information

Package.xml file below
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Account</members>
        <name>CustomObject</name>
    </types>
    <types>
        <members>Account.Field1__c</members>
        <members>Account.Field2__c</members>
        <members>Account.Field3__c</members>
        <name>CustomField</name>
    </types>
    <version>52.0</version>
</Package>
```

_Feel free to attach a screenshot_.

**Comment by maggiben** [comment]
Hi @willianmatheus98 that's an old version your running, try updating to latest-rc: `7.142.0`, also can you provide a demo Org to repro this issue ?

**Comment by willianmatheus98** [comment]
Hi @maggiben my problem was solved after the update, thanks!

**Comment by u0028854** [comment]
I am experiencing this again in `7.180.0`. The workaround solved the issue but it appears the fix is no longer working.
