### ISSUE TITLE
Info Release Notes Display - Warning - Version 7.142.1

### ISSUE THREAD

**Issue by estrudels** [forcedotcom/cli#1441]
### Summary

* I have recently downloaded the latest version of SFDX, using the command `sfdx update`
* I successfully am able to upgrade to v7.142.1, however the following **WARNING** is thrown when it finishes updating.
  * `WARNING: info:releasenotes:display failed: Didn't find version '7.142.1'.`
  * `View release notes online at: https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx`

### Steps To Reproduce
* Have SFDX installed globally already in your machine.
* Open a terminal.
* Perform an update for SFDX with the following command
  * `sfdx update`

### Expected result

* Upgrade SFDX **WITHOUT** any warnings, and displaying the appropriate **Release Notes** for the version of SFDX  I updated to.

### Actual result

* Upgrade SFDX **WITH** warnings, and **DOES NOT** display the appropriate **Release Notes** for the version of SFDX I updated to.

### System Information

* I have SFDX installed globally on my machine.
* To update I am using the basic command `sfdx update`

### Screenshot

* Below is a screenshot of my terminal after running the command `sfdx update`

![Broken-SFDX](https://user-images.githubusercontent.com/100722689/158311861-f042418b-a1d1-4634-84a7-3578a7c40fd8.png)

**Comment by maggiben** [comment]
Hi @estrudels the reason for the error is that we did not posted release notes for that version, we'll update them soon.
