### ISSUE TITLE
Conditional Formatting from Wave Dashboard widget not being deployed as part of unlocked package install

### ISSUE THREAD

**Issue by jdschleicher** [forcedotcom/cli#1442]
### Summary

When packaging a Wave Dashboard we experienced the conditionalFormatting attributes for a widget were not being added to the dashboard in the target environment. We were able to use a standard force:source:deploy  to push the same file representing the Wave Dashboard and the conditionalFormatting showed up as expected.  

### Steps To Reproduce:

1. Create a wavedashboard component and add conditional formatting
`. create new unlocked Package a WaveDashboard component
1. Install the package to a scratch org/clean environment
1. Confirm the conditional formatting did not come with the wavedashboard component
1. deploy that same wavedashboard file to same target environment
1. confirm conditional formatting rendered as expected

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*  

sorry short on time to create a sample analytics project for this effort. I'm hoping it's possibly low-hanging fruit as a similar issue was fixed in spring'20 ( but i may be completely off :) ) https://trailblazer.salesforce.com/issues_view?id=a1p3A000001PYXYQA4&title=xmd-is-not-deploying-updates-to-conditional-formatting-when-namespaced-org-is-involved

### Expected result
conditional formatting rendered and actual formatting values existing in edit settings when clicking on widget

### Actual result
no conditional formatting rendered, when navigating into the edit settings the conditional formatting inputs are completely empty

### System Information

{
        "cliVersion": "sfdx-cli/7.142.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.14.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-scanner 2.13.0",
                "alias 1.2.1 (core)",
                "auth 1.8.1 (core)",
                "community 1.1.4 (core)",
                "config 1.3.23 (core)",
                "generator 1.2.2 (core)",
                "info 1.3.0 (core)",
                "salesforcedx 52.0.0",
                "├─ salesforce-alm 52.0.0",
                "├─ data 0.4.11",
                "├─ custom-metadata 1.0.12",
                "├─ apex 0.2.2",
                "├─ limits 1.2.1",
                "├─ org 1.6.6",
                "├─ templates 51.5.0",
                "├─ user 1.3.0",
                "├─ schema 1.0.7",
                "└─ @salesforce/sfdx-plugin-lwc-test 0.1.7",
                "sfdmu 4.12.9",
                "sfdx-cli 7.142.1 (core)",
                "sfdx-waw-plugin 1.5.0",
                "sfpowerkit 4.1.5",
                "shane-sfdx-plugins 4.43.0",
                "├─ @mshanemc/plugin-streaming 1.1.7",
                "└─ @mshanemc/sfdx-sosl 1.1.0",
                "source 1.8.18 (core)",
                "telemetry 1.4.0 (core)",
                "texei-sfdx-plugin 1.14.4",
                "trust 1.1.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19041"
}

### Additional information

![image](https://user-images.githubusercontent.com/3968818/158388626-d054454c-42a3-4d18-8fef-6402180b0e02.png)

**Comment by maggiben** [comment]
Hi, @jdschleicher what sfdx commands did you use, Im trying to repro. thanks.

**Comment by jdschleicher** [comment]
hi @maggiben  I apologize for the delay. I went through a full end-to-end unlocked package installation of this associated app and the conditional formatting did show as expected.

The issue stemmed from having a variance of the components in version control compared to what we were seeing in the sandbox ( of course :) )
