### ISSUE TITLE
Source tracking does not detect local changes for relative paths

### ISSUE THREAD

**Issue by aly76** [forcedotcom/cli#1444]
### Summary

`force:source:beta:status` or `force:source:beta:push` does not detect local changes for paths in the sfdx-project.json that have been specified as a relative path i.e. `./path/to/package`

#1258 
### Steps To Reproduce:

1. Create a scratch org using `force:org:create` 
1. Specify packages in sfdx-project.json with relative paths i.e. `path: "./path/to/package"`
1. Run `force:source:beta:push` using the scratch org from step 1 
1.  Run `force:source:beta:status` using the scratch org from step 1

### Expected result

Source tracking should detect local changes regardless of how the path is specified e.g. `path/to/package` or `./path/to/package`

### Actual result

"No results found" for `force:source:beta:push`
Either no results or remote changes only for `force:source:beta:status` 

### System Information

- sfdx-cli 7.134.0
- macOS 10.15.7

**Comment by maggiben** [comment]
marked as bug: @W-10886128@
<img width="498" alt="image" src="https://user-images.githubusercontent.com/2845947/159624265-4e261f10-02d6-4e1e-bba0-d1f9e9195f31.png">
