### ISSUE TITLE
RangeError: Maximum call stack size exceeded with force:source:manifest:create command

### ISSUE THREAD

**Issue by ar-srinivas** [forcedotcom/cli#1446]
### Summary

force:source:manifest:create command is failing to generate package.xml and showing the below error.

{
  "status": 1,
  "name": "RangeError",
  "message": "Maximum call stack size exceeded",
  "exitCode": 1,
  "commandName": "create",
  "stack": **"RangeError: Maximum call stack size exceeded**\n    at MetadataResolver.getComponentsFromPathRecursive (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\resolve\\metadataResolver.js:102:24)\n    at MetadataResolver.getComponentsFromPathRecursive (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\resolve\\metadataResolver.js:102:37)\n    at MetadataResolver.getComponentsFromPathRecursive (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\resolve\\metadataResolver.js:102:37)\n    at MetadataResolver.getComponentsFromPath (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\resolve\\metadataResolver.js:49:25)\n    at buildComponents (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\collections\\componentSet.js:73:50)\n    at Function.fromSource (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\collections\\componentSet.js:78:9)\n    at Function.build (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\collections\\componentSetBuilder.js:39:59)\n    at createManifest (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\source\\manifest\\create.js:51:81)\n    at create.run (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\source\\manifest\\create.js:32:20)\n    at create._run (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:81:51)\nOuter stack:\n    at Function.wrap (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\n    at create.catch (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:248:67)\n    at async create._run (C:\\Users\\xxxx\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:85:13)\n    at async Config.runCommand (C:\\Program Files\\sfdx\\client\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async SfdxMain.run (C:\\Program Files\\sfdx\\client\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async SfdxMain._run (C:\\Program Files\\sfdx\\client\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Program Files\\sfdx\\client\\dist\\cli.js:162:47)",
  "warnings": []
}

### System Information
{
        "cliVersion": "sfdx-cli/7.135.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.13.2",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.1",
                "config 1.3.23",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.1 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.2",
                "salesforce-alm 53.7.5 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.135.0 (core)",
                "sfdx-codescan-plugin 1.0.7",
                "source 1.8.20",
                "telemetry 1.4.0 (core)",
                "templates 53.1.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}

**Comment by maggiben** [comment]
Hi, can you provide us with an org that causes this error to repro or include the instructions to reproduce ?

**Comment by ar-srinivas** [comment]
This is happening on our production source and unfortunately, I can't share you the source details. But this is happening when we have multiple metadata(more than 3L files including all metadata types) in a package directory.

**Comment by WillieRuemmele** [comment]
hi @ar-srinivas, it seems like some of your plugins are pinned to specific versions (`org`, `source`, `auth`, `config`) is there a reason for that? I would suggest running `sfdx plugins:uninstall <plugin>` for those plugins and trying again. You're missing the latest fixes to all of those plugins

**Comment by ar-srinivas** [comment]
I had the correct versions and as part of debugging this issue, I tried updating the individual plugins.

Here is the original plugin versions with the 7.134 version

{
    "cliVersion": "sfdx-cli/7.134.0",
    "architecture": "linux-x64",
    "nodeVersion": "node-v16.13.2",
    "pluginVersions": [
        "@oclif/plugin-autocomplete 0.3.0 (core)",
        "@oclif/plugin-commands 1.3.0 (core)",
        "@oclif/plugin-help 3.3.1 (core)",
        "@oclif/plugin-not-found 1.2.6 (core)",
        "@oclif/plugin-plugins 1.10.11 (core)",
        "@oclif/plugin-update 1.5.0 (core)",
        "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
        "@oclif/plugin-which 1.0.4 (core)",
        "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
        "alias 1.2.0 (core)",
        "apex 0.7.0 (core)",
        "auth 1.4.3 (1.4.3)",
        "config 1.3.14 (core)",
        "custom-metadata 1.0.12 (core)",
        "data 0.6.8 (core)",
        "generator 1.2.1 (core)",
        "info 1.2.0 (core)",
        "limits 1.3.0 (core)",
        "org 1.11.0 (core)",
        "salesforce-alm 53.7.2 (core)",
        "schema 1.1.0 (core)",
        "sfdx-cli 7.134.0 (core)",
        "source 1.8.0 (core)",
        "telemetry 1.4.0 (core)",
        "templates 53.1.0 (core)",
        "trust 1.1.0 (core)",
        "user 1.7.0 (core)"
    ],
    "osVersion": "Linux 5.4.0-1060-aws"
}

**Comment by WillieRuemmele** [comment]
Ok, that makes sense.

- Did this issue just start happening for you? When was the last time it succeeded?
- Are you able to `source:deploy` whichever directory/file path you're trying to create a manifest from?
- Is this in a very large project? Or one with a complex structure? 

it's stemming from [here](https://github.com/forcedotcom/source-deploy-retrieve/blob/230c3a6f640b1e245de021e0f7101a277ed6f448/src/resolve/metadataResolver.ts#L65) and I'm trying to understand what's causing it to happen for you. That method hasn't changed in quite a while

**Comment by ar-srinivas** [comment]
- The issue is occurring on different machines for the same and even other huge source. It started as soon as I upgrade to this specific version and start using this command.
- I didn't try the source:deploy as I don't have the package.xml for the whole source.
- It's  a large and even complete structure

Even if I split the source into multiple package directories, I am ending up with the same issue.

**Comment by WillieRuemmele** [comment]
Thank you.

if you're able to share the project that is causing this issue that'll be hugely helpful in reproducing the error. But I'll be looking into this

**Comment by ar-srinivas** [comment]
Thank you @WillieRuemmele for your response.
Since it is our production metadata, I can' share you. But in size the metadata is around 3GB...

We are also facing another issue with the same command where it keeps running for more than 30-40 mins in case where we have the metadata of size 3.5GB. Just to complete this command and generate package manifest it is consuming high CPU and running for more than 40 mins. Does this tested with such high source systems and is there any fix for such issues in later releases. We are on 7.134 version as mentioned above.

**Comment by mshanemc** [comment]
@ar-srinivas I still don't know how to reproduce this.  I'm gonna ask some questions that might seem strange, but relate to known things that have caused trouble in the past.  We can fill up a repo with thousands of apex classes and not have problems.  So it's not *just the size* that's the problem.

Can you describe your customLabels?  How many labels have you got, in how many different files?

Can you describe your zipped staticResources?  How many files and how large are the total size of each resource?  Are there lots of nested folders in there?

Are there any symbolic links anywhere?

Is this still a problem on a current CLI (7.159 or 7.160)?

**Comment by mshanemc** [comment]
@ar-srinivas please open a new case with repro steps if you can still see this happening.  We've made quite a few changes on the problem types I mentioned, so I'm cautiously optimistic it may have helped yours
