### ISSUE TITLE
sfdx force:mdapi:deploy command failed but deployment reached Salesforce

### ISSUE THREAD

**Issue by ncnxx** [forcedotcom/cli#145]
### Summary

I have set up a Jenkins pipeline to automatically deploy to orgs using sfdx cli. We have faced this error:
```
22:30:14  + sfdx force:mdapi:deploy -d ./package -u sit -l NoTestRun -w -1 -g
 > /usr/bin/git rev-list --no-walk 260585898891d074aa2b871477554f33e82fed77 # timeout=10
22:30:15  6228 bytes written to /tmp/package.zip using 96.275ms
22:30:15  Deploying /tmp/package.zip...
22:30:16  ERROR running force:mdapi:deploy:  Parse error in file /home/jenkins/.sfdx/stash.json on line 6
22:30:16  ame": "uat"
22:30:16      }
22:30:16  } }}
22:30:16  
```
The error caused failure to the `sfdx force:mdapi:deploy`. However, the deployment request would reach the Salesforce target org and performed deployment as it should on the Salesforce side. 

### Steps To Reproduce:
1. Try jenkins with the following snippet of code:
```
withCredentials([file(credentialsId: 'SIT-SECRET-FILE', variable: 'jwt_key_file')]) {
                    sh 'sfdx force:auth:jwt:grant --clientid ${sitConsumerKey} --jwtkeyfile ${jwt_key_file} --username xxxxxxxx --setalias sit --instanceurl https://test.salesforce.com'
                    sh "sfdx essentials:filter-metadatas -i ./src -o ./package -p ./src/package.xml"
                    sh(returnStdout: false, script: '''
                        if [ -d ./package/classes ] 
                        then 
                            sfdx force:mdapi:deploy -d ./package -u sit -l RunSpecifiedTests -w -1 -g -r \$(sh testclasses.sh ./package/classes)
                        else 
                            sfdx force:mdapi:deploy -d ./package -u sit -l NoTestRun -w -1 -g 
                        fi
                    '''.stripIndent())
                }
```
Remark: I only pasted a snippet of the problematic code here not the full code, because the full code would contain references to libraries and steps which are unique to my Jenkins environment.

2. Run the Jenkins job

### Expected result

The mdapi:deploy command should work properly without errors.

### Actual result
```
22:30:16  ERROR running force:mdapi:deploy:  Parse error in file /home/jenkins/.sfdx/stash.json on line 6
22:30:16  ame": "uat"
22:30:16      }
22:30:16  } }}
22:30:16  
```
The command failed with the error above. But the deployment did reach Salesforce and work as it should.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.18.0-ee5dc8194c linux-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.0 (core)
generator 1.1.0 (core)
salesforcedx 46.8.0 (core)
  ├─ force-language-services 46.12.0 (core)
  └─ salesforce-alm 46.11.0 (core)
sfdx-cli 7.18.0 (core)
sfdx-essentials 0.4.5 (link) /home/jenkins/software/sfdx-essentials

**OS and version**: redhat (Jenkins instance)

**Comment by ncnxx** [comment]
I have solved this problem by removing the directory `/home/jenkins/.sfdx` and run the commands again. I suspect that it might be from a malformed `stash.json` file which is automatically created by sfdx cli.

**Comment by reda-benhemmouche** [comment]
We use Jenkins and we get this error many times when we have a lot of activities (deployment to sandbox or validating PR).
`ERROR running force:mdapi:deploy:  Parse error in file /home/jenkins/.sfdx/stash.json on line`
I think this is related to parallel access to the file .sfdx/stash.json by multiple instances of sfdx.
The code is not thread safe !
