### ISSUE TITLE
running sfdx update from npm installed sfdx for linux aarch64 fails

### ISSUE THREAD

**Issue by kushney** [forcedotcom/cli#1454]
### Summary

I am setting up gitlab runner in docker on M1 Apple Silicon

### Steps To Reproduce:

Run following commands:
`npm install --global sfdx-cli`
`sfdx update`

### Expected result

no errors

### Actual result

```
# sfdx update
sfdx-cli: Updating CLI... !
    Error: HTTP Error 404 for GET https://developer.salesforce.com/linux-arm64

```

### System Information

M1 Apple Silicon
Docker image `node:latest`
Docker app for Apple Silicon

`uname`:
Linux
`arch`:
aarch64
`sfdx version`
sfdx-cli/7.142.1 linux-arm64 node-v17.8.0

_Feel free to attach a screenshot_.

**Comment by WillieRuemmele** [comment]
npm-based installations are updated through `npm` commands, `sfdx update` is used when the CLI is downloaded from [here](https://developer.salesforce.com/tools/sfdxcli)... you might've happened to run that update while we were releasing the newest version earlier this morning too
