### ISSUE TITLE
Error message should be enhanced when requiresDevhubUsername = true

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#146]
When we develop a custom CLI command and specify requiresDevhubUsername = true, if the user does not supply a devHubUsername, the error message received is "Must pass a username and/or OAuth options when creating an AuthInfo instance."

The issue is that there is no distinction between a command missing a devHubUsername and the command missing the username.

If the devHubUsername is missing, the request here is to enhance the error message to something like "Must pass a username and/or OAuth options when creating a DevHub AuthInfo instance."

**Comment by clairebianchi** [comment]
Hi @ImJohnMDaniel we are doing a big error message bash soon and I will add this to the list

**Comment by ImJohnMDaniel** [comment]
Thanks @clairebianchi for the update.

**Comment by amphro** [comment]
This should be fixed in the latest version of `@salesforce/command`.
