### ISSUE TITLE
force:data:bulk:upsert errors out if file is over batch character limit

### ISSUE THREAD

**Issue by aheber** [forcedotcom/cli#1460]
### Summary

If the total character count of a file exceeds the allowed per-batch character count (still less than 10K rows) then the command errors when uploading the file.

### Steps To Reproduce:

Upload a batch file that includes >10MB of data in less than 10K rows

### Expected result

The file should be broken into smaller batches, just as it would be if the source file was >10K rows

### Actual result

The command end in Error but doesn't provide failure details.

### System Information
{
        "cliVersion": "sfdx-cli/7.144.2",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.14.2",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.1 (core)",
                "apex 0.11.0 (core)",
                "auth 1.8.1 (core)",
                "community 1.1.4 (core)",
                "config 1.3.23 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.11 (core)",
                "generator 1.2.2 (core)",
                "info 1.3.1 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.2 (core)",
                "salesforce-alm 54.1.0 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.144.2 (core)",
                "sfdx-devops 0.4.6",
                "sfdx-heber 0.0.2",
                "sfdx-typegen 0.6.2",
                "sfpowerkit 4.1.5",
                "shane-sfdx-plugins 4.43.0",
                "├─ @mshanemc/sfdx-sosl 1.1.0",
                "└─ @mshanemc/plugin-streaming 1.1.7",
                "source 1.9.2 (core)",
                "telemetry 1.4.0 (core)",
                "templates 54.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19043"
}

### Additional information

I will have a PR against the data plugin shortly

**Comment by mshanemc** [comment]
Thanks for the PR!
