### ISSUE TITLE
force:source:push fails on label that uses CDATA

### ISSUE THREAD

**Issue by nawforce** [forcedotcom/cli#1467]
### Summary

If you try and push a labels files which contains a label whose value contains a CDATA section, the push fails with 'Error parsing file: Unexpected element'  

### Steps To Reproduce:

[Sample repo](https://github.com/nawforce/sfdx-test/tree/main/badlabel)

1. Run sfdx force:source:push -f for error
2. Remove .sfdx directory
3. Run sfdx force:source:legacy:push -f for success

### Expected result

The file should be deployed without error.

### Actual result

=== Component Failures [1]
    Type   Name          Problem
    Error  CustomLabels  Error parsing file: Unexpected element {http://soap.sforce.com/2006/04/metadata}p during simple type deserialization (8:19)

    ERROR running force:source:deploy:  Deploy failed.

### System Information

{
        "cliVersion": "sfdx-cli/7.144.2",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.6.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.1 (core)",
                "apex 0.11.0 (core)",
                "apexlink 2.3.2 (link) /Users/kevin/Projects/apex-link-sfdx-cli",
                "auth 1.8.1 (core)",
                "community 1.1.4 (core)",
                "config 1.3.23 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.11 (core)",
                "generator 1.2.2 (core)",
                "info 1.3.1 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.2 (core)",
                "salesforce-alm 54.1.0 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.144.2 (core)",
                "sfpowerkit 3.3.3 (link) /Users/kevin/Projects/sfpowerkit",
                "source 1.9.2 (core)",
                "telemetry 1.4.0 (core)",
                "templates 54.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Darwin 21.3.0"
}

**Comment by WillieRuemmele** [comment]
Hi @nawforce 👋  

thanks for reporting this. We'll jump on it

@W-10946208@

**Comment by WillieRuemmele** [comment]
After some investigation this issue is in the SDR library so it affects `push` and `deploy`. As a workaround you can continue to use the `source:legacy:*` commands until its fixed

**Comment by shetzel** [comment]
This is fixed in the current CLI release candidate.

**Comment by shetzel** [comment]
This fix is now in the latest CLI release, 7.146.1
