### ISSUE TITLE
`SfdxCommand.ux.table` method not working in `@salesforce/command@5.x`

### ISSUE THREAD

**Issue by jfeingold35** [forcedotcom/cli#1470]
### Summary

`SfdxCommand.ux.table` not working in `@salesforce/command@5.x`. Instead of logging a table, garbage is logged.

### Steps To Reproduce:

**Repository to reproduce:** [bugDemonstrationPlugin](https://github.com/jfeingold35/bugDemonstrationPlugin)

1. Clone the provided repo.
1. `cd` into the root of that project
1. Run `yarn` or whatever other command to install the dependencies.
1. Run `bin/run hello:bugdemo`

### Expected result

As per [the underlying code in the command](https://github.com/jfeingold35/bugDemonstrationPlugin/blob/main/src/commands/hello/bugdemo.ts), the same table should be printed twice:

```
 NAME      SOME PROP SOME OTHER PROP 
 ───────── ───────── ─────────────── 
 some name a value   another value 
 NAME      SOME PROP SOME OTHER PROP 
 ───────── ───────── ─────────────── 
 some name a value   another value 
```

### Actual result
The first table, which is the one created by calling `this.ux.table()`, is malformed. The second one, which is created by manually creating the header information for oclif to use and calling `this.ux.cli.ux.table()` directly, is printed correctly.
```
 Columns   
 ───────── 
 undefined 
 NAME      SOME PROP SOME OTHER PROP 
 ───────── ───────── ─────────────── 
 some name a value   another value   
```

### System Information
```
$ sfdx version --verbose --json
{
	"cliVersion": "sfdx-cli/7.145.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.14.2",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"@salesforce/sfdx-scanner 2.13.1",
		"alias 2.0.0 (core)",
		"apex 0.11.0 (core)",
		"auth 1.8.2 (core)",
		"community 1.1.4 (core)",
		"config 1.3.24 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.12 (core)",
		"generator 1.2.2 (core)",
		"info 1.3.1 (core)",
		"limits 1.3.0 (core)",
		"org 1.11.2 (core)",
		"salesforce-alm 54.1.0 (core)",
		"schema 1.1.0 (core)",
		"sfdx-cli 7.145.0 (core)",
		"sfdx-waw-plugin 1.5.0",
		"source 1.9.2 (core)",
		"telemetry 1.4.0 (core)",
		"templates 54.3.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.1 (core)"
	],
	"osVersion": "Darwin 19.6.0"
}
```
### Additional information

I have already identified the cause: [Line 306 of ux.ts](https://github.com/salesforcecli/command/blob/main/src/ux.ts#L306) should be `this.cli.ux.table(rows, tableColumns, options);` instead of `...{columns: tableColumns}...`.

**Comment by WillieRuemmele** [comment]
Hi @jfeingold35 the table options have changed for `Command5` check out the [OCLIF table options](https://oclif.io/docs/table)

**Comment by jfeingold35** [comment]
@WillieRuemmele , I'm aware that the table options have changed. The problem is that `utx.ts` hasn't changed with them. `table()` expects an object whose properties are the columns. The object being provided has a property called `columns` whose value is itself the object in question. The code change I included resolves the issue.

**Comment by WillieRuemmele** [comment]
@jfeingold35 ahh makes sense, so far we've been defining our table columns as objects so it's using L308 instead. Feel free to make a PR and tag me  there, or I'll try to get to this and just make your suggested change

**Comment by jfeingold35** [comment]
@WillieRuemmele , here's a PR that fixes the issue. As a first-time contributor, I need a maintainer to approve running workflows. Is that something you're empowered to do? https://github.com/salesforcecli/command/pull/71

**Comment by WillieRuemmele** [comment]
@jfeingold35 nice, I was going to work on this right now actually. I'll take a look and get CI going
