### ISSUE TITLE
Vulnerabilities on CLI install cannot be solved using npm audit fix

### ISSUE THREAD

**Issue by albarivas** [forcedotcom/cli#1475]
### Summary

A customer has reported that when they install the CLI with npm they cannot fix found vulnerabilities with `npm audit fix`.

### Steps To Reproduce:

1. Install the CLI with `sudo npm install sfdx-cli --global -force`
2. Try to fix the vulnerabilities found running `npm audit fix`

### Expected result

That vulnerabilities are fixed. 

### Actual result

![vulne](https://user-images.githubusercontent.com/12017842/162715686-d4bd5c86-a1c2-4204-a52a-29d25ec1798c.jpeg)

### System Information

The customer is using MacOs Catalina and they tried the install yesterday.

**Comment by manwey** [comment]
Thank you Alba for transmitting my problem to those who can help solve it.

This is the content of the file with the logs in case it can be of help.

0 verbose cli [
0 verbose cli   '/Users/manwey/.nvm/versions/node/v16.13.2/bin/node',
0 verbose cli   '/Users/manwey/.nvm/versions/node/v16.13.2/bin/npm',
0 verbose cli   'audit',
0 verbose cli   'fix'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v16.13.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/manwey/.nvm/versions/node/v16.13.2/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/manwey/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/manwey/.nvm/versions/node/v16.13.2/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:setTitle Completed in 15ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 0ms
26 timing npm:load Completed in 28ms
27 timing arborist:ctor Completed in 1ms
28 timing command:audit Completed in 4ms
29 verbose stack Error: loadVirtual requires existing shrinkwrap file
29 verbose stack     at Arborist.loadVirtual (/Users/manwey/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:62:18)
29 verbose stack     at async Arborist.audit (/Users/manwey/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/audit.js:25:18)
29 verbose stack     at async Audit.audit (/Users/manwey/.nvm/versions/node/v16.13.2/lib/node_modules/npm/lib/audit.js:66:5)
30 verbose cwd /
31 verbose Darwin 19.6.0
32 verbose argv "/Users/manwey/.nvm/versions/node/v16.13.2/bin/node" "/Users/manwey/.nvm/versions/node/v16.13.2/bin/npm" "audit" "fix"
33 verbose node v16.13.2
34 verbose npm  v8.1.2
35 error code ENOLOCK
36 error audit This command requires an existing lockfile.
37 error audit Try creating one first with: npm i --package-lock-only
38 error audit Original error: loadVirtual requires existing shrinkwrap file
39 verbose exit 1

**Comment by mshanemc** [comment]
@manwey we've never intended npm audit to auto-fix problems or tested that approach.  We don't currently ship an npm-shrinkwrap, either, which looks like it's what's preventing that from working.

you *could* try `yarn audit fix` (we do have that lockfile) but we've never tested it.  If you're seeing some dependency vulnerabilities you're concerned about, you could specify those on a separate issue (and be sure to include the requested version info!)
