### ISSUE TITLE
Stable version tag for npm is no longer available

### ISSUE THREAD

**Issue by Kevmo92** [forcedotcom/cli#1476]
### Summary

The npm `stable` version tag no longer exists. 

### Steps To Reproduce:

1.  npm i -g sfdx-cli@stable

### Expected result

The current stable version of sfdx is installed. 

### Actual result

`No matching version found for sfdx-cli@stable.`

### System Information

not relevant

**Comment by shetzel** [comment]
The npm tags for sfdx-cli are `latest` and `latest-rc`.  The installer tags are `stable` and `stable-rc`.

**Comment by Kevmo92** [comment]
> The npm tags for sfdx-cli are `latest` and `latest-rc`. The installer tags are `stable` and `stable-rc`.

Ah, ok. I guess that changed recently. Is it safe to assume `latest` is stable @shetzel ?

**Comment by shetzel** [comment]
latest == stable
latest-rc == stable-rc

Afaik, it's been this way since we starting doing release candidates.

**Comment by daveespo** [comment]
@shetzel  -- something is not right -- the docs for downloading the tarballs use the "stable" and "stable-rc"


https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_rc.htm

However, https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable-rc/sfdx-linux-x64.tar.xz currently points to CLI 7.140.x (several weeks old) so there's likely something not updating the tarball URLs

**Comment by shetzel** [comment]
@daveespo - yeah, something is off there.  1478 is definitely a bug.

I wasn't aware of this, but it seems that there used to be a stable tag for sfdx-cli npm.  That was a mistake long ago and pointed to a very old version (it wasn't being updated) and has been removed.  @Kevmo92 - apologies for my inaccurate response.
