### ISSUE TITLE
lwc in subfolders no longer work in force:source:push

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#1477]
### Summary

`force:source:push` no longer supports lwc subfolders ini the source code. Prior to 7.144 this worked just fine

### Steps To Reproduce:

1. Have a source based project with the LWC in a folder structure like this:

lwc
+--folder1
|   \ \--lwc
|       +--myLwcCmp1
|      \ \--myLwcCmp2
\\--myLwcCmp3

1. SFDX 7.144 or newer
1. run force:source:push

### Expected result

Source push to succeed

### Actual result

Deploy Errors:
Error  folder1                                             No base file for markup://c:folder1
Error  folder1          duplicate value found: <unknown> duplicates value on record with id: <unknown>
Error  folder1          duplicate value found: <unknown> duplicates value on record with id: <unknown>

### System Information

{
        "cliVersion": "sfdx-cli/7.145.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.1",
        "pluginVersions": [
                "@mavens/mic-cli-plugin 11.0.0-0 (link) /Users/kaiamundsen/workspace/P-Tool-MIC-Installer",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.0 (core)",
                "apex 0.11.0 (core)",
                "auth 1.8.2 (core)",
                "community 1.1.4 (core)",
                "config 1.3.24 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.12 (core)",
                "generator 1.2.2 (core)",
                "info 1.3.1 (core)",
                "isvte-sfdx-plugin 1.1.14",
                "limits 1.3.0 (core)",
                "org 1.11.2 (core)",
                "salesforce-alm 54.1.0 (core)",
                "schema 1.1.0 (core)",
                "sfdmu 4.13.0",
                "sfdx-cli 7.145.0 (core)",
                "source 1.9.2 (core)",
                "telemetry 1.4.0 (core)",
                "templates 54.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Darwin 21.4.0"
}

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11051996](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000vkpzlYAA/view)

**Comment by iowillhoit** [comment]
This fix is included in the latest stable build of `sfdx` (`7.149.1`). Let us know if you still are seeing issues. Thanks!
