### ISSUE TITLE
CLI Release Candidate tarball is not being updated

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#1478]
The CLI docs provide a URL to download the release candidate tarball over here:

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_rc.htm

But when you pull that URL, the tarball is actually the CLI from 4 or 5 weeks ago (7.140 to be exact)

https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable-rc/sfdx-linux-x64.tar.xz

This is similar to the bug report over on #1476 where it appears as though what once worked (pulling the NPM module via the stable-rc tag) is no longer working?

It should be noted that the instructions for pulling the `stable` tarball are still accurate (i.e. it still pulls the most current stable version)

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux

Expected:
 * the tarball at that URL should resume being updated weekly with the latest release candidate
 * OR, less desirable, the docs should be updated AND the old URLs should return 404 errors so that people who have automation and depend on that URL don't mistakenly think that it's the "release candidate" when it's most certainly not

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10990415](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000us1KzYAI/view)

**Comment by shetzel** [comment]
Thanks for reporting @daveespo - getting right on this!

**Comment by shetzel** [comment]
This will be fixed with this PR: https://github.com/salesforcecli/sfdx-cli/pull/532

After the release tomorrow the .xz files should be updated.  The .gz files were being properly copied to that location so if you want to temporarily switch to them you could.

**Comment by shetzel** [comment]
Actually @daveespo they are updated now.  Closing this.  Thanks for reporting!

**Comment by daveespo** [comment]
@shetzel  thanks for the speedy fix -- confirmed, my CI is now building with `sfdx-cli/7.146.0 linux-x64 node-v16.14.2`
