### ISSUE TITLE
Regression: config:get no longer returns defaultusername on CLI 7.146.0

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#1480]
On CLI 7.145.0 (and all versions prior), doing a `config:get defaultusername` would return the username for the default scratch org defined for that project directory

In CLI 7.146.0, the username value is now `undefined`. I installed CLI 7.146.0 from the Tarball URL (https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable-rc/sfdx-linux-x64.tar.xz) (and yes, it's after the fix for #1478 went out)

Repro steps:
 * Download and unpack the tarball from the above URL
 * Add the `sfdx/bin` directory to your path
 * Authorize your DevHub (`sfdx auth:web:login --setdefaultdevhubusername`)
 * Create a new project (`sfdx force:project:create -n sample`)
 * Change into sample directory (`cd sample`)
 * Create a scratch org (`sfdx force:org:create --setdefaultusername -f config/project-scratch-def.json `)
 * Run: `sfdx config:get defaultusername`

Actual:
```
esposito@PT-WIN-ESPOSITO:~/sample$ sfdx config:list
=== List Config

 Name                  Value                         Location
 ───────────────────── ───────────────────────────── ────────
 defaultdevhubusername d@pt.com                      Global
 defaultusername       test-veamnu7sxlnj@example.com Local
esposito@PT-WIN-ESPOSITO:~/sample$ sfdx config:get defaultusername
=== Get Config

 Name            Value     Success
 ─────────────── ───────── ───────
 defaultusername undefined true
esposito@PT-WIN-ESPOSITO:~/sample$
```

Expected (this is output from 7.145.0):

```
esposito@PT-WIN-ESPOSITO:~/sample$ sfdx config:list
=== List Config
Name                   Value                          Location
─────────────────────  ─────────────────────────────  ────────
defaultdevhubusername  d@pt.com                       Global
defaultusername        test-veamnu7sxlnj@example.com  Local
esposito@PT-WIN-ESPOSITO:~/sample$ sfdx config:get defaultusername
=== Get Config
Name             Value                          Success
───────────────  ─────────────────────────────  ───────
defaultusername  test-veamnu7sxlnj@example.com  true
```

### System Information

```
 CLI Version :
        sfdx-cli/7.146.0

 Architecture:
        wsl-x64

 Node Version :
        node-v16.14.2

 Plugin Version:
        @oclif/plugin-autocomplete 0.3.0 (core)
        @oclif/plugin-commands 1.3.0 (core)
        @oclif/plugin-help 3.3.1 (core)
        @oclif/plugin-not-found 1.2.6 (core)
        @oclif/plugin-plugins 1.10.11 (core)
        @oclif/plugin-update 1.5.0 (core)
        @oclif/plugin-warn-if-update-available 1.7.3 (core)
        @oclif/plugin-which 1.0.4 (core)
        @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
        alias 2.0.0 (core)
        apex 0.11.0 (core)
        auth 1.8.2 (core)
        community 1.1.4 (core)
        config 1.4.0 (core)
        custom-metadata 1.0.12 (core)
        data 0.6.12 (core)
        etcopydata 0.6.4-Beta (beta)
        generator 1.2.2 (core)
        info 2.0.0 (core)
        limits 2.0.0 (core)
        org 1.11.2 (core)
        salesforce-alm 54.1.0 (core)
        schema 2.0.0 (core)
        sfdx-cli 7.146.0 (core)
        source 1.9.3 (core)
        telemetry 1.4.0 (core)
        templates 54.3.0 (core)
        trust 1.1.0 (core)
        user 1.7.1 (core)

 OS and Version:
        Linux 5.10.16.3-microsoft-standard-WSL2
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10996313](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000uwHSOYA2/view)

**Comment by shetzel** [comment]
@daveespo - That tarball is now updated to 7.146.1 which should have a version of the config plugin that works for `config:get`.  Note that it's a patched release we will use to promote to production before creating the next release candidate today (7.147.0) so there will be a few updates today.  As always, thanks for posting and please let me know if 7.146.1 doesn't fix it for you.

**Comment by daveespo** [comment]
Yep, perfect, the 7.146.1 and 7.147.0 builds passed. Thanks for the quick turnaround on the fix!
