### ISSUE TITLE
SyntaxError: Unexpected token '.' when trying to use source commands on Linux with npm sfdx-cli

### ISSUE THREAD

**Issue by danielheadbang** [forcedotcom/cli#1482]
### Summary

When trying to use sfdx commands like force:source:retrieve -m ApexClass, it immediately throws "SyntaxError: Unexpected token '.'", for what I am seeing this is not happening on Windows, I've tried changing the versions but still the same.

### Steps To Reproduce:

1.  Install sfdx on linux
2. Run force:source commands

### Expected result

Command should be executed and components retrieved

### Actual result

Returns "SyntaxError: Unexpected token '.'"

### System Information
	`{
	"cliVersion": "sfdx-cli/7.146.1",
	"architecture": "linux-x64",
	"nodeVersion": "node-v12.22.5",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 2.0.0 (core)",
		"apex 0.11.0 (core)",
		"auth 1.8.2 (core)",
		"community 1.1.4 (core)",
		"config 1.3.30 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.12 (core)",
		"generator 1.2.2 (core)",
		"info 2.0.0 (core)",
		"limits 2.0.0 (core)",
		"org 1.11.2 (core)",
		"salesforce-alm 54.1.0 (core)",
		"schema 2.0.0 (core)",
		"sfdx-cli 7.146.1 (core)",
		"source 1.9.3 (core)",
		"telemetry 1.4.0 (core)",
		"templates 54.3.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.1 (core)"
	],
	"osVersion": "Linux 5.16.19-76051619-generic"
}
`

**Comment by shetzel** [comment]
@danielheadbang - workaround is to use node v14 or higher with the npm install.  The SDR library (used by the source plugin) as well as many of the CLI plugins use the optional chaining syntax which requires v14 or higher.  That's not a new change but something must have changed recently that people are starting to see this.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11027588](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000vQ0L2YAK/view)

**Comment by danielheadbang** [comment]
How do I do that sorry? I ended up going with a workaround without npm as it worked for me, using the https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz file and then my retrieves worked, but would like to know how to fix the npm too :) thanks for the response!

**Comment by danielheadbang** [comment]
I know it's not directly related to the bug but after using that link the node version was higher
`{
	"cliVersion": "sfdx-cli/7.146.1",
	"architecture": "linux-x64",
	"nodeVersion": "node-v16.14.2",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 2.0.0 (core)",
		"apex 0.11.0 (core)",
		"auth 1.8.2 (core)",
		"community 1.1.4 (core)",
		"config 1.3.30 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.6.12 (core)",
		"generator 1.2.2 (core)",
		"info 2.0.0 (core)",
		"limits 2.0.0 (core)",
		"org 1.11.2 (core)",
		"salesforce-alm 54.1.0 (core)",
		"schema 2.0.0 (core)",
		"sfdx-cli 7.146.1 (core)",
		"source 1.9.3 (core)",
		"telemetry 1.4.0 (core)",
		"templates 54.3.0 (core)",
		"trust 1.1.0 (core)",
		"user 1.7.1 (core)"
	],
	"osVersion": "Linux 5.16.19-76051619-generic"
}
`

**Comment by mshanemc** [comment]
For people hitting this--we're about to drop node 12 support when it [goes off of maintenance next weekend](https://nodejs.org/en/about/releases/).

We accidentally did that a tiny bit early by using some newer Promise methods that don't work on 12.  

Use 14, or install from the installer instead of npm (those always use a current node).  This week's RC will formalize that in the `engines` property so you can a nice warning on install instead of this horrible runtime error.
