### ISSUE TITLE
LightningMessageChannel cannot be created using sfdx force:source:deploy or sfdx force:source:push

### ISSUE THREAD

**Issue by constantine-prokopenko-vrp** [forcedotcom/cli#1484]
### Summary

SFDX doesn't want to deploy/convert the LightningMessageChannel.

### Steps To Reproduce:

1. Create new messageChannels/controlChanel.messageChannel and fill it with something like code below.
```
<?xml version="1.0" encoding="UTF-8"?>
<LightningMessageChannel xmlns="http://soap.sforce.com/2006/04/metadata">
    <isExposed>true</isExposed>
    <lightningMessageFields>
        <description>Lorum Ipsum</description>
        <fieldName>action</fieldName>
    </lightningMessageFields>
    <masterLabel>controlChanel</masterLabel>
</LightningMessageChannel>
```

2. Create new Dev/Scratch org

3. Push the code using `sfdx force:source:deploy -p force-app/main/default/messageChannels/controlChanel.messageChannel` or `sfdx force:source:push`

### Expected result

LMS channel deployed with no errors

### Actual result

An object 'controlChanel' of type LightningMessageChannel was named in package.xml, but was not found in zipped directory
This meta file cannot be converted. I'm getting this message trying to convert it - Component conversion failed: messageChannels/controlChanel.messageChanne: Could not infer a metadata type

### System Information

- If you are using `sfdx`
```
{
        "cliVersion": "sfdx-cli/7.146.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.14.2",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/analytics 1.0.6",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-scanner 2.13.1",
                "alias 2.0.0 (core)",
                "apex 0.11.0 (core)",
                "auth 1.8.2 (core)",
                "community 1.1.4 (core)",
                "config 1.3.30 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.12 (core)",
                "generator 1.2.2 (core)",
                "info 2.0.0 (core)",
                "isvte-sfdx-plugin 1.1.15",
                "limits 2.0.0 (core)",
                "org 1.11.2 (core)",
                "salesforce-alm 54.1.0 (core)",
                "schema 2.0.0 (core)",
                "sfdx-cli 7.146.1 (core)",
                "source 1.9.3 (core)",
                "telemetry 1.4.0 (core)",
                "templates 54.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Darwin 21.4.0"
}
```

**Comment by i814u2** [comment]
@constantine-prokopenko-vrp Can you double-check the naming of your file? I tried to duplicate but it worked fine for me.
That said, I'm on one version newer: sfdx-cli/7.147.1 darwin-x64 node-v16.14.2

Also, the filename has to end in messageChannel-meta.xml, not just messageChannel, just in case you copied that and didn't type it wrong.

The reason I mention the naming, is because your example is controlChanel instead of controlChannel. When I named everything as you posted, force:source:push said nothing found. Adding -meta.xml worked without issue. I tried naming the file different from the masterLabel, just to get the same error, but I got nothing (it just kept working).

So, either some details aren't perfect, or 7.147 might fix your issue.

**Comment by constantine-prokopenko-vrp** [comment]
> @constantine-prokopenko-vrp Can you double-check the naming of your file? I tried to duplicate but it worked fine for me. That said, I'm on one version newer: sfdx-cli/7.147.1 darwin-x64 node-v16.14.2
> 
> Also, the filename has to end in messageChannel-meta.xml, not just messageChannel, just in case you copied that and didn't type it wrong.
> 
> The reason I mention the naming, is because your example is controlChanel instead of controlChannel. When I named everything as you posted, force:source:push said nothing found. Adding -meta.xml worked without issue. I tried naming the file different from the masterLabel, just to get the same error, but I got nothing (it just kept working).
> 
> So, either some details aren't perfect, or 7.147 might fix your issue.

You are right.

**Comment by i814u2** [comment]
@constantine-prokopenko-vrp Sounds good, but was it the naming, or the version? I'm asking just so that anyone else finding this can know which detail ended up fixing the situation.

**Comment by constantine-prokopenko-vrp** [comment]
@i814u2 the issue was related to the extension of the file.
The typo in the name worked fine. Once I added the messageChannel-meta.xml extension in lieu of messageChannel the issue vanished.
