### ISSUE TITLE
Deployment Error with Record Types with picklist values.

### ISSUE THREAD

**Issue by vakkalanka123** [forcedotcom/cli#1486]
I'm deploying with github to salesforce but getting these many errors. Record types and list views are under Case object. But it can't deploy that and giving errors. It's not getting the special characters and spaces.

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened_.

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- Paste the output here
### Additional information

![image](https://user-images.githubusercontent.com/100380463/165114292-56c2bcf6-16ac-45da-8f5e-72b05648e7c0.png)

**Comment by mshanemc** [comment]
there's some `System Information` that would make this issue more useful.

It also looks like your Record Type is referring to a picklist value that's not there.  Did the field deploy to the org?
