### ISSUE TITLE
sfdx:create project with manifest failed

### ISSUE THREAD

**Issue by deborahlevycaprtraite** [forcedotcom/cli#149]
I get this error : 
TypeError Plugin: sfdx-cli: Cannot read property 'close' of undefined
module: @oclif/config@1.13.0
task: runHook init
plugin: sfdx-cli

**Comment by lcampos** [comment]
Please provide the following information:

- Salesforce CLI version (can get this by running `sfdx --version` in your terminal)
- Operative System
- the parameters you're using when running this command

**Comment by AkshayDevelopers-cloud** [comment]
Starting SFDX: Authorize an Org

21:59:48.35 sfdx force:auth:web:login --setalias AMaha --instanceurl https://login.salesforce.com --setdefaultusername
(node:636) [ERR_SYSTEM_ERROR] SystemError Plugin: sfdx-cli [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
module: @oclif/config@1.18.3
task: runHook init
plugin: sfdx-cli
root: C:\Users\Dharmendra\AppData\Local\sfdx\client\7.144.2-2fa8aca
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
    SystemError: A system error occurred: uv_os_gethostname returned ENOSYS 
    (function not implemented)
    Code: ERR_SYSTEM_ERROR
21:59:49.250 sfdx force:auth:web:login --setalias AMaha --instanceurl https://login.salesforce.com --setdefaultusername
 ended with exit code 1
