### ISSUE TITLE
SFDX CLI Node Version Errors

### ISSUE THREAD

**Issue by jhgihub0** [forcedotcom/cli#1491]
When we try to deploy our Salesforce project via CLI, it fails on docker and on my local Mac. On a colleague's Mac it works fine.

In all cases, we are running the following commands:
```
sfdx force:auth:web:login --setalias OrgAlias --instanceurl https://test.salesforce.com
sfdx force:source:deploy --targetusername OrgAlias --wait 120 --testlevel 'NoTestRun' --sourcepath ./sfdx-source --checkonly
```

The deployment fails with 32 errors on Docker or my local Mac.

**On Docker Hub image "salesforce/salesforcedx:7.148.1-full"** the `sfdx force:source:deploy` command FAILS with 32 errors
```
sfdx --version
sfdx-cli/7.148.1 linux-x64 node-v16.13.2
```

**On my local Mac** the `sfdx force:source:deploy` command FAILS with 32 errors
```
sfdx --version
sfdx-cli/7.147.1 darwin-x64 node-v16.15.0
```

**On my colleague's Mac** the `sfdx force:source:deploy` PASSES SUCCESSFULLY 
```
sfdx --version
sfdx-cli/7.147.1 darwin-x64 node-v17.8.0
```

The only difference between them is the node version.  My colleague has node-v17.8.0 installed.

How do I upgrade my node version to 17?

**Comment by mshanemc** [comment]
Node 16 should work fine (that's what I'm using right now).  Is there anything interesting about the 32 errors? 

also, can you run `sfdx version --verbose` like the issue template requests so we can see your plugins

**Comment by jhgihub0** [comment]
We found the issues. It was not related to Node. Thank you for the support
