### ISSUE TITLE
Error running force:data:tree:import:  no schema with key or ref "http://json-schema.org/draft-04/schema#"

### ISSUE THREAD

**Issue by sunil-tf** [forcedotcom/cli#1493]
### Summary

After freshly installing sfdx-cli and running force:data:tree:import getting an error no schema with key or ref "http://json-schema.org/draft-04/schema#". Have tried with various sfdx-cli versions 7.134.0 , 7.135.0 , 7.147.1 

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  **Fresh install** sfdx-cli globally using `npm install -g sfdx-cli@7.134.0`    
2.  Clone dreamhouse-lwc and create org and steps as per README.MD
3. run  `sfdx force:data:tree:import -p data/sample-data-plan.json` to import sample data.

### Expected result

Import successful.

### Actual result

Error running force:data:tree:import:  no schema with key or ref "http://json-schema.org/draft-04/schema#"

### System Information

- Run `sfdx version --verbose --json`

   {
        "cliVersion": "sfdx-cli/7.134.0",
        "architecture": "darwin-arm64",
        "nodeVersion": "node-v16.14.2",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.14 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.0 (core)",
                "isvte-sfdx-plugin 1.1.15",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.7.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.134.0 (core)",
                "source 1.8.0 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.1.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Darwin 21.4.0"
}

### Additional information

This error is also reproducible with fresh install of other sfdx-cli versions 7.135.0 , 7.147.1 

My analysis is that due to caret present in the dependency of package.json of plugin-data@0.6.8  has  "@salesforce/core": "^2.31.0",  it picks up the latest released version @salesforce/core@2.36.4
Inside @salesforce/plugin-data/schema/dataImportPlanSchema.json  the  "$schema": "http://json-schema.org/draft-04/schema#" is present which is invalid as per @salesforce/core@2.36.4 -> "ajv": "^8.11.0",

 sfdx-cli@7.134.0 /usr/local/lib/node_modules/sfdx-cli
├─┬ @salesforce/plugin-data@0.6.8
│ └── @salesforce/core@2.36.4 deduped

Same with v7.135.0

sfdx-cli@7.135.0 /usr/local/lib/node_modules/sfdx-cli
├─┬ @salesforce/plugin-data@0.6.8
│ └── @salesforce/core@2.36.4 deduped

package.json of plugin-data@0.6.8  has  "@salesforce/core": "^2.31.0",

Same with v7.147.1
sfdx-cli@7.147.1 /usr/local/lib/node_modules/sfdx-cli
├─┬ @salesforce/plugin-data@0.6.13
│ ├─┬ @salesforce/command@4.2.2
│ │ └── @salesforce/core@2.36.4 deduped
│ └── @salesforce/core@2.36.4

package.json of plugin-data@0.6.13  has  "@salesforce/core": "^2.35.3",

One possible fix could be that inside @salesforce/core  set  validateSchema : false in  src/schema/validator.ts to bypass this error . This will need a release 2.36.5

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11085202](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000wC3HFYA0/view)

**Comment by thvd** [comment]
Already made a PR to fix this https://github.com/forcedotcom/sfdx-core/pull/574

**Comment by iowillhoit** [comment]
Hey @thvd, I did see the PR. Thank you for creating it. The work item is for our internal tracking. 

Thank you also @sunil-tf for the detailed issue!

This actually has more to do with our build process for our `npm` packages. The newest version of `sfdx-core` is brought in because of the caret (described above), but `plugin-data` is pinned in the `package.json`. The [latest version](https://github.com/salesforcecli/plugin-data/pull/297) of `plugin-data` already has the changes needed to work with `AJV v8` update. 

I have a few ideas on this that I am going to discuss with the the team. In the meantime, you can use the `latest-rc` with `npm` (`npm install -g sfdx-cli@latest-rc`). If you _need_ a `latest` or an older version of the CLI, you can use an old "Installer" version or Tarball. The links to download those can be found [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_olderversions)

I am going to leave this open for now and will follow up soon

**Comment by thvd** [comment]
About the use of caret for the install of `sfdx-core`. Given this bug, maybe not the first, isn't it better to use fixed version? I understand there will be cons/pros, curious to hear your thoughts on this.

**Comment by mshanemc** [comment]
this should now be fixed for npm users

@thvd we're planning to put shrinkwrap on the whole thing in the medium term, which solves the problem in a much better way than pinning this library would.

**Comment by thvd** [comment]
@mshanemc that sounds like a good plan! Looking forward to it

**Comment by sunil-tf** [comment]
Thanks @mshanemc @thvd @iowillhoit

**Comment by tggagne** [comment]
> `npm install -g sfdx-cli@latest-rc`

So this is the recommended work-around until `sfdx update` brings down a corrected version?
