### ISSUE TITLE
ServiceCloudVoicePartnerTelephony Feature causes scratch org create to fail

### ISSUE THREAD

**Issue by rob-sanuk** [forcedotcom/cli#1495]
### Summary
ServiceCloudVoicePartnerTelephony Feature causes scratch org create to fail

### Steps To Reproduce:
1. Create project-scratch-def.json file in the config folder of the project as below:
{
  "orgName": "orgName",
  "edition": "Enterprise",
  "features": [
    "ServiceCloud",
    "ServiceUser",
    "LightningServiceConsole",
    "ServiceCloudVoicePartnerTelephony:1"
  ],
  "settings": {
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    },
    "omniChannelSettings": {
      "enableOmniChannel": true
    }
  }
}

2. Run the following command to create a scratch org:
sfdx force:org:create -f config/project-scratch-org-def.json

3. View Error:
ERROR running force:org:create:  An unknown server error occurred. Please try again. If you still see this error, contact Salesforce support for assistance. Include the information from 'sfdx force:data:record:get -s ScratchOrgInfo -i 2SR4L000000Gy6oWAC -u ‘xxxx’.

4. Run command:
sfdx force:data:record:get -s ScratchOrgInfo -i 2SR4L000000Gy6oWAC -u ‘xxxx’

5. View response:
attributes:
  type: ScratchOrgInfo
  url: /services/data/v54.0/sobjects/ScratchOrgInfo/2SR4L000000Gy6tWAC
Id: 2SR4L000000Gy6tWAC
OwnerId: 0054L000003oWhwQAE
IsDeleted: false
Name: 00000788
CreatedDate: 2022-05-04T14:55:15.000+0000
CreatedById: 0054L000003oWhwQAE
LastModifiedDate: 2022-05-04T14:55:28.000+0000
LastModifiedById: 0054L0000013t5oQAA
SystemModstamp: 2022-05-04T14:55:28.000+0000
LastViewedDate: 2022-05-04T14:55:28.000+0000
LastReferencedDate: 2022-05-04T14:55:28.000+0000
Edition: Enterprise
Username: null
OrgName: orgName
DurationDays: null
ConnectedAppConsumerKey: PlatformCLI
ConnectedAppCallbackUrl: https://urldefense.com/v3/__http://localhost:1717/OauthRedirect__;!!GF_29dbcQIUBPA!wYkMp1K451Lg4wAc_oq0ZGGo3nqwr37vSzQF0qFlrqzQ3jnN0bFXI_bLBI5X53sKaG-P6xtF7XqdR5phh2OvsgLg912b39EjBi8$ [localhost]
Namespace: null
Features: ServiceCloudVoicePartnerTelephony:1;ServiceCloud;ServiceUser;LightningServiceConsole
Country: null
Language: null
Instance: null
Package2AncestorIds: null
SourceOrg: null
HasSampleData: false
Release: Current
SignupUsername: test-xwxnsd9f8e1h@example.com
Status: Error
ErrorCode: null
ScratchOrg: null
SignupInstance: null
AuthCode: null
SignupCountry: GB
SignupLanguage: en_US
SignupEmail: robert.matthews@santander.co.uk
SignupTrialDays: 7
LoginUrl: null
Description: null
ExpirationDate: 2022-05-11
LastLoginDate: null
DeletedBy: null
DeletedDate: null
Getting Record... done

6. Edit project-scratch-def.json file and remove "ServiceCloudVoicePartnerTelephony:1"
Try and create. anew scratch org with this file as the definition and the scratch org is created.

### Expected result
Scratch Org created with Service Cloud Voice with Partner Telephony enabled

### Actual result
ERROR running force:org:create:  An unknown server error occurred. Please try again. If you still see this error, contact Salesforce support for assistance. Include the information from 'sfdx force:data:record:get -s ScratchOrgInfo -i 2SR4L000000Gy6oWAC -u ‘xxxx’.

### System Information
{
  "cliVersion": "sfdx-cli/7.148.3",
  "architecture": "win32-x64",
  "nodeVersion": "node-v16.14.2",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 0.3.0 (core)",
    "@oclif/plugin-commands 1.3.0 (core)",
    "@oclif/plugin-help 3.3.1 (core)",
    "@oclif/plugin-not-found 1.2.6 (core)",
    "@oclif/plugin-plugins 1.10.11 (core)",
    "@oclif/plugin-update 1.5.0 (core)",
    "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
    "@oclif/plugin-which 1.0.4 (core)",
    "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
    "alias 2.0.0 (core)",
    "apex 0.11.0 (core)",
    "auth 2.0.2 (core)",
    "community 1.1.4 (core)",
    "config 1.3.30 (core)",
    "custom-metadata 1.1.0 (core)",
    "data 0.6.13 (core)",
    "generator 1.2.2 (core)",
    "info 2.0.0 (core)",
    "limits 2.0.0 (core)",
    "org 1.11.2 (core)",
    "salesforce-alm 54.2.0 (core)",
    "schema 2.0.0 (core)",
    "sfdx-cli 7.148.3 (core)",
    "signups 1.0.0 (core)",
    "source 1.9.3 (core)",
    "telemetry 1.4.0 (core)",
    "templates 54.3.0 (core)",
    "trust 1.1.0 (core)",
    "user 1.7.1 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19042"
}

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11104593](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000wRzSaYAK/view)

**Comment by iowillhoit** [comment]
Thanks for the detailed issue @rob-sanuk. This scratch org creation error will need to be looked at by another team. I've created a work item and assigned it over to them. I will post back when I've received a reply.

**Comment by mshanemc** [comment]
This was fixed by another team in Aug 2022.
