### ISSUE TITLE
PATH not updated, original length 1286 > 1024

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1500]
### Summary

I tried to install sfdx using the .exe and this error happened. I had to manually add the env prop to my path.

![image](https://user-images.githubusercontent.com/55927613/167273868-48733a58-c021-46d1-9bbf-c9ef7818f9b5.png)

**Comment by iowillhoit** [comment]
Hey @AllanOricil, have you faced this issue before? It sounds to me that your `PATH` variable has grown over time and now is running up against this `1024` character check. Could you please review the paths/variables that are set on your `PATH` and remove any that are no longer needed? If you are able to shorten the set `PATH`, I don't think this will be an issue any longer. Let me know if that works! Thanks

**Comment by AllanOricil** [comment]
I actually added the sfdx binnary path into path without deleting any other entry. And this is why I thought this error message was weird. I don't think windows is limiting this update.

**Comment by iowillhoit** [comment]
I did a little bit more digging on this. It is a limitation of the [NSIS installation system](https://nsis.sourceforge.io/Path_Manipulation#Warning) itself. [Oclif is doing a check](https://github.com/oclif/oclif/blob/acd986d53681b3840f17220b6e16fd8bb3c869f7/src/commands/pack/win.ts#L114) for `$PATH` length to make sure that NSIS fails gracefully and doesn't get into a bad state. 

It does look like NSIS has a special build that will allow for longer `$PATH` length but this is not likely something that we will invest dev time in at the moment. If we receive several more reports of this being a blocker, we can open an issue on oclif.  

If this is a persistent problem for you, I would encourage you to audit your current `$PATH` and see if there is anything that is no longer being used. Thank you for creating this issue @AllanOricil, have a good one!

**Comment by matcaampos** [comment]
Hi everyone, I'm passing for this error and my vs code not recognize my sfdx, how to resolve this error? Which path i gave to audit?

**Comment by aspnerd** [comment]
I'm having this same issue and it's a blocker for us

**Comment by AllanOricil** [comment]
You have to edit the PATH env variable on your OS and remove some characters from it because it has a size limit. Just ask chatgpt "how to edit the PATH env variable on TYPE_OS_NAME ?"

**Comment by OmarGonD** [comment]
This is a problem, will make delete other variables, difficulting devlopers adoption.

**Comment by AllanOricil** [comment]
The installer could show a link where the User can learn how to fix the issue

**Comment by KrzysztofB666** [comment]
This is still an ongoing issue, 3 years later - nothing fixed...

**Comment by AllanOricil** [comment]
This issue could be mitigate but won't ever be fixed because there is no way to change the length of PATH

https://superuser.com/questions/387619/overcoming-the-1024-character-limit-with-setx

This issue is old and I don't think microsoft would ever change it

https://answers.microsoft.com/en-us/windows/forum/all/how-to-make-the-path-enviornment-variable-longer/fa1a19ad-4e66-446f-ad97-cc35fdcb8641

Because it is an issue that very few people will face, and that can be fixed easily by the end user, by manually editing their PATH, it is not worthy spending engineering time automating a fix that won't ever really fix the root cause.

The quickest, and cheapest, solution was making this github page indexed in Google so that these very few people could find it. You're welcome 😊 

I usually open github issues with the error message so that it can help other people 😄
