### ISSUE TITLE
Unable to create a Preview Org

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#1502]
### Summary

I am tying to create a developer org for Summer '22. I have the following in my project-scratch-def.json
"edition": "Developer", "release": "Preview",

I am getting the error

> At this time, we are outside of the preview period. You can create only current release scratch orgs.

I first tried it on May 9th which is within the window for the preview. I have also attempted today as well, to no avail.

As per this [link](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_version_selection.htm) it should work after May 6th.

I believe in the past, there has been a workaround of signing up for a Preview org, and turning it into a Devhub to make scratches from. I will look to do that in the meantime. 

### Steps To Reproduce:

1.  update your scratch definition file to have `"release": "Preview"`
1.  attempt to create a scratch org

### Expected result

a Scratch org is created with the Salesforce Summer '22 release in it

### Actual result

Recieved 'At this time, we are outside of the preview period. You can create only current release scratch orgs.'

### System Information
{
        "cliVersion": "sfdx-cli/7.148.3",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.10.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-scanner 2.12.0",
                "alias 2.0.0 (core)",
                "apex 0.11.0 (core)",
                "auth 2.0.2 (core)",
                "community 1.1.4 (core)",
                "config 1.3.30 (core)",
                "custom-metadata 1.1.0 (core)",
                "data 0.6.13 (core)",
                "generator 1.2.2 (core)",
                "info 2.0.0 (core)",
                "limits 2.0.0 (core)",
                "org 1.11.2 (core)",
                "salesforce-alm 54.2.0 (core)",
                "schema 2.0.0 (core)",
                "sfdx-cli 7.148.3 (core)",
                "signups 1.0.0 (core)",
                "source 1.9.3 (core)",
                "telemetry 1.4.0 (core)",
                "templates 54.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.5.0"
        ],
        "osVersion": "Darwin 20.6.0"
}

**Comment by iowillhoit** [comment]
Morning @nBray-tLP, this is a known issue. I am hoping to have an external link that you could track this issue here soon. Thanks for your patience!

**Comment by jfeng-salesforce** [comment]
Hi @nBray-tLP , here is the Known Issue link: https://trailblazer.salesforce.com/issues_view?id=a1p4V000002CMNgQAO

Thank you again for your patience!

**Comment by ghost** [comment]
awesome, thanks! I'll just close this then.

**Comment by jfeng-salesforce** [comment]
Hi @nBray-tLP , the fix is being deployed now; thank you again for your patience!
