### ISSUE TITLE
Unable deploy wave dashboard metadata with any Salesforce API version

### ISSUE THREAD

**Issue by AzaruddinKhan** [forcedotcom/cli#1509]
Error when tried to deploy the wave dashboard through meta data api 

### Steps To Reproduce:

1. retrieve the wave dashboard from the org
2. deploy the same wave dashboard to the org with same api version / package.xml version

### Expected result
Should be able to deploy successfully without any issue
--

### Actual result

Property 'dateVersion' not valid in version 51.0
--

### System Information

        "cliVersion": "sfdx-cli/7.133.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.4.2",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.14 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.7.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.133.0 (core)",
                "sfdx-git-delta 4.11.0",
                "source 1.7.0 (core)",
                "telemetry 1.4.0 (core)",
                "templates 52.7.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Darwin 21.1.0"

**Comment by micha-voigt** [comment]
Same issue after getting retrieving wave dashboard from production org and trying to deploy to any sandbox.
Analytics-Lens ... Property 'dateVersion' not valid in version 52.0

Issue came up in the last 2 days, may be related to spring/summer release switch?
sfdx-cli/7.150.0 win32-x64 node-v16.15.0

**Comment by shetzel** [comment]
What commands are you using to retrieve and deploy?  `force:mdapi:retrieve` (and deploy) or `force:source:retrieve` (and deploy)?

When you retrieve/deploy, are you specifying an API version?  If not, the retrieve could be coming down with metadata versions matching the API version of your org.  You might then be deploying as the API version specified by your project.  The error message from your post is what you would see in this case.  I would try a few things to confirm:

1. set the `SFDX_MDAPI_TEMP_DIR` env var to some location and check API versions in the package.xml after the retrieve and the deploy.
2. run the commands with `--dev-debug` to get additional debug output and look for API version differences.  Compare that with what is in your `sfdx-project.json` file for sourceApiVersion and the output of running `sfdx config:list` in your project, looking for API_VERSION or apiVersion values.

**Comment by AzaruddinKhan** [comment]
Hi Shetzel,

Thanks for your inputs.

I am actually passing the below in package.xml & sfdx-project.json version and using the option[SFDX:Retrieve Source in Manifest from Org] visual studio code.
------------
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
<types>
	<members>Track_Files_and_Attachments</members>
	<name>WaveDashboard</name>
</types>
<version>51.0</version>
</Package>
-------

{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "name": "Test-profile",
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "51.0"
}

I am able to retrieve the files but when I try to deploy that back to same org I am getting this error.

**Property 'dateVersion' not valid in version 51.0**

I tried this with 52 and 53 version both in package.xml and also sfdx-project.json files.
I looked for this error in community but no luck.

What would be the fix for this ? Is it bug ? I am observing this after summer'22 release

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11166186](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xJvG8YAK/view)

**Comment by shetzel** [comment]
Retrieving from the VS Code extension is similar but not exactly the same.  Retrieve source from manifest means you're pointing to a manifest file.  Does the manifest have `<version>51.0</version>` in the contents?  Does this reproduce with the CLI by running:
`sfdx force:source:retrieve -x <path-to-manifest> -u <org-username>`  (optionally append `--apiversion=51.0`)
`sfdx force:source:deploy -x <path-to-manifest> -u <org-username>`

If you are specifying API version 51.0 and the retrieved dashboard contains `dateVersion` then that would be a serverside problem and the owning team (i.e., not CLI) would have to fix it.  The work item attached to this issue will handle that.

**Comment by shetzel** [comment]
@AzaruddinKhan  @micha-voigt - I've heard from the owning team that it's a serverside bug that was recently fixed and in the process of being rolled out.  I will try to get dates for you.  If you are seeing this fixed already please let me know here.

**Comment by shetzel** [comment]
The fix should be available now.  Please reopen if you're still seeing problems.
