### ISSUE TITLE
Salesforce CLI returning status of exit code 1

### ISSUE THREAD

**Issue by marsh-mellow** [forcedotcom/cli#1510]
### Summary

Saleforce CLI has been recently updated and started throwing errors in our build scripts. After investigating we saw the the CLI commands are returning exit code of 1 (Fail) instead of 0 (Pass) when the script successfully executes.

This happens for creating scratch org, installing packages and from what I can tell all of the commands.

### Steps To Reproduce:

1. sfdx force:community:publish -n your_test_community
2. echo $? <-- show you the status of previous command

Similarly you can script if and catch error like so
if ! sfdx force:community:publish -n your_test_community; then
  echo "Publishing Community] failed."
fi

### Expected result

Return status 0

### Actual result

Return Status 1

### Additional information

Running this in GIT BASH terminal (MINGW64)

CLI Version : 
        sfdx-cli/7.150.0

 Architecture:
        win32-x64

 Node Version :
        node-v16.15.0

 Plugin Version:
        @oclif/plugin-autocomplete 0.3.0 (core)
        @oclif/plugin-commands 1.3.0 (core)
        @oclif/plugin-help 3.3.1 (core)
        @oclif/plugin-not-found 1.2.6 (core)
        @oclif/plugin-plugins 1.10.11 (core)
        @oclif/plugin-update 1.5.0 (core)
        @oclif/plugin-warn-if-update-available 1.7.3 (core)
        @oclif/plugin-which 1.0.4 (core)
        @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
        alias 2.0.0 (core)
        apex 0.11.0 (core)
        auth 2.0.2 (core)
        community 1.1.4 (core)
        config 1.4.6 (core)
        custom-metadata 1.1.0 (core)
        data 0.6.15 (core)
        generator 2.0.0 (core)
        info 2.0.0 (core)
        limits 2.0.0 (core)
        org 1.12.1 (core)
        salesforce-alm 54.3.0 (core)
        schema 2.1.0 (core)
        sfdx-cli 7.150.0 (core)
        signups 1.0.0 (core)
        source 1.9.7 (core)
        telemetry 1.4.0 (core)
        templates 54.6.0 (core)
        trust 1.1.0 (core)
        user 1.7.1 (core)

 OS and Version:
        Windows_NT 10.0.19044

**Comment by frederikhors** [comment]
This happens using `heroku` CLI too. Please, this is HUGE!

**Comment by iowillhoit** [comment]
I just tried to replicate using the community command above and using `7.150.0` on a mac. @marsh-mellow can you please run a command with `--dev-debug` to see if we can get more information from the command as to what might be happening? Are you able to pin this down to a specific version of `sfdx` that this started happening in? That could really help narrow this down. 

@frederikhors are you also on a windows machine?

**Comment by iowillhoit** [comment]
Also @marsh-mellow, you mentioned this is happening on `from what I can tell all of the commands`. If possible, can you provide a simple one-off command (like `force:org:list`) that you can confirm exits with a non-zero exit code? Publishing a community takes a little setup, I would like to have a simple command for one of our Windows engineers test with. Thank you

**Comment by frederikhors** [comment]
@iowillhoit I'm on WIndows 10.

You can reproduce it like this:

1. Install Git with Git bash
1. Open PowerShell
1. Launch `sh.exe`
1. Execute commands like `heroku restart`
1. The command works but the exit code is 1

It works on PowerShell but not on Git Bash or sh (which git bash uses underneath)

**Comment by iowillhoit** [comment]
Sorry @frederikhors and @marsh-mellow, we unfortunately we do not support GitBash on Windows. See the warning text under the `Install the CLI on Windows` [here](https://developer.salesforce.com/docs/atlas.en-us.236.0.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#:~:text=Salesforce%20CLI%20works%20best%20within%20the%20native%20Windows%20command%20prompt%20(cmd.exe)%20and%20the%20Microsoft%20Windows%20PowerShell.%20We%20don%E2%80%99t%20recommend%20using%20Salesforce%20CLI%20with%20a%20Linux%20terminal%20emulator%2C%20such%20as%20Windows%2010%20Subsystem%20for%20Linux%2C%20cygwin%2C%20or%20MinGW%2C%20because%20support%20for%20bugs%20is%20limited.). Please let us know if you see this issue in Command Prompt or PowerShell. Thank you.

**Comment by marsh-mellow** [comment]
That is too bad. Do you support Git Bash on Mac?

**Comment by marsh-mellow** [comment]
Also note everything was working properly until recent changes to CLI

**Comment by marsh-mellow** [comment]
@iowillhoit looking at the link you sent. Technically there is nothing about not supporting, just that support is limited. I assume it means that one guy on the team that uses bash on windows. If support is truely non-exisitant can you include when this support stopped and ask to have the website reflect that. I need to report back to management about estimates to move all our scripts to powershell. Thanks for all the help on this

**Comment by RodEsp** [comment]
Heya @marsh-mellow 👋🏼
I'm the "one guy on the team" that uses Windows, but I don't use Git Bash because there have been numerous unexplainable issues with it in the past. It's not so much a matter of not supporting it but issues with it are usually very hard to debug and fall so low on our priority list we usually won't ever get to them. Which is why we _highly_ recommend using Powershell. If previous versions of the CLI have worked flawlessly with Git Bash on Windows that's mostly just a happy coincidence, not because we ever fully supported it.

Bash is already the shell used on Mac's terminal, which is fully supported (everyone else on the team uses Mac and bash or zsh). Afaik there's no such thing as "Git Bash on Mac".

**Comment by marsh-mellow** [comment]
Haha. Thanks for the reply and the detailed explanation. We also have a
mixed team and want to share scripts across OS's ... Hence bash for
Windows. We will need to come up with a workaround for now. Anyway to keep
this ticket open for the backlog? Even if it's low priority.

**Comment by RodEsp** [comment]
No problem, and I feel your pain with cross-OS scripting, we often deal with that too. Something that's worked for us is writing scripts in JavaScript which can be run with [`node`](https://nodejs.org/en/) in any OS but that's certainly more complicated than just using Bash.

We have a bot that automatically closes issues after a certain number of days without activity so even if we re-open this issue it'll be closed again. If for some reason this ends up being a complete deal-breaker for your company's use of the CLI please open a support ticket with Salesforce Customer Support and that'll get it onto our internal backlog.

**Comment by marsh-mellow** [comment]
JS is a great idea. Thanks for that. I will run by our team and see how
they feel.
