### ISSUE TITLE
mdapi deploy issue

### ISSUE THREAD

**Issue by mundsambit007** [forcedotcom/cli#1517]
### Details

- With the new GA on beta as I see  for mdapi commands - mdapi deploy command is being skipped in the CICD pipeline - I am using GH Actions for this
- The same works fine with source command

### Usage: 

> sfdx force:mdapi:deploy -d mdapi-source -u QA_ORG -l RunLocalTests -w 120

### Expected - 

> TO kick off deployment 

### Actual - 

- Skips the execution of this command
- the actual deployment takes around 7 minutes :

### PFB 
![image](https://user-images.githubusercontent.com/57349844/168534690-11053197-b8bf-4f1d-aee0-007e443074aa.png)

**Comment by SoftCreatR** [comment]
See #1508

**Comment by mundsambit007** [comment]
@SoftCreatR  - Thanks ! I am following it up here and have opened an SF case as well. I had switched it to legacy. It works fine .

**Comment by iowillhoit** [comment]
@SoftCreatR On the surface this looks unrelated to the `--wait -1` issue that others are reporting. I am surprised this is acting this way. Could you please run this command with `DEBUG=*` and share the output? Thanks! 

`DEBUG=* sfdx force:mdapi:deploy -d mdapi-source -u QA_ORG -l RunLocalTests -w 120`

**Comment by shetzel** [comment]
I can't reproduce this.  The command as you have it should work.  I was able to deploy the dreamhouse-lwc project with the exact command you're using and the latest CLI and plugins.  Is it possible there's something else going on like the `mdapi-source` dir is empty?  Can you post the output of `sfdx version --verbose` as well?

**Comment by AzaruddinKhan** [comment]
I am facing the same issue after the recent Summer'22 release.
The deployments just struck in the queue and never picked up for deployment. There is something went wrong after the Summer'22 I think.

There is no work around as such for this , I tried with below , still it didn't pick up the deployment.

sfdx force:source:deploy -x manifest/package.xml -u qa --testlevel NoTestRun

When I check in the morning hours there is no issue, it works fine but all of sudden the deployments get struck in queue.

**Comment by iowillhoit** [comment]
@AzaruddinKhan what your are describing sounds like the known performance degradation being discussed in https://github.com/forcedotcom/cli/issues/1522. Especially since you are able to deploy just fine during "off hours"

**Comment by shetzel** [comment]
This should be fixed in the latest CLI.  Please reopen if you're on the latest and still seeing the same behavior.
