### ISSUE TITLE
MDAPI deploy from a folder fails in 7.150.0 because of a timeout but in the background actually deploys to the target org

### ISSUE THREAD

**Issue by ganesh2109-cloud** [forcedotcom/cli#1519]
### Summary

MDAPI deploy from a folder fails in 7.150.0

### Steps To Reproduce:
Run mdapi deploy command:
sfdx force:mdapi:deploy -d ./deploy -w -1 --json

### Expected result

Contents of deploy folder should be deployed

### Actual result

{
  "status": 1,
  "result": {
    "id": "0Af0Q00001tUMXvSAO"
  },
  "name": "MetadataTransferError",
  "message": "Metadata API request failed: The client has timed out.",
  "exitCode": 1,
  "actions": [],
  "commandName": "Deploy",
  "data": {
    "id": "0Af0Q00001tUMXvSAO"
  },
  "stack": "MetadataTransferError: Metadata API request failed: The client has timed out.\n    at MetadataApiDeploy.pollStatus (node_modules\\sfdx-cli\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\client\\metadataTransfer.js:81:27)\n    at async Deploy.deploy (C:\\Users\\M65F134\\Downloads\\node-v18.1.0-win-x64\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\mdapi\\deploy.js:69:33)\n    at async Deploy.run (node_modules\\sfdx-cli\\node_modules\\@salesforce\\plugin-source\\lib\\commands\\force\\mdapi\\deploy.js:25:9)\n    at async Deploy._run (node_modules\\sfdx-cli\\node_modules\\@salesforce\\plugin-source\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:81:40)\n    at async Config.runCommand (node_modules\\sfdx-cli\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async SfdxMain.run (node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n  
  at async SfdxMain._run (node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (node_modules\\sfdx-cli\\dist\\cli.js:162:47)",
  "warnings": [
    "apiVersion configuration overridden at \"53.0\""
  ]
}
### System Information

{
        "cliVersion": "sfdx-cli/7.150.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v18.1.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",    
                "@oclif/plugin-help 3.3.1 (core)",        
                "@oclif/plugin-not-found 1.2.6 (core)",   
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.0 (core)",
                "apex 0.11.0 (core)",
                "auth 2.0.2 (core)",
                "community 1.1.4 (core)",
                "config 1.4.6 (core)",
                "custom-metadata 1.1.0 (core)",
                "data 0.6.15 (core)",
                "generator 2.0.0 (core)",
                "info 2.0.0 (core)",
                "limits 2.0.0 (core)",
                "org 1.12.1 (core)",
                "salesforce-alm 54.3.0 (core)",
                "schema 2.1.0 (core)",
                "sfdx-cli 7.150.0 (core)",
                "signups 1.0.0 (core)",
                "source 1.9.7 (core)",
                "telemetry 1.4.0 (core)",
                "templates 54.6.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}

**Comment by rrhodes** [comment]
Also experiencing this issue since v7.150.0

**Comment by mshanemc** [comment]
looks like `-w -1` isn't working like it's supposed to.  As a workaround while we get that fixed, you can change `-w` to some large number.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11147622](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000x9CzeYAE/view)

**Comment by iowillhoit** [comment]
👋 The `--wait -1` (`-w -1`) bug has been fixed in latest-rc version `7.151.1`. This will be promoted to latest tomorrow (Thursday). The help docs have also been updated to make this functionality more clear.

• Update with npm: npm install -g sfdx-cli@latest-rc
• Update with Installer: sfdx update stable-rc (run sfdx update stable to rollback)

Please let us know if you continue to have issues. Thanks for everyone's patience while it got this fixed!

**Comment by iowillhoit** [comment]
Hello again, `sfdx` version `7.151.1` has been promoted to latest! This should fix all of the `--wait -1` issues. If you are still having issues please open a new ticket with steps to reproduce. Thanks!

Note that we are still seeing some performance degradation with deploys to sandboxes https://github.com/forcedotcom/cli/issues/1522
