### ISSUE TITLE
Symbolic link no longer working 

### ISSUE THREAD

**Issue by fischerp** [forcedotcom/cli#152]
### Summary

Symbolic links are no longer working, at least they are not when using salesforce-cli v46.9.0.
It does work when using version 46.6.0.

The deployment process started throwing all sort of errors:
In field: page - no ApexPage named CLASS found
The specified Static Resource is not a valid zip file
Required field is missing: content
Component c:COMPONENT_NAME does not exist
It turned out that the missing files were symbolic links, so it started working again after downgrading to Salesforce DX 46.6.0.

### Steps To Reproduce:

1. Add a symbolic link to your project
2. Push the code

### Expected result
SFDX should push all files from the symbolic link to Scratch orgs.

### Actual result
It reports that files are missing or arbitrary errors, but all because files were not found.

### Additional information
**Doesn't work** sfdx plugins:install salesforcedx@46.9.0
**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.18.0-ee5dc8194c darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.0 (core)
generator 1.1.0 (core)
salesforcedx 46.9.0 (46.9.0)
├─ force-language-services 46.13.0
└─ salesforce-alm 46.12.0

**Does work** sfdx plugins:install salesforcedx@46.6.0
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.0 (core)
generator 1.1.0 (core)
salesforcedx 46.6.0 (46.6.0)
├─ force-language-services 46.11.0
└─ salesforce-alm 46.10.0

**OS and version**:
Mac OS

**Comment by tnoonan-salesforce** [comment]
So you have a valid SFDX project that contains a symbolic link to other Salesforce metadata?

Can you provide a very simplified set of steps to set up this scenario?

More details than 'Add a symbolic link to your project'. Whats does the symlink point to? How did you create the symlink? Whats the owner, group, and permission? Where in the project is the symlink created?

**Comment by davidknoll** [comment]
My project was originally arranged as I saw fit and deployed piecemeal with change sets. The SFDX side I retrofitted on top with a bunch of symlinks to the actual classes etc.

**Comment by fischerp** [comment]
Hi @tnoonan-salesforce,  
I'm using VS code and Mac OS, but here are the steps: I can provide you the project, but there is nothing special, please let me know if you still need it.

1. Create a new SFDX project
2. Create a scratch org
3. Login on this scratch org to create a class called hello.cls
4. On VsCode, pull changes to your local project
5. Move this class and its metadata to a folder on your desktop, I suggested ".git_externals" as your folder name
6. Create a file symbolic link from your desktop .../Desktop/.git_externals/hello.cls to your project class folder (...force-app/main/default/classes)
7. Create a file symbolic link from your desktop .../Desktop/.git_externals/hello.cls-meta.xml to your project class folder (...force-app/main/default/classes/hello.cls-meta.xml)
8. Change the content of the hello.cls class, can be an empty space
9. Push the code to your org
10. If if fails, execute this command "sfdx plugins:install salesforcedx@46.6.0" and it will work
11. To make it fail again, execute  "sfdx plugins:install salesforcedx@46.9.0" or "sfdx plugins:install salesforcedx@46.10.2"

I hope you can find this helpful, thanks! 
Note that some folks have reported same problem using Linux, I'm not sure about Windows.

**Comment by fischerp** [comment]
I'm afraid you will not be able to reproduce on Windows, but people have reported same thing on Mac Os and Linux. 
Note: 100% of our developers are getting exactly the same problem.

Here is the project that I've created: 
https://github.com/fischerp/sfdxFileSymbolicLink

**Comment by fischerp** [comment]
This bug has been accepted by Salesforce. 
Bug Number #W-6535313

**Comment by fischerp** [comment]
It has been fixed on version 46.15.3 (September 19, 2019).

"FIX: On macOS, the temporary zip file created when running force:source:push, force:source:deploy, or force:mdapi:deploy once again contains files that are symbolically linked."
Source: https://developer.salesforce.com/media/salesforce-cli/releasenotes.html

Please close this issue.

**Comment by jefersonchaves** [comment]
This problem is happening again with the latest version 👎

**Comment by fischerp** [comment]
Yes, the issue is back! I've reopened this ticket. Thanks Jeferson! Maybe some sort of unit testing can prevent releasing future versions with this bug again, which is very annoying!

**Comment by jefersonchaves** [comment]
The last version I'm sure it worked so far is v49.2.3.
This is what I currently have installed:
CLI:
```
sfdx-cli/7.72.0-697e9faee2 darwin-x64 node-v12.18.3
```
Plugins:
```
@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.5.1
├─ @oclif/plugin-update 1.3.9
└─ @oclif/plugin-help 2.2.0
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.2.1 (core)
analytics 1.12.0 (core)
config 1.1.6 (core)
generator 1.1.3 (core)
salesforcedx 49.2.3 (49.2.3)
├─ custom-metadata 1.0.10
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ salesforcedx-templates 48.32.0
└─ salesforce-alm 49.3.0
sfdx-cli 7.72.0 (core)
```

**Comment by jefersonchaves** [comment]
This is broken in v50, is this yous can take a look?
@tnoonan-salesforce or @ntotten?

**Comment by jefersonchaves** [comment]
Is there anything I could do to help?

**Comment by amphro** [comment]
I'm a little confused this is still an issue. It said the fix was in [`1.2.0`](https://github.com/archiverjs/node-compress-commons/pull/23) and we are shipping with `1.3.0`. 

```
-> yarn add sfdx-cli
....
-> yarn why archiver
yarn why v1.22.0
[1/4] 🤔  Why do we have the module "archiver"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "archiver@1.3.0"
info Reasons this module exists
   - "sfdx-cli#salesforcedx#salesforce-alm" depends on it
   - Hoisted from "sfdx-cli#salesforcedx#salesforce-alm#archiver"
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "6.31MB"
info Disk size with transitive dependencies: "7.59MB"
info Number of shared dependencies: 31
....
```

I wonder if we upgrade to `archiver@4` if that will solve the issue, but I don't know the implications of those major version bumbs.

**Comment by amphro** [comment]
Hmm, I still see some weird behavior with `archive@4`

```
TYPE   PROJECT PATH                                           PROBLEM
─────  ─────────────────────────────────────────────────────  ───────────────────────────
Error  force-app/main/default/apex/SymLinkClass.cls           Unexpected token '.'. (1:1)
Error  force-app/main/default/apex/SymLinkClass.cls-meta.xml  Invalid api version:0.0
```

Marking as a bug but I'm not sure when we will be able to get to this.

**Comment by jefersonchaves** [comment]
Hey, @amphro, thanks for the update, that is actually great info. Let me see if I can find something to help yous out.

Cause this really hurt us given we use symbolic links to share code.

**Comment by WillieRuemmele** [comment]
Hi @jefersonchaves @fischerp, I believe this issue is related to HOW you are creating the symlink. Following [these](https://github.com/forcedotcom/cli/issues/152#issuecomment-525140409) steps, it was still failing.

I was following those steps by initially symlink with the command 
```
ln -s ../../../Desktop/classes/hello.cls force-app/main/default/classes 
ln -s ../../../Desktop/classes/hello.cls-meta.xml force-app/main/default/classes
```
after doing some [reading](https://apple.stackexchange.com/questions/115646/how-can-i-create-a-symbolic-link-in-terminal) (the last comment) on symlinks I tried using an absolute path like
```
 ln -s ~/Desktop/classes/hello.cls force-app/main/default/classes
 ln -s ~/Desktop/classes/hello.cls-meta.xml force-app/main/default/classes
```
and `source:push`, `source:beta:push`, and `source:deploy` all worked as expected. Try symlinking with absolute paths and let me know how it goes 👍

**Comment by vytautasgermanavicius** [comment]
@WillieRuemmele force:source:deploy does not work with symlinks: neither symbolic, nor absolute. 

```
$ sfdx -v
sfdx-cli/7.132.0 linux-x64 node-v16.13.1
$ ls -la "./vendors/SObjectFabricator"
lrwxrwxrwx 1 vytautas vytautas 32 saus.  12 11:19 ./vendors/SObjectFabricator -> ../modules/SObjectFabricator/src
$ sfdx force:source:deploy  -p "./vendors/SObjectFabricator"
ERROR running force:source:deploy:  /home/░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░/vendors/SObjectFabricator: Could not infer a metadata type
$ sfdx force:source:deploy  -p ./modules/SObjectFabricator/src/
*** Deploying with SOAP API v53.0 ***
Deploy ID: 0░░░░░░░░░░░░░░░D
SOURCE PROGRESS | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/13 Components
```
