### ISSUE TITLE
Mdapi deployment gets stuck in the queue, even when there are no other deployments in progress.

### ISSUE THREAD

**Issue by patrykacc** [forcedotcom/cli#1522]
### Summary

Mdapi deployment gets stuck in the queue, even when there are no other deployments in progress.

### Steps To Reproduce:

1.  Prepare package for deployment
2. run force:legacy:mdapi:deploy  

### Expected result

Deployment in sandbox starts immediately when there is no other deployment in progress,  or gets into a queue when there is another deployment/validation in progress.

### Actual result

Deployment job gets into queue, and stays there for hours, even when there is no any deployment in progress
Each next submitted deployment lands in queue as well

I tested this on multiple orgs, and for 2 out of 5 of them, it happens currently. Also, the nature of this wrong behavior is a bit random because it starts to happen this way one day, and the next day it's all fine again, then after some days strikes again.

Killing jobs manually in the sandbox and rerunning doesn't help, following jobs are stuck in the same way in the queue. That would mean that its issue is related to the sandbox state rather than a particular deployment.

### System Information

sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3

**Comment by AzaruddinKhan** [comment]
I am facing the same issue after the recent Summer'22 release.
The deployments just struck in the queue and never picked up for deployment. There is something went wrong after the Summer'22 I think.

There is no work around as such for this , I tried with below , still it didn't pick up the deployment. 

sfdx force:source:deploy -x manifest/package.xml -u qa --testlevel NoTestRun


When I check in the morning hours there is no issue, it works fine but all of sudden the deployments get struck in queue.

**Comment by patrykacc** [comment]
@AzaruddinKhan true, same here. Killing jobs manually in sandbox and rerunning doesn't help, following jobs are stuckin same way. That would mean that its issue related for sandbox state rather than particular deployment.

**Comment by AzaruddinKhan** [comment]
@patrykacc I have one work around for this do delta deploy & delta deploy works without any issue.
It looks like a global issue with full package deployment.

Please do let me know in case if you come across any work around for this.:)

**Comment by patrykacc** [comment]
> @patrykacc I have one work around for this do delta deploy & delta deploy works without any issue. It looks like a global issue with full package deployment.
> 
> Please do let me know in case if you come across any work around for this.:)

@AzaruddinKhan what you mean by delta deploy?
The biggest goal for me is to have check only validations working in my CI pipeline
Could delta deploy help me? @

**Comment by stoevie** [comment]
Same problem here in combination with sfdx source:force deploy.
It looks like around the release of a SP preview the performance of scratch orgs and sandboxes are going backwards. I see deployment tasks which have more then 60 minutes the status pending.

there is also a known issue: https://trailblazer.salesforce.com/issues_view?id=a1p3A000000mDKEQA2
This issue mention the CS88 but we see this problem also with other hosts and not only with sandboxes but also with scratch orgs.

**Comment by iowillhoit** [comment]
@stoevie is correct, a lot of folks are seeing performance degradation with sandboxes where certain jobs (especially large deploys and retrieves) are being suspended. I am hoping to have another public facing record to track here soon. Thanks for everyone's patience

**Comment by SimasRamoska** [comment]
Adding my own two cents. Last week we had exact same issues with.
sfdx force:source:deploy -x manifest/package.xml -u qa --testlevel NoTestRun

Whether it would get stuck in pending or no depended on package contents a lot. For example removing all FlexiPages and Workflow rules, made deployment start. Even just running deployment of single workflow rule didn't work entire Friday, although Monday was okay. Probably not even Summer '22 Issue because the only environment we had such issues was still in Spring.

**Comment by AzaruddinKhan** [comment]
@SimasRamoska I think you are right , this is purely performance degradation as acknowledged by Salesforce.
Not something with Summer'22. Apparently the coincidence of summer'22 and this performances degradation issue had created that confusion and everyone is relating it to summer'22. Salesforce knows well :) 
 
There were some Incident raised for this also but are closed without any permanent fix.

https://status.salesforce.com/incidents/9038
https://status.salesforce.com/incidents/9057
https://status.salesforce.com/incidents/9101

The best work around that we can implement is the delta deploy just by differentiating your current branch with master with some git stuff , --diff=master...HEAD

**Comment by shetzel** [comment]
This is now fixed in sfdx cli v7.155.0
