### ISSUE TITLE
Exception on force:org:beta:create when providing objectSettings section

### ISSUE THREAD

**Issue by jonathankretzmer** [forcedotcom/cli#1526]
### Summary

When using the command `force:org:beta:create` to create a scratch org, it will fail 

### Steps To Reproduce:

**Repository to reproduce:** [forcedotcom-issue-scratchOrg-objectSettings](https://github.com/jonathankretzmer/forcedotcom-issue-scratchOrg-objectSettings)

1. Run command `sfdx force:org:create --definitionfile config\project-scratch-def.json --durationdays 2 -w 30`, passes
2. Run command `sfdx force:org:beta:create --definitionfile config\project-scratch-def.json --durationdays 2 -w 30`, **FAILS**.

### Expected result

I expect that the CLI should work for both the `create` and `beta:create` commands.

### Actual result

**sfdx force:org:create** creates a scratch org as expected

**sfdx force:org:beta:create** Fails with error message:
```
ERROR running force:org:beta:create:  A scratch org was created with username test-xxxxxxxxxxxx@example.com, but the settings failed to deploy due to:
Invalid fullName, must end in a custom suffix ( for ex. __c )
```

If I remove the `objectSettings` the `beta:create` command works.

### System Information

```
{
        "cliVersion": "sfdx-cli/7.150.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.0",
        "pluginVersions": [
                "@dxatscale/sfpowerscripts 13.0.15",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.0 (core)",
                "apex 0.11.0 (core)",
                "auth 2.0.2 (core)",
                "community 1.1.4 (core)",
                "config 1.4.6 (core)",
                "custom-metadata 1.1.0 (core)",
                "data 0.6.15 (core)",
                "generator 2.0.0 (core)",
                "info 2.0.0 (core)",
                "limits 2.0.0 (core)",
                "org 1.12.1 (core)",
                "salesforce-alm 54.3.0 (core)",
                "schema 2.1.0 (core)",
                "sfdmu 4.14.3",
                "sfdx-cli 7.150.0 (core)",
                "sfdx-ext 0.0.55",
                "sfpowerkit 4.2.8",
                "signups 1.0.0 (core)",
                "source 1.9.7 (core)",
                "telemetry 1.4.0 (core)",
                "templates 54.6.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Windows_NT 10.0.22000"
}
```

### Additional information

The use of beta commands is due to a plugin that we are using that references the underlying SFDX core lib and not the CLI directly.

Related issue:
https://github.com/Accenture/sfpowerscripts/issues/942

**Comment by iowillhoit** [comment]
Hey @jonathankretzmer, thank you so much for the reproduction repo 🎉 I was able to reproduce this issue as well. I'll get a ticket created and we'll get it sorted out. Thanks for trying out our beta commands!

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11163191](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xIl6gYAC/view)

**Comment by dieffrei** [comment]
FYI @iowillhoit we also got the same issue.

**Comment by domrycz** [comment]
Hey @iowillhoit , any idea when this will be fixed? It's very painful issue for us.

**Comment by ruslan-kurchenko** [comment]
I have the same issue, any news about a solution?

**Comment by ppeersgi** [comment]
We are running into the same problem. Would be good to have a solution for this.

**Comment by dieffreys-angel** [comment]
Yup, this issue is very problematic. Solution is strongly needed.

**Comment by maggiben** [comment]
Hello @dieffreys-angel @ppeersgi @ruslan-kurchenko @jonathankretzmer Can you please try the `latest-rc` a solution was deployed last RC release.
