### ISSUE TITLE
Profile deployment not working after reconcile in Summer 22

### ISSUE THREAD

**Issue by brijpandey7519** [forcedotcom/cli#1529]
### Summary

Profile deployment not working after reconcile in Summer 22
Profile deployment not working after reconcile in Summer 22

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

Profiles should have been deployed, please see the attached errors

### Actual result

Unknown user permission: ManageHpi

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
sfdx version --verbose --json
 »   Warning: sfdx-cli update available from 7.145.0 to 7.146.1.
{
        "cliVersion": "sfdx-cli/7.145.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.14.2",
        "pluginVersions": [
                "@dxatscale/sfpowerscripts 13.0.12",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.0 (core)",
                "apex 0.11.0 (core)",
                "auth 1.8.2 (core)",
                "community 1.1.4 (core)",
                "config 1.3.24 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.12 (core)",
                "generator 1.2.2 (core)",
                "info 1.3.1 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.2 (core)",
                "salesforce-alm 54.1.0 (core)",
                "schema 1.1.0 (core)",
                "sfdmu 4.13.4",
                "sfdx-cli 7.145.0 (core)",
                "sfpowerkit 4.2.5",
                "source 1.9.2 (core)",
                "telemetry 1.4.0 (core)",
                "templates 54.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
	- Run `sf version` **AND** `sf plugins --core`
sfdx plugins --core
» Warning: sfdx-cli update available from 7.145.0 to 7.146.1.
@dxatscale/sfpowerscripts 13.0.12
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 2.0.0 (core)
apex 0.11.0 (core)
auth 1.8.2 (core)
community 1.1.4 (core)
config 1.3.24 (core)
custom-metadata 1.0.12 (core)
data 0.6.12 (core)
generator 1.2.2 (core)
info 1.3.1 (core)
limits 1.3.0 (core)
org 1.11.2 (core)
salesforce-alm 54.1.0 (core)
schema 1.1.0 (core)
sfdmu 4.13.4
sfdx-cli 7.145.0 (core)
sfpowerkit 4.2.5
source 1.9.2 (core)
telemetry 1.4.0 (core)
templates 54.3.0 (core)
trust 1.1.0 (core)
user 1.7.1 (core)
### Additional information

_Feel free to attach a screenshot_.

**Comment by brijpandey7519** [comment]
[Errors_Profile_Deploy.txt](https://github.com/forcedotcom/cli/files/8722980/Errors_Profile_Deploy.txt)
Attached are the error details

**Comment by WillieRuemmele** [comment]
Hi @brijpandey7519 

from your .txt file provided, it looks like the `sfpowerkit` plugin might be creating the profiles incorrectly. Clearly the server says you have incorrect permissions for `ManageHPI` I'd reach out to the `sfpowrkit` plugin owners. I don't believe this is an `sfdx` CLI related issue.
