### ISSUE TITLE
new flag for specifying the compute in sf deploy functions

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#1533]
### Description
Currently when deploying salesforce functions we use `sf deploy functions -o orgalias`. But we are not able to specify to which compute the function needs to be deployed to, since there can be many compute env under one org. This will give complete control over the compute environment.

**Suggested solution**
`sf deploy functions -c "compute-id"`. If we have something of this sort, we can have a control on which compute the functions are running. 

This feature may address the below problems,
- Say if i have a function which is heavy, i may run it in a separate compute. 
- I may move a function running in one compute to another

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11176249](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xQ2r9YAC/view)
