### ISSUE TITLE
desstructiveChanges.xml No 'Component' named:......

### ISSUE THREAD

**Issue by felix-clay** [forcedotcom/cli#1534]
### Summary

We deploy using Azure DevOps pipelines and were recently impacted by the issues highlighted at the bottom of this thread https://github.com/forcedotcom/cli/issues/1508 where the command force:mdapi:deploy was 'succeeding' but not reaching the org.

I have worked around this by reverting to 7.149.1 which now allows the command to run and reach the Salesforce environment. The problem now is that we are seeing multiple errors;

API Name: destructiveChanges.xml
Type: SharingCriteriaRule, Custom Metadata Record, Email Template, List View, Validation Rule etc
Line: 0
Column: 0
Error Message: No SharingCriteriaRule named: ...., No CustomMetadata named: ...., No EmailTemplate named: ...., No ValidationRule named: .... etc

This repo has not been changed and worked fine before I was trying to fix the previous error.

/src folder contains package.xml, destructiveChangesPre.xml and destructiveChangesPost.xml. My understanding of these files is that if the component is not found, it should not throw an error.

### Steps To Reproduce:

Unfortunately I can't provide the repo but happy to answer any questions on it

1.  Create repo containing package.xml, destructiveChangesPre.xml and destructiveChangesPost.xml 
1.  Use command sfdx force:mdapi:deploy with sfdx version 7.149.1 (though the same occurs with earlier version for me as well).

### Expected result

Deploy to environment with no errors, delete any components from destructive file, deploy any components in package.xml

### Actual result

Receive multiple errors highlighted in summary, e.g. No ValidationRule named: ET_Tertiary__c.Opportunity_Required found

### System Information

sfdx-cli/7.149.1 linux-x64 node-v16.15.0
 ›   Warning: sfdx-cli update available from 7.149.1 to 7.151.1.
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.3.1 (core)
@oclif/plugin-not-found 1.2.6 (core)
@oclif/plugin-plugins 1.10.11 (core)
@oclif/plugin-update 1.5.0 (core)
@oclif/plugin-warn-if-update-available 1.7.3 (core)
@oclif/plugin-which 1.0.4 (core)
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 2.0.0 (core)
apex 0.11.0 (core)
auth 2.0.2 (core)
community 1.1.4 (core)
config 1.3.30 (core)
custom-metadata 1.1.0 (core)
data 0.6.15 (core)
generator 1.2.2 (core)
info 2.0.0 (core)
limits 2.0.0 (core)
org 1.12.1 (core)
salesforce-alm 54.2.1 (core)
schema 2.1.0 (core)
sfdx-cli 7.149.1 (core)
signups 1.0.0 (core)
source 1.9.6 (core)
telemetry 1.4.0 (core)
templates 54.5.0 (core)
trust 1.1.0 (core)
user 1.7.1 (core)

**Comment by mshanemc** [comment]
did this get better after the fix for https://github.com/forcedotcom/cli/issues/1508 ?
