### ISSUE TITLE
Question: How long will the force:mdapi:legacy commands be available?

### ISSUE THREAD

**Issue by gdman** [forcedotcom/cli#1536]
In the release notes there is a note that states the force:mdapi:legacy commands will be around in the short term:

`The functionality in the old force:mdapi:deploy is now in force:mdapi:legacy:deploy. In the short term, you can use these force:mdapi:legacy commands if you run into issues with the new commands.`

My question is, roughly how long will these commands be around?

**Comment by cristiand391** [comment]
Hey @gdman 👋🏼 

The [CLI Deprecation Policy](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/sfdx_dev_cli_deprecation.htm) applies for all deprecated commands/flags.

We deprecated the old mdapi commands on May 12, 2022: https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx#71500-may-12-2022
so they will be available until mid Sep 2022, after that date will remove them (users could still use old tarballs but we will not be providing support), hope that answer your question, thanks!
