### ISSUE TITLE
force:package:version:create returns error "Missing Organization Feature: ContactsToMultipleAccounts" intermittently

### ISSUE THREAD

**Issue by AndreyShestakovACN** [forcedotcom/cli#1537]
### Summary

Package:version:create with the reference to definition file, which has feature "ContactsToMultipleAccounts" on it **intermittently** returns the error:
`ERROR running force:package:version:create:  An error occurred while trying to install a package dependency, ID 04########: Missing Organization Feature: ContactsToMultipleAccounts`

### Steps To Reproduce:

1. Create the scratch org definition file `config\project-scratch-def.json`

```
{
    "orgName": "Test Org",
    "description": "Test",
    "country": "US",
    "edition": "Enterprise",
    "hasSampleData": false,
    "language": "en_US",
    "features": [
        "FinancialServicesUser:10",
        "ContactsToMultipleAccounts",
        "PersonAccounts",
        "IndustriesActionPlan",
        "DocumentChecklist",
        "RecordTypes",
        "SharedActivities",
        "PlatformEncryption"
    ],
    "settings": {
        "chatterSettings": {
          "enableChatter": true
        },
        "knowledgeSettings": {
          "enableKnowledge": true,
          "enableLightningKnowledge": true
          },
        "lightningExperienceSettings": {
          "enableS1DesktopEnabled": true
        },
        "languageSettings": {
          "enableTranslationWorkbench": true
        },
        "nameSettings":{
          "enableMiddleName": true,
          "enableNameSuffix": true
        },
        "enhancedNotesSettings": {
          "enableEnhancedNotes": true
        }        
      },
      "objectSettings": {
            "opportunity": {
                "sharingModel": "private"
            },
            "contact": {
              "sharingModel": "private"
            },
            "case": {
                "sharingModel": "private"
            }
        }
}
```
2. Define the package on sfdx-project.json as dependent on FSC managed package

```
"packageDirectories": [
        {
            "path": "src\\package-test",
            "package": PackageTest",
            "versionName": "ver 0.1",
            "versionNumber": "0.1.0.NEXT",
            "default": false,
            "dependencies": [
                {
                    "package": "FSC@236.2"
                }
            ]
        }
],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "54.0",
    "packageAliases": {
        "FSC@236.2": "04t1E000001IrDtQAK",
        "PackageTest": "0H############",
    },
    "plugins": {}
}
```

3. Create Package:

`sfdx force:package:create --name "PackageTest" --packagetype Unlocked --path "src/package-test" --targetdevhubusername DevHubUsername --errornotificationusername DevHubUsername`

4. Run Package Create Version Create:

`sfdx force:package:version:create --package "PackageTest" --installationkeybypass --wait 90 --targetdevhubusername DevHubUsername --definitionfile "config/project-scratch-def.json"`

### Expected result

`force:package:version:create` request must verify dependencies successfully and propagate to the next stage, i.e.:
`Request in progress. Sleeping 30 seconds. Will wait a total of 3960 more seconds before timing out. Current Status='Verifying metadata'`

### Actual result

Sometimes **but not always**, the error generated during 'Verifying dependencies' that ContactsToMultipleAccounts feature is missed

```
Request in progress. Sleeping 30 seconds. Will wait a total of 4890 more seconds before timing out. Current Status='Verifying dependencies'
ERROR running force:package:version:create:  An error occurred while trying to install a package dependency, ID 04t1E000001IrDt: Missing Organization Feature: ContactsToMultipleAccounts
```

### System Information

```
{
        "cliVersion": "sfdx-cli/7.149.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.0",
        "pluginVersions": [
                "@dxatscale/sfpowerscripts 13.0.15",
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.0 (core)",
                "apex 0.11.0 (core)",
                "auth 2.0.2 (core)",
                "community 1.1.4 (core)",
                "config 1.3.30 (core)",
                "custom-metadata 1.1.0 (core)",
                "data 0.6.15 (core)",
                "generator 1.2.2 (core)",
                "info 2.0.0 (core)",
                "limits 2.0.0 (core)",
                "org 1.12.1 (core)",
                "salesforce-alm 54.2.1 (core)",
                "schema 2.1.0 (core)",
                "sfdmu 4.14.1",
                "sfdx-cli 7.149.1 (core)",
                "sfpowerkit 4.2.5",
                "signups 1.0.0 (core)",
                "source 1.9.6 (core)",
                "telemetry 1.4.0 (core)",
                "templates 54.5.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.1 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19043"
}
```

**Comment by cristiand391** [comment]
Thanks for reporting @AndreyShestakovACN!

I'll ping the team that own the package commands.

**Comment by azlam-abdulsalam** [comment]
Its an issue with scratch org used for validation. Scratch Orgs are flaky with ACR

**Comment by cristiand391** [comment]
@AndreyShestakovACN from packaging support:

> Can you confirm if you have the org pref ContactsToMultipleAccounts enabled in setup.
Try this configuration: Setup -> Account Settings -> check the Allow users to relate a contact to multiple accounts

As Azlam said, there was an issue on sandbox/scratch infra, that should be solved by now: https://status.salesforce.com/generalmessages/964

**Comment by AndreyShestakovACN** [comment]
@cristiand391 , the issue I described is realted to a scratch org created based on the scratch org definition file. Sometimes a scratch org is created with the feature "ContactsToMultipleAccounts" enabled and sometime without.
To clarify, the issue happens no only when trying to create a package version, but also when creating a scratch org manually.
I will be testing the scratch orgs creation for the next few days to see if the issue still exists or not.

**Comment by cristiand391** [comment]
Ah gotcha, yeah we saw a few scratch org errors last week.

`I will be testing the scratch orgs creation for the next few days to see if the issue still exists or not.`
Sure, thanks! I'll keep this issue open for at least 1 week.

**Comment by AndreyShestakovACN** [comment]
I tried to create scratch orgs on different days this week, and did not get the issue on Tuesday, but had the 2 times occurence of `Missing Organization Feature: ContactsToMultipleAccounts` on Thursday: first 2 attempts I've got the error, but with the 3rd attempt the scratch org has been properly created.

**Comment by shetzel** [comment]
This is a known serverside issue and the appropriate team is tracking internally with W-9529783 and W-9604466.  Since this is not an issue with the CLI I'm closing this issue.  Feel free to contact support for anything addtional.

**Comment by AndrewRayCode** [comment]
Why is this closed? This is a multi-month outage that's still happening. "Open a support ticket" = "throw the issue into a canyon."

**Comment by AndrewRayCode** [comment]
More examples:
https://trailblazer.salesforce.com/issues_view?id=a1p3A000001PYYlQAO
https://trailblazer.salesforce.com/issues_view?id=a1p4V000001s8OlQAI
https://salesforce.stackexchange.com/questions/388111/error-installing-package-in-scratch-org-missing-organization-feature-contacts

There is a very painful workaround for CI systems: https://salesforce.stackexchange.com/a/360103/68098

**Comment by AndrewRayCode** [comment]
The more I try to use scratch orgs, the more confused I get. Do people actually use these for CI? They seem really unstable. You can't even log in to a scratch org safely: https://github.com/forcedotcom/cli/issues/1640
