### ISSUE TITLE
Changes to XML builder?

### ISSUE THREAD

**Issue by gdman** [forcedotcom/cli#1539]
### Summary

Have there been intentional changes to XML building in the most recent release?

Observations:
Previously there were self closing tags now there are empty tags e.g. `<stringValue/>` is now `<stringValue></stringValue>`
Now comments seem to be removed e.g. `<label><!-- BST End Date --></label>` in translation files is now `<label></label>`

These things obviously have the same meaning but now there are going to be a whole bunch of changes detected in all of our repositories. It'll be made worse because users will auto-update to the new SFDX version at different times so some will have the changes and some won't.

Is this an intentional change and is it going to stay this way?

If so, I'll start work on getting all our repositories updated and put notices out to the whole team for force updates to SFDX so that everyone is on the same version. However, I don't want to do that to find in the next version it gets changed back and have to do the same thing again...

I should point out this is when retrieving using mdapi and the converting to source format. source:retrieve also seems to show the same behaviour but not sure if this is how source:retrieve behaved previously.

**Comment by cristiand391** [comment]
Hey @gdman!

I've tried adding a translation for a label, when I do `mdapi:retrieve` the translation file has comments and when converting it to source format with `mdapi:convert` the comments are preserved.

sfdx-cli/7.152.0 darwin-x64 node-v16.13.2

Do you have any repo to try repro this issue?

afaik, the new commands are using the same xml parser than the legacy commands, I'll check with my team and get back to you.

**Comment by w-andre** [comment]
Just wanted to confirm that we noticed the same behavior using `source:retrieve`. The retrieved metadata xml is slightly different using the new `source`-commands.

**Comment by WillieRuemmele** [comment]
Hi @w-andre @gdman 

If I recall correctly, this was noted when we transitioned the `source:*` commands to use the [SDR library](https://github.com/forcedotcom/source-deploy-retrieve), we've recently switched the `mdapi:*` commands to use that same library, so we're probably seeing that same side-effect again. Now that all commands are moving towards that format, it should be standardized moving forward.
