### ISSUE TITLE
aura in subfolders no longer work in force:source:push and force:source:deploy

### ISSUE THREAD

**Issue by zhebinliu** [forcedotcom/cli#1541]
Summary
force:source:push no longer supports aura subfolders in the source code. Prior to 7.129, this worked just fine

Steps To Reproduce:
Have a source based project with the aurain a folder structure like this:
aura
+--folder1
| \ --aura
| +--myAuraCmp1
| \ --myAuraCmp2
\--myAuraCmp3

SFDX 7.146 or newer
run force:source:push or force:source:deploy
Expected result
Source push to succeed

Actual result
Deploy Errors:
Failed to handle component xxxxx, file path not expected

System Information
{
"cliVersion": "sfdx-cli/7.145.0",
"architecture": "win32-x64",
"nodeVersion": "node-v16.14.2",
"osVersion": "Windows 11"
}

**Comment by cristiand391** [comment]
Hi @zhebinliu 👋🏼 

In [sfdx v7.144.2 ](https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx#71442-march-31-2022) the `source:*` commands were migrated to use the [source-deploy-retrieve](https://github.com/forcedotcom/source-deploy-retrieve/ ) library.

The previous source commands unintentionally supported that file structure, but the new library requires every aura components to be in a folder.

Try with this:

```
force-app/main/default/
...
aura
├── myAuraCmp1
│   ├── myAuraCmp1.cmp
│   ├── myAuraCmp1.cmp-meta.xml
├── myAuraCmp2
│   ├── myAuraCmp2.cmp
│   ├── myAuraCmp2.cmp-meta.xml
├── myAuraCmp3
│   ├── myAuraCmp3.cmp
│   ├── myAuraCmp3.cmp-meta.xml
```

Aura definition bundle docs: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_auradefinitionbundle.htm

With that folder layout you should be able to deploy your project, I'm going to close this issue but please let me know if that doesn't work for you, thanks!
