### ISSUE TITLE
sfdx Version 7.151.1 force:mdapi:deploy cannot fails when attempting to deploy metadata without apex classes

### ISSUE THREAD

**Issue by bast-shb** [forcedotcom/cli#1542]
### Summary

Hi. We use `sfdx force:mdapi:deploy` to deploy metadata to our org. We have specifically decided to omit the `--testlevel` flag, as it is very convenient that the cli chooses the testlevel based on the metadata (for apex classes and such, it is `RunLocalTests`, while `NoTestRun` is selected when there are no apex classes or similar (see https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy_running_tests.htm for reference on when each is choosen).

However, today when trying to deploy with Version 7.151.1, we received the error `sf:INVALID_OPERATION: INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations`. We tried revering to version 7.150.0 but got the same result. Revering back to 7.145.0, however, resulted in the expected scenario: The deployment was successful.

Thus, the error reported here is that in at least versions 7.150.0-7.151.0, a wrongful error is thrown when attempting to deploy metadata with NoTestRun, when the metadata does not contain any apex classes or similar that requires unit tests.

### Steps To Reproduce:

1. Create an sfdx project with metadata, such a fields for account, but no apex classes or other code.
2. run `sfdx force:mdapi:deploy` towards a production org, without specifying the `--testlevel` flag.

### Expected result

The metadata deployment is allowed and successful.

### Actual result

The error `sf:INVALID_OPERATION: INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations` is thrown.

### System Information

I cannot supply this as the error was received on our cloud agents used for builds and deployments. The agent simply runs `npm install sfdx-cli --global` at the start of the run, to get the latest version of the cli.

### Additional information

![image](https://user-images.githubusercontent.com/52501746/169850283-05f59805-7b0c-4954-bd0e-3de3190825b1.png)

**Comment by alan-morey** [comment]
Also experiencing the same error.

I have a metadata format package folder as follows:
```
$ tree build/src-package && echo && find build/src-package -type f -print -exec cat {} \; -exec echo -e "\n---\n" \;
build/src-package                                                                                                                                                                         
├── destructiveChangesPost.xml                                                                                                                                                            
├── destructiveChangesPre.xml                                                                                                                                                             
├── package.xml                                                                                                                                                                           
└── permissionsets                                                                                                                                                                        
    └── AlanTest.permissionset                                                                                                                                                            

1 directory, 4 files
                                                                                                                                                                                          
build/src-package/destructiveChangesPost.xml                                                                                                                                              
<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                                    
<Package xmlns="http://soap.sforce.com/2006/04/metadata">

</Package>                                                                                                                                                                                
---                                                                                                                                                                                       

build/src-package/package.xml                                                                                                                                                             
<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                                    
<Package xmlns="http://soap.sforce.com/2006/04/metadata">                                                                                                                                 
  <types>                                                                                                                                                                                 
    <members>AlanTest</members>
    <name>PermissionSet</name>
  </types>
  <version>52.0</version>
</Package>

---

build/src-package/destructiveChangesPre.xml                                                                                                                                               
<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                                    
<Package xmlns="http://soap.sforce.com/2006/04/metadata">                                                                                                                                 
                                                                                                                                                                                          
</Package>                                                                                                                                                                                
---

build/src-package/permissionsets/AlanTest.permissionset                                                                                                                                   
<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                                    
<PermissionSet xmlns="http://soap.sforce.com/2006/04/metadata">
    <description>Alan testing deployment errors in production. This should be deleted after testing is complete.</description>
    <hasActivationRequired>false</hasActivationRequired>
    <label>AlanTest</label>
    <license>Salesforce</license>
</PermissionSet>

---
```

Executing the following command to deploy:

```
$ sfdx force:mdapi:deploy -u PROD -d build/src-package -w -1
ERROR running force:mdapi:deploy:  INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations
```

I have tested this deployment with the following sfdx versions:

- 7.153.1 - :x:
- 7.152.0 - :x:
- 7.151.1 - :x:
- 7.150.0 - :x: 
- 7.149.1 - :heavy_check_mark: 

While not exhaustive, it appears that the issue was introduced with `v7.150.0` which coincides with the promotion of `force:mdapi:beta` commands to `force:mdapi`.

`force:mdapi:deploy` command works as expected with `v7.149.1`. 

Using `force:mdapi:legacy:deploy` with `v7.153.1` also works as expected.

```
$ sfdx version && sfdx force:mdapi:legacy:deploy -u PROD -d build/src-package -w -1
sfdx-cli/7.153.1 linux-x64 node-v14.19.3                                                                                                                                                  
*** Deploying with SOAP ***                                                                                                                                                               
Job ID | 0Af5Y00000FPoLESA1                                                                                                                                                               
MDAPI PROGRESS | ████████████████████████████████████████ | 1/1 Components        
```

**Comment by WillieRuemmele** [comment]
Hi @alan-morey 

first off, wow, thank you for all of that research and investigating 👏 👏 . We've been working on getting a prod org to use to replicate this issue, but just from comparing the current vs the `legacy` commands, I can see that the default value for `--testlevel` was set to `NoTestRun` in the new [version](https://github.com/salesforcecli/plugin-source/blob/main/src/commands/force/mdapi/deploy.ts#L55) and was left undefined in the `legacy` [version](https://github.com/salesforcecli/toolbelt/blob/main/src/commands/force/mdapi/legacy/deploy.ts#L51) 

If you're up for it, could you try modifying your local file and remove that default value? That might help us speed up the process and verify the fix at the same time. Depending on OS and install type (npm vs installer) you should be able to run `which sfdx` or `npm root -g` to find the installed location, from there navigate to `node_modules/@salesforce/plugin-source/lib/commands/force/mdapi` and remove line 129 of `deploy.js`?

**Comment by alan-morey** [comment]
Hi @WillieRuemmele,

I made the change as you suggested and removed line 129 from `node_modules/@salesforce/plugin-source/lib/commands/force/mdapi/deploy.js`, however that results in the following error:

```
sfdx version && sfdx force:mdapi:deploy -u PROD -d build/src-package -w -1
sfdx-cli/7.153.1 linux-x64 node-v14.19.3
ERROR running force:mdapi:deploy:  'undefined' is not a valid value for the enum 'TestLevel'
```

I then tried setting the default to an empty string:
```
        default: '',
```
However, that also results in error:

```
sfdx version && sfdx force:mdapi:deploy -u PROD -d build/src-package -w -1
sfdx-cli/7.153.1 linux-x64 node-v14.19.3
ERROR running force:mdapi:deploy:  '' is not a valid value for the enum 'TestLevel'
```

Also tried setting default to `null`, similar error

**Comment by WillieRuemmele** [comment]
Hi @alan-morey thank you so much for making those changes, and I apologize for the delay getting back to you. 

Could you try one more thing for me? Could you remove lines 58-59 of that same file? 
```
                runTests: this.getFlag('runtests'),
                testLevel: this.getFlag('testlevel'),
```

I've done some research, and testing between the `mdapi:deploy` and `mdapi:legacy:deploy` and now believe that if those keys are present, and set to `undefined` - what you tried, or `NoTestLevel` the default flag, it will fail. I'm hoping that by excluding those keys, it'll work correctly. 

Just as a reminder: if you remove those, and the deploy succeeds - you will be deploying to prod

**Comment by alan-morey** [comment]
Hi @WillieRuemmele,

I removed those 2 lines and deployment request goes through:
```
$ sfdx version && sfdx force:mdapi:deploy -u PROD -d . -w -1 --checkonly
sfdx-cli/7.153.1 linux-x64 node-v14.19.3
Deploy ID: 0Af5Y00000FPuh1SAD
*** Deploying with SOAP ***
DEPLOY PROGRESS | ████████████████████████████████████████ | 1/1 Components
```

**Comment by WillieRuemmele** [comment]
Hey @alan-morey 🎉 great news! we'll get this fixed right away! 😎 

Thank you so much for all of your help

**Comment by ganesh2109-cloud** [comment]
@WillieRuemmele Facing the same issue, any idea which version of the sfdx-cli will the fix be a part of?

**Comment by WillieRuemmele** [comment]
Hi @ganesh2109-cloud I'm planning on getting those changes into this week's `latest-rc` build, it should be available as a standalone install before that. I'll update this thread when it's available

**Comment by kalyanGK1** [comment]
Hi team,

I require your help with the following issue:

command:-
sfdx force:source:deploy -u devops@xyz.com --sourcepath 'force-app/main/default/lwc/cmsIndiaReports/cmsIndiaReports.html' --loglevel fatal

Error:- 
**ERROR running force:source:deploy: INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations**

I am trying to deploy non-Apex classes, and I would like to exclude test validations for these components during deployment in production. Is there a way to bypass the test execution for non-Apex metadata while still complying with the production deployment requirements?

For reference, I am using the following version of Salesforce CLI:

**sfdx-cli/7.81.0-7b953c80d1 linux-x64 node-v12.18.3**

Any insights or suggestions would be greatly appreciated.

Thank you!
