### ISSUE TITLE
StaticResource memory issues when using sfdx

### ISSUE THREAD

**Issue by nathanfranklinau** [forcedotcom/cli#1544]
This one is related to the original post I made regarding memory issues:
https://github.com/forcedotcom/cli/issues/1348

I've noticed that in the latest version of sfdx, this is still a problem. While using force:mdapi:convert with static resources, the memory of my docker containers hits it's memory limit and dies.

I've uploaded a screencast which shows the memory usage when running force:mdapi:convert on a package with 2 static resources only:
https://drive.google.com/file/d/16B1ShbMiZfqAHFZ7FrYxekhHhQ8pAAO_/view

It shows an increase up 6.9 GB in the screen, but the overall container memory usage hits its threshold of 7.75GB before it died.

The file itself is an old version of SLDS:

Lightning Design System
Version: v0.8.0
I've uploaded the static resource here: https://drive.google.com/file/d/1rL6eBun-zAch6KcWcOR4IoMytbgmxrr3/view?usp=sharing

Hoping this helps diagnose the issue further

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11197251](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xk8c9YAA/view)

**Comment by cristiand391** [comment]
Uploaded the provided static resource to my scratch org, was able to `source:convert` and then when I ran `mdapi:convert` memory went up to ~10gb before finishing.

![Screen Shot 2022-05-24 at 19 03 43](https://user-images.githubusercontent.com/6853656/170139850-c24a061c-8acb-4ad0-bceb-2748f4de600b.png)

We'll get this fixed, thanks for the repro @nathanfranklinau!

**Comment by WillieRuemmele** [comment]
Hi @nathanfranklinau - we've recently changed what library we used to process zip files, I know this issue is pretty old, but I couldn't reproduce it using the latest cli 
```bash
 ➜  sf -v                                                                                 
@salesforce/cli/2.1.7 darwin-arm64 node-v18.16.0
```
I saw a node process spawn, and use ~300 mb when converting your SR
