### ISSUE TITLE
.forceignore issue, --concise parameter isn't working as expected for force:source:status command

### ISSUE THREAD

**Issue by saurabh-deep** [forcedotcom/cli#1545]
### Summary

Remote changes are not being ignored correctly by `force:source:status` command when using the `--concise` parameter. It happens when the added/metadata updated in the org doesn't exist in local source, and is supposed to be ignored as per .forceignore. Details and steps are provided for Profiles only, so that the issue can be reproduced easily without making any changes after cloning the dreamhouse-lwc repo, but it can just as easily be replicated with any metadata type (e.g. ApexClass) by making the required entries in the .forceignore file.

As per the documentation, ignored files shouldn't be returned in the output of `force:source:status` command when using `--concise` parameter. But the metadata is reported as _Remote Add_. Even stranger is the fact that the same file which is incorrectly reported as _Remote Add_ by the `force:source:status` command is still ignored (correctly) by `force:source:pull` command.

This issue came into existence when the new `force:source:beta` commands became generally available in version `7.144.2`.

This breaks our use cases which depend on the output of the status command to decide whether a pull/push needs to take place. Without the --concise parameter to work as expected we are having to use legacy versions of the source tracking and status/pull/push commands.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1. Clone the dreamhouse-lwc repo.
1. Check .forceignore file to ensure that all profiles are ignored.
1. Without making any code changes, create a new scratch org.
  `sfdx force:org:create -f config/project-scratch-def.json -s -a dreamhouse-org -v DEVHUB`
1. Push the repo source to the new scratch org.
  `sfdx force:source:push`
1. Check the source status, with complete output (without --concise parameter)
  `sfdx force:source:status`
1. Check the source status, with concise output
  `sfdx force:source:status --concise`
1. Try retrieving from remote.
  `sfdx force:source:pull`

### Expected result

1. Step # 5 `force:source:status` - should show the complete output, i.e. Admin profile should show up as _Remote Add_.
1. Step # 6 `force:source:status --concise` - shouldn't show the Admin profile as _Remote Add_ since we are using the `--concise` paramter and profiles are ignored using .forceignore.
1. Step # 7 `force:source:pull` - should report _No results found_

### Actual result

1. Output of step # 5 is as expected.
1. Output of step # 6 is not correct. Even when using `--concise` param with the `force:source:status` command, the ignored profile is being reported as _Remote Add_.
1. Interestingly, output of step # 7 is also correct. `force:source:pull` command reports _No results found_, even when status command shows the profile as _Remote Add_. 

This indicates that the .forceignore is being interpret correctly by the pull command, but not by the status command as should happen when using the --concise param.

### System Information

▶ sfdx version --verbose --json
{
	"cliVersion": "sfdx-cli/7.152.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v14.19.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 2.0.0 (core)",
		"apex 0.12.0 (core)",
		"auth 2.0.2 (core)",
		"community 1.1.4 (core)",
		"config 1.4.6 (core)",
		"custom-metadata 1.1.0 (core)",
		"data 2.0.0 (core)",
		"generator 2.0.1 (core)",
		"info 2.0.0 (core)",
		"limits 2.0.0 (core)",
		"org 1.13.1 (core)",
		"salesforce-alm 54.4.0 (core)",
		"schema 2.1.0 (core)",
		"sfdx-cli 7.152.0 (core)",
		"signups 1.1.1 (core)",
		"source 1.9.9 (core)",
		"telemetry 2.0.0 (core)",
		"templates 54.7.0 (core)",
		"trust 1.1.0 (core)",
		"user 2.0.0 (core)"
	],
	"osVersion": "Darwin 20.6.0"
}

### Additional information

The issue can be replicated with any metadata type when the following 2 conditions are true -
1. Metadata which is being added/updated in the org is ignored using .forceignore.
1. Metadata is not present in your local source.

At this point `force:source:status --concise` command still reports the ignored metadata as _Remote Add_ and `force:source:pull` command refuses to retrieve that.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/31232091/170027541-5111e3f0-715b-413a-b402-0ef8363b3132.png">

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11224417](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000yEFvMYAW/view)

**Comment by mshanemc** [comment]
We fixed this last June and didn't update the gh issue.
