### ISSUE TITLE
Cannot deploy service channel with managed sobject

### ISSUE THREAD

**Issue by Xu-Stefan** [forcedotcom/cli#1546]
```
<?xml version="1.0" encoding="UTF-8"?>
<ServiceChannel xmlns="http://soap.sforce.com/2006/04/metadata">
    <doesMinimizeWidgetOnAccept>false</doesMinimizeWidgetOnAccept>
    <label>Test</label>
    <relatedEntityType>Namespace__CustomObject__c</relatedEntityType>
</ServiceChannel>
```

when use `sfdx force:source:deploy` or `sfdx force:mdapi:deploy` command to deploy a service channel that related entity type is a sobject from managed package, got error: `Error  Test  Only related entity type(s) of *** are currently supported.`

**Comment by cristiand391** [comment]
Hey @Xu-Stefan 👋🏼 
was this working before? can you complete the issue template please?

**Comment by Xu-Stefan** [comment]
Hi, @cristiand391 i am not sure it's working before.

and this is whole metadata of `Test.serviceChannel-meta.xml` file
```
<?xml version="1.0" encoding="UTF-8"?>
<ServiceChannel xmlns="http://soap.sforce.com/2006/04/metadata">
    <doesMinimizeWidgetOnAccept>false</doesMinimizeWidgetOnAccept>
    <label>Test</label>
    <relatedEntityType>MyNamesapce__ObjectName__c</relatedEntityType>
</ServiceChannel>
```

you can reproduce it in any org with this.
1. replace `MyNamesapce__ObjectName__c` with an exist sobject name and that sobject is from managed package
2. execute `sfdx force:mdapi:deploy`

**Comment by WillieRuemmele** [comment]
Hi @Xu-Stefan, 

this might not be supported based on your packaging type, from the [Coverage Report](https://developer.salesforce.com/docs/metadata-coverage/55) under `Service Channel`

**Comment by shetzel** [comment]
Closing since type is not packageable.

**Comment by jairzh** [comment]
Has this issue been resolved? After installing a managed package and configuring the Service Channel with a custom object from this package, we were unable to use sf deploy metadata to deploy the Service Channel to another sandbox or production environment. We encountered an error similar to this issue. However, the command worked after we changed the related object in the Service Channel to a standard object.

@shetzel

**Comment by shetzel** [comment]
@jairzh Not supported per this doc: https://developer.salesforce.com/docs/metadata-coverage/59

That's not something the CLI team can fix.  It's up to the team that owns `ServiceChannel`

**Comment by jairzh** [comment]
> @jairzh Not supported per this doc: https://developer.salesforce.com/docs/metadata-coverage/59
> 
> That's not something the CLI team can fix. It's up to the team that owns `ServiceChannel`

@shetzel Thank you for the information. In that case, we will have to manually create the `ServiceChannel` now.
