### ISSUE TITLE
Issue installing unlocked packages in scratch orgs

### ISSUE THREAD

**Issue by jordan-mathews** [forcedotcom/cli#1547]
### Summary

Installing unlocked packages in a new scratch org is taking several hours and sometimes the installation process never completes.

### Steps To Reproduce:
1. Create a new scratch org
` sfdx force:org:create -f config/enterprise-scratch-def.json -a MyScratchOrg`
2. Install your package to a scratch org.
`sfdx force:package:install --package 04t... -u me@example.com -w 10`

### Expected result

The packaged is successfully installed in the scratch org within a reasonable amount of time (minutes **NOT** hours)

### Actual result

The package is taking several hours to install or the installation process never completes. 

### System Information

sfdx-cli/7.81.0-7b953c80d1 darwin-x64 node-v12.18.3

**Comment by mshanemc** [comment]
There's a larger issue on sandbox/scratch infrastructure.  I don't think this is a CLI issue.  
https://status.salesforce.com/generalmessages/964

You could try a newer CLI version since that one is over a year old and packaging team makes changes/fixes sometimes.
