### ISSUE TITLE
Typo in the error message for the missing environment flag in the log tail command

### ISSUE THREAD

**Issue by i-m-anas** [forcedotcom/cli#1550]
I think it is a more of an typo than an issue,
The error message for the `sf env log tail` command misleads the user to add `-c` flag for environment which should be `-e` instead.
![image](https://user-images.githubusercontent.com/41505610/170384970-7eb169a5-6a1a-4808-96dd-76c931feea3f.png)
![image](https://user-images.githubusercontent.com/41505610/170385023-1fa284be-65d8-4a1e-85ee-9be2107b729d.png)

**Comment by saracope** [comment]
Merged in the fix for this; can be closed.

**Comment by RodEsp** [comment]
Hey @saracope would you mind closing this once the PR to bump the new version of `plugin-functions` that has this fix is merged into https://github.com/salesforcecli/cli please? 🙏🏼
