### ISSUE TITLE
SFDX outputs an insane amount of empty DEBUG statements with --dev-debug

### ISSUE THREAD

**Issue by goto-dev-null** [forcedotcom/cli#1551]
**Is your feature request related to a problem? Please describe.**
I honestly don't know how many places this occurs but the face that it occurs at all is really frickin annoying. Sometimes I notice every ~250ms, in this instance it's literally every frickin 1ms. How is this helpful, even to devs?

**What are you trying to do**
In this instance, create a Package Version. I'm pretty sure I've seen it in other places but I'm just now finally fed up with it to create an issue.

**Describe the solution you'd like**
Stop pushing all the useful debug info off the screen with utterly useless statements.

**Describe alternatives you've considered**
Literally none. I can't even pipe the output to a file because it's not included in stdout or stderr.

**Additional context**
This is not all of them. I don't know how many it actually it outputs because it fills up the screen in a quarter of a second. I'm guessing at hundreds if not thousands.

![image](https://user-images.githubusercontent.com/2322497/170760205-37596b79-ad83-43cb-b327-b1cd130af57e.png)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-11215254](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000xxuB5YAI/view)

**Comment by WillieRuemmele** [comment]
Hey @jonnypetraglia - have you seen any unnecessary logging lately? I know for a fact that the `SourcePathStatusManager` is deprecated and shouldn't be being used on current versions of the CLI. 

I'm going to close this issue for now, but will happily reopen if we can find more
