### ISSUE TITLE
SFDX CLI deployment report command return status 69

### ISSUE THREAD

**Issue by amarek-cytiva** [forcedotcom/cli#1554]
### Summary

After upgrading the SFDX CLI to 7.152 .0 version when executing the command 

_sfdx force:mdapi:deploy:report --json -i DEPLOY_ID -u ORG_ALIAS _
The return status is not 0 but 69.
It is causing the Jenkins to detect this as a script error 

`hudson.AbortException: script returned exit code 69`

When command is finished the status is back to 0.

Here is the output during validation execution:
`{
  "status": 69,
  "result": {
    "checkOnly": true,
    "createdBy": "....",
    "createdByName": "... Admin",
    "createdDate": "2022-05-31T11:15:06.000Z",
    "details": {
      "runTestResult": {
        "numFailures": "0",
        "numTestsRun": "0",
        "totalTime": "0.0"
      }
    },
    "done": false,
    "id": ".... ",
    "ignoreWarnings": true,
    "lastModifiedDate": "2022-05-31T11:15:06.000Z",
    "numberComponentErrors": 0,
    "numberComponentsDeployed": 0,
    "numberComponentsTotal": 0,
    "numberTestErrors": 0,
    "numberTestsCompleted": 0,
    "numberTestsTotal": 0,
    "rollbackOnError": true,
    "runTestsEnabled": false,
    "status": "Pending",
    "success": false
  }
}`

### Steps To Reproduce:

1.  Invoke the deployment.
1.  Run report command and check the status

### Expected result

The status should be 0

### Actual result

Status is 69

### System Information

openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10-LTS, mixed mode, sharing)

git version 1.8.3.1

sfdx-cli/7.152.0 linux-x64 node-v16.15.0

### Additional information
I've found a workaround for this error which I don't like but the command is identified correctly,
before outputting the json file I've added sed to change the code status from 69 to 0 
`sed \'s/"status": 69/"status": 0/g\'`

**Comment by mshanemc** [comment]
`69` denotes a timeout waiting for an asynchronous process.  Did the deploy succeed (0) or fail (1)?  Well, you kinda don't know because it's still going.

we also use `68` for partial successes (you tried to `user:permset:assign` a permset to some users, and some worked but some didn't).

Most systems will treat anything besides 0 as an error (pretty reasonable)


---
this way you can handle a 69 (for example, re-run the report command to wait some more) differently than a 1.

**Comment by amarek-cytiva** [comment]
Hi @mshanemc, 
thank you for your answer on this one.
However, this status was not appearing in the previous version.
I just checked version 7.143.0 and during the deployment process, I'm, having status 0.

Just a bit of background on how we are doing the deployment.
We are invoking the deploy command first with flag -w 0

`sfdx force:source:deploy --targetusername stage --testlevel RunSpecifiedTests --runtests AgreementTaskBatchTest -w 0 --json`

Then in order to get currect status of a job and not kill the console we are calling mdapi report command,

`sfdx force:mdapi:deploy:report --json -i 0Af9E00003UEaCySAL -u stage`

In previous versions the status was always 0 of this report command,
after upgrading to the newest version it start returning different status.

`C:\Users\amarek\Documents\GitHub\Cytiva_Salesforce.com>sfdx force:mdapi:deploy:report -i 0Af5t00000G4sLZCAZ -u ... --json
{
  "status": 0,
  "result": {
    "checkOnly": false,
    "createdBy": "0052p000009gWn6",
    "createdByName": ".... Admin",
    "createdDate": "2022-06-03T07:41:38.000Z",
    "details": {
      "componentFailures": [
      .....
      ],
      "runTestResult": {
        "numFailures": "0",
        "numTestsRun": "0",
        "totalTime": "0.0"
      }
    },
    "done": false,
    "id": "0Af5t00000G4sLZCAZ",
    "ignoreWarnings": false,
    "lastModifiedDate": "2022-06-03T07:42:11.000Z",
    "numberComponentErrors": 3,
    "numberComponentsDeployed": 0,
    "numberComponentsTotal": 16,
    "numberTestErrors": 0,
    "numberTestsCompleted": 0,
    "numberTestsTotal": 0,
    "rollbackOnError": true,
    "runTestsEnabled": false,
    "startDate": "2022-06-03T07:41:39.000Z",
    "status": "InProgress",
    "success": false,
    "timedOut": true
  }
}`

```
C:\Users\amarek\Documents\GitHub\[.com](http://.com/)>sfdx --version
sfdx-cli/7.143.0 win32-x64 node-v16.14.0
```

Is there a chance that it was not working correctly before and now it is?

**Comment by pablogrs** [comment]
This results as a command failure in Linux, returning other result than 0.
It is okay to have a "status": 69 in the JSON output (even though previously was a string), but the command should not return that as an exit code, unless it had failed, wrong parameters or something like that.
Where can we see the different statuses returned by the command?

**Comment by pablogrs** [comment]
**Return zero exit code on success, non-zero on failure.** Exit codes are how scripts determine whether a program succeeded or failed, so you should report this correctly. Map the non-zero exit codes to the most important failure modes.

[CLI guidelines](https://clig.dev/#the-basics)

**Comment by mshanemc** [comment]
0: success
1: failure/error
68: partial success
69: timed out
