### ISSUE TITLE
sfdx force:org:open timeouts waiting to resolve the Lightning Experience-enabled custom domain in new urls

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#1556]
### Summary

I have a Sandbox in CS160. No idea why but the url of the salesforce has changed, now has the format of

https://ORG--SANDBOXNAME.sandbox.my.salesforce.com

### Steps To Reproduce:

N/A

### Expected result

  Opening the org

### Actual result

❯ sfdx force:org:open -u xxx-xxx-d
Opening org 00D5r0000004Z7lEAE as user miguel.nunez@xxxx.com.des3
Waiting to resolve the Lightning Experience-enabled custom domain...... ⣻
ERROR running force:org:open:  The client has timed out.
Waiting to resolve the Lightning Experience-enabled custom domain...... done

### System Information

```json
{
	"cliVersion": "sfdx-cli/7.153.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.15.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 2.0.1 (core)",
		"apex 0.13.0 (core)",
		"auth 2.0.3 (core)",
		"community 1.1.5 (core)",
		"config 1.4.7 (core)",
		"custom-metadata 1.1.0 (core)",
		"data 2.0.2 (core)",
		"generator 2.0.1 (core)",
		"info 2.0.1 (core)",
		"limits 2.0.1 (core)",
		"org 1.13.2 (core)",
		"salesforce-alm 54.4.0 (core)",
		"schema 2.1.1 (core)",
		"sfdx-cli 7.153.0 (core)",
		"signups 1.1.2 (core)",
		"source 1.10.1 (core)",
		"telemetry 2.0.0 (core)",
		"templates 54.8.0 (core)",
		"trust 1.1.0 (core)",
		"user 2.0.2 (core)"
	],
	"osVersion": "Darwin 21.5.0"
}
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by AllenFrank** [comment]
Got the same problem with newly created sandboxes (all of them had the same structure: https://xxx.sandbox.my.salesforce.com)

@mnunezdm as a workaround it worked for me to first get the display navigation URL via `-r / --urlonly` and then open the generated URL

**Comment by cristiand391** [comment]
Hey all 👋🏼 

Seems enhanced domains is being enabled automatically in new sboxes, we got a fix for this but in the meantime you can get the url from `org:display` as @AllenFrank suggested, here are a few aliases to speed up the process (requires `jq` installed) ⚡:

macOS:
`open $(sfdx force:org:display -u <sandbox-username> --json | jq -r '.result.instanceUrl')`

linux:
`xdg-open $(sfdx force:org:display -u <sandbox-username> --json | jq -r '.result.instanceUrl')`

**Comment by mshanemc** [comment]
QA notes:

I tested this on a sandbox that's been around for a long time.  It didn't have an error without this change (looks like it properly handles redirects from the existing un-enhanced domain)
✅ this PR doesn't change anything

I tested this on a sandbox known to not work with the current code
✅ can replicate the problem
✅ this PR fixes it

**Comment by dalden1981** [comment]
This is a problem for me as well.

**Comment by cristiand391** [comment]
hey, just an update:

The fix was included in `sfdx-core v3`, current plugin-org is using `sfdx-core v2`, we are bumping core to v3 in this PR:
https://github.com/salesforcecli/plugin-org/pull/332

once it's merged the fix will be available in sfdx, hopefully in the next week RC :)

**Comment by ImJohnMDaniel** [comment]
@cristiand391, I am seeing this issue as well.  I see that 7.158.0 was released as the latest "release candidate".  I upgraded to 7.158.0 and it does indeed appear to resolve this issue.  Cheers!

**Comment by mnunezdm** [comment]
Also working for me in latest release candidate! (7.158.1)

**Comment by delightful-trooper** [comment]
Fixed on windows as well after running  `npm install --global sfdx-cli@7.158.1` . Thanks!
