### ISSUE TITLE
"Parse error in file unknown on line 16"  with sfdx force:auth:web:login

### ISSUE THREAD

**Issue by jeromegv** [forcedotcom/cli#1558]
### Summary

I can't login to my dev hub

### Steps To Reproduce:

sfdx force:auth:web:login --setdefaultdevhubusername -a testdevhub

### Expected result

To be successfully logged in

### Actual result

```
ERROR running auth:web:login:  Parse error in file unknown on line 16
2022, 10:32:50 AM"
}"
}
```

### System Information

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`

```{
	"cliVersion": "sfdx-cli/7.153.1",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.15.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 1.3.0",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 2.0.1 (core)",
		"apex 0.13.0 (core)",
		"auth 2.0.3 (core)",
		"community 1.1.5 (core)",
		"config 1.4.7 (core)",
		"custom-metadata 1.1.0 (core)",
		"data 2.0.2 (core)",
		"generator 2.0.1 (core)",
		"info 2.0.1 (core)",
		"limits 2.0.1 (core)",
		"org 1.13.2 (core)",
		"salesforce-alm 54.4.0 (core)",
		"schema 2.1.1 (core)",
		"sfdx-cli 7.153.1 (core)",
		"sfdx-hardis 2.87.5",
		"signups 1.1.2 (core)",
		"soqlx-opener 0.1.12",
		"source 1.10.2 (core)",
		"telemetry 2.0.0 (core)",
		"templates 54.8.0 (core)",
		"trust 1.1.0 (core)",
		"user 2.0.2 (core)"
	],
	"osVersion": "Darwin 20.6.0"
}
```

### Additional information

<img width="806" alt="Screen Shot 2022-06-02 at 1 10 26 PM" src="https://user-images.githubusercontent.com/86115/171685913-aa9d88c9-0dfa-4a2f-9007-de763c0ea9e3.png">
<img width="1046" alt="Screen Shot 2022-06-02 at 1 09 56 PM" src="https://user-images.githubusercontent.com/86115/171685916-a8d6188e-1ea8-49d9-a771-9749dc00228b.png">

**Comment by socialsuiteDavid** [comment]
Also getting this error when running commands. How did you fix it?

**Comment by socialsuiteDavid** [comment]
So I managed to resolve it.

What I did:
Add `--dev-debug` to the command throwing the error.
I found the configFile.js that was throwing the error.
I added `throw new Error(this.getPath());` on line 163 (above the rethrow)
I reran the command, now it shows me the file path that has the error.
Then I just opened that file up and removed the extra }

**Comment by jeromegv** [comment]
For me it was mostly clearing things out in `.sfdx` (which I assume is whereto were able to see the bad file)
