### ISSUE TITLE
Unable to authorize an org (ERROR running auth:web:login:  spawn EPERM)

### ISSUE THREAD

**Issue by coolirisme** [forcedotcom/cli#1563]
### Summary

Can't authorize an Org

### Steps To Reproduce:

1. Open vscode and create a new project
2. Select SFDX: Authorize An Org from command pallete

### Expected result

Browser window should open

### Actual result

18:15:39.266 sfdx force:auth:web:login --setalias devrow --instanceurl https://test.salesforce.com --setdefaultusername
ERROR running auth:web:login:  spawn EPERM

### System Information

`
{
        "cliVersion": "sfdx-cli/7.153.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-diff 0.0.6",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.1 (core)",
                "apex 0.13.0 (core)",
                "auth 2.0.3 (core)",
                "community 1.1.5 (core)",
                "config 1.4.7 (core)",
                "custom-metadata 1.1.0 (core)",
                "data 2.0.2 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.4.0 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.153.1 (core)",
                "signups 1.1.2 (core)",
                "source 1.10.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 54.8.0 (core)",
                "trust 1.1.0 (core)",
                "user 2.0.2 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}
`

**Comment by WillieRuemmele** [comment]
Hi @coolirisme 👋 

 what happens if you run the `sfdx force:auth:web:login --setalias devrow --instanceurl https://test.salesforce.com/ --setdefaultusername` command directly from the terminal? Do you get the same error?

**Comment by coolirisme** [comment]
Hi @WillieRuemmele 
Getting the same error from command prompt and powershell window as well.

**Comment by coolirisme** [comment]
@WillieRuemmele Here is the output from CLI after using the `--dev-debug` parameter.
https://gist.github.com/coolirisme/937fc20328101c5f32c1e6abffbe01a5

**Comment by WillieRuemmele** [comment]
Hi @coolirisme 

it seems like it's another report of this [bug](https://github.com/sindresorhus/open/issues/205#issue-741113409) in the `open` library we use

**Comment by coolirisme** [comment]
@WillieRuemmele I have powershell installed on my system so not sure whether that's the cause.
