### ISSUE TITLE
sf reporting 0/0 components on a `metadata deploy resume`

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#1565]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

**Repository to reproduce:** 
https://github.com/salesforcecli/sample-project-multiple-packages

1.  `sf env create scratch -d -f config/project-scratch-def.json -y 1`
1.  `../../plugin-deploy-retrieve/bin/dev deploy:metadata --source-dir force-app --async`
1.  `../../plugin-deploy-retrieve/bin/dev deploy:metadata:resume --job-id 0Af...`

### Expected result

show the # of components deployed already

### Actual result

`
Status: Succeeded | ████████████████████████████████████████ | 0/0 Components
`

<img width="1488" alt="Screen Shot 2022-06-10 at 1 02 44 PM" src="https://user-images.githubusercontent.com/4261788/173125267-216e5bdc-4e0a-4e46-ad6b-870a7a898476.png">

### System Information
sf version --verbose                               
                                    
@salesforce/cli/1.31.0 darwin-x64 node-v16.15.0

**Comment by WillieRuemmele** [comment]
fixed. 
```bash
 ➜  sf project deploy start --source-dir force-app --async                                                   
Deploying v50.0 metadata to test-js76zontlkmb@example.com using the v58.0 SOAP API.
Deploy ID: 0AfDa00001VHFGQKA5
Deploy has been queued.

Run "sf project deploy resume --job-id 0AfDa00001VHFGQKA5" to resume watching the deploy.
Run "sf project deploy report --job-id 0AfDa00001VHFGQKA5" to get the latest status.
Run "sf project deploy cancel --job-id 0AfDa00001VHFGQKA5" to cancel the deploy.
➜  sample-project-multiple-packages git:(main) ✗  hub:(GLOBAL - DevHub) scratch:(test-js76zontlkmb@example.com)
 ➜  sf project deploy resume --job-id 0AfDa00001VHFGQKA5  
Deploy ID: 0AfDa00001VHFGQKA5
Status: Succeeded | ████████████████████████████████████████ | 8/8 Components (Errors:0) | 0/0 Tests (Errors:0)

Deployed Source
===========================================================================================================
| State   Name            Type         Path                                                                 
| ─────── ─────────────── ──────────── ──────────────────────────────────────────────────────────────────── 
| Created MyTest          ApexClass    force-app/main/default/apex/MyTest.cls                               
| Created MyTest          ApexClass    force-app/main/default/apex/MyTest.cls-meta.xml                  
```
