### ISSUE TITLE
force:package:version:create gives error that specified ancestor version is not latest. (It is.)

### ISSUE THREAD

**Issue by dschach** [forcedotcom/cli#1567]
### Summary

Action Plans (github.com/Salesforcelabs/ActionPlansv4) released version 4.2.1.5 to the AppExchange. I want to create version 4.3.0.1 and I want users to be able to upgrade to it from the latest released version. 
The ancestor tree, so far, is pretty simple: 
```
─┬ 4.1.0.1
 └─┬ 4.2.0.7
   └── 4.2.1.5
```
I should be able to specify 4.2.1.5 as the ancestorVersion, but I get this error message:
`Can’t create package version. The ancestor version [4.2.1.5] you specified isn’t the highest released package version. Set the ancestor version to 4.2.0, and try creating the package version again. You can also specify --skipancestorcheck to override the ancestry requirement.`

I cannot skip ancestor check, as I want users to be able to upgrade.

### Steps To Reproduce:

Though you won't have access to the packaging/LDO org, you can see the script I'm trying to run in the branch at https://github.com/SalesforceLabs/ActionPlansV4/blob/4.3.0/scripts/packagedev/build.sh so that should help.

### Expected result

The latest promoted/released package version is allowed to be specified as the package ancestor.

### Actual result

The second-to-latest version is required.

### System Information
```json
{
        "cliVersion": "sfdx-cli/7.153.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.15.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-scanner 2.13.4",
                "alias 2.0.1 (core)",
                "apex 0.13.0 (core)",
                "auth 2.0.3 (core)",
                "bbdoc 4.0.5",
                "community 1.1.5 (core)",
                "config 1.4.7 (core)",
                "custom-metadata 1.1.0 (core)",
                "data 2.0.2 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "isvte-sfdx-plugin 1.1.16",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.4.0 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.153.1 (core)",
                "signups 1.1.2 (core)",
                "source 1.10.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 54.8.0 (core)",
                "trust 1.1.0 (core)",
                "user 2.0.2 (core)"
        ],
        "osVersion": "Darwin 21.4.0"
}```

### Additional information

**Comment by dschach** [comment]
bump 
@mshanemc I'm happy to show you what is going on. There is a released version on the AppExchange, but I can't list it as the ancestor version - the CLI wants me to use an older version. I can't do that because it's going to screw up a lot of people.

**Comment by dschach** [comment]
I even get the error when specifying the latest RELEASED package:
`Can’t create package version. The ancestor version [04t5f000000rKJ9AAM] you specified isn’t the highest released package version. Set the ancestor version to 4.2.0, and try creating the package version again. You can also specify --skipancestorcheck to override the ancestry requirement.`

**Comment by dschach** [comment]
Full package version report on the package **I** think is the latest one:
```
Name                           Value                                                
 ────────────────────────────── ──────────────────────────────────────────────────── 
 Name                           4.2.1.5                                              
 Subscriber Package Version Id  04t5f000000rKJ9AAM                                   
 Package Id                     0Ho5f000000oLlrCAE                                   
 Version                        4.2.1.5                                              
 Description                    Welcome to the new Action Plans from Salesforce Labs 
 Branch                         null                                                 
 Tag                            null                                                 
 Released                       true                                                 
 Validation Skipped             false                                                
 Ancestor                       04t5f000000rK9EAAU                                   
 Ancestor Version               4.2.0.7                                              
 Code Coverage                  93%                                                  
 Code Coverage Met              true                                                 
 Org-Dependent Unlocked Package N/A                                                  
 Release Version                54.0                                                 
 Build Duration in Seconds      443                                                  
 Managed Metadata Removed       No                                                   
 Created By                     0055f000001gXVCAA2 
```

**Comment by shetzel** [comment]
Thank you for posting, however this is working as designed.  The code does not allow using a patch from a different major.minor as the ancestor.  I.e., 4.2.1.5 would be a patch from a different major.minor (i.e. 4.2.0.7) than the version you are attempting to create (4.3.0.1) so it is disallowed, and must use 4.2.0.7 as the common ancestor for the new version 4.3.0.1.

Based on this issue, we will be updating the public docs to clarify.

**Comment by dschach** [comment]
I'm not following, then. What is the purpose of a patch org? If I have users who have upgraded to a patch, then what are they supposed to do? It looks like the design is flawed - how should I have handled this? @shetzel 
Should I rather try to release 4.2.2.0? Would that even work? Then I would add new fields to that and would be able to go to 4.3.0? When adding a new field, what is the proper way to handle things? This is quite confusing.

**Comment by shetzel** [comment]
I'm not on the packaging team so I don't know the answers to any of these questions.  I've been trying to determine whether this is a CLI problem by getting some answers from that team.  Here is something they've said about the purpose of patches: "They are primarily meant to address issues in Apex between releases."

At this point I would probably contact support with those questions.

**Comment by dschach** [comment]
Thanks. At this point, I decided to remove the extra field I created, just so I could increment to 4.2.2.0 instead of all the way to 4.3.0.0. I am now getting invalid cross reference id errors on my custom metadata, which hasn't changed. This whole thing looks pretty screwy. 
Is it the packaging team that surfaces all the errors when trying to build? I'll drop this thread, then.

**Comment by VivekMChawla** [comment]
@dschach - I think there may be a misunderstanding about how patches work and the intent behind them in Salesforce managed packaging.

Patch releases (i.e. any package version where the `patch` portion of the `major.minor.patch` version number is non-zero) are intended to be backwards-looking fixes for package versions that are already installed in subscriber orgs. 

As you build new functionality or make **any** incrementatl changes, you should **always** update the `major.minor` version numbers and **never** the `patch` version number.

Consider this package lineage:

```
1.0.0 --> 1.1.0 --> 1.2.0
```

These represent a baseline package version (`1.0.0`) and two package versions where incremental changes were introduced (`1.1.0` and `1.2.0`). Patch versions should *only* be created to fix something that went wrong with a version that's already installed in a subscriber's org.  

Imagine a bug was found in `1.2.0` and will be fixed in version `1.3.0`.  In the meantime, your subscribers on `1.2.0` need the bug fixed but, understandably, don't want to upgrade to `1.3.0` without extensive testing. This is where a patch version comes in.

```
1.0.0 --> 1.1.0 --> 1.2.0 --> 1.3.0
                    |- 1.2.1
```

Patch versions are **highly restricted** in terms of the metadata changes that can be made. Subscribers can install them without very little fear of something breaking.

Patch versions **are not** intended to be used in a pure semantic versioning sense where you introduce "safe" updates that shouldn't impact the customer. They are **only** intended for use in backwards-looking fixes like the example I showed, above.  

That's why you can't use a patch version as the ancestor of another package version that's not, itself, a higher patch version in the same `major.minor` family as the ancestor patch version.

FYI: @shetzel

**Comment by dschach** [comment]
I understand. So when one gives out the patched version to those orgs, how do we get all orgs on the same version when that one is ready to go?
Or, in other words, once that org does its testing, how can it get back on the tree with everyone else?

**Comment by VivekMChawla** [comment]
@dschach - The org that got patched can update to **any** package version whose `major.minor` version number is further forward in the lineage.  

This is precisely why the restrictions on patch versions exist.  You're not allowed to add anything to a patch that violates the manageability rules of the related `major.minor` version.  This way, that patch is safe for any descendant package to provide as an upgrade path because that descendant will share similar manageability rules.

**Comment by dschach** [comment]
Actually, I'm not sure it makes sense, @VivekMChawla - every package version has, by definition, a patch number. It may be zero, but it's there. As I'm creating my package, I do version 1.0.0.0, 1.0.0.1...1.0.0.7, which I want to release. What's the number of the package version that I'm releasing? To me, it looks to be 1.0.0.7. But if I can't use that as an ancestor, then what's the point of builds?

How does that customer on 1.2.1 get to install 1.3.0, since 1.3.0 clearly lists 1.2.0 as its ancestor version.

If the patched org 1.2.1 can just hop back on the train and put in 1.3.0 without worrying, then that's great --- but the documentation certainly doesn't explain that. And I'm trying to go from 4.2.1 to 4.3.0 and that's not working. For 4.3.0, Should I just put the 4.2.0 as the ancestor and anyone with 4.2.1 will be able to install it without problems?

This looks like a documentation deficiency to me. There are a lot of scenarios that aren't addressed.

**Comment by VivekMChawla** [comment]
@dschach - Here are the answers to your questions:

1. A patch version is ONLY created if the `patch` portion of `major.minor.patch.build` is non-zero.  Even though it may look like your released version is something like `1.0.0.1`, the reality is that once you promote `1.0.0.1` it's locked into a **non-patch** `major.minor` version of `1.0`.  It doesn't matter how many build versions you created. It only matters which one of those you ended up promoting to the released state.

2. Ancestors can ONLY be set to released (i.e. non-beta) package versions whose `major.minor` version number is **lower** than the `major.minor` of the package version being created.  

3. A customer on `1.2.1` can install `1.3.0` as long as `1.2.0` is part of the lineage (i.e. "line of ancestry") of `1.3.0`.  Please note that `1.2.1` could **only** be installed in a subscriber org as an upgrade to an installed version of `1.2.0`.

4. For your example, package `4.3.0` must define `4.2.0` as its ancestor.  If it does, then both `4.2.0` and `4.2.1` subscriber installs can be upgraded directly to `4.3.0`.

5. Could you share a link to the documentation you found lacking? I'll take a fresh look at it to see if there's a better way to present this information. 

Thank you!

**Comment by dschach** [comment]
THANK YOU - those explanations make sense. 

Please see https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_config_upgrades.htm and look at the image - it needs some sort of explanation at what people are allowed to do.

**Comment by dschach** [comment]
FIXED!
