### ISSUE TITLE
Update cli-ux dependency to 5.0.0

### ISSUE THREAD

**Issue by catalandres** [forcedotcom/cli#157]
**Is your feature request related to a problem? Please describe.**
I want to be able to leverage the new supertable functionality in cli-ux 5.0.0, in a plugin project that I'm working on, including sorting, filtering and outputting CSV files.

**Describe the solution you'd like**
Update the cli-ux dependency to 5.0.0.

**Describe alternatives you've considered**
Updating the dependency at the plugin level.

**Additional context**
None

**Comment by mshanemc** [comment]
oclif-core is now using current cliUx, including all the breaking table changes.  

All of the CLI commands use the new oclif/core and you can, too.
