### ISSUE TITLE
snapshot:generate yields inconsistent whitespace

### ISSUE THREAD

**Issue by joshwlewis** [forcedotcom/cli#1570]
### Summary

When I run `./bin/dev snapshot:generate`, I get a `command-snapshot.json` that has extra whitespace compared to other folks. Here's an example: https://github.com/salesforcecli/cli/pull/240/commits/63303be11fe8206a77ba3ffc7e589487000bd128

### Steps To Reproduce:

**Repository to reproduce:** salesforcecli/cli

1.  `./bin/dev snapshot:generate`
1.  `git diff` shows a bunch of changes

### Expected result

`git diff` should not show any changes with no code changes.

### Actual result

`git diff` shows a large diff, and it's all whitespace. 

### System Information

```
▹ ./bin/dev version --verbose --json
@salesforce/cli/1.33.0 darwin-x64 node-v18.2.0
```

```
▹ ./bin/dev plugins --core
@oclif/plugin-autocomplete 1.3.0 (core)
@oclif/plugin-command-snapshot 3.1.3 (dev)
@oclif/plugin-help 5.1.12 (core)
@oclif/plugin-not-found 2.3.1 (core)
@oclif/plugin-plugins 2.1.0 (core)
@oclif/plugin-update 3.0.0 (core)
@oclif/plugin-version 1.0.4 (core)
@salesforce/cli 1.33.0 (core)
config 2.3.2 (core)
deploy-retrieve 1.4.3 (core)
env 1.3.2 (core)
functions 1.7.1 (prerelease)
generate 1.0.14 (core)
info 2.0.1 (core)
login 1.0.9 (core)
release-management 2.12.5 (dev)
└─ trust 1.1.0 (dev)
telemetry 2.0.0 (core)
```

**Comment by joshwlewis** [comment]
Further info on this:

`bin/dev snapshot:generate` does not run `prettier` on the `command-snapshot.json`. However, it looks like there is a `git` commit hook that runs prettier on this file:

```sh
$ /Users/josh.lewis/code/cli/node_modules/.bin/pretty-quick --staged
🔍  Finding changed files since git revision 9fb3b64.
🎯  Found 1 changed file.
✍️  Fixing up command-snapshot.json.
```

Since the snapshot on the main branch is not prettified, it looks like there is a pattern of developers bypassing the `git` commit hooks on `salesforcecli/cli`. The solution to my problem is to also bypass the commit hooks after regenerating the snapshot. For example:

```sh
$ bin/dev generate:snapshot
$ git add -A
$ git commit -m "chore: regenerate snapshot" --no-verify
```

/cc @RodEsp who helped me figure some of this out initially.

**Comment by RodEsp** [comment]
@joshwlewis are you ok if we close this now that https://github.com/salesforcecli/cli/pull/258 has been merged?

It doesn't make it so that `/bin/dev snapshot generate` uses prettify but as long as we're diligent about not allowing PRs that check in unprettified command snapshots this shouldn't be a problem again.
And also, running `yarn format` on `sf`'s repo will also format the command snapshot.

**Comment by joshwlewis** [comment]
Works for me =)
