### ISSUE TITLE
sfdx force:mdapi:convert fails to convert custom label component

### ISSUE THREAD

**Issue by yogeshdixit41** [forcedotcom/cli#1573]
I am trying to convert the metadata retrieved from an org using Metadata API into the source format using `sfdx force:mdapi:convert` but it fails to convert the CustomLabels components (under label directory).
I have tried different definitions in the package.xml and none of them works,

```
<types>
    <members>*</members>
        <name>CustomLabels</name>
</types>
```
![Screen Shot 2022-06-15 at 12 38 43 PM](https://user-images.githubusercontent.com/6316101/173880460-1ec5838f-17c3-4ccb-b6fc-1261d42ca0af.png)

even though I don't get any errors it does not convert anything and the output directory is empty

```
<types>
    <members>*</members>
        <name>CustomLabel</name>
</types>
```
![Screen Shot 2022-06-15 at 12 40 41 PM](https://user-images.githubusercontent.com/6316101/173880932-0ab326f2-a6bd-4569-b250-4bf97df0e5cc.png)
Here I get an error and so it obviously doesn't work

```
<types>
    <members>label_name</members>
        <name>CustomLabel</name>
</types>
```
![Screen Shot 2022-06-15 at 12 43 57 PM](https://user-images.githubusercontent.com/6316101/173881342-16faa073-2dc0-4ab6-88e3-89911acd508d.png)
get the same error as previous command

```
<types>
    <members>label_name</members>
        <name>CustomLabels</name>
</types>
```
![Screen Shot 2022-06-15 at 12 45 23 PM](https://user-images.githubusercontent.com/6316101/173881617-b73d3de0-eb24-4f78-b1d9-8e659cee4bee.png)

I also tried

`sfdx force:mdapi:convert --rootdir ../mdapipkg/unpackaged  --outputdir ../mdapipkg/temp_convert ` without the manifest option but it fails to add custom labels component to the output

![Screen Shot 2022-06-15 at 12 52 36 PM](https://user-images.githubusercontent.com/6316101/173883168-21e791ad-30c3-43b5-80ed-22cc73d5ca24.png)

sfdx -v verbose output
```
CLI Version : 
        sfdx-cli/7.154.0

 Architecture: 
        darwin-x64

 Node Version : 
        node-v16.15.0

 Plugin Version: 
        @oclif/plugin-autocomplete 0.3.0 (core)
        @oclif/plugin-commands 1.3.0 (core)
        @oclif/plugin-help 3.3.1 (core)
        @oclif/plugin-not-found 1.2.6 (core)
        @oclif/plugin-plugins 1.10.11 (core)
        @oclif/plugin-update 1.5.0 (core)
        @oclif/plugin-warn-if-update-available 1.7.3 (core)
        @oclif/plugin-which 1.0.4 (core)
        @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
        alias 2.0.1 (core)
        apex 0.13.0 (core)
        auth 2.0.3 (core)
        community 2.0.0 (core)
        config 1.4.11 (core)
        custom-metadata 1.1.0 (core)
        data 2.0.2 (core)
        generator 2.0.1 (core)
        info 2.0.1 (core)
        limits 2.0.1 (core)
        org 1.13.2 (core)
        salesforce-alm 54.4.0 (core)
        schema 2.1.1 (core)
        sfdx-cli 7.154.0 (core)
        signups 1.1.2 (core)
        source 1.10.2 (core)
        telemetry 2.0.0 (core)
        templates 54.8.0 (core)
        trust 2.0.0 (core)
        user 2.0.2 (core)

 OS and Version: 
        Darwin 21.3.0

```

**Comment by cristiand391** [comment]
Hey @yogeshdixit41 👋🏼 

I'll close this as dup of https://github.com/forcedotcom/cli/issues/1540, we are working to get this fixed next week, keep an eye on the issue so you can try the rc before it's promoted to stable, thanks!
