### ISSUE TITLE
force:org:create: A fatal signup error occurred

### ISSUE THREAD

**Issue by db-lyon** [forcedotcom/cli#1575]
Summary
It started to happen today, during scratch org creation I am receiving the following error which is a blocker for our development process, take a look pls with urgency, thanks.

### Steps To Reproduce:
authenticate to devhub
create new org shape
execute  `sfdx force:org:create` (I've tried this via local terminal & github actions)

### Expected result
scratch org should have been created successfully.

### Actual result
The following error is displayed:

ERROR running force:org:create: A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance.
Try this:
See https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_signuprequest.htm for information on error code C-9999.

System Information
SFDX versions tested:
sfdx-cli/7.154.0-1c265b4 (windows)
sfdx-cli/7.153.1-3ad97f8 (windows)
sfdx-cli/7.82.0-3d0c527ac6 (linux-x64)
sfdx-cli/7.94.3-a4e7c7955b (linux-x64)

**Comment by shetzel** [comment]
C-9999 is a server error that the CLI is simply reporting.  This is not a CLI bug.  I would contact Salesforce Customer Support since the CLI team cannot do anything about this error.  The support team will handle this with the urgency it requires.
