### ISSUE TITLE
Unable to push static resource to scratch org after v46.6.0

### ISSUE THREAD

**Issue by jefersonchaves** [forcedotcom/cli#158]
### Summary

I have a static resource in folder format and a single file, both of them fail to be pushed once I upgrade from v46.6.0 to any further version.

### Steps To Reproduce:

1.  Create a static file named singeFile (add its respective -meta.xml).
1.  Create a folder with some files on it named zipFile (add its respective -meta.xml)
1.  Create a scratch org.
1. Push the code.

### Expected result

Code pushed.

### Actual result
The push errors below:

| PROJECT PATH  | ERRORS |
| ------------- | ------------- |
| localFolder/singleFile.resource-meta.xml  | Required field is missing: content  |
| Required field is missing: content | The specified Static Resource is not a valid zip file  |
   
### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**:
sfdx-cli/7.19.0-c5be43915c darwin-x64 node-v10.15.3
Plugins:
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.0 (core)
salesforcedx 46.9.0
├─ force-language-services 46.13.0
└─ salesforce-alm 46.12.0

**OS and version**:
Mac OS Mojave 10.14.6 (18G87)

**Comment by clairebianchi** [comment]
@jefersonchaves, Just to be sure, you were able to push the file before? using the same command? Also how large is the file?

**Comment by jefersonchaves** [comment]
Hi @clairebianchi: yes, I'm able to push the file before. It is in an uncompressed folder and gets pushed by sfdx as a static resource as usual. 

I just triple checked with a brand new project, and now I think this is actually related to #152, because the problem is also that this static resource is assembled with symbolic links - the reason I'm doing that is to be able to share code between Managed Packages.

**Comment by fischerp** [comment]
This bug has been accepted by Salesforce. 
Bug Number #W-6535313

**Comment by jefersonchaves** [comment]
It has been fixed on version 46.15.3 (September 19, 2019).

"FIX: On macOS, the temporary zip file created when running force:source:push, force:source:deploy, or force:mdapi:deploy once again contains files that are symbolically linked."
Source: https://developer.salesforce.com/media/salesforce-cli/releasenotes.html

Closing this issue.
