### ISSUE TITLE
Return codes are different when calling sfdx force:create:org using Windows sfdx cli and the npm installed sfdx cli 

### ISSUE THREAD

**Issue by waterfif** [forcedotcom/cli#1580]
### Summary

Return codes from the "sfdx force:org:create" command differ if performed using the Windows SFDX CLI (see instructions [Install the CLI on Windows](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_windows:~:text=of%20the%20CLI-,Install%20the%20CLI%20on%20Windows,-Install%20Salesforce%20CLI)) versus the npm equivalent set up using the [Install the CLI with npm instructions](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_windows:~:text=of%20the%20CLI-,Install%20the%20CLI%20with%20npm,-If%20you%27ve%20installed). The Windows SFDX CLI will return 1 once the command has completed and the NPM equivalent will return 0. Both will create the org as expected however the Windows SFDX CLI version causes our setup script to exit. 

### Steps To Reproduce:

For each of Windows SFDX CLI and NPM SFDX CLI perform the following ensuring that your path is picking up the correct version of sfdx each time: 

1. Inside a known good project run: `sfdx force:org:create --setalias test1 --definitionfile config/project-scratch-def.json --durationdays 1 --wait 10`
2. The scratch org should have been created successfully
3. Once this has finished run: `echo $?`  

### Expected result

Both Windows SFDX CLI and NPM SFDX CLI should exit with a return code of 0

### Actual result

Windows SFDX CLI exits with a return code of 1

### System Information

 sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.155.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.1 (core)",
                "apex 0.13.0 (core)",
                "auth 2.1.0 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.3 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.5.1 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.155.1 (core)",
                "signups 1.1.2 (core)",
                "source 1.10.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 54.8.0 (core)",
                "trust 2.0.0 (core)",
                "user 2.0.2 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}

**Comment by RodEsp** [comment]
Hi @waterfif, which shell or terminal are you using?

The fact that you state to use `echo $?` makes me think you might be using git bash or WSL? If so, we don't support either of those, unfortunately.

I just tried and can't reproduce this on Powershell or cmd.exe.

`npm` version:
![image](https://user-images.githubusercontent.com/1084688/175319760-42deb7e2-8a8b-472e-80b2-2679825ce6f4.png)

installer version:
![image](https://user-images.githubusercontent.com/1084688/175319838-c11ba332-9840-4617-9afb-aa794811ddef.png)

**Comment by waterfif** [comment]
Hi RodEsp, 

Thanks for the response. You are correct, I'm using Git Bash locally. The script we use to setup scratch orgs on our Ubuntu CI environment is also used to setup our scratch orgs locally hence the use of Git Bash on Windows. I'll close the ticket as Git Bash is not supported.
