### ISSUE TITLE
`force:package:version:create`  is failing for all Custom Metadata records with Invalid Cross Reference Id.

### ISSUE THREAD

**Issue by chriskarpyszyn** [forcedotcom/cli#1582]
ISV Partners have a critical problem with the SFDX CLI to create 2GP packages.

 

Today, packaging with `force:package:version:create` started failing for all Custom Metadata records with the error Invalid Cross Reference Id

 

The error has been reported by others attempting to package today on SFXD. No changes to the code caused the error.

 

Blocked and need help ASAP.

**Comment by bbrummer** [comment]
Exact same issue here.  Our last successful build was June 20th (two days ago).  It began failing for us yesterday, including the exact same code revision we packaged successfully on the 20th.

We hadn't updated SFDX tooling in between, so this is most likely a Salesforce side bug. -AFAIK the SFDX cli does very little of the actual packaging and validation work, most all of that is handed on the Salesforce side.

**Comment by ClayChipps** [comment]
We are also now experiencing this issue, but as @bbrummer mentioned, this looks to be on the Salesforce "server" side, not on the CLI.

**Comment by m-rodriguez7** [comment]
Same here ... we are unable to create new package versions. The issue started last night. I have been able to recreate the problem with the dreamhouse app (see public repo linked below). I added a custom metadata record and proceeded to create a new package version. The following error is thrown for custom metadata records.

https://gitlab.com/mrodriguez1232/dreamhouse-lwc

ERROR running force:package:version:create:  Support_Tier.Bronze: An unexpected error occurred. Please include this ErrorId if you contact support: 1106878027-189513 (1860077356)

Salesforce CLI Version: sfdx-cli/7.155.1

**Comment by jwalke** [comment]
I'm seeing this as well with our Unlocked packages. This is blocking our ability to package/install code internally into our sandboxes and production environments.

**Comment by shetzel** [comment]
Thanks for posting.  It's a known issue and the team is working to revert the server code.  I'm not aware of a public KI post yet but I'll post here if I see one.

**Comment by chriskarpyszyn** [comment]
https://partners.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HXAq&fId=0D54V00006CgNsz

>Information Regarding 2GP Package Version Creation Issues (June, 22 2022)
It has been determined that a regularly scheduled Summer '22 maintenance release (238.10) contained a regression that may cause some 2GP package:version:create requests to fail.
NOTE: This issue only affects package version creation. Package upgrades and installations should not be affected in any way.
Salesforce R&D is in the final stages of testing a fix. We're working to get this into an emergency patch release ASAP. Once the patch is approved it will take approximately 24-72 hours to be deployed to all pods.
A KI for this issue is being created. I'll modify this post to include the link once it's available.
If you have any questions, please respond to this post and mention [@Vivek Chawla](https://partners.salesforce.com/0053000000Bgjd9) ([Salesforce.com](http://salesforce.com/)).
FYI: [@AppExchange & ISV Technical Enablement](https://partners.salesforce.com/0F9300000001s8i) [@Dileep Burki](https://partners.salesforce.com/00530000000wPVo) ([salesforce.com](http://salesforce.com/)) [@Vydianath Iyer](https://partners.salesforce.com/00530000003rhkS) ([Salesforce.com](http://salesforce.com/))

**Comment by keithrogersfenergo12** [comment]
We are also facing the same issue. 
I have raised a case with Salesforce to help increase the priority.

**Comment by user851** [comment]
I think there may be another facet to this issue. It appears that when a package with custom metadata types is declared as a dependency in the sfdx-project.json file the package that depends on it also can not have a version created. It fails stating

> An error occurred while trying to install a package dependency, ID (packageID): The data you were trying to access could not be found. It may be due to another user deleting the data or a system error. If you know the data is not deleted but cannot access it, please look at our <A href="{0}" title="support{1}">support</a> page.

At this point it's a little difficult to test this as we can't create a test package version with metadata, but from what I'm seeing this may also need to be investigated

**Comment by mlabrosse6** [comment]
We have also started experiencing this issue yesterday and cannot created a new package version.  Salesforce Support Case created to help push as priority.

**Comment by mohanraj-svmx** [comment]
We have also started experiencing this issue yesterday and cannot created a new package version. Salesforce Support Case created to help push as priority. It was success on 20th June, without code change we initiated which was failing from yesterday.

**Comment by Gontsov** [comment]
We have the same issue, started on 21 June

**Comment by VivekMChawla** [comment]
**Information Regarding 2GP Package Version Creation Issues (June, 22 2022)**

**IMPORTANT:** This will be the ONLY post I make here in GitHub.  Please see one of the following threads for further updates.

* [Partner Community Thread for Managed Packages](https://partners.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HXAq&fId=0D54V00006CgNsz) (Partner Login Required)
* [Trailblazer Community Thread for Unlocked Packages](https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000Hmv4uSAB)


Hello everyone. My name is Vivek M. Chawla.  I'm a Platform Expert for Packaging at Salesforce and work closely with the product and engineering teams.

It has been determined that a regularly scheduled Summer '22 maintenance release (238.10) released on June 20, 2022, contained a regression that may cause some 2GP `package:version:create` requests to fail.

This issue only affects package version creation. Package upgrades and installations should not be affected

Salesforce R&D has designed a fix for this issue. We're working to get this into an emergency patch release ASAP.  Once the patch is approved it will take approximately 24-72 hours to be deployed to all pods.  

**Please see one of the following threads for further updates.**

* [Partner Community Thread for Managed Packages](https://partners.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HXAq&fId=0D54V00006CgNsz) (Partner Login Required)
* [Trailblazer Community Thread for Unlocked Packages](https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000Hmv4uSAB)

**Comment by chriskarpyszyn** [comment]
At 6:40pm EST I was able to create a package.

**Comment by user851** [comment]
> At 6:40pm EST I was able to create a package.

Lucky You!

Patch roll-out status is [here](https://trailblazer.salesforce.com/issues_releases_view?release=238010001)

**Comment by shetzel** [comment]
This should now be fixed.
