### ISSUE TITLE
Deploying Manifest via CLI Returns Error

### ISSUE THREAD

**Issue by austin-convoy** [forcedotcom/cli#1586]
### Summary

Attempting to deploy a package with the sfdx or sf CLI returns an error with message `name.toLowerCase is not a function`. 

SFDX version: 1.156.1
@salesforce/cli version 1.34.0

### Steps To Reproduce:

Note: Cannot link internal company repository

1.  Create an Apex Class in VS Code
1.  Attempt to deploy to a connected Sandbox with CLI, e.g. `sfdx force:source:deploy -x manifest/packageTemp.xml`

### Expected result

Apex Class should deploy successfully to org

### Actual result

Error returned from CLI stderr stream `ERROR running force:source:deploy:  name.toLowerCase is not a function`

![Screen Shot 2022-06-23 at 9 49 53 AM](https://user-images.githubusercontent.com/103006721/175352537-b90a0675-8193-44d3-aaec-1b3f23b38378.png)

### System Information

- Shell: ZSH w/Oh-My-Zsh framework

- If you are using `sfdx`
❯ sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.156.1",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.0 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.6.0 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.156.1 (core)",
                "signups 1.2.0 (core)",
                "source 2.0.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.0 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Darwin 21.5.0"
}
- If you are using `sf`
❯ sf version
@salesforce/cli/1.34.0 darwin-x64 node-v16.15.1

❯ sf plugins --core
@oclif/plugin-autocomplete 1.3.0 (core)
@oclif/plugin-help 5.1.12 (core)
@oclif/plugin-not-found 2.3.1 (core)
@oclif/plugin-plugins 2.1.0 (core)
@oclif/plugin-update 3.0.0 (core)
@oclif/plugin-version 1.0.4 (core)
@salesforce/cli 1.34.0 (core)
config 2.3.2 (core)
deploy-retrieve 1.4.3 (core)
env 1.3.2 (core)
functions 1.7.1 (core)
generate 1.0.14 (core)
info 2.0.1 (core)
login 1.0.9 (core)
telemetry 2.0.0 (core)

**Comment by shetzel** [comment]
How did you generate `manifest/packageTemp.xml`?  It looks invalid.  The names of your apex classes are in the `<name>` elements rather than `<members>` elements.  It should instead be:
```
<types>
  <name>ApexClass</name>
  <members>AccountTeamTriggerHandler</members>
 ...
</types>
```
