### ISSUE TITLE
force:mdapi:deploy does not work with windows file path 

### ISSUE THREAD

**Issue by Szandor72** [forcedotcom/cli#159]
### Summary

_Short summary of what is going on or to provide context_.
![image](https://user-images.githubusercontent.com/16804218/63706891-ce802200-c830-11e9-9393-1bfee9c90606.png)

### Steps To Reproduce:

1.  Try force:mdapi:deploy on a windows machine using windows file path notation
2. notice: '/' works as folder delimiter and '\\\\' (double back-slash, 'escaped' backslash) works but not the single (windows-style) '\\'

### Expected result

I should be able to deploy with *nix and windows file paths

### Actual result

Deploy fails with error: 
The flag value ".\appero quote\main\default\aura\apo_BaseInputOutput"" is not in the correct format for "directory."

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**:
sfdx-cli/7.20.1-d88ae4707c win32-x64 node-v10.15.3

**OS and version**:
current stable Win10 built

**Comment by mshanemc** [comment]
Wow, that's really old!  we have tests that assert this behavior on windows.  If there's till an issue, please open a new issue.
