### ISSUE TITLE
Windows Server 2016: SFDX Update doesn't result in the latest CLI version

### ISSUE THREAD

**Issue by rajesh-kemisetti** [forcedotcom/cli#1590]
### Summary

_Running the sfdx update command, but the version still remains same though the update command says done._

### Expected result

_The CLI version should have got updated but still shows older version prior to the update.
**_sfdx --version_** 
 _Â»   Warning: sfdx-cli update available from 7.109.0 to 7.152.0.
sfdx-cli/7.109.0 win32-x64 node-v14.17.1__

### Actual result

_**sfdx update**_ 
_sfdx-cli: Updating CLI... fetching manifest_

_sfdx-cli: Updating CLI from 7.109.0 to 7.155.1-a22fcb0... done_

**_sfdx --version_** 
 _Â»   Warning: sfdx-cli update available from 7.109.0 to 7.152.0.
sfdx-cli/7.109.0 win32-x64 node-v14.17.1_

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
**_cmd.exe_**

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
	- **_sfdx version --verbose --json_** 
 _Â»   Warning: sfdx-cli update available from 7.109.0 to 7.152.0.
{
	"cliVersion": "sfdx-cli/7.109.0",
	"architecture": "win32-x64",
	"nodeVersion": "node-v14.17.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.2.2 (core)",
		"@oclif/plugin-not-found 1.2.4 (core)",
		"@oclif/plugin-plugins 1.10.0 (core)",
		"@oclif/plugin-update 1.4.0-3 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.0 (core)",
		"@oclif/plugin-which 1.0.3 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"@salesforce/sfdx-trust 3.6.0 (core)",
		"alias 1.1.10 (core)",
		"apex 0.2.2 (core)",
		"auth 1.7.1 (core)",
		"config 1.2.12 (core)",
		"custom-metadata 1.0.12 (core)",
		"data 0.4.12 (core)",
		"generator 1.1.7 (core)",
		"limits 1.2.1 (core)",
		"org 1.6.7 (core)",
		"salesforce-alm 52.0.4 (core)",
		"schema 1.0.7 (core)",
		"sfdx-cli 7.109.0 (core)",
		"source 2.0.1",
		"telemetry 1.2.2 (core)",
		"templates 52.1.0 (core)",
		"user 1.3.0 (core)"
	],
	"osVersion": "Windows_NT 10.0.14393"
}_

**Comment by shetzel** [comment]
Can you try running `sfdx plugins:uninstall source` first, then `sfdx update`.  If it still doesn't update, run `sfdx update --dev-debug` and look for something in the debug output that might indicate the problem.  You can attach the last ~50 lines if nothing stands out.
