### ISSUE TITLE
SFDX force:source:retrieve working slowly on version 7.156.1

### ISSUE THREAD

**Issue by JMercie** [forcedotcom/cli#1595]
### Summary

When attempting to use the command in the title or the VScode task to retrieve metadata, the command will take up to 6 minutes to retrieve a single file.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  run the command sdfx  force:source:retrieve -m "any metadata here"

### Expected result

If the metadata we try to retrieve exists in the org, we should be able to retrieve it in less than a minute.

### Actual result

It's taking up to 6 minutes per file.

### System Information

- Which shell/terminal are you using? Bash

```json
{
        "cliVersion": "sfdx-cli/7.156.1",
        "architecture": "wsl-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.0 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.6.0 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.156.1 (core)",
                "signups 1.2.0 (core)",
                "source 2.0.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.0 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Linux 5.4.72-microsoft-standard-WSL2"
}
```

**Comment by maggiben** [comment]
Hi, Im retrieving metadata like so and I don't see excessive slowness: 

<img width="962" alt="image" src="https://user-images.githubusercontent.com/2845947/177399848-ae4986f7-781f-4611-a8cc-a2ae5144b90e.png">

Could this be attributed to your network and or device ? Can you try running this command from other machines/network and see if that makes any difference ?

**Comment by mshanemc** [comment]
@JMercie if this still happens (sometimes the server has a rough day and the problem gets better eventually), can you please re-run the command with DEBUG=* in front of it so you can see the debug output and share it here?

Those timestamps should help us see if it's something on the client or the server.

**Comment by JMercie** [comment]
Hello @mshanemc and @maggiben! 

Since last week I'm also trying to run the command from a different device and location, and today I just try @mshanemc idea to use the DEBUG=* at the beginning. Here is the output.

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/53920455/178836381-7c403e35-0b24-44db-a94f-07b36d72b29b.png">

9min 27 secs for a single Apex class.

**Comment by mshanemc** [comment]
can you share the OrgId and the Instance (from Company Information in the setup UI)?  

Based on the debug logs, I think this is more likely to be on the server and not in the CLI but the mdapi team may be able to help see what's causing it if it's in their logs

**Comment by JMercie** [comment]
The OrgId is "00D56000000LE0U". Could you please explain to me what would it mean that the problem is on the server and not the CLI? would that mean is related to the sandbox?

**Comment by mshanemc** [comment]
yeah, if the CLI sends the retrieve request and then it takes the server 9 minutes to respond with the metadata, then that's on the server.  

If the CLI is spending 9 minutes before sending the request, or 9 minutes handling the response, then that's not the server.

**Comment by JMercie** [comment]
Which actions can I take to try to solve this? 😞

**Comment by mshanemc** [comment]
If it can be reproduced reliably, open a salesforce case with all this information.  They may be able to find it in logs that I don't have access to and see what's going on.  Or they might log into your org and try it themselves.
