### ISSUE TITLE
Commands throwing error on Jenkins when Jenkins is using JenkinsFile

### ISSUE THREAD

**Issue by SurbhiDemo198** [forcedotcom/cli#1596]
Hi, 

I am getting this error on running the sfdx force:source:push in my Jenkins file
![image](https://user-images.githubusercontent.com/107412078/176182780-6fc5c255-ff95-4650-911a-5a4d44a2abc4.png)

**Comment by shetzel** [comment]
Your script has to change directories to the root of your project before running `force:source:push`.  That is what the error means.  Commands that require a project look for the `sfdx-project.json` file in the current working directory and if it's not found it will throw that error.  Please reopen with more details if this is not the case.
