### ISSUE TITLE
SFDX - force:mdapi:convert - Component conversion failed: getaddrinfo ENOTFOUND mdcoverage.secure.force.com

### ISSUE THREAD

**Issue by CedricWillems** [forcedotcom/cli#1597]
### Summary

Running force:mdapi:convert command results in failure. The work environment is a proxy environment. So all traffic should go through the proxy. But it seems that 'mdcoverage.secure.force.com" is trying a direct connection.

### Steps To Reproduce:

run command:
sfdx force:mdapi:convert --rootdir C:\Users\<user>\AppData\Local\Temp\2\.sfdx\tools\conflicts\<org>\unpackaged --outputdir C:\Users\<user>\AppData\Local\Temp\2\.sfdx\tools\conflicts\<org>\converted --dev-debug

### Expected result

store converted metadata in "C:\Users\<user>\AppData\Local\Temp\2\.sfdx\tools\conflicts\<org>\converted"

### Actual result

ERROR running force:mdapi:convert:  Component conversion failed: getaddrinfo ENOTFOUND mdcoverage.secure.force.com 

### System Information

- Which shell/terminal are you using? VSCode terminal

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
{
        "cliVersion": "sfdx-cli/7.156.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.0 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.6.0 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.156.1 (core)",
                "signups 1.2.0 (core)",
                "source 2.0.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.0 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.18363"
}
 
### Additional information
![image](https://user-images.githubusercontent.com/20746282/176211425-c3731671-9d32-4159-9bd8-15647ba035fd.png)
![image](https://user-images.githubusercontent.com/20746282/176211495-70d15ac8-1fa6-47bc-a8bf-2d1c9c6f6a59.png)

**Comment by maggiben** [comment]
Hello, this is probably due to DNS not being resolved can you try setting env var `SFDX_DISABLE_DNS_CHECK` ?

**Comment by CedricWillems** [comment]
> Hello, this is probably due to DNS not being resolved can you try setting env var `SFDX_DISABLE_DNS_CHECK` ?

Tried that. No difference. Also issue only happens with this specific command. And only started happening when I updated the CLI.

**Comment by maggiben** [comment]
HI can you please upload an org so we can try reproduce this issue ?

**Comment by JohanJohanson** [comment]
I also experienced this behavior for the auth:jwt:grant command, 7.145.0 is using the proxy settings all versions after that will not use proxy settings but a direct connection instead.

**Comment by mshanemc** [comment]
@JohanJohanson that's a different issue, but you can follow it here (and there seems to be a workaround until we get the actual fix in jsforce) https://github.com/forcedotcom/cli/issues/1626
