### ISSUE TITLE
sfdx force:org:open does not work in sandboxes with enhanced domains enabled

### ISSUE THREAD

**Issue by ganesh2109-cloud** [forcedotcom/cli#1603]
### Summary

In recently created sandboxes, sfdx force:org:open cannot resolve lightning domain after enhanced domains are enabled. 

### Steps To Reproduce:

Try sfdx force:org:open for a sandbox with enhanced domain enabled. When done, the .lightning.force.com domain is not available for the DNS lookup. Because of this, the following error is seen in the debug logs:
{"name":"sfdx","hostname":"LPZWN**********","pid":17004,"log":"MyDomainResolver","level":20,"msg":"Error: getaddrinfo ENOTFOUND **-**--*******.lightning.force.com","time":"2022-07-03T22:39:59.683Z","v":0}

### Expected result

Default browser should open up with the autheticated session of a given user

### Actual result

{"name":"sfdx","hostname":"LPZWN********","pid":6128,"log":"OrgOpenCommand","level":50,"msg":"[\n  '\\x1B[1mERROR running force:org:open: \\x1B[22m',\n  '\\x1B[31mThe client has timed out.\\x1B[39m'\n]","time":"2022-07-03T22:23:49.670Z","v":0}

### System Information

{
        "cliVersion": "sfdx-cli/7.154.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v18.1.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.0.1 (core)",
                "apex 0.13.0 (core)",
                "auth 2.0.3 (core)",
                "community 2.0.0 (core)",
                "config 1.4.11 (core)",
                "custom-metadata 1.1.0 (core)",
                "data 2.0.2 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.4.0 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.154.0 (core)",
                "signups 1.1.2 (core)",
                "source 1.10.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 54.8.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.0.2 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}

**Comment by ganesh2109-cloud** [comment]
After looking at the implementation in the core module, the workaround is to set the environment variable SFDX_DISABLE_DNS_CHECK to true but ofcourse it is not a structural solution.

**Comment by cristiand391** [comment]
Hey @ganesh2109-cloud, this seems like a dup of https://github.com/forcedotcom/cli/issues/1556

Can you try installing latest-rc and see if the fix works for you? Thanks!

**Comment by ganesh2109-cloud** [comment]
Works with latest-rc [7.158.1]. Thanks again!
