### ISSUE TITLE
Intermittent duplicate picklist value errors

### ISSUE THREAD

**Issue by jwalke** [forcedotcom/cli#1605]
### Summary

Starting within the last 24 hours, we’ve started seeing a high rate of intermittent errors when executing sfdx force:source:push and during unlocked package version creation. The errors are related to duplicate picklist values. For example:

`Incident_Report__c.Claim: Duplicate picklist value:Possible_Safety_Rule_Violation__c - No`

We haven’t touched the related schema recently. Re-trying sometimes will resolve the issue or return duplicate picklist value errors related to different schema. 

### Steps To Reproduce:

Note: I attempted to reproduce this issue using a version of the Dreamhouse app where I added a record type to a custom object, but was unable to quickly reproduce the issue in that sample project. As this issue is intermittent, I suspect it may occur more frequently in when pushing schema that contains a large number of record types and/or picklist fields. 

Run `sfdx force:source:push`

### Expected result

Source pushes successfully

### Actual result

One or more errors are returned, similar to this one: 

`Incident_Report__c.Claim: Duplicate picklist value:Possible_Safety_Rule_Violation__c - No`

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
zsh

- SFDX version info:
```
❯ sfdx version --verbose --json
{
	"cliVersion": "sfdx-cli/7.157.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.15.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 2.1.0 (core)",
		"apex 0.13.0 (core)",
		"auth 2.2.0 (core)",
		"community 2.0.0 (core)",
		"config 1.4.12 (core)",
		"custom-metadata 2.0.0 (core)",
		"data 2.0.4 (core)",
		"generator 2.0.1 (core)",
		"info 2.0.1 (core)",
		"limits 2.0.1 (core)",
		"org 1.13.2 (core)",
		"salesforce-alm 54.6.1 (core)",
		"schema 2.1.1 (core)",
		"sfdx-cli 7.157.0 (core)",
		"signups 1.2.0 (core)",
		"source 2.0.3 (core)",
		"telemetry 2.0.0 (core)",
		"templates 55.0.0 (core)",
		"trust 2.0.0 (core)",
		"user 2.1.0 (core)"
	],
	"osVersion": "Darwin 21.5.0"
}
```

### Additional information

This issue has been reported by other users in the Salesforce Community in these posts:
https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000HEAATSA5
https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000HEACASA5
https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000HEAGrSAP
https://salesforce.stackexchange.com/questions/380061/sfdx-source-push-failing-on-duplicate-picklist-value

**Comment by yippie** [comment]
This started today and also is happening with CLI version 7.151

Our entire CI and testing process is full stop right now because of this.

**Comment by jawildey** [comment]
I have have a Salesforce Case regarding this issue, but they created it as a Sev 4 at the moment.  If other users contact Salesforce they will see the urgency in getting this resolved as quickly as possible.

**Comment by vernemi2** [comment]
Exactly the same behaviour. Started happening today. Actually also on ‘No’ picklist value, so wondering if that’s a coincidence or not…

What we're getting is this for example:
`Duplicate picklist value:Chimney_Installation_OK__c - No`

We have loads of picklist values in our org which are No, Yes + sometimes something on top of that. So the picklist which errors out varies, but it's always on the `No` value

**Comment by Brian-Triplett** [comment]
We are seeing this as well and logged it as a Sev 2. It's completely disrupting all our ISV operations as we are having broad an intermitent  deployment failures with the `Duplicate picklist value:` message. Seems to affect both source pushes and metadata deployments.

**Comment by goto-dev-null** [comment]
Also seeing this. We started encountering this literally overnight. Didn't even upgrade SFDX at all.

I downgraded to 7.150.0 and the issue persists.

> Exactly the same behaviour. Started happening today. Actually also on ‘No’ picklist value, so wondering if that’s coincidence or not…

Fascinating. Same here. Seems too specific to be a coincidence.

The weirdest thing is that the error varies. It always gives "Duplicate picklist value:Sponsorship__c - No" but only *sometimes* gives "Duplicate picklist value:StaticOrVariableRates__c - No".

**Comment by JoseBerbel** [comment]
We started to see this error yesterday, I updated to last version sfdx-cli/7.157.0 linux-x64 node-v16.15.1 and still is happening.
Adding isActive true to the field is working but always another different field is failing.

**Comment by Javivb** [comment]
Same issue here! 2 days now with our CI process blocked

**Comment by aidiagre** [comment]
Same here, even updating to the latest version, scratch orgs are still failing

**Comment by elizabetef** [comment]
Same situation for us too, happening since yesterday seemingly out of nowhere, most frequently with Yes/No type of picklists and the value "No". Our whole development/release cycle is being affected by this issue at the moment.

**Comment by ivelinganev** [comment]
The same here. Randomly errors occur when we are trying to push code in the Scratch Org or create a new one!

**Comment by MiguelAngelGalindo** [comment]
We are having the same issue, it started yesterday for us and completely random picklists on random objects with values Yes or No.
we cannot create scratch orgs or deploy.

**Comment by DavidGodoyEbury** [comment]
Same issue here. Any fix or workaround for the problem?

**Comment by giri-uipath** [comment]
Yes, so much for Semantic versioning. Why bother If we are going to break things anyway.
On a related note, not sure who needs to hear this - but the metadata structure for picklists that are associated to recordTypes needs a complete rethink. The current structure clearly is not working especially in the context of 2GP.

**Comment by sheetalpathak31** [comment]
We were facing the same issue since yesterday afternoon (2pm UK time)
Just kicked off the deployment again an hour back and it deployed successfully !
So not sure if the fix is already in place... but worth trying again.
good luck folks !

**Comment by toddhalfpenny** [comment]
I had also experienced this yesterday when installing managed packages.

**Comment by jwalke** [comment]
It looks like this issue may have been fixed server-side overnight. Is anyone still observing the issue?

**Comment by jeffrey-faber** [comment]
Fixed for me

**Comment by Javivb** [comment]
yeah, fixed here as well

**Comment by Brian-Triplett** [comment]
I believe this was the related incident and seems like this resolved it: http://status.salesforce.com/incidents/9417

**Comment by jawildey** [comment]
The issue appears to have been resolved with the following incident: https://status.salesforce.com/incidents/9417.  I tested our sandbox and there were no issues.

**Comment by madhankumargi** [comment]
New picklist value added as part of the commit is not included when we create new package version

Steps to reproduce 👍 
Add a new picklist to a custom field on Custom Object
Add a new flow as well
Create a new package version and when you install in other org you will not see the new picklist

**Comment by Julian88Tex** [comment]
@madhankumargi sounds like that should be a new issue separate from this one.

**Comment by jwalke** [comment]
> New picklist value added as part of the commit is not included when we create new package version

@madhankumargi See this known issue: https://trailblazer.salesforce.com/issues_view?id=a1p3A0000003Uk2QAE&title=picklist-values-not-getting-deployed-during-unlocked-package-upgrades
