### ISSUE TITLE
Scratch Org creation fails when using "sf env create" command

### ISSUE THREAD

**Issue by sumanthreddybolledla** [forcedotcom/cli#1608]
### Summary

Unable to create scratch org using "sf env create scratch" command. I get the below error 
<img width="619" alt="image" src="https://user-images.githubusercontent.com/19957368/177639054-bb5deea8-37a3-4673-957a-1bec70df5d28.png">

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  run the below command(the definition file I use is very basic):
sf env create scratch --target-dev-hub=DevHub --definition-file config/project-scratch-def.json -w 1000

### Expected result

Scratch Org should have been created

### Actual result

Error while creating Scratch org

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
- cmd

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- Paste the output here
@salesforce/cli/1.34.0 win32-x64 node-v16.15.1
@oclif/plugin-autocomplete 1.3.0 (core)
@oclif/plugin-help 5.1.12 (core)
@oclif/plugin-not-found 2.3.1 (core)
@oclif/plugin-plugins 2.1.0 (core)
@oclif/plugin-update 3.0.0 (core)
@oclif/plugin-version 1.0.4 (core)
@salesforce/cli 1.34.0 (core)
config 2.3.2 (core)
deploy-retrieve 1.4.3 (core)
env 1.3.2 (core)
functions 1.7.1 (core)
generate 1.0.14 (core)
info 2.0.1 (core)
login 1.0.9 (core)
telemetry 2.0.0 (core)
### Additional information

_Feel free to attach a screenshot_.

**Comment by mshanemc** [comment]
can you run the update to get your plugins updated?

`plugin-env` should be on a newer version than that

**Comment by sumanthreddybolledla** [comment]
Hi @mshanemc ,

I have updated the env plugin to 1.5.1 version, I can see it is working fine. However, when I try to use Org-Shape I get the below error using sf command
<img width="881" alt="image" src="https://user-images.githubusercontent.com/19957368/177810223-b7aff812-8628-483f-a50a-2ec01b681d0a.png">

**Comment by tprouvot** [comment]
Hi @sumanthreddybolledla,
Does your dev hub alias is "DevHub" ? It looks like you copied the alias given in the doc and did not replace it with yours
