### ISSUE TITLE
invalid logging about file that doesn't exist

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#1609]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1. DEBUG=* sfdx force:org:beta:create -f config/project-scratch-def.json -d 1 -s

### Expected result

don't warn about non-existing file

### Actual result

```sh
sf:SfProjectJson INFO Reading config file: /Users/shane.mclaughlin/.sfdx/sfdx-project.json +32ms
  sf:SfProjectJson INFO Reading config file: /Users/shane.mclaughlin/eng/repros/forcedotcom-issue-scratchOrg-objectSettings/sfdx-project.json +0ms
  sf:SfProjectJson TRACE Setup child 'SchemaValidator' logger instance +3ms
  sf:SchemaValidator DEBUG Schema loaded for /Users/shane.mclaughlin/eng/sfdx-core/node_modules/@salesforce/schemas/sfdx-project.schema.json +35ms
  sf:SfProjectJson WARN The config file "/Users/shane.mclaughlin/.sfdx/sfdx-project.json" is not schema valid.
  sf:SfProjectJson Due to: Validation errors:
  sf:SfProjectJson #/required: must have required property 'packageDirectories' +11ms
  sf:SfProjectJson TRACE Setup child 'SchemaValidator' logger instance +7ms
  sf:SchemaValidator DEBUG Schema loaded for /Users/shane.mclaughlin/eng/sfdx-core/node_modules/@salesforce/schemas/sfdx-project.schema.json +19ms
  sf:SfProjectJson TRACE Setup child 'SchemaValidator' logger instance +13ms
  sf:SchemaValidator DEBUG Schema loaded for /Users/shane.mclaughlin/eng/sfdx-core/node_modules/@salesforce/schemas/sfdx-project.schema.json +13ms
  sf:SfProjectJson TRACE Setup child 'SchemaValidator' logger instance +10ms
  sf:SchemaValidator DEBUG Schema loaded for /Users/shane.mclaughlin/eng/sfdx-core/node_modules/@salesforce/schemas/sfdx-project.schema.json +9ms
  sf:SfProjectJson WARN The config file "/Users/shane.mclaughlin/.sfdx/sfdx-project.json" is not schema valid.
  sf:SfProjectJson Due to: Validation errors:
  sf:SfProjectJson #/required: must have required property 'packageDirectories' +10ms

```

### System Information
- zsh
{
	"cliVersion": "sfdx-cli/7.158.1",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.15.1",
	"pluginVersions": [
		"@mshanemc/sfdx-migration-automatic 0.3.1",
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 2.0.4 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
		"alias 2.1.0 (core)",
		"apex 0.13.0 (core)",
		"auth 2.2.2 (core)",
		"community 2.0.0 (core)",
		"config 1.4.12 (core)",
		"custom-metadata 2.0.0 (core)",
		"data 2.0.4 (core)",
		"generator 2.0.2 (core)",
		"info 2.0.1 (core)",
		"limits 2.0.1 (core)",
		"org 2.0.1 (core)",
		"release-management 2.13.0",
		"└─ trust 1.1.0",
		"salesforce-alm 54.6.2 (core)",
		"schema 2.1.1 (core)",
		"sfdx-cli 7.158.1 (core)",
		"shane-sfdx-plugins 4.43.0",
		"├─ @mshanemc/plugin-streaming 1.1.7",
		"└─ @mshanemc/sfdx-sosl 1.1.0",
		"signups 1.2.0 (core)",
		"source 2.0.3 (core)",
		"telemetry 2.0.0 (core)",
		"templates 55.0.0 (core)",
		"user 2.1.0 (core)"
	],
	"osVersion": "Darwin 21.5.0"
}

**Comment by maggiben** [comment]
@mshanemc is this a feature request or a bug ?
