### ISSUE TITLE
sfdx force:source:push --quiet failing on Mac with error "Unexpected argument: --quiet"

### ISSUE THREAD

**Issue by manjot0074** [forcedotcom/cli#1611]
### Summary

When i am running "sfdx force:source:push --quiet" on my mac it is failing with error "Unexpected argument: --quiet". My sfdx version is sfdx-cli/7.157.0.

<img width="585" alt="Screenshot 2022-07-07 at 1 18 48 PM" src="https://user-images.githubusercontent.com/18004394/177722338-385ac04f-299d-4a15-89c9-f1dad5e5e037.png">

I tried running this on linux system it was working fine. I ran this on Travis CLI.

Reproducing Steps:- 
1.  Run sfdx force:source:push --quiet command on mac OS

### Expected result

Command should run without showing list of files deployed

### Actual result
Command fails with above error

### System Information

- VS Code terminal

- If you are using `sfdx`
	{
        "cliVersion": "sfdx-cli/7.157.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "alias 2.1.0 (core)",
                "auth 2.2.0 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "etcopydata 0.5.7",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "salesforcedx 52.0.0",
                "├─ salesforce-alm 52.0.0",
                "├─ data 0.4.11",
                "├─ apex 0.2.2",
                "├─ org 1.6.6",
                "├─ user 1.3.0",
                "├─ limits 1.2.1",
                "├─ custom-metadata 1.0.12",
                "├─ schema 1.0.7",
                "├─ templates 51.5.0",
                "└─ @salesforce/sfdx-plugin-lwc-test 0.1.7",
                "sfdx-cli 7.157.0 (core)",
                "signups 1.2.0 (core)",
                "source 2.0.3 (core)",
                "telemetry 2.0.0 (core)",
                "texei-sfdx-plugin 1.16.0",
                "trust 2.0.0 (core)"
        ],
        "osVersion": "Darwin 21.5.0"
}

_Feel free to attach a screenshot_.

**Comment by maggiben** [comment]
`--quiet` param is working fine in the `latest-rc` can you try installing that version ? 
<img width="655" alt="image" src="https://user-images.githubusercontent.com/2845947/178020315-a75ec992-dd08-4c37-b16f-86fe56672023.png">

**Comment by cristiand391** [comment]
@manjot0074 can you uninstall the `salesforcedx` plugin? That was deprecated and is possibly taking precedence over the current plugin-source commands which have the `--quiet` flag defined.

Question: didn't you get a warning when updating your CLI about this plugin?
We added some logic here just for this plugin: https://github.com/salesforcecli/sfdx-cli/pull/436

**Comment by mshanemc** [comment]
Remove the salesforcedx plugin `sfdx plugins:uninstall salesforcedx`
reinstall your CLI if that doesn't fix it.
