### ISSUE TITLE
mdapi deploy report timeout error for in progress deployments

### ISSUE THREAD

**Issue by t-zakar** [forcedotcom/cli#1612]
### Summary

Since the sfdx v7.150.0, the sfdx force:mdapi:deploy:report --wait 1 command are failing with an error message when I use to query status of an in progress deployment.
'MetadataTransfer:Metadata API request failed: The client has timed out.'
The sfdx force:mdapi:legacy:deploy:report command is still working but it is deprecated and will be removed.

### Steps To Reproduce:

1. Start a deploy which is running long time (we have 2000 tests, running ~3 hours):
$deployJob = sfdx force:mdapi:deploy --deploydir ./deploydir --ignorewarnings -w 0 --testlevel RunLocalTests -u $deployUser --json | ConvertFrom-Json
2. Query the status of the deployment:
$report = sfdx force:mdapi:deploy:report -i $deployJobId --wait 1 -u $deployUser --json 2>&1 | ConvertFrom-Json 
(We are using this from Azure pipeline)

### Expected result

status in json format

### Actual result

MetadataTransfer:Metadata API request failed: The client has timed out.

### System Information

PS > sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.158.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.2 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.2 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 2.0.1 (core)",
                "salesforce-alm 54.6.2 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.158.1 (core)",
                "sfdx-git-delta 5.3.0",
                "signups 1.2.0 (core)",
                "source 2.0.3 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}

### Additional information

But it does not matter from where you start the deploy, when you use the 'sfdx force:mdapi:deploy:report -i $deployJobId --wait 1 -u $deployUser --json' on a deploy in progress, it returns 'MetadataTransfer:Metadata API request failed: The client has timed out.' error.
When you use this on a deployment is already finished or cancelled, it is working as expected.
Before the sfdx version 7.150.0 it was working, and the force:mdapi:legacy:deploy:report command still working.

Please fix it before removing the force:mdapi:legacy:deploy:report command.

**Comment by maggiben** [comment]
Hello, is this happen frequently, can it be attributed to network issues ?

**Comment by t-zakar** [comment]
Hi, no, it is happening always.. and the force:mdapi:legacy:deploy:report is working always

**Comment by mshanemc** [comment]
has the deployment completed when you run `sfdx force:mdapi:deploy:report --wait 1` ?  Or is it still pending/in progress? (you can check Deployment Status in an org's UI to see).

If yes, what happens if you put it to a larger number than 1, like (--wait 10)?  Does it still fail?

**Comment by t-zakar** [comment]
If the deploy is in progress I get this error, even with --wait 10. If the deploy is completed it is working fine.
I use this command to monitoring a deploy from a powershell script in Azure pipeline and it had worked before the sfdx version 7.150.0.

**Comment by mshanemc** [comment]
one more question: does the same happen if you use `force:source:deploy:report` with the same jobid on an in progress job ?  If so, I'll make sure that gets fixed there, too.

**Comment by t-zakar** [comment]
> one more question: does the same happen if you use `force:source:deploy:report` with the same jobid on an in progress job ? If so, I'll make sure that gets fixed there, too.

I don't know, we don't use that command.

**Comment by mshanemc** [comment]
it's good, we'll fix them both to handle this timeout thing

**Comment by shetzel** [comment]
@t-zakar - note that by providing `-w 1` to the report command you are polling for the deploy status for a minute (which is how the client timeout error comes back).  If you want an immediate response you could either leave off the `wait` param or specify `-w 0` (which is the default when omitted).  Not sure if this fits with what your script does but thought I'd mention it in case it does.

Regardless, it doesn't match the behavior of the legacy command so it'll be fixed.

**Comment by RohitGagan16** [comment]
I am also facing the same issue and i am using the version sfdx-cli/7.160.0 
Waiting for the upcoming fix

**Comment by RohitGagan16** [comment]
Hi,
Is this be fixed in the upcoming sfdx release?

Regards
Rohit

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RohitGagan16** [comment]
@mshanemc Could you please confirm if this is fixed in July 28 th rc release

**Comment by peternhale** [comment]
@RohitGagan16 it is not is the 7/28 release.

**Comment by RohitGagan16** [comment]
With which release this be available?
Regards
Rohit

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by t-zakar** [comment]
I have just tried the version 7.162.0, it is working fine, thanks.
