### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by Shadlimitless** [forcedotcom/cli#1613]
I have a scratch org that is created from a snapshot feature. Until version 7.153.0, we were able to change the language via sfdx by using the command: `sfdx force:data:record:update --sobjectid=$(sfdx force:user:display --json -v DevHub | jq .result.id | tr -d '"') --sobjecttype=User --values="LanguageLocaleKey=en_US"`

After upgrading we keep getting the error TypeError: Cannot read properties of undefined (reading 'prototype'). See attached image 
<img width="651" alt="sfdx error on lang change" src="https://user-images.githubusercontent.com/12892045/177795955-e4646e00-eb17-42f5-8c9e-77165ed93187.PNG">

**Comment by maggiben** [comment]
Hello, is this issue related to a specific version ? can you you please share the output of `sfdx --version --verbose` also was this issue introduced recently maybe after an update of the CLI ?

**Comment by mshanemc** [comment]
use `-u` and not `-v`.

There's no requirement that this command uses a devhub, so we're removing that flag at some point.
We didn't mean for it to stop working, but it was going to in Winter anyway, so you might as well change it now.

**Comment by azanatta** [comment]
I'm having the same issue using the scanner v.3 when launching 
`sfdx scanner:run:dfa --target .\main\default\ --json`

`TypeError: Cannot read properties of undefined (reading 'prototype')`
