### ISSUE TITLE
sfdx update broke deploy/retrieve

### ISSUE THREAD

**Issue by dcraigmile1357911** [forcedotcom/cli#1617]
I just did an **sfdx update** and now when I save-and-deploy any file using CNTL-S or from the right-click menu I get this error:

Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

**Nothing else changed at all.**  Just an sfdx upgrade.  I am running VS Code on a Windows 11 PC.  All this has been working fine for years so nothing new here.....

My sfdx-project.json has never changed and was working until the upgrade:

{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "name": "TMS",
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "54.0"
}

**Comment by balderm** [comment]
Can confirm, same problem on my end with a similar machine, no changes done to my project, all i did was update Salesforce CLI extensions, VSCode and SFDX.

@dcraigmile1357911 Manually downgrading the "Salesforce CLI Integration" and "Apex" extensions to the previous version (55.3.0) fixed the issue for me

**Comment by dcraigmile1357911** [comment]
Thanks, balderm.  Would you have the exact command to downgrade?

**Comment by balderm** [comment]
> Thanks, balderm. Would you have the exact command to downgrade?

It's fairly simple, go in the Extensions tab in VSCode, right click on the Extension you want to downgrade then select "Install another version..." from there select the older version (55.3.0)

**Comment by dcraigmile1357911** [comment]
Cool thank you.  That worked for me.

**Comment by abuwahid16** [comment]
I had the same issue, spent at least 2 hours, no clues, did changes on directory, downgraded VSCode version, setup everything fresh, didn't work. Found "https://developer.salesforce.com/forums/?id=9062I000000IFKyQAO" the last comment help.
I downgraded to 55.3.0 (also this works 55.2.0) and everything working now.

**Comment by cromwellryan** [comment]
Thank you all for reporting the issue. [Version 55.4.1 of Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode) has been published and resolves the issue. Check out the [release notes](https://github.com/forcedotcom/salesforcedx-vscode/releases/tag/v55.4.1) for more info.
