### ISSUE TITLE
QUESTION -- Why does force:package:installed:list need project?

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#162]
Quick question.  Why is it that the `force:package:installed:list` command needs to be executed in a SFDX project?  What from a project does it need to execute?  The command only accepts one flag and that is the targetusername flag.

**Comment by ImJohnMDaniel** [comment]
@clairebianchi -- Is there an answer to the question??

**Comment by clairebianchi** [comment]
Yes, sorry working with Dileep on this :)

**Comment by ImJohnMDaniel** [comment]
Thank you very much!

**Comment by clairebianchi** [comment]
@ImJohnMDaniel can you please ask this question in the trailblazer community?

**Comment by ImJohnMDaniel** [comment]
Done

Here is the post -- https://success.salesforce.com/0D53A00004bau0j
