### ISSUE TITLE
Package version creation is failing intermittently with error: Before you can use this duplicate rule, all associated matching rules must be active and have their fields mapped.

### ISSUE THREAD

**Issue by honeyverma** [forcedotcom/cli#1621]
### Summary

We have our CI-CD pipeline which creates a new version for every PR/Push, however, sometimes it gets failed intermittently with the error: ```ERROR running force:package:version:create:  Before you can use this duplicate rule, all associated matching rules must be active and have their fields mapped.```

So if we retry (without any changes) the process, it creates a package version successfully

PS: We always installed a new version of SFDX in our pipeline server

### Steps To Reproduce: (in our unlocked package repo pipeline)

1. Install sfdx: `npm i sfdx-cli --global`
2. Dev-hub auth: `sfdx auth:jwt:grant --clientid *** --jwtkeyfile server.key --username *** --setdefaultdevhubusername -a <devHubAlias>`
3. Create package version: `sfdx force:package:version:create -p onagsf -d force-app -k test1234 --wait 120 -v OnProd2.0 -c --definitionfile config/project-scratch-def.json`

### Expected result

It should create a new version.

### Actual result (failed intermittently)

Error
```ERROR running force:package:version:create:  Before you can use this duplicate rule, all associated matching rules must be active and have their fields mapped.```

### System Information

1. We run our CI-CD on GitHub actions
2. We are using `npm i sfdx-cli --global`

### Additional information

1. We have been facing this issue for the last three months (approx)
2. Business and Development team escalated this as we need to rerun the process (re-try), and it doesn't make any sense that it gets failed once and then next try, it successfully creates version 
3. Sometimes, we need to run it 3 or 4 times until it successfully create a version

**Comment by mshanemc** [comment]
packaging team doesn't monitor github
