### ISSUE TITLE
sfdx non:existing:command gives exit code 0 if run in scripts (no terminal / stdin attached)

### ISSUE THREAD

**Issue by busybox0** [forcedotcom/cli#1628]
### Summary

sfdx non:existing:command gives exit code 0 if run in scripts (no terminal / stdin attached)

### Steps To Reproduce **in Bash terminal**:

1.  `sfdx non:existing:command 0<&-`  The command `0<&-` tells to block input from stdin like it would work in CI/automations. Only put it to test interactively.
1.  `echo $? ` # gives 0 (zero).

### Steps To Reproduce **in cmd.exe**:

1.  `sfdx non:existing:command <nul`  The command `<nul` tells to block input from stdin like it would work in CI/automations. Only put it to test interactively.
1.  `echo  %errorlevel% ` # gives 0 (zero).

### Expected result

Exit code must be non-zero, as it's typo or missing plugin.

### Actual result

Exit code is 0.

### System Information

Reproduced in bash and cmd.exe

sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.158.1",
        "architecture": "wsl-x64",
        "nodeVersion": "node-v14.17.6",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.2 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.2 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 2.0.1 (core)",
                "salesforce-alm 54.6.2 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.158.1 (core)",
                "sfdx-git-delta 5.2.0 (5.2.0)",
                "sfpowerkit 4.2.9 (4.2.9)",
                "signups 1.2.0 (core)",
                "source 2.0.3 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Linux 5.4.72-microsoft-standard-WSL2"
}

**Comment by mshanemc** [comment]
you are correct.  There's an [open bug](https://github.com/oclif/plugin-not-found/issues/266) down in oclif (the cli framework we use) so I'm gonna close this one.
