### ISSUE TITLE
plugin install not working behind proxy and npm mirror

### ISSUE THREAD

**Issue by KevinGossentCap** [forcedotcom/cli#163]
Hi,
I've been struggling trying to install sfdx plugins behind a corporate proxy needing npm registry to be mirrored.
My npm parameters are set and I can install any package from registry.npm.org but when trying with "sfdx plugins:install" I only receive an "error 407".
How to fix that without asking the company to reduce the security settings ?
How to have the "sfdx plugins:install" to use the npm parameters for plugin install ?

**Comment by KevinGossentCap** [comment]
Just to complete tech info:
- Windows 10
- node 10.16.3
- sfdx-cli installed through npm

sfdx plugins --core
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.11.0 (core)
├─ force-language-services 46.15.0 (core)
└─ salesforce-alm 46.14.0 (core)

sfdx-cli 7.21.0 (core)

**Comment by tnoonan-salesforce** [comment]
Do you have the http_proxy and https_proxy set?

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_firewall.htm

**Comment by KevinGossentCap** [comment]
Hi, I have the environment variables set.
I tried setting them in NPM also.
It never works.
Again, with pure npm , package install work, it's only through "sfdx plugins:install" as if it's trying to force its own conf instead of relying on npm parameters to deal with it.

to explain the company constraints:
- no direct internet connexion
- internet connexion through a proxy
- npm, maven, etc. have to go through company mirrors instead of directly to internet repo
- access to mirrors have to go without proxy (use of the "no_proxy" parameter)

**Comment by baksale** [comment]
> Hi,
> I've been struggling trying to install sfdx plugins behind a corporate proxy needing npm registry to be mirrored.
> My npm parameters are set and I can install any package from registry.npm.org but when trying with "sfdx plugins:install" I only receive an "error 407".
> How to fix that without asking the company to reduce the security settings ?
> How to have the "sfdx plugins:install" to use the npm parameters for plugin install ?

Hi Kevin,
407 error means that you corporate proxy requires username and password to be passed to the proxy when trying to access a url from CLI. (search for NTLM proxy issue)

We had exactly same proxy issue.

You can address it via a proxy tool which will take you system credentials and pass it to the corporate proxy (similar to what other tools do, e.g. your browser on corporate machine)

This is the proxy tool we are using: https://github.com/genotrance/px
There is a README.md how to run it.

It will start a proxy (on localhost:3128 by default)

In your .npmrc file, please update proxy to http://localhost:3128.

You will also need to set your environment variables: HTTP_PROXY and HTTPS_PROXY to the http://localhost:3128 (most likely it will require log-off/log-on to take effect)

This approach resolved our issue with passing NTLM authorization information to corporate proxy.

This is not the sfdx-cli tool issue - it's just your corporate proxy configuration which requires username/pass to be passed.

**Comment by KevinGossentCap** [comment]
Hi @baksale 
I do understand the credential part because I already struggled on previous companies with them (and especially with NTLM proxy).
2 points here though
- first, I'm pretty sure it's not NTLM here
- second, if it was completely a credential issue, pur npm install wouldn't work...

Those points makes me continue to think it's a sfdx-cli issue.
I'd like to help dip it because if the sfdx-cli is supposed to do the same things as npm install with only additional step to link it correctly, then I shouldn't face the issue.

Maybe, if I'm explained the steps that the sfdx plugins:install do I can do them manually one by one through NPM or other means and drive the digging to find the steps that are failing and help it work globally and easier in the futur.

**Comment by baksale** [comment]
Completely agree with you - it would be much easier if it works out of the box.

It might be the case, node.js registry is white-listed on your corporate proxy, so it bypasses username/pass.

In our case it solved the issue - we couldn't wait for a proper fix since it blocked a lot of people.

Nevertheless, have you tried the suggested approach with additional local proxy in the chain?

**Comment by KevinGossentCap** [comment]
@baksale I will test it but I already see a problem with it => it will force proxy everything instead of doing the right thing only for what's needed, so other tools will not work anymore...

**Comment by KevinGossentCap** [comment]
@baksale also, the registry is mirrored internally to reduce internet usage and install time for same packages, that's what I'd like sfdx-cli to use exactly as npm if it's using the same procedure.

**Comment by KevinGossentCap** [comment]
for information and to help finding a solution that could use npm registry overriding, here is how I managed to overcome my problem without installing a proxy:
- npm i -g yarn (install yarn)
- npm config set registry (your registry mirror) -g
- yarn config set registry (your registry mirror) -g
- create a project folder to receive your plugin
- cd to the project folder
- yarn add [pluginName] (because it's the system yarn and not the sfdx yarn, it will use the global config values)
- sfdx plugins:link ./nodemodules/[pluginName]

Like that we end-up linking the plugin as if we were a developer of it, but at least it work behind a complexe proxy/mirroring corporate configuration and security

Hoping we'll have improvement to oclif/sfdx-cli to support npm&yarn proxy&mirror/registry settings in the futur

**Comment by KevinGossentCap** [comment]
@tnoonan-salesforce @ntotten Does my explanation help drill down the way the SFDX-CLI is doing and help find a way to make it standard without my workaround ?
I can definitely help testing things on the subject

**Comment by KevinGossentCap** [comment]
@tnoonan-salesforce @ntotten Just found an easier way to do the same (but still unable to install through the "sfdx plugins:install" command)

- npm i -g [plugin name]
- sfdx plugins:link [node path]/node_modules/[plugin name]
it helps to not install yarn when not needed.
But it still would be better if the plugins:install command inherited from OCLIF would use the global/normal npm registry url instead of forcing its own yarn forcing an internal registry url that can't be overridden.

**Comment by KevinGossentCap** [comment]
@tnoonan-salesforce @ntotten 
After a long time digging SFDX-CLI source code, I managed to find the undocumented env variable "SFDX_NPM_REGISTRY".
Setting this env var with my NPM mirror now it works !!! (slowly but works)
Maybe at least a documentation on it (or even on each env var usable) would help others

**Comment by amphro** [comment]
It's documented here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm
