### ISSUE TITLE
sfdx force:org:beta:create doesn't assign aliases

### ISSUE THREAD

**Issue by sanderott** [forcedotcom/cli#1630]
### Summary

`sfdx force:org:beta:create` does not properly assign the alias it is given via flag.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)
(Verified it was reproducible with dreamhouse)

1.  Run command `sfdx force:org:beta:create -t scratch -a dreamhouseScratchBetaTest -f config/project-scratch-def.json -v DEVHUB-ALIAS -d 1 --wait 60`
1.  After beta create command finishes, run `sfdx force:org:list`. The scratch org shows up without the defined alias.

### Expected result

Expected the scratch org to get assigned with the alias given, and being able to approach the scratch org using said alias in other sfdx commands.

### Actual result

The scratch org is created without alias. No alias shows up in `force:org:list`, and other commands (`force:org:open`, `force:org:delete`, etc.) do not respond to the alias either.
Scratch orgs made with the old `force:org:create` command with identical flags **do** get their alias assigned correctly.

### System Information

This error is being encountered both on local computer, as well as when running a build using CI tooling for a project.

- Which shell/terminal are you using?  (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
**Local computer:** bash & cmd
**CI builds:** TeamCity using Runner type: 'Command Line'

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- Paste the output here

**Local Computer:**
```
{
        "cliVersion": "sfdx-cli/7.159.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
                "alias 2.1.0 (core)",
                "apex 1.1.0 (core)",
                "auth 2.2.2 (core)",
                "community 2.0.0 (core)",
                "config 1.4.14 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.2 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 2.0.2 (core)",
                "salesforce-alm 54.6.2 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.159.0 (core)",
                "signups 1.2.0 (core)",
                "source 2.0.7 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19043"
}
```

**CI builds:**
```
{
	"cliVersion": "sfdx-cli/7.159.0",
	"architecture": "linux-x64",
	"nodeVersion": "node-v16.15.1",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
		"alias 2.1.0 (core)",
		"apex 1.1.0 (core)",
		"auth 2.2.2 (core)",
		"community 2.0.0 (core)",
		"config 1.4.14 (core)",
		"custom-metadata 2.0.0 (core)",
		"data 2.0.4 (core)",
		"generator 2.0.2 (core)",
		"info 2.0.1 (core)",
		"limits 2.0.1 (core)",
		"org 2.0.2 (core)",
		"salesforce-alm 54.6.2 (core)",
		"schema 2.1.1 (core)",
		"sfdx-cli 7.159.0 (core)",
		"signups 1.2.0 (core)",
		"source 2.0.7 (core)",
		"telemetry 2.0.0 (core)",
		"templates 55.0.0 (core)",
		"trust 2.0.1 (core)",
		"user 2.1.0 (core)"
	],
	"osVersion": "Linux 5.4.0-110-generic"
}
```

### Additional information

- Am encountering this error both on local computer, as well as when running builds using CI tooling for a project.

Screenshot of created scratch org lacking an alias:
![sfdxbetacreateissue](https://user-images.githubusercontent.com/11257110/179224399-8f39be96-5ed2-4558-83c2-529b05875ffe.png)

**Comment by mshanemc** [comment]
yep, we just fixed this yesterday (thanks for the report, though!).  You can try/confirm by running

`sfdx plugin:install org` 

and then `sfdx plugins:uninstall org` to get back to your normal CLI setup.

**Comment by sanderott** [comment]
Can confirm setting aliases works with the newer org plugin, thank you!
