### ISSUE TITLE
Component conversion failed: Callback called multiple times

### ISSUE THREAD

**Issue by jtodorovicJDE** [forcedotcom/cli#1631]
### Summary

When I want to deploy code from VS code, most often I am getting this error 'Component conversion failed: Callback called multiple times'. Especially when it comes to deploying the static resource files. No one in the team has this issue, while we are all working on the same code and having the same extensions. The issue is solved only when VS code is restored, but then the issue appears all over again when I try to deploy some files.

### Steps To Reproduce:

1. Right-click on a file/folder you want to deploy
1. Select SFDX: Deploy This Source To Org

### Expected result

Expected is to have the files successfully deployed

### Actual result

Code is not deployed to the org, and after that, nothing can be deployed, unless VS code is restarted.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
 **I am using cmd.exe**

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- Paste the output here
![image](https://user-images.githubusercontent.com/106378718/179241811-01ae9738-a633-4976-9078-5879fccfa8e0.png)

### Additional information
This is the output. There is nothing more about it.
![image](https://user-images.githubusercontent.com/106378718/179240185-004e636d-11b6-4414-a682-94e1e461e577.png)

**Comment by mshanemc** [comment]
VSCode extensions is a different team/github https://github.com/forcedotcom/salesforcedx-vscode/issues and you may find information there (pinned issues, similar open issues) to help.

Is there a way to reproduce this with just the CLI (not using vscode)?
