### ISSUE TITLE
force:package:version:list shows No for IsOrgDependent when the package is Org Dependent

### ISSUE THREAD

**Issue by MarcDBehr** [forcedotcom/cli#1632]
### Summary

When running the command `sfdx force:package:version:list --json -p packageID` for an org dependent package, it is showing `"IsOrgDependent": "No"` despite the package being org dependent. This can be verified by running the command `sfdx force:package:list --json`, which shows `"IsOrgDependent": "Yes"` for the same package.

### Steps To Reproduce:

1. Create an org dependent package
2. Create a package version of that package
3. Run the sfdx force:package:list --json command to see that the version is marked as IsOrgDependent = Yes
4. Run the sfdx force:package:version:list --json command to see that the version is marked as IsOrgDependent = No

### Expected result

The results should match

### Actual result

The results don't match

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.) bash

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- Paste the output here

$ sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.157.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.13.2",
        "pluginVersions": [
                "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.3",
                "@oclif/plugin-autocomplete 1.3.0",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/lwc-dev-server 2.11.0",
                "@salesforce/sfdx-diff 0.0.6",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.0 (core)",
                "bbdoc 4.0.5",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.6.1 (core)",
                "schema 2.1.1 (core)",
                "sfdmu 4.14.5",
                "sfdx-cli 7.157.0 (core)",
                "sfdx-flowdoc-plugin 0.5.1",
                "sfdx-waw-plugin 1.5.0",
                "sfpowerkit 4.2.8",
                "shane-sfdx-plugins 4.43.0",
                "├─ @mshanemc/sfdx-sosl 1.1.0",
                "└─ @mshanemc/plugin-streaming 1.1.7",
                "signups 1.2.0 (core)",
                "source 2.0.3 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Darwin 21.5.0"
}

### Additional information

sfdx force:package:list --json 
{
    "Id": "0Ho5G000000ABCDEFG",
    "SubscriberPackageId": "0335G000000XXXXXXX",
    "Name": "xx_sales",
    "Description": "xx Sales Application",
    "NamespacePrefix": null,
    "ContainerOptions": "Unlocked",
    "ConvertedFromPackageId": null,
    "Alias": "xx_sales",
    "IsOrgDependent": "Yes",
    "PackageErrorUsername": "xx@xxx.com",
    "CreatedBy": "005f4000000nxxxxxx"
  }

Same package:

sfdx force:package:version:list -p 0Ho5G000000ABCDEFG --json | jq '.result | last'
{
  "Package2Id": "0Ho5G000000ABCDEFG",
  "Branch": null,
  "Tag": null,
  "MajorVersion": 1,
  "MinorVersion": 5,
  "PatchVersion": 0,
  "BuildNumber": 1,
  "Id": "05i5G000000xxxxQAA",
  "SubscriberPackageVersionId": "04t5G00000xxxxxQAQ",
  "Name": "ver 1.5",
  "NamespacePrefix": null,
  "Package2Name": "xx_sales",
  "Description": null,
  "Version": "1.5.0.1",
  "IsPasswordProtected": false,
  "IsReleased": true,
  "CreatedDate": "2022-07-08 05:29",
  "LastModifiedDate": "2022-07-11 08:35",
  "InstallUrl": "https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G00000xxxxxQAQ",
  "CodeCoverage": "",
  "ValidationSkipped": false,
  "AncestorId": "N/A",
  "AncestorVersion": "N/A",
  "Alias": "xx_sales@1.5.0-1",
  "IsOrgDependent": "No",
  "ReleaseVersion": "",
  "BuildDurationInSeconds": "",
  "HasMetadataRemoved": "N/A",
  "CreatedBy": "005f4000000xxxxAAC"
}

_Feel free to attach a screenshot_.

**Comment by RodEsp** [comment]
@WillieRuemmele can this be closed now?

**Comment by cristiand391** [comment]
Hey @MarcDBehr, sorry for the late reply.

This was fixed in the current packaging beta commands, see this for more info: https://github.com/forcedotcom/cli/issues/1721

You can test these beta commands by updating to the latest stable sfdx release, please let us know if it works for you. Thanks!

**Comment by MarcDBehr** [comment]
Thanks @cristiand391 - it does appear that the beta version of the command is returning the correct data now.
