### ISSUE TITLE
requesting version list results in error

### ISSUE THREAD

**Issue by ranizi** [forcedotcom/cli#1634]
### Summary

try to retrieve a version list of a package

### Steps To Reproduce:

1.  sfdx force:package1:version:list

### Expected result

list of version of managed package on the default org

### Actual result
ERROR running force:package1:version:list:  Cannot read properties of undefined (reading 'force')

### System Information

- Which shell/terminal are you using? cmd.exe
{
        "cliVersion": "sfdx-cli/7.159.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
                "alias 2.1.0 (core)",
                "apex 1.1.0 (core)",
                "auth 2.2.2 (core)",
                "community 2.0.0 (core)",
                "config 1.4.14 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.2 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 2.0.2 (core)",
                "salesforce-alm 54.6.2 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.159.0 (core)",
                "signups 1.2.0 (core)",
                "source 2.0.7 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.22000"
}

**Comment by sfrycertinia** [comment]
I'm seeing this on any command but I get the following.

(node:20521) TypeError Plugin: sfdx-cli: Cannot read properties of undefined (reading 'prototype')
module: @oclif/config@1.18.3
task: runHook prerun
plugin: sfdx-cli
root: /home/developer/.npm-global/lib/node_modules/sfdx-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)


Info


{
        "cliVersion": "sfdx-cli/7.136.2",
        "architecture": "linux-x64",
        "nodeVersion": "node-v16.15.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.8.0 (core)",
                "auth 1.8.1 (core)",
                "config 1.3.15 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.1 (core)",
                "salesforce-alm 53.7.6 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.136.2 (core)",
                "source 1.8.9 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Linux 5.10.104-linuxkit"
}

**Comment by ranizi** [comment]
Still happening

**Comment by cristiand391** [comment]
Hey all 👋🏼 , sorry for the late reply.

Can someone try the beta commands and see if they work ok? These will promoted in the next few days, see: https://github.com/forcedotcom/cli/issues/1721

**Comment by WillieRuemmele** [comment]
Hey @ranizi - I'm closing this for now assuming it's fixed in the latest CLI versions. If not, ping me
