### ISSUE TITLE
Running sfdx commands now leads to an error being output to stderr.

### ISSUE THREAD

**Issue by sfrycertinia** [forcedotcom/cli#1635]
### Summary

Running sfdx commands now leads to an error being output to stderr.

### Steps To Reproduce:

1.  sfdx force:org:list

### Expected result

Formatted list of my orgs.

### Actual result

```bash
(node:22747) TypeError Plugin: sfdx-cli: Cannot read properties of undefined (reading 'prototype')
module: @oclif/config@1.18.3
task: runHook prerun
plugin: sfdx-cli
root: /home/developer/.npm-global/lib/node_modules/sfdx-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
```
Followed by the nicely formatted list of orgs.

### System Information

{
        "cliVersion": "sfdx-cli/7.136.2",
        "architecture": "linux-x64",
        "nodeVersion": "node-v16.15.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.8.0 (core)",
                "auth 1.8.1 (core)",
                "config 1.3.15 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.1 (core)",
                "salesforce-alm 53.7.6 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.136.2 (core)",
                "source 1.8.9 (core)",
                "telemetry 1.4.0 (core)",
                "templates 53.3.0 (core)",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Linux 5.10.104-linuxkit"
}

**Comment by mshanemc** [comment]
v7.136 is over 5 months ago.  Since then, we've migrated to a new major version of `oclif` (where that error seems to be coming from).

Is this reproducible in a current CLI versions? see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm

**Comment by wkloster** [comment]
C:\>sfdx --version
(node:5912) TypeError Plugin: sfdx-cli: Cannot read properties of undefined (reading 'prototype')
module: @oclif/config@1.18.3
task: runHook init
plugin: sfdx-cli
root: C:\Program Files\sfdx\client
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
sfdx-cli/7.159.0 win32-x64 node-v16.15.1

**Comment by McFlyssss** [comment]
We are facing the same issue in our CI/CD env. This started Aug the 11th for us. Could anyone figure out what is causing the error?

**Comment by McFlyssss** [comment]
It seems that after updating to the latest version the issue got fixed

**Comment by sfrycertinia** [comment]
Seems like it is OK again now. I guess other changes to dependencies have fixed.

**Comment by iowillhoit** [comment]
Morning all, thanks for following up. I am going to close this issue since it appears to be resolved. Feel free to reopen it if you are still seeing issues. Thanks!

**Comment by dvdjg** [comment]
It is failing again with:

sfdx-cli/7.174.0 win32-x64 node-v16.17.1

**Comment by WillieRuemmele** [comment]
hey @dvdjg what's the output of `sfdx doctor`? or `sfdx version --verbose`?
