### ISSUE TITLE
force:source:push Error on deleting Reports / Dashboards and Containing Folders

### ISSUE THREAD

**Issue by jamesmelville** [forcedotcom/cli#164]
### Summary

SFDX appears unable to handle deletion of reports and dashboards & containing folders

### Steps To Reproduce:

1.  Include a folder containing a dashboard in your repository
1.  Include a folder containing a report in your repository
1.  Deploy / retrieve this so source and scratch org are synced
1.  Delete the dashboard and the dashboard folder locally
1.  Delete the report and the report folder locally
1. force:source:push

### Expected result

Deletion of reports, dashboards and folders succeeds, continue working

### Actual result

Error message:
```
PROJECT PATH  ERROR
───────── ──────────────────────────────────────
N/A           Before deleting this folder, you need to delete these dashboards from the folder and the Recycle Bin.: My Dashboard
N/A           Before deleting this folder, you need to delete these reports from the folder and the Recycle Bin.: My Report
ERROR running force:source:push:  Push failed.
````

### Additional information

Workaround, manually delete in scratch org, empty reports and dashboards from recycle bin and force push. Appears reports and dashboards need purging on delete.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.22.0-de5c6ecff8 win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.12.1 (core)
├─ force-language-services 46.16.0 (core)
└─ salesforce-alm 46.15.0 (core)

sfdx-cli 7.22.0 (core)

**OS and version**:
Microsoft Windows [Version 10.0.18362.295]

**Comment by clairebianchi** [comment]
@jamesmelville This is a bug for the Reports and Dashboards team, we have made them aware. For the current way to deleate please see https://releasenotes.docs.salesforce.com/en-us/summer18/release-notes/rn_rd_folders_organize.htm
