### ISSUE TITLE
sfdx force:org:list does not return active orgs

### ISSUE THREAD

**Issue by james-hafer** [forcedotcom/cli#1641]
### Summary

When running sfdx force:org:list, sfdx force:org:list --all, sfdx force:org:list --verbose --json no active orgs are returned. I am still able to open the latest org but cannot open any other orgs if I do not know the username.

### Steps To Reproduce:

Run sfdx force:org:list

### Expected result

I have three active scratch orgs that should be displayed. If I switch to a previous version I am able to get the active orgs:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/70535908/180868054-c894f7a9-2e06-4168-9457-e7941c5d1be3.png">

### Actual result

No active scratch orgs found. Specify --all to see all scratch orgs:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/70535908/180867178-32ff3e95-d6e1-4d25-a840-1d0fff8de0b6.png">

### System Information

{
        "cliVersion": "sfdx-cli/7.160.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v14.17.0",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
                "alias 2.1.0 (core)",
                "apex 1.1.0 (core)",
                "auth 2.2.2 (core)",
                "community 2.0.0 (core)",
                "config 1.4.14 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.2 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 2.0.3 (core)",
                "salesforce-alm 54.6.2 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.160.0 (core)",
                "signups 1.2.0 (core)",
                "source 2.0.7 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Darwin 21.1.0"
}

**Comment by mshanemc** [comment]
whoa!

1. Does the devhub that they're related to still show up in your `org:list` results with a good `Connected` status?
2. if you open up one of the auth files for an org you're missing like `cat ~/.sfdx/test-fcous0ktagnx@example.com.json` what do you see?  The tokens are encrypted, but feel free to omit them if you like.

you should see 
```json
{
  "instanceUrl": "https://ability-nosoftware-3674-dev-ed.my.salesforce.com",
  "orgId": "00D63000000fzG8EAI",
  "loginUrl": "https://CS43.salesforce.com",
  "clientId": "PlatformCLI",
  "isDevHub": false,
  "devHubUsername": "etc",
  "created": "1657219262000",
  "expirationDate": "2022-08-06",
  "createdOrgInstance": "CS43",
  "snapshot": null,
  "instanceApiVersion": "55.0",
  "instanceApiVersionLastRetrieved": "7/25/2022, 1:48:08 PM",
  "name": "portfolio-tracker",
  "instanceName": "CS43",
  "namespacePrefix": null,
  "isSandbox": false,
  "isScratch": true,
  "trailExpirationDate": "2022-08-07T18:41:27.000+0000",
  "tracksSource": true
}%                
```

**Comment by james-hafer** [comment]
1. Yes and it does still have a good `Connected` status
2.  {
  "instanceUrl": "https://page-data-8336-dev-ed.my.salesforce.com",
  "orgId": "00D1h000000OEIWEA4",
  "loginUrl": "https://CS79.salesforce.com",
  "clientId": "PlatformCLI",
  "isDevHub": false,
  "devHubUsername": "etc",
  "created": "1658776487000",
  "expirationDate": "2022-08-08",
  "createdOrgInstance": "CS79",
  "instanceApiVersion": "55.0",
  "instanceApiVersionLastRetrieved": "7/26/2022, 3:50:36 PM",
  "name": "Squivr Development",
  "instanceName": "CS79",
  "namespacePrefix": "squivr",
  "isSandbox": false,
  "isScratch": true,
  "trailExpirationDate": "2022-08-09T19:15:03.000+0000",
  "tracksSource": true,
}%

**Comment by jstvz** [comment]
I also hit this issue. Steps to reproduce against dreamhouse-lwc ([gist](https://gist.github.com/jstvz/19ced1cb1dd2d0784b6bde471749957d)):

1. `sfdx force:org:create`  
2. `sfdx force:user:password:generate` 
3. `sfdx force:user:create`

**Comment by peternhale** [comment]
@jstvz thanks for your repo. I have been able to reproduce the issue. @james-hafer can you confirm that the orgs not appearing in the list also have additional users created for them?

**Comment by james-hafer** [comment]
@peternhale Yes, the orgs have additional users created for them.

**Comment by peternhale** [comment]
Thanks @james-hafer. I have identified the issue and a fix will be made soon.

**Comment by peternhale** [comment]
fix in version 7.162.0 of sfdx-cli

**Comment by vernemi2** [comment]
Can confirm it's working as expected when updated the cli to 7.162.0. Thanks a lot for a quick turnaround!

**Comment by MikhailShumenko** [comment]
@peternhale This issue is still present in "sfdx-cli/7.188.1 darwin-x64 node-v18.13.0" for Mac OS Monterey 12.6
