### ISSUE TITLE
sfdx force:org:create command fails

### ISSUE THREAD

**Issue by pranitjain1** [forcedotcom/cli#1644]
### Summary

sfdx force:org:create command fails to create Scratch org.

### Steps To Reproduce:

**Repository to reproduce:** [salesforce/salesforcedx:latest-full](https://hub.docker.com/layers/salesforcedx/salesforce/salesforcedx/latest-full/images/sha256-3e4239035d305d241d287fb092b458b5bf6456ccf2bd08c71f1a9ee8d312e5aa?context=explore)

1.  We are using salesforce/salesforcedx:latest-full in our CI/CD pipelines
2. In our pipeline we authenticate DevHub
3. Create Scratch Org

### Expected result

Scratch org gets created and we display scratch org info

### Actual result
Scratch org is not getting created and sfdx force:org:display -u (alias) command is failing to display info
<img width="796" alt="Screen Shot 2022-07-27 at 13 08 27" src="https://user-images.githubusercontent.com/110100414/181232868-28134f4a-95d0-45e3-b9ad-56c8f332d632.png">

**Comment by mshanemc** [comment]
when you open an issue, please provide something we can reproduce using sfdx commands and the indicated output from `sfdx version --verbose`.

Right now, I see some script or wrapper that's probably wrapping sfdx commands, which we have no way of verifying its correctness.

Is something wrong with your script? Your config?  Your CI environment?

**Comment by pranitjain1** [comment]
Hi Shane - As we are using docker I could find version in our pipelines. I found this on the docker SALESFORCE_CLI_VERSION=7.160.0. Below is what I have it in my mac.
CLI Version : 
        sfdx-cli/7.160.0

 Architecture: 
        darwin-x64

 Node Version : 
        node-v16.16.0

 Plugin Version: 
        @oclif/plugin-autocomplete 0.3.0 (core)
        @oclif/plugin-commands 1.3.0 (core)
        @oclif/plugin-help 3.3.1 (core)
        @oclif/plugin-not-found 1.2.6 (core)
        @oclif/plugin-plugins 1.10.11 (core)
        @oclif/plugin-update 1.5.0 (core)
        @oclif/plugin-warn-if-update-available 1.7.3 (core)
        @oclif/plugin-which 1.0.4 (core)
        @salesforce/sfdx-plugin-lwc-test 1.0.0 (core)
        alias 2.1.0 (core)
        apex 1.1.0 (core)
        auth 2.2.2 (core)
        community 2.0.0 (core)
        config 1.4.14 (core)
        custom-metadata 2.0.0 (core)
        data 2.0.4 (core)
        generator 2.0.2 (core)
        info 2.0.1 (core)
        limits 2.0.1 (core)
        org 2.0.3 (core)
        salesforce-alm 54.6.2 (core)
        schema 2.1.1 (core)
        sfdx-cli 7.160.0 (core)
        signups 1.2.0 (core)
        source 2.0.7 (core)
        telemetry 2.0.0 (core)
        templates 55.0.0 (core)
        trust 2.0.1 (core)
        user 2.1.0 (core)

 OS and Version: 
        Darwin 21.5.0

Scripts that we have are working since long and they haven't been changed. They last worked today at 11CET and started failing after that.

**Comment by mshanemc** [comment]
Can you produce the error without your scripts, using just CLI commands?

**Comment by pranitjain1** [comment]
With just CLI it works in my local VS Code.

**Comment by pranitjain1** [comment]
[DebugLog.txt](https://github.com/forcedotcom/cli/files/9199788/DebugLog.txt)
Also attaching logs from Pipelines if it helps.
