### ISSUE TITLE
ERROR running force:source:pull:  Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by shubhammittal2048** [forcedotcom/cli#1647]
I am facing this issue in vs code while trying to run the command- `sfdx force:source:pull -f` 
I tried to downgrade and upgrade the SFDX version for the workaround. 
Can you please help?
![image](https://user-images.githubusercontent.com/110152823/181433051-550905fc-cd28-4e79-91b0-05a931f13188.png)

**Comment by gitmevg** [comment]
Facing similar issue. Can someone please help. Followed all fixes from below article but still an issue:

https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000A8MIGSA3

**Comment by peternhale** [comment]
@shubhammittal2048 can you provide us with the details as presented in the issues template please; key are results of `sfdx version --verbose` and reproduction steps along with a reference source repository that we can use with the reproduction.

I would also ask that you run the failing command again with `--json` flag and provide that output as well.

**Comment by Tom331** [comment]
I'm also receiving this issue when running `sfdx force:source:tracking:reset`

**Comment by shubhammittal2048** [comment]
@peternhale 

> @shubhammittal2048 can you provide us with the details as presented in the issues template please; key are results of `sfdx version --verbose` and reproduction steps along with a reference source repository that we can use with the reproduction.
> 
> I would also ask that you run the failing command again with `--json` flag and provide that output as well.


Hello @peternhale,
As you have suggested running the command 'sfdx version --verbose'- I am sharing the output for the same.
<img width="576" alt="abc1" src="https://user-images.githubusercontent.com/110152823/182293179-1bc36519-cc8e-4afe-809c-0383d537fecd.png">
![abc2](https://user-images.githubusercontent.com/110152823/182293207-56efac5f-ba24-4077-bab3-a5ecbc0261b7.JPG)

And for the command 'sfdx force:source:pull -f --json'- I am sharing the output.
![image](https://user-images.githubusercontent.com/110152823/182294454-34b9ec72-60b8-494d-bd07-cbfd1a5a5d80.png)

**Comment by peternhale** [comment]
@shubhammittal2048 thank you

**Comment by patlafreniere** [comment]
I get the same error when running:
> sfdx force:source:tracking:reset
ERROR running force:source:tracking:reset:  Cannot read properties of null (reading 'split')

Version info:
> sfdx version --verbose
 CLI Version:
        sfdx-cli/7.165.0

 Architecture:
        win32-x64

 Node Version:
        node-v16.17.0

 Plugin Version:
        @oclif/plugin-autocomplete 1.3.0 (core)
        @oclif/plugin-commands 2.2.0 (core)
        @oclif/plugin-help 5.1.12 (core)
        @oclif/plugin-not-found 2.3.1 (core)
        @oclif/plugin-plugins 2.1.0 (core)
        @oclif/plugin-update 3.0.0 (core)
        @oclif/plugin-version 1.1.2 (core)
        @oclif/plugin-warn-if-update-available 2.0.4 (core)
        @oclif/plugin-which 2.1.0 (core)
        alias 2.1.0 (core)
        apex 1.2.0 (core)
        auth 2.2.3 (core)
        community 2.0.0 (core)
        config 1.4.17 (core)
        custom-metadata 2.0.0 (core)
        data 2.1.2 (core)
        generator 2.0.2 (core)
        info 2.0.1 (core)
        limits 2.0.1 (core)
        org 2.2.0 (core)
        schema 2.1.1 (core)
        signups 1.2.0 (core)
        source 2.0.12 (core)
        telemetry 2.0.0 (core)
        templates 55.1.0 (core)
        trust 2.0.3 (core)
        user 2.1.0 (core)
        @salesforce/sfdx-plugin-lwc-test 1.0.0 (core)
        salesforce-alm 54.8.1 (core)

 OS and Version:
        Windows_NT 10.0.19044

 Shell:
        C:\Program Files\Git\usr\bin\bash.exe

 Root Path:
        C:\Users\xxxxxxx\AppData\Local\sfdx\client\7.165.0-65b4bb0

**Comment by PseudoDarwinist** [comment]
Is there any workaround for this? Still receiving this error.
