### ISSUE TITLE
force:source:push Error on deleting Reports

### ISSUE THREAD

**Issue by jamesmelville** [forcedotcom/cli#165]
### Summary

SFDX appears unable to handle deletion of reports from Windows client

### Steps To Reproduce:

1.  Include a folder containing a report in your repository
1.  Deploy / retrieve this so source and scratch org are synced
1.  Delete the report locally
1.  force:source:push

### Expected result

Report deleted from scratch org.

### Actual result

```
ERROR running force:source:push: 
SourceMember WHERE MemberName IN ('ReportFolder\MyReport'
                                 ^
ERROR at Row:1:Column:85
Invalid string literal 'ReportFolder\MyReport'. Illegal character sequence '\E' in string literal.
```

### Additional information

Issue doesn't seem reproducible on mac, so I suspect it could be to do with `\` character in path, although same issue is not seen for dashboard deletion from windows.

Workaround: manually delete entries from sourcePathInfos.json, and manually delete from org, pull & push.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.22.0-de5c6ecff8 win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.12.1 (core)
├─ force-language-services 46.16.0 (core)
└─ salesforce-alm 46.15.0 (core)

sfdx-cli 7.22.0 (core)

**OS and version**:
Microsoft Windows [Version 10.0.18362.295]

**Comment by clairebianchi** [comment]
@jamesmelville this is a bug with the reports and dashboards team that we have made them aware of. For now please see this document for information on how to delete: https://releasenotes.docs.salesforce.com/en-us/summer18/release-notes/rn_rd_folders_organize.htm

**Comment by JodieM** [comment]
@clairebianchi is this actually the same as #221?

**Comment by JodieM** [comment]
I deleted a report from the org, deleted it from the recycle bin, did a force:source:pull and it does not change the source. So I have to delete it from the source locally, and then issue 221 occurs.
