### ISSUE TITLE
Using sfdx via ssh : User interaction is not allowed.

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/cli#1651]
### Summary

sfdx commands requiring org authentication fail inside ssh session to mac os x 

### Steps To Reproduce:

1.  ssh to any mac osx box with properly installed sfdx
1.  `sfdx force:limits:api:display`

### Expected result

 ```Name                                        Remaining Max       
 ─────────────────────────────────────────── ───────── ───────── 
 AnalyticsExternalDataSizeMB                 40960     40960     
 BOZosCalloutHourlyLimit                     20000     20000     
 ConcurrentAsyncGetReportInstances           200       200   
...
```

### Actual result

```
Droz2:~ tgagne$ sfdx force:limits:api:display
ERROR running force:limits:api:display:  Command failed with response:
 - security: SecKeychainItemCreateFromContent (<default>): User interaction is not allowed.
 

Try this: 
Determine why this command failed to set an encryption key for user tgagne: [/usr/bin/security add-generic-password -a local -s sfdx -w 65ce733588ac5c581d5a10cc2cb083be].
```

### System Information

Droz2:~ tgagne$ uname -a 
Darwin Droz2.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
Droz2:~ tgagne$ sfdx version
sfdx-cli/7.154.0 darwin-x64 node-v18.7.0
Droz2:~ tgagne$ sfdx version --verbose --json
{
	"cliVersion": "sfdx-cli/7.154.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v18.7.0",
	"pluginVersions": [
		"@copado/copado-cli 1.1.14",
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
		"alias 2.0.1 (core)",
		"apex 0.13.0 (core)",
		"auth 2.0.3 (core)",
		"community 2.0.0 (core)",
		"config 1.4.11 (core)",
		"custom-metadata 1.1.0 (core)",
		"data 2.0.2 (core)",
		"generator 2.0.1 (core)",
		"info 2.0.1 (core)",
		"limits 2.0.1 (core)",
		"org 1.13.2 (core)",
		"salesforce-alm 54.4.0 (core)",
		"schema 2.1.1 (core)",
		"sfdx-cli 7.154.0 (core)",
		"signups 1.1.2 (core)",
		"source 1.10.2 (core)",
		"telemetry 2.0.0 (core)",
		"templates 54.8.0 (core)",
		"trust 2.0.1 (core)",
		"user 2.0.2 (core)",
		"vlocityestools 0.22.12"
	],
	"osVersion": "Darwin 21.5.0"
}

### Additional information

Obviously, the other `force` commands work fine when executed inside a terminal thru the gui -- the error only occurs when I ssh to another mac.

Also, the same error happens when I `ssh username@localhost`

**Comment by peternhale** [comment]
@tggagne The error you are seeing is caused by the inability of the target Mac to open a dialog asking the user to enter the keychain password for the login-db keychain.

A bit of research on the error led me to an option (which I personally do not recommend) that allows one to unlock the login-db keychain. This would need to be done on the target machine prior to running the sfdx command.

See Max OSx command `security unlock-keychain` for more information.
