### ISSUE TITLE
Not able import json tree export

### ISSUE THREAD

**Issue by Salesforce-JK** [forcedotcom/cli#1653]
### Summary

I am not able import json tree export, I tried export of real data, example (https://github.com/trailheadapps/easy-spaces-lwc/blob/develop/data/Leads.json) and our old json we are sure were able to import

### Steps To Reproduce:

sfdx force:data:tree:export -u production --query "SELECT FIELDS(ALL) FROM Lead LIMIT 1"  
Wrote 1 records to Lead.json

sfdx force:data:tree:import -p Lead.json -u stage 

ERROR running force:data:tree:import:  Validation errors:
#/type: must be array

### Actual result

import is failing with validation error

ERROR running force:data:tree:import:  Validation errors:
#/type: must be array

### System Information

sfdx version --verbose --json
{
	"cliVersion": "sfdx-cli/7.161.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.16.0",
	"pluginVersions": [
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
		"alias 2.1.0 (core)",
		"apex 1.1.0 (core)",
		"auth 2.2.3 (core)",
		"community 2.0.0 (core)",
		"config 1.4.14 (core)",
		"custom-metadata 2.0.0 (core)",
		"data 2.0.4 (core)",
		"generator 2.0.2 (core)",
		"info 2.0.1 (core)",
		"limits 2.0.1 (core)",
		"org 2.0.5 (core)",
		"salesforce-alm 54.6.3 (core)",
		"schema 2.1.1 (core)",
		"sfdx-cli 7.161.0 (core)",
		"signups 1.2.0 (core)",
		"source 2.0.9 (core)",
		"telemetry 2.0.0 (core)",
		"templates 55.0.0 (core)",
		"trust 2.0.1 (core)",
		"user 2.1.0 (core)"
	],
	"osVersion": "Darwin 21.6.0"

**Comment by peternhale** [comment]
@Salesforce-JK the form of the command you are using is not correct. The `-p` flag references a `Plan`, which has a different schema than the actual records you want to import. Please us `-f` when you want to import a set of records for a given type.

Another thing to note is only fields that can created can be contained in the data to import, so using a query of `select fields(all) from Lead...` will result in a JSON file that contains read-only fields, such as latest modified date, etc.

**Comment by peternhale** [comment]
I am going to close this issue as resolved. If you need further assistance with this issue, feel free to reopen.

**Comment by Salesforce-JK** [comment]
I am sorry, you are right. I am sorry for bothering
