### ISSUE TITLE
Please add a  -f flag to the force:data:soql:query command.

### ISSUE THREAD

**Issue by docbill** [forcedotcom/cli#1654]
The general problem is currently queries are only passed through the command line.

At first this does not seem to be problematic because one can use a commandline like:

```
sfdx force:data:soql:query -r human -q "$(cat scripts/soql/Accounts.soql)"
```

However, for the same reason the other data commands need a -f flag, so does a query.  

The biggest issue is the passing in the query as a command line option makes long queries impossible under windows.
The longest command line supported under MINGW is 8192 characters.  The longest command line support under cmd.exe is 8192 characters, ...   But salesforce supports queries with as many as 100000 characters.

Even when one is within the commandline limits, it makes directions unnecessarily complicated.  As one has to tell a cmd.exe user how to occomplish the equivalent of a cat command under windows.

**What are you trying to do**
Run queries without resorting to workbench.  For example I wrote a script that uses a dynamically generated query that is 9826 characters long.  I tried every trick in the book but I could not find a way our Windows users could run the script, even though it worked perfectly for me under Fedora.   I finally ended resorting to making the script just output the query, and telling the user they had to run the query in workbench.

**Describe the solution you'd like**
I would like a solution that allows almost unlimited length queries, regardless of platform, from commandline scripts.

**Describe alternatives you've considered**
I did try an anonymous apex script that uploads the query into salesforce using callbacks and runs it as a batch query.   That solution works.  However, we do not allow developers Anonymous Apex access in production.   So I then had to modify the script to run on one sandbox to do the callbacks into production.   That worked for the large static query.  But for the dynamically generated query I needed to query production and generate another query to send to production.  That is extremely messy and low level to do through callbacks.

**Comment by peternhale** [comment]
Hi @docbill, thank you for the feature request. The ability to specify a file for the soql query text will be available in this week's latest-rc build of sfdx-cli. If you want to try it now run `sfdx plugins:install data`.

**Comment by docbill** [comment]
Thanks.  I'm not sure if I am testing this right.  But if I am, it doesn't seem to work:
```
[briemers@briemers tech-debt]$ sfdx plugins:install data
Polling for new version(s) to become available on npm... done
Successfully validated digital signature for @salesforce/plugin-data.
Finished digital signature check.
warning "sfpowerkit > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
Installing plugin data... installed v2.1.1
[briemers@briemers tech-debt]$ sfdx force:data:soql:query -r human -f scripts/DataMigration/Contacts/01contact-Sales01.soql
    TypeError: Cannot read properties of undefined (reading 'prototype')
```

**Comment by docbill** [comment]
Looks like there are problems even when not using the -f flag:
```
[briemers@briemers tech-debt]$ sfdx force:data:soql:query -r human -q "select Id from Contact limit 1"
    TypeError: Cannot read properties of undefined (reading 'prototype')
```

**Comment by peternhale** [comment]
@docbill what are the results of `sfdx version --verbose`

**Comment by peternhale** [comment]
@docbill I was mistaken about when the new flag will appear in sfdx-cli. It is available in the current sfdx-cli@latest-rc and will be promoted to latest Thursday.

**Comment by docbill** [comment]
It is working as expected when using sfdx-cli@latest-rc.

```
$ sudo npm install --force --global sfdx-cli@latest-rc
...
$ sfdx force:data:soql:query -r human -f scripts/DataMigration/Contacts/01contact-Sales01.soql
Querying Data... ⢿
...
```
