### ISSUE TITLE
force:org:create and force:org:beta:create commands error

### ISSUE THREAD

**Issue by ferhatco** [forcedotcom/cli#1659]
### Summary

When I run the force:org:create and force:org:beta:create I always get the following error even if I authenticate the devhub org:
"error authenticating with auth code due to: client identifier invalid"

<img width="714" alt="Screenshot 2022-08-08 at 17 30 04" src="https://user-images.githubusercontent.com/35259846/183455388-a8e02bf9-c1fb-4b27-b29e-a98e72e4f1ca.png">

The other issue is that even if the code fails, it creates the scratch org in my dev hub org. How it is possible? 

### Expected result

Scratch org created and authenticated the dev hub correctly.

### Actual result

It authenticates to dev hub but can not execute the scratch org commands after authentication.

### System Information

I am executing the following code in bash script. 

`#!/bin/bash
set -euo pipefail # set up error handling: fail on any command with exit code !=0 , fail with undefined variables.

export instanceUrl="https://$(echo "$ENDPOINT" | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')"
seturl=$(sfdx force:config:set instanceUrl="$instanceUrl" --global --json)    
echo $seturl

export SFDX_ACCESS_TOKEN="$SESSION"
authenticate=$(sfdx auth:accesstoken:store -p -s -a myhub --instanceurl "$instanceUrl" --json)
echo $authenticate

sname="Scratch$(echo "$packageName")"
sfdx force:org:beta:create -d 30 -f "temp/config/project-scratch-def.json" -a "$sname" -v myhub 

sfdx force:user:password:generate -u "$sname" -v myhub

scratchorg==$(sfdx force:org:display -u "$sname" --json)
echo $scratchorg

**Comment by peternhale** [comment]
@ferhatco has this command ever worked using the accesstoken auth with `force:org:beta:create`? Would you share the results of `sfdx version --verbose` please.

**Comment by ferhatco** [comment]
I tried to add client id -i parameter, but i receive same error. I am not creating a package version, so I do not have result of that.

**Comment by peternhale** [comment]
Could you tell me why you are using access token login for the devhub?

Would you share the results of sfdx version --verbose please.

**Comment by Torsen** [comment]
We are using the accesstoken to save the credentials because it is running in a CI Pipeline.

The SFDx version is 7.152.

But we tried it with 7.162 and we are facing the same issue

**Comment by peternhale** [comment]
What auth method are you using to acquire the access token?

**Comment by ferhatco** [comment]
export SFDX_ACCESS_TOKEN="$SESSION"
export instanceUrl="https://$(echo "$ENDPOINT" | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')"
sfdx auth:accesstoken:store -p -d -a myhub --instanceurl "$instanceUrl"

**Comment by peternhale** [comment]
Also have you considered using ` sfdx auth:sfdxurl:store`
```
sfdx auth:sfdxurl:store -h
authorize an org using an SFDX auth URL stored within a file

USAGE
  $ sfdx auth:sfdxurl:store -f <filepath> [-d] [-s] [-a <string>] [--json] [--loglevel trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]

FLAGS
  -a, --setalias=<value>                                                            set an alias for the authenticated org
  -d, --setdefaultdevhubusername                                                    set the authenticated org as the default dev hub org for scratch org creation
  -f, --sfdxurlfile=<value>                                                         (required) path to a file containing the sfdx url
  -s, --setdefaultusername                                                          set the authenticated org as the default username that all commands run against
  --json                                                                            format output as json
  --loglevel=(trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL)  [default: warn] logging level for this command invocation

DESCRIPTION
  authorize an org using an SFDX auth URL stored within a file

  The SFDX auth URL must have the format "force://<clientId>:<clientSecret>:<refreshToken>@<instanceUrl>". NOTE: The SFDX auth URL uses the "force" protocol, and not "http" or "https". Also, the
  "instanceUrl" inside the SFDX auth URL doesn't include the protocol ("https://").

  You have three options when creating the auth file. The easiest option is to redirect the output of the `sfdx force:org:display --verbose --json` command into a file. For example, using an org
  you have already authorized:

  $ sfdx force:org:display -u <OrgUsername> --verbose --json > authFile.json

  $ sfdx auth:sfdxurl:store -f authFile.json

  The resulting JSON file contains the URL in the sfdxAuthUrl property inside of a results object. NOTE: The `force:org:display --verbose` command displays the refresh token only for orgs
  authorized with the web server flow, and not the JWT bearer flow.

  You can also create a JSON file that has a top-level property named sfdxAuthUrl whose value is the auth URL. Finally, you can create a normal text file that includes just the URL and nothing
  else.

ALIASES
  $ sfdx force:auth:sfdxurl:store

EXAMPLES
  $ sfdx auth:sfdxurl:store -f <path to sfdxAuthUrl file>

  $ sfdx auth:sfdxurl:store -f <path to sfdxAuthUrl file> -s -a MyDefaultOrg
```

**Comment by peternhale** [comment]
> 

@ferhatco This describes you using the access token to auth the dev hub. How did you originally acquire the token?

**Comment by Torsen** [comment]
@peternhale  the problem of usign the sfdxurl is that we need to use the clientId and clientSecret but on the other hand the auth:accesstoken we don't need to specify the clientId and clientSecret

**Comment by ferhatco** [comment]
The other problem is that scratch org is being created even the command fails with authentication. But we can not generate password or display that scratch org because of this authenticate issue.

**Comment by peternhale** [comment]
@Torsen using sfdxurl store command does not involve clientid and secret. Are you referring to auth:web:login? One does need to run web:login to capture the URL, but that is the same for access token. Also the auth produced by sfdxurl is more stable and can be refreshed.
```
sfdx auth:sfdxurl:store -f <filepath> [-d] [-s] [-a <string>] [--json] [--loglevel trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]

OPTIONS
  -a, --setalias=setalias                                                           set an alias for the authenticated org
  -d, --setdefaultdevhubusername                                                    set the authenticated org as the default dev hub org for scratch org creation
  -f, --sfdxurlfile=sfdxurlfile                                                     (required) path to a file containing the sfdx url
  -s, --setdefaultusername                                                          set the authenticated org as the default username that all commands run against
  --json                                                                            format output as json
  --loglevel=(trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL)  [default: warn] logging level for this command invocation
```

**Comment by Torsen** [comment]
Maybe I missunderstanding something in the documentation

![image](https://user-images.githubusercontent.com/2922027/183651546-03c62371-ccaa-4fe0-a5bb-3f3cc1d21a0d.png)

**Comment by peternhale** [comment]
Yes, those values are needed, but you do not have to construct the URL, After you auth using `sfdx auth:web:login` (which may require clientid/secret) you can run`sfdx force:org:display -u <devhub username> --verbose`. You will see results similar to this.
```
=== Org Description

 KEY              VALUE                                                                                                                                                   
 ──────────────── ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
 Access Token     <access token>                                       
 Client Id        PlatformCLI                                                                                                                                             
 Connected Status Connected                                                                                                                                               
 Id               <org Id>                                                                                                                                      
 Instance Url     <instance url to org>                                                                                                   
 Sfdx Auth Url    force://PlatformCLI::<data from auth expressed as documentation explains>
 Username         <devhub username>                                                                                                                               
```
You capture the value for `Sfdx Auth Url` into a file and then run `sfdx auth:sfdxurl:store -f <path to sfdxurl file>` Sfdx then authenticate the org and stores the auth info. The key difference you will see is the authinfo for sfdxurl auth will be a refresh token, creating an auth info that is similar to the one obtained via web login.

**Comment by ferhatco** [comment]
Thank you @peternhale by using `sfdx auth:sfdxurl:store -f <path to sfdxurl file>` we managed to authenticate and create scratch orgs.

**Comment by peternhale** [comment]
Nice! Let us know if there is anything else we can help with
