### ISSUE TITLE
force:source:push  pushes all files and not modified ones

### ISSUE THREAD

**Issue by kvor** [forcedotcom/cli#166]
### Summary

sfdx force:source:push

### Steps To Reproduce:

1.  User creates a scratch org.
1. User modifies existing class MyClass.cls.
1.  User pushes files changes sfdx back to scratch org, by running force:source:push.

### Expected result
 
Modified  class (MyClass.cls) should be pushed.

### Actual result

Only MyClass.cls should be pushed.

### Additional information
Noticed after upgrading to latest version (7.22).

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.22.0-de5c6ecff8 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.12.1 (core)
├─ force-language-services 46.16.0 (core)
└─ salesforce-alm 46.15.0 (core)

sfdx-cli 7.22.0 (core)

**OS and version**:
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G87

**Comment by clairebianchi** [comment]
@kvor is the issue that the Push is taking a long time?

**Comment by kvor** [comment]
@clairebianchi Yes one big issue is this. The other one is that force:source:push output is spammed with all pushed (which were not modified) files.

**Comment by clairebianchi** [comment]
@kvor we are unable to replicate this issue on our side. Are you using deploy and push together? If this continues to be an issue please file an issue with Salesforce Support.

**Comment by kvor** [comment]
@clairebianchi We still encounter this problem. We noticed that when we create the scratch org all files have `"state": "n"`. We do deploy/push.
