### ISSUE TITLE
force:data:export:tree --plan only exports 1000 rows of 1400-row object

### ISSUE THREAD

**Issue by tggagne** [forcedotcom/cli#1663]
### Summary

Object with 1400 rows (1000 > x < 2000) only exports 1000 rows even with --plan 

### Steps To Reproduce:
Here's the command:

sfdx force:data:tree:export -u uat -q 'select a-bunch-of-fields from aCustomObject__c limit 2000' -d ./data/ --plan
Wrote 1000 records to data/HWKForm__cs.json
Wrote 0 records to data/HWKForm__c-plan.json

### Expected result

Wrote 1456 records to data/aCustomObject.json ??? (not sure what this should be)
Wrote 0 records to data/HWKForm__c-plan.json ??? ( not sure what this should be)

% grep aCustomField  data/aCustomObject.json |  wc -l
    1456  
### Actual result

Wrote 1000 records to data/HWKForm__cs.json
Wrote 0 records to data/HWKForm__c-plan.json

% grep aCustomField  data/aCustomObject.json |  wc -l
    1000    2000   36463

### System Information

Using zsh on mac osx

tgagne@HWKMAC-C02DN69QMD6M dx-mga % sfdx version --verbose --json 
{
	"cliVersion": "sfdx-cli/7.159.0",
	"architecture": "darwin-x64",
	"nodeVersion": "node-v16.15.0",
	"pluginVersions": [
		"@copado/copado-cli 1.1.15",
		"@oclif/plugin-autocomplete 0.3.0 (core)",
		"@oclif/plugin-commands 1.3.0 (core)",
		"@oclif/plugin-help 3.3.1 (core)",
		"@oclif/plugin-not-found 1.2.6 (core)",
		"@oclif/plugin-plugins 1.10.11 (core)",
		"@oclif/plugin-update 1.5.0 (core)",
		"@oclif/plugin-warn-if-update-available 1.7.3 (core)",
		"@oclif/plugin-which 1.0.4 (core)",
		"@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
		"alias 2.1.0 (core)",
		"apex 1.1.0 (core)",
		"auth 2.2.2 (core)",
		"community 2.0.0 (core)",
		"config 1.4.14 (core)",
		"custom-metadata 2.0.0 (core)",
		"data 2.0.4 (core)",
		"generator 2.0.2 (core)",
		"info 2.0.1 (core)",
		"limits 2.0.1 (core)",
		"org 2.0.2 (core)",
		"salesforce-alm 54.6.2 (core)",
		"schema 2.1.1 (core)",
		"sfdx-cli 7.159.0 (core)",
		"signups 1.2.0 (core)",
		"source 2.0.7 (core)",
		"telemetry 2.0.0 (core)",
		"templates 55.0.0 (core)",
		"trust 2.0.1 (core)",
		"user 2.1.0 (core)",
		"vlocityestools 0.22.14"
	],
	"osVersion": "Darwin 21.5.0"
}

### Additional information

None.

**Comment by mshanemc** [comment]
I don't know when this was fixed, but it works now.

```
sf data export tree -o gus -q 'select id from ADM_Work__c limit 1500' -d data --plan
Wrote 1500 records to data/ADM_Work__cs.json
```

If you can still repro, please open a new issue with your reproduction.
