### ISSUE TITLE
Error with RC Version (v7.164.1)

### ISSUE THREAD

**Issue by thobanrev** [forcedotcom/cli#1665]
### Summary

When building with recent CA version of the sfdx cli (v7.164.1), the sfdx force:source:push fails with the following error:

ERROR running force:source:push:  UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1516507965-95591 (-1488516052)

When we revert to v7.163.0, it works again.

### Steps To Reproduce:

run this command from our circleci job...
sfdx force:source:push -u circle_build_$CIRCLE_BUILD_NUM -w 30

### Expected result

The push succeeds in executing push to deploy all code in our CI scratch org.

### Actual result

ERROR running force:source:push:  UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 1516507965-95591 (-1488516052)

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

running from docker image:  salesforce/salesforcedx:latest-rc-full

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
- Paste the output here
You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements.

{
  "cliVersion": "sfdx-cli/7.164.1",
  "architecture": "linux-x64",
  "nodeVersion": "node-v16.13.2",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.1.0 (core)",
    "auth 2.2.3 (core)",
    "community 2.0.0 (core)",
    "config 1.4.17 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.0.1 (core)",
    "limits 2.0.1 (core)",
    "org 2.1.7 (core)",
    "schema 2.1.1 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.11 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.3 (core)",
    "user 2.1.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
    "salesforce-alm 54.8.1 (core)"
  ],
  "osVersion": "Linux 5.10.104-linuxkit"
}

### Additional information

_Feel free to attach a screenshot_.

**Comment by mdonnalley** [comment]
@thobanrev I'm not able to reproduce this with dreamhouse-lwc. Are you able to share a salesforce project that reliably reproduces the issue? Thanks!

**Comment by thobanrev** [comment]
Thanks for trying to reproduce this issue.  Unfortunately, I won't be able to send you our source code.

**Comment by thobanrev** [comment]
Closing this.  We will pursue with with SF support.

**Comment by Renan-Mastropaolo** [comment]
Hey @thobanrev , any help from SF support? I am facing the same behavior but with different command.

**Comment by thobanrev** [comment]
Yes.  SF support acknowledges there's a problem.  They escalated the issue to their R&D team.  I guess they will work with the GitHub CLI team.

**Comment by jjkarsten** [comment]
@thobanrev Any news on this? We are still running into this problem.

**Comment by thobanrev** [comment]
No word yet.  Our work around is to use the last version that worked for us: v7.163.0

If you create a ticket with saleforce support, they can probably put you onto their notification list.

**Comment by Renan-Mastropaolo** [comment]
Hello @thobanrev test new version 7.169.1. This version includes a fix for the issue.

**Comment by thobanrev** [comment]
Thanks.  I tested it last week and yes it fixed the issue for us.
