### ISSUE TITLE
Certain SFDX commands fail to run in Git Bash environment

### ISSUE THREAD

**Issue by slaght** [forcedotcom/cli#1666]
### Summary

While running `sfdx` commands in my Git Bash environment (writing a shell script for my team to automate scratch org creation) I noticed that some commands were failing to execute at all, while some others were passing. 

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Open project in VSCode and start a new terminal with the Git Bash environment
2.  Run any of the following commands:
    - `sfdx force:data:record:update -s User -w "Name='UserName" -v "Role='CEO'"`
    - `sfdx force:community:publish --name "CommunityName"`
    - `sfdx force:user:permset:assign -n "PermissionSetName" `
3. Note that the following commands run properly:
    - `sfdx force:org:create -s -f config/project-scratch-def.json -a "ScratchOrgName" -d 30`
    - `sfdx force:source:push -f`
    - `sfdx force:mdapi:deploy -d force-app/main/default/audience`
4. Additionally, all commands listed run properly in the Powershell environment.

### Expected result

Commands execute properly

### Actual result

The commands listed under the second step of reproduction steps produce the following output:
```
$ sfdx force:data:record:update -s User -w "Name='UserName'" -v "Role='CEO'"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
```
$ sfdx force:community:publish --name "CommunityName"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
```
$ sfdx force:user:permset:assign -n "PermissionSetName"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

### System Information

Using Git Bash through VSCode on Windows 10.

```
VSCode:
Version: 1.70.1 (system setup)
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T06:08:33.642Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19042
```

```
$ git -v
git version 2.37.1.windows.1
```

```
$ sfdx version --verbose --json
{
        "cliVersion": "sfdx-cli/7.156.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.0 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.1 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 1.13.2 (core)",
                "salesforce-alm 54.6.0 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.156.1 (core)",
                "sfdx-wry-plugin 0.0.11 (link) [location redacted]",
                "signups 1.2.0 (core)",
                "source 2.0.2 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.0 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19042"
}
```

### Additional information

Would appreciate some troubleshooting if the issue is configuration-related on my end.

**Comment by mdonnalley** [comment]
@slaght Thanks for filing the issue. Can you see if updating to `7.163.0` or `7.164.1` resolves the issue for you?

If not, could you then provide the following:
1. Output from `sfdx plugins:inspect sfdx-cli`
2. The debug output from one of the failing commands (by appending `--dev-debug` to any of those commands)

Thanks!

**Comment by slaght** [comment]
Hey @mdonnalley - 
Updating to `7.163.0` did not end up fixing the issue unfortunately. I can try `7.164.1` if you think that has a good chance of fixing it. 
Here is my output for `sfdx plugins:inspect sfdx-cli`:
```
$ sfdx plugins:inspect sfdx-cli
└─ sfdx-cli
   ├─ version 7.163.0
   ├─ homepage https://github.com/salesforcecli/sfdx-cli/
   ├─ location C:\Users\brandon.slaght\AppData\Local\sfdx\client\7.163.0-ea5a9c6
   ├─ commands
   └─ dependencies
      ├─ @oclif/core ^1.9.3 => 1.13.1
      ├─ @oclif/plugin-autocomplete ^1.3.0 => 1.3.0
      ├─ @oclif/plugin-commands ^2.2.0 => 2.2.0
      ├─ @oclif/plugin-help ^5.1.12 => 5.1.12
      ├─ @oclif/plugin-not-found ^2.3.1 => 2.3.1
      ├─ @oclif/plugin-plugins ^2.1.0 => 2.1.0
      ├─ @oclif/plugin-update 3.0.0 => 3.0.0
      ├─ @oclif/plugin-version ^1.1.1 => 1.1.1
      ├─ @oclif/plugin-warn-if-update-available ^2.0.4 => 2.0.4
      ├─ @oclif/plugin-which ^2.1.0 => 2.1.0
      ├─ @salesforce/kit ^1.5.13 => 1.5.45
      ├─ @salesforce/lazy-require ^0.4.0 => 0.4.21
      ├─ @salesforce/plugin-alias 2.1.0 => 2.1.0
      ├─ @salesforce/plugin-apex 1.1.0 => 1.1.0
      ├─ @salesforce/plugin-auth 2.2.3 => 2.2.3
      ├─ @salesforce/plugin-community 2.0.0 => 2.0.0
      ├─ @salesforce/plugin-config 1.4.17 => 1.4.17
      ├─ @salesforce/plugin-custom-metadata 2.0.0 => 2.0.0
      ├─ @salesforce/plugin-data 2.1.1 => 2.1.1
      ├─ @salesforce/plugin-generator 2.0.2 => 2.0.2
      ├─ @salesforce/plugin-info 2.0.1 => 2.0.1
      ├─ @salesforce/plugin-limits 2.0.1 => 2.0.1
      ├─ @salesforce/plugin-org 2.0.7 => 2.0.7
      ├─ @salesforce/plugin-schema 2.1.1 => 2.1.1
      ├─ @salesforce/plugin-signups 1.2.0 => 1.2.0
      ├─ @salesforce/plugin-source 2.0.11 => 2.0.11
      ├─ @salesforce/plugin-telemetry 2.0.0 => 2.0.0
      ├─ @salesforce/plugin-templates 55.1.0 => 55.1.0
      ├─ @salesforce/plugin-trust ^2.0.3 => 2.0.3
      ├─ @salesforce/plugin-user 2.1.0 => 2.1.0
      ├─ @salesforce/require-analytics ^0.9.16 => 0.9.21
      ├─ @salesforce/sfdx-plugin-lwc-test 1.0.0 => 1.0.0
      ├─ @salesforce/ts-types ^1.5.17 => 1.5.20
      ├─ debug ^4.3.1 => 4.3.4
      ├─ salesforce-alm 54.7.1 => 54.7.1
      ├─ shelljs ^0.8.4 => 0.8.5
      ├─ tslib ^2.1.0 => 2.4.0
      └─ v8-compile-cache ^2.2.0 => 2.3.0
```
And unfortunately the `--dev-debug` flag does not generate any additional output either:
```
$ sfdx force:community:publish --name "CommunityName" --dev-debug
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mdonnalley** [comment]
@slaght thanks!

Does `sfdx force:community:publish --name CommunityName` (no quotes around CommunityName) work for you?

**Comment by slaght** [comment]
> @slaght thanks!
> 
> Does `sfdx force:community:publish --name CommunityName` (no quotes around CommunityName) work for you?

@mdonnalley well, this is interesting - I created a new community with no spaces in the name (my other communities have multi-word names) and publishing the new one WITH the quotes around the name works fine. Could that have something to do with it? I also realized the other two commands I sent that I thought would work actually throw errors in poweshell as well, but I would expect those error messages to show up in Git Bash output too instead of what is shown.

**Comment by mdonnalley** [comment]
@slaght I suspect that there's something wrong with your `PATH`, although I don't know what the exact issue would be. However, I'm fairly certain that it's _not_ an sfdx issue since `sfdx force:community:publish --name "CommunityName" --dev-debug` failed before any logs could be sent to the terminal.

That being said, we don't officially support sfdx on the git bash terminal so I'm going to close this issue for now
