### ISSUE TITLE
force:source:deploy fails with ENOENT -4058

### ISSUE THREAD

**Issue by Andrews-Consulting** [forcedotcom/cli#167]
Behavior:
1) Deploying LWC and Aura components via command pallete failed to produce the "deployed source" response. 
2) Entered the command in the CLI and received an ENOENT error (-4058), "No such file or directory"

Relevant Notes:
3) I am deploying to a "demo/trial org" created from a partner account.
4) The attached trace file shows the directory created (potentially as a plain directory), files moved in, and then the reference to the Zip file that fails.  Not every step is documented, so I'm unable to pinpoint the failure.  The zip file does exist once the process is complete.  
5) I  validated security settings for the folder and they appear correct - the process should have access.

Versions: 
C:\Users\Chris\Desktop\Work in Progress\Enlighten\CLI\Enlighten>sfdx plugins --core
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.12.1 (core)
├─ force-language-services 46.16.0 (core)
└─ salesforce-alm 46.15.0 (core)

sfdx-cli 7.22.0 (core)

[sfdx-trace.log](https://github.com/forcedotcom/cli/files/3569744/sfdx-trace.log)

**Comment by clairebianchi** [comment]
@Andrews-Consulting can you please provide the command you are using

**Comment by Andrews-Consulting** [comment]
I'm now seeing this error sporadically with Aura component deployments in other non-scratch orgs, so I'm going to reopen this ticket.  
I see the same results for the following commands: 
     right clicking and using the "sfdx:Deploy this source to Org" in vscode 
     sfdx force:source:deploy --sourcepath c:\Users\....[directory structure].....\force-app\main\default\aura\ProductSelector --json --loglevel fatal

**Comment by Andrews-Consulting** [comment]
I'm also seeing this error occasionally on Deletes: Here is a successful Delete followed by a failure: 
Both deletes were invoked via the right click in the file explorer pane and selecting Delete from Project and Org.
Running sfdx-cli/7.33.2-045d48473e win32-x64 node-v10.15.3 on this date.

`
Starting SFDX: Delete from Project and Org

12:28:04.748 sfdx force:source:delete --sourcepath c:\Users\Chris\Desktop\Work in Progress\XXX\CLI\XXX-chrisdev\force-app\main\default\classes\OpportunityLineItemTrgUtilTest.cls --noprompt
=== Deleted Source
FULL NAME                       TYPE       PROJECT PATH
──────────────────────────────  ─────────  ──────────────────────────────────────────────────────────────────────────
OpportunityLineItemTrgUtilTest  ApexClass  force-app\main\default\classes\OpportunityLineItemTrgUtilTest.cls
OpportunityLineItemTrgUtilTest  ApexClass  force-app\main\default\classes\OpportunityLineItemTrgUtilTest.cls-meta.xml
12:28:11.533 sfdx force:source:delete --sourcepath c:\Users\Chris\Desktop\Work in Progress\XXX\CLI\XXX-chrisdev\force-app\main\default\classes\OpportunityLineItemTrgUtilTest.cls --noprompt ended with exit code 0

Starting SFDX: Delete from Project and Org

12:30:18.314 sfdx force:source:delete --sourcepath c:\Users\Chris\Desktop\Work in Progress\XXX\CLI\XXX-chrisdev\force-app\main\default\triggers\OpportunityLineItemTrigger.trigger --noprompt
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
{ [Error: ENOENT: no such file or directory, open 'C:\Users\Chris\AppData\Local\Temp\sdx_sourceDeploy_1574533820048.zip']
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path:
   'C:\\Users\\Chris\\AppData\\Local\\Temp\\sdx_sourceDeploy_1574533820048.zip' }
12:30:20.969 sfdx force:source:delete --sourcepath c:\Users\Chris\Desktop\Work in Progress\XXX\CLI\XXX-chrisdev\force-app\main\default\triggers\OpportunityLineItemTrigger.trigger --noprompt ended with exit code 0`

**Comment by Andrews-Consulting** [comment]
I re-encountered this issue again working on certifications today.  After uninstalling the CLI and re-installaing the CLI, I'm able to deploy to this org.  Not sure if it was a code issue or installation issue.
