### ISSUE TITLE
(7.58.1) Issue deploying matching rules through manifest/package.xml

### ISSUE THREAD

**Issue by gcidre1** [forcedotcom/cli#1677]
### Summary

When I run manifest/package.xml on with MatchingRule setup, I sometimes get duplicate errors with no understanding what the issue is. 

### Steps To Reproduce:

1.  Create force-app\main\default\matchingRules\Contact.matchingRule-meta.xml with the following content specified below
2.  Create manifest/package.xml with the package below
3. Deploy file: sfdx force:source:deploy -p force-app/main/default/matchingRules/Contact.matchingRule-meta.xml
4. Deploy through manifest: sfdx force:source:deploy -x manifest/package.xml
### Expected result
Program should run and deploy the matching rules. This is happening with version 7.85.1.

### Actual result

we get the following duplicate errors:
  Type  Name                                   Problem

 ───── ────────────────────────────────────── ─────────────────────────────────────────────────────────────────
 Error Contact.Banana_Apple_Orange            Duplicate name 'Contact.Banana_Apple_Orange' specified       

 Error Contact.Banana_Apple_Orange            Duplicate name 'Contact.Banana_Apple_Orange' specified       

 Error Contact.Banana_Apple_Orange_Lemon      Duplicate name 'Contact.Banana_Apple_Orange_Lemon' specified 

 Error Contact.Banana_Apple_Orange_Lemon      Duplicate name 'Contact.Banana_Apple_Orange_Lemon' specified 

 Error Contact.Banana_Apple_Orange_Lemon_Lime Duplicate name 'Contact.Banana_Apple_Orange_Lemon_Lime' specified
 Error Contact.Banana_Apple_Orange_Lemon_Lime Duplicate name 'Contact.Banana_Apple_Orange_Lemon_Lime' specified

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version` **AND** `sf plugins --core`
{
        "cliVersion": "sfdx-cli/7.158.1",
        "architecture": "win32-x64",
        "nodeVersion": "node-v16.15.1",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",    
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
                "alias 2.1.0 (core)",
                "apex 0.13.0 (core)",
                "auth 2.2.2 (core)",
                "community 2.0.0 (core)",
                "config 1.4.12 (core)",
                "custom-metadata 2.0.0 (core)",
                "data 2.0.4 (core)",
                "generator 2.0.2 (core)",
                "info 2.0.1 (core)",
                "limits 2.0.1 (core)",
                "org 2.0.1 (core)",
                "salesforce-alm 54.6.2 (core)",
                "schema 2.1.1 (core)",
                "sfdx-cli 7.158.1 (core)",
                "signups 1.2.0 (core)",
                "source 2.0.3 (core)",
                "telemetry 2.0.0 (core)",
                "templates 55.0.0 (core)",
                "trust 2.0.1 (core)",
                "user 2.1.0 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19042"
}
#### package.xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>55.0</version>
    <types>
        <members>Contact.Banana_Apple_Orange</members>
        <members>Contact.Banana_Apple_Orange_Lemon</members>
        <members>Contact.Banana_Apple_Orange_Lemon_Lime</members>
        <name>MatchingRule</name>
    </types>
</Package>

#### Contact Matching rules
<?xml version="1.0" encoding="UTF-8"?>
<MatchingRules xmlns="http://soap.sforce.com/2006/04/metadata">
    <matchingRules>
        <fullName>Banana_Apple_Orange</fullName>
        <booleanFilter>1 AND 2</booleanFilter>
        <description></description>
        <label>Banana_Apple_Orange</label>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>FirstName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>LastName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <ruleStatus>Inactive</ruleStatus>
    </matchingRules>
    <matchingRules>
        <fullName>Banana_Apple_Orange_Lemon</fullName>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <description></description>
        <label>Banana_Apple_Orange_Lemon</label>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>FirstName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>LastName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>Email</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <ruleStatus>Inactive</ruleStatus>
    </matchingRules>
    <matchingRules>
        <fullName>Banana_Apple_Orange_Lemon_Lime</fullName>
        <booleanFilter>(1 AND 2) OR (3 OR 4)</booleanFilter>
        <description></description>
        <label>Banana_Apple_Orange_Lemon_Lime</label>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>FirstName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>LastName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>Email</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>MobilePhone</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <ruleStatus>Inactive</ruleStatus>
    </matchingRules>
</MatchingRules>

**Comment by gcidre1** [comment]
sorry the files didn't render right :(.
Re rendering them here:
## Package.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>55.0</version>
    <types>
        <members>Contact.Banana_Apple_Orange</members>
        <members>Contact.Banana_Apple_Orange_Lemon</members>
        <members>Contact.Banana_Apple_Orange_Lemon_Lime</members>
        <name>MatchingRule</name>
    </types>
</Package>
```

## Contact matching rule file:
```
<?xml version="1.0" encoding="UTF-8"?>
<MatchingRules xmlns="http://soap.sforce.com/2006/04/metadata">
    <matchingRules>
        <fullName>Banana_Apple_Orange</fullName>
        <booleanFilter>1 AND 2</booleanFilter>
        <description></description>
        <label>Banana_Apple_Orange</label>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>FirstName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>LastName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <ruleStatus>Inactive</ruleStatus>
    </matchingRules>
    <matchingRules>
        <fullName>Banana_Apple_Orange_Lemon</fullName>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <description></description>
        <label>Banana_Apple_Orange_Lemon</label>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>FirstName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>LastName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>Email</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <ruleStatus>Inactive</ruleStatus>
    </matchingRules>
    <matchingRules>
        <fullName>Banana_Apple_Orange_Lemon_Lime</fullName>
        <booleanFilter>(1 AND 2) OR (3 OR 4)</booleanFilter>
        <description></description>
        <label>Banana_Apple_Orange_Lemon_Lime</label>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>FirstName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>LastName</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>Email</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <matchingRuleItems>
            <blankValueBehavior>NullNotAllowed</blankValueBehavior>
            <fieldName>MobilePhone</fieldName>
            <matchingMethod>Exact</matchingMethod>
        </matchingRuleItems>
        <ruleStatus>Inactive</ruleStatus>
    </matchingRules>
</MatchingRules>
```

**Comment by gcidre1** [comment]
It is version 7.158.1.... I can't type correctly today =|

**Comment by mdonnalley** [comment]
@gcidre1 Thanks for filing an issue. From my testing you should be able to successfully deploy your MatchingRules using this package.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>55.0</version>
    <types>
        <members>Contact.Banana_Apple_Orange</members>
        <members>Contact.Banana_Apple_Orange_Lemon</members>
        <members>Contact.Banana_Apple_Orange_Lemon_Lime</members>
        <name>MatchingRule</name>
    </types>
    <types>
      <members>Contact</members>
      <name>MatchingRules</name>
    </types>
</Package>
```

**Comment by gcidre1** [comment]
That is great!!! thx
