### ISSUE TITLE
Retrieving metadata modifies xmlns

### ISSUE THREAD

**Issue by vmarasow** [forcedotcom/cli#168]
### Summary

_When retrieving metadata that was created using the cli the org is modifying the xmlns of the meta.xml file_.

### Steps To Reproduce:

1. Create a new apex class using the CLI.
2. Deploy the class to an org.
3. Retrieve the class from the org.
4. The class.cls-meta.xml file will be changed.

### Expected result

_The meta file values should be consistent across sfdx commands_.

### Actual result

_Attributes on the metadata type are modified from the value that is provided when the create command is run_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli 7.22.0 (core)

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
salesforcedx 46.12.1 (core)
├─ force-language-services 46.16.0 (core)
└─ salesforce-alm 46.15.0 (core)

**OS and version**:
MacOS Mojave 10.14

**Comment by mshanemc** [comment]
I can't reproduce this with what's given.

If you still can get the problem, please provide more detailed reproduction steps (ex: what exact command are you running to deploy/retrieve?  What's in your class? What did the meta file change from/to?
