### ISSUE TITLE
(7.85.1) sfdx force:auth:jwt:grant intermitten authentication issue.

### ISSUE THREAD

**Issue by gcidre1** [forcedotcom/cli#1681]
### Summary
Hi man. my team is currently experiencing a really weird intermittent issues revolving around jwt authentication issue.. We are getting connection issue when running two bash scripts in a row sometimes that tries to run jwt authentication. I was wondering if I can get your opinion around the issue. I'm hoping the issue is going to go away. But initially it hasn't. 

### Steps To Reproduce:
we have a jenkins pipeline that runs a script(call script A) that runs:
```
 export NODE_EXTRA_CA_CERTS=/usr/lib/jvm/jre-1.8.0/lib/security/cacerts
                            export NODE_TLS_REJECT_UNAUTHORIZED=0
                            export PATH=...
                            export HTTP_PROXY=...
                            export HTTPS_PROXY=...
                            ....
                            sfdx force:auth:jwt:grant -i ... -u ... -f ...-r ...
                            sfdx deploy ....
```
Then it runs the another script called script B:
```
 export NODE_EXTRA_CA_CERTS=/usr/lib/jvm/jre-1.8.0/lib/security/cacerts
                            export NODE_TLS_REJECT_UNAUTHORIZED=0
                            export PATH=...
                            export HTTP_PROXY=...
                            export HTTPS_PROXY=...
                            ....
                            sfdx force:auth:jwt:grant -i ... -u ... -f ...-r ...
                            sfdx deploy ....
```

### Expected result
Both script would authorize jwt correctly and run whatever was needed below.

### Actual result
Script A would run successfully. But when running Script B, we would get the following error:
```
11:54:08  ERROR running auth:jwt:grant:  We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: Error authenticating with JWT config due to: request to https://test.salesforce.com//services/oauth2/token failed, reason: read ECONNRESET
11:54:08  request to https://login.salesforce.com/services/oauth2/token failed, reason: read ECONNRESET
11:54:08  request to https://test.salesforce.com//services/oauth2/token failed, reason: read ECONNRESET
```

This happened on August 17 on 100% percent of our pipeline calls. August 18 yielded 37.5%

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
I know it is done on 7.85.1 in a docker build.
### Additional information

_Feel free to attach a screenshot_.

**Comment by mdonnalley** [comment]
@gcidre1 Can you try on the latest version of the CLI (7.164.2)? Version 7.85.1 is nearly 1.5 years old at this point

Thanks!

**Comment by gcidre1** [comment]
due to some business contraints... I can't upgrade the version for the pipeline yet. We are currently in the process of updating it but it is going to take a while. The issue also disappeared on the pipeline :). maybe it is an intermitten issue.
