### ISSUE TITLE
ERROR running force:package:install Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by nemobeamo** [forcedotcom/cli#1685]
Whenever I run the package install command, I get a weird error.

```
PS /Users/xxxxx/IdeaProjects/NA_VEEVA_MARS> sfdx force:package:install --package 04XXXXXXXXXXXXXX
ERROR running force:package:install:  Cannot read properties of undefined (reading 'length')
```

I verified that I'm logged into the correct dev hub and destination org. Does anybody know how to resolve this?

**CLI Version Info**
```
{
  "cliVersion": "sfdx-cli/7.165.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.3 (core)",
    "community 2.0.0 (core)",
    "config 1.4.17 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.0.1 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.0 (core)",
    "schema 2.1.1 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.12 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.3 (core)",
    "user 2.1.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
    "salesforce-alm 54.8.1 (core)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/georgemandala/.local/share/sfdx/client/7.165.0-65b4bb0"
}
```

**Comment by iowillhoit** [comment]
Hello @nemobeamo, thanks for the issue. I just tried to reproduce this but I was unable to. My package was installed successfully. I am using `sfdx 7.165.0 - node 16.15.1`. 

- Has this exact package worked for you on a previous version of the CLI? 
- Any chance you could create a reproduction repo that you could share with us (with steps to reproduce)?
  - We often use [Dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc) for this

**Comment by nemobeamo** [comment]
I was able to fix the issue by disconnecting and reauthorising the destination org.  I must have had a stale auth key.

**Comment by sawuapara** [comment]
I just tried doing that but no luck. Nothing on the sfdx.log either:

`{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":17554,"log":"SfdxProjectJson","level":40,"msg":"The config file: /Users/samirawuapara/.sfdx/sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2022-08-26T19:40:17.031Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":17554,"log":"SfdxProjectJson","level":40,"msg":"The config file: /Users/samirawuapara/.sfdx/sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2022-08-26T19:40:17.036Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":17554,"log":"SfdxProjectJson","level":40,"msg":"The config file: /Users/samirawuapara/IdeaProjects/Clients/Fivesky/Fivesky/sfdx-project.json is not schema valid\nDue to: Validation errors:\n should NOT have additional properties 'name'","time":"2022-08-26T19:40:17.040Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":17636,"log":"SfdxProjectJson","level":40,"msg":"The config file: /Users/samirawuapara/.sfdx/sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2022-08-26T19:42:02.332Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":17636,"log":"SfdxProjectJson","level":40,"msg":"The config file: /Users/samirawuapara/IdeaProjects/Clients/Fivesky/Fivesky/sfdx-project.json is not schema valid\nDue to: Validation errors:\n should NOT have additional properties 'name'","time":"2022-08-26T19:42:02.341Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":17636,"log":"SfdxProjectJson","level":40,"msg":"The config file: /Users/samirawuapara/.sfdx/sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2022-08-26T19:42:02.347Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":17636,"log":"SfdxProjectJson","level":40,"msg":"The config file: /Users/samirawuapara/IdeaProjects/Clients/Fivesky/Fivesky/sfdx-project.json is not schema valid\nDue to: Validation errors:\n should NOT have additional properties 'name'","time":"2022-08-26T19:42:02.349Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":17636,"log":"SourceDeployCommand","level":50,"msg":"[\n  '\\x1B[1mERROR running force:source:deploy: \\x1B[22m',\n  '\\x1B[31mUnexpected argument: -f\\x1B[39m\\n\\x1B[31mSee more help with --help\\x1B[39m'\n]","time":"2022-08-26T19:42:02.351Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":17670,"log":"OrgListCommand","level":40,"msg":"[\n  '\\x1B[33mWARNING:\\x1B[39m',\n  'Starting in API version 52, the JSON output of this command no longer returns the property connectedStatus for scratch orgs.'\n]","time":"2022-08-26T19:42:20.004Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":40067,"log":"OrgListCommand","level":40,"msg":"[\n  'WARNING:',\n  'Starting in API version 52, the JSON output of this command no longer returns the property connectedStatus for scratch orgs.'\n]","time":"2022-08-29T11:53:06.715Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":41956,"log":"OrgListCommand","level":40,"msg":"[\n  'WARNING:',\n  'Starting in API version 52, the JSON output of this command no longer returns the property connectedStatus for scratch orgs.'\n]","time":"2022-08-29T17:38:44.309Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":43108,"log":"OrgListCommand","level":40,"msg":"[\n  'WARNING:',\n  'Starting in API version 52, the JSON output of this command no longer returns the property connectedStatus for scratch orgs.'\n]","time":"2022-08-29T17:46:41.385Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":43331,"log":"OrgListCommand","level":40,"msg":"[\n  '\\x1B[33mWARNING:\\x1B[39m',\n  'Starting in API version 52, the JSON output of this command no longer returns the property connectedStatus for scratch orgs.'\n]","time":"2022-08-29T17:47:30.146Z","v":0}
{"name":"sfdx","hostname":"MacBook-Pro.localdomain","pid":44785,"log":"OrgListCommand","level":40,"msg":"[\n  '\\x1B[33mWARNING:\\x1B[39m',\n  'Starting in API version 52, the JSON output of this command no longer returns the property connectedStatus for scratch orgs.'\n]","time":"2022-08-29T18:27:06.400Z","v":0}`
