### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by sawuapara** [forcedotcom/cli#1686]
### Summary

Receiving "Cannot read properties of undefined (reading 'length')" error when running command 

`sfdx force:org:shape:list`

### Steps To Reproduce:
Run from a SFDX Project

`sfdx force:org:shape:list`

### System Information

Running Mac M1 Pro with the following version of sfdx-cli. I already uninstalled all plugins per other similar github issues:

`{
  "cliVersion": "sfdx-cli/7.165.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.3 (core)",
    "community 2.0.0 (core)",
    "config 1.4.17 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.0.1 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.0 (core)",
    "schema 2.1.1 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.12 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.3 (core)",
    "user 2.1.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
    "salesforce-alm 54.8.1 (core)"
  ],
  "osVersion": "Darwin 21.5.0",
  "shell": "bash",
  "rootPath": "/Users/samirawuapara/.local/share/sfdx/client/7.165.0-65b4bb0"
}
`
_Feel free to attach a screenshot_.

**Comment by iowillhoit** [comment]
Hey @sawuapara, thanks for reporting this issue. Unfortunately I am not able to reproduce this. I've tried the following with `sfdx` from the Installer and `npm`. I am using version `7.165.0` with `npm: '8.15.0'` and  `node: '16.17.0'`

- `sfdx force:org:shape:list` (with no shapes) -> `No org shapes found.`
- `sfdx force:org:shape:create -u myDevHub` -> shape creates
- `sfdx force:org:shape:list` -> lists created shape
- `sfdx force:org:shape:delete` -> deletes created shape
- `sfdx force:org:shape:list` -> `No org shapes found.`

Can you provide any additional details on how to reproduced this issue? Thanks

**Comment by iowillhoit** [comment]
Could you try reauthenticating with your devhub/scratch org and see if that helps? Someone reported that this resolved their issue yesterday. 

https://github.com/forcedotcom/cli/issues/1685#issuecomment-1230786742

**Comment by gsbasso** [comment]
Re-authenticating resolved issue for me. Thank you.
