### ISSUE TITLE
unfiled$public email templates failing with invalid source path

### ISSUE THREAD

**Issue by AzaruddinKhan** [forcedotcom/cli#1688]
### Summary

$public symbol is skipped when deploying the public email template. Below is the command that I have executed.

### Steps To Reproduce:

1.  Run the below command to deploy the public email template
2. **npx sfdx force:source:deploy --sourcepath 'force-app/main/default/email/unfiled$public/O_testexcept.email' --json  --targetusername testorg1 --testlevel NoTestRun**

### Expected result

Email template should get deployed to org without any issues

### Actual result

{
  "status": 1,
  "name": "SfdxError",
  "message": "The sourcepath \"force-app/main/default/email/unfiled/O_testexcept.email\" is not a valid source file path.",
  "exitCode": 1,
  "commandName": "Deploy",
  "stack": "SfdxError: The sourcepath \"force-app/main/default/email/unfiled/OC_TH_Formal_Answer_accepted_by_customer.email\" is not a valid source file path.\n    at /Volumes/HD/Azar/Salesforce/node_modules/@salesforce/plugin-source/lib/componentSetBuilder.js:33:31\n    at Array.forEach (<anonymous>)\n    at Function.build (/Volumes/HD/Azar/Salesforce/node_modules/@salesforce/plugin-source/lib/componentSetBuilder.js:31:28)\n    at Deploy.deploy (/Volumes/HD/Azar/Salesforce/node_modules/@salesforce/plugin-source/lib/commands/force/source/deploy.js:61:81)\n    at async Deploy.run (/Volumes/HD/Azar/Salesforce/node_modules/@salesforce/plugin-source/lib/commands/force/source/deploy.js:32:9)\n    at async Deploy._run (/Volumes/HD/Azar/Salesforce/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/Volumes/HD/Azar/Salesforce/node_modules/@oclif/config/lib/config.js:173:24)\n    at async SfdxMain.run (/Volumes/HD/Azar/Salesforce/node_modules/@oclif/command/lib/main.js:27:9)\n    at async SfdxMain._run (/Volumes/HD/Azar/Salesforce/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Volumes/HD/Azar/Salesforce/node_modules/sfdx-cli/dist/cli.js:162:47)",
  

### System Information

{
        "cliVersion": "sfdx-cli/7.133.0",
        "architecture": "darwin-x64",
        "nodeVersion": "node-v16.4.2",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.3.1 (core)",
                "@oclif/plugin-not-found 1.2.6 (core)",
                "@oclif/plugin-plugins 1.10.11 (core)",
                "@oclif/plugin-update 1.5.0 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
                "@oclif/plugin-which 1.0.4 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "alias 1.2.0 (core)",
                "apex 0.7.0 (core)",
                "auth 1.8.0 (core)",
                "config 1.3.14 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.6.8 (core)",
                "generator 1.2.2 (core)",
                "info 1.2.0 (core)",
                "limits 1.3.0 (core)",
                "org 1.11.0 (core)",
                "salesforce-alm 53.7.2 (core)",
                "schema 1.1.0 (core)",
                "sfdx-cli 7.133.0 (core)",
                "sfdx-git-delta 5.2.0",
                "sfdx-hardis 2.87.4",
                "source 1.7.0 (core)",
                "telemetry 1.4.0 (core)",
                "templates 52.7.0 (core)",
                "texei-sfdx-plugin 1.16.0",
                "trust 1.1.0 (core)",
                "user 1.7.0 (core)"
        ],
        "osVersion": "Darwin 21.1.0"
_Feel free to attach a screenshot_.

**Comment by AzaruddinKhan** [comment]
The work around I have is to remove the npx from the command and run it. But I have dependencies to use that npx for other commands. So Just curious what exactly the issue is.

**Comment by iowillhoit** [comment]
Hello @AzaruddinKhan, thanks for the issue. I am not sure what would be happening with `npx`. However, we do not currently support executing commands this way. Please let us know if you continue to see an issue with `sfdx` installed by one of our supported methods (`npm`, Installers, TAR file, Docker image) and we will investigate further.
