### ISSUE TITLE
Extreme latency in sfdx source push commands

### ISSUE THREAD

**Issue by jwalke** [forcedotcom/cli#1689]
### Summary

Starting today (August 30th, 2022) we're seeing extreme latency when executing the `sfdx force:source:push` command.

We're also seeing timeouts/latency in `sfdx force:package:version:create` with unlocked packages (likely due to the same underlying issue)

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Create a scratch org: `sfdx force:org:create -s -f config/project-scratch-def.json -a dreamhouse`
1.  Push source: `sfdx force:source:push`

### Expected result

The push command will complete and the dreamhouse project will push into scratch org

### Actual result

Command hangs indefinitely (this screenshot was taken 25 minutes after executing the push command):

![Screen Shot 2022-08-30 at 11 19 49 AM](https://user-images.githubusercontent.com/4999865/187502274-6ffc6f76-ca05-447b-869f-dc438bdc6ca7.png)

### System Information

- Which shell/terminal are you using? zsh
```
❯ sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.165.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.3 (core)",
    "community 2.0.0 (core)",
    "config 1.4.17 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.0.1 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.0 (core)",
    "schema 2.1.1 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.12 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.3 (core)",
    "user 2.1.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
    "salesforce-alm 54.8.1 (core)",
    "sfdx-browserforce-plugin 2.9.1 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/walkej/.local/share/sfdx/client/7.165.0-65b4bb0"
}
```

### Additional Information

[Trailblazer Community thread for this issue
](https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000JdEyjSAF)

**Comment by daveespo** [comment]
I filed a Case for this: #43210316

I suggest you do the same -- this has basically caused our entire engineering team to grind to a halt.

**Comment by iowillhoit** [comment]
Hello all, please see this pinned issue: https://github.com/forcedotcom/cli/issues/1690

**Comment by iowillhoit** [comment]
Note: I am going to leave this open for a while to drive folks to the pinned issue ^
