### ISSUE TITLE
sfdx-cli Not working for Fork Public PR

### ISSUE THREAD

**Issue by Sarveshgithub** [forcedotcom/cli#1691]
Facing an issue in SFDX CLI on Github Action 
Background issue [detail](https://github.com/scolladon/sfdx-git-delta/issues/344)

So I have a public [repo](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable), I am adding a CI process for the new fork or New User's PR.

I want every PR should first validate no matter if I raise PR or New User raise PR - this works fine
Next, i want only Delta changes should validate, so I used sgd in [Action](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/blob/be36a21462ea93174255751f3ac2a56a86175b1d/.github/workflows/PR_Validate.yml#L70) - this works fine if i raise PR. this is failing for other Github User raise PR.
At the moment I am testing for Other Github User, only modifying Apex class so sgd can check and validate only that particular class , so [here](https://github.com/Sarveshgithub/sfdc-lwc-lightning-datatable/pull/58/files) is the commit on class. this should validate. But unfortunately, this does not work for outside Github Users.

**Comment by iowillhoit** [comment]
Hello @Sarveshgithub, iI want to make sure I understand the issue: 
- When you open a PR on `sfdc-lwc-lightning-datatable`, the GHA action that uses `sgd:source:delta` works as expected
- However, when someone forks `sfdc-lwc-lightning-datatable` and opens a PR on that fork, the GHA action that uses `sgd:source:delta` fails? 

Is that correct? What error message do they receive?
