### ISSUE TITLE
ERROR running force:source:push:  Metadata API request failed: UNKNOWN_EXCEPTION: common.exception.SfdcSqlException 

### ISSUE THREAD

**Issue by amtrack** [forcedotcom/cli#1692]
We recently started seeing an intermittent error on pushing sources to Scratch Orgs:

context:
```
5052/7006 components deployed. 0 errors.
0/0 tests completed. 0 errors.

=== Status: InProgress
ERROR running force:source:push:  Metadata API request failed: UNKNOWN_EXCEPTION: common.exception.SfdcSqlException ORA-06550: line 1, column 13:
This almost certainly means your PL/SQL is out of sync with your Java. Rebuild and then run ./ant plsql.
ORA-06550: line 1, column 7:

PL/SQL: Statement ignored
This almost certainly means your PL/SQL is out of sync with your Java. Rebuild and then run ./ant plsql.
SQLException while executing plsql statement: {?=call cApiCursor.mark_used_auto(?)}(01g5400000qoeM9)

PLS-00306: wrong number or types of arguments in call to 'MARK_USED_AUTO'

This almost certainly means your PL/SQL is out of sync with your Java. Rebuild and then run ./ant plsql.
```

### Summary

Pushing to a Scratch Org in our CI.

### Steps To Reproduce:

This is an intermittent error and not reproducible every time.

### Expected result

push should succeed

### Actual result

push failed

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

bash

- If you are using `sfdx`
	- Run `sfdx --version`
	7.163.0

**Comment by iowillhoit** [comment]
Hello @amtrack, we are seeing Scratch Org performance issues since the Winter 23 preview. Can you try using the `release: preview` suggestion [here](https://github.com/forcedotcom/cli/issues/1690) and see if that works for you. Thanks!

**Comment by amtrack** [comment]
@iowillhoit Thanks, I've seen the announcement and I will probably give the preview a try.

Generally I prefer to stay on the current release for standard CI builds **except** I explicitly want to try something in the preview release.
For example: When someone uses a new feature in a PR, the CI build would be green and I'd potentially merge the PR but at the moment this could not be released to a package or deployed to production.

**Comment by iowillhoit** [comment]
You bet, and I completely agree. The performance issues are causing a lot of pain, just wanted to provide an option that could potentially keep you moving. At the very least you could rule out that this issue is indeed due to performance issues.

**Comment by amtrack** [comment]
@iowillhoit Thank you! 🙏
