### ISSUE TITLE
Possible Issue with Beta Packaging Promote

### ISSUE THREAD

**Issue by paulknebulaconsulting** [forcedotcom/cli#1693]
### Summary
I have installed the beta version of the packaging plugin using `sfdx plugins:install packaging`.

When using the new `force:package:beta:version:promote` command, it isn't accepting the -v flag to specify the dev hug org username or alias.

### Steps To Reproduce:
There is no default hub username in the local sfdx-config.json for the project.

    sfdx force:package:beta:version:promote -p 04txxxxxxxxxxxxxxx -v username@devhub.org

### Expected result

    Are you sure you want to release package version 04txxxxxxxxxxxxxxx? You can't undo this action. Release package (y/n)?:

### Actual result

    ERROR running force:package:beta:version:promote:  The Package Version Id 04txxxxxxxxxxxxxxxis invalid, as a corresponding Package Version Id was not found

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
PowerShell 7.2.6

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`

```
{
  "cliVersion": "sfdx-cli/7.165.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.3 (user)",
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.3 (core)",
    "community 2.0.0 (core)",
    "config 1.4.17 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.0.1 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.0 (core)",
    "packaging 1.6.0 (user)",
    "schema 2.1.1 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.12 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.3 (core)",
    "user 2.1.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
    "salesforce-alm 54.8.1 (core)"
  ],
  "osVersion": "Windows_NT 10.0.22000",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\Paul Kissick\\AppData\\Local\\sfdx\\client\\7.165.0-65b4bb0"
}
```

**Comment by iowillhoit** [comment]
Thanks for the issue @paulknebulaconsulting! I am seeing the same thing, I'll get an issue created to track this.

**Comment by WillieRuemmele** [comment]
Hi @paulknebulaconsulting thanks so much for trying out the packaging beta 😄 We really appreciate your feedback and hope the rest of your testing/usage of the `beta` commands goes well. 

I've put up a PR to fix this - thanks for being involved with the beta 🏆
