### ISSUE TITLE
running force:source:pull:  Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by magdalenaAtFevo** [forcedotcom/cli#1695]
### Summary

Failing to push or pull, get status or reset tracking. They all complete with that error. 

### System Information

- Which shell/terminal are you using? -bash

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- {
  "cliVersion": "sfdx-cli/7.166.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.3 (core)",
    "community 2.0.1 (core)",
    "config 1.4.17 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.0.1 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.0 (core)",
    "packaging 1.5.1 (core)",
    "schema 2.1.1 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.13 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.3 (core)",
    "user 2.1.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
    "@salesforce/sfdx-scanner 2.13.8 (user)",
    "salesforce-alm 54.8.1 (core)",
    "sfdx-plugin-prettier 1.0.5 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/{user}/.local/share/sfdx/client/7.166.1-12dce37"
}
### Additional information

_Feel free to attach a screenshot_.

**Comment by iowillhoit** [comment]
Hey @magdalenaAtFevo, we seen a few similar reports of this. Can you please try re-authenticating with your Scratch Org and see if that makes a difference? Thanks!

**Comment by magdalenaAtFevo** [comment]
@iowillhoit actually that did the trick. I should have replayed back on this thread. Thank you!
