### ISSUE TITLE
ERROR running force:mdapi:convert: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tsofindavid** [forcedotcom/cli#1699]
### Summary

I'm using sfdx to convert mdapi to source format.

### Steps To Reproduce:

1.Clone test source data here https://github.com/tsofindavid/sfdx-issue/tree/main.
2.Run sfdx force:mdapi:convert  --dev-debug -r ./path_to_sourceFolder

### Expected result
Successfully result without error.

### Actual result
ERROR running force:mdapi:convert:  Maximum call stack size exceeded 

### Additional information
This problem not reproduce on OS Windows.  

### System Information

- Linux(ubuntu) terminal.
- SFDX Verssion: sfdx-cli/7.166.1 linux-x64 node-v16.15.0

![image](https://user-images.githubusercontent.com/46505741/188477718-992ec985-02a7-4e4f-b8d8-6cc53a683e7e.png)
![image](https://user-images.githubusercontent.com/46505741/188476650-bec0f2db-432e-4ec7-b88b-4f13588a22e4.png)
![image](https://user-images.githubusercontent.com/46505741/188476686-38d9b3fa-6c09-4566-ae01-dbd4ce819d05.png)

**Comment by tsofindavid** [comment]
I understood what the problem is. You have the SWITCH module to enable debug logs. And this module, if the command has --dev-debug, will set env DEBUG = "*". In my case I am using sfdx-cli in child process and my server app has the same node-debug module and I am using the same env DEBUG="my-app*" value. As a result, we only got my logs, because the DEBUG value has my key, but sfdx started sending logs like this { sfdx force:mdapi:convert } &> /dev/null. And that's okay. But now I have disabled all debug logs in my application and this is a very bad case.

**Comment by cristiand391** [comment]
Hey, sorry for the late reply 👋🏼 

I remember seeing this with another command, I haven't reproduced with `force:mdapi:convert` from the logs it's seems it's the same cause:

the base command class used in the `sfdx` commands tries to pass a huge array to `node-bunyan` which then crashes:

https://github.com/salesforcecli/command/blob/main/src/ux.ts#L317
https://github.com/trentm/node-bunyan/blob/master/lib/bunyan.js#L1036

Over the coming weeks there will be some improvements to the CLI which might fix this so I'll leave the issue open until I can test it.

See: https://developer.salesforce.com/blogs/2022/12/big-improvements-coming-to-the-salesforce-cli
