### ISSUE TITLE
Retrieve Source from Org

### ISSUE THREAD

**Issue by cvraghu** [forcedotcom/cli#17]
Summary
"ERROR: Cannot read property 'fileName' of undefined." when trying to retrieve source from Org.

Steps To Reproduce:
Authorize a Sandbox Org
Right click package.xml and choose "Retrieve Source from Org"
Expected result
Source retrieved.

Actual result
ERROR: Cannot read property 'fileName' of undefined.

**Comment by shetzel** [comment]
@v-rachen - your vscode extensions are version 44.  I don't know what your CLI version or plugins are but I'm guessing they are also version 44.  You need to be on version 45 (aka, "pre-release") to retrieve/deploy LWC metadata.  The docs should describe how to do this.  E.g. sfdx plugins:install salesforcedx@pre-release is what you would do to get the pre-release version of the salesforcedx CLI plugin.

**Comment by dcarroll** [comment]
EDIT: Assuming the comment above is valid, ie this is related to LWC.

You will also need to have a Dev Hub that is on the pre-release servers (GS0). 
You can sign up for one here https://www.salesforce.com/form/signup/prerelease-spring19/

**Comment by clairebianchi** [comment]
Please let us know if this is still an issue and we can reopen this bug
