### ISSUE TITLE
"Outside of preview period" error message showing when still in preview period

### ISSUE THREAD

**Issue by Julian88Tex** [forcedotcom/cli#1707]
### Summary
Receiving below error message regarding preview period even though we are within preview period. Today is 9/8/22 and preview period ends 10/15/22 according to: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_version_selection.htm

```
Error: Failed to create scratch org: 

ERROR running force:org:create:  At this time, we are outside of the preview period. You can create only current release scratch 
orgs.
```

### Steps To Reproduce:

1. Add `"release": "Preview"` to `project-scratch-def.json` file
2. Create a scratch org using a command `sfdx force:org:create  -f orgs/project-scratch-def.json`

### Expected result

Scratch org is created.

### Actual result

Error is shown and no scratch org is created.

### System Information

```
{
  "cliVersion": "sfdx-cli/7.167.2",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.3 (core)",
    "community 2.0.1 (core)",
    "config 1.4.19 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.0.1 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.0 (core)",
    "packaging 1.6.0 (core)",
    "schema 2.1.1 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.13 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.3 (core)",
    "user 2.1.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.1 (core)",
    "sfdx-retrieve-deploy-companion 1.0.6 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/julianjoseph/.local/share/sfdx/client/7.167.2-93d663e"
}
```

Dev Hub instance: `NA210`

### Additional information

Reproduced locally and in a CI/CD build.

**Comment by Julian88Tex** [comment]
Was about to close this out because I got one to build but then had an error my second go around so it appears to be intermittent.

**Comment by toddhalfpenny** [comment]
I have been seeing this too.
I have tried various versions of the CLI (inc latest) to see if that helps.
I must have attempted well over 50 times and have not yet had success.

To note, as well as getting the error mentioned above I also receive this one.
```
{
  "status": 1,
  "name": "SfError",
  "message": "The request to create a scratch org failed with error code: VR-0003.",
  "exitCode": 1,
  "context": "OrgCreateCommand",
  "stack": "SfError: The request to create a scratch org failed with error code: VR-0003.\n    at Object.exports.checkScratchOrgInfoForErrors (/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/org/scratchOrgErrorCodes.js:41:15)\n    at Object.exports.pollForScratchOrgInfo (/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/org/scratchOrgInfoApi.js:237:35)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at ScratchOrgCreateCommand.execute (/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/org/scratchOrgCreateCommand.js:77:38)\n    at OrgCreateCommand.run (/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/commands/force/org/create.js:123:28)\n    at OrgCreateCommand._run (/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)\n    at Config.runCommand (/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at SfdxMain.run (/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at SfdxMain._run (/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at Object.run (/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli/dist/cli.js:162:47)",
  "warnings": [],
  "commandName": "OrgCreateCommand"
}
```

**Comment by rasmuszimmer** [comment]
seeing same

`{
  "status": 1,
  "name": "RemoteOrgSignupFailed",
  "message": "A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance",
  "exitCode": 1,
  "actions": [
    "See https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_signuprequest.htm for information on error code C-9999."
  ],
  "context": "Create",
  "stack": "RemoteOrgSignupFailed: A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance\n    at checkScratchOrgInfoForErrors (C:\\Users\\X5T\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\core\\lib\\org\\scratchOrgErrorCodes.js:72:19)\n    at async scratchOrgCreate (C:\\Users\\X5T\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\core\\lib\\org\\scratchOrgCreate.js:162:17)\n    at async Create.createScratchOrg (C:\\Users\\X5T\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\plugin-org\\lib\\commands\\force\\org\\create.js:200:68)\n    at async Create._run (C:\\Users\\X5T\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:89:40)\n    at async Config.runCommand (C:\\Users\\X5T\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\core\\lib\\config\\config.js:272:25)\n    at async run (C:\\Users\\X5T\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\core\\lib\\main.js:76:5)",
  "warnings": [],
  "commandName": "Create"
}
`

**Comment by Julian88Tex** [comment]
Looks like #1690 has some potential workarounds but no definite solution.

Starting from here: https://github.com/forcedotcom/cli/issues/1690#issuecomment-1232154386

**Comment by RodEsp** [comment]
Heya @Julian88Tex I'm going to close this issue since it seems to be the same performance root cause as the one you linked, we can track the resolution there. Lemme know if you disagree and we can re-open this if needed.

**Comment by Julian88Tex** [comment]
@RodEsp thanks for letting me know. If you'd like to close this one I'm fine with that but fwiw from my point of view this appears to be a separate issue with its own workarounds and potential resolution. I realize it may likely be realted or the same cause but it seems unique enough to justify it's own issue so that discussion can continue on it separately.

**Comment by RodEsp** [comment]
There's not much the CLI can do about intermittent errors like these coming back from the server due to performance issues so tracking a resolution for this past the linked issue above is out of the purview of this issues repo.

**Comment by toddhalfpenny** [comment]
I wonder if this issue 100% _is_ related to the capacity issues.
I've run the command well over 100 times now and haven't had a single scratch org created successfully.

**Comment by Julian88Tex** [comment]
@RodEsp got it. I realize this repo may not be related to the cause but it still may be a good place to discuss workarounds and solutions with the community.

**Comment by RodEsp** [comment]
@toddhalfpenny and every single time it fails with the "Outside of preview period" error?

**Comment by ImJohnMDaniel** [comment]
I am seeing this issue as well.

**Comment by RodEsp** [comment]
So it seems like there was an issue with a feature gate that was intermittently causing this error but it was patched last night in an emergency release. Please let me know if you continue to experience this going forward.

@W-11727723@

**Comment by toddhalfpenny** [comment]
> 

I also see this, probably half the time
’The request to create a scratch org failed with error code: VR-0003’

**Comment by RodEsp** [comment]
@toddhalfpenny that's a totally different issue. See [this](https://github.com/forcedotcom/cli/issues/1022#issuecomment-847063234).

**Comment by toddhalfpenny** [comment]
Thanks @RodEsp. That's interesting to know... _BUT_ the DevHub in use in these commands is always our PBO... which isn't on the pre-release version (instance EU41 just in case that helps),

My experience is that about half the time I see the `VR-0003` error, and the other half I see the `Outside of preview period` error.

**Comment by RodEsp** [comment]
EU41 got the same fix I mentioned before I closed this issue. Are you still seeing the `Outside of preview period` error today, @toddhalfpenny?

**Comment by toddhalfpenny** [comment]
Hi @RodEsp, I've run about 30 today, and not seen the `Outside of preview period` error today, so looks like this has been fixed in regards that error.

I still am not able to create any orgs though and get the `The request to create a scratch org failed with error code: VR-0003.` error back.
Looking at other issues (e.g #272) it seems that this is often to do with the release version of the devhub. In my case my devhub is our production PBO.

Any ideas what could be up here? Should I open a new issue?

**Comment by RodEsp** [comment]
@toddhalfpenny yes, please open a new issue, this one is about the `Outside of preview` error and that's been fixed. Although you'll probably be better served by going through the official support channels since the `VR-0003` error doesn't seem to be a CLI problem.
