### ISSUE TITLE
source:convert  source:push sfdx source command "Path" variable not a string :: Misleading error message

### ISSUE THREAD

**Issue by krishnas2** [forcedotcom/cli#171]
### Summary

_If we miss out a static resource file and have resource meta xml then we get this error  _.

### Steps To Reproduce:

1. check for any meta-xml references and delete the actual file and continue to have resource meta xml.
2. try source:convert or source:push or any command you will land in error "Path" variable not a string 

### Expected result

_Probably a a better error message is expected_.

**Comment by clairebianchi** [comment]
@krishnas2  can you run with --debug and provide us with the output?

**Comment by krishnas2** [comment]
@clairebianchi here is how this issue can be reproduced.

1. cloned a sample repo and added a simple randomimage as static resource and able to `source:convert`
![ramdomimage](https://user-images.githubusercontent.com/12509913/64906886-07742e00-d72f-11e9-8dd7-c020896aedba.PNG)

2. Now,  **if i remove the actual file and continue to have meta-xml file.** i hit the path error .
**The "path" argument must be of type string. Received type undefined**
![ramdomimagefailure](https://user-images.githubusercontent.com/12509913/64906894-2377cf80-d72f-11e9-819b-0469f9a5bc80.PNG)

Didn't understand what you meant by run with --debug .tried these
![misunderstooddebug](https://user-images.githubusercontent.com/12509913/64906905-4efaba00-d72f-11e9-947b-7f0b487360df.PNG)

**Comment by mshanemc** [comment]
This got fixed as part of the new source plugin.  There error now says, 
```
ERROR running force:source:convert:  /Users/shane.mclaughlin/eng/repros/171/force-app/main/default/staticresources/sample_data_brokers.resource-meta.xml: Expected source files for type 'StaticResource'
```

so you can see which static resource you're missing files for.
