### ISSUE TITLE
Be able to check the status of running deployment without JobId

### ISSUE THREAD

**Issue by Renan-Mastropaolo** [forcedotcom/cli#1712]
**Is your feature request related to a problem? Please describe.**
Currently we have one CI/CD job for each non-prod environment we deploy to, and for each new commit to our branch, a new pipeline is created.
Each job consists in 4 deployment, one for pre destructive package, a second for the full components deployment except for reports/reportTypes and dashboards, a third one for only reports/reportTypes and dashboards, and the last one for post destructive.
The problem is, if person 1 makes a commit, and during the full components deploy of job 1, person 2 makes another commit, a second job is created to the same environment, and the pre destructive deployment starts and fails, because we already have an deployment in progress (job 1). We would like to check if there is already an deployment running on the environment, and if there is, skip this deployment.

**What are you trying to do**
Run sfdx force:source:deploy:report (or mdapi equivalent) -u CONNECTION without passing an jobId on -i, and as a result get the deployment status of current running deployment

**Describe the solution you'd like**
when we run the deploy:report command, sfdx should return the deployment status of current running deployment, without an jobId

**Describe alternatives you've considered**
There is one workaround for this, run an SOQL query thru sfdx and handle the result there, but it is not a very good solution.

**Comment by AllanOricil** [comment]
@Renan-Mastropaolo could you explain why the second job fails? Why isn't it added to the queue?

**Comment by Renan-Mastropaolo** [comment]
@AllanOricil the second job fails after some time. It indeed is added to the queue, but after some time waiting, the deployment fails with message "LIMIT_EXCEEDED: Try deploying again. Your deployment exceeded its maximum retry limit. If you keep seeing this error, please contact Salesforce Customer Support."

**Comment by AllanOricil** [comment]
How exactly skiping a deployment would solve your issue?

"We would like to check if there is already an deployment running on the environment, and if there is, skip this deployment."

Could you share more details of your automated deployment process? I really don't see how this feature request would be useful when there is already a queue organizing deployments.

**Comment by Renan-Mastropaolo** [comment]
We use shared environments for UAT with other teams and other repos, so we would like to check, on the running CI/CD job, if there is already an deployment running on UAT and wait until this deploy is done to start a new one.

**Comment by AllanOricil** [comment]
> We use shared environments for UAT with other teams and other repos, so we would like to check, on the running CI/CD job, if there is already an deployment running on UAT and wait until this deploy is done to start a new one.

Why would you need to manage the queue by yourself if it is already managed by SF? There is no way a second deploy job can start in a Sandbox before the current one is done.


1 - Team 1 enqueues a Deploy Validation to Sandbox X
2 - Team 2 enqueues a Deploy Validation to Sandbox X
3 - Team 1 Deploy Validation fails on Sandbox X
4 - Team 2 Deploy Validation Starts on Sandbox X
5 - Team 1 fixes issues and enqueues a new Deploy Validation job on Sandbox X
6 - Team 2 Deploy Validation succeeds on Sandbox X
7 - Team 2 enqueues a Deploy job on Sandbox X ( this job just runs a Quick Deploy using the Validaiton Job ID)
8 - Team 1 Deploy Validation succeeds on Sandbox X
9 - Team 1 enqueues a Deploy Job on Sandbox X

**Comment by Renan-Mastropaolo** [comment]
But in our case, if Team 2 enqueues a Deploy to Salesforce, this deployment fails before start with error message "LIMIT_EXCEEDED: Try deploying again. Your deployment exceeded its maximum retry limit. If you keep seeing this error, please contact Salesforce Customer Support."
And for each CI/CD job we run 4 deployments to Salesforce: Pre deployment destructive, components deployment, Reports/ReportTypes/Dashboards deployment, Post deployment destructive. So in your scenario our flow would be something like that:

1. Team 1 pushes a commit (commit 1) to Team1's git repo.
2. CI/CD creates the job for commit 1, pre-deployment destruction starts on Sandbox X.
3. Team 2 pushes a commit (commit 2) to Team2's git repo.
4. Commit 1 pre-destruction ends with success, components deployment starts for commit 1 on Sandbox X.
5. CI/CD creates the job for commit 2, pre-deployment destruction starts on Sandbox X.
6. Commit 2's pre-deployment destruction is enqueued on Sandbox X
7. Components deployment for commit 1 is still running on Sandbox X.
8. Commit 2's pre-deployment destruction fails with error message "LIMIT_EXCEEDED: Try deploying again. Your deployment exceeded its maximum retry limit. If you keep seeing this error, please contact Salesforce Customer Support."
9. CI/CD job for commit 2 fails and no more deployments are created.
10. Team 1b pushed a commit (commit 3) to Team1's git repo.
11. CI/CD creates the job for commit 3, pre-deployment destruction is enqueued on Sandbox X.
12. Commit1's Components deployment end successfully, commit3's pre-deployment destruction starts, commit1's Report/ReportTypes/Dashboards deployment is enqueued.
13. Commit3's pre-deployment destruction is still running.
14. Commit1's Report/ReportTypes/Dashboards deployment fails with error message "LIMIT_EXCEEDED: Try deploying again. Your deployment exceeded its maximum retry limit. If you keep seeing this error, please contact Salesforce Customer Support."
15. No more developers commiting, Commit 3 job runs successfully.

**Comment by daveespo** [comment]
It sounds like your CI system should do a better job of orchestrating concurrent builds -- this doesn't seem like a problem specific to Salesforce. It's the common problem of having a single destination environment and multiple commits that need to get there. 

For example, on GH Actions, you can define a concurrency property to protect against multiple jobs running at the same time:

https://docs.github.com/en/actions/using-jobs/using-concurrency

**Comment by AllanOricil** [comment]
@Renan-Mastropaolo take a different approach. Instead of deploying only what each team has developed, try to deploy everything that hasn't been deployed yet. Every time a deployment to a sandbox succeeds, create a tag for saving the state of that sandbox (it is like a checkpoint). When I say a "deployment" I mean that all steps run succesfully for that particular commit, and not SF deployments. If one of the steps fails, your tag isn't updated for that environment, which means the next commit will try again to deploy those changes. This next commit can be just a fix for what went wrong in the previous deployment, or a new feature from another team.

You can use this sfdx plugin to compute diffs between checkpoint tags: https://github.com/scolladon/sfdx-git-delta
To ensure your SF pre and post deployments steps are scheduled properly in the right order, and not in between jobs from different commits, use these two features from this sfdx command 
https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_deploy

![image](https://user-images.githubusercontent.com/55927613/193305123-1cb02357-ca18-45e8-9545-0365bcbbfb71.png)

**Comment by Renan-Mastropaolo** [comment]
Thanks @AllanOricil and @daveespo for this tips.
I get that this is not an error on sfdx-cli side and more related to how our pipelines were built in the first place.
Just thought about this feature because it would fit well in our current implementation of CI/CD and deployment orchestration.

**Comment by shetzel** [comment]
Thanks for posting and thanks for the responses Allan and Dave.  The team is in agreement with how Allan and Dave responded so this is not a feature that would be prioritized.  If you want to keep your CI/CD as is then your best bet is what you mentioned already in your issue description; the soql command.  You might want to explore using sandbox source tracking as another option.
