### ISSUE TITLE
Any cli command return read ECONNRESET

### ISSUE THREAD

**Issue by HBouch** [forcedotcom/cli#1717]
### Summary

any cli command, including update returns Error: read ECONNRESET.

### Log :

  config reading core plugin C:\Program Files\sfdx\client +0ms
  config loadJSON C:\Program Files\sfdx\client\package.json +0ms
  config loadJSON C:\Program Files\sfdx\client\oclif.manifest.json +0ms
  config:sfdx-cli using manifest from C:\Program Files\sfdx\client\oclif.manifest.json +0ms
  config reading user plugins pjson C:\Users\hamza\AppData\Local\sfdx\package.json +0ms
  config loadJSON C:\Users\hamza\AppData\Local\sfdx\package.json +0ms
  config loading plugins [
  '@oclif/plugin-command-snapshot',
  '@salesforce/plugin-release-management'
] +1ms
  config loadJSON C:\Program Files\sfdx\client\package.json +0ms
  config loadJSON C:\Program Files\sfdx\client\package.json +0ms
  config loadJSON C:\Program Files\sfdx\package.json +0ms
  config loadJSON C:\Program Files\sfdx\package.json +0ms
  config loadJSON C:\Program Files\package.json +0ms
  config loadJSON C:\Program Files\package.json +0ms
  config loadJSON C:\package.json +0ms
  config loadJSON C:\package.json +0ms
(node:6836) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'dev',
  root: 'C:\\Program Files\\sfdx\\client',
  name: '@oclif/plugin-command-snapshot'
}
module: @oclif/core@1.16.0
task: loadPlugins
plugin: sfdx-cli
root: C:\Program Files\sfdx\client
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Error Plugin: sfdx-cli: could not find package.json with {
  type: 'dev',
  root: 'C:\\Program Files\\sfdx\\client',
  name: '@oclif/plugin-command-snapshot'
}
    at Plugin.load (C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\plugin.js:106:19)
    at async C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\config.js:438:17
    at async Promise.all (index 0)
    at async Config.loadPlugins (C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\config.js:426:9)
    at async Config.loadDevPlugins (C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\config.js:160:21)
    at async Config.load (C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\config.js:139:9)
    at async Object.run (C:\Program Files\sfdx\client\dist\cli.js:106:13)
module: @oclif/core@1.16.0
task: loadPlugins
plugin: sfdx-cli
root: C:\Program Files\sfdx\client
See more details with DEBUG=*
  config loading plugins [
  '@oclif/plugin-autocomplete',
  '@oclif/plugin-commands',
  '@oclif/plugin-help',
  '@oclif/plugin-version',
  '@oclif/plugin-not-found',
  '@oclif/plugin-plugins',
  '@oclif/plugin-update',
  '@oclif/plugin-warn-if-update-available',
  '@oclif/plugin-which',
  '@salesforce/plugin-alias',
  '@salesforce/plugin-apex',
  '@salesforce/plugin-auth',
  '@salesforce/plugin-config',
  '@salesforce/plugin-community',
  '@salesforce/plugin-custom-metadata',
  '@salesforce/plugin-data',
  '@salesforce/plugin-generator',
  '@salesforce/plugin-info',
  '@salesforce/plugin-limits',
  '@salesforce/plugin-org',
  '@salesforce/plugin-packaging',
  '@salesforce/plugin-source',
  '@salesforce/plugin-schema',
  '@salesforce/plugin-telemetry',
  '@salesforce/plugin-templates',
  '@salesforce/plugin-trust',
  '@salesforce/plugin-user',
  '@salesforce/plugin-signups',
  '@salesforce/sfdx-plugin-lwc-test',
  'salesforce-alm'
] +9ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@oclif\plugin-autocomplete +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-autocomplete\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@oclif\plugin-commands +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-commands\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@oclif\plugin-update +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-update\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-alias +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-alias\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-community +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-community\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-custom-metadata +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-custom-metadata\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-telemetry +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-telemetry\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-templates +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-templates\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@oclif\plugin-help +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-help\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@oclif\plugin-version +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-version\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@oclif\plugin-not-found +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-not-found\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@oclif\plugin-plugins +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-plugins\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@oclif\plugin-warn-if-update-available +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-warn-if-update-available\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@oclif\plugin-which +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-which\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-apex +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-apex\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-auth +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-auth\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-config +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-config\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-data +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-data\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-generator +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-generator\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-info +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-info\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-limits +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-limits\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-org +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-org\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-packaging +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-packaging\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-source +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-source\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-schema +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-schema\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-trust +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-trust\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-user +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-user\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-signups +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-signups\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\@salesforce\sfdx-plugin-lwc-test +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\sfdx-plugin-lwc-test\package.json +0ms
  config reading core plugin C:\Program Files\sfdx\client\node_modules\salesforce-alm +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\salesforce-alm\package.json +0ms
(node:6836) Error Plugin: sfdx-cli: could not find package.json with {
  type: 'dev',
  root: 'C:\\Program Files\\sfdx\\client',
  name: '@salesforce/plugin-release-management'
}
module: @oclif/core@1.16.0
task: loadPlugins
plugin: sfdx-cli
root: C:\Program Files\sfdx\client
See more details with DEBUG=*
Error Plugin: sfdx-cli: could not find package.json with {
  type: 'dev',
  root: 'C:\\Program Files\\sfdx\\client',
  name: '@salesforce/plugin-release-management'
}
    at Plugin.load (C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\plugin.js:106:19)
    at async C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\config.js:438:17
    at async Promise.all (index 1)
    at async Config.loadPlugins (C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\config.js:426:9)
    at async Config.loadDevPlugins (C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\config.js:160:21)
    at async Config.load (C:\Program Files\sfdx\client\node_modules\@oclif\core\lib\config\config.js:139:9)
    at async Object.run (C:\Program Files\sfdx\client\dist\cli.js:106:13)
module: @oclif/core@1.16.0
task: loadPlugins
plugin: sfdx-cli
root: C:\Program Files\sfdx\client
See more details with DEBUG=*
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-autocomplete\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-commands\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-update\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-alias\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-custom-metadata\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-community\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-templates\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-telemetry\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-help\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-version\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-not-found\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-plugins\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-warn-if-update-available\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@oclif\plugin-which\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-apex\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-config\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-auth\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-info\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-data\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-org\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-limits\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-generator\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-packaging\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-source\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-schema\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-trust\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-user\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\sfdx-plugin-lwc-test\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-signups\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\salesforce-alm\oclif.manifest.json +0ms
  config loadJSON C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-generator\.oclif.manifest.json +0ms
  config:@oclif/plugin-autocomplete using manifest from C:\Program Files\sfdx\client\node_modules\@oclif\plugin-autocomplete\oclif.manifest.json +0ms
  config:@oclif/plugin-update using manifest from C:\Program Files\sfdx\client\node_modules\@oclif\plugin-update\oclif.manifest.json +0ms
  config:@oclif/plugin-commands using manifest from C:\Program Files\sfdx\client\node_modules\@oclif\plugin-commands\oclif.manifest.json +0ms
  config:@salesforce/plugin-custom-metadata using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-custom-metadata\oclif.manifest.json +0ms
  config:@salesforce/plugin-community using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-community\oclif.manifest.json +0ms
  config:@salesforce/plugin-alias using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-alias\oclif.manifest.json +0ms
  config:@salesforce/plugin-telemetry using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-telemetry\oclif.manifest.json +0ms
  config:@salesforce/plugin-templates using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-templates\oclif.manifest.json +0ms
  config:@oclif/plugin-not-found using manifest from C:\Program Files\sfdx\client\node_modules\@oclif\plugin-not-found\oclif.manifest.json +0ms
  config:@oclif/plugin-help using manifest from C:\Program Files\sfdx\client\node_modules\@oclif\plugin-help\oclif.manifest.json +0ms
  config:@oclif/plugin-which using manifest from C:\Program Files\sfdx\client\node_modules\@oclif\plugin-which\oclif.manifest.json +0ms
  config:@oclif/plugin-warn-if-update-available using manifest from C:\Program Files\sfdx\client\node_modules\@oclif\plugin-warn-if-update-available\oclif.manifest.json +0ms
  config:@oclif/plugin-version using manifest from C:\Program Files\sfdx\client\node_modules\@oclif\plugin-version\oclif.manifest.json +0ms
  config:@salesforce/plugin-config using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-config\oclif.manifest.json +0ms
  config:@salesforce/plugin-apex using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-apex\oclif.manifest.json +0ms
  config:@salesforce/plugin-auth using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-auth\oclif.manifest.json +0ms
  config:@salesforce/plugin-info using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-info\oclif.manifest.json +0ms
  config:@oclif/plugin-plugins using manifest from C:\Program Files\sfdx\client\node_modules\@oclif\plugin-plugins\oclif.manifest.json +0ms
  config:@salesforce/plugin-data using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-data\oclif.manifest.json +0ms
  config:@salesforce/plugin-org using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-org\oclif.manifest.json +0ms
  config:@salesforce/plugin-limits using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-limits\oclif.manifest.json +0ms
  config:@salesforce/plugin-packaging using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-packaging\oclif.manifest.json +0ms
  config:@salesforce/plugin-schema using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-schema\oclif.manifest.json +0ms
  config:@salesforce/plugin-source using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-source\oclif.manifest.json +0ms
  config:@salesforce/plugin-trust using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-trust\oclif.manifest.json +0ms
  config:@salesforce/plugin-signups using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-signups\oclif.manifest.json +0ms
  config:@salesforce/plugin-user using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-user\oclif.manifest.json +0ms
  config:@salesforce/sfdx-plugin-lwc-test using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\sfdx-plugin-lwc-test\oclif.manifest.json +0ms
  config:salesforce-alm using manifest from C:\Program Files\sfdx\client\node_modules\salesforce-alm\oclif.manifest.json +0ms
  config:@salesforce/plugin-generator using manifest from C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-generator\.oclif.manifest.json +0ms
  config config done +87ms
  sfdx                        OS: +0ms
  sfdx                  platform: win32 +0ms
  sfdx              architecture: x64 +1ms
  sfdx                   release: 10.0.25201 +0ms
  sfdx                     shell: cmd.exe +0ms
  sfdx                      NODE: +0ms
  sfdx                   version: 16.17.0 +0ms
  sfdx                       CLI: +0ms
  sfdx                   version: 7.168.0 +0ms
  sfdx                   channel: stable +0ms
  sfdx                       bin: sfdx +0ms
  sfdx                      data: C:\Users\hamza\AppData\Local\sfdx +1ms
  sfdx                     cache: C:\Users\hamza\AppData\Local\sfdx +0ms
  sfdx                    config: C:\Users\hamza\AppData\Local\sfdx +0ms
  sfdx                       ENV: +0ms
  sfdx              NODE_OPTIONS: <not set> +0ms
  sfdx   SFDX_AUTOUPDATE_DISABLE: true +0ms
  sfdx              SFDX_BINPATH: C:\Program Files\sfdx\bin\\sfdx.cmd +0ms
  sfdx        SFDX_COMPILE_CACHE: <not set> +0ms
  sfdx   SFDX_DISABLE_AUTOUPDATE: true +1ms
  sfdx                  SFDX_ENV: development +0ms
  sfdx            SFDX_INSTALLER: <not set> +0ms
  sfdx    SFDX_LAZY_LOAD_MODULES: true +0ms
  sfdx         SFDX_NPM_REGISTRY: <not set> +0ms
  sfdx           SFDX_REDIRECTED: <not set> +0ms
  sfdx              SFDX_S3_HOST: <not set> +0ms
  sfdx  SFDX_UPDATE_INSTRUCTIONS: Use "npm update --global sfdx-cli" to update npm-based installations. +0ms
  sfdx                      ARGS: +0ms
  sfdx                         0: C:\Program Files\sfdx\client\bin\node.exe +0ms
  sfdx                         1: C:\Program Files\sfdx\client\bin\run +0ms
  sfdx                         2: update +1ms
  lazy-require loading type cache from C:\Users\hamza\AppData\Local\sfdx\module-types.json +0ms
  lazy-require loaded type cache +0ms
  lazy-require parsing type cache +0ms
  lazy-require parsed type cache +1ms
  lazy-require enabled +0ms
  config start init hook +6ms
  sfdx:@oclif/plugin-update:hooks:init start (require) C:\Program Files\sfdx\client\node_modules\@oclif\plugin-update\lib\hooks\init.js +0ms
  sfdx:@salesforce/plugin-telemetry:hooks:init start (require) C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-telemetry\lib\hooks\telemetryInit.js +0ms
  sfdx:@oclif/plugin-warn-if-update-available:hooks:init start (require) C:\Program Files\sfdx\client\node_modules\@oclif\plugin-warn-if-update-available\lib\hooks\init\check-update.js +0ms
  sfdx:@salesforce/plugin-config:hooks:init start (require) C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-config\lib\hooks\init\load_config_meta.js +0ms
  sf:core TRACE Setup child 'plugin-config:load_config_meta' logger instance +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for sfdx-cli +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @oclif/plugin-autocomplete +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @oclif/plugin-update +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @oclif/plugin-commands +1ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-custom-metadata +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-community +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-alias +1ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-telemetry +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-templates +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @oclif/plugin-not-found +1ms
  sf:plugin-config:load_config_meta INFO No config meta found for @oclif/plugin-help +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @oclif/plugin-which +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @oclif/plugin-warn-if-update-available +1ms
  sf:plugin-config:load_config_meta INFO No config meta found for @oclif/plugin-version +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-config +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-apex +1ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-auth +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-info +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @oclif/plugin-plugins +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-data +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-org +1ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-limits +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-packaging +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-schema +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-source +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-trust +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-signups +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-user +1ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/sfdx-plugin-lwc-test +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for salesforce-alm +0ms
  sf:plugin-config:load_config_meta INFO No config meta found for @salesforce/plugin-generator +0ms
  sfdx:@oclif/plugin-update:hooks:init done +786ms
  sfdx:@salesforce/plugin-telemetry:hooks:init done +736ms
  sfdx:@salesforce/plugin-config:hooks:init done +764ms
  sfdx:@oclif/plugin-warn-if-update-available:hooks:init done +768ms
  config init hook done +837ms
  config runCommand update [] +1ms
  config:@oclif/plugin-update (require) C:\Program Files\sfdx\client\node_modules\@oclif\plugin-update\lib\commands\update.js +865ms
  config start prerun hook +20ms
  sfdx:@salesforce/plugin-telemetry:hooks:prerun start (require) C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-telemetry\lib\hooks\telemetryPrerun.js +0ms
  sf:core TRACE Setup child 'Config' logger instance +82ms
  sf:core TRACE Setup child 'Config' logger instance +1ms
  sf:Config INFO Reading config file: C:\Users\hamza\.sf\config.json +0ms
  sf:Config INFO Reading config file: C:\Users\hamza\.sf\config.json +9ms
  sf:core TRACE Setup child 'core:config' logger instance +18ms
  sfdx:telemetry@2.0.0 Usage acknowledgement file already exists +0ms
  sfdx:telemetry@2.0.0 Using telemetry logging file C:\Users\hamza\AppData\Local\Temp\sfdx-telemetry\telemetry-9f5bbd06aa36e4175eefcc8180eaa5aee61b554a.log +1ms
  sfdx:telemetry@2.0.0 Not in a sfdx project, using current working directory +6ms
  sfdx:telemetry@2.0.0 Setting up process exit handler +0ms
  sfdx:@salesforce/plugin-telemetry:hooks:prerun done +49ms
  config prerun hook done +53ms
  sfdx:update init version: @oclif/core@1.16.0 argv: [] +0ms
  http → GET https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-win32-x64-buildmanifest
  http   user-agent: 'sfdx-cli/7.168.0 win32-x64 node-v16.17.0' +0ms
  http Error: read ECONNRESET
  http     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) +123ms
  http → GET https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-win32-x64-buildmanifest
  http   user-agent: 'sfdx-cli/7.168.0 win32-x64 node-v16.17.0' +299ms
  http Error: read ECONNRESET
  http     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) +26ms
  http → GET https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-win32-x64-buildmanifest
  http   user-agent: 'sfdx-cli/7.168.0 win32-x64 node-v16.17.0' +429ms
  http Error: read ECONNRESET
  http     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) +24ms
  http → GET https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-win32-x64-buildmanifest
  http   user-agent: 'sfdx-cli/7.168.0 win32-x64 node-v16.17.0' +856ms
  http Error: read ECONNRESET
  http     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) +24ms
  http → GET https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-win32-x64-buildmanifest
  http   user-agent: 'sfdx-cli/7.168.0 win32-x64 node-v16.17.0' +2s
  http Error: read ECONNRESET
  http     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) +25ms
  http → GET https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-win32-x64-buildmanifest
  http   user-agent: 'sfdx-cli/7.168.0 win32-x64 node-v16.17.0' +3s
  http Error: read ECONNRESET
  http     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) +24ms
sfdx-cli: Updating CLI... !
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
  lazy-require saving type cache to C:\Users\hamza\AppData\Local\sfdx\module-types.json +8s
  lazy-require no changes to save +1ms
  sfdx:telemetry@2.0.0 Spawning "C:\Program Files\sfdx\client\bin\node.exe C:\Program Files\sfdx\client\node_modules\@salesforce\plugin-telemetry\processes\upload C:\Users\hamza\AppData\Local\sfdx C:\Users\hamza\AppData\Local\Temp\sfdx-telemetry\telemetry-9f5bbd06aa36e4175eefcc8180eaa5aee61b554a.log" +7s

### Additional Info :
I am on Windows 11 insider edition

**Comment by cristiand391** [comment]
@HBouch this seems to be an issue with your Windows machine/environment, are you behind a firewall or proxy?

**Comment by HBouch** [comment]
Hey, sorry for the delay, no I am not behind any firewall or proxy, it used to work on the same machine

**Comment by vc4u** [comment]
@HBouch Were you able to get past this error? I suddenly started getting this error today on my machine. it was working fine previously. Now, no CLI command work except retrieving org list which also fails for all orgs showing Org Connection status as "ECONNRESET" or "DomainNotFoundError". Got any pointers?

**Comment by HBouch** [comment]
hey @vc4u, I dug deep into it and found it is some sort of TLS issue. My machine was running Windows 11 insider for a while and after multiple "dirty" updates things just started to break down. After a clean install of Windows everything just went back to normal, hope this helps !
