### ISSUE TITLE
Deploying Entitlement Settings file to Winter' 20 org fails with invalid property

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#172]
### Summary

I have an Entitlement.settings file from API 46.0 (https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_entitlementsettings.htm). When trying to deploy that file into an organization in API 47.0 I receive an error of unsupported property.

Currently, the file does not contain that property.

I have tried deploying it forcing to use the latest API (with --apiversion=47.0), but with no success, also adding the property with the same result

### Steps To Reproduce:

1.  Create an entitlement settings file.
1.  Deploy it to API 47.0 organization

### Expected result

Returning error when trying to deploy the property to API 46.0 organization or no returning error when deploying to 47.0

### Actual result

Error when deploying in API 46.0 and API 47.0 org

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**: sfdx-cli/7.23.1-ced0ec4940 linux-x64 node-v10.15.3

**SFDX plugin Version**: 
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.13.1
├─ force-language-services 46.18.0
└─ salesforce-alm 46.17.0

sfdx-cli 7.23.1 (core)

**OS and version**: WSL

**Comment by mnunezdm** [comment]
After some further testing...

We have noticed that when converting to mdapi format, and specifying the api version in the package xml whe manged to deploy without errors.

These are the contents of both two files

package.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
        <types>
                <members>*</members>
                <name>Settings</name>
        </types>
        <version>47.0</version>
</Package>
```

Entitlements.settings

```xml
<?xml version="1.0" encoding="UTF-8"?>
<EntitlementSettings xmlns="http://soap.sforce.com/2006/04/metadata">
    <assetLookupLimitedToActiveEntitlementsOnAccount>false</assetLookupLimitedToActiveEntitlementsOnAccount>
    <assetLookupLimitedToActiveEntitlementsOnContact>false</assetLookupLimitedToActiveEntitlementsOnContact>
    <assetLookupLimitedToSameAccount>false</assetLookupLimitedToSameAccount>
    <assetLookupLimitedToSameContact>false</assetLookupLimitedToSameContact>
    <enableEntitlementVersioning>true</enableEntitlementVersioning>
    <enableEntitlements>true</enableEntitlements>
    <entitlementLookupLimitedToActiveStatus>false</entitlementLookupLimitedToActiveStatus>
    <entitlementLookupLimitedToSameAccount>false</entitlementLookupLimitedToSameAccount>
    <entitlementLookupLimitedToSameAsset>false</entitlementLookupLimitedToSameAsset>
    <entitlementLookupLimitedToSameContact>false</entitlementLookupLimitedToSameContact>
</EntitlementSettings>
```

So seems to be a problem with sfdx force:source:deploy, that does not take into consideration the API version specified

**Comment by clairebianchi** [comment]
@mnunezdm can you send the structure of the command you are using?
Also, have you installed the pre-release version of the CLI? Pre-Release uses the next version of the API.

To install: 

`sfdx plugins:install salesforcedx@pre-release`

Make sure that you have the pre-release version.

```
sfdx plugins --core
salesforcedx 47.0.1-xx
```
When we officially release v47 on October 12, 2019, uninstall the pre-release, then update the CLI.

```
sfdx plugins:uninstall salesforcedx
sfdx update
```

**Comment by mnunezdm** [comment]
I just managed to work around this error in workspaces using source format, changing the API version of the sfdx-project.json to 47.0 seems to allow deploying the Entitlement.settings file

Still strange as we are not using any unsupported tag in our Entitlement.settings file
