### ISSUE TITLE
postorgcreate hook will not be fired by force:org:create

### ISSUE THREAD

**Issue by gitfish** [forcedotcom/cli#1722]
### Summary

After the changes via PR https://github.com/salesforcecli/plugin-org/pull/391, `force:org:create` will no longer invoke the postorgcreate hook, as the lifecycleEventNames prop has been removed and no lifecycle listener gets registered here: https://github.com/salesforcecli/command/blob/9a20f1f57bb55c2929520510ef6bffd5786482d5/src/sfdxCommand.ts#L586

### Steps To Reproduce:

Run `force:org:create` with a plugin that provides a `postorgcreate` hook.

### Expected result

The `postorgcreate` hook runs when running the `force:org:create` command

### Actual result

The `postorgcreate` hook DOES NOT run when running the `force:org:create` command

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

zsh

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here

{
  "cliVersion": "sfdx-cli/7.169.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.14.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.5 (core)",
    "community 2.0.1 (core)",
    "config 1.4.19 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.1.0 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.3 (core)",
    "packaging 1.9.1 (core)",
    "schema 2.1.3 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.13 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.4 (core)",
    "user 2.1.2 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.1 (core)",
    "sfdx-bfs-plugin 2.2.0-10 (link) /usr/local/lib/node_modules/sfdx-bfs-plugin"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/usr/local/lib/node_modules/sfdx-cli"
}

### Additional information

_Feel free to attach a screenshot_.

**Comment by cristiand391** [comment]
Alright, I merged your PR and the fix should be included in the RC next Thursday, sorry we missed your comment after merging the other PR.
We will keep this issue open until it's is promoted to latest on 11/17, thanks for contributing! :)
