### ISSUE TITLE
Any sfdx command fails after npm update

### ISSUE THREAD

**Issue by Kruckemeyer** [forcedotcom/cli#1728]
### Summary

After installing the latest version of the sfdx-cli from npm, any sfdx command is going to fail with the same error message. After this happened on two different machines with the same pattern I thought it might be an issue.

### Steps To Reproduce:
```
npm install -g sfdx-cli
sfdx --version
```

### Expected result
$ sfdx --version
sfdx-cli/7.169.1 win32-x64 node-v14.17.0

### Actual result
$ sfdx --version
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'node:os'
Require stack:
- C:\Users\user\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\plugin-version\lib\commands\version.js
- C:\Users\user\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\plugin-version\lib\index.js
- C:\Users\user\AppData\Roaming\npm\node_modules\sfdx-cli\dist\cli.js
- C:\Users\user\AppData\Roaming\npm\node_modules\sfdx-cli\bin\run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\plugin-version\lib\commands\version.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\plugin-version\\lib\\commands\\version.js',
    'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\plugin-version\\lib\\index.js',
    'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\dist\\cli.js',
    'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\bin\\run'
  ]
}

### System Information

- Which shell/terminal are you using? 
bash

- If you are using `sfdx`
	- Run `sfdx version --verbose --json` --> fails
same output like in the actual result

- If you are using `sf`
	- Run `sf version --verbose --json` --> works
$ sf version --verbose --json
@salesforce/cli/1.9.1 win32-x64 node-v14.17.0

**Comment by cristiand391** [comment]
Hey @Kruckemeyer 👋🏼 

This is a node issue, fixed in v14.18.0. if you update to the latest v14 release sfdx should work again.

See node release notes: https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V14.md#2021-09-28-version-14180-fermium-lts-targos

> [[f9f9389d83](https://github.com/nodejs/node/commit/f9f9389d83)] - (SEMVER-MINOR) module: add support for node:‑prefixed require(…) calls (ExE Boss) https://github.com/nodejs/node/pull/37246

**Comment by Kruckemeyer** [comment]
Hey @cristiand391,
thanks for your super fast reply. sfdx is running fine with a newer nodejs version.
