### ISSUE TITLE
CLI retrieve CustomObjectTranslation Manage Package layout Bug

### ISSUE THREAD

**Issue by rubicn** [forcedotcom/cli#1729]
### Summary

CLI retrieve CustomObjectTranslation Manage Package layout

### Steps To Reproduce:

cli retrieve CustomObjectTranslation with  Layout is missing the namespace

what we got: <layout>Layout Name</layout>
what we should got: <layout>NAMESPACE__Layout Name</layout>

Please fix

**Comment by shetzel** [comment]
@rubicn - please fill out the requested information to get help with this.  Easiest way is to run `sf doctor` and provide the information generated.  What is the exact command you used to retrieve?
