### ISSUE TITLE
Different namespace between sfdx force:apex:class:create and sfdx force:source:pull

### ISSUE THREAD

**Issue by kvor** [forcedotcom/cli#173]
### Summary

Namespace of xml  file changes if we create it using sfdx, push it to scratch org, modify it and pull it back.

### Steps To Reproduce:

1.  Create a class: sfdx force:apex:class:create -n FooClass
1.  Push it to scratch org: sfdx force:source:push
1.  Modify FooClass in scratch org
1.  Pull sources from scratch org: sfdx force:source:pull

### Expected result

Metadata file when was create was this:
```<?xml version="1.0" encoding="UTF-8"?>
<ApexClass xmlns="urn:metadata.tooling.soap.sforce.com" fqn="BarClass">
    <apiVersion>46.0</apiVersion>
    <status>Active</status>
</ApexClass>
```

### Actual result

Metadata file after pull was this after pull:

```
<?xml version="1.0" encoding="UTF-8"?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>46.0</apiVersion>
    <status>Active</status>
</ApexClass>
```
As we see, namespace changes. 

### Additional information

**SFDX CLI Version**: sfdx-cli/7.23.1-ced0ec4940 darwin-x64 node-v10.15.3

**SFDX plugin Version**:
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.13.1 (core)
├─ force-language-services 46.18.0 (core)
└─ salesforce-alm 46.17.0 (core)

**OS and version**:
ProductName:    Mac OS X
ProductVersion: 10.14.6

**Comment by dieffrei** [comment]
+1

**Comment by cristiand391** [comment]
It seems this was fixed some years ago: https://github.com/forcedotcom/salesforcedx-vscode/issues/1550, if you still experience this issue when creating an apex class from the CLI make sure you are using the latest version.
