### ISSUE TITLE
[Documentation - release notes] Add links to CLI guides

### ISSUE THREAD

**Issue by ekapner** [forcedotcom/cli#1733]
**Is your feature request related to a problem? Please describe.**
I would love for the intro to each release note to point to the corresponding documentation so I can get more info. 
I know I could launch --help but sometimes I want to look up multiple things and think it would be convenient to have those links handy. FYI @jshackell-sfdc 

**What are you trying to do**
Make it easy for devs to find the related docs

**Describe the solution you'd like**
A link to CLI reference guide and it's sf counterpart

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jshackell-sfdc** [comment]
Updated into of each rel note
