### ISSUE TITLE
CLIError: timed out

### ISSUE THREAD

**Issue by faheemaligit** [forcedotcom/cli#1736]
I don't know why I frequently face these errors while taking metadata backup

CLIError: timed out

And after that, it stuck in List metadata and did not continue for backup, on some days it work fine on others it throws an error.
Sometimes things got stopped in Describe metadata step too.
I hope this is a common issue that needs a fix.

If anyone has a fix for these errors, please comment with your working solutions  #1511 :)
![image](https://user-images.githubusercontent.com/85924785/193877806-1be376e3-2d60-46b9-bb89-0fa396dea4b0.png)

**Comment by shetzel** [comment]
Thank you for posting.  We're going to need more information.  At a minimum, we will need your CLI and plugin versions.  You can get that from running this command: `sfdx version --verbose` and posting it here.  We'll also need the exact command (including all parameters) that causes the problem and the error.  It will help us even more to provide a stack trace if possible.  Alternatively, you can get all of this information by running, `sfdx doctor --command "[insert command here]"` which will generate several files and have some suggestions on what might be wrong.  From your post I can see that you're on CLI version 7.163.0 and the latest is 7.170.0, so you'll want to update.

**Comment by nvuillam** [comment]
@shetzel same happening here, metadata backup jobs failing because of timeouts, on some projects but not all
