### ISSUE TITLE
CLI retrieve ExternalCredentials not supported

### ISSUE THREAD

**Issue by MatRoss93** [forcedotcom/cli#1740]
### Summary

Cannot retrieve required metadata for named credentials

### Steps To Reproduce:

1. configure named credentials
2. try to retrieve an external credential: `sfdx force:source:retrieve -m ExternalCredential` 

### Expected result

ExternalCredential metadata is retrieved

### Actual result

ERROR running force:source:retrieve: The specified metadata type is unsupported; [externalcredential]

### System Information

- cmd.exe
{
  "cliVersion": "sfdx-cli/7.170.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "@salesforce/lwc-dev-server 2.11.0 (user)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.8 (core)",
    "community 2.0.1 (core)",
    "config 1.4.20 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.1.3 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.3 (core)",
    "packaging 1.9.1 (core)",
    "schema 2.1.6 (core)",
    "signups 1.2.2 (core)",
    "source 2.0.15 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.4 (core)",
    "user 2.1.4 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.1 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "cmd.exe",
}

**Comment by shetzel** [comment]
Look for this in the next CLI release candidate in a week.  Thanks Shane!
