### ISSUE TITLE
sfdx force:source:push fails, reason: connect ENETUNREACH 160.8.253.80:443 

### ISSUE THREAD

**Issue by eneag-sf** [forcedotcom/cli#1748]
### Summary

Pushing metadata to a newly created scratch org throws an error (no many time you try)

`Metadata API request failed: request to https://drive-fun-1342.scratch.my.salesforce.com/services/Soap/m/56.0 failed, reason: connect ENETUNREACH 160.8.253.80:443`

### Steps To Reproduce:

1.  Start the script to create a scratch org
2. Scratch org is successfully created
3. Push the metadata with sfdx force:source:push command
4. Command fails (tried multiple times (restarting vscode, updating sfdx version, etc)

### Expected result

Push the metadata to the scratch org without any errors.

### Actual result

`Metadata API request failed: request to https://drive-fun-1342.scratch.my.salesforce.com/services/Soap/m/56.0 failed, reason: connect ENETUNREACH 160.8.253.80:443`

### System Information

- Which shell/terminal are you using? **zsh**

{
  "cliVersion": "sfdx-cli/7.171.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "@salesforce/lwc-dev-server 2.11.0 (user)",
    "1commerce 0.0.10 (user)",
    "alias 2.1.3 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.10 (core)",
    "community 2.0.3 (core)",
    "config 1.4.21 (core)",
    "custom-metadata 2.0.1 (core)",
    "data 2.1.4 (core)",
    "generator 2.0.2 (core)",
    "info 2.1.6 (core)",
    "limits 2.0.3 (core)",
    "org 2.2.7 (core)",
    "packaging 1.9.2 (core)",
    "schema 2.1.8 (core)",
    "signups 1.2.4 (core)",
    "source 2.0.16 (core)",
    "telemetry 2.0.2 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.4 (core)",
    "user 2.1.7 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.1 (core)",
    "sfdx-git-delta 5.5.0 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/xxxxxx/.local/share/sfdx/client/7.171.0-fbe9e7d"
}
### Additional information

![image](https://user-images.githubusercontent.com/75849511/195329541-0f4587cb-7dc3-406f-bcd5-11b8fc741e4d.png)

**Comment by eneag-sf** [comment]
I should add that I do not have any network issues.

**Comment by maxmsf** [comment]
got the same issue manly on recently created or fetched scratchorgs.

**Comment by eneag-sf** [comment]
any update on this? :/

**Comment by eneag-sf** [comment]
This issue was related to my internet connection actually. Even though it seemed my connection was "Stable", it really wasn't. This vscode addon helped me find out: [Show-Ping vsCode](https://marketplace.visualstudio.com/items?itemName=savajols.ping). I will now close this issue as there is no need for further investigation.
