### ISSUE TITLE
Running multiple SFDX conversion commands concurrently

### ISSUE THREAD

**Issue by clouddevsf** [forcedotcom/cli#175]
We have Jenkins setup where it is possible to have multiple builds running concurrently (for different DX projects) on the same machine. The only SFDX commands that we use are force:mdapi:convert and force:source:convert.

So far we have not noticed any issues but wanted to ensure that there are no potential internal lockings between the concurrent command executions.

I am aware of the various commands that need to share the .sfdx context. But for us, we only use SFDX as pure binary function to help with source conversion and nothing else.

I don't have enough internal understanding of the SFDX CLI to make this judgement but would appreciate comments on this.

Thanks.

**Comment by clairebianchi** [comment]
@clouddevsf you can target different user folders per job by retargeting $home so you are sandboxing the home folder. Then you should not have to worry about locking problems
