### ISSUE TITLE
Salesforce Extensions not working on VS Code

### ISSUE THREAD

**Issue by trentch24** [forcedotcom/cli#1754]
**Summary**
The Salesforce extensions are not working in VS Code. I have a Macbook with an M1. The extensions were working just fine and seemed to stop working once I updated to the latest Mac Software: Monterey 12.6.

**Steps to Reproduce**
When I first pull up VS Code, I get the following error:

"Salesforce Extensions for VS Code encountered a problem while configuring your environment. Some features might not work. For details, click Help > Toggle Developer Tools or check the Salesforce CLI logs in ~/.sfdx/sfdx.log."

Is anyone else encountering this same issue?

**Comment by i814u2** [comment]
@trentch24 What's in the log, anything useful? I'm on 12.6 (since it came out), and also on M1 chip, and I don't have that issue. Terminal commands work, as well as commands through the menu. No errors on launch, either.

**Comment by trentch24** [comment]
@i814u2 I'm not sure if this is helpful, but when I try to run sfdx update in the terminal I get the following error: `Bad CPU type in executable`.

There may be helpful information in the log, but I am not well versed in reading it. In the log, It looks like the SFDX CLI Extension is activated.

**Comment by i814u2** [comment]
That's node telling you that it doesn't know how to deal with the M1 chip. That would tell me that you have the x64 variation installed, but don't have Rosetta 2.

Check this out: https://support.apple.com/en-us/HT211861

You can also review issue #1045, and the final comment by RodEsp if you want to try and use the native client. I recently tried and had some issues, but it easily could have been my setup.

**Comment by trentch24** [comment]
Thanks! I will try that out. 

I am experiencing this issue on my work mac, but I also have a personal mac and sfdx works just fine and I don't have Rosetta.

**Comment by trentch24** [comment]
That worked. Thank you!

**Comment by imanol309** [comment]
@trentch24 Were you able to solve it? I have a MSI Katana and I just updated the Salesforce extension and I get the same error.

**Comment by trentch24** [comment]
Yes @imanol309. I believe I just followed these instructions: https://support.apple.com/en-us/HT211861. 

Also, you can look here: https://github.com/forcedotcom/cli/issues/1045.

**Comment by rt83FMR** [comment]
Facing same issue on Windows Let me know if any solution is there
