### ISSUE TITLE
ERROR running force:source:convert:  Unexpected child metadata  [.../force-app/main/default/obje ctTranslations/npo02__Household__c-de/npo02__OppAmountLastNDays__c.fieldTranslat ion-meta.xml] found for parent type [CustomObjectTranslation]

### ISSUE THREAD

**Issue by fabioAtANT** [forcedotcom/cli#1757]
### Summary

We get an error when creating a package version with SFDX 7.172.0. The creation of package version with same content works as expected with 7.171.0

### Steps To Reproduce:

1.  cci flow run build_feature_test_package (CumulusCI) which basically runs force:package:version:create

### Expected result

Package version is created

### Actual result

ERROR running force:source:convert:  Unexpected child metadata 
[/.../force-app/main/default/obje
ctTranslations/npo02__Household__c-de/npo02__OppAmountLastNDays__c.fieldTranslat
ion-meta.xml] found for parent type [CustomObjectTranslation]

### System Information

sfdx 7.172.0
CumulusCI 3.67.1

### Additional information

Same works with sfdx 7.171.0 and CumulusCI 3.67.1

**Comment by j-schreiber** [comment]
This also affects `force:source:deploy` and now broke our pipeline. The last build that successfully ran was using 7.171.

**Comment by mshanemc** [comment]
I think we got all the COFT bugs fixed last year.  Is this still reproducible on newer CLIs?
