### ISSUE TITLE
sfdx force:source:deploy -x path/to/package.xml  is struck not getting deployment status back

### ISSUE THREAD

**Issue by praveen-sfdc** [forcedotcom/cli#1761]
In our CD pipeline we are executing the below command to deploy components. This was working fine till yesterday 10/16/2022. Starting 10/17/2022 we are not getting the deployment status back though the components are successfully deployed to the Salesforce Org. 
CLI Command: sfdx force:source:deploy -x path/to/package.xml -l RunSpecifiedTests -r apexTests -w 480

sfdx-cli@7.110.0 is the cli version

**Comment by WillieRuemmele** [comment]
hey @praveen-sfdc, Can you try updating to the latest CLI version? If something is changing, and you aren't changing the CLI versions, it's likely a server error
