### ISSUE TITLE
Source tracking commands throwing error when using apiVersion 56.0

### ISSUE THREAD

**Issue by janhnhi** [forcedotcom/cli#1766]
### Summary

After the sandboxes were upgraded to Winter 23, when trying to run the source tracking commands, we get the below errors using the default apiVersion of 56.0 and sfdx-cli version 7.158.0:

- sfdx force:source:push -f
  - `No such column 'RevisionCounter' on entity 'SourceMember'. If you are attempting to use a custom field, be sure to append the __c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.`
- sfdx force:source:status
  - `ERROR running force:source:status:  MemberType, MemberName, IsNameObsolete, RevisionCounter FROM SourceMember`

### Steps To Reproduce:

1. Download sfdx-cli version 7.158.0
1. Authorize a sandbox.
1. Run `sfdx force:source:push -f`
1. Run `sfdx force:source:status`

### Expected result

`sfdx force:source:push -f`: The local metadata should be deployed to the connected sandbox.
`sfdx force:source:status`: The differences between local and the sandbox will be output in the terminal.

### Actual result

The above error messages.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
Bash

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here
{
    "cliVersion": "sfdx-cli/7.158.1",
    "architecture": "win32-x64",
    "nodeVersion": "node-v16.15.1",
    "pluginVersions": [
        "@oclif/plugin-autocomplete 0.3.0 (core)",
        "@oclif/plugin-commands 1.3.0 (core)",
        "@oclif/plugin-help 3.3.1 (core)",
        "@oclif/plugin-not-found 1.2.6 (core)",
        "@oclif/plugin-plugins 1.10.11 (core)",
        "@oclif/plugin-update 1.5.0 (core)",
        "@oclif/plugin-warn-if-update-available 1.7.3 (core)",
        "@oclif/plugin-which 1.0.4 (core)",
        "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
        "alias 2.1.0 (core)",
        "apex 0.13.0 (core)",
        "auth 2.2.2 (core)",
        "community 2.0.0 (core)",
        "config 1.4.12 (core)",
        "custom-metadata 2.0.0 (core)",
        "data 2.0.4 (core)",
        "generator 2.0.2 (core)",
        "info 2.0.1 (core)",
        "limits 2.0.1 (core)",
        "org 2.0.1 (core)",
        "salesforce-alm 54.6.2 (core)",
        "schema 2.1.1 (core)",
        "sfdx-cli 7.158.1 (core)",
        "signups 1.2.0 (core)",
        "source 2.0.3 (core)",
        "telemetry 2.0.0 (core)",
        "templates 55.0.0 (core)",
        "trust 2.0.1 (core)",
        "user 2.1.0 (core)"
    ],
    "osVersion": "Windows_NT 10.0.19042"
}

**Comment by WillieRuemmele** [comment]
hi @janhnhi 

that's really strange. We use `RevisionCounter` for source tracking on the [SourceMember](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_sourcemember.htm) object. Can you make sure the [source tracking for sandboxes](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_setup_enable_source_tracking_sandboxes.htm) is still enabled? Can you try running `sfdx doctor` command to see if it has any additional diagnosis for you?

**Comment by janhnhi** [comment]
We do have source tracking enabled for all our sandboxes! This issue didn't happen to everyone on our team, and it seems to be tied only to apiVersion 56.0.

I'm getting this error when running `sfdx doctor`:
`sfdx doctor
 »   Warning: sfdx-cli update available from 7.158.1 to 7.166.1.
 »   Warning: doctor is not a sfdx command.
Did you mean force? [y/n]: 
 »   Error: Run sfdx help for a list of available commands.`

**Comment by WillieRuemmele** [comment]
oh sorry about that, we introduced `sfdx doctor` only a few releases ago. Can you try updating your CLI and trying running those commands against your sandbox? If they're still failing you should have the `doctor` command to hopefully help diagnose the situation

**Comment by janhnhi** [comment]
Hi, unfortunately we are unable to upgrade to a newer SFDX version due to corporate policy for any external technology upgrades. Our current workaround is setting the apiVersion to 55.0, but we're not sure if we will be able to update to version 57.0 when Spring '23 is applied, or if the issue will still occur.

**Comment by WillieRuemmele** [comment]
Hi @janhnhi - we believe this is due to some users no longer having access to the `SourceMember` object which is used for source tracking. Are you still seeing this issue? Have you tried using an older api version like 55?

**Comment by janhnhi** [comment]
Both users having the issues were Admins, while other Admin users on our team did not have any issue. We are able to use the older apiVersion 55.0, but this is only a temporary workaround as we want to stay on the recent API version moving forward. Every Salesforce release, we rebase our repo based on the newest API version, and we want to avoid potential issues if developers are stuck on an older version.

**Comment by mshanemc** [comment]
Did this get better?  It doesn't seem like a CLI issue, so if it's still happening you're going to need to open a support case for it.

**Comment by balindersingh** [comment]
I am seeing the same issue.. After sfdx update to latest .. still seeing the same issue.. I am working with scratch org only not sandbox

**Comment by cromwellryan** [comment]
@balindersingh, we would encourage you to open a support case. The error reported is indicative of permission issues. This may take some time to diagnose if it intermittent. Having multiple people reporting will help expedite the resolution.
