### ISSUE TITLE
New sfdx version 7.173 with npm does not work - Error: Cannot find module 'node:os'

### ISSUE THREAD

**Issue by JuliWaver** [forcedotcom/cli#1768]
### Summary

I got some API version error therefore I updated my sfdx version with command: npm update --global sfdx-cli like in the past. Afterwards nothing is working anymore. I can't run any sfdx command withou getting an error message.

### Steps To Reproduce:

Update your sfdx version to the latest version with command "npm update --global sfdx-cli" and try to use any sfdx command afterwards (e.g. sfdx version, sfdx force:org:list, ...)

### Expected result

Normally the command should work, no error message shown.

### Actual result

Error message is shown:

PS C:\XXX> sfdx --version
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:os'
Require stack:
- C:\Users\XYZ\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\plugin-version\lib\commands\version.js
- C:\Users\XYZ\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\plugin-version\lib\index.js
- C:\Users\XYZ\AppData\Roaming\npm\node_modules\sfdx-cli\dist\cli.js
- C:\Users\XYZ\AppData\Roaming\npm\node_modules\sfdx-cli\bin\run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Object.<anonymous> (C:\Users\XYZ\AppData\Roaming\npm\node_modules\sfdx-cli\node_modules\@oclif\plugin-version\lib\commands\version.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\XYZ\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\plugin-version\\lib\\commands\\version.js',
    'C:\\Users\\XYZ\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\plugin-version\\lib\\index.js',
    'C:\\Users\\XYZ\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\dist\\cli.js',
  ]
}

### System Information

- Terminal: Visual Studio Code embedded Terminal (Powershell)
- npm version: 8.19.2
- node.js version: v14.17.3
- sfdx version: sfdx-cli@7.173.0

**Comment by cristiand391** [comment]
This is an issue with the node version you have installed, make sure to always use the latest LTS version available, see:

https://github.com/forcedotcom/cli/issues/1728

**Comment by JuliWaver** [comment]
Perfect, thank you so much @cristiand391. I was not able to find the related issue https://github.com/forcedotcom/cli/issues/1728 before. With the new version of node.js v16.18.0 it is working for me :)
