### ISSUE TITLE
Managed Package Version Creation Error for CLI v 7.172.+

### ISSUE THREAD

**Issue by wboyd-fuseit** [forcedotcom/cli#1771]
Running "sfdx force:package:version:create" on CLI 7.172 and above fails with multiple errors due to not including the package Namespace on sObject fields.
e.g. "Multiple Errors - No such column 'fieldName__c' on entity namespace__objectName__c"
The CLI does not include the namespace onto each field name when creating a new package version i.e. "namespace__fieldName__c"

Steps to recreate.
CLI version 7.172 or above.
Namespace Org and DevHub Org set up.
VS Code project with sfdx-project.json set up with namespace and custom objects.
Run "sfdx force:package:create" to create the 0H0 package
Run sfdx force:package:version:create to produce error.

I was able to replicate the error on two different computers.
The fix was to uninstall with "C:\Program Files\Salesforce CLI\uninstal.exe"
Install older CLI version
e.g. "https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/7.167.1/27670a3/sfdx-v7.167.1-27670a3-x64.exe"

Running  "sfdx force:package:version:create" with CLI 7.167.1 created new version package without errors

**Comment by WillieRuemmele** [comment]
Hi @wboyd-fuseit sorry to hear you had to downgrade, could you try using the `beta` version of the packaging commands? `force:package(1):beta:*`? We're getting closer to GA'ing those, and would love to make sure it's fixed there

**Comment by kwikalot** [comment]
Hi @wboyd-fuseit - I've got the same problem as you, however it was working for me before Winter 23 release. When that new release was deployed, suddenly I started seeing the same errors as you.

And I can confirm that workaround with that older version of the CLI is working. I've created a SF support ticket regarding this.

**Comment by noblejasper** [comment]
I ran into the same situation, downgraded and dealt with it.
I tried it with `sfdx force:package:beta:version:create` as @WillieRuemmele wrote and succeeded in [getting it](https://github.com/forcedotcom/cli/issues/1771#issuecomment-1292183564) to work correctly.

Thanks to @wboyd-fuseit for making the issue and @WillieRuemmele for commenting!

**Comment by eugenevabishchevich** [comment]
Hi guys,

we got the same error with "No such column" for managed package using `sfdx force:package:version:create` But on the macOS, CLI version 7.174.

**Comment by WillieRuemmele** [comment]
Hi @eugenevabishchevich can you try the `beta` commands? It seems like they've worked for other users on this thread. I think I'll leave this GitHub issue open so other users can find it and test out the `beta` commands

**Comment by eugenevabishchevich** [comment]
@WillieRuemmele `beta` command works good

**Comment by kwikalot** [comment]
@WillieRuemmele Are you able to verify, that the beta command works with the unpacked metadata? Because when I was testing it, it was throwing an error during the test run (package was being built with --codecoverage). It looked like with this new command CLI doesn't take into account the unpackaged metadata.

**Comment by WillieRuemmele** [comment]
Hi @paweliwanowicz can you create a new issue, with steps to reproduce and we can solve that independently

**Comment by kwikalot** [comment]
@WillieRuemmele Sure, no problem. I will do it right after the weekend.

**Comment by gikokopev** [comment]
Is this issue fixed? If so in which version ?

**Comment by mshanemc** [comment]
it seems to work on the beta version, with the possible exception of unlocked packages that have unpackaged metadata.  If you have a reproduction and want to help, please open another issue.  Nobody responded to this one with any problems, so it closed.
