### ISSUE TITLE
force:package:beta:version:create command fails if there is unpackaged metadata

### ISSUE THREAD

**Issue by kwikalot** [forcedotcom/cli#1775]
Hi,

During managed package version creation with sfdx-cli/7.174.0 win32-x64 node-v16.17.1 and the beta command `sfdx force:package:beta:version:create` we've observed, that if the package contains unpackaged metadata, then the version creation is failing during test execution.

### Steps To Reproduce:

1.  Make sure you have the newest version of the CLI (minimum 7.174.0)
1.  Create a sample manage package with unpackaged metadata - for example it can be an approval process (for details go here: [https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev
/sfdx_dev_dev2gp_unpackaged_md.htm](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_unpackaged_md.htm)). Make sure, that you've got some apex tests, that are using that approval process or any other unpackaged metadata that you are using.
1. Try to create a new version of the package with the following command: `sfdx force:package:beta:version:create -v yourDevHubUser -p "YourPackageAlias" -k yourInstallationKey -w 30 --codecoverage`

### Expected result
New version is being created without any problems

### Actual result
Apex unit tests are throwing an error:
`System.DmlException: Process failed. First exception on row 0; first error: NO_APPLICABLE_PROCESS, No applicable approval process was found.: []`

**Comment by WillieRuemmele** [comment]
thank you so much for creating this @paweliwanowicz 🎉

**Comment by WillieRuemmele** [comment]
Hi @paweliwanowicz could you please try using the `beta` commands on version `7.177.1`, I believe this has been fixed by this comment https://github.com/forcedotcom/cli/issues/1743#issuecomment-1317288953

would love to verify this - thank you 👍 

I verified this is working `sfdx-cli/7.178.0 darwin-arm64 node-v18.7.01` and will close. If you're still having issues please let me know and I'll reopen :)

**Comment by kwikalot** [comment]
Hi @WillieRuemmele,

I've checked the newest version `7.179.0` and everything works just perfectly. Thank you for the help! :)
