### ISSUE TITLE
ERROR running force:source:push:  Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by ndingass** [forcedotcom/cli#1776]
Am getting the below error when running: sfdx force:source:push   command to a new scratch org:

*** Pushing with SOAP API v54.0 ***
DEPLOY PROGRESS | ████████████████████████████████████████ | 3053/3053 Components
ERROR running force:source:push:  Cannot read properties of null (reading 'split')
CLIError: timed out
    at Object.error (/Users/myusr/.nvm/versions/node/v19.0.0/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/errors/index.js:28:15)
    at /Users/myusr/.nvm/versions/node/v19.0.0/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:25:66
    at async flush (/Users/myusr/.nvm/versions/node/v19.0.0/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/cli-ux/index.js:124:9) {
  oclif: { exit: 2 },
  code: undefined
}

**Comment by WillieRuemmele** [comment]
hi @ndingass can you please create the issue with the information requested in the template? `sfdx version --verbose` a few steps, or project, to recreate this?
