### ISSUE TITLE
sfdx force:cmdt:record:insert does not insert records for custom metadata that isn't maintained in the project's repository

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1778]
### Summary

`sfdx force:cmdt:record:insert` has two bugs:

1 - scans the project looking for a directory path that doesn't exist `force-app/main/default` instead of looking for the `path` declared in the `sfdx-project.json`

in the image below you can see my attempt while using this command to insert custom metadata records
![image](https://user-images.githubusercontent.com/55927613/199013818-4ff86a59-1b7e-46ee-acb5-5e90d20efd0a.png)

and this is the path configured in the `sfdx-project.json` which contains the right path to locate the metadata definition
![image](https://user-images.githubusercontent.com/55927613/199013790-812abd3e-e9c6-410d-8c87-eddc3dabb17e.png)

2 - this custom metadata called VARS__ENV__mdt (namespace VARS) was installed by this unlocked package "https://github.com/callawaycloud/Salesforce-Environment-Vars" . This means I'm not tracking its fields in my repository, and because of that I can't use this command unless I retrieve this custom metadata fields and store in my project's repository. And in my opinion, this does not make sense in this case because this custom metadata is maintained in another repo.

### Steps To Reproduce:

1 - install any unlocked package that contains a custom metadata that you want to create records for using `sfdx force:cmdt:record:insert`
2 - try to add records to this custom metadata using `sfdx force:cmdt:record:insert --filepath <YOUR_CSV_PATH> --typename <CUSTOM_METADATA_API_NAME>`
3.1 - 1st bug: verify that sfdx throws an error because it tried to look for your custom metadata fields in this path `force-app/main/default/objects/<CUSTOM_METADATA_API_NAME>/fields` which might not be the path you configured in the `sfdx-project.json`
3.2 - 2nd bug: verify that sfdx did not create records for you custom metadata because it could not locate the `fields` folder from `force-app/main/default/objects/<CUSTOM_METADATA_API_NAME>/fields`. This command should try to look for the fields querying the schema of that particular custom metadata from the sandbox.
 
 
### Workaround:

add to .forceignore and .gitignore the path where you intend to extract your custom metadata fields. This step is a must to avoid tracking and deploying changes to this custom metadata.

extract the custom metadata fields and save on the default path configured in `sfdx-project.json` running
`sfdx force:source:retrieve -m "CustomObject:<CUSTOM_METADATA_API_NAME>"`

finally insert records for your custom metadata
obs: because of the 1st bug, it is mandatory to set the optional flag called "--inputdir" 
`sfdx force:cmdt:record:insert --filepath <PATH_TO_CSV> --typename <CUSTOM_METADATA_API_NAME> --inputdir <CUSTOM_METADATA_PATH>`

 
 
### Expected result

`sfdx force:cmdt:record:insert` should be able to create custom metadata records for custom metadata that are not maintained on the project's repository

### Actual result

`sfdx force:cmdt:record:insert` can't insert records for custom metadata that aren't maintained in the project's repository

### System Information

![image](https://user-images.githubusercontent.com/55927613/199016105-45c0aebe-abd6-413a-bec3-20f6b4d0d197.png)

**Comment by mshanemc** [comment]
background: we've kinda inherited these commands from the team that built them.  I've used them just enough to test with. 

bug 1: both `--inputdir` and `--outputdir` default to looking in `force-app/main/default/*`.  I agree that using the default pkgDir would have been smarter than hardcoding it.

Is there something that doesn't work correctly when you use those flags?

I think you'd also have the option to retrieve just the metadata of your choice and then point the inputdir to that without impacting your project (especially with the new --retrievetargetdir  that's about to land in `source:retrieve` https://github.com/salesforcecli/plugin-source/pull/624

**Comment by AllanOricil** [comment]
Could you reopen this. I will take a look at it later 👍

**Comment by AllanOricil** [comment]
I'm going to start my analysis tomorrow 🤙
