### ISSUE TITLE
sfdx "force:package:beta:version:create:report" does not print errors

### ISSUE THREAD

**Issue by higgspa** [forcedotcom/cli#1779]
### Summary

When running the new command "force:package:beta:version:create:report" on a failed build it only logs a "Status: Error" without logging the actual errors that caused it to fail. I tried increasing the --loglevel settings but they did not work. Luckily switching back to the old command "sfdx force:package:version:create:report" still printed the errors. 

### Steps To Reproduce:

1. Run "sfdx force:package:beta:version:create --package" on a package that has known errors
2. Run "sfdx force:package:beta:version:create:report" on the built package and notice the status is Error but it does not print any of the reasons or errors. 
3. Run the older command "sfdx force:package:version:create:report" on the same package id and it will display the actual errors. 

### Expected result

A failed package build "Status: Error" should display the errors that caused the build to fail. 

### Actual result

No errors are logged. 

NOTE:  When running the new "sfdx force:package:beta:version:create:report" command it still recommends running the old status command "sfdx force:package:version:create:report" instead of the new beta command "sfdx force:package:beta:version:create:repor"

**Comment by WillieRuemmele** [comment]
Thanks for testing out the beta @higgspa we really appreciate it and will fix this bug 😄

**Comment by iowillhoit** [comment]
This has been released in today's `latest` build `7.181.1`
