### ISSUE TITLE
`force:project:create` templates still use API version 55.0 instead of 56.0

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#1780]
Hopefully this is pretty straightforward, but a project created using the CLI still includes the Summer '22 API version number 55.0 in the `sfdx-project.json` and (if `-x` is used) `manifest/package.xml` files. It seems like they should be using 56.0 for Winter '23, no? This is with:

```
$ sfdx version
sfdx-cli/7.174.0 win32-x64 node-v16.17.1
```

**Comment by WillieRuemmele** [comment]
Hey @SCWells72 we're aware, and are tracking under W-11969892

Thank you 😄

**Comment by SCWells72** [comment]
Thanks for the update. Just logging because I had issues logged against IC2 for SFDX projects being created via IC2 with the older API version number. Logged this so I could link from the corresponding items in my own issue tracker. Thanks again!

**Comment by WillieRuemmele** [comment]
https://github.com/forcedotcom/salesforcedx-templates/pull/519

**Comment by mshanemc** [comment]
late update: fixed, now v57
