### ISSUE TITLE
Unexpected error when pushing external credentials linked to a permission set

### ISSUE THREAD

**Issue by imTachu** [forcedotcom/cli#1781]
### Summary

Cryptic error when pushing External Credentials linked to a permission set.

### Steps To Reproduce:

**Repository to reproduce:** https://github.com/imTachu/sfdx-cli-external-credentials-issue-example

1. Make sure to have update sfdx cli to v7.173.0 which [now allows](https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71730-oct-20-2022) to push external credentials. 
2. Clone the example repository
3. Execute `./bin/orgInit.sh -d 1 -n issueExternalCredential`
4. You should get an unexpected error.

By trying different things, I found out that the issue appears when the permission set that is linked to the external credential includes a `classAccesses` property. Removing it does the trick as a workaround. In our project we had to create a separate permission just to link it to the external credentials, ideally we can use the permission set that also allows access to Apex classes.

NB: Upgrading the project to API 56 does not help.

### Expected result

External credentials (and rest of metadata) are successfully pushed.

### Actual result

```
An unexpected error occurred. Please include this ErrorId if you contact support: 505302306-751196 (2056426840)
```

### System Information

- MacOS 12.2.1
- zsh 5.8
- sfdx-cli/7.174.0 (also tested with sfdx-cli/7.173.0)

**Comment by WillieRuemmele** [comment]
Hi @imTachu thanks for reaching out. I've let a few other teams know and they'll be looking at this soon - I'm not sure it's solely a CLI issue. Thanks for reporting 😄

**Comment by jefersonchaves** [comment]
I understand that this bug might be owned by a different team, but is there an update on [W-12075756](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001DGV82YAH/view)?

**Comment by mshanemc** [comment]
I don't have any updates.  The more customers who open cases, the higher the priority for the bug.

**Comment by tehnrd** [comment]
This is impacting me too. I'll open a case...but the easiest path is to revert to "Legacy" Named Credential, which is what I will probably do as I can't wait for this to get fixed.

**Comment by mshanemc** [comment]
I heard from the people that own this that it's working now and they asked me to close this.

Holler if it you're still getting the error..

**Comment by mryhmln** [comment]
I know this issue is closed but I'm still getting this error @mshanemc. My sfdx version is sfdx-cli/7.185.0 darwin-x64 node-v18.12.1

**Comment by stephen-wilcox** [comment]
I encountered this error. I have two external service. One deployed successfully, one didn't. I copied this <serviceBinding> element from the working service to the non-working service:
`<serviceBinding>{&quot;compatibleMediaTypes&quot;:{}}</serviceBinding>`
