### ISSUE TITLE
Ubuntu 18 and Node glibc errors

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#1788]
The error looks like this 
```
/home/ubuntu/.local/share/sfdx/client/7.175.0-a62760c/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version 
GLIBC_2.28' not found (required by /home/ubuntu/.local/share/sfdx/client/7.175.0-a62760c/bin/node)
```

Node 18, which we currently bundle in our tarballs/installed requires a newer unbuntu version that contains a newer glibc 
https://github.com/nodejs/node/blob/main/BUILDING.md#platform-list
https://github.com/nodejs/node/issues/42351

Your two best options would be
1. update your unbuntu version (preferred)
2. install the CLI via npm https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_npm

We officially support node 14 (until its EOL 4/30/2022) or higher.

**Comment by mnunezdm** [comment]
Could be possible to continue uploading this binaries for ubuntu 18?

installing with npm its more than 10x slower

**Comment by mnunezdm** [comment]
Could be possible to continue uploading the binaries for ubuntu 18?

installing with npm its more than 10x slower

**Comment by abdennour** [comment]
this and this https://github.com/openshift/openshift-docs/pull/27181 both are related.

**Comment by seenu-salloori** [comment]
We are also facing the same error
