### ISSUE TITLE
Unexpected Error on Package creation with "force:package:beta:version:create" command

### ISSUE THREAD

**Issue by rsavaliyagit** [forcedotcom/cli#1789]
### Summary

I'm getting below error on package creation with "force:package:beta:version:create" command.

Command: sfdx force:package:beta:version:create --codecoverage -p "PACKAGE" -k "INSTALLATIONKEY" -v "TARGETDEVHUBUSERNAME" --wait 120

(Use `node --trace-warnings ...` to show where the warning was created)
ERROR running force:package:beta:version:create:  Converting circular structure to JSON
    --> starting at object with constructor 'Connection'
    |     property '_refreshDelegate' -> object with constructor 'SessionRefreshDelegate'
    --- property '_conn' closes the circle

### Steps To Reproduce: Run this command to create a package.
Command: sfdx force:package:beta:version:create --codecoverage -p "PACKAGE" -k "INSTALLATIONKEY" -v "TARGETDEVHUBUSERNAME" --wait 120

### Expected result

Package should be created successfully. 

### Actual result

Error:

ERROR running force:package:beta:version:create:  Converting circular structure to JSON
    --> starting at object with constructor 'Connection'
    |     property '_refreshDelegate' -> object with constructor 'SessionRefreshDelegate'
    --- property '_conn' closes the circle

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.) : sfdx-cli/7.174.0
- If you are using `sfdx`
	- Run 'sfdx force:package:beta:version:create --codecoverage -p "PACKAGE" -k "INSTALLATIONKEY" -v "TARGETDEVHUBUSERNAME" --wait 120'
- Paste the output here

**Comment by peternhale** [comment]
@rsavaliyagit I would like some additional information please.
* results of running `sfdx version --verbose`
* If you can, share the contents of sfdx-project.json
* the files created by `sfdx doctor -c "force📦beta:version:create --codecoverage -p "PACKAGE" -k "INSTALLATIONKEY" -v "TARGETDEVHUBUSERNAME" --wait 120" (please examine the resulting files to redact any sensitive information)

**Comment by rsavaliyagit** [comment]
Here are some more details. Please let me know if you need more info. Thanks!

sfdx version --verbose
 CLI Version:
        sfdx-cli/7.175.0 ( Version on Jenkins Pipeline Server: sfdx-cli/7.174.0)

 Architecture:
        win32-x64

 Node Version:
        node-v18.12.0

 Plugin Version:
        @oclif/plugin-autocomplete 1.3.1 (core)
        @oclif/plugin-commands 2.2.0 (core)
        @oclif/plugin-help 5.1.14 (core)
        @oclif/plugin-not-found 2.3.3 (core)
        @oclif/plugin-plugins 2.1.1 (core)
        @oclif/plugin-update 3.0.2 (core)
        @oclif/plugin-version 1.1.2 (core)
        @oclif/plugin-warn-if-update-available 2.0.6 (core)
        @oclif/plugin-which 2.1.0 (core)
        alias 2.1.6 (core)
        apex 1.3.0 (core)
        auth 2.2.16 (core)
        community 2.0.13 (core)
        config 1.4.21 (core)
        custom-metadata 2.0.2 (core)
        data 2.1.5 (core)
        generator 2.0.8 (core)
        info 2.2.1 (core)
        limits 2.0.8 (core)
        org 2.2.9 (core)
        packaging 1.9.6 (core)
        schema 2.1.11 (core)
        signups 1.2.8 (core)
        source 2.0.26 (core)
        telemetry 2.0.2 (core)
        templates 55.1.0 (core)
        trust 2.0.4 (core)
        user 2.1.14 (core)
        @salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
        salesforce-alm 54.8.3 (core)

 OS and Version:
        Windows_NT 10.0.19042

 Shell:
        cmd.exe

____________________________________________________________________

contents of sfdx-project.json

{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true,
            "package": "sfdx-sales-lib",
            "versionNumber": "22.10.0.NEXT",
            "definitionFile": "config/enterprise-scratch-def.json",
            "dependencies": [
                {
                    "package": "S3-Link"
                },
                {
                    "package": "CMTD Enhanced Related List"
                },
                {
                    "package": "Marketing Cloud"
                },
                {
                    "package": "sfdx-base-lib",
                    "versionNumber": "22.10.0.LATEST"
                },
                {
                    "package": "Gryphon"
                },
                {
                    "package": "ZoomInfo"
                },
                {
                    "package": "DOZISF ZoomInfo"
                },
                {
                    "package": "UniversalTimeline"
                },
                {
                    "package": "PhoneTools"
                },
                {
                    "package": "AMSTAT"
                }
            ]
        },
        {
            "path": "manual-metadata",
            "default": false
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "55.0",
    "packageAliases": {
        *packageAliases*
    }
}

**Comment by peternhale** [comment]
@rsavaliyagit Thank you for the information, but could use a bit more,

Are you able to share the results of the sfdx doctor command?

If not, could you return the command agains with the `--json` flag, so a stack trace can be captured

Does the version create work with the `sfdx force:project:create:version` command?

**Comment by rsavaliyagit** [comment]
[Result_sfdx doctor command.txt](https://github.com/forcedotcom/cli/files/9939764/Result_sfdx.doctor.command.txt)

attached the result of doctor command.

**Comment by rsavaliyagit** [comment]
Hi @peternhale just checking if you have any update on this issue?

**Comment by peternhale** [comment]
@rsavaliyagit The issue has been located and corrected. The change was made in packaging library. We hope to have that version include in the plugin commands in this week's latest-rc release of sfdx-cli.

**Comment by rsavaliyagit** [comment]
@peternhale thanks for the quick response. what date is the release of sfdx-cli in this week ?

**Comment by peternhale** [comment]
@rsavaliyagit we typically release each Thursday.

**Comment by Charles-Revelle** [comment]
@peternhale can we get confirmation that a fix for this bug is planned for tomorrow (Thursday 11/10)? I work with @rsavaliyagit and we have several deployments dependent on this.

**Comment by rsavaliyagit** [comment]
Hi @peternhale  Let us know the latest-rc version # once it's available. Thanks!

**Comment by mshanemc** [comment]
https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71771-nov-17-2022-stable-rc
