### ISSUE TITLE
Make "versionNumber" optional in sfdx-project.json

### ISSUE THREAD

**Issue by douglascayers** [forcedotcom/cli#179]
**Is your feature request related to a problem? Please describe.**

In a CI/CD setup, I automate the creation of package versions. No developers maintain the `sfdx-project.json` file.

Once a package version has been promoted/released, no other package version with the same major.minor number can be promoted/released. Our [script](https://gist.github.com/douglascayers/e3a9525729a1b512618adf720e3fbe94) therefore determines the next appropriate major.minor version number based on the most recently released package version and specifies it via the `--versionnumber` flag to the `force:package:version:create` command.

However, as of Winter '20, the [Salesforce documentation](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev2gp_config_file.htm) says, and [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode) requires, that a package directory in `sfdx-project.json` that specifies the `package` property must also specify the `versionNumber` property.

![image](https://user-images.githubusercontent.com/4142577/65211499-900f0900-da64-11e9-854f-9dbbd4ae4e3f.png)

Functionally, though, that's not a requirement because the version number can be provided at runtime via the `--versionnumber` flag to the `force:package:version:create` command.

It's only if neither the `--versionnumber` flag or the `versionNumber` property in `sfdx-project.json` are missing that an error should be raised.

**What are you trying to do**

To not need the `versionNumber` property in `sfdx-project.json` because we always specify it as an argument to the `force:package:version:create` command and no one maintains the `sfdx-project.json` file.

**Describe the solution you'd like**

Salesforce Extensions for Visual Studio Code to not complain that `versionNumber` property is missing if a package directory specifies the `package` property.

Since other arguments like `versionName`, `description`, `branch`, `tag`, etc. are not required in `sfdx-project.json` and their values can be provided at runtime to the `force:package:version:create` command, I'd like to see `versionNumber` be documented as optional in `sfdx-project.json` too.

**Describe alternatives you've considered**

Since our CI/CD service uses a bash script to generate the appropriate major.minor.patch.build version number and passes it as the `--versionnumber` flag to the `force:package:version:create` command, we added the placeholder `"versionNumber": "1.0.0.NEXT"` property to our `sfdx-project.json`. However, this gives impression that our package is on the `1.0.0.x` version numbering scheme when in reality it may be something different. For our purposes, we derive no value from `versionNumber` as a required property in `sfdx-project.json`.

https://gist.github.com/douglascayers/e3a9525729a1b512618adf720e3fbe94

```
{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true,
            "package": "MyPackage",
            "versionNumber": "1.0.0.NEXT"
        }
    ],
    "namespace": "my_namespace",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "46.0",
    "packageAliases": {
        "MyPackage": "0Hoxxx"
    }
}
```

**Comment by ntotten** [comment]
I have passed this feedback along to the packaging team, however this isn't something controlled by the CLI so I am closing this as out of scope.

**Comment by douglascayers** [comment]
Hi @ntotten, is the `sfdx-project.json` file not in scope of the Salesforce CLI? The CLI uses that file to drive configuration of CLI commands.

**Comment by ntotten** [comment]
I misread your initial request. This is really just something in the schema. VS Code is just enforcing the basic rules here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev2gp_config_file.htm

This warning shouldn't actually prevent you from doing what you are doing, it is just informational.

**Comment by douglascayers** [comment]
Thanks for the clarification, understood.
