### ISSUE TITLE
REGRESSION: SFDX 7.176 silently exits when pushing Zipfile static resource

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#1791]
### Summary

Our nightly CI build for the CLI Release Candidate failed tonight on CLI sfdx-cli/7.176.0

Through binary debugging of removing one metadata type at a time, I was able to isolate it down to the expanded static resources in our source tree. I created a repo below with an example static resource that exhibits the problem. I was unable to generate log files for some reason -- sfdx.log never got created?

### Steps To Reproduce:

**Repository to reproduce:** 

https://github.com/patronmanager/regression-176-staticresource

1.  Clone the above repo
2.  `sfdx force:org:create --setdefaultusername -f config/project-scratch-def.json`
3. `sfdx force:source:push`

### Expected result

Expected the static resource to be pushed into the org

### Actual result

Command immediately exits with no error

```
esposito@PT-WIN-ESPOSITO:~/regression-176-staticresource$ sfdx force:source:push
*** Pushing with SOAP API v55.0 ***
esposito@PT-WIN-ESPOSITO:~/regression-176-staticresource$ 
```

Note that I tried generating log output but even using `--loglevel debug` didn't generate an `sfdx.log` for me

### System Information

Same failure on both the current GH Actions default `ubuntu-latest` container as well as WSL 

```
 CLI Version:
        sfdx-cli/7.176.0

 Architecture:
        wsl-x64

 Node Version:
        node-v18.12.0

 Plugin Version:
        @oclif/plugin-autocomplete 1.3.5 (core)
        @oclif/plugin-commands 2.2.1 (core)
        @oclif/plugin-help 5.1.17 (core)
        @oclif/plugin-not-found 2.3.3 (core)
        @oclif/plugin-plugins 2.1.1 (core)
        @oclif/plugin-update 3.0.6 (core)
        @oclif/plugin-version 1.1.3 (core)
        @oclif/plugin-warn-if-update-available 2.0.6 (core)
        @oclif/plugin-which 2.1.1 (core)
        alias 2.1.7 (core)
        apex 1.3.0 (core)
        auth 2.2.19 (core)
        community 2.0.14 (core)
        config 1.4.22 (core)
        custom-metadata 2.0.3 (core)
        data 2.1.7 (core)
        generator 2.0.9 (core)
        info 2.2.4 (core)
        limits 2.0.10 (core)
        org 2.2.11 (core)
        packaging 1.9.8 (core)
        schema 2.1.12 (core)
        signups 1.2.11 (core)
        source 2.3.0 (core)
        telemetry 2.0.2 (core)
        templates 55.1.0 (core)
        trust 2.0.4 (core)
        user 2.1.16 (core)
        @salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
        salesforce-alm 54.8.3 (core)

 OS and Version:
        Linux 5.10.102.1-microsoft-standard-WSL2

 Shell:
        bash

 Root Path:
        /home/esposito/sfdx
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by mshanemc** [comment]
I'm going to fix this and patch RC with it.

**Comment by daveespo** [comment]
@mshanemc -- thanks for the quick turnaround! I re-ran the build that was failing and it passes on 7.176.1.
