### ISSUE TITLE
domainPartition not respected in new scratch orgs

### ISSUE THREAD

**Issue by toddhalfpenny** [forcedotcom/cli#1792]
### Summary

Setting the `domainPartition` to `"none"` in the _project-scratch.def_ does not disable the "Use partitioned domains" checkbox/setting.
From what I can see in the [docs](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_mydomainsettings.htm) I should be able to influence this setting with this config;
```
   "settings": {
      "myDomainSettings": {
          "domainPartition": "none"
        }
   }
```

### Steps To Reproduce:

1.  Set the `"myDomainSettings"` as per above.
1.  Create a new scratch org

### Expected result

A new scratch org is created with the _"Use partitioned domains"_ checkbox un-checked, and there to be no `.scratch.` in the domain URL.

### Actual result

A new scratch org is created with the _"Use partitioned domains"_ checkbox *checked*, and the domain URL includes `.scratch.`.

### System Information

- Which shell/terminal are you using? bash

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
```
{
  "cliVersion": "sfdx-cli/7.168.0",
  "architecture": "linux-x64",
  "nodeVersion": "node-v16.14.2",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.3 (core)",
    "community 2.0.1 (core)",
    "config 1.4.19 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.2 (core)",
    "generator 2.0.2 (core)",
    "info 2.0.1 (core)",
    "limits 2.0.1 (core)",
    "org 2.2.0 (core)",
    "packaging 1.6.0 (core)",
    "schema 2.1.1 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.13 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.3 (core)",
    "user 2.1.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@salesforce/sfdx-scanner 2.13.8 (user)",
    "salesforce-alm 54.8.1 (core)",
    "sf-package-version-checker 0.0.0 (link) /home/todd/projects/mc/sf-package-version-checker",
    "sfdx-plugin-mobilecaddy 0.0.1 (link) /home/todd/projects/mc/sfdx-plugin-mobilecaddy",
    "sfignore 0.0.1 (user)"
  ],
  "osVersion": "Linux 5.14.0-1054-oem",
  "shell": "bash",
  "rootPath": "/home/todd/.nvm/versions/node/v16.14.2/lib/node_modules/sfdx-cli"
}
```

**Comment by mshanemc** [comment]
I've asked the domain to find out what's expected here.  It's either a bug, or the docs haven't been updated (see how sboxes *don't* support `none` ?  Maybe scratch orgs are like that, too.  

I'll let you know what I find out.

**Comment by toddhalfpenny** [comment]
Thanks for the quick response @mshanemc, I really appreciate it.
And just to clarify we **can** un-check the "Use partitioned domains" checkbox via the UI once the scratch has been created.

**Comment by mshanemc** [comment]
Ahh, I totally sped right past this part: `This field is read-only in the API`.

**Comment by toddhalfpenny** [comment]
Thanks @mshanemc , I had missed that entirely too.
I know this issue is now rightly closed, but wondering if you know of why this might be read-only or if there's scope to modify this (could I perhaps create an Idea)?

**Comment by mshanemc** [comment]
You could definitely create an idea.  

pure speculation: the ability to toggle these in the UI is available for the transition period, and that longer-term these partitions are just on (similar to how mydomain works on any new orgs...you can't undo that).

That allows for manual testing without requiring a breaking mdapi change when it does become read-only.
