### ISSUE TITLE
sfdx force:source:retrieve very slow (5 mins+ for single file)

### ISSUE THREAD

**Issue by willcobbett** [forcedotcom/cli#18]
Trying to retrieve a single file via VSCode with Salesforce Extensions is taking an excessive amount of time. This behaviour has been seen on two different machines (Windows & Mac) over several days so think we can rule out network glitch.

**SFDX CLI version** - sfdx-cli/6.44.0-dead729fb5 (darwin-x64) node-v8.9.4
**VSCode Version** - Version 1.30.2 (1.30.2)

![sfdx](https://user-images.githubusercontent.com/8554725/50975985-c0220780-14e6-11e9-80f2-3e2c92fdadd6.jpeg)

**Comment by willcobbett** [comment]
Hi Thomas,

Please see attached as requested - for info the commands appear to be responding much faster, has anything been done server-side?

[sfdx-console-output.txt](https://github.com/forcedotcom/cli-packages/files/2778164/sfdx-console-output.txt)

[sfdx.log](https://github.com/forcedotcom/cli-packages/files/2778184/sfdx.log)

**Comment by clairebianchi** [comment]
@willcobbett We have escalated this internally and the Server team is working to diagnose and fix the performance. I am going to close this because it is being tracked internally. I will leave this open and report back soon with an update. Thank you for the feedback

**Comment by willcobbett** [comment]
Thanks @clairebianchi

**Comment by clairebianchi** [comment]
@willcobbett We are still working with the server team to make improvements on performance. We made some updates recently on the client side that should have helped. When you get the chance would you let me know if you are seeing faster retrieve times on the most recent version of the CLI? 

I am closing this issue, but know that we are actively looking for more ways to improve preference

**Comment by jatinschneider** [comment]
@clairebianchi this is still very slow, can you help?

**Comment by julesx** [comment]
it's also extremely slow to deploy an individual file.
i sometimes get this as well

`Job ID | 0Af3h000005RKunCAG
SOURCE PROGRESS | ████████████████████████████████████████ | 1/1 ComponentsERROR:  Error: socket hang up
Unhandled rejection Error: socket hang up
    at connResetException (internal/errors.js:610:14)
    at TLSSocket.socketOnEnd (_http_client.js:453:23)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`
