### ISSUE TITLE
The metadata retrieve operation failed: INVALID_TYPE: sObject when adding custom metadata to manifest

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/cli#180]
### Summary

After adding CustomMeta to the project manifest, I can no longer retrieve source, due to a CustomMetadata entity in a managed package.

### Steps To Reproduce:

1.  Install zendesk managed package (It likely works with other managed packages which expose custom metadata
1.  Add CustomMetadata to project manifest
```
   <types>
        <members>*</members>
        <name>CustomMetadata</name>
    </types>
```
1. run `sfdx force:source:retrieve --manifest my/project/manifest/package.xml`

### Expected result

It would retrieve all custom metadata

### Actual result
Command fails:
```
ERROR running force:source:retrieve:  The metadata retrieve operation failed: INVALID_TYPE: sObject type 'Zendesk__Zendesk_Global_OAuth_Client__mdt' is not supported.
```

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
7.23.1-ced0ec4940

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.13.1 (core)
├─ force-language-services 46.18.0 (core)
└─ salesforce-alm 46.17.0 (core)

**OS and version**:

osx 10.14.5

**Comment by idanblich** [comment]
Look like API issue happen also on workbench see img 

![image](https://user-images.githubusercontent.com/1132993/65252783-3b21d000-db02-11e9-8b8f-d6e451448472.png)

**Comment by soleger** [comment]
This issue is being tracked in the following Known Issue:

https://success.salesforce.com/issues_view?Id=a1p3A0000003ek8

**Comment by clairebianchi** [comment]
@ChuckJonas This is a known issue owned by another team. I will pass on your comments, but close this issue
