### ISSUE TITLE
[Campaign] Object Feed Tracking not enabled in build org

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#1804]
### Summary
Package version creation fails when building Campaign fields with feed tracking enabled, that depends on another package that contains the Campaign object. 

I have only tested/reproduced this error with the Campaign object. Unsure whether this is the case for other objects as well. 

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/petter-eikeland/dreamhouse-lwc)

1. Create new folder **campaign** and add the Campaign object with **enableFeeds=true** and custom field "Test_Field__c" with **trackFeedHistory=true**
1. Create a new package using `sfdx force:package:beta:create -n campaign -r campaign -t Unlocked -v myhuborg`
1. Successfully create new version of campaign package using `sfdx force:package:beta:version:create -p campaign -w 10 -x -v myhuborg`
1. Create second folder **campaign-field**. Add Campaign field "Test_Field_2__c" with **trackFeedHistory = true**
1. Create second package using `sfdx force:package:beta:create -n campaign-field -r campaign-field -t Unlocked -v myhuborg`
1. Add campaign package as dependency to campaign-field package
1. Create version of campaign-field package using `sfdx force:package:beta:version:create -p campaign-field -w 15 -x -v myhuborg`

### Expected result
A new package version of campaign-field is successfully created as feed tracking for the Campaign object is set/installed by the campaign package. 

### Actual result
Package version build fails with the following exception: 
`ERROR running force:package:beta:version:create:  Package version creation failed with unknown error. Campaign.Test_Field_2__c: The entity: Campaign does not have feeds enabled`

### System Information
 ```
{
  "cliVersion": "sfdx-cli/7.176.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.12.0",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 19.7.3 (user)",
    "@oclif/plugin-autocomplete 1.3.5 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.17 (core)",
    "@oclif/plugin-not-found 2.3.7 (core)",
    "@oclif/plugin-plugins 2.1.6 (core)",
    "@oclif/plugin-update 3.0.6 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.12 (core)",
    "@oclif/plugin-which 2.1.1 (core)",
    "alias 2.1.7 (core)",
    "apex 1.3.0 (core)",
    "auth 2.2.19 (core)",
    "community 2.0.14 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.3 (core)",
    "data 2.1.7 (core)",
    "generator 2.0.9 (core)",
    "info 2.2.4 (core)",
    "limits 2.0.10 (core)",
    "org 2.2.11 (core)",
    "packaging 1.10.1 (core)",
    "schema 2.1.12 (core)",
    "signups 1.2.11 (core)",
    "source 2.3.0 (core)",
    "telemetry 2.0.2 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.4 (core)",
    "user 2.1.16 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.3 (core)",
    "sfdmu 4.17.6 (user)",
    "sfpowerkit 6.0.0 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/[username]/.local/share/sfdx/client/7.176.1-458b658"
}

**Comment by mshanemc** [comment]
@petter-eikeland thanks for testing the beta!  Do the original commands work (meaning something is wrong/different with the beta code) or is it broken on both?

**Comment by petter-eikeland** [comment]
@mshanemc Thanks for swift response! 

Seems like its broken on both. Output:

 ```
sfdx force:package:version:create -p campaign-field -w 20 -x -v myhuborg 
 ›   Warning: We no longer maintain the current implementation of the "force:package:version:create" command. You should instead use the "force:package:beta:version:create" command, which is functionally the same. If you run into 
 ›   issues, file a report against the "force:package:beta:version:create" command on https://github.com/forcedotcom/cli/issues.
Dependency on package campaign was resolved to version number 0.1.0.1, branch null, 04t090000003oDwAAI.
Request in progress. Sleeping 30 seconds. Will wait a total of 1200 more seconds before timing out. Current Status='Initializing'
Request in progress. Sleeping 30 seconds. Will wait a total of 1170 more seconds before timing out. Current Status='Initializing'
Request in progress. Sleeping 30 seconds. Will wait a total of 1140 more seconds before timing out. Current Status='Verifying dependencies'
ERROR running force:package:version:create:  Campaign.Test_Field_2__c: The entity: Campaign does not have feeds enabled

```

**Comment by mshanemc** [comment]
that's not good news (CLI problems are easier to fix).  I can log a bug and hand it off to the packaging team, but it helps a lot if you can also open a case so they can prioritize.

**Comment by petter-eikeland** [comment]
Response from Salesforce Support Team:

"We cannot package the standard object settings. The rule for packaging is that you cannot package standard components and settings whereby two packages could package the same thing with conflicting values.

For example, if in package A you enable history tracking on Contact -> Account Name, and in package B Contact -> Account Name has history tracking disabled, it creates a conflict, so we don't allow those properties to be packaged.

So to answer the first question, any standard object setting could create such a conflict so should not be allowed to be packaged. For the second question, there are 2 scenarios we think you're raising.

1) You create a custom field on a standard object and enable history tracking for that custom field. The fact that you can't package that works as designed, as it's a limitation of the metadata format. In my opinion that could be considered as a new feature request.

There is also a Known Issue created for this: 
https://trailblazer.salesforce.com/issues_view?Id=a1p3A000001SHEU&_ga=2.236252098.218888078.1669275733-1801365879.1669275733"
