### ISSUE TITLE
sfdx force:source:deploy throwing error Expected source files for type 'StaticResource'

### ISSUE THREAD

**Issue by arabinda85** [forcedotcom/cli#1809]
**Summary**
When trying to deploy/validate through force:source:deploy , its throwing error /force-app/main/default/staticresources/XYZ.resource-meta.xml: Expected source files for type 'StaticResource'

**Steps To Reproduce:**
Run Command For Source Validation

sfdx force:source:deploy --checkonly -w 500 -x  manifest\feature\test_package.xml --targetusername  [test@testuser.com](mailto:test@testuser.com) -l RunSpecifiedTests -r MainControllerTest

**Expected result**

Source should get validate against the target org

**Actual result**

ERROR running force:source:deploy: [C:\NovRepo\Nov14\new_repository\force-app\main\default\staticresources\XYZ.resource-meta.xml](file:///C:/NovRepo/Nov14/new_repository/force-app/main/default/staticresources/XYZ.resource-meta.xml): Expected source files for type 'StaticResource'

**System Information**
Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
A: powershell 

sfdx version --verbose --json

```
{

 "cliVersion": "sfdx-cli/7.172.0",

 "architecture": "win32-x64",

 "nodeVersion": "node-v16.17.1",

 "pluginVersions": [

  "@oclif/plugin-autocomplete 1.3.1 (core)",

  "@oclif/plugin-commands 2.2.0 (core)",

  "@oclif/plugin-help 5.1.14 (core)",

  "@oclif/plugin-not-found 2.3.3 (core)",

  "@oclif/plugin-plugins 2.1.1 (core)",

  "@oclif/plugin-update 3.0.2 (core)",

  "@oclif/plugin-version 1.1.2 (core)",

  "@oclif/plugin-warn-if-update-available 2.0.6 (core)",

  "@oclif/plugin-which 2.1.0 (core)",

  "alias 2.1.5 (core)",

  "apex 1.2.0 (core)",

  "auth 2.2.13 (core)",

  "community 2.0.3 (core)",

  "config 1.4.21 (core)",

  "custom-metadata 2.0.1 (core)",

  "data 2.1.4 (core)",

  "generator 2.0.5 (core)",

  "info 2.1.9 (core)",

  "limits 2.0.5 (core)",

  "org 2.2.7 (core)",

  "packaging 1.9.4 (core)",

  "schema 2.1.10 (core)",

  "signups 1.2.7 (core)",

  "source 2.0.17 (core)",

  "telemetry 2.0.2 (core)",

  "templates 55.1.0 (core)",

  "trust 2.0.4 (core)",

  "user 2.1.10 (core)",

  "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",

  "salesforce-alm 54.8.1 (core)"

 ],

 "osVersion": "Windows_NT 10.0.18363",

 "shell": "cmd.exe",

 "rootPath": "[****/Local//sfdx//client//7.172.0-1aa6bdf)"

}
```

**Comment by mshanemc** [comment]
if you're getting an error on `/force-app/main/default/staticresources/XYZ.resource-meta.xml` it's not finding what it expects
* a matching file (ex `staticresources/XYZ.css` )
* a folder of files named `XYZ` 

Then also check that the folder/file isn't empty or being ignored by `.forceignore`

**Comment by faradeen-ja** [comment]
#1809   @arabinda85 
It has to do with the way you are referencing to your static resource file you uploaded to Static Recourses, as salesforce comes with almost 11 resource types for import, please check example below if your reference is correct.  

## Accessing the static resource directory  
`fontawesome.zip
➡️fontawesome.folder
➡️css.folder
➡️font-awesome.min.css `

`✅loadStyle(this, fontawesome+'/fontawesome/css/font-awesome.min.css')`



____________________________________
## In code
```javascript
import { LightningElement } from 'lwc';
import {loadStyle} from 'lightning/platformResourceLoader'
import fontawesome from '@salesforce/resourceUrl/fontawesome'  // import our font awesome library from Salesforce Static Resources in quick find
export default class MemoryGameInLwc extends LightningElement {



    renderedCallback(){ //renders 3rd party libraries

        if(this.isLibLoaded){
            return
        }else{
            loadStyle(this, fontawesome+'/fontawesome/css/font-awesome.min.css') // go to font awesome folder directory and select the file with extension 
            .then(() => {
                console.log('font awesome library loaded successfully') // check to see if font awesome is loading...and if available
            }).catch((error) =>{
                console.error(error)
            })
            this.isLibLoaded = true

        }

    }


```
#1809
+ I hope this was useful :)
