### ISSUE TITLE
SFDX Pull & Retrieve not populating XML with UI Option - "Auto add to custom report type"

### ISSUE THREAD

**Issue by gitmevg** [forcedotcom/cli#1812]
### Summary

When we do an SFDX Pull or Retrieve for a new field created in Scratch Org/Sandbox it doesn't pull any markup of UI option - "Auto add to custom report type" which is a big downside of using SFDX for Deployment Purpose as this is causing a shift in Source of Truth for a critical Metadata

**Comment by peternhale** [comment]
@gitmevg would you please provide more details surrounding your issue. Ideally a sample project that reproduces the issue. Thank you
