### ISSUE TITLE
Cannot push from VS Code after sf deploy metadata

### ISSUE THREAD

**Issue by phardaker** [forcedotcom/cli#1815]
### Summary

Push source to org failed to run from VS Code.

### Steps To Reproduce:

1.  Simple sfdx project with HelloWorld Apex class.
2. Clean scratch org.
3. sf deploy metadata
4. Open in VS Code
5. Edit HelloWorld and hit CMD S
6. Push source to org failed to run from VS Code

### Expected result

Should be able to push from VS Code.

### Actual result

We couldn’t push your source due to conflicts. Make sure that you want to overwrite the metadata in your org with your local files, then run "SFDX: Push Source to Default Scratch Org and Override Conflicts".

### System Information

- Which shell/terminal are you using? (e.g. Git Bash on Windows)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
	- sfdx-cli/7.82.1-0 win32-x64 node-v18.12.0
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here
{
  "cliVersion": "@salesforce/cli/1.38.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.12.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.1 (core)",
    "config 2.3.2 (core)",
    "deploy-retrieve 1.5.2 (core)",
    "env 1.5.0 (core)",
    "functions 1.13.1 (core)",
    "generate 1.0.14 (core)",
    "info 2.0.1 (core)",
    "login 1.1.1 (core)",
    "telemetry 2.0.0 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19045"
}

_Feel free to attach a screenshot_.

**Comment by peternhale** [comment]
@phardaker I see that you are using older versions of sfdx (v7.82.1) and sf (v1.38.0). I was wondering if you have had an opportunity to try this on a more recent version of each?

**Comment by peternhale** [comment]
@phardaker I tried to reproduce on nix and windows 11 and cannot reproduce the error you are seeing. My testing was done with the latest versions of sfdx and sf.

**Comment by phardaker** [comment]
Thank you I will test this myself after upgrading tomorrow. On 23 Nov 2022, at 21:21, peternhale ***@***.***> wrote:﻿
@phardaker I tried to reproduce on nix and windows 11 and cannot reproduce the error you are seeing. My testing was done with the latest versions of sfdx and sf.

**Comment by phardaker** [comment]
Working in latest versions of cli's, many thanks.
