### ISSUE TITLE
Compilation error on "@testVisible" method reference in "Test.isRunningTest()" block

### ISSUE THREAD

**Issue by RemyVULTAGGIO** [forcedotcom/cli#1816]
### Summary

An unexpected compilation error occurs when trying to push a non-Test Apex Class using "@testVisible" method reference inside a "Test.isRunningTest()" block.

### Steps To Reproduce:

This is a very simple reproducible example.

1.  In an existing or new sfdx project, create an Apex Class named ClassA :

public with sharing class ClassA {
    public ClassA() {
        if ( Test.isRunningTest() ) {
            ClassB.myMethod();
        } else {
            // Whatever
        }
    }
}

2.  Create an other Apex Class named ClassB :

public with sharing class ClassB {
    public ClassB() {

    }

    @testVisible
    private static void myMethod() {
        // Whatever
    }
}

3. sfdx force:source:push

### Expected result

sfdx force:source:push
*** Pushing with SOAP API v55.0 ***
DEPLOY PROGRESS | ████████████████████████████████████████ | 1/1 Components
Updating source tracking... done

=== Pushed Source

 STATE   FULL NAME                        TYPE      PROJECT PATH
 ─────── ──────────────────────────────── ───────── ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
 Added ClassA                           ApexClass force-app\main\default\classes\ClassA.cls
 Added ClassA                           ApexClass force-app\main\default\classes\ClassA.cls-meta.xml
 Added ClassB                           ApexClass force-app\main\default\classes\ClassB.cls
 Added ClassB                           ApexClass force-app\main\default\classes\ClassB.cls-meta.xml

### Actual result

sfdx force:source:push
*** Pushing with SOAP API v55.0 ***
DEPLOY PROGRESS | ████████████████████████████████████████ | 0/0 Components
Check the order of your dependencies and ensure all metadata is included.

=== Component Failures [1]

 Type  Name                             Problem
 ───── ──────────────────────────────── ──────────────────────────────────────────────────────────────────── 
 Error ClassA Method is not visible: void ClassB.myMethod() (4:20)

ERROR running force:source:push:  Push failed.

### System Information

- Which shell/terminal are you using? Powershell 7

- sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.175.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.12.0",
  "pluginVersions": [
    ...
  ],
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\...\\AppData\\Local\\sfdx\\client\\7.175.0-a62760c"
}

**Comment by peternhale** [comment]
@RemyVULTAGGIO the Test.isRunningTest() method is not an access check to the content inside the {} during compilation, but just returns the state of "are tests currently running?" The `@TestAccessible` annotation marks class members so an Apex Test can access those members when a test runs.

If you want to guard the execution of ClassB.myMethod() using Test.isRunningTest() in ClassA constructor you will need to change the visibility of ClassB.myMethod() to public.

**Comment by RemyVULTAGGIO** [comment]
Hi @peternhale ,

Thanks for your answer.

When you say "the Test.isRunningTest() method is not an access check to the content inside the {} during compilation", that's the whole point of submitting this issue.

There should be a way to call a "@testVisible" method outside a Test class but inside a "Test.isRunningTest()" block.

Regarding your answer considering this is not a bug, maybe this issue could be requalified as an improvement or new feature ?

What do you think about it?

**Comment by daveespo** [comment]
@RemyVULTAGGIO  -- what you're asking for is a new Apex feature, not a CLI bug or enhancement. The standard path for requesting such things is to file an issue on the IdeaExchange:

https://ideas.salesforce.com/s/search#t=All&sort=relevancy

**Comment by peternhale** [comment]
@RemyVULTAGGIO The isRunningTest allows one to check the running context of Apex, it is not a means to violate the class/method access modifiers outside a test. As Dave suggested, if you would like to file a feature request for the Apex language, please visit IdeaExchange to make that request.

**Comment by RemyVULTAGGIO** [comment]
> it is not a means to violate the class/method access modifiers outside a test. 

@peternhale, that's clearly not the point 


> what you're asking for is a new Apex feature, not a CLI bug or enhancement.

@daveespo, you're right, my bad.


Thanks again, both !   :-)
