### ISSUE TITLE
Wrong Exit code of sf env create scratch command

### ISSUE THREAD

**Issue by galfons** [forcedotcom/cli#1821]
### Summary

Wrong Exit code of sf env create scratch command irrespective of outcome

### Steps To Reproduce:

When executing

sf env create scratch -f config/project-scratch-def.json -y 30 -a $ORG_ALIAS -d
echo $?

it always returns exit code 1 whatever the results of scratch org creation is.

**Repository to reproduce:** 

N/A

### Expected result

Exit code 1 in case of failure
Exit code 0 in case of success

### Actual result

Always exit code 1

### System Information

git bash

{
  "cliVersion": "@salesforce/cli/1.54.1",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.12.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.2 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.16 (core)",
    "@oclif/plugin-not-found 2.3.8 (core)",
    "@oclif/plugin-plugins 2.1.7 (core)",
    "@oclif/plugin-search 0.0.2 (core)",
    "@oclif/plugin-update 3.0.3 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-which 2.2.1 (core)",
    "deploy-retrieve 1.6.11 (core)",
    "env 1.5.9 (core)",
    "functions 1.14.2 (core)",
    "generate 1.0.31 (core)",
    "info 2.2.7 (core)",
    "login 1.1.9 (core)",
    "settings 1.1.6 (core)",
    "sobject 0.0.28 (core)",
    "telemetry 2.0.3 (core)",
    "trust 2.1.0 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\user\\AppData\\Local\\sfdx\\client\\7.177.1-617a284\\sf"
}
### Additional information

N/A

**Comment by peternhale** [comment]
@galfons we have been unable to reproduce the issue on Windows w/ git-bash or other platforms.

Could you run the command again with debug enabled.

`DEBUG=* sf env create scratch -f config/project-scratch-def.json -y 30 -a $ORG_ALIAS -d`

Please share the results.

**Comment by galfons** [comment]
Sharing last lines of debug.

I would have expected 0 not 1

......
✓ Deploy Settings
Done

Your scratch org is ready.
  config start postrun hook +6m
  config postrun hook done +3ms
  sfdx:telemetry@2.0.3 Spawning "C:\Users\giualfon\AppData\Local\sfdx\client\7.177.1-617a284\bin\node.exe C:\Users\giualfon\AppData\Local\sfdx\client\7.177.1-617a284\sf\node_modules\@sf\telemetry\processes\upload C:\Users\giualfon\AppData\Local\sf C:\Users\giualfon\AppData\Local\Temp\sfdx-telemetry\telemetry-f4f853443a2c667b6a97a565992c8c98bb6cf73e.log" +6m 

giualfon@giualfonw MINGW64 ~/dx/arx-crm (beppe)
$ echo $?
1

**Comment by peternhale** [comment]
@galfons could I get all of the debug output please. Please redact any information you do not want to share.

**Comment by peternhale** [comment]
@galfons I also wondering if you could try this in a different shell. [We don't recommend using Linux terminal emulators](https://developer.salesforce.com/docs/atlas.en-us.216.0.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm).
