### ISSUE TITLE
sfdx force:org:shape:list throwing "Error authenticating with the refresh token due to: grant type not supported"

### ISSUE THREAD

**Issue by brianocoleman** [forcedotcom/cli#1822]
### Summary

Trying to use an org shape to create a Scratch org. 
I can create the org shape but i cannot seem to get the "sfdx force:org:shape:list" to work
I keep getting the "Error authenticating with the refresh token due to: grant type not supported" message

### Steps To Reproduce:

1/ Connect to DevHub
2/ Run sfdx force:org:shape:list command in VS Code

### Expected result

List of existing org shapes

### Actual result

Getting the following error
ERROR running force:org:shape:list:  Error authenticating with the refresh token due to: grant type not supported

### System Information

bash

{
  "cliVersion": "sfdx-cli/7.177.1",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.12.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.5 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.18 (core)",
    "@oclif/plugin-not-found 2.3.8 (core)",
    "@oclif/plugin-plugins 2.1.6 (core)",
    "@oclif/plugin-update 3.0.6 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.13 (core)",
    "@oclif/plugin-which 2.2.0 (core)",
    "alias 2.1.8 (core)",
    "apex 1.3.0 (core)",
    "auth 2.2.21 (core)",
    "community 2.0.15 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.4 (core)",
    "data 2.1.10 (core)",
    "generator 2.0.10 (core)",
    "info 2.2.7 (core)",
    "limits 2.0.11 (core)",
    "org 2.2.12 (core)",
    "packaging 1.10.6 (core)",
    "schema 2.1.13 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.4 (core)",
    "telemetry 2.0.3 (core)",
    "templates 55.1.0 (core)",
    "trust 2.1.0 (core)",
    "user 2.1.17 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.3 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\xxxx\\AppData\\Local\\sfdx\\client\\7.177.1-617a284"
}
### Additional information

![image](https://user-images.githubusercontent.com/73656511/203649086-2cb89413-f895-48fa-99ad-b928e8018fd0.png)

**Comment by peternhale** [comment]
@brianocoleman the error you are seeing is coming from the org uatpv from your list. The `force:org:shape:list` will try and connect to all of the orgs you have authenticated to before to load the list of org shapes present in each. To work around the error you are seeing, re-authenticate to uatpv,  using auth:logout then login, or logout of the org uatpv, or run `sfdx force:org:list --clean`.

I will log a bug against `force:org:shape:list` so that auth errors are handled better when situations like this occur.

**Comment by cristiand391** [comment]
Fixed in Feb. 2023:
https://github.com/salesforcecli/plugin-signups/pull/216
