### ISSUE TITLE
force:source:retrieve -x will not retrieve managed components next to wildcard asterisk

### ISSUE THREAD

**Issue by jh480** [forcedotcom/cli#1825]
### Summary

sfdx force:source:retrieve with a manifest will ignore managed components above or below wildcards.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Install any managed package, if none present.
1.  In a manifest file (like package.xml), for a managed component (eg. a prefixed ApexClass), add a members line for such a managed component alongside the wildcard line (`<members>*</members>`), as in the image below (members order is not relevant).
1. Run `sfdx force:source:retrieve -x path/to/package.xml`.

### Expected result

sfdx should retrieve, as per manifest, both the managed component and all unmanaged components.

### Actual result

sfdx retrieves only unmanaged components.

### System Information

Using VisualStudio's Powershell v5.1.19041.1682.

{  
  "cliVersion": "sfdx-cli/7.163.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v16.16.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.4 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.0 (core)",
    "apex 1.1.0 (core)",
    "auth 2.2.3 (core)",
    "community 2.0.0 (core)",
    "config 1.4.17 (core)",
    "custom-metadata 2.0.0 (core)",
    "data 2.1.1 (core)",
    "generator 2.0.2 (core)",
    "info 2.0.1 (core)",
    "limits 2.0.1 (core)",
    "org 2.0.7 (core)",
    "schema 2.1.1 (core)",
    "signups 1.2.0 (core)",
    "source 2.0.11 (core)",
    "telemetry 2.0.0 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.3 (core)",
    "user 2.1.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.0 (core)",
    "salesforce-alm 54.7.1 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19044"
}

### Additional information

JFTR, retrieval with the _Ant Migration Tool_ or _workbench.developerforce.com_ works as expected.
Also, retrieval without a wildcard will fetch the managed components just fine, even alongside (also explicitely listed) unmanaged components.

![image](https://user-images.githubusercontent.com/113723451/190788843-cd9f59e0-f0d2-4bae-9458-9a4320017f61.png)

**Comment by peternhale** [comment]
@jh480 I read your original issue for vscode. I was wondering if you could try fetching the metadata using the `sfdx force:mdapi:retrieve` command? I would like to see if md retrieve works as expected.

Also, could you try the same using the most recent version of sfdx-cli 7.178.0?

**Comment by jh480** [comment]
@peternhale I tried both commands with sfdx-cli 7.178.0, both retrieve only the unmanaged components.

I thought for a minute that the ant library might be doing something extra, but at least workbench.developerforce.com can also get a hold of the unmanaged component.

**Comment by peternhale** [comment]
@jh480 I don't believe it is possible to fetch managed package components from a org where the package is installed. I tried doing what your described outside of the CLI, using the metadata retrieve API directly. I get the same results as you, components from the package are not retrieved.

The only way I could get a managed package component was to modify it in a scratch org and the do a source pull.

**Comment by jh480** [comment]
@peternhale, for one, retrieving alongside wildcards actually works with Ant Migration Tool and Workbench; it's why I came to believe this to be a bug with the CLI.
Also, retrieval of managed components _without_ wildcard works perfectly fine with both `force:source:retrieve` and `force:mdapi:retrieve`, even along with (also explicitely listed) unmanaged components.
This is actually how I currently work around this limitation, by explicitely listing every single component. The bother then is keeping the manifest up to date, as unmanaged components come and go much more quickly.

**Comment by peternhale** [comment]
@jh480, my apologies, you are correct. How a package.xml that contains a wildcard and an explicit member entry for a managed component  is handled differently between dx commands and MD API retrieve (workbench). It seems the wildcard is given deference when multiple member entries are present in package.xml.

I'll mark this as a bug so it can be investigated further.

**Comment by shetzel** [comment]
@jh480 - I reproduced what you are seeing.  However, the CLI is doing the correct thing.  This appears to be a server side issue.  When using the command `sfdx force:mdapi:retrieve -k package.xml -r outputDir` the CLI simply makes a request to the metadata API SOAP endpoint with the provided manifest and polls for the response, then writes the files from the response.  So my interpretation of the behavior is either:

1. With explicit unpackaged and managed package apex classes defined in a manifest the server is incorrectly sending both managed and unpackaged metadata.  Per [the docs here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/file_based_zip_file.htm): "<fullName> contains the name of the server-side package. If no <fullName> exists, the package.xml defines a client-side unpackaged package."

-OR-

2. That doc is wrong/misleading and the wildcard unpackaged metadata usecase should be working.

The best course of action to get this fixed with that team (the server side team who owns this) is to open a support case with them.  I'll close this issue since there is nothing the CLI can do, but you can reference this with support for the new case.

**Comment by jh480** [comment]
@shetzel, how does this explain the discrepancy between the CLI and ant/Workbench?

Please see https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/collections/componentSet.ts#L392,
especially the comment "if the type doesn't support mixed wildcards and specific names, overwrite the names to be a wildcard".

As per https://github.com/forcedotcom/source-deploy-retrieve/blob/main/HANDBOOK.md#breaking-down-a-metadata-type-entry, _supportsWildcardAndName_ supposedly is only defined true for CustomObject and DigitalExperienceBundle.

I know I may be making a few leaps here, but the zipped package.xml returned by `sfdx force:mdapi:retrieve -k package.xml -r outputDir` indeed has stripped out ApexClass members other than the wildcard, but CustomObject on the other hand is left as is defined per the package input. jftr, Workbench leaves both sections as is.

**Comment by shetzel** [comment]
@jh480 - my mistake!  I was sure the `force:mdapi:retrieve` command did not use a ComponentSet from SDR and instead just used the exact manifest file directly.  I knew about that behavior but didn't think it applied in this case.  Simply adding supportsWildcardAndName to ApexClass in metadataRegistry.json provides the expected behavior.  I'll try to get that in to the release candidate this week.  Thanks for pointing that out and sorry for the bad information!

**Comment by jh480** [comment]
@shetzel, thank you, but it's not just ApexClass.
Checking my ant manifest, the most interesting to me are (those with moving/profile parts):
- ApexClass
- ApexPage
- CustomApplication
- CustomLabel (probably; I use this for managed and CustomLabels for unmanaged)
- CustomMetadata
- CustomObjectTranslation (unsure; wildcard suffices for everything mentioned in CustomObject)
- CustomTab
- Flow
- FlowDefinition (technically redundant to Flow)
- GlobalValueSet
- GlobalValueSetTranslation
- Layout
- Letterhead (unsure)
- PathAssistant
- QuickAction
- RemoteSiteSetting (unsure)
- ReportType
- SharingRules (pretty sure)
- Workflow

I'm very sure (most of) these support wildcard with managed components, but technically, there are likely more.
Though wether _supportsWildcardAndName_ should get turned around to being generally permissive, I couldn't say.

**Comment by shetzel** [comment]
@jh480 - thanks for the data.  This is all very useful.  The `supportsWildcardAndName` registry property was added with [this PR](https://github.com/forcedotcom/source-deploy-retrieve/pull/464) 18 months ago.  The original intent was to support retrieving both CustomObjects and StandardObjects using a wildcard for CustomObjects and by name of specific StandardObjects.  This usecase is similar but different.  However, I think we can use the same registry property for this.  I have no idea what types support it.  I suspect it's the same list that supports wildcard usage, which is unfortunately not available from a describemetadata call (see [this old issue](https://github.com/forcedotcom/cli/issues/313)).

I can start with the list you noted and see how our tests respond as a first step.  I'm concerned it might have unintended affects with deploy so testing this will be important.  I don't have an ETA for this work yet.

**Comment by jh480** [comment]
@shetzel No worries.

Deploying some of the managed components (like hidden Apex code) will indeed fail, though it can't be helped if one wants to retrieve profile permissions for them.

fyi, the API's _listMetadata_ will return managed Layout, QuickAction, CustomMetadata & GlobalValueSetTranslation components without the necessary namespace prefixes, you will need to add them manually.
(#1697)

**Comment by WillieRuemmele** [comment]
with https://github.com/forcedotcom/source-deploy-retrieve/pull/894 we've hopefully fixed the issue. This has made it's way through our `nightly`/`latest-rc` process, and should now be available under the `latest` tag

**Comment by jh480** [comment]
Looking good, thanks a bunch!
