### ISSUE TITLE
Decomposed source containing Record Types across multiple package directories are not recomposed back into package.zip properly

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#183]
### Summary

We are building a 2GP managed package and we have a SFDX project defined with 2 package directories. The first package directory is `force-app` and it's the default. This is the metadata that we'd like to include in our managed package. The second package directory is `unpackaged` and is all of the other ancillary metadata we need in our scratch orgs in order to test and develop the package.

The bug we're seeing is that when a RecordType is defined for an object (such as Contact), it is not properly composed back into the package.zip that's pushed to org via `force:source:push`

I have created a bare bones project to demonstrate the problem:

https://github.com/patronmanager/two-package-directories

In the `force-app` directory is the one field on Contact that we want to package.

In the `unpackaged` directory is an additional field that we DON'T want to package along with a RecordType (also DON'T want to package)

If you try to create a source org with this project, you will get an error upon deployment:

```
PROJECT PATH                                                                   ERROR
─────────────────────────────────────────────────────────────────────────────  ─────────────────────────────────────────────────────────────────────────────────
unpackaged\main\default\layouts\Contact-Contact Layout.layout-meta.xml         In field: field - no CustomField named Contact.MyUnpackagedField__c found (48:26)
unpackaged\main\default\profiles\Custom%3A Sales Profile.profile-meta.xml      In field: recordType - no RecordType named Contact.Patron found (18:29)
unpackaged\main\default\profiles\Custom%3A Support Profile.profile-meta.xml    In field: recordType - no RecordType named Contact.Patron found (18:29)
unpackaged\main\default\profiles\Admin.profile-meta.xml                        In field: recordType - no RecordType named Contact.Patron found (21:29)
unpackaged\main\default\profiles\Custom%3A Marketing Profile.profile-meta.xml  In field: recordType - no RecordType named Contact.Patron found (18:29)
ERROR running force:source:push:  Push failed.
```

However, that masks the true root cause of the problem. I enabled the `SFDX_MDAPI_TEMP_DIR` environment variable and you'll see that the `package.xml` that's generated correctly contains the reference to the Contact.Patron record type. However, the Contact.object metadata file does not contain the definition.

https://github.com/patronmanager/two-package-directories/blob/master/mdapi/sdx_mdpkg_1569256561462/package.xml

Also note that the package.xml lists both of the custom fields defined in the project but the Contact.object only enumerates the one:

https://github.com/patronmanager/two-package-directories/blob/master/mdapi/sdx_mdpkg_1569256561462/objects/Contact.object

In short, it's half-working. Either it should error out if this configuration is not supported (not great) or correctly compose the multiple package directories into the proper package.zip

It should be noted that this sort of configuration seems to work correctly for Custom Fields -- i.e. you can define Custom Fields in both of the directories listed in packageDirectories and they will successfully get composed back into Contact.object before being sent up. 

### Steps To Reproduce:

1. Create a blank SFDX project and create a scratch org
1. Create two new custom fields on Contact and define a Record Type -- don't add the new fields to any page layouts nor grant access to the fields or RTs to any Profiles
1. Perform a `force:source:pull` -- note the new metadata files for the custom fields, record types, and Admin profile
1. Move all of the files except 1 of the custom fields into a different package directory and update your sfdx-project.json to reflect that you have 2 package directories
1. Try creating a new scratch org and `force:source:push` your changes 
1. Expected: The new fields and RecordType should be created
1. Actual: Various errors about the RecordType not being defined (see above)

### Additional information

We've tried various things: Deleting the Profiles from the project, etc, but they all result in basically the same flavor of the error: The package.xml is created "properly" but the zip file doesn't contain metadata for the definition of the RecordType

### CLI version

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx plugins --version
sfdx-cli/7.25.3-16d54c01ee win32-x64 node-v10.15.3

sfdx plugins --core
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 46.15.3 (core)
├─ force-language-services 46.22.0 (core)
└─ salesforce-alm 46.20.0 (core)

sfdx-cli 7.25.3 (core)

**OS and version**:
Windows 10 Pro

**Comment by clairebianchi** [comment]
@daveespo We currently do not support multiple package directories in the CLI. We are starting the work to add support in the next release.
