### ISSUE TITLE
`sfdx force:package:beta:list` shows recently deleted packages

### ISSUE THREAD

**Issue by jvg123** [forcedotcom/cli#1834]
`sfdx force:package:beta:list` appears to be showing recently deleted packages.

Whereas the legacy `sfdx force:package:list` does not.

Related issue: when running `sfdx force:package:beta:delete -p <package ID>` on that same recently deleted package, it fails with 
```
ERROR running force:package:beta:delete:  Could not find an alias for the ID <package ID>.
```
which is misleading

Note that running the legacy `sfdx force:package:delete` for the same package ID also shows a misleading message. It says:
```
Successfully deleted the package. <package ID>
```
even when run multiple times

**Comment by iowillhoit** [comment]
Hey @jvg123, thanks for sharing this! I am discussing it with the team and I'll get back to you

**Comment by iowillhoit** [comment]
Alright, got a ticket created to get this sorted out. Thank you for helping us make these beta commands better!

**Comment by WillieRuemmele** [comment]
https://github.com/salesforcecli/plugin-packaging/pull/193 was just merged ✅
