### ISSUE TITLE
sfdx:force:data:record:create and sfdx:force:data:record:update don't allow key=value pairs with quoted strings

### ISSUE THREAD

**Issue by RodEsp** [forcedotcom/cli#1837]
### Summary

If you try to create or update a record using a `key=value` pair that has a quoted string in it, like this `key="this is a 'quote'"`, then `sfdx:force:data:record:create` and `sfdx:force:data:record:update` just error out.

### Steps To Reproduce:

This is a little hard to reproduce because the quotes being passed to the `-v` flag need to be escaped properly in the command line.

Here's an example of a failure on Powershell:
1.  Run `sfdx force:data:record:update -u <yourOrg> -s <SObjectName> -i <SObjectID> -v 'key="this is a "''quote''"'`

### Expected result

This should have updated my SObject's key to have the value `this is a 'quote'`.

### Actual result

The command errors out with a weird message
![image](https://user-images.githubusercontent.com/1084688/206284152-3d53b90f-c98a-42b6-8308-98a04102efcd.png)

### System Information

- Which shell/terminal are you using? Powershell 7

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
```
> sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.179.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v19.0.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.6 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.18 (core)",
    "@oclif/plugin-not-found 2.3.8 (core)",
    "@oclif/plugin-plugins 2.1.6 (core)",
    "@oclif/plugin-update 3.0.6 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.14 (core)",
    "@oclif/plugin-which 2.2.2 (core)",
    "alias 2.1.8 (core)",
    "apex 1.3.0 (core)",
    "auth 2.2.23 (core)",
    "community 2.0.18 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.5 (core)",
    "data 2.1.14 (link) C:\\Users\\rodrigo.espinosa\\git\\salesforcecli\\plugin-data",
    "generator 2.0.12 (core)",
    "info 2.2.9 (core)",
    "limits 2.1.1 (core)",
    "org 2.2.8 (user)",
    "packaging 1.10.8 (core)",
    "schema 2.1.16 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.5 (core)",
    "telemetry 2.0.4 (core)",
    "templates 55.1.0 (core)",
    "trust 2.1.0 (core)",
    "user 2.1.19 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.4 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\rodrigo.espinosa\\nvm\\v19.0.0\\node_modules\\sfdx-cli"
}
```
### Additional information

_Feel free to attach a screenshot_.

**Comment by mshanemc** [comment]
Saves records successfully.  I think it was solved by the same fix as https://github.com/forcedotcom/cli/issues/1820
