### ISSUE TITLE
Salesforce CLI Team on Github over End of Year Holidays

### ISSUE THREAD

**Issue by cromwellryan** [forcedotcom/cli#1838]
Over the end of year holidays, the Salesforce CLI team is adjusting how we monitor and respond to Github activity. These adjustments begin December 19th and will return to normal on January 3rd.

During this time, we will respond to [Salesforce cases](https://help.salesforce.com/s/articleView?id=sf.workcom_contact_support.htm&type=5) as normal. If you have an issue, we'll be here to support your cases. Github issues will be reviewed daily for widespread issues, but we will be slower to respond to individual issues or pull requests.

**Releases & Promotions**
Week of December 15th: Our normal release candidates (RC) and promotion to latest (GA) will take place on Wednesday (`sf`) and Thursday (`sfdx`). 

Week of December 19th: No release candidate will occur, but a promotion of the previous RC will take place. 

Week of Dec 26th: Neither an RC or promotion will take place. 

Week of January 2nd: We will resume our regular schedule of RC and GA.

**Comment by RodEsp** [comment]
Note that the week of January 2nd, there will be no promotion of RC to latest/stable (GA) because there will not be one from the earlier week to promote.
