### ISSUE TITLE
Deploying using `force:source:deploy -m Report` deploys all files with `report` in the name or filepath

### ISSUE THREAD

**Issue by shliachtx** [forcedotcom/cli#184]
### Summary

Deploying using `force:source:deploy -m Report` deploys all files with `report` in the name or filepath

### Steps To Reproduce:

1. create a a static resource or permissionset with Report in the filename or filepath
1.  run `sfdx force:source:deploy -m Report`

### Expected result

Deploy all reports in source control

### Actual result

Deployed all static resources and permission sets with the word `report` in the filepath

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.25.3-16d54c01ee win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
salesforcedx 46.15.3 (core)

**OS and version**:
Windows 10 Pro x64 version 1903

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9300246](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MR86YAG/view)
