### ISSUE TITLE
Illegal Request on force:source:delete

### ISSUE THREAD

**Issue by SoftCreatR** [forcedotcom/cli#1843]
### Summary

`force:source:delete` leads to "Illegal request".

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

Execute `sfdx force:source:delete -m CustomField:Foo.Bar -u Baz`

### Expected result

The field (if existent) should've been deleted.

### Actual result

If the field does not exist, it works as expected:

```
*** Deleting with REST API ***
Deploy ID: 0Af9O000000L5ntSAC

=== Component Failures [1]

 Type    Name                   Problem
 ─────── ────────────────────── ────────────────────────────────────────────────────────
 Warning destructiveChanges.xml No CustomField named: Foo.Bar found

ERROR running force:source:delete:  Deploy failed.
```

But if it exists:

```html
This operation will delete the following metadata in your org:
CustomField:Foo.Bar

Are you sure you want to proceed (y/n)?: y
*** Deleting with REST API ***
ERROR running force:source:delete:
<html>
<body>

<table cellspacing=10>
    <tr>
        <td><span style="font-weight: bold; font-size: 12pt;">Illegal Request</span></td>
    </tr>
    <tr>
        <td>You have sent us an Illegal URL or an improperly formatted request.
        </td>
    </tr>
    <tr>
        <td>

        </td>
    </tr>
</table>



<!-- Body events -->
<script type="text/javascript">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken="null";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>

</body>
</html>


<!--
...................................................................................................
...................................................................................................
...................................................................................................
...................................................................................................
-->
```

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

Powershell 7

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`

```json
{
  "cliVersion": "sfdx-cli/7.181.1",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.12.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.6 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.19 (core)",
    "@oclif/plugin-not-found 2.3.9 (core)",
    "@oclif/plugin-plugins 2.1.7 (core)",
    "@oclif/plugin-search 0.0.4 (core)",
    "@oclif/plugin-update 3.0.7 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.14 (core)",
    "@oclif/plugin-which 2.2.2 (core)",
    "alias 2.1.11 (core)",
    "apex 1.3.0 (core)",
    "auth 2.3.1 (core)",
    "community 2.0.18 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.5 (core)",
    "data 2.1.15 (core)",
    "generator 2.0.12 (core)",
    "info 2.2.11 (core)",
    "limits 2.1.3 (core)",
    "org 2.2.18 (core)",
    "packaging 1.10.10 (core)",
    "schema 2.1.18 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.7 (core)",
    "telemetry 2.0.5 (core)",
    "templates 55.1.0 (core)",
    "trust 2.2.1 (core)",
    "user 2.1.22 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.4 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\NB00132\\AppData\\Local\\sfdx\\client\\7.181.1-05b8719"
}
```

### Additional information

Tried to execute the command with `--verbose`, and `--loglevel debug` but no additional information is returned.

If that helps: It fails on 5 independent sandboxes.

**Comment by iowillhoit** [comment]
Hello @SoftCreatR, I tried to replicate this using Dreamhouse and `sfdx-cli/7.181.1` but was unable to. 
The steps I took:
- Cloned Dreamhouse and went through the README setup
- Opened the org and created a custom field on `Property__c`
- Ran `sfdx force:source:pull`
- Confirmed the field pulled
- Ran `sfdx force:source:delete -m CustomField:Property__c.Test_Custom_Field__c`
- Saw the following:
<img width="910" alt="Screen Shot 2022-12-16 at 3 34 38 PM" src="https://user-images.githubusercontent.com/1715111/208193562-e67b8b05-f204-4a84-b5be-b3fd2a0a3ccd.png">


Try running your command with `DEBUG=*` before the command. Example:
`DEBUG=* sfdx force:source:delete -m CustomField:Property__c.Test_Custom_Field__c`

That will give you a lot more information to debug. If that does not help could you please provide a repo (a fork of Dreamhouse is fine) with step by step instructions to replicate this issue? Thanks!
