### ISSUE TITLE
force:package:beta:install - Does not output the request ID when a timeout occurs

### ISSUE THREAD

**Issue by lesmando24** [forcedotcom/cli#1844]
When installing a package with the old version of "force : package : install", if the package didn't install in time, it gave you the request ID so you could run the report.

```
% sfdx force:package:install --wait 10 --publishwait 10 --package station-configuration@1.0.0-1 -k key -r -u user
Waiting for the package install request to complete. Status = IN_PROGRESS
-- snip --
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
PackageInstallRequest is currently InProgress. You can continue to query the status using

sfdx force:package:install:report -i 0Hf9r0000000TWfCAM -u user
```

But the new command "force : package : beta : install" reports a timeout, it exits and does not give you the the request ID.
I tired to find another command to find the request ID, but was unsuccessful. So I have no idea if the package has finished installing. Besides refreshing the installed packages page until it changes.

```
% sfdx force:package:beta:install --wait 10 --publishwait 10 --package station-configuration2@1.0.48-1 -k key -r -u user 
ERROR running force:package:beta:install:  The client has timed out.
Waiting 10 minutes for package install to complete.... done
```

**Comment by mshanemc** [comment]
we're going to make the new one work like the old one did for timeouts
