### ISSUE TITLE
Unable to set file download behavior on PDF to Execute in browser upon scratch org creation

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#1847]
### Summary

Unable to set file download behavior on PDF to Execute in browser upon scratch org creation. I assume I most likely have a syntax error in my setting below, however, the error messages and documentation suggest to me that it is actually a bug. 

### Steps To Reproduce:

1. Add the following setting to project-scratch-def.json:

```
"fileUploadAndDownloadSecuritySettings": {
	"dispositions": [
		{
			"behavior": "EXECUTE",
			"filetype": "PDF"
		}
	]
}
```
As per documentation: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_fileuploadanddownloadsecuritysettings.htm

2.  Create a scratch org using `sfdx force:org:create`
### Expected result

Scratch org is successfully created with file download behavior on PDF set to "Execute in browser" in File Upload and Download Security Settings

### Actual result
```

ERROR running force:org:create:  A scratch org was created with username test-yjlcci51x1bg@example.com, but the settings failed to deploy due to: 
Error parsing file: 'EXECUTE' is not a valid value for the enum 'FileDownloadBehavior'
```

If I change the behavior value to e.g. HYBRID, I get the following error instead:

```
ERROR running force:org:create:  A scratch org was created with username test-voftn1bvoh2a@example.com, but the settings failed to deploy due to: 
Error parsing file: Element {}filetype invalid at this location in type FileTypeDispositionAssignmentBean

```

### System Information
```
{
  "cliVersion": "sfdx-cli/7.181.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.12.1",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 20.2.11 (user)",
    "@oclif/plugin-autocomplete 1.3.6 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.19 (core)",
    "@oclif/plugin-not-found 2.3.9 (core)",
    "@oclif/plugin-plugins 2.1.7 (core)",
    "@oclif/plugin-search 0.0.4 (core)",
    "@oclif/plugin-update 3.0.7 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.14 (core)",
    "@oclif/plugin-which 2.2.2 (core)",
    "1commerce 0.0.10 (user)",
    "alias 2.1.11 (core)",
    "apex 1.3.0 (core)",
    "auth 2.3.1 (core)",
    "community 2.0.18 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.5 (core)",
    "data 2.1.15 (core)",
    "generator 2.0.12 (core)",
    "info 2.2.11 (core)",
    "limits 2.1.3 (core)",
    "org 2.2.18 (core)",
    "packaging 1.10.10 (core)",
    "schema 2.1.18 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.7 (core)",
    "telemetry 2.0.5 (core)",
    "templates 55.1.0 (core)",
    "trust 2.2.1 (core)",
    "user 2.1.22 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.4 (core)",
    "sfdmu 4.18.2 (user)",
    "sfpowerkit 6.0.1 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/Username/.local/share/sfdx/client/7.181.1-05b8719"
}
```

### Additional information
I have tried many different syntaxes for this setting, but they all fail. I believe the syntax provided above should be in accordance to the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_fileuploadanddownloadsecuritysettings.htm)

**Comment by peternhale** [comment]
@petter-eikeland Sorry the trouble with this.

I was able to get this to work with this structure.
```
        "fileUploadAndDownloadSecuritySettings": {
            "dispositions": [
                {
                    "behavior": "EXECUTE_IN_BROWSER",
                    "fileType": "PDF",
                    "securityRiskFileType": false
                }
            ],
            "noHtmlUploadAsAttachment": true
        }
```
The `noHtmlUploadAsAttachment` is a required field in this setting, so use with caution. The second error you saw with `filetype` is just a typo, should be `fieldType`. This feature belongs to another team, but I will log a bug so they might address the differences between public docs and what it took to get this to work.

**Comment by petter-eikeland** [comment]
Thank you so much for a swift resolution to my issue @peternhale! I will create a case for it and the attached Work Item.

I will keep the Issue open as you attached a Work Item, but feel free to close it.

**Comment by petter-eikeland** [comment]
Update from Salesforce Support:

> As I could see, this issue has been identified as a bug at our end and would be fixed soon in the upcoming patches/releases (Safe Harbor).
