### ISSUE TITLE
`force:source:retrieve` does not list retrieved components

### ISSUE THREAD

**Issue by shliachtx** [forcedotcom/cli#185]
### Summary

When retrieving `Dashboard` or `Report` metadata components using `force:source:retrieve` the retrieved source files are not listed in the results.

### Steps To Reproduce:

1. Create a report (or dashboard) in a production org
1.  run `sfdx force:source:retrieve -m Report:Folder/ReportName`

### Expected result

Retrieve the source file and list the retrieved report

```
=== Retrieved Source
FULL NAME           TYPE     PROJECT PATH
──────────────────  ───────  ────────────────────────────────────────────────────────────────
Folder\ReportName   Report   force-app\main\default\reports\Folder\ReportName.report-meta.xml
```

### Actual result

The report is retrieved but not listed
```
=== Retrieved Source
No results found
```
### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.25.3-16d54c01ee win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
salesforcedx 46.15.3 (core)

**OS and version**:
Windows 10 Pro x64 version 1903

**Comment by clairebianchi** [comment]
@shliachtx This is a known issue that we are going to fix soon. Currently, the workaround is to use a Windows path separator.

**Comment by nramyasri-sf** [comment]
@shliachtx , please do an update to latest cli version and let me know if you are still facing any issues. Thank you.

**Comment by shliachtx** [comment]
I am having the same issue with Documents. Additionally, I can no longer push Dashboards/Reports on windows, I am getting the following error when trying to force push

```ERROR running force:source:push: 
SourceMember WHERE MemberName IN ('SalesDashboards\STkBYlosNyWOHyxeqHqivzIoRXXUMg'
                                 ^
ERROR at Row:1:Column:85
Invalid string literal 'SalesDashboards\STkBYlosNyWOHyxeqHqivzIoRXXUMg'. Illegal character sequence '\S' in string literal.```
