### ISSUE TITLE
Cannot add or edit Custom Metadata Type picklist field values when installed via Unlocked Package

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#1850]
### Summary
Not sure whether this is a bug or a feature request, but it is not possible to add or edit Custom Metadata Type Picklist field values when it is part of an Unlocked Package. However, you are able to edit picklist field values on any standard and custom objects that are part of Unlocked Packages. See screenshots below.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/petter-eikeland/dreamhouse-lwc)

1.  Create a new folder **cmt-picklist-field**, add a Custom Metadata Type, e.g. Test_CMT_Object__mdt, a picklist field picklist_field_1__c for this CMT, and a picklist field picklist_field_1__c for Account
1.  Create a new package using `sfdx force:package:beta:create -n cmt-picklist-field -r cmt-picklist-field -t Unlocked -v myhuborg`
1. Successfully create new version of the cmt-picklist-field package using `sfdx force:package:beta:version:create -p cmt-picklist-field -w 10 -x -v myhuborg`
1. Install package version in myhuborg using `sfdx force:package:beta:install --package 04t090000003oJQAAY -u myhuborg --securitytype=AdminsOnly --wait=10 -a package`

### Expected result
Picklist field values on both Account and Custom Metadata Type can be edited and added.

### Actual result
Picklist field values can be edited and added only on the Account object. Picklist field values on the Custom Metadata Type can neither be added or edited. 

### System Information
```
{
  "cliVersion": "sfdx-cli/7.181.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.12.1",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 20.2.11 (user)",
    "@oclif/plugin-autocomplete 1.3.6 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.19 (core)",
    "@oclif/plugin-not-found 2.3.9 (core)",
    "@oclif/plugin-plugins 2.1.7 (core)",
    "@oclif/plugin-search 0.0.4 (core)",
    "@oclif/plugin-update 3.0.7 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.14 (core)",
    "@oclif/plugin-which 2.2.2 (core)",
    "1commerce 0.0.10 (user)",
    "alias 2.1.11 (core)",
    "apex 1.3.0 (core)",
    "auth 2.3.1 (core)",
    "community 2.0.18 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.5 (core)",
    "data 2.1.15 (core)",
    "generator 2.0.12 (core)",
    "info 2.2.11 (core)",
    "limits 2.1.3 (core)",
    "org 2.2.18 (core)",
    "packaging 1.10.10 (core)",
    "schema 2.1.18 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.7 (core)",
    "telemetry 2.0.5 (core)",
    "templates 55.1.0 (core)",
    "trust 2.2.1 (core)",
    "user 2.1.22 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.4 (core)",
    "sfdmu 4.18.2 (user)",
    "sfpowerkit 6.0.1 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/Username/.local/share/sfdx/client/7.181.1-05b8719"
}
```

### Additional information
**NB!** I have set Field Manageability to SubscriberControlled for the CMT picklist field. However, if I have understood [Field Manageability](https://help.salesforce.com/s/articleView?id=sf.custommetadatatypes_fields.htm&type=5) correctly, it affects whether you are able to change the field value on **CMT records**, not the CMT Picklist field values. 

#### Account Picklist Field Values - Editable
<img width="1193" alt="Account Picklist Field Values" src="https://user-images.githubusercontent.com/97173615/208863054-a87f828e-4fd6-42be-84d9-a182347854bd.png">

#### CMT Picklist Field Values - Non-editable
<img width="1497" alt="Custom Metadata Picklist Field Values" src="https://user-images.githubusercontent.com/97173615/208863102-34e4cab0-c7bc-42be-b1d6-beee2ea329e9.png">

**Comment by peternhale** [comment]
The CLI team does not own this feature. I suggest contacting support with your question.
