### ISSUE TITLE
SFDX JWT authorization failing with Jenkins

### ISSUE THREAD

**Issue by shashi202012** [forcedotcom/cli#1854]
The system cannot find the path specified.
[Pipeline] error
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: hub org authorization failed
Finished: FAILURE

**Comment by cristiand391** [comment]
@shashi202012 please follow the bug report template:
https://github.com/forcedotcom/cli/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
