### ISSUE TITLE
Deploy & Push failing with too many files in zip error

### ISSUE THREAD

**Issue by naveen-agarwal-sf** [forcedotcom/cli#1855]
### Summary

I am trying to push my local changes to remote and it is failing with " too many files in zip". There are only 2 classess and 2 aura file event classes that have changed
I have tried following things:
1. `sfdx force:source:push -f --loglevel=trace` - Push all changes
2. `sfdx force:source:deploy -t -p force-app/main/default/classes/ -f` : Push only apex class (single apex class)

### Steps To Reproduce:
I have my own project running on scratch org so others can't reproduce this.

### Expected result

Local source code should have been deployed

### Actual result

Deployment is failing

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
```
sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.182.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.12.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.6 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.19 (core)",
    "@oclif/plugin-not-found 2.3.9 (core)",
    "@oclif/plugin-plugins 2.1.8 (core)",
    "@oclif/plugin-search 0.0.4 (core)",
    "@oclif/plugin-update 3.0.7 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.15 (core)",
    "@oclif/plugin-which 2.2.2 (core)",
    "alias 2.1.12 (core)",
    "apex 1.3.0 (core)",
    "auth 2.3.3 (core)",
    "community 2.0.18 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.5 (core)",
    "data 2.1.17 (core)",
    "generator 2.0.13 (core)",
    "info 2.2.13 (core)",
    "limits 2.1.3 (core)",
    "org 2.2.19 (core)",
    "packaging 1.10.10 (core)",
    "schema 2.1.19 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.8 (core)",
    "telemetry 2.0.5 (core)",
    "templates 55.1.0 (core)",
    "trust 2.2.2 (core)",
    "user 2.1.22 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.4 (core)"
  ],
  "osVersion": "Darwin 22.2.0",
  "shell": "zsh",
  "rootPath": "/Users/nav/.local/share/sfdx/client/7.182.1-dad7ae3"
}
```

### Additional information
- Project structre
<img width="643" alt="image" src="https://user-images.githubusercontent.com/98874923/209934974-8a8ad74c-8f8c-42d5-a63b-84ed36cc3a56.png">
- Source status

![image](https://user-images.githubusercontent.com/98874923/209935561-ea55792e-fedc-4309-a070-511dcb2c9abf.png)

- Source status dev debug details
`sfdx:force:source:status --dev-debug` attached as [debug.log](https://github.com/forcedotcom/cli/files/10318778/debug.log)

**Comment by naveen-agarwal-sf** [comment]
After enabling env SFDX_MDAPI_TEMP_DIR, I could see it is due to large size of node_modules. Why the heck aura component and apex classes are uploading a whole set of node_modules?

<img width="668" alt="image" src="https://user-images.githubusercontent.com/98874923/209989093-eb7d1121-6fed-47ff-bb4f-f55362bd21cc.png">


**If I remove the apex class, I am able to deploy/push my changes.** Content of my apex class:

```
public with sharing class ExpensesController {
  @AuraEnabled
  public static List<Expense__c> getExpenses() {
    // Check to make sure all fields are accessible to this user
    String[] fieldsToCheck = new List<String>{
      'Id',
      'Name',
      'Amount__c',
      'Client__c',
      'Date__c',
      'Reimbursed__c',
      'CreatedDate'
    };
    Map<String, Schema.SObjectField> fieldDescribeTokens = Schema.SObjectType.Expense__c.fields.getMap();
    for (String field : fieldsToCheck) {
      if (!fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
        throw new System.NoAccessException();
      }
    }
    // OK, they're cool, let 'em through
    return [
      SELECT Id, Name, Amount__c, Client__c, Date__c, Reimbursed__c, CreatedDate
      FROM Expense__c
    ];
  }

  @AuraEnabled
  public static Expense__c saveExpense(Expense__c expense) {
    // Perform isUpdateable() checking first, then
    upsert expense;
    return expense;
  }
}

```

**Comment by cristiand391** [comment]
@naveen-agarwal-sf in the screenshot above you can see that you have a `node_modules` folder **inside** of your sfdx project (`aura/harness/node_modules`). 

Before sfdx can deploy your changes, it needs to convert the files from source format into the Metadata API format, see:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_source_file_format.htm


so sfdx expects that `force/main/default/aura` only contains aura bundles and components, and will zip everything there for deployment (including your `node_modules` folder). 

if you really need to have `node_modules` inside your aura cmp folder, then you should add it to the `.forceignore` file in your project. 
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm

**Comment by naveen-agarwal-sf** [comment]
@cristiand391 My actual code base doesn't have `node_module`s folder inside it. This `node_modules` folder is only coming in metadata folder before upload. That's where my confusion is.

My project structure:
```
harness/force-app/main/default ❯ du -hd 2 .
8.0K	./lwc
  0B	./tabs
  0B	./permissionsets
  0B	./contentassets
  0B	./flexipages
  0B	./triggers
  0B	./staticresources
  0B	./objects
  0B	./layouts
  0B	./applications
  0B	./profiles
 36K	./aura/helloMessageInteractive
 36K	./aura/helloWorld
 32K	./aura/navigate
 36K	./aura/camping
 36K	./aura/expenses
  0B	./aura/harnessApp
 36K	./aura/expenseItem
 36K	./aura/expenseList
 32K	./aura/harness
 36K	./aura/navigateReciever
8.0K	./aura/expenseItemUpdate
 36K	./aura/campingList
 36K	./aura/helloPlayground
 36K	./aura/navigateMain
 36K	./aura/helloHeading
 36K	./aura/campingHeader
 36K	./aura/helloMessage
540K	./aura
548K	.
```

**Comment by cristiand391** [comment]
hmm, that's weird. Do you see that `node_modules` folder when running `git status`?

Maybe it's a symlink? (`du` doesn't follow them). Try running `du -Lhd 4 <project-folder>`

**Comment by naveen-agarwal-sf** [comment]
@cristiand391  Project structure at root
<img width="254" alt="image" src="https://user-images.githubusercontent.com/98874923/210003406-06738697-3277-4e7c-9126-53d58d062264.png">

<img width="601" alt="image" src="https://user-images.githubusercontent.com/98874923/210003445-d13a35f4-de8a-4daf-abe5-6ae97e7d3dff.png">

**Comment by mshanemc** [comment]
@naveen-agarwal-sf what would happen if you...

1. delete the `node_modules` folder from your Aura components
2. run the deployment again?

Is there something in your local setup that's causing that folder to get created and filled with files?  Is there maybe a `package.json` inside that component?  Did you (or some script) perhaps accidentally run `yarn install` from inside that component instead of at the top level of the project?
