### ISSUE TITLE
force:data:soql:query doesn't run on Windows 11

### ISSUE THREAD

**Issue by Astisme** [forcedotcom/cli#1856]
### Summary

When using `sfdx force:data:soql:query -q "SELECT Id FROM Account"` in GitBash on Windows 11, the only response is
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
Which means sfdx is using some command which isn't recognized due to Windows naming system.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1. Open a terminal with GitBash profile
1. Write the above command
1. Read result

### Expected result

The command output

### Actual result

```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

### System Information

- Which shell/terminal are you using? GitBash

```
 sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.180.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.12.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.6 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.19 (core)",
    "@oclif/plugin-not-found 2.3.9 (core)",
    "@oclif/plugin-plugins 2.1.7 (core)",
    "@oclif/plugin-search 0.0.4 (core)",
    "@oclif/plugin-update 3.0.7 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.14 (core)",
    "@oclif/plugin-which 2.2.2 (core)",
    "alias 2.1.10 (core)",
    "apex 1.3.0 (core)",
    "auth 2.3.0 (core)",
    "community 2.0.18 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.5 (core)",
    "data 2.1.13 (core)",
    "generator 2.0.12 (core)",
    "info 2.2.10 (core)",
    "limits 2.1.2 (core)",
    "org 2.2.15 (core)",
    "packaging 1.10.9 (core)",
    "schema 2.1.17 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.7 (core)",
    "telemetry 2.0.5 (core)",
    "templates 55.1.0 (core)",
    "trust 2.1.0 (core)",
    "user 2.1.21 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.4 (core)"
  ],
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\astisme\\AppData\\Local\\sfdx\\client\\7.180.0-d902059"
}
```
### Additional information

A simple fix should be adding quotes before calling the program you are using

**Comment by cristiand391** [comment]
`force:data:soql:query` doesn't call any other program. We got a few similar reports from git-bash users:
https://github.com/forcedotcom/cli/issues?q=is%3Aissue+is+not+recognized+as+an+internal+or+external+command%5C

Can you try passing the query as a file? Maybe it's git-bash not handling the quotes correctly.

1. `echo "SELECT Id FROM Account" > query.txt`
2. `DEBUG=* sfdx force:data:soql:query --soqlqueryfile query.txt`

Setting the `DEBUG` env var will make sfdx print logs.

**Comment by Astisme** [comment]
Using the query from a file works without any issues.

While I was at it, I ran `DEBUG=* sfdx force:data:soql:query -q "SELECT Id FROM Account"` as well and I'm still getting the same wrong output.

**Comment by cristiand391** [comment]
@Astisme This seems to be an issue with how git bash and your terminal handles quoting, see:
https://stackoverflow.com/questions/6714165/powershell-stripping-double-quotes-from-command-line-arguments

It's not that sfdx calls a program by passing an unquoted path, but rather your shell/terminal might strip quotes from args and then make it fail to call the binary (`DEBUG=* sfdx ...` should have thrown some node logs, but it didn't because the process never starts).

I'll close this as git bash for windows isn't supported by sfdx, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm
If you still need to use the CLI with git bash you will need to careful when passing quotes.
