### ISSUE TITLE
Error deploying or retrieving source

### ISSUE THREAD

**Issue by ivannapanchenkoseequent** [forcedotcom/cli#1864]
### Summary

When I tried to retrieve or deploy file using the UI, visual studio code for windows through this exception
Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: 
[https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm]

### Steps To Reproduce:

Click right on the package.xml and select retrieve source from Org
I have reported the same issue a month ago but it was closed without be fixed or resolution.
[https://github.com/forcedotcom/salesforcedx-vscode/issues/4602](url)

### Expected result
I would like to be able to retrieve or deploy from the package.xml

### Actual result
Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

Vs Code :
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Java version 17

Salesforce CLI version : sfdx-cli/7.181.1 win32-x64 node-v18.12.1

Salesforce Extension Pack : v56.5.1     ( I downgrade the version to V.54.8 as per comment but still doesn't work) 
### Additional information
<img width="950" alt="image" src="https://user-images.githubusercontent.com/121065559/211394692-58f7c2c3-f228-421e-bb26-c9588c20e45e.png">

**Comment by tallytsabary** [comment]
I am facing similar issue with the same environment as describe above.
After the deployment - looking at the Schema Builder I see the custom fields, but when I try to use them (for example in SELECT command from the Developer console it says that the field does not exist)
It is blocking my ability to work and provide my team separate dev orgs for their development.
Please do not close this issue.

It was reported several times but never fixed
Thank you

**Comment by cristiand391** [comment]
HI @ivannapanchenkoseequent.

This doesn't seem to be a CLI issue, the error is coming from the Salesforce VSCode extensions:
https://github.com/forcedotcom/salesforcedx-vscode/blob/418fab63c03e7ee6fc8600fffe35f69611e778f5/packages/salesforcedx-vscode-core/src/messages/i18n.ts#L306

This repo is for CLI-related issues only, it seems your issue on the vscode repo got closed by automation so I would ping Randi to get it re-opened.
