### ISSUE TITLE
Salesforce CLI does not pull ExperienceBundle metadata from scratch org

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#1870]
### Summary

The `force:source:pull` command appears to be ignoring ExperienceBundle metadata when executing against a scratch org.

### Steps To Reproduce:

**Repository to reproduce:** [reference-source-pull-not-getting-digexp-issue](https://github.com/ImJohnMDaniel/reference-source-pull-not-getting-digexp-issue)

See the [README.md](https://github.com/ImJohnMDaniel/reference-source-pull-not-getting-digexp-issue/blob/main/README.md) file in the reference project for steps to reproduce issue

### Expected result

`force:source:pull` command should pull ExperienceBundle metadata to the local project

### Actual result

`force:source:pull` command is not pulling ExperienceBundle metadata to the local project

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.).   I am using zsh and bash

- sfdx version info
```
{
  "cliVersion": "sfdx-cli/7.183.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.12.1",
  "pluginVersions": [
    "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.4 (user)",
    "@dx-cli-toolbox/sfdx-toolbox-utils 0.1.3 (link) /Users/john/workspace/_cli-related/sfdx-toolbox-utils",
    "@mshanemc/plugin-streaming 1.1.7 (user)",
    "@mshanemc/sfdx-sosl 1.1.0 (user)",
    "@oclif/plugin-autocomplete 1.3.10 (user)",
    "@oclif/plugin-commands 2.2.2 (core)",
    "@oclif/plugin-help 5.1.20 (core)",
    "@oclif/plugin-not-found 2.3.11 (core)",
    "@oclif/plugin-plugins 2.1.8 (core)",
    "@oclif/plugin-search 0.0.6 (core)",
    "@oclif/plugin-update 3.0.9 (core)",
    "@oclif/plugin-version 1.1.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.16 (core)",
    "@oclif/plugin-which 2.2.4 (core)",
    "alias 2.1.14 (core)",
    "apex 1.3.0 (core)",
    "auth 2.3.8 (core)",
    "community 2.0.18 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.5 (core)",
    "data 2.1.19 (core)",
    "generator 2.0.13 (core)",
    "info 2.3.1 (core)",
    "limits 2.2.0 (core)",
    "org 2.2.20 (core)",
    "packaging 1.12.0 (core)",
    "schema 2.2.2 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.12 (core)",
    "telemetry 2.0.5 (core)",
    "templates 55.1.0 (core)",
    "trust 2.2.4 (core)",
    "user 2.1.24 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@steampunk/sfdx-steampunk-org 0.1.1 (user)",
    "salesforce-alm 54.8.5 (core)",
    "sfdmu 4.23.2 (user)",
    "shane-sfdx-plugins 4.43.0 (user)",
    "soqlx-opener 0.1.12 (user)"
  ],
  "osVersion": "Darwin 22.2.0",
  "shell": "zsh",
  "rootPath": "/Users/john/.local/share/sfdx/client/7.183.0-87b32e0"
}
```

### Additional information

n/a

**Comment by WillieRuemmele** [comment]
thanks as always for the great repo and steps @ImJohnMDaniel - we'll get this fixed 👍

**Comment by WillieRuemmele** [comment]
Hey @ImJohnMDaniel, I spoke too soon, 
`DigitalExperienceBundle`s don't have source tracking enabled until v57.0... which is rolling out now. https://developer.salesforce.com/docs/metadata-coverage/56, as a workaround you can use `force:source:retrieve -m DigitalExperienceBundle`

**Comment by shetzel** [comment]
After discussion with @ImJohnMDaniel, things are working as designed so closing this.
