### ISSUE TITLE
SFDX Org Creation command fails with strange error `DomainNotFound` `The org cannot be found`

### ISSUE THREAD

**Issue by bdovh** [forcedotcom/cli#1874]
### Summary

I have a command in the CI to create a scratch org

sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1 -u Prod --json
Whether I execute it through the CI or manually, I got the following error:

{
  "status": 1,
  "name": "DomainNotFound",
  "message": "The org cannot be found",
  "exitCode": 1,
  "actions": [
    "Verify that the org still exists',",
    "If your org is newly created, wait a minute and run your command again',",
    "If you deployed or updated the org's My Domain, logout from the CLI and authenticate again\",",
    "If you are running in a CI environment with a DNS that blocks external IPs, try setting SFDX_DISABLE_DNS_CHECK=true'"
  ],
  "context": "Create",
  "stack": "DomainNotFound: The org cannot be found\n    at Messages.createError (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/messages.js:446:16)\n    at Connection.isResolvable (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:244:28)\n    at async Connection.retrieveMaxApiVersion (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:190:9)\n    at async Connection.useLatestApiVersion (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:214:32)\n    at async Connection.create (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:98:17)\n    at async Org.init (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/org.js:766:31)\n    at async Org.create (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/kit/lib/creatable.js:57:9)\n    at async scratchOrgCreate (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:174:24)\n    at async Create.createScratchOrg (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:187:68)\n    at async Create._run (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)\nCaused by: MyDomainResolverTimeoutError: The client has timed out.\n    at PollingClient.subscribe (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/status/pollingClient.js:91:19)\n    at async MyDomainResolver.resolve (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/status/myDomainResolver.js:103:45)\n    at async Connection.isResolvable (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:239:13)\n    at async Connection.retrieveMaxApiVersion (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:190:9)\n    at async Connection.useLatestApiVersion (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:214:32)\n    at async Connection.create (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:98:17)\n    at async Org.init (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/org.js:766:31)\n    at async Org.create (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/kit/lib/creatable.js:57:9)\n    at async scratchOrgCreate (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:174:24)\n    at async Create.createScratchOrg (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:187:68)",
  "warnings": [],
  "commandName": "Create"
}
I don't understand why this error happens and how to fix it or find a workaround to it?

I can see the production org has the correct enhanced domain and the Sfdx Auth Url is correct and has not been changed. What is wrong here?

### Steps To Reproduce:
1. Register for a new DevHub Trial org by a link https://developer.salesforce.com/promotions/orgs/dx-signup
<img width="1584" alt="Screenshot 2023-01-12 at 12 51 22" src="https://user-images.githubusercontent.com/75684333/212054109-35339ce5-4c94-4b7c-bb24-0cfc86c4b9c4.png">
You might see some error here, but actually looks like the devhub is created but with some delay.

2. Execute command `sfdx force:auth:web:login -a bdssdxtry`
In my case on this step I receive another error
![Screenshot 2023-01-12 at 12 50 37](https://user-images.githubusercontent.com/75684333/212054642-92f33098-5b30-42f5-8f8d-123edde60505.png)
So to workaround this error I use `sfdx force:auth:web:login -a bdssdxtry -r https://incredible-appy-102739.my.salesforce.com` but you need to replace it with your domain.

3. Try to execute a command `sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1 --json` or simply `sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1`.
I guess the scratch org definition file doesn't matter for this case, so you might just create a new blank sfdx project.
In case if it does matter, I can attach my file here https://gist.github.com/bdovh/408f1c570e8c5b030be05577f17f19ce

### Expected result

I expect the scratch org to be created without issues.

### Actual result

The error happens

{
  "status": 1,
  "name": "DomainNotFound",
  "message": "The org cannot be found",
  "exitCode": 1,
  "actions": [
    "Verify that the org still exists',",
    "If your org is newly created, wait a minute and run your command again',",
    "If you deployed or updated the org's My Domain, logout from the CLI and authenticate again\",",
    "If you are running in a CI environment with a DNS that blocks external IPs, try setting SFDX_DISABLE_DNS_CHECK=true'"
  ],
  "context": "Create",
  "stack": "DomainNotFound: The org cannot be found\n    at Messages.createError (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/messages.js:446:16)\n    at Connection.isResolvable (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:244:28)\n    at async Connection.retrieveMaxApiVersion (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:190:9)\n    at async Connection.useLatestApiVersion (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:214:32)\n    at async Connection.create (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:98:17)\n    at async Org.init (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/org.js:766:31)\n    at async Org.create (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/kit/lib/creatable.js:57:9)\n    at async scratchOrgCreate (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:174:24)\n    at async Create.createScratchOrg (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:187:68)\n    at async Create._run (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)\nCaused by: MyDomainResolverTimeoutError: The client has timed out.\n    at PollingClient.subscribe (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/status/pollingClient.js:91:19)\n    at async MyDomainResolver.resolve (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/status/myDomainResolver.js:103:45)\n    at async Connection.isResolvable (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:239:13)\n    at async Connection.retrieveMaxApiVersion (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:190:9)\n    at async Connection.useLatestApiVersion (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:214:32)\n    at async Connection.create (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/connection.js:98:17)\n    at async Org.init (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/org.js:766:31)\n    at async Org.create (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/kit/lib/creatable.js:57:9)\n    at async scratchOrgCreate (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:174:24)\n    at async Create.createScratchOrg (/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:187:68)",
  "warnings": [],
  "commandName": "Create"
}

It happens both on CI and on the local machine. On the latest version of the sfdx and also on the previous versions of the SFDX CLI.

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
I think it doesn't matter, on local machine zsh or bash.
On github actions I guess the default shell is used.

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
On my local machine
	
{
  "cliVersion": "sfdx-cli/7.182.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.12.1",
  "pluginVersions": [
    "@mshanemc/plugin-streaming 1.1.7 (user)",
    "@mshanemc/sfdx-sosl 1.1.0 (user)",
    "@oclif/plugin-autocomplete 1.3.6 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.19 (core)",
    "@oclif/plugin-not-found 2.3.9 (core)",
    "@oclif/plugin-plugins 2.1.8 (core)",
    "@oclif/plugin-search 0.0.4 (core)",
    "@oclif/plugin-update 3.0.7 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.15 (core)",
    "@oclif/plugin-which 2.2.2 (core)",
    "alias 2.1.12 (core)",
    "apex 1.3.0 (core)",
    "auth 2.3.3 (core)",
    "community 2.0.18 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.5 (core)",
    "data 2.1.17 (core)",
    "evergreen 0.34.0 (user)",
    "evergreen-build 0.20.2 (user)",
    "generator 2.0.13 (core)",
    "info 2.2.13 (core)",
    "limits 2.1.3 (core)",
    "org 2.2.19 (core)",
    "packaging 1.10.10 (core)",
    "schema 2.1.19 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.8 (core)",
    "telemetry 2.0.5 (core)",
    "templates 55.1.0 (core)",
    "trust 2.2.2 (core)",
    "user 2.1.22 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@salesforce/sfdx-scanner 3.7.1 (user)",
    "salesforce-alm 54.8.4 (core)",
    "shane-sfdx-plugins 4.43.0 (user)"
  ],
  "osVersion": "Darwin 20.5.0",
  "shell": "zsh",
  "rootPath": "/Users/bdovh/.local/share/sfdx/client/7.182.1-dad7ae3"
}

On the github action ci

```
v16.18.1

added 984 packages, and audited 119 packages in 24s

77 packages are looking for funding
  run `npm fund` for details

3 vulnerabilities (1 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
Version of SFDX CLI is: sfdx-cli/7.182.1 linux-x
```

**Comment by warbio** [comment]
Same issue here. This is the error message I get:

```
ERROR running force:org:create:  The org cannot be found 

Try this: 
Verify that the org still exists', 
If your org is newly created, wait a minute and run your command again', 
If you deployed or updated the org's My Domain, logout from the CLI and authenticate again", 
If you are running in a CI environment with a DNS that blocks external IPs, try setting SFDX_DISABLE_DNS_CHECK=true'
```

**Comment by warbio** [comment]
This seems to be working as normal again.

**Comment by bdovh** [comment]
> This seems to be working as normal again.

this is strange, what was that? why it is working as normal now?

**Comment by warbio** [comment]
> > This seems to be working as normal again.
> 
> this is strange, what was that? why it is working as normal now?

They probably had some DNS issues that they resolved.

**Comment by WillieRuemmele** [comment]
Hi @warbio @bdovh seems like this has been resolved for both of you?

**Comment by bdovh** [comment]
I

> 

it seems to be working now. Do you know if this issue is going to reoccur?

**Comment by WillieRuemmele** [comment]
Great, unfortunately, I don't know if it'll happen again. we are in a release period which can lead to some issues 
https://github.com/forcedotcom/cli/issues/1690

**Comment by bdovh** [comment]
@WillieRuemmele the issue has reoccured

Org creation failed with error DomainNotFound DomainNotFound: The org cannot be found


Run echo $(sfdx force:org:create -f src/unpackaged/config/project-scratch-def.json -a scratch-org -s -d 1 --json) > create.json
Create scratch org failed
Error message: DomainNotFound DomainNotFound: The org cannot be found
 at Messages.createError (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/messages.js:446:16)
 at Connection.isResolvable (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/connection.js:244:28)
 at async Connection.retrieveMaxApiVersion (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/connection.js:190:9)
 at async Connection.useLatestApiVersion (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/connection.js:214:32)
 at async Function.create (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/connection.js:98:17)
 at async Org.init (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/org.js:766:31)
 at async Function.create (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/creatable.js:57:9)
 at async scratchOrgCreate (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:174:24)
 at async Create.createScratchOrg (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:[18](https://github.com/LinkSquares/salesforce-finalize/actions/runs/3938055787/jobs/6736293246#step:12:19)7:68)
 at async Create._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)
Caused by: MyDomainResolverTimeoutError: The client has timed out.
 at PollingClient.subscribe (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/status/pollingClient.js:91:[19](https://github.com/LinkSquares/salesforce-finalize/actions/runs/3938055787/jobs/6736293246#step:12:20))
 at async MyDomainResolver.resolve (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/status/myDomainResolver.js:103:45)
 at async Connection.isResolvable (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/connection.js:239:13)
 at async Connection.retrieveMaxApiVersion (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/connection.js:190:9)
 at async Connection.useLatestApiVersion (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/connection.js:[21](https://github.com/LinkSquares/salesforce-finalize/actions/runs/3938055787/jobs/6736293246#step:12:22)4:32)
 at async Function.create (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/connection.js:98:17)
 at async Org.init (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/org.js:766:31)
 at async Function.create (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/kit/lib/creatable.js:57:9)
 at async scratchOrgCreate (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:174:[24](https://github.com/LinkSquares/salesforce-finalize/actions/runs/3938055787/jobs/6736293246#step:12:25))
 at async Create.createScratchOrg (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:187:68)

**Comment by shetzel** [comment]
@bdovh - this happens when DNS isn't performing normally, which is outside the control of the CLI.  However you can manipulate how the CLI handles DNS resolution by setting a few environment variables:
`SFDX_DNS_TIMEOUT`: Specifies the number of seconds that the force:org:* commands wait for a response when checking whether an org is connected. If the commands don’t receive a response in that time, they time out. Default value is 3.  You could increase it to (e.g.) 30.
`SFDX_DISABLE_DNS_CHECK`: Disable the DNS resolution entirely by setting to true.  There may be issues encountered with later commands or it could be fine.

**Comment by bdovh** [comment]
Well, when I install SFDX CLI on the CI environment, I have command to set SFDX_DISABLE_DNS_CHECK to true

npm install sfdx-cli --global
export SFDX_DISABLE_DNS_CHECK=true

And also I have it second time on push

- name: "Push source to scratch org"
        id: "deploy0"
        shell: bash
        env:
          SFDX_DISABLE_DNS_CHECK: true
        run: |
          cd src/unpackaged
          echo "Changed dir"
          DEBUG=sf:MyDomainResolver
          echo "Set debug to $DEBUG"
          SFDX_DISABLE_DNS_CHECK=true
          echo "Set SFDX_DISABLE_DNS_CHECK to $SFDX_DISABLE_DNS_CHECK"
          sfdx force:source:deploy -p force-app --json > ../../deploy.txt || true
          echo "File created"
          
Should I try to copy it again just before the executing create org command? Isn't it enough to include that variable just once?

**Comment by bdovh** [comment]
Could you please tell me if this error is also related to DNS resolution problem?

Org creation failed with error ScratchOrgInfoTimeout ScratchOrgInfoTimeout: The client has timed out. at PollingClient.subscribe (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/status/pollingClient.js:91:19) at async pollForScratchOrgInfo (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgInfoApi.js:303:34) at async scratchOrgCreate (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:165:17) at async Create.createScratchOrg (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-org/lib/commands/force/org/create.js:187:68) at async Create._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40) at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:272:25) at async run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/main.js:74:5)

**Comment by WillieRuemmele** [comment]
@bdovh that's more related to the `--wait` parameter on the command timing out. It could be timing out for a DNS issue, but a lot of other things could by causing your SO to take a while to create. Try increasing your `--wait` parameter

**Comment by bdovh** [comment]
> @bdovh that's more related to the `--wait` parameter on the command timing out. It could be timing out for a DNS issue, but a lot of other things could by causing your SO to take a while to create. Try increasing your `--wait` parameter

what is default value and what is the maximum value?

**Comment by WillieRuemmele** [comment]
`sfdx force:org:create --help` => wait's default is 6 minutes, maximum... not sure there is one

**Comment by bdovh** [comment]
> `sfdx force:org:create --help` => wait's default is 6 minutes, maximum... not sure there is one

where do you see the default value on executing this command?

Since when I execute it, I see


```
sfdx help force:org:create
create a scratch or sandbox org 

USAGE
  $ sfdx force org create [name=value...] [-t scratch|sandbox] [-f <filepath>] [-n] [-c] [-i <string>] [-s] [-a <string>] [-w <minutes>] [-d <integer>] [-v <string>] [-u
    <string>] [--apiversion <string>] [--json] [--loglevel trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]

FLAGS
  -a, --setalias=<value>                                                            alias for the created org
  -c, --noancestors                                                                 do not include second-generation package ancestors in the scratch org
  -d, --durationdays=<value>                                                        [default: 7] duration of the scratch org (in days) (default:7, min:1, max:30)
  -f, --definitionfile=<value>                                                      path to an org definition file
  -i, --clientid=<value>                                                            connected app consumer key; not supported for sandbox org creation
  -n, --nonamespace                                                                 create the scratch org with no namespace
  -s, --setdefaultusername                                                          set the created org as the default username
  -t, --type=(scratch|sandbox)                                                      [default: scratch] type of org to create
  -u, --targetusername=<value>                                                      username or alias for the target org; overrides default target org
  -v, --targetdevhubusername=<value>                                                username or alias for the dev hub org; overrides default dev hub org
  -w, --wait=<value>                                                                [default: [object Object]] the streaming client socket timeout (in minutes)
  --apiversion=<value>                                                              override the api version used for api requests made by this command
  --json                                                                            format output as json
  --loglevel=(trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL)  [default: warn] logging level for this command invocation

DESCRIPTION
  create a scratch or sandbox org
  Creates a scratch org or a sandbox org using the values specified in a configuration file or key=value pairs that you specify on the command line. Values specified on the command
  line override values in the configuration file. Specify a configuration file or provide key=value pairs while creating a scratch org or a sandbox. When creating scratch orgs,
  —targetdevhubusername (-v) must be a Dev Hub org. When creating sandboxes, the --targetusername (-u) must be a production org with sandbox licenses. The —type (-t) is required if
  creating a sandbox.



ALIASES
  $ sfdx force org beta create

EXAMPLES
  $ sfdx force:org:create -f config/enterprise-scratch-def.json -a MyScratchOrg

  $ sfdx force:org:create edition=Developer -a MyScratchOrg -s -v devHub

  $ sfdx force:org:create -f config/enterprise-scratch-def.json -a ScratchOrgWithOverrides username=testuser1@mycompany.org

  $ sfdx force:org:create -t sandbox -f config/dev-sandbox-def.json -a MyDevSandbox -u prodOrg
```

**Comment by bdovh** [comment]
I can't find anything in the documentation but I could instead to find out this value experimentally.

If we try to experiment we will find out the following results:

```
sfdx force:org:create -s -d 30 -a o$(( RANDOM % 1000)) -f config/manual.json -w 9999999999999999999999
(node:45988) TimeoutOverflowWarning: 6.0000000000000006e+26 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(Use `node --trace-warnings ...` to show where the warning was created)
ERROR running force:org:create:  The client has timed out.
```
Clearly -w parameter should be less than maximum value of 32-bit signed integer, which is (2^31) - 1 or 2147483647.

Further, let's try to pass the value of max signed int into -w parameter

```
sfdx force:org:create -s -d 30 -a o$(( RANDOM % 1000)) -f config/manual.json -w 2147483647
(node:46082) TimeoutOverflowWarning: 128849018820000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(Use `node --trace-warnings ...` to show where the warning was created)
```
Ok, looks like the minutes parameter is multiplied by 60000 to be converted into number of milliseconds and that value should be less than max signed int. So let's just divide 2147483647 by 60000 and take floor of the result.

```
sfdx force:org:create -s -d 30 -a o$(( RANDOM % 1000)) -f config/manual.json -w 35791
Successfully created scratch org: 00D8N0000005l0YUAQ, username: test-bbem48xfwufo@example.com.
```

So, the maximum value is 35791

**Comment by bdovh** [comment]
If we try `35792` then we receive an error

```
sfdx force:org:create -s -d 30 -a o$(( RANDOM % 1000)) -f config/manual.json -w 35792
(node:46439) TimeoutOverflowWarning: 2147520000 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(Use `node --trace-warnings ...` to show where the warning was created)
ERROR running force:org:create:  The client has timed out.
```
