### ISSUE TITLE
force:source:deploy does not honor destructiveChanges.xml 

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#188]
### Summary

Our MDAPI project made heavy use of `package.xml` and `destructiveChangesPost.xml` (the sibling to `destructiveChanges.xml`)

When we converted the MDAPI format project to source format, we chose to also continue to use package.xml since it allows us to make up for the lack of source tracking in DE and EE orgs. 

However, when using `force:source:deploy` with the `-x package.xml` argument, the `destructiveChangesPost.xml` that's in the same directory as package.xml is not bundled into the zip that's sent up for deployment

I'll state the purpose of destructiveChanges.xml for completeness: It allows us to propagate deletion of components from one org to another in a reliable, repeatable fashion. ex. removing a custom field, renaming a field, deleting a VF page, etc. 

Without support for an explicitly maintained destructiveChanges.xml via the CLI, it's not true that the CLI is now a replacement for the Ant migration tool

### Steps To Reproduce:

1. Convert a MDAPI project to Source format
1. Create a VF page in your org named VenueMigrator (whatever) using Dev Console
1. Define a `package.xml` in a directory with the following content
```
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>*</members>
		<name>ApexPage</name>
	</types>
	<version>46.0</version>
</Package>
```
1. Define a `destructiveChanges.xml` in the same directory with the following content
```
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>VenueMigrator</members>
		<name>ApexPage</name>
	</types>
	<version>46.0</version>
</Package>
```
1. Execute a `force:source:deploy -x package.xml`
1. Expected: The VenueMigrator page should be deleted
1. Actual: The VenueMigrator page is not deleted

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.25.3-16d54c01ee win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 46.15.3 (core)
├─ force-language-services 46.22.0 (core)
└─ salesforce-alm 46.20.0 (core)

sfdx-cli 7.25.3 (core)

**OS and version**:
Windows 10 Pro

**Comment by clairebianchi** [comment]
We are going to add support for destructive changes in the coming months. Thank you for your feedback.

**Comment by zerkz** [comment]
@clairebianchi Thanks for your response on this issue!

Is there any update on the progress? We also have traditionally used destructiveChanges.xml / etc, and we're somewhat hindered by this.   

Do you have any information on what major release this is slated for? v48, v49?

**Comment by clairebianchi** [comment]
Our team is currently working on support for multiple package directories which has an impact on destructive changes, so we had to do that work first. We hope to finish that up in the next 2 months and then pick up the work on destructive changes.

**Comment by tsalb** [comment]
@clairebianchi Connecting some dots here! I'd also be interested to learn when this can be picked back up with an official work item.

It seems like [this issue](https://github.com/forcedotcom/cli/issues/379) is currently a dependency that is blocking this one.

Do you know if another issue will be opened in the future once that is resolved or will this issue just make its way into some future version silently?

**Comment by clairebianchi** [comment]
@tsalb we do not track our work in Github, which is why this has been closed. We will be working on destructive changes this year, it is on our roadmap. We have to complete our work on supporting multiple packages first in order to avoid a bunch of rework that would have to happen. I apologize for the delay.

**Comment by MuriloKakazu** [comment]
Although the destructive changes xml file is currently only supported by the mdapi format, as a work around you could maintain a project in the source format, and only when you need to deploy it to an environment, convert the project to mdapi with `sfdx force:source:convert` in another directory, copy the destructive changes xml file to that directory, and then deploy it with `sfdx force:mdapi:deploy`

**Comment by gdman** [comment]
@clairebianchi - even if the work is being managed outside of Github, could these issues be left open until they are fixed? From an external point of view it's difficult to know what has and hasn't been fixed.

Could there be a simple implementation (even if it's only in the interim) to do something like:
`force:source:deploy [existing args] [--destructivepre destructiveChangesPre.xml] [--destructivepost destructiveChangesPost.xml]`

If one or more of the destructive args are populated copy the file(s) into the temp directory that gets pushed to the Metadata API.

I understand that there are loads of things that need to be done and everything has to be prioritised but it's small things like this that block us from adopting source functionality.

**Comment by RupertBarrow** [comment]
Hi @clairebianchi , since you are closing issues here and announcing feature requests as future features on the roadmap, could we see that roadmap somewhere ?
We need answers to be able to set up deployment strategies in complex contexts (SI, multi-project). 
Without visibility, we have to invest in workarounds.

**Comment by gdman** [comment]
For anyone that's interested in this functionality - I've had a stab at creating an SFDX plugin that hooks into `force:source:deploy` to copy destructive changes files into the package temp directory before it's zipped and pushed to the Metadata API.

I'm planning to use this plugin until Salesforce implements the functionality natively into `force:source:deploy`.

The plugin is available on NPM: https://www.npmjs.com/package/sfdx-destruction. It can be configured by environment variables and / or the SFDX project configuration file.

The source is on GitHub: https://github.com/gdman/sfdx-destruction

**Comment by goto-dev-null** [comment]
So, uh, why is this closed?

**Comment by gdman** [comment]
Whilst the ticket shouldn't have been closed originally (IMO), the functionality does exist now. You can use the following args:
`--predestructivechanges <filepath> --postdestructivechanges <filepath>`
