### ISSUE TITLE
Build org does not accept language option in project-scratch-def.json upon package version creation

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#1883]
### Summary
Setting the language option results in the following error upon package version creation: 
`ERROR running force:package:version:create:  No such column 'Language' on sobject of type Package2VersionCreateRequest.
`
### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/petter-eikeland/dreamhouse-lwc)

1. Create new folder **campaign-field** and add a custom field "Test_Field__c"
1. Create a new package using `sfdx force:package:beta:create -n campaign-field -r campaign-field -t Unlocked -v myhuborg`
1. Add the ` "language": "en_US",` option to the project-scratch-def.json 
1. Create new version of campaign-field package using `sfdx force:package:beta:version:create -p campaign-field -w 20 -x -v myhuborg -f config/project-scratch-def.json`

### Expected result
A new package version of campaign-field is successfully created

### Actual result
Error is thrown: `ERROR running force:package:version:create:  No such column 'Language' on sobject of type Package2VersionCreateRequest.
`

### System Information
```
{
  "cliVersion": "sfdx-cli/7.183.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.12.1",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 20.5.2 (user)",
    "@eon-com/eon-sfdx 1.9.4 (user)",
    "@oclif/plugin-autocomplete 1.3.8 (core)",
    "@oclif/plugin-commands 2.2.2 (core)",
    "@oclif/plugin-help 5.1.20 (core)",
    "@oclif/plugin-not-found 2.3.13 (core)",
    "@oclif/plugin-plugins 2.1.8 (core)",
    "@oclif/plugin-search 0.0.6 (core)",
    "@oclif/plugin-update 3.0.9 (core)",
    "@oclif/plugin-version 1.1.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.18 (core)",
    "@oclif/plugin-which 2.2.6 (core)",
    "1commerce 0.0.10 (user)",
    "alias 2.1.14 (core)",
    "apex 1.3.0 (core)",
    "auth 2.3.8 (core)",
    "community 2.0.18 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.5 (core)",
    "data 2.1.19 (core)",
    "generator 2.0.13 (core)",
    "info 2.3.1 (core)",
    "limits 2.2.0 (core)",
    "org 2.2.20 (core)",
    "packaging 1.12.2 (core)",
    "schema 2.2.2 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.12 (core)",
    "telemetry 2.0.5 (core)",
    "templates 55.1.0 (core)",
    "trust 2.2.4 (core)",
    "user 2.1.24 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.5 (core)",
    "sfdmu 4.23.8 (user)",
    "sfpowerkit 6.0.1 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/user/.local/share/sfdx/client/7.183.1-3a2f5ba"
}
```

### Additional information
The same error occurs for both the beta command & the "ordinary" command.

If this parameter is no longer supported upon package version request means, then we need maintain different versions of the project-scratch-def.json file for package version creation & scratch org creation

**Comment by WillieRuemmele** [comment]
Hi @petter-eikeland thanks for reporting this! We're aware and have already [fixed](https://github.com/forcedotcom/packaging/pull/192) the bug. This will be availble in tomorrow's `latest-rc` build, or you can install the packaging plugin individually with `sfdx plugins:install @salesforce/plugin-packaging` and then you can verify with 
```
sfdx plugins --core

...
org 2.2.22 (core)
packaging 1.12.3
...
```
just make sure to uninstall before upgrading versions 👍

**Comment by petter-eikeland** [comment]
@WillieRuemmele FYI, I'm also getting the following error when specifying a default record type for the Case object (needed for the SSH managed package)
```
	"objectSettings": {
		"case": {
			"defaultRecordType": "default"
		}
```
Error:
```
ERROR running force:package:version:create:  Multiple errors occurred: 
(1) Case.DefaultProcess: Picklist value: New not found
```

The error goes away when removing the case default record type. However, I'm not able to recreate the issue with dreamhouse lwc
