### ISSUE TITLE
Issue occured while building the salesforce unlock package - error code: 1479842573-694 (-852365351)

### ISSUE THREAD

**Issue by amit-ranganekar** [forcedotcom/cli#1884]
Summary
We were building the salesforce unlock package through salesforce sfpowerscript command and are getting below error.

Expected result
Package should be built.

Actual result
Package is failing with below error.

System Information
Package Creation Failed for gdpr-core
Source converted successfully to /builds/hcl-da/salesforce/master-repository/.sfpowerscripts/dxElp_source/.sfpowerscripts/BSbTa_mdapi
command: create  package
package name: gdpr-core
package type: unlocked
package directory: src/compliance/gdpr-core
-------------------------------------------------------------------------------------------
Fetching Package Type Info from DevHub
Package gdpr-core
IsOrgDependent No
Package Id 0Ho090000004CdKCAU
-------------------------
Package creation for gdpr-core Initiated
Status: Initializing, Next Status check in 30 seconds
Status: VerifyingFeaturesAndSettings, Next Status check in 30 seconds
Status: VerifyingFeaturesAndSettings, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: VerifyingDependencies, Next Status check in 30 seconds
Status: Error, Next Status check in 30 seconds
Unable to create gdpr-core due to 
Creation errors: 
1) An unexpected error occurred. Please contact Salesforce Support and provide the following error code: 1479842573-694 (-852365351)
Removed all childs of gdpr-core from queue

**Comment by WillieRuemmele** [comment]
Hi @amit-ranganekar, This sounds like you'll need to reach out to the `sfpowerkit` plugin maintainers, which is not us. Have you tried using the `package:` commands available in `sfdx`?

**Comment by shetzel** [comment]
This server side error: `1479842573-694 (-852365351)` has details of: `ZipException: only DEFLATED entries can have EXT descriptor` so I would suspect something wrong with the zipped metadata being packaged.  Please re-open if you're continuing to have problems.
