### ISSUE TITLE
Version of Node packaged with the Salesforce CLI is incompatible with the Salesforce Code Analyzer

### ISSUE THREAD

**Issue by simonfoden** [forcedotcom/cli#1886]
The Salesforce CLI looks like it's packaged with version 12.18.3 of Node. The Salesforce Code Analyzer (forcedotcom/sfdx-scanner) doesn't appear to function with this version of Node. 

sfdx -v
sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3

When using CircleCI I'm getting an assortment of warnings and errors as a higher version of Node is expected by the Salesforce Code Analyzer.

I'm getting the CLI from here :
https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

To reproduce : 
1. Install the Salesforce CLI.
2. sfdx plugins:install @salesforce/sfdx-scanner OR sfdx plugins:install @salesforce/sfdx-scanner@latest --non-interactive.

This produces the following warnings and errors : 
Log :
Installing plugin @salesforce/sfdx-scanner... yarn add v1.22.10
Installing plugin @salesforce/sfdx-scanner... info No lockfile found.Installing plugin @salesforce/sfdx-scanner... [1/4] Resolving packages...Installing plugin @salesforce/sfdx-scanner... [2/4] Fetching packages...Installing plugin @salesforce/sfdx-scanner... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin @salesforce/sfdx-scanner... failed
warning @salesforce/sfdx-scanner > @salesforce/command > cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning @salesforce/sfdx-scanner > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @salesforce/sfdx-scanner > @salesforce/core > jsforce > request > uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
warning @salesforce/sfdx-scanner > retire > read-installed > readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
warning @salesforce/sfdx-scanner > @salesforce/core > jsforce > request > har-validator@5.1.5: this library is no longer supported
error eslint@8.32.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "12.18.3"
error Found incompatible module.
Error: yarn add @salesforce/sfdx-scanner@latest --non-interactive
--mutex=file:/home/circleci/.local/share/sfdx/yarn.lock
--preferred-cache-folder=/home/circleci/.cache/sfdx/yarn --check-files
exited with code 1

Exited with code exit status 1
CircleCI received exit code 1

I think the Salesforce CLI should be packaged with a higher version of Node (>=16.0.0) e.g. v18.12.0. This should then allow the Salesforce Scanner to function.

I'm using CircleCI with various images that include the Java JDK. Using an image that includes a newer version of Node or installing it manually doesn't solve the problem. I've also used an Ubuntu VM and found similar issues. 

Please correct this issue. 

Thanks a lot. 

Regards
Simon

**Comment by WillieRuemmele** [comment]
Hi @simonfoden, the CLI should be shipping with the `LTS` version of node, which should be 18 now... please check which node version you have installed 
```
 ➜  sfdx -v                              
sfdx-cli/7.184.2 darwin-arm64 node-v18.7.0
 ➜  node -v                                
v18.7.0
```

or checkout our "full" docker images which include [node](https://hub.docker.com/layers/salesforce/salesforcedx/7.184.2-full/images/sha256-66c9b23496bdf37a25ab060fb31b8deca9e5ab0d97e5e09d12b88181f5570a56?context=explore)

**Comment by simonfoden** [comment]
Hello @WillieRuemmele. 

Thanks for looking into this. 

The Salesforce CLI here : https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz 
returns the following using sfdx -v : 
sfdx -v
sfdx-cli/7.82.0-3d0c527ac6 linux-x64 **node-v12.18.3**

It looks like you're using MacOS and the corresponding Salesforce CLI which may be correctly packaged. The above Linux 64 bit version of the Salesforce CLI looks out of date. 

I'm using CircleCI who host their own docker images for builds. Also using an image with a more up-to-date version of Node or installing Node manually doesn't solve the issue. The Salesforce Code Analyzer (scanner) ignores any new version not included in the Salesforce CLI. I presume it's possible to alter config files / paths to maybe point elsewhere but that's not helpful with an automated DevOps process. 

Using node -v with an image including the latest version of Node returns the following :
v18.12.0
CircleCI received exit code 0

If I'm correct I think the 64 bit Linux Salesforce CLI needs updating. Either that or I need to point to another URL to get the correct version. 

Thanks.

Regards
Simon

**Comment by WillieRuemmele** [comment]
Hi @simonfoden I see the issue now! You should be using these steps to install it https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux the link you've posted is pointing to `7.82.0`, while latest is `7.183.0`, almost 100 releases ahead. So I'm sure in the `.80` release, node 12 was LTS. Try following the above links to get a newer download URL to get `.183`

**Comment by simonfoden** [comment]
@WillieRuemmele Updating the URL and installation steps resolved the issue. 

I've other parts of my build script that appear to be out of date that I need to correct but this fixed the problem.

Thanks a lot for your help.

Regards 
Simon
