### ISSUE TITLE
Metadata API odd errors during the long pulling

### ISSUE THREAD

**Issue by steals** [forcedotcom/cli#1887]
### Summary

This issue is the continuation of https://github.com/forcedotcom/cli/issues/1835

During our daily deployment, we have a lot of failures because in the middle of the pulling results Metadata API hangs with some odd errors, like:
`ERROR running force:source:deploy:report:  Metadata API request failed: request to https://.....sandbox.my.salesforce.com/services/Soap/m/56.0 failed, reason: Client network socket disconnected before secure TLS connection was established`
or
`ERROR running force:source:deploy:report:  Metadata API request failed: Unexpected internal servlet state`
or
`ERROR running force:source:deploy:report:  Metadata API request failed: Unable to complete the creation of the query cursor at this time, please retry your query later.`

Is it possible to add these errors to the list of ignored errors so the sfdx cli doesn't stop pulling for the results?

### System Information

sfdx-cli/7.182.1 linux-x64 node-v18.12.1

running on Ubuntu 20.04 docker image

**Comment by WillieRuemmele** [comment]
I haven't seen those errors before, we can add them to the retry-able list

**Comment by steals** [comment]
@WillieRuemmele any ETA when this issue can be resolved?

**Comment by mshanemc** [comment]
@steals this'll be in RC on Thursday Feb16 and the main channel the following week (Feb23).

**Comment by gfarb** [comment]
Commenting to subscribe but wanted to call out at GitHub we have been running into these errors a lot recently, primarily:
- `Metadata API request failed: Unexpected internal servlet state`
- `Metadata API request failed: Failed while fetching query cursor data for this QueryLocator`

It causes our GitHub Actions to fail and despite the fact that the deployment continues, we need to re-run our CI/CD jobs which results in time and resources wasted

**Comment by hudec117** [comment]
@mshanemc that PR doesn't seem to address this error message?

`Metadata API request failed: Failed while fetching query cursor data for this QueryLocator`

This is the main one we're seeing at the moment.

**Comment by steals** [comment]
Also noticed this new error today. I guess we need to create a new GitHub ticket for that.

**Comment by mshanemc** [comment]
that last one will go out in tomorrow's RC.

**Comment by shetzel** [comment]
Here is some additional information about the server side errors you're seeing during polling for deploy status:

`Failed while fetching query cursor data for this QueryLocator` - There is a known bug tracked by the appropriate internal team.  W-12563567.  Feel free to open support cases and mention that to bump the priority for that team.

`Unexpected internal servlet state` - This looks like a known issue: https://issues.salesforce.com/issue/a028c00000gAzYKAA0/intermittent-unexpected-internal-servlet-state-during-soap-and-bulk-api-requests

Happy to add them to the list of "retry-errors".  Letting support know about them will also help prevent them from happening at all.

Thanks!

**Comment by hudec117** [comment]
We're using `sfdx-cli/7.190.2 linux-x64 node-v18.14.1` in our CI/CD pipelines and we're still seeing the `Metadata API request failed: Failed while fetching query cursor data for this QueryLocator` error that ends the SFDX process and fails the build.

Was this fix included in 7.190.2 or in the upcoming 7.191.1?

**Comment by cristiand391** [comment]
@hudec117 sorry for the late reply, v7.190.2 should definitely include this fix. Can you open a new GH issue with the commands you are running? Thanks!
https://github.com/forcedotcom/cli/issues/new/choose
