### ISSUE TITLE
Error: SHA mismatch

### ISSUE THREAD

**Issue by giraffe81** [forcedotcom/cli#189]
I am currently having an issue trying to update Salesforce CLI. I have tried updating multiple times but receive the below error:

`C:\>sfdx update
sfdx-cli: Updating CLI from 7.8.1-8f830784cc to 7.26.0-9118501918... !
Error: SHA mismatch: expected bf8d463429df6d7dcb9c0deed09cfcd5aab1b13da9ee3e5dc7
048d7f2287e90b to be 148c0ff783d27224d4e0f41d818245ac7cc1e89ee92d3c66fc84f31bb57
75ffc
    at IncomingMessage.stream.on (C:/Program Files/Salesforce CLI/client/node_mo
dules/@oclif/plugin-update/lib/tar.js:32:32)`

I have tried removing and re-installing Salesforce CLI, and removing the sfdx folder in AppData. We only experience this issue from some servers and cannot find out why. We have opened up the firewall to allow connections to developer.salesforce.com

Any idea what could be the issue?

Thanks

**Comment by clairebianchi** [comment]
@giraffe81 what is your OS?

**Comment by giraffe81** [comment]
It's Windows Server 2012

**Comment by clairebianchi** [comment]
@giraffe81 can you try a full uninstall and then go to the C:/Program Files/Salesforce CLI directory and make sure it is actually deleted and try to install again
