### ISSUE TITLE
sfdx force:package:beta console output format

### ISSUE THREAD

**Issue by jbc329** [forcedotcom/cli#1894]
**Is your feature request related to a problem? Please describe.**
The new sfdx force:package:beta commands appear to produce console output which is wrapped instead of linear. A comparison of the old and new console output is below. The wrapped text makes troubleshooting console errors more difficult. 
output using the beta: commands. 

![image](https://user-images.githubusercontent.com/93673910/214166409-f5d06194-5cd3-4f58-9ef0-86f72c674250.png)

![image](https://user-images.githubusercontent.com/93673910/214167154-4e6f850d-f28b-4325-934c-8771725b472b.png)

We are using sfdx cli version 7.180.0

**What are you trying to do**
A description of the outcome you are hoping to achieve 
We are hoping you can modify the console output of the new sfdx force:package:beta commands to match the formatting of the previous commands. 

**Describe the solution you'd like**
The text output on the package:beta commands would be improved if the output was similar to the previous format. 

**Describe alternatives you've considered**
I've considered writing custom logic around the response from the cli command to stream the output in a format we prefer. 

**Additional context**
Nothing additional. Thank you!

**Comment by shetzel** [comment]
@jbc329 - the newer versions of the commands use a spinner with a message that updates on every poll to minimize the amount of output a user has to visually parse.  This is designed for a human and not a CI system.  A few questions:
1. Do you prefer the previous output because it's easier to read in CI output?
2. What is the OS being used?
3. If there was an environment variable to toggle the spinner output (and instead display poll results on a separate line each time) would that solve your usecase?

**Comment by jbc329** [comment]
Do you prefer the previous output because it's easier to read in CI output?
This the previous output was easier to read. 
![image](https://user-images.githubusercontent.com/93673910/214967516-4796d127-f8e9-4057-9665-3756d0fb1c50.png)

Looking at the new output, I almost suspect there is a bug. You can see the first line has a break, but the subsequent lines do not break, right? Line 151 breaks, then line 152 wraps. The text 'InitializingVersion Create' seems to be missing a break. I could be wrong and this is the intended output. 
![image](https://user-images.githubusercontent.com/93673910/214967722-0fcc72e3-7030-4f96-9451-cf69b44a9058.png)

What is the OS being used?
In the screenshots we are using Linux Alpine in a Docker container for CI/CD. Locally, I get the same output. My local machine is running Windows 10. 

If there was an environment variable to toggle the spinner output (and instead display poll results on a separate line each time) would that solve your usecase?
That would be fine. 

Strange, another pipeline is showing the output similar to the previous commands. 

![image](https://user-images.githubusercontent.com/93673910/214969062-0ab206b4-6943-46df-b51b-c4db12c6804f.png)

**Comment by shetzel** [comment]
The intended output is:

<img width="935" alt="Screenshot 2023-01-26 at 4 09 30 PM" src="https://user-images.githubusercontent.com/2703995/214971274-49ea4e58-15c3-49b7-9fb0-22b18b6574f9.png">

where a spinner is displayed just before "20 minutes ..." and that one line is updated with changes in status and time remaining.  There shouldn't be multiple lines but maybe different things happen in other OS and shell combinations particularly with `tee`.  On your local machine if you leave off the pipe to tee do you still see multiple lines or does it behave as I described?

Regardless, I think providing a way to not use a spinner might be the best of both worlds.  I'll try a few things.

**Comment by shetzel** [comment]
@jbc329 - a verbose flag was added to the command in the 7.187.1 CLI release candidate to support this usecase a little better.  Feel free to try it out and let me know.
