### ISSUE TITLE
force:source:retrieve -x ... doesn't update static resources

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/cli#190]
### Summary

`force:source:retrieve` will pull down static resources, but it does not update them.

### Steps To Reproduce:

1.  Create a static resource called `broken.txt` with the text: `Hello World`
1.  Create a dx manifest project connected to the org
1. run `sfdx force:source:retrieve -x manifest/package.xml`
1. Confirm the `broken.txt` was retrieved and contains `Hello World`
1. upload a new version of the `broken.txt` via salesforce.com (not via local compile), that reads `goodbye world`
1. run `sfdx force:source:retrieve -x manifest/package.xml`

### Expected result

The local copy of `broken.txt` should be updated to read `goodbye world`

### Actual result

The local copy of `broken.txt` still reads `hello world`

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.25.3-16d54c01ee darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

sfdx-cli 7.25.3 (core)

**OS and version**:
OSX 10.14.5

**Comment by Pflaumen** [comment]
I and my coworkers have been running into this same issue.

sfdx-cli/7.33.2 darwin-x64 node-v9.5.0

@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.2.2 (core)
generator 1.1.2 (core)
salesforcedx 47.6.2 (core)
├─ salesforce-alm 47.9.0 (core)
└─ salesforcedx-templates 47.6.2 (core)

OSX 10.14.6 (18G1012)

**Comment by ChuckJonas** [comment]
@Pflaumen we've created a work around for this in https://github.com/ChuckJonas/force-source-clean

(although make sure you understand the "clean"  behavior before running it)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9299116](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MPlaYAG/view)
