### ISSUE TITLE
sfdx force package version create Not_Found

### ISSUE THREAD

**Issue by munikumare** [forcedotcom/cli#1901]
### Summary

We are encountering issues while version Salesforce unlocked packages. It was working till last month and stopped all of a sudden.

+ sfdx force:package:version:create -x -p connecte3d -w 60 --codecoverage --json
{
  "status": 1,
  "name": "NOT_FOUND",
  "message": "The requested resource does not exist",
  "exitCode": 1,
  "context": "PackageVersionCreateCommand",
  "stack": "NOT_FOUND: The requested resource does not exist\n    at Function.wrap (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfError.js:84:25)\n    at PackageVersionCreateCommand.catch (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:283:38)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async PackageVersionCreateCommand._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:106:13)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:272:25)\nCaused by: NOT_FOUND: The requested resource does not exist\n    at HttpApi.getError (/usr/local/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/http-api.js:307:12)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /usr/local/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/http-api.js:154:23\n    at async Tooling.create (/usr/local/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/connection.js:929:133)\n    at async PackageVersionCreate.packageVersionCreate (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:508:30)\n    at async Function.create (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/packaging/lib/package/packageVersion.js:105:30)\n    at async PackageVersionCreateCommand.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-packaging/lib/commands/force/package/version/create.js:44:24)\n    at async PackageVersionCreateCommand._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:272:25)",
  "warnings": [],
  "commandName": "PackageVersionCreateCommand"
}
### Steps To Reproduce:

sfdx force:package:version:create -x -p connecte3d -w 60 --codecoverage --json

### Expected result

A new version of package should have been created

### Actual result

Error

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
bash (Azure Pipelines)
- If you are using `sfdx`

@oclif/plugin-search 0.0.8 (core)
@oclif/plugin-update 3.0.9 (core)
@oclif/plugin-version 1.1.4 (core)
@oclif/plugin-warn-if-update-available 2.0.19 (core)
@oclif/plugin-which 2.2.6 (core)
@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
alias 2.1.18 (core)
apex 1.4.2 (core)
auth 2.3.12 (core)
community 2.1.3 (core)
config 1.4.23 (core)
custom-metadata 2.0.11 (core)
data 2.1.22 (core)
generator 2.0.16 (core)
info 2.3.3 (core)
limits 2.2.3 (core)
org 2.2.22 (core)
packaging 1.12.3 (core)
salesforce-alm 54.8.5 (core)
schema 2.2.2 (core)
sfdx-cli 7.185.0 (core)
signups 1.2.12 (core)
source 2.3.15 (core)
telemetry 2.0.5 (core)
templates 55.2.1 (core)
trust 2.2.8 (core)
user 2.1.25 (core)

- Paste the output here
### Additional information

<img width="1772" alt="Screenshot 2023-01-30 at 2 25 39 PM" src="https://user-images.githubusercontent.com/19892277/215431524-bd1c501f-a13b-4ccd-9633-96ef7f9258da.png">

**Comment by munikumare** [comment]
It seems permission issue

**Comment by jonny-harte** [comment]
@munikumare how did you resolve the permissions issue?

**Comment by munikumare** [comment]
> @munikumare how did you resolve the permissions issue?

@jonny-harte - It worked after changing my profile to SA.
