### ISSUE TITLE
SFDX force:source:ignored:list default values

### ISSUE THREAD

**Issue by Cerelius** [forcedotcom/cli#1908]
### Summary

I have a large project repository and am trying to make updates to the `.forceignore` file. To test my modifications I'm using the `sfdx force:source:ignored:list` command. When I run the ignored list command I'm expecting it to output a list of the files that are excluded based on the `.forceignore` file located in the root directory. 

I'm getting output from the command that looked like it aligned with my `.forceignore` but to make it easier to see my update I removed all of the lines from the `.forceignore` file and still got a list of ignored files. 

I'm curious to know if there are default exclusions because I expect to get an empty result with an empty .forceignore and that was not what I received. I haven't been able to find any references to default exclusions in the documentation. 

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Open an SFDX Project with source contents.
1.  Remove all lines from the `.forceignore` file.
1.  Run `sfdx force:source:ignored:list`.

### Expected result

I expect an empty result with an empty `.forceignore` file.

### Actual result

I get a list of excluded files. 

### System Information

zsh
```
sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.185.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.19.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.10 (core)",
    "@oclif/plugin-commands 2.2.2 (core)",
    "@oclif/plugin-help 5.1.22 (core)",
    "@oclif/plugin-not-found 2.3.13 (core)",
    "@oclif/plugin-plugins 2.1.8 (core)",
    "@oclif/plugin-search 0.0.8 (core)",
    "@oclif/plugin-update 3.0.9 (core)",
    "@oclif/plugin-version 1.1.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.19 (core)",
    "@oclif/plugin-which 2.2.6 (core)",
    "alias 2.1.18 (core)",
    "apex 1.4.2 (core)",
    "auth 2.3.12 (core)",
    "community 2.1.3 (core)",
    "config 1.4.23 (core)",
    "custom-metadata 2.0.11 (core)",
    "data 2.1.22 (core)",
    "generator 2.0.16 (core)",
    "info 2.3.3 (core)",
    "limits 2.2.3 (core)",
    "org 2.2.22 (core)",
    "packaging 1.12.3 (core)",
    "schema 2.2.2 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.15 (core)",
    "telemetry 2.0.5 (core)",
    "templates 55.2.1 (core)",
    "trust 2.2.8 (core)",
    "user 2.1.25 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.5 (core)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/jason/.nvm/versions/node/v16.19.0/lib/node_modules/sfdx-cli"
}
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by shetzel** [comment]
Yes, there are files that by default are ignored.  Not sure if it's documented anywhere.
See: https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/resolve/forceIgnore.ts#L20

**Comment by shetzel** [comment]
Feel free to open this back up if the ignored list doesn't match the default patterns being ignored.
