### ISSUE TITLE
Error OPERATION_TOO_LARGE seen when creating scratch org from Org Snapshot

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#191]
### Summary

Error message `Unhandled rejection OPERATION_TOO_LARGE: Only 25 requests are allowed in a single batch operation` received when creating scratch org from an Org Snapshot

### Steps To Reproduce:

1.  Create a org snapshot
1.  Create a scratch org from org snapshot

### Expected result

Scratch org is created successfully

### Actual result

Scratch org is created successfully but I also receive following error:
```
Successfully created scratch org: 00D540000005aEuEAI, username: test-ulypshtv3j3b@example.com
Unhandled rejection OPERATION_TOO_LARGE: Only 25 requests are allowed in a single batch operation
    at HttpApi.getError (/Users/johndaniel/.local/share/sfdx/client/7.26.0-9118501918/node_modules/salesforce-alm/node_modules/jsforce/lib/http-api.js:250:13)
    at /Users/johndaniel/.local/share/sfdx/client/7.26.0-9118501918/node_modules/salesforce-alm/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/Users/johndaniel/.local/share/sfdx/client/7.26.0-9118501918/node_modules/promise/lib/core.js:37:12)
    at /Users/johndaniel/.local/share/sfdx/client/7.26.0-9118501918/node_modules/promise/lib/core.js:123:15
    at flush (/Users/johndaniel/.local/share/sfdx/client/7.26.0-9118501918/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.26.0-9118501918 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.2
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
rstk-sfdx-package-utils 0.1.6 (link) /Users/johndaniel/workspace/custom-cli/rstk-sfdx-package-utils
rstk-sfdx-plugins-for-carmax 0.1.7 (link) /Users/johndaniel/workspace/custom-cli/rstk-sfdx-plugins-for-carmax
rstk-sfdx-utils 0.0.2
salesforce-to-types 0.0.0
salesforcedx 46.16.0 (core)
├─ force-language-services 46.23.0 (core)
└─ salesforce-alm 46.21.0 (core)

sfdx-cli 7.26.0 (core)
sfpowerkit 1.20.2
shane-sfdx-plugins 4.3.2 (link) /Users/johndaniel/workspace/custom-cli/shane-sfdx-plugins
soqlx-opener 0.1.13 (link) /Users/johndaniel/workspace/custom-cli/soqlx-opener
```
**OS and version**:
MacOS 10.14.6

**Comment by ImJohnMDaniel** [comment]
@rrmehta2 -- FYI on this one.

**Comment by pablogrs** [comment]
Getting the same since last upgrade

**Comment by laithal** [comment]
Any update on this issue? I see get the same error message.
`➜ sfdx --version
sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3`

`
sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
mo-dx-plugin 0.3.2
salesforcedx 50.7.1
├─ schema 1.0.1
├─ templates 50.1.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ apex 0.1.4
├─ custom-metadata 1.0.10
└─ salesforce-alm 50.7.1
sfdx-browserforce-plugin 2.2.1
sfdx-cli 7.82.0 (core)
sfpowerkit 2.4.11 (beta)
`

**Comment by brandbarr** [comment]
Same issue for me as well.

**Comment by pablogrs** [comment]
This is a recurrent problem with Snapshots, when a new Salesforce release comes out, Snapshots gets broken.

**Comment by pablogrs** [comment]
I withdraw what I said, we are seeing the same in newly created Snapshots. 
That said, the Scratch Org is being created anyway.

**Comment by iowillhoit** [comment]
Hey all, I was just able to generate a snapshot with `sf org create snapshot` and then create a scratch org from that snapshot with `sf org create scratch` using `sf` version `2.13.9`. If this is still a problem, please open a new Issue with all of the Issue Template information. Including `--dev-debug` logs would also be helpful. Thanks!
