### ISSUE TITLE
SFDX Deploy is taking quite a long time intermittently (Spring '23 release related?)

### ISSUE THREAD

**Issue by Julian88Tex** [forcedotcom/cli#1913]
### Summary

Deploy commands are taking a long time intermittently. Have one yesterday that took about 40 minutes which normally takes half the time and seeing a similar issue today. This feels very reminiscent of forcedotcom/cli#1690.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Run a `force:source:deploy` command

### Expected result

• Always takes approximately the same time it has to run this command in the past (in my case ~20 minutes).

### Actual result

• Intermittently taking about twice as much time (in my case ~40 minutes). 

### System Information

`sfdx-cli@7.179.0`

### Additional information
start: [01/31/23 23:49:52]
end: [02/01/23 00:31:51]
• Perhaps same issue as forcedotcom/salesforcedx-vscode#4662

**Comment by shetzel** [comment]
Yes, very likely same as #1690.  Unfortunately, it's nothing the CLI can do anything about since it just adds the job to a queue.  If the queue is backed up it's going to take longer.  One thing you can try for deploys is to keep it small if possible.  E.g., under ~20 components jumps the queue.

**Comment by Julian88Tex** [comment]
@shetzel Thanks for confirming. Unfortunately, most of our deploys are entire managed package deploys to brand new scratch orgs. Any way we can get visibility into this queue and the stress levels it is under at a point in time?

**Comment by shetzel** [comment]
I would love to have that visibility as well but unfortunately it doesn't exist.  :(

**Comment by shetzel** [comment]
I'm closing this since the CLI can't do anything about the slowness.  Hope things are back to normal for you, or will be very soon.
