### ISSUE TITLE
Create sfdx-package.json

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1915]
**Is your feature request related to a problem? Please describe.**

No, it isn't.

**What are you trying to do**

I want to find package configurations in a file in the root of the package, not in `sfdx-project.json`. It would work like `package.json` or `pom.xml`, like seen in node and maven projects. The `sfdx-project.json` would become an aggregator of packages. It can contain 1 or many sfdx packages, and it would also behave like a parent `sfdx-package.json`.

**Describe the solution you'd like**

A `sfdx-package.json` must xist in the root of every package. All the information that is specific for a package, which is currently located in the `sfdx-project.json`, must be moved to this file.

````json
{
  "name" : "bla",
  "version": "1.0.0",
  "description": "bla",
  "repository": "https://githu.com/bla/bla",
  "type": "unlocked",
  "is_org_dependent": false,
   "dependencies": {
       "d_1": "1.0.0", // dependencies from the devhub
       "d_2": "https://github.com/bla/d_2@v2.0.0", //non packaged dependency from a repository
       "d_3": ./d_3 //maybe it is a directory dependency that isn't packaged.
       "d_4": //managed packages could also be here. For instance, "vlocity" packages could be necessary for me to start working on changes to my package
    },
    "sfdx_plugins":{
          "sfdx-git-delta": "^5.14.0"
     },
    "scratch_org_config": "./bla-so.config" //file path, including github paths because there could exist a common file shared by many packages from different sfdx projects, or it could be inline if someone needs it
   "key_store": //customers can use their own, or salesforce could sell this as a service.
   "key_id": //ID to locate key within a key store. If passed sfdx will fetch the key automatically at runime and won't save it anywhere. This also means the package must be created/installed using a key. 
    ...

    //string replacement feature properties
    ... 
   //permission set feature properties
    ...

  //any other attribute that is used for the lifecycle of a package
}
````

**Describe alternatives you've considered**
Couldn't find one

**Comment by AllanOricil** [comment]
You can treat sfdx-project.json as a parent pom from maven, and then use sfdx-package.json for packages

**Comment by AllanOricil** [comment]
https://github.com/forcedotcom/cli/issues/1950

**Comment by dieffrei** [comment]
+1

**Comment by AllanOricil** [comment]
This could also be called sf-package.json, since now you have rename sfdx to sf. And sfdx-project.json could become sf-project.json
