### ISSUE TITLE
conn.metadata.read returning empty objects

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#1917]
As of midday yesterday, new installs of SFDX are no longer able to use the metadata.read call for CustomFields. Our sfdx plugin is returning a list of empty objects instead of data.

### Summary

sfdx plugin conn.metadata.read is returning {} for all CustomField results

### Steps To Reproduce:

1.  Have an sfdx plugin that reads individual custom field metadata
2. have a fresh install of sfdx

### Expected result

result to return metadata information

### Actual result

result is an empty javascript object {}

### System Information

sfdx-cli/7.185.0 darwin-arm64 node-v16.16.0

**Comment by shetzel** [comment]
`Connection.metadata.read()` is a jsforce function.  Did you change your plugin's dependencies with jsforce or `@salesforce/core`?  You could try `export JSFORCE_LOG_LEVEL=DEBUG` and run the command again for some debug output from jsforce.

**Comment by yippie** [comment]
I have changed nothing in 6 months, this has been running weekly for a year.

I also just found this behavior is happening in 2 year old code as well. Connection.metadata.read() is not returning anything anymore.

**Comment by yippie** [comment]
So I think this can be closed?

It turns out this was mostly my fault but is a very unintuitive failure mode.

When trying to read fields that either don't exist (had the namespace missing when it was needed) or don't have access (not licensed to a managed object) instead throwing an error or simply not returning a result, metadata.read is returning an empty object {}

**Comment by shetzel** [comment]
Can you tell if jsforce is swallowing an error returned by the server (in which case we can try to make that better) or if the server returns HTTP 200 with an empty object?  If it's the latter, I can try to get some time with that team and get more details about why.

**Comment by yippie** [comment]
I made a quick, super basic ts script that uses jsforce to demonstrate this.

`import * as jsforce from "jsforce";

const username = "my username";
const password = "My Secure Password";
const securityToken = "";
var conn = new jsforce.Connection({
  // you can change loginUrl to connect to sandbox or prerelease env.
  loginUrl: "https://test.salesforce.com",
  version: "56.0",
  instanceUrl: "https://inspiration-energy-4542.scratch.my.salesforce.com",
});
conn.login(username, password + securityToken, function (err, userInfo) {
  if (err) {
    return console.error(err);
  }
});

conn.metadata.read("CustomField", ["asdf.adsfaDP2__c"]).then((results) => {
  console.log(JSON.stringify(results));
});`

The output to console.log is just `{}` nothing else.

**Comment by shetzel** [comment]
Thanks for that.  I agree that's not a great user experience.  I'll bring it up with that team.  I'm glad you figured out what was causing it.
