### ISSUE TITLE
Github action using sfdx-cli/7.186.2 linux-x64 node-v16.19.0

### ISSUE THREAD

**Issue by OrtooAdam** [forcedotcom/cli#1918]
### Summary

Since 03/02/2023, the command 'sfdx force:package:install:report' is failing.
status code in response is '1' and error starts with :-
Error: Parsing --request-id \n\tThe id must be 15 or 18 characters

Running the same script on Mac OS with v7.185.0 does not exhibit this behaviour.

The Github action has not been changed in this time period.
The package install itself does seem to install, just the inability to report on when it's completed.

### Steps To Reproduce:

Create scratch org
Use 'sfdx force:package:install' command to install a package (in our case a managed package).

Response to the above command returns the Report ID to be used in subsequent command
sfdx force:package:install:report -i <ReportID> -u me@example.com --json

### Expected result

JSON response with 'status' of 0 and 'result.Status' of 'SUCCESS'

### Actual result

{ "message": "Parsing --request-id \n\tThe id must be 15 or 18 characters.\nSee more help with --help", "name": "Error", "status": 1, "stack": "Error: Parsing --request-id \n\tThe id must be 15 or 18 characters.\nSee more help with --help\n at Parser._parseFlag (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/parser/parse.js:212:19)\n at async Parser._flags (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/parser/parse.js:167:31)\n at async Parser.parse (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/parser/parse.js:128:23)\n at async Object.parse (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/parser/index.js:29:20)\n at async Report.parse (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:166:25)\n at async Report.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-packaging/lib/commands/package/install/report.js:39:27)\n at async Report._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:80:22)\n at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:298:25)", "exitCode": 1, "warnings": [ "The \"force package install report\" command has been deprecated. Use \"package install report\" instead." ] }

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
basic sh

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here

{
  "cliVersion": "sfdx-cli/7.186.2",
  "architecture": "linux-x64",
  "nodeVersion": "node-v16.19.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.4.2 (core)",
    "@oclif/plugin-commands 2.2.4 (core)",
    "@oclif/plugin-help [5](https://github.com/xxxxx/xxxxx/actions/runs/xxxxx/jobs/7082008572#step:3:6).2.1 (core)",
    "@oclif/plugin-not-found 2.3.17 (core)",
    "@oclif/plugin-plugins 2.2.4 (core)",
    "@oclif/plugin-search 0.0.11 (core)",
    "@oclif/plugin-update 3.1.0 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.23 (core)",
    "@oclif/plugin-which 2.2.9 (core)",
    "alias 2.1.19 (core)",
    "apex 1.4.3 (core)",
    "auth 2.3.12 (core)",
    "community 2.1.5 (core)",
    "config 1.4.23 (core)",
    "custom-metadata 2.0.1[6](https://github.com/xxxxx/xxxxx/actions/runs/xxxxx/jobs/7082008572#step:3:7) (core)",
    "data 2.1.22 (core)",
    "generator 2.0.1[7](https://github.com/xxxxx/xxxxx/actions/runs/xxxxx/jobs/7082008572#step:3:8) (core)",
    "info 2.3.5 (core)",
    "limits 2.2.3 (core)",
    "org 2.2.24 (core)",
    "packaging 1.12.4 (core)",
    "schema 2.2.3 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.16 (core)",
    "telemetry 2.0.7 (core)",
    "templates 55.2.3 (core)",
    "trust 2.3.0 (core)",
    "user 2.2.1 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.[8](https://github.com/xxxxx/xxxxx/actions/runs/xxxxx/jobs/7082008572#step:3:9).5 (core)"
  ],
  "osVersion": "Linux 5.15.0-[10](https://github.com/xxxxx/xxxxx/actions/runs/xxxxx/jobs/7082008572#step:3:11)[31](https://github.com/xxxxx/xxxxx/actions/runs/xxxxx/jobs/7082008572#step:3:32)-azure",
  "shell": "unknown",
  "rootPath": "/usr/local/lib/node_modules/sfdx-cli"
}
### Additional information

_Feel free to attach a screenshot_.

**Comment by shetzel** [comment]
Are you passing the 18 character 0Hf install ID as the value for `-i`?  We're not able to reproduce this with the latest CLI.

**Comment by OrtooAdam** [comment]
Yes it's the full 18 chars id as returned in package install response json - result.Id

**Comment by shetzel** [comment]
Is the json response from the install command parsed for the ID and used in the install:report command?  If so, did the json shape change between 7.185.0 and 7.186.2?  I hope not, but it might have slipped through with some changes being made.

**Comment by OrtooAdam** [comment]
We were originally parsing the non JSON install response and when it stopped working on 03/02/2023 i thought maybe the response had changed slightly and affected our parsing. So to be sure i changed to using JSON install response and jq to extract the report id.

I've just tried another test and it works when the report id value is **not** within speech marks (as extracted by jq without -r flag - i've changed to use -r flag and the package report is now working.

As the package id and org alias were enclosed in speech marks for the package install command i had assumed the id would be fine with or without in report call too.

Apologies if this was not as intended, in which case this issue is closed.

**Comment by shetzel** [comment]
All of these versions work for me:
sfdx force:package:install:report -i '0Hf7d0000001kGcCAI'
sfdx force:package:install:report -i "0Hf7d0000001kGcCAI"
sfdx force:package:install:report -i 0Hf7d0000001kGcCAI

If there are any spaces in between the single or double quotes it will not work so if you're using them, please make sure there are no spaces.

**Comment by OrtooAdam** [comment]
That's really odd that it works for you with/without quotes. My only change from not working to working was to add -r flag to the jq command.
I know it shouldn't make a difference but have you tried with the additional -u parameter on report command as that seems the only difference.
