### ISSUE TITLE
Support destructive changes with force:source:deploy for production org.

### ISSUE THREAD

**Issue by bob-laz** [forcedotcom/cli#192]
**Is your feature request related to a problem? Please describe.**
I am trying to build a new deployment pipeline for my org using only the CLI and source format, moving away from the metadata API and metadata format. As far as I can tell there is no way to delete files from a production org using the CLI.

**What are you trying to do**
Delete files from a production org as part of a deployment.

**Describe the solution you'd like**
I would like to be able to run `sfdx force:source:deploy -x package.xml` and if a `destructiveChangesPre.xml` or `destructiveChangesPost.xml` file exists in the same directory, files in these manifests should be deleted from the org. Running `sfdx force:source:deploy -x package.xml --checkonly` should also validate these deletions.

**Describe alternatives you've considered**
I have tried `sfdx force:source:delete` but this command does not support a manifest file and as far as I can tell does not work against a production org.

**Additional context**
None at this time. Let me know if you have any questions or need clarification.

**Comment by daveespo** [comment]
:-) Asked and answered #188 

@clairebianchi -- can we keep Issues open that are in progress and perhaps flag them with a label indicating that they're planned for delivery?

**Comment by bob-laz** [comment]
Sorry I missed that in my search. I'll close the issue. thank you.
