### ISSUE TITLE
Case Field History Tracking "exceeded the allowed number of fields to track on a given entity"

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#1922]
### Summary
When creating a new scratch org, or building a new package version, the Case object is initialized with several standard fields with Field History Tracking (FHT) enabled. This means that when we have enabled FHT on 20 custom fields, we run into the error  "exceeded the allowed number of fields to track on a given entity"

### Steps To Reproduce:
**Repository to reproduce:** [dreamhouse-lwc](https://github.com/petter-eikeland/dreamhouse-lwc)

1.  Create a new scratch org
1.  Open and verify that 11 standard fields on Case have FHT enabled
1. [Optional] Create 20 custom fields with FHT enabled and deploy them

### Expected result
No standard fields on Case have FHT enabled

[Optional] Deploy 20 custom fields with FHT enabled --> All Custom fields deploy successfully

### Actual result
11 standard fields on Case have FHT enabled
[Optional] Deploy 20 custom fields with FHT enabled --> get "exceeded the allowed number of fields to track on a given entity" error

### System Information
```
{
  "cliVersion": "sfdx-cli/7.186.2",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.13.0",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 20.2.11 (user)",
    "@eon-com/eon-sfdx 1.9.4 (user)",
    "@oclif/plugin-autocomplete 1.4.2 (core)",
    "@oclif/plugin-commands 2.2.4 (core)",
    "@oclif/plugin-help 5.2.1 (core)",
    "@oclif/plugin-not-found 2.3.17 (core)",
    "@oclif/plugin-plugins 2.2.4 (core)",
    "@oclif/plugin-search 0.0.11 (core)",
    "@oclif/plugin-update 3.1.0 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.23 (core)",
    "@oclif/plugin-which 2.2.9 (core)",
    "1commerce 0.0.10 (user)",
    "alias 2.1.19 (core)",
    "apex 1.4.3 (core)",
    "auth 2.3.12 (core)",
    "community 2.1.5 (core)",
    "config 1.4.23 (core)",
    "custom-metadata 2.0.16 (core)",
    "data 2.1.22 (core)",
    "generator 2.0.17 (core)",
    "info 2.3.5 (core)",
    "limits 2.2.3 (core)",
    "org 2.2.24 (core)",
    "packaging 1.12.4 (core)",
    "schema 2.2.3 (core)",
    "signups 1.2.12 (core)",
    "source 2.3.16 (core)",
    "telemetry 2.0.7 (core)",
    "templates 55.2.3 (core)",
    "trust 2.3.0 (core)",
    "user 2.2.1 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.5 (core)",
    "sfdmu 4.26.2 (user)",
    "sfpowerkit 6.0.1 (user)"
  ],
  "osVersion": "Darwin 21.6.0",
  "shell": "zsh",
  "rootPath": "/Users/user/.local/share/sfdx/client/7.186.2-b2fe485"
}
```
### Additional information

_Feel free to attach a screenshot_.
![Screenshot 2023-02-10 at 08 46 40](https://user-images.githubusercontent.com/97173615/218032672-f70799be-30c6-4602-8cb6-b0ed083adbab.png)

**Comment by gleisonmalheiros** [comment]
Related?
https://issues.salesforce.com/issue/a028c00000qPztSAAS/toggling-history-tracking-may-cause-exceeded-the-allowed-number-of-fields-to-track-on-a-given-entity-error-during-mdapi-deployment

**Comment by petter-eikeland** [comment]
Yeah related, but still a separate issue
