### ISSUE TITLE
sfdx force:org:delete and org:delete:scratch lost flag to specify the devhub

### ISSUE THREAD

**Issue by bdovh** [forcedotcom/cli#1925]
### Summary

The new version of SFDX CLI has broken the `sfdx force:org:delete` command

### Steps To Reproduce:

1. Assume you have existing CI workflow, which was working just fine recent two years.
2. Suddenly it starts failing with an error:

```
sfdx force:org:delete -v sodh -p
  shell: /usr/bin/bash -e {0}
Warning: The force:org:delete command is deprecated. Use org:delete:scratch or org:delete:sandbox.
Error: Nonexistent flag: -v
See more help with --help
```

3. All it has is it tries to fetch the latest SFDX CLI and just delete the org after completion of CI step.

### Expected result

Expect existing CI workflows not to be broken by SFDX CLI updates.

### Actual result

Actually it is broken.

### System Information

Version of SFDX CLI is: sfdx-cli/7.187.1 linux-x64 node-v16.19.0

### Additional information

```
 sfdx force:org:delete -v sodh -p
  shell: /usr/bin/bash -e {0}
Warning: The force:org:delete command is deprecated. Use org:delete:scratch or org:delete:sandbox.
Error: Nonexistent flag: -v
See more help with --help
```

**Comment by bdovh** [comment]
<img width="600" alt="Screenshot 2023-02-10 at 17 03 55" src="https://user-images.githubusercontent.com/75684333/218124882-72fe460b-74a8-4212-9b4e-bd7b8b2bc2a2.png">
<img width="845" alt="Screenshot 2023-02-10 at 17 04 00" src="https://user-images.githubusercontent.com/75684333/218124885-85c0dd72-4bc5-41d1-b03f-bbc7d14bf9f3.png">

**Comment by mshanemc** [comment]
We didn't mean to break that.  Sorry!

It may have been working, but only accidentally.  You're not deleting a dev hub, you're deleting an org.

Use `-o` or `-u` instead to specify the scratch org alias/username (or in your case, it looks like you're maybe deleting the project's default org, so the hub is unnecessary information).

**Comment by bdovh** [comment]
@mshanemc the problem is default devhub is used for package versions, but another one is used for scratch org.
So if default devhub is different than devhub from which scratch org has been created, will it fail?

Or would I have to switch between active devhubs each time I need to delete a scratch org?

**Comment by mshanemc** [comment]
If you're authenticated to the scratch org, you can delete it.  The process goes something like,

you: please delete org X
cli: (finds that org in local authentications)
cli: (looks to see which hub it belongs to)
cli: "hey hub, delete org X"
hub: (marks it for deletion)
cli: (deletes it from local auth files)
cli: "ok, done!"

**Comment by bdovh** [comment]
I received some new error

Warning: This command is currently in beta. Any aspect of this command can change without advanced notice. Don't use beta commands in your scripts.
Error (1): Target file doesn't exist. path: /home/runner/.sfdx/test-rxo2auqa2ass@example.com.json

is this error expected to happen?

**Comment by mshanemc** [comment]
can you share the command that's causing that error?

**Comment by bdovh** [comment]
> can you share the command that's causing that error?

not sure, it is hard to detect. maybe `sfdx org:delete:scratch`?

This error started when I replaced `sfdx force:org:delete` with `sfdx org:delete:scratch` command
