### ISSUE TITLE
Re-composed StaticResource zip files are accumulating in a temp directory

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#193]
### Summary

Our CI server keeps running out of space in our temp folder (/tmp). The folder is littered with files named `sdx_srzip_7952627320663804.zip` (the numeric part varies)

Each `force:source:deploy` creates a new fleet of these files and they are never deleted. After a period of time, all disk space is exhausted

### Steps To Reproduce:

1. Create an SFDX project with an exploded Static Resource (i.e. the contents of a zip file)
2. Run `force:source:deploy`

### Expected result

My temp directory should not have any new files in it

### Actual result

An `sdx_srzip` file exists for each exploded StaticResource in the project 

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.25.3-16d54c01ee win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 46.15.3 (core)
├─ force-language-services 46.22.0 (core)
└─ salesforce-alm 46.20.0 (core)

sfdx-cli 7.25.3 (core)

**OS and version**:

Windows 10 Pro and Ubuntu 16

**Comment by daveespo** [comment]
The problem exists with the latest SFDX client and plugins too

@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 46.16.0 (core)
├─ force-language-services 46.23.0 (core)
└─ salesforce-alm 46.21.0 (core)

sfdx-cli 7.26.0 (core)

sfdx-cli/7.26.0-9118501918 win32-x64 node-v10.15.3

**Comment by jefersonchaves** [comment]
Facing the same issue in Linux and Mac. So, seems that is not something platform-specific.

**Comment by mshanemc** [comment]
The current deploy/retrieve commands and the [beta](https://github.com/forcedotcom/cli/issues/1258) push/pull commands no longer use temporary files.
