### ISSUE TITLE
Unable to make Org Snapshot Active.

### ISSUE THREAD

**Issue by Pradeepveeraj16** [forcedotcom/cli#1932]
We use Org shape to create snapshot. After Spring 23 release we have created New org shape. Usually Old org shape gets inactive when new orgshape gets created but we have 2 Active org for the same devhub.

Issue:
After building the Snapshot the status is in "ERROR" It does not become "Active". 

### Steps To Reproduce:

Starting: Building Org-Snapshot
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /__w/_temp/45a9c80d-894a-4ee4-9478-b1b6bd836d8f.sh
Warning: The "force org snapshot delete" command has been deprecated. Use "org delete snapshot" instead.
Successfully deleted snapshot OrgShapeSnap.
##### Get Snapshot Status #####
Warning: The "force org snapshot get" command has been deprecated. Use "org get snapshot" instead.
 Name               Value                
 ────────────────── ──────────────────── 
 Id                 0Oo3X0000008PCmSAM   
 Snapshot Name      OrgShapeSnap         
 Description                             
 Status             Error                
 Source Org         00DAa000000bEC5MAM   
 Created Date       02/13/2023, 06:15 AM 
 Last Modified Date 02/13/2023, 06:24 AM 
 Expiration Date                         
 Last Cloned Date                        
 Last Cloned By Id                       
Finishing: Building Org-Snapshape

### Expected result

Snapshot status should become 'Active' by 10 mins after building the snapshot

### Actual result

Snapshot Status is in "Error". If I try deleting the snapshot and create new, the status will be 'Inprogress' for a while and then turns to 'Error'

**Comment by mshanemc** [comment]
It could be related to this incident: https://trailblazer.salesforce.com/issues_view?id=a1p4V000003BIYGQA4

**Comment by Pradeepveeraj16** [comment]
Issue is related to know issue Reference W-12186950.
