### ISSUE TITLE
[API Version 57.0] - Global Picklist bug during package version create

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#1933]
### Summary
When updating source API version to 57.0, package version create fails due to missing global picklist error. Perhaps related to this:
https://help.salesforce.com/s/articleView?id=release-notes.rn_api_global_value_set_suffix.htm&release=242&type=5

### Steps To Reproduce:
**Repository to reproduce:** [dreamhouse-lwc](https://github.com/petter-eikeland/dreamhouse-lwc)

1.  Update `"sourceApiVersion": "57.0",` in sfdx-project.json
1.  Create global value set **Test**
1.  Create custom picklist field **Test__c** on e.g. Campaign
1.  Create custom picklist field **Test2__c** also on Campaign
1.  Create picklist dependency where **Test__c** is the controlling picklist and **Test2__c** the dependent picklist
1.  Create a new package using `sfdx package create -n campaign -r campaign -t Unlocked -v myhuborg` with both global value set and picklist fields
1.  Successfully create new version of campaign package using `sfdx package version create -p campaign -w 10 -x -v myhuborg -f config/project-scratch-def.json`
1.  Create a new package, e.g. campaign-field, that lists the campaign package as a dependency
1.  Try to create a new version of campaign-field package using `sfdx package version create -p campaign-field -w 10 -x -v myhuborg -f config/project-scratch-def.json`

### Expected result
New version of campaign-field package successfully created.

### Actual result
Package version create fails with the following error:
```
sfdx package version create -p campaign-field -w 40 -x -v myhuborg -f config/project-scratch-def.json
Version create.... Create version status: Error
Error (1): Multiple errors occurred: 
(1) Det oppstod en feil ved forsøk på å installere en pakkeavhengighet. ID 04t090000003oo0: Campaign.Test2__c: In field: controllingField - no CustomField named Campaign.Test__c found
(2) Det oppstod en feil ved forsøk på å installere en pakkeavhengighet. ID 04t090000003oo0: Campaign.Test__c: The global picklist cannot be resolved
```

**NB!** Language bug is already listed in #1921 

### System Information
```
{
  "cliVersion": "sfdx-cli/7.188.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.13.0",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 20.20.3 (user)",
    "@eon-com/eon-sfdx 1.9.4 (user)",
    "@oclif/plugin-autocomplete 1.4.5 (core)",
    "@oclif/plugin-commands 2.2.7 (core)",
    "@oclif/plugin-help 5.2.4 (core)",
    "@oclif/plugin-not-found 2.3.18 (core)",
    "@oclif/plugin-plugins 2.3.0 (core)",
    "@oclif/plugin-search 0.0.13 (core)",
    "@oclif/plugin-update 3.1.3 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.26 (core)",
    "@oclif/plugin-which 2.2.14 (core)",
    "1commerce 0.0.10 (user)",
    "alias 2.2.1 (core)",
    "apex 1.5.1 (core)",
    "auth 2.4.2 (core)",
    "community 2.2.1 (core)",
    "config 1.5.1 (core)",
    "custom-metadata 2.1.1 (core)",
    "data 2.2.1 (core)",
    "generator 2.0.17 (core)",
    "info 2.4.2 (core)",
    "limits 2.3.3 (core)",
    "org 2.3.2 (core)",
    "packaging 1.14.3 (core)",
    "schema 2.3.1 (core)",
    "signups 1.4.0 (core)",
    "source 2.5.1 (core)",
    "telemetry 2.1.1 (core)",
    "templates 55.4.1 (core)",
    "trust 2.4.1 (core)",
    "user 2.3.2 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.5 (core)",
    "sfdmu 4.18.2 (user)",
    "sfpowerkit 6.1.0 (user)"
  ],
  "osVersion": "Darwin 22.3.0",
  "shell": "zsh",
  "rootPath": "/Users/user/.local/share/sfdx/client/7.188.1-4a4bb9c"
}
```
### Additional information
When refering to global value set with the suffix in **Test__c field** as per the Spring 23 documentation above:
```
   <valueSet>
        <restricted>true</restricted>
        <valueSetName>Test__gvs</valueSetName>
    </valueSet>
```
no error is thrown during package version creation of the campaign package. However, the same error is thrown when creating a new version of the campaign-field package. Although, sfdx deploy throws the following error when deploying the updated file with the suffix to a scratch org: 
```
Deploying v57.0 metadata to test-e473cmhfa2hx@example.com using the v57.0 SOAP API
Deploy ID: 0AfAa000002emWEKAY
DEPLOY PROGRESS | ████████████████████████████████████████ | 0/0 Components

=== Component Failures [1]

 Type  Name                          Problem                                         
 ───── ───────────────────────────── ─────────────────────────────────────────────── 
 Error Campaign.Test__c  The global picklist cannot be resolved (168:13)
```

**Comment by arafesthain** [comment]
Hi @mshanemc any timeline to share with us ?

**Comment by petter-eikeland** [comment]
@arafesthain FYI I got this response from Salesforce Support:

"As we have this issue being reviewed by our Product team, the relevant details have been shared with them.

This issue has been identified as a bug at our end and would be fixed soon in the upcoming patches/releases (Safe Harbor). Following is the Known issue link:

https://trailblazer.salesforce.com/issues_view?id=a1p3A0000003fLSQAY"

I don't think it is a very accurate description. However, Support assured me that the bug described above is being worked on
