### ISSUE TITLE
ERROR running force:source:deploy: Component conversion failed: Cannot read properties of undefined (reading 'RecordType')

### ISSUE THREAD

**Issue by satyasfdc6** [forcedotcom/cli#1937]
Hello,

I have updated my SFDX cli to 7.183.1 using below docker image

https://hub.docker.com/layers/salesforce/salesforcedx/7.183.1-full/images/sha256-d6e0eff7e16b3914b701b07312c576b890a8d33bb704f143e764f791cc82958e?context=explore

and while i am trying to run below sfdx:force:deploy command I am encountering this issue..

sfdx force:source:deploy --manifest manifest/package.xml  --loglevel error --targetusername $USERNAME --checkonly --testlevel RunLocalTests -w 60
 ›   Warning: sfdx-cli update available from 7.183.1 to 7.186.2.
ERROR running force:source:deploy:  Component conversion failed: Cannot read properties of undefined (reading 'RecordType')
 

However while running the same command from VSCODE is not throwing this [error.In](https://error.in/) my system the CLI version is too 7.183.1 which is successfully executing the command.

 

Note:Even I tried updating to the latest version(7.186.2),which throws the same error

 

ERROR running force:source:deploy:  Component conversion failed: Cannot read properties of undefined (reading 'RecordType')
 JSON OUTPUT:

{

  "status": 1,

  "name": "Conversion",

  "message": "Component conversion failed: Cannot read properties of undefined (reading 'RecordType')",

  "exitCode": 1,

  "actions": [],

  "context": "Deploy",

  "stack": "Conversion: Component conversion failed: Cannot read properties of undefined (reading 'RecordType')\n    at MetadataConverter.convert (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/convert/metadataConverter.js:107:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async MetadataApiDeploy.getZipBuffer (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/client/metadataApiDeploy.js:380:35)\n    at async Promise.all (index 0)\n    at async MetadataApiDeploy.pre (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/client/metadataApiDeploy.js:285:29)\n    at async MetadataApiDeploy.start (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/client/metadataTransfer.js:41:29)\n    at async ComponentSet.deploy (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/collections/componentSet.js:196:9)\n    at async Deploy.deploy (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-source/lib/commands/force/source/deploy.js:107:28)\n    at async Deploy.run (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-source/lib/commands/force/source/deploy.js:33:9)\n    at async Deploy._run (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:102:40)\n    at async Config.runCommand (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:272:25)\n    at async run (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/main.js:74:5)\nCaused by: TypeError: Cannot read properties of undefined (reading 'RecordType')\n    at RecompositionFinalizer.recompose (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/convert/convertContext.js:87:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async RecompositionFinalizer.finalize (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/convert/convertContext.js:43:38)\n    at async ConvertContext.executeFinalizers (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/convert/convertContext.js:264:17)\n    at async ComponentConverter._flush (/usr/local/lib/nodejs/lib/node_modules/sfdx-cli/node_modules/@salesforce/source-deploy-retrieve/lib/src/convert/streams.js:87:30)",

  "warnings": [],

  "commandName": "Deploy"

}

Upon further investigation I found If Custom Object is added to my package.xml its throwing above error.
Is there any issue with the docker image or package.xml
Any suggestions on this is really appreciable

**Comment by mshanemc** [comment]
@satyasfdc6 there's some instructions in our issue template that provide version and plugin information we need.  Can you please run that?

**Comment by mshanemc** [comment]
Looking into where this error is coming from, can you check that your metadata looks like

```
objects/
└ Something__c/
  └ Something__c.object-meta.xml
  └ recordTypes/
    └ whatever.recordType-meta.xml
```

**Comment by satyasfdc6** [comment]
> Looking into where this error is coming from, can you check that your metadata looks like
> 
> ```
> objects/
> └ Something__c/
>   └ Something__c.object-meta.xml
>   └ recordTypes/
>     └ whatever.recordType-meta.xml
> ```

this is how my directory looks like as exactly mentioned by you
![image](https://user-images.githubusercontent.com/125441303/219070086-d6bcbab5-4c0b-43b3-a6b0-b82eea2246f5.png)

**Comment by mshanemc** [comment]
is Account the only object?  Might there be some object that has `recordTypes` but doesn't have an object-meta.xml, or some recordTypes not inside an object folder, or some files with the wrong extension?
