### ISSUE TITLE
sfdx force:project:create generates a project with an unexpected sourceAPIVersion in the sfdx-project.json 

### ISSUE THREAD

**Issue by ganesh2109-cloud** [forcedotcom/cli#1939]
### Summary

sfdx force:project:create generates a project with a sfdx-project.json sourceAPIVersion which is hardcoded in @salesforce/templates/package.json

### Steps To Reproduce:

sfdx config:set apiVersion=57.0 -g
sfdx force:project:create

### Expected result

The sourceAPIVersion in sfdx-project.json should be 57.0
The sourceApiVersion in the sfdx-project.json should get the value from the sfdx-config.json first, if not defined there it should take the default value as it is now.

### Actual result

It is always taken from the hardcoded "version" attribute in an internal @salesforce/templates/package.json

### System Information

{
  "cliVersion": "sfdx-cli/7.187.1",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.1.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.4.4 (core)",
    "@oclif/plugin-commands 2.2.5 (core)",
    "@oclif/plugin-help 5.2.2 (core)",
    "@oclif/plugin-not-found 2.3.17 (core)",
    "@oclif/plugin-plugins 2.3.0 (core)",
    "@oclif/plugin-search 0.0.11 (core)",
    "@oclif/plugin-update 3.1.1 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.24 (core)",
    "@oclif/plugin-which 2.2.12 (core)",
    "alias 2.2.0 (core)",
    "apex 1.5.0 (core)",
    "auth 2.4.0 (core)",
    "community 2.2.0 (core)",
    "config 1.5.0 (core)",
    "custom-metadata 2.1.0 (core)",
    "data 2.2.0 (core)",
    "generator 2.0.17 (core)",
    "info 2.4.0 (core)",
    "limits 2.3.0 (core)",
    "org 2.3.0 (core)",
    "packaging 1.14.1 (core)",
    "schema 2.3.0 (core)",
    "signups 1.4.0 (core)",
    "source 2.4.1 (core)",
    "telemetry 2.1.0 (core)",
    "templates 55.3.0 (core)",
    "trust 2.4.0 (core)",
    "user 2.3.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.5 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\M65F134\\Downloads\\node-v18.1.0-win-x64\\node_modules\\sfdx-cli"
}

### Additional information
The same erroneous behavior is also in the latest-rc version: [7.188.1](https://www.npmjs.com/package/sfdx-cli/v/7.188.1)

**Comment by mshanemc** [comment]
I agree that's how it should work (it should use an `--api-version` flag that respects the config value like many other commands do).

**Comment by shetzel** [comment]
This is now in the latest CLI, 7.208.10
