### ISSUE TITLE
SFDX_DISABLE_INSIGHTS doesn't appear to prevent telemetry reporting

### ISSUE THREAD

**Issue by jeremyhenson** [forcedotcom/cli#194]
### Summary

Our CI jobs fail when telemetry reporting occurs because the CI machines are behind a proxy that does not have access to the endpoints.

When attempting to disable telemetry using all the following methods...

export SFDX_DISABLE_INSIGHTS=true
SFDX_DISABLE_INSIGHTS=true
SFDX_DISABLE_INSIGHTS=true $WORKSPACE_DIR/node_modules/.bin/sfdx force:mdapi:deploy

... it doesn't prevent the telemetry and the jobs fail with the following error:

08:39:20 2019-10-04T15:39:20.264Z sfdx:core TRACE Setup child 'telemetry' logger instance
08:39:20 2019-10-04T15:39:20.265Z sfdx:telemetry DEBUG creating appInsightsClient
08:39:20 2019-10-04T15:39:20.335Z sfdx:telemetry DEBUG Sending telemetry event: sfdx-plugin-analytics/ERROR
08:39:20 ApplicationInsights:CorrelationIdManager [ { Error: connect ECONNREFUSED 52.167.221.184:443
08:39:20       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
08:39:20     errno: 'ECONNREFUSED',
08:39:20     code: 'ECONNREFUSED',
08:39:20     syscall: 'connect',
08:39:20     address: '52.167.221.184',
08:39:20     port: 443 } ]

 (SFDC Support Case # 24376331) 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.27.0 linux-x64 node-v10.15.3

**Comment by jeremyhenson** [comment]
Salesforce Support is telling me "_As per the latest updates that I have heard from team internally,it is not possible to disable telemetry in CLI._"

Seems odd since SFDX_DISABLE_INSIGHTS is an available option.

**Comment by clairebianchi** [comment]
@jeremyhenson I apologize, setting this environment var should disable insights. We will look into the issue.

**Comment by clairebianchi** [comment]
@jeremyhenson, also can you please send me your case number with support?

**Comment by mdonnalley** [comment]
@jeremyhenson Could you please provide the full debug output (use `--dev-debug`) as well as the output from `sfdx plugins --core`?

**Comment by jeremyhenson** [comment]
> @jeremyhenson, also can you please send me your case number with support?

24376331, thanks

**Comment by jeremyhenson** [comment]
> @jeremyhenson Could you please provide the full debug output (use `--dev-debug`) as well as the output from `sfdx plugins --core`?

[dev_debug_deploy.txt](https://github.com/forcedotcom/cli/files/3713705/dev_debug_deploy.txt)

Attached - this deploy I set SFDX_DISABLE_INSIGHTS by the following:
SFDX_DISABLE_INSIGHTS=true

I have tried it with...
export SFDX_DISABLE_INSIGHTS=true
SFDX_DISABLE_INSIGHTS=true sfdx force:mdapi:deploy
... with the same result

Also the jobs have to fail in order for this to happen and the telemetry to send, so I added some invalid metadata to force it to fail.

**Comment by jeremyhenson** [comment]
@mdonnalley @clairebianchi - wanted to check in here and see if you had any updates? Thanks!

**Comment by clairebianchi** [comment]
@jeremyhenson this is now fixed. Please update your CLI and it should be working. I will also follow up again with support to make sure they know that this is the correct way to turn off telemetry

**Comment by jeremyhenson** [comment]
Yep looks fixed - thanks!

**Comment by paferpo** [comment]
Hi Claire, I was trying to disable it on a Windows machine. According to the documentation, the variables are for Linux and Mac only:
"Environment variables override CLI runtime configuration values. (Linux and Mac only)"
There is not any other way to do the same on Windows?

Thanks!

**Comment by clairebianchi** [comment]
@paferpo that is incorrect, using the env var will work on Windows as well.

There has been an update, the env var is `SFDX_DISABLE_TELEMETRY` 

We are updating the Documentation, I am so sorry for the confusion
