### ISSUE TITLE
The "org shape list" command fails when one org credential fails

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#1940]
### Summary

Execution of the `org shape list` command fails when you have multiple org connections but one of those connections fails to authenticate.

### Steps To Reproduce:

1. Setup 2 or more connections to orgs
2. Take one connection and create a condition where the CLI authentication would fail.  i.e. JWT auth failure, user account deactivated, etc.
3. execute the `org shape list` command

### Expected result

If the `org shape list` command fails one connection, it should not abort the entire process.  It should move on to the next auth connection available and then provide a list of shapes for the orgs that it could authenticate to.

### Actual result

The command fails when it encounters the first auth connection that is invalid and does not report on any of the orgs it was able to look at.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
I am using bash and zsh

- SFDX version
```
{
  "cliVersion": "sfdx-cli/7.187.1",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.13.0",
  "pluginVersions": [
    "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.4 (user)",
    "@mshanemc/plugin-streaming 1.1.7 (user)",
    "@mshanemc/sfdx-sosl 1.1.0 (user)",
    "@oclif/plugin-autocomplete 1.4.5 (user)",
    "@oclif/plugin-commands 2.2.5 (core)",
    "@oclif/plugin-help 5.2.2 (core)",
    "@oclif/plugin-not-found 2.3.17 (core)",
    "@oclif/plugin-plugins 2.3.0 (core)",
    "@oclif/plugin-search 0.0.11 (core)",
    "@oclif/plugin-update 3.1.1 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.24 (core)",
    "@oclif/plugin-which 2.2.12 (core)",
    "alias 2.2.0 (core)",
    "apex 1.5.0 (core)",
    "auth 2.4.0 (core)",
    "community 2.2.0 (core)",
    "config 1.5.0 (core)",
    "custom-metadata 2.1.0 (core)",
    "data 2.2.0 (core)",
    "generator 2.0.17 (core)",
    "info 2.4.0 (core)",
    "limits 2.3.0 (core)",
    "org 2.3.0 (core)",
    "packaging 1.14.1 (core)",
    "schema 2.3.0 (core)",
    "signups 1.4.0 (core)",
    "source 2.4.1 (core)",
    "telemetry 2.1.0 (core)",
    "templates 55.3.0 (core)",
    "trust 2.4.0 (core)",
    "user 2.3.0 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@steampunk/sfdx-steampunk-org 0.1.1 (user)",
    "salesforce-alm 54.8.5 (core)",
    "sfdmu 4.26.5 (user)",
    "shane-sfdx-plugins 4.43.0 (user)",
    "soqlx-opener 0.1.12 (user)"
  ],
  "osVersion": "Darwin 22.2.0",
  "shell": "zsh",
  "rootPath": "/Users/john/.local/share/sfdx/client/7.187.1-09910f2"
}
```

### Additional information

n/a

**Comment by ekapner** [comment]
Rohit and team are aware of this issue - and I'm in process of documenting some workaround tips. Like running --clean.

**Comment by ekapner** [comment]
@ImJohnMDaniel -- And the dev team does have an open bug to fix this issue: W-12432302

**Comment by ImJohnMDaniel** [comment]
Thanks for the update @ekapner !

**Comment by mshanemc** [comment]
@W-12432302@

**Comment by mshanemc** [comment]
no longer reproducible, not from a recent intentional change.  

QA notes
`org list shape` see 3 shapes
change the username of one of the orgs to something wrong
✅ other 2 shapes show up, 1 is missing, we have a warning in the output
