### ISSUE TITLE
sfdx command via proxy not resilient on 5xx errors - zombie loop

### ISSUE THREAD

**Issue by MaciekLeks** [forcedotcom/cli#1944]
### Summary
Context: Deploying on scratches

We are struggling with  sdx-cli via proxy. For several days we have been noticing a lot of 5xx errors on proxy side (your DNS changes A records every 30 seonds and our Squid in many cases does not get A records from DNS and responds to sfdx with the code 500 ) that led to many timeouts on sfdx command side (`Metadata API request failed: The client has timed out. `)...

So if you get 500 via tunnel sfdx starts behaving like a `zombie`. It cannot move farther.

### Steps To Reproduce:
1. You need a proxy, we use squid v5.7
2. set proxy env accordingly (e.g. https_proxy) accordingly
3. For at least 5  parallel deployments
a. Build scratch
b. Start deploying a lot of metadata, e..g 8000 shoud be enough (e..g `sfdx force:source:deploy -u alias -p force-app -g -w 120`)

### Expected result
`sfdx` should retry on 5xx errors not stop responding.

### Actual result
Screenshot:
- lef hand side: gitlab runner job - zombie loop which ends with "Metadata API request failed: The client has timed out."
- right hand side: top record /500 - from this point in time sfdx becomes "zombie" (waiting loop)

### System Information
- GKE
- Alpine containers
- sfdx-cli/7.187.1 linux-x64 node-v18.14.0

_Feel free to attach a screenshot_.
![sfdx-proxy-500](https://user-images.githubusercontent.com/11923449/219636726-c0b1cd2a-44ee-47b3-aeac-ce3a330d970e.png)

**Comment by MaciekLeks** [comment]
For at least 2-3 weeks we've been investigating a huge problem with your DNS which one of the side effects is the "zombie loop" I had raised above. We figured out what's wrong. So to catch the context.  Our scratch orgs fabric works as a fabric not a  craft manufacture, so we build a lot of scratches every day.

We face the problem of NXDomain error code (especially on your scratch orgs) handled by our Squid proxy which we try to rescue by a farm of proxies which handle NXDomain error after a 1-2-3 seconds and try to get A Record from a public DNS server once again. Sometimes it's not possible and the last-resort proxy returns the 500 error code which leads here to 'zombie loop' (it does not matter what sfdx command we run - it happens everywhere where TCP connection with an org is needed).

So, what we figured out:
1. No matter if we use proxy or not we struggled with NXDomain error on public DNS servers (the same one you recommend in the official docs) - on GCP, or even AWS (with nameservers set to 8.8.8.8, 1.1.1.1,...)
2. SF works on AWS and you probably test it only on AWS which does not need using public DNS so the path to the AWS Authoritative DNS Server is short there.  

P.S. Public DNS server IPs are VIPs so the problem may lay in our localization (Poland@Europe).

**Comment by shetzel** [comment]
I don't think the CLI should retry on http 5xx errors.  The CLI can't distinguish between a 500 that should not be retried and a proxy returning a 500 that might be ok to retry.  It's safest to stop and report the error or "Metadata API request failed: The client has timed out."

**Comment by MaciekLeks** [comment]
It turned out to be a problem with your infrastructure (DNS), but let's back to the issue. If you get a 5xx error why don't you stop the whole command? If you do not want to retry you should immediately exit with an error (5xx) .

**Comment by shetzel** [comment]
I agree, the command should exit upon receiving a 5xx response when polling.  It should be doing that in the latest CLI version.  What is the output of `sfdx version --verbose` (or `sfdx doctor`)?  Do you see this happen when not running multiple requests in parallel?

**Comment by MaciekLeks** [comment]
@shetzel

`sfdx-cli/7.198.7` - Is it good enough?

**Comment by shetzel** [comment]
If all the plugin versions are `(core)`, meaning you have not overridden any plugins used by the CLI, then that is probably enough.
