### ISSUE TITLE
Enable customers to version Package Settings

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1949]
**Is your feature request related to a problem? Please describe.**
Yes, I can't version installed package settings because there isn't a native/standardized solution on the platform for doing so. After installing a package, I have to manually open that [configuration page](https://salesforce.stackexchange.com/questions/92355/configuration-page-for-package) to set package settings by hand.

**What are you trying to do**

1. Version package settings.
2. Automate package configuration after installation.

**Describe the solution you'd like**

`sfdx-project.json` could introduce new set of settings that would control how package settings are configured, such as

````json
{
   "packageDirectories":[
      {
         "name":"my-package",
         "versionNumber":"1.0.0",
         "configuration":{
            "required":true,
            "settings":{
               "setting_1":{
                  "type":"boolean",
                  "default":true,
                  "description" : "Used for ...."
               },
               "setting_2":{
                  "type":"string",
                  "default":"bla", 
                  "description" : "Used for ...."
               },
               "setting_3":{
                  "type":"string",
                  "default":"bla",
                  "required":true,
                  "description" : "Used for ...."
               },
              "setting_4":{
                  "type": "options",
                  "options": ["1", "2", "3"],
                  "default":"1", 
                  "description" : "Used for ...."
               },
            }
         }
      }
   ]
}
````

- These package settings could be used in Apex Clases

````java
System.PackageSettings
````

Package Developers would no longer waste their time creating their own way to store, read and write these settings.

- These settings could also be used to generate these package configuration pages mentioned in this [post](https://salesforce.stackexchange.com/questions/92355/configuration-page-for-package). 
Package Developers would no longer waste their time creating their own visualforce page for this purpose.

This page could be displayed before proceeding with the package instalation when `packageDirectories[].configuration.required` is true, and when installing a package using a link

- These settings could be used by `sfdx force:package:install`

When `packageDirectories[].configuration.required` is `true`, sfdx would ask the values for these settings before installing the package. Since these settings are part of the package definition, sfdx would know exactly what to ask, and the type of information each property requires. For instance:

````shell
sfdx force:package:install -p <package_id>
setting_1 [default: true] [true, false]: true
setting_2: bla
setting_3 [default: bla]: blabla
setting_4 [default: 1] [1,2,3,4]: 2
````

These settings could be set with a json file
 `sfdx force:package:install -p <package_id> --configuration configuration.json`

Each one of these settings could also be set individually (something similar to -D in maven): 
`sfdx force:package:install -p <package_id> -Ssetting_1 true -Ssetting_2 bla -Ssetting_3 bla -Ssetting_4 2`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by daveespo** [comment]
@AllanOricil  -- are you referring to Managed packages? If so, have you considered using an [InstallHandler](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_install_handler.htm) -- InstallHandler allows you to be far more expressive than what you're proposing above

**Comment by AllanOricil** [comment]
> @AllanOricil  -- are you referring to Managed packages? If so, have you considered using an [InstallHandler](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_install_handler.htm) -- InstallHandler allows you to be far more expressive than what you're proposing above

Nope. I want something that can work with any type of package, including non packaged metadata. 

The goal of this feature request is to enable developers to export"package" settings and create a standard way that every package developer must follow.
