### ISSUE TITLE
Is it possible to use force:source:delete against a production org?

### ISSUE THREAD

**Issue by bob-laz** [forcedotcom/cli#195]
Just a question, wondering if it is possible to use `force:source:delete` against a production org? [Documentation](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_build_mdapi_production.htm) states that `force:source:deploy` can be used to deploy files to a production org, but not sure how deleting would work with validation rules in place for production orgs. My organization would prefer I not try to delete a random file from production to test this so I thought I would ask :-)

**Comment by clairebianchi** [comment]
Yes, force:source:delete works against production orgs. You can test how the command would work with your validation rules in a scratch org.
