### ISSUE TITLE
Unable to Deploy or Retrieve on Debian all of a sudden

### ISSUE THREAD

**Issue by prateekamana** [forcedotcom/cli#1952]
### Summary

This might be related to the fact that after successfully authorizing the org, the cli has started to create .sfdx/ and .sf/ directories in my home directory (~/) I don't think it was like that before. Now it gives me the error org not found or can not decipher.

### Steps To Reproduce:

1.  Authorize an org in Debian 
1.  Try to retrieve after authorizing
2. Get the error that org can not be found.

### Expected result

Should have been able to successfully retrieve it 

### Actual result

Got errors org can not be found instead

### System Information

- Which shell/terminal are you using? VSCode terminal

- If you are using `sfdx`
```
{
  "cliVersion": "sfdx-cli/7.188.1",
  "architecture": "linux-x64",
  "nodeVersion": "node-v16.15.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.4.5 (core)",
    "@oclif/plugin-commands 2.2.7 (core)",
    "@oclif/plugin-help 5.2.4 (core)",
    "@oclif/plugin-not-found 2.3.18 (core)",
    "@oclif/plugin-plugins 2.3.0 (core)",
    "@oclif/plugin-search 0.0.13 (core)",
    "@oclif/plugin-update 3.1.3 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.26 (core)",
    "@oclif/plugin-which 2.2.14 (core)",
    "@salesforce/lwc-dev-server 2.11.0 (user)",
    "alias 2.2.1 (core)",
    "apex 1.5.1 (core)",
    "auth 2.4.2 (core)",
    "community 2.2.1 (core)",
    "config 1.5.1 (core)",
    "custom-metadata 2.1.1 (core)",
    "data 2.2.1 (core)",
    "generator 2.0.17 (core)",
    "info 2.4.2 (core)",
    "limits 2.3.3 (core)",
    "org 2.3.2 (core)",
    "packaging 1.14.3 (core)",
    "schema 2.3.1 (core)",
    "signups 1.4.0 (core)",
    "source 2.5.1 (core)",
    "telemetry 2.1.1 (core)",
    "templates 55.4.1 (core)",
    "trust 2.4.1 (core)",
    "user 2.3.2 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.5 (core)"
  ],
  "osVersion": "Linux 5.10.0-15-amd64",
  "shell": "bash",
  "rootPath": "/home/amana/.npm_packages/lib/node_modules/sfdx-cli"
}
```

**Comment by prateekamana** [comment]
I was able to solve a similar issue by removing these .sfdx/ project files from my home directory (~/) but now after each authorization they are generated in my home. 
https://github.com/forcedotcom/salesforcedx-vscode/issues/4170

**Comment by prateekamana** [comment]
I don't know what I did exactly, but I do remember installing the normal sfdx-cli (without npm) using the standard procedure with the `install` script, and updating it, and it worked after that I guess.

**Comment by prateekamana** [comment]
This issue flickers, sometimes it arises and sometimes it doesn't...

**Comment by WillieRuemmele** [comment]
Hey @prateekamana have you been seeing this happening with the new `sf` v2 CLI?
