### ISSUE TITLE
Publishing package errors with `Cannot read properties of undefined (reading 'Id')`

### ISSUE THREAD

**Issue by TheOptimist** [forcedotcom/cli#1954]
### Summary
Cannot publish package due to `cannot read properties of undefined (reading 'Id')`

### Steps To Reproduce:
I can't provide a repository as it contains confidential material. 

I have two separate machines (my local development machine and a build agent machine). Currently I am successfully able to publish our specific package on my local development machine. The build agent however gets the above error about not being able to read undefined.

As far as I can work out, the machines are configured (for sfdx) identically, and they are attempting the publish operations from identical projects (from git). Both machines are authorized to the `devpkg` org via sfdxurl:store operations. The sfdx project the following command is based on is attached.

1. Run `npx sfdx package version create -p qa -v devpkg --json --skip-validation --j -x`

The error message is really not clear here. It does not tell me if it's something I've got configured wrong on my machine (which may well be the case). These build agents were able to publish these packages before when it was in a completely separate sfdx-project. Having joined them together in a single project (easier development on our side) publishing still obviously works as I can publish from my local machine.

### Expected result
The package is published.

### Actual result
Error: `Cannot read properties of undefined (reading 'Id')`

### System Information
PowerShell 7

See attached files for `doctor` output from both machines. The sfdx proejct file that we're using has also been attached, scrubbed of some information.

### Additional information

[sfdx-doctor-local.txt](https://github.com/forcedotcom/cli/files/10794491/sfdx-doctor-local.txt)
[sfdx-doctor-agent.txt](https://github.com/forcedotcom/cli/files/10794492/sfdx-doctor-agent.txt)
[sfdx-project.redacted.txt](https://github.com/forcedotcom/cli/files/10794534/sfdx-project.redacted.txt)

**Comment by peternhale** [comment]
@TheOptimist I don't see the doctor output for the debug output. Is that file available?

**Comment by TheOptimist** [comment]
Attached two trace files from the publishing operations @peternhale - let me know if that's what you need. I've included both the SCVQA and SCV package traces (I only experience the problem when publishing SCVQA).

[publishing-scv-trace-log.txt](https://github.com/forcedotcom/cli/files/10814739/publishing-scv-trace-log.txt)
[publishing-scvqa-trace-log.txt](https://github.com/forcedotcom/cli/files/10814742/publishing-scvqa-trace-log.txt)

**Comment by peternhale** [comment]
Thank you @TheOptimist

**Comment by peternhale** [comment]
@TheOptimist I was expecting debug level logging in these files. I was wondering if you could run with doctor again like this.

sfdx doctor -c "package version create -p qa -v devpkg --json --skip-validation --j -x"

and then return the files produced to me. Thanks in advance

**Comment by TheOptimist** [comment]
@peternhale Attached a series of files here to look through. A new version was published recently, so have included output from both the version we have currently defined in our systems, and the new version (same result). Latest version are listed first.

[7.188-1677247502458-command-stdout.log](https://github.com/forcedotcom/cli/files/10825004/7.188-1677247502458-command-stdout.log)
[7.188-1677247502458-command-debug.log](https://github.com/forcedotcom/cli/files/10825007/7.188-1677247502458-command-debug.log)
[7.188-1677247502458-diagnosis.json.txt](https://github.com/forcedotcom/cli/files/10825014/7.188-1677247502458-diagnosis.json.txt)

[7.187-1677245836117-command-stdout.log](https://github.com/forcedotcom/cli/files/10825016/7.187-1677245836117-command-stdout.log)
[7.187-1677245836117-command-debug.log](https://github.com/forcedotcom/cli/files/10825017/7.187-1677245836117-command-debug.log)
[7.187-1677245836117-diagnosis.json.txt](https://github.com/forcedotcom/cli/files/10825018/7.187-1677245836117-diagnosis.json.txt)

**Comment by peternhale** [comment]
Thank you

**Comment by TheOptimist** [comment]
Thanks @peternhale - will head back over to our partner channel and pursue this there.
