### ISSUE TITLE
sf org create sandbox --clone --license-type conflict

### ISSUE THREAD

**Issue by mpaul1** [forcedotcom/cli#1957]
Using the clone attribute alone responds that it needs a license-type specified, but if you specify both - the response is you cannot use both together. 

sf org create sandbox --name devsan2--license-type Developer --alias devsan2--clone devsan1--target-org prod
Error: The following errors occurred:
  --clone=StdDlySan2 cannot also be provided when using --license-type
  --license-type=Developer cannot also be provided when using --clone

### System Information
sfdx-cli/7.187.1 win32-x64 node-v18.14.0

Powershell
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  2364

sf version --verbose --json results:
{
  "cliVersion": "@salesforce/cli/1.66.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.14.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.0 (core)",
    "@oclif/plugin-commands 2.2.9 (core)",
    "@oclif/plugin-help 5.2.4 (core)",
    "@oclif/plugin-not-found 2.3.20 (core)",
    "@oclif/plugin-plugins 2.3.2 (core)",
    "@oclif/plugin-search 0.0.13 (core)",
    "@oclif/plugin-update 3.1.4 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.27 (core)",
    "@oclif/plugin-which 2.2.15 (core)",
    "apex 2.2.0 (core)",
    "data 2.2.1 (core)",
    "deploy-retrieve 1.8.1 (core)",
    "env 2.0.4 (core)",
    "functions 1.19.3 (core)",
    "info 2.4.2 (core)",
    "limits 2.3.3 (core)",
    "login 1.1.18 (core)",
    "org 2.4.0 (core)",
    "schema 2.3.1 (core)",
    "settings 1.2.2 (core)",
    "sobject 0.1.2 (core)",
    "telemetry 2.1.1 (core)",
    "templates 55.4.1 (core)",
    "trust 2.4.1 (core)",
    "user 2.3.2 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\MPaul001\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli"
}

**Comment by cristiand391** [comment]
This should be fixed in sfdx >= v7.141.1.
