### ISSUE TITLE
Warning: apex run is not a sf command.

### ISSUE THREAD

**Issue by dschach** [forcedotcom/cli#1958]
### Summary

I am trying to run this line
```
sf apex run --apex-code-file ./data/sample-data.apex
```
The following line does work
```
sfdx force:apex:execute -f ./data/sample-data.apex
```
And the documentation clearly says that the sf command is valid: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_apex_commands_unified.htm#cli_reference_apex_run_unified

### Steps To Reproduce:

**Repository to reproduce:** [ActionPlansV4](https://github.com/dschach/ActionPlansV4)

I think this is a universal problem, so I don't think it would make a difference which repository I use.

### Expected result

Anonymous Apex debug log in the CLI terminal

### Actual result

CLI error: Warning: apex run is not a sf command.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

zsh in VSCode on OSX

```json
{
  "cliVersion": "@salesforce/cli/1.65.0",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.13.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.4.5 (core)",
    "@oclif/plugin-commands 2.2.7 (core)",
    "@oclif/plugin-help 5.2.4 (core)",
    "@oclif/plugin-not-found 2.3.18 (core)",
    "@oclif/plugin-plugins 2.3.0 (core)",
    "@oclif/plugin-search 0.0.13 (core)",
    "@oclif/plugin-update 3.1.3 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.26 (core)",
    "@oclif/plugin-which 2.2.14 (core)",
    "community 2.2.1 (core)",
    "custom-metadata 2.1.1 (core)",
    "data 2.2.1 (core)",
    "deploy-retrieve 1.8.0 (core)",
    "env 2.0.2 (core)",
    "functions 1.17.4 (core)",
    "generate 1.1.2 (core)",
    "info 2.4.2 (core)",
    "limits 2.3.3 (core)",
    "login 1.1.18 (core)",
    "org 2.3.2 (core)",
    "schema 2.3.1 (core)",
    "settings 1.2.1 (core)",
    "signups 1.4.0 (core)",
    "sobject 0.1.2 (core)",
    "telemetry 2.1.1 (core)",
    "trust 2.4.1 (core)",
    "user 2.3.2 (core)"
  ],
  "osVersion": "Darwin 22.3.0",
  "shell": "zsh",
  "rootPath": "/Users/dschach/.local/share/sfdx/client/7.188.1-4a4bb9c/sf"
}
```

### Additional information

<img width="414" alt="sf apex run" src="https://user-images.githubusercontent.com/636977/220751660-19f3c756-a363-49f5-9555-20c76664fa7f.png">

**Comment by dschach** [comment]
Wait - I just checked the release notes in this org. It seems that this command is in the stable-rc version... but the docs say that it is available.

This may be a documentation mismatch problem.

**Comment by dschach** [comment]
Yes, the documentation is out of sync - so perhaps this is a docs issue. The README for sfdx says that the flag is `--file`, but the documentation says `--apex-code-file`. Confusing!

I will stick with the sfdx command until this gets to the stable release next week.

**Comment by peternhale** [comment]
@dschach when we publish a release candidate, the release notes announce which version the changes will be available in latest. Version 1.66.2 (promoted today from latest-rc) contains the apex commands.

**Comment by jshackell-sfdc** [comment]
Just want to add that there IS a bit of a doc-timing issue here.  I've noticed that the CLI Reference is sometimes published on developer.salesforce.com a few hours, sometimes a whole day, before an "sf" release goes from stable-rc to stable on Wednesdays.  We're dealing with different publishing schedules/processes for docs vs CLI releases, so there's not much I can do.  The other alternative is for the CLI Reference to be a week out of date, which isn't ideal, but maybe less confusing?  I'm not sure.  In any case, sorry for the confusion.
