### ISSUE TITLE
Add support for `queryAll`

### ISSUE THREAD

**Issue by surajp** [forcedotcom/cli#1959]
**Is your feature request related to a problem? Please describe.**
Currently, the CLI's `data:query` command does not seem to support `queryAll` which is frustrating when trying to fetch deleted records, archived activities, etc.

**What are you trying to do**
Fetch deleted records/archived activities.

**Describe the solution you'd like**
The `data:query` command should add support for an `allRows` flag which would cause it to use the `queryAll` api instead of the `query` api.

**Describe alternatives you've considered**
Currently, I resort to using Apex Dataloader or running an anonymous Apex script with `ALL ROWS` parameter. I've also built my own CLI plugin.

**Additional context**
This should be trivial to implement, I think, since the version of `jsForce` the CLI is using seems to simply require a `scanAll` flag to be set to true to use `queryAll` instead of `query`. Additonally, setting `autoFetch` to true seems to fetch all records as well by hitting the `nextRecordsUrl` in a loop till all rows are returned.

**Comment by peternhale** [comment]
@surajp Thank you for filing this feature request. Seems like this would be a good addition to the query command! We will have to prioritize this work, so not sure when we would be able to get to it. We do accept contributions, so if you would like to do that please see [CONTRIBUTING](https://github.com/forcedotcom/cli/blob/main/.github/CONTRIBUTING.md) guide.

**Comment by shetzel** [comment]
This is now in the latest CLIs: sfdx 7.208.10 / sf 1.85.8
