### ISSUE TITLE
Aura linting doesn't support glob wildcard when run by an npm script

### ISSUE THREAD

**Issue by pozil** [forcedotcom/cli#196]
### Summary

The following command works fine when entered in a terminal:
`sfdx force:lightning:lint **/aura`
However, the same command doesn't pick up files when run in the context of an npm script like `npm run lint:aura`. The `**` glob prefix isn't working in that context.

### Steps To Reproduce:

1. Clone the e-bikes sample app repo `git clone git@github.com:trailheadapps/ebikes-lwc.git`
1. Edit `package.json` and set the `lint:aura` script to `sfdx force:lightning:lint **/aura`
1. Install dependencies `npm install`
1. Run the Aura linting npm script `npm run lint:aura`

### Expected result

Script should run on 8 files:
```bash
'Search for "**/*.js" in folder "**/aura/"'
' -> Ignoring: **/node_modules/**,**/jsdoc/**,**/htdocs/**,**/invalidTest/**,**/purposelyInvalid/**,**/invalidTestData/**,**/validationTest/**,**/lintTest/**,**/target/**,**/parseError/**,**/*.junk.js,**/*_mock?.js'
Found 8 matching files.
```

### Actual result

No files are linted:
```bash
'Search for "**/*.js" in folder "**/aura/"'
' -> Ignoring: **/node_modules/**,**/jsdoc/**,**/htdocs/**,**/invalidTest/**,**/purposelyInvalid/**,**/invalidTestData/**,**/validationTest/**,**/lintTest/**,**/target/**,**/parseError/**,**/*.junk.js,**/*_mock?.js'
 ▸    Did not find matching files.
```

### Additional information

**SFDX CLI Version**:
sfdx-cli/7.27.0-714f62f9c1 darwin-x64 node-v10.15.3

**SFDX plugin Version**
```
salesforcedx 47.0.7 (pre-release)
├─ force-language-services 47.0.2
└─ salesforce-alm 47.0.7
```

**OS and version**: MacOS Mojave

**Comment by clairebianchi** [comment]
@trevor-bliss, can you take a look at this one

**Comment by trevor-bliss** [comment]
@ntotten @KrisGraySFDC

**Comment by KrisGraySFDC** [comment]
We have this bug already filed. 

@W-6746941 near the top of our backlog, we should be able to get this fixed soon.

**Comment by AdamTReineke** [comment]
@pozil Can you verify the expected result still repros? I don't see the expected result when running the sfdx command.

```
<redacted>:ebikes-lwc <redacted>$ sfdx force:lightning:lint **/aura
'Search for "**/*.js" in folder "**/aura"'
' -> Ignoring: **/node_modules/**,**/jsdoc/**,**/htdocs/**,**/invalidTest/**,**/purposelyInvalid/**,**/invalidTestData/**,**/validationTest/**,**/lintTest/**,**/target/**,**/parseError/**,**/*.junk.js,**/*_mock?.js'
 ▸    Did not find matching files.
```

**Comment by pozil** [comment]
@AdamTReineke I confirm that the issue is fixed with the current CLI version.
