### ISSUE TITLE
 `sfdx force:org:create` creates scratchorgs in russian, ignoring language and locale settings in prod org 

### ISSUE THREAD

**Issue by vytautasgermanavicius** [forcedotcom/cli#1962]
### Summary

`sfdx force:org:create` creates scratchorgs in russian, ignoring language and locale settings in prod org 

### Steps To Reproduce:

1.  sfdx force:org:create -f config/project-scratch-def.json -a dummy-scratch -v prod-org-en-US

### Expected result

Scratch org with user with locale en-US and language set to English

### Actual result

Scratch org with user with Lithuanian locale and language set to Russian.

**Comment by myklek** [comment]
Having same issue since spring update

**Comment by VytautasC** [comment]
The same problem for me.

**Comment by vika0** [comment]
Same problem for me since the spring update

**Comment by JurgitaGecaite** [comment]
Having the same issue

**Comment by peternhale** [comment]
@vytautasgermanavicius I sorry you seeing this issue. 

Could I get some additional information.
* results of `sfdx version --verbose`
* share the contents of the scratch org definition file
* where are you located?

**Comment by d-sydorenko** [comment]
Same problem for me. 

```
CLI Version:
        sfdx-cli/7.188.1

 Architecture:
        darwin-x64

 Node Version:
        node-v18.13.0

 Plugin Version:
        @oclif/plugin-autocomplete 1.4.5 (core)
        @oclif/plugin-commands 2.2.7 (core)
        @oclif/plugin-help 5.2.4 (core)
        @oclif/plugin-not-found 2.3.18 (core)
        @oclif/plugin-plugins 2.3.0 (core)
        @oclif/plugin-search 0.0.13 (core)
        @oclif/plugin-update 3.1.3 (core)
        @oclif/plugin-version 1.2.1 (core)
        @oclif/plugin-warn-if-update-available 2.0.26 (core)
        @oclif/plugin-which 2.2.14 (core)
        alias 2.2.1 (core)
        apex 1.5.1 (core)
        auth 2.4.2 (core)
        community 2.2.1 (core)
        config 1.5.1 (core)
        custom-metadata 2.1.1 (core)
        data 2.2.1 (core)
        generator 2.0.17 (core)
        info 2.4.2 (core)
        limits 2.3.3 (core)
        org 2.3.2 (core)
        packaging 1.14.3 (core)
        schema 2.3.1 (core)
        signups 1.4.0 (core)
        source 2.5.1 (core)
        telemetry 2.1.1 (core)
        templates 55.4.1 (core)
        trust 2.4.1 (core)
        user 2.3.2 (core)
        @salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
        @salesforce/sfdx-scanner 3.7.1 (user)
        salesforce-alm 54.8.5 (core)

 OS and Version:
        Darwin 22.3.0

 Shell:
        bash

 Root Path:
        /.local/share/sfdx/client/7.188.1-4a4bb9c
```

The scratch org creates in en when specified in a scratch org definition file.

But it does not work with `sfdx package:version:create` for 2gen managed package. Even with parameter --language set to en_US.

Originally I ran into this issue trying to create a new package version. I'm getting these errors:
`    (59) Application__c.Is_Applied__c: Cannot modify managed object: entity=CustomFieldDefinition, component=00N7a00000IbjeI, 
    state=MANAGED_RELEASED, Field: Datatype Previous Value: Checkbox New Value: Кнопка-флажок
    (60) Application__c.Rating__c: Cannot modify managed object: entity=CustomFieldDefinition, component=00N7a00000IbjeJ, 
    state=MANAGED_RELEASED, Field: Datatype Previous Value: Number New Value: Число
`

Language of my user in DevHub is En.
DevHub default language is En.

I assume this is the same issue, the packaging org is created with wrong language and that cause the version creation to fail.

**Comment by vytautasgermanavicius** [comment]
> * results of `sfdx version --verbose`

```
$ sfdx version --verbose
 CLI Version:
	sfdx-cli/7.185.0

 Architecture:
	linux-x64

 Node Version:
	node-v18.14.2

 Plugin Version:
	@oclif/plugin-autocomplete 1.3.10 (core)
	@oclif/plugin-commands 2.2.2 (core)
	@oclif/plugin-help 5.1.22 (core)
	@oclif/plugin-not-found 2.3.13 (core)
	@oclif/plugin-plugins 2.1.8 (core)
	@oclif/plugin-search 0.0.8 (core)
	@oclif/plugin-update 3.0.9 (core)
	@oclif/plugin-version 1.1.4 (core)
	@oclif/plugin-warn-if-update-available 2.0.19 (core)
	@oclif/plugin-which 2.2.6 (core)
	alias 2.1.18 (core)
	apex 1.4.2 (core)
	auth 2.2.8 (user)
	community 2.1.3 (core)
	config 1.4.23 (core)
	custom-metadata 2.0.11 (core)
	data 2.1.22 (core)
	generator 2.0.16 (core)
	info 2.3.3 (core)
	limits 2.2.3 (core)
	org 2.2.22 (core)
	packaging 1.12.3 (core)
	schema 2.2.2 (core)
	signups 1.2.12 (core)
	source 2.3.15 (core)
	telemetry 2.0.5 (core)
	templates 55.2.1 (core)
	trust 2.2.8 (core)
	user 2.1.25 (core)
	@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
	salesforce-alm 54.8.5 (core)

 OS and Version:
	Linux 5.19.0-32-generic

 Shell:
	bash

 Root Path:
	/usr/lib/node_modules/sfdx-cli
```
> * share the contents of the scratch org definition file

It's default file created with `sfdx force:project:create`
```
{
  "orgName": "vytautas company",
  "edition": "Developer",
  "features": ["EnableSetPasswordInApi"],
  "settings": {
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    }
  }
}
```
> * where are you located?

Lithuanian IP address

**Comment by peternhale** [comment]
@vytautasgermanavicius and @d-sydorenko thank your for the additional details.

**Comment by bdovh** [comment]
Same happens to me

**Comment by bdovh** [comment]
Production org country is Ukraine.

Summary
sfdx force:org:create creates scratchorgs in russian, ignoring language and locale settings in prod org

Steps To Reproduce:
sfdx force:org:create -f config/project-scratch-def.json -a dummy-scratch -v prod-org-en-US
Expected result
Scratch org with user with locale en-US and language set to English

Actual result
Scratch org with user with Ukrainian locale but language set to Russian.

**Comment by bdovh** [comment]
I guess as a workaround we can change the country of devhub to be US or UK

**Comment by peternhale** [comment]
@bdovh yes the workaround is to use the county field in the scratch org definition file.

**Comment by bdovh** [comment]
> We have determined that the issue you reported exists in code owned by another team that uses only the official support channels. To ensure that your issue is addressed, open an official [Salesforce customer support](https://help.salesforce.com/s/) ticket with a link to this issue. We encourage anyone experiencing this issue to do the same to increase the priority. We will keep this issue open for the community to collaborate on.

Yes, I have already opened a case Case #44161625 https://help.salesforce.com/s/case-view?caseId=500Hx00000CnvizIAB

**Comment by vytautasgermanavicius** [comment]
> @bdovh yes the workaround is to use the county field in the scratch org definition file.

I know, but problems is that default language is detected incorrectly. There are no (technical) reason to set Russian as default language: we are not Russians, we are not working with Russian projects.

**Comment by peternhale** [comment]
@vytautasgermanavicius I fully understand your frustration with this issue. The team responsible for this is working on a solution. I only mention the workaround as a temporary solution, not as a permanent one.

**Comment by vytautasgermanavicius** [comment]
Workaround: set  `"language": "en_US", ` in project-scratch-def.json 
```{
  "orgName": "vytautas company",
  "edition": "Developer",
 "language": "en_US",
  "features": ["EnableSetPasswordInApi"],
  "settings": {
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    }
  }
}
```

It's set only language, but not locale.

**Comment by d-sydorenko** [comment]
I received another workaround suggested by SF Support: set `"country": "US"` in project-scratch-def.json. Also changed the country in Company information of the DevHub to US. This worked and the package version was successfully created.

**Comment by vytautasgermanavicius** [comment]
There are 2 problems:  
1. Setting autodetecting Language or Country by IP address is bad practice.  Let say, I have CI/CD server in Finland, why would i like to get finish locale or country, when prog org is from US? Missing setting must be taken from *prod* org.

2. Lithuanian locale is binded with russian language. Seriously?

**Comment by bdovh** [comment]
@vytautasgermanavicius when you open a Salesforce support case, are you able to select Lithuanian time zone?
 I have opened one case regarding absense of any of Eastern European timezone and I got response that it is not a bug, since it was never an option. However, I can clearly remember, that there was earlier some option for Eastern European timezone, if not Ukrainian, I used to be able to select Finnish, Latvian, Estonian or Lithuanian timezone instead, but now neither of those options are available

**Comment by AyushGangwar07** [comment]
@bdovh @vytautasgermanavicius @vika0 @JurgitaGecaite 
Please find the Know issue link for the scratch org creation issue with the Russian language.
https://issues.salesforce.com/issue/a028c00000smIKf/scratch-orgs-created-in-russian-language-even-if-devhub-org-has-been-set-with-english-language

**Comment by bdovh** [comment]
Thanks @AyushGangwar07

**Comment by min-Ivan** [comment]
> I received another workaround suggested by SF Support: set `"country": "US"` in project-scratch-def.json. Also changed the country in Company information of the DevHub to US. This worked and the package version was successfully created.

Hi! Could you please share more detailed steps that were done to create a package version. I have the same problem. I've set Dev Hub Org Country to US, Language - English, and for the user I am authorised from CLI the same. But still have errors when try to create a package version. Thanks

Update: I've successfully used this workaround to create a package version. Set Country to US, Language to English in Dev Hub Org and User settings, 

added "definitionFile": "config/project-scratch-def.json" to sfdx-project.json
added "country": "US",
    "language": "en_US", to project-scratch-def.json

Thanks

**Comment by preddivari** [comment]
Closing this as the known issue is now in review - https://issues.salesforce.com/issue/a028c00000smIKf/scratch-orgs-created-in-russian-language-even-if-devhub-org-has-been-set-with-english-language
