### ISSUE TITLE
sfdx plugins:install package_name@[^|~]version does not work

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1966]
### Summary

This isn't a bug. I just would like to share something I observed while doing some experiments.

npm and yarn allow this notation when specifiying a version while installing a package: 

`npm install bla@^1.0.0`
`yarn add bla@^1.0.0`

while sfdx plugins:install does not.

Because of this problem, I can't use a npm's `package.json` to install my sfdx plugins. And because I can't use a `package.json`, I can't use Dependabot to keep my sfdx plugins up to date.  Everytime a new update to any of my plugins is released, Dependabot creates a PR to notify me about this update. Then, when merging dependabot's PR a new docker container is built so that I can use it in my CI/CD pipelines.

I have a package.json for global npm packages, such as sfdx, and a package.json for sfdx-plugins. They are both shown below:

````json
{
  "name": "global-dependencies",
  "version": "1.0.0",
  "description": "This package controls global npm dependencies",
  "devDependencies": {
    "typescript": "4.9.5",
    "@salesforce/cli": "1.65.0",
    "sfdx-cli": "7.188.1",
    "@vodafoneis/vlocity": "1.16.10",
    "puppeteer": "19.7.2",
    "mustache": "4.2.0",
    "xml-js": "^1.6.11"
  }
}

````

````json
{
  "name": "sfdx-plugins",
  "version": "1.0.0",
  "description": "This package controls sfdx plugins",
  "devDependencies": {
    "sfdx-git-delta": "^5.13.2"
  }
}

````

In my docker image, I use these package.json files as shown below:

````yml
WORKDIR /global-dependencies
RUN cat ./package.json | jq '.devDependencies | keys[] as $k | "\($k)@\(.[$k])"' | xargs -t npm install --global

WORKDIR /sfdx-plugins
RUN echo 'y' | $(cat ./package.json | jq '.devDependencies | keys[] as $k | "\($k)@\(.[$k])"' | xargs -t sfdx plugins:install)
````

Unfortunatelly, because `sfdx plugins:install` does not work like npm, my docker build fails while installing sfdx plugins as shown above. I can fix this issue in many different ways, but I was thinking why can't sfdx plugins install work like yarn if it uses yarn to install the package? Maybe the plugins:install plugin is changing the version argument ? I think it should not do any transformations to the version argument, and just hand it over to yarn as is.

### Steps To Reproduce:

1. run `sfdx plugins:install sfdx-git-delta@^5.13.2`
2. verify sfdx throws this error

![image](https://user-images.githubusercontent.com/55927613/221957667-fe17253f-e0ed-40ba-9ddf-8b4e8a62c68e.png)

3. run `sfdx plugins:install sfdx-git-delta@5.13.2`
4. verify that the package is installed without a problem
5. run `npm install sfdx-git-delta@^5.13.2`
6. verify that the package was installed without a problem
7. run `yarn add sfdx-git-delta@^5.13.2`
8. verify that the package was installed without a problem

### Expected result

sfdx plugins:install should work exactly as yarn|npm when specifying versions

### Actual result

sfdx plugins:install does not work like yarn|npm when specifying versions

### System Information

![image](https://user-images.githubusercontent.com/55927613/221957297-080f10a8-6356-4436-91de-a223f1a98c55.png)

**Comment by cristiand391** [comment]
Hey @AllanOricil 
This is a known bug, IIRC the hook that verifies a plugin signature fails to parse the semver range and throws that error.

call to verify hook in preinstall hook:
https://github.com/salesforcecli/sfdx-cli/blob/main/src/hooks/pluginsPreinstall.ts#L12
verify signature hook:
https://github.com/salesforcecli/plugin-trust/blob/main/src/hooks/verifyInstallSignature.ts

I think I tried to fix it a while ago and think it required to do some refactor to not break the current behavior.

**Comment by AllanOricil** [comment]
I kind of have a fix for this, but it is going to take some time becuse I decided to delete that custom npmParse class. Maybe tomorrow I will open a PR to show my changes.
