### ISSUE TITLE
Enable sfdx plugins:install to install plugins and hooks when initializing a project

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1967]
**Is your feature request related to a problem? Please describe.**
More or less: https://github.com/forcedotcom/cli/issues/1966

**What are you trying to do**

I would like to install sfdx plugins and hooks when initializing an `sfdx-project.json`

Why?

1. ease the instalation of sfdx plugins and hooks in an sfdx-project. It should work like dev dependencies in node projects.
2. reduce the amount of time spent while installing plugins. Currently we have to install one by one. This isn't really a big problem because projects usually use a few plugins.
3. properly version sfdx plugins and hooks required in a given state (commit sha).
4. get rid of the `unsignedPluginsAllowList` [feature](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_allowlist.htm). The cli could use the list of plugins found in the `sfdx-project.json`. If it is in the repo, you could assume that the plugin is safe to be installed.

**Describe the solution you'd like**

`sfdx plugins:install` must install all plugins and hooks listed in the `sfdx-project.json` when no arguments/flags are passed

![image](https://user-images.githubusercontent.com/55927613/222185414-6eac6d87-e09c-4a05-878b-eeb9c2d4ccb7.png)

https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

You will probably have to redesign the schema of the `plugins` object because it does not seem to accept package versions. I think it was created for another purpose.

**Describe alternatives you've considered**
Have to manually install each plugin and after the project has been initialized

**Additional context**
N/A

**Comment by AllanOricil** [comment]
This autimation could be triggered by the `postinstall` hook

**Comment by ImJohnMDaniel** [comment]
FWIW, I like this idea!

**Comment by amtrack** [comment]
@AllanOricil @ImJohnMDaniel I was searching for a way to install and use sfdx plugins via `package.json` (so the Node.js way) as well and have just recently documented my findings in this article: https://hutte.io/trails/dependency-management-for-sfdx-projects/.
Of course this might only be a temporary solution until Salesforce comes up with a better way.
Anyway I would love to hear your thoughts on this.
