### ISSUE TITLE
Org created in a different language, only during PackageVersion Creation

### ISSUE THREAD

**Issue by ikljaic-nubilum** [forcedotcom/cli#1968]
### Summary

In our CICD pipeline we have 2 steps.  In the first one we create a scratch org to run a few tests and here everything works fine as expected. In the second step we create a Package version out of it and a few days ago, without any changes, we started getting failed unit tests. After digging a bit we realized that the test that fail are the ones that somehow depend on the language of the org. Out of the sudden, the org in the 2nd step is created in German, and SF Namespace Exception messages became German, ... also the Profilenames are also in German.
We ofc patched up the Unit tests, but it would be good to have this patched up. I am sure that some people will run into it as well, where the patching will be much bigger than for us. 

Yeah, one more thing I forgot to say is, that I tried also to set explicitly the language to en_US

`sfdx package:version:create --json --skip-ancestor-check --package examplePackage --code-coverage --installation-key "XXX" --branch exampleBranch --tag exampleTag --definition-file config/project-scratch-def.json --wait 30 --language en_US `

The `project-scratch-def.json` also explicitly says `"language": "en_US",`

### Expected result

A new PackageVersion created after executing unit tests in a en_US definded org

### Actual result

Package Version fail, because the org was a german one

### System Information

$ sfdx version --verbose
 CLI Version:
        sfdx-cli/7.186.2

 Architecture:
        win32-x64

 Node Version:
        node-v19.2.0

 Plugin Version:
        @oclif/plugin-autocomplete 1.4.2 (core)
        @oclif/plugin-commands 2.2.4 (core)
        @oclif/plugin-help 5.2.1 (core)
        @oclif/plugin-not-found 2.3.17 (core)
        @oclif/plugin-plugins 2.2.4 (core)
        @oclif/plugin-search 0.0.11 (core)
        @oclif/plugin-update 3.1.0 (core)
        @oclif/plugin-version 1.2.1 (core)
        @oclif/plugin-warn-if-update-available 2.0.23 (core)
        @oclif/plugin-which 2.2.9 (core)
        alias 2.1.19 (core)
        apex 1.4.3 (core)
        auth 2.3.12 (core)
        community 2.1.5 (core)
        config 1.4.23 (core)
        custom-metadata 2.0.16 (core)
        data 2.1.22 (core)
        generator 2.0.17 (core)
        info 2.3.5 (core)
        limits 2.2.3 (core)
        org 2.2.24 (core)
        packaging 1.12.4 (core)
        schema 2.2.3 (core)
        signups 1.2.12 (core)
        source 2.3.16 (core)
        telemetry 2.0.7 (core)
        templates 55.2.3 (core)
        trust 2.3.0 (core)
        user 2.2.1 (core)
        @salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
        @salesforce/sfdx-scanner 3.9.0 (user)
        salesforce-alm 54.8.5 (core)
        sfdx-codescan-plugin 1.0.8 (user)

 OS and Version:
        Windows_NT 10.0.19045

 Shell:
        C:\Program Files\Git\usr\bin\bash.exe

**Comment by con242** [comment]
Any Update here? facing same issue

**Comment by ikljaic-nubilum** [comment]
any updates? my CICD pipeline is stuck because of this.

**Comment by petter-eikeland** [comment]
@ikljaic-nubilum The newest sfdx Release Candidate fixed this issue (#1921) for me. Hopefully it resolves your issue as well
