### ISSUE TITLE
B2B Commerce template not available in scratch orgs

### ISSUE THREAD

**Issue by IvanBoban** [forcedotcom/cli#1969]
### Summary

B2B Commerce template not available in scratch orgs.

### Steps To Reproduce:
1. Create a new scratch org using sf org create scratch --definition-file config/project-scratch-def.json -y 3 -d    and the following config.json :
```{
  "orgName": "myScratchOrg",
  "edition": "Enterprise",
  "country": "en",
  "language": "en_US",
  "features": [
    "Communities",
    "B2BCommerce",
    "OrderManagement",
    "EnableSetPasswordInApi"
  ],
  "settings": {
    "languageSettings": {
      "enableTranslationWorkbench": true,
      "enableEndUserLanguages": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "experienceBundleSettings": {
      "enableExperienceBundleMetadata": true
    },
    "communitiesSettings": {
      "enableNetworksEnabled": true
    },
    "orderManagementSettings": {
      "enableOrderManagement": true
    },
    "orderSettings": {
      "enableOrders": true,
      "enableEnhancedCommerceOrders": true,
      "enableOptionalPricebook": true
    },
    "commerceSettings": {
      "commerceEnabled": true
    }
  }
}
``` 
2. Run `sf community template list`

### Expected result

B2B Commerce listed as a community template.

### Actual result

B2B Commerce not listed as a community template. Only B2B Commerce (LWR) listed.

### System Information

- ZSH

"cliVersion": "@salesforce/cli/1.65.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.13.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.4.5 (core)",
    "@oclif/plugin-commands 2.2.7 (core)",
    "@oclif/plugin-help 5.2.4 (core)",
    "@oclif/plugin-not-found 2.3.18 (core)",
    "@oclif/plugin-plugins 2.3.0 (core)",
    "@oclif/plugin-search 0.0.13 (core)",
    "@oclif/plugin-update 3.1.3 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.26 (core)",
    "@oclif/plugin-which 2.2.14 (core)",
    "community 2.2.1 (core)",
    "custom-metadata 2.1.1 (core)",
    "data 2.2.1 (core)",
    "deploy-retrieve 1.8.0 (core)",
    "env 2.0.2 (core)",
    "functions 1.17.4 (core)",
    "generate 1.1.2 (core)",
    "info 2.4.2 (core)",
    "limits 2.3.3 (core)",
    "login 1.1.18 (core)",
    "org 2.3.2 (core)",
    "schema 2.3.1 (core)",
    "settings 1.2.1 (core)",
    "signups 1.4.0 (core)",
    "sobject 0.1.2 (core)",
    "telemetry 2.1.1 (core)",
    "trust 2.4.1 (core)",
    "user 2.3.2 (core)"
  ],
  "osVersion": "Darwin 21.5.0",
  "shell": "zsh",

_Feel free to attach a screenshot_.

**Comment by peternhale** [comment]
@IvanBoban thank you for filing this issue. Is this something the previously worked for you and is not meeting expectations?

**Comment by IvanBoban** [comment]
@peternhale Hello, yes previously after creating a scratch org and running : `sf community template list` you'd get the following list of templates:

```
 Template Name                 Publisher  
 ───────────────────────────── ────────── 
 Build Your Own                Salesforce 
 Help Center                   Salesforce 
 B2B Commerce                  Salesforce 
 Microsite (LWR)               Salesforce 
 Customer Account Portal       Salesforce 
 Aloha                         Salesforce 
 Customer Service              Salesforce 
 Build Your Own (LWR)          Salesforce 
 Salesforce Tabs + Visualforce Salesforce 
```

Currently if you run the same command the list of available templates is like this:

```
 Template Name                 Publisher  
 ───────────────────────────── ────────── 
 Build Your Own                Salesforce 
 Help Center                   Salesforce 
 Microsite (LWR)               Salesforce 
 B2B Commerce (LWR)            Salesforce 
 Customer Account Portal       Salesforce 
 Aloha                         Salesforce 
 Customer Service              Salesforce 
 Build Your Own (LWR)          Salesforce 
 Salesforce Tabs + Visualforce Salesforce 
```
As you see the difference is in the fact that the previously ran command listed  `B2B Commerce` but the new lists `B2B Commerce (LWR)` which isn't the same template. This is an issue for my team because our code wasn't built to run inside LWR, but inside the old  template.

**Comment by petter-eikeland** [comment]
Yeah, we experience the same. This changed overnight with Spring '23

**Comment by peternhale** [comment]
@IvanBoban sorry for the delay.

The feature B2BCommerce as you have discovered now enables template B2B Commerce (LWR). To have the old `B2B Commerce` template added to your scratch org add the new feature `B2BAuraTemplateEnabled` to the scratch def file.
```
"features": [
    "Communities",
    "B2BCommerce",
    "B2BAuraTemplateEnabled",
    "OrderManagement",
    "EnableSetPasswordInApi"
  ],
```
yields
```
sf community template list -o gh1969
=== Site list template result

 Template Name                 Publisher  
 ───────────────────────────── ────────── 
 Build Your Own                Salesforce 
 Help Center                   Salesforce 
 B2B Commerce                  Salesforce 
 Microsite (LWR)               Salesforce 
 B2B Commerce (LWR)            Salesforce 
 Customer Account Portal       Salesforce 
 Aloha                         Salesforce 
 Customer Service              Salesforce 
 Build Your Own (LWR)          Salesforce 
 Salesforce Tabs + Visualforce Salesforce 

Total 10
```

**Comment by IvanBoban** [comment]
@peternhale Thank you for the response, I just tested in on our local setup and I can confirm that the old Aura template is visible. Thank you for your help.

As another point of note this isn't listed in the [official documentation ](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file_config_values.htm) . I'd advise this be added to the official documentation.

**Comment by peternhale** [comment]
We are aware of the documentation error, but thank you for raising that as well.
