### ISSUE TITLE
Package Install with AdminsOnly option is changing all the profiles

### ISSUE THREAD

**Issue by ar-srinivas** [forcedotcom/cli#1973]
### Summary

When we run "`sfdx force:package:install -p <*****> -b 0 -u <****> --apiversion=55.0 -r -s AdminsOnly --json`" it should install and change the profile of the admin but it is changing the non admin profiles. When we do the same from a browser and selecting AdminsOnly option it is changing only the admin profile.

### Steps To Reproduce:

Run  `sfdx force:package:install -p <*****> -b 0 -u <****> --apiversion=55.0 -r -s AdminsOnly --json` and see the profiles modified. It changes are non admin and admin profiles

### Expected result

It should modify only the admin profiles

### Actual result

Updating admin and non admin profiles

### System Information
We have seen this behaviour starting from 7.180 to the latest 7.190
{
  "cliVersion": "sfdx-cli/7.190.2",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.14.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.2 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.5 (core)",
    "@oclif/plugin-not-found 2.3.20 (core)",
    "@oclif/plugin-plugins 2.3.2 (core)",
    "@oclif/plugin-search 0.0.13 (core)",
    "@oclif/plugin-update 3.1.5 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.28 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "alias 2.2.2 (core)",
    "apex 2.2.0 (core)",
    "auth 2.7.1 (core)",
    "community 2.2.3 (core)",
    "config 1.5.1 (core)",
    "custom-metadata 2.1.3 (core)",
    "data 2.3.1 (core)",
    "info 2.4.4 (core)",
    "limits 2.3.5 (core)",
    "org 2.4.2 (core)",
    "packaging 1.15.0 (core)",
    "schema 2.3.1 (core)",
    "signups 1.4.3 (core)",
    "source 2.5.4 (core)",
    "telemetry 2.1.1 (core)",
    "templates 55.4.1 (core)",
    "trust 2.4.2 (core)",
    "user 2.3.2 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@salesforce/sfdx-scanner 3.10.0 (user)",
    "sfdx-codescan-plugin 1.0.8 (user)"
  ],
  "osVersion": "Darwin 22.3.0",
  "shell": "zsh",
  "rootPath": "/Users/srinivas.s/.local/share/sfdx/client/7.190.2-cd6cf69"
}

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here
### Additional information

_Feel free to attach a screenshot_.

**Comment by shetzel** [comment]
@ar-srinivas - can you please run the same command but without `-s AdminsOnly`.  AdminsOnly is the default and I'm curious if there is a difference in behavior.

**Comment by ar-srinivas** [comment]
Tried and it does the same

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shetzel** [comment]
Ok good to know.  One last thing to try is the legacy install command.  Can you run `sfdx plugins:install salesforce-alm`, then run `sfdx force:package:legacy:install -p <*****> -b 0 -u <****> --apiversion=55.0 -r -s AdminsOnly --json` and see if that behaves correctly?  Then you can uninstall that plugin with `sfdx plugins:uninstall salesforce-alm`.  Thanks!

**Comment by ar-srinivas** [comment]
@shetzel I tried the steps you suggested to test it with legacy commands and the result is same.

**Comment by ar-srinivas** [comment]
@shetzel Please let us know if you have any updates on this issue.

**Comment by shetzel** [comment]
I just checked the work item and it's been closed.  The packaging team would like issues to come from support.  Apologies, but can you please open a support ticket and the packaging team will service the request that way?
