### ISSUE TITLE
force:org:display --verbose Access Token & Sfdx Auth Url are cut off and unusable

### ISSUE THREAD

**Issue by dpuza-formativ** [forcedotcom/cli#1974]
Version 7.132.0 works correctly.  The full value is displayed and is not cut off.

Version 7.187.1 causes a problem for us because instead of the full value being displayed it cuts it off and just shows a "..." at the end.

EDIT: it's also cut off the same way in the "sf" CLI.

Workaround: adding --json helped and the full value is available that way

**Comment by peternhale** [comment]
@dpuza-formativ for the text output we try to limit line wrapping based on terminal width when the command is run. You could try expanding the width your window. Once it is wide enough the column data for the attributes will no longer be trucated.

**Comment by dpuza-formativ** [comment]
@peternhale We confirmed that expanding the window when the command is run increases the number of characters displayed.  Still gets cut off even when maximized on some displays.  It's not ideal.  The previous behavior is preferred.

**Comment by peternhale** [comment]
@dpuza-formativ I'll mark this as a feature request and have product management review the request.

**Comment by shetzel** [comment]
fixed and in production
