### ISSUE TITLE
Announcement:  Node.js 14 and 16 End-of-Life Dates

### ISSUE THREAD

**Issue by jshackell-sfdc** [forcedotcom/cli#1985]
If you install Salesforce CLI using `npm`, and use Node.js 14 or 16, be aware of these end-of-life announcements.

**NOTE**: If you install Salesforce CLI using the installers (`.pkg`, `.exe`, or TAR files), these announcements don't apply to you. Salesforce CLI installers and TAR files bundle the [LTS version of Node.js](https://nodejs.org/en/about/releases/), so keeping Salesforce CLI updated to its latest release also keeps you current with Node.js. 

# Node.js 14 End-of-Life

The end-of-life date for Node.js 14 is [April 30, 2023](https://nodejs.org/en/about/releases/).

We’ll start modifying Salesforce CLI plugins and libraries to require Node.js 16 or higher in early May 2023.  We’ll be taking advantage of new syntax features that don’t work on Node.js 14.

Node.js recommends that if you’re using Node.js 14, move to Node.js 18 and _not_ Node.js 16, because the latter has such a short remaining lifespan.

# Node.js 16 End-of-Life (Brought Forward)

The end-of-life date for Node.js 16 is [September 11, 2023](https://nodejs.org/en/about/releases/). This date is earlier than previously published. 

Node.js’s [blog](https://nodejs.org/en/blog/announcements/nodejs16-eol/) explains why they chose this earlier end-of-life date. 

When Node.js drops support for Node.js 16, Salesforce CLI will too.

# Salesforce Recommendations

Generally, we recommend using Node.js 18. 

If you're unable to change your Node.js version to a supported version, we recommend that you install Salesforce CLI from a TAR file or installer. Your computer can then have the older Node.js version installed, but Salesforce CLI will bring its own supported Node.js version and not use the one on your computer. 

If you're using the `sfdx-lwc-jest` [plugin](https://github.com/salesforce/sfdx-lwc-jest) package, please see [this issue](https://github.com/salesforce/sfdx-lwc-jest/issues/301) around the impact of node versions, a [known bug](https://github.com/facebook/jest/issues/11956) in its `jest` dependency, and various tradeoffs/workarounds.

**Comment by AllanOricil** [comment]
@jshackell-sfdc 

This [issue](https://github.com/salesforce/sfdx-lwc-jest/issues/301) affects this decision depending on the amount of tests developers have in their projects. You have to upgrade Jest to v29 if you want to support node > 16.10

**Comment by jshackell-sfdc** [comment]
@mshanemc  , can you respond to Allan's comment above? Thx.

**Comment by AllanOricil** [comment]
@jshackell-sfdc ur team could use start using Github's Discussions feature to notify developers about important announcements such as this one

![Screenshot_20230314-125759_GitHub.jpg](https://user-images.githubusercontent.com/55927613/225063330-1f352602-ee96-4185-8a56-d6126b90cc26.jpg)

**Comment by jshackell-sfdc** [comment]
@AllanOricil , thanks for letting us know about that issue.   We updated our announcement accordingly.

**Comment by AllanOricil** [comment]
14 and 16 are forever part of my life. I will miss them 😭
