### ISSUE TITLE
sfdx force:org:list/org:list not showing all authenticated orgs

### ISSUE THREAD

**Issue by stian-schikora-stb** [forcedotcom/cli#1988]
### Summary

A developer on our team is having issues with the CLI not tracking the authenticated orgs. Not even the DevHub is displayed in the force:org:list.

### Steps To Reproduce:

We can only reproduce this issue for the developer experiencing the problem and have not managed to reproduce this on any other machine

1.  Authenticate an org using the ``sfdx auth:web:login`` command
1.  Authentication is successfull, auth file stored in the dataDir
1. Run ``sfdx force:org:list`` to see authenticated orgs

### Expected result
CLI outputting the connected orgs.

### Actual result
Actual output from ``sfdx force:org:list`` and ``sfdx org:list``

=========================================================================== 
|   ALIAS USERNAME                      ORG ID             CONNECTED STATUS 
| ─ ───── ───────────────────────────── ────────────────── ──────────────── 
|   MifXXX test-jvbypXXXXX@example.com 00D1x000XXXXXXX Connected
No active scratch orgs found. Specify --all to see all scratch orgs.

### System Information

- Running commands on Powershell 5

Output from ``sfdx doctor``
````JSON
{
  "versionDetail": {
    "cliVersion": "sfdx-cli/7.190.2",
    "architecture": "win32-x64",
    "nodeVersion": "node-v18.13.0",
    "pluginVersions": [
      "@dxatscale/sfpowerscripts 20.26.2 (user)",
      "@oclif/plugin-autocomplete 2.1.2 (core)",
      "@oclif/plugin-commands 2.2.10 (core)",
      "@oclif/plugin-help 5.2.5 (core)",
      "@oclif/plugin-not-found 2.3.20 (core)",
      "@oclif/plugin-plugins 2.3.2 (core)",
      "@oclif/plugin-search 0.0.13 (core)",
      "@oclif/plugin-update 3.1.5 (core)",
      "@oclif/plugin-version 1.2.1 (core)",
      "@oclif/plugin-warn-if-update-available 2.0.28 (core)",
      "@oclif/plugin-which 2.2.16 (core)",
      "alias 2.2.2 (core)",
      "apex 2.2.0 (core)",
      "auth 2.7.1 (core)",
      "community 2.2.3 (core)",
      "config 1.5.1 (core)",
      "custom-metadata 2.1.3 (core)",
      "data 2.3.1 (core)",
      "info 2.4.4 (core)",
      "limits 2.3.5 (core)",
      "org 2.4.2 (core)",
      "packaging 1.15.0 (core)",
      "schema 2.3.1 (core)",
      "signups 1.4.3 (core)",
      "source 2.5.4 (core)",
      "telemetry 2.1.1 (core)",
      "templates 55.4.1 (core)",
      "trust 2.4.2 (core)",
      "user 2.3.2 (core)",
      "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
      "sfdmu 4.26.8 (user)",
      "sfpowerkit 6.1.0 (user)"
    ],
    "osVersion": "Windows_NT 10.0.19044",
    "shell": "cmd.exe",
    "rootPath": "C:\\Users\\XXX\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli"
  },
  "sfdxEnvVars": [
    [
      "SFDX_AUTOUPDATE_DISABLE",
      "true"
    ],
    [
      "SFDX_DISABLE_AUTOUPDATE",
      "true"
    ],
    [
      "SFDX_UPDATE_INSTRUCTIONS",
      "Use \"npm update --global sfdx-cli\" to update npm-based installations."
    ]
  ],
  "sfEnvVars": [],
  "cliConfig": {
    "_base": "@oclif/core@2.3.0",
    "debug": 0,
    "topicSeparator": " ",
    "warned": false,
    "commandPermutations": {
      "validPermutations": {}
    },
    "topicPermutations": {
      "validPermutations": {}
    },
    "_commands": {},
    "_topics": {},
    "root": "C:\\Users\\XXX\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli",
    "name": "sfdx-cli",
    "version": "7.190.2",
    "channel": "stable",
    "valid": true,
    "arch": "x64",
    "platform": "win32",
    "windows": true,
    "bin": "sfdx",
    "dirname": "sfdx",
    "flexibleTaxonomy": true,
    "userAgent": "sfdx-cli/7.190.2 win32-x64 node-v18.13.0",
    "shell": "cmd.exe",
    "home": "H:\\",
    "cacheDir": "C:\\Users\\XXX\\AppData\\Local\\sfdx",
    "configDir": "C:\\Users\\XXX\\AppData\\Local\\sfdx",
    "dataDir": "C:\\Users\\XXX\\AppData\\Local\\sfdx",
    "errlog": "C:\\Users\\XXX\\AppData\\Local\\sfdx\\error.log",
    "nodeEngine": ">=14.0.0"
  },
  "pluginSpecificData": {
    "@salesforce/plugin-source": [
      {
        "sourceApiVersion": "56.0",
        "targetDevHubApiVersion": "57.0",
        "targetOrgApiVersion": "57.0"
      }
    ]
  },
  "diagnosticResults": [
    {
      "testName": "salesforcedx plugin not installed",
      "status": "pass"
    },
    {
      "testName": "no linked plugins",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] sourceApiVersion matches apiVersion",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] default target DevHub max apiVersion matches default target org max apiVersion",
      "status": "pass"
    },
    {
      "testName": "[@salesforce/plugin-source] sourceApiVersion matches default target org max apiVersion",
      "status": "warn"
    },
    {
      "testName": "using latest or latest-rc CLI version",
      "status": "pass"
    }
  ],
  "suggestions": [
    "Check https://github.com/forcedotcom/cli/issues for CLI issues posted by the community.",
    "Check http://status.salesforce.com for general Salesforce availability and performance.",
    "The sourceApiVersion in sfdx-project.json doesn't match the max apiVersion of the default target org. As a result, you're not using the latest features available in API version 57.0. The version mismatch isn't a problem, as long as it's the behavior you actually want."
  ],
  "logFilePaths": []
}
````

**Comment by peternhale** [comment]
@stian-schikora-stb could you have the affected user run `sfdx org:list --all` to see if new auth'd org appears in the list.

**Comment by stian-schikora-stb** [comment]
@peternhale we tried with the --all tag but still receive the same response. Both DevHub and other sandboxes are not present in the list.

**Comment by peternhale** [comment]
@stian-schikora-stb Could you share the filenames found in $HOME/.sfdx and $HOME/.sf? If the filenames are sensitive, please redact the name, but leave the extensions.

Another option would be to start from scratch by removing $HOME/.sfdx and $HOME/.sf and then authorize orgs again.

**Comment by stian-schikora-stb** [comment]
@peternhale :
.sf folder
![sf-dump](https://user-images.githubusercontent.com/122268538/224009254-31057fa3-4787-4a5d-a0a9-3d1009bac150.png)

.sfdx
![sfdx](https://user-images.githubusercontent.com/122268538/224009793-cfc9c0b3-7ebc-42db-b650-d69d30734f62.png)

We have tried deleting all the auth files both manually and bu using ``sfdx auth:logout -a`` and then reauthenticating but with no luck 👎

**Comment by shetzel** [comment]
@stian-schikora-stb - not sure if this is still a problem for your developer, but the doctor output above reports a `cliConfig.home` value of `H:\\`.  That is probably causing the problem.  It should be `C:\\Users\\XXX` since that is probably where the auth files are being written.  To fix you can have them set the `HOME` environment variable to `C:\\Users\\XXX`.  Also, they might have the `HOMEDRIVE` and `HOMEPATH` environment variables set which could cause this.

Please reopen if they continue to have problems.
