### ISSUE TITLE
@salesforce/sfdx-scanner > ts-node@10.9.1" has unmet peer dependency "@types/node@*

### ISSUE THREAD

**Issue by dschach** [forcedotcom/cli#1992]
### Summary

When I update sfdx (`sfdx update`) I get this error. 
```
warning "@salesforce/sfdx-scanner > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
```

This happened today, even when I ran `sfdx update`:
```
% sfdx update
sfdx-cli: Updating sf... done
warning "@salesforce/sfdx-scanner > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
sfdx-cli: Updating plugins... ⣷ [3/4] Linking dependencies...
# Release notes for 'sfdx':

## 7.191.1 (March 9, 2023) [stable]
etc...
```

Note: I submitted this on sfdx-scanner and they told me to post it here. https://github.com/forcedotcom/sfdx-scanner/issues/1000

### Steps To Reproduce:

Run `sfdx update` and see the error. It also happens on `sfdx plugins:update`

### Expected result

Absence of this error

### Actual result

Error as above.

### System Information
**Desktop (please complete the following information):**
 - OS: OSX
 - Scanner Version 3.10.0

**Additional context**
```
@salesforce/sfdx-scanner 3.10.0
bbdoc 4.1.0
isvte-sfdx-plugin 1.1.16
```
```
@oclif/plugin-autocomplete 2.1.2 (core)
@oclif/plugin-commands 2.2.10 (core)
@oclif/plugin-help 5.2.5 (core)
@oclif/plugin-not-found 2.3.20 (core)
@oclif/plugin-plugins 2.3.2 (core)
@oclif/plugin-search 0.0.13 (core)
@oclif/plugin-update 3.1.5 (core)
@oclif/plugin-version 1.2.1 (core)
@oclif/plugin-warn-if-update-available 2.0.28 (core)
@oclif/plugin-which 2.2.16 (core)
@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
@salesforce/sfdx-scanner 3.10.0
alias 2.2.2 (core)
apex 2.2.0 (core)
auth 2.7.1 (core)
bbdoc 4.1.0
community 2.2.3 (core)
config 1.5.1 (core)
custom-metadata 2.1.3 (core)
data 2.3.1 (core)
info 2.4.4 (core)
isvte-sfdx-plugin 1.1.16
limits 2.3.5 (core)
org 2.4.2 (core)
packaging 1.15.0 (core)
schema 2.3.1 (core)
sfdx-cli 7.190.2 (core)
signups 1.4.3 (core)
source 2.5.4 (core)
telemetry 2.1.1 (core)
templates 55.4.1 (core)
trust 2.4.2 (core)
user 2.3.2 (core)
```

"Workaround": Nope. No idea where it's coming from.

"Urgency": Annoying, but NBD.

**Comment by AllanOricil** [comment]
I believe this warning happens because the scanner plugin declared @types for node 17, it was probably not compatible with the ts

**Comment by AllanOricil** [comment]
Maybe the issue can go away if someone adds @types/node as a dependency in this package https://github.com/salesforcecli/sfdx-cli/blob/main/package.json

**Comment by iowillhoit** [comment]
Hey @dschach, could you please try running `sfdx update` again? I am not seeing this locally. FWIW, This is something that we see occasionally. We run dependabot to keep deps up to date and also dedup dependecies during our build process, but sometimes versions can be slightly out of sync. It usually does not cause issues.

**Comment by dschach** [comment]
@iowillhoit Looks like it's resolved. Thanks for looking into it!

**Comment by AllanOricil** [comment]
🤢
