### ISSUE TITLE
`sfdx data:create:record --sobject Attachment --values "Body='<my-large-body>'" `fails with a large body

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/cli#1993]
**Is your feature request related to a problem? Please describe.**
To create an attachment with the `sfdx data:record:create` command, the file body (base64 encoded) needs to be passed as a parameter in the `--values "Body='<my-large-body>'"` parameter. Unfortunately, shell commands are limited in length (eg 1Mb on Macos) which limits the size of attachments which can be created by `sfdx` CLI.

**What are you trying to do**
I am trying to create a Salesforce Attachment object by command line with `sfdx data:record:create` command

**Describe the solution you'd like**
It would be nice to have an option to pass any large parameters as filenames, which the command would read and base64-encode before passing the data in to the Salesforce REST API to create the Attachment.
For example, we could imagine :
```
sfdx data:record:create \
  --sobject      Attachment \
  --values       "ParentId='xxxxxx' ContentType='pdf' Name='My PDF File'" \
  --valuesbyfile "Body='./myfile.pdf'"
```

**Describe alternatives you've considered**
The only alternative I have imagined is to code this myself, to load the file body contents directly into the REST API request sent to Salesforce, without passing it through the CLI as a parameter.

**Additional context**
This could also apply to creating ContentVersion objects.

**Comment by RupertBarrow** [comment]
This is what I wrote : 

```
const fs = require("fs-extra")
const axios = require("axios")

const attach = (org, parentId, filename, type="pdf", debug) => {
  const url = org.instanceUrl + "/services/data/v56.0/sobjects/Attachment"
  const file = fs.readFileSync(filename)
  const body = new Buffer.from(file).toString("base64")

  let request = axios.create({
    headers: {
      "Authorization": `Bearer ${org.accessToken}`,
      //"Content-Encoding": "gzip",
    },
  })
  
  return request
    .post(url, {
      ParentId: parentId,
      Name: filename,
      ContentType: type,
      Body: body,
    })
    .then(response => {
      if (debug) console.log("### POST RESPONSE", response)
      return response.data
    })
    .catch(error => {
      console.error("### POST ERROR", error)
      throw error
    })
}

module.exports = { attach }
```
and
```
const caseid = "5001i000016NXIRAA4"
const filename = "./docs/Ticket.pdf"
const att = await attach(org, caseid, filename, "pdf")

// output is : { id: '00P1i00000eQKE7EAO', success: true, errors: [] }
```

It would be better to have this work natively.

**Comment by AllanOricil** [comment]
There could actually exist a new namespace command called `file` or `doc` for uploading/downloading/deleting all types of files Salesforce has, like contentDocument and attachments

`sfdx file:upload|download|delete`


This command must work with streams if the API supports it... we don't want to load an entire file in memory just to start uploading it...
This command should work with multiple files

**Comment by mshanemc** [comment]
I did something like this, long ago, with the Content* objects:

https://github.com/mshanemc/shane-sfdx-plugins/blob/master/src/commands/shane/data/file/upload.ts.

I agree it's a missing feature.

**Comment by mshanemc** [comment]
For "load record where the fields come from a file" have you considered using the tree command (make a json of just one record, and your json could include the blob for that field) ?

Not sure where the limits are there, but it sees *almost* like one of the things you've asked for.
