### ISSUE TITLE
sf data query --bulk throws Fatal Error Javascript Heap out of memory

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#1995]
**Is your feature request related to a problem? Please describe.**

Bulk query stores all records in memory, instead of writing them to disk

![image](https://user-images.githubusercontent.com/55927613/224577680-d947aa88-e15b-441f-9f85-22482fa73447.png)
src: https://github.com/jsforce/jsforce/blob/95932f288a59a0b68ff9fe8cc1a94523a4d0fb85/src/api/bulk.ts#L1077-L1099

![image](https://user-images.githubusercontent.com/55927613/224576107-cbd1be5a-f5e2-4f6d-b57e-08c7169d95bc.png)
src: https://github.com/jsforce/jsforce/blob/95932f288a59a0b68ff9fe8cc1a94523a4d0fb85/src/api/bulk.ts#L1244-L1264

this could throw an exception like `Process out of Memory Exception` if someone tries to export a few million records, because all records are stored in memory inside of a record[] array. For instance,

````shell
sf data query --query "SELECT Id FROM Contact" --bulk
```` 

![image](https://user-images.githubusercontent.com/55927613/224576125-0bcb5b4a-fd73-4348-9827-7c27f8765cb9.png)
src: https://github.com/salesforcecli/plugin-data/blob/b56e778f6c9ef8affbc0719cafb629b07d19ce2c/src/commands/data/query.ts#L135-L153 

This type of exception can't be captured by a try/catch. The node runtime would exit 1 straight away.

This issue does not happen when using jsforce bulk v1 implementation because it was developed with streams in mind.

![image](https://user-images.githubusercontent.com/55927613/224577609-44aa0c3c-5eaf-428a-b744-51a741fb669a.png)
src: https://github.com/jsforce/jsforce/blob/95932f288a59a0b68ff9fe8cc1a94523a4d0fb85/src/api/bulk.ts#L959-L983

**What are you trying to do**
Export a few million records using sfdx force:data:query --bulk

**Describe the solution you'd like**

1 . jsforce must accept a write stream so that memory could be released after its data is written to disk. Additionally, memory can be released when `this.records[]` reaches N kbs of data.
2. sfdx should create a write stream when the `-b` flag is true.

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by AllanOricil** [comment]
@mshanemc @RodEsp 
I think you could take a look at this since you are maintaining jsforce 2.0

**Comment by RodEsp** [comment]
Heya @AllanOricil, I'm not involved with JSForce anymore but I'm sure Shane can take a look.

**Comment by AllanOricil** [comment]
Experiment with 103k Product2 records

![image](https://user-images.githubusercontent.com/55927613/225485009-7eb6f972-84a6-4dad-8f83-0792ad41c82e.png)

![image](https://user-images.githubusercontent.com/55927613/225485024-55329981-dbc2-4aef-b1e1-b7c916c38abe.png)

This is the result when using the default heap size
![image](https://user-images.githubusercontent.com/55927613/225484931-20f230f4-7845-4dc8-97bd-e3c6f00ccb93.png)


This is the result after configuring the heap size to 128Mb
![image](https://user-images.githubusercontent.com/55927613/225486577-1a332857-cc82-4fc9-86d0-3b1320480f7d.png)

![image](https://user-images.githubusercontent.com/55927613/225486273-ae709d2f-ab11-4947-8b52-518ab3441775.png)

**Comment by iowillhoit** [comment]
Thanks for this also @AllanOricil, I'll add this to a JSForce category in our back log

**Comment by AllanOricil** [comment]
@iowillhoit

I still can't understand why this stupid bulk api v2 doesn't break my job into 2 batches when I'm creating a job with `'Sforce-Enable-PKChunking': 'chunkSize=100000',`

![image](https://user-images.githubusercontent.com/55927613/226781298-525d453a-5461-4644-8779-06341f87d5bd.png)

When querying the job information, the output says the job processed 103344 records instead of 100k records
![image](https://user-images.githubusercontent.com/55927613/226781425-2419c194-a4ea-4f18-ab1f-bd7c4085e08b.png)

the `locator` header is `undefined` even after setting `maxRecords` query param to `10k` 
![image](https://user-images.githubusercontent.com/55927613/226781633-1356979e-2596-4c65-be80-3997e302d009.png)

**Comment by AllanOricil** [comment]
I've just tried creating a job using 'Sforce-Enable-PKChunking': 'TRUE', which set the defualt chunk size to 100k according to this [doc](https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/async_api_headers_enable_pk_chunking.htm), but it did not work as well

![image](https://user-images.githubusercontent.com/55927613/226782992-39e04a2a-5d5c-47a8-9988-464090b06c96.png)

**Comment by AllanOricil** [comment]
`Product2` is in the list of support objects, so my job request should have been broken into 2 batches
![image](https://user-images.githubusercontent.com/55927613/226783534-f14fda98-b9aa-480d-9a7b-cfb98d2d377c.png)

**Comment by AllanOricil** [comment]
I finally made it work. I will try to open a PR in the jsforce repo and if my changes are approved I can then open a PR in the data plugin repo.

**Comment by AllanOricil** [comment]
@iowillhoit I managed to fix jsforce creating a async iterator. I will soon open a PR to share my code, but here is a preview

https://user-images.githubusercontent.com/55927613/227083974-a2f6730a-b2e6-4d01-a121-865db43473a7.mov

**Comment by AllanOricil** [comment]
These PRs fix this bug

**Comment by cristiand391** [comment]
closing this, for big queries we added a new `data export bulk` commands:
https://github.com/forcedotcom/cli/tree/main/releasenotes/#2626-october-16-2024

bulk mode for `data query` will be deprecated in a future release.
