### ISSUE TITLE
Source deploy destructive changes issues with Documents

### ISSUE THREAD

**Issue by gitfish** [forcedotcom/cli#1996]
### Summary

When attempting to use source deploy (force:source:deploy) with a destructive manifest containing a document that has the same name as the containing folder, the deployment will attempt to delete the containing folder.

### Steps To Reproduce:

1.  Create a document folder named 'A'
2.  Create a document under the folder named 'A'

Create a destructive manifest that looks as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>A</members>
        <name>Document</name>
    </types>
    <version>57.0</version>
</Package>
```
Use this manfiest with `force:source:deploy` and the `--postdestructivechanges` flag (along with any/an empty manifest for the `--manifest` flag).

### Expected result

Deployment succeeds and deletes the document named 'A'. No attempt should be made to delete the document folder 'A'.

### Actual result

Deployment attempts to delete the document folder 'A' and we get the following result:

```
Type  Name Problem                                                                                                                                                                                                    
 ───── ──── ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
 Error A    Your attempt to delete A cannot be completed because it contains the following documents. If any of these documents are in the Recycle Bin, you must empty your Recycle Bin before deleting the folder.: A 
 Error A    Your attempt to delete A cannot be completed because it contains the following documents. If any of these documents are in the Recycle Bin, you must empty your Recycle Bin before deleting the folder.: A
```

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

zsh

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here

```
{
  "cliVersion": "sfdx-cli/7.191.1",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v16.18.1"
}
```

### Additional information

_Feel free to attach a screenshot_.

**Comment by gitfish** [comment]
I suspect this is not actually a source plugin issue but an issue on the sf metadata api side.

**Comment by iowillhoit** [comment]
Hey @gitfish 👋 I think that this might be functioning as designed. 

- I created a `documents` directory in `force-app/main/default`
- In the `documents` folder, I added:
  - A folder named `logo`
  - and a `DocumentFolder` metadata file (`logo-meta.xml`): 
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
    <DocumentFolder xmlns="http://soap.sforce.com/2006/04/metadata">
        <accessType>Public</accessType>
        <name>Logo</name>
        <publicFolderAccess>ReadOnly</publicFolderAccess>
    </DocumentFolder>
    ```
- In the `logo` folder I added:
  - A png also called `logo` (no extension)
  - and a `Document` metadata file (`logo-meta.xml`):
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
    <Document xmlns="http://soap.sforce.com/2006/04/metadata">
        <name>Logo</name>
        <internalUseOnly>true</internalUseOnly>
        <public>false</public>
    </Document>
    ```
- I pushed all source with `sfdx force:source:push`
- I generated a `package.xml` manifest with `sfdx force source manifest create --fromorg my-user@example.com`
- I created a `destructiveChangesPost.xml` file with the following contents:
  ```xml
  <?xml version="1.0" encoding="UTF-8"?>
  <Package xmlns="http://soap.sforce.com/2006/04/metadata">
      <types>
          <members>logo</members>
          <name>Document</name>
      </types>
      <version>57.0</version>
  </Package>
  ```
- I was able to reproduce your error when running `sfdx force:source:deploy --manifest package.xml --postdestructivechanges destructiveChangesPost.xml`
- However when I looked at the `package.xml` manifest that was generated from the org, I noticed that the members included `logo` for the folder and `logo/logo` for document:
  ```xml
  <types>
    <members>logo</members>
    <members>logo/logo</members>
    <name>Document</name>
  </types>
  ```
- I updated the `members` in my `destructiveChangesPost.xml` to `<members>logo/logo</members>` and I was able to successfully delete the nested `logo` file. 

Hopefully this is helpful. Let me know if are still seeing odd behavior. If so, a demo repo to reproduce it would be super helpful. Thanks!

**Comment by gitfish** [comment]
Ah yep - makes sense - looking at this guy now: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_folder.htm. Was expecting any folder related activity to have a metadata entry of type `Folder`, but I'd forgotten it comes along with the `Document` type.
We're actually generating the manifest using the source-deploy-retrieve lib after creating a component set with the deleted document entries using getPackageXml. Looks like this will automatically include the folder path as well, but that's probably because I haven't set some state indicating deletion (markedForDeletion on source components or destructive changes type).
Cheers @iowillhoit and thanks for the reminder.

**Comment by gitfish** [comment]
Working as expected.
