### ISSUE TITLE
nonexistant flag org-instance-url

### ISSUE THREAD

**Issue by thedavidhanks** [forcedotcom/cli#1998]
### Summary

In sfdx-cli v7.191.1
Issuing command `sfdx auth:jwt:grant --org-instance-url=https://test.salesforce.com` results in an error
Error (1): Nonexistent flag: --org-instance-url=https://test.salesforce.com

### Steps To Reproduce:

I'm running this command:
`sfdx auth:jwt:grant --client-id=$QA_CONSUMER_KEY --username=$SFDX_QA_USER --jwt-key-file=/home/node/keys/server.key --set-default-dev-hub --alias=sfdx-ci --org-instance-url=https://test.salesforce.com`

which produces the error:
`Error (1): Nonexistent flag: --org-instance-url=https://test.salesforce.com`

`--org-instance-url https://test.salesforce.com` results in "Unexpected argument: https://test.salesforce.com/"
`--instanceurl=https://test.salesforce.com`  results in "Nonexistent flag: --instanceurl=https://test.salesforce.com"
-r https://test.salesforce.com works as expected

### System Information

This is being run in a bitbucket pipeline utilizing the docker container: [dphanks/sfdx-pipeline](https://hub.docker.com/r/dphanks/sfdx-pipeline)  on Alpine linux

*SFDX version*
sfdx-cli/7.191.1 linux-x64 node-v19.7.0

```{
  "cliVersion": "sfdx-cli/7.191.1",
  "architecture": "linux-x64",
  "nodeVersion": "node-v19.7.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.3 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.6 (core)",
    "@oclif/plugin-not-found 2.3.21 (core)",
    "@oclif/plugin-plugins 2.3.2 (core)",
    "@oclif/plugin-search 0.0.13 (core)",
    "@oclif/plugin-update 3.1.6 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.29 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "apex 2.2.1 (core)",
    "auth 2.7.3 (core)",
    "community 2.2.3 (core)",
    "custom-metadata 2.1.5 (core)",
    "data 2.3.4 (core)",
    "info 2.4.7 (core)",
    "limits 2.3.5 (core)",
    "org 2.4.4 (core)",
    "packaging 1.15.0 (core)",
    "schema 2.3.1 (core)",
    "settings 1.4.0 (core)",
    "signups 1.4.5 (core)",
    "source 2.5.5 (core)",
    "telemetry 2.1.1 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.4 (core)",
    "user 2.3.2 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)"
  ],
  "osVersion": "Linux 5.10.101",
  "shell": "unknown",
  "rootPath": "/usr/local/lib/node_modules/sfdx-cli"
}```

**Comment by AllanOricil** [comment]
@thedavidhanks 

The flag is called `--instance-url` 

https://github.com/salesforcecli/plugin-auth/blob/main/src/commands/org/login/jwt.ts#L47-L53

**Comment by iowillhoit** [comment]
Hey @thedavidhanks, thanks for the issue. @AllanOricil is correct, the flag `--instance-url` should work. 

I am curious why `--instanceurl` is not working for you though. This **should** work because of the [flag alias configured here](https://github.com/salesforcecli/plugin-auth/blob/main/src/commands/org/login/jwt.ts#LL52).
I just ran this locally with an `npm` installed `7.191.1` and it worked. You _should_ see a message like:
`Warning: The "--instanceurl" flag has been deprecated. Use "--instance-url" instead.`

Is this an issue for you locally? 

FWIW, in case you are not aware we do publish Docker images weekly with every new release. They can be found [here](https://hub.docker.com/r/salesforce/salesforcedx/tags)

**Comment by thedavidhanks** [comment]
Ahh thanks guys  I see that now in your v7.190.0 release notes.

 --instance-url param works just fine.  Consider this closed.

@iowillhoit Looks like I used "--instanceUrl=" rather than "--instanceurl".  My fault.

Note that the[ README](https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md) for v7.191.1 says,
| Old name    | New Name         |
|-------------|------------------|
| instanceUrl | org-instance-url |

Perhaps this was only in reference to the plugin.

**Comment by iowillhoit** [comment]
You bet @thedavidhanks! That table you linked is for config values that you would set with `sfdx config set`, not flags for commands.
