### ISSUE TITLE
sf apex run: Nonexistent flag: --apex-code-file

### ISSUE THREAD

**Issue by dschach** [forcedotcom/cli#1999]
### Summary

```
sf apex run --apex-code-file ./data/sample-data.apex --target-org MyOrg
Error (1): Nonexistent flag: --apex-code-file
See more help with --help
```

`-f` works. `--apex-code-file` does not.

Unable to run Apex using the code from the documentation

### Steps To Reproduce:

1. Create a scratch org where you know an Apex class can run
2. Verify that `sfdx force:apex:execute -f ./data/sample-data.apex` works
3. Verify that `sf apex run -f ./data/sample-data.apex` works
4. Try with `sf apex run --apex-code-file ./data/sample-data.apex`
5. See the error above

### Expected result

Apex should execute, as the documentation says it would: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_apex_commands_unified.htm#cli_reference_apex_run_unified

### Actual result

Error as above

### System Information

- Which shell/terminal are you using? bash on OSX

```json
{
  "cliVersion": "@salesforce/cli/1.68.2",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.14.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.3 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.6 (core)",
    "@oclif/plugin-not-found 2.3.21 (core)",
    "@oclif/plugin-plugins 2.3.2 (core)",
    "@oclif/plugin-search 0.0.13 (core)",
    "@oclif/plugin-update 3.1.6 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.29 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "apex 2.2.1 (core)",
    "auth 2.7.3 (core)",
    "data 2.3.4 (core)",
    "deploy-retrieve 1.8.2 (core)",
    "env 2.1.1 (core)",
    "functions 1.21.2 (core)",
    "info 2.4.7 (core)",
    "limits 2.3.5 (core)",
    "login 1.2.1 (core)",
    "org 2.4.4 (core)",
    "schema 2.3.2 (core)",
    "settings 1.4.1 (core)",
    "sobject 0.1.7 (core)",
    "telemetry 2.1.1 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.4 (core)",
    "user 2.3.2 (core)"
  ],
  "osVersion": "Darwin 22.3.0",
  "shell": "zsh",
  "rootPath": "/Users/<my_user>/.local/share/sfdx/client/7.191.1-3d81e83/sf"
}
```

**Comment by AllanOricil** [comment]
@dschach 
The right flag is `--file` or `--apexcodefile` (alias)

https://github.com/salesforcecli/plugin-apex/blob/main/src/commands/apex/run.ts

**Comment by AllanOricil** [comment]
@dschach 


The right flag is "file"

https://github.com/salesforcecli/plugin-apex/blob/main/src/commands/apex/run.ts

**Comment by iowillhoit** [comment]
Thanks again @AllanOricil, that's correct! It does look like the [examples are incorrect on this though](https://github.com/salesforcecli/plugin-apex/blob/8bd1361183a0a99859802a2c36c391cbefd35cf4/messages/run.md?plain=1#L20), I will get a quick fix in. Thanks!

**Comment by dschach** [comment]
Will the documentation I referenced be updated as well?

**Comment by iowillhoit** [comment]
It will! I just got this fix merged in and we generate the website's Command Reference guide from the CLI itself. This change will be included in Thursday's `latest-rc` release of `sfdx`. Thanks again for reporting this @dschach
