### ISSUE TITLE
Add defaultpath to CLI Runtime Configuration Values

### ISSUE THREAD

**Issue by idanblich** [forcedotcom/cli#2]
**Is your feature request related to a problem? Please describe.**
Working in a DX project is done in most cases, on a specific feature , with a clear entry point (VisualForce page , Lightning app or any other URL).

**Describe the solution you'd like**
I would like to have a parameter like : defaultpath in the project level [CLI Runtime Configuration](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_config_values.htm) 
similar to FORCE_OPEN_URL from [Environment Variables
](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_env_variables.htm)

**What will be the result of the addition**
The expected behaviour is to be able to set a parameter like any other parameter (ex. defaultusername in sfdx-config.json in the .sfdx foler ) that will be the --path .
Run open comment ```sfdx force:org:open ``` will be open with defaultusername and defaultpath (as path)

**Comment by idanblich** [comment]
inspired by @douglascayers [ great post](https://douglascayers.com/2019/02/17/develop-against-any-org-with-visual-studio-code-tasks/) i was manage to accomplish opening of  VF page and Lightning App using code tasks feature.
Here is the code for the tasks.json file
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "SFDX: Open Visualforce Page",
            "type": "shell",
            "command": "sfdx",
            "args": [
                "force:org:open",
                "--path",
                "/apex/${fileBasenameNoExtension}",
            ],
            "group": "build",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "problemMatcher": []
        },
        {
            "label": "SFDX: Open Lightning App",
            "type": "shell",
            "command": "sfdx",
            "args": [
                "force:org:open",
                "--path",
                "/c/${fileBasename}",
            ],
            "group": "build",
            "presentation": {
                "reveal": "always",
                "panel": "shared"
            },
            "problemMatcher": []
        }
    ]
}
```

**Comment by mshanemc** [comment]
It's better to add new metadata types that you'd want to open directly (the example here was a VF page) to the source:open command https://github.com/salesforcecli/plugin-source/blob/main/src/commands/force/source/open.ts so that you can open any file in the CLI that you want.

**Comment by idanblich** [comment]
@mshanemc TY for your answer . 
How can i open a FlexiPage **not in edit mode** ? in lightning View
