### ISSUE TITLE
sfdx plugin command takes 2 minutes to run 

### ISSUE THREAD

**Issue by snugsfbay** [forcedotcom/cli#20]
### Summary

sfdx plugins 
command takes excessive time to run on my work computer 

### Steps To Reproduce:

1.  open command prompt
1.  sfdx plugins

### Expected result

prompt return of plugins information to confirm version as described here: https://trailhead.salesforce.com/content/learn/projects/quick-start-lightning-web-components/set-up-salesforce-dx

### Actual result

timed it at 2 minutes on work computer (personal computer does not have this issue)

### Additional information

**SFDX CLI Version**:
6.34.0

**OS and version**:
windows 7 (I know, it's my work computer, not my choice here)

**Comment by snugsfbay** [comment]
Saw the same today with **SFDX force:org:list** taking _2 minutes_ to complete from command prompt.
**SFDX CLI Version:**
6.50.0

**Comment by clairebianchi** [comment]
@snugsfbay can you give me more information on your work setup? 
-Are you behind a firewall? 
-Are you using windows defender? 
-Is this a new performance issue or have it always been slow?
-I realize it will take a while but providing the version of the CLI plugin would be very helpful as well

We are aware of the performance on Windows and are investigating. Any information you provide will help us.

**Comment by r-dub** [comment]
My issue is that that I hadn't set the proxy in the command prompt. 
set https_proxy=xxxxx
Then connected immediately as expected, but an error message would be nice when it's not able to connect.
