### ISSUE TITLE
`force:source:retrieve` does not work on unfiled/public email templates

### ISSUE THREAD

**Issue by shliachtx** [forcedotcom/cli#200]
### Summary

I cannot retrieve unfiled/public email templates using `force:source:retrieve`

### Steps To Reproduce:

1.  run `sfdx force:source:retrieve -m 'EmailTemplate:unfiled$public/My_Email_Template'`

### Expected result

Retrieve the named EmailTemplate from the org

### Actual result

Returns `No results found`

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.27.0-714f62f9c1 win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)

**OS and version**:
Windows 10 v 1903

**Comment by clairebianchi** [comment]
@shliachtx, Thank you. We have this logged as a bug and are sending it to the team that owns public email templates

**Comment by shliachtx** [comment]
Not sure if anything changed, but it seems to be working for me now.

**Comment by venkatesh-ss** [comment]
I am also facing the same issue. I am facing this in MAC systems only. In Windows, It's working fine.

Any thoughts guys?

**Comment by dschibster** [comment]
Should anyone ever comes across this issue again, in bash (especially on Macs), you need to escape the "$" symbol to ensure the entire path is correct. This command did it for me:

`sfdx force:source:retrieve -m "EmailTemplate:unfiled\$public/XXXXX`
