### ISSUE TITLE
sfdx org create scratch failing due to missing devhub authorization

### ISSUE THREAD

**Issue by robdavis-cs** [forcedotcom/cli#2003]
### Summary
In trying to migrate to the new versions of sfdx commands, I tried to create a scratch org like this `sfdx org create scratch --set-default -f config/project-scratch-def.json --duration-days 30 -a <ALIAS> --wait 10 --json --target-dev-hub <devhub>` but this command fails.

### Steps To Reproduce:
Authorize a devhub, attempt to create a scratch org

### Expected result
The scratch org should be created

### Actual result
The scratch org creation fails with the following error:
```
{
  "code": 1,
  "message": "No authorization information found for <DEVHUBUSERNAME>.",
  "name": "NamedOrgNotFoundError",
  "status": 1,
  "stack": "NamedOrgNotFoundError: No authorization information found for <DEVHUBUSERNAME>.\n    at Messages.createError (C:\\Users\\drd00\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-org\\node_modules\\@salesforce\\core\\lib\\messages.js:443:16)\n    at AuthInfo.loadDecryptedAuthFromConfig (C:\\Users\\drd00\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-org\\node_modules\\@salesforce\\core\\lib\\org\\authInfo.js:603:28)\n    at AuthInfo.initAuthOptions (C:\\Users\\drd00\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-org\\node_modules\\@salesforce\\core\\lib\\org\\authInfo.js:557:53)\n    at async AuthInfo.init (C:\\Users\\drd00\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-org\\node_modules\\@salesforce\\core\\lib\\org\\authInfo.js:528:13)\n    at async AuthInfo.create (C:\\Users\\drd00\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-org\\node_modules\\@salesforce\\kit\\lib\\creatable.js:57:9)\n    at async authorizeScratchOrg (C:\\Users\\drd00\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-org\\node_modules\\@salesforce\\core\\lib\\org\\scratchOrgInfoApi.js:168:22)\n    at async scratchOrgCreate (C:\\Users\\drd00\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-org\\node_modules\\@salesforce\\core\\lib\\org\\scratchOrgCreate.js:161:32)\n    at async EnvCreateScratch.run (C:\\Users\\drd00\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\plugin-org\\lib\\commands\\org\\create\\scratch.js:54:72)\n    at async EnvCreateScratch._run (C:\\Users\\drd00\\AppData\\Local\\sfdx\\node_modules\\@salesforce\\sf-plugins-core\\node_modules\\@oclif\\core\\lib\\command.js:108:22)\n    at async Config.runCommand (C:\\Users\\drd00\\AppData\\Local\\sfdx\\client\\7.192.2-2a9b975\\node_modules\\@oclif\\core\\lib\\config\\config.js:326:25)",
  "exitCode": 1,
  "warnings": []
}
```

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
- mintty 3.5.0

 CLI Version:
        sfdx-cli/7.192.2

 Architecture:
        win32-x64

 Node Version:
        node-v18.14.1

 Plugin Version:
        @oclif/plugin-autocomplete 2.1.4 (core)
        @oclif/plugin-commands 2.2.10 (core)
        @oclif/plugin-help 5.2.7 (core)
        @oclif/plugin-not-found 2.3.21 (core)
        @oclif/plugin-plugins 2.4.0 (core)
        @oclif/plugin-search 0.0.14 (core)
        @oclif/plugin-update 3.1.6 (core)
        @oclif/plugin-version 1.2.1 (core)
        @oclif/plugin-warn-if-update-available 2.0.30 (core)
        @oclif/plugin-which 2.2.16 (core)
        apex 2.2.2 (core)
        auth 2.7.7 (core)
        community 2.2.4 (core)
        custom-metadata 2.1.6 (core)
        data 2.3.6 (core)
        info 2.5.1 (core)
        limits 2.3.8 (core)
        org 2.6.0 (user)
        packaging 1.16.1 (core)
        schema 2.3.3 (core)
        settings 1.4.2 (core)
        signups 1.4.6 (core)
        source 2.5.5 (core)
        telemetry 2.1.3 (core)
        templates 55.4.4 (core)
        trust 2.4.4 (core)
        user 2.3.3 (core)
        @salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
        isvte-sfdx-plugin 1.1.16 (user)
        sfdmu 4.26.8 (user)
        sfdx-browserforce-plugin 2.10.0 (user)
        sfdx-plugin-prettier 1.0.5 (user)
        sfpowerkit 6.1.0 (user)

 OS and Version:
        Windows_NT 10.0.22621

 Shell:
        C:\Program Files\Git\usr\bin\bash.exe

 Root Path:
        C:\Users\drd00\AppData\Local\sfdx\client\7.192.2-2a9b975
### Additional information
This command works fine and the devhub is definitely authorized.
`sfdx force:org:create -s -f config/project-scratch-def.json -d 30 -a <ALIAS>`

**Comment by iowillhoit** [comment]
Hey @robdavis-cs, thanks for the issue! I just ran this locally with the same version of the CLI and was not able to replicate it. Is this happening every time you run this command or intermittently?

**Comment by iowillhoit** [comment]
A few other thoughts on this: 
- Can you run `sfdx org list` and confirm that the dev hub (under `Non-scratch orgs`) you are passing as `--target-dev-hub` is listed and connected?
- Are you passing in an `alias` or `username` for the `--target-dev-hub`?
- I notice in the working alternative command `force:org:create` you are not passing your hub, which would fall back to your default. Can you confirm you are using the same devhub for both commands: `force:org:create` and `org create scratch`?

**Comment by robdavis-cs** [comment]
@iowillhoit yes, it is happening every time I run the command.
* Confirmed that the org is conneced
* I've tried alias, username, and none for target dev hub
* Sorry I excluded it on the post but I've tried both with and without the devhubusername being explicit on the `force:org:create` command

**Comment by robdavis-cs** [comment]
@iowillhoit some more information: according to the devhub, those scratch orgs were actually created even though the command looks like it failed.

**Comment by robdavis-cs** [comment]
Actually, it appears to be working today. I didn't change anything since Friday so unfortunately don't have a potential solution if anyone else runs into this

**Comment by robdavis-cs** [comment]
It never gets past "Prepare Request" being checked in these steps if that means anything.
![image](https://user-images.githubusercontent.com/61063988/226403862-a6220a0d-a6c6-4e1a-a916-054006ddf598.png)

**Comment by iowillhoit** [comment]
Hey @robdavis-cs, thanks for the additional info. So those orgs are actually getting created? If you run `sfdx org list` do they show up? 
What happens if you run the `sfdx org create scratch` command with `--async`? I wonder if you'll see the same error.
Might also be worth logging out and back into your devhub.

**Comment by robdavis-cs** [comment]
They do not show up in `sfdx org list`

Running with the async flag appears to run successfully. I get the org info printed out without any errors at least (never used async creation before)

Reauthenticating the devhub had no effect unfortunately, same result.

**Comment by iowillhoit** [comment]
Glad that `--async` worked! I wonder if this is an output issue. When I create a scratch org with `sfdx org create scratch` I am not seeing any of the "steps" listed. Just this:

<img width="406" alt="Screenshot 2023-03-22 at 9 44 38 AM" src="https://user-images.githubusercontent.com/1715111/226941154-5005d6fd-78bc-46a3-b24a-5e2780c39831.png">

**Comment by iowillhoit** [comment]
Oh! Are you using Git Bash on Windows? Could you try this command in Powershell or Command Prompt? 
We don't currently support Git Bash (See the `Warning` [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_windows))

**Comment by robdavis-cs** [comment]
I thought that would do it but same issue when directly executing the sfdx command from powershell

**Comment by WillieRuemmele** [comment]
Hey @robdavis-cs, sorry for the silence, is this still affecting you? 

I just ran the command and noticed it hang after the `prepare request` step... but it eventually completed
```
 ➜  sfdx org create scratch -d -y 1 --definition-file config/project-scratch-def.json 

Creating Scratch Org... 
RequestId: 2SR3i0000008Yez (https://brave-bear-dev-ed.my.salesforce.com/2SR3i0000008Yez)
OrgId: 00DDH000000 
Username: test-edkaogvlcnev@example.com 
✓ Prepare Request
✓ Send Request
✓ Wait For Org
✓ Available
✓ Authenticate
✓ Deploy Settings
Done

Your scratch org is ready.
```

how long have you let it `send request` for?

**Comment by robdavis-cs** [comment]
@WillieRuemmele the `sfdx` version is failing, yes. But I switched to the `sf` version and that's working fine.

**Comment by emullernl** [comment]
I experience the same issue with `sfdx-cli/7.202.7 darwin-x64 node-v18.15.0`

```{
  "code": 1,
  "context": "EnvCreateScratch",
  "commandName": "EnvCreateScratch",
  "message": "No authorization information found for XXXXXXXXXXX.",
  "name": "NamedOrgNotFoundError",
  "status": 1,
  "stack": "NamedOrgNotFoundError: No authorization information found for XXXXXXXXXX.\n    at Messages.createError (/Users/xxxx/.local/share/sfdx/node_modules/@salesforce/plugin-org/node_modules/@salesforce/core/lib/messages.js:428:16)\n    at AuthInfo.loadDecryptedAuthFromConfig (/Users/xxxx/.local/share/sfdx/node_modules/@salesforce/plugin-org/node_modules/@salesforce/core/lib/org/authInfo.js:606:28)\n    at AuthInfo.initAuthOptions (/Users/xxxx/.local/share/sfdx/node_modules/@salesforce/plugin-org/node_modules/@salesforce/core/lib/org/authInfo.js:560:53)\n    at async AuthInfo.init (/Users/xxxx/.local/share/sfdx/node_modules/@salesforce/plugin-org/node_modules/@salesforce/core/lib/org/authInfo.js:531:13)\n    at async AuthInfo.create (/Users/xxxx/.local/share/sfdx/node_modules/@salesforce/kit/lib/creatable.js:57:9)\n    at async authorizeScratchOrg (/Users/xxxx/.local/share/sfdx/node_modules/@salesforce/plugin-org/node_modules/@salesforce/core/lib/org/scratchOrgInfoApi.js:168:22)\n    at async scratchOrgCreate (/Users/xxxx/.local/share/sfdx/node_modules/@salesforce/plugin-org/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:161:32)\n    at async EnvCreateScratch.run (/Users/xxxx/.local/share/sfdx/node_modules/@salesforce/plugin-org/lib/commands/org/create/scratch.js:38:72)\n    at async EnvCreateScratch._run (/Users/xxxx/.local/share/sfdx/node_modules/@oclif/core/lib/command.js:117:22)\n    at async Config.runCommand (/Users/xxxx/.local/share/sfdx/client/7.202.7-c8df4cc/node_modules/@oclif/core/lib/config/config.js:329:25)",
  "exitCode": 1,
  "warnings": []
}
```

But when i run the org create scratch command with `sf` it is working fine.
