### ISSUE TITLE
sf community create should not require a url-path-prefix since that is not required by Salesforce

### ISSUE THREAD

**Issue by peterTrifecta** [forcedotcom/cli#2005]
https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_community_commands_unified.htm#cli_reference_community_create_unified

When I run an `sf community create` command without an --url-path-prefix or with --url-path-prefix "" I get errors.

without --url-path-prefix gives me Missing required flag url-path-prefix
--url-path-prefix "" gives me Error (1): Enter a URL for your site.

The problem is that it is perfectly legitimate to not have a url-prefix on a community in a scratch org.

I am able to successfully run `sfdx force:community:create` and pass --url-path-prefix "".

**Comment by mshanemc** [comment]
Hey.  I tried removing the `required` property of the flag, and the communities REST api that the command calls always throws if the url prefix is missing.

I think you're right, according to the docs, but not according to what the API will actually accept.  

If this is important to you, open a salesforce case so that API gets fixed.

**Comment by peterTrifecta** [comment]
Well, can the REST API accept an empty string?  

This command work for me: 
sfdx force:community:create --name "mystore" --template-name "B2C Commerce (LWR)" --url-path-prefix "" --description "Store mystore created by script."

The change to the new "sf community create" command broke that behavior of allowing --url-path-prefix "".  Trying to pass -url-path-prefix "" should work with the new "sf community create" and it doesn't. That's the bug, I believe.

**Comment by iowillhoit** [comment]
Hey @peterTrifecta, I will give this a try and report back

**Comment by iowillhoit** [comment]
Thanks for the followup @peterTrifecta, this was a regression! I got a quick fix in.
You can install it now with `sfdx plugins install @salesforce/plugin-community` (version `2.2.8`) or wait until Thursday for it to be include in the `latest-rc` of `sfdx`

**Comment by cristiand391** [comment]
fixed in sfdx v7.194.1.
Release notes: https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71940-march-30-2023-stable
