### ISSUE TITLE
"sfdx apex:log:get" always returning the latest log file, even if a log-id is provided

### ISSUE THREAD

**Issue by coreychch** [forcedotcom/cli#2006]
### Summary

The `sfdx apex:log:get` command is not paying attention to the --log-id (-i) parameter.  It always returns the first/latest log file.

### Steps To Reproduce:

1.  Run `sfdx apex:log:list` which returns the list of logs in date/time order descending.
1.  Take a note of the first log id (e.g., say it is 07L000000000001), and pick a log id further down the list (e.g., 07L000000000005).
1.  Run `sfdx apex:log:get -i 07L000000000005 -d logs` to write the log out to a 'logs' folder.

### Expected result

The 'logs' folder should contain a file called 07L000000000005.log with the contents of that log from Salesforce.

### Actual result

The 'logs' folder contains a file called 07L000000000001.log with the contents of that log from Salesforce.

### Additional information

From a quick check, it appears src/commands/apex/get/log.ts is setting the 'number' flag to '1' by default, even if it is not passed in as a command line argument.  This is then passed onto LogService (logService.ts) and it is using "numberOfLogs" *in preference to* a specific "logId", which is why it looks to me like it always comes back with the latest log.

**SFDX CLI Version**: 7.192.2

**OS and version**: MacOS Monterey 12.6.2

**Comment by iowillhoit** [comment]
Good catch, your "quick check" looks accurate. I'll get a bug created. Thanks!

**Comment by iowillhoit** [comment]
I got a simple fix in @coreychch.
You can install it now with `sfdx plugins install @salesforce/plugin-apex` (version `2.2.7`) or wait until Thursday for it to be include in the `latest-rc` of `sfdx`
Thank you for reporting this and taking the time to dig into the source!

**Comment by coreychch** [comment]
@iowillhoit Great, thanks for addressing this so quickly!  Appreciate it.

**Comment by coreychch** [comment]
Tested in `latest-rc` release - is working fine now.
