### ISSUE TITLE
Cannot generate or Change a Password for a Scratch Org User: sfdx force:user:password:generate  shows error  "Error (1): No authorization information found for DevHub."

### ISSUE THREAD

**Issue by vytautasgermanavicius** [forcedotcom/cli#2007]
### Summary

Cannot Generate or Change a Password for a Scratch Org User using instructions [Generate or Change a Password for a Scratch Org User](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_passwd.htm)

### Steps To Reproduce:

I'm connected  to prod org.  I can open org using 'sfdx force:org:open -u prod-org'

I created scratchorg from prod-org .  I can open org using 'sfdx force:org:open -u scratch-org'

I need to generate password for a scratch-org user. I follow instructions from  
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_passwd.htm

> Generate a password for a scratch org user with this command:
> ```sfdx force:user:password:generate --targetusername <username>```

I run:  
```
sfdx force:user:password:generate  --targetusername scratch-org
```
But it shows: 
```
Error (1): No authorization information found for DevHub.
```

### Expected result

New password for scratch-org user .

### Actual result

```
Error (1): No authorization information found for DevHub.
```

### System Information

shell/terminal:  bash

```
$ sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.192.2",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.15.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.4 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.7 (core)",
    "@oclif/plugin-not-found 2.3.21 (core)",
    "@oclif/plugin-plugins 2.4.0 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.6 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.30 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "apex 2.2.2 (core)",
    "auth 2.2.8 (user)",
    "community 2.2.4 (core)",
    "custom-metadata 2.1.6 (core)",
    "data 2.3.6 (core)",
    "info 2.5.1 (core)",
    "limits 2.3.8 (core)",
    "org 2.4.6 (core)",
    "packaging 1.16.1 (core)",
    "schema 2.3.3 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.6 (core)",
    "source 2.5.5 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.4 (core)",
    "user 2.3.3 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)"
  ],
  "osVersion": "Linux 5.19.0-35-generic",
  "shell": "bash",
  "rootPath": "/usr/lib/node_modules/sfdx-cli"
}
```

**Comment by mshanemc** [comment]
duplicate of #2003

**Comment by iowillhoit** [comment]
Hey @vytautasgermanavicius, I am looking into this on the Issue that Shane linked. However, I did notice that you have a user linked version of `plugin-auth` (`"auth 2.2.8 (user)",`). Can you uninstall that so that you use the version of auth that is shipped with the plugin instead? Run: `sfdx plugins uninstall auth`

**Comment by vytautasgermanavicius** [comment]
@iowillhoit  Uninstalled plugin-auth ("auth 2.2.8 (user)",). 

? May this issue be related with : 
> Warning: The --target-dev-hub flag is deprecated and is no longer used by this command. The flag will be removed in API version 57.0 or later.

I had file in `~/.sfdx` with setting `defaultdevhubusername`.  I could not get `sfdx force:user:password:generate` running until I deleted that file.


Just in case, I uninstalled plugin-auth ("auth 2.2.8 (user)",).

**Comment by vytautasgermanavicius** [comment]
> duplicate of #2003

I created scratchorg using prod org as DevHub. After creation i can access both prod and scratchorg. 
Do I have to use any other DevHub, while I'm working with client's project? This would be security issue.
