### ISSUE TITLE
force:source:push doesn't fail on component failures

### ISSUE THREAD

**Issue by noerremark** [forcedotcom/cli#2008]
### Steps To Reproduce:

1. Change a component to something obviously invalid
2. Run ($? is the Return Code)
```
force:source:push
echo $?
```
3. Observe that the code returned is 0, which indicates that no failure happened

### Expected result

Since the push actually failed, it should have returned something else than 0.

### Actual result

```
Pushing v53.0 metadata to ------@example.com using the v57.0 SOAP API
DEPLOY PROGRESS | ████████████████████████████████████████ | 1/1 Components
Updating source tracking... done

=== Pushed Source

 STATE   FULL NAME  TYPE      PROJECT PATH                                           
 ─────── ────────── ───────── ────────────────────────────────────────────────────── 
 Changed c_UnitTest ApexClass force-app/main/default/classes/c_UnitTest.cls          
 Changed c_UnitTest ApexClass force-app/main/default/classes/c_UnitTest.cls-meta.xml 

=== Component Failures [1]

 Type  Name                            Problem                 
 ───── ─────────────────────────────── ─────────────────────── 
 Error classes/c_UnitTest.cls-meta.xml Invalid api version:0.0 

0
```

### System Information
`sfdx-cli/7.192.2 darwin-x64 node-v18.14.1`

**Comment by iowillhoit** [comment]
Interesting, I am not seeing that. 
<img width="970" alt="Screenshot 2023-03-21 at 1 28 57 PM" src="https://user-images.githubusercontent.com/1715111/226707341-8c826d86-4c0a-400e-aa21-42843df9c142.png">

- When you run this with `--json` does it give you an `exitCode` and `status` of `1`? 
- Could you send the full output of `sfdx version --verbose`

**Comment by iowillhoit** [comment]
Ok i was able to reproduce this. In my example above there were only failures, which gave an exitcode of `1` as expected. When you have a push that has successes and failures, it looks like you _should_ get an exit code `68` to show partial success. 

Source: https://github.com/salesforcecli/plugin-source/blob/main/src/commands/force/source/push.ts#L200-L215

<img width="1337" alt="Screenshot 2023-03-21 at 2 01 43 PM" src="https://user-images.githubusercontent.com/1715111/226714633-45853000-8237-4085-92b3-ff5ca88791d2.png">

I will get a ticket created and confirm with the team. Thanks @noerremark!

**Comment by iowillhoit** [comment]
This is working as expected in the new `project deploy start` command, please use that command instead. Note that we did just merge in a fix to properly print component failures to stdout. That will be in latest-rc next week.
