### ISSUE TITLE
Settings failing to deploy with CLI v47

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/cli#201]
**BUG**

### Summary

Settings in `project-scratch-def.json` fails to deploy with sfdx cli v47.1.5.
Moving back to previous version of the sfdx cli does work (`sfdx plugins:install salesforcedx@46.17.0`)

### Steps To Reproduce:

1.  Create a DX Project
2.  Update project-scratch-def.json to use the following settings:
```
"orgPreferenceSettings": {
      "eventLogWaveIntegEnabled": true,
      "sendThroughGmailPref": false,
      "loginForensicsEnabled": true
}
```

### Expected result

Scratch Org is created.

### Actual result

```
ERROR running force:org:create:  Failed to deploy settings to scratch org.
Error  shape/settings/EmailAdministration.settings  EmailAdministration enableSendThroughGmailPref.   
Error  shape/settings/Event.settings                Event                enableLoginForensics.   
Error  shape/settings/Event.settings  Event  enableEventLogWaveIntegration
```

### Additional information

@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.6
├─ @oclif/plugin-update 1.3.9
└─ @oclif/plugin-help 2.2.1

@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 47.1.5 (core)
├─ force-language-services 47.5.0 (core)
└─ salesforce-alm 47.4.0 (core)

sfdx-cli 7.28.7 (core)
sfdx-migration-automatic 1.5.0

**Comment by Boussad-Sedoud** [comment]
I'm facing the same kind of issue : 

_Error  shape/settings/EmailAdministration.settings  settings/EmailAdministration.settings  
Error  shape/settings/EnhancedNotes.settings        settings/EnhancedNotes.settings  
Error  shape/settings/Language.settings             settings/Language.settings_           

With the error :
**ERROR running force:org:create:  Failed to deploy settings to scratch org.**

The scratch is created but impossible to push from my org to the scratch. And Don't know why, the "Opportunity Split" doesn't existe in the scratch anymore.

I created a scratch yesterday without facing this issue..

In the "test-online-crm-scratch-def.json" file : 

`{

  "orgName": "TestOnsite CRM",
  "edition": "Enterprise",
  "country": "FR",
  "hasSampleData": false,
  "language": "en_US",
  "features": [
    "API",
    "AuthorApex",
    "AddCustomApps:10",
    "AddCustomTabs:30",
    "MultiCurrency",
    "ProcessBuilder",
    "StateAndCountryPicklist",
    "Workflow",
    "ContactsToMultipleAccounts",
    "SalesforceContentUser"
  ],
  "settings": {
    "accountSettings": {
      "enableAccountTeams": true,
      "showViewHierarchyLink": true
    },
    "opportunitySettings": {
      "enableOpportunityTeam": true,
      "autoActivateNewReminders": true,
      "promptToAddProducts": false
    },
    "name": {
      "enableMiddleName": true,
      "enableNameSuffix": true
    },
    "languageSettings": {
      "enableTranslationWorkbench": false
    },
    "pathAssistantSettings": {
      "pathAssistantEnabled": true
    },
    "enhancedNotesSettings": {
      "enableEnhancedNotes": false
    },
    "emailAdministrationSettings": {
      "enableEnhancedEmailEnabled": false
    }
  }
}
`

**Comment by Bilel3203** [comment]
Hello everyone,
Did someone find a solution of this kind of error because i'm facing the same issue. And the error persists even i get back to my previous project-scratch-def version.

Thank you for your help

**Comment by iandrosov** [comment]
This may be slightly different issue but still a problem in sfdx-cli/7.54.4-8ff9ba9cc5

ERROR running force:org:create:  No such column 'LanguageSettings' on sobject of type ScratchOrgInfo

Very simple config cannot enable translation Workbench on scratch org on creation to require manual step and breaks any type of CICD pipelines. This case NO actual translation used but Admin simply enabled Report Filter by language and broke the DX build.
{
  "orgName": "MyOrgName",
  "edition": "Developer",
  "features": [],
  "languageSettings": {
    "enableTranslationWorkbench": true
  }
}

**Comment by FabienTaillon** [comment]
@iandrosov aren't you just missing a `settings` section on top of `languageSettings` ?

```
{
    "orgName": "MyOrgName",
    "edition": "Developer",
    "features": [],
    "settings": {
        "languageSettings": {
            "enableTranslationWorkbench": true
        }
    }
}
```

**Comment by ayan-sarkar-cse** [comment]
@FabienTaillon : What JSON structure to add here to make sure that for German and French the translation workbench is pre-selected?

**Comment by FabienTaillon** [comment]
I don't think it's part of the settings, but part of the metadata. For instance, after activating French, a file named `fr.translation-meta.xml` was pulled from the Scratch Org. Pushing it back to a new Scratch Org activate this specific language.

**Comment by iowillhoit** [comment]
:wave: Grooming old Issues. Regarding the original post, `orgPreferenceSettings` was removed in API version 48 ([docs](https://developer.salesforce.com/docs/atlas.en-us.246.0.api_meta.meta/api_meta/meta_orgpreferencesettings.htm#:~:text=OrgPreferenceSettings-,Removed%20in%20API%20version%2048.0,-.%20Represents%20the%20unique)). 

If others are still having Settings related trouble, please open a new Github Issue. Thanks!
