### ISSUE TITLE
Seeing a situation where `force:source:push` exits successfully but hasn't pushed everything; second push is required

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#2013]
While testing a bit with a few open source projects, I noticed that one project had a strange behavior where an initial push succeeds but not everything is actually pushed, then a second push--which should be a no-op--deploys the rest to make it whole as a third push is in fact a no-op. The specific project is [NebulaLogger](https://github.com/jongpie/NebulaLogger). Should be easy to reproduce as you just need to clone the project, create a scratch org, and push. If you look in the org after the first push, you'll find that the CMDTs weren't pushed. Push again, and they are. Push again and there's nothing left to do. Expected? My guess is no...

**Comment by petter-eikeland** [comment]
I also experience this from time to time, but haven't been able to reproduce the issue yet

**Comment by iowillhoit** [comment]
Hey @SCWells72 are you still seeing this issue with the latest version of `sf` and the `project deploy start` command?

**Comment by SCWells72** [comment]
@iowillhoit, IC2 still executes `sfdx force:source:push`, though my understanding is that under the hood, that should resolve to the same thing. Having said that, I don't recall having seen this in quite a while, so I'm fine if you want to resolve/close it.

**Comment by petter-eikeland** [comment]
I haven't seen it in a while either
