### ISSUE TITLE
force:source:convert with Digital Experiences creating invalid packages on windows

### ISSUE THREAD

**Issue by Bobnix** [forcedotcom/cli#2014]
### Summary

When running sfdx force:source:convert on windows against a directory with digital experiences in it, the resulting package.xml contains invalid entries

### Steps To Reproduce:

**Repository to reproduce:** [SFDXConvertBug](https://github.com/Bobnix/SFDXConvertBug)

1.  Start with a windows PC
2. Install sfdx-cli 193.2
3. Pull from the repository
4. Run sfdx force:source:convert
5. Observe the package.xml file in the newly created folder

### Expected result

Members with forward slash path delimiter

[...]
<members>site/CED_LWR1.sfdc_cms__view/newsDetail</members>
<members>site/CED_LWR1.sfdc_cms__view/register</members>
<members>site/CED_LWR1.sfdc_cms__view/serviceNotAvailable</members>
<members>site/CED_LWR1.sfdc_cms__view/tooManyRequests</members>
[...]

### Actual result

Members with back slash path delimiter

[...]
<members>site\DE_LWR1.sfdc_cms__view\newsDetail</members>
<members>site\DE_LWR1.sfdc_cms__view\register</members>
<members>site\DE_LWR1.sfdc_cms__view\serviceNotAvailable</members>
<members>site\DE_LWR1.sfdc_cms__view\tooManyRequests</members>
[...]

### System Information

Microsoft Azure DevOps
{
"cliVersion": "sfdx-cli/7.193.2",
"architecture": "win32-x64",
"nodeVersion": "node-v16.15.1",
"osVersion": "Windows_NT 10.0.17763",
"shell": "cmd.exe",
"rootPath": "D:\\Agent2\\_work\\1578\\s\\node_modules\\sfdx-cli",
"pluginVersions": [
"@oclif/plugin-autocomplete 2.1.5 (core)",
"@oclif/plugin-commands 2.2.10 (core)",
"@oclif/plugin-help 5.2.8 (core)",
"@oclif/plugin-not-found 2.3.22 (core)",
"@oclif/plugin-plugins 2.4.2 (core)",
"@oclif/plugin-search 0.0.14 (core)",
"@oclif/plugin-update 3.1.7 (core)",
"@oclif/plugin-version 1.3.0 (core)",
"@oclif/plugin-warn-if-update-available 2.0.31 (core)",
"@oclif/plugin-which 2.2.16 (core)",
"apex 2.2.5 (core)",
"auth 2.7.8 (core)",
"community 2.2.5 (core)",
"custom-metadata 2.1.7 (core)",
"data 2.3.6 (core)",
"info 2.6.0 (core)",
"limits 2.3.8 (core)",
"org 2.5.0 (core)",
"packaging 1.16.2 (core)",
"schema 2.3.3 (core)",
"settings 1.4.2 (core)",
"signups 1.4.7 (core)",
"source 2.8.0 (core)",
"telemetry 2.1.3 (core)",
"templates 55.4.4 (core)",
"trust 2.4.4 (core)",
"user 2.3.5 (core)",
"@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
"sfdx-cli 7.193.2 (core)",
"sfdx-git-delta 5.13.3 (user)"
]
}

**Comment by shetzel** [comment]
@Bobnix - does this cause errors when using the manifest in a deploy or retrieve?

**Comment by Bobnix** [comment]
@shetzel Deploy, I run this command followed by sfdx force:mdapi:deploy

**Comment by Bobnix** [comment]
Also the code that generates this is in [digitalExperienceSourceAdapter.ts](https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/resolve/adapters/digitalExperienceSourceAdapter.ts), it would be a small change but I do not understand the codebase enough to know the side effects of always using '/' instead of path.sep

**Comment by shetzel** [comment]
Thank you.  Looks like a bug and will be fixed asap.  Thanks for reporting!

**Comment by cristiand391** [comment]
This should be fixed on latest. Please let us know if you still see this on windows.
