### ISSUE TITLE
Permission sets not updating when renaming API fieldname

### ISSUE THREAD

**Issue by ng-nina** [forcedotcom/cli#2015]
### Summary

When I rename API name of a field, I must navigate to relevant permission sets and update them manually.

### Steps To Reproduce:

1.  Create a field in a scratch org
2. Assign to relevant permission set(s)
3. SFDX Pull
4. Rename API-name of field
5. SFDX Pull

### Expected result

I expect that after renaming the API-name of the field, the permission set is automatically updated when I pull metadata from my scratch org, giving me two files consisting of the field and the permission set.

### Actual result

I only receive one file regarding the renaming, and must navigate in to the relevant permission set in the scratch org and update it, and execute another SFDX Pull to receive the file of the updated permission set.

### System Information

- Terminal in VS Code

**Comment by WillieRuemmele** [comment]
Hi @ng-nina,

I tried reproducing this, but it was working as I was expecting it to.

1. create custom field on object
2. add CF to permissionSet
3. pull
4. see CF in permissionset in the project
5. rename the field from objects > <object> > fields > rename
6. pull
7. I now see the updated field name in the permission set in the project.

```
    <fieldPermissions>
        <editable>false</editable>
        <field>Broker__c.customField2__c</field>
        <readable>true</readable>
```

it was originally named `customField` and updated to `customField2` 

let me know if I missed a step, or looked in the wrong place

**Comment by ng-nina** [comment]
Hello,

Thank you for your response.

Are you adding the CF to the permissionSet using Field-Level Security for Permission Sets during Field Creation (Beta)?
![Screenshot 2023-04-11 at 12 47 27](https://user-images.githubusercontent.com/72379479/231138039-38ac0a5e-84d0-4521-bf6b-ba929c890882.png)

**Comment by WillieRuemmele** [comment]
Hey @ng-nina - I didn't have that enabled the first time. I just tried it again, with that enabled, and still couldn't reproduce it.

my permission set again... same name 
```
    <fieldPermissions>
        <editable>false</editable>
        <field>Broker__c.customField2__c</field>
```
and the pull result 
```
=== Retrieved Source

 STATE   FULL NAME                 TYPE          PROJECT PATH                                                                   
 ─────── ───────────────────────── ───────────── ────────────────────────────────────────────────────────────────────────────── 
 Created Broker__c.customField2__c CustomField   force-app/main/default/objects/Broker__c/fields/customField2__c.field-meta.xml 
 Deleted Broker__c.customField__c  CustomField   force-app/main/default/objects/Broker__c/fields/customField__c.field-meta.xml  
 Changed Broker__c-Broker Layout   Layout        force-app/main/default/layouts/Broker__c-Broker Layout.layout-meta.xml         
 Changed dreamhouse                PermissionSet force-app/main/default/permissionsets/dreamhouse.permissionset-meta.xml 
```
are you using the latest CLI version? what's the output of `sfdx plugins --core`?

**Comment by petter-eikeland** [comment]
Hi @WillieRuemmele, we experience the same issue. However, it seems like might be related to https://github.com/forcedotcom/source-tracking and `sfdx org login sfdx-url`. We have a nightly job that prepares our scratch org (deploying all metadata on main branch). Then, each developer authenticates to a scratch org with all metadata preinstalled. To avoid having to push all files locally, we generate local source tracking files while we fetch the pre-generated scratch org using https://github.com/forcedotcom/source-tracking

 
The easiest way to replicate this would be to do the following:

1. Have a custom field and a permission set that references this custom field in a local project
1. Create an empty scratch org
1. `sfdx project deploy `the field and perm set
    a.  This will generate source tracking files that we will reuse
1. Mimic fetching a scratch org previously created:
    a. Move the source tracking (.sf/orgs/<OrgID> folder) out of the project
    b. Expose sfdx auth url using `sfdx org display --json --verbose > auth.json`
    c. Delete the auth file for the newly created scratch org (.sfdx folder in your user directory)
    d. Authenticate to the scratch org again using `sfdx org login sfdx-url -f auth.json`
    e. Move the source tracking folder back to the project
1. Open the scratch org, rename the custom field and project retrieve down changes
     a. Now, only the field should be listed as the change. The Perm Set is unchanged


```
Pulling v56.0 metadata from test-vnncfyy1u95i@example.com using the v57.0 SOAP API
Updating source tracking... done
=== Retrieved Source

 STATE   FULL NAME        TYPE        PROJECT PATH                                                        
 ─────── ──────────────── ─────────── ─────────────────────────────────────────────────────────────────── 
 Deleted Account.Test__c CustomField src-tmp/main/default/objects/Account/fields/Test__c.field-meta.xml 
 Created Account.Test2__c CustomField src-tmp/main/default/objects/Account/fields/Test2__c.field-meta.xml 
```

**sfdx version**
```
{
  "cliVersion": "sfdx-cli/7.196.5",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.3.0",
  "shell": "zsh",
  "rootPath": "/Users/user/.local/share/sfdx/client/7.196.5-233a8d3",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 20.30.4 (user)",
    "@eon-com/eon-sfdx 1.11.2 (user)",
    "@oclif/plugin-autocomplete 2.1.8 (core)",
    "@oclif/plugin-commands 2.2.13 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.4 (core)",
    "@oclif/plugin-search 0.0.15 (core)",
    "@oclif/plugin-update 3.1.9 (core)",
    "@oclif/plugin-version 1.3.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.33 (core)",
    "@oclif/plugin-which 2.2.18 (core)",
    "1commerce 0.0.10 (user)",
    "apex 2.2.10 (core)",
    "auth 2.7.11 (core)",
    "community 2.2.9 (core)",
    "custom-metadata 2.1.11 (core)",
    "data 2.3.9 (core)",
    "deploy-retrieve 1.8.8 (core)",
    "info 2.6.4 (core)",
    "limits 2.3.12 (core)",
    "org 2.6.5 (core)",
    "packaging 1.16.3 (core)",
    "schema 2.3.6 (core)",
    "settings 1.4.3 (core)",
    "signups 1.4.11 (core)",
    "source 2.9.1 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.5 (core)",
    "trust 2.4.6 (core)",
    "user 2.3.7 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "sfdmu 4.26.10 (user)",
    "sfdx-cli 7.196.5 (core)",
    "sfpowerkit 6.1.0 (user)"
  ]
}
```

**Comment by WillieRuemmele** [comment]
Hi @petter-eikeland 👋 

Myself and a fellow CLI engineer followed your instructions a few times, with and without the setting that @ng-nina had enabled and weren't able to reproduce it 😦 

do you have anything in your `.forceignore` that could be preventing this from working? Can you create a reproduction repository with a simple project, and script, that reproduces this issue, or a screen recording we can follow step for step?

below I've attatched the commands I ran, and their outputs. This starts from step 4c, I run a `force source status` command just to ensure that the auth information is removed 
```
➜  dreamhouse-lwc git:(main) ✗  hub:(DevHub) scratch:(test-ghvp7r0qwn3j@example.com)
 ➜  status (force source status)
Warning: We plan to deprecate this command in the future. Try using the "project retrieve/deploy preview" command instead.
Error (1): No default environment found. Use -o or --target-org to specify an environment.
➜  dreamhouse-lwc git:(main) ✗  hub:(DevHub) scratch:(test-ghvp7r0qwn3j@example.com)
 ➜  sfdx org login sfdx-url -f auth.json
Successfully authorized test-ghvp7r0qwn3j@example.com with org ID 00DDE0000045aEk2AI
➜  dreamhouse-lwc git:(main) ✗  hub:(DevHub) scratch:(test-ghvp7r0qwn3j@example.com)
 ➜  mv ../00DDE0000045aEk2AI .sf/orgs 
➜  dreamhouse-lwc git:(main) ✗  hub:(DevHub) scratch:(test-ghvp7r0qwn3j@example.com)
 ➜  oo (org open)
Opening org 00DDE0000045aEk2AI as user test-ghvp7r0qwn3j@example.com
Waiting to resolve the Lightning Experience-enabled custom domain...... done

-- 
in the org, objects > Broker > fields > rename customField3
--
➜  dreamhouse-lwc git:(main) ✗  hub:(DevHub) scratch:(test-ghvp7r0qwn3j@example.com)
 ➜  sfdx project retrieve start
Preparing retrieve request... Succeeded

Retrieved Source
================================================================================================================================
| State   Name                      Type          Path                                                                           
| ─────── ───────────────────────── ───────────── ────────────────────────────────────────────────────────────────────────────── 
| Deleted Broker__c.customField3__c CustomField   force-app/main/default/objects/Broker__c/fields/customField3__c.field-meta.xml 
| Created Broker__c.customField4__c CustomField   force-app/main/default/objects/Broker__c/fields/customField4__c.field-meta.xml 
| Changed Broker__c-Broker Layout   Layout        force-app/main/default/layouts/Broker__c-Broker Layout.layout-meta.xml         
| Changed dreamhouse                PermissionSet force-app/main/default/permissionsets/dreamhouse.permissionset-meta.xml    
```

I changed `customfield3` to `customfield4` on the `Broker` object in dreamhouse.

**Comment by petter-eikeland** [comment]
@WillieRuemmele Thanks for your swift investigation. I'm also struggling reproducing the issue again with the steps above. I must be missing a step or two. I will investigate further how I can confidently reproduce our issue without reimplementing our implementation of https://github.com/forcedotcom/source-tracking and come back to you
