### ISSUE TITLE
`sfdx org create scratch` should support key=value pairs as `sfdx force:org:create` did

### ISSUE THREAD

**Issue by amtrack** [forcedotcom/cli#2016]
**Is your feature request related to a problem? Please describe.**

The new `sfdx org create scratch` command does not allow overriding values from the configuration file which the `sfdx force:org:create` command did allow.

**What are you trying to do**

When creating Scratch Orgs I want to be able to pass dynamic for values like

- `username`
- `description`
- `orgName`
- `release`

I don't want to write them to a config file first.

**Describe the solution you'd like**

Pass overrides as

- "varargs", similar to
   `sfdx org create user username=testuser1@my.org email=me@my.org permsets=DreamHouse`
- or as "values" flag, similar to
   `sfdx data create record --sobject Account --values "Name='Universal Containers' Website=www.example.com"`
- yet another solution

**Describe alternatives you've considered**

Staying on `sfdx force:org:create`, not updating to `sfdx org create scratch`

**Additional context**

I'd like to offer my help here.
If you think this is a good idea for a contribution, please tell me which style you'd prefer.

**Comment by mshanemc** [comment]
would new flags cover your use cases instead of values/args

The reason we prefer flags is that they can have help, or support multiple values, and validate allowed options (ex: release only allows certain things).

**Comment by amtrack** [comment]
@mshanemc Great idea! Love it!
And yes, this would cover my use cases.
If there are many new flags, maybe using the `helpGroup` would make sense for readability of the help page.

**Comment by mshanemc** [comment]
oh, a help group just for the "flags that override the config file" ?  Makes sense.

**Comment by amtrack** [comment]
I still like the idea of creating new flags (especially for fields that caused trouble in the past like "release").
I counted ~10 new flags for writeable standard fields on ScratchOrgInfo.

What about custom fields on ScratchOrgInfo?
Do you know if someone is using the varargs to populate custom fields?
This could also be a use case.

**Comment by mshanemc** [comment]
I don't have any data about custom fields on ScratchOrgInfo.  

We also don't read the varArgs in telemetry (trying to keep confidential data out of logs), only which flags are being used (but not values).  So we don't have data.  I'm hoping people will tell us, like you did, about what they need on the new command.

**Comment by amtrack** [comment]
I just raised this question in the `cli-friends` slack channel...
