### ISSUE TITLE
Delete Scratch Org when force:org:create didn't succeed

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/cli#202]
**BUG**
With the new mapping between the Metadata API settings and the project-scratch-def.json file, the CLI is now creating a Scratch Org, and then deploy the settings. 

This is an implementation detail, but leading to a painful result:   
Each time a Scratch Org fails because of a setting issue (`ERROR running force:org:create:  Failed to deploy settings to scratch org`), the Scratch Org is still created and counts against the active Scratch Org limit (`ERROR running force:org:create:  The signup request failed because this organization has reached its active scratch org limit`).

**What are you trying to do**
Trying to create a Scratch Org, and if it doesn't work, don't count it in the active scratch org limit as the command failed. 

**Describe the solution you'd like**
When `sfdx force:org:create` fails, don't count it in the active scratch org limit (most likely, delete it if settings deployment failed).

**Additional context**
Today we had an issue with Scratch Org creation and its related settings (see #201). When a whole team is trying to create a Scratch Org, that it's failing, and that each failed attempt count against the limit, you quickly reach the limit.

**Comment by aheber** [comment]
As a side note, this will also count against the daily creation limit (usually double the active limit). If this becomes a consistent problem you could easily exhaust both limits before you know it.

**Comment by jshackell-sfdc** [comment]
This issue was fixed in version 2.47.6 (June 26, 2024).
