### ISSUE TITLE
Cannot push static resource zip file containing file named *-meta.xml

### ISSUE THREAD

**Issue by jeffhube** [forcedotcom/cli#2020]
### Summary

If you attempt to use `sfdx force source push` to push a static resource zip file containing a file such as "A-meta.xml", it will fail.

### Steps To Reproduce:

**Repository to reproduce:** [sfdx-repro](https://github.com/jeffhube/sfdx-repro)

```console
$ git clone https://github.com/jeffhube/sfdx-repro.git
$ cd sfdx-repro
$ sfdx force org create -f config/project-scratch-def.json -s
$ sfdx force source push
ERROR running force:source:push:  Component conversion failed: A StaticResource must have an associated .resource file, missing staticresources\A.resource-meta.xml
```

### Expected result

The `sfdx force source push` command completes successfully, creating a static resource that is a zip file containing the expected files.

### Actual result

The `sfdx force source push` command fails.

### System Information

- Which shell/terminal are you using? PowerShell 7

```json
{
  "cliVersion": "sfdx-cli/7.193.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.14.2",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\****\\AppData\\Local\\sfdx\\client\\7.193.2-380b8be",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.5 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.2 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.7 (core)",
    "@oclif/plugin-version 1.3.0 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.31 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "apex 2.2.5 (core)",
    "auth 2.7.8 (core)",
    "community 2.2.5 (core)",
    "custom-metadata 2.1.7 (core)",
    "data 2.3.6 (core)",
    "info 2.6.0 (core)",
    "limits 2.3.8 (core)",
    "org 2.5.0 (core)",
    "packaging 1.16.2 (core)",
    "schema 2.3.3 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.7 (core)",
    "source 2.8.0 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.4 (core)",
    "user 2.3.5 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "sfdx-cli 7.193.2 (core)"
  ]
}
```

**Comment by WillieRuemmele** [comment]
Hi @jeffhube - I'm not sure this is a bug, but a limitation with the `StaticResource` Metadata type itself... it's [limited](https://help.salesforce.com/s/articleView?id=sf.pages_static_resources.htm&type=5) to 
> Static resources allow you to upload content that you can reference in a Visualforce page, including archives (such as .zip and .jar files), images, style sheets, JavaScript, and other files

if I zip the example in your directory like 

`zip MyStaticResource.zip force-app/main/default/staticresources/MyStaticResource` on MacOS
then replace your "MyStaticResource" directory, with the zip, it `project deploy starts` correctly. It seems like directories must be stored as zips when pushing to an org

**Comment by jeffhube** [comment]
Given that it works fine when using a zip file instead of having sfdx zip it automatically, it seems to be an issue with sfdx rather than a platform limitation. However, I also realize that this is not a common scenario and it is pretty easy to work around.
