### ISSUE TITLE
Simplify Project Deploy & Project Retrieve commands

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#2022]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
`project deploy start` & `project retrieve start` should be simplified to `project deploy` & `project retrieve`

**Comment by AllanOricil** [comment]
@petter-eikeland where did you find these commands? I cant see them. Im using 1.70.0

**Comment by petter-eikeland** [comment]
@AllanOricil They are coming in 7.195.0, i.e. sfdx RC this week
