### ISSUE TITLE
Metadata API deploy client timeout error after 2 hours, But deployment is running and successful on salesforce end.

### ISSUE THREAD

**Issue by Saipraneeth-hub** [forcedotcom/cli#2023]
**Summary**

The customer is deploying through SFDX where deployment is successfully running in salesforce, but SFDX is failing with the below error which is causing the time out after 2 hrs. and breaking the CI/CD.

ERROR running force:mdapi:deploy: Metadata API request failed: The client has timed out.

**Steps To Reproduce:**

1. CI/CD pipeline.
2. We need to deploy through SFDX.

**Expected result**

SFDX shouldn't fail with the timeout error after 2 hrs and break the CI/CD

**Actual result**

SFDX is failing with the timeout error which is causing the time out after 2 hrs and breaking the CI/CD pipleline.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.) - gitlab

**Comment by cristiand391** [comment]
Hi @Saipraneeth-hub , can you fill the issue template with the requested info? See: https://github.com/forcedotcom/cli/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

Also would help if you can share the full command with flags the customer is running.
