### ISSUE TITLE
Package Version Create command fails to read version number build keyword

### ISSUE THREAD

**Issue by thomasminney** [forcedotcom/cli#2024]
### Summary

In [packageVersionCreate](https://github.com/forcedotcom/packaging/blob/main/src/package/packageVersionCreate.ts) versionNumber type is not consistently used. Where array index is being used, class properties are now available.

For example, in [resolveBuildNumber()](https://github.com/forcedotcom/packaging/blob/main/src/package/packageVersionCreate.ts#L221), `versionNumber[3]` is compared for build keyword but this always returns `undefined`. Instead `versionNumber.build` property should be used.

This causes branch and isreleased conditions to be excluded when calculating dependency subscriber package version ids and then error **VersionNumberNotFoundInDevHubError** is thrown.

### Steps To Reproduce:

1. Create two package versions of a dependency with no branch and versionNumber `0.1.0.LATEST` (so latest build number without branch set is 2).
2. Create another package version of the same dependency with branch `test` and versionNumber `0.1.0.LATEST` (so latest build number with branch set to `test` is 1).
3. Run `package version create` command with branch `test`.
4. This will cause `resolveBuildNumber()` to return 2 instead of 1.

### Expected result

Package version is created with dependency at version 0.1.0.1 for branch `test`

### Actual result

`VersionNumberNotFoundInDevHubError` error with message `No version number was found in Dev Hub for package id <dependency id> and branch 'test' and version number 0.1.0.LATEST that resolved to build number 2.`

### System Information

cmd.exe
{
  "cliVersion": "sfdx-cli/7.193.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.14.2",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\thomasminney\\AppData\\Local\\sfdx\\client\\7.193.2-380b8be",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.5 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.2 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.7 (core)",
    "@oclif/plugin-version 1.3.0 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.31 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "apex 2.2.5 (core)",
    "auth 2.7.8 (core)",
    "community 2.2.5 (core)",
    "custom-metadata 2.1.7 (core)",
    "data 2.3.6 (core)",
    "info 2.6.0 (core)",
    "limits 2.3.8 (core)",
    "org 2.5.0 (core)",
    "packaging 1.16.2 (core)",
    "schema 2.3.3 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.7 (core)",
    "source 2.8.0 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.4 (core)",
    "user 2.3.5 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.5 (user)",
    "sfdx-cli 7.193.2 (core)",
    "sfdx-git-delta 5.13.3 (user)"
  ]
}

**Comment by peternhale** [comment]
Issue fixed in PR [fix: add strict null checks](https://github.com/forcedotcom/packaging/pull/259)

**Comment by thomasminney** [comment]
Thank you @peternhale, which release will have this fix?

**Comment by peternhale** [comment]
@thomasminney should be in this week's latest-rc.
