### ISSUE TITLE
Sandbox definition file to support Sandbox Access group

### ISSUE THREAD

**Issue by thomasminney** [forcedotcom/cli#2027]
Spring '23 has a new feature where group id can be specified to provide sandbox access to a subset of users.

https://help.salesforce.com/s/articleView?id=sf.data_sandbox_selective_access.htm&type=5

This group id can be specified by field `ActivationUserGroupId` on [SandboxInfo](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_sandboxinfo.htm) object.

Can the sandbox definition file used by `org create sandbox` command support setting this field?

**Comment by mshanemc** [comment]
That link looks broken--did that feature get pulled back or not ship?

**Comment by thomasminney** [comment]
Salesforce have confirmed this release item was pulled back.
