### ISSUE TITLE
sf org assign permset doesn't work with multiple permission sets

### ISSUE THREAD

**Issue by ClayChipps** [forcedotcom/cli#2029]
### Summary

If you provide multiple permission set names to sf org assign permset, the command fails as it tries to treat the comma delimited list as a single permission set name.

The issue is caused because the new sf org assign permset command does not use an array as the input type for the name flag. Whereas the "legacy" force command uses an array.

[force/user/permset/assign](https://github.com/salesforcecli/plugin-user/blob/aa8ddc7293b905390f6f588cdaa3b985154d690b/src/commands/force/user/permset/assign.ts#L22)

[org/assign/permset](https://github.com/salesforcecli/plugin-user/blob/main/src/commands/org/assign/permset.ts#L21)

### Steps To Reproduce:

1. sf org assign permset --name "PermissionSetName1,PermissionSetName2"

### Expected result

The command works.

### Actual result

Permission set "PermissionSetName1,PermissionSetName2" not found in target org. Do you need to push source?

### System Information

- bash

- sfdx output

$ sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.193.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.14.2",
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\BCCA1JV\\AppData\\Local\\Programs\\node-v18.14.2-win-x64\\node_modules\\sfdx-cli",
  "pluginVersions": [
    "@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.4 (user)",
    "@mshanemc/plugin-streaming 1.1.7 (user)",
    "@mshanemc/sfdx-sosl 1.1.0 (user)",
    "@oclif/plugin-autocomplete 2.1.5 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.2 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.7 (core)",
    "@oclif/plugin-version 1.3.0 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.31 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "apex 2.2.5 (core)",
    "auth 2.7.8 (core)",
    "community 2.2.5 (core)",
    "custom-metadata 2.1.7 (core)",
    "data 2.3.6 (core)",
    "info 2.6.0 (core)",
    "limits 2.3.8 (core)",
    "org 2.5.0 (core)",
    "packaging 1.16.2 (core)",
    "schema 2.3.3 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.7 (core)",
    "source 2.8.0 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.4 (core)",
    "user 2.3.5 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@steampunk/sfdx-steampunk-package 0.2.3 (user)",
    "sfdmu 4.23.10 (user)",
    "sfdx-cli 7.193.2 (core)",
    "shane-sfdx-plugins 4.43.0 (user)"
  ]
}

- sf output

$ sf version --verbose --json
{
  "cliVersion": "@salesforce/cli/1.67.1",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.14.2",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.2 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.5 (core)",
    "@oclif/plugin-not-found 2.3.20 (core)",
    "@oclif/plugin-plugins 2.3.2 (core)",
    "@oclif/plugin-search 0.0.13 (core)",
    "@oclif/plugin-update 3.1.5 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.28 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "apex 2.2.0 (core)",
    "auth 2.7.1 (core)",
    "data 2.3.1 (core)",
    "deploy-retrieve 1.8.1 (core)",
    "env 2.1.0 (core)",
    "functions 1.21.0 (core)",
    "info 2.4.4 (core)",
    "limits 2.3.5 (core)",
    "login 1.2.0 (core)",
    "org 2.4.2 (core)",
    "schema 2.3.1 (core)",
    "settings 1.3.0 (core)",
    "sobject 0.1.4 (core)",
    "telemetry 2.1.1 (core)",
    "templates 55.4.1 (core)",
    "trust 2.4.2 (core)",
    "user 2.3.2 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\BCCA1JV\\AppData\\Local\\Programs\\node-v18.14.2-win-x64\\node_modules\\@salesforce\\cli"
}

**Comment by jshackell-sfdc** [comment]
This should work:

  sf org assign permset --name PermissionSetName1 --name PermissionSetName2

The example is incorrect, I will update it soon.  I'll also add a brief note to the --help description to explain this change in how you specify multiple values to the --name flag.

**Comment by ClayChipps** [comment]
Thanks @jshackell-sfdc! You probably also want to have the docs updated here as well: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_org_commands_unified.htm#cli_reference_org_assign_permset_unified

**Comment by WillieRuemmele** [comment]
Hi @ctchipps - thanks for bringing this to our attention, we've fixed it and the updated help is availble in the `latest-rc` version

**Comment by pgonzaleznetwork** [comment]
This seems like a "functional" regression to me. If you have any scripts passing an array of perm sets to the old command, and simply replace the old command with the new one, the script will not work.

Are you able to share any info on why this change was made?

**Comment by mshanemc** [comment]
@pgonzaleznetwork where commands have just been renamed, we're providing backward compatibility for the old flag behavior so that switching to the new one "just works"

For other commands where we have a new and old version that both co-exist, we're using the "new" way of doing things.  

Why are there 2 commands for permset assignment?  There was already a breaking change because the new command uses `-o` for the `target-org` (to be consistent with everything else) and the old one had `-o` for the `on-behalf-of` flag.
