### ISSUE TITLE
No Grace Period for deprecation of Scratch org settings

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#203]
### Summary

With the latest CLI release, deprecated settings under orgPreferenceSettings are gone overnight with no warning or grace period even though they still work in older CLI versions. Some of these settings now orphan org features that are required by code/config but can only be set in the UI now.

Warning should be provided but setting should be honored until it is officially deprecated in Summer 20

### Steps To Reproduce:

1.  Create a scratch def with an important but deprecated setting such as analyticsSharingEnable
{
  "orgName": "Folder Sharing Org",
  "edition": "Enterprise",
  "settings": {
    "orgPreferenceSettings" : {
        "analyticsSharingEnable": true
    }
  }
}

1.  Create an org using it

### Expected result

Scratch org is created with Enhanced Folder Sharing enabled

### Actual result

Scratch org is created with Enhanced Folder Sharing disabled even though the setting is not set to be removed until Summer 20 and there was no previous warning that it was going away.

Pushing codebase to this scratch org will fail due to Enhanced Folder sharing changing available User Permissions in the org

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.28.7-7bceba6f24 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.17.0 (46.17.0)
├─ force-language-services 46.24.0
└─ salesforce-alm 46.22.0

sfdx-cli 7.28.7 (core)

**OS and version**: macOS 10.15.0

**Comment by kfidelak94** [comment]
We will be releasing a fix for this shortly.  I will post back here when I know more concretely when the fix will be available.

**Comment by nbatterham** [comment]
@kfidelak94 - any updates?

**Comment by yippie** [comment]
Yes, the update is the legacy folder sharing is finally, truly, dying and we won’t have to worry about this anymore


https://releasenotes.docs.salesforce.com/en-us/summer20/release-notes/rn_rd_legacy_folder_sharing_retirement.htm
