### ISSUE TITLE
force:source:pull says "Loading source tracking information..." and stops

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/cli#2030]
### Summary

When I run the `sfdx force:source:pull -u myusername --loglevel=debug`command, I get a message saying `Loading source tracking information...`and nothing else

### Steps To Reproduce:

This is only reproduced on out old production org of 2011.

1.  sfdx force:source:pull -u myusername --loglevel=debug
1.  Notice the info message and nothing else
2. Notice that the command has finished

### Expected result

I expected the source to be pulled, or a more explicit warning or error message be displayed.

### Actual result

Nothing is pulled.
An information message is displayed, letting the user think that he needs to wait, but the command stops (with no error message).
The `--loglevel=debug`option provides no extra information.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
zsh

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
{
  "cliVersion": "sfdx-cli/7.193.2",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.14.2",
  "osVersion": "Darwin 20.6.0",
  "shell": "zsh",
  "rootPath": "/Users/rupert/.local/share/sfdx/client/7.193.2-380b8be",
  "pluginVersions": [
    "@mshanemc/plugin-streaming 1.1.7 (user)",
    "@mshanemc/sfdx-sosl 1.1.0 (user)",
    "@oclif/plugin-autocomplete 2.1.5 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.2 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.7 (core)",
    "@oclif/plugin-version 1.3.0 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.31 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "@salesforce/lwc-dev-server 2.11.0 (user)",
    "apex 2.2.5 (core)",
    "auth 2.7.8 (core)",
    "community 2.2.5 (core)",
    "custom-metadata 2.1.7 (core)",
    "data 2.3.6 (core)",
    "info 2.6.0 (core)",
    "limits 2.3.8 (core)",
    "org 2.5.0 (core)",
    "packaging 1.16.2 (core)",
    "schema 2.3.3 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.7 (core)",
    "source 2.8.0 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.4 (core)",
    "user 2.3.5 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "security-plugins 0.0.0 (user)",
    "sfdmu 4.26.10 (user)",
    "sfdx-cli 7.193.2 (core)",
    "sfdx-git-delta 5.13.3 (user)",
    "sfpowerkit 6.1.0 (user)",
    "shane-sfdx-plugins 4.43.0 (user)"
  ]
}
### Additional information

_Feel free to attach a screenshot_.

**Comment by WillieRuemmele** [comment]
Hi @RupertBarrow - I'm assuming that there's changes in the org that you're expecting to be pulled down? Even if there's no changes, it should still print a message saying so...

you might explore the `project reset tracking` or `project clear tracking`

Is this consistently happening? or just the one time? The next steps would be understanding the steps to reproduce it
