### ISSUE TITLE
Parse error in file unknown on line 13 2e4f8e82e0dfe29a" } } when doing sfdx org list

### ISSUE THREAD

**Issue by riadhmankai** [forcedotcom/cli#2031]
### Summary

Calling sfdx org list from the Mac OS terminal results in the following error: Parse error in file unknown on line 13
2e4f8e82e0dfe29a"
}
}
### Steps To Reproduce:

type sfdx org list in the Mac os terminal

### Expected result

The list of orgs and scratch orgs that the current user is connected to

### Actual result

Error message:
Parse error in file unknown on line 13
2e4f8e82e0dfe29a"
}
}

I tried everything: a complete removal of sfdx from my system (including cache folder), reinstallation from the package, then tried installation via NodeJS. Nothing worked, kept having the same error over and over again.

### System Information

{
  "cliVersion": "sfdx-cli/7.194.1",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/usr/local/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.6 (core)",
    "@oclif/plugin-commands 2.2.11 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.3 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.8 (core)",
    "@oclif/plugin-version 1.3.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.32 (core)",
    "@oclif/plugin-which 2.2.17 (core)",
    "apex 2.2.7 (core)",
    "auth 2.7.10 (core)",
    "community 2.2.8 (core)",
    "custom-metadata 2.1.9 (core)",
    "data 2.3.8 (core)",
    "info 2.6.2 (core)",
    "limits 2.3.9 (core)",
    "org 2.6.2 (core)",
    "packaging 1.16.2 (core)",
    "schema 2.3.4 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.8 (core)",
    "source 2.8.0 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.5 (core)",
    "user 2.3.5 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "sfdx-cli 7.194.1 (core)"
  ]
}

**Comment by cristiand391** [comment]
Hi @riadhmankai!
Sometimes config/auth JSON files get corrupted and causes these type of  errors when the CLI tries to parse them.
We have some plans to include diagnostics test for the `sfdx doctor` command to show the bad files, but for now you will need to do that manually, here are a few options:

1) Check which JSON file is bad:
You can use the debug env var to show which files are being parsed by the CLI:
```
DEBUG=*sf:Config* sfdx org list
  sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +0ms
  sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +5ms
  sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +9ms
  sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +41ms
  sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +71ms
```

You might see different files, manually open them in your editor and check that they contain valid JSON.

2) Nuke all config/auth files
You can just delete the folders where these files are stored, one downside is that you'll have to auth again (might be an issue if you have a bunch of orgs).
```
rm -rf ~/.sf
rm -rf ~/.sfdx
```

**Comment by riadhmankai** [comment]
> Hi @riadhmankai! Sometimes config/auth JSON files get corrupted and causes these type of errors when the CLI tries to parse them. We have some plans to include diagnostics test for the `sfdx doctor` command to show the bad files, but for now you will need to do that manually, here are a few options:
> 
> 1. Check which JSON file is bad:
>    You can use the debug env var to show which files are being parsed by the CLI:
> 
> ```
> DEBUG=*sf:Config* sfdx org list
>   sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +0ms
>   sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +5ms
>   sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +9ms
>   sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +41ms
>   sf:Config INFO Reading config file: /Users/cdominguez/.sf/config.json +71ms
> ```
> 
> You might see different files, manually open them in your editor and check that they contain valid JSON.
> 
> 2. Nuke all config/auth files
>    You can just delete the folders where these files are stored, one downside is that you'll have to auth again (might be an issue if you have a bunch of orgs).
> 
> ```
> rm -rf ~/.sf
> rm -rf ~/.sfdx
> ```

Thanks! The DEBUG=*sf:Config* sfdx org list didn't reveal the exact file causing the issue, it just says: Parse error in file unknown on line 13 2e4f8e82e0dfe29a"}}. However, deleting all config/auth file worked, with the acceptable side effect of losing all active connections. So solved - thanks!

**Comment by cristiand391** [comment]
@riadhmankai glad it got solved!
We got a few reports about similar errors caused by corrupted config files last week too and we're thinking about adding a diagnostic test for this so that  users can run `sfdx doctor` and see which json files are causing trouble instead of removing all files.
