### ISSUE TITLE
SFDX: deloy to org keeps on loading.. Not showing any error. It was working perfectly till last week friday

### ISSUE THREAD

**Issue by vishalkumar413** [forcedotcom/cli#2033]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened_.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here
### Additional information

_Feel free to attach a screenshot_.

**Comment by WillieRuemmele** [comment]
Hi @vishalkumar413 can you please fill out the required information?
