### ISSUE TITLE
package:version:create fails when reports have subfolders

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#2039]
creating a new issue to represent the residual part of https://github.com/forcedotcom/cli/issues/367.

`sfdx force:package:version:create` fails with error `Entity Report and member ManagementLevelReports/PeopleDashboardReports did not resolve to an id while serializing Released Entity State` where there are report subfolders.

**Comment by shetzel** [comment]
I followed the steps of #367 and created a package version that includes the report folders and subfolders without errors.  My report structure within the Dreamhouse-lwc sample app looked like this:
![Screenshot 2024-02-01 at 2 05 06 PM](https://github.com/forcedotcom/cli/assets/2703995/af651606-762a-4bcf-afb2-47ecd13c6447)

I command I ran was: `sf package version create -x -p DreamhouseLWC -w 10 --skip-validation`

**Comment by sawuapara** [comment]
@shetzel If you --skip-validation the error does not occur but if you omit --skip-validation you will see the error.

sf Version: 2.78.3
packaging 2.9.17

**Comment by WillieRuemmele** [comment]
hi @sawuapara - 

using 2.79.4 / packaging 2.10.1 I was able to create a package + package version with nested folders. 

using the hidden `--preserve` flag on `package version create` I was able to confirm the metadata was in the correct format.

if you're still seeing this error, open a case with support. This will be a packaging server-side bug at that point
