### ISSUE TITLE
ERROR running force:source:deploy:  this.isRestDeploy is not a function

### ISSUE THREAD

**Issue by JodieM** [forcedotcom/cli#204]
### Summary

I've just updated CLI to the latest version, upgraded all my DX extensions, and tried a simple deploy. I've done this previously many times with no issue. 

After I've done the validation step, trying to deploy the JobID produces the error

ERROR running force:source:deploy:  this.isRestDeploy is not a function

### Steps To Reproduce:

1.  use sfdx force:source:deploy --checkonly --sourcepath force-app --targetusername mysandboxorg --testlevel RunLocalTests
1. After that runs successfully use force:source:deploy --targetusername mysandboxorg --validateddeployrequestid 0Af5D00000ONSJhSAP
1.  The error occurs immediately

### Expected result

The deployment should have completed.

### Actual result

Error received
ERROR running force:source:deploy:  this.isRestDeploy is not a function

### Additional information
**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.28.7-7bceba6f24 win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 47.1.5 (core)
├─ force-language-services 47.5.0 (core)
└─ salesforce-alm 47.4.0 (core)

sfdx-cli 7.28.7 (core)
sfdx-migration-automatic 1.5.0
shane-sfdx-plugins 4.8.2

**OS and version**:
Windows 10 Pro
10.0.18362

I have a work-around to Quick Deploy the job in the Org, but it would be great for this to continue working.

**Comment by clairebianchi** [comment]
Hi @JodieM, we have an internal work item (W-6803187) that is currently being worked on. I am closing this issue here and the fix should go out next week

**Comment by SaoBiz** [comment]
@clairebianchi is there currently a work around for this?

I am setting up a CI environment for our deployments and this is currently a blocker for us. I have set it up the same as described but instead of using `force:source:deploy` I am using `force:mdapi:deploy` and getting the same error.

OS: Windows Server 2008
Install method: exe

**Comment by clairebianchi** [comment]
@SaoBiz you should be able to do a regular deploy instead of a validated deploy. Otherwise, you can go to the UI and select the quick deploy option in the deployment UI page if you would rather do a Validate and then deploy.

This fix is going into this Thursday's CLI release.
