### ISSUE TITLE
[MDAPI:DEPLOY:REPORT][7.195.2] Error when asking for deploy status/report

### ISSUE THREAD

**Issue by arafesthain** [forcedotcom/cli#2042]
### Summary

[MDAPI:DEPLOY:REPORT] Error when asking for deploy status/report

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Launch a deployment and get the deploy id
1.  Retrieve deployment status with : `sfdx force:mdapi:deploy:report -i ${DEPLOYMENT_ID} --json -u $ORG_ALIAS`

### Expected result
Get the deployment status in json as usual

### Actual result

```
{
  "code": 1,
  "message": "Cannot read properties of undefined (reading 'minutes')",
  "name": "TypeError",
  "status": 1,
  "stack": "TypeError: Cannot read properties of undefined (reading 'minutes')\n    at Report.doReport (/opt/hostedtoolcache/node/18.15.0/x64/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-source/lib/commands/force/mdapi/deploy/report.js:34:39)\n    at Report.run (/opt/hostedtoolcache/node/18.15.0/x64/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-source/lib/commands/force/mdapi/deploy/report.js:25:20)\n    at async Report._run (/opt/hostedtoolcache/node/18.15.0/x64/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:108:22)\n    at async Config.runCommand (/opt/hostedtoolcache/node/18.15.0/x64/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:328:25)\n    at async run (/opt/hostedtoolcache/node/18.15.0/x64/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/main.js:89:16)",
  "exitCode": 1,
  "warnings": [
    "We plan to deprecate this command in the future. Try using the \"project deploy report\" command instead.",
    "The \"-u\" flag has been deprecated. Use \"--target-org | -o\" instead."
  ]
}

```

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
Bash

- If you are using `sfdx`
```
Node version : 
+ echo 'Node version : '
+ node --version
v18.15.0
+ echo 'Npm version : '
+ npm --version
Npm version : 
9.5.0
+ SFDX_CLI_VERSION=sfdx-cli@latest
+ npm install sfdx-cli@latest --global

added 955 packages in 18s

81 packages are looking for funding
  run `npm fund` for details
+ echo 'sfdx version: :'
+ sfdx --version
sfdx version: :
sfdx-cli/7.195.2 linux-x64 node-v18.15.0

```
- Paste the output here
### Additional information

No error in version 7.194.1

![image](https://user-images.githubusercontent.com/13768869/230575577-8e60540d-e405-47b2-b6b4-ec84e9accbb0.png)

**Comment by thomasminney** [comment]
Facing same error on 7.195.2

**Comment by adrianioana** [comment]
Facing a similar error while running 

**sfdx project deploy report --job-id myJobId --coverage-formatters text** 

Error (1): Cannot read properties of undefined (reading 'apiVersion')

SFDX runs on version
sfdx-cli/7.195.2 linux-x64 node-v18.12.1
GIT runs on version
git version 2.40.0

**Comment by mshanemc** [comment]
@adrianioana I made that a separate issue.  https://github.com/forcedotcom/cli/issues/2046

**Comment by WillieRuemmele** [comment]
Hi @adrianioana - this was released as part of a patch to the `latest-rc` tag... it'll be available under `latest` on Thursday
