### ISSUE TITLE
ERROR running force:source:pull:  Entity of type 'CustomApplication' named 'Opportunity' cannot be found

### ISSUE THREAD

**Issue by matcadg** [forcedotcom/cli#205]
### Summary

When New Record Lighting page is activated as Opportunity Org default on a scratch org, and Oppotunity.object file was not present in the source directoy this error is thrown upon source:pull command. ERROR running force:source:pull:  Entity of type 'CustomApplication' named 'Opportunity' cannot be found

### Steps To Reproduce:

1.  Create Lightning Record Page for Opportunity, assign as Org Default
1.  execute force:source:pull

### Expected result

Opportunity.object file created, with new lighting page as view action override. 

### Actual result

error ERROR running force:source:pull:  Entity of type 'CustomApplication' named 'Opportunity' cannot be found

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 27

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**: w10

**Comment by couchand** [comment]
Note the workaround suggested [here](https://salesforce.stackexchange.com/questions/281958/sfdx-forcesourcepull-entity-of-type-customapplication-named-case-cannot-be): just create the custom app that the CLI expects.  Go to Setup > Apps > App Manager, click New Lightning App, and create the app named (in this case) Opportunity.

**Comment by dcarroll** [comment]
A better way is to grab the id of the custom app using

`sfdx force:data:soql:query -q "Select Id, MemberName From SourceMember Where MemberType = 'CustomApplication'" -t`

Then delete the source member with

`fdx force:data:record:delete -s SourceMember -i <id retrieved above> -t`

**Comment by toddhalfpenny** [comment]
You can also add an entry to the forceignore.
The syntax is very confusing (IMO) and getting the correct case (as entries are case sensitive) is tricky. I _think_ this is what's needed;

`Opportunity.CustomApplication`

**Comment by a-v-w** [comment]
> Note the workaround suggested [here](https://salesforce.stackexchange.com/questions/281958/sfdx-forcesourcepull-entity-of-type-customapplication-named-case-cannot-be): just create the custom app that the CLI expects. Go to Setup > Apps > App Manager, click New Lightning App, and create the app named (in this case) Opportunity.

This worked great for me. You can also delete the created apps in your project folder then push back to the org and it will remove the created apps and the error will not reoccur on your next pull.

**Comment by umeditor** [comment]
The workaround also solved the problem for me. After pulling down the code, I deleted the new app in the UI and did another pull.

...I stand corrected. I still had to manually modify the metadata to get subsequent pushes to work.

**Comment by FabienTaillon** [comment]
You can also subscribe to the related [Known Issue](https://success.salesforce.com/issues_view?Id=a1p3A000001SjPn).

**Comment by pogilvie** [comment]
The only way I found to work around this was to create a new scratch org and push the working source to and NOT create an override lightning page in the scratch org.   I use DX for doing trailhead development for fun and practice so not a big deal.  My company is starting at DX pilot this month and I'm disappointed that this issue is taking so long to address.  I'm a DX advocate but this would have hit us hard.

**Comment by ninarosen** [comment]
What an annoying bug...
Thanks for sharing workarounds!
I hope the fix comes around quickly.

**Comment by jclark-dot-org** [comment]
I was able to workaround this issue with `.forceignore`, although it took some trial and error to find the right syntax.  `Opportunity.app` works, even though it should be `Opportunity.CustomApplication` based on the DX Dev docs.

**Comment by lsheerin** [comment]
Hi, Same SFDX GIT  topic/pull error but different in that I am getting an error on a report folder/report.  ERROR running force:source:pull:  "Entity type Report' named 'Communities_Reports_2_0/M_Member_Logins' cannot be found."   
I have validated that the report folder and report exist in my scratch org as well as in production.  This folder/report was installed as part of the appexchange Community 2.0 dashboard.
Any suggestions would be very much appreciated.

**Comment by mattmie** [comment]
The work around for updating .forceignore fixed the issue for me on removing the error from the pull however it does not accomplish the task of adding the change of the selected page to our source which has to be done manually.

If you want to fix the issue manually you can create the object file if it doesn't exist or update an existing file.

- In [folder-context]/main/default/objects/[object name] create a file named [object name].object-meta.xml if it doesn't exist; example Account.object-meta.xml.
- If that file exists check for <actionName>View</actionName> in <actionOverrides> section. If it exists edit the section to use the correct page. If it doesn't exist then add the <actionName>View</actionName> section from the below example editing as needed or use the example below when creating a new file and updating each tag as needed. The example has a page named Account_Record_Page.flexipage-meta.xml in the org.

**Example object meta-data file:**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
  <actionOverrides>
    <actionName>View</actionName>
    <comment>This is my override for the page for the Account object</comment>
    <content>Account_Record_Page</content>
    <formFactor>Large</formFactor>
    <skipRecordTypeSelect>false</skipRecordTypeSelect>
    <type>Flexipage</type>
  </actionOverrides>
</CustomObject>
```

**Comment by troveryor** [comment]
I just ran into this in a brand new scratch org with a single custom Lightning App added as a placeholder for new dev work.

 Spun up a new project and had the same problem with something named "AppBrand" of type "CustomApplication". 
 Added it to the .forceignore as "AppBrand.CustomApplication" to no effect, changed it to "AppBrand.app" did work however.

**Comment by AllanOricil** [comment]
I also have a Scratch Org with nothing else there. I created only one Lightning App and when I ran force:source:pull I got this error.

Starting SFDX: Pull Source from Default Scratch Org and Override Conflicts
 
11:52:41.801 sfdx force:source:pull --forceoverwrite
ERROR running force:source:pull:  Entity of type 'CustomApplication' named 'AppBrand' cannot be found
11:52:54.742 sfdx force:source:pull --forceoverwrite
 ended with exit code 1

@shetzel do you know if there is a work item for this?

**Comment by tenten0213** [comment]
@AllanOricil 

I was able to workaround this issue following.

1. https://github.com/forcedotcom/cli/issues/205#issuecomment-550504897
2. add `AppBrand.app` to `.forceignore`

**Comment by mshanemc** [comment]
I can't reproduce this anymore.  Please open a new issue if you can.
