### ISSUE TITLE
breaking json differences in source:push

### ISSUE THREAD

**Issue by WillieRuemmele** [forcedotcom/cli#2050]
<@WB4TF6RFY> — I am guessing that there is a gap between the output that VSCode Salesforce Extensions are expecting and what SFDX CLI v7.196.5 is giving.

When I save a file in VSCode, I have it set to push changes to scratch org.  When there is an issue and deploy fails, the VSCode output channel “Salesforce CLI” shows there is an error but it no longer gives me details.  I have revert to CLI directly to push source and see what the issue is.

Am I correct that this is on your team’s and the VSCode team’s radar??

[Slack Message](https://salesforce-external.slack.com/archives/C02R1NEG2G3/p1681150806893579?thread_ts=1681150806.893579&cid=C02R1NEG2G3)

**Comment by ImJohnMDaniel** [comment]
Definitely interested in this one.  😎

**Comment by WillieRuemmele** [comment]
https://github.com/salesforcecli/plugin-source/pull/811 

we're patching latest-rc right now, it should be available in nightlies already 😎
