### ISSUE TITLE
sfdx force:apex:test:run process can't be stopped with ctrl+c

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#2052]
### Summary

After running `sfdx force:apex:test:run` without specifying the list of tests I decided to stop the process, but something did not allow me to do it. Im pressing `ctrl+c` to exit the process and the terminal does not let me do it. 

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/55927613/231157919-57740a2d-b6c2-4840-8958-2fcdfa3f49e8.png">

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/55927613/231157944-62514dc9-b579-4ff1-85a3-628f28f4f391.png">

### Steps To Reproduce:

1 - run `sfdx force:apex:test:run -o TARGET_ORG -c -r human -d .`
2 - press `ctrl+c` to exit the process
3 - verify that something is not allowing the process to exit

### Expected result

pressing ctrl+c must exit the process.

obs: im not saying killing the process should stop the tests. I just want to regain control of my terminal.

### Actual result

pressing ctrl+c does not exit the process

### System Information

- Which shell/terminal are you using?  zsh

````json
{
  "cliVersion": "sfdx-cli/7.194.1",
  "architecture": "linux-x64",
  "nodeVersion": "node-v14.21.3",
  "osVersion": "Linux 5.10.0-21-cloud-amd64",
  "shell": "bash",
  "rootPath": "/home/admin/.nvm/versions/node/v14.21.3/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.6 (core)",
    "@oclif/plugin-commands 2.2.11 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.3 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.8 (core)",
    "@oclif/plugin-version 1.3.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.32 (core)",
    "@oclif/plugin-which 2.2.17 (core)",
    "apex 2.2.7 (core)",
    "auth 2.7.10 (core)",
    "community 2.2.8 (core)",
    "custom-metadata 2.1.9 (core)",
    "data 2.3.8 (core)",
    "info 2.6.2 (core)",
    "limits 2.3.9 (core)",
    "org 2.6.2 (core)",
    "packaging 1.16.2 (core)",
    "schema 2.3.4 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.8 (core)",
    "source 2.8.0 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.5 (core)",
    "user 2.3.5 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "sfdx-cli 7.194.1 (core)",
    "sfdx-git-delta 5.17.1 (user)"
  ]
}
````
### Additional information
 N/A

**Comment by WillieRuemmele** [comment]
Hey @AllanOricil thanks for bringing this up - we just reverted behavior on that command to run asynchronously by default, you can test with the `nightly` or `latest-rc` tag

hopefully this change nullifies this issue

**Comment by AllanOricil** [comment]
with: sfdx-cli/7.194.1 linux-x64 node-v14.21.3
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/55927613/231207794-ff44ef2b-2130-44ab-9ac3-bdca44fe5c0f.png">

with: sfdx-cli/7.197.3 linux-x64 node-v14.21.3
<img width="827" alt="image" src="https://user-images.githubusercontent.com/55927613/231223300-f84117b7-953d-4b28-9ee0-90d8dce962f1.png">

**Comment by WillieRuemmele** [comment]
```
 ➜  sfdx force apex test run -c -r human -d .
Warning: The "force apex test run" command has been deprecated. Use "apex run test" instead.
^CError (1): Cancelled


 ➜  sfdx -v                                  
sfdx-cli/7.196.6 darwin-arm64 node-v18.7.0
```

I was able to cancel it, were you?

**Comment by AllanOricil** [comment]
yes

<img width="832" alt="image" src="https://user-images.githubusercontent.com/55927613/231227641-c88bbb21-eade-4a2e-9765-9c154af9ac81.png">

**Comment by WillieRuemmele** [comment]
Cool - I'll close this issue

**Comment by AllanOricil** [comment]
when will u guys give me the "most valuable tester" trophy ? 🥺
