### ISSUE TITLE
project deploy shouldn't update tracking when deploy fails

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#2057]
`project deploy start` command

If you have a fresh scratch org and you deploy an entire packageDirectory’s contents but one of those files has an error, the deployment event fails.  That part is fine and expected.  But then, if you edit the single file (in my case, it was a perm set file) to correct the issue and save the file, the source tracking seems to get confused.  Because then when I try to execute the `project deploy start` command again, the source tracking wants to only push that one file that I edited and the deployment fails because none of the rest of the packageDirectory metadata was actually deployed on the previous attempt.  For some reason the source tracking believes that it was deployed.

**Comment by shetzel** [comment]
Fix is now in production

**Comment by ImJohnMDaniel** [comment]
Thanks for this one!!!  I appreciate it!  😎
