### ISSUE TITLE
generate CMDT records shows "Cannot find module 'bluebird'"

### ISSUE THREAD

**Issue by juergensens** [forcedotcom/cli#2058]
### Summary

Try to create records in a CMDT object with the command: `sf cmdt generate records --csv years.csv --type-name Year__mdt   `

### Steps To Reproduce:

1.  Create a custom metadata type object
1.  Create a csv file with one column header Name
1.  Follow help article command: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_cmdt_commands_unified.htm#cli_reference_cmdt_generate_record_unified

### Expected result

Creation of year values in a metadata type object named Year__mdt

### Actual result
Error message
ModuleLoadError: [MODULE_NOT_FOUND] require failed to load 
@salesforce\plugin-custom-metadata\lib\commands\cmdt\generate\records.js: Cannot find module 'bluebird'

### System Information
powershell

{
  "cliVersion": "@salesforce/cli/1.73.0",
  "architecture": "win32-x86",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\just2\\AppData\\Local\\sfdx\\client\\7.196.6-a969651\\sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.8 (core)",
    "@oclif/plugin-commands 2.2.13 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.4 (core)",
    "@oclif/plugin-search 0.0.15 (core)",
    "@oclif/plugin-update 3.1.9 (core)",
    "@oclif/plugin-version 1.3.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.33 (core)",
    "@oclif/plugin-which 2.2.18 (core)",
    "@salesforce/cli 1.73.0 (core)",
    "apex 2.2.9 (core)",
    "auth 2.7.11 (core)",
    "custom-metadata 2.1.11 (user)",
    "data 2.3.9 (core)",
    "deploy-retrieve 1.8.8 (core)",
    "info 2.6.4 (core)",
    "limits 2.3.12 (core)",
    "login 1.2.5 (core)",
    "org 2.6.5 (core)",
    "schema 2.3.6 (core)",
    "settings 1.4.3 (core)",
    "sobject 0.1.14 (core)",
    "source 2.9.1 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.5 (core)",
    "trust 2.4.6 (core)",
    "user 2.3.7 (core)"
  ]
}

**Comment by WillieRuemmele** [comment]
Hey @honestmondayJS 👋 

this sounds like a bug with our just-in-time installation code... 

can you try using `sfdx` which ships with this plugin by default?

**Comment by juergensens** [comment]
Hi @WillieRuemmele 
I got the same error with the command `sfdx force:cmdt:record:insert --csv years.csv --type-name Year__mdt`
