### ISSUE TITLE
`project deploy start` command throws error when there are no changes to deploy

### ISSUE THREAD

**Issue by vertexcs-suraj** [forcedotcom/cli#2061]
### Summary

When `project deploy start` is run on a source tracked or (source:push) it fails with a non-zero exit code when there are no changes to deploy. `force:source:push` doesn't throw an error when there are no changes to deploy, which seems like the correct behavior. I think it makes sense to throw error when a source path or metadata directory is specified and there are no changes to deploy, but not for `push`

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Push the code to a scratch org using `project deploy start`.
1.  Run the `project deploy start` command again

### Expected result

The message `no changes to deploy` should be displayed with a non-zero exit code.

### Actual result

An error is thrown with the message `No local changes to deploy`

### System Information

- bash in wsl2

- If you are using `sfdx`
```	{
  "cliVersion": "sfdx-cli/7.196.7",
  "architecture": "wsl-x64",
  "nodeVersion": "node-v19.7.0",
  "osVersion": "Linux 5.15.90.1-microsoft-standard-WSL2",
  "shell": "bash",
  "rootPath": "/home/suraj/.npm/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.8 (core)",
    "@oclif/plugin-commands 2.2.10 (user)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.4 (core)",
    "@oclif/plugin-search 0.0.15 (core)",
    "@oclif/plugin-update 3.1.9 (core)",
    "@oclif/plugin-version 1.3.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.33 (core)",
    "@oclif/plugin-which 2.2.18 (core)",
    "apex 2.2.10 (core)",
    "auth 2.7.11 (core)",
    "community 2.2.9 (core)",
    "custom-metadata 2.1.11 (core)",
    "data 2.3.9 (core)",
    "deploy-retrieve 1.8.10 (core)",
    "info 2.6.4 (core)",
    "limits 2.3.12 (core)",
    "org 2.6.12 (core)",
    "packaging 1.16.3 (core)",
    "schema 2.3.6 (core)",
    "settings 1.4.3 (core)",
    "signups 1.4.11 (core)",
    "sobject 0.1.4 (user)",
    "source 2.9.4 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.5 (core)",
    "trust 2.4.6 (core)",
    "user 2.3.7 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "@salesforce/sfdx-scanner 3.10.0 (user)",
    "queryAll 0.0.1 (link) /home/suraj/projects/cli-plugins/queryAll",
    "sfdmu 4.26.8 (user)",
    "sfdx-apex-typings-generator 3.0.1 (user)",
    "sfdx-cli 7.196.7 (core)"
  ]
}```

**Comment by mshanemc** [comment]
@vertexcs-suraj you're not the first person to comment on this...coming from `push` it's definitely different having these all in the same command.

What would you expect to happen for the same command if you provided a `-m CustomObject` or `-d force-app/main/defaul/classes` or `-x package.xml` and there was nothing to deploy?  Do those still feel like 0 or would that be a 1?

If 1, would you want only the "deploy changes like push" to return zero for empty deploys?
