### ISSUE TITLE
org-metadata-rest-deploy not taken into account

### ISSUE THREAD

**Issue by RenaudAM** [forcedotcom/cli#2062]
### Summary

Since version **7.195**, org-metadata-rest-deploy seems to no more take into account.
Works fine with 7.194.1, but with an higher version, all deployments use SOAP.

### Steps To Reproduce:

**Repository to reproduce:** Any

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Configure cli to use REST deploy with
`sf config set org-metadata-rest-deploy=true`
2.  Launch a deployment with 
`sfdx force:source:deploy -p force-app/ -u $ORG_ALIAS -l NoTestRun -w $WAIT_TIME`

### Expected result

Deployment using REST 

### Actual result

Deployment with SOAP

![image](https://user-images.githubusercontent.com/129757308/231986041-71104140-4bcf-4e16-bc7e-649ebb4892b9.png)

### System Information

- Which shell/terminal are you using? git bash

Works fine with version 7.194.1
I try all version higher than this one and the result is the same.

**Comment by WillieRuemmele** [comment]
Hey @RenaudAM thanks for reporting this - seems like there's bug in the `force source deploy` and the `project deploy start` commands. 

I'll look into this as soon as I can

**Comment by RenaudAM** [comment]
Hello, 

This issue reappear in version 2.2.7-3653112

**Comment by RenaudAM** [comment]
Hello, 
Sorry it still works on 2.27 for deploy but not for the retrieve.

**Comment by shetzel** [comment]
The metadata API does not support REST for retrieve, only SOAP.
