### ISSUE TITLE
Add --webhook flag to sfdx force:source:deploy when scheduling asynchronous deployment jobs

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#2068]
**Is your feature request related to a problem? Please describe.**

Currently CI/CD pipelines spend unecessary computing time and memory while pulling the status of  deployment job. Since the build and test process happens inside salesforce, there is no need to keep a whole Node process alive waiting for this job to finish. These resources could be released so that they can be used by other important jobs.

example: 14min doing nothing but consuming resources in the host machine.
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/55927613/234892328-b6e63e49-f056-4920-9472-b7c01ae0143f.png">

**What are you trying to do**
After scheduling a deployment job inside a salesforce instance, I want to release cpu and memory, and restart the workflow only when the job has finished. I don't want to keep a process alive pulling the job status.

**Describe the solution you'd like**
This could be achieved if there was a webhook service sending events to clients on every deployment job stage. Something similar to what github does

<img width="795" alt="image" src="https://user-images.githubusercontent.com/55927613/232227079-ca5f8b4f-96dd-4ffa-b67d-524abf53cc53.png">

With this service in place, you can then add a new flag called `--webhook` which would tell salesforce where to send these events to.
`sfdx force:source:deploy ... -w 0 --webhook $webhook` 

This feature could also enable serverless CICD pipelines for Salesforce.

AWS Step Functions are free when paused: https://stackoverflow.com/questions/58110826/aws-step-function-costing
Example of Step Functions that are paused while waiting for a response for a 3rd party service: https://catalog.workshops.aws/serverless-service-coordination/en-US/add-application-review/pausing-execution

**Describe alternatives you've considered**
There is no alternative. 

**Additional context**
NA

**Comment by AllanOricil** [comment]
This could also be added to the service and command that creates communities
https://github.com/forcedotcom/cli/issues/445

**Comment by jonathanwiesel** [comment]
Any news on this front?

**Comment by jonathanwiesel** [comment]
@AllanOricil according to the history of this issue it seems this was completed some time ago but no information regarding the features seems to exist, do you have some info to share to determine what is the future of this feature?

**Comment by AllanOricil** [comment]
@jonathanwiesel I have no idea. I think you have to ask those guys that maintain the repo. But I no longer think this is useful for CICD pipelines
