### ISSUE TITLE
Add ability to pragmatically refresh an org

### ISSUE THREAD

**Issue by SaoBiz** [forcedotcom/cli#207]
**Is your feature request related to a problem? Please describe.**
There is currently no way to (though I understand that the Org tooling that is built into the CLI is currently in BETA) refresh an org through the cli.

**What are you trying to do**
I am currently in the process of setting up our CI environment for our implementation of Salesforce, specifically, implementing a mechanism to run E2E tests. Due to the restrictions in place from one of the plugins we are using, constant creation and deletion of an org to run these tests with a fresh set of data will not work. (The plugin (paid) requires a key for each sandbox we want to use it on which sets up its initial configuration). Having the ability to refresh the org enables me to restore the org to a clean state before running E2E tests over it.

**Describe the solution you'd like**
As I see it, there is 2 ways that this could be implments (from a CLI perspective):

1. Create a new command `force:org:refresh` that can be called with the org alias and trigger the refresh.

2. Add additional flags to the `force:org:clone` command to specify that rather than cloning a new org, that you want to refresh and existing one.

**Describe alternatives you've considered**
The alternative to the refresh appraoch for my specific situation is that I could do the following:

1. Create a clone of my pristine data org
2. Once cloning is complete, pull down (using `force:mdapi:retrieve`) the required connected apps.

  The conencted apps are required as they are set up so that the automation framework and log into the system as different users because all users get their emails appended with `.invalid`. Thus making it impossible without some manual intervention, to log into the sandbox through the automation framework we are using.

  Those activities look like:

  - Reset all users emails to a common email
  - Attempt to log in, but be presented with 2FA screen to verify login (this is an email sent to the user)
  - Someone would have to retrieve this verification code and pass it to the Automation Framework some how (Main problem)
  - Continue with tests

  This approach is not ideal as we want to automate the whole process and have the E2E tests running on some schedule (might be a nightly run)

3. Run E2E tests using clientids of conntected apps to bypass the login screen (`frontdoor.jsp`)
4. Once all E2E tests are complete, delete the org

I just see this approach of constantly creating and deleting orgs as extra overhead as we would have to keep track of what orgs we have created.

**Additional context**
N/A

**Comment by clairebianchi** [comment]
@rrmehta2, looks like a feature request for your team

**Comment by SaoBiz** [comment]
@clairebianchi Can I ask how this is a feature request for my team when we have no control over how the CLI works?

The ability that I am requesting is to be able to refresh an org through the CLI and I have provided my use case for it. If this is not the right place to make such a request, can you please direct me to where I can raise this request?

**Comment by clairebianchi** [comment]
Sorry, I think I confused you @SaoBiz. This is a feature request for @rrmehta2, who is the product manager for Scratch Orgs. His team owns the commands that are associated with scratch orgs I was passing the information on to him.
