### ISSUE TITLE
SFDX replacements: not able to replace with blank value

### ISSUE THREAD

**Issue by benben-user** [forcedotcom/cli#2070]
Im using the replacements feature, all work as expected only issue i cannot replace some text with blank value.

My use case is to replace NameSpace prefix with blank in order to deploy my code to another environment that do not have NameSpace  . 

Here is an example : 
```
"replacements": [
    {
      "filename": "/force-app/main/default/classes/myHelper.cls",
      "stringToReplace": "myNS__",
      "replaceWithEnv": "BLANK"
    }
  ]
```
.env 
`BLANK =`

My cli commend is 
`dotenv -e .env sfdx force source push `

which results with :
```
 Component conversion failed: "BLANK" is in sfdx-project.json as a value for "replaceWithEnv" property, but it's not set in your environment.
```

**Comment by mshanemc** [comment]
oh, interesting.  Would an empty string `''` work?

**Comment by pgonzaleznetwork** [comment]
@mshanemc I'm not the OP but I can confirm this works with a string that contains a space, like this

`export HAPPY_SOUP_URL='  '`

However, if it's a real entry empty string, like this

`export HAPPY_SOUP_URL=' '`

The command fails with

`Error (1): Component conversion failed: "HAPPY_SOUP_URL" is in sfdx-project.json as a value for "replaceWithEnv" property, but it's not set in your environment.`

**Comment by benben-user** [comment]
> oh, interesting. Would an empty string `''` work?

Well not for my (Mac).
Also my use case is to replace NS__ so a space will not do the job. 
I guess we can use some CONSTE like `__BLANK__ `and the code (sfdx) will use "" as the replacement and not consider that as an empty env parameter

**Comment by mshanemc** [comment]
ugh.  The downside of changing this would be making it hard to detect the very real mistake of missing envs, which seems backward.

The "cleanest" thing might be to have a new json prop in the `replacements` to make it clear you want to **remove** the matched value.

**Comment by shetzel** [comment]
I'm on a mac using zsh and both of these worked for me in replacements:
1. `export BLANK=''` (empty string)
2. `export BLANK=` (pretty sure zsh also sets this to an empty string)

Maybe this is specific to the shell?  Regardless, the fix will resolve an env var that is not found as an empty string (when explicitly set in the replacements section)

**Comment by shetzel** [comment]
This is now in the latest CLIs: sfdx 7.208.10 / sf 1.85.8
