### ISSUE TITLE
Use a command or script to upgrade old sfdc commands

### ISSUE THREAD

**Issue by jairzh** [forcedotcom/cli#2071]
**Is your feature request related to a problem? Please describe.**
Yes, Salesforce is deprecating a lot of old commands which are causing inconvenience to users who have been using them for a long time. These users need a way to upgrade their old commands to new ones easily.

**What are you trying to do**
I want Salesforce to provide a command or bash script that can help me upgrade my old commands to new ones easily.

**Describe the solution you'd like**
I would like Salesforce to provide a command or bash script that can help me upgrade my old commands to new ones easily. The script should be able to identify the old command and suggest the corresponding new command. It should also provide instructions on how to use the new command.

**Describe alternatives you've considered**
I have not considered any alternatives as I believe this is the most efficient and effective solution.

**Additional context**
None.

**Comment by WillieRuemmele** [comment]
Hey @jairzh - this work has already been planned and is at the top of our priority list - just to reaffirm, the "deprecated" commands will continue to exist, and work for a long time. We appreciate your urgency in migrating, but also understand that there is no deadline yet, and we'll provide a command to help migrate scripts
