### ISSUE TITLE
Using sfdx cmdt:record:insert creates an undefined field in generated record

### ISSUE THREAD

**Issue by sarahbrock** [forcedotcom/cli#2072]
When using sfdx cmdt:record:insert (or sfdx force:cmdt:record:insert or sfdx cmdt generate records) and processing a CSV. The generated customMetadata records always contain an undefined field whether the namecolumn parameter is used or not.

The Syntax used is:
sfdx force:cmdt:record:insert --filepath List.csv --typename Dashboard_ID --namecolumn Random_Value_Name__c

the csv has 2 columns  (attached), for Random_Value_Name__c and Position__c,  but the resulting xml is:

<?xml version="1.0" encoding="UTF-8"?>
<CustomMetadata xmlns="http://soap.sforce.com/2006/04/metadata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <label>aaa</label>
    <protected>false</protected>
    **<values>
        <field>undefined</field>
        <value xsi:type="xsd:string">undefined</value>
    </values>**
    <values>
        <field>Position__c</field>
        <value xsi:type="xsd:int">1</value>
    </values>
    <values>
        <field>Random_Value_Name__c</field>
        <value xsi:type="xsd:string">aaa</value>
    </values>
</CustomMetadata>

[List.csv](https://github.com/forcedotcom/cli/files/11250253/List.csv)

**Comment by WillieRuemmele** [comment]
Hey @sarahbrock - could you please fill out the bug template, and include version information from `sfdx version --verbose`

could you also include some steps on how to create this custom metadata type in the org, what fields are required, etc...

**Comment by WillieRuemmele** [comment]
https://github.com/forcedotcom/cli/issues/2074
