### ISSUE TITLE
regression: sfdx package1 version list output only contains first 2000 entries in most recent versions

### ISSUE THREAD

**Issue by OscarScholten** [forcedotcom/cli#2073]
### Summary

sfdx package1 version list output only contains first 2000 entries when you use a recent version of the CLI, older versions return more entries. Looks like the new implementation does not page over multiple pages if they are available.

### Steps To Reproduce:

It's easy to reproduce using our release org, happy to provide login access if necessary.

Install version 7.139 of the CLI, this results in 2534 results (first two lines are the column headers)
$ sfdx force:package1:version:list -u hr2day-dev | wc
   2536   18230  266559

Install version 7.191.3 of the CLI, this results in 2000 results
$ sfdx package1 version list -o hr2day-dev | wc
   2002   14494  224432

### Expected result

also using 7.193 and later you'd expect all results to be available

### Actual result

result is clipped to the first 2000 entries

### System Information

- Which shell/terminal are you using? gitbash

**Comment by OscarScholten** [comment]
Hi @mshanemc - just tried version 7.200.7, but unfortunately I have to report that the number of lines printed is still the same 2000 lines as when using version 7.191. Could you reopen this issue?

Happy to help debugging

**Comment by mshanemc** [comment]
We dug in and found that the tooling API will gack if you try to query PackageVersion with an OFFSET parameter ( to try to get records after 2000).  You can verify this via `sf data query -t `.  

I'm going to mark it as owned by the Packaging team, and cases are required to help them proritize.

**Comment by jshackell-sfdc** [comment]
This issue is fixed in version 2.28.6.
