### ISSUE TITLE
Scratch Org error for deployment

### ISSUE THREAD

**Issue by danico2104** [forcedotcom/cli#2075]
### Summary

Hello i am getting this error when i try to push some code to Salesforce scratch Org, i try both ways, using the CLI directly and using the CLI into the VSCode

Error here.
danielcardonao@DanielsMacBook2 bo-salesforce-cmr-bf-cl % sfdx force:source:push --targetusername test-gdqsutrhszfw@example.com -f
Pushing v57.0 metadata to test-gdqsutrhszfw@example.com using the v57.0 SOAP API
DEPLOY PROGRESS | ████████████████████████████████████████ | 3971/3971 Components
ERROR running force:source:push: Cannot read properties of null (reading 'split')
CLIError: timed out
at Object.error (/Users/danielcardonao/.local/share/sfdx/client/7.194.1-faa045e/node_modules/@oclif/core/lib/errors/index.js:27:15)
at /Users/danielcardonao/.local/share/sfdx/client/7.194.1-faa045e/node_modules/@oclif/core/lib/cli-ux/index.js:29:62
at async flush (/Users/danielcardonao/.local/share/sfdx/client/7.194.1-faa045e/node_modules/@oclif/core/lib/cli-ux/index.js:121:9) {
oclif: { exit: 2 },
code: undefined
}
Updating source tracking... ⣽

-------------------------------------------------------------------------------------------------
danielcardonao@DanielsMacBook2 bo-salesforce-cmr-bf-cl % sfdx force:source:push --targetusername test-gdqsutrhszfw@example.com -f
Pushing v57.0 metadata to test-gdqsutrhszfw@example.com using the v57.0 SOAP API
DEPLOY PROGRESS | ████████████████████████████████████████ | 3970/3970 Components

=== Component Failures [2]

Type Name Problem
───── ──────── ────────────────────────────────────────
Error CaseType Concurrent modification from setup pages
Error CaseType Concurrent modification from setup pages

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened_.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here
### Additional information

_Feel free to attach a screenshot_.

**Comment by WillieRuemmele** [comment]
Hi @danico2104, can you try updating your CLI to either the `latest` version?
Can you add the required information, such as `sfdx version --verbose`

if you can, add the `--dev-debug` flag to the command, and provide the stack trace

**Comment by danico2104** [comment]
Hello @WillieRuemmele , this is the actual version of the CLI
 CLI Version:
        sfdx-cli/7.194.1

 Architecture:
        darwin-x64

 Node Version:
        node-v18.15.0

 Plugin Version:
        @oclif/plugin-autocomplete 2.1.6 (core)
        @oclif/plugin-commands 2.2.11 (core)
        @oclif/plugin-help 5.2.8 (core)
        @oclif/plugin-not-found 2.3.22 (core)
        @oclif/plugin-plugins 2.4.3 (core)
        @oclif/plugin-search 0.0.14 (core)
        @oclif/plugin-update 3.1.8 (core)
        @oclif/plugin-version 1.3.1 (core)
        @oclif/plugin-warn-if-update-available 2.0.32 (core)
        @oclif/plugin-which 2.2.17 (core)
        apex 2.2.7 (core)
        auth 2.7.10 (core)
        community 2.2.8 (core)
        custom-metadata 2.1.9 (core)
        data 2.3.8 (core)
        info 2.6.2 (core)
        limits 2.3.9 (core)
        org 2.6.2 (core)
        packaging 1.16.2 (core)
        schema 2.3.4 (core)
        settings 1.4.2 (core)
        signups 1.4.8 (core)
        source 2.8.0 (core)
        telemetry 2.1.3 (core)
        templates 55.4.4 (core)
        trust 2.4.5 (core)
        user 2.3.5 (core)
        @salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
        sfdx-cli 7.194.1 (core)

 OS and Version:
        Darwin 21.6.0

 Shell:
        zsh

 Root Path:
        /Users/danielcardonao/.local/share/sfdx/client/7.194.1-faa045e

in order to put this to work i have used a macbookPro, btw i can see the error gets resolved using a previous version of the CLI (using the 7.142.1)
Also, attached you can see the error log that you request for, thanks in advance
[ErrorLog.log](https://github.com/forcedotcom/cli/files/11253928/ErrorLog.log)

**Comment by danico2104** [comment]
hello @WillieRuemmele do we have any luck here ? if you want i'm glad to jump in a call if needed to show you this error.

thanks in advance.

**Comment by WillieRuemmele** [comment]
Sorry @danico2104 -  I haven't had much time to look into this. Have you tried this on a newer version of the CLI? `7.196.9` is about to be promoted to latest today

**Comment by danico2104** [comment]
i just try updating during today and the error still remains. please let me know any aditional step that should i take.
