### ISSUE TITLE
Remove empty failure tag on successful test execution

### ISSUE THREAD

**Issue by roftone** [forcedotcom/cli#2076]
**Is your feature request related to a problem? Please describe.**
Yes, new deployment commands seems to have changed the junit xml format. Before, an empty failure tag was not present on the returned xml.

**What are you trying to do**
Run a mock deployment on a gitlab merge request.

**Describe the solution you'd like**
 Not have the test results be considered a failure.

**Describe alternatives you've considered**
Reverting to the previous sfdx commands.

**Additional context**

Before:
![image](https://user-images.githubusercontent.com/131013134/232555992-2a848edb-bcb3-43ae-9b14-0a78ce31bc18.png)

After:
![image](https://user-images.githubusercontent.com/131013134/232556276-72fe8074-dbfd-402c-80d1-747ac112c261.png)

**Comment by WillieRuemmele** [comment]
Hey @roftone 👋  thanks for reporting this,

can you provide some more information such as CLI version and command with flags that you're running, when did you first notice this change?

**Comment by roftone** [comment]
Yes,

sfdx-cli 7.196.8 (core)

The command is:
sfdx project deploy start $packageParams $postDestructiveParams --dry-run --wait 3600 --verbose --junit --results-dir ./tests/apex -l RunLocalTests --coverage-formatters json

I had tested the new commands locally and everything seemed fine. It was only today, when I pushed the pipeline change, that I noticed the change in the merge request test results and compared the generated junit files.

**Comment by WillieRuemmele** [comment]
great, and does it work correctly if you use `sfdx force source deploy`?

**Comment by WillieRuemmele** [comment]
^ more of a bug, but the WI has already been created

**Comment by roftone** [comment]
> great, and does it work correctly if you use `sfdx force source deploy`?

Yes, that's the command that we are using again.

**Comment by R0Wi** [comment]
https://github.com/salesforcecli/plugin-deploy-retrieve/pull/610 should fix this. Cheers.

**Comment by roftone** [comment]
> [salesforcecli/plugin-deploy-retrieve#610](https://github.com/salesforcecli/plugin-deploy-retrieve/pull/610) should fix this. Cheers.

Awesome, I'll test it as soon as it goes live.

**Comment by WillieRuemmele** [comment]
Thanks @R0Wi for the contribution 🏆 

I just merged this into `plugin-deploy-retrieve` which will be available in tonight's `nightly` build of the CLIs 🎉

**Comment by R0Wi** [comment]
Just tested the current nightly (https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/7.202.3/8fc437b/sfdx-v7.202.3-8fc437b-linux-x64.tar.xz) and the error seems to be gone.

**Comment by roftone** [comment]
@R0Wi 
Just tested the fix, works great. Thanks.
