### ISSUE TITLE
Regression in `force:source:push` failure JSON output; `status` is zero when `exitCode` is non-zero

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#2079]
I've had a few IC2 users reporting situations where `force:source:push` has actually failed but is being reported as successful by IC2. After digging in a bit, this seems to be because the JSON output now specifies a `status` value of `0` when `exitCode` is non-zero, e.g.:

```
{
    "status": 0,
    "name": "DeployFailed",
    "exitCode": 1,
    "commandName": "Push",
     ...
```

In the past, `status` has been reliably non-zero on failure. Is this an expected/intentional change? I can (and likely will) update IC2 to use all of the available information to determine success vs. failure, but `status` has been a reliable indicator pretty much all along until very recently, so my guess is that this is an unintentional/accidental regression.

**Comment by SCWells72** [comment]
Upon further inspection, it looks like this may actually be happening because `status` was removed from the response altogether and the value of `0` is the result of deserialization from JSON into a `status` property with a default value of `0`. Still a breaking change to the previous CLI-as-an-API contract, but perhaps a bit different from described above where it was assumed to be set explicitly to that value.

**Comment by SCWells72** [comment]
Confirmed that `status` has been removed from the failure response for `force:source:push`:
```
$ sfdx force:source:push --json
{
  "name": "DeployFailed",
  "actions": [],
  "exitCode": 1,
  "data": [
    ...
  ],
  "commandName": "Push",
  "warnings": [
    "We plan to deprecate this command in the future. Try using the \"project deploy start\" command instead.",
    "The \"-u\" flag has been deprecated. Use \"--target-org | -o\" instead."
  ]
}
```

**Comment by WillieRuemmele** [comment]
Hey @SCWells72 This is fixed in the `nightly` build of the CLI, I'm patching `latest-rc` now which will be promoted tomorrow, as you probably know. I'm also patching `latest` for today

Thanks again for reporting 😄

**Comment by WillieRuemmele** [comment]
This should be fixed in all channels of the CLI with `plugin-source@2.10.1`
