### ISSUE TITLE
Retrieving Versions of Entitlement Process

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#208]
### Summary

Pulling Entitlement Process with versions throws error.

Also when launching a sfdx force:source:status, shows the entitlement without the version.

### Steps To Reproduce:

1. Create a new Scratch Org
1.  Enable Entitlements and Entitlement Versioning
1. Create a new Entitlement Process
1. Try to pull changes with sfdx force:source:pull

### Expected result

Correct retrieve of the Entitlement Process with the version edited.

When launching a sfdx force:source:status, have the version added to the result

### Actual result

Doing a pull

```bash
$ sfdx force:source:pull  
ERROR running force:source:pull:  Entity of type 'EntitlementProcess' named 'test_entitlement' cannot be found
```

Doing a status

```bash
$ sfdx force:source:status
=== Source Status
STATE       FULL NAME          TYPE                PROJECT PATH
──────────  ────────────────  ───────────────────  ────────────
Remote Add  test_entitlement  EntitlementProcess
```

Doing a retrieve with the name that appears in the status

```bash
$ sfdx force:source:retrieve -m EntitlementProcess:test_entitlement
=== Retrieved Source
No results found
```

### Additional information

Entitlement Process can be ignored in the .forceignore if adding the fullname of the entitlement, like test_entitlement

Entitlement Process can be correctly retrieved using 

```shell
$ sfdx force:source:retrieve -m EntitlementProcess:{apiname}_v{versionNumber}
```

**SFDX CLI Version**: sfdx-cli/7.28.7-7bceba6f24 linux-x64 node-v10.15.3

**SFDX plugin Version**: 
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.16.0
├─ force-language-services 46.23.0
└─ salesforce-alm 46.21.0

sfdx-cli 7.28.7 (core)
sfpowerkit 1.20.1-3
**OS and version**: Ubuntu 18.04 WSL 1.0 on Windows 10

**Comment by clairebianchi** [comment]
@mnunezdm, are you using packaging? This metadata type requires a package without a namespace, if you are. 

This bug is owned by the team that builds the entitlement process, I will pass this on to that team. Thank you.

**Comment by leonardopmacedo** [comment]
Did we have a solution for this?

**Comment by mnunezdm** [comment]
Ignoring the entitlement procress in the forceignore is the only workaround I found

**Comment by leonardopmacedo** [comment]
Salesforce Team please focus on this resolution.

**Comment by leonardopmacedo** [comment]
> Ignoring the entitlement procress in the forceignore is the only workaround I found

How did I do this? Can you paste the line here, please? @mnunezdm

**Comment by mnunezdm** [comment]
@leonardopmacedo have you tried the **Additional Information** section in this issue?

**Comment by leonardopmacedo** [comment]
Yes, but I'm having trouble with the format of name... I need to put the file extension? for example:
force-app\main\default\entitlementProcesses\relacionamento com clientes - elogio - assistência técnica_v1.entitlementProcess-meta.xml

How would that look inside the forceignore in this scenario, for example?
Tks

**Comment by mnunezdm** [comment]
It's strange, Entitlement Process management using SFDX is terrible, I've manage to ignore the entitlement process only with exact matches in the api name

For example when entitlement versioning is not active, just adding the relative path works

```
force-app/main/default/entitlementProcesses/relacionamento com clientes - elogio - assistência técnica.entitlementProcess-meta.xml
``` 

When the versioning is active i've only manage to ignore it adding the version to the forceignore

```
force-app/main/default/entitlementProcesses/relacionamento com clientes - elogio - assistência técnica_v2.entitlementProcess-meta.xml
```

**Comment by leonardopmacedo** [comment]
@mnunezdm very much thanks!
