### ISSUE TITLE
Why do array flags behave differently in sf compared to sfdx? 

### ISSUE THREAD

**Issue by pgonzaleznetwork** [forcedotcom/cli#2083]
Apologies for not using the template, I have a question that is neither a bug nor a feature request.

The new `sf` CLI has a different syntax for passing lists of items to a flag, from the [official docs](https://github.com/salesforcecli/cli/wiki/Design-Your-Plugin)

> When creating a flag that accepts multiple values, design the flag so that users specify it multiple times rather than once with a comma-separated list of the values. For example, --metadata accepts multiple values and users run the command this way:
> 
> `sf deploy metadata --metadata ApexClass:MyClass --metadata ApexClass:MyOtherClass`
> 
> And not this way:
> 
> `sf deploy metadata --metadata ApexClass:MyClass,ApexClass:MyOtherClass`

The `sfdx` CLI allows for the 2nd syntax, for example, this works:

`sfdx force:source:retrieve -m "CustomObject,ApexClass"`

With the new CLI, the same command becomes

`sf project retrieve start --metadata CustomObject --metadata ApexClass`

Why was this changed introduced? This new syntax makes commands longer than they need to be, and makes it harder to port `sfdx` scripts to `sf` ones.

**Comment by shetzel** [comment]
It was a design decision to prefer individual assignment, matching the original behavior of oclif.  oclif now supports both patterns so plugin authors can choose to support multi-value params either way.

**Comment by pgonzaleznetwork** [comment]
@shetzel thanks, in that case, shouldn't the docs I mentioned above be modified to state that bot behaviors are supported?  also, is there anything that needs to be configured at the flag level to specify which behavior to use?

**Comment by mshanemc** [comment]
I'm going to clarify this a bit.

For commands that we've renamed, we've hacked together a flag that works with commas like the old one (for backward compatibility) but encourages the new behavior.

For net new commands that are meant to be replacements, they have the new syntax and don't use commas. 

if you're looking for brevity, you *can* also use this format (spaces) on a "multiple" flag.   
```
sf deploy metadata --metadata ApexClass:MyClass ApexClass:MyOtherClass
```

Our docs and examples will use `--foo a --foo b`

This change came from `oclif`.  The previous "array" flag was really just a big string that was being split on the commas.  Then the command would be responsible for doing the various validations, parsing, on each item in the array.  It wasn't very easy to work with, and very mistake prone and several bugs came from it.

The new way of doing `multiple` flags lets them work like other flags
- validations/parse run on each item in the array
- you can say what the type should be

**Comment by pgonzaleznetwork** [comment]
Thanks a lot @mshanemc ! I still think there should be something in the docs about this behavior, a copy/paste of what you said would've prevented me from logging this issue :)
