### ISSUE TITLE
Socket timeout using SFDX

### ISSUE THREAD

**Issue by mwannamaker41** [forcedotcom/cli#2086]
After using SFDX on my mac via the pkg installer for years, we've decided to move to NPM version.  But after uninstalling and installing via NPM I now get socket timeout issues.

I am on a Mac with Apple Silicon (Mac Studio)

I had SFDX installed via the pkg installer for years with no issues.  I uninstalled via this link
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

Then I installed via npm
npm install sfdx-cli --global
npm install @salesforce/cli --global

I was at

sfdx-cli/7.196.9 darwin-arm64 node-v20.0.0
@salesforce/cli/1.74.7 darwin-arm64 node-v20.0.0

I did not reinstall any plugins that I might have had.

When I try to push, I get the following error even though when I go to the salesforce org, the deployment shows that it succeeded.

Here is the result:

{
  "name": "DeployFailed",
  "actions": [],
  "exitCode": 1,
  "data": [],
  "result": [],
  "commandName": "Push",
  "warnings": [
    "We plan to deprecate this command in the future. Try using the \"project deploy start\" command instead.",
    "The \"-u\" flag has been deprecated. Use \"--target-org | -o\" instead."
  ],
  "message": "Push Failed.",
  "stack": "DeployFailed: Push failed. \n    at PushResultFormatter.getJson (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-source/lib/formatters/source/pushResultFormatter.js:37:27)\n    at Push.catch (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-source/lib/commands/force/source/push.js:165:23)\n    at Push._run (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/command.js:112:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Config.runCommand (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/config/config.js:328:25)\n    at async run (/opt/homebrew/lib/node_modules/sfdx-cli/node_modules/@oclif/core/lib/main.js:89:16)",
  "context": "Push",
  "status": 1
}

 Attached is the output from push command with --dev-debug option

 
[pushlog.txt](https://github.com/forcedotcom/cli/files/11286315/pushlog.txt)

**Comment by mshanemc** [comment]
two things:
1. we've got a change that *should* help get the error message into the json output so you don't have to dig in the log files to get it.
2. I'll add the socket connection timeout to the list of things we retry.  Thanks for reporting!
