### ISSUE TITLE
SF: allow "project deploy start --metadata-dir" to be executed outside of an SFDX project

### ISSUE THREAD

**Issue by hudec117** [forcedotcom/cli#2089]
### Summary

The new `project deploy start` command (replacing `force:mdapi:deploy`) requires an SFDX project to deploy metadata in metadata format. The previous command did not have this requirement and the transition is causing difficulties with CI/CD since our directory structure does not conform to an SFDX project.

### Steps To Reproduce:

1. Create a folder `empty-package`
2. Create an empty `package.xml` in it:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>57.0</version>
</Package>
```

3. Go up a directory and execute `sf project deploy start -o username --metadata-dir empty-package`

### Expected result

No error and the metadata API deployment should have started.

### Actual result

`RequiresProjectError: This command is required to run from within a Salesforce project directory. Code: RequiresProjectError`

### System Information

- Which shell/terminal are you using?
bash

- If you are using `sf`
```json
{
  "cliVersion": "@salesforce/cli/1.73.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "C:\\Users\\aurel.hudec1\\AppData\\Local\\Programs\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Program Files\\sfdx\\client\\sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.8 (core)",
    "@oclif/plugin-commands 2.2.13 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.4 (core)",
    "@oclif/plugin-search 0.0.15 (core)",
    "@oclif/plugin-update 3.1.9 (core)",
    "@oclif/plugin-version 1.3.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.33 (core)",
    "@oclif/plugin-which 2.2.18 (core)",
    "@salesforce/cli 1.73.0 (core)",
    "apex 2.2.9 (core)",
    "auth 2.7.11 (core)",
    "data 2.3.9 (core)",
    "deploy-retrieve 1.8.8 (core)",
    "info 2.6.4 (core)",
    "limits 2.3.12 (core)",
    "login 1.2.5 (core)",
    "org 2.6.5 (core)",
    "schema 2.3.6 (core)",
    "settings 1.4.3 (core)",
    "sobject 0.1.14 (core)",
    "source 2.9.1 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.5 (core)",
    "trust 2.4.6 (core)",
    "user 2.3.7 (core)"
  ]
}
```

**Comment by gdman** [comment]
Same thing happens with retrieves in MD API format. Also, the error is returned as text even if using the --json flag.

**Comment by jarednielson** [comment]
Experiencing the same thing `sfdx force:mdapi:retrieve` works fine `sfdx project retrieve start` says it is required to be run from within a salesforce package.

```sh
 sfdx project retrieve start --source-dir deployment-packages/housekeeping/deployment-tracking/src --target-metadata-dir deployment-packages/housekeeping/deployment-tracking/src --unzip  --target-org=*****
    RequiresProjectError: This command is required to run from within a Salesforce project directory.
    Code: RequiresProjectError
```

Mac OS 13.2.1
sfdx-cli/7.198.7 darwin-x64 node-v18.15.0

**Comment by hudec117** [comment]
I see sf 1.79.0 was meant to fix this issue but after trying it, it's still not working:
![image](https://github.com/forcedotcom/cli/assets/10981949/d4708bc6-3398-4852-8663-5c7bc53ac0c9)

Mentioned here: https://github.com/forcedotcom/cli/blob/main/releasenotes/sf/README.md#1790-may-24-2023-stable

**Comment by mshanemc** [comment]
@hudec117 can you try with the current `sf` (that's 1.79.5) or current `sfdx`
