### ISSUE TITLE
apex:test:run fails on the format Namespace.TestClass

### ISSUE THREAD

**Issue by ajw725** [forcedotcom/cli#209]
### Summary

apex:test:run seems to allow several argument formats. You can just pass the name of a test class to run all tests in that class, or you can pass the name of a single test method like TestClass.testMethod. If you are trying to run a test from a namespace, you can do this like Namespace.TestClass.testMethod, which works fine.

The problem is if you try to run all tests in a class with a namespace:

```
08:07:01.609 sfdx force:apex:test:run --tests MyNS.MyTestClass --resultformat human --outputdir /Users/andrewweinstein/repos/my_project/.sfdx/tools/testresults/apex --loglevel error
ERROR running force:apex:test:run:  Unable to invoke any tests. Ensure the tests are loaded into the org or valid inputs are supplied. This class name's value is invalid: MyNS.MyNS. Provide the name of an Apex class that has test methods.
```

This happens both in a namespaced scratch org and in an org into which the MyNS package has been installed. In the scratch org, running the command like this instead (without the namespace) works fine:
```
sfdx force:apex:test:run --tests MyTestClass --resultformat human --outputdir /Users/andrewweinstein/repos/my_project/.sfdx/tools/testresults/apex --loglevel error
```
Running a single test with the namespace also works fine:
```
sfdx force:apex:test:run --tests MyNS.MyTestClass.myTestMethod --resultformat human --outputdir /Users/andrewweinstein/repos/my_project/.sfdx/tools/testresults/apex --loglevel error
```
And running a single test **without** the namespace also works fine:
```
sfdx force:apex:test:run --tests MyTestClass.myTestMethod --resultformat human --outputdir /Users/andrewweinstein/repos/my_project/.sfdx/tools/testresults/apex --loglevel error
```

So it seems like "MyNS.MyTestClass" is incorrectly interpreted as a class name + test method name instead of a namespace + class name. I realize the difficulty of accepting both of those formats, because you'd have to figure out whether the first argument is a namespace or a class name and whether the second is a class name or a method name, but it seems like inconsistent behavior if a command like `MyNS.MyClassName.myTestMethod` works correctly and `MyNS.MyClassName` doesn't.

### Steps To Reproduce:

1. Create a scratch org with a namespace.
1. Create an apex class in that namespace with a simple test method
1. Create an apex test class with a test method
1. Try to invoke force:apex:test:run with the namespace-prefixed name of the test class, like MyNS.MyTestClass (as seen above)

### Expected result

All tests in the class should run

### Actual result

The test class cannot be found

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.28.7-7bceba6f24 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.6
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.1.5 (core)
├─ force-language-services 47.5.0 (core)
└─ salesforce-alm 47.4.0 (core)
```

**OS and version**: macOS Mojave 10.14.6

**Comment by ajw725** [comment]
see also [https://github.com/forcedotcom/salesforcedx-vscode/issues/1358](https://github.com/forcedotcom/salesforcedx-vscode/issues/1358)

**Comment by clairebianchi** [comment]
@ntotten can you take a look at this?

**Comment by ajw725** [comment]
@clairebianchi from the issue i linked in the VS code repo, it sounds like they're on it. just wasn't sure where this belonged

**Comment by preddivari** [comment]
@ajw725 the issue on the VS code repo is closed. Just want to make sure this is no longer an issue for you before closing this. Can you please confirm? Thanks

**Comment by ajw725** [comment]
hi @preddivari - sorry, i'm not really in a position to test now, as i no longer work on the salesforce platform. all i can tell you is that it was apparently working for me as of this comment: https://github.com/forcedotcom/salesforcedx-vscode/issues/1358#issuecomment-548832803

so you can probably go ahead and close this issue.

**Comment by preddivari** [comment]
Thanks you for your response.

**Comment by preddivari** [comment]
Closing the issue
