### ISSUE TITLE
sf apex run test: --output-dir not taken into account

### ISSUE THREAD

**Issue by RenaudAM** [forcedotcom/cli#2090]
### Summary

Executing Apex tests with `sf apex run test` command doesn't produce anything if -`-output-dir` is specified.

### Steps To Reproduce:

**Repository to reproduce:** Any

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Execute command 
`sf apex run test --output-dir target`

### Expected result

Creation of a target repository with a test-run-id.txt file

### Actual result

Nothing

### System Information

- Which shell/terminal are you using? git bash

- If you are using `sf`
	- Run `sf version --verbose --json`
$ sf version --verbose --json
{
  "cliVersion": "@salesforce/cli/1.73.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19042",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\A0468184\\AppData\\Local\\sfdx\\client\\7.197.8-077a68b\\sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.8 (core)",
    "@oclif/plugin-commands 2.2.13 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.4 (core)",
    "@oclif/plugin-search 0.0.15 (core)",
    "@oclif/plugin-update 3.1.9 (core)",
    "@oclif/plugin-version 1.3.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.33 (core)",
    "@oclif/plugin-which 2.2.18 (core)",
    "@salesforce/cli 1.73.0 (core)",
    "apex 2.2.12 (user)",
    "auth 2.7.11 (core)",
    "data 2.3.9 (core)",
    "deploy-retrieve 1.8.8 (core)",
    "info 2.6.4 (core)",
    "limits 2.3.12 (core)",
    "login 1.2.5 (core)",
    "org 2.6.5 (core)",
    "schema 2.3.6 (core)",
    "settings 1.4.3 (core)",
    "sobject 0.1.14 (core)",
    "source 2.9.1 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.5 (core)",
    "trust 2.4.6 (core)",
    "user 2.3.7 (core)"
  ]
}

**Comment by shetzel** [comment]
@RenaudAM - I can't reproduce this when running the command synchronously.  E.g., `sf apex run test --output-dir target --wait 10`
Without using a `wait` parameter the command is run asynchronously and you won't get results until you request them with `sf apex get test`

**Comment by RenaudAM** [comment]
@shetzel sorry but in the past a text file containing the test run ID was generated even when test are run asynchronously. This test run ID can be use after to run the get test command in CI/CD process…this is no more the case.

**Comment by RenaudAM** [comment]
Hello

Any news on this issue? 
I try again this morning and have this result:
`$ sf apex run test --output-dir target`
`Run "sf apex get test -i 7071w00003VJ8tZ -o xxxxxx@xxxxx" to retrieve test results`
But no `target` dir create with a file containing the testID.
So my CI/CD job running the test classes can't work because I'm not able to retrieve the test ID to later launch the `sf apex get test` command.

**Comment by RenaudAM** [comment]
Hello

Still no news?
:(

**Comment by mshanemc** [comment]
duplicate #2321
