### ISSUE TITLE
Error when deploying a project with multiple RunSpecifiedTests classes

### ISSUE THREAD

**Issue by Orkhidion** [forcedotcom/cli#2097]
### Summary

When I using the command project deploy start with RunSpecifiedTests and having multiple test classes, the deployment is failing: 'Fatal error' code coverage at 0%.
But when we only specify one test class, it is working as expected.

### Steps To Reproduce:

**Repository to reproduce:** 
1. Run this command: sf project deploy start -d env-specific-default -d force-app-o dev -l RunSpecifiedTests -t "ClassA_TEST,ClassB_TEST" --ignore-conflicts
2. Check the deployment Result: it is falling: "Status: Failed"

### Expected result

The deployment should be OK.

### Actual result
The deployment is falling
_Cli Status:_
*** Deploying with SOAP API v57.0 ***
Deploy ID: 0Af1l000023MelnCAC
Status: Failed | ████████████████████████████████████████ | 757/757 Components

Test Results Summary
Passing: 0
Failing: 0
Total: 0

_UI Status:_ 'Fatal error'

### System Information

- Which shell/terminal are you using? Powershell
{
  "cliVersion": "@salesforce/cli/1.76.1",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\XXX\\AppData\\Local\\sfdx\\client\\7.198.7-cad6700\\sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.9 (core)",
    "@oclif/plugin-commands 2.2.14 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.6 (core)",
    "@oclif/plugin-search 0.0.16 (core)",
    "@oclif/plugin-update 3.1.12 (core)",
    "@oclif/plugin-version 1.3.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.35 (core)",
    "@oclif/plugin-which 2.2.19 (core)",
    "@salesforce/cli 1.76.1 (core)",
    "apex 2.2.13 (core)",
    "auth 2.7.12 (core)",
    "data 2.3.10 (core)",
    "deploy-retrieve 1.8.15 (core)",
    "info 2.6.7 (core)",
    "limits 2.3.13 (core)",
    "login 1.2.5 (core)",
    "org 2.7.0 (core)",
    "schema 2.3.8 (core)",
    "settings 1.4.4 (core)",
    "sobject 0.1.17 (core)",
    "source 2.10.3 (core)",
    "telemetry 2.1.4 (core)",
    "templates 55.4.9 (core)",
    "trust 2.4.9 (core)",
    "user 2.3.8 (core)"
  ]
}

**Comment by shetzel** [comment]
I believe with this command `sf project deploy start` you need to list each test class individually.  E.g., `-t  ClassA_TEST -t ClassB_TEST` which is different from `sfdx force:source:deploy`.  Can you try that and let me know if it solves your issue?

**Comment by ChouTH** [comment]
> 

I have the same issue and list the test classes separatly works for me.

But this is not the same as what the document says:

[Separate multiple test names with commas, and enclose the entire flag value in double quotes if a test contains a space.
](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_project_commands_unified.htm#cli_reference_project_deploy_start_unified:~:text=Separate%20multiple%20test%20names%20with%20commas%2C%20and%20enclose%20the%20entire%20flag%20value%20in%20double%20quotes%20if%20a%20test%20contains%20a%20space)

**Comment by Orkhidion** [comment]
Indeed, I just made a test and if I'm putting -t and the list of classes separatly it is working @shetzel.
But it is in contradiction with what it is specified in the documentation.

**Comment by pgonzaleznetwork** [comment]
@Orkhidion I think this is related to https://github.com/forcedotcom/cli/issues/2083

**Comment by Orkhidion** [comment]
uhmm thanks @pgonzaleznetwork, indeed it is the same behavior. So as I understand it correctly, it is done on purpose.

The documentation needs to be updated accordingly in order to avoir false issues opened :)
