### ISSUE TITLE
project deploy validate should support validation with destructive packages

### ISSUE THREAD

**Issue by dobrusia** [forcedotcom/cli#2099]
**Is your feature request related to a problem? Please describe.**
As force:source:deploy is planned to be deprecated in the future it would be nice that "project deploy validate" supported destructive packages like fotce:source:deploy does. 

**What are you trying to do**
Validations that include destructive packages are highly useful in automated pipelines and code deployments. It would be regression comparing to `force:source:deploy -c` if destructive packages support was not included and it is actual blocker from migration to newer command.

**Describe the solution you'd like**
`sfdx project deploy validate -x .\package.xml  --pre-destructive-changes .\destructiveChangesPre.xml  --post-destructive-changes .\destructiveChangesPost.xml`

**Describe alternatives you've considered**
None. 

**Additional context**
N/A

**Comment by shetzel** [comment]
This is supported by the `project deploy start` command and the `--dry-run` parameter.  It would be:
`project deploy start --dry-run -x .\package.xml  --pre-destructive-changes .\destructiveChangesPre.xml  --post-destructive-changes .\destructiveChangesPost.xml`
