### ISSUE TITLE
INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations

### ISSUE THREAD

**Issue by Sebastian-Axenon** [forcedotcom/cli#2105]
### Summary

When deploying Custom Fields to a production org with _sf project deploy start_ command, following error is returned:
_Error (1): INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations_
### Steps To Reproduce:

Run _sf project deploy start_ targeting a production org and only deploying a custom field

**Comment by pgonzaleznetwork** [comment]
@Sebastian-Axenon I'm not from sf but I'm curious what were you expecting, the default behaviour where all local tests are run?

**Comment by Sebastian-Axenon** [comment]
Hi @pgonzaleznetwork, as the documentation state, the default value is NoTestRun.
Previous I've have not encountered enforcement to include Apex Tests when deploying fields only.

**Comment by mshanemc** [comment]
the old commands (`force:source:deploy`) would omit the `testLevel` from the [deploy request](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy.htm) unless specified.  The metadata API interprets that as "let the org decide what it should do" which means it may or may not run tests depending on what the org requires (ex: apex tests have to run on a prod org but only if there's components in the deploy that require it, but a sandbox would not run the tests given the same deployment).

Would you want an option that means "do not specify" to delegate to the org's default behavior?

**Comment by marshallvaughn** [comment]
> the old commands (`force:source:deploy`) would omit the `testLevel` from the [deploy request](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy.htm) unless specified. The metadata API interprets that as "let the org decide what it should do" which means it may or may not run tests depending on what the org requires (ex: apex tests have to run on a prod org but only if there's components in the deploy that require it, but a sandbox would not run the tests given the same deployment).
> 
> Would you want an option that means "do not specify" to delegate to the org's default behavior?

This issue impacts my team as well. I'm currently able to specify `NoTestRun` using the legacy `sfdx` CLI, but not `sf`. I frequently used that for things like PermissionSet updates, CustomField deployments, Layout hotfixes, etc. For things like that, there is no Apex Class built that will validate it, and it's not worth it to build one.

We can build a workaround by having it run an empty test class, but that seems a bit wonky as a permanent solution.

**Comment by ps-carl-bussema** [comment]
Agreed, this is a problematic gap. You can actually specify a non-existent test class: `--testlevel RunSpecifiedTests --tests FakeClassName` will work, but it's very annoying to have to do that when previously "let the org decide" was the default and there is no equivalent. I sometimes script low-risk or emergency deployments across multiple orgs, some sandbox and some production, and just letting the org decide would be ideal here.

**Comment by shetzel** [comment]
This issue was fixed with this PR to the deploy-retrieve plugin: https://github.com/salesforcecli/plugin-deploy-retrieve/pull/611

Please reopen if you have steps that reproduce the problem.
