### ISSUE TITLE
Translation-File is not retrieved correctly

### ISSUE THREAD

**Issue by Schuchie** [forcedotcom/cli#2113]
### Summary

We want to retrieve CustomTab, CustomApplication, Labels renamings in a specific language. For our case its german.
If we retrieve the `de.translation-meta.xml` it does not contain all translated values. 

### Steps To Reproduce:

1. Create a custom object and a custom tab.
2. Rename the custom tab in german.
3. Retrieve the `de.translation-meta.xml` file.
4. CustomTab Translation is missing.

Notice: The Custom Object and Tab is locally also available. 

### Expected result

Contains all enabled translations of custom apps, tabs, labels.

### Actual result

Translations are missing.

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
```
{
  "cliVersion": "sfdx-cli/7.194.1",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.11.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/opt/homebrew/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 20.20.3 (user)",
    "@oclif/plugin-autocomplete 2.1.6 (core)",
    "@oclif/plugin-commands 2.2.11 (core)",
    "@oclif/plugin-help 5.2.8 (core)",
    "@oclif/plugin-not-found 2.3.22 (core)",
    "@oclif/plugin-plugins 2.4.3 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.8 (core)",
    "@oclif/plugin-version 1.3.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.32 (core)",
    "@oclif/plugin-which 2.2.17 (core)",
    "apex 2.2.7 (core)",
    "auth 2.7.10 (core)",
    "community 2.2.8 (core)",
    "custom-metadata 2.1.9 (core)",
    "data 2.3.8 (core)",
    "info 2.6.2 (core)",
    "limits 2.3.9 (core)",
    "org 2.6.2 (core)",
    "packaging 1.16.2 (core)",
    "schema 2.3.4 (core)",
    "settings 1.4.2 (core)",
    "signups 1.4.8 (core)",
    "source 2.8.0 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.5 (core)",
    "user 2.3.5 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "sfdmu 4.26.10 (user)",
    "sfdx-cli 7.194.1 (core)",
    "sfpowerkit 6.0.1 (user)"
  ]
}
```

### Additional information
English Translation:
![image](https://user-images.githubusercontent.com/18148112/236234929-25487368-92d2-4587-a47d-19b81ea39f8b.png)
German Translation:
![image](https://user-images.githubusercontent.com/18148112/236235024-2896e0f7-d3fb-4ec1-9fb1-cb9364f1b57d.png)

**Comment by mshanemc** [comment]
can you add the command you ran for `Retrieve the de.translation-meta.xml file.`

**Comment by mshanemc** [comment]
Does it work as expected if your retrieve for Step 3 also includes the CustomTab, CustomApplication, and Labels?

**Comment by Schuchie** [comment]
Hey @mshanemc,
`sfdx force:source:retrieve -m "Translations:de"`

Also tried to pull it via the the package.xml including the CustomTabs, CustomApplications and Labels, but still no success.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>Activity_History__c</members>
		<name>CustomTab</name>
	</types>
	<types>
		<members>de</members>
		<name>Translations</name>
	</types>
	<version>57.0</version>
</Package>
```

**Comment by mshanemc** [comment]
Well, the [mdapi docs](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_translations.htm) do say this

> When you use the [retrieve()](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_retrieve.htm) call to get translations, the files returned in the .translations folder only include translations for the other metadata types referenced in package.xml. For example, this package.xml file contains types elements that match all custom applications, custom labels, web links defined in home page components, custom tabs, report types, and s-controls. Translations for all these metadata types are returned because each metadata type is explicitly listed in package.xml.

So are saying that even when you retried the Translations with the CustomTab, you get the CustomTab but not its translation?

**Comment by mshanemc** [comment]
I agree.  It's a bug, but not in the CLI, it seems to be coming down from the metadata API with the tab translation missing.  

Here's what I'd recommend:
verify that you can reproduce this without the CLI (for example, same process, same package.xml but use workbench).

open a Salesforce case with your repro.

**Comment by Schuchie** [comment]
@mshanemc FYI: same problem with the workbench :D Gonna create a ticket. Thx for the response!
