### ISSUE TITLE
Please add pre and post destructive xml changes on sf project deploy validate

### ISSUE THREAD

**Issue by junners** [forcedotcom/cli#2115]
**Is your feature request related to a problem? Please describe.**
We've been migrating our scripts to the new sf cli since the old one is being deprecated.
We have noticed there's no support for pre/post deployment destructive changes for validation only deployments (--checkonly)

**What are you trying to do**
Validate a package with pre and post deployment packages

**Describe the solution you'd like**
Similar with the sfdx force:source:deploy wherein you can specify --manifest, --predestructivechanges --postdestructivechanges, and a --checkonly, we should also be able to do this in the new sf namespace cli

**Describe alternatives you've considered**
Installed a lower version of the sfdx cli @7.185.0

**Additional context**
Usage documentation on the sf project deploy validate only contains the following flags/opts
`sf project deploy validate
[--json]
[-a API-VERSION]
[--async]
[--concise]
[-x MANIFEST]
[-m METADATA]
[-d SOURCE-DIR]
[--metadata-dir METADATA-DIR]
[--single-package]
-o TARGET-ORG
[-t TESTS]
[-l TEST-LEVEL]
[--verbose]
[-w WAIT]`

**Comment by Raspikabek** [comment]
@junners is it not possible to instead of using `sf project deploy validate` to use `sf project deploy start --dry-run` ? In that scenario you can use the flags `--post-destructive-changes` and `--pre-destructive-changes` while running validations.

Would that workaround your problem?  I've done some tests and seems to be adding everything and running it correctly.

**Comment by junners** [comment]
Oohh I missed that one, thanks for pointing it out. Yeah that would suffice for my scenario

**Comment by jonnypetraglia** [comment]
Is this going to eventually be supported? This is non-negotiable for us.
