### ISSUE TITLE
package version create stops after 1 second - static resource with mp3

### ISSUE THREAD

**Issue by Dietermartens** [forcedotcom/cli#2116]
### Summary

When trying to create a package version with an mp3 in a zipped static resource the package command stops without error right after the start. 

Issue started right after update to the latest version  7.199. 

### Steps To Reproduce:

sfdx package version create -p "PACKAGE" --wait 60 -v DEVHUB -c

static resource:
<?xml version="1.0" encoding="UTF-8"?>
<StaticResource xmlns="http://soap.sforce.com/2006/04/metadata">
    <cacheControl>Private</cacheControl>
    <contentType>application/zip</contentType>
    <description>sounds</description>
</StaticResource>
The directory sounds includes a small mp3 of 2 seconds. 

### Expected result

Start package creation process

### Actual result

sfdx package version create -p "PACKAGE" --wait 60 -v DEVHUB -c
Version create.... done
right after the start.

### System Information

Mac OSX ZSH terminal

sfdx version 7.199

**Comment by Stassy** [comment]
Same problem here (without any MP3) - Windows 11 / VSCode 1.78.0 / sfdx version 7.199.7:
sfdx package version create --package "xxxxx" --installation-key yyyyyyy --definition-file config/project-scratch-def.json --wait 20

Display is just:
Version create... -
Version create... \
Version create... |
Version create... done

Note 1: If I execute the same command with previous version of SFDX (same project, sames files, another computer), there is no problem, the version is created after like 15 min.
Note 2: The title should be "package VERSION create stops after..." instead of "package create stops after")

**Comment by mshanemc** [comment]
Do you get better info if you run the the command with `--json`?   
Is it happening for all uses of the command, or just certain packages?
Is the package/version being created in the org?

**Comment by Dietermartens** [comment]
I'll try it with the --json param and post the result here. I was able to build other packages with the same version. When i removed the mp3 file from the static resources the package was built. 

The version was not created in the org.

**Comment by Stassy** [comment]
Nothing is displayed if I add the "--json" parameter, and I'm back to the prompt after 2 seconds.

I work with only 1 package (source files), so can't say about other packages.

I can create a new package "sfdx package create ........" without problems (same source files).
But when I use "sfdx package version create .....", same problem. Exit after 2 seconds.

**Comment by Dietermartens** [comment]
@Stassy you can downgrade to version 7.188, that works for me atm.

**Comment by Stassy** [comment]
> @Stassy you can downgrade to version 7.188, that works for me atm.

I've installed it initialy with Windows regular installer. Then I do my updates with "sfdx update". Is there a way to downgrade with sfdx command?

**Comment by Dietermartens** [comment]
As far as i know you can only select your version when you use the npm install

**Comment by shetzel** [comment]
This seems similar to #2092 .  The main difference I see is that the issue only happens in CI for 2092.  To confirm, you see this behavior with v7.199.7 when running the `package version create` command locally (i.e., not in CI)?

**Comment by Dietermartens** [comment]
I'm not using a CI for this project, only on local.

**Comment by shetzel** [comment]
@Dietermartens - I cannot repro what you're seeing.  I am using an npm installation of 7.199.7 on a macbook, zsh.  I created a public github repo for this issue and issue 2092 here: https://github.com/shetzel/pvc-no-output.  When I create a package and package version from the source in that repo, everything is created as expected.  If you notice anything missing from the repo I created let me know.

If you run the command with `--dev-debug` is there anything you notice in the debug output?  What version of nodejs are you using?

**Comment by Dietermartens** [comment]
@shetzel I tried it with your repo and that worked fine indeed. So i started testing a few oher things too, and i think i found it. We are using a custom directory structure, where we split the metadata per app in a folder. Like the Falcon Template (https://github.com/sfdx-isv/sfdx-falcon-template) (https://www.slideshare.net/VivekMChawla/salesforce-dx-201-advanced-implementation-for-isvs#34)

Now this worked fine before (and still does in older versions) but I noticed when you add another app and also put a folder 'staticresources' in there, you can replicate the behavior. I submitted an example to your test repo.

This is a log file for what happens during the packaging when i add --dev-debug
[sfdx-debug.log](https://github.com/forcedotcom/cli/files/11425087/sfdx-debug.log)

**Comment by shetzel** [comment]
@Dietermartens - what are the exact steps you are following with your fork that cause the bad behavior?  I've tried a bunch of combinations and it works every time for me.  What does `sfdx version --verbose` output?

**Comment by Stassy** [comment]
There is no CI, only local and Node is 18.16.0

Here is my debug log
[sfdx-debug-log.txt](https://github.com/forcedotcom/cli/files/11428078/sfdx-debug-log.txt)

**Comment by Dietermartens** [comment]
@shetzel That is weird, so when i added the second staticresources folder that also included a zip upload i could reproduce the issue 100% of the tries. When i removed the zip in one of the folders it worked again. 
Steps: 
1. Create package version -> See TEST in sfdx-project
2. Create package version with basic options -> sfdx package version create -p "TEST" --wait 60 -v DEBHUB -c -k KEY

If you like I can create a short screen capture to show it 

(node:91466) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:91466) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
 CLI Version:
	sfdx-cli/7.199.7

 Architecture:
	darwin-x64

 Node Version:
	node-v19.9.0

 Plugin Version:
	@oclif/plugin-autocomplete 2.1.9 (core)
	@oclif/plugin-commands 2.2.14 (core)
	@oclif/plugin-help 5.2.9 (core)
	@oclif/plugin-not-found 2.3.23 (core)
	@oclif/plugin-plugins 2.4.7 (core)
	@oclif/plugin-search 0.0.16 (core)
	@oclif/plugin-update 3.1.13 (core)
	@oclif/plugin-version 1.3.3 (core)
	@oclif/plugin-warn-if-update-available 2.0.36 (core)
	@oclif/plugin-which 2.2.19 (core)
	apex 2.2.14 (core)
	auth 2.7.13 (core)
	community 2.2.11 (core)
	custom-metadata 2.1.17 (core)
	data 2.3.11 (core)
	deploy-retrieve 1.8.18 (core)
	info 2.6.8 (core)
	limits 2.3.13 (core)
	org 2.7.2 (core)
	packaging 1.16.8 (core)
	schema 2.3.10 (core)
	settings 1.4.5 (core)
	signups 1.4.13 (core)
	source 2.10.6 (core)
	telemetry 2.1.6 (core)
	templates 55.4.11 (core)
	trust 2.4.12 (core)
	user 2.3.9 (core)
	sfdx-cli 7.199.7 (core)

 OS and Version:
	Darwin 21.6.0

 Shell:
	zsh

 Root Path:
	/Users/dietermartens/.config/yarn/global/node_modules/sfdx-cli

**Comment by Ushank** [comment]
Are you able to find a solution for this one? I am stuck on the same issue; the debug logs are producing the same results. I have tried on the previous versions as well but no luck

**Comment by shetzel** [comment]
Are you all able to successfully source convert the same package?  E.g., `sfdx project convert source -p force-app -d converted` or does that also silently fail to actually convert the source?

2 other teammates and I have been unsuccessful reproducing any of the `package version create` issues.  I've been working in a docker container for the past hour with no success.  All of the debug logs I've seen from people who can repro the problem have similar output.  A ComponentSet of source is created and should be converted and zipped, but there is no debug output that anything was zipped.  For example, my debug output contains:
```
sf:core TRACE Setup child 'srcDevUtils#zipDir' logger instance +56ms
sf:srcDevUtils#zipDir DEBUG 205603 bytes written to /var/folders/_x/0dvp4tv91zbfy4d31lff9fd40000gp/T/0Ho4p000000bnxMCAQ-b6b5552740577a27790602805a18f254/package-version-info/package.zip in 56.456ms +0ms
sf:core TRACE Setup child 'srcDevUtils#zipDir' logger instance +57ms
sf:srcDevUtils#zipDir DEBUG 205213 bytes written to /var/folders/_x/0dvp4tv91zbfy4d31lff9fd40000gp/T/0Ho4p000000bnxMCAQ-b6b5552740577a27790602805a18f254/package-version-info.zip in 12.500ms +13ms
```

This suggests that the problem is in the source-deploy-retrieve library, most likely during zip operations.

**Comment by shetzel** [comment]
The current theory with this issue is that it's nodejs version related.  Looks like nodejs v18.16.0 and higher have this problem but downgrading nodejs to below 18.16.0 should workaround the issue.  We're continuing to investigate why.  I'll post updates as we find them.

**Comment by mshanemc** [comment]
We've got some workarounds and a fixed RC available.  I'd love to know that this is working for you.
https://github.com/forcedotcom/cli/issues/2125

**Comment by Dietermartens** [comment]
On Node 19.9.0 -> Same issue with version 7.199.7 or 7.200.7

On Node 18.15.0 -> Both versions work.

So I guess this ticket is a duplicate/ variant of #2125

**Comment by Ushank** [comment]
It’s happening because of static resource of zip type. I was able to make
the package by removing the zip file.
