### ISSUE TITLE
2GP Package Version Create Command not working nor giving any error

### ISSUE THREAD

**Issue by Ushank** [forcedotcom/cli#2119]
Create package version command does not create a new package version or generate any error or exception.

sfdx package version create -p "Lending Manager (LOS)" -f config/project-scratch-def.json --target-dev-hub xyz@cloudmaveninc.com -c --installation-key-bypass --wait 60

### Expected result
- A new package version should have been created or produced an error.

### Actual result
- Nothing. Please see the attached screenshot.

### System Information

{
  "cliVersion": "sfdx-cli/7.199.7",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\HP\\AppData\\Local\\sfdx\\client\\7.199.7-cc56357",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.9 (core)",
    "@oclif/plugin-commands 2.2.14 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.7 (core)",
    "@oclif/plugin-search 0.0.16 (core)",
    "@oclif/plugin-update 3.1.13 (core)",
    "@oclif/plugin-version 1.3.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.19 (core)",
    "apex 2.2.14 (core)",
    "auth 2.7.13 (core)",
    "community 2.2.11 (core)",
    "custom-metadata 2.1.17 (core)",
    "data 2.3.11 (core)",
    "deploy-retrieve 1.8.18 (core)",
    "info 2.6.8 (core)",
    "limits 2.3.13 (core)",
    "org 2.7.2 (core)",
    "packaging 1.16.8 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.5 (core)",
    "signups 1.4.13 (core)",
    "source 2.10.6 (core)",
    "telemetry 2.1.6 (core)",
    "templates 55.4.11 (core)",
    "trust 2.4.12 (core)",
    "user 2.3.9 (core)",
    "sfdx-cli 7.199.7 (core)"
  ]
}
![package version issue](https://user-images.githubusercontent.com/6064460/236949120-b76e2171-cb23-4bca-bdaa-7730c281d6bf.png)

I am stuck and not able to move forward. these commands were working before.

**Comment by mshanemc** [comment]
Can you look at this issue and see if you might have something similar?  https://github.com/forcedotcom/cli/issues/2116

**Comment by Ushank** [comment]
@mshanemc The issue looks similar but i don't have any MP3 files in the static resource. However, I do have static resource files.
Please note, i was able to able the version around 10 days back on 04/27. I have wanted 3 days in the issue and need to have it working asap.

Today, I set up another machine using version 7.198.7 but no luck. Since we are not seeing any errors, it's making life very complicated, and not sure how to proceed further.

**Comment by Ushank** [comment]
Hello @mshanemc,

Tried using the debug mode.

version = sfdx-cli/7.199.7 win32-x64 node-v18.16.0

[debuglogs.txt](https://github.com/forcedotcom/cli/files/11427744/debuglogs.txt)

It seems like we are unable to load two plugins and have some issues with telemetry.

**Comment by Ushank** [comment]
Seems like multiple people are reporting the issue. The debug logs are matching or having the same issue.

I am using local version and my package also has dependencies.

other similar issues.

https://github.com/forcedotcom/cli/issues/2116
https://github.com/forcedotcom/cli/issues/2092

I haven't found any solution or workaround.

**Comment by Ushank** [comment]
@mshanemc sorry to tag you here. Do you have any suggestion for us or do you need additional information from me?

**Comment by mshanemc** [comment]
We're looking at several of these, so I'm sure they real.  We just haven't been able to reproduce the failure yet--whatever we try seems to work so far.

**Comment by mshanemc** [comment]
Out of curiosity, does your package contain static resources?  How big are they (if you have a lot, maybe "how big are the largest 2-3?")

**Comment by Ushank** [comment]
Yes, i do have static resources (but not huge). I was able to create the package on 04/27. Everything is same in the current version its just i updated my cli to the latest version.

**Comment by Ushank** [comment]
Please note we also have dependencies on the other packages.

**Comment by Ushank** [comment]
the total size of the static resource is less than 170KB. PLease note, i was able to package it before.

**Comment by Ushank** [comment]
for testing purposes, i just deleted the static resources and it seems to processing something(I didn't get the issue). The size of the static resource folder was 168KB and it's required for me to package it.
Could you please suggest.

**Comment by Skelding** [comment]
I've been investigating this one for a while, as it's impacting our package versioning as well. I just made an interesting discovery, that I was consistently seeing this when using sfdx-cli on Node 18. I tried downgrading to Node 16, and now the versioning is executing. If other folks are experiencing the same issue, I suggest trying this same workaround.

**Comment by rlbarreto** [comment]
I do have the same problem. I need to create 2 packages. They are basically static resources. When I execute the version create line it takes a few seconds showing the message "Version create..." and then show the message as done, but there is no version created

**Comment by ImJohnMDaniel** [comment]
What version of Node is the standard Salesforce Docker image running right now?  We have also been seeing this issue across some of the projects.  The common element is that they all fail on our CI platform which is using the latest Docker image.

**Comment by shetzel** [comment]
Current docker image uses nodejs v18.16.0.  I was working in a container yesterday with the latest image and reproduced the problem.  I could not repro it using v18.14.2.  So it does appear nodejs version related and at this point downgrading to whatever version works for you is recommended.  We're continuing to investigate this and will update threads as we find more.  Thanks for your patience while we track down the problem.  Feel free to post any data points you think would be helpful.

**Comment by mshanemc** [comment]
We've got some workarounds and a fixed RC available.  I'd love to know that this is working for you.
https://github.com/forcedotcom/cli/issues/2125

**Comment by rlbarreto** [comment]
> We've got some workarounds and a fixed RC available. I'd love to know that this is working for you. #2125

New version working for me. Thank you.
