### ISSUE TITLE
enable sfdx auth:login:sfdx-url to read the url from stdin

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#2120]
**Is your feature request related to a problem? Please describe.**

no

**What are you trying to do**

I don't want to store a secret in disk as a plain text.

**Describe the solution you'd like**

sfdx could read the auth url from stdin like docker login does `echo $PASSWORD | docker login --username foo --password-stdin`. Where `$PASSWORD` is an env variable available in a single shell session. It isn't saved anywhere in disk as a plain text, also not loaded by `~/.profile`, or rc files like `~/.bashrc,~/.zshrc`

It could work like this

`echo $AUTH_URL | sfdx auth:login:sfdx-url --sfdx-auth-url` 

or

`sfdx auth:login:sfdx-url --sfdx-auth-url $AUTH_URL`

Then you can delete the `--sfdx-auth-url-file` flag. 

**Describe alternatives you've considered**

N/a

**Additional context**
N/A

**Comment by AllanOricil** [comment]
seems simple to do it
https://github.com/salesforcecli/plugin-auth/blob/2966bf9c5d1e38ac0e56aacf3b619975375e9445/src/commands/org/login/sfdx-url.ts#L72-L74

**Comment by amtrack** [comment]
I'd love to see this natively supported as well.

@AllanOricil Until this is implemented you could use the following workaround on UNIX and MacOS:

```console
sfdx auth sfdxurl store -d -a devhub -f <(echo "$SFDX_AUTH_URL_DEVHUB")
```

This is using [Bash Process Substitution](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Process-Substitution
).

```console
$ ls <(echo "hi ls")
/dev/fd/11
$ cat <(echo "hi cat")
hi cat
```

**Comment by AllanOricil** [comment]
I dont think it would solve the problem because process substitution saves the information you piped in it to a file at `/dev/fd/`

When we use process substitution, the file location is echoed. This means its location can be retrieved from history if not deleted. I can consult the history, find the file, read its content. Even without knowing its location, I could just search for the Auth Url Pattern in all files at `/dev/fd`

**Comment by amtrack** [comment]
@AllanOricil As far as I know it isn't written to disk.

```console
$ ls <(echo "hi ls")
/dev/fd/11
$ cat /dev/fd/11
cat: /dev/fd/11: Bad file descriptor
```

**Comment by AllanOricil** [comment]
According to this [guide](https://tldp.org/LDP/abs/html/process-sub.html), 

`Process substitution uses /dev/fd/<n> files to send the results of the process(es) within parentheses to another process`


I tried to access them and it seems possible
<img width="336" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/41400be3-9ce9-49a2-9305-a919748c38c2">

**Comment by AllanOricil** [comment]
Simple example to demonstrate that `/dev/fd/n` are readable

<img width="404" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/eeb46975-5fd1-4447-8b7b-f07e7436db68">

https://unix.stackexchange.com/questions/556490/is-it-guaranteed-freshly-opened-dev-fd-3-always-reads-from-start

**Comment by amtrack** [comment]
@AllanOricil Yes, I can reproduce your example.
But using `exec 3<FILENAME` isn't what I suggested :-)

Can you reproduce my example?

```
$ ls <(echo "hi ls")
/dev/fd/11
$ cat /dev/fd/11
cat: /dev/fd/11: Bad file descriptor
```

**Comment by AllanOricil** [comment]
@amtrack I can confirm that `/dev/fd/11` does not have any data in it. No idea why some of these files are readable and some are not. Kind weird. 

<img width="424" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/12a37ddf-722a-4ade-a242-911814b9c8dc">

I can """read""" it using the browser, but it displays nothing
<img width="1266" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/0329750b-5094-4ea2-a733-cf0ec0cd8a41">

the fs also shows that it has 0 bytes
<img width="351" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/dc8c573e-b9e4-47fb-9d03-365325bfa918">

do you know why the number 11 is a constant in your example? I thought `n` was the number of the shell process
why it does not store data like number 3 do?

**Comment by AllanOricil** [comment]
the following sfdx|sf docs could be updated with @amtrack solution

https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_auth_sfdxurl.htm#cli_reference_auth_sfdxurl_store


https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_org_commands_unified.htm#cli_reference_org_login_sfdx-url_unified

By the way, just noticed that the new doc was not templated properly. 

<img width="968" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/294ea00b-421c-4528-b1a5-232be51d321a">

**Comment by ImJohnMDaniel** [comment]
FWIW,  I love this idea!!!!

**Comment by amtrack** [comment]
I'd definitely prefer having it implemented using a new `--sfdx-auth-url` flag just like @AllanOricil described it instead of documenting a workaround that unfortunately only works on UNIX and MacOS with Bash. 😄

**Comment by AllanOricil** [comment]
the same problems could happen with the jwt flow which also reads a key from disk `--jwt-key-file`
just don't use this auth url in ci automations, create ur own connected app and rotate keys from time to time.

**Comment by AllanOricil** [comment]
reopened because I still think it does not make sense to read unencryted secrets from disk

**Comment by AllanOricil** [comment]
doc still broken
<img width="980" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/f97fa4b6-aab0-4a71-b067-7561ab8fa8b0">

**Comment by cristiand391** [comment]
@AllanOricil thanks for the heads up!
We fixed the issue with templates not being rendered when generating the CLI command reference. IIRC, it take a few weeks to get those pages updated, I'll check again next week.

**Comment by AllanOricil** [comment]
Here there is an example of how this could be achieved
https://github.com/oclif/oclif/issues/245

**Comment by AllanOricil** [comment]
I opened a PR for this new flag

**Comment by WillieRuemmele** [comment]
https://github.com/salesforcecli/plugin-auth/pull/765

**Comment by AllanOricil** [comment]
ALMOST THERE GUYS!
NEXT STEPS:
 - WIN AN OSCAR

**Comment by AllanOricil** [comment]
<img width="451" alt="Screenshot 2023-08-15 at 16 48 30" src="https://github.com/salesforcecli/plugin-auth/assets/55927613/8ee08e5b-4f0c-4120-895f-4afb1fb7f9b1">

**Comment by AllanOricil** [comment]
It can be implemented with https://github.com/oclif/core/pull/894 once core is updated to v3

**Comment by shetzel** [comment]
The fix is now in the sf CLI release candidate version, v2.24.4.

**Comment by AllanOricil** [comment]
![SmartSelect_20240110_184438_Brave.jpg](https://github.com/forcedotcom/cli/assets/55927613/659c1104-d4b0-450d-bc6c-c6740affebcf)

**Comment by AllanOricil** [comment]
https://youtube.com/clip/Ugkxy3FFXYGwr5TnOfwiG2fZAJZEA7JZqAeg?feature=shared
