### ISSUE TITLE
Source conversion failing with multiple large .zip static resources

### ISSUE THREAD

**Issue by bowserad20** [forcedotcom/cli#2121]
### Summary

After the latest update (7.199.7), we started experiencing issues while performing source conversion in our devops pipeline. After some testing, we found using `force:source:convert` on 2 large .zip static resources was not completing successfully. 

When using `force:source:convert` on either resource individually, a success message is displayed. However, when running the command on both resources at once, no success message is displayed and the output metadata is incomplete.

Using `project source convert` rather than `force:source:convert`  does not fix this issue

Downgrading to the previous version (7.198.6) fixes the issue entirely

### Steps To Reproduce:

**Repository to reproduce:** 
[Repo to reproduce issue](https://github.com/bowserad20/sfdx-bug-5-4-23)
This repo contains an sfdx project with the .zip files that are causing issues. Access to this repo will be granted upon request.

1.  Specify multiple large .zip static resources in a package.xml
1.  Run `sfdx force:source:convert -x manifest/package.xml` to convert those resources

### Expected result

A success message is printed, and all source was converted to metadata format, and is able to be deployed successfully.

### Actual result

No success or error message is printed. Resultant metadata is incomplete (in our case, we saw metadata errors such as missing fields when trying to deploy).

### System Information

This issue has been observed using the VSCode integrated terminal on MacOS and Windows, as well as using a bash script on Linux (sfdx installed via npm).

The issue has been observed on versions 7.199.7 and 7.200.0, and can be fixed by downgrading to any prior versions.

Here is verbose version information using MacOS Terminal:

{
  "cliVersion": "sfdx-cli/7.199.7",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/Users/abowser/.local/share/sfdx/client/7.199.7-cc56357",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.9 (core)",
    "@oclif/plugin-commands 2.2.14 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.7 (core)",
    "@oclif/plugin-search 0.0.16 (core)",
    "@oclif/plugin-update 3.1.13 (core)",
    "@oclif/plugin-version 1.3.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.19 (core)",
    "apex 2.2.14 (core)",
    "auth 2.7.13 (core)",
    "community 2.2.11 (core)",
    "custom-metadata 2.1.17 (core)",
    "data 2.3.11 (core)",
    "deploy-retrieve 1.8.18 (core)",
    "info 2.6.8 (core)",
    "limits 2.3.13 (core)",
    "org 2.7.2 (core)",
    "packaging 1.16.8 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.5 (core)",
    "signups 1.4.13 (core)",
    "source 2.10.6 (core)",
    "telemetry 2.1.6 (core)",
    "templates 55.4.11 (core)",
    "trust 2.4.12 (core)",
    "user 2.3.9 (core)",
    "sfdx-cli 7.199.7 (core)"
  ]
}
### Additional information

_Feel free to attach a screenshot_.

**Comment by mshanemc** [comment]
can you open that repo up publicly so I can try with your code?

**Comment by bowserad20** [comment]
@mshanemc I've added you as a contributor to that repo. 

I will add other users as needed, but have been asked to keep the repo private as it contains source code from a production environment.

Thanks!

**Comment by mshanemc** [comment]
Thanks for the access!  I *totally* believe you because there's some people who can repro a packaging bug involving multiple static resources.  There's a bug somewhere in 7.199

Unfortunately, neither Steve nor I can get the bug to appear.  

sfv2 <img width="1792" alt="Screenshot 2023-05-09 at 1 42 26 PM" src="https://github.com/forcedotcom/cli/assets/4261788/34f888c2-d491-43bd-8a97-1b9360381614">

I even uninstalled and downgraded to the version you're on and it seems to work fine.

sfdx latest <img width="1792" alt="Screenshot 2023-05-09 at 1 44 03 PM" src="https://github.com/forcedotcom/cli/assets/4261788/516f05ba-eb64-4888-9e8e-7f86938acbcb">

**Comment by mshanemc** [comment]
not memory related.  this works fine:
`NODE_OPTIONS='--max-old-space-size=2000' sf force source convert -x manifest/package.xml --output-dir mdapiOut`

**Comment by bowserad20** [comment]
Yikes! As a sanity check I just updated to 7.200.6, freshly cloned the repo, and tested again. Still getting the same results:

Individual file succeeds:
![singleFileWorks](https://github.com/forcedotcom/cli/assets/102424314/f6a980ef-ce65-450b-b33c-4c556df1f9bb)

Both files at once, doesn't succeed:
![nope](https://github.com/forcedotcom/cli/assets/102424314/ab926541-e4db-4bb6-a1ab-66b5df018321)

Both files at once, using old version succeeds:
![oldVersionWorks](https://github.com/forcedotcom/cli/assets/102424314/528d2b8f-8d94-4c65-bbd8-a6cf77aebede)

Looks like we're both on the trusty Salesforce MacBook, so there should be minimal difference in OS, etc. Other than something _very_ silly like memory or file structure differences, I couldn't imagine what would make the difference

Let me know if there's anything else I could provide to help repro. I think my team can just use the older version for now as a workaround. 

Thanks for looking into this!

**Comment by mshanemc** [comment]
We've got some workarounds and a fixed RC available.  I'd love to know that this is working for you.
https://github.com/forcedotcom/cli/issues/2125

**Comment by bowserad20** [comment]
Good news so far, updating to 7.200.7 seems to have fixed the issue for me when running locally on my machine!

I'd imagine this update will fix the same issue when running in our devops pipeline as well. I'll post an update here later today after some testing and close the issue if all is well.

**Comment by bowserad20** [comment]
We've had success running 7.200.7 in our devops pipelines today, so it seems the fix worked for us.

If only those amateurs working on Node.js could get their act together, am I right??
