### ISSUE TITLE
Character encoding difference between source:retrieve vs mdapi:retrieve?

### ISSUE THREAD

**Issue by sfdcale** [forcedotcom/cli#213]
### Summary

Character encoding is different when components are retrieved using the command `sfdx force:mdapi:retrieve`(apostrophe is encoded as **`&apos;`**) vs `sfdx force:source:retrieve`(apostrophe is encoded as **`&#39;`**)

### Steps To Reproduce:

Here is the screenshot of a simple validation rule in Salesforce:

![Screen Shot 2019-10-09 at 10 54 30 AM](https://user-images.githubusercontent.com/11079913/66507881-e29c7d80-ea84-11e9-85f7-5b5d22c5a57f.png)

1.  Create a **package.xml** with below content:
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types>
    <name>ValidationRule</name>
    <members>Foo__c.Tru_validation_rule</members>
  </types>
  <version>46.0</version>
</Package>
```
2.  Retrieve components using the command `sfdx force:mdapi:retrieve --unpackaged=package.xml --retrievetargetdir=temp_folder --targetusername=dev` and this is what it looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <validationRules>
        <fullName>Tru_validation_rule</fullName>
        <active>true</active>
        <errorConditionFormula>OR( &apos;a&apos;&amp; &apos;b&apos; = &apos;ab&apos;)</errorConditionFormula>
        <errorMessage>Test</errorMessage>
    </validationRules>
</CustomObject>
```

3.  Retrieve components using the command `sfdx force:source:retrieve --manifest=package.xml --targetusername=dev` and this is what it looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<ValidationRule xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>Tru_validation_rule</fullName>
    <active>true</active>
    <errorConditionFormula>OR( &#39;a&#39;&amp; &#39;b&#39; = &#39;ab&#39;,&#39;c&#39;&amp; &#39;d&#39; = &#39;cd&#39;,&#39;e&#39;&amp; &#39;f&#39; = &#39;ef&#39;, 1 = 1, 2= 2)</errorConditionFormula>
    <errorMessage>Test</errorMessage>
</ValidationRule>
```

### Expected result

Character encoding of apostrophe should match.

### Actual result

Character encoding of apostrophe when retrieved using the command `sfdx force:mdapi:retrieve` is **`&apos;`** 
Character encoding of apostrophe when retrieved using the command `sfdx force:source:retrieve` is **`&#39;`**

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**: 
sfdx-cli/7.27.0-714f62f9c1 darwin-x64 node-v10.15.3

**SFDX plugin Version**:
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.17.0 (core)
├─ force-language-services 46.24.0 (core)
└─ salesforce-alm 46.22.0 (core)

sfdx-cli 7.27.0 (core)

**OS and version**:
macOs Mojave( 10.14.5)

https://salesforce.stackexchange.com/questions/280818/character-encoding-difference-between-sourceretrieve-vs-mdapiretrieve

**Comment by prashanthml** [comment]
@clairebianchi  , @sfdcale  Is there any workaround for resolving this issue.

**Comment by timkuntz** [comment]
Can anyone confirm this was corrected in the Summer 2020 release? I noticed the following change.
```
sfdx force:source:retrieve -u staging -p force-app/main/default/objects/Case/fields/...
```
Produces the following change (from my Git diff)
```
             <value>
-                <fullName>I&#39;m getting an error</fullName>
+                <fullName>I&apos;m getting an error</fullName>
                 <default>false</default>
-                <label>I&#39;m getting an error</label>
+                <label>I&apos;m getting an error</label>
             </value>
```

**Comment by nebc-jasonfung** [comment]
Any news on this one? I'm getting loads of `&#39;` -> `&apos;` diffs

**Comment by ZboiiZammy** [comment]
Hi,

I am getting the same in a force:source:retrieve. Any news on this?

**Comment by samhowle** [comment]
Also going crazy over this issue as of Winter 2021 (API 50.0) release and SFDX version 50.16.0.

**Comment by kidjansen** [comment]
Same here, CLI version 7.82.0

**Comment by kg345** [comment]
This should be closed - was fixed with W-6853964

**Comment by mshanemc** [comment]
I can't reproduce this on current versions.

source:retrieve (decomposed file inside the object) 
```
<?xml version="1.0" encoding="UTF-8"?>
<ValidationRule xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>test</fullName>
    <active>true</active>
    <errorConditionFormula>OR(&apos;a&apos;&amp; &apos;b&apos; = &apos;ab&apos;)</errorConditionFormula>
    <errorMessage>test</errorMessage>
</ValidationRule>
```

mdapi:retrieve
```
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
    <validationRules>
        <fullName>test</fullName>
        <active>true</active>
        <errorConditionFormula>OR(&apos;a&apos;&amp; &apos;b&apos; = &apos;ab&apos;)</errorConditionFormula>
        <errorMessage>test</errorMessage>
    </validationRules>
</CustomObject>

```

**Comment by banderson-stripe** [comment]
Could this be an OS issue causing the differences in encoding?
