### ISSUE TITLE
sf (v2) is Generally Available

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#2132]
As of July 12, 2023, `sf` (v2) is GA and ready for you to use. 

Check out [this blog post](https://developer.salesforce.com/blogs/2023/07/salesforce-cli-sf-v2-is-here) for information and context about this new release. 

A few quick notes about `sf` (v2):

* It answers to either `sfdx` or `sf`. For example, `sfdx version`  now returns the same information as `sf version`. 
* It knows the same commands and plugins as either existing CLI. 
* It contains only one copy of the plugins, so it’s 40% smaller, which means faster downloads and updates. 
* When you install a plugin, it’s reachable with either `sfdx` or `sf` . So you don’t need to remember how you installed it.

We recommend you move to `sf` (v2) as soon as possible. It’s easy: simply uninstall `sfdx` (v7) and install `sf` (v2). See the new [Move from `sfdx` (v7) to `sf` (v2)](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm) section of the Setup Guide for details, including how to update your continuous integration (CI) scripts.

As of July 12, we no longer publish new versions of `sfdx` (v7).  You can keep using it, but it won’t contain new features or bug fixes.

**Comment by jefersonchaves** [comment]
The autocomplete breaks for both `sf` and `sfdx`in my Mac installation,
`sf` autocomplete shows no error.
`sfdx` autocomplete shows an error `(eval):1: _sfdx: function definition file not found`.

When I run `sfdx update` it updates to v1 and the autocomplete remains broken.

**Comment by cristiand391** [comment]
@jefersonchaves the first step here links to our uninstall instructions which ask to delete some folders:
https://github.com/salesforcecli/cli/blob/492f1cb73549359a9ddafed971db6a12bd013845/.github/workflows/v2-beta.md#installers

Autocompletes file are in `~/Library/Caches/sf` and `~/Library/Caches/sfdx`, so if you follow the steps and delete these folders, then generate them again by running `sf autocomplete` and restart your terminal you should get autocomplete working for `sf`.

Autocomplete will not work for the `sfdx` executable included in `sf` v2 yet.

**Comment by jefersonchaves** [comment]
Hey @cristiand391,

Thanks for the reply.

That is exactly what I did: uninstalled and cleaned up all folders per [uninstall instructions](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm).

So, fair enough, it is broken, for now, that explains. I was curious to know if you guys were aware, though.

**Comment by cristiand391** [comment]
@jefersonchaves ah, sorry, that `(eval):1: _sfdx: function definition file not found` made me think you may still had the old autocomplete files. 

Yep, we'll add support for this feature (oclif bin aliases) in all supported shells (bash,zsh and powershell) in the following days. 
If you are using zsh you can manually assign the `sf` autocomplete func to `sfdx` by running `compdef sfdx=sf` (make sure to generate sf autocompletion and reload your terminal before running this).

**Comment by jefersonchaves** [comment]
Hey @cristiand391,

That could be the as well (perhaps old `.zshrc` reference). The autocomplete is also broken for `sf` with v2 anyway, so, I have to wait until you guys implement that, fair deal.

What is also weird is that `sfdx update` updates `sfdx` back to v1.

**Comment by WillieRuemmele** [comment]
Hey @jefersonchaves 👋 

I was looking into the `sfdx update` issue and couldn't reproduce it and had a few questions. Firstly, I installed the beta through the mac arm64 installers
```
 ➜  sf -v                    
@salesforce/cli/2.0.0-beta.31 darwin-arm64 node-v18.15.0
➜  core
 ➜  sfdx -v
@salesforce/cli/2.0.0-beta.31 darwin-arm64 node-v18.15.0
➜  core
 ➜  sfdx update      
@salesforce/cli: Updating plugins... ⡿ [1/4] Resolving packages...
...
@salesforce/cli: Updating plugins... done
➜  core
 ➜  sfdx -v    
@salesforce/cli/2.0.0-beta.36 darwin-arm64 node-v18.15.0
```

if you're doing anything different please let me know. This might also just be a side-effect of publishing V2 under the `beta` tag, and since `sfdx update` defaults to `latest` it would make sense it's pointing to the current version, but that doesn't explain why it's working for me... you should be able to `sf update beta` to get back to the V2 version

**Comment by jefersonchaves** [comment]
Hello @WillieRuemmele 👋

Thanks, you did the same as me (remove everything, install v2 via arm64 installer) but on a different timeframe - maybe the latest tag has changed in between our tests.

Another potential cause could be that I had not previously selected a beta channel on my `sfdx` setup.

**Comment by BobSeu** [comment]
Is the sfdx alias going to remain after sf v2 leaves beta?  Or will it stick around indefinitely?

**Comment by WillieRuemmele** [comment]
Hey @BobSeu - the `sfdx` alias will stick around for quite a long time - we'll just be referring to the executable and name as `sf` in docs and other messaging
