### ISSUE TITLE
sf project deploy start returns Error(1): Cannot read properties of undefined (reading 'validate')

### ISSUE THREAD

**Issue by JeffArwady** [forcedotcom/cli#2138]
### Summary

When running "sf project deploy start --source-dir sf1/" I get the error in the title.  I'm trying to deploy my entire package directory "sf1" to the target-org (set as the default) so not listed in my command.  

Please help.

**Comment by JeffArwady** [comment]
Update - when running sf project deploy validate --source-dir sf1
I get this error:

Error(1): Component conversion failed: fast_xml_parser_1.XMLBuilder is not a constructor

Thinking that might be the real error message?  Please advise.

**Comment by JeffArwady** [comment]
RESOLVED - I uninstalled and reinstalled the cli software on my Windows PC and it fixed my issue.  I had previously updated to the latest by installing the latest software.  In the future I will both uninstall and reinstall sfdx cli when performing updates.  NOTE: I'm behind a firewall so sfdx update will not work for me.

**Comment by mshanemc** [comment]
@JeffArwady good to know.  Thanks for posting the `RESOLVED`
