### ISSUE TITLE
sf package version create fails on queries using "WITH SECURITY_ENFORCED"

### ISSUE THREAD

**Issue by gregstackaero** [forcedotcom/cli#2139]
### Summary

When running the package version create commands, the following error is received:
```SObject row was retrieved via SOQL without querying the requested field```

The error is received from apex tests run in the package, on queries which specify WITH SECURITY_ENFORCED or the 'stripInaccessible' helper from the Security Class. 

### Steps To Reproduce:
1. For any package that includes WITH SECURITY_ENFORCED or Security.stripInaccessible where the query is called by an apex test

2. Ensure CLI is updated to the latest version
```sfdx version```
should return 7.200.7'
if not then run 
```npm install npm install --global sfdx-cli```

3.  Run the package create command
```sfdx package version create --installation-key "yourkey" --wait 30 --code-coverage -v devhub@user.invalid --path force-app --json --verbose```

### Expected result

Successful package version result

### Actual result

```
{
    "code": 1,
    "context": "PackageVersionCreateCommand",
    "commandName": "PackageVersionCreateCommand",
    "message": "Multiple errors occurred: (1) Apex Test Failure: Class.namespace.classname.methodName: SObject row was retrieved via SOQL without querying the requested field: Object.FieldName",
    "name": "MultipleErrorsError",
    "status": 1,
    "stack": "MultipleErrorsError: lots more stuff here siimilar to message",
    "exitCode": 1,
    "warnings":
    [
        "The \"force package version create\" command has been deprecated. Use \"package version create\" instead."
    ]
}
```

### System Information

- Which shell/terminal are you using? zsh, github actions and macbook pro

both of these commands fail for CLI version 7.200.7
```sfdx package version create --installation-key "yourkey" --wait 30 --code-coverage -v devhub@user.invalid --path force-app --json --verbose```
```sfdx force:package:version:create --installation-key "yourkey" --wait 30 --code-coverage -v devhub@user.invalid --path force-app --json --verbose```

### Workaround

Downgrade to CLI version 7.199.7
```npm install --global sfdx-cli@7.199.7```

This results in successful execution of sfdx package version create

**Comment by gregstackaero** [comment]
![image](https://github.com/forcedotcom/cli/assets/28810016/a69948da-e040-45ae-bb15-a58c01ebed96)

**Comment by daveespo** [comment]
Are you assigning a Perm Set with CRUD/FLS to the QuoteStatus object to the user (`UserInfo.getUserId()`)  in your `@TestSetup` and then doing a `System.runAs()` for all of your tests?

The user that the package creation is being run as is NOT a Sys Admin and does not have full CRUD/FLS access.

Alternatively, a recently-added feature to sfdx-project.json is the ability to define the Perm Sets your tests need:

https://help.salesforce.com/s/articleView?id=release-notes.rn_sfdx_packaging_apex_test_access.htm&release=232&type=5

**Comment by mshanemc** [comment]
I think the error is legit, and that downgrading gets you into false-negatives that result from https://github.com/forcedotcom/cli/issues/2125.

**Comment by gregstackaero** [comment]
Thanks David & Shane. I think we will go down the path of assign perm sets via the sfdx-project.json file. It had never been an issue until the latest CLI version hence why I thought it might be an error. Let me know if you need more information. Thanks.

**Comment by gregstackaero** [comment]
An additional note to this, which I think is related as the errors are similar - we are having a similar issue trying to create a scratch org on a preview instance. adding the "--release preview" flag to the "sf org create scratch" command causes the subsequent "sf project deploy start" command to fail.

In summary, 
1. this sequence of commands works fine:
```
sf org create scratch -a GithubActionsOrg --target-dev-hub ${{ secrets.DEVHUB_USERNAME }} --definition-file config/project-scratch-def.json --set-default --duration-days 14 -w 10 --json
sf project deploy start -o GithubActionsOrg -w 30 --ignore-warnings --json
```

2. this sequence of commands fails during deploy step, with example errors pasted below
```
sf org create scratch -a GithubActionsOrg --target-dev-hub ${{ secrets.DEVHUB_USERNAME }} --definition-file config/project-scratch-def.json --set-default --duration-days 14 -w 10 --json --release preview
sf project deploy start -o GithubActionsOrg -w 30 --ignore-warnings --json
```

More than 400 component errors, all of the following nature
![image](https://github.com/forcedotcom/cli/assets/28810016/4ce58fd7-7a26-41c5-bffd-4ffada050338)

**Comment by mshanemc** [comment]
OH, the behavior is different between releases?!

You probably want to check the metadata api docs for v58 and see if there's any intentional changes across major versions.  If not, and if your project is using the same sourceApiVersion (in sfdx-project.json) then that might be a preview release regression and you'll want to get a case open to make sure it gets handled.

There are some threads on SFSE about that RecordType Error ex:
https://salesforce.stackexchange.com/questions/13457/custom-field-definition-id-bad-value-for-restricted-picklist-field-recordtype
https://help.salesforce.com/s/articleView?id=000384095&type=1
that might help fix the underlying issue on for both releases

**Comment by harshanav** [comment]
> Are you assigning a Perm Set with CRUD/FLS to the QuoteStatus object to the user (`UserInfo.getUserId()`) in your `@TestSetup` and then doing a `System.runAs()` for all of your tests?
> 
> The user that the package creation is being run as is NOT a Sys Admin and does not have full CRUD/FLS access.
> 
> Alternatively, a recently-added feature to sfdx-project.json is the ability to define the Perm Sets your tests need:
> 
> https://help.salesforce.com/s/articleView?id=release-notes.rn_sfdx_packaging_apex_test_access.htm&release=232&type=5

After doing your steps. It shows an error of "Permission Set cannot be added to the managed package because it is backed by a Permission Set License."
