### ISSUE TITLE
`sf schema generate field` doesn't work for Number-type fields

### ISSUE THREAD

**Issue by jkranz-rk** [forcedotcom/cli#2142]
### Summary

When using `sf schema generate field` to generate a Number-type field, the prompt for "Total number of digits" doesn't accept any input, and you must kill the process to escape. Understood that this command is in beta, and thus I'm not relying on it for any scripts, but I've found it useful so I thought it'd be valuable to report this bug.

### Steps To Reproduce:

1. Install the latest `sf` executable
2. Create an object `CustomObject__c`
3. Run `sf schema generate field --label "Number Field"`
4. Select your custom object
5. Accept the default `NumberField__c` for the API Name
6. Select `Number` for the field type
7. Accept the default `0` for number of decimal places
8. No default is provided for Total number of digits. Attempt to enter an allowed value, like `18` or `10`

### Expected result

A legitimate number of digits value should be accepted and either continue with prompts or generate the field xml file.

### Actual result

No values are accepted, hitting enter seems to effectively do nothing. To escape the prompt you must kill the process.

### System Information

- Which shell/terminal are you using? powershell on windows 11

```
sf version --verbose --json
{
  "cliVersion": "@salesforce/cli/1.77.6",
  "architecture": "win32-x64",
  "nodeVersion": "node-v19.6.1",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.9 (core)",
    "@oclif/plugin-commands 2.2.14 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 3.0.1 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.13 (core)",
    "@oclif/plugin-version 1.3.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.19 (core)",
    "@salesforce/cli 1.77.6 (core)",
    "apex 2.2.15 (core)",
    "auth 2.7.14 (core)",
    "data 2.3.14 (core)",
    "deploy-retrieve 1.8.18 (core)",
    "functions 1.21.4 (user)",
    "info 2.6.10 (core)",
    "limits 2.3.13 (core)",
    "login 1.2.8 (core)",
    "org 2.7.3 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.6 (core)",
    "sobject 0.1.18 (core)",
    "source 2.10.7 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.13 (core)",
    "trust 2.4.14 (core)",
    "user 2.3.10 (core)"
  ]
}
```

_Feel free to attach a screenshot_.
![image](https://github.com/forcedotcom/cli/assets/40637750/d7132c0f-c59e-44c9-b8f3-aeb2fc7350b8)

**Comment by iowillhoit** [comment]
:wave: This has been fixed in `plugin-sobject` `0.1.20`. It will be included in tomorrows `latest-rc`.
https://github.com/salesforcecli/plugin-sobject/pull/292
