### ISSUE TITLE
sf plugin migration guide is missing

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/cli#2145]
### Summary

Migration guide link in README.md of https://github.com/salesforcecli/command points to wiki page that does not exist.

### Steps To Reproduce:

1. Open https://github.com/salesforcecli/command in browser
2. Scroll down README.md and find paragraph "A migration guide is provided in the sf wiki..." and click the link to open the guide

### Expected result

The migration guide URL (https://github.com/salesforcecli/cli/wiki/Migrate-Plugins-Built-For-Sfdx) would exist, with the page showing instructions on how to migrate my old sfdx plugin to an sf plugin.

### Actual result

The URL https://github.com/salesforcecli/cli/wiki/Migrate-Plugins-Built-For-Sfdx  redirects to https://github.com/salesforcecli/cli/wiki/ and there does not seem to be a migration guide link in the table of contents.

**Comment by jshackell-sfdc** [comment]
Thanks for letting us know about this -- I see now that we mistakenly deleted some pages from the WIKI without realizing it!  We're working furiously to get 'em back.  Stay tuned!

**Comment by jshackell-sfdc** [comment]
@alan-morey , the page is back.  Thanks again for letting us know!
