### ISSUE TITLE
Docs say the sfdx CLI is deprecated, but the release notes don't and commands don't generate warnings

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/cli#2147]
### Summary

According to the [docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference.htm), all sfdx commands are now deprecated as of April 20th, and as it refers to sfdx (deprecated) in the index, they kind of suggest the entire executable is deprecated. The release notes don't seem to match up with this statement, and if I run a deprecated command I don't get any warnings about it. I'd also expect updating the CLI to give me a big warning if all the commands are deprecated, but it just tells me about the latest fixes.
Finally, the VS Code extension is still executing sfdx with deprecated commands, so I'm confused! 

### Steps To Reproduce:

1.  Execute `sfdx alias:list`  

### Expected result

This command is deprecated according to this [document](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_alias_list.htm). I'd expect a warning about this, according to the [CLI Deprecation Policy](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/sfdx_dev_cli_deprecation.htm)

### Actual result

The command completes without any warnings about deprecation

### System Information

- zsh

$ sfdx version --verbose --json
{
  "cliVersion": "sfdx-cli/7.200.7",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/Users/kbowden/.local/share/sfdx/client/7.200.7-499d9c2",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.9 (core)",
    "@oclif/plugin-commands 2.2.14 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 3.0.1 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.13 (core)",
    "@oclif/plugin-version 1.3.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.19 (core)",
    "apex 2.2.15 (core)",
    "auth 2.7.14 (core)",
    "community 2.2.11 (core)",
    "custom-metadata 2.1.19 (core)",
    "data 2.3.14 (core)",
    "deploy-retrieve 1.8.18 (core)",
    "dev 0.7.4 (user)",
    "info 2.6.10 (core)",
    "limits 2.3.13 (core)",
    "org 2.8.1 (core)",
    "packaging 1.16.11 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.6 (core)",
    "signups 1.4.14 (core)",
    "source 2.10.7 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.13 (core)",
    "trust 2.4.14 (core)",
    "user 2.3.10 (core)",
    "bbdoc 4.1.0 (user)",
    "bbmutation 1.1.0 (user)",
    "sfdx-cli 7.200.7 (core)"
  ]
}

### Additional information

I'm trying to figure out the likelihood of the existing tools/automation built with sfdx breaking, and how long I've got to migrate to sf, but it's really not clear to me what is happening.

**Comment by preddivari** [comment]
Thank you for your question and we apologize for the confusion. We are in the process of moving from 2 CLIs (`sfdx` and `sf`) to 1 . We're working hard to make the transition as seamless as possible for our customers, including updating all of our docs to reflect this change. However, we probably jumped ahead of the game when we marked all commands as deprecated in the Salesforce CLI Reference. We fixed that, and you should see the updated docs next week.

Currently some `sfdx` commands are marked as deprecated and we are encouraging you to try out the newer commands where and when applicable.

Our goal is to guide you through this transition with clear messages (where applicable) within the CLI commands themselves, along with documentation support. 

Thank you for following our release notes closely. Keep reading them for more updates.

**Comment by preddivari** [comment]
@keirbowden, as we are going from 2 CLIs (sfdx and sf) to 1, can we get 30 mins of your time for a user interview to better understand your current experiences with the CLI and how we can make this transition more seamless?
Looking forward to hearing from you!

Thanks!

**Comment by keirbowden** [comment]
@preddivari sure thing - I'm in the UK so usually late afternoon for me/first thing in the morning for you works well.

**Comment by mshanemc** [comment]
we changed the text to explain better that "that set of docs is deprecated."  In *some* cases the commands are similar/identical in the new docs
