### ISSUE TITLE
SF Project Retrieve Start --package-name also downloads "unpackaged" folder

### ISSUE THREAD

**Issue by jxbambrick** [forcedotcom/cli#2148]
### Summary

Running the command sf project retrieve start --package-name 'name-of-changeset' will also download the folder 'unpackaged' which contains all the metadata in the environment. 

### Steps To Reproduce:

Using the following version of SF: @salesforce/cli/1.79.0 darwin-arm64 node-v18.15.0

- create a change set with 1 or more components called testchangeset1
- open a terminal and navigate to a folder with a Salesforce project
- run the following command: sf project retrieve start --package-name testchangeset1
- confirm that the change set as well as the unpackaged folder are downloaded

### Expected result

- testchangeset1 should be downloaded, no other folders

### Actual result

- There are two folders: testchangeset1 and unpackaged

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`

{
  "cliVersion": "@salesforce/cli/1.79.0",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.1.0",
  "shell": "zsh",
  "rootPath": "/Users/bambrick/.local/share/sfdx/client/7.201.6-4edd82d/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.2.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 3.0.1 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.14 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.20 (core)",
    "@salesforce/cli 1.79.0 (core)",
    "apex 2.2.17 (core)",
    "auth 2.7.15 (core)",
    "data 2.3.16 (core)",
    "deploy-retrieve 1.8.20 (core)",
    "info 2.6.10 (core)",
    "limits 2.3.14 (core)",
    "login 1.2.8 (core)",
    "org 2.8.2 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.6 (core)",
    "sobject 0.1.18 (core)",
    "source 2.10.7 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.13 (core)",
    "trust 2.4.16 (core)",
    "user 2.3.10 (core)"
  ]
}

### Additional information

_Feel free to attach a screenshot_.

**Comment by iowillhoit** [comment]
Hey @jxbambrick, is this a recent change in behavior? If so, what version of the CLI where you seeing the desired behavior?

**Comment by jxbambrick** [comment]
I had an error after updating SFDX to the latest version. I don't know what my previous version was. In an attempt to resolve the error and update my deployment scripts, I switched from using SFDX commands to SF commands. I only need to download the specified change sets but it's including the unpackaged folder.

SFDX:
- sfdx force:source:retrieve -x package_xml -u user_alias_placeholder --json

SF: 
- sf project retrieve start--target-org --target-metadata-dir dir_placeholder --manifest manifest_placeholder --json

**Comment by iowillhoit** [comment]
Ok, I am still not able to reproduce your issue due to something unrelated, but I have been able to show that this used to work with `sfdx force:mdapi:retrieve -p testchangeset1 -r export-dir -o hub`

The structure created was (after unzipping):
```
.
|____testchangeset1
| |____package.xml
| |____objects
| | |____Broker__c.object
|____unpackaged.zip
```
Note that the `unpackaged.zip` only contained the the contents of the `unpackaged` directory
