### ISSUE TITLE
ENNOENT on most commands

### ISSUE THREAD

**Issue by laszlo-foldi-attentioncrm** [forcedotcom/cli#2150]
I'm having a similar (or same issue) issue like the closed #1416 

When i try to retrieve via the VS Code "Org Browser" feature, via a package.xml I get the following error:
13:03:56.323 Starting SFDX: Retrieve Source from Org

ENOENT: no such file or directory, stat 'd:.eslintignore'

Then I created the file in my D:\ root. After this I got the following error:
13:04:43.340 Starting SFDX: Retrieve Source from Org

ENOENT: no such file or directory, stat 'd:.forceignore'

It seems like to CLI thinks my project is in my D drive root.

Also I have the following versions:
{
"cliVersion": "sfdx-cli/7.201.6",
"architecture": "win32-x64",
"nodeVersion": "node-v18.15.0",
"osVersion": "Windows_NT 10.0.22621",
"shell": "cmd.exe",
"rootPath": "C:\Users\foldi\AppData\Local\sfdx\client\7.201.6-4edd82d",
"pluginVersions": [
"@oclif/plugin-autocomplete 2.2.0 (core)",
"@oclif/plugin-commands 2.2.15 (core)",
"@oclif/plugin-help 5.2.9 (core)",
"@oclif/plugin-not-found 2.3.23 (core)",
"@oclif/plugin-plugins 3.0.1 (core)",
"@oclif/plugin-search 0.0.17 (core)",
"@oclif/plugin-update 3.1.14 (core)",
"@oclif/plugin-version 1.3.4 (core)",
"@oclif/plugin-warn-if-update-available 2.0.36 (core)",
"@oclif/plugin-which 2.2.20 (core)",
"apex 2.2.17 (core)",
"auth 2.7.15 (core)",
"community 2.2.11 (core)",
"custom-metadata 2.1.20 (core)",
"data 2.3.16 (core)",
"deploy-retrieve 1.8.20 (core)",
"info 2.6.10 (core)",
"limits 2.3.14 (core)",
"org 2.8.2 (core)",
"packaging 1.16.11 (core)",
"schema 2.3.10 (core)",
"settings 1.4.6 (core)",
"signups 1.4.15 (core)",
"source 2.10.7 (core)",
"telemetry 2.2.0 (core)",
"templates 55.4.13 (core)",
"trust 2.4.16 (core)",
"user 2.3.10 (core)",
"sfdx-cli 7.201.6 (core)"
]
}

**Comment by laszlo-foldi-attentioncrm** [comment]
I tried running retrieve manually with the following result:

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\.git'
Preparing retrieve request... done
PS D:\Projects\AttentionBasePackage> 

EDIT:

Wanted to try to find a solution and started adding files to my D root, and it seems like the CLI is adamant that the project is located in D:\.

Here is a copy of my console output:

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\.git'
Preparing retrieve request... done

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\.gitignore'
Preparing retrieve request... done

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\.husky'
Preparing retrieve request... done

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\.prettierignore'
Preparing retrieve request... done

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\.prettierrc'
Preparing retrieve request... done

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\.sf'
Preparing retrieve request... done

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\.sfdx'
Preparing retrieve request... done

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\.vscode'
Preparing retrieve request... done

PS D:\Projects\AttentionBasePackage> sfdx force:source:retrieve -x manifest/attentioncrm.xml
Warning: We plan to deprecate this command in the future. Try using the "project retrieve start" command instead.
Error (1): ENOENT: no such file or directory, stat 'D:\attentioncrm'
Preparing retrieve request... done

PS D:\Projects\AttentionBasePackage>

**Comment by laszlo-foldi-attentioncrm** [comment]
Here is another command failing:

PS D:\Projects\AttentionBasePackage> sfdx project generate manifest --source-dir attentioncrm-ai --name allObjects
Error (1): ENOENT: no such file or directory, stat 'D:\.eslintignore'
PS D:\Projects\AttentionBasePackage>

**Comment by iowillhoit** [comment]
Hey @laszlo-foldi-attentioncrm, these types of issues are difficult to debug. Since it "went away" in the issue you linked it makes me wonder if it is a machine setup issue. Could please try to completely uninstall the CLI and reinstall it again? 
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

**Comment by laszlo-foldi-attentioncrm** [comment]
Hi @iowillhoit ,
I've tried a full reinstall of the CLI, and I'm still getting this error:
15:31:03.830 Starting SFDX: Retrieve Source from Org

ENOENT: no such file or directory, stat 'd:\.eslintignore'

All I tried to do is retrieve a single custom metadata.
![image](https://github.com/forcedotcom/cli/assets/47455710/76228881-0dbd-4377-bf89-bdaaa8202bfa)

EDIT:
To be clear, this issue is present when I try to invoke retrieve from command line.

**Comment by laszlo-foldi-attentioncrm** [comment]
I did some further testing, and now, after uninstalling the CLI, I uninstalled the extension pack from VS Code, then reinstalled everything, then recreated the project from scratch, and now, it seems to work, but this needs some more time to investigate. 

This issue is very strange, seems like the CLI just breaks itself after a certain period of time (or after a few updates).

**Comment by iowillhoit** [comment]
Thank you for testing all of this @laszlo-foldi-attentioncrm, I am glad that it is working for you now. If you are able to find a way to reliably reproduce this issue, we would be happy to look into what is going on!

**Comment by iowillhoit** [comment]
@laszlo-foldi-attentioncrm I am going to close this for now. If you find a way to replicate this feel free to reopen or create a new issue. Thanks

**Comment by laszlo-foldi-attentioncrm** [comment]
The issue came back. I'm facing the same issue and can't figure out what happened. I created a brand new project, connected to a DEMO org by Salesforce, and all of a sudden all operations in VS Code are failing.
