### ISSUE TITLE
sf project convert mdapi removes comment placeholders from objectTranslation files

### ISSUE THREAD

**Issue by vandyk-nw** [forcedotcom/cli#2151]
### Summary

sf project convert mdapi is removing comment placeholders from objectTranslation files.  This causes errors in the subsequent deploy.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1. with object translations in src/objectTranslations, the translation file contains:
`<picklistValues>
   <masterLabel>Aging with Dignity</masterLabel>
   <translation></translation>
</picklistValues>`
2. Run sf project convert mdapi --root-dir src --output-dir source
1.  check any translation file in the new source folder.  And see the translation is now:
`<picklistValues>
    <masterLabel>Aging with Dignity</masterLabel>
    <translation></translation>
</picklistValues>`

### Expected result

Expected the file to match what was in the source folder:
`<picklistValues>
   <masterLabel>Aging with Dignity</masterLabel>
   <translation></translation>
</picklistValues>`

### Actual result
`<picklistValues>
    <masterLabel>Aging with Dignity</masterLabel>
    <translation></translation>
</picklistValues>`

This results in a deployment/validation error:
Invalid picklist value: Aging with Dignity in field: Contact.NRI_Interest_Tagging_Journeys__c

### System Information

- Which shell/terminal are you using? (e.g. bash, zsh, powershell 5, powershell 7, cmd.exe, etc.)
cmd.exe

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`

{
  "cliVersion": "@salesforce/cli/1.77.1",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Progra~1\\sfdx\\sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.9 (core)",
    "@oclif/plugin-commands 2.2.14 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.7 (core)",
    "@oclif/plugin-search 0.0.16 (core)",
    "@oclif/plugin-update 3.1.13 (core)",
    "@oclif/plugin-version 1.3.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.19 (core)",
    "@salesforce/cli 1.77.1 (core)",
    "apex 2.2.14 (core)",
    "auth 2.7.14 (core)",
    "data 2.3.12 (core)",
    "deploy-retrieve 1.8.18 (core)",
    "info 2.6.8 (core)",
    "limits 2.3.13 (core)",
    "login 1.2.7 (core)",
    "org 2.7.2 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.5 (core)",
    "sobject 0.1.18 (core)",
    "source 2.10.5 (core)",
    "telemetry 2.1.6 (core)",
    "templates 55.4.11 (core)",
    "trust 2.4.12 (core)",
    "user 2.3.9 (core)"
  ]
}

### Additional information
This also happens if I run with sfdx:
{
  "cliVersion": "sfdx-cli/7.199.7",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Progra~1\\sfdx",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.9 (core)",
    "@oclif/plugin-commands 2.2.14 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.7 (core)",
    "@oclif/plugin-search 0.0.16 (core)",
    "@oclif/plugin-update 3.1.13 (core)",
    "@oclif/plugin-version 1.3.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.19 (core)",
    "apex 2.2.14 (core)",
    "auth 2.7.13 (core)",
    "community 2.2.11 (core)",
    "custom-metadata 2.1.17 (core)",
    "data 2.3.11 (core)",
    "deploy-retrieve 1.8.18 (core)",
    "info 2.6.8 (core)",
    "limits 2.3.13 (core)",
    "org 2.7.2 (core)",
    "packaging 1.16.8 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.5 (core)",
    "signups 1.4.13 (core)",
    "source 2.10.6 (core)",
    "telemetry 2.1.6 (core)",
    "templates 55.4.11 (core)",
    "trust 2.4.12 (core)",
    "user 2.3.9 (core)",
    "sfdmu 4.26.13 (user)",
    "sfdx-cli 7.199.7 (core)",
    "sfdx-git-delta 5.19.0 (user)"
  ]
}

**Comment by iowillhoit** [comment]
Hello @vandyk-nw, thanks for the issue. I think I know what is happening here. We recently updated our XML parser to a new major version. There is some configuration that needs to be done to support comments. Could you please put together a quick repository that reproduces this issue with translations on picklist values so that I can be certain the fix works? You can start with a fork of [Dreamhouse](https://github.com/dreamhouseapp/dreamhouse-lwc) if that is easier. Thanks

**Comment by iowillhoit** [comment]
Adding some additional context here so that it does not get lost. Both the `XMLParser` and `XMLBuilder` in [SDR](https://github.com/forcedotcom/source-deploy-retrieve) will need the `commentPropName` option added ([docs](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/docs/v4/2.XMLparseOptions.md#commentpropname)). However in some quick testing, I am worried that inline comments are not going to work well. For example:
`<label><!-- a comment -></label>`
transforms into
```
<label>
    <!-- a comment -->
</label>
```
I am worried the newlines will cause issues, this is why I am wanting a sample repo with objectTranslations so that we can properly test this.
