### ISSUE TITLE
sf deploy error deploying Custommetadata

### ISSUE THREAD

**Issue by phiff** [forcedotcom/cli#2152]
### Summary

When trying to do a ' sf project deploy start -x' deploy with only CustomMetadata in package.xml I get an error stating 'No source-backed components present in the package.'

'sfdx force:source:deploy -x' works like a charm

### Steps To Reproduce:

1. sf project deploy start -o [ORG] -x package.xml -w 30 --json > deployStatus.json

### Expected result

Deploy

### Actual result

Fails with "message": "No source-backed components present in the package."

### System Information

Windows 10
Cmder / Bash 221218 [64] stable 

- If you are using `sfdx`
	- Run `sfdx version --verbose [--json`]
- If you are using `sf`
	- Run `sf version --verbose --json`
- Paste the output here
### Additional information

_Feel free to attach a screenshot_.
![deployStatus](https://github.com/forcedotcom/cli/assets/43665539/fd57bd95-e291-4e5e-a85f-027b759520c3)

![package xml](https://github.com/forcedotcom/cli/assets/43665539/4fc02161-21e8-4940-bf33-cc3278086dd4)
![sf version](https://github.co
![sfdx version](https://github.com/forcedotcom/cli/assets/43665539/3476d112-dbff-4f3c-8fe6-316f7fb7946c)
m/forcedotcom/cli/assets/43665539/bc6960e3-2423-44aa-9e75-22e7621180fb)

**Comment by iowillhoit** [comment]
Hello @phiff, I am not able to replicate this issue. Make sure that all of the `members` listed in the `package.xml` actually exists in the project. To be certain, you can generate the manifest from the `customMetadata` directory itself with: `sf project manifest generate -p force-app/main/default/customMetadata`

[Here is a repo](https://github.com/iowillhoit/custom-metadata-type) I created to test the issue. If you are still seeing problems, please add instructions on how to replicate using my repo or fork it and modify it to cause the failure. Will be happy to investigate further once we can replicate it
