### ISSUE TITLE
[SF package version create] fail due to "missing" Profile 

### ISSUE THREAD

**Issue by arafesthain** [forcedotcom/cli#2153]
### Summary

When trying to create a new version of our package our Unit Tests are failing due to not found Profile.
The packaging was fine since nearly a year (with the exact same profile inside).

### Steps To Reproduce:

1. Create a package with a custom profile
2. Create a unit test that is Querying the 'Custom profile'
`Profile p = [SELECT Id FROM Profile WHERE Name = '[Custom] Profile'];`
3. Run `sf package version create --package PACKAGE_NAME --code-coverage -x -w 90` (same result with sfdx command)

### Expected result

The Query is returning the profile and package version create Run successfully.

### Actual result

The Query don't find the queried profile hence packaging is KO

```
Version create.... Create version status: Error
Error (1): Multiple errors occurred: 
(1) Apex Test Failure: Class.WL_Wozilla_OpportunityTest.makeData: line 6, column 1 System.QueryException: List has no rows for assignment to SObject
(2) Apex Test Failure: Class.WL_Wozilla_OpportunityTest.makeData: line 6, column 1 System.QueryException: List has no rows for assignment to SObject
(3) Apex Test Failure: Class.WL_Wozilla_OpportunityTest.makeData: line 6, column 1 System.QueryException: List has no rows for assignment to SObject
(4) Apex Test Failure: Class.WL_Wozilla_OpportunityTest.makeData: line 6, column 1 System.QueryException: List has no rows for assignment to SObject
(5) Apex Test Failure: Class.WL_Wozilla_OpportunityTest.makeData: line 6, column 1 System.QueryException: List has no rows for assignment to SObject
(6) Apex Test Failure: Class.WL_Wozilla_OpportunityTest.makeData: line 6, column 1 System.QueryException: List has no rows for assignment to SObject
Error: Process completed with exit code 1.
```

Profiles names screen shot if it can help:

![image](https://github.com/forcedotcom/cli/assets/13768869/51608fd9-6dd3-4433-ae75-b32cf8f50306)

**Nota : If I change back the queried Profile to a standard one, package creation is fine.**

### System Information

{
  "cliVersion": "sfdx-cli/7.201.6",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Linux 5.15.0-1037-azure",
  "shell": "bash"
}

Same error with older CLI versions

**Comment by iowillhoit** [comment]
From https://github.com/forcedotcom/cli/issues/2133

**Comment by iowillhoit** [comment]
At a glance, this looks like it might be a character encoding issue (`%5B` -> `[` and `%5d` -> `]`). Could you try removing the square brackets from your Custom Profile name? 

If you are still seeing an issue, can you put together a quick repo that reproduces the issue? Either from [Dreamhouse](https://github.com/dreamhouseapp/dreamhouse-lwc) or from a new scratch org created with `sf org create scratch`?

**Comment by arafesthain** [comment]
Hi @iowillhoit, I sent you an invite to access our repo: https://github.com/WorldlineSMI/sf-ps-wozilla

I tried without Special charachters --> Same result unfortunately

I'm dropping here the profile in case it can ring any bell:
```
<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <custom>true</custom>
    <layoutAssignments>
        <layout>Opportunity-FS Change Request Page Layout</layout>
        <recordType>Opportunity.FS_Change_Request</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>OpportunityLineItem-FS Change Request - Opportunity Product Layout</layout>
    </layoutAssignments>
    <userLicense>Salesforce</userLicense>
    <userPermissions>
        <enabled>true</enabled>
        <name>ActivitiesAccess</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>AddDirectMessageMembers</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ApexRestServices</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ApiEnabled</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>AssignTopics</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ChatterEditOwnPost</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ChatterFileLink</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ChatterInternalUser</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ConvertLeads</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>CreateCustomizeFilters</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>CreateCustomizeReports</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>CreateTopics</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>DistributeFromPersWksp</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>EditEvent</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>EditOppLineItemUnitPrice</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>EditTask</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>EditTopics</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>EmailMass</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>EmailSingle</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>EnableNotifications</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ExportReport</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ImportPersonal</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>LightningConsoleAllowedForUser</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>LightningExperienceUser</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ListEmailSend</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>MassInlineEdit</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>RunReports</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>SelectFilesFromSalesforce</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>SubscribeToLightningReports</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>TransactionalEmailSend</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>UseWebLink</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ViewDeveloperName</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ViewHelpLink</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ViewRoles</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ViewSetup</name>
    </userPermissions>
</Profile>
```

**Comment by AdashDev** [comment]
I can confirm we are also experiencing the same issue. The unit tests started to fail due to missing Admin profile, despite it being clearly included in the `foce-app` folder. We had to lower our version of sfdx (7.190.2 worked) and the issue was no longer present.

**Comment by arafesthain** [comment]
Hello I just found that it seems fine on windows on version sfdx-cli/7.191.1 win32-x64 node-v16.13.1 (was not able to reproduce on ubuntu latest)
and KO at least from 7.194.1 (on windows)

let's find the failing one :)

![image](https://github.com/forcedotcom/cli/assets/13768869/34df8eed-8aaa-4d52-b8df-6af610d5a090)

**Comment by arafesthain** [comment]
Playing me... 
![image](https://github.com/forcedotcom/cli/assets/13768869/910e0df1-8bd2-4fae-8a4e-5b2202e2a5c0)

![image](https://github.com/forcedotcom/cli/assets/13768869/45934c19-06e2-4bdd-b031-04bd2f6c87c1)

So the only difference between the 2 run:
- the full FAIL one is installing sfdx via pnpm (version 6.0.2)
- the full SUCCESS one is installing sfdx via npm

**Comment by iowillhoit** [comment]
Interesting, so just using `pnpm` is causing the failures? Well at this time, we do not officially support `pnpm` as an install method. Although we may look into it in the future. We have several release steps to ensure that we are deduping and shrink-wrapping dependencies for our `npm` installs to work properly. 

If you continue to see issues with an `npm` install, please add more details. Otherwise feel free to close this issue.

**Comment by arafesthain** [comment]
#2218

**Comment by mwannamaker41** [comment]
It is getting harder and harder to use unlocked packages.  Now ProfileActionOverride are in customapplication metadata.  This means now you won't be able to package customapplication metadata if it references profileactionoverride because the profile is not there.

And the metadata coverage report says that Profiles are supported in unlocked packages.

<img width="686" alt="image" src="https://github.com/forcedotcom/cli/assets/10143429/3fd00a1e-a96e-4715-9bf7-f62f73365ce4">

**Comment by dudunato** [comment]
Facing the same issue with package creation on our github actions. Very frustrating. Any workaround?

**Comment by dalden1981** [comment]
Is there any movement on this?
