### ISSUE TITLE
sf deployment fails when deploying permission set groups in a namespaced org w/o the namespace in the meta tags

### ISSUE THREAD

**Issue by aozomaro** [forcedotcom/cli#2156]
### Summary

* I have a permission set group that references permission sets in my project.
* The project is namespaced
* However, the namespace is not added when referencing permission set meta tags in the permission set group. E.g.: `<permissionSets>SomePermissionSetWhichExcludesNamespacePrefix</permissionSets>`
* When I deploy this permission set group to a scratch org I get the following error:

"Cannot create permission set group components since the following permission set names are invalid: SomePermissionSetWhichExcludesNamespacePrefix"

### Steps To Reproduce:

1. Create a permission set group with permission sets (do not reference the namespace in the permission set)
2. Create a scratch org with a Namespace
3. Deploy the metadata to the scratch org

### Expected result

Successful deployment

### Actual result

"Cannot create permission set group components since the following permission set names are invalid: SomePermissionSetWhichExcludesNamespacePrefix"

### System Information

{
  "cliVersion": "sfdx-cli/7.198.7",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.3.0",
  "shell": "zsh",
  "rootPath": "/Users/aozomaro/.local/share/sfdx/client/7.198.7-cad6700",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.9 (core)",
    "@oclif/plugin-commands 2.2.14 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 2.4.6 (core)",
    "@oclif/plugin-search 0.0.16 (core)",
    "@oclif/plugin-update 3.1.12 (core)",
    "@oclif/plugin-version 1.3.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.35 (core)",
    "@oclif/plugin-which 2.2.19 (core)",
    "apex 2.2.13 (core)",
    "auth 2.7.12 (core)",
    "community 2.2.10 (core)",
    "custom-metadata 2.1.15 (core)",
    "data 2.3.10 (core)",
    "deploy-retrieve 1.8.15 (core)",
    "info 2.6.7 (core)",
    "limits 2.3.13 (core)",
    "org 2.7.0 (core)",
    "packaging 1.16.6 (core)",
    "schema 2.3.8 (core)",
    "settings 1.4.4 (core)",
    "signups 1.4.12 (core)",
    "source 2.10.3 (core)",
    "telemetry 2.1.4 (core)",
    "templates 55.4.9 (core)",
    "trust 2.4.9 (core)",
    "user 2.3.8 (core)",
    "sfdx-cli 7.198.7 (core)"
  ]
}

**Comment by aozomaro** [comment]
bump

**Comment by cristiand391** [comment]
Hey @aozomaro , sorry for the late reply.

Thanks for the report, I'll close this as a dup #1803, will add to our list so it doesn't get lost.
