### ISSUE TITLE
Add ls-lint to sfdx projects

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#2160]
**Is your feature request related to a problem? Please describe.**
No

**What are you trying to do**
Standardize the way sfdx projects enforce file/directory naming conventions.

**Describe the solution you'd like**
- sfdx projects must be created with `ls-lint`
- sfdx projects must have a standard set of `ls-lint` rules.
- rules must be overwritten
- must be called by an sfdx hook (pre commit|push prefarably)
- include ls-lint in the lint script. I want to run es-lint and ls-lint when typing `npm run lint`
- it could be released as a plugin called @salesforce/plugin-ls-lint and later, based on telemetry data, you can decide if it makes sense to add it, or not, in the list of core plugins.

https://ls-lint.org/

You could create a new package that bundles `ls-lint` with your pre defined set of rules, and then add it in the dev dependencies of sfdx projects.

Benefits:

- less time reviewing PRs to check if files and directories are following naming conventions
- ease project onboarding
- avoid deploying metadata that arent following naming conventions

**Describe alternatives you've considered**
I can add `ls-lint` to every sfdx project I work on... but I would have to spend time convincing people about its benefits, and every sfdx project could end up having different set of naming conventions.

**Additional context**
N/A

still waiting my gift...

**Comment by iowillhoit** [comment]
Thanks for the feature request, it is now in our backlog. Some the folder structure ls-lint config could be created from the metadata registry.
