### ISSUE TITLE
sf apex run test -r json does not return JSON

### ISSUE THREAD

**Issue by phiff** [forcedotcom/cli#2162]
### Summary

All of a sudden 'sf apex run test -r json' does not return JSON but returns

- Run "sf apex get test -i 7075p0000H2Hrx8 -o _myusername_" to retrieve test results

### Steps To Reproduce:

1.  sf apex run test -o $APEXTEST_ENV -l ${TESTLEVEL} -r json > ${APEXDIR}/${RUNFILE}
where $APEXTEST_ENV = TARGET-ORG, ${TESTLEVEL} = RunLocalTests and ${APEXDIR}/${RUNFILE} = outputfile
2. outputfile only contains the text "Run "sf apex get test -i 7075p0000H2Hrx8 -o _myusername_" to retrieve test results"

### Expected result

Output file should hold a JSON like 
{
  "status": 100,
  "result": {
    "summary": {
      "outcome": "Failed",
      "testsRan": 3733,
      "passing": 3640,
      "failing": 93,
      "skipped": 0,
      "passRate": "98%",
      "failRate": "2%",
      "testStartTime": "Mon May 15 2023 00.15.16",
      "testExecutionTime": "5592431 ms",
      "testTotalTime": "5592431 ms",
      "commandTime": "814 ms",
 .
.
.etc

### Actual result

outputfile only contains the text "Run "sf apex get test -i 7075p0000H2Hrx8 -o _myusername_" to retrieve test results"

### System Information

bash

- If you are using `sfdx`
	- Run `sfdx version --verbose --json`
- If you are using `sf`
	- Run `sf version --verbose --json`
	- 
![sf version](https://github.com/forcedotcom/cli/assets/43665539/137f847d-b440-4a37-9ef6-d6899fbd5c62)
![sfdx version](https://github.com/forcedotcom/cli/assets/43665539/94268f5d-13d4-44a6-939b-f6404b091c4d)

- Paste the output here
### Additional information

_Feel free to attach a screenshot_.

**Comment by phiff** [comment]
Last good / correct result fron -r JSON was before I upgraded to sf 1.77.6-2ac0f05

**Comment by MarcDBehr** [comment]
Have you tried adding the -w (wait)  and -y (synchronously) flag? I recommend adding "-w 20 -y" to run the tests synchronously and wait up to 20 minutes for the results. You should then get the JSON results.

**Comment by iowillhoit** [comment]
Hey @phiff, thanks for the issue. We recently changed these tests to run async by default to fix another issue. @MarcDBehr is correct, try running the command with the `-y` flag to run the tests synchronously. Note that there is a difference between the `-r` flag to specify the type of test report format and using the `--json` flag on a command.

 Alternatively, you can run the following:
- `sf apex run test --json`
  - This will return the `testRunId`
- The you can run `sf apex get test -i THE_ID -r json` to get the results in `json` format. 


That said, I will create a ticket and make it clear that the async flag is required when you are passing `--result-format` to `run`.
