### ISSUE TITLE
SFDX doesn't support Standard Value Sets for ASM (Vlocity) picklists migrated into the core 

### ISSUE THREAD

**Issue by pgumiela** [forcedotcom/cli#2163]
### Summary

SFDX doesn't support Standard Value Sets for ASM (Vlocity) picklists migrated into the core 

### Steps To Reproduce:

Please request a Media Cloud org with ASM from the following link:
https://success.vlocity.com/s/request-org?recordId=0TT3c000000JFvn&appSuite=a443m000001ZWU9AAO&libId=aBQ3m000000KysZGAS

Let's take AdQuoteLine.MaximumFrequencyInterval as an example. This picklist field is now transitioned into the core
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_adquoteline.htm
but we don't have a corresponding Standard Value Set even in API 58.0:
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/standardvalueset_names.htm

### Expected result

All Vlocity/Industries picklists transitioned into the core should be fully supported by SFDX, including Standard Value Sets. 

### Actual result

SFDX can only retrieve picklist definition but we can't retrieve/deploy actual picklist values of ASM-related fields.

### System Information

Terminal: Powershell

SFDX Version Output:
`{
  "cliVersion": "sfdx-cli/7.201.6",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.2.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 3.0.1 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.14 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.20 (core)",
    "apex 2.2.17 (core)",
    "auth 2.7.15 (core)",
    "community 2.2.11 (core)",
    "custom-metadata 2.1.20 (core)",
    "data 2.3.16 (core)",
    "deploy-retrieve 1.8.20 (core)",
    "info 2.6.10 (core)",
    "limits 2.3.14 (core)",
    "org 2.8.2 (core)",
    "packaging 1.16.11 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.6 (core)",
    "signups 1.4.15 (core)",
    "source 2.10.7 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.13 (core)",
    "trust 2.4.16 (core)",
    "user 2.3.10 (core)",
    "sfdx-cli 7.201.6 (core)",
    "vlocityestools 0.24.2 (user)"
  ]`

**Comment by mshanemc** [comment]
Your best option is to open a Support Case and ask that those types be added to the metadata API.  Once that happens, the CLI should be able to work with them

**Comment by pgumiela** [comment]
@mshanemc,
Case #44676101 is already there (created on May 25th).

Based on the conversation with the support, these ASM-related Standard Value Sets can be retrieved using package.xml. Can you please confirm this on your end? If it's looking good, can we include these metadata entries in SFDX?

[Package-Case-44676101.txt](https://github.com/forcedotcom/cli/files/11934346/Package-Case-44676101.txt)

**Comment by shetzel** [comment]
Support was added to the SDR library here: https://github.com/forcedotcom/source-deploy-retrieve/pull/1031
It should be available in the nightly CLI release tonight.

**Comment by pgumiela** [comment]
@shetzel,
Thanks a lot. I've replied on the PR level as I believe we should include both AQLMUFInterval and AQLMFrequencyInterval:
- AdQuoteLine.MaximumFrequencyInterval (AQLMFrequencyInterval)
- AdQuoteLine.MaximumUserFrequencyInterval (AQLMUFInterval)
Can you please cross-check that?

**Comment by iowillhoit** [comment]
Hey @pgumiela, I am doing some issue cleanup. It looks like both values `AQLMUFInterval` and `AQLMFrequencyInterval` now exist in the registry ([here](https://github.com/forcedotcom/source-deploy-retrieve/blob/81aba1ca66a328f6bf7d094ea839f366731c4420/src/registry/stdValueSetRegistry.json#L31-L32)).

If you are still seeing problems with this, please open a new Issue.
