### ISSUE TITLE
sf package create version does not add custom profiles in sourceProfiles

### ISSUE THREAD

**Issue by oldgunner** [forcedotcom/cli#2164]
### Summary

When I created new version package via `sf package create version -d force-app -x -w 20`  there are no custom profiles in pachage version metadata

### Steps To Reproduce:

**Repository to reproduce:** I can not share meta cause it is in azure private folder

1.   Type `sf package create version -d force-app -x -w 20`  in bash terminal and press enter

### Expected result

Via SOQL `SELECT Id, BuildNumber, CreatedDate, SubscriberPackageVersion.Profiles FROM Package2Version ORDER BY CreatedDate DESC LIMIT 1`  on my dev hub I would like to see custom profiles in package version metadata.
```
"sourceProfiles": [
    {
      "label": "No Access",
      "value": "__noAccess__"
    },
    {
      "label": "Full Access",
      "value": "__allAccess__"
    },
    {
      "label": "Custom Profile 1",
      "value": "Custom Profile 1"
    },
    {
      "label": "Custom Profile 2",
      "value": "Custom Profile 2"
    },
    {
      "label": "Custom Profile 3",
      "value": "Custom Profile 3"
    },
    {
      "label": "Custom Profile N",
      "value": "Custom Profile N"
    }
  ]
```

### Actual result

Via SOQL `SELECT Id, BuildNumber, CreatedDate, SubscriberPackageVersion.Profiles FROM Package2Version ORDER BY CreatedDate DESC LIMIT 1`  on my dev hub I a
```
"sourceProfiles": [
    {
      "label": "No Access",
      "value": "__noAccess__"
    },
    {
      "label": "Full Access",
      "value": "__allAccess__"
    }
  ]
```

### System Information

- Which shell/terminal are you using? - I used **bash** terminal

sfdx result
{
  "cliVersion": "sfdx-cli/7.201.6",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\vitali.gribko\\AppData\\Local\\sfdx\\client\\7.201.6-4edd82d",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.2.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 3.0.1 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.14 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.20 (core)",
    "apex 2.2.17 (core)",
    "auth 2.7.15 (core)",
    "community 2.2.11 (core)",
    "custom-metadata 2.1.20 (core)",
    "data 2.3.16 (core)",
    "deploy-retrieve 1.8.20 (core)",
    "info 2.6.10 (core)",
    "limits 2.3.14 (core)",
    "org 2.8.2 (core)",
    "packaging 1.16.11 (core)",
    "schema 2.3.10 (core)",
    "settings 1.4.6 (core)",
    "signups 1.4.15 (core)",
    "source 2.10.7 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.13 (core)",
    "trust 2.4.16 (core)",
    "user 2.3.10 (core)",
    "sfdx-cli 7.201.6 (core)"
  ]
}

sf resul 
{
  "cliVersion": "@salesforce/cli/1.79.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\vitali.gribko\\AppData\\Local\\sfdx\\client\\7.201.6-4edd82d\\sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.2.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.23 (core)",
    "@oclif/plugin-plugins 3.0.1 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.14 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.36 (core)",
    "@oclif/plugin-which 2.2.20 (core)",
    "@salesforce/cli 1.79.0 (core)",
    "apex 2.2.17 (core)",
    "auth 2.7.15 (core)",
    "data 2.3.16 (core)",
    "deploy-retrieve 1.8.20 (core)",
    "functions 1.21.9 (user)",
    "info 2.6.10 (core)",
    "limits 2.3.14 (core)",
    "login 1.2.8 (core)",
    "org 2.8.2 (core)",
    "packaging 1.17.1 (user)",
    "schema 2.3.10 (core)",
    "settings 1.4.6 (core)",
    "sobject 0.1.18 (core)",
    "source 2.10.7 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.13 (core)",
    "trust 2.4.16 (core)",
    "user 2.3.10 (core)"
  ]
}

### Additional information
The case was created 18th of May and did not resolved as for now.

**Comment by oldgunner** [comment]
After a millions and billions of investigation hours I found that "includeProfileUserLicenses": true attribute from packageDirectories in my sfdx-project.json file was accidentally deleted in one of previous merges.

Adding this attribute helped fixing the issue and all custom profiles appeared in package.

**Comment by iowillhoit** [comment]
I appreciate the follow up @oldgunner, hopefully this will help save someone else some trouble 👍
