### ISSUE TITLE
Inconsistency of `-t | --tests` flag between `sf project deploy start` and `sf apex run test`

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/cli#2165]
### Summary

`sf apex run test` requires `-t | --tests` flag argument to be provided as comma seperated list, where as `sf project deploy start` requires `-t | --tests` flag argument to be provided as space seperated list. This leads to confusion and simple mistakes when moving between the two commands as part of working with the CLI.

### Steps To Reproduce:
1. Execute `sf apex run test --help` and refer to `-t | --tests` flag description
    > -t, --tests=<value>  Comma-separated list of Apex test class names or IDs and, if applicable, test methods to run; default is all 
tests.
    >
    >  If you specify --tests, you can't specify --class-names or --suite-names
3. Execute `sf project deploy start --help` and refer `-t | --tests` flag description
    > -t, --tests=<value>...  Apex tests to run when --test-level is RunSpecifiedTests.
    >
    > If a test name contains a space, enclose it in double quotes.
    > For multiple test names, use one of the following formats:
    >
    > - Repeat the flag for multiple test names: --tests Test1 --tests Test2 --tests "Test With Space"
    > - Separate the test names with spaces: --tests Test1 Test2 "Test With Space"
4. Compare flag descriptions, formats are different

### Expected result

Expected that the `-t | --tests` flag format for executing tests in both `sf apex run test` and `sf project deploy start` would be in a consistent format so that I have an improved developer experience and avoid mixing up the argument formats.

### Actual result

Different `-t | --tests` flag formats between the two commands, which often results in error when I specify the tests in the wrong format depending on the command being exectued and requires I refer to help each time I make a mistake.

### System Information

```
 CLI Version:
        @salesforce/cli/1.79.5

 Architecture:
        linux-x64

 Node Version:
        node-v18.16.0

 Plugin Version:
        @oclif/plugin-autocomplete 2.2.0 (core)
        @oclif/plugin-commands 2.2.15 (core)
        @oclif/plugin-help 5.2.9 (core)
        @oclif/plugin-not-found 2.3.23 (core)
        @oclif/plugin-plugins 3.0.1 (core)
        @oclif/plugin-search 0.0.17 (core)
        @oclif/plugin-update 3.1.15 (core)
        @oclif/plugin-version 1.3.4 (core)
        @oclif/plugin-warn-if-update-available 2.0.37 (core)
        @oclif/plugin-which 2.2.20 (core)
        @salesforce/cli 1.79.5 (core)
        apex 2.2.19 (core)
        auth 2.7.15 (core)
        data 2.3.18 (core)
        deploy-retrieve 1.9.1 (core)
        info 2.6.13 (core)
        limits 2.3.15 (core)
        login 1.2.9 (core)
        org 2.9.0 (core)
        schema 2.3.10 (core)
        settings 1.4.8 (core)
        signups 1.4.14 (user)
        sobject 0.1.19 (core)
        source 2.10.9 (core)
        telemetry 2.2.0 (core)
        templates 55.4.15 (core)
        trust 2.4.18 (core)
        user 2.3.13 (core)
        gr-sfdx-plugin 0.0.0 (link) /home/alan.morey/repos/salesforce/gr-sfdx-plugin

 OS and Version:
        Linux 5.19.0-41-generic

 Shell:
        zsh

 Root Path:
        /home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli
```

**Comment by iowillhoit** [comment]
Good call @alan-morey, I do think these should be consistent. 

Note: This is ultimately processed in [salesforcedx-apex](https://github.com/forcedotcom/salesforcedx-apex/blob/main/src/tests/testService.ts#L398) (`apex-node`). Since this is a shared library, it may be best to add `allowMultiple` in [plugin-apex](https://github.com/salesforcecli/plugin-apex/blob/main/src/commands/apex/run/test.ts#LL80) and pass it to `apex-node` as a comma-delimited string. Otherwise it could be a breaking change for other consumers of `apex-node`

We could also use `arrayWithDeprecation` in `plugin-apex`
