### ISSUE TITLE
Instanceurl is ignored when authenticating towards a sandbox using jwt:grant

### ISSUE THREAD

**Issue by fredrikstaahl** [forcedotcom/cli#217]
### Summary

I'm trying to authenticate towards my sandbox using jwt:grant by specifying the clientId, username and the instanceurl of my sandbox. I run the following command:

> sfdx force:auth:jwt:grant --clientid $DEV_CONSUMER_KEY --jwtkeyfile assets/server.key --username $DEV_SFDX_USER -r https://myorg--dev.my.salesforce.com

I get the following error message:

> ERROR running force:auth:jwt:grant:  This org appears to have a problem with its OAuth configuration. Reason: invalid_grant - invalid assertion 
> username: {myemail@example.com.dev}, --censored 
> clientId: {myClientId}, --censored
**> loginUrl: https://login.salesforce.com,-- loginUrl is pointing towards production, even though I specified an instance url** 
> privateKey: assets/server.key 
> 

### Steps To Reproduce:

1.  Run the jwt:grant towards a sandbox, specify the instanceurl param "-r" and specify your sandbox url 

### Expected result

the loginUrl should be the specified instanceurl and the authentication should succeed.

### Actual result

The loginUrl used is https://login.salesforce.com instead of the instanceurl I specified.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
7.28.
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
Circleci pipeline.

**OS and version**:
N/A

**Comment by mshanemc** [comment]
I think this was closed by the above changes.  Please reopen if not.
