### ISSUE TITLE
sfdx-project.json is not updating after the Package and package Version Deletion

### ISSUE THREAD

**Issue by Mars-PrakashSaini** [forcedotcom/cli#2173]
### Summary

sfdx-project.json is not updating after the Package and package Version Deletion

### Steps To Reproduce:

1. Setup > DevHub > Enable Enable Dev Hub, Enable Source Tracking in Developer and Developer Pro Sandboxes, Enable Unlocked 
Packages and Second-Generation Managed Packages
2. Authorize the Devhub Org,
3. Create Scratch org
4. Create a package > This will update the sfdx-project.json with created package details
5. Create a package version > This will update the  sfdx-project.json with created package version details
6. Now Delete the Package Version and Delete package > and check if it's updating the sfdx-project.json file (Removing the details created in step 5 and step 4)

### Expected result

The Deleted Package or Package Version should be deleted from sfdx-project.json file 

### Actual result

The Deleted Package or Package Version is not getting deleted from sfdx-project.json file 

### System Information
Operating System: … Windows
node version: … 18.0.0
git version: … 2.39.2.windows.1
sfdx version: … sfdx-cli/7.197.8
sgd plugin version: … v5.18.0

**Comment by cristiand391** [comment]
Hi @Mars-PrakashSaini I don't see this was happening before in the legacy commands. Is this a feature request or was this working before in an old version of the CLI?
