### ISSUE TITLE
Allow project delete source to run specific tests

### ISSUE THREAD

**Issue by jefersonchaves** [forcedotcom/cli#2175]
**Is your feature request related to a problem? Please describe.**
Destructive changes are usually laser-focused, and sometimes they are needed as a second or even third step to clean-up, given the need first to remove the references, sometimes not working as `--post-destructive-changes `.

This is related to #971 (thanks a lot for adding this).

**What are you trying to do**
I want to be able to run a deletion and specify the tests to be executed. Example: I may want to delete one class and run a set of unit tests instead of all of them. This enhancement can speed up destructive deployment with this command.

**Describe the solution you'd like**
Add the flag `--tests` and the value `RunSpecifiedTests` as a valid test level on flag `--test-level`.

**Describe alternatives you've considered**
The workaround is either to use `project deploy start` with `--post-destructive-changes` or create a secondary package and run a separate `project deploy start` with a separate package and the targeted tests.

**Comment by AllanOricil** [comment]
Couldn't this be done with `sfdx force:source:deploy`  with `--post-destructive-changes` and `--tests`?

**Comment by jefersonchaves** [comment]
Yes, that is on the workaround section. So, yep but it means crafting a package while the delete could be easier.

**Comment by shetzel** [comment]
This is now in the latest CLIs: sfdx 7.208.10 / sf 1.85.8
