### ISSUE TITLE
named in package.xml, but was not found in zipped directory

### ISSUE THREAD

**Issue by KK-Singh** [forcedotcom/cli#2182]
All of a sudden when deploying to production, It is saying "named in package.xml, but was not found in zipped directory" almost for all things.
two days before it was running good. we deployed the same in UAT environment using same Azure devops pipeline. Now it is showing error and even for UAT and other lower environment. 

.........
Job ID | 0AfAq000007DgIWKA0
MDAPI PROGRESS | █████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 385/1643 Components
MDAPI PROGRESS | █████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 385/1643 Components

=== Component Failures [1258]
TYPE   FILE                     NAME                                                                        PROBLEM
─────  ───────────────────────  ──────────────────────────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  KNSeM_mdapi/package.xml  Account                                                                     An object 'Account' of type CustomObject was named in package.xml, but was not found in zipped directory
Error  KNSeM_mdapi/package.xml  Account.Account_Compact_Layout                                              An object 'Account.Account_Compact_Layout' of type CompactLayout was named in package.xml, but was not found in zipped directory
Error  KNSeM_mdapi/package.xml  Account.Account_List                                                        An object 'Account.Account_List' of type ListView was named in package.xml, but was not found in zipped directory
Error  KNSeM_mdapi/package.xml  Account.ACN_Age_group__c                                                    An object 'Account.ACN_Age_group__c' of type CustomField was named in package.xml, but was not found in zipped directory
Error  KNSeM_mdapi/package.xml  Account.ACN_Care_Team__c                                                    An object 'Account.ACN_Care_Team__c' of type CustomField was named in package.xml, but was not found in zipped directory
Error  KNSeM_mdapi/package.xml  Account.ACN_PartnerRegistrationURL__c                                       An object 'Account.ACN_PartnerRegistrationURL__c' of type CustomField was named in package.xml, but was not found in zipped directory
Error  KNSeM_mdapi/package.xml  Account.Address_1__c                                                        An object 'Account.Address_1__c' of type CustomField was named in package.xml, but was not found in zipped directory
Error  KNSeM_mdapi/package.xml  Account.Address_2__c                                                        An object 'Account.Address_2__c' of type CustomField was named in package.xml, but was not found in zipped directory
Error  KNSeM_mdapi/package.xml  Account.Administered_Telephone__c                                           An object 'Account.Administered_Telephone__c' of type CustomField was named in package.xml, but was not found in zipped directory
Error  KNSeM_mdapi/package.xml  Account.Adults_65_years_of_age_and_older__c                                 An object 'Account.Adults_65_years_of_age_and_older__c' of type CustomField was named in package.xml, but was not found in zipped directory
..........................................................................

I am very confused what is causing this issue?

**Comment by shetzel** [comment]
Please provide the required information from the issue template.

**Comment by KK-Singh** [comment]
what information is required? kindly elaborate.
Also what are the possible reasons for this kind of error?

**Comment by shetzel** [comment]
When you create a new issue for this repo it is pre-populated with a template of all the information we require.  New versions of the CLI are published nightly so at the very least we need to know what version you are using.  What command (and all flags) cause the problem?  We need to be able to reproduce the problem you are seeing so the easier you are able to make that for us the quicker the resolution will be.

That error comes from the org (specifically the metadata API) and it means that it was expecting a file named in the manifest to exist in the zip file generated/sent by the CLI but didn't find a match.  Several things _could_ cause that.  The types in the error you posted are all children of CustomObject so maybe that is the key to reproducing this.

**Comment by cristiand391** [comment]
@KK-Singh here's the issue template:
https://raw.githubusercontent.com/forcedotcom/cli/main/.github/ISSUE_TEMPLATE/bug_report.md

As Steve said, once you provide all the required info and a way to repro the issue we can take a look at it.
