### ISSUE TITLE
sf package version create command return an error in cli version higher than sfdx-cli/7.198.7

### ISSUE THREAD

**Issue by martinzurkowski** [forcedotcom/cli#2192]
### Summary
sf package version create  return 

=== Errors
Warning: (1) MYAPPLICATION: invalid cross reference id

### Steps To Reproduce:

run: 
**sf package version create** --target-dev-hub MYDEVHUB --package 0HoXXXXXXXXXXXX --installation-key MYKEY --json --code-coverage --skip-ancestor-check

### Expected result

package version can be created successful.

### Actual result

	=== Errors
	Warning: (1) MYAPPLICATION: invalid cross reference id

### System Information

sfdx-cli/7.198.7 win32-x64 node-v18.12.0

folders:	
	force-app\main\default\applications
	force-app\main\default\aura
	force-app\main\default\brandingSets
	force-app\main\default\classes
	force-app\main\default\components
	force-app\main\default\contentassets
	force-app\main\default\customMetadata
	force-app\main\default\customPermissions
	force-app\main\default\dashboards
	force-app\main\default\duplicateRules
	force-app\main\default\email
	force-app\main\default\flexipages
	force-app\main\default\flows
	force-app\main\default\labels
	force-app\main\default\layouts
	force-app\main\default\lightningExperienceThemes
	force-app\main\default\lwc
	force-app\main\default\matchingRules
	force-app\main\default\messageChannels
	force-app\main\default\namedCredentials
	force-app\main\default\notificationtypes
	force-app\main\default\objects
	force-app\main\default\objectTranslations
	force-app\main\default\pages
	force-app\main\default\permissionsetgroups
	force-app\main\default\permissionsets
	force-app\main\default\profiles
	force-app\main\default\quickActions
	force-app\main\default\remoteSiteSettings
	force-app\main\default\reports
	force-app\main\default\reportTypes
	force-app\main\default\settings
	force-app\main\default\staticresources
	force-app\main\default\tabs
	force-app\main\default\triggers
	force-app\main\default\workflows

	force-app\main\default\applications
		MYAPPLICATION.app-meta.xml contains profileActionOverrides with profile's

### Additional information
The command: 

**sfdx package:version:create** -v MYDEVHUB --package 0HoXXXXXXXXXXXX --installation-key MYKEY --json --code-coverage --skip-ancestor-check

works without problems up to the sfdx-cli/7.198.7 version. In all higher versions, the same error as with the **sf** command is returned.

**Comment by cristiand391** [comment]
@martinzurkowskiSST are you able to create a repro in a new project or by modifying [dreamhouse](https://github.com/trailheadapps/dreamhouse-lwc/)?

I don't see any doc'd change related to packaging right after v7.198.6 https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx#71986-april-27-2023
and seems your case is something specific with your project structure.

**Comment by martinzurkowski** [comment]
@cristiand391, I haven't tried a new project with dreamhouse. 
Why should I? Of course, every project is different. 

The first question for us is why the command:
sfdx package:version:create 
works correctly up to version 7.198.7 and then no longer in any version?  Especially if nothing is supposed to have changed in the new versions.
In our project nothing has changed in the metadata.

The other question is why the command: 
sf package version create
handles the processing of the metadata for packaging quite differently?

**Comment by cristiand391** [comment]
> The first question for us is why the command:
sfdx package:version:create
works correctly up to version 7.198.7 and then no longer in any version? Especially if nothing is supposed to have changed in the new versions.
In our project nothing has changed in the metadata.

I looked again and don't see huge change between v7.198 and v7.199 related to packaging so I'm not sure yet.

> The other question is why the command:
sf package version create
handles the processing of the metadata for packaging quite differently?

both `sf` and `sfdx` share the code for those commands they are 100% identical you shouldn't see any difference.

We'll need more logs to investigate further, can you try creating a package version with **sfdx > 7.198.7** (which fails in your project) using the `doctor` command?: Example:

`sfdx --doctor "package version create --target-dev-hub MYDEVHUB --package 0HoXXXXXXXXXXXX --installation-key MYKEY --json --code-coverage --skip-ancestor-check"`

the `doctor` command will write 3 log files in your current dir (make sure to redact sensitive info).

**Comment by gsbasso** [comment]
We too are seeing this error. In our case the issue seems to be related to profile references in `profileActionOverrides` elements of the `.app-meta.xml` file. If we remove the `profileActionOverrides` content the package version create runs successfully.

I have attached the log files produced by `doctor`. You can actually see it is removing the profile `BVS-Standard-Profile` which is referenced within the `profileActionOverrides` element of the `.app-meta.xml` file. The profile is in the same package folder.

It looks to me like a profile is removed if **any** content is being removed which doesn't seem correct to me.

[1686772644781-doctor.zip](https://github.com/forcedotcom/cli/files/11750590/1686772644781-doctor.zip)

**Comment by gsbasso** [comment]
To reproduce the issue build the `bvs_app` package in the attached modified `dreamhouse` project.

[dreamhouse-lwc-main.zip](https://github.com/forcedotcom/cli/files/11762304/dreamhouse-lwc-main.zip)

**Comment by martinzurkowski** [comment]
Hello @cristiand391, 

sorry for the late reply. 
I have removed the _profileActionOverrides_ entries from the .app-meta.xml (as @gsbasso has also written), then the creation of the package version works.

I wonder why up to the version < 7.198.7 these entries do not throw an error, because according to the documentation it shouldn't work in the package ([https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_profileactionoverride.htm])

**Comment by gsbasso** [comment]
Hi @martinzurkowskiSST ,
I believe the issue is related to how profiles are processed during package creation (more specifically how this processing has changed). Basically they are being removed during the package creation process - incorrectly in my view - which, among other things, causes this issue. This is also causing tests that have previously passed for years to suddenly fail. See also #2133 linked above.
