### ISSUE TITLE
include of @salesforce/core cause swallowing of uncaught exceptions

### ISSUE THREAD

**Issue by pawel-id** [forcedotcom/cli#2198]
I spend some time writing and debugging a little script. I found that an import of @salesforce/core registers a handler to ‘uncaughtException’. This pollutes global scope and prevents showing uncaught exceptions and returning non zero exit code.

Sample code:
```javascript
import { Org } from '@salesforce/core'
throw new Error('this should be printed to stderr and returned non zero exit code')
```

The above script should print an error and return 1. But it does nothing and returns 0. 
 It is the first import handling ‘uncaughtException’. Comment first line to get proper behaviour.

Another side effect is swallowing errors like this:
```javascript
import { Org } from '@salesforce/core'
nonExistentFunction()
```

The above code also completes without notifying any issues.

It would be great if the module would not do this. See more information https://nodejs.org/docs/latest-v18.x/api/process.html#warning-using-uncaughtexception-correctly

**Comment by mshanemc** [comment]
duplicate #2196
