### ISSUE TITLE
Environment variables are not taken into account when there is no sfdx-project.json in cwd

### ISSUE THREAD

**Issue by antoinechampion** [forcedotcom/cli#2199]
### Summary

Environment variables `FORCE_SFDC_LOGIN_URL` and `SFDX_SCRATCH_ORG_CREATION_LOGIN_URL` are not taken into account if SFDX is launched from a directory without a `sfdx-project.json` file.

### Steps To Reproduce:

```
cd /tmp
rm sfdx-project.json 2> /dev/null
export FORCE_SFDC_LOGIN_URL=<redacted>
export SFDX_SCRATCH_ORG_CREATION_LOGIN_URL=<redacted>
sfdx force:org:create edition=Developer --targetdevhubusername=dh-stmfa@salesforce.com
```

### Expected result

SFDX should use `FORCE_SFDC_LOGIN_URL` for its auth commands and `SFDX_SCRATCH_ORG_CREATION_LOGIN_URL` as a target signup login url.

### Actual result

SFDX does not use `FORCE_SFDC_LOGIN_URL` and `SFDX_SCRATCH_ORG_CREATION_LOGIN_URL`. If a dummy sfdx-project.json is created in the working directory, those variables are then taken into account:

```
cd /tmp
mkdir .dummy
cat <<EOF >> sfdx-project.json
{
  "packageDirectories": [
    {
      "path": ".dummy",
      "default": true
    }
  ]
}
EOF
export FORCE_SFDC_LOGIN_URL=<redacted>
export SFDX_SCRATCH_ORG_CREATION_LOGIN_URL=<redacted>
sfdx force:org:create edition=Developer --targetdevhubusername=dh-stmfa@salesforce.com
```

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.178.0 darwin-x64 node-v18.12.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-autocomplete 1.3.6 (core)
@oclif/plugin-commands 2.2.1 (core)
@oclif/plugin-help 5.1.18 (core)
@oclif/plugin-not-found 2.3.8 (core)
@oclif/plugin-plugins 2.1.6 (core)
@oclif/plugin-update 3.0.6 (core)
@oclif/plugin-version 1.1.3 (core)
@oclif/plugin-warn-if-update-available 2.0.13 (core)
@oclif/plugin-which 2.2.0 (core)
@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)
alias 2.1.8 (core)
apex 1.3.0 (core)
auth 2.2.22 (core)
community 2.0.16 (core)
config 1.4.22 (core)
custom-metadata 2.0.4 (core)
data 2.1.11 (core)
generator 2.0.11 (core)
info 2.2.8 (core)
limits 2.0.13 (core)
org 2.2.12 (core)
packaging 1.10.7 (core)
salesforce-alm 54.8.3 (core)
schema 2.1.15 (core)
sfdx-cli 7.178.0 (core)
signups 1.2.12 (core)
source 2.3.4 (core)
telemetry 2.0.4 (core)
templates 55.1.0 (core)
trust 2.1.0 (core)
user 2.1.19 (core)

**OS and version**:
ProductName:	macOS
ProductVersion:	12.6.1
BuildVersion:	21G217

**Comment by WillieRuemmele** [comment]
Hello @antoinechampion 👋

Those aren't recognized environment variables https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm 

were these working in previous versions of the CLI?
