### ISSUE TITLE
sfdx plugins:update is not updating to the lastest version

### ISSUE THREAD

**Issue by venkatpolisetti** [forcedotcom/cli#22]
Do you want to request a *feature* or report a *bug*?
-----------------------------------------------------
Bug

What is the current behavior?
-----------------------------
sfdx plugins:update is not upgrading the custom plugin to the latest plugin

What is the expected behavior?
------------------------------
It should update to the latest version. See attachment.

**Current sfdx version:**
-----------------------
$ sfdx version
sfdx-cli/6.42.0-ae478b3cb8 (windows-x64) node-v8.9.4

![capture](https://user-images.githubusercontent.com/192425/49377859-39a12b80-f6d9-11e8-8045-fb8786878de1.PNG)

**Comment by clairebianchi** [comment]
@venkatpolisetti we are in the process of an update that includes a more recent version of Yarn. This should fix this issue. We will test once the update is done and close this bug once we verify its no longer an issue. The update should be out mid-March

**Comment by MarcDBehr** [comment]
@clairebianchi I am starting to see this this week. Is the mid-March update out yet or is there an updated ETA?

**Comment by clairebianchi** [comment]
@MarcDBehr The update goes out next Thursday :)
