### ISSUE TITLE
LWC SFDX source push error TypeError: LWC1009: decl.moveTo is not a function

### ISSUE THREAD

**Issue by alcoforado** [forcedotcom/cli#220]
### Summary
Getting the following error when try to push code to my org  sfdx force:source:push

PROJECT PATH ERROR ──────────── ───────────────────────────────────────────────── N/A TypeError: LWC1009: decl.moveTo is not a function

The issue happens when I have a css in Lightning Web Component with two entries for the same selector
Like

.json-map-view {
    border: 1px #CFD7E6 solid !important;
    border-radius: 5px !important;
    background-color: #b0c4df !important;
    padding-left: 1rem !important;
    padding-right: 1rem !important;
    margin-bottom: 5px;
}

.json-map-view {
    padding-right: 1rem !important;
    margin-bottom: 5px;
}

Merging both into one solves the problem.

Usig windows, cli version 
fdx-cli/7.1.4-79f97a7df8 node-v10.15.3

**Comment by clairebianchi** [comment]
@alcoforado are you still encountering this issue. I have moved it into the general CLI issues repository. This sounds like a linting issue. If you are still having an issue with source:push. Let me know and I can reopen this issue
