### ISSUE TITLE
Some classes out of date with sfdx-project.json schema 

### ISSUE THREAD

**Issue by goto-dev-null** [forcedotcom/cli#2201]
### Summary

From what I can see, the schema has been updated but not the class, which is causing Typescript to have a fit. Specifically in our custom plugin and specifically for apexTestAccess, though I noticed that others are also missing as well like unpackagedMetadata.

The PackageDir class the code is using is @salesforce\core\lib\sfdxProject.d.ts

### Steps To Reproduce:

Reference `apexTestAccess` on a `PackageDir` object

### Expected result

No syntax error

### Actual result

Syntax error

### Additional information

![image](https://user-images.githubusercontent.com/2322497/138182163-d8283561-a438-411c-9433-1f77130961df.png)

![image](https://user-images.githubusercontent.com/2322497/138181544-32aefb9d-7efe-4cc6-b458-cbd0d3d50db1.png)

**SFDX CLI Version**
sfdx-cli/7.118.1 win32-x64 node-v14.17.4

**SFDX plugin Version**:
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.3 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.1 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
alias 1.1.10 (core)
apex 0.2.8 (core)
auth 1.7.1 (core)
config 1.2.34 (core)
custom-metadata 1.0.12 (core)
data 0.6.1 (core)
generator 1.2.0 (core)
limits 1.2.1 (core)
mo-dx-plugin 0.3.2
org 1.7.0 (core)
plugin-lightning-testing-service 1.0.1
salesforce-alm 52.3.3 (core)
schema 1.0.8 (core)
sfdx-cli 7.118.1 (core)
sfdx-git-delta 4.9.0
sfdx-git-packager 0.3.3
sfdx-isdot 2.7.0 (link) C:\Users\jpetraglia\repos\isdot
sfdx-jayree 3.11.2
└─ @jayree/sfdx-plugin-prettier 1.0.4
source 1.0.15 (core)
telemetry 1.2.3 (core)
templates 52.1.0 (core)
texei-sfdx-plugin 1.10.1
trust 1.0.7 (core)
user 1.4.0 (core)

**OS and version**:
Windows 10

**Comment by goto-dev-null** [comment]
Bumping on this as it's almost been 2 weeks.

This is causing issues with new versions of our plugin able to be packed. What would be a timeline for adding this?

**Comment by goto-dev-null** [comment]
Bumping on this as another week has passed.

Apologies if I'm being aggressive but, as far as I know, this is not a new feature, this has been something available in SFDX for quite some time, so I'm wondering why this hasn't been prioritized.

**Comment by mshanemc** [comment]
Thanks for the pings--we don't get a lot of issues on this library so sorry for not paying closer attention to it.

You're right about it missing some properties--those usually get added as we need them (and not always as the are created in the schema).

Are you just wanting us to add the properties on the types here?
https://github.com/forcedotcom/sfdx-core/blob/e8c5e79f6039970ce72945abad7e9b4bcb13a51b/src/sfdxProject.ts#L29

**Comment by goto-dev-null** [comment]
You are correct, sir!

**Comment by jshackell-sfdc** [comment]
This issue is fixed in the 2.42.6 (May 22, 2024) release.
