### ISSUE TITLE
ConnectedApp creation via connection.metadata.create() issues

### ISSUE THREAD

**Issue by Raspikabek** [forcedotcom/cli#2203]
### Summary
Attribute isAdminApproved always as `false` on ConnectedApp element creation.

Usage of `connection.metadata.create('ConnectedApp', metadata);` with attribute `isAdminApproved` as true creates always the ConnectedApp with this as false.

### Steps To Reproduce:

1. Create an element with the necessary information for your ConnectedApp:
```
const metadata = [
      {
        contactEmail: 'johndoe@acme.com'
        description: 'my awesome connected app',
        fullName: 'MyAwesomeConnectedApp',
        label: 'MyAwesomeConnectedApp',
        permissionSetName: 'MyPermissionSet'
        oauthConfig: {
          callbackUrl: 'http://localhost:1717/OauthRedirect',
         "scopes": [
           "Api",
           "Web",
           "RefreshToken"
         ],
          isAdminApproved: true
        }
      }
    const connection = this.org.getConnection();
    const results = (await connection.metadata.create(
      'ConnectedApp',
      metadata
    )) as SaveResult;
```

### Expected result

A new Connected App with Permitted Users policy as `Admin approved users are pre-authorized`

### Actual result

A new Connected App with Permitted Users policy as `All users may self-authorize`
No PermissionSet or Profile related

#### Workaround for isAdminApproved
I've been able to set the ConnectedApp with the attribute `isAdminApproved` updating the application after the creation. Sample snippet:

```
[...] results variable is the result from connection.metadata.create('ConnectedApp',metadata); [...]
      const createdElement = (await connection.metadata.read(
        'ConnectedApp',
        results.fullName
      )) as MetadataInfo;
      this.ux.styledHeader('CREATED ELEMENT');
      this.ux.styledJSON(createdElement); // here the log displays the attribute isAdminApproved as false on creation
      createdElement['oauthConfig'].isAdminApproved = true; // from the read element, we set again isAdminApproved as true
      const updateResult = (await connection.metadata.update(
        'ConnectedApp',
        createdElement
      )) as SaveResult;

      const updatedElement = (await conn.metadata.read(
        'ConnectedApp',
        updateResult.fullName
      )) as MetadataInfo;
      this.ux.styledJSON(updatedElement); // here we can see the isAdminApproved is now true. the org represents the correct value now as well.
```
Following the similar workaround I've been trying to include the `permissionSetName` or `profileName` attributes in the creation and update operation but the elements are not related.

As a workaround I've to execute an Anonymous Apex execution script in order to create the relationship or query the ConnectedApp & PermissionSet/Profile ids + create a new record in SetupEntityAccess table with connection.query() and connection.create() commands

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli 7.74.1 (core)`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ templates 49.4.4 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
├─ apex 0.0.9 (core)
└─ salesforce-alm 49.11.0 (core)
sfdx-cli 7.74.1 (core)
```

**OS and version**: Manjaro Linux - Kernel version: 5.7.19-2-MANJARO

**Comment by WillieRuemmele** [comment]
sorry for the very long delayed response. We don't monitor the `sfdx-core` repo for issues, but still had issues enabled, and so we missed quite a few of them... the `connection.metadata.create` is in jsforce https://github.com/jsforce/jsforce - I'll duplicate this issue there
