### ISSUE TITLE
Webpack bundler gives critical warning about: Dependency is an expression 

### ISSUE THREAD

**Issue by claboran** [forcedotcom/cli#2204]
### Summary
Usage of Webpack gives the following error message:
```WARNING in ./node_modules/@salesforce/core/lib/messages.js 297:11-28
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@salesforce/core/lib/exported.js
 @ ./src/connection.ts
 @ ./src/index.ts
```
The problem seems to be loacted here: [messages.ts](https://github.com/forcedotcom/sfdx-core/blob/develop/src/messages.ts)
```
 /**
   * Internal readFile. Exposed for unit testing. Do not use util/fs.readFile as messages.js
   * should have no internal dependencies.
   * @param filePath read file target.
   * @ignore
   */
  public static _readFile = (filePath: string): AnyJson => {
    return require(filePath);
  };
```

### Steps To Reproduce:

1.  Create a project using @salesforce/core
1.  Bundle with webpack

### Expected result

It should be possible to create a bundled version.

### Additional information

**Version 2.11.0**
**node >= 10.x**
**Windows 10**:

**Comment by saurabh-deep** [comment]
Hey All!

Further from the above, due to the above and the approach to load messages in the plugins (i.e. with `Messages.importMessagesDirectory`) any packages that use @salesforce/core or Salesforce CLI plugins cannot be bundled correctly with Webpack or other bundlers.

Is there a chance that the approach to read messages can be looked at to enable the package to play well with Webpack and other JS bundlers?

**Comment by gabriel-keith** [comment]
I'm currently experiencing this issue as well for an electron app use case.

**Comment by lukecotter** [comment]
> Hey All!
> 
> Further from the above, due to the above and the approach to load messages in the plugins (i.e. with `Messages.importMessagesDirectory`) any packages that use @salesforce/core or Salesforce CLI plugins cannot be bundled correctly with Webpack or other bundlers.
> 
> Is there a chance that the approach to read messages can be looked at to enable the package to play well with Webpack and other JS bundlers?

Also hitting this issue. I tried using `dynamicRequireTargets ` but could not get it to work right.
https://github.com/rollup/plugins/tree/master/packages/commonjs#dynamicrequiretargets

Do we have a workaound?

**Comment by vkmita** [comment]
I'm experiencing this issue as well. Couldn't figure it out, and had to include it as an external... :(

**Comment by mshanemc** [comment]
sfdx-core should be bundle-able now as a result of this change https://github.com/forcedotcom/sfdx-core#message-transformer

If you find some other way besides these issues where it fails bundling, please open a new issue.  
I'd also be interested in a PR that does a minimal webpack exercise to prevent new changes from causing un-bundleability.
