### ISSUE TITLE
Lost permissions when retrieving permission set that have view all data and modifyalldara 

### ISSUE THREAD

**Issue by mohametso** [forcedotcom/cli#2205]
When we retrieve permission set that have Modify all data and view All data we always lost the permissions bellow that make error during our deployment process

The permissions bellow is lost when pulling the permission set <userPermissions>

<-----ModifyAllData------>

    <userPermissions>
        <enabled>true</enabled>
        <name>ManageQuotas</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>OverrideForecasts</name>
    </userPermissions>

<-----ViewAllData------>

 <userPermissions>
        <enabled>true</enabled>
		<name>ViewAllForecasts</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ViewDataLeakageEvents</name>
    </userPermissions>
    <userPermissions>
        <enabled>true</enabled>
        <name>ViewPlatformEvents</name>
    </userPermissions>

**Comment by mshanemc** [comment]
Are you using this library (sfdx-core) directly, or using one of the Salesforce CLI commands like `force:source:retrieve` ?
