### ISSUE TITLE
checkScratchOrg fails to use default dev hub username

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/cli#2207]
### Summary

Running `this.org.checkScratchOrg()` tries to check on the dev hub if the current org is a scratch org or not. However, this commands fails finding the defaultdevhubusername, failing with the following error:
`No AuthInfo found for name MyDevHub`

Running `this.org.checkScratchOrg(this.hubOrg.getUsername())` works fine.

### Steps To Reproduce:

1.  Login to a default DevHub with an alias 'MyDevHub'
2.  Create a Scratch Org
3.  Try running `this.org.checkScratchOrg()` in a custom CLI command

### Expected result

The commands connect to the DevHub and check whether the default org is a scratch org.

### Actual result

`No AuthInfo found for name MyDevHub`

**Comment by mshanemc** [comment]
Looks like this was fixed by https://github.com/forcedotcom/sfdx-core/blob/e74bcd44effe34b38a576a4f69b38f16fb737187/src/org/org.ts#L418-L419
