### ISSUE TITLE
SF build package unable to generate Job ID in run apex step

### ISSUE THREAD

**Issue by torihefti** [forcedotcom/cli#2213]
### Summary
Building the package via ADO pipeline for UAT deployment, but the job took time to complete in the run apex test step which normally finished less than 5 minutes. Prior steps is ok with no failing job log. There was no development changes moved to the platform package, only to reference the latest master version as all product streams using the reference from the latest version stamp.
[Successful Package build - 2023-05-23.txt](https://github.com/forcedotcom/cli/files/11745158/Successful.Package.build.-.2023-05-23.txt)
[Current Package build log - 2023-06-14.txt](https://github.com/forcedotcom/cli/files/11745160/Current.Package.build.log.-.2023-06-14.txt)

### Expected result
Starting: Run Apex Tests (running time 2min)
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /__w/_temp/414f38f8-430c-4d0d-95c8-276c6d5834cb.sh
*** Running Tests ***

Running tests for the first time

Getting Job ID...
(node:1078)

### Actual result
Starting: Run Apex Tests (running time 45min)
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.212.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /__w/_temp/358724ee-d09b-4bc7-977e-b31e8ff87354.sh
*** Running Tests ***

Running tests for the first time

Getting Job ID...
*job log unable to generate a job id.

**Comment by WillieRuemmele** [comment]
Hey @torihefti - can you please provide the information requested in the template?
