### ISSUE TITLE
Scratch Org Creation fails with Org Shape - Summer 23 - Multicurrency feature

### ISSUE THREAD

**Issue by prakash-purswani** [forcedotcom/cli#2214]
I realized the hard way that Salesforce has auto-enabled Multicurrency in all scratch orgs created from Summer'23 and hence we should not add "MultiCurrency" under features else it will fail with An unexpected error occurred while preparing endpoint: C-9999.

We removed  "features": ["MultiCurrency"] and added "settings": {  "currencySettings": { "enableMultiCurrency": true } }.

As we are using Org shape which already has multi-currency enabled, it now fails with "C**urrency: Do not have an access to enableMultiCurrency**". It works fine without org shape. 

Any fixes being worked on?

References:
https://salesforce.stackexchange.com/questions/404728/multicurrency-cannot-be-enabled-in-scratch-org
https://salesforce.stackexchange.com/questions/404617/scratch-org-problems-with-summer-23-release
https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000Pf5mXSAR
https://salesforce.stackexchange.com/questions/404536/summer-23-scratch-org-wont-load

**Comment by David-Polehonski** [comment]
@prakash-purswani I have been in contact with salesforce support and after much digging through the documentation I believe this issue affects org shapes where the org does not have [Multi Currency Everywhere](https://help.salesforce.com/s/articleView?id=000381840&type=1) enabled. I have had support enable this feature for me and recreated the org shape and everything is now working as expected.

**Comment by rlbarreto** [comment]
I was able to create my scratch org.I have changed my scratch org definition file and remove the feature Multicurrency and add the setting "currencySettings": {"enableMultiCurrency": true}
After that, I was able to create my scratch org.

**Comment by iowillhoit** [comment]
I am going to close this issue since it is not owned by the CLI team and there are a few workarounds provided. If you are still having problems with this, I would recommend opening a Salesforce customer support case. 

@David-Polehonski Could you please provide your Case number in this Issue so that others can reference it in the future if needed? Thank you!
