### ISSUE TITLE
CLI commands do not properly stub `~/.sfdx` when missing during command execution on Mac; Windows/Linux are fine

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#2222]
A Mac user reported an issue to me where, in IC2, things could go haywire if the `~/.sfdx` directory is missing when IC2 executes `force:org:list` (and potentially other commands). I was unable to reproduce that behavior...but evidently because I was trying to do so specifically on Windows, though Linux looks fine as well. Here's the behavior across various platforms:

Mac M1 (fails):
```
$ mv ~/.sfdx ~/_sfdx
$ mv ~/.sf ~/_sf
$ sfdx org list --json
{
  "code": 1,
  "context": "OrgListCommand",
  "commandName": "OrgListCommand",
  "message": "ENOENT: no such file or directory, scandir '/Users/swells/.sfdx'",
  "name": "Error",
  "status": 1,
  "stack": "Error: ENOENT: no such file or directory, scandir '/Users/swells/.sfdx'",
  "exitCode": 1,
  "warnings": []
}
```

Ubuntu Linux (works):
```
$ mv ~/.sfdx ~/_sfdx
$ mv ~/.sf ~/_sf
$ sfdx org list --json
{
  "status": 0,
  "result": {
    "nonScratchOrgs": [],
    "scratchOrgs": []
  },
  "warnings": []
}
```

Windows (works):
```
$ mv ~/.sfdx ~/_sfdx
$ mv ~/.sf ~/_sf
$ sfdx org list --json
{
  "status": 0,
  "result": {
    "nonScratchOrgs": [],
    "scratchOrgs": []
  },
  "warnings": []
}
```

I'm assuming that in _all_ cases, the command should stub the `~/.sfdx` directory and not blow up like this, no?

**Comment by SCWells72** [comment]
Looking more closely, the errors are all about log rotation, so seems to be the same issue as #2209 and would be addressed by `logger-replacement`.

**Comment by SCWells72** [comment]
Note that it's important to delete/move both `~/.sfdx` and `~/.sf` or you can get issues with log rotation, e.g.:

```
$ mv ~/.sfdx ~/_sfdx
$ sfdx org list --json
[Error: ENOENT: no such file or directory, rename '/home/swells/.sf/sf.log.0' -> '/home/swells/.sf/sf.log.1'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/home/swells/.sf/sf.log.0',
  dest: '/home/swells/.sf/sf.log.1'
}
[Error: ENOENT: no such file or directory, rename '/home/swells/.sf/sf.log.0' -> '/home/swells/.sf/sf.log.1'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/home/swells/.sf/sf.log.0',
  dest: '/home/swells/.sf/sf.log.1'
}
{
  "status": 0,
  "result": {
    "nonScratchOrgs": [],
    "scratchOrgs": []
  },
  "warnings": []
}
```

While still an error, that's already logged elsewhere, e.g., #2209.

**Comment by SCWells72** [comment]
CLI versions on the respective OSes:

Windows:
```
$ sfdx version
sfdx-cli/7.204.6 win32-x64 node-v18.15.0
```

Linux:
```
$ sfdx version
sfdx-cli/7.204.6 linux-x64 node-v19.9.0
```

Mac:
```
$ sfdx version
sfdx-cli/7.204.6 darwin-x64 node-v18.15.0
```

**Comment by iowillhoit** [comment]
Hey Scott 👋 This should be working as expected in `latest` (`sfdx-cli/7.205.6`), can you please have them update and try again? 

Sidenote: I do think there is a check we can add to prevent this from happening again

<img width="1072" alt="Screenshot 2023-06-15 at 1 40 46 PM" src="https://github.com/forcedotcom/cli/assets/1715111/85090019-d738-4ba5-8500-c285ce15c24a">

**Comment by SCWells72** [comment]
Looks better to me after updating:

```
$ sfdx version
sfdx-cli/7.205.6 darwin-x64 node-v18.15.0
$ mv ~/.sfdx ~/_sfdx
$ mv ~/.sf ~/_sf
$ sfdx org list --json
{
  "status": 0,
  "result": {
    "nonScratchOrgs": [],
    "scratchOrgs": []
  },
  "warnings": []
}
```

I'll ask the user to update and verify as well. I'm curious...was this already slated for the latest update, or did you squeeze it in at the last minute?

**Comment by iowillhoit** [comment]
The timing of the fix actually appears to be completely unrelated. The problem was coming from [here](https://github.com/salesforcecli/plugin-org/blob/d25c08b2c4d0f800e22d9a44235b13c901461c6d/src/shared/orgListUtil.ts#LL132C33-L132C59). When the `.sfdx` directory did not exist, it would throw an error. 

@mshanemc recently make some changes to aliases ([PR](https://github.com/forcedotcom/sfdx-core/pull/842)) and that included a check to [ensure the aliases file existed](https://github.com/forcedotcom/sfdx-core/blob/b8d995f646da7628ef703e41de7ad343607aaaf7/src/stateAggregator/accessors/aliasAccessor.ts#L209-L218) (and the `.sfdx` directory as well). 

Based on telemetry, we are also seeing some `org:list` errors on Linux and Windows as well. Not entirely sure why they were not seeing the same issue.

**Comment by SCWells72** [comment]
Ah, so the "fix" was actually just serendipity. Any idea why the original problem was unique to Mac and not present on Windows/Linux? And if I'm wandering too far into the weeds, feel free to say so. Just curious, but to some extent, a fix is a fix.

**Comment by iowillhoit** [comment]
I am honestly not sure Scott, we have telemetry that is also showing errors for Linux and Windows on the `org:list` command in the last 24 hours. Could have been how the CLI is being installed, for example using yarn to install the CLI would not respect the shrinkwrap file and pull in the most recent `sfdx-core` 🤷

**Comment by iowillhoit** [comment]
Whoops, this should have been closed a while ago. I added a check to prevent this from becoming a regression later on.
