### ISSUE TITLE
Cannot deploy managed deprecated global batch classes

### ISSUE THREAD

**Issue by gonzalezjesus** [forcedotcom/cli#2225]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI. Yes 7.205.6-dfc6717
> - You've searched both open and closed issues for related posts. Yes
> - You've used the `doctor` command to diagnose common issues. No
> - You understand that GitHub Issues don't adhere to any agreement or SLA. Yes
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support. Yes

### Summary
We have a managed global deprecated batch class that implements Database.Batchable<sObject> and Database.Stateful. 
We are currently stuck because we can't deploy nor upgrade customers with our package. 
If we try to change the class (it can be just a blank space or even without any change at all) we are getting the following error: 
"Deprecated managed type that is released can't implement new interfaces"
We have opened a known issue (https://issues.salesforce.com/issue/a028c00000tIoUY/not-able-to-save-or-deploy-deprecated-global-classes-after-summer23-release).

### Steps To Reproduce
- Create the following class and its test below. 
- Create a managed package
- Uncomment the `//@Deprecated` and try to push again using the cli. 

`//@Deprecated
global with sharing class DeprecatedGlobal implements Database.Batchable<sObject>, Database.Stateful {
    global DeprecatedGlobal() {}
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return null;
    }
    global void execute(Database.BatchableContext BC, List<SObject> scope) {   
    }
    global void finish(Database.BatchableContext BC) {   
    }
}`

`@IsTest
public class DeprecatedGlobalTest {
    @IsTest
    private static void myTest() {
        DeprecatedGlobal classInstance = new DeprecatedGlobal();
		classInstance.start(null);
		classInstance.execute(null, null);
		classInstance.finish(null);
    }
}`

This is the sfdx version

```json
{
  "cliVersion": "sfdx-cli/7.205.6",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/Users/jesusgonzalez/.local/share/sfdx/client/7.205.6-dfc6717",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.17 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/analytics 1.3.4 (user)",
    "apex 2.3.3 (core)",
    "auth 2.8.1 (core)",
    "community 2.3.1 (core)",
    "custom-metadata 2.1.25 (core)",
    "data 2.3.22 (core)",
    "deploy-retrieve 1.11.7 (core)",
    "info 2.6.19 (core)",
    "limits 2.3.18 (core)",
    "org 2.9.8 (core)",
    "packaging 1.19.0 (core)",
    "schema 2.3.12 (core)",
    "settings 1.4.11 (core)",
    "signups 1.4.21 (core)",
    "source 2.10.14 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.20 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.17 (core)",
    "sfdx-browserforce-plugin 2.9.1 (user)",
    "sfdx-cli 7.205.6 (core)",
    "sfdx-plugin-ipfolio 0.0.0-development (user)"
  ]
}
```

Thank you very much

**Comment by WillieRuemmele** [comment]
Hi @gonzalezjesus - this is a server-side error being shown to you through the CLI. Unfortunately there's not much that we'll be able to help you with :( Following through your known issue, or other, more official support channels might be your best option

**Comment by gonzalezjesus** [comment]
Many thanks for the quick response. That makes sense. I'll see if I can get a solution for this via other support channels. Again, thank you!
