### ISSUE TITLE
`sf project generate manifest --from-org` failing with partial error message

### ISSUE THREAD

**Issue by tehnrd** [forcedotcom/cli#2229]
### Summary

Created a brand new developer sandbox with source tracking enabled. Connected or to the project. Try to run the following command:

`sf project generate manifest --from-org thenameoforg`

Fails with the message:
`Error (1): No type found for  when matching by suffix.  Check the file extension.`

Logs show nothing.

### Steps To Reproduce
Didn't provide a repository as this is reproduced with a completely empty project.
- Create new Developer Sandbox
- Generated empty project
- Auth the sandbox org
- Run the command `sf project generate manifest --from-org thenameoforg`
- Fails with the message:
`Error (1): No type found for when matching by suffix.  Check the file extension.`

### Expected result
The manifest file should be generated successfully.

Or the error message should display the full message. It looks like it is try to concatenate an empty string.

### Actual result
`Error (1): No type found for when matching by suffix.  Check the file extension.`

### System Information
zsh OSX

` sf version --verbose --json`:
```json
{
  "cliVersion": "@salesforce/cli/1.83.0",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/usr/local/lib/sfdx/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.17 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.83.0 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.1 (core)",
    "data 2.3.22 (core)",
    "deploy-retrieve 1.11.7 (core)",
    "info 2.6.19 (core)",
    "limits 2.3.18 (core)",
    "login 1.2.11 (core)",
    "org 2.9.8 (core)",
    "schema 2.3.12 (core)",
    "settings 1.4.11 (core)",
    "sobject 0.1.24 (core)",
    "source 2.10.14 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.20 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.17 (core)"
  ]
}
```
### Additional information
<img width="636" alt="Screenshot 2023-06-19 at 2 48 24 PM" src="https://github.com/forcedotcom/cli/assets/1007085/f71cd7a3-d47d-41f5-8c99-d6b2b8219151">

**Comment by mshanemc** [comment]
@tehnrd I fixed the error message to handle when there's no type OR filename available for a component.   It should provide the fullName of the mystery component so you can see what it is, as well as information about the metadataRegistry.

Clearing the error would involve getting the type into SDR's registry [the improved error message should have links for that] OR you `.forceignoring` it (maybe).

**Comment by tehnrd** [comment]
The `.forceignore` file is the following, so I don't think that is the issue.

```
# List files or directories below to ignore them when running force:source:push, force:source:pull, and force:source:status
# More information: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm
#

package.xml

# LWC configuration files
**/jsconfig.json
**/.eslintrc.json

# LWC Jest
**/__tests__/**
```

I also messed up the logging before. Here is a log, but I am not sure exactly where the error is. Might be related to new metadata types in Summer 23?


[sf.log](https://github.com/forcedotcom/cli/files/11793015/sf.log) `SF_LOG_LEVEL=trace `

**Comment by tehnrd** [comment]
@mshanemc is there a way for me force usage of https://github.com/forcedotcom/source-deploy-retrieve/releases/tag/9.2.4 or do I need to wait for next CLI update? Maybe the next nightly?

edit: I think the log in the previous comment shows the problematic types.

**Comment by mshanemc** [comment]
it'll be in the nightly (that's the easiest way).  

I can't tell from the log what the problem might be.  It's generally pretty tolerant of things that aren't enabled on the org when it requests them (as you can see from the log).  

From where the error is happening, it looks like something was retrieved but whatever is in the output is missing information that's usually there (what type it is).

**Comment by iowillhoit** [comment]
I just kicked off a new "nightly" build (https://github.com/salesforcecli/cli/pull/908). As long as tests pass, `1.8.5` will be available on `npm` here in ~15 minutes for you to test with

**Comment by tehnrd** [comment]
@iowillhoit Thanks! @mshanemc Hmm...still not sure what the issue is...

Log file, not much different from the previous one: [sf.log](https://github.com/forcedotcom/cli/files/11794883/sf.log)



```
jvenable@F3H5F6V4Y0 retrieve % sf project generate manifest --from-org retrieve
Error (1): _Default: Could not infer a metadata type

Try this:

Additional suggestions:
Confirm the file name, extension, and directory names are correct. Validate against the registry at:
<https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/registry/metadataRegistry.json>

If the type is not listed in the registry, check that it has Metadata API support via the Metadata Coverage Report:
<https://developer.salesforce.com/docs/metadata-coverage>

If the type is available via Metadata API but not in the registry

- Open an issue <https://github.com/forcedotcom/cli/issues>
- Add the type via PR. Instructions: <https://github.com/forcedotcom/source-deploy-retrieve/blob/main/contributing/metadata.md>
```

**Comment by mshanemc** [comment]
there's some component being retrieved whose fullName is `_Default` but it doesn't have a type or a filename.  
[talking about one of these FileProperties] https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_retrieveresult.htm#retrieveresult_fileproperties

I'm stumped as to what that component might be.  One option would be to skip (and warn) when we get a component without filename/type so it's not breaking the whole process.

**Comment by renz-id** [comment]
Following since I'm currently experiencing the same issue on a new empty project.

**Comment by tehnrd** [comment]
@mshanemc Are you saying there is a metadata component with the name `_Default` ? Would it be possible to just dump the entire https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_retrieveresult.htm#retrieveresult_fileproperties object as json ? 

I have no idea how to chase this component down? This org has hundreds of managed packages and 10s of thousands of other components.

EDIT: Looks like fix/work-around was merged in yesterday. I'll try the nightly and report back

**Comment by mshanemc** [comment]
I don't think that nightly has published yet.  Check it tomorrow

**Comment by aheber** [comment]
I've run into this exact error before. In my case it was the Synonym Dictionary that was missing context metadata when retrieved via the API.

I resolved it by copying the `_Default` into another SynonymDictionary then deleting the `_Default`.

My unsubstantiated guess was that this was a result of a migration that happened, or partially happened on these a few years ago.

I didn't try and resolve it in the CLI because it seemed like more of a bug in my Metadata. Once we found a resolution we haven't had a problem since.

If you do find that it is the SynonymDictionary I would either do what I have done and move on, or you can invest more in this than I did and open a support case and maybe Salesforce can find and fix this across any other similar orgs as well as fixing yours. Or at least they can open a known issue so others can get answers more quickly.

**Comment by tehnrd** [comment]
@aheber Genius! I found it, but still working on the fix with my team.

<img width="877" alt="Screenshot 2023-06-28 at 6 06 43 PM" src="https://github.com/forcedotcom/cli/assets/1007085/2dd40d99-9d1c-41b7-8e0e-5fd2e1ee8899">

**Comment by shetzel** [comment]
Closing this as it's in the sf CLI release candidate now.
