### ISSUE TITLE
sfdx force:source:push doesn't seem to be calculating dependency order properly

### ISSUE THREAD

**Issue by joeferraro** [forcedotcom/cli#223]
### Summary

I have an sfdx project with two packages: Package A with some common lib code and Package B with my core application. Both packages are listed in `sfdx-project.json` with Package B listed second in the order and specifying Package A as a dependency.

When I `sfdx force:source:push`, Package B seems to be installed first which sets off a cascading series of errors because references to elements in Package A don't exist.

I could be missing something obvious, but I think this is what's happening because if I push Package A explicitly (by itself) first, THEN push Package B, everything compiles.

Thanks

### Steps To Reproduce:

1.  Create a project with two packages, one relying on the other
1.  `sfdx force:source:push`

### Expected result

Package A is installed first, followed by Package B

### Actual result

Package B seems to be installed first.

### Additional information

This seems to be an intermittent issue: I was able to build my project against a different fresh scratch org yesterday, today it isn't working. 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.13.0-27dbcb37d3 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
```
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.3.0 (core)
├─ force-language-services 46.8.0 (core)
└─ salesforce-alm 46.7.0 (core)
```

**OS and version**:
macOS 10.14.2

**Comment by clairebianchi** [comment]
@joeferraro, We currently do not support multiple packages with dependencies in the CLI. We are currently spiking on this and will hopefully add enhancements to the CLI to cover this use case in the next couple of months.

**Comment by ghost** [comment]
@clairebianchi  Any updates on this feature? Is it rolled out?

**Comment by clairebianchi** [comment]
@azlamsalam we are actively working on this and plan to have an announcement in Github this Thursday with details on how to test out our changes.

**Comment by calvinle1** [comment]
Hi @clairebianchi, very interested in this also, is there an update? Thanks

**Comment by amphro** [comment]
See #379 for instructions on how to try it out.

**Comment by mshanemc** [comment]
Closing.  Packages go in the order listed in the file.
