### ISSUE TITLE
Thousands of API Calls - Client Id  "sfdx toolbelt:"

### ISSUE THREAD

**Issue by JimJiraffe** [forcedotcom/cli#2231]
Tonight suddenly I'm experiencing Salesforce Queueables that won't run, and Deployments through SFDX  CLI  that won't start -- stuck in "Pending".     This might not seem related to the CLI,  but I noticed that over the past hour or so,  almost 6,000 API requests were generated against my org by the SFDX CLI.     All I attempted over the past hour or so is to retrieve a few files, and deploy a few files using SFDX and a manifest file (with only 3 classes in it.)

What would cause these *thousands* of API calls?

![Screenshot 2023-06-20 040058](https://github.com/forcedotcom/cli/assets/46829286/47887b21-5736-4ac8-ab35-b1b249a28189)

I can't say the problem is only limited to the CLI, but I wanted to share this experience to see if maybe you had some insight.  

Thanks!

**Comment by JimJiraffe** [comment]
{
  "cliVersion": "sfdx-cli/7.205.6",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\jim\\AppData\\Local\\sfdx\\client\\7.205.6-dfc6717",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.17 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/lwc-dev-server 2.11.0 (user)",
    "apex 2.3.3 (core)",
    "auth 2.8.1 (core)",
    "community 2.3.1 (core)",
    "custom-metadata 2.1.25 (core)",
    "data 2.3.22 (core)",
    "deploy-retrieve 1.11.7 (core)",
    "info 2.6.19 (core)",
    "limits 2.3.18 (core)",
    "org 2.9.8 (core)",
    "packaging 1.19.0 (core)",
    "schema 2.3.12 (core)",
    "settings 1.4.11 (core)",
    "signups 1.4.21 (core)",
    "source 2.10.14 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.20 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.17 (core)",
    "@salesforce/sfdx-diff 0.0.6 (user)",
    "sfdx-cli 7.205.6 (core)"
  ]
}

**Comment by AllanOricil** [comment]
Poor @JimJiraffe you were hacked 😭 (JK)

**Comment by mshanemc** [comment]
the metadata API is asynchronous, so we when the CLI deploys or retrieves something, we have to poll the API to see when it's complete.

For a small deploy/retrieve, that normally finishes really quickly so the polling interval is pretty small (why make people wait even a few extra seconds?).  

https://github.com/forcedotcom/source-deploy-retrieve/blob/0f6e40c2f5aaddae85c25c9ec099db64537df128/src/client/metadataTransfer.ts#L263

**Comment by mshanemc** [comment]
If you do get into one of these weird situations where the API is having a bad day, the new `project deploy` command will let you `resume` after it times out or you ctrl-c it.

`retrieve` is one-time-use, so for that you'd just have to ctrl-c and start a new retrieve operation.

**Comment by AllanOricil** [comment]
Over 9000* apis calls to check the state of a job. This api overhead could be a reason to create an event system to notify consumers/clients about the stage of the deployment. Maybe it could save some money

**Comment by JimJiraffe** [comment]
@mshanemc -  It seems like there were two boogie-men after all.   Today I woke up to a service disruption notice from Salesforce that began around the time I attempted my deployment for the first time.  (Wasn't me!)   So that's definitely (partially) to blame.   Still a mystery why thousands of API calls were necessary before I had a fail / timeout my small handful of deployment attempts and one retrieval attempt.       Due to this disruption on SF,  I wonder if devs all over are unwittingly burning through their 24-hour API limits ... yikes!
