### ISSUE TITLE
Deployments are failing with Flows and relations to External Services(manifest).

### ISSUE THREAD

**Issue by viktor-saranchuk** [forcedotcom/cli#2233]
Steps to reproduce:

- Create External Service via OpenAPI 2.0 schema (Dynamic Apex will generated automatically) - I was using `https://excise.avalara.com/docs/api/v1`;
- Create flow with Action block referenced to External Service - in my case - transaction/create.
- Retrieve into SFDX project.
- Create manifest with ApexClass, ExternalServiceRegistration, NamedCredential, ExternalCredential, RemoteSiteSetting etc... (everything you need to deploy) - example of my manifest - below
- Try to deploy into another org **with using manifest**.

Expected result: the deployment job is successful;
Actual result: the job fails;

```sf deploy metadata validate -x path/to/manifest.xml
sf project deploy start -x path/to/manifest.xml
sf project deploy validate -x path/to/manifest.xml
sfdx force:source:deploy -x path/to/manifest.xml
```

the job will fail:
<img width="1144" alt="image" src="https://github.com/forcedotcom/cli/assets/40137179/64f504f8-df1a-4d68-8b3a-c160c121a64e">

`SomeVariable Name (Variable) - "apexClass" is invalid. Provide the API name of an Apex class that includes an Apex data type supported in flows.`

`Error SOM_Avalara_Tax_Excise_Recalculation_Flow CalloutResponseTransactionResult (Variable) - "apexClass" is invalid. Provide the API name of an Apex class that includes an Apex data type supported in flows. `

When deploying with different approaches - like `-d force-app` - it works with no errors.
It is crucial to work on a current project with using manifest.

I've tried with the name of the External Service in the manifest instead of wildcard - asterisk (*) - unsuccessful.

OS: `macOs Ventura 13.4`

```
json
{
  "cliVersion": "@salesforce/cli/1.83.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/Users/viktorsaranchuk/.local/share/sfdx/client/7.205.6-dfc6717/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.17 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.83.0 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.1 (core)",
    "data 2.3.22 (core)",
    "deploy-retrieve 1.11.7 (core)",
    "info 2.6.19 (core)",
    "limits 2.3.18 (core)",
    "login 1.2.11 (core)",
    "org 2.9.8 (core)",
    "schema 2.3.12 (core)",
    "settings 1.4.11 (core)",
    "sobject 0.1.24 (core)",
    "source 2.10.14 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.20 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.17 (core)"
  ]
}
```

versions
```
sf version: @salesforce/cli/1.83.0 darwin-x64 node-v18.15.0
sfdx version: sfdx-cli/7.205.6 darwin-x64 node-v18.15.0

```
plugins
```
@oclif/plugin-autocomplete 2.3.0 (core)
@oclif/plugin-commands 2.2.15 (core)
@oclif/plugin-help 5.2.9 (core)
@oclif/plugin-not-found 2.3.24 (core)
@oclif/plugin-plugins 3.1.2 (core)
@oclif/plugin-search 0.0.17 (core)
@oclif/plugin-update 3.1.17 (core)
@oclif/plugin-version 1.3.4 (core)
@oclif/plugin-warn-if-update-available 2.0.37 (core)
@oclif/plugin-which 2.2.22 (core)
@salesforce/cli 1.83.0 (core)
apex 2.3.3 (core)
auth 2.8.1 (core)
data 2.3.22 (core)
deploy-retrieve 1.11.7 (core)
info 2.6.19 (core)
limits 2.3.18 (core)
login 1.2.11 (core)
org 2.9.8 (core)
schema 2.3.12 (core)
settings 1.4.11 (core)
sobject 0.1.24 (core)
source 2.10.14 (core)
telemetry 2.2.0 (core)
templates 55.4.20 (core)
trust 2.4.20 (core)
user 2.3.17 (core)
```

manifest
```
<?xml version="1.0" encoding="UTF-8" ?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ExternalCredential</name>
    </types>
    <types>
        <member>*</member>
        <name>ExternalServiceRegistration</name>
    </types>
    <types>
        <members>*</members>
        <name>Flow</name>
    </types>
    <types>
        <members>*</members>
        <name>NamedCredential</name>
    </types>
    <types>
        <members>*</members>
        <name>PermissionSet</name>
    </types>
    <types>
        <members>*</members>
        <name>Profile</name>
    </types>
    <types>
        <members>*</members>
        <name>RemoteSiteSetting</name>
    </types>
    <version>57.0</version>
</Package>
```

command
```sf deploy metadata validate -x path/to/manifext.xml -l RunLocalTests```

output:
```Component Failures [2]
=================================================================================================================================================================================================================
| Type  Name                                      Problem                                                                                                                                                         
| ───── ───────────────────────────────────────── ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
| Error SOM_Avalara_Tax_Excise_Recalculation_Flow CalloutResponseTransactionResult (Variable) - "apexClass" is invalid. Provide the API name of an Apex class that includes an Apex data type supported in flows. 
| Error SOM_Avalara_Tax_Excise_Recalculation_Flow CalloutResponseTransactionResult (Variable) - "apexClass" is invalid. Provide the API name of an Apex class that includes an Apex data type supported in flows. 
Test Results Summary
Passing: 0
Failing: 0
Total: 0
Error (1): Failed to validate the deployment (0AfDQ0000029qO10AI).```

**Comment by shetzel** [comment]
>When deploying with different approaches - like -d force-app - it works with no errors.

Under the covers, a manifest is used whether you use the `-d`, `-m`, or `-x`.  So if it works when using `-d`, it should also work when using `-x`.  I would compare the manifest generated when deploying with `-d` with the manifest you created and are using with `-x`.  To do that, set the `SF_MDAPI_TEMP_DIR` to some directory and look at the generated manifest.

**Comment by viktor-saranchuk** [comment]
Thanks for explanation.
`-m RemoteSiteSetting ExternalServiceRegistration NamedCredential ExternalCredential Flow` - successful
`-x path/to/manifest.xml` with listed the same metadata types - failed!

<img width="694" alt="image" src="https://github.com/forcedotcom/cli/assets/40137179/eab67d06-c8a8-4992-a637-9a35d2af45af">

**Comment by WillieRuemmele** [comment]
Hey @Blackbackroom - Do you see any differences when comparing the two manifests? to generate a manifest for the `-d` command, set the `SF_MDAPI_TEMP_DIR` environment variable to a temp directory, and see what was generated.

**Comment by kbtyne** [comment]
Did you ever find a solution to this problem? I've just run into the same situation.

**Comment by ggiralsfdc** [comment]
Have this issue been ever solved? We have to resort to create the external service manually because deployment via CLI seems to be not working...

**Comment by viktor-saranchuk** [comment]
Hi @ggiralsfdc
I am already working on different project, so can not check it.
4 months ago, we haven't it resolved the issue.
The ticket is closed.- So you can open a new one and provide your details
