### ISSUE TITLE
If Push Detects a Username Reference in the Source not working in Groups

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/cli#224]
### Summary

_Short summary of what is going on or to provide context_.
If Push Detects a Username Reference in the Source not working in Groups push
### Steps To Reproduce:

1.  This is step 1. Create a group with username
and push to scratch org
1.  This is step 2. All steps should start with '1.'

### Expected result
 push succeeds, even if the scratch org does not contain the original username.
_Describe what should have happened_.

### Actual result

Group | 0 | 0 | In field: userName - no User named aniko.test@test.com found
-- | -- | -- | --

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
PS C:\SalesforceDX\HMI DX\HMIPROD> sfdx --version
sfdx-cli/7.13.0-27dbcb37d3 win32-x64 node-v10.15.3
PS C:\SalesforceDX\HMI DX\HMIPROD> sfdx plugins --core
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.2.0 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 46.3.0 (core)
├─ force-language-services 46.8.0 (core)
└─ salesforce-alm 46.7.0 (core)
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):

**OS and version**:Windows

**Comment by clairebianchi** [comment]
@chandra2ravi I am passing on this information to the metadata team. Thank you for reporting this.
