### ISSUE TITLE
sf help command inconsistency

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#2240]
### Summary
`sf` supports listing command words in any order.  `sf package install` is the same as `sf install package`.  However, `sf package help` is not the same as `sf help package`.  `sf package --help` (or `-h`) do work as expected.

### Steps To Reproduce

In ANY sfdx project, run `sf package help`

### Expected result
Output should be the same as `sh help package`

### Actual result
The command was not recognized, and an alternate command was suggested.
```
 ›   Warning: package help is not a sf command.
Did you mean package delete? [y/n]: 
```

### System Information
Running zsh on Mac OS 13.1 Ventura

sf version output:
```json
{
  "cliVersion": "@salesforce/cli/1.82.6",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v17.2.0",
  "osVersion": "Darwin 22.2.0",
  "shell": "zsh",
  "rootPath": "/Users/jclark/.nvm/versions/node/v17.2.0/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.17 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.82.6 (core)",
    "apex 2.3.2 (core)",
    "auth 2.8.1 (core)",
    "data 2.3.22 (core)",
    "deploy-retrieve 1.11.4 (core)",
    "info 2.6.19 (core)",
    "limits 2.3.18 (core)",
    "login 1.2.11 (core)",
    "org 2.9.7 (core)",
    "packaging 1.17.3 (user)",
    "schema 2.3.12 (core)",
    "settings 1.4.10 (core)",
    "sobject 0.1.23 (core)",
    "source 2.10.13 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.20 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.16 (core)"
  ]
}
```

**Comment by mshanemc** [comment]
yeah, that one's kinda confusing in a spaces-not-colons scenario.

The command is named `help` and it takes an argument that is the topic/command name.  If you don't want the `help` command, you can use the `--help` flag on any command.

I think we could modify the `did you mean` to look for `help` in the arguments and give a better output.
