### ISSUE TITLE
Allow SF Executable to Return Non-Zero Exit Codes

### ISSUE THREAD

**Issue by mcarvin8** [forcedotcom/cli#2243]
### Summary

Cancelled or failed validations and deployments do not return a non-zero exit code. As a DevOps Engineer, I would like the `sf project deploy` command to exit with a non-zero exit code, so that I can easily halt my CI/CD jobs when a deployment failure occurs.

### Steps To Reproduce

- Run `sf project deploy validate` or `sf project deploy start`.
- Cancel the deployment in Salesforce.
- Record the exit code from the sf executable.

### Expected result
SF should return a non-zero exit code that would fail a CI/CD pipeline.

### Actual result
SF returns a zero exit code and the CI/CD pipeline passes.

### System Information
bash shell in the latest Ubuntu Docker image.
Using Python 3 to call the SF executable with subprocess as such:
```
    try:
        subprocess.run(cmd, check=True, shell=True)
    except subprocess.CalledProcessError as exception:
        sys.exit(1)
```

```json
{
  "cliVersion": "@salesforce/cli/1.82.6",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Linux 5.15.108",
  "shell": "bash",
  "rootPath": "/usr/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.17 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.[37](https://scm.platform.us-west-2.avalara.io/matthew.carvin/carvin/-/jobs/12454660#L37) (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.82.6 (core)",
    "apex 2.3.2 (core)",
    "auth 2.8.1 (core)",
    "data 2.3.22 (core)",
    "deploy-retrieve 1.11.4 (core)",
    "info 2.6.19 (core)",
    "limits 2.3.18 (core)",
    "login 1.2.11 (core)",
    "org 2.9.7 (core)",
    "schema 2.3.12 (core)",
    "settings 1.4.10 (core)",
    "sobject 0.1.23 (core)",
    "source 2.10.13 (core)",
    "telemetry 2.2.0 (core)",
    "templates [55](https://scm.platform.us-west-2.avalara.io/matthew.carvin/carvin/-/jobs/12454660#L55).4.20 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.16 (core)",
    "sfdx-git-delta 5.22.0 (user)"
  ]
}
```

**Comment by AllanOricil** [comment]
The cli returns 0 because it successfully received a response when pooling the job status. To do what you want, you have to read the cli response, parse it and fetch the job status code. Non zero status code means the cli could not do what It was suppose to.

**Comment by mcarvin8** [comment]
Thanks for the update. This is different behavior compared to the `sfdx` executable were using (7.170.0). When `sfdx` successfully received a final response from the org and the final response indicated a deployment failure or cancellation, `sfdx` returned a 1 in that case.

**Comment by AllanOricil** [comment]
When I use report and the job fails, I have to read its response `.status` to check if it was 0 or 1. Maybe they decided to make the sync command like the async one?

**Comment by PHI4133** [comment]
Understood. Yes, when you format the output as JSON, the `.status` will return as 1 for failed deployments.

Since the JSON output removes the real-time progress bars from the command, opted just to print all output to the terminal and also re-direct the output to a text file using `tee -a`. 

Then, I just opted for parsing the text file like this for a Successful Validation/Deployment message that the command will print with the `--verbose` flag.

```
    with open(log, 'r', encoding='utf-8') as log_file:
        content = log_file.read()

    pattern = r"Successfully (validated the deployment|deployed)"
    match = re.search(pattern, content)

    if match:
        sys.exit(0)
    else:
        sys.exit(1)
```

**Comment by iowillhoit** [comment]
Yea, for async operations you'll need to check the `status` of the job when running report. Although if you are running the commands sync, you should get a non-zero exit code. Here is what I am seeing with `@salesforce/cli/1.82.6 darwin-arm64 node-v18.15.0` using [Dreamhouse](https://github.com/trailheadapps/dreamhouse-lwc). 


![Image](https://github.com/forcedotcom/cli/assets/1715111/5bb02911-8e31-49cb-84b9-7f70ce7532e0)

**Comment by mcarvin8** [comment]
Closing this issue. `sf` is returning exit codes correctly. There was an issue with how my script was re-directing output to a text file, which masked any failures.

**Comment by iowillhoit** [comment]
Makes sense, thanks for following up @mcarvin8!

**Comment by lordkortex** [comment]
Yes sf and sfdx  returni exit codes correctly. In order to avoid the script maske any failures, try to use this command at begin of the script , in order to get a bash pipeline to output non-zero exit code when a step fails.

`set -e`

You're looking for set -eo pipefail. Add that after the first (#!/bin/bash) line and your script will fail if any part of your script fails.
