### ISSUE TITLE
sf project deploy resume command stopped giving deployment progress immediately 

### ISSUE THREAD

**Issue by shabu74** [forcedotcom/cli#2249]
### Summary
sf project deploy resume command stopped giving deployment progress. It was working perfectly till day before yesterday. There is no error. But no deployment progress

### Steps To Reproduce

- use sf project deploy start with async and grab the deployment job id
- use that job id in sf project deploy resume command

### Expected result

I should see deployment progress

### Actual result
No deployment progress. Just waiting for deployment to be completed with out showing any progress

### System Information

Bash in gitlab yml

```json
Latest version as I am deploying Salesforce CLI every time
```
##### Validating deployment package in UAT org by running below specified test classes (FilesCleanup_Batch_Test)...
Deploy ID: 0Af9h000005QK53CAG

**Comment by shabu74** [comment]
I am using latest version of Salesforce CL every time.

**Comment by WillieRuemmele** [comment]
Hey @shabu74 can you please elaborate on what you're seeing?

I ran those commands sequentially, and the `deploy resume` command picked up the deployment, started the progress bar at 40/91 and I watched it complete the deployment 
```bash
 ➜  sf project deploy start --async
Deploying v58.0 metadata to test-iizdrfqygk4j@example.com using the v58.0 SOAP API.
Deploy ID: 0Af8N00000f0lcWSAQ
Deploy has been queued.

Run "sf project deploy resume --job-id 0Af8N00000f0lcWSAQ" to resume watching the deploy.
Run "sf project deploy report --job-id 0Af8N00000f0lcWSAQ" to get the latest status.
Run "sf project deploy cancel --job-id 0Af8N00000f0lcWSAQ" to cancel the deploy.
➜  dreamhouse-lwc git:(main)  hub:(DevHub) scratch:(test-iizdrfqygk4j@example.com)
 ➜  sf project deploy resume --job-id 0Af8N00000f0lcWSAQ                  
Deploy ID: 0Af8N00000f0lcWSAQ
Status: Succeeded | ████████████████████████████████████████ | 91/91 Components (Errors:0) | 0/0 Tests (Errors:0)

Deployed Source
===============================================================================================================================================================================
| State   Name                                Type                     Path                                                                                                     
| ─────── ─────────────────────────────────── ──────────────────────── ──────────────────────────────────────────────────────────────────────────────────────────────────────── 
| Created FileUtilities                       ApexClass                force-app/main/default/classes/FileUtilities.cls                                                         
| Created FileUtilities                       ApexClass                force-app/main/default/classes/FileUtilities.cls-meta.xml 
```

**Comment by shabu74** [comment]
In GitLab pipeline, I am not getting that progress bar now. It was there before a couple of days.

**Comment by WillieRuemmele** [comment]
@shabu74 if this is in a CI environment, the progress bar is disabled, there's a few [environment variables](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm) you can set to ensure the command won't timeout on long deploys, but we suggest increasing the timeout in your CI env instead.

If you're polling, you should add `--json` flag and get the progress from the `results` object

**Comment by shabu74** [comment]
Thanks. But the progress bar was there withou any additional env variable. Suddenly it has been disabled. I would like to see the dynamic progress. I will read it from json, it will be a one time output, right? 😊

**Comment by WillieRuemmele** [comment]
@shabu74 we changed the way progress bars are displayed in TTY/non-TTY environments and so it'll no longer display in CI.

**Comment by shabu74** [comment]
Ok. But progress bar is still available for force report command. So, normally we expect that for project resume command also. 😊

**Comment by shetzel** [comment]
Tracked internally with W-13701811
