### ISSUE TITLE
add the --purgeOnDelete flag to the force:mdapi:deploy command

### ISSUE THREAD

**Issue by joeythomaschaske** [forcedotcom/cli#225]
**Is your feature request related to a problem? Please describe.**
I am using force:mdapi:deploy and still have to manually go into the org and erase the fields

**What are you trying to do**
Delete fields/classes

**Describe the solution you'd like**
I would like a flag similar to [purgeOnDelete](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy.htm)

**Describe alternatives you've considered**
Using ant mdapi

**Comment by mshanemc** [comment]
added in May2022
https://github.com/forcedotcom/cli/blob/9eddfa9f266d82e902e7ff328f11acad6952c14f/releasenotes/sfdx/README.md?plain=1#L1134
