### ISSUE TITLE
Create loaders to ease the usage of inline assets in lwc

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#2252]
**Is your feature request related to a problem? Please describe.**
Currently there is no native way to work with "inline" static assets in sfdx projects like we can do when creating web apps using webpack or rollup. Developers usually add assets in their components using `loadScript|loadStyles` and static resources (which increases the time a page takes to load), or worse, they copy and paste assets in their components by hand, like a json object or an svg.

**What are you trying to do**
Enhance DX while providing value to Salesforce Users reducing page loading times.

I want to standardize the way developers work with inline assets in LWC components. The goal is to enable developers to load their assets at build time, right before deployment, using Webpack/Rollup loaders triggered with sfdx hooks to add  inline assets in code without the need to manually copy and paste their contents. This could decrease the time pages are loaded because static resources usage would be decreased. For example, I see people using Static Resources to load images in their components instead of using an [inline approach.](https://v4.webpack.js.org/loaders/url-loader/)

**Describe the solution you'd like**

inspired by nuxt: https://v2.nuxt.com/docs/get-started/directory-structure/

loader ideas you can think about: 

- graphql: https://github.com/salesforce/lwc/issues/3581
- json: https://v4.webpack.js.org/loaders/json-loader/
- images: https://v4.webpack.js.org/loaders/url-loader

Developers, or salesforce, would then create their loaders and share with the community.

This is like the env variables feature.

**Describe alternatives you've considered**
I have to create my own solution but I believe this should be done by Salesforce to standardize the way developers work with assets in sfdx projects, like a framework does.

**Additional context**
N/A

**Comment by AllanOricil** [comment]
relates https://github.com/forcedotcom/cli/issues/2282

**Comment by AllanOricil** [comment]
https://github.com/salesforce/lwc/issues/3615

Would be good if you could give ur inputs on this 

@mshanemc @cromwellryan @WillieRuemmele @iowillhoit

**Comment by mshanemc** [comment]
Interesting idea.  I'll defer to some of the LWC folks on the best approach perf-wise (ex: static resources getting cached on Salesforce's CDN might be *better* than this when considered across multiple users) vs. how browsers cache inlined stuff.  I don't spend enough time in web stuff anymore to have a valid opinion.

**Comment by mshanemc** [comment]
Got some feedback: LWC doesn't have something like this on the roadmap (replacing `loadScript`) and it would be a big change.

I passed along the idea--it doesn't belong here and might not see any visible action for awhile given the size (Locker, etc).

From the "can I do this from the client" you probably could via hooks, etc.  The challenge I see would be how to do it backwards on the retrieve (something we really haven't solved for metadata string replacements either).  

Are you imagining a one-way transformation to inline stuff, and never retrieving?

**Comment by AllanOricil** [comment]
I was indeed just thinking about 1 way transformation only. The source of truth for code must always be a git repository.
But I have a few ideas to transform the code back to its original form:

- add comment boundaries in the transformed source files with instructions to let the hook determine how to change it back to its original form.
- add a comment with the original code as base64 in the bottom of the .js file. Something similar to inline source maps. Html and css transformations would also be stringified and encoded as base64, and added to the bottom of the .js file.
- enable the metadata api to store the original source file as a new type of Metadata. You could call it MetadataSourceMap (I'm not creative haha) When retrieving metadata, a hook would check if there is a correspondent MetadataSourceMap file/bundle, and then swap the transformed one with the original. 


The third option seems less error prone, and it would work for all metadata types.

**Comment by AllanOricil** [comment]
@mshanemc @cromwellryan 

so for the graphql loader, this is what I'm doing:


Given a lwc directory containing .graphql|gql files as shown below

````js
my-component
├── myComponent.js
└── myQuery.graphql
````

and the following lwc component
````js
import { myQuery } from './myQuery.graphql';
...

@wire(graphql, {
 query: myQuery
})
````

a pre deploy/push/pack hook automation would ensure .forceignore contains entries to ignore .graphql|.gql files in lwc bundles. These files would still be versioned in git repositories.
````bash
**/lwc/**/*.graphql
**/lwc/**/*.gql
````

a .js file containing the loaded query would be generated

````js
import { gql } from 'lightning/uiGraphQLApi';
const myQuery = gql `query {}`;

export {
 myQuery
}
...

//base64 containing the original graphqlfile file information as a comment for retrievals
````

and imported on the component so that its query reference can be used in @wire adapters

````js
import { gql } from 'lightning/uiGraphQLApi';
import { myQuery } from './myQuery.js';
...

@wire(graphql, {
 query: myQuery
})
````


During a post retrieve, in a sfdx project different than the one where the .graphql|.gql files are versioned, the .graphql|gql files can be recreated using the base64 comment found in the .js modules that were created in the pre deploy/push/pack hook

After retrieving
````js
my-component
├── myComponent.js
└── myQuery.js
````

After passing through the post retrieve hook, `myQuery.js` is deleted and recreated as a .graphql|gql file
````js
my-component
├── myComponent.js
└── myQuery.graphql
````



Jest tests can work with .graphql imports if this transformer is added to the lwc-jest-test package

**Comment by AllanOricil** [comment]
In order for this to work while creating packages versions, new ocliff hook types would have to be created
https://github.com/forcedotcom/cli/issues/2290

**Comment by AllanOricil** [comment]
pre processing graphql queries does not seem to work :/ 
I tried this [example](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.reference_graphql) with this [loader](https://www.npmjs.com/package/babel-plugin-import-graphql)



In the platform, `import { gql } from "lightning/uiGraphQLApi";` gql is converted to  `import { _RandomNumber } from "@salesforce/lds/c__graphql"`; and when it can't be visualized. When printing or hovering over `_RandomNumber` nothing is displayed


This is the pre processed Graphql in AST format I passed to graphql adapter

````js
var bigAccounts = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: {
        kind: "Name",
        value: "bigAccounts"
      },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: {
            kind: "Variable",
            name: {
              kind: "Name",
              value: "minAmount"
            }
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Currency"
            }
          },
          directives: []
        }
      ],
      directives: [],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: {
              kind: "Name",
              value: "uiapi"
            },
            arguments: [],
            directives: [],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                {
                  kind: "Field",
                  name: {
                    kind: "Name",
                    value: "query"
                  },
                  arguments: [],
                  directives: [],
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [
                      {
                        kind: "Field",
                        name: {
                          kind: "Name",
                          value: "Account"
                        },
                        arguments: [
                          {
                            kind: "Argument",
                            name: {
                              kind: "Name",
                              value: "where"
                            },
                            value: {
                              kind: "ObjectValue",
                              fields: [
                                {
                                  kind: "ObjectField",
                                  name: {
                                    kind: "Name",
                                    value: "AnnualRevenue"
                                  },
                                  value: {
                                    kind: "ObjectValue",
                                    fields: [
                                      {
                                        kind: "ObjectField",
                                        name: {
                                          kind: "Name",
                                          value: "gte"
                                        },
                                        value: {
                                          kind: "Variable",
                                          name: {
                                            kind: "Name",
                                            value: "minAmount"
                                          }
                                        }
                                      }
                                    ]
                                  }
                                }
                              ]
                            }
                          }
                        ],
                        directives: [],
                        selectionSet: {
                          kind: "SelectionSet",
                          selections: [
                            {
                              kind: "Field",
                              name: {
                                kind: "Name",
                                value: "edges"
                              },
                              arguments: [],
                              directives: [],
                              selectionSet: {
                                kind: "SelectionSet",
                                selections: [
                                  {
                                    kind: "Field",
                                    name: {
                                      kind: "Name",
                                      value: "node"
                                    },
                                    arguments: [],
                                    directives: [],
                                    selectionSet: {
                                      kind: "SelectionSet",
                                      selections: [
                                        {
                                          kind: "Field",
                                          name: {
                                            kind: "Name",
                                            value: "Id"
                                          },
                                          arguments: [],
                                          directives: []
                                        },
                                        {
                                          kind: "Field",
                                          name: {
                                            kind: "Name",
                                            value: "Name"
                                          },
                                          arguments: [],
                                          directives: [],
                                          selectionSet: {
                                            kind: "SelectionSet",
                                            selections: [
                                              {
                                                kind: "Field",
                                                name: {
                                                  kind: "Name",
                                                  value: "value"
                                                },
                                                arguments: [],
                                                directives: []
                                              }
                                            ]
                                          }
                                        },
                                        {
                                          kind: "Field",
                                          name: {
                                            kind: "Name",
                                            value: "AnnualRevenue"
                                          },
                                          arguments: [],
                                          directives: [],
                                          selectionSet: {
                                            kind: "SelectionSet",
                                            selections: [
                                              {
                                                kind: "Field",
                                                name: {
                                                  kind: "Name",
                                                  value: "displayValue"
                                                },
                                                arguments: [],
                                                directives: []
                                              }
                                            ]
                                          }
                                        }
                                      ]
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    }
  ],
  loc: {
    start: 0,
    end: 339,
    source: {
      body: "query bigAccounts($minAmount: Currency) {\\n  uiapi {\\n    query {\\n      Account(where: { AnnualRevenue: { gte: $minAmount } }) {\\n        edges {\\n          node {\\n            Id\\n            Name {\\n              value\\n            }\\n            AnnualRevenue {\\n              displayValue\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\\n",
      name: "GraphQL request",
      locationOffset: {
        line: 1,
        column: 1
      }
    }
  }
};
export { bigAccounts };

````
