### ISSUE TITLE
Metadata API request failed: Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by pledbetter-cvet** [forcedotcom/cli#2253]
### Summary
June 15, 2023, everything is fine. Come back to work from a week off and "Metadata API request failed: Cannot read properties of null (reading 'split')".

### Steps To Reproduce
Every class I try to deploy in VS Code; same error. I've tried a dozen different versions of the Salesforce CLI Integration extension, still get the error.

**Comment by pledbetter-cvet** [comment]
{
  "cliVersion": "sfdx-cli/7.206.6",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/Users/patrick.ledbetter/.local/share/sfdx/client/7.206.6-140cac7",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.25 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.18 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.1 (core)",
    "community 2.3.2 (core)",
    "custom-metadata 2.1.26 (core)",
    "data 2.3.24 (core)",
    "deploy-retrieve 1.12.0 (core)",
    "info 2.6.20 (core)",
    "limits 2.3.20 (core)",
    "org 2.9.12 (core)",
    "packaging 1.20.0 (core)",
    "schema 2.3.13 (core)",
    "settings 1.4.12 (core)",
    "signups 1.4.22 (core)",
    "source 2.10.15 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.4.21 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.17 (core)",
    "sfdx-cli 7.206.6 (core)"
  ]
}

I've tried with many different, older versions of the CLI; still getting the same error. No issues when running the Doctor command.

**Comment by pledbetter-cvet** [comment]
I've seen this error before, several times. Usually, when I see it, I'm able to install an older version of the CLI and that allows me to keep working. Not this time.

**Comment by cristiand391** [comment]
@pledbetter-cvet can you repro the issue deploy via the CLI?

This repo is for the CLI issues, for vscode extensions you file an issue here: https://github.com/forcedotcom/salesforcedx-vscode/issues

**Comment by YodaDaCoda** [comment]
I'm getting this when doing `sf project deploy resume`

`> sf version --verbose --json`
```json
{
  "cliVersion": "@salesforce/cli/1.82.6",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.5.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.24 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.17 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",    
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.82.6 (core)",
    "apex 2.3.2 (core)",
    "auth 2.8.1 (core)",
    "community 2.2.12 (user)",
    "data 2.3.22 (core)",
    "deploy-retrieve 1.11.4 (core)",
    "info 2.6.19 (core)",
    "limits 2.3.18 (core)",
    "login 1.2.11 (core)",
    "org 2.9.7 (core)",
    "packaging 1.20.0 (user)",
    "schema 2.3.12 (core)",
    "settings 1.4.10 (core)",
    "sobject 0.1.23 (core)",
    "source 2.10.13 (core)",
    "telemetry 2.2.0 (core)",
    "templates 55.4.20 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.16 (core)",
    "sfdx-git-delta 5.19.0 (user)",
    "sfdx-hardis 3.17.0 (user)"
  ]
}
```

`sf project deploy resume --use-most-recent --wait 9999 --json`
```json
{
  "code": 1,
  "context": "DeployMetadataResume",
  "commandName": "DeployMetadataResume",
  "data": {
    "id": "0Af1y00000s7b0KCAQ"
  },
  "message": "Metadata API request failed: Cannot read properties of null (reading 'split')",
  "name": "MetadataTransferError",
  "status": 1,
  "stack": "MetadataTransferError: Metadata API request failed: Cannot read properties of null (reading 'split')\n    at MetadataApiDeploy.pollStatus (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\client\\metadataTransfer.js:84:27)\n    at async DeployMetadataResume.run (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\plugin-deploy-retrieve\\lib\\commands\\project\\deploy\\resume.js:36:24)\n    at async DeployMetadataResume._run (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\command.js:117:22)\n    at async Config.runCommand (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\config\\config.js:329:25)\n    at async run (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\main.js:89:16)\nDUE TO:\nTypeError: Cannot read properties of null (reading 'split')\n    at new GitConfig (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\isomorphic-git\\index.cjs:1604:30)\n    at GitConfig.from (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\isomorphic-git\\index.cjs:1627:12)\n    at GitConfigManager.get (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\isomorphic-git\\index.cjs:1750:22)\n    at async _getConfig (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\isomorphic-git\\index.cjs:5397:18)\n    at async normalizeAuthorObject (C:\\Userjs:417:9)\n    at async C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\source-tracking\\lib\\sourceTracking.js:493:21\n    at async Lifecycle.emit (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\core\\lib\\lifecycleEvents.js:181:17)\n    at async MetadataApiDeploy.post (C:\\Users\\will\\github\\rtba\\node_modjs:417:9)\n    at async C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\source-tracking\\lib\\sourceTracking.js:493:21\n    at async Lifecycle.emit (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\core\\lib\\lifecycleEvents.js:181:17)\n    at async MetadataApiDeploy.post (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\client\\metadataApiDeploy.js:348:17)\n    at async MetadataApiDeploy.pollStatus (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\client\\metadataTransfer.js:73:28)\n    at async DeployMetadataResume.run (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\plugin-deploy-retrieve\\lib\\commands\\project\\deploy\\resume.js:36:24)\n    at async DeployMetadataResume._run (C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\command.js:117:22)",
  "exitCode": 1,
  "warnings": []
}
```

**Comment by mshanemc** [comment]
digging all the way down, it looks like we're getting back a metadata component without its [fullName property](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deployresult.htm#deploymessage) set.

It's maybe the same root cause as https://github.com/forcedotcom/cli/issues/2229--something has changed recently that's causing the metadata API to provide incomplete responses.  Which is *probably* why older CLIs don't help.

that code is here https://github.com/forcedotcom/source-deploy-retrieve/blob/856cc16515efaec759371af689b4bec739677ee7/src/client/metadataApiDeploy.ts#L209-L210 if you want to debug and find out what component is missing its information.

The fact that this is happening on a single apex class deployment is concerning.

**Comment by mshanemc** [comment]
if you've got a repro repo that will reliably generate the error, that would help a LOT.

**Comment by shetzel** [comment]
This appears to be a problem introduced with the Summer '23 release on the server side.  E.g., possibly some new metadata type.  To get to the solution faster, we'll either need a way to reproduce this or you can find out the problem type by editing the installed CLI code.  Check the stack trace of the error, open the metadataApiDeploy.js file and dump out the component data when the fullName is null.  E.g. in the trace above from YodaDaCode I would edit the `key` function of:
C:\\Users\\will\\github\\rtba\\node_modules\\@salesforce\\cli\\node_modules\\@salesforce\\source-deploy-retrieve\\lib\\src\\client\\metadataApiDeploy.js
To be something like:
```javascript
if (!component.fullName) { console.dir(component, { depth: 8 }) }
```
Then run the deploy again.

**Comment by YodaDaCoda** [comment]
Interesting that the stack trace doesn't mention that function.

I took a day off yesterday and now I'm struggling to reproduce the error. I can get it pretty reliably in our CI pipeline which quick-deploys pre-validated PRs; I'll see if I can introduce a patch to get that info logged out...

Edit: disregard, that's a different error I'm still looking in to.

**Comment by mshanemc** [comment]
@YodaDaCoda did this problem go away (hopefully the Salesforce release got better) or do we still need to come up with a workaround for it?

**Comment by YodaDaCoda** [comment]
Best I can tell it's gone away -haven't seen it in a while & have been doing plenty of deploys which used to trigger it. :)
