### ISSUE TITLE
The "project deploy <start|validate>" supersede "force:source:deploy" but do not offer the "--coverageformatters" option

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/cli#2255]
**Is your feature request related to a problem? Please describe.**
The "--coverageformatters" option has disappeared : how do we generate code coverage reports ?

**What are you trying to do**
Trying to output code coverage reports.

**Describe the solution you'd like**
Any command which accepts the "--test-level" option to run tests should be able to generate code coverage reports

**Describe alternatives you've considered**
Carry on using "force:source:deploy"

**Comment by WillieRuemmele** [comment]
Hi @RupertBarrow - I totally agree that there's a lack of consistency between the commands, especially ones that can run tests, and I'm working on creating a predictable behavior between all of them... but `project deploy start` has a `--coverage-formatters`

**Comment by RupertBarrow** [comment]
Oh, good !
But that only works asynchronously ?

**Comment by WillieRuemmele** [comment]
it works in sync/async commands, the reports are generated once the deployment completes. So either at the end of the `project deploy start` command for synchronous situations, or it will store the requested test report information and write the reports once the deployment has finished, when a `project deploy report` is ran
