### ISSUE TITLE
ERROR running force:auth:list:  Unexpected end of JSON input

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/cli#226]
### Summary

Getting error running `force:auth:list` after updating to latest version.

### Steps To Reproduce:

```
sfdx update
sfdx force:auth:list
```

### Expected result

See a list of auth connection information and see results of fix

> FIX: When an alias for a username exists, running force:auth:list displays the username and the alias. If no alias exists, the command returns only the username.
> https://developer.salesforce.com/media/salesforce-cli/releasenotes.html

### Actual result

```
(node:14538) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
ERROR running force:auth:list:  Unexpected end of JSON input
```

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): `sfdx-cli/7.31.0-6a986f8be5 linux-x64 node-v10.15.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.3
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.4.0 (core)
├─ salesforcedx-templates 47.3.2 (core)
└─ salesforce-alm 47.7.0 (core)

sfdx-cli 7.31.0 (core)
sfdx-waw-plugin 1.5.0
```

**OS and version**: `Ubuntu 16.04.6 LTS`

**Comment by alan-morey** [comment]
Updated to lastest again to today, problem still persists.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): `sfdx-cli/7.32.0-b30e0302f0 linux-x64 node-v10.15.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.3
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.5.0 (core)
├─ salesforcedx-templates 47.5.0 (core)
└─ salesforce-alm 47.8.0 (core)

sfdx-cli 7.32.0 (core)
sfdx-waw-plugin 1.5.0
```

**OS and version**: `Ubuntu 16.04.6 LTS`

**Comment by clairebianchi** [comment]
@alan-morey are you getting this error when you run any other commands?

**Comment by alan-morey** [comment]
@clairebianchi So far it has only been `force:auth:list` where this error occurs.

While not exhaustive, the following are some of the commands I am using daily that are working as expected:
 - `force:apex:class:create`
 - `force:apex:log:tail`
 - `force:apex:test:run`
 - `force:auth:web:login`
 - `force:mdapi:deploy`
 - `force:mdapi:describemetadata`
 - `force:mdapi:listmetadata`
 - `force:mdapi:retrieve`
 - `force:org:display`
 - `force:source:deploy`
 - `force:schema:sobject:describe`

**Comment by clairebianchi** [comment]
@alan-morey  Thank you, We are looking into it

**Comment by alan-morey** [comment]
Closing this issue as it is not a bug.

I discovered the cause of the issue I was experience and it was my own fault.

I had an empty `.json` file in `$HOME/.sfdx/` left over from some testing I was doing on my own sfdx plugin, removing this file fixed my issue.

**Comment by gkcd83** [comment]
@alan-morey great works for me for the command sfdx force:org:list, I didn't know why let a user json file empty , I deleted and works fine! thanks so much!

**Comment by prakash-ac** [comment]
I had the same issue although I did not have any empty json file in the .sfdx folder. I removed the json file having file name same as the username of the org I was trying to log into and it worked for me.
