### ISSUE TITLE
SFDX commands using PollingClient throws "CLIError: timed out"

### ISSUE THREAD

**Issue by SakshiV19** [forcedotcom/cli#2267]
Summary:
I'm currently on **sfdx-cli/7.206.6 darwin-x64 node-v18.15.0**
While using PollingClient (salesforce/core) module, the command times out in most of the newer SFDX versions.
Although the other operation continues to work, but this error displays on the terminal.

_CLIError: timed out
at Object.error (/Users/s***/.local/share/sfdx/client/7.206.6-140cac7/node_modules/@oclif/core/lib/errors/index.js:27:15)
at /Users/s***/.local/share/sfdx/client/7.206.6-140cac7/node_modules/@oclif/core/lib/cli-ux/index.js:29:62
at flush (/Users/s***/.local/share/sfdx/client/7.206.6-140cac7/node_modules/@oclif/core/lib/cli-ux/index.js:121:9) {
oclif: { exit: 2 },
code: undefined
}_

It is working fine for v7.179.0 but not for v7.192.0
Not sure about the versions in between this range and when it actually stopped working.

Steps To Reproduce:
TBD

Expected result
It should not time-out.

Actual result
For newer versions, it times out in under a minute.

Additional information: N/A

OS and version: N/A

**Comment by SakshiV19** [comment]
> Hello @SakshiV19 👋 It looks like you didn't include the full Salesforce CLI version information in your issue. Please provide the output of `version --verbose --json` for the CLI you're using (`sf` or `sfdx`).
> 
> A few more things to check:
> 
> * Make sure you've provided detailed steps to reproduce your issue.
>   
>   * A repository that clearly demonstrates the bug is ideal.
> * Make sure you've installed the latest version of Salesforce CLI. ([docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm))
>   
>   * Better yet, try the `rc` or `nightly` versions. ([docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_rc.htm))
> * Try running the `doctor` command to diagnose common issues.
> * Search GitHub for existing related issues.
> 
> Thank you!

Information provided above.

**Comment by shetzel** [comment]
@SakshiV19 - do you have steps to reproduce this?  Lots of commands rely on PollingClient and if this was a widespread issue we'd have a fire on our hands.  E.g., deploying metadata and creating scratch orgs both rely on PollingClient.  This is likely specific to something in your environment.

**Comment by SakshiV19** [comment]
We are also using this while deploying metadata and then we poll for the results of the deployment job in our custom CLI solution. This is where PollingClient is being used.

Although the operation continues to poll even after getting the below error, but every time the wait parameter is used, this error is displayed on the screen :
```
CLIError: timed out
at Object.error (/Users/s***/.local/share/sfdx/client/7.206.6-140cac7/node_modules/@oclif/core/lib/errors/index.js:27:15)
at /Users/s***/.local/share/sfdx/client/7.206.6-140cac7/node_modules/@oclif/core/lib/cli-ux/index.js:29:62
at flush (/Users/s***/.local/share/sfdx/client/7.206.6-140cac7/node_modules/@oclif/core/lib/cli-ux/index.js:121:9) {
oclif: { exit: 2 },
code: undefined
}

```

**Comment by mshanemc** [comment]
is there some code you can share of your implementation?

**Comment by SakshiV19** [comment]
Hi @mshanemc My implementation of `poll() ` doesn't have try, catch yet, which might be a reason for this error. I am working on the same. I will get back in case it doesn't work. Thank you!
