### ISSUE TITLE
sfdx update fails randomly

### ISSUE THREAD

**Issue by AshishSinghSFDC** [forcedotcom/cli#2270]
### Summary
I am currently attempting to update the Salesforce CLI by running the command "sfdx update" in my command prompt. However, I'm encountering an issue where the update process randomly stops  in range of 40-80mb but not till 110mb. 

### Steps To Reproduce
Open the command Prompt and run sfdx update

### Expected result
The job to update CLI should start and finish with a success message

### Actual result
The job is not finishing and getting stuck randomly between 40-80mb but not getting completed till 110 MB.

### System Information
cmd.exe

```json
{
  "cliVersion": "sfdx-cli/7.176.1",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.12.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.5 (core)",
    "@oclif/plugin-commands 2.2.1 (core)",
    "@oclif/plugin-help 5.1.17 (core)",
    "@oclif/plugin-not-found 2.3.7 (core)",
    "@oclif/plugin-plugins 2.1.6 (core)",
    "@oclif/plugin-update 3.0.6 (core)",
    "@oclif/plugin-version 1.1.3 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.12 (core)",
    "@oclif/plugin-which 2.1.1 (core)",
    "alias 2.1.7 (core)",
    "apex 1.3.0 (core)",
    "auth 2.2.19 (core)",
    "community 2.0.14 (core)",
    "config 1.4.22 (core)",
    "custom-metadata 2.0.3 (core)",
    "data 2.1.7 (core)",
    "generator 2.0.9 (core)",
    "info 2.2.4 (core)",
    "limits 2.0.10 (core)",
    "org 2.2.11 (core)",
    "packaging 1.10.1 (core)",
    "schema 2.1.12 (core)",
    "signups 1.2.11 (core)",
    "source 2.3.0 (core)",
    "telemetry 2.0.2 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.4 (core)",
    "user 2.1.16 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "mo-dx-plugin 0.3.2 (user)",
    "salesforce-alm 54.8.3 (core)"
  ],
  "osVersion": "Windows_NT 10.0.22000",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\ashish.singh\\AppData\\Local\\sfdx\\client\\7.176.1-458b658"
}
```

**Comment by AshishSinghSFDC** [comment]
The issue is update command is not working.

**Comment by iowillhoit** [comment]
Hey Ashish 👋 Understood, that is a Github Action that is running some regex. 

We've not heard of any wide-spread update issues.
Could you try uninstalling the CLI by following [these instructions](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm)
Then do a fresh install with [these docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_windows) 

Let us know if you continue to have problems

**Comment by AshishSinghSFDC** [comment]
Thanks @iowillhoit, I uninstalled it and did a fresh installation to overcome this issue.
