### ISSUE TITLE
Retrieve Source from Org results in "Cannot read property 'describer' of undefined"

### ISSUE THREAD

**Issue by will-dinn** [forcedotcom/cli#228]
### Summary

Attempting to retrieve source from a Salesforce scratch org into VSCode results in the error "Cannot read property 'describer' of undefined"

### Steps To Reproduce:

1. Setup a default scratch org with no customisations and set as default org
1.  Run "Retrieve Source from Org" with below package file
1. Observe "Cannot read property 'describer' of undefined" error

### Expected result

Resources retrieved from org

### Actual result

The following error was thrown:
![image](https://user-images.githubusercontent.com/57429137/68445768-ef042980-022e-11ea-94ec-34d622b5a191.png)

### Additional information

This is a screenshot of the structure and types in my package.xml file:
![image](https://user-images.githubusercontent.com/57429137/68445743-dbf15980-022e-11ea-864f-5e3ef9a799fa.png)

**SFDX CLI Version**
sfdx-cli/7.30.13-9e204762d5 win32-x86 node-v10.15.3

**SFDX plugin Version**
![image](https://user-images.githubusercontent.com/57429137/68445662-a3ea1680-022e-11ea-8dd8-f202a95febcc.png)

**OS and version**:
Windows 10

**Comment by clairebianchi** [comment]
@will-dinn Does this happen when you run the command from the command line?

**Comment by will-dinn** [comment]
@clairebianchi if I run the following:
sfdx force:source:retrieve -x _packagefilepath_\package.xml

I get the response:
![image](https://user-images.githubusercontent.com/57429137/68736641-4d694780-0635-11ea-9579-1bb3b0fa25df.png)

**Comment by clairebianchi** [comment]
@will-dinn What are you trying to retrieve from the org? Sounds like there is nothing in the org yet. Also, why are you using source:retrieve instead of source:pull? Scratch orgs are designed to track changes between your local development environment and the org, if you use the source:pull command it will pull all changes that have been made to the org that are not reflected in your dev environment locally.

**Comment by will-dinn** [comment]
@clairebianchi I was originally hoping to revert the configuration of some standard profile files before writing anything to the org. Is the error "Cannot read property 'describer' of undefined" an issue with the CLI or with VSCode?

**Comment by clairebianchi** [comment]
@will-dinn can you send us the stack trace on this?

**Comment by DaneKimZennify** [comment]
I resolved this issue by re-authorizing the org I was pulling from.
