### ISSUE TITLE
sfdx package version create completely remove Admin.profile in managed packages (2gp)

### ISSUE THREAD

**Issue by mekadigital** [forcedotcom/cli#2280]
### Summary
We have a managed package (2gp) which includes the component Admin.profile in it.

When we generate a new package version an error is thrown indicating that the component {Profile=[Admin]} has been removed from the package and as such we can't create a new package version.

### Steps To Reproduce
Try to generate a new package version for an existing managed package (2gp)
sfdx package:version:create -c -d force-app -w 100

The error is thrown.

We don't have a public repo as you need access to our devhub/namespace to recreate the error.  If access is helpful more than happy to find a way to provide it.

We have replicated this on other managed packages in the same namespace.

### Expected result
A new package version is created

### Actual result
Version create.... Create version status: Error
Error (1): Multiple errors occurred: 
(1) Can’t create package version. Removing metadata components from a second-generation managed package is a pilot feature that requires acceptance into a pilot program. 

To join the Remove Metadata Components from 2GP pilot, file a case in the Salesforce Partner Community. 

To create a package version without removing metadata components, restore the removed components and try creating the package version again. Add components {Profile=[Admin]} back into the package version, and create the package version again.

### System Information
We've tested this on Mac & Windows 11 with ZSH and powershell respectively.

% sfdx --version
sfdx-cli/7.207.5 darwin-x64 node-v18.15.0

I've also tested it and replicated it on other managed packages. When replicating the issue, I am not making code changes apart from updating the versionName, versionNumber and ancestorVersion in the sfdx-project.json.

We've also tested it on unlocked 2gp packages and those don't get the error (no ancestry) however they do throw errors that indicate the permissions from the Admin.profile were not included in the test run which is a change in behaviour.

**Comment by mekadigital** [comment]
{
  "cliVersion": "sfdx-cli/7.207.5",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/Users/nich/.local/share/sfdx/client/7.207.5-0cc4ec0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.16 (core)",
    "@oclif/plugin-help 5.2.10 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.3 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.19 (core)",
    "@oclif/plugin-version 1.3.5 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.39 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.2 (core)",
    "community 2.3.2 (core)",
    "custom-metadata 2.1.26 (core)",
    "data 2.3.26 (core)",
    "deploy-retrieve 1.13.3 (core)",
    "info 2.6.22 (core)",
    "limits 2.3.22 (core)",
    "org 2.9.14 (core)",
    "packaging 1.20.0 (core)",
    "schema 2.3.14 (core)",
    "settings 1.4.14 (core)",
    "signups 1.4.22 (core)",
    "source 2.10.19 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.4.22 (core)",
    "trust 2.4.22 (core)",
    "user 2.3.17 (core)",
    "sfdx-cli 7.207.5 (core)"
  ]
}

**Comment by mekadigital** [comment]
I found the known issue, details available here. 
https://issues.salesforce.com/issue/a028c00000tJcJF/not-able-to-create-package-version-using-version-create-command

The listed workaround for anyone else impacted is:

Adding profiles to the package is discouraged, however, we understand that there were already packages built with profiles in them. So it can be resolved by following one of the options,

1) Reach out to salesforce to enable manage package deletion so that you can delete the existing profiles from package.

2) For any reason if option 1 is not suitable then you may have to downgrade SFDX version to v7.199.7.

**Comment by mshanemc** [comment]
I'm going to close this since there's a KI to track it instead of here.
