### ISSUE TITLE
Unable to update sf from 1.84.0

### ISSUE THREAD

**Issue by nikatmavens** [forcedotcom/cli#2285]
### Summary
Hello, I am unable to update to the latest version of sf.

If I run `sf --version` I get:
```
›   Warning: @salesforce/cli update available from 1.84.0 to 1.85.8.
@salesforce/cli/1.84.0 darwin-x64 node-v18.15.0
```

Next if I run `sf update` I get:

```
@salesforce/cli: Updating CLI... already on version 1.85.8-28f45df
```

Initially I had sf installed using npm but encountered some issues so I deleted it using the steps for Mac listed [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm). 

After that I installed it using the link for MacOS from [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_macos).

### System Information

I am running MacOS Ventura 13.1
I am using zsh
```
{
  "cliVersion": "@salesforce/cli/1.84.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.2.0",
  "shell": "zsh",
  "rootPath": "/usr/local/lib/sfdx/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.25 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.18 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.84.0 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.1 (core)",
    "data 2.3.24 (core)",
    "deploy-retrieve 1.12.0 (core)",
    "info 2.6.20 (core)",
    "limits 2.3.20 (core)",
    "login 1.2.11 (core)",
    "org 2.9.12 (core)",
    "schema 2.3.13 (core)",
    "settings 1.4.12 (core)",
    "sobject 0.1.25 (core)",
    "source 2.10.15 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.4.21 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.17 (core)"
  ]
}
```

**Comment by nikatmavens** [comment]
`@salesforce/cli: Updating CLI... already on version 1.85.8-28f45df`

**Comment by shetzel** [comment]
@nikatmavens - it's a bit confusing at the moment, but you can't update the sf CLI with `sf update` when you installed it via the sfdx CLI installer.  If you want to update sf when it's installed with sfdx you must run `sfdx update`.  That should update both sfdx and sf.
As an alternative, you can follow the instructions on how to install the sf v2 beta CLI using the installers [here](https://github.com/salesforcecli/cli/blob/main/.github/workflows/v2-beta.md), then when you run `sf update` it will work as you're expecting.  Our plan is to switch the main install page to point to the sf v2 installers next week Wednesday, July 12th.

Please reopen if this isn't working for you.
