### ISSUE TITLE
Creating a package version with the new sf commands doesn't update sfdx-project.json

### ISSUE THREAD

**Issue by albarivas** [forcedotcom/cli#2287]
### Summary
When I create a package version with the new sf commands, its alias is not added to sfdx-project.json. It's not a problem of the code, as I've tried the same using sfdx commands (concretely those in https://trailhead.salesforce.com/content/learn/modules/unlocked-packages-for-customers/build-your-first-unlocked-package), and it works like a charm. These are the commands that I am using:

### Steps To Reproduce
1. Clone the repo https://github.com/albarivas/plants
2. Connect to your DevHub
3. Run `sf package create --name plants --package-type Unlocked --path force-app --target-dev-hub <DevHub>` --> In this case the alias is added correctly
4. Run` sf package version create --package plants --installation-key-bypass --target-dev-hub <DevHub>` --> In this case it's not

### Expected result
Package version alias gets added to sfdx-project.json

### Actual result
Package version alias is not added to sfdx-project.json

### System Information
I'm using zsh

```json
{
  "cliVersion": "@salesforce/cli/1.84.9",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/Users/aazcona/.volta/tools/image/packages/@salesforce/cli/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.16 (core)",
    "@oclif/plugin-help 5.2.10 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.3 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.19 (core)",
    "@oclif/plugin-version 1.3.5 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.39 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.84.9 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.2 (core)",
    "data 2.3.26 (core)",
    "deploy-retrieve 1.13.3 (core)",
    "dev 0.7.7 (user)",
    "info 2.6.22 (core)",
    "limits 2.3.22 (core)",
    "login 1.2.13 (core)",
    "org 2.9.14 (core)",
    "packaging 1.17.3 (user)",
    "schema 2.3.14 (core)",
    "settings 1.4.14 (core)",
    "sobject 0.1.26 (core)",
    "source 2.10.19 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.4.22 (core)",
    "trust 2.4.22 (core)",
    "user 2.3.17 (core)"
  ]
}
```

Per @mshanemc request, output of `sfdx version --verbose`here:

```json
{
  "cliVersion": "sfdx-cli/7.207.5",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/Users/aazcona/.volta/tools/image/packages/sfdx-cli/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.16 (core)",
    "@oclif/plugin-help 5.2.10 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.3 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.19 (core)",
    "@oclif/plugin-version 1.3.5 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.39 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/lwc-dev-mobile 1.6.0 (user)",
    "@salesforce/lwc-dev-server 2.11.0 (user)",
    "apex 2.3.3 (core)",
    "auth 2.8.2 (core)",
    "community 2.3.2 (core)",
    "custom-metadata 2.1.26 (core)",
    "data 2.3.26 (core)",
    "deploy-retrieve 1.13.3 (core)",
    "info 2.6.22 (core)",
    "limits 2.3.22 (core)",
    "org 2.9.14 (core)",
    "packaging 1.20.0 (core)",
    "schema 2.3.14 (core)",
    "settings 1.4.14 (core)",
    "signups 1.4.22 (core)",
    "source 2.10.19 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.4.22 (core)",
    "trust 2.4.22 (core)",
    "user 2.3.17 (core)",
    "sfdx-cli 7.207.5 (core)"
  ]
}
```

**Comment by shetzel** [comment]
This command: `sf package version create --package plants --installation-key-bypass --target-dev-hub <DevHub>` is asynchronous so it won't update unless you also wait for the results using `--wait 10` or something similar.  The sf and sfdx CLIs are using the same packaging plugin so it should be the same between the CLIs.  They could be running slightly different versions of the plugin so that could cause a difference but in this case I think it's just the `wait` flag.

By the way, when I ran that command using my devhub and your project I get an error (when I get the report):
Error (1): Multiple errors occurred:
(1) ForecastRESTApiWIthoutSharing: File name mismatch with class name: ForecastRESTApiWithoutSharing

**Comment by albarivas** [comment]
Worked, thank you very much for your help!
