### ISSUE TITLE
When I run sfdx force:source:retrieve --manifest manifest/package.xml -u myOrg from Python script I get ERROR running force:source:retrieve:  Unexpected end of JSON input

### ISSUE THREAD

**Issue by Stepan007** [forcedotcom/cli#229]
When I run sfdx force:source:retrieve --manifest manifest/package.xml -u myOrg from Python script I get ERROR running force:source:retrieve:  Unexpected end of JSON input

I think it's because sfdx command returns return code = 1 immediately. Other sfdx commands work fine from Python.

**Comment by clairebianchi** [comment]
@Stepan007 can you please? provide us with the version of the CLI you are on? and any other information you can give us about your manifest file
