### ISSUE TITLE
The CS detected a suspicious process disabled Windows Defender during install sf-x64.exe (v2 beta cli)

### ISSUE THREAD

**Issue by stoevie** [forcedotcom/cli#2298]
### Summary
This morning I tried to install the v2 Beta version of the new Cli. I used the Windows sf-x64.exe link from this page: https://github.com/salesforcecli/cli/blob/main/.github/workflows/v2-beta.md -> https://developer.salesforce.com/media/salesforce-cli/sf/channels/beta/sf-x64.exe

The installation was succesfull but I got the following message from our security department: The installer tried to disable Windows Defender.

CrowdStrike: The CS detected a suspicious process disabled Windows Defender, a technique commonly used by malware to evade detection. The user ...... seems to download an executable named "sf-x64.exe" using Chrome browser and on Jul. 12, 2023 08:11:13, the user seems to launched this executable from this download path "C:\Users\.......\Downloads\sf-x64.exe". We couldn't retrieve any information from TI concerning his hash "6745c9f9e02050ce0d5d2daad307638d5041ee201293b2cdc7555e226c7316fd". Hash search in the last 7 days, only found executed in this host.

### Steps To Reproduce

Install https://developer.salesforce.com/media/salesforce-cli/sf/channels/beta/sf-x64.exe

### Expected result
No CrowdStrike warning and no attempt to stop Windows Defender.

### Actual result

CrowdStrike: The CS detected a suspicious process disabled Windows Defender, a technique commonly used by malware to evade detection. The user ...... seems to download an executable named "sf-x64.exe" using Chrome browser and on Jul. 12, 2023 08:11:13, the user seems to launched this executable from this download path "C:\Users\.......\Downloads\sf-x64.exe". We couldn't retrieve any information from TI concerning his hash "6745c9f9e02050ce0d5d2daad307638d5041ee201293b2cdc7555e226c7316fd". Hash search in the last 7 days, only found executed in this host.

### System Information
- windows installer executable of the Cli

![image](https://github.com/forcedotcom/cli/assets/51631119/1fb073a0-405c-4b9e-b3bf-40a88c972288)

- Windows 10 Enterprise 22H2
- I couldn't run the cli version verbose command, The security officer asked me to remove this cli as soon as possible.

**Comment by stoevie** [comment]
As said, I had to deinstall the cli, so can't provide the output of sf version --verbose --json

**Comment by mshanemc** [comment]
@stoevie there's something in oclif (which creates the windows installers) that does that:
https://github.com/oclif/oclif/blob/15c43daf208755f27ed5aee3ad884d4c3fe8f725/src/commands/pack/win.ts#L85

windows' filesystem already makes install/update pretty slow--I'm concerned that having Defender scan each file change is going to *really* suck.

I'm going to mark this as a feature for oclif because there's probably other oclif scenarios that would need it.  

The feature would be to run the installer with an option to preserve Defender behavior

**Comment by matthewsvensson-bc** [comment]
This also came up for us from the following binary's download link: 

https://developer/[.]salesforce[.]com/media/salesforce-cli/sf/channels/stable/sf-x64.exe
MD5: 9960f69fc48f629446b2d1c396f6eb70

**Comment by stoevie** [comment]
> @stoevie there's something in oclif (which creates the windows installers) that does that: https://github.com/oclif/oclif/blob/15c43daf208755f27ed5aee3ad884d4c3fe8f725/src/commands/pack/win.ts#L85
> 
> windows' filesystem already makes install/update pretty slow--I'm concerned that having Defender scan each file change is going to _really_ suck.
> 
> I'm going to mark this as a feature for oclif because there's probably other oclif scenarios that would need it.
> 
> The feature would be to run the installer with an option to preserve Defender behavior


@mshanemc where can I find this feature request? for me this issue is still relevant. IT departments should manage virus scanner exclusions, not installers.

**Comment by dalla73** [comment]
@stoevie you can install the sf-64.exe unchecking the last option. This option make the install to try disable Windows Defender.
I had the same problem here and I solved with this procedure.
![screen capture 2023-08-17 185044](https://github.com/forcedotcom/cli/assets/40531923/ea70865a-b1fe-4fe5-8137-1d59df1e1a07)

**Comment by stoevie** [comment]
> 

Thanks @dalla73, I will try.

Kr,
Gert

**Comment by stoevie** [comment]
Good morning, I tried the suggestion of @dalla73 , that works and is ok for me. I will close the case.

**Comment by cristiand391** [comment]
Thanks @dalla73 for the tip!
We'll add a section about this in the CLI setup guide.
