### ISSUE TITLE
Performance of core commands

### ISSUE THREAD

**Issue by davidmreed** [forcedotcom/cli#23]
Following up on [Twitter thread](https://twitter.com/ntotten/status/1090989706647691269).

Running VS Code 1.30.2 on Windows 7 with all manner of corporate security and proxies running. All examples below executed in VSC integrated terminal using Bash (installed via MINGW/Git Bash, not WSL).

    $ sfdx -v
    sfdx-cli/6.50.0-9817aece8a (windows-x64) node-v8.9.4

I am using the pre-release version but pinned to API 44.

```
$ time sfdx --version
sfdx-cli/6.50.0-9817aece8a (windows-x64) node-v8.9.4

real    0m3.729s
user    0m0.015s
sys     0m0.031s

```
```
$ time sfdx force:org:list
WARNING: apiVersion configuration overridden at 44.0
=== Orgs
     ALIAS         USERNAME                      ORG ID              CONNECTED STATUS
───  ────────────  ────────────────────────────  ──────────────────  ────────────────
                   david+other@ktema.org         00D36000000YDboEAG  ENOENT
                   david+sfdx@ktema.org          00D1I000002yJUJUA2  invalid_grant
                   david.reed+sfdx3@radian.biz   00D6A000002I66oUAC  invalid_grant
                   david.reed+sfdx4@radian.biz   00Df4000003lKwxEAE  ENOTFOUND
                   david.reed-z7jy@force.com     00DB0000000Y0oEMAS  Connected
(D)                david@ktema.org               00D36000000YDboEAG  Connected
     DevHub        david.reed+sfdx@radian.biz    00D1N000002cKIQUA2  invalid_grant
     Prod_Deploy   david.reed+devops@radian.biz  00D1U000000t6NvUAI  ENOENT
     newhub        david.reed+sfdx6@radian.biz   00D0b000000DNDpEAO  ENOTFOUND
     reports-test  dave.user@ktema.org           00D36000000YDboEAG  ENOENT

No active scratch orgs found. Specify --all to see all scratch orgs

real    0m16.785s
user    0m0.000s
sys     0m0.047s
```
I do have a lot of trial orgs registered here from before Dev Hub became available on Developer Editions. I removed all orgs with `sfdx force:auth:logout -p -a` and reran the time test:

```
$ time sfdx force:org:list
WARNING: apiVersion configuration overridden at 44.0
ERROR:  No orgs can be found.

Try this:
Use one of the commands in force:auth or force:org:create to add or create new scratch orgs.

real    0m12.437s
user    0m0.000s
sys     0m0.077s
```

Opening an org:

```
$ time sfdx force:org:open -u david@ktema.org
WARNING: apiVersion configuration overridden at 44.0
Access org 00D36000000YDboEAG as user david@ktema.org with the following URL: https://david-ktema-dev-ed.my.salesforce.com/secur/frontdoor.jsp?sid=00D36000000YDbo!ARMAQPE7Xnq8.QeUSziUj3HXa3a8nnnExXwDwtGWd.LmoKLuFtH1wlkx_Pe9SJ3KPFSvhn2wAPOspLpdQNFLXO1MjvI52ppi

real    0m20.423s
user    0m0.000s
sys     0m0.078s
```

Happy to gather more timing and logging data if that is helpful.

**Comment by clairebianchi** [comment]
@davidmreed Thank you for the feedback. 

First off the org:list command is a known issue and we will be working on that in this quarter. It is probably worse on Windows but the performance is bad across the board 

Second, for the rest of the commands, this is an issue with Windows that we are experiencing and looking into. Your logs are very helpful, thank you. A few questions:

Is there anything more you can tell me about the setup you have in terms of security? 

If you run similar commands on a windows machine that is not on behind your companies firewall do you experience the same performance, better but still slow performance, or speed you expect? 

Finally has this issue gotten worse or stayed the same over time?

**Comment by davidmreed** [comment]
> Is there anything more you can tell me about the setup you have in terms of security?

Only a little bit, because I don't know a whole lot about it. I can tell you that the machine has additional certificates in place to allow monitoring of secure connections, and that outbound HTTP connections are routed through an internet security appliance (Zscaler). 

> If you run similar commands on a windows machine that is not on behind your companies firewall do you experience the same performance, better but still slow performance, or speed you expect?

Unfortunately, I have only one equivalent (Windows 7) machine, and its connection to my corporate internet security apparatus is permanent.

I can say that on Windows 10, my home machine experiences some similar and some different performance challenges. `sfdx --version` takes only 0.6 seconds, but `sfdx force:org:list` clocks in at 14 seconds (two orgs connected), and `sfdx force:org:open` at 5.5 seconds.

> Finally has this issue gotten worse or stayed the same over time?

I don't know the answer to this one, I'm afraid.

**Comment by clairebianchi** [comment]
@davidmreed thank you for the feedback.

**Comment by clairebianchi** [comment]
@davidmreed a few updates we have updated the CLI to V7 and you should see performance improvements on commands, especially those only run on the client. 

For org:list, in particular, we have introduced a new command auth:list ([see the command reference guide here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_auth.htm)). This command lists the usernames you’ve authorized. Unlike org:list, this command doesn’t check whether orgs are still valid.

I am going to close this issue, but we are continuing to work on performance on an ongoing basis
