### ISSUE TITLE
Redirecting sfdx deploy report is not working

### ISSUE THREAD

**Issue by Mercer44** [forcedotcom/cli#230]
### Summary

I am trying to run a sfdx force:mdapi:deploy:report command and save the output in a file.
The command does save output without --json but throws an error.
With --json, the output file is empty.

### Steps To Reproduce:

1.  Auth to an org.
sfdx force:auth:jwt:grant -a cicd --clientid ${CLIENTID} --jwtkeyfile server.key --username ${USERNAME} --instanceurl ${URL} -s

2.  Create a deployment
sfdx force:mdapi:deploy -f $deployName -c -l RunLocalTests

3. Check that deployment's status 
sfdx force:mdapi:deploy:report -i 0AfS000000gS2yrKAC > deployResult.json
or
sfdx force:mdapi:deploy:report -i 0AfS000000gS2yrKAC --json > deployResult.json

### Expected result

without --json, deployResult.json has the contents of the output.

with --json, deployResult.json has the contents of the output.

### Actual result

without --json, deployResult.json has contents, but given this error: ERROR running force:mdapi:deploy:report:  The metadata deploy operation failed.

with --json, deployResult.json is empty. results are written to my terminal

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.26.0-9118501918 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 46.16.0 (core)
├─ force-language-services 46.23.0 (core)
└─ salesforce-alm 46.21.0 (core)

sfdx-cli 7.26.0 (core)
sfpowerkit 1.20.2

**OS and version**:
osx 10.14.6

**Comment by clairebianchi** [comment]
@Mercer44 I am contacting the metadata api team who owns this command, they will take a look at your issue

**Comment by reda-benhemmouche** [comment]
Hello, 
i think it's similar to my issue.

The **STDOUT** and **command exit code** are not well managed in SFDX. Which make a big issue if you are creating a script to do CI or CD with Jenkins or other CI/CD solution.

When i run this command without JOBID (the default behaviour is to get the last deployment job)

```
$ sfdx force:mdapi:deploy:report -u mpsa_ci08build
Job ID | 0Af0Q00000xe9shSAA
ERROR running force:mdapi:deploy:report:  INVALID_CROSS_REFERENCE_KEY: invalid cross reference id

```
In the first case,i get the result **AND** the sfdx error

But, when i print the result as json  using --json

```
$ sfdx force:mdapi:deploy:report -u mpsa_ci08build --json
{
  "status": 1,
  "name": "sf:INVALID_CROSS_REFERENCE_KEY",
  "message": "INVALID_CROSS_REFERENCE_KEY: invalid cross reference id",
  "exitCode": 1,
  "commandName": "MdapiDeployReportCommand",
  "stack": "sf:INVALID_CROSS_REFERENCE_KEY: INVALID_CROSS_REFERENCE_KEY: invalid cross reference id\n    at module.exports.HttpApi.getError (/Users/redabenh/.local/share/sfdx/client/7.59.0-05e06e37e0/node_modules/jsforce/lib/http-api.js:250:13)\n    at /Users/redabenh/.local/share/sfdx/client/7.59.0-05e06e37e0/node_modules/jsforce/lib/http-api.js:95:22\n    at tryCallOne (/Users/redabenh/.local/share/sfdx/client/7.59.0-05e06e37e0/node_modules/promise/lib/core.js:37:12)\n    at /Users/redabenh/.local/share/sfdx/client/7.59.0-05e06e37e0/node_modules/promise/lib/core.js:123:15\n    at flush (/Users/redabenh/.local/share/sfdx/client/7.59.0-05e06e37e0/node_modules/asap/raw.js:50:29)\n    at process._tickCallback (internal/process/next_tick.js:61:11)\nOuter stack:\n    at Function.wrap (/Users/redabenh/.local/share/sfdx/client/7.59.0-05e06e37e0/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at MdapiDeployReportCommand.catch (/Users/redabenh/.local/share/sfdx/client/7.59.0-05e06e37e0/node_modules/salesforce-alm/dist/ToolbeltCommand.js:246:46)",
  "warnings": []
}
```
I get only the error and the result is not printed !

**Comment by WillieRuemmele** [comment]
this is now fixed in the latest cli version of `sf` or `sfdx`
```
➜  dreamhouse-lwc git:(main)  hub:(DevHub) scratch:(test-ynxltcfl9uqz@example.com)
 ➜  sfdx force source deploy -p force-app -w 0                                                
Warning: We plan to deprecate this command in the future. Try using the "project deploy start" command instead.
Deploying v58.0 metadata to test-ynxltcfl9uqz@example.com using the v58.0 SOAP API.
Deploy ID: 0Af7X00000ypCRtSAM
Deploy has been queued. 

Run "force source deploy cancel -i 0Af7X00000ypCRtSAM -u test-ynxltcfl9uqz@example.com" to cancel the deploy.
Run "force source deploy report -i 0Af7X00000ypCRtSAM -u test-ynxltcfl9uqz@example.com" to get the latest status.
➜  dreamhouse-lwc git:(main)  hub:(DevHub) scratch:(test-ynxltcfl9uqz@example.com)
 ➜  sf force source deploy report -i 0Af7X00000ypCRtSAM > deploy.txt                                          
Warning: We plan to deprecate this command in the future. Try using the "project deploy start" and "project deploy report" pair instead.
DEPLOY PROGRESS | ████████████████████████████████████████ | 91/91 Components
➜  dreamhouse-lwc git:(main) ✗  hub:(DevHub) scratch:(test-ynxltcfl9uqz@example.com)
 ➜  more deploy.txt                  
Deploy ID: 0Af7X00000ypCRtSAM
Status: Succeeded
Deployed: 91/91 Errors: 0
Tests Complete: 0/0 Errors: 0
➜  dreamhouse-lwc git:(main) ✗  hub:(DevHub) scratch:(test-ynxltcfl9uqz@example.com)
 ➜  sf force source deploy report -i 0Af7X00000ypCRtSAM --json > deploy.json
➜  dreamhouse-lwc git:(main) ✗  hub:(DevHub) scratch:(test-ynxltcfl9uqz@example.com)
 ➜  more deploy.json 
{
  "status": 0,
  "result": {
    "checkOnly": false,
    "completedDate": "2023-06-22T13:31:49.000Z",
    "createdBy": "0057X000005xi4K",
    "createdByName": "User User",
```

you can see that my `deploy.txt` file is populated with the `deploy report` stdout
