### ISSUE TITLE
QuickAction not converting to mdapi format

### ISSUE THREAD

**Issue by Mercer44** [forcedotcom/cli#231]
### Summary
When trying to convert source format to mdapi format, i get an error saying quickAction is an unexpected file.
sfdx force:source:convert -r diffqa/force-app/ -d deployqa$currdate/
ERROR running force:source:convert:  Expected file at path: Documents/Company-SALESFORCE/diffqa/force-app/main/default/quickActions/Contact.Customer_Connection_Call.quickAction-meta.xml

### Steps To Reproduce:

1.  Create a force-app folder with only a global quickAction
2.  Try to convert to mdapi format, sfdx force:source:convert

### Expected result

Expect conversion to occur and mdapi folder to be generated with package.

### Actual result

CLI errors out

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.26.0-9118501918 darwin-x64 node-v10.15.3
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
etcopydata 0.4.4
generator 1.1.1 (core)
salesforcedx 46.16.0 (core)
├─ force-language-services 46.23.0 (core)
└─ salesforce-alm 46.21.0 (core)

sfdx-cli 7.26.0 (core)
sfpowerkit 1.20.2
**OS and version**:
Macos 10.14.6

**Comment by mshanemc** [comment]
Works fine now.
