### ISSUE TITLE
sf project tracking commands do not follow command ordering convention

### ISSUE THREAD

**Issue by kyle-blair** [forcedotcom/cli#2311]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
The `sf project delete tracking` and `sf project reset tracking` do not follow the `sf` cli's command ordering convention. Nouns/objects come first, followed by the verb/action operating on those objects i.e. `sf alias set`. By that convention, it seems like the tracking commands should be `sf project tracking delete` and `sf project tracking reset`?

### Steps To Reproduce

N/A

### Expected result
The tracking delete and reset commands are in the order `sf project tracking delete` and `sf project tracking reset`.

### Actual result
The tracking delete and reset commands are in the order `sf project delete tracking` and `sf project reset tracking`.

### System Information
```json
{
  "cliVersion": "@salesforce/cli/1.84.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 21.6.0",
  "shell": "bash",
  "rootPath": "/Users/user/.local/share/sfdx/client/7.206.6-140cac7/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.0 (core)",
    "@oclif/plugin-commands 2.2.15 (core)",
    "@oclif/plugin-help 5.2.9 (core)",
    "@oclif/plugin-not-found 2.3.25 (core)",
    "@oclif/plugin-plugins 3.1.2 (core)",
    "@oclif/plugin-search 0.0.17 (core)",
    "@oclif/plugin-update 3.1.18 (core)",
    "@oclif/plugin-version 1.3.4 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.37 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.84.0 (core)",
    "apex 2.3.3 (core)",
    "auth 2.8.1 (core)",
    "data 2.3.24 (core)",
    "deploy-retrieve 1.12.0 (core)",
    "info 2.6.20 (core)",
    "limits 2.3.20 (core)",
    "login 1.2.11 (core)",
    "org 2.9.12 (core)",
    "packaging 1.20.1 (user)",
    "schema 2.3.13 (core)",
    "settings 1.4.12 (core)",
    "sobject 0.1.25 (core)",
    "source 2.10.15 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.4.21 (core)",
    "trust 2.4.20 (core)",
    "user 2.3.17 (core)"
  ]
}
```

**Comment by mshanemc** [comment]
Check out the current command structure guidelines here: https://github.com/salesforcecli/cli/wiki/Design-Guidelines#Command-Structure

You'll see a lot of commands structures have been reorganized.  ex: 
`force:org:create` => `org create scratch`
`force:data:record:create` => `data create record`

**Comment by kyle-blair** [comment]
@mshanemc Thanks for the link, I read that a while ago but didn't want to go hunting for it. So my example was wrong because the tracking commands do follow the convention.

However, I believe my point still stands that this convention is applied inconsistently. Take these examples instead: `sf package version create` and `sf project deploy validate`. There's some nuance, but I think `version` and `deploy` are the resources in this context and `create` and `validate` are the actions. Meaning those commands do not follow the `<topic> <action> <resource> [flags]` convention. I called out the tracking example because it seemed to be in a different order than other commands.

I'm not trying to be pedantic here; I just want to call attention to what I see as usability issues stemming from inconsistency. There are a lot of topics/actions/resources in the cli so users are likely to rely heavily on convention rather than memorization. Since correcting the issue would constitute a breaking change, if it's addressed earlier it can potentially reduce the impact.

**Comment by mshanemc** [comment]
@kyle-blair I agree that the `package` commands don't follow the new styles.  

We're getting into some org chart stuff here...that's a plugin that the CLI team doesn't own and the packaging crew is kinda busy with the 1GP => 2GP transition.  And their structure is hard (ex: `package version create report`)

"on the roadmap" is the best I can do for those.

---

FWIW I also agree about `validate` coming after deploy.  It looks weird by itself, but makes more sense in the context of all the other `project deploy foo` commands.  We're balancing naming convention vs. autocomplete/discoverability and trying to keep like things together.

As we did this work, that 3rd property shifted a bit from `resource` to `resource | sub-action`.  This happens a lot when there are followups or related actions to an existing action (ex that `package version create report` or `project deploy preview`).

We had so many arguments about all this noun/verb order stuff that we changed `oclif` to make it moot.  The ordering of terms doesn't matter anymore.  `org create scratch` and `create scratch org` and `scratch org create` will all work fine.  

---

> Since correcting the issue would constitute a breaking change

Additionally, we have the power now in `oclif` now to change command and flag names without breaking stuff--that's how we changed the names of a bunch of commands but they still work under the old names.  

See https://github.com/salesforcecli/plugin-deploy-retrieve/blob/67221f96cd1b13d318d4a3d86eb2bc6d758b91f5/src/commands/project/reset/tracking.ts#L29C30-L29C30.

Commands (and flags) can have `aliases` for backward compatibility and we mark `deprecateAliases` true if we want the command to warn you that it changed (vs. "we meant for it to answer to both names permanently")

**Comment by kyle-blair** [comment]
Yeah, that all makes sense (and is a lot of the nuance I was referring to). Glad to hear you argued about it and that these weren't necessarily simple lapses in diligence. The sub-actions do complicate the situation.

For what it's worth, `sf package create version` does work and that's great. However, I generally use autocomplete to fill out my commands and autocomplete doesn't work for the aliases, so it still causes me a moment of pause trying to think which word comes next. Given the large scope of topics/actions/resources/sub-actions those pauses can add up. Maybe I'd fare better if I just went for it rather than worrying about correctness. Maybe autocomplete can be enhanced to support aliases (sounds like a potential complexity explosion)?

Anyways, glad y'all are thinking about and arguing over these things and thanks for the quick responses @mshanemc!
