### ISSUE TITLE
Suppresse `sf org create scratch` progress logs for CI/CD builds

### ISSUE THREAD

**Issue by melissapalmer** [forcedotcom/cli#2313]
**Is your feature request related to a problem? Please describe.**
When using `sf org create scratch` via CI/CD scripts the progress log comes to 1000's of lines. Is there a way to reduce the number of lines. 
```
·[G·[12A·[JCreating Scratch Org... ⣻
--
209 | RequestId: 2SR4*000000CwzLGAS (https://mit-tlo.my.salesforce.com/2SR4*000000CwzLGAS)
210 | OrgId: 00D040000002usl
211 | Username: test-4apy0n6y0cyg@e*ample.com
212 | ✓ Prepare Request
213 | ✓ Send Request
214 | Wait For Org
215 | Available
216 | Authenticate
217 | Deploy Settings
218 | Done
```

**What are you trying to do**
Reduce the number of log lines on CI/CD builds when running `sf org create scratch` it's fulling up the logs and we battle to see what actual errors are. 

**Describe the solution you'd like**
A way of seeing less progress updates/logs for the `sf org create scratch` command

**Comment by mshanemc** [comment]
for CI, or anytime you're not interested in the human output, you can run this with `--json`.  

You'll get the results in a more parseable form and not all the intermittent status updates.
