### ISSUE TITLE
Internal Salesforce Error on `System.runAs()` Apex Tests

### ISSUE THREAD

**Issue by MatthewBotha** [forcedotcom/cli#2314]
### Summary
We have been using Scratch Orgs for testing as part of our automated deployment, but have encountered a recurring Internal Salesforce error when running our Apex Tests:

```bash
TestClass.ExampleTest                                                                                              Fail     Internal Salesforce Error: 490571133-56370 (-1492806191) (-1492806191)              
```

We have narrowed down the error to two specific tests that both use `System.runAs()` to test permissions. If we run the tests a second time, everything passes as expected. It appears that the first time a `System.runAs()` command is run on a Scratch Org, it throws an Internal Salesforce Error, but subsequent uses work as expected.

Our current workaround is to run the tests twice during our build process, ignoring the first result set that causes the error. However, this is suboptimal and we would like to find a better solution.

### Steps To Reproduce

```bash
# Install Salesforce CLI version 2.0.2
npm install --global @salesforce/cli@2.0.2
sf --version

# Auth into Dev Hub
sf org login sfdx-url -f sfdx_auth -d -a org-shape-dev-hub

# Create Scratch Org and deploy metadata
sf org create scratch --duration-days=1 -f project-scratch-def.json --alias=dep-test-scratch-org --set-default --no-track-source --wait 10 --json
sf project deploy start -d force-app

# Run tests (human readable for debugging)
sf apex run test -r human --code-coverage --wait 5
```

### Expected result

The tests should pass.

### Actual result

```bash
TestClass.ExampleTest                                                                                              Fail     Internal Salesforce Error: 490571133-56370 (-1492806191) (-1492806191)              
```

### System Information

```json
{
  "cliVersion": "@salesforce/cli/2.0.2",
  "architecture": "wsl-x64",
  "nodeVersion": "node-v18.0.0",
  "osVersion": "Linux 5.15.90.1-microsoft-standard-WSL2",
  "shell": "zsh",
  "rootPath": "/home/mbotha/.nvm/versions/node/v18.0.0/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.1 (core)",
    "@oclif/plugin-commands 2.2.17 (core)",
    "@oclif/plugin-help 5.2.11 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.18 (core)",
    "@oclif/plugin-update 3.1.22 (core)",
    "@oclif/plugin-version 1.3.6 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.41 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 2.0.2 (core)",
    "apex 2.3.4 (core)",
    "auth 2.8.4 (core)",
    "data 2.4.5 (core)",
    "deploy-retrieve 1.13.5 (core)",
    "info 2.6.25 (core)",
    "limits 2.3.23 (core)",
    "login 1.2.15 (core)",
    "org 2.9.19 (core)",
    "schema 2.3.17 (core)",
    "settings 1.4.17 (core)",
    "sobject 0.1.32 (core)",
    "source 2.10.22 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.5.2 (core)",
    "trust 2.4.27 (core)",
    "user 2.3.20 (core)"
  ]
}
```
### Additional information
Example from one of our AWS CodeBuild deployments showing the error:
![image](https://github.com/forcedotcom/cli/assets/9319900/cb24a4d3-6f19-4764-9daf-daed2ca4a435)

**Comment by mshanemc** [comment]
@MatthewBotha it's a good repro.  I'll pass it along to the Apex team, but as always, Support Cases help with prioritization and give that team an easier way to collaborate.

**Comment by MRASoft** [comment]
For what it's worth, we are having this problem also. Which is unfortunate because we are trying to ensure security on our external community sites and need to be able to run automated tests as a user of that site and make sure that they don't have access to more data than they need for compliance reasons. I found the link to this post via a search, but haven't found any other links on the salesforce site or anywhere else yet, so if somebody does open a case and salesforce posts the known issue can someone please post a link to that? Thanks
