### ISSUE TITLE
sf project deploy report requiring  a Salesforce project directory

### ISSUE THREAD

**Issue by HerbertHBT** [forcedotcom/cli#2316]
> **Note** 
> - I'm using the latest version of Salesforce CLI (@salesforce/cli/2.0.2 win32-x64 node-v18.15.0)

### Summary
I'm updating my CI/CD scripts with the new sf commands
Due to some specific requirements, our CI/CD jobs/scripts utilize the package.xml instead of the salesforce project directory.
I've successfully replaced the command "force:mdapi:deploy" with "project deploy start" using the flag --metadata-dir, but when I use the "project deploy report" passing the job-id returned by the deploy command, I'm getting the following error:

**RequiresProjectError: This command is required to run from within a Salesforce project directory.
Code: RequiresProjectError** 

### Steps To Reproduce
1 - Retrive a package with any type of metadata using the package.xml file
Example: 
sf project retrieve start --target-metadata-dir "C:\Package" --manifest "C:\package.xml" -o $sourceEnvName

2 - Unzipe the zipped package

3 - Deploy the package using sf project deploy start
Example:
$deployJob = sf project deploy start --async --metadata-dir "C:\Package\unpackaged\" --dry-run --test-level RunLocalTests -o $targetEnvName --json | ConvertFrom-Json
$deployJobId = $deployJob.result.id

4 - Run the sf deploy report command
Example: 
$report = sf project deploy report -i $deployJobId -o $targetEnvName --json --verbose 2>&1 | ConvertFrom-Json

### Expected result
Get the deploy report data

### Actual result
Getting an error 
RequiresProjectError: This command is required to run from within a Salesforce project directory.
Code: RequiresProjectError

### System Information

Windows PowerShell - Prodcut Version 10.0.17763.1

{
  "cliVersion": "@salesforce/cli/2.0.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.17763",
  "shell": "cmd.exe",
  "rootPath": "C:\\Program Files\\sf\\client",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.1 (core)",
    "@oclif/plugin-commands 2.2.17 (core)",
    "@oclif/plugin-help 5.2.11 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.18 (core)",
    "@oclif/plugin-update 3.1.22 (core)",
    "@oclif/plugin-version 1.3.6 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.41 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 2.0.2 (core)",
    "apex 2.3.4 (core)",
    "auth 2.8.4 (core)",
    "data 2.4.5 (core)",
    "deploy-retrieve 1.13.5 (core)",
    "info 2.6.25 (core)",
    "limits 2.3.23 (core)",
    "login 1.2.15 (core)",
    "org 2.9.19 (core)",
    "schema 2.3.17 (core)",
    "settings 1.4.17 (core)",
    "sobject 0.1.32 (core)",
    "source 2.10.22 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.5.2 (core)",
    "trust 2.4.27 (core)",
    "user 2.3.20 (core)",
    "@salesforce/sfdx-scanner 3.14.0 (user)"
  ]
}

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by mshanemc** [comment]
I was not able to reproduce the error.  We made some recent changes to make projects optional, so I think we fixed your issue as well.

Can you try this using the `nightly` channel to confirm I'm not missing anything.  Docs: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_rc

---
couple of notes:
`project retrieve start` has a `--unzip` flag so you don't have to do that as a separate step
`project deploy report` doesn't have a `--verbose` flag
`project deploy report` has a `--use-most-recent` that is a substitute for the jobID so you don't have to do all the json parsing if you're just checking on the last deployment you started.

**Comment by HerbertHBT** [comment]
@mshanemc 

Hi Shane,

Thanks a lot. You are right.
I just installed the nightly version and I was able to run the report and quick deploy sf style commands.

Do you know when this fix will be released in the stable version?

Thanks,
Herbert

**Comment by mshanemc** [comment]
We do promotions on Wed, so it's in `rc` right now.
`rc` becomes `stable` a week later (unless we find something bad we can't patch and don't promote the RC)

https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md#216-july-26-2023-stable-rc

**Comment by HerbertHBT** [comment]
Great!
Thanks again.
