### ISSUE TITLE
NpmError: Failed to find @salesforce/plugin-dev@latest in the registry

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/cli#2318]
### Summary
Trying to install plugin `@salesforce/plugin-dev` but results in error.

### Steps To Reproduce
1. `sf plugins install @salesforce/plugin-dev`

### Expected result
Plugin is installed without error

### Actual result
Install fails with following error:
> NpmError: Failed to find @salesforce/plugin-dev@latest in the registry
> Code: NpmError

### System Information
```json
{
  "cliVersion": "@salesforce/cli/2.0.2",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.16.1",
  "osVersion": "Linux 5.19.0-46-generic",
  "shell": "zsh",
  "rootPath": "/home/alan.morey/.npm-packages/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.1 (core)",
    "@oclif/plugin-commands 2.2.17 (core)",
    "@oclif/plugin-help 5.2.11 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.18 (core)",
    "@oclif/plugin-update 3.1.22 (core)",
    "@oclif/plugin-version 1.3.6 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.41 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 2.0.2 (core)",
    "apex 2.3.4 (core)",
    "auth 2.8.4 (core)",
    "data 2.4.5 (core)",
    "deploy-retrieve 1.13.5 (core)",
    "info 2.6.25 (core)",
    "limits 2.3.23 (core)",
    "login 1.2.15 (core)",
    "org 2.9.19 (core)",
    "schema 2.3.17 (core)",
    "settings 1.4.17 (core)",
    "signups 1.4.22 (user)",
    "sobject 0.1.32 (core)",
    "source 2.10.22 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.5.2 (core)",
    "trust 2.4.27 (core)",
    "user 2.3.20 (core)"
  ]
}

```
### Additional information
Also tried: `sf plugins install dev` produced the same error as above

Referring to releases https://github.com/salesforcecli/plugin-dev/releases, I tried all releases going backwards from 1.1.3 and finally got the install to work with 0.7.13

```bash
$ sf plugins install dev@0.7.13
Installing plugin dev... ⢿ [1/4] Resolving packages...
warning @salesforce/plugin-dev > yeoman-environment > @npmcli/arborist > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
warning @salesforce/plugin-dev > yeoman-environment > pacote > cacache > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
Installing plugin dev... ⣯ [1/4] Resolving packages...
warning @salesforce/plugin-dev > yeoman-environment > pacote > npm-registry-fetch > make-fetch-happen > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
warning @salesforce/plugin-dev > yeoman-environment > @npmcli/arborist > readdir-scoped-modules > debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/supporInstalling plugin dev... ⣟ [2/4] Fetching packages...
warning "@salesforce/plugin-signups > @oclif/core > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
Installing plugin dev... installed v0.7.13
```

However, I would like to update to latest. Running `sf plugins update` does update the `dev 0.7.13 (user)` plugin.

**Comment by mshanemc** [comment]
"works on my machine."

Can you try `npm view @salesforce/plugin-dev` to verify that your npm registry is reachable (sometimes people block npm or proxy it or use an alternate npm registry)

You should see `latest` as 1.1.3.

---
also, you shouldn't have to install this manually-running any command from that plugin should install it for you.

**Comment by alan-morey** [comment]
> "works on my machine." 

Of course it does :grin: 

---

Running `npm view @salesforce/plugin-dev` shows `latest: 1.1.3` as expected.

I uninstalled the plugin `sf plugins uninstall dev` then tried to execute a command to have it automatically install as you mentioned but it automatically installed `0.7.13` and not `latest`

```
$ sf dev generate command -n foobar
Installing plugin dev... ⣯ [1/4] Resolving packages...
warning @salesforce/plugin-dev > yeoman-environment > @npmcli/arborist > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
warning @salesforce/plugin-dev > yeoman-environment > pacote > cacache > @npmcli/move-file@1.1.
Installing plugin dev... ⣷ [1/4] Resolving packages...
warning @salesforce/plugin-dev > yeoman-environment > @npmcli/arborist > readdir-scoped-modules
Installing plugin dev... ⣽ [1/4] Resolving packages...
warning @salesforce/plugin-dev > yeoman-environment > pacote > npm-registry-fetch > make-fetch-
Installing plugin dev... ⣻ [1/4] Resolving packages...
warning @salesforce/plugin-dev > yeoman-environment > @npmcli/arborist > readdir-scoped-modules > debuglog@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/suppor
Installing plugin dev... ⣷ [2/4] Fetching packages...
warning "@salesforce/plugin-signups > @oclif/core > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning "@salesforce/plugin-signups > @oclif/core > ts-node@10.9.1" has unmet peer dependency "
Installing plugin dev... installed v0.7.13

     _-----_     ╭──────────────────────────╮
    |       |    │    Adding a command to   │
    |--(o)--|    │    cli-plugin Version:   │
   `---------´   │          0.7.13          │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

identical package.json
   create src/commands/foobar.ts
   create messages/foobar.md
   create test/commands/foobar.nut.ts
   create test/commands/foobar.test.ts
```

**Comment by alan-morey** [comment]
Looks like the `jitPlugins` configuration for `cli` 2.0.2 says to install `0.7.13`

https://github.com/salesforcecli/cli/blob/3bd4327355c11e54a06cee50e9f8a362c17d3736/package.json#L74

That would at least explain why it automatically installed `0.7.13` for me but I still don't know why I can't install newer versions.

**Comment by mshanemc** [comment]
oops, we may have screwed that JIT version up as part of merging the sfv2 branch for last week.  It's correct in nightly/rc now, so it'll work itself out next week when that becomes `latest`.

https://github.com/salesforcecli/cli/blob/main/package.json#L74 

I'm still not sure why `Failed to find @salesforce/plugin-dev@latest in the registry` happened to you though.  That's a real npm package and it'll install when I try it.

**Comment by alan-morey** [comment]
I updated my cli to `latest-rc` and confirmed this issue is resolved there.

Running `sf dev generate command -n foobar` installs `@salesforce/plugin-dev@1.1.2` just in time, as expected.
