### ISSUE TITLE
sf package install makes over 8 api calls per second while polling

### ISSUE THREAD

**Issue by jeffhube** [forcedotcom/cli#2319]
### Summary
When the `sf package install` command polls installation status, it makes an absurd number of api calls. The package install command ran for 7m23.384s and it made 3570 api calls, which is over 8 per second. On a slower package installation, this consumed the org's entire 15000 api call limit in ~30 minutes of polling.

Additionally, because of the update rate of the spinner, the command generates a significant amount of logs in ci systems. One package installation can result in over 1MB of logs.

### Steps To Reproduce

```bash
sf org create scratch -f config/project-scratch-def.json -d
sf package install -p 04t*** -k *** -r -w 360
```

### Expected result
The command makes api calls to poll package installation status at a reasonable rate (maximum one per second, preferably slower).

### Actual result
The command makes api calls to poll package installation status at an average rate of over 8 per second.

### System Information
Shell: Bash

```json
{
  "cliVersion": "@salesforce/cli/2.0.2",
  "architecture": "wsl-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Linux 5.15.90.1-microsoft-standard-WSL2",
  "shell": "bash",
  "rootPath": "/home/jeff/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.1 (core)",
    "@oclif/plugin-commands 2.2.17 (core)",
    "@oclif/plugin-help 5.2.11 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.18 (core)",
    "@oclif/plugin-update 3.1.22 (core)",
    "@oclif/plugin-version 1.3.6 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.41 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 2.0.2 (core)",
    "apex 2.3.4 (core)",
    "auth 2.8.4 (core)",
    "data 2.4.5 (core)",
    "deploy-retrieve 1.13.5 (core)",
    "info 2.6.25 (core)",
    "limits 2.3.23 (core)",
    "login 1.2.15 (core)",
    "org 2.9.19 (core)",
    "packaging 1.20.1 (user)",
    "schema 2.3.17 (core)",
    "settings 1.4.17 (core)",
    "sobject 0.1.32 (core)",
    "source 2.10.22 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.5.2 (core)",
    "trust 2.4.27 (core)",
    "user 2.3.20 (core)"
  ]
}
```

**Comment by mshanemc** [comment]
aww, that sucks. We'll get it fixed in next week or so.

**Comment by mshanemc** [comment]
this'll be in `sf` `nightly` tomorrow, RC on Wednesday the 26th, and latest the following Wednesday
