### ISSUE TITLE
EERROR running force:source:retrieve

### ISSUE THREAD

**Issue by jyotisingh3** [forcedotcom/cli#232]
Cannot read property 'metadataName' of undefined 

I am using my own package.xml for migration.

**Comment by clairebianchi** [comment]
@jyotisingh3 can you please send me more information. What is your CLI version and OS, Steps to reproduce including: the command with the parameters you are using, any information about the metadata types you are trying to retrieve, the type of org you are retrieving from?

**Comment by megatdanial** [comment]
Currently facing the same issue. Please help look into it

VS Code Information:
Version: 1.38.0 (system setup)
Commit: 3db7e09f3b61f915d03bbfa58e258d6eee843f35
Date: 2019-09-03T21:49:13.459Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

VERSION
  sfdx-cli/7.33.2-045d48473e win32-x64 node-v10.15.3

sfdx plugins --core
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.6.2 (core)
├─ salesforcedx-templates 47.6.2 (core)
└─ salesforce-alm 47.9.0 (core)

sfdx-cli 7.33.2 (core)

Name: Salesforce Extension Pack
Id: salesforce.salesforcedx-vscode
Description: Extensions for developing on the Salesforce Platform
Version: 47.6.0
Publisher: Salesforce
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode

Name: Salesforce CLI Integration
Id: salesforce.salesforcedx-vscode-core
Description: Provides integration with the Salesforce CLI
Version: 47.6.0
Publisher: Salesforce
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-core

**Comment by clairebianchi** [comment]
@megatdanial can you please send steps to reproduce? What metadata is defined in your package?
