### ISSUE TITLE
sf apex run test --json is not returning testRunId after July 13 release

### ISSUE THREAD

**Issue by VenkatNaveenM** [forcedotcom/cli#2320]
- Before July 13 release, I used to get testRunId after apex test run in json output.
- After release, testRunId is missing in json response. I suspect summary itself is missing.
- I saw a difference in Apex Test History in my org, after release Run id is showing on the history whereas before it is missing.
<img width="286" alt="image" src="https://github.com/forcedotcom/cli/assets/41520213/f07a5425-8c29-4c6c-81f4-b8a3f85e1aa6">

**Comment by mshanemc** [comment]
I see what you're seeing.  The test results are coming back with the summary but an empty string for the testRunId. 

![Screenshot 2023-07-21 at 9 44 26 AM](https://github.com/forcedotcom/cli/assets/4261788/b56130ca-9cbe-4878-b39a-b0246b58c989)

Based on what I see [here](https://github.com/forcedotcom/salesforcedx-apex/blob/c986abfabee3edf12f396f1d2e43720988fa3911/src/tests/syncTests.ts#L109-L110), synchronous tests don't have an testRunId.  

You didn't supply the requested information about your CLI/plugin versions OR what command you're executing.

**Comment by VenkatNaveenM** [comment]
**Please find below information:**

SF Version - @salesforce/cli/2.0.2 linux-x64 node-v18.17.0

**Command:**
sf apex run test --test-level RunLocalTests --json > test_outcome_full.json --wait 180 --target-org "$(fullsandbox-username)"
echo "-- Test Summary --"
jq . test_outcome_full.json
echo "--------------------------------------"
testRunId=($(cat test_outcome_full.json | jq ".result.summary.testRunId" | tr -d '"'))
echo "Test Run Id: $testRunId"

**Response:**

-- Test Summary --
{
  "code": 1,
  "context": "Test",
  "commandName": "Test",
  "message": "<h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>",
  "name": "ERROR_HTTP_431",
  "status": 1,
  "stack": "ERROR_HTTP_431: <h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>\n    at HttpApi.getError (/usr/local/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/http-api.js:252:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /usr/local/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/http-api.js:122:23\n    at async Query._execute (/usr/local/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/query.js:413:18)\n    at async /usr/local/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/query.js:346:9",
  "exitCode": 1,
  "warnings": []
}
--------------------------------------
Test Run Id: null
