### ISSUE TITLE
sf apex run test : --output-dir parameter ignored

### ISSUE THREAD

**Issue by RenaudAM** [forcedotcom/cli#2321]
### Summary
When I run the `sf apex run test` command, the `--output-dir` parameter is ignored.

### Steps To Reproduce
Run `sf apex run test` command with `--output-dir` parameter.

### Expected result
File in the output directory specified with the test run ID.

### Actual result
Nothing

### System Information
Bash

$ sf version --verbose --json
{
  "cliVersion": "@salesforce/cli/2.0.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\A0468184\\AppData\\Local\\sf\\client\\2.0.2-3bd4327",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.1 (core)",
    "@oclif/plugin-commands 2.2.17 (core)",
    "@oclif/plugin-help 5.2.11 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.18 (core)",
    "@oclif/plugin-update 3.1.22 (core)",
    "@oclif/plugin-version 1.3.6 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.41 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 2.0.2 (core)",
    "apex 2.3.4 (core)",
    "auth 2.8.4 (core)",
    "data 2.4.5 (core)",
    "deploy-retrieve 1.13.5 (core)",
    "info 2.6.25 (core)",
    "limits 2.3.23 (core)",
    "login 1.2.15 (core)",
    "org 2.9.19 (core)",
    "schema 2.3.17 (core)",
    "settings 1.4.17 (core)",
    "sobject 0.1.32 (core)",
    "source 2.10.22 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.5.2 (core)",
    "trust 2.4.27 (core)",
    "user 2.3.20 (core)"
  ]
}

### Additional information
![image](https://github.com/forcedotcom/cli/assets/129757308/231dad38-dc64-4860-9d44-d8be35b2c08d)

**Comment by mshanemc** [comment]
That starts an asynchronous test run, so the command finishes without any results, so there's nothing to put in your dir.

the output is trying to tell you what to do: 
`sf apex run test -o UAT -l RunLocalTests --output-dir testResults --synchronous` would get results, which would then be savd

(--wait with some large enough number also works)

**Comment by RenaudAM** [comment]
Sorry but this is not correct.
That should create a testrunID.txt file with the ID of the test run. Then we can use this ID to build the test report.
It was the case with sfdx. I have a CI/CD job that fail because of this file no more created. 
How can I schedule my CI/CD tests jobs with this behavior?

**Comment by mshanemc** [comment]
Oh, wow.  I never knew it did that.  This would also be the same in sfdx since it's the same plugin/libary underneath. 
https://github.com/forcedotcom/salesforcedx-apex/blob/c986abfabee3edf12f396f1d2e43720988fa3911/src/tests/testService.ts#L245

That code is owned by the VSCode Extensions folks, and if the problem is there, I can transfer the issue.

If you're trying to script with the CLI, use `--json` output.  If you need a file written (ex: for artifacts for later user) then pipe the `--json` output to a file.

Json output is considered sacred because of these kind of use cases and there's tests to make sure we don't break the format.

```sh
apexTestRepro ../../plugin-apex/bin/dev apex:run:test --class-names Test --json > out.json
➜  apexTestRepro cat out.json 
{
  "status": 0,
  "result": {
    "testRunId": "7078I00001uqDzk"
  },
  "warnings": []
}
```

We *could* try to restore the old behavior, but I'd rather people use stable json best practices for scripting.  I'm going to see if it can be fixed from the plugin.

**Comment by RenaudAM** [comment]
With the JSON output, is it still asynchronous? Because I also would like to avoid a multiple hours running pipeline.

Here is my script that work before.

First I run 
`sfdx force:apex:test:run -u $ORG_ALIAS -l $LOCAL_TESTS -d uat_test_id `

I store the output dir in an Artifact.

3 hours later I run another script
`- export REPORT_ID=‘cat uat_test_id/test-run-id.txt’`
`-sfdx force:apex:test:report -i $REPORT_ID -u $ORG_ALIAS -d uat_test_report -r human -w $WAIT_TIME `

It was great. I would prefer to avoid to have to parse a JSON file…and to wait the 3h with the process running…as we pay the pipeline minutes, so asynchronous solution is preferred.

**Comment by mshanemc** [comment]
yep, it's still asynchronous (unless you tell it to wait).

I think I can restore the old file behavior.  

use `jq` for parsing json.  You could even > the output from it to your file while you wait for the fix.

```
$ sf apex run test --class-names Test --json | jq -r '.result.testRunId'
7078I00001uqH3h
```
