### ISSUE TITLE
Unable to login to org that has a lightning path in its URL

### ISSUE THREAD

**Issue by melvincanafranca** [forcedotcom/cli#2322]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
Unable to log in to org that has a lightning domain

### Steps To Reproduce
1. Download the latest sf cli package from https://developer.salesforce.com/tools/salesforcecli
2. Open a terminal and run sf org login web --alias test --instance-url https://mycompany--test.sandbox.lightning.com/

### Expected result
A web browser will open to allow the user to login to the chosen org instance

### Actual result
An error occurred in the terminal that says 'Invalid instance URL. It should NOT be a lightning domain'

**Comment by mshanemc** [comment]
That's correct.  The error message is telling you what you're doing wrong.  
Don't use the lightning domain for the instance url.  

It should be your MyDomain, something like https://mycompany--test.sandbox.my.salesforce.com

**Comment by melvincanafranca** [comment]
Thank you. I got an OAuth failure a while ago when I changed the format but it seems I am using my.force.com instead of my.salesforce.com.

**Comment by mshanemc** [comment]
Cool, so it worked?  Sorry we have so many domain variations.

**Comment by mshanemc** [comment]
And do the hints show up on your CLI?  if not, can you supply the plugin/version info that the issue template asks for?  these are meant to help you figure it out.

<img width="1269" alt="Screenshot 2023-07-21 at 3 27 23 PM" src="https://github.com/forcedotcom/cli/assets/4261788/18565ef1-0843-4021-98e0-decc8948ab46">
