### ISSUE TITLE
LWS Eslint rules return error on Array.prototype.find

### ISSUE THREAD

**Issue by JackVeromeev** [forcedotcom/cli#2323]
### Summary

New LWC ruleset has a rule to block several `Window` class properties. However, it false-positively blocks the same named properties on `Array` class, particularly `Array.prototype.find` method

### Steps To Reproduce

In an SFDX project, install additional LWS ruleset

```$ npm install --save-dev eslint @locker/eslint-config-locker```

Adjust `.eslintrc.json` file as the following:

```json
{
    "extends": [
        "@salesforce/eslint-config-lwc/recommended",
        "@locker/eslint-config-locker/recommended"
    ],
    "parserOptions": {
        "sourceType": "module"
    },
    "overrides": [
        {
            "files": ["*.test.js"],
            "rules": {
                "@lwc/lwc/no-unexpected-wire-adapter-usages": "off"
            },
            "env": {
                "node": true
            }
        }
    ]
}
```

Create a Lightning Web Component `testEslintIssue` and paste the next code in JS

```javascript
import { LightningElement } from 'lwc';

export default class TestEslintIssue extends LightningElement {

    testOptions = [
        {label: 'a', value: 'a'},
        {label: 'b', value: 'b'},
    ];

    get testOptionB() {
        return this.testOptions.find(option => option.value === "b");
    }
}
```

### Expected result

ESLint audit shows no errors

### Actual result

ESLint audit shows error for using `find` method

<img width="979" alt="image" src="https://github.com/forcedotcom/cli/assets/15068679/d354f91c-6258-4d5c-ad26-7aa4b87fba5f">

The reason is in the rule in `@locker/eslint-plugin-locker/dist/rules/distorted-window-blocked-properties.js` file, but I cannot suggest a correct fix, as not skilled in ESLint rules

### System Information

```json
{
  "cliVersion": "@salesforce/cli/1.45.0",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v16.17.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.1 (core)",
    "@oclif/plugin-plugins 2.1.0 (core)",
    "@oclif/plugin-search 0.0.1 (core)",
    "@oclif/plugin-update 3.0.0 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "config 2.3.3 (core)",
    "deploy-retrieve 1.6.0 (core)",
    "env 1.5.3 (core)",
    "functions 1.13.5 (core)",
    "generate 1.0.16 (core)",
    "info 2.0.1 (core)",
    "login 1.1.2 (core)",
    "sobject 0.0.10 (core)",
    "telemetry 2.0.0 (core)",
    "trust 2.0.3 (core)"
  ],
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli"
}
```

**Comment by JackVeromeev** [comment]
I updated, but apparently the behaviour didn't change

**Comment by mshanemc** [comment]
Hey @JackVeromeev I'm asking the team that owns that where they want their issues sent.

**Comment by JackVeromeev** [comment]
Thank you @mshanemc !
TBH I didn't know where to address the issue, so I wrote it here. Later I found a read-only mirror of the LWS ruleset, but there were no issues, so I'm not sure if anyone watches that repo

**Comment by mshanemc** [comment]
If you have access to support cases, I'd open one.  That's how most teams prioritize their work.

If I hear back, I'll re-open and transfer OR create a WI for them, depending on what they way.
