### ISSUE TITLE
sf (2.0.2) package version create immediate error

### ISSUE THREAD

**Issue by winterrk** [forcedotcom/cli#2324]
### Summary
sf package version create --package "PackageName" --definition-file orgs/dev.json --wait 30 -x --code-coverage --verbose

Works fine in sfdx v7, immediately fails in sf v2.

### Steps To Reproduce
sf package version create --package "PackageName" --definition-file orgs/dev.json --wait 30 -x --code-coverage --verbose

### Expected result
Package Version create process.

### Actual result
Version create...
Error (1): Cannot assign to read only property 'types' of object '#<Object>'

### System Information
Using Powershell7 Terminal in VSCode

  "cliVersion": "@salesforce/cli/2.0.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "F:\\sf-cli\\sf\\client",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.1 (core)",
    "@oclif/plugin-commands 2.2.17 (core)",
    "@oclif/plugin-help 5.2.11 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.18 (core)",
    "@oclif/plugin-update 3.1.22 (core)",
    "@oclif/plugin-version 1.3.6 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.41 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 2.0.2 (core)",
    "apex 2.3.4 (core)",
    "auth 2.8.4 (core)",
    "data 2.4.5 (core)",
    "deploy-retrieve 1.13.5 (core)",
    "info 2.6.25 (core)",
    "limits 2.3.23 (core)",
    "login 1.2.15 (core)",
    "org 2.9.19 (core)",
    "packaging 1.20.1 (user)",
    "schema 2.3.17 (core)",
    "settings 1.4.17 (core)",
    "sobject 0.1.32 (core)",
    "source 2.10.22 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.5.2 (core)",
    "trust 2.4.27 (core)",
    "user 2.3.20 (core)"
  ]
}

**Comment by nsbingham** [comment]
I'm seeing the same failure with @salesforce/cli/2.2.6 linux-arm64 node-v18.17.0 and @salesforce/cli/2.0.2 linux-arm64 node-v18.17.0

**Comment by gadamson-upco** [comment]
Seeing same issue with @salesforce/cli/2.0.2 linux-x64 node-v18.15.0

Command is:
`sf package version create --version-name "$branch_release_name" --branch "$branch_name" --definition-file config/project-scratch-def.json --installation-key "$PACKAGE_KEY" --version-number "$new_version" --package "$PACKAGE_NAME" --tag "$commit_hash" --code-coverage --wait 60 --json`

Tried downgrading to 2.0.1 and upgrading to 2.2.6, both without change. I also tried installing specific older versions of the packaging plugin, 1.21.1 and 1.20.1, which also had no impact.

**Comment by thobanrev** [comment]
I see the same error with @salesforce/cli/2.0.2 darwin-arm64 node-v18.15.0

Here is the full json response

$ sf package version create --package "Revenova Analytics" --installation-key revenova --definition-file project-scratch-def.json --wait 10 --json
{
  "code": 1,
  "context": "PackageVersionCreateCommand",
  "commandName": "PackageVersionCreateCommand",
  "message": "Cannot assign to read only property 'types' of object '#<Object>'",
  "name": "TypeError",
  "status": 1,
  "stack": "TypeError: Cannot assign to read only property 'types' of object '#<Object>'\n    at PackageVersionCreate.cleanGeneratedPackage (/Users/txh/.local/share/sf/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:354:35)\n    at async PackageVersionCreate.createPackageVersionCreateRequestFromOptions (/Users/txh/.local/share/sf/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:308:9)\n    at async PackageVersionCreate.packageVersionCreate (/Users/txh/.local/share/sf/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:477:25)\n    at async PackageVersion.create (/Users/txh/.local/share/sf/node_modules/@salesforce/packaging/lib/package/packageVersion.js:92:30)\n    at async PackageVersionCreateCommand.run (/Users/txh/.local/share/sf/node_modules/@salesforce/plugin-packaging/lib/commands/package/version/create.js:60:24)\n    at async PackageVersionCreateCommand._run (/Users/txh/.local/share/sf/node_modules/@oclif/core/lib/command.js:117:22)\n    at async Config.runCommand (/usr/local/lib/sf/node_modules/@oclif/core/lib/config/config.js:329:25)\n    at async run (/usr/local/lib/sf/node_modules/@oclif/core/lib/main.js:89:16)",
  "exitCode": 1,
  "warnings": []
}

**Comment by okonomi** [comment]
I saw the same error and I found the workaround like this.

In `~/.local/share/sf/package.json`:

```diff
{
  "private": true,
  "oclif": {
    "schema": 1,
    "plugins": [
      {
        "name": "@salesforce/plugin-packaging",
        "tag": "1.20.1",
        "type": "user"
      }
    ]
  },
  "dependencies": {
    "@salesforce/plugin-packaging": "^1.21.4"
  },
+  "resolutions": {
+    "@salesforce/plugin-packaging/@salesforce/packaging/xml2js": "0.6.0"
+  }
}
```

packaging plugin depends `@salesforce/packaging` package, and `@salesforce/packaging` uses `xml2js` package.

It appears that xml2js was recently updated and the change caused the error.

https://www.npmjs.com/package/xml2js/v/0.6.1

So, I pinned xml2js version to v0.6.0.

**Comment by burntsugar** [comment]
Seeing same error on docker image f36cc32d4d2b68af1f7b9ae10ccdbfadcdd27caa2245f3876180ccde83163898 with 7.209

**Comment by mshanemc** [comment]
yep, I see it too.  It's caused by https://github.com/Leonidas-from-XIV/node-xml2js/issues/689

Looks like they already fixed it, so I should be able to get a patch out quickly.

**Comment by mshanemc** [comment]
The workaround for this, if you get a "broken version" *should be*

`sf plugins uninstall @salesforce/plugin-packaging` then try your command again.  Would appreciate confirmation that this picks up the patch.

**Comment by nsbingham** [comment]
Can confirm uninstalling `@salesforce/plugin-packaging` allowed me to create a package with `@salesforce/cli/2.0.2 linux-arm64 node-v18.17.0`.

**Comment by thobanrev** [comment]
the uninstall worked for me as well.
