### ISSUE TITLE
Typo in Package Promotion Command Feedback:  "version-umber" instead of "version-number"

### ISSUE THREAD

**Issue by jdschleicher** [forcedotcom/cli#2326]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary

Seems to be typo in promotion command feedback when attempting to promote version that already has a promoted package

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

create a package version 1.1.0, promote it. 

create a new package version off of that same convention, promote it.

### Expected result

Here's the results of the SFDX CLI Promote Command: {   "code": 1,   "actions": [     "Create a new package version with a different --version-**number**, then promote the package version.\nsf package:version:create -p <name> -n <versionnum> -k <key>\nsf package:version:promote -p 05ixxx"   ],   "context": "PackageVersionPromoteCommand",   "commandName": "PackageVersionPromoteCommand",   "message": "You already promoted a package version with this major.minor.patch version number. For a given major.minor.patch number, you can promote only one version.",   "name": "DUPLICATE_VALUE",   "status": 1,   "stack": "DUPLICATE_VALUE: You already promoted a package version with this major.minor.patch version number. For a given major.minor.patch number, you can promote only one version.\n  

### Actual result

Here's the results of the SFDX CLI Promote Command: {   "code": 1,   "actions": [     "Create a new package version with a different --version-**umber**, then promote the package version.\nsf package:version:create -p <name> -n <versionnum> -k <key>\nsf package:version:promote -p 05ixxx"   ],   "context": "PackageVersionPromoteCommand",   "commandName": "PackageVersionPromoteCommand",   "message": "You already promoted a package version with this major.minor.patch version number. For a given major.minor.patch number, you can promote only one version.",   "name": "DUPLICATE_VALUE",   "status": 1,   "stack": "DUPLICATE_VALUE: You already promoted a package version with this major.minor.patch version number. For a given major.minor.patch number, you can promote only one version.\n  

### System Information

@salesforce/cli/2.1.7 linux-x64 node-v18.17.0

```json
{
  "cliVersion": "@salesforce/cli/2.1.7",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.17.0",
  "osVersion": "Linux 5.15.0-1041-azure",
  "shell": "bash",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.2 (core)",
    "@oclif/plugin-commands 2.2.18 (core)",
    "@oclif/plugin-help 5.2.13 (core)",
    "@oclif/plugin-not-found 2.3.[31](https://github.com/department-of-veterans-affairs/dtc-release-hub/actions/runs/5679964641/job/15393204221#step:4:31) (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.20 (core)",
    "@oclif/plugin-update 3.1.26 (core)",
    "@oclif/plugin-version 1.3.7 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.43 (core)",
    "@oclif/plugin-which 2.2.25 (core)",
    "@salesforce/cli 2.1.7 (core)",
    "apex 2.3.6 (core)",
    "auth 2.8.9 (core)",
    "data 2.5.1 (core)",
    "deploy-retrieve 1.16.0 (core)",
    "info 2.6.31 (core)",
    "limits 2.3.26 (core)",
    "login 1.2.20 (core)",
    "org 2.9.25 (core)",
    "schema 2.3.20 (core)",
    "settings 1.4.20 (core)",
    "sobject 0.1.37 (core)",
    "source 2.10.25 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.5 (core)",
    "trust 2.4.[32](https://github.com/department-of-veterans-affairs/dtc-release-hub/actions/runs/5679964641/job/15393204221#step:4:32) (core)",
    "user 2.3.24 (core)"
  ]
}
```
### Additional information

![image](https://github.com/forcedotcom/cli/assets/3968818/d1c8ba5c-a48c-4b7f-8013-33aa77484844)

**Comment by iowillhoit** [comment]
Thanks for reporting this @jdschleicher! I've got a fix in and it will be release in `latest` in the coming weeks.
