### ISSUE TITLE
Space-separated test classes are not executed during deployment in GitLab pipeline

### ISSUE THREAD

**Issue by shabu74** [forcedotcom/cli#2329]
### Summary
spece-separated test classes specified using --tests are not executed for sf project deploy start command

### Steps To Reproduce

Execute sf project deploy start command with space-separated test classes for --tests argument. (More than one test classes)

### Expected result

Test methods in the specified test classes should be executed and deployment must be successful with successful test class execution or failed with one or more failed test methods

### Actual result

Tests have not been executed and ended up with deployment failure due to 0% code coverage. All were previously working fine.

### System Information
bash

{
  "cliVersion": "@salesforce/cli/2.1.7",
  "architecture": "linux-x64",
  "nodeVersion": "node-v19.9.0",
  "osVersion": "Linux 5.15.0-1039-aws",
  "shell": "bash",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.2 (core)",
    "@oclif/plugin-commands 2.2.18 (core)",
    "@oclif/plugin-help 5.2.13 (core)",
    "@oclif/plugin-not-found 2.3.31 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.20 (core)",
    "@oclif/plugin-update 3.1.26 (core)",
    "@oclif/plugin-version 1.3.7 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.43 (core)",
    "@oclif/plugin-which 2.2.25 (core)",
    "@salesforce/cli 2.1.7 (core)",
    "apex 2.3.6 (core)",
    "auth 2.8.9 (core)",
    "data 2.5.1 (core)",
    "deploy-retrieve 1.16.0 (core)",
    "info 2.6.31 (core)",
    "limits 2.3.26 (core)",
    "login 1.2.20 (core)",
    "org 2.9.25 (core)",
    "schema 2.3.20 (core)",
    "settings 1.4.20 (core)",
    "sobject 0.1.37 (core)",
    "source 2.10.25 (core)",
    "telemetry 2.2.3 (core)",
    "templates [55](https://xxxxxxx/-/jobs/7509457#L55).5.5 (core)",
    "trust 2.4.32 (core)",
    "user 2.3.24 (core)"
  ]
}

```json
PASTE_VERSION_OUTPUT_HERE
```
### Additional information
![image](https://github.com/forcedotcom/cli/assets/10748642/998a9a04-5753-4755-b4e2-c67ab403e5f8)

**Comment by iowillhoit** [comment]
Hello @shabu74, a few questions
- Could you share the exact command you are running? 
- Is this only failing in GitLab? Does it work for you locally?
- Can you try passing the `--tests` flag multiple times?
  - Instead of `--tests Test1 Test2`
  - ...use `--tests Test1 --tests Test2`

**Comment by shabu74** [comment]
sf project deploy start --async --dry-run --ignore-conflicts --manifest releasePackage/package.xml --post-destructive-changes releasePackage/destructiveChangesPost.xml --target-org $targetusername --test-level RunSpecifiedTests --tests $run_specified_test --json --api-version $SF_API_VERSION > deploy-result.json

I did not try it locally. It worked perfectly for me in GitLab till last week. Also I have never tried --tests Test1 --tests Test2. I will try that. But my concern is that it worked fine before

**Comment by shabu74** [comment]
![image](https://github.com/forcedotcom/cli/assets/10748642/484215da-c34f-485e-a3f0-56c1dbb2cbac)

**Comment by shabu74** [comment]
You can see that those test classes have not been considered @iowillhoit

**Comment by shabu74** [comment]
--tests Test1 --tests Test2... This approach worked. But if we need to execute 50 test classes, we need to specify 50 --tests. I don't prefer that

**Comment by cristiand391** [comment]
> sf project deploy start --async --dry-run --ignore-conflicts --manifest releasePackage/package.xml --post-destructive-changes releasePackage/destructiveChangesPost.xml --target-org $targetusername --test-level RunSpecifiedTests --tests $run_specified_test --json --api-version $SF_API_VERSION > deploy-result.json

@shabu74 can you check the value of `$run_specified_test` in CI logs?

I see this works locally:
```
➜  dreamhouse-lwc git:(main) ✗ sf project deploy start --test-level RunSpecifiedTests --tests GeocodingServiceTest TestPropertyController --metadata ApexClass:Geocoding
ServiceTest --metadata ApexClass:TestPropertyController
Deploying v58.0 metadata to test-jbtdeyv8do52@example.com using the v58.0 SOAP API.
Deploy ID: 0Af03000016LQlDCAW
Status: Failed | ████████████████████████████████████████ | 2/2 Components (Errors:0) | 4/6 Tests (Errors:2)

Test Failures [2]
• GeocodingServiceTest.successResponse
  message: System.AssertException: Assertion Failed: Expected: 0, Actual: 1
  stacktrace:
    Class.GeocodingServiceTest.successResponse: line 32, column 1

• TestPropertyController.testGetPagedPropertyList
  message: System.AssertException: Assertion Failed: Expected: 4, Actual: 5
  stacktrace:
    Class.TestPropertyController.testGetPagedPropertyList: line 70, column 1


Test Results Summary
Passing: 4
Failing: 2
Total: 6
Time: 2693
```

**Comment by shabu74** [comment]
My friend, its value is space separated test classes. I have already mentioned that it was working fine for the same implementation. We did not make any change.

**Comment by cristiand391** [comment]
sorry, I didn't saw it was in the screenshot.

We haven't made any change to that specific flag, I wonder if this is a regression caused by the improvements made to the flag parser in the CLI framework...

can you try installing `@salesforce/cli` v2.0.2 in the GitLab pipeline and run it again? that version includes the previous parser and sf 2.1.7 started including the new one.

**EDIT**:
I'm testing a few cases (double/single quotes, spaces, order) using both version but can't get it to fail.

**Comment by iowillhoit** [comment]
I looked into a related issue and was able to replicate this with [Dreamhouse](https://github.com/trailheadapps/dreamhouse-lwc). Hope this helps someone in the future

The problem is that the env var is getting treated as a single string containing all tests names rather than being split on the spaces.

A few things to try:
1. Don't use double quotes around the env var in the command. This _may_ allow it to split correctly on the spaces
    - **Note**: This may not work in certain shells. In zsh I had to run `setopt shwordsplit` for this to work

```shell
TEST_TO_RUN="FileUtilitiesTest GeocodingServiceTest TestPropertyController TestSampleDataController"
sf project deploy validate -d force-app --test-level RunSpecifiedTests --tests $TEST_TO_RUN # <-- no quotes
```


2. Use an array instead

```shell
TESTS_TO_RUN=(FileUtilitiesTest GeocodingServiceTest TestPropertyController TestSampleDataController)
sf project deploy validate -d force-app --test-level RunSpecifiedTests --tests "${TESTS_TO_RUN[@]}"
```

3. Try using `--flags-dir` ([documentation](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_flag_values_in_files.htm)).
    - I have not tested this, but this is generally useful when you have a lot of flags to pass to a command.
