### ISSUE TITLE
Allow Output path for sfdx force:source:retrieve

### ISSUE THREAD

**Issue by ChuckJonas** [forcedotcom/cli#233]
**Is your feature request related to a problem? Please describe.**
It would be nice if you could specify a different root output path when running `sfdx force:source:retrieve`.  

This would allow you to pull down source from multiple orgs and compare them

**Describe the solution you'd like**

Add a optional param (--retrievetargetdir  -r) which would allow you to specify the result path.

**Describe alternatives you've considered**
The only alternative is to clone the project before running the command..... Way less than ideal.

**Additional context**
Blocking https://github.com/ChuckJonas/vscode-salesforce-diff/issues/1

**Comment by ChuckJonas** [comment]
@clairebianchi, yes potentially.  This would really only be for secondary use-cases of this command.  EG: I want to fetch source from two different orgs and compare them using diff-tool.

However, I can see how this behavior could impact other features, so it's honestly not as critical as something like #97...

**Comment by mshanemc** [comment]
This exists since v7.180.  We didn't have your issue linked, though, and I just now noticed this was here.

https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71800-dec-8-2022
