### ISSUE TITLE
[Documentation]. Readme for this repo says to check known issues

### ISSUE THREAD

**Issue by codefriar** [forcedotcom/cli#2332]
### Summary
The description of this repo's readme states: 
> If you have encountered a bug in with the sfdx or sf CLI, please first go to the [Salesforce DX](https://success.salesforce.com/issues_index?tag=Salesforce%20DX) section in Known Issues to determine if there is already a documented workaround. If you don’t see your bug listed, please open an issue on this repository.

However, there is no (longer?) a SalesforceDX section, or category on the known issues page that the link takes us to.

### Steps To Reproduce

Click on the [Salesforce DX] (https://success.salesforce.com/issues_index?tag=Salesforce%20DX) link from the repo description and try to find a DX related category. 

### System Information
N/a

```json
{
  "cliVersion": "@salesforce/cli/2.1.7",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v19.9.0",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/Users/kpoorman/.volta/tools/image/packages/@salesforce/cli/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.2 (core)",
    "@oclif/plugin-commands 2.2.18 (core)",
    "@oclif/plugin-help 5.2.13 (core)",
    "@oclif/plugin-not-found 2.3.31 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.20 (core)",
    "@oclif/plugin-update 3.1.26 (core)",
    "@oclif/plugin-version 1.3.7 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.43 (core)",
    "@oclif/plugin-which 2.2.25 (core)",
    "@salesforce/cli 2.1.7 (core)",
    "apex 2.3.6 (core)",
    "auth 2.8.9 (core)",
    "data 2.5.1 (core)",
    "deploy-retrieve 1.16.0 (core)",
    "info 2.6.31 (core)",
    "limits 2.3.26 (core)",
    "login 1.2.20 (core)",
    "org 2.9.25 (core)",
    "schema 2.3.20 (core)",
    "settings 1.4.20 (core)",
    "sobject 0.1.37 (core)",
    "source 2.10.25 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.5 (core)",
    "trust 2.4.32 (core)",
    "user 2.3.24 (core)",
    "@salesforce/sfdx-scanner 3.14.0 (user)"
  ]
}
```
### Additional information
![image](https://github.com/forcedotcom/cli/assets/642589/e93f6074-db5d-4dde-bf2f-3c43196c4b68)

**Comment by jshackell-sfdc** [comment]
@codefriar , thanks for pointing this out.   The readme was out of date in other ways too, so I just updated it.  Let us know if you see any other problems.  Cheers!
