### ISSUE TITLE
sfdx-cli and @salesforce/cli install bins

### ISSUE THREAD

**Issue by justin-lyon** [forcedotcom/cli#2334]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
I cannot have separate npm installs for `@salesforce/cli` and `sfdx-cli`. 

### Steps To Reproduce

1. `npm uninstall -g @salseforce/cli`
2. `npm uninstall -g sfdx-cli`
3. `npm i -g @salesforce/cli` -> Installs the new 2.0 version
4. `npm i -g sfdx-cli` -> Results in an Error because the 2.0 version has installed the now bundled sfdx executable to the same bin. 
5. `npm uninstall -g @salesforce/cli`
6. `npm i -g sfdx-cli`
7.  `npm i -g @salesforce/cli` -> Results in an Error because the 2.0 version is trying to install to the same bin that the npm sfdx-cli is using.

### Expected result
I can have both installed separately on my machine so that I can continue to migrate sfdx commands at my own pace.

### Actual result
I cannot use both on a single machine.

### System Information

`npm i -g sfdx-cli` version info after installing `sfdx-cli` using npm
```json
{
  "cliVersion": "sfdx-cli/7.209.6",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.1.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/Users/justin/.nvm/versions/node/v18.1.0/lib/node_modules/sfdx-cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.1 (core)",
    "@oclif/plugin-commands 2.2.17 (core)",
    "@oclif/plugin-help 5.2.11 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.18 (core)",
    "@oclif/plugin-update 3.1.22 (core)",
    "@oclif/plugin-version 1.3.6 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.41 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "apex 2.3.4 (core)",
    "auth 2.8.4 (core)",
    "community 2.3.5 (core)",
    "custom-metadata 2.1.30 (core)",
    "data 2.3.26 (user)",
    "deploy-retrieve 1.13.5 (core)",
    "info 2.6.30 (core)",
    "limits 2.3.23 (core)",
    "org 2.9.19 (core)",
    "packaging 1.20.1 (core)",
    "schema 2.3.17 (core)",
    "settings 1.4.17 (core)",
    "signups 1.4.22 (core)",
    "source 2.10.22 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.5.2 (core)",
    "trust 2.4.27 (core)",
    "user 2.3.20 (core)",
    "sfdmu 4.28.0 (user)",
    "sfdx-cli 7.209.6 (core)"
  ]
}
```
`npm i -g @salesforce/cli` version info after separately installing @salesforce/cli using npm
```json
{
  "cliVersion": "@salesforce/cli/2.1.7",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.1.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/Users/justin/.nvm/versions/node/v18.1.0/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.2 (core)",
    "@oclif/plugin-commands 2.2.18 (core)",
    "@oclif/plugin-help 5.2.13 (core)",
    "@oclif/plugin-not-found 2.3.31 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.20 (core)",
    "@oclif/plugin-update 3.1.26 (core)",
    "@oclif/plugin-version 1.3.7 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.43 (core)",
    "@oclif/plugin-which 2.2.25 (core)",
    "@salesforce/cli 2.1.7 (core)",
    "apex 2.3.6 (core)",
    "auth 2.8.9 (core)",
    "data 2.5.1 (core)",
    "deploy-retrieve 1.16.0 (core)",
    "info 2.6.31 (core)",
    "limits 2.3.26 (core)",
    "login 1.2.20 (core)",
    "org 2.9.25 (core)",
    "packaging 1.16.5 (user)",
    "schema 2.3.20 (core)",
    "settings 1.4.20 (core)",
    "sobject 0.1.37 (core)",
    "source 2.10.25 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.5 (core)",
    "trust 2.4.32 (core)",
    "user 2.3.24 (core)"
  ]
}
```

**Comment by mshanemc** [comment]
That's intentional.  They contain the same plugins, so you should not have any issues switching from one to the other.  But they would collide over which one owns the letters `sfdx` so they can't co-exist.

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm
https://developer.salesforce.com/blogs/2023/07/salesforce-cli-sf-v2-is-here

> so that I can continue to migrate sfdx commands at my own pace.

I'm curious what you mean by this.  You can use all the same commands, flags, and even start them with `sfdx` or `sf` and it all works.

**Comment by justin-lyon** [comment]
Thanks for the quick response.

I encountered this while trouble shooting issue #2335 which I've already closed with a resolution. Just growing pains of moving to the new commands. 

A combination of `--check-only` being renamed to `--dry-run` and not being able to locate the correct `sf project deploy ...` command amongst the sub commands of `...deploy start` `deploy validate` and `deploy preview`. 

If I want to continue using the old flags, I do still need to use a separate older npm install version for sfdx-cli. But again this issue was only opened as a tangent while I was trying to figure out how to solve #2335 .

**Comment by mshanemc** [comment]
>If I want to continue using the old flags, I do still need to use a separate older npm install version for sfdx-cli.

# **sf v2 recognizes all of the commands and flags that sfdx does.**

You could run `sf force source deploy ...` and it works.  You could even call it `sfdx force:source:deploy ...` and that's fine.
