### ISSUE TITLE
Lost feature in migrating from `sfdx force:source:deploy` to `sf`

### ISSUE THREAD

**Issue by justin-lyon** [forcedotcom/cli#2335]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
I cannot run a validate only deployment without apex tests.

### Expected result
`sfdx force:source:deploy --checkonly` previously would run a validation only job, and by default it did NOT run apex tests. 

### Actual result
`sf project deploy ...` does not have options to support the same feature. 
`sf project deploy start` can deploy without apex tests using `--test-level NoTestRun`, but this is a deployment, not a validation.
`sf project deploy validate` can run a validate only run, but it defaults to include apex tests and does not support `--test-level NoTestRun` flag.

### System Information

```json
{
  "cliVersion": "@salesforce/cli/2.1.7",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.1.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/Users/justin/.nvm/versions/node/v18.1.0/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.2 (core)",
    "@oclif/plugin-commands 2.2.18 (core)",
    "@oclif/plugin-help 5.2.13 (core)",
    "@oclif/plugin-not-found 2.3.31 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.20 (core)",
    "@oclif/plugin-update 3.1.26 (core)",
    "@oclif/plugin-version 1.3.7 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.43 (core)",
    "@oclif/plugin-which 2.2.25 (core)",
    "@salesforce/cli 2.1.7 (core)",
    "apex 2.3.6 (core)",
    "auth 2.8.9 (core)",
    "data 2.5.1 (core)",
    "deploy-retrieve 1.16.0 (core)",
    "info 2.6.31 (core)",
    "limits 2.3.26 (core)",
    "login 1.2.20 (core)",
    "org 2.9.25 (core)",
    "packaging 1.16.5 (user)",
    "schema 2.3.20 (core)",
    "settings 1.4.20 (core)",
    "sobject 0.1.37 (core)",
    "source 2.10.25 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.5 (core)",
    "trust 2.4.32 (core)",
    "user 2.3.24 (core)"
  ]
}
```
### Additional information
The old force:source:deploy functionality is still available on the individual npm sfdx-cli install. After the 2.0 release of @salesforce/cli I cannot reproduce the original functionality of sfdx force:source:deploy because of this issue #2334

**Comment by justin-lyon** [comment]
`sf project deploy start --dry-run --test-level NoTestRun` is the incantation I was missing.

**Comment by mshanemc** [comment]
@justin-lyon if it helps with your mental model, `deploy validate` is meant as a precursor to `deploy quick` so we want it to produce something that could quick deploy.

--dry-run is the more flexible one

**Comment by andylightful** [comment]
There is still a loss of functionality here - `sf project deploy start --dry-run --test-level NoTestRun` is not accepted for production orgs.

It seems that we're unable to deploy admin related metadata without running all tests in production.

**Comment by RupertBarrow** [comment]
Hi @andylightful , you might need to open a new issue; they (usually) don't spend time reading comments on old closed issues.
