### ISSUE TITLE
sf apex run test --json is not returning testRunId

### ISSUE THREAD

**Issue by VenkatNaveenM** [forcedotcom/cli#2337]
- testRunId is missing in json response. I suspect summary itself is missing.
- I saw a difference in Apex Test History in my org, after release Run id is showing on the history whereas before it is missing.
image.
![image](https://github.com/forcedotcom/cli/assets/41520213/e1a13044-3c2c-4bf7-b4da-df75c5ddacc0)

**Please find below information:**

SF Version - @salesforce/cli/2.0.2 linux-x64 node-v18.17.0

Command:
sf apex run test --test-level RunLocalTests --json > test_outcome_full.json --wait 180 --target-org "$(fullsandbox-username)"
echo "-- Test Summary --"
jq . test_outcome_full.json
echo "--------------------------------------"
testRunId=($(cat test_outcome_full.json | jq ".result.summary.testRunId" | tr -d '"'))
echo "Test Run Id: $testRunId"

Response:

-- Test Summary --
{
"code": 1,
"context": "Test",
"commandName": "Test",
"message": "
Bad Message 431
reason: Request Header Fields Too Large
",
"name": "ERROR_HTTP_431",
"status": 1,
"stack": "ERROR_HTTP_431:
Bad Message 431
reason: Request Header Fields Too Large
\n at HttpApi.getError (/usr/local/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/http-api.js:252:12)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async /usr/local/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/http-api.js:122:23\n at async Query._execute (/usr/local/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/query.js:413:18)\n at async /usr/local/lib/node_modules/@salesforce/cli/node_modules/jsforce/lib/query.js:346:9",
"exitCode": 1,
"warnings": []
}
Test Run Id: null

**Comment by iowillhoit** [comment]
Hello @VenkatNaveenM, 
Please follow all of the instructions on the bug creation template. Most importantly, updating to the latest version of `sf` and providing the full output of `sf versions --verbose --json`.

I am not seeing this locally. They 403 error is odd though, were you seeing that error before the last release? How many tests are you trying to run?
