### ISSUE TITLE
sfdx force:auth:web:login -r https://partners.salesforce.com/services/auth/sso/partnerCommunity does not return

### ISSUE THREAD

**Issue by RupertBarrow** [forcedotcom/cli#234]
### Summary

sfdx force:auth:web:login -r https://partners.salesforce.com/services/auth/sso/partnerCommunity does not return.
Login works correctly in the browser but the CLI stays in waiting mode.

### Steps To Reproduce:

1.  > sfdx force:auth:web:login -r https://partners.salesforce.com/services/auth/sso/partnerCommunity

### Expected result

Normally, after successful login, the CLI displays a messaging sayong you can close the web browser. The CLI then returns successfully.

### Actual result

In our case, the CLI displays no message and does not return, although authentification went well in the web browser.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.22.0-de5c6ecff8 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 46.12.1 (core)
├─ force-language-services 46.16.0 (core)
└─ salesforce-alm 46.15.0 (core)

sfdx-cli 7.22.0 (core)

**OS and version**:
MacOS 10.14.6
Default browser = Safari, version 12.1.2

**Comment by clairebianchi** [comment]
@RupertBarrow does it hang if you remove the -r param?
