### ISSUE TITLE
Can't Create 2nd Generation MANAGED package with Connected App

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#235]
Whenever I try to create a package version with a connected app on it I get the following error message:

![image](https://user-images.githubusercontent.com/55927613/68533499-8c3f8a80-0321-11ea-8f9a-8cb6db61d432.png)

my sfdx version: sfdx-cli/7.28.7-7bceba6f24 win32-x64 node-v10.15.3

I followed this article to create my managed package:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_dev2gp_workflow.htm

Another guy commented the same problem in this blog post:
https://salesforce.stackexchange.com/questions/263112/sfdx-create-package-version-connected-app-error

**Comment by clairebianchi** [comment]
@AllanOricil, I will pass your issue on the packaging team. They track their work in an internal system but I will make sure that the PM has seen this.
