### ISSUE TITLE
DomainNotFoundError for all authenticated orgs with sf org login web

### ISSUE THREAD

**Issue by JuliWaver** [forcedotcom/cli#2397]
### Summary
I authenticated my orgs (Sandboxes and Production) to set an alias with following command: 
`sf org login web --alias cis --instance-url https://test.salesforce.com ` and the connection itself was successful, but when I run the command `sf org list` to double check it I can see that none of my orgs are connected successfully. Following Error message is shown: DomainNotFoundError

### Steps To Reproduce
- Install new sf version
- Authenticate a sandbox with following command: sf org login web --alias <sandboxName> --instance-url https://test.salesforce.com
- After successful authetication run command: sf org list

### Expected result
My Orgs have status connected

### Actual result
======================================================================================
|   ALIAS   USERNAME                            ORG ID             CONNECTED STATUS    
| ─ ─────── ─────────────────────────────────── ────────────────── ─────────────────── 
|   preprod XXX.preprod 123 DomainNotFoundError
|   prod    XXX         124 DomainNotFoundError
|   rollout XXX.rollout 125 DomainNotFoundError
|   testing XXX.testing 126 DomainNotFoundError

### System Information
I use Windows and VSC
sf version: @salesforce/cli/2.2.7 win32-x64 node-v20.5.0

**Comment by cristiand391** [comment]
@JuliWaver does `org display` works for a specific org?
I wonder if it's not correctly saving the instance URL in the auth files.

**Comment by JuliWaver** [comment]
@cristiand391 No, `org display` is not working for any autheticated org. I am getting an error message: `The org cannot be found.`

I also tried to set a default org with command: `sf config set target-dev-hub prod` and it throws an error as well: 

`Invalid config value: org 'prod' is not authenticated`

**Comment by cristiand391** [comment]
@JuliWaver try specifying the org instance url instead of just  `https://test.salesforce.com`. 

That `DomainNotFoundError` seems to come from a failed query using the instance URL of the org to get the current API version supported.

**Comment by JuliWaver** [comment]
@cristiand391 I have done that as well with command: `sf org login web --alias testing --instance-url https://<OurDomain>--testing.sandbox.lightning.force.com/`
Unfortunately the authentication is showing that it was successful, but org list command shows still same error message `DomainNotFoundError`

**Comment by JuliWaver** [comment]
I somehow found a solution. I compared my old setup on my old laptop with the new one and in my current environment variables I missed the entry:

SFDX_DISABLE_DNS_CHECK = true

After setting this variable and a reboot the orgs have now status Connected.
