### ISSUE TITLE
Better handling of git merge conflict markers

### ISSUE THREAD

**Issue by ntotten** [forcedotcom/cli#24]
When a user tries to deploy metadata that has git merge conflict markets in it, we simply return an error like: 

![image](https://user-images.githubusercontent.com/282782/52220935-06605180-286e-11e9-899e-b4679882656d.png)

Because this is a known format of strings and we are encoraging users to use source tracking, we could do a much better job of handling this special case.

For example, when using the git CLI if you try to commit file changes that have unresolved conflicts git will say something like "you are trying to commit files with unresolved conflicts, are you sure?".

We should do something similar and show a better error. "You are trying to deploy metadata to your org that has unresolved git conflicts. Please resolve the conflicts before you deploy."

**Comment by JodieM** [comment]
Yes, an error message like that would be really helpful. Thanks.
