### ISSUE TITLE
How to reproduce force:source:push + pushPackageDirectoriesSequentially with project:deploy:start?

### ISSUE THREAD

**Issue by gsbasso** [forcedotcom/cli#2400]
**Is your feature request related to a problem? Please describe.**
Need to update CI/CD process to use `project:deploy:start` rather than `force:source:push` (which will eventually be deprecated).

**What are you trying to do**
Currently the behaviour of `force:source:push` is influenced by the `pushPackageDirectoriesSequentially` option in the project file. More specifically, the `pushPackageDirectoriesSequentially` option ensures package folders are deployed based on their order in the project file.

**Describe the solution you'd like**
Ideally `project:deploy:start` would honour the `pushPackageDirectoriesSequentially` option. Or alternatively provide an option that replicates the current behaviour.

**Describe alternatives you've considered**
As far as I can tell in order to reproduce the current behaviour I have to explicitly deploy each package folder. So one command will be replaced with multiple commands (one for each package). I don't see how this is an improvement.

**Additional context**
In our experience `sfdx` commands aren't the speediest. So having to replace a single command with, in our case, 10+ commands is likely to increase our build times, which are already too lengthy (30+ minutes to push source, 60+ minutes to run tests).

**Comment by mshanemc** [comment]
I'm making this a discussion.  @gsbasso would love your input and use cases.  Tell all your friends, too.

https://github.com/forcedotcom/cli/discussions/2402
