### ISSUE TITLE
Unable to install SF using PowerShell

### ISSUE THREAD

**Issue by goto-dev-null** [forcedotcom/cli#2401]
**Is your feature request related to a problem? Please describe.**
Pretty straightforward, PowerShell always chokes when trying to install SF via NPM. I have not encountered this with any of the NPM packages I've used which leads me to believe that it is an SF thing and not NPM or Yarn.

I'm not a Bash expert but [from what I can tell](https://stackoverflow.com/a/3224910), it sounds like it's trying to support ancient shells instead of a modern one with pretty widespread adoption.

> Historically, Bourne shells didn't have true and false as built-in commands. true was instead simply aliased to :, and false to something like let 0.
> : is slightly better than true for portability to ancient Bourne-derived shells. 

**What are you trying to do**
Install SF using NPM inside of PowerShell instead of Bash.

**Describe the solution you'd like**
Installation succeeds.

**Describe alternatives you've considered**
Run in bash.

**Additional context**

This has been going on for quite some time and is not new to the latest version which, as of now, is 2.3.8.

```
npm install -g @salesforce/cli@latest
npm ERR! code 1
npm ERR! path C:\Users\USER\AppData\Roaming\npm\node_modules\@salesforce\cli\node_modules\yarn
npm ERR! command failed
npm ERR! command C:\Program Files\PowerShell\7\pwsh.exe -c :; (node ./preinstall.js > /dev/null 2>&1 || true)
npm ERR! :: The term ':' is not recognized as a name of a cmdlet, function, script file, or executable program.
npm ERR! Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
npm ERR! Out-File: Could not find a part of the path 'C:\dev\null'.
npm ERR! true: The term 'true' is not recognized as a name of a cmdlet, function, script file, or executable program.
npm ERR! Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\USER\AppData\Local\npm-cache_logs\2023-08-09T15_17_59_502Z-debug-0.log
```

**Comment by cristiand391** [comment]
@jonnypetraglia what version of npm are you using?

I see that 
![Screenshot 2023-08-10 at 15 58 43](https://github.com/forcedotcom/cli/assets/6853656/dd0dcb00-4cf4-4b41-946e-9172504210b2)
preinstall script is coming from yarn:

but can't repro with npm 9.6.7 and powershell 7 on mac or windows.

**Comment by goto-dev-null** [comment]
Well shoot, looks like it is yarn after all. My bad. Just a lesson for future issue searchers. Upgrading from NPM 8.3.0 to 9.8.1 on Windows didn't fix it, but I'll close this since it isn't SF related.
