### ISSUE TITLE
warning "@salesforce/plugin-packaging > @oclif/core > ts-node@10.9.1" has unmet peer dependency "@types/node@*".

### ISSUE THREAD

**Issue by gourusaiteja** [forcedotcom/cli#2406]
![image](https://github.com/forcedotcom/cli/assets/14835363/23ba7765-b46a-4be9-bda8-dd8c4f7ed6ed)

**Comment by gourusaiteja** [comment]
![image](https://github.com/forcedotcom/cli/assets/14835363/b0b29c76-1986-46d9-b2c1-9174690a65ce)

**Comment by gourusaiteja** [comment]
> **Note** 
> Before you submit your issue, make sure that:
> - Currently we are using the latest version of cli .



> - You've searched both open and closed issues for related posts----> Yes Nothing found
> - You've used the `doctor` command to diagnose common issues ---> yes we have used doctor command 



> - You understand that GitHub Issues don't adhere to any agreement or SLA.---> yes
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.
 
### Summary


< we have updated the cli to latest and while validating the sfdx commands which we use in our pipelines, we found this warning>.
The below commands are facing the warning, But when using sfdx the warning is not appearing.
sf package install
sf package installed list
sf package list
sf package version create
sf package version list
sf package version report
sf package promote
sf package create


Only for SF commands we are seeing this warning. 
 
### Steps To Reproduce
 
> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.

It is happening for when a new container starts in Jenkins irrespective of package commands listed above.

Create a New container 
Install the necessary packages like, Npm, NodeJs, salesforce-cli --global



> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc]( https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.
 Steps to Reproduce:
Install Sf and run any package related commands at the very beginning you will the above warning.
 
### Expected result
 It should execute the commands with out any warnings.
 
### Actual result
 But it is throwing warnings.

 
### System Information
 Bash
 

Sf Version 2.3.8
 
sf version --verbose --json
```json
{
  "cliVersion": "@salesforce/cli/2.3.8",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.17.1",
  "osVersion": "Linux 5.4.0-1056-kvm",
  "shell": "bash",
  "rootPath": "/usr/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.3 (core)",
    "@oclif/plugin-commands 2.2.21 (core)",
    "@oclif/plugin-help 5.2.15 (core)",
    "@oclif/plugin-not-found 2.3.34 (core)",
    "@oclif/plugin-plugins 3.1.8 (core)",
    "@oclif/plugin-search 0.0.21 (core)",
    "@oclif/plugin-update 3.1.28 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.46 (core)",
    "@oclif/plugin-which 2.2.29 (core)",
    "@salesforce/cli 2.3.8 (core)",
    "apex 2.3.9 (core)",
    "auth 2.8.10 (core)",
    "data 2.5.4 (core)",
    "deploy-retrieve 1.16.5 (core)",
    "info 2.6.35 (core)",
    "limits 2.3.27 (core)",
    "login 1.2.23 (core)",
    "org 2.9.28 (core)",
    "packaging 1.21.4 (user)",
    "schema 2.3.21 (core)",
    "settings 1.4.21 (core)",
    "sobject 0.1.42 (core)",
    "source 2.10.28 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.7 (core)",
    "trust 2.5.1 (core)",
    "user 2.3.27 (core)"
  ]
}

----------------------------------------------------------------------------------------------------------------

Sfdx version 2.3.8:- 

sfdx version --verbose --json

```
{
  "cliVersion": "@salesforce/cli/2.3.8",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.17.1",
  "osVersion": "Linux 5.4.0-1056-kvm",
  "shell": "bash",
  "rootPath": "/usr/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.3 (core)",
    "@oclif/plugin-commands 2.2.21 (core)",
    "@oclif/plugin-help 5.2.15 (core)",
    "@oclif/plugin-not-found 2.3.34 (core)",
    "@oclif/plugin-plugins 3.1.8 (core)",
    "@oclif/plugin-search 0.0.21 (core)",
    "@oclif/plugin-update 3.1.28 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.46 (core)",
    "@oclif/plugin-which 2.2.29 (core)",
    "@salesforce/cli 2.3.8 (core)",
    "apex 2.3.9 (core)",
    "auth 2.8.10 (core)",
    "data 2.5.4 (core)",
    "deploy-retrieve 1.16.5 (core)",
    "info 2.6.35 (core)",
    "limits 2.3.27 (core)",
    "login 1.2.23 (core)",
    "org 2.9.28 (core)",
    "packaging 1.21.4 (user)",
    "schema 2.3.21 (core)",
    "settings 1.4.21 (core)",
    "sobject 0.1.42 (core)",
    "source 2.10.28 (core)",
    "telemetry 2.2.3 (core)",
    "templates 55.5.7 (core)",
    "trust 2.5.1 (core)",
    "user 2.3.27 (core)"
  ]
}

```

**Comment by cristiand391** [comment]
@gourusaiteja thanks for the heads up! I'll take a look at those deps causing the warning.
Does it affects the CLI functionality when running packaging commands or is it just about warnings?

**Comment by gourusaiteja** [comment]
Hi @cristiand391 I think Yes, Developers will come into the picture about the warning and ask what is the main cause of this warning. And this warning is appearing in every container.

**Comment by cristiand391** [comment]
I understand, my question was more about if the warnings were affecting a command execution.

Customers don't need to know this, but those warnings are from npm and (talking specifically about ts-node), it shouldn't affect commands.

**Comment by gourusaiteja** [comment]
Hi, @cristiand391 actual function of package Related commands is posting these warnings when we run in our docker container we are just letting you know about the warning. So, In the coming release salesforce tries to resolve it.

**Comment by gourusaiteja** [comment]
Hi, @cristiand391 do we have any updates on this we are expecting to roll out the new version of SF, before doing that we must ensure that the warning disappears from that version, If not Developers will raise a defect/issue regarding this warning.

**Comment by gourusaiteja** [comment]
Hi @cristiand391 Can you provide an update on this

**Comment by cristiand391** [comment]
@gourusaiteja sorry for the late reply.
I was looking at this again last Friday and I think the warning is caused by `oclif/core` not shipping `@types/node` which is a peerDependency of `ts-node` (oclif/core dep):
https://github.com/oclif/core/blob/3c8cc06946b11f53006f4a58cd521eb33fd102a5/package.json#L33
https://github.com/TypeStrong/ts-node/blob/47d4f45f35e824a2515e17383a563be7dba7d8ff/package.json#L150

note: when I looked at CLI dependency tree there's 2 version of `@types/node` that are installed from other deps, but I think the warning is because types/node is expected in oclif/core
```
CLI root level folder
@types/node 20.5.1 ↰ 2 days ago
├── 20.4.0 ⇡ 1 month ago
├─┬ jsforce
│ └── 12.20.55 ⇡ 1 year ago
└─┬ mem-fs
  └── 15.14.9 ⇡ 2 years ago
```

afaict, there's no plan to ship `@types/node` as a dep in oclif.
