### ISSUE TITLE
Creating AuthProvider + NamedCredential breaks pull

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#241]
### Summary

After creating an Auth provider and NamedCredential in my scratch org to test an integration, force:source:pull seems to be completely broken with no work around. Every pull throws the following error:

Entity of type 'AuthProvider' named 'My Credential' cannot be found

This happens even if I add the following to my .forceignore file

**.namedCredential
**.authProvider

### Steps To Reproduce:

1. create a scratch org and sync some source to it  
Create an auth provider to connect to another service via OAuth (such as another salesforce org)
1.  Create a Named credential that uses the auth provider
1. add **.namedCredential
**.authProvider
to your .forceignore
1. run sfdx force:source:pull

### Expected result

pull to complete as expected without namedcredentials or AuthProvider

### Actual result

Receive error
Entity of type 'AuthProvider' named 'My Credential' cannot be found

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.33.2-045d48473e darwin-x64 node-v10.15.3
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
salesforcedx 47.6.2
├─ salesforcedx-templates 47.6.2
└─ salesforce-alm 47.9.0
**OS and version**:
macOS 10.15

**Comment by shetzel** [comment]
@yippie - I can't reproduce the behavior you're seeing.  I'm able to push/pull auth providers and named credentials without an issue.  If you are not acting as the sys admin, could this be a permissions issue?

The pattern you added to the .forceignore file would not match auth providers and named credentials, so that is why it's not excluding them from push/pull.  For that you should do something like this:
**/namedCredentials/**
**/authproviders/**

**Comment by aidan-harding** [comment]
I ran into the same error message, and the thing I found out via StackExchange (https://salesforce.stackexchange.com/questions/265481/sfdx-forcesourcepull-entity-of-type-authprovider-named-cannot-be-found) is that having spaces in the Name of an Auth Provider causes DX to error when pulling source.

It is immediately fixed if you remove the spaces. You can reproduce by making an auth provider called "My Auth" with URL suffix "My_Auth" via the UI. This is all fine, but a sfdx pull fails.

Change the name to "My_Auth", and it works.

This seems like a minor bug.
