### ISSUE TITLE
Test results percentage colors are misleading.

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/cli#2412]
### Summary

Test results colors shown in CLI are misleading as only 100% is green.

### Steps To Reproduce

Run tests for classes with different coverage.

### Expected result
Colors are assigned gradually. 
75% and less is red as it does not meet the required coverage
76%-90% is orange as this coverage is acceptable but could be improved
91%-100% is green as it is hard to get full 100% coverage in most cases.

### Actual result

Command: sfdx project deploy start --ignore-conflicts --verbose --test-level RunLocalTests --source-dir . --target-org sandbox88
Currently, everything below 100% is red.
<img width="255" alt="image" src="https://github.com/forcedotcom/cli/assets/5740564/046e507d-4f28-411c-9216-dda95577ef3d">

### System Information

PowerShell 7.3.6

```json
sf version --verbose --json
{
  "cliVersion": "@salesforce/cli/2.4.10",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\u1\\AppData\\Local\\sf\\client\\2.4.10-703551c",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.21 (core)",
    "@oclif/plugin-help 5.2.16 (core)",
    "@oclif/plugin-not-found 2.3.36 (core)",
    "@oclif/plugin-plugins 3.2.0 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.30 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.46 (core)",
    "@oclif/plugin-which 2.2.29 (core)",
    "@salesforce/cli 2.4.10 (core)",
    "apex 2.3.10 (core)",
    "auth 2.8.12 (core)",
    "data 2.5.5 (core)",
    "deploy-retrieve 1.17.2 (core)",
    "info 2.6.38 (core)",
    "limits 2.3.29 (core)",
    "login 1.2.25 (core)",
    "org 2.9.30 (core)",
    "schema 2.3.22 (core)",
    "settings 1.4.24 (core)",
    "sobject 0.2.2 (core)",
    "source 2.10.30 (core)",
    "telemetry 2.2.5 (core)",
    "templates 55.5.9 (core)",
    "trust 2.5.4 (core)",
    "user 2.3.28 (core)"
  ]
}
```

**Comment by AllanOricil** [comment]
fixed and added yellow color range 
https://github.com/salesforcecli/plugin-source/pull/934

when code coverage percentage <= 75  -> red
when code coverage percentage >= 90  -> green
else                                                              -> yellow

**Comment by PawelWozniak** [comment]
@AllanOricil Thank you for such a quick fix.
I just have second thoughts. After reading this article https://help.salesforce.com/s/articleView?id=000385650&type=1 my understanding is that 75% is an acceptable value so it should be then in the yellow range.
Then <= 74 should be red.

**Comment by AllanOricil** [comment]
@PawelWozniak fixed

**Comment by AllanOricil** [comment]
by the way, I'ill keep doing this until Salesforce cant ignore me anymore and send me an offer so that I can refuse and post on linkedin

**Comment by AllanOricil** [comment]
:/

**Comment by AllanOricil** [comment]
🧓

**Comment by AllanOricil** [comment]
👴🏻

**Comment by mshanemc** [comment]
@AllanOricil Thanks for the PR, but we're not doing enhancements to deprecated commands in `plugin-source`.

This issue references `project deploy start` from https://github.com/salesforcecli/plugin-deploy-retrieve.  You might want to look in https://github.com/salesforcecli/plugin-deploy-retrieve/blob/26769ca9d2c8fe13dbec98df496220813598f6e7/src/utils/coverage.ts#L97

**Comment by AllanOricil** [comment]
Sorry for that 😅
