### ISSUE TITLE
Unable to create scratch orgs with multiple sf and sfdx versions. Receiving error: The request to create a scratch org failed with error code: C-1033

### ISSUE THREAD

**Issue by jdschleicher** [forcedotcom/cli#2413]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary

Within our GH Actions and experienced locally by several team members, we are unable to create scratch orgs and receive a failure of : ```The request to create a scratch org failed with error code: C-1033```

We are also using 2 concurrent jobs to test creating a scratch org with the "sf" and "sfdx"  scratch org creation commands

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

We have setup a public github repository to troubleshoot.

The last failed job is here: https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893082972

The CLI version can be changed here: https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/settings/variables/actions

We have also discovered if we use a developer edition devhub we do not experience the issues

### Expected result

create scratch org

### Actual result

```json
{   "code": 1,   "context": "EnvCreateScratch",   "commandName": "EnvCreateScratch",   "data": {     "username": "jonathon.schleicher@b3groupinc.comvapm",     "orgId": "00Dt0000000LAyREAW",     "scratchOrgInfoId": "2SROE00000002de4AA"   },   "message": "The request to create a scratch org failed with error code: C-1033.",   "name": "SfError",   "status": 1,   "stack": "SfError: The request to create a scratch org failed with error code: C-1033.\n    at checkScratchOrgInfoForErrors (/opt/hostedtoolcache/node/18.14.2/x64/lib/node_modules/@salesforce/cli/node_modules/@salesforce/core/lib/org/scratchOrgErrorCodes.js:66:15)\n    at async pollForScratchOrgInfo (/opt/hostedtoolcache/node/18.14.2/x64/lib/node_modules/@salesforce/cli/node_modules/@salesforce/core/lib/org/scratchOrgInfoApi.js:303:16)\n    at async scratchOrgCreate (/opt/hostedtoolcache/node/18.14.2/x64/lib/node_modules/@salesforce/cli/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:160:17)\n    at async EnvCreateScratch.run (/opt/hostedtoolcache/node/18.14.2/x64/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-org/lib/commands/org/create/scratch.js:39:72)\n    at async EnvCreateScratch._run (/opt/hostedtoolcache/node/18.14.2/x64/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:117:22)\n    at async Config.runCommand (/opt/hostedtoolcache/node/18.14.2/x64/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:329:25)\n    at async run (/opt/hostedtoolcache/node/18.14.2/x64/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:89:16)",   "exitCode": 1,   "warnings": [] }

```
### System Information

```json
{
  "cliVersion": "@salesforce/cli/2.4.10",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.17.0",
  "osVersion": "Linux 5.15.0-1042-azure",
  "shell": "bash",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.21 (core)",
    "@oclif/plugin-help 5.2.[16](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:17) (core)",
    "@oclif/plugin-not-found 2.3.36 (core)",
    "@oclif/plugin-plugins 3.2.0 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.30 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.46 (core)",
    "@oclif/plugin-which 2.2.29 (core)",
    "@salesforce/cli 2.4.10 (core)",
    "apex 2.3.10 (core)",
    "auth 2.8.12 (core)",
    "data 2.5.5 (core)",
    "deploy-retrieve 1.[17](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:18).2 (core)",
    "info 2.6.38 (core)",
    "limits 2.3.29 (core)",
    "login 1.2.25 (core)",
    "org 2.9.30 (core)",
    "schema 2.3.[22](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:23) (core)",
    "settings 1.4.[24](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:25) (core)",
    "sobject 0.2.2 (core)",
    "source 2.10.30 (core)",
    "telemetry 2.2.5 (core)",
    "templates 55.5.9 (core)",
    "trust 2.5.4 (core)",
    "user 2.3.[28](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:29) (core)"
  ]
}
```

**Comment by jdschleicher** [comment]
still seeing issue with latest ( that's what we started with as well)

**Comment by ImJohnMDaniel** [comment]
I have a dev team that is reporting similar issues.  Still trying to get details now.

**Comment by jprichter** [comment]
Same issue here.

**Comment by jdschleicher** [comment]
rerunning test workflows now : https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460

**Comment by jdschleicher** [comment]
we have also submitted a help desk case with salesforce

**Comment by cristiand391** [comment]
Hey, sorry for the late reply.

@jdschleicher @jprichter @ImJohnMDaniel what's the instance of your hub?

@jdschleicher that json response includes a record, do you see more info in your hub?
`sf data get record --where Id=<record-id> --target-org <hub-username> --sobject ScratchOrgInfo`

**Comment by jdschleicher** [comment]
hey hey @cristiand391  thank you. See below for scratchorginfo :

```json

{
  "status": 0,
  "result": {
    "attributes": {
      "type": "ScratchOrgInfo",
      "url": "/services/data/v58.0/sobjects/ScratchOrgInfo/2SROE00000002de4AA"
    },
    "Id": "2SROE00000002de4AA",
    "OwnerId": "005t0000001kkZ1AAI",
    "IsDeleted": false,
    "Name": "00019195",
    "CreatedDate": "2023-08-17T15:48:26.000+0000",
    "CreatedById": "005t0000001kkZ1AAI",
    "LastModifiedDate": "2023-08-17T15:49:41.000+0000",
    "LastModifiedById": "005t00000015dbUAAQ",
    "SystemModstamp": "2023-08-17T15:49:41.000+0000",
    "LastViewedDate": "2023-08-17T15:49:41.000+0000",
    "LastReferencedDate": "2023-08-17T15:49:41.000+0000",
    "Edition": "Developer",
    "Username": null,
    "AdminEmail": null,
    "OrgName": "Dreamhouse",
    "DurationDays": 1,
    "ConnectedAppConsumerKey": "PlatformCLI",
    "ConnectedAppCallbackUrl": "http://localhost:1717/OauthRedirect",
    "Namespace": null,
    "Features": "Walkthroughs;EnableSetPasswordInApi",
    "Country": null,
    "Language": null,
    "Instance": null,
    "Package2AncestorIds": null,
    "SourceOrg": null,
    "HasSampleData": false,
    "Release": "Current",
    "SignupUsername": "test-9zhyrb5bfc4g@example.com",
    "Status": "Error",
    "ErrorCode": "C-1033",
    "ScratchOrg": null,
    "SignupInstance": null,
    "AuthCode": null,
    "SignupCountry": "US",
    "SignupLanguage": "en_US",
    "SignupEmail": "jonathon.schleicher@b3groupinc.com",
    "SignupTrialDays": 1,
    "LoginUrl": null,
    "Description": null,
    "ExpirationDate": "2023-08-18",
    "LastLoginDate": null,
    "DeletedBy": null,
    "DeletedDate": null
  },
  "warnings": []
}


```

**Comment by cristiand391** [comment]
and hub instance? 
`sf data query -q 'select InstanceName from Organization' -o <hub-username>`

I don't see any current incident but we can ask signup folks.

**Comment by jdschleicher** [comment]
thank you @cristiand391 

```json

{
  "status": 0,
  "result": {
    "records": [
      {
        "attributes": {
          "type": "Organization",
          "url": "/services/data/v58.0/sobjects/Organization/00Dt0000000LAyREAW"
        },
        "InstanceName": "NA291"
      }
    ],
    "totalSize": 1,
    "done": true
  },
  "warnings": []
}
```

**Comment by jprichter** [comment]
@cristiand391, our DevHubs are on NA107 and NA217.

**Comment by cristiand391** [comment]
@jdschleicher @jprichter @ImJohnMDaniel sorry for the late reply, they said they don't see any error for those instancse but  they got the Summer '23 patch 17.1 around August 16 which seems related.

I'll try to get more details on Monday, but opening a case might help getting more attention.

**Comment by jdschleicher** [comment]
thank you @cristiand391  still receiving same error as of 1:45 PM EST 8/19

**Comment by ImJohnMDaniel** [comment]
@jdschleicher - your DevHub is [NA291](https://status.salesforce.com/instances/NA291/details).   That is currently running "Summer '23 Patch 17.1".  All of the DevHubs that I am having problems with are on instances where they are running "Summer '23 Patch 17.1".  Where I don't have problems are DevHubs running "Summer '23 Patch 17.2" or higher.  There is a scheduled database maintenance window later this evening on these instances that are running into issues.  My plan is to check tomorrow, after the maintenance window, and see if the instance has been upgraded to patch 17.2, and then try this again.

**Comment by jdschleicher** [comment]
many thanks @ImJohnMDaniel that sounds like a plan

**Comment by jprichter** [comment]
The maintenance window came and went. The affected orgs were not updated to "Summer '23 Patch 17.2" or higher. The problem persists when attempting to create scratch orgs from devhubs on those instances. 

My personal devhub is on NA129 which is on Summer '23 Patch 17.2 and I can create scratch orgs from there without issue.

**Comment by ImJohnMDaniel** [comment]
@cristiand391 -- I am seeing the same things that @jprichter is seeing.  Are you able to find out when instances like NA107, NA215, and NA291 will be getting upgraded to Summer '23 Patch 17.2 or higher?  It certainly was not last night 😉

**Comment by ptc-tsweet** [comment]
Anyone have any feedback from Salesforce on this issue?

**Comment by jdschleicher** [comment]
negative @ptc-tsweet , we have a case in, completely blocked. been open for a 5 days

**Comment by cristiand391** [comment]
Asked again, no public KI or update on status page but there's an ongoing investigation about this.

**Comment by jprichter** [comment]
We also have a case open with Salesforce. The response to this issue from Salesforce has been embarrassing. Incredible that such basic tooling is left completely broken for such a large and important population of their customers for so many days.

**Comment by etroiani** [comment]
Hi, we are working on fixing this issue, can someone please try to see if it's still reproducible?

**Comment by ImJohnMDaniel** [comment]
@etroiani  -- I just tried on NA107 and got the same error

**Comment by ImJohnMDaniel** [comment]
@etroiani -- I just tried on NA215 as well and it failed

**Comment by etroiani** [comment]
Can you please provide more detailed info such as Scratch Org Ids Request ( those Ids are starting with 2SR ) for each Instance? Thank you! ( we will need to use those for our search in logs )

**Comment by ImJohnMDaniel** [comment]
@etroiani -- getting data ready now.  I am sending it directly to Milly Millbanks now via email

**Comment by etroiani** [comment]
Can anyone please do a test now on Na107 and Na215? Thank you,

**Comment by ImJohnMDaniel** [comment]
@etroiani -- Just tested.  NA107 and NA215 are both working.

**Comment by etroiani** [comment]
ok, can we also get customers on the other pods testing and then confirming the output of their tests? Thanks again!

**Comment by jdschleicher** [comment]
@etroiani @cristiand391 

working here as well. What learnings can we share with our Customers to provide confidence going forward?
