### ISSUE TITLE
can't request feature requests via issue forms 8/17/23

### ISSUE THREAD

**Issue by jdschleicher** [forcedotcom/cli#2414]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary

receive error in selecting feature request:

![image](https://github.com/forcedotcom/cli/assets/3968818/a8b7ed93-035d-46af-be20-bc3b5cdfe88b)

![image](https://github.com/forcedotcom/cli/assets/3968818/aa6e6d15-76eb-4281-a27f-f4a8bc93f000)

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### System Information

```json
{
  "cliVersion": "@salesforce/cli/2.4.10",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.17.0",
  "osVersion": "Linux 5.15.0-1042-azure",
  "shell": "bash",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.21 (core)",
    "@oclif/plugin-help 5.2.[16](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:17) (core)",
    "@oclif/plugin-not-found 2.3.36 (core)",
    "@oclif/plugin-plugins 3.2.0 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.30 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.46 (core)",
    "@oclif/plugin-which 2.2.29 (core)",
    "@salesforce/cli 2.4.10 (core)",
    "apex 2.3.10 (core)",
    "auth 2.8.12 (core)",
    "data 2.5.5 (core)",
    "deploy-retrieve 1.[17](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:18).2 (core)",
    "info 2.6.38 (core)",
    "limits 2.3.29 (core)",
    "login 1.2.25 (core)",
    "org 2.9.30 (core)",
    "schema 2.3.[22](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:23) (core)",
    "settings 1.4.[24](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:25) (core)",
    "sobject 0.2.2 (core)",
    "source 2.10.30 (core)",
    "telemetry 2.2.5 (core)",
    "templates 55.5.9 (core)",
    "trust 2.5.4 (core)",
    "user 2.3.[28](https://github.com/jdschleicher/sf-sfdx-cli-version-troubleshooting/actions/runs/5893258460/job/15987028213#step:3:29) (core)"
  ]
```

**Comment by jdschleicher** [comment]
We have introduced a self-service form that increments the package version. It's used a majority of the time and sometimes it is not.

because we are reliant on gitflow, we don't release a package version until a pre-step before production install

is there any way to have a validation on the package version that says "Hey you silly goose, there's already a released version of this package?....."

**Comment by mshanemc** [comment]
Finally got github permissions figured out for Discussions.  Hit us with all your fantastic ideas.
