### ISSUE TITLE
mdapi:deploy failing when deploying contentAssets folder

### ISSUE THREAD

**Issue by vmarasow** [forcedotcom/cli#242]
### Summary

_Deployment is failing when deploying the entire contentassets folder_.

### Steps To Reproduce:

1. `sfdx force:mdapi:deploy -u vc -d force-app/main/default/contentassets`

### Expected result

_The content assets should have gotten deployed_.

### Actual result

_Deployment failed with the error No package.xml found_.

### Additional information

_
![image](https://user-images.githubusercontent.com/2812195/69747296-1d7d7200-1114-11ea-8b61-d4be4b03e7af.png)
_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.33.2-045d48473e darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
salesforcedx 47.6.2 (core)
├─ salesforcedx-templates 47.6.2 (core)
└─ salesforce-alm 47.9.0 (core)
**OS and version**:
macOS Catalina 10.15.1

**Comment by clairebianchi** [comment]
@vmarasow you need to include a package.xml file in the deploy directory. If you are using source formate you can use source:deploy which does not need a package
