### ISSUE TITLE
Authorization and deployment failure using sf auth device login -r https://test.salesforce.com -a testAlias

### ISSUE THREAD

**Issue by ashishrajbanshi** [forcedotcom/cli#2425]
### Summary
sf command not working properly for authorization and deployment.

## sys information
{
  "cliVersion": "@salesforce/cli/2.5.7",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.16.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\user21\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.22 (core)",
    "@oclif/plugin-help 5.2.17 (core)",
    "@oclif/plugin-not-found 2.3.37 (core)",
    "@oclif/plugin-plugins 3.2.6 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.32 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.48 (core)",
    "@oclif/plugin-which 2.2.30 (core)",
    "@salesforce/cli 2.5.7 (core)",
    "apex 2.3.10 (core)",
    "auth 2.8.12 (core)",
    "data 2.5.6 (core)",
    "deploy-retrieve 1.17.5 (core)",
    "env 2.1.20 (user)",
    "functions 1.21.10 (user)",
    "info 2.6.39 (core)",
    "limits 2.3.30 (core)",
    "login 1.2.26 (core)",
    "org 2.10.0 (core)",
    "packaging 1.20.1 (user)",
    "schema 2.3.23 (core)",
    "settings 1.4.25 (core)",
    "sobject 0.2.4 (core)",
    "source 2.10.31 (core)",
    "telemetry 2.3.0 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.1 (core)",
    "user 2.3.28 (core)"
  ]
}

### Steps To Reproduce
sf auth device login -r https://test.salesforce.com -a testAlias

### Expected result
Login code and url in terminal

### Actual result
Error (1): request to https://test.salesforce.com//services/oauth2/token failed, reason: connect ETIMEDOUT 101.53.161.131:443

Getting error while retreiving/deploying in vscode
![image](https://github.com/forcedotcom/cli/assets/46884226/200c15e3-d56e-4e68-b1ab-82f847a46445)

### System Information
@salesforce/cli/2.3.8 win32-x64 node-v18.16.0

**Comment by shetzel** [comment]
I cannot reproduce this.  Do you have any additional steps to reproduce?

**Comment by mshanemc** [comment]
We recommend using `-r` with the mydomain (instanceUrl) instead of the generic `https://test.salesforce.com` because there can be replication delays between the real domain and the login servers at test.salesforce.com.

Other than that, there's not much to be done from the CLI side.  My guess is that this was intermittent or one org with a problem and not happening consistently everywhere.
