### ISSUE TITLE
Add check-only flag option to force:source:delete

### ISSUE THREAD

**Issue by klouf-threshold** [forcedotcom/cli#243]
Currently in our CI process we have commits to our "feature" (non-master) branches fire off `force:source:deploy` with the `-c` ("check only") flag to perform a validation-only deployment of any new/modified metadata. We are looking to add metadata deletion to the process and would like to use `force:source:delete` since it would allow us to easily provide a list of metadata files much like `force:source:deploy` does, without having to create a `destructiveChanges.xml` file. However, there's no flag on this command to only validate the deletion without actually doing the delete like we can with `force:source:deploy`.  It seems that currently the only way to do what we want is with `force:mdapi:deploy` and the aforementioned XML file.

**Comment by shetzel** [comment]
I've wanted the same thing on a project I just rolled off of.  We'll track this internally and release it in an upcoming patch.  Thanks!  We'll let you know when it's in the core plugin.

**Comment by klouf-threshold** [comment]
This was added in v47.14.0, so I am going to close this. Thanks!
