### ISSUE TITLE
Error "sfdc.messaging.MessagingException: java.lang.IllegalStateException" when deploying Permission Set Group (Winter '24)

### ISSUE THREAD

**Issue by corentindoctolib** [forcedotcom/cli#2430]
### Summary
We're facing an error when deploying Permission Set Groups on Scratch Orgs (Winter'24 only) : "sfdc.messaging.MessagingException: java.lang.IllegalStateException: Value 0PS9Q000000t0U5,0PS9Q000000t0U7,[...]" exceeds maximum length (255)

### Steps To Reproduce
Private repo but : 
- deployment of a Permission Set Groups including 50 Permission Sets for example 

### Expected result
The Permission Set Group is deployed

### Actual result
The Permission Set Group isn't inserted, we get an error message.

### System Information
Terminal : cmd.exe
Full Output : 
```
{
  "cliVersion": "@salesforce/cli/2.6.6",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.17.1",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\corentin.romilly\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.23 (core)",
    "@oclif/plugin-help 5.2.17 (core)",
    "@oclif/plugin-not-found 2.3.37 (core)",
    "@oclif/plugin-plugins 3.2.7 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.32 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.48 (core)",
    "@oclif/plugin-which 2.2.31 (core)",
    "@salesforce/cli 2.6.6 (core)",
    "apex 2.3.11 (core)",
    "auth 2.8.13 (core)",
    "data 2.5.7 (core)",
    "deploy-retrieve 1.17.5 (core)",
    "dev 0.7.0 (user)",
    "info 2.6.39 (core)",
    "limits 2.3.31 (core)",
    "login 1.2.28 (core)",
    "org 2.10.3 (core)",
    "packaging 1.16.2 (user)",
    "schema 2.3.23 (core)",
    "settings 1.4.26 (core)",
    "signups 1.4.10 (user)",
    "sobject 0.2.6 (core)",
    "source 2.10.32 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.3 (core)",
    "user 2.3.29 (core)"
  ]
}
```

### Additional information
![image](https://github.com/forcedotcom/cli/assets/88317880/5f75ef22-00f3-4607-af91-553f460ee81b)

**Comment by ebertineau** [comment]
Same issue here.

**Comment by ammads** [comment]
+1

**Comment by jcallaha** [comment]
I don't know if this is helpful but if the permission set group has only a few permissions it does work.  The magic number appears to be 16 or fewer - maybe because 16 x 15 (length of id) + 15 commas as separators is just under 255

**Comment by scaldra** [comment]
Same issue here

**Comment by jcallaha** [comment]
FYI this seems to be resolved after doing an "sf update".  My previous version was 2.5.8 and now 2.6.7 is working for me, don't know which version resolved it.

**Comment by ammads** [comment]
> FYI this seems to be resolved after doing an "sf update". My previous version was 2.5.8 and now 2.6.7 is working for me, don't know which version resolved it.

I just tried it with a sandbox that has the Winter ‘24 release but I’m still getting the error.

I got this response from Salesforce:

```
We have done some investigation from our end. Please find the case updates below:

1. Created a new Winter24 preview release org.
2. Created a new permission set group.
3. Tried to add the all the permission sets (23) to the permission set group from the UI and I got the same error.
4. It is due to when we are assigning the permission set then it is trying to count the 18digit id of the each permission set as 18 characters and when the total count is exceeding 255 then we are facing the errors.

As a workaround, you can try adding 13 permission sets in one batch and try other remaining permission sets in another batch which will resolve this error.

Meanwhile, I will contact our TMP team to get the details about this issue.
```

**Comment by SoftCreatR** [comment]
I've opened a case regarding this matter (Case ID: 45245575). The same issue is being discussed on [Reddit](https://www.reddit.com/r/salesforce/comments/163oe53).

This isn't related to `sf` or `sfdx`. Moreover, there's no mention of such changes in any official documentation, including changelogs. This leads us to believe it's a bug inherent to the Winter '24 release, but unrelated to salesforce-cli.

**Comment by shetzel** [comment]
Thanks for reporting.  This is a server side error and must be fixed there.  A short-term workaround would be to make multiple deploys of those permission set groups.  I'll close this issue as the problem is server side.

**Comment by SoftCreatR** [comment]
Just a quick heads up:

> I would like to provide you with the latest updates regarding the issue you reported concerning the Winter '24 release. Our (TMP) team has conducted a thorough investigation and has confirmed that the issue indeed stems from a bug within the Winter '24 release.
> 
> The good news is that they have already taken the necessary steps to address this bug. A fix has been developed, and it is slated for release in an upcoming patch release. You can expect this patch to be rolled out by 7th September 2023, 23:00 EMEA Hours (Safe Harbour)
>
> The TMP team has recommended a workaround for this issue, which involves managing fewer than 16 permission sets when adding or removing them from a permission set group, which will help to solve this issue in the meantime the when bug fix is released.

**Comment by jcallaha** [comment]
The patch appears to have fixed the issue for my orgs as of 7 September 2023.
