### ISSUE TITLE
When switching to GitHub Actions with windows-latest, installing sf cli with npm takes 5-10 minutes

### ISSUE THREAD

**Issue by jdschleicher** [forcedotcom/cli#2436]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary

Had to recently switch to windows-latest to workaround "Admin not found in package.xml" error.

Now the sfdx-cli install command takes 5-10 minutes ever time compared to 45s with ubuntu-latest

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

Change runs-on to windows-latest

install sfdx cli:
```npm install --global @salesforce/cli@latest```

### Expected result

Does not take 5-10 minutes

### Actual result

Takes 5-10 minutes to install

### System Information

```json
{
  "cliVersion": "@salesforce/cli/2.5.8",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.17.1",
  "osVersion": "Windows_NT 10.0.20348",
  "shell": "cmd.exe",
  "rootPath": "C:\\npm\\prefix\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.22 (core)",
    "@oclif/plugin-help 5.2.17 (core)",
    "@oclif/plugin-not-found 2.3.37 (core)",
    "@oclif/plugin-plugins 3.2.6 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.32 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.48 (core)",
    "@oclif/plugin-which 2.2.30 (core)",
    "@salesforce/cli 2.5.8 (core)",
    "apex 2.3.10 (core)",
    "auth 2.8.12 (core)",
    "data 2.5.6 (core)",
    "deploy-retrieve 1.17.5 (core)",
    "info 2.6.39 (core)",
    "limits 2.3.30 (core)",
    "login 1.2.26 (core)",
    "org 2.10.0 (core)",
    "schema 2.3.23 (core)",
    "settings 1.4.25 (core)",
    "sobject 0.2.4 (core)",
    "source 2.10.31 (core)",
    "telemetry 2.3.0 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.1 (core)",
    "user 2.3.28 (core)"
  ]
}
```

### Additional information

![image](https://github.com/forcedotcom/cli/assets/3968818/30d78f36-a3a9-454a-a752-21ba8a66136f)

**Comment by AllanOricil** [comment]
@jdschleicher 

Instead of installing build dependencies while the pipeline is running, use a docker image that has sfdx and node in it already. Pulling an image takes seconds. Salesforce has images available in docker hub.

Make the container attribute a repo variable so that you can easily swap images when new versions are released. This will help u to avoid adding dummy commits to ur repository.  Be careful to not use :latest tags when selecting the image version. Always specify the hash of the image.

If u need further help dm me on LinkedIn. I'm a github actions specialist hahahaha

**Comment by mshanemc** [comment]
We use windows-latest on our CI, and see similar numbers (4 min is more common, but there are days!)

<img width="1215" alt="Screenshot 2023-08-31 at 1 21 22 PM" src="https://github.com/forcedotcom/cli/assets/4261788/430678f8-5342-450d-a06a-3069ee2a8634">

we've got some open work for continuing to shrink the CLI's dependency tree (jsforce in particular!) which will help marginall.

Other than that, we've no control of github's runners or especially the atrocious perf of FS on windows (installing a bunch of small files like node does) so I'm closing this one.

**Comment by AllanOricil** [comment]
![image](https://github.com/forcedotcom/cli/assets/55927613/f6d5e49e-fc0a-456d-8ec4-dadcb18cd837)

**Comment by jdschleicher** [comment]
@AllanOricil  i will definitely be reaching out soon :) and THANK YOU!!!!

I got really frustrated last night as some of the feedback I was hoping to get for some new functionality was dependent upon sfdx cli install so I dove in on trying to figure out how to leverage a windows salesforce cli tar install approach. Haven't done a full end-2-end test yet to confirm if old cli commands are still working as expected but I have been able to confirm the install takes under 2 minutes consistently. ( docker still very much seems like something we want to do ). I was also able to create a fully validated package version. 

```


### INSTALL SALESFORCE CLI
Install-Module -Name 7Zip4Powershell -RequiredVersion 2.0.0 -Force

$sf_cli_tar_xz_path = "sf-cli.tar.xz"
$sf_cli_tar_path = "sf-cli"
$sf_cli_tar_file = "sf-cli.tar"

Write-Host " Download Salesforce CLI tar file"
Invoke-WebRequest -Uri "https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64.tar.xz" -OutFile "$sf_cli_tar_xz_path"

Write-Host " Extract the downloaded tar file"
Expand-7Zip -TargetPath $sf_cli_tar_path -ArchiveFileName "$sf_cli_tar_xz_path"

tar -xvf "$sf_cli_tar_path/$sf_cli_tar_file" -C sf-cli

### BELOW CAN BE IN NEW STEP 

if (!(Test-Path -Path $PROFILE)) {
    New-Item -ItemType File -Path $PROFILE -Force
}

# Add "sf" command alias to all powershell instances with the GitHub Actions job
$sf_alias = @"
`n Set-Alias -Name sf -Value '.\sf-cli\sf\bin\sf'
"@
Add-Content -Path $PROFILE -Value $sf_alias

# Add "sfdx" alias for CI jobs that have not been updated yet
$sfdx_alias = @"
`n Set-Alias -Name sfdx -Value '.\sf-cli\sf\bin\sf'
"@
Add-Content -Path $PROFILE -Value $sfdx_alias

# INITIATE PROFILE FOR ALIASES TO REGISTER
. $PROFILE


```

![image](https://github.com/forcedotcom/cli/assets/3968818/3b938d66-7d22-4a2b-8868-b52c780354da)

@mshanemc  if using tar install may be frowned upon for windows please let me know :)

**Comment by mshanemc** [comment]
AFAIK docker on github actions doesn't support windows.  We definitely don't have a docker image for the CLI built on windows.

**Comment by AllanOricil** [comment]
Is there a reason why you are using windows?

**Comment by jdschleicher** [comment]
@AllanOricil we have a strange error we are hitting in ubuntu. I thought we were dead-in-the-water and just so happened to try windows and ended up not receiving the error. I have no idea what about what in the windows systems it works lol. We have an actual Salesforce case open with our account as well. So far still in research.

The error was the same for about all things related with package version creation/installation.

(not sure if i should add the issue here if it messes with the issue management)
its documented here: https://github.com/forcedotcom/cli/issues/2427
