### ISSUE TITLE
'package version create' fails silently when compressing multiple folders under staticresources

### ISSUE THREAD

**Issue by gbutt-tr** [forcedotcom/cli#2442]
### Summary
We are attempting to build a 2GP package for our app and running into this issue.
When we run the `package version create` command, it fails silently. We do not get any extra info from --verbose or even --json. Just nothing.

After some heavy troubleshooting, I was able to reproduce the issue. It occurs when I try to create a package version with multiple uncompressed static resource folders. I'm not sure why this happens, but it is easily reproducible using the provided repo. The error seems to happen somewhere in the MetadataConverter's conversionPipeline, which makes it difficult to troubleshoot further. `@salesforce/source-deploy-retrieve/lib/src/convert/metadataConverter.js`

### Steps To Reproduce
See https://github.com/gbutt-tr/package-version-create-error

### Expected result
A package version is created

### Actual result
CLI fails silently.

### System Information
```json
{
  "cliVersion": "@salesforce/cli/2.6.7",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.17.1",
  "osVersion": "Darwin 22.5.0",
  "shell": "zsh",
  "rootPath": "/opt/homebrew/Cellar/nvm/0.39.5/versions/node/v18.17.1/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.23 (core)",
    "@oclif/plugin-help 5.2.17 (core)",
    "@oclif/plugin-not-found 2.3.37 (core)",
    "@oclif/plugin-plugins 3.2.7 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.32 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.48 (core)",
    "@oclif/plugin-which 2.2.31 (core)",
    "@salesforce/cli 2.6.7 (core)",
    "apex 2.3.11 (core)",
    "auth 2.8.13 (core)",
    "community 2.2.9 (user)",
    "data 2.5.7 (core)",
    "deploy-retrieve 1.17.5 (core)",
    "info 2.6.39 (core)",
    "limits 2.3.31 (core)",
    "login 1.2.28 (core)",
    "org 2.10.3 (core)",
    "packaging 1.16.5 (user)",
    "schema 2.3.23 (core)",
    "settings 1.4.26 (core)",
    "sobject 0.2.6 (core)",
    "source 2.10.32 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.3 (core)",
    "user 2.3.29 (core)"
  ]
}
```

**Comment by AllanOricil** [comment]
@gbutt-tr why `packaging` is under user and not core?

<img width="226" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/a51cbf9f-c43f-48bc-b9fa-afdb1af87624">

Well, maybe it does not matter but just trying to understand it. I thought this package was part of the core plugins.

Try updating it to its [latest](https://www.npmjs.com/package/@salesforce/plugin-packaging) version and check if the issue persists

````bash
sf plugins:install @salesforce/plugin-packaging@1.23.2
````

If updating the plugin doesnt fix the issue run sfdx executable with a debugger attached to its process

````bash
node --inspect-brk $(which sfdx) package version create
````

then open sfdx modules, and add break points in this [class](https://github.com/salesforcecli/plugin-packaging/blob/main/src/commands/package/version/create.ts)

then attach a debugger to the process. You can do it with vscode

<img width="717" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/d401158c-d85d-478a-a214-41cbdebbf11c">

<img width="699" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/1e481c83-a65a-472f-b18c-bf4c44f71485">
 
<img width="1256" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/1a3e6dcf-5a55-4fac-858b-9996524448b6">

Eventually it will stop where you added your breakpoints.

**Comment by gbutt-tr** [comment]
@AllanOricil updating the packaging plugin resolved the issue. Thanks!

**Comment by AllanOricil** [comment]
course it does 😤
Now donate some money to charity

**Comment by shetzel** [comment]
Adding some clarity about user versus core plugin for plugin-packing.  In the sf v2 CLI (e.g., the one you listed above) the plugin-packaging plugin is a JIT, meaning it's installed "just in time" upon first packaging command execution.  When installed, it is a user plugin and not a core plugin.  In previous versions of sf and sfdx, plugin-packaging was a core plugin.  JIT plugins allow for a slimmer CLI.  They are generally medium to large sized plugins that have fewer total executions per analytics data.

Thanks Allan for answering!
