### ISSUE TITLE
"IntelligentDocumentReader", "EinsteinDocReader" Features Error

### ISSUE THREAD

**Issue by doug-kells** [forcedotcom/cli#2443]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
I've been trying to create a scratch org with the ability to enable either or both Intelligent Form Reader or Intelligent Document Reader. From the list of support features (https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file_config_values.htm), it appears that this should be available by adding "features": ["IntelligentDocumentReader", "EinsteinDocReader"] to the scratch org definition.

When I include this, VS Code identifies these features as problems "String does not match the pattern of "^(AddCustomApps:[0-9]+$)"." and scratch org creation fails "IntelligentDocumentReader is not a valid Features value".

Is there a way to have these available in a scratch org?

### Steps To Reproduce
I'm not including a repository as this happens in a completely empty salesforce project. 
project-scratch-def.json
{
  "orgName": "Demo company",
  "edition": "Developer",
  "features": ["IntelligentDocumentReader", "EinsteinDocReader"],
  "settings": {}
}
sf org create scratch --definition-file config/project-scratch-def.json --alias docs --set-default --duration-days 1 --json

### Expected result
Scratch org should be created.

### Actual result
{
  "code": 1,
  "context": "EnvCreateScratch",
  "commandName": "EnvCreateScratch",
  "message": "IntelligentDocumentReader is not a valid Features value.",
  "name": "INVALID_INPUT",
  "status": 1,
  "stack": "INVALID_INPUT: IntelligentDocumentReader is not a valid Features value.\n    at SfError.wrap (C:\\Users\\DougKells\\AppData\\Local\\sf\\client\\2.6.7-2553c44\\node_modules\\@salesforce\\core\\lib\\sfError.js:84:25)\n    at requestScratchOrgCreation (C:\\Users\\DougKells\\AppData\\Local\\sf\\client\\2.6.7-2553c44\\node_modules\\@salesforce\\core\\lib\\org\\scratchOrgInfoApi.js:252:33)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Promise.all (index 0)\n    at async scratchOrgCreate (C:\\Users\\DougKells\\AppData\\Local\\sf\\client\\2.6.7-2553c44\\node_modules\\@salesforce\\core\\lib\\org\\scratchOrgCreate.js:132:71)\n    at async EnvCreateScratch.run (C:\\Users\\DougKells\\AppData\\Local\\sf\\client\\2.6.7-2553c44\\node_modules\\@salesforce\\plugin-org\\lib\\commands\\org\\create\\scratch.js:39:72)\n    at async EnvCreateScratch._run (C:\\Users\\DougKells\\AppData\\Local\\sf\\client\\2.6.7-2553c44\\node_modules\\@oclif\\core\\lib\\command.js:117:22)\n    at async Config.runCommand (C:\\Users\\DougKells\\AppData\\Local\\sf\\client\\2.6.7-2553c44\\node_modules\\@oclif\\core\\lib\\config\\config.js:329:25)\n    at async run (C:\\Users\\DougKells\\AppData\\Local\\sf\\client\\2.6.7-2553c44\\node_modules\\@oclif\\core\\lib\\main.js:89:16)",
  "exitCode": 1,
  "warnings": []
}

### System Information

powershell PSVersion 5.1.19041.3031

{
  "cliVersion": "@salesforce/cli/2.6.7",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",       
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\DougKells\\AppData\\Local\\sf\\client\\2.6.7-2553c44",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.23 (core)",
    "@oclif/plugin-help 5.2.17 (core)",
    "@oclif/plugin-not-found 2.3.37 (core)",
    "@oclif/plugin-plugins 3.2.7 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.32 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.48 (core)",
    "@oclif/plugin-which 2.2.31 (core)",
    "@salesforce/cli 2.6.7 (core)",
    "apex 2.3.11 (core)",
    "auth 2.8.13 (core)",
    "data 2.5.7 (core)",
    "deploy-retrieve 1.17.5 (core)",
    "info 2.6.39 (core)",
    "limits 2.3.31 (core)",
    "login 1.2.28 (core)",
    "org 2.10.3 (core)",
    "schema 2.3.23 (core)",
    "settings 1.4.26 (core)",
    "sobject 0.2.6 (core)",
    "source 2.10.32 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.3 (core)",
    "user 2.3.29 (core)"
  ]
}
### Additional information
Is there any combination of features and/or settings that would allow a scratch org?

**Comment by shetzel** [comment]
Thanks for reporting, however this doesn't look like a problem with the CLI.  You mentioned the problems reported by VS Code and that is something that team can update.  The error, "IntelligentDocumentReader is not a valid Features value" is coming from the server so it's either a problem that support will have to assist with or perhaps something the org being created doesn't support due to (e.g.) API version or org edition.
