### ISSUE TITLE
Unable to poll deployment initiated by another sf client

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#2446]
### Summary

We are migrating our CI pipelines from sfdx to sf. We have two different build steps, one for generating the deployment and a second one for polling the deployment. We cannot assure that the agent that enqueued the deployment is the one polling it, some deployments can take more than one hour so we normally stop the agent and allow to continue polling later

Previous to the migration to sf we were doing this with a `sfdx force:source:deploy` and then a `sfdx force:source:deploy:report` without any problem

In the migration we changed the `sfdx force:source:deploy` to `sf project deploy start` and the `sfdx force:source:deploy:report` to `sf project deploy report` (we tried also with resume, no idea what is the difference)

But when we poll de deployment we are not allowed to specify the target org and we receive the following error

Error (1): No job found for ID: 0Af1q00001fTuLeCAK.

### Steps To Reproduce

- Start a deployment from a machine
- Try to resume from another machine

### Expected result

It should be possible to start deployments and report deployments even the client is different

### Actual result

You can only track a deployment if you started

### System Information

```json
{
  "cliVersion": "@salesforce/cli/2.6.7",
  "architecture": "linux-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Linux 5.15.0-1041-azure",
  "shell": "bash",
  "rootPath": "/opt/hostedtoolcache/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.23 (core)",
    "@oclif/plugin-help 5.2.17 (core)",
    "@oclif/plugin-not-found 2.3.37 (core)",
    "@oclif/plugin-plugins 3.2.7 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.32 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.48 (core)",
    "@oclif/plugin-which 2.2.31 (core)",
    "@salesforce/cli 2.6.7 (core)",
    "apex 2.3.11 (core)",
    "auth 2.8.13 (core)",
    "data 2.5.7 (core)",
    "deploy-retrieve 1.17.5 (core)",
    "info 2.6.39 (core)",
    "limits 2.3.31 (core)",
    "login 1.2.28 (core)",
    "org 2.10.3 (core)",
    "schema 2.3.23 (core)",
    "settings 1.4.26 (core)",
    "sobject 0.2.6 (core)",
    "source 2.10.32 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.3 (core)",
    "user 2.3.29 (core)"
  ]
}
```

### Additional information

`sfdx force source deploy report --jobid 0Afxxxxxxx --target-org xxxxx` is stil available but there is a warning telling that this functionality is not going to be available in the future

**Comment by mshanemc** [comment]
We have a discussion going about this use case here: https://github.com/forcedotcom/cli/discussions/2300.  

It's definitely going to get built
