### ISSUE TITLE
Salseforce CLI does not release the running process when finished executing

### ISSUE THREAD

**Issue by justin-lyon** [forcedotcom/cli#2450]
### Summary
For all sf and sfdx commands, the running process is not released immediately after completing execution. Instead sf keeps the process open for a few seconds delay after the output has already been reported to standard out. 

### Steps To Reproduce
1. Execute `sf version` or `sfdx version` in your terminal. 
2. Notice the version is instantly printed to standard out
3. Notice it takes ~10 seconds to release the process back to the terminal

https://github.com/forcedotcom/cli/assets/9729366/ebcf9ccd-b7e3-4463-bee6-73b0c1d4a5d8

### Expected result
After the command reports to standard out, it should release the process back to the user.

### Actual result
After the command reports to standard out, it hangs for ~10 seconds before releasing back to the user.

### System Information
zsh

```json
{
  "cliVersion": "@salesforce/cli/2.6.9",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.1.0",
  "osVersion": "Darwin 22.4.0",
  "shell": "zsh",
  "rootPath": "/Users/justin/.nvm/versions/node/v18.1.0/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.23 (core)",
    "@oclif/plugin-help 5.2.17 (core)",
    "@oclif/plugin-not-found 2.3.37 (core)",
    "@oclif/plugin-plugins 3.2.7 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.1.32 (core)",
    "@oclif/plugin-version 1.3.8 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.48 (core)",
    "@oclif/plugin-which 2.2.31 (core)",
    "@salesforce/cli 2.6.9 (core)",
    "apex 2.3.11 (core)",
    "auth 2.8.13 (core)",
    "data 2.5.7 (core)",
    "deploy-retrieve 1.17.5 (core)",
    "info 2.6.39 (core)",
    "limits 2.3.31 (core)",
    "login 1.2.28 (core)",
    "org 2.10.3 (core)",
    "packaging 1.16.5 (user)",
    "schema 2.3.23 (core)",
    "settings 1.4.26 (core)",
    "signups 1.4.33 (user)",
    "sobject 0.2.6 (core)",
    "source 2.10.32 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.3 (core)",
    "user 2.3.29 (core)"
  ]
}

```

**Comment by mshanemc** [comment]
hey @justin-lyon someone from our team did see this--it was fixed by updating the node version (18.17.1 is current, I think that very early 18.1.0 is the problem).

Can you try and let us know?

**Comment by AllanOricil** [comment]
It would be good if ocliff could verify the supported node version before running any command. Useful for people, like me, who have multiple node version in their machines.

**Comment by justin-lyon** [comment]
Thanks @mshanemc. That seems to be it. After updating my node version, I don't experience these delays any longer.
