### ISSUE TITLE
Bad CPU type in executable - v58.14.1

### ISSUE THREAD

**Issue by JeffStevensAASF** [forcedotcom/cli#2451]
### Summary
Just started this week (been vs code and extension for years now).  I can't authorize to an Org.  It started with not finding a folder.  But I have uninstalled the extensions, then VSCode, restarted machine, updated the Java to 17, restarted (several times) . So now - I'm getting this error:

6:18:12.321 sfdx force:auth:web:login --setalias vscodeOrg --instanceurl https://test.salesforce.com --setdefaultusername
/usr/local/bin/sfdx: line 44: /usr/local/lib/sf/bin/node: Bad CPU type in executable
16:18:12.358 sfdx force:auth:web:login --setalias vscodeOrg --instanceurl https://test.salesforce.com --setdefaultusername
 ended with exit code 1

when I try the SFDX: Authorize an Org command

I'm on a MACOS, macbook pro-2019, Intel, Ventura 13.5.1

I've started a Salesforce ticket on it, but not sure if I'll actually get any support from there.

Can anyone give me additional guidance or options?

Thanks!

**Comment by AllanOricil** [comment]
Relates https://github.com/oclif/oclif/issues/854

@RodEsp might be able to help you here

**Comment by AllanOricil** [comment]
My guess is that you are running arm build instead of the Intel one. Just don't know how it happened.

**Comment by petter-eikeland** [comment]
We got the same error when a Developer with Intel CPU Mac installed the Apple Silicon Version. @JeffStevensAASF Try uninstalling sfdx and installing the Intel CPU version instead.
![image](https://github.com/forcedotcom/cli/assets/97173615/52124aab-41d0-406e-8f31-e86a0a32b6b4)

**Comment by JeffStevensAASF** [comment]
@petter-eikeland - Yes - that did it!.  Thanks so much.

**Comment by JeffStevensAASF** [comment]
Downloading and installing the correct Salesforce CLI (Intel CPU) corrected the issue.

**Comment by AllanOricil** [comment]
u seem rich (halo effect). Don't forget to donate some money to charity
You're welcome

**Comment by vatsvaishali1** [comment]
> We got the same error when a Developer with Intel CPU Mac installed the Apple Silicon Version. @JeffStevensAASF Try uninstalling sfdx and installing the Intel CPU version instead. ![image](https://private-user-images.githubusercontent.com/97173615/266277940-52124aab-41d0-406e-8f31-e86a0a32b6b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NTc1ODgsIm5iZiI6MTcwOTc1NzI4OCwicGF0aCI6Ii85NzE3MzYxNS8yNjYyNzc5NDAtNTIxMjRhYWItNDFkMC00MDZlLThmMzEtZTg2YTBhMzJiNmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDIwMzQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0M2EyMjlhMzM0MDFkNDhiZDRjMDRhNTU1MGExYWRiODhkZTc5N2RhZjNhY2Q2ZDVlNDhmM2YzOTcwOTc1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YapLDqdp2KlC1owzsMMwIWPvVHJt21evtDyLLXHBMEc)

You saved me :-) Thank you!!
