### ISSUE TITLE
ERROR 403: Forbidden https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#2460]
@mshanemc @WillieRuemmele @shetzel @cristiand391 

could you tell us why this url is no longer working?
I'm working with a customer that is downloading sfdx from this place on every ci run. I'm going to change it, but first I would like to know why I'm seeing 403 - Forbidden

From my computer:
![image](https://github.com/forcedotcom/cli/assets/55927613/3073f64f-b200-4549-8a93-8886bc7de2ba)

From Github:
![image](https://github.com/forcedotcom/cli/assets/55927613/65ea3be9-0720-4355-866d-a1d6cd911d71)

**Comment by cristiand391** [comment]
Hi @AllanOricil 

yes, this was deleted on purpose. I remember we deleted this one last year and got a lot reports from customers still using it so we restored it and mentioned it will be deleted in the future.

For context: that tarball had a very old version of the CLI, back then customer mentioned they found that tarball via our docs (which are versioned, google was showing an old frozen version that we couldn't update).

#### Install the CLI with a TAR File:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux

**Comment by Shahul9891NL** [comment]
Hi @cristiand391 We are receiving below error on the SF cli installation

$ mkdir -p ~/cli/sf
$ tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
$ export PATH=~/cli/sf/bin:$PATH
$ sf autocomplete --refresh-cache
/root/cli/sf/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /root/cli/sf/bin/node)
/root/cli/sf/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /root/cli/sf/bin/node)
/root/cli/sf/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /root/cli/sf/bin/node)
/root/cli/sf/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /root/cli/sf/bin/node)
/root/cli/sf/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/cli/sf/bin/node)
/root/cli/sf/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/cli/sf/bin/node)

**Comment by cristiand391** [comment]
@Shahul9891NL yep, that's a node error and you might be on an old linux distro:
https://github.com/forcedotcom/cli/issues/1788

**Comment by Shahul9891NL** [comment]
@cristiand391 We are using our Gitlab runner for CICD Process. Is there any alternative approach ?

**Comment by cristiand391** [comment]
yeah, you can install the CLI via npm as mentioned in the linked issue.

**Comment by AllanOricil** [comment]
weird that almost nobody use docker images in their ci builds
