### ISSUE TITLE
Unable to run `data:record:update` via. Windows Bash Emulator when sfdx /sf is installed in a spaced directory path on windows. 

### ISSUE THREAD

**Issue by supert3d** [forcedotcom/cli#2461]
### Summary
Unable to run `data:record:update` via. Windows Bash Emulator when sfdx /sf is installed in a spaced directory path on windows. Example: `C:\Program Files` fails. `C:\mysfdxpath` works. 

### Steps To Reproduce

- Install VSCode
- Install MinTTY (Bash Emulator for Windows). 
- Install SFDX CLI to a (Windows) directory path that contains spaces. (Default install is `C:\Program Files`). 
- Run `data:record:update` command. (Interestingly `data:tree:import` works just fine). 

### Expected result
Command runs. 

### Actual result
```
'C:\program' is not recognized as an internal or external command,
operable program or batch file.
```

(Suspect pathing isn't correctly escaped?) 

### System Information
- Windows 11 (Version 22H2 (OS Builder 22621.2134) 
- mintty 3.6.3 (x86_64-pc-msys)
- VSCode 1.81.1

```json
$ sfdx version --verbose
 CLI Version:
        @salesforce/cli/2.7.11

 Architecture:
        win32-x64

 Node Version:
        node-v18.15.0

 Plugin Version:
        @oclif/plugin-autocomplete 2.3.6 (core)
        @oclif/plugin-commands 2.2.24 (core)
        @oclif/plugin-help 5.2.18 (core)
        @oclif/plugin-not-found 2.4.0 (core)
        @oclif/plugin-plugins 3.3.2 (core)
        @oclif/plugin-search 0.0.22 (core)
        @oclif/plugin-update 3.2.0 (core)
        @oclif/plugin-version 1.3.9 (core)
        @oclif/plugin-warn-if-update-available 2.0.49 (core)
        @oclif/plugin-which 2.2.32 (core)
        @salesforce/cli 2.7.11 (core)
        apex 2.3.12 (core)
        auth 2.8.14 (core)
        data 2.5.7 (core)
        deploy-retrieve 1.17.6 (core)
        info 2.6.40 (core)
        limits 2.3.32 (core)
        login 1.2.28 (core)
        marketplace 0.1.1 (core)
        org 2.10.5 (core)
        schema 2.3.24 (core)
        settings 1.4.27 (core)
        sobject 0.2.6 (core)
        source 2.10.32 (core)
        telemetry 2.3.1 (core)
        templates 55.5.10 (core)
        trust 2.6.7 (core)
        user 2.3.31 (core)

 OS and Version:
        Windows_NT 10.0.22621

 Shell:
        cmd.exe

 Root Path:
        C:\Program Files
```

**Comment by mshanemc** [comment]
Any chance you're using volta for node version switching?   If so, see https://github.com/forcedotcom/cli/issues?page=3&q=space

poweshell and cmd.exe are the "officially supported" windows shells.  We've had issues with that spaces thing on some of the others.
https://github.com/forcedotcom/cli/issues/1666
https://github.com/forcedotcom/cli/issues/44

**Comment by supert3d** [comment]
Thanks for getting back @mshanemc - I think, that extra layer, Bash Emulator on top of Windows can be problematic. For now, and for others coming to this thread, the easiest solve for me was to re-install in a non-spaced directory. `c:\salesforce-cli` and 🫰🏻 so far, so good....
