### ISSUE TITLE
Error: Unable to install unlocked package due to error Cannot add component of type:null named:null

### ISSUE THREAD

**Issue by gorankarabeg** [forcedotcom/cli#2462]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
I keep getting error when releasing unlocked package that a component of type:null named:null exists in another package.

### Steps To Reproduce
Work on two unlocked packages.
Move an item from one package to another. 

### Expected result
Expected to see the type and name of the component which is already installed in different package

### Actual result
Error: Unable to install "package-name" due to 
Installation errors: 
1) Cannot add component of type:null named:null subjectId:"xxx"to this package because it is an installed component in another package with packageId:"xxx", Details: package.xml: Cannot add component of type:null named:null subjectId:"xxx" to this package because it is an installed component in another package with packageId:"xxx".

### System Information
Running form Powershell terminal in VS code

PASTE_VERSION_OUTPUT_HERE
@salesforce/cli/2.3.8 win32-x64 node-v18.15.0

### Additional information
This doesn't always happen, but happen very often where several components have been moved between packages and after couple of removals from installed package we start getting type:null named:null bug.

**Comment by gorankarabeg** [comment]
Thanks for response. Here is full Salesfroce CLI version. Unfortunately I am not in power to provide the repo for this issue since it happens in our production environment only. Hope this helps:

sf version --verbose --json
{
  "cliVersion": "@salesforce/cli/2.7.11",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\a1610096\\AppData\\Local\\sf\\client\\2.7.11-5a5b1de",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 23.4.2 (user)",
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.24 (core)",
    "@oclif/plugin-help 5.2.18 (core)",
    "@oclif/plugin-not-found 2.4.0 (core)",
    "@oclif/plugin-plugins 3.3.2 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.0 (core)",
    "@oclif/plugin-version 1.3.9 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.49 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.7.11 (core)",
    "apex 2.3.12 (core)",
    "auth 2.8.14 (core)",
    "data 2.5.7 (core)",
    "deploy-retrieve 1.17.6 (core)",
    "env 2.1.23 (user)",
    "info 2.6.40 (core)",
    "limits 2.3.32 (core)",
    "login 1.2.28 (core)",
    "marketplace 0.1.1 (core)",
    "org 2.10.5 (core)",
    "packaging 1.22.2 (user)",
    "schema 2.3.24 (core)",
    "settings 1.4.27 (core)",
    "sobject 0.2.6 (core)",
    "source 2.10.32 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.7 (core)",
    "user 2.3.31 (core)",
    "sfdmu 4.30.0 (user)"
  ]
}

**Comment by mshanemc** [comment]
That error comes from the server and not the CLI.  I'm not a packaging expert, so I have a basic question:

Is this something that you think should work and there should not be an error (you are allowed to remove something from one package and add it to another)

or

Yeah, you're doing something that should produce an error BUT the error is bad with that `null` and so you want Salesforce to make the error more useful?

---

Either way, I'm pretty sure this doesn't belong to the CLI but to the packaging team's API.  They unfortunately don't take github issues and you'll need to open the official support case so they can collaborate with you to get it fixed?

**Comment by gorankarabeg** [comment]
Ok, I ll do that. I was thinking it was CLI issue but it might as well be packaging issue.
