### ISSUE TITLE
sf: command not found on GITLAB CLI Installation through Yaml file

### ISSUE THREAD

**Issue by Shahul9891NL** [forcedotcom/cli#2464]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
In the CI Script on GITLAB , Old SFDX CLI Tar file URL stopped working

### Steps To Reproduce
 ****OLD CI Script:****
 # Setup SFDX environment variables
 - export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
 - export ROOTDIR=force-app/main/default/

 # Install Salesforce CLI
 - mkdir sfdx
 - wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
 - "./sfdx/install"
 - export PATH=./sfdx/$(pwd):$PATH
 # Output CLI version and plug-in information
 - sfdx --version
 - sfdx plugins --core

New CI Script:

# Setup SFDX environment variables
 - export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
 - export ROOTDIR=force-app/main/default/

 # Install Salesforce CLI
 - mkdir sfdx
 - wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
 - export PATH=./sfdx/$(pwd):$PATH
 # Output CLI version and plug-in information
 - sf --version

### Expected result
It should return the installed version

### Actual result
but we are receiving sf command not found, we are not able to proceed to next step  as below. System is not recognizing the installation

JWT Auth and force deploy

Adding our complete Script file

#
default:
  tags:
    - virtualbox 

  
before_script:
 # Decrypt server key
 - which openssl
 - openssl aes-256-cbc -d -md md5 -in JWTFiles/server.key.enc -out JWTFiles/server.key -k $SERVER_KEY_PASSWORD

 # Setup SFDX environment variables
 - export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
 - export ROOTDIR=force-app/main/default/

 # Install Salesforce CLI
 - mkdir sfdx
 - wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
 - export PATH=./sfdx/$(pwd):$PATH
 # Output CLI version and plug-in information
 - sf --version

stages:
 - deploy

deploy: 
 stage: deploy  
 script:
  # Setting consumer key and username for the script to run
 - echo "Starting Deployment..."
 - if [ "$CI_COMMIT_BRANCH" == "INTG"  ]; 
   then 
      USERNAME="$SF_USERNAME_INTG"; 
      CONSUMERKEY="$SF_CONSUMER_KEY_INTG"; 
   elif [ "$CI_COMMIT_BRANCH" == "SIT"  ]; 
   then
      USERNAME="$SF_USERNAME_SIT";
      CONSUMERKEY="$SF_CONSUMER_KEY_SIT"; 
   elif [ "$CI_COMMIT_BRANCH" == "UAT"  ]; 
   then
      USERNAME="$SF_USERNAME_UAT";
      CONSUMERKEY="$SF_CONSUMER_KEY_UAT"; 
   elif [ "$CI_COMMIT_BRANCH" == "master"  ]; 
   then
      USERNAME="$SF_USERNAME_PROD";
      CONSUMERKEY="$SF_CONSUMER_KEY_PROD";       
   else
      echo "None of the condition met";
   fi
 
 - if [ "$CI_COMMIT_BRANCH" == "master"  ]; 
   then 
      CHECKONLY="-c";
      SFDC_LOGIN_URL="$SFDC_PRODUCTION_URL";
   else
      SFDC_LOGIN_URL="$SFDC_SANDBOX_URL";
   fi

  # Authenticate to the target org using the server key
 - sfdx auth:jwt:grant --clientid ${CONSUMERKEY} --jwtkeyfile JWTFiles/server.key --username ${USERNAME} --instanceurl ${SFDC_LOGIN_URL}

 - if [ "$CI_COMMIT_BRANCH" == "master"  ]; 
   then 
      MODULE="-l RunLocalTests"; 
   else MODULE=""; 
   fi

  #Deploying metadata to the target org
 - sfdx force:source:deploy --targetusername ${USERNAME} -p $ROOTDIR ${MODULE} ${CHECKONLY}
 rules:
    - if: $CI_COMMIT_BRANCH == "master"  || $CI_COMMIT_BRANCH == "INTG" || $CI_COMMIT_BRANCH == "SIT" || $CI_COMMIT_BRANCH == "UAT"
      when: always

**Comment by Shahul9891NL** [comment]
https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz

**Comment by cristiand391** [comment]
Hey @Shahul9891NL, we deleted that old tarball a few days ago, see:
https://github.com/forcedotcom/cli/issues/2460#issuecomment-1714309082

Last time we checked it was pointing to sfdx v7.82.0, which was published almost 3 years ago.

**Comment by Shahul9891NL** [comment]
Thanks cristian for checking.  We are using the latest version, but that is also failing
https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz

**Comment by cristiand391** [comment]
just tested it on a clean docker container and it works:

![Screenshot 2023-09-13 at 10 47 03](https://github.com/forcedotcom/cli/assets/6853656/b9da3cef-3ac0-4e62-9873-65a95d4f43c7)

After reading how you are installing it:
```
mkdir sfdx
wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
export PATH=./sfdx/$(pwd):$PATH
```

I think it's because you are adding `sfdx` to your `$PATH` when that should be `sfdx/bin`.

If that was working before it may be that the old tarballs was putting the CLI bin in the top-level folder.

**Comment by mshanemc** [comment]
The instructions are here.  They're slightly different for `sf`

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux
