### ISSUE TITLE
SFDX CLI is not getting installed- Showing GLIBC error

### ISSUE THREAD

**Issue by jitintaneja** [forcedotcom/cli#2465]
While installing Salesforce CLI on Linux using a TAR file -System is throwing GLIBC dependency error

### Steps To Reproduce
Running below commands in YML file to install SFDX CLI 

![image](https://github.com/forcedotcom/cli/assets/52113085/b28a5846-39ed-4f64-809c-c7e90ae8a7b2)

### Actual result
 
![image](https://github.com/forcedotcom/cli/assets/52113085/bd8cfeb5-e296-49fa-a7ad-019ea2acf1f6)

Please let us know if anyone knows the script which we can use to get rid of the above error or knows a different way to install SFDX CLI via YML file.

**Comment by cristiand391** [comment]
you'll need to update your linux distro or install the CLI via npm with an old node until you can update your distro, see:
https://github.com/forcedotcom/cli/issues/1788
