### ISSUE TITLE
@salesforce/cli: Updating CLI... already on version 2.7.11-5a5b1de NOTE: This error can be ignored in CI and may be silenced in the future

### ISSUE THREAD

**Issue by NagarjunaParala** [forcedotcom/cli#2466]
@salesforce/cli: Updating CLI... already on version 2.7.11-5a5b1de
NOTE: This error can be ignored in CI and may be silenced in the future
- Set the SF_HIDE_RELEASE_NOTES env var to "true" to skip this script

**Comment by mshanemc** [comment]
Closing because we never got the requested information
