### ISSUE TITLE
Could not use "sf project deploy start" command in VS Code

### ISSUE THREAD

**Issue by pnguyenduy2023** [forcedotcom/cli#2467]
Hello everyone, 
I am facing a weird issue in my VS Code, it happened when I tried to use "sf project deploy start" command to deploy my code to salesforce org:
![image](https://github.com/forcedotcom/cli/assets/131115759/dfe3ba6a-1ffd-4d15-9343-b9f6365c38b0)

My sfdx version is: 
![image](https://github.com/forcedotcom/cli/assets/131115759/c5c9dfee-0082-40d1-8109-d1be8b71f301)

Step to reproduce:
1. Open VS Code
2. Open a Salesforce project (the whole project folder with all required information was got from git)
3. Authenticate the salesforce org from VS Code.
4. From terminal, run "sf project deploy start"
5. Observe the result
Expected result: the project source code should be deployed successfully.
Actual result: the command could not run, and the "URI malformed" error happened.

I could not find out any article or topic that mentions about this issue or find out any way to fix it, I uninstalled and re-installed salesforce CLI but the same problem happened.

This is the version of my Salesforce CLI: 

{
  "cliVersion": "@salesforce/cli/2.7.11",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 21.6.0",
  "shell": "bash",
  "rootPath": "/usr/local/lib/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.24 (core)",
    "@oclif/plugin-help 5.2.18 (core)",
    "@oclif/plugin-not-found 2.4.0 (core)",
    "@oclif/plugin-plugins 3.3.2 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.0 (core)",
    "@oclif/plugin-version 1.3.9 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.49 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.7.11 (core)",
    "apex 2.3.12 (core)",
    "auth 2.8.14 (core)",
    "data 2.5.7 (core)",
    "deploy-retrieve 1.17.6 (core)",
    "info 2.6.40 (core)",
    "limits 2.3.32 (core)",
    "login 1.2.28 (core)",
    "marketplace 0.1.1 (core)",
    "org 2.10.5 (core)",
    "schema 2.3.24 (core)",
    "settings 1.4.27 (core)",
    "sobject 0.2.6 (core)",
    "source 2.10.32 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.7 (core)",
    "user 2.3.31 (core)"
  ]
}

Could you please advice what causes that problem and how to fix it?

Thanks in advance

**Comment by mshanemc** [comment]
@pnguyenduy2023 let's troubleshoot a few things.

1. can you run that with `DEBUG=*` in front of it and let me know if there are any URLs in the logs?
2. does `sf org open` work?  I'm making sure the org's auth files are in a good state
3. can you also try updating your CLI?  We had an issue with URI encoding a few weeks ago that had to roll back.   If that's the source of the error, it might already be fixed

**Comment by pnguyenduy2023** [comment]
Hello Shane McLaughlin,

That issue was gone after I updated the CLI, thank you very much for your
help, really appreciate it!

Best regards,
Phuong Nguyen Duy

======================
*Senior **Salesforce** Developer*
*Mobile:* +84 94 616 1983
*Linkedin Profile:* https://www.linkedin.com/in/phuong-nguyen-9033a6172/
