### ISSUE TITLE
Index file is empty (.git/index)

### ISSUE THREAD

**Issue by SD-ArunKumar** [forcedotcom/cli#2473]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### Expected result

Meadata should have been deployed.

### Actual result

An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

### System Information

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by mshanemc** [comment]
Closing the issue because it's missing the requested info about the CLI version/plugins.  It doesn't say what you're deploying wen the error happens, what command you're running, etc.
