### ISSUE TITLE
Cannot create package version while converting 1GP to 2GP managed package using sf package convert.

### ISSUE THREAD

**Issue by ashishrajbanshi** [forcedotcom/cli#2474]
### Summary
While migrating 1st gen package to 2nd gen managed package using sf package convert only package is created with 0Ho id. The command should also create package version. 

### Steps To Reproduce

- Identify 1st generation Package Id starts with 033.
- Create a test DX project
- Convert the package using command.
 `sf package convert --installation-key test -v debhubUsername --package 033.. --wait 20`
- Run following command to verification:
 `sf package list --verbose`
`sf package version list -p 0Ho.. -v debhubUsername`

> **IMPORTANT**
You can use any test project. 

### Expected result
There should be package version list of newly converted package while viewing version lists after using sf package command.

### Actual result
Only package id is shown while using sf package convert.

### System Information
{
  "cliVersion": "@salesforce/cli/2.9.8",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.17.1",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\user21\\AppData\\Roaming\\nvm\\v18.17.1\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.25 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.6.1 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.9.8 (core)",
    "apex 2.3.14 (core)",
    "auth 2.8.16 (core)",
    "data 2.5.9 (core)",
    "deploy-retrieve 1.17.13 (core)",
    "info 2.6.42 (core)",
    "limits 2.3.34 (core)",
    "login 1.2.30 (core)",
    "marketplace 0.2.1 (core)",
    "org 2.10.7 (core)",
    "packaging 1.22.1 (user)",
    "schema 2.3.25 (core)",
    "settings 1.4.28 (core)",
    "sobject 0.2.7 (core)",
    "source 2.10.33 (core)",
    "telemetry 2.3.2 (core)",
    "templates 55.5.11 (core)",
    "trust 2.6.10 (core)",
    "user 2.3.32 (core)",
    "@salesforce/sfdx-scanner 3.15.0 (user)"
  ]
}

```json
PASTE_VERSION_OUTPUT_HERE
```
### Additional information

I have followed the following steps in attach screenshot.
![image](https://github.com/forcedotcom/cli/assets/46884226/44f0444e-8f5d-423f-8bd6-ed03d006300b)

**Comment by mshanemc** [comment]
@ashishrajbanshi Thanks for reporting this, but the packaging team doesn't work with github issues.  
They'll only work with Salesforce support cases, and that'll give you the opportunity to share the pkg1 info with them so they can replicate this.
