### ISSUE TITLE
An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index)

### ISSUE THREAD

**Issue by Esma-De** [forcedotcom/cli#2476]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI. _**Yes it is 2.8.11**_
> - You've searched both open and closed issues for related posts. 
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
When I tried to retrieve or deploy to my sandbox I had this error 'An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Index file is empty (.git/index) ' 

For this org I also had an error "Metadata API request failed: EBUSY: resource busy or locked, open '\.sf\org\00D3H0000000PELUA2\localSourceTracking\index'

When I connected my trailhead org and retrieved and deployed there it worked with no error.

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### System Information

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by mshanemc** [comment]
@Esma-De I can't tell from your issue what CLI command you're running.

**Comment by bjconover** [comment]
I have ran into this issue before as well. The way that I was able to start pushing/pulling files from Salesforce again was by going to the .sf\orgs\(Org ID)\localSourceTracking\index and renaming the index file to a different name. Once I did that I reattempted the send and it created a new index file for me.

**Comment by tomansley** [comment]
> I have ran into this issue before as well. The way that I was able to start pushing/pulling files from Salesforce again was by going to the .sf\orgs(Org ID)\localSourceTracking\index and renaming the index file to a different name. Once I did that I reattempted the send and it created a new index file for me.

@bjconover how did you know to do that? Your solution worked for me. Nice job!

**Comment by Faaiz26** [comment]
> I have ran into this issue before as well. The way that I was able to start pushing/pulling files from Salesforce again was by going to the .sf\orgs(Org ID)\localSourceTracking\index and renaming the index file to a different name. Once I did that I reattempted the send and it created a new index file for me.

your solution works for me , thanks
