### ISSUE TITLE
Can't run sf commands without using sudo

### ISSUE THREAD

**Issue by pgonzaleznetwork** [forcedotcom/cli#2478]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
I just installed the `sf` CLI using [these instructions](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm).

I installed it using NPM and I had to use the `sudo` command because the `install` command was failing otherwise.

Now, every time I run an `sf` command, it fails with the following error:

```
pgonzalez@Pablos-MacBook-Pro:~ » sfdx version     
@salesforce/cli/2.8.11 darwin-arm64 node-v16.13.0
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/Users/pgonzalez/.sf/sf-2023-09-20.log'
Emitted 'error' event on ThreadStream instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/@salesforce/cli/node_modules/thread-stream/index.js:360:12)
    at processImmediate (node:internal/timers:464:21)
```

If I run the command with `sudo`, it works

Notice the command actually worked, but I get that weird permission error. 

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

Uninstall the sfdx CLI
Install the sf CLI via NPM
I get the error

### Expected result

I should be able to run the commands without `sudo`

### Actual result

All commands fail if I don't use `sudo`

### System Information

```json
 "cliVersion": "@salesforce/cli/2.8.11",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v16.13.0",
  "osVersion": "Darwin 21.0.1",
  "shell": "zsh",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.25 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.4.2 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.8.11 (core)",
    "apex 2.3.14 (core)",
    "auth 2.8.16 (core)",
    "data 2.5.8 (core)",
    "deploy-retrieve 1.17.8 (core)",
    "info 2.6.40 (core)",
    "limits 2.3.33 (core)",
    "login 1.2.29 (core)",
    "marketplace 0.1.3 (core)",
    "org 2.10.6 (core)",
    "schema 2.3.25 (core)",
    "settings 1.4.28 (core)",
    "sobject 0.2.6 (core)",
    "source 2.10.33 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.11 (core)",
    "trust 2.6.9 (core)",
    "user 2.3.32 (core)"
  ]
}
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/Users/pgonzalez/.sf/sf-2023-09-20.log'
Emitted 'error' event on ThreadStream instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/@salesforce/cli/node_modules/thread-stream/index.js:360:12)
    at processImmediate (node:internal/timers:464:21)
```
### Additional information

Here's what the log shows

```
cat /Users/pgonzalez/.sf/sf-2023-09-20.log                    1 ↵
{"level":40,"time":1695207115888,"name":"sf:TelemetryReporter","msg":"Connection to https://dc.services.visualstudio.com timed out after 1000 ms"}
{"0":"devhub pgonzaleznetwork@brave-raccoon-mm7crl.com has no scratch orgs","1":{"name":"NoActiveScratchOrgFound","exitCode":1},"level":50,"time":1695207434013,"name":"sf:Common","tag":"identifyPossibleScratchOrgs"}
{"0":"devhub pgonzaleznetwork@resourceful-moose-448750.com has no scratch orgs","1":{"name":"NoActiveScratchOrgFound","exitCode":1},"level":50,"time":1695207434591,"name":"sf:Common","tag":"identifyPossibleScratchOrgs"}
```

**Comment by mshanemc** [comment]
> I installed it using NPM and I had to use the sudo command because the install command was failing otherwise.

That's the source of the problem.  I'm more interested in the error that was happening that led you to make that choice.

We have a test that can cause that, only on windows, but have never seen it outside of that test environment.

We appreciate the new data!

**Comment by mshanemc** [comment]
Can you run some commands to check file/folder perms?
`ls -ld /Users/pgonzalez/.sf`
`ls -ld /Users/pgonzalez/.sf/sf-2023-09-20.log`

They'll probably show that they are owned by the root user, not you, so you can `chown` ([googled](https://linuxize.com/post/linux-chown-command/)) either `.sf` or that log file that it's complaining about so that your user can access it.

**Comment by mshanemc** [comment]
Remember that node16 is EOL, so you're about to have all kinds of problems trying to use it

https://github.com/forcedotcom/cli/issues/1985

**Comment by mshanemc** [comment]
I'm going to close this issue since I know what caused it.  Please open another one if you want to share what was happening during install that required `sudo`
