### ISSUE TITLE
pauseButtonlabel within vscode not displaying from salesforce screen flow

### ISSUE THREAD

**Issue by MattBracewell** [forcedotcom/cli#2485]
Within VSCode i have connected to my repo within azure dev ops.

I am retrieving from my salesforce developer sandbox a screen flow that includes custom labels on the footer of the screen related to the pause element.

Within the metadata i should be seeing a line such as:

` <pauseButtonLabel>Save and exit</pauseButtonLabel>`
 
 For a custom label on the standard pause button.
 
 However when i retrieve it from the org it removes this line of the code,
 
 If i do not connect to my repo and just pull the flow from the dev sandbox it will show.

**Comment by MattBracewell** [comment]
Hi the Salesforce CLI version is 
![image](https://github.com/forcedotcom/cli/assets/145788018/4cf891f2-26a9-43ba-a612-0f12e4222274)

**Comment by mdonnalley** [comment]
@MattBracewell Thanks for filing the issue! I have a few followup questions:

1. Can you provide the output of `sf version --verbose --json`?
2. What command are you using to deploy your source to the org?
3. If possible, it would be incredibly helpful if you could provide a repo that reproduces the issue. You can use [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc) as a starting point

Thanks!

**Comment by MattBracewell** [comment]
@mdonnalley see the screenshot for number 1
![image](https://github.com/forcedotcom/cli/assets/145788018/92429c25-5add-4e44-bab2-12df07a0da09)

The issue is not with deploying to the org. It is when i retrieve the flow metadata from from the org to my local branch it removes any reference to the line for the screen footer pause button label `<pauseButtonLabel>Save and exit</pauseButtonLabel>` 

I'm not sure how i would go about doing number 3 without some assistance sorry

**Comment by mdonnalley** [comment]
@MattBracewell I attempted to reproduce this with the following steps:
- create a scratch org based on the [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc) repo
- open the org, create a new Screen Flow
- add a new Screen
- in the Footer section, select `Use a custom label` under Pause Button and type `Save and exit`
- save all the changes
- retrieve using `sf project retrieve start --metadata Flow`

```
~/repos/trailheadapps/dreamhouse-lwc (main*) » sf project retrieve start --metadata Flow 
Preparing retrieve request...
Preparing retrieve request... Succeeded

Retrieved Source
=========================================================================================
| State   Name            Type Path
| ─────── ─────────────── ──── ──────────────────────────────────────────────────────────
| Created EmailFlow       Flow force-app/main/default/flows/EmailFlow.flow-meta.xml
```

And I see the `pauseButtonLabel` tag in the retrieved file:
```
~/repos/trailheadapps/dreamhouse-lwc (main*) » grep pauseButtonLabel force-app/main/default/flows/EmailFlow.flow-meta.xml
        <pauseButtonLabel>Save and exit</pauseButtonLabel>
```

Is there anything else I should do to reproduce the issue you're seeing? 

One last question, what do see from `sf project retrieve preview` if you edit the text of the pause button? You should see that flow show in the results. If it's not showing then it's either an issue with your source tracking files or with the org you're using

**Comment by MattBracewell** [comment]
I think it may be something to do with the repo that i am connecting to.

If i create a new manifest with project in vscode and do not connect to my repo then when i retrieve the flow from the org i see the changes made to the pause label.

However if i then connect to the repo and try again it disappears.

I am guessing somewhere in a config file there may be something stopping this from being pulled in

**Comment by iowillhoit** [comment]
Hello @MattBracewell I am not familiar with how connecting to a repo in Azure Dev Ops works. It almost sounds like a checkout is happening prior to the retrieve. 

Did you try @mdonnalley's suggestion of running `sf project retrieve preview` after modifying the label locally?

**Comment by iowillhoit** [comment]
Closing as stale. If you are still having problems please open a new Github Issue
