### ISSUE TITLE
Release Candidate (2.10.2) - No file found at config/project-scratch-def.json

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#2486]
### Summary
When trying to create a scratch org on RC (2.10.2), the following error is thrown: "No file found at config/project-scratch-def.json"

### Steps To Reproduce
1.  Execute `sf org create scratch -f config/project-scratch-def.json -d -a test-scratch-org`

### Expected result
Scratch org created successfully

### Actual result
Error thrown: **"No file found at config/project-scratch-def.json"**, despite the file being present

### System Information

zsh

```json
{
  "cliVersion": "@salesforce/cli/2.10.2",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.6.0",
  "shell": "zsh",
  "rootPath": "/Users/user/.local/share/sf/client/2.10.2-1c35561",
  "pluginVersions": [
    "@eon-com/eon-sfdx 1.13.3 (user)",
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.25 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.7.1 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.10.2 (core)",
    "1commerce 0.0.10 (user)",
    "apex 2.3.15 (core)",
    "auth 2.8.17 (core)",
    "community 2.4.2 (user)",
    "data 2.5.9 (core)",
    "deploy-retrieve 1.18.0 (core)",
    "functions 1.22.3 (user)",
    "info 2.6.43 (core)",
    "limits 2.3.34 (core)",
    "login 1.2.31 (core)",
    "marketplace 0.2.2 (core)",
    "org 2.10.8 (core)",
    "packaging 1.25.0 (user)",
    "schema 2.3.26 (core)",
    "settings 1.4.29 (core)",
    "signups 1.5.0 (user)",
    "sobject 0.2.7 (core)",
    "source 2.10.34 (core)",
    "telemetry 2.3.3 (core)",
    "templates 55.5.12 (core)",
    "trust 2.6.13 (core)",
    "user 2.3.32 (core)",
    "sfdmu 4.30.0 (user)"
  ]
}
```
### Additional information
<img width="1060" alt="image" src="https://github.com/forcedotcom/cli/assets/97173615/775f7430-ec0a-446f-9f7c-83d186e50128">

**Comment by petter-eikeland** [comment]
Downgrading to `2.9.8` fixes the issue

**Comment by mdonnalley** [comment]
@petter-eikeland I'm not seeing this on our end. Can you provide the contents of `config/project-scratch-def.json`? Also it'd be helpful if you could rerun the command with the `DEBUG=*` env var set and upload those logs. Thanks!

**Comment by petter-eikeland** [comment]
Yeah this is just me being stupid again. Just in the wrong directory... 🙃

Apologies
