### ISSUE TITLE
Spawn unknown error 

### ISSUE THREAD

**Issue by Prashantsoni25** [forcedotcom/cli#2488]
Type: <b>Bug</b>

I can't link salesforce Cli to vs code . I need to authorize my org but there is some issue.

Extension version: 58.14.2
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 7520U with Radeon Graphics          (8 x 2795)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.25GB (0.84GB free)|
|Process Argv|--crash-reporter-id 6998b177-9bc6-4490-ac19-2d1c7e374425|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
vscrp:30673768
2i9eh265:30646982
showlangstatbar:30737416
0bi6i642:30835152
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by mdonnalley** [comment]
@Prashantsoni25 Can you show me the contents of `C:\Program Files\sf\bin`? Also could you try running `sf` instead of `sfdx`? I ask because `sfdx` is really just an alias to `sf` so it's possible that something has gone wrong when the installer creates that alias

**Comment by Prashantsoni25** [comment]
@git

> Hello @Prashantsoni25 👋 It looks like you didn't include the full Salesforce CLI version information in your issue. Please provide the output of `version --verbose --json` for the CLI you're using (`sf` or `sfdx`).
> 
> A few more things to check:
> 
> * Make sure you've provided detailed steps to reproduce your issue.
>   
>   * A repository that clearly demonstrates the bug is ideal.
> * Make sure you've installed the latest version of Salesforce CLI. ([docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm))
>   
>   * Better yet, try the `rc` or `nightly` versions. ([docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_rc.htm))
> * Try running the `doctor` command to diagnose common issues.
> * Search GitHub for existing related issues.
> 
> Thank you!

![image](https://github.com/forcedotcom/cli/assets/143036067/0c75dff0-4a63-494c-a55e-f61f6013c073)

**Comment by Prashantsoni25** [comment]
@mdonnalley 
![Screenshot (193)](https://github.com/forcedotcom/cli/assets/143036067/7ee6be9a-600a-4a9a-a72f-93bef8246463)
![Screenshot (195)](https://github.com/forcedotcom/cli/assets/143036067/980b8c18-c55c-40d8-9fc0-e96f7a6425af)
![Screenshot (196)](https://github.com/forcedotcom/cli/assets/143036067/d9f8b5c8-e5fd-4e68-8c16-f8b21731adc0)
![Screenshot (208)](https://github.com/forcedotcom/cli/assets/143036067/3ca64059-ac9f-4380-b5f4-e828abdde824)


![image](https://github.com/forcedotcom/cli/assets/143036067/2fc81540-7554-474a-b1aa-916c921b7bea)

**Comment by Prashantsoni25** [comment]
@git
This the  output for sf version --verbose --json :

![image](https://github.com/forcedotcom/cli/assets/143036067/5423cc6f-04a1-452c-9e37-bdb45a1536d3)

This error im facing now : 
![image](https://github.com/forcedotcom/cli/assets/143036067/69491532-5ecf-4397-8c54-3408802a748a)

**Comment by Prashantsoni25** [comment]
@daphne-sfdc 
@git

Its working now I have reset my pc and installed everything again now i can authorize my  org .
![image](https://github.com/forcedotcom/cli/assets/143036067/b0d64207-75f2-4b88-b8c8-b7534e07c403)
