### ISSUE TITLE
WaveDataset deploy fails in DX format, works in MDAPI format

### ISSUE THREAD

**Issue by FeldhackerChrisPFG** [forcedotcom/cli#2505]
### Summary
Metadata of type "WaveDataset" can be successfully deployed with the CLI as long as the metadata is in MDAPI format.
However, deploy fails if the metadata is in DX format.

### Steps To Reproduce
Using the "new-exceptions-analysis" branch of the Event Monitoring Plus repository:
https://github.com/seamusocionnaigh/eventmonitoringplus/tree/new-exceptions-analysis

Given a Salesforce org with CRM Analytics and the Event Monitoring application fully installed:

Deploying the metadata in MDAPI format with the command:
sf project deploy start --metadata-dir .\misc\mdapi --dry-run
...succeeds without error:
Status: Succeeded | 17/17 Components (Errors:0) | 0/0 Tests (Errors:0)

Deploying the metadata in SF format with the command:
sf project deploy start --dry-run --dry-run
...fails with:
Status: Failed | 17/17 Components (Errors:1) | 0/0 Tests (Errors:0)
...and the error message:
An object 'ApexUnexpectedExceptionWithUsers' of type WaveDataset was named in package.xml, but was not found in zipped directory

The same results are generated even if the "--dry-run" argument is omitted.

### Expected result
It is expected that deploying WaveDataset metadata in DX format should complete without error.

### Actual result
Deployment fails with the problem:  "An object 'ApexUnexpectedExceptionWithUsers' of type WaveDataset was named in package.xml, but was not found in zipped directory"

### System Information
Windows 10 version 21H2 os build 19044.3448, Powershell 7.3.7
```json
{
  "cliVersion": "@salesforce/cli/2.10.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\X123456\\AppData\\Local\\sf\\client\\2.10.2-1c35561",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.25 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.7.1 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.10.2 (core)",
    "apex 2.3.15 (core)",
    "auth 2.8.17 (core)",
    "data 2.5.9 (core)",
    "deploy-retrieve 1.18.0 (core)",
    "info 2.6.43 (core)",
    "limits 2.3.34 (core)",
    "login 1.2.31 (core)",
    "marketplace 0.2.2 (core)",
    "org 2.10.8 (core)",
    "schema 2.3.26 (core)",
    "settings 1.4.29 (core)",
    "sobject 0.2.7 (core)",
    "source 2.10.34 (core)",
    "telemetry 2.3.3 (core)",
    "templates 55.5.12 (core)",
    "trust 2.6.13 (core)",
    "user 2.3.32 (core)"
  ]
}
```

**Comment by mshanemc** [comment]
source format would end in `.wds-meta.xml`.

https://github.com/search?q=.wds-meta.xml&type=code
