### ISSUE TITLE
[ERROR] - Flow Definition Metadata Type Error

### ISSUE THREAD

**Issue by o-olaosebikan** [forcedotcom/cli#2509]
### Summary

Version:
`o.olaosebikan@oolaose-ltmgjbv ~ % sf --version
@salesforce/cli/2.11.8 darwin-arm64 node-v18.15.0`

I was trying to create a package version but received an error while trying `sf package version create --package "*********" --installation-key "******" --wait 10` 

And I am receiving this error: 
`Error (1): /var/folders/qx/c80y96js615bp6bws45grfmr0000gp/T/0HoQT00000000060AA-c5f451c63ac6efc461e283ff09298baf/md-files/flowDefinitions/AbandonedCartFlow.flowDefinitio: Could not infer a metadata type

Try this:

A metadata type lookup for "AbandonedCartFlow.flowDefinitio" found the following close matches:
-- Did you mean ".flowDefinition" instead for the "FlowDefinition" metadata type?
`

I was hoping I could get some assistance with this as I do have the right suffix for the metadata type in my project structure.

Thanks in advance!

**Comment by o-olaosebikan** [comment]
version:
{
  "cliVersion": "@salesforce/cli/2.11.8",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.6.0",
  "shell": "zsh",
  "rootPath": "/Users/o.olaosebikan/.local/share/sf/client/2.11.8-c9872b8",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.26 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.8.2 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.11.8 (core)",
    "apex 2.3.15 (core)",
    "auth 2.8.17 (core)",
    "data 2.5.12 (core)",
    "deploy-retrieve 1.18.3 (core)",
    "info 2.6.45 (core)",
    "limits 2.3.35 (core)",
    "login 1.2.31 (core)",
    "marketplace 0.2.2 (core)",
    "org 2.10.8 (core)",
    "packaging 1.26.1 (user)",
    "schema 2.3.28 (core)",
    "settings 1.4.30 (core)",
    "sobject 0.2.7 (core)",
    "source 2.10.36 (core)",
    "telemetry 2.3.4 (core)",
    "templates 55.5.13 (core)",
    "trust 2.6.15 (core)",
    "user 2.3.32 (core)"
  ]
}

**Comment by iowillhoit** [comment]
Hello @o-olaosebikan, it looks like you might have a typo in your metadata suffix. `flowDefinitio` is missing a `n`. I believe the full correct suffix would be `.flowDefinition-meta.xml`. The full filename would then be `AbandonedCartFlow.flowDefinition-meta.xml`

Could you give that a try and let me know if it solves your issue?

**Comment by shetzel** [comment]
You are packaging metadata in mdapi format.  Solution is to convert the source in your project to source format and package that source.

**Comment by yehielz** [comment]
I have the same issue.  Trying to create a new version on an existing package will generate this error:  Could not infer a metadata type.
looking behind the scenes:   sf plugin generates md-files in tempapp data, and the metadata type is truncated at the last letter.  
flexipag instead of flexipage
ap instead of app
....

below ouput of sf version --verbose --json

{
  "cliVersion": "@salesforce/cli/1.86.7-legacy.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.22621",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\Yehiel\\AppData\\Local\\sfdx\\client\\7.209.6-8ba3197\\sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.1 (core)",
    "@oclif/plugin-commands 2.2.17 (core)",
    "@oclif/plugin-help 5.2.11 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.18 (core)",
    "@oclif/plugin-update 3.1.22 (core)",
    "@oclif/plugin-version 1.3.6 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.41 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.86.7-legacy.0 (core)",
    "apex 2.3.4 (core)",
    "auth 2.8.4 (core)",
    "data 2.4.5 (core)",
    "deploy-retrieve 1.13.5 (core)",
    "env 2.1.15 (user)",
    "info 2.6.30 (core)",
    "limits 2.3.23 (core)",
    "login 1.2.15 (core)",
    "org 2.9.19 (core)",
    "packaging 1.20.1 (user)",
    "schema 2.3.17 (core)",
    "settings 1.4.17 (core)",
    "sobject 0.1.32 (core)",
    "source 2.10.22 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.5.2 (core)",
    "trust 2.4.27 (core)",
    "user 2.3.20 (core)"
  ]
}

**Comment by cristiand391** [comment]
@yehielz can you try using latest sf v2?

you are using sf v1.86.7-legacy.0

**Comment by yehielz** [comment]
Thanks for your reply.  My issue was related to the fact that I had metadata in md format within the project.  
https://github.com/forcedotcom/cli/issues/2541
