### ISSUE TITLE
"INVALID_OPERATION: rollbackOnError option must be true on a production org" when running force:source:deploy of a single class to production

### ISSUE THREAD

**Issue by RuneSor** [forcedotcom/cli#251]
### Summary

I'm running this command:
`sfdx force:source:deploy -m "ApexClass:LeadController" -u customerProd -l RunLocalTests`
and get this response:
````
8536 bytes written to /var/folders/../sdx_sourceDeploy_1576322508976.zip using 78.532ms
Deploying /var/folders/../sdx_sourceDeploy_1576322508976.zip...
ERROR running force:source:deploy:  INVALID_OPERATION: rollbackOnError option must be true on a production org
````

### Steps To Reproduce:
Set up with plug-ins for a setup like this:
````
$ sfdx plugins   
@salesforce/lwc-dev-server 1.0.8
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

salesforcedx 48.0.5 (pre-release)
├─ salesforcedx-templates 48.0.7
└─ salesforce-alm 48.0.5
````
As you may notice, i've got the pre-release plug-in installed (which i think may be the culprit in this case). I uninstalled the plug-in with:
`$ sfdx plugins:uninstall salesforcedx`

 so my setup now looks like this:
````
$ sfdx plugins                       
@salesforce/lwc-dev-server 1.0.8
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

$ sfdx version                       
sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3
````
And presto! 

````
$ sfdx force:source:deploy -m "ApexClass:LeadController" -u customerProd -l RunLocalTests
8536 bytes written to /var/folders/../T/sdx_sourceDeploy_1576322699415.zip using 34.557ms
Deploying /var/folders/../T/sdx_sourceDeploy_1576322699415.zip...

=== Status
Status:  InProgress
jobid:  0Af1v00001dmHneCAE
..
..

Total Test Time:  67581.0

=== Deployed Source
FULL NAME       TYPE       PROJECT PATH
──────────────  ─────────  ──────────────────────────────────────────────────────────
LeadController  ApexClass  force-app/main/default/classes/LeadController.cls
LeadController  ApexClass  force-app/main/default/classes/LeadController.cls-meta.xml
````

### Additional information

I noticed [Peter Knolles recent bug report](https://github.com/forcedotcom/cli/issues/249) on the source:deploy command and figured best to report mine as well in case these are related. 

#### SFDX CLI Version:
sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3

#### SFDX plugin Version (after removing only the pre-release plugin)

`````
$ sfdx plugins --core
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.8
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)
`````

#### OS and version:

macOS Catalina
Version 10.15.2

**Comment by clairebianchi** [comment]
@RuneSor, Thank you for reporting this, just so I am clear, what you are saying is you are able to do the deploy on the current weekly version of the CLI but when you have pre-release installed you get the error?

**Comment by RuneSor** [comment]
@clairebianchi, That's correct.

I will try to reproduce the error, there should be some open time during the holidays to play around with my setup :)
