### ISSUE TITLE
AutoLauchedFlow Type could not trigger

### ISSUE THREAD

**Issue by o-olaosebikan** [forcedotcom/cli#2510]
### Summary
Currently looking to create a package version using `sf package version create --package "********" --installation-key "*****" --wait 10` and ran into an error for my source flow definition file which stated

**Error (1): Multiple errors occurred: 
(1) **********: Flows of type AutoLaunchedFlow can’t have the trigger type DataCloudDataChange.
(2) **********: Flows of type AutoLaunchedFlow can’t have the trigger type DataCloudDataChange.**

My source files currently have a trigger type of "DataCloudChange" 

Is there any possible workaround for this?

Version:
{
  "cliVersion": "@salesforce/cli/2.11.8",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.6.0",
  "shell": "zsh",
  "rootPath": "/Users/o.olaosebikan/.local/share/sf/client/2.11.8-c9872b8",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.26 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.8.2 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.11.8 (core)",
    "apex 2.3.15 (core)",
    "auth 2.8.17 (core)",
    "data 2.5.12 (core)",
    "deploy-retrieve 1.18.3 (core)",
    "info 2.6.45 (core)",
    "limits 2.3.35 (core)",
    "login 1.2.31 (core)",
    "marketplace 0.2.2 (core)",
    "org 2.10.8 (core)",
    "packaging 1.26.1 (user)",
    "schema 2.3.28 (core)",
    "settings 1.4.30 (core)",
    "sobject 0.2.7 (core)",
    "source 2.10.36 (core)",
    "telemetry 2.3.4 (core)",
    "templates 55.5.13 (core)",
    "trust 2.6.15 (core)",
    "user 2.3.32 (core)"
  ]
}

**Comment by shetzel** [comment]
This is a question for the Flows team.  The CLI is just reporting the error.
