### ISSUE TITLE
Issue in new CLI command, package version creation

### ISSUE THREAD

**Issue by adlsolution** [forcedotcom/cli#2515]
After updating to the new CLI version, I could not create a new package version.

I am not getting an error, in a few seconds it's saying as created but actually, it's not creating anything. 

![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/71051782/97bf295e-f95d-4095-b031-774c4dc17d4a)

**Comment by mshanemc** [comment]
Can you "pretend" to open a new issue on this repo (open it but don't save).   It'll have some instructions for getting the version of the CLI and plugins that you're using.

I'm pretty sure this error was fixed recently but I'm not sure what version you're on.
* https://github.com/forcedotcom/cli/issues/2434
* https://github.com/forcedotcom/cli/issues/2469

**Comment by adlsolution** [comment]
Thanks for the info, found the issue that I was missing meta.xml file in a static resource file.

I am in the latest version.
