### ISSUE TITLE
sf package version create - Language code not valid Winter '24

### ISSUE THREAD

**Issue by marsh-mellow** [forcedotcom/cli#2518]
### Summary
This issue appears to have started when Salesforce version was updated. Error message says this language isn't available when everything was packaging before the upgrade. 

sf package version create -w 100 -x -c -v <hub> -p 0Hxxx
 »   Warning: Plugin @salesforce/plugin-packaging (1.16.2) differs from the version specified by sf (1.26.1)
Version create.... -
Error (1): Can’t create package version. **en_CA** isn’t a valid language code. Review the language codes listed on this Salesforce Help page: https://help.salesforce.com/s/articleView?id=sf.faq_getstart_what_languages_does.htm&type=5. Then update the language code, and try creating the package 

### Steps To Reproduce

![image](https://github.com/forcedotcom/cli/assets/25592474/301e5bb1-ec1e-4fc0-9316-c2eee0c9e202)

### Expected result
Package was built without error

### Actual result
Error (1): Can’t create package version. **en_CA** isn’t a valid language code. Review the language codes listed on this Salesforce Help page: https://help.salesforce.com/s/articleView?id=sf.faq_getstart_what_languages_does.htm&type=5. Then update the language code, and try creating the package 

### System Information
Windows Bash MINGW64

```json
{
  "cliVersion": "@salesforce/cli/2.11.8",
  "architecture": "win32-x64",
  "nodeVersion": "node-v16.15.1",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\marsham1\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.26 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.8.2 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.11.8 (core)",
    "apex 2.3.15 (core)",
    "auth 2.8.17 (core)",
    "community 2.2.8 (user)",
    "data 2.5.12 (core)",
    "deploy-retrieve 1.18.3 (core)",
    "info 2.6.45 (core)",
    "limits 2.3.35 (core)",
    "login 1.2.31 (core)",
    "marketplace 0.2.2 (core)",
    "org 2.10.8 (core)",
    "packaging 1.16.2 (user)",
    "schema 2.3.28 (core)",
    "settings 1.4.30 (core)",
    "sobject 0.2.7 (core)",
    "source 2.10.36 (core)",
    "telemetry 2.3.4 (core)",
    "templates 55.5.13 (core)",
    "trust 2.6.15 (core)",
    "user 2.3.32 (core)"
  ]
}
```

**Comment by marsh-mellow** [comment]
CLI Version:
        @salesforce/cli/2.11.8

 Architecture:
        win32-x64

 Node Version:
        node-v16.15.1

 Plugin Version:
        @oclif/plugin-autocomplete 2.3.8 (core)
        @oclif/plugin-commands 2.2.26 (core)
        @oclif/plugin-help 5.2.19 (core)
        @oclif/plugin-not-found 2.4.1 (core)
        @oclif/plugin-plugins 3.8.2 (core)
        @oclif/plugin-search 0.0.22 (core)
        @oclif/plugin-update 3.2.3 (core)
        @oclif/plugin-version 1.3.10 (core)
        @oclif/plugin-warn-if-update-available 2.1.0 (core)
        @oclif/plugin-which 2.2.32 (core)
        @salesforce/cli 2.11.8 (core)
        apex 2.3.15 (core)
        auth 2.8.17 (core)
        community 2.2.8 (user)
        data 2.5.12 (core)
        deploy-retrieve 1.18.3 (core)
        info 2.6.45 (core)
        limits 2.3.35 (core)
        login 1.2.31 (core)
        marketplace 0.2.2 (core)
        org 2.10.8 (core)
        packaging 1.16.2 (user)
        schema 2.3.28 (core)
        settings 1.4.30 (core)
        sobject 0.2.7 (core)
        source 2.10.36 (core)
        telemetry 2.3.4 (core)
        templates 55.5.13 (core)
        trust 2.6.15 (core)
        user 2.3.32 (core)

 OS and Version:
        Windows_NT 10.0.19045

 Shell:
        C:\Program Files\Git\usr\bin\bash.exe

 Root Path:
        C:\Users\marsham1\AppData\Roaming\npm\node_modules\@salesforce\cli

**Comment by marsh-mellow** [comment]
### Updated 3 plugins
- @salesforce/plugin-packaging
- @salesforce/plugin-community
- @salesforce/plugin-signups

using **npm install --global** @salesforce/plugin-packaging

### Same Error
Error (1): Can’t create package version. en_CA isn’t a valid language code. Review the language codes listed on this Salesforce Help page: https://help.salesforce.com/s/articleView?id=sf.faq_getstart_what_languages_does.htm&type=5. Then update the language code, and tryVersion create.... done

**Comment by marsh-mellow** [comment]
Confirmed scratches are still working

**Comment by marsh-mellow** [comment]
`{
  "code": 1,
  "message": "Can’t create package version. en_CA isn’t a valid language code. Review the language codes listed on this Salesforce Help page: https://help.salesforce.com/s/articleView?id=sf.faq_getstart_what_languages_does.htm&type=5. Then update the language code, and 
try creating the package version again.",
  "name": "INVALID_INPUT",
  "status": 1,
  "stack": "INVALID_INPUT: Can’t create package version. en_CA isn’t a valid language code. Review the language codes listed on this Salesforce Help page: https://help.salesforce.com/s/articleView?id=sf.faq_getstart_what_languages_does.htm&type=5. Then update the language code, and try creating the package version again.\n    at HttpApi.getError (C:\\Users\\marsham1\\AppData\\Local\\sf\\node_modules\\@salesforce\\sf-plugins-core\\node_modules\\jsforce\\lib\\http-api.js:307:12)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async C:\\Users\\marsham1\\AppData\\Local\\sf\\node_modules\\@salesforce\\sf-plugins-core\\node_modules\\jsforce\\lib\\http-api.js:154:23\n    at async Tooling.create (C:\\Users\\marsham1\\AppData\\Local\\sf\\node_modules\\@salesforce\\sf-plugins-core\\node_modules\\jsforce\\lib\\connection.js:929:133)\n    at async PackageVersionCreate.packageVersionCreate (C:\\Users\\marsham1\\AppData\\Local\\sf\\node_modules\\@salesforce\\packaging\\lib\\package\\packageVersionCreate.js:486:30)\n    at async Function.create (C:\\Users\\marsham1\\AppData\\Local\\sf\\node_modules\\@salesforce\\packaging\\lib\\package\\packageVersion.js:92:30)\n    at async PackageVersionCreateCommand.run (C:\\Users\\marsham1\\AppData\\Local\\sf\\node_modules\\@salesforce\\plugin-packaging\\lib\\commands\\package\\version\\create.js:60:24)\n    at async PackageVersionCreateCommand._run (C:\\Users\\marsham1\\AppData\\Local\\sf\\node_modules\\@salesforce\\sf-plugins-core\\node_modules\\@oclif\\core\\lib\\command.js:108:22)\n    at async Config.runCommand (C:\\Users\\marsham1\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\config\\config.js:314:25)\n    at async run (C:\\Users\\marsham1\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli\\node_modules\\@oclif\\core\\lib\\main.js:89:16)",
  "exitCode": 1,
  "warnings": []
}`

**Comment by mshanemc** [comment]
@marsh-mellow FYI you can update that plugin to latest by saying

```
sf plugins uninstall packaging
sf plugins install packaging@latest
```

not `npm -g`.

I doubt it'll solve your problem because this looks like a server/release issue.

**Comment by iowillhoit** [comment]
I agree with Shane. This does not look like a CLI issue. Can you try uninstalling these plugins with 
`npm uninstall @salesforce/plugin-packaging @salesforce/plugin-community @salesforce/plugin-signups --global`

And installing them with the CLI itself:
`sf plugins install @salesforce/plugin-packaging @salesforce/plugin-community @salesforce/plugin-signups`

Do you have any other languages in your project?

**Comment by marsh-mellow** [comment]
Just the en_CA, fr_Ca and of course the default en_US

**Comment by marsh-mellow** [comment]
Tried the uninstall in npm and install with SF. Same error. I also have a ticket open with salesforce.

**Comment by marsh-mellow** [comment]
FYI Here is the new version output after plugin install

```json{
  "cliVersion": "@salesforce/cli/2.11.8",
  "architecture": "win32-x64",
  "nodeVersion": "node-v16.15.1",
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "rootPath": "C:\\Users\\marsham1\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.26 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.8.2 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.11.8 (core)",
    "apex 2.3.15 (core)",
    "auth 2.8.17 (core)",
    "community 2.4.5 (user)",
    "data 2.5.12 (core)",
    "deploy-retrieve 1.18.3 (core)",
    "info 2.6.45 (core)",
    "limits 2.3.35 (core)",
    "login 1.2.31 (core)",
    "marketplace 0.2.2 (core)",
    "org 2.10.8 (core)",
    "packaging 1.26.3 (user)",
    "schema 2.3.28 (core)",
    "settings 1.4.30 (core)",
    "signups 1.5.5 (user)",
    "sobject 0.2.7 (core)",
    "source 2.10.36 (core)",
    "telemetry 2.3.4 (core)",
    "templates 55.5.13 (core)",
    "trust 2.6.15 (core)",
    "user 2.3.32 (core)"
  ]
}```

**Comment by iowillhoit** [comment]
Interesting, I am assuming you are not having any issues with `fr_Ca`? Let us know what you find out on the Case, it may help someone else out 👍

**Comment by BMTBalazsBiro** [comment]
I have experienced the same with 'hu'.

"Can’t create package version. hu isn’t a valid language code."

**Comment by marsh-mellow** [comment]
Still waiting on Case with Salesforce. Will update here once I know more.

**Comment by paulhxcd** [comment]
Does anyone have any updates on this? We've also logged a case with Salesforce but not making any progress so far.

**Comment by shetzel** [comment]
What's the case number?  I'll check on it.

**Comment by paulhxcd** [comment]
Thanks @shetzel our case number is 45520085

I also reached out to the packaging PM

**Comment by shetzel** [comment]
That case number doesn't match something related to this issue.  Possibly a different number?

**Comment by Mr-Modus** [comment]
Our case number is #45474747

**Comment by paulhxcd** [comment]
@shetzel sorry I'm confused, case 45520085 is exactly about this issue!

**Comment by shetzel** [comment]
@paulhxcd - sorry, I checked with the wrong system (which referenced a different case).  Dileep appears to be helping to move the case along.

**Comment by marsh-mellow** [comment]
Response from Salesforce today about issue

=============================

I would like to provide an update regarding the issue pertaining to the new package version creation. After our investigation, our product team has identified a critical bug. This bug arises when a user attempts to create a package version, and we identify their locale (in this case, en_CA) to create a package version. Currently, our validation method for supported languages is stringent, allowing only "Fully Supported Languages." We are working to expand this to accommodate all types of languages supported by the organization.

Our team is actively working to resolve this high-priority bug. In the meantime, if this issue is hindering your package version creation, there is a temporary workaround available. You can specify a fully supported language code, such as en_US, via the CLI command (using --language=en_US), which should enable you to create versions successfully.

**Comment by marsh-mellow** [comment]
I confirmed the workaround does work with the language switch.
sf package version create -c -w 100 -x -v hub -p XXX **--language en_US**

**Comment by marsh-mellow** [comment]
Closing.
