### ISSUE TITLE
Creating scratch orgs - getting errors related to SpawnedTelemetry and TelemetryReporter

### ISSUE THREAD

**Issue by sinanbunni** [forcedotcom/cli#252]
### Summary
Trying to create a scratch org from a bash script using the command
sfdx force:org:create -f project-scratch-def.json -a ${ORG_NAME} -d 7 --setdefaultusername --json

Getting the following error:
{
    "status": 1,
    "name": "ProblemDeployingSettings",
    "message": "Failed to deploy settings to scratch org.",
    "exitCode": 1,
    "commandName": "OrgCreateCommand",
    "stack": "ProblemDeployingSettings: Failed to deploy settings to scratch org.\n    at ALMError (/Users/deenajebry/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/salesforce-alm/dist/lib/core/almError.js:44:19)\n    at settings.createDeployDir.then.catch.err (/Users/deenajebry/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/salesforce-alm/dist/lib/core/scratchOrgApi.js:672:37)\nOuter stack:\n    at Function.wrap (/Users/deenajebry/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at OrgCreateCommand.catch (/Users/deenajebry/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)",
    "warnings": []
}

### SFDX Log file
{"name":"sfdx","hostname":"Deenas-MacBook-Pro.local","pid":58234,"log":"OrgCreateCommand","level":50,"msg":"{\n    \"status\": 1,\n    \"name\": \"ProblemDeployingSettings\",\n    \"message\": \"Failed to deploy settings to scratch org.\",\n    \"exitCode\": 1,\n    \"commandName\": \"OrgCreateCommand\",\n    \"stack\": \"ProblemDeployingSettings: Failed to deploy settings to scratch org.\\n    at ALMError (/Users/deenajebry/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/salesforce-alm/dist/lib/core/almError.js:44:19)\\n    at settings.createDeployDir.then.catch.err (/Users/deenajebry/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/salesforce-alm/dist/lib/core/scratchOrgApi.js:672:37)\\nOuter stack:\\n    at Function.wrap (/Users/deenajebry/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\\n    at OrgCreateCommand.catch (/Users/deenajebry/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/salesforce-alm/dist/ToolbeltCommand.js:247:46)\",\n    \"warnings\": []\n}","time":"2019-12-17T17:53:00.473Z","v":0}
{"name":"sfdx","hostname":"Deenas-MacBook-Pro.local","pid":58234,"log":"SpawnedTelemetry","level":40,"msg":"Insights logging in enabled. This can be disabled by setting SFDX_DISABLE_INSIGHTS=true","time":"2019-12-17T17:53:00.478Z","v":0}
{"name":"sfdx","hostname":"Deenas-MacBook-Pro.local","pid":58242,"log":"TelemetryReporter","level":40,"msg":"Insights logging in enabled. This can be disabled by setting SFDX_DISABLE_INSIGHTS=true","time":"2019-12-17T17:53:00.857Z","v":0}

**SFDX CLI Version**
sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3

**SFDX plugin Version**
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)

sfdx-cli 7.36.0 (core)

**OS and version**:
Mac OS 
version 10.15.1

**Comment by clairebianchi** [comment]
We are taking a look at this internally. I will keep you posted when we know more

**Comment by clairebianchi** [comment]
@sinanbunni, talking a look at the log lines, the message telemetry is merely stating that telemetry is enabled:
{"name":"sfdx","hostname":"Deenas-MacBook-Pro.local","pid":58242,"log":"TelemetryReporter","level":40,"msg":"Insights logging in enabled. This can be disabled by setting SFDX_DISABLE_INSIGHTS=true","time":"2019-12-17T17:53:00.857Z","v":0}
Can you make sure that the devhub that you are creating the org from has all the settings you are using available?
