### ISSUE TITLE
Task Related List Mass quick actions cannot be deployed

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#2521]
### Summary
Trying to deploy new Related List Mass quick actions using `sf`. It works for Custom Objects and other Standard Objects (Accounts, Contacts, Case), but not Task. However, I can enable the Task Related List mass quick action in the UI. And I can retrieve it using `sf`. 

### Steps To Reproduce

1.  Checkout [dreamhouse-lwc](https://github.com/petter-eikeland/dreamhouse-lwc)
1.  Create new scratch org
1.  Deploy Account Layout in **issues/mass-quick-action-bug/** using `sf project deploy start -d  "issues/mass-quick-action-bug/layouts/Account-Account Layout.layout-meta.xml"`

### Expected result

Task Related List Mass Action should have been added to Account Layout.

### Actual result

`Mass quick actions don’t support Activity. Use a valid entity` error is thrown. 

### System Information

```json
{
  "cliVersion": "@salesforce/cli/2.12.9",
  "architecture": "darwin-arm64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 22.6.0",
  "shell": "zsh",
  "rootPath": "/Users/user/.local/share/sf/client/2.12.9-007e29c",
  "pluginVersions": [
    "@eon-com/eon-sfdx 1.13.3 (user)",
    "@oclif/plugin-autocomplete 2.3.9 (core)",
    "@oclif/plugin-commands 2.2.28 (core)",
    "@oclif/plugin-help 5.2.20 (core)",
    "@oclif/plugin-not-found 2.4.3 (core)",
    "@oclif/plugin-plugins 3.8.4 (core)",
    "@oclif/plugin-search 0.0.23 (core)",
    "@oclif/plugin-update 3.2.4 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.1 (core)",
    "@oclif/plugin-which 2.2.34 (core)",
    "@salesforce/cli 2.12.9 (core)",
    "1commerce 0.0.10 (user)",
    "apex 2.3.17 (core)",
    "auth 2.8.19 (core)",
    "community 2.4.5 (user)",
    "data 2.5.15 (core)",
    "deploy-retrieve 1.18.6 (core)",
    "functions 1.22.3 (user)",
    "info 2.6.48 (core)",
    "limits 2.3.37 (core)",
    "login 1.2.34 (core)",
    "marketplace 0.3.0 (core)",
    "org 2.10.11 (core)",
    "packaging 1.26.3 (user)",
    "schema 2.3.29 (core)",
    "settings 1.4.33 (core)",
    "signups 1.5.3 (user)",
    "sobject 0.2.10 (core)",
    "source 2.10.39 (core)",
    "telemetry 2.3.6 (core)",
    "templates 55.5.14 (core)",
    "trust 2.6.18 (core)",
    "user 2.3.35 (core)",
    "sfdmu 4.30.0 (user)"
  ]
}

```
### Additional information

If you remove the Task.Defer quick action in the Layout and deploy again, then you are able to deploy a Case Related List mass quick action. Also, you are able to add the Task Related List mass quick action in the UI. And if you do, then `sf` is able to retrieve it.
<img width="1275" alt="image" src="https://github.com/forcedotcom/cli/assets/97173615/35c999ec-16f2-4135-8b23-1470fd27f837">

 [The Salesforce Docs](https://help.salesforce.com/s/articleView?id=sf.mass_quick_actions_considerations.htm&type=5) state that "**You can’t use the Tooling API, AppExchange, and Changesets to add mass quick actions to an object’s list view button layout.**", which could suggest that it is not supported by the Metadata API? However it seems like this is not the issue as I am able deploy the Related List Mass quick actions for other objects.

**Comment by iowillhoit** [comment]
Hey @petter-eikeland 👋 Thank you for the reproduction repo! We really appreciate it. I am able to see the exact same results. Unfortunately, this does not appear to be a CLI issue. I was able to deploy your metadata in Workbench and saw the same results (bypassing the CLI). 



![Image](https://github.com/forcedotcom/cli/assets/1715111/ba73cdad-5ac8-4260-a89f-8c899ec6646b)



It is odd that this does seem to work on certain objects despite the docs that you shared. I think your best bet is to open a Salesforce support ticket to see if you can get more information from the team that owns that metadata. Thanks again for the thorough details and good luck!

**Comment by petter-eikeland** [comment]
Thank you for a thorough reply 🔥

I've created a Case for this. I'll keep the Issue open until I've clarified the issue with SF Support.

**Comment by iowillhoit** [comment]
Sounds great @petter-eikeland! Any information you find out could be helpful to someone later on. Thanks!

**Comment by petter-eikeland** [comment]
The reason why the Task Related List Mass Action Quick Action cannot be deployed is that the related list is actually an **Activity** related list. And the Activity object does not support Quick Actions. Thus, the deployment fails correctly due to the limitations of the Activity object.

I would argue that the metadata change in Salesforce when adding quick actions to Activity Related List is a bug, as the metadata is then in an invalid state. And furthermore, it is weird that SF supports the change in the UI to this invalid state, but does not allow the same change through the Metadata API. But I guess that's the SF technical debt for you.
