### ISSUE TITLE
Unable to use Salesforce CLI commands via VS Code

### ISSUE THREAD

**Issue by simonhyphen8** [forcedotcom/cli#2524]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
Unable to run commands such as Authorize an Org or Create a Default Scratch Org from within VS Code - errors below

### Steps To Reproduce

- Open a new project in VS Code with the Salesforce Extension Pack installed
- Use the command SFDX: Authorize an Org
- Error occurs (see below)
- Open a project in VS Code with the Salesforce Extension Pack installed
- While connected to a Salesforce Dev Hub use command SFDX: Create a Default Scratch Org...
- Populate settings (Scratch definition file, Scratch org alias, duration of scratch org. in days)
- Error occurs (see below)

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
No repo available as this is not repo / project specific.  These errors are occurring on ALL projects and ALL scratch org projects
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### Expected result
Either the web browser opens to authorize an org OR a new scratch org should be generated

### Actual result
Error messages:
Authorize an org. error:
sfdx org:login:web --alias [REDACTED] --instance-url https://test.salesforce.com/ --set-default
/Users/[USERNAME]/.local/share/sfdx/client/bin/sfdx: line 16: /Users/[USERNAME]/.local/share/sfdx/client/bin/../7.209.6-8ba3197/bin/sfdx: No such file or directory

Create default scratch org error:
10:31:29.728 sfdx force:org:create -f config/project-scratch-def.json --setalias [SCRATCHORGNAME] --durationdays 7 --setdefaultusername --json --loglevel fatal
ended with exit code 1

### System Information
Terminal = zsh

Unable to run either "SF" or "SFDX" commands from the terminal - This is part of the issue.
```json

```
### Additional information
I have tried removing the Salesforce Extension Pack and then uninstalling VS Code, then reinstalling VSCode and the Salesforce Extension pack, with no success.
This was working fine up until about two weeks ago - everything was working as expected, all CLI commands were working.  I have changed nothing in my setup but now CLI commands do not work.  I raised this originally under the VS Code repository but was told I had to log it here.
Please assist.

**Comment by simonhyphen8** [comment]
I am unable to run either SF or SFDX commands, so cannot provide the version --verbose --json data.
I have changed nothing on my laptop setup, but this stopped working about two weeks ago and I am out of ideas on how to fix it.

**Comment by iowillhoit** [comment]
Hello @simonhyphen8 👋  This is a known bug, please see the workarounds on this pinned issue: https://github.com/forcedotcom/cli/issues/2447

Best solution is to completely uninstall `sfdx` and install the new `sf` CLI

**Comment by digihims** [comment]
Hi [simonhyphen8](https://github.com/simonhyphen8), SFDX and it's packages are essentially "dead" as of this year. You better try installing sf using npm and debug all the "quickstart" packages by replacing SFDX commands with the equivalent sf commands. 

We are able to install Salesforce B2B "scratch" org using sf
