### ISSUE TITLE
I am trying to create mainfest but its failing 

### ISSUE THREAD

**Issue by pjha06** [forcedotcom/cli#2527]
Command used: `sfdx force source manifest create --from-org EpamOneHealthConnectdev -n=allMetadata -d manifest`
Issues:
```
C:\Users\Prabhatkumar_Jha\AppData\Local\sf\client\2.12.9-007e29c\node_modules\@salesforce\source-deploy-retrieve\lib\src\resolve\connectionResolver.js:59
                    throw new core_1.SfError(messages.getMessage('error_could_not_infer_type', [component.fullName]), 'TypeInferenceError', [messages.getMessage('suggest_type_more_suggestions')]);
                          ^

SfError [TypeInferenceError]: _Default: Could not infer a metadata type
    at C:\Users\Prabhatkumar_Jha\AppData\Local\sf\client\2.12.9-007e29c\node_modules\@salesforce\source-deploy-retrieve\lib\src\resolve\connectionResolver.js:59:27
    at Array.map (<anonymous>)
    at ConnectionResolver.resolve (C:\Users\Prabhatkumar_Jha\AppData\Local\sf\client\2.12.9-007e29c\node_modules\@salesforce\source-deploy-retrieve\lib\src\resolve\connectionResolver.js:36:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ComponentSet.fromConnection (C:\Users\Prabhatkumar_Jha\AppData\Local\sf\client\2.12.9-007e29c\node_modules\@salesforce\source-deploy-retrieve\lib\src\collections\componentSet.js:157:26)
    at async ComponentSetBuilder.build (C:\Users\Prabhatkumar_Jha\AppData\Local\sf\client\2.12.9-007e29c\node_modules\@salesforce\source-deploy-retrieve\lib\src\collections\componentSetBuilder.js:116:40)
    at async ManifestGenerate.run (C:\Users\Prabhatkumar_Jha\AppData\Local\sf\client\2.12.9-007e29c\node_modules\@salesforce\plugin-deploy-retrieve\lib\commands\project\generate\manifest.js:38:30)
    at async ManifestGenerate._run (C:\Users\Prabhatkumar_Jha\AppData\Local\sf\client\2.12.9-007e29c\node_modules\@oclif\core\lib\command.js:117:22)
    at async Config.runCommand (C:\Users\Prabhatkumar_Jha\AppData\Local\sf\client\2.12.9-007e29c\node_modules\@oclif\core\lib\config\config.js:314:25)
    at async run (C:\Users\Prabhatkumar_Jha\AppData\Local\sf\client\2.12.9-007e29c\node_modules\@oclif\core\lib\main.js:89:16) {
  cause: undefined,
  actions: [
    'Additional suggestions:\n' +
      'Confirm the file name, extension, and directory names are correct. Validate against the registry at:\n' 
+
      '<https://github.com/forcedotcom/source-deploy-retrieve/blob/main/src/registry/metadataRegistry.json>\n' 
+
      '\n' +
      'If the type is not listed in the registry, check that it has Metadata API support via the Metadata Coverage Report:\n' +
      '<https://developer.salesforce.com/docs/metadata-coverage>\n' +
      '\n' +
      'If the type is available via Metadata API but not in the registry\n' +
      '\n' +
      '- Open an issue <https://github.com/forcedotcom/cli/issues>\n' +
      '- Add the type via PR. Instructions: <https://github.com/forcedotcom/source-deploy-retrieve/blob/main/contributing/metadata.md>'
  ],
  exitCode: 1
}
```
Workaround :i created package using another plugin and it has below metadatatypes which is not listed in your registry so it maybe failing:
1)CareBenefitVerifySettings
2)DiscoveryStory
3)ExternalAIModel
4)IdentityVerificationProcDef
5)IdentityVerificationProcDtl
6)IdentityVerificationProcFld
7)RegisteredExternalService

Please check and let me know if you need any more info.

**Comment by pjha06** [comment]
Please exclude below as it is not in coverage report 
5)IdentityVerificationProcDtl
6)IdentityVerificationProcFld

**Comment by pjha06** [comment]
> version --verbose --json

{
  "code": 1,
  "context": "ManifestGenerate",
  "commandName": "ManifestGenerate",
  "message": "Nonexistent flag: --verbose\nSee more help with --help",
  "name": "Error",
  "status": 1,
  "stack": "Error: Nonexistent flag: --verbose\nSee more help with --help\n    at validateArgs (C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.12.9-007e29c\\node_modules\\@oclif\\core\\lib\\parser\\validate.js:10:19)\n    at validate (C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.12.9-007e29c\\node_modules\\@oclif\\core\\lib\\parser\\validate.js:153:5)\n    at Object.parse (C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.12.9-007e29c\\node_modules\\@oclif\\core\\lib\\parser\\index.js:19:35)\n    at async ManifestGenerate.parse (C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.12.9-007e29c\\node_modules\\@oclif\\core\\lib\\command.js:221:25)\n    at async ManifestGenerate.run (C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.12.9-007e29c\\node_modules\\@salesforce\\plugin-deploy-retrieve\\lib\\commands\\project\\generate\\manifest.js:32:27)\n    at async ManifestGenerate._run (C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.12.9-007e29c\\node_modules\\@oclif\\core\\lib\\command.js:117:22)\n    at async Config.runCommand (C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.12.9-007e29c\\node_modules\\@oclif\\core\\lib\\config\\config.js:314:25)\n    at async run (C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.12.9-007e29c\\node_modules\\@oclif\\core\\lib\\main.js:89:16)",
  "exitCode": 1,
  "warnings": []
}

**Comment by shetzel** [comment]
@pjha06 - just to clarify, the ask is to get the following types added to SDR's metadata registry correct?

1. CareBenefitVerifySettings
2. DiscoveryStory
3. ExternalAIModel
4. IdentityVerificationProcDef
5. RegisteredExternalService

**Comment by pjha06** [comment]
> @pjha06 - just to clarify, the ask is to get the following types added to SDR's metadata registry correct?
> 
> 1. CareBenefitVerifySettings
> 2. DiscoveryStory
> 3. ExternalAIModel
> 4. IdentityVerificationProcDef
> 5. RegisteredExternalService

yes correct

**Comment by pjha06** [comment]
yes correct
