### ISSUE TITLE
Error after plugin is linked - TypeError: this.config.plugins.filter

### ISSUE THREAD

**Issue by tparaiso** [forcedotcom/cli#2529]
After we linked the custom plugin, when we are starting a command we have :  TypeError: this.config.plugins.filter is not a function, any thing has changed in the custom plugin.

**Comment by tparaiso** [comment]
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.13.9",
  "nodeVersion": "node-v20.6.0",
  "osVersion": "Darwin 23.0.0",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.9 (core)",
    "@oclif/plugin-commands 2.2.28 (core)",
    "@oclif/plugin-help 5.2.20 (core)",
    "@oclif/plugin-not-found 2.4.3 (core)",
    "@oclif/plugin-plugins 3.9.1 (core)",
    "@oclif/plugin-search 0.0.23 (core)",
    "@oclif/plugin-update 3.2.4 (core)",
    "@oclif/plugin-version 2.0.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.1 (core)",
    "@oclif/plugin-which 2.2.34 (core)",
    "@salesforce/cli 2.13.9 (core)",
    "apex 2.3.19 (core)",
    "auth 2.8.20 (core)",
    "data 2.5.16 (core)",
    "deploy-retrieve 1.19.0 (core)",
    "info 2.6.49 (core)",
    "limits 2.3.38 (core)",
    "login 1.2.35 (core)",
    "marketplace 0.3.0 (core)",
    "org 2.10.12 (core)",
    "packaging 1.18.0 (user)",
    "schema 2.3.29 (core)",
    "settings 1.4.33 (core)",
    "sobject 0.2.11 (core)",
    "source 2.10.40 (core)",
    "telemetry 2.3.6 (core)",
    "templates 55.5.14 (core)",
    "trust 2.6.18 (core)",
    "user 2.3.36 (core)",
    "edenred-sfdx-plugin 2.0.0 (link) /Users/Thomas/developpement/programmes/customer/Redforce/customer-sfdx-plugin"
  ]
}

**Comment by cristiand391** [comment]
Hi @tparaiso, I don't see this error when linking our core plugins on sf v2.13.9. 
is your plugin open source? if not, can you show what dependencies is it using? I'm interested in the oclif ones.

**Comment by tparaiso** [comment]
Hi Christian, sorry the plugin isn't open source.
This is our dependencies : 
"dependencies": {
    "@oclif/core": "^2.8.2",
    "@salesforce/core": "^3.34.8",
    "@salesforce/kit": "^3.0.1",
    "@salesforce/sf-plugins-core": "^2.4.3",
    "csvtojson": "^2.0.10",
    "fs": "^0.0.1-security",
    "path": "^0.12.7",
    "tslib": "^2",
    "xml2js": "^0.5.0"
  },
  "devDependencies": {
    "@oclif/test": "^2.3.17",
    "@salesforce/cli-plugins-testkit": "^3.4.0",
    "@salesforce/dev-config": "^4.0.1",
    "@salesforce/dev-scripts": "^5.0.1",
    "@salesforce/prettier-config": "^0.0.2",
    "@salesforce/ts-sinon": "^1.4.6",
    "@swc/core": "^1.3.61",
    "@types/inquirer": "^9.0.3",
    "@types/xml2js": "^0.4.11",
    "@typescript-eslint/eslint-plugin": "^5.59.6",
    "@typescript-eslint/parser": "^5.59.6",
    "chai": "^4.3.6",
    "eslint": "^8.21.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-salesforce": "^2.0.1",
    "eslint-config-salesforce-typescript": "^1.1.1",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-jsdoc": "^44.2.4",
    "eslint-plugin-sf-plugin": "^1.15.3",
    "mocha": "^9.2.2",
    "nyc": "^15.1.0",
    "oclif": "^3.8.1",
    "prettier": "^2.8.8",
    "pretty-quick": "^3.1.3",
    "shx": "^0.3.4",
    "sinon": "10.0.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.7.3",
    "wireit": "^0.9.5"
  }

**Comment by cristiand391** [comment]
A teammate suggested to bump `@oclif/core` to 2.15.0 or higher (and also `@salesforce/sf-plugins-core` to 3.1.21 or higher).

**Comment by tparaiso** [comment]
I have updated my dependencies and the plugin works well! Thank you for your help! 

 "dependencies": {
    "**@oclif/core": "^2.15.0",**
    "@salesforce/core": "^3.34.8",
    "@salesforce/kit": "^3.0.1",
    "**@salesforce/sf-plugins-core": "^3.1.21**",
    "csvtojson": "^2.0.10",
    "fs": "^0.0.1-security",
    "path": "^0.12.7",
    "tslib": "^2",
    "xml2js": "^0.5.0"
  },
