### ISSUE TITLE
force:source:retrieve causes JavaScript heap out of memory

### ISSUE THREAD

**Issue by tsadigovAgmail** [forcedotcom/cli#253]
### Summary

Trying to retrieve all metadata

### Steps To Reproduce:

1.  we:auth
2.  force:source:retrieve ...

### Expected result

files should have been downloaded.

### Actual result

I get
FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory

### Additional information

I tried with --dev-debug
and heres my output

sfdx:SourceRetrieve INFO Retrieving metadata 'InstalledPackage,CustomLabels,StaticResource,Scontrol,Certificate,AuraDefinitionBundle,LightningComponentBundle,ApexComponent,ApexPage,Queue,CaseSubjectParticle,ExternalDataSource,NamedCredential,ExternalServiceRegistration,Role,Group,GlobalValueSet,StandardValueSet,CustomPermission,CustomObject,ReportType,Report,Dashboard,AnalyticSnapshot,CustomFeedFilter,Layout,Document,CustomPageWebLink,Letterhead,EmailTemplate,QuickAction,FlexiPage,CustomTab,CustomApplicationComponent,CustomApplication,CustomMetadata,Flow,FlowDefinition,Workflow,AssignmentRules,AutoResponseRules,EscalationRules,PostTemplate,ApprovalProcess,HomePageComponent,HomePageLayout,CustomObjectTranslation,GlobalValueSetTranslation,StandardValueSetTranslation,ApexClass,ApexTrigger,ApexTestSuite,Profile,PermissionSet,ProfilePasswordPolicy,ProfileSessionSetting,OauthCustomScope,DataCategoryGroup,RemoteSiteSetting,CspTrustedSite,MatchingRules,DuplicateRule,CleanDataService,AuthProvider,EclairGeoData,CustomSite,ChannelLayout,ContentAsset,SharingRules,Community,ChatterExtension,PlatformEventChannel,PlatformEventChannelMember,CallCenter,CanvasMetadata,MobileApplicationDetail,CustomNotificationType,ConnectedApp,AppMenu,DelegateGroup,SiteDotCom,NetworkBranding,BrandingSet,FlowCategory,LightningBolt,LightningExperienceTheme,LightningOnboardingConfig,CustomHelpMenuSection,Prompt,CampaignInfluenceModel,SamlSsoConfig,CorsWhitelistOrigin,ActionLinkGroupTemplate,SynonymDictionary,PathAssistant,AnimationRule,LeadConvertSettings,PlatformCachePartition,TopicsForObjects,RecommendationStrategy' from org: 'removed@real.login.foo' +0ms

<--- Last few GCs --->

[31608:0x102802800]  1139828 ms: Scavenge 281.9 (308.4) -> 275.2 (309.4) MB, 4.3 / 0.0 ms  (average mu = 1.000, current mu = 0.987) allocation failure 
[31608:0x102802800]  1139956 ms: Scavenge 282.4 (309.4) -> 275.8 (310.4) MB, 2.8 / 0.0 ms  (average mu = 1.000, current mu = 0.987) allocation failure 
[31608:0x102802800]  1140082 ms: Scavenge 283.0 (310.4) -> 276.3 (311.9) MB, 3.7 / 0.0 ms  (average mu = 1.000, current mu = 0.987) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x10f3a4f5be3d]
    1: StubFrame [pc: 0x10f3a511c1dd]
Security context: 0x2da12ec1e6e9 <JSObject>
    2: lookupValue(aka lookupValue) [0x2da154b736e9] [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/node_modules/salesforce-alm/node_modules/jsforce/lib/soap.js:135] [bytecode=0x2da1968fe5b1 offset=26](this=0x2da1e21026f1 <undefined>,obj=0x2da1ff982201 <Very long string[124818057]>,propRegExps=0x2da1096bca59 <JS...

FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
 1: 0x10003c597 node::Abort() [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
 2: 0x10003c7a1 node::OnFatalError(char const*, char const*) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
 3: 0x1001ad575 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
 4: 0x100579242 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
 5: 0x1006e4e81 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet, 1>::Rehash(v8::internal::Handle<v8::internal::OrderedHashSet>, int) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
 6: 0x1006e4175 v8::internal::OrderedHashSet::Add(v8::internal::Handle<v8::internal::OrderedHashSet>, v8::internal::Handle<v8::internal::Object>) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
 7: 0x10065a31d v8::internal::KeyAccumulator::AddKey(v8::internal::Handle<v8::internal::Object>, v8::internal::AddKeyConversion) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
 8: 0x10050e709 v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastStringWrapperElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)9> >::CollectElementIndices(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::KeyAccumulator*) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
 9: 0x10065c2b7 v8::internal::KeyAccumulator::CollectOwnElementIndices(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
10: 0x10065b5ae v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
11: 0x10065aa4b v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
12: 0x10065baee v8::internal::FastKeyAccumulator::GetKeysSlow(v8::internal::GetKeysConversion) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
13: 0x1007cd9ae v8::internal::Runtime_ForInEnumerate(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/test/.local/share/sfdx/client/7.36.0-b1c4e9c7c8/bin/node]
14: 0x10f3a4f5be3d 
15: 0x10f3a511c1dd 
/Users/test/.local/share/sfdx/client/bin/../7.36.0-b1c4e9c7c8/bin/sfdx: line 58: 31608 Abort trap: 6           SFDX_BINPATH="$DIR/$BIN_NAME" "$NODE_PATH" "${NODE_FLAGS[@]}" "$DIR/$MAIN_NAME" "$@"
mbpro:CCI test$ 

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
sfdx --version

sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3
mbpro:CCI test$ 
mbpro:CCI test$ sfdx plugins --core
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)

sfdx-cli 7.36.0 (core)

**OS and version**:
MacOS Mojave
v 10.14.3 (18D42)
MacBook Pro (15-inch, 2018)
Mem 16 GB 2400 MHz DDR4

**Comment by turalsadik** [comment]
does anyone check thease issues?

**Comment by clairebianchi** [comment]
@tsadigov can you give us more information on what you are trying to retrieve and the size?

**Comment by RajkumarGaikwad** [comment]
I am also experiencing the same issue ? do we have any solution on this?

**Comment by turalsadik** [comment]
@clairebianchi  thanks for interest, I specified in summary that I am trying to retreive all metadata. Do you need anything else or something specifically?

What you mean by size? Size of all xml files?

**Comment by turalsadik** [comment]
this is the list from above log that I am trying to retreive

InstalledPackage,CustomLabels,StaticResource,Scontrol,Certificate,AuraDefinitionBundle,LightningComponentBundle,ApexComponent,ApexPage,Queue,CaseSubjectParticle,ExternalDataSource,NamedCredential,ExternalServiceRegistration,Role,Group,GlobalValueSet,StandardValueSet,CustomPermission,CustomObject,ReportType,Report,Dashboard,AnalyticSnapshot,CustomFeedFilter,Layout,Document,CustomPageWebLink,Letterhead,EmailTemplate,QuickAction,FlexiPage,CustomTab,CustomApplicationComponent,CustomApplication,CustomMetadata,Flow,FlowDefinition,Workflow,AssignmentRules,AutoResponseRules,EscalationRules,PostTemplate,ApprovalProcess,HomePageComponent,HomePageLayout,CustomObjectTranslation,GlobalValueSetTranslation,StandardValueSetTranslation,ApexClass,ApexTrigger,ApexTestSuite,Profile,PermissionSet,ProfilePasswordPolicy,ProfileSessionSetting,OauthCustomScope,DataCategoryGroup,RemoteSiteSetting,CspTrustedSite,MatchingRules,DuplicateRule,CleanDataService,AuthProvider,EclairGeoData,CustomSite,ChannelLayout,ContentAsset,SharingRules,Community,ChatterExtension,PlatformEventChannel,PlatformEventChannelMember,CallCenter,CanvasMetadata,MobileApplicationDetail,CustomNotificationType,ConnectedApp,AppMenu,DelegateGroup,SiteDotCom,NetworkBranding,BrandingSet,FlowCategory,LightningBolt,LightningExperienceTheme,LightningOnboardingConfig,CustomHelpMenuSection,Prompt,CampaignInfluenceModel,SamlSsoConfig,CorsWhitelistOrigin,ActionLinkGroupTemplate,SynonymDictionary,PathAssistant,AnimationRule,LeadConvertSettings,PlatformCachePartition,TopicsForObjects,RecommendationStrategy
