### ISSUE TITLE
Error "TypeError: this.config.plugins.filter is not a function" when running commands

### ISSUE THREAD

**Issue by corentindoctolib** [forcedotcom/cli#2530]
### Summary
Getting error `TypeError: this.config.plugins.filter is not a function` when running commands like : 
- `sf org list shape`
- `sf org create shape`
- `sf org delete shape`

(I'm also getting a warning when running these commands : 
_"Warning: Plugin @salesforce/plugin-signups (1.4.10) differs from the version specified by sf (1.5.5)_", could be related)

### Steps To Reproduce
Private repo, sorry.  Just run the command `sf org list shape`

### Expected result
Command get list of org shape

### Actual result
Command fails, with message `TypeError: this.config.plugins.filter is not a function`

### System Information

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.13.9",
  "nodeVersion": "node-v18.17.1",
  "osVersion": "Windows_NT 10.0.22621",
  "rootPath": "C:\\Users\\corentin.romilly\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.9 (core)",
    "@oclif/plugin-commands 2.2.28 (core)",
    "@oclif/plugin-help 5.2.20 (core)",
    "@oclif/plugin-not-found 2.4.3 (core)",
    "@oclif/plugin-plugins 3.9.1 (core)",
    "@oclif/plugin-search 0.0.23 (core)",
    "@oclif/plugin-update 3.2.4 (core)",
    "@oclif/plugin-version 2.0.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.1 (core)",
    "@oclif/plugin-which 2.2.34 (core)",
    "@salesforce/cli 2.13.9 (core)",
    "apex 2.3.19 (core)",
    "auth 2.8.20 (core)",
    "data 2.5.16 (core)",
    "deploy-retrieve 1.19.0 (core)",
    "dev 0.7.0 (user)",
    "info 2.6.49 (core)",
    "limits 2.3.38 (core)",
    "login 1.2.35 (core)",
    "marketplace 0.3.0 (core)",
    "org 2.10.12 (core)",
    "packaging 1.16.2 (user)",
    "schema 2.3.29 (core)",
    "settings 1.4.33 (core)",
    "signups 1.4.10 (user)",
    "sobject 0.2.11 (core)",
    "source 2.10.40 (core)",
    "telemetry 2.3.6 (core)",
    "templates 55.5.14 (core)",
    "trust 2.6.18 (core)",
    "user 2.3.36 (core)"
  ]
}
```

### Additional information
![image](https://github.com/forcedotcom/cli/assets/88317880/32081ded-0e0b-42b8-bd24-c0bba469a7b5)

**Comment by cristiand391** [comment]
@corentindoctolib I think the error is caused by the signups plugin (which contains the `shape` commands) using an old dependencies that conflict with latest CLI.

can you uninstall and reinstall latests again?
just run `sf plugins uninstall @salesforce/plugin-signups` then `sf plugins install @salesforce/plugin-signups`

**EDIT**:
if someone else gets this error you can run `sf plugins update` to update old JIT/user plugins to latest.

**Comment by corentindoctolib** [comment]
It worked, thanks @cristiand391 for you quick answer :)
