### ISSUE TITLE
Cannot install  "npm install @salesforce/cli --global" in githubactions

### ISSUE THREAD

**Issue by Shrivatsa1988** [forcedotcom/cli#2534]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Steps To Reproduce
9m 5s
Run npm install @salesforce/cli --global

added 923 packages in [1](https://github.com/ILC-Technology/juno-booking/actions/runs/6612163904/job/17958149265#step:4:1)9s

92 packages are looking for funding
  run `npm fund` for details
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sa11y/assert@5.2.0',
npm WARN EBADENGINE   required: { node: '^[16](https://github.com/ILC-Technology/juno-booking/actions/runs/6612163904/job/17958149265#step:4:17) || ^[18](https://github.com/ILC-Technology/juno-booking/actions/runs/6612163904/job/17958149265#step:4:19)' },
npm WARN EBADENGINE   current: { node: 'v[21](https://github.com/ILC-Technology/juno-booking/actions/runs/6612163904/job/17958149265#step:4:22).0.0', npm: '10.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sa11y/common@5.2.0',
npm WARN EBADENGINE   required: { node: '^16 || ^18' },
npm WARN EBADENGINE   current: { node: 'v21.0.0', npm: '10.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sa11y/format@5.2.0',
npm WARN EBADENGINE   required: { node: '^16 || ^18' },
npm WARN EBADENGINE   current: { node: 'v21.0.0', npm: '10.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sa11y/jest@5.2.0',
npm WARN EBADENGINE   required: { node: '^16 || ^18' },
npm WARN EBADENGINE   current: { node: 'v21.0.0', npm: '10.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sa11y/preset-rules@5.2.0',
npm WARN EBADENGINE   required: { node: '^16 || ^18' },
npm WARN EBADENGINE   current: { node: 'v21.0.0', npm: '10.2.0' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic. 
npm WARN deprecated cli-ux@4.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated cli-ux@5.6.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated cli-ux@5.6.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated cli-ux@5.6.7: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### System Information

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by Shrivatsa1988** [comment]
This is same as 
**https://github.com/forcedotcom/cli/issues/1293**

**Comment by cristiand391** [comment]
@Shrivatsa1988 are you getting a failure in GH actions or is it just the warnings from npm? I'm able to install sf from npm using node v21.0.0 + npm v10.2.0.

**Comment by Shrivatsa1988** [comment]
This was issue with node version i have downgraded and i was able to proceed further
@cristiand391  even i was able to install this locally but in github action it was just loading ,
after downgrading the version to 20.8.1 it worked might be something to do with node latest version with cli

@cristiand391  i was getting only warnings no failures,

**Comment by cristiand391** [comment]
@Shrivatsa1988 do you get those warnings locally using node v21 + npm v10?

**Comment by Shrivatsa1988** [comment]
Hello Sorry i missed responding here, we resolved it using Latest LTS version, but it is still an issue
