### ISSUE TITLE
Error when generating new package version:  Could not infer metada type 

### ISSUE THREAD

**Issue by yehielz** [forcedotcom/cli#2541]
I have the same issue. Trying to create a new version on an existing package will generate this error: Could not infer a metadata type.
I was trying to create a package version but received an error while trying sf package version create --package "*********" --installation-key "******" --wait 10

And I am receiving this error:
C:\Users\*****\AppData\Local\Temp\**********-912e2879161444ba06e8aef5d588e651\md-files\applications\***********.ap: Could not infer a metadata type

or

C:\Users\*****\AppData\Local\Temp\**********-912e2879161444ba06e8aef5d588e651\md-files\applications\***********.flexipag: Could not infer a metadata type

looking behind the scenes: sf plugin generates md-files in tempapp data, and the metadata type is truncated at the last letter.
flexipag instead of flexipage
ap instead of app
....

below ouput of sf version --verbose --json

{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.14.6",
  "nodeVersion": "node-v16.17.1",
  "osVersion": "Windows_NT 10.0.22621",
  "rootPath": "C:\\Users\\*****\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.10 (core)",
    "@oclif/plugin-commands 3.0.3 (core)",
    "@oclif/plugin-help 6.0.3 (core)",
    "@oclif/plugin-not-found 3.0.2 (core)",
    "@oclif/plugin-plugins 3.9.2 (core)",
    "@oclif/plugin-search 1.0.3 (core)",
    "@oclif/plugin-update 4.1.2 (core)",
    "@oclif/plugin-version 2.0.3 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.1 (core)",
    "@oclif/plugin-which 3.0.5 (core)",
    "@salesforce/cli 2.14.6 (core)",
    "apex 2.3.20 (core)",
    "auth 2.8.22 (core)",
    "data 2.5.19 (core)",
    "deploy-retrieve 1.19.2 (core)",
    "env 2.1.15 (user)",
    "info 2.6.49 (core)",
    "limits 2.3.39 (core)",
    "login 1.2.37 (core)",
    "marketplace 0.3.0 (core)",
    "org 2.11.4 (core)",
    "packaging 1.26.4 (user)",
    "schema 2.3.30 (core)",
    "settings 1.4.35 (core)",
    "sobject 0.2.13 (core)",
    "source 2.10.43 (core)",
    "telemetry 2.3.6 (core)",
    "templates 55.5.14 (core)",
    "trust 2.6.20 (core)",
    "user 2.3.37 (core)"
  ]
}

**Comment by shetzel** [comment]
90% of the time people report this error it's because they are running a command that requires metadata in source format but their metadata is in mdapi format.  If the flexipage metadata files in your project have a suffix of (e.g.) `Property_Explorer.flexipage` versus `Property_Explorer.flexipage-meta.xml` then your source is in mdapi format and you must first convert it to source format before creating a package version.

**Comment by shetzel** [comment]
Also, the nodeVersion reported above from `sf version --verbose` is 16.17.1, which is no longer supported by node so I would update to the latest LTS.  https://endoflife.date/nodejs

**Comment by yehielz** [comment]
Thanks for you help!! Closing the issue.
