### ISSUE TITLE
Error while inserting Metadata Records through .csv file

### ISSUE THREAD

**Issue by SourabhMulay** [forcedotcom/cli#2546]
I am using latest version of CLI.

While inserting custom metadata records with below command.
sfdx force:cmdt:record:insert --filepath  (path to .csv)  --typename  (Metadata sObj Name)

result:(Error)
Cannot read properties of undefined (reading 'fullName')

**Comment by cristiand391** [comment]
@SaurabhMulay999 please complete the bug report template
https://raw.githubusercontent.com/forcedotcom/cli/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by SourabhMulay** [comment]
Hey @cristiand391 ,
I have tried appending the records through Linux machine  and it worked. 
I'm not sure why for windows it's not working. But Currently I'm okay so I'll mark it as close. 
If I found any further issue I'll raise a issue in suggested templated format.
Thanks!!!!
