### ISSUE TITLE
Unable to retrieve LWC with manifest

### ISSUE THREAD

**Issue by ericrsmith35** [forcedotcom/cli#255]
This package.xml file comes back with no results even though I have lwc components in the org.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
<types>
    <members>*</members>
    <name>LightningComponentBundle</name>
</types>
<version>47.0</version>
</Package>
```
`09:35:14.867 sfdx force:source:retrieve --manifest d:\esmit\Documents\Salesforce\ersmith\manifest\package.xml
=== Retrieved Source
No results found
09:35:39.492 sfdx force:source:retrieve --manifest d:\esmit\Documents\Salesforce\ersmith\manifest\package.xml ended with exit code 0`

**Comment by clairebianchi** [comment]
@ericrsmith35 can you please send us more information such as your CLI version and OS. Also please confirm that you are pointing to the org that contains the LWC components when you run the command
