### ISSUE TITLE
Facing error while using @salesforce/core on AWS serverless

### ISSUE THREAD

**Issue by thebedroomprogrammer** [forcedotcom/cli#2553]
### Summary
I am using the @salesforce/core package and just upgraded to version 5.2.9. The issue that I am running into now is that when running the code on the server I get the error `ERROR	Error: unable to determine transport target for "../../lib/logger/transformStream"`, even though I am using the flag `SF_DISABLE_LOG_FILE: true` in my env file to disable the logs. This was not happening in the previous version as the logger was honouring the flag passed in the env file.

I looked at the code and I think that [this](https://github.com/forcedotcom/sfdx-core/blob/d20ec2a1069a593ef7a7db33b429fc6913ca6d6b/src/logger/logger.ts#L187) is the code that is causing the issue.

### Steps To Reproduce
Any serverless project that uses the @salesforce/core package with the version. 5.2.9 with AWS serverless should have the issue with the logs disabled.

### Expected result
Since I had not opted for the logs I should not have got the error.

### Actual result
Serverless function threw an error 
`ERROR	Error: unable to determine transport target for "../../lib/logger/transformStream"`

### System Information
I am using zsh

<img width="1517" alt="Screenshot 2023-11-03 at 11 28 11 AM" src="https://github.com/forcedotcom/cli/assets/20200740/d696e6f7-4fa3-4b0a-a0f9-2afa8d1a7bf4">

**Comment by shetzel** [comment]
@thebedroomprogrammer - the stack trace doesn't show it but I'm assuming the Logger creation is happening from other classes in `@salesforce/core` right?  It should be an easy fix to get in.  Thanks for reporting.
