### ISSUE TITLE
Using @salesforce/plugin-packaging gives warning

### ISSUE THREAD

**Issue by nwcm** [forcedotcom/cli#2555]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary

When using `sf package` commands the cli will throw warnings for the version of the plugin. 

```
 ›   Warning: Plugin @salesforce/plugin-packaging (1.27.1) differs from the 
 ›   version specified by sf (1.26.4)
 ```

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

1. run `sf plugins:install @salesforce/plugin-packaging@1.27.1`
2. run `sf package install` with a package to an org
3. notice warnings on version

### Expected result
1. Command should utilize manually installed version and not erroneously warn

### Actual result
```
 ›   Warning: Plugin @salesforce/plugin-packaging (1.27.1) differs from the 
 ›   version specified by sf (1.26.4)
 ```

### System Information

```json
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.15.9",
  "nodeVersion": "node-v18.18.2",
  "osVersion": "Linux 6.2.0-1015-azure",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.10 (core)",
    "@oclif/plugin-commands 3.0.4 (core)",
    "@oclif/plugin-help 6.0.4 (core)",
    "@oclif/plugin-not-found 3.0.2 (core)",
    "@oclif/plugin-plugins 3.9.4 (core)",
    "@oclif/plugin-search 1.0.4 (core)",
    "@oclif/plugin-update 4.1.3 (core)",
    "@oclif/plugin-version 2.0.3 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.2 (core)",
    "@oclif/plugin-which 3.0.6 (core)",
    "@salesforce/cli 2.15.9 (core)",
    "apex 2.3.20 (core)",
    "auth 2.8.25 (core)",
    "data 2.6.1 (core)",
    "deploy-retrieve 1.19.2 (core)",
    "info 2.6.51 (core)",
    "limits 2.3.41 (core)",
    "login 1.2.39 (core)",
    "marketplace 0.3.1 (core)",
    "org 2.11.5 (core)",
    "packaging 1.27.1 (user)",
    "schema 2.3.31 (core)",
    "settings 1.4.36 (core)",
    "sobject 0.2.14 (core)",
    "source 2.10.45 (core)",
    "telemetry 2.3.8 (core)",
    "templates 55.5.17 (core)",
    "trust 2.6.22 (core)",
    "user 2.3.39 (core)"
  ]
}
```

**Comment by shetzel** [comment]
The warning message is by design.  It's telling you that the version of the plugin that's installed differs from the version specified for the CLI version you have.  The version defined for the CLI was tested and went through the release candidate process whereas another version may not have gone through that same process (e.g., a plugin version that was just published).

**Comment by nwcm** [comment]
Great. 
Is there a way to suppress it?

**Comment by shetzel** [comment]
No.  Using `--json` may be an option for you.

**Comment by nwcm** [comment]
`--json` does not suppress the warning. I guess it's revert to the version or live with it.
