### ISSUE TITLE
Missing --ignore-warnings flag for 'sf project deploy validate'

### ISSUE THREAD

**Issue by githubben1** [forcedotcom/cli#2559]
### Summary
The sf validate command - `sf project deploy validate` -  doesn't seem to support the `--ignore-warnings` flag. The equivalent sfdx command has it (`force:source:deploy --checkonly --ignorewarnings`).

Using `sf project deploy start --dry-run --ignore-warnings` instead of validate is not an option either if one wants to do a quick deploy as --dry-run doesn't return the Jod ID.

### Steps To Reproduce
Run any `sf project deploy validate --ignore-warnings` with warnings, for instance `sf project deploy validate --manifest package.xml --pre-destructive-changes destructiveChangesPre.xml` referencing a metadata in destructiveChangesPre.xml that doesn't exist in the target org.

### Expected result
It should be possible to ignore warnings when doing a `sf project deploy validate`

### Actual result
Warnings are thrown, thus halting the validation.

### System Information
The flag is missing in in the latest stable rc 2.16.7 as well as all versions prior to that. Tested on both Mac and Windows.

Last version where tried:
`CLI Version:
        @salesforce/cli/2.16.7

Architecture:
        win32-x64
 
Node Version:
        node-v18.18.2

Plugin Version:
        @oclif/plugin-autocomplete 3.0.1 (core)
        @oclif/plugin-commands 3.0.5 (core)
        @oclif/plugin-help 6.0.5 (core)
        @oclif/plugin-not-found 3.0.2 (core)
        @oclif/plugin-plugins 4.0.1 (core)
        @oclif/plugin-search 1.0.5 (core)
        @oclif/plugin-update 4.1.3 (core)
        @oclif/plugin-version 2.0.4 (core)
        @oclif/plugin-warn-if-update-available 3.0.2 (core)
        @oclif/plugin-which 3.0.7 (core)
        @salesforce/cli 2.16.7 (core)
        apex 2.3.20 (core)
        auth 2.8.25 (core)
        data 2.6.1 (core)
        deploy-retrieve 1.19.3 (core)
        info 2.6.51 (core)
        limits 2.3.41 (core)
        login 1.2.40 (core)
        marketplace 0.3.2 (core)
        org 2.11.7 (core)
        schema 2.3.32 (core)
        settings 1.4.37 (core)
        sobject 0.2.14 (core)
        source 2.10.46 (core)
        telemetry 2.3.8 (core)
        templates 55.5.17 (core)
        trust 2.6.22 (core)
        user 2.3.41 (core)

OS and Version:
        Windows_NT 10.0.19045

Shell:
        cmd.exe

Root Path:
        C:\xxx\npm\node_modules\@salesforce\cli`

**Comment by tggagne** [comment]
why just validate?  Why not all the deploys since I should be able to run destructive changes multiple times and ignore already-removed items.  Destructive changes should be additive, not a delta.  After a couple years destructive changes should include /everything/ that's ever been removed so that it can be removed again if it ever slips back in.
