### ISSUE TITLE
sf project convert source not generating the output directory correctly

### ISSUE THREAD

**Issue by AlfonsoTomeCoronas** [forcedotcom/cli#2567]
### Summary
When running the command sf project convert source result in error

### Steps To Reproduce

1.  Generate a project with `sf project generate` 
2. Add any application into the applications folder
3. Run the command

### Expected result
The output directory should be generated correctly

### Actual result
The command end with an error saying: "Could not infer a metadata type" and the output directory it is created with the  package.xml and the first folder of the project. If you open that folder you will see that there is a file with the correct name but the extension of the folder has missing the last letter.

Source folder 
![Source](https://github.com/forcedotcom/cli/assets/145976309/0e2531c5-17db-40c3-9f0f-349181acf5d2)

Output folder
![Output](https://github.com/forcedotcom/cli/assets/145976309/b1c2c523-a0f1-46f8-8eb1-bc5fb03cabfe)

### System Information
I'm running it in a cmd.exe and in a azure pipeline

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.16.10",
  "nodeVersion": "node-v18.18.2",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\atome\\AppData\\Local\\sf\\client\\2.16.10-38f3e4f",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.1 (core)",
    "@oclif/plugin-commands 3.0.5 (core)",
    "@oclif/plugin-help 6.0.5 (core)",
    "@oclif/plugin-not-found 3.0.2 (core)",
    "@oclif/plugin-plugins 4.1.4 (core)",
    "@oclif/plugin-search 1.0.5 (core)",
    "@oclif/plugin-update 4.1.3 (core)",
    "@oclif/plugin-version 2.0.4 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.2 (core)",
    "@oclif/plugin-which 3.0.7 (core)",
    "@salesforce/cli 2.16.10 (core)",
    "apex 2.3.20 (core)",
    "auth 2.8.25 (core)",
    "data 2.6.1 (core)",
    "deploy-retrieve 1.19.3 (core)",
    "info 2.6.51 (core)",
    "limits 2.3.41 (core)",
    "login 1.2.40 (core)",
    "marketplace 0.3.2 (core)",
    "org 2.11.7 (core)",
    "schema 2.3.32 (core)",
    "settings 1.4.37 (core)",
    "sobject 0.2.14 (core)",
    "source 2.10.46 (core)",
    "telemetry 2.3.8 (core)",
    "templates 55.5.17 (core)",
    "trust 3.0.2 (core)",
    "user 2.3.41 (core)"
  ]
}
```

**Comment by shetzel** [comment]
This is working as designed.  You are trying to convert a file already in mdapi format to mdapi format.  That is what the `sf project convert source` does (see output of `--help`).  If you want to convert mdapi format files to source format, you need to run `sf project convert mdapi`
