### ISSUE TITLE
force:source:deploy non-code deploy to PROD requires Apex test to be run

### ISSUE THREAD

**Issue by vanortiz13** [forcedotcom/cli#257]
### Summary

Deploying permission sets  only to PROD using force:source:deploy. The command is forcing to run a test when [Salesforce docs](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy_running_tests.htm) advise that for a no code deploy to PROD, Apex tests aren't run. 

### Steps To Reproduce:

1.  Run the following command against PROD: `sfdx force:source:deploy -u exampleUser@example.com -w 33 -g -m PermissionSet --checkonly`

### Expected result

The deployment of the permission sets should have been successful.

### Actual result

Deployment fails with the following error: 
`4113 bytes written to /tmp/sdx_sourceDeploy_1576509115919.zip using 59.325ms
Deploying /tmp/sdx_sourceDeploy_1576509115919.zip...
ERROR running force:source:deploy:  INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations`

### Additional information

Running the same command but adding the -runSpecifiedTests parameter will make the deploy succeed. Another possible bug with this is that when running the command with this param, you can enter anything as the value and it the deployment will succeed. 

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.36.0 linux-x64 node-v10.15.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:
Windows 10

**Comment by rvwatch** [comment]
@vanortiz13 We've been attempting to replicate this issue and have been unable to do so. I've been able to deploy permission sets to prod orgs on both windows and mac. I'm curious if this may have been an issue that was fixed in a recent update to the CLI. Have you had an opportunity to update to the latest version of the CLI and retry this command? 

sfdx-cli/7.43.1 darwin-x64 node-v13.0.1 - for example

Thanks!

**Comment by rvwatch** [comment]
It appears an update to the latest version of the CLI has taken care of this issue.

**Comment by camisotro** [comment]
I am still experiencing this in: sfdx-cli/7.66.2-4f159a1d07 win32-x64 node-v12.13.0
I pulled all Permission Sets from a prod org and then tried to deploy one back to prod:

sfdx force:source:deploy --sourcepath d:\code\projectFolder\force-app\main\default\permissionsets\PermSetName.permissionset-meta.xml
ERROR running force:source:deploy:  INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations

**Comment by aheber** [comment]
@camisotro, I believe this is a limitation of the Metadata API and not the CLI. I don't believe you can run a deployment without running some kind of tests. This is different from ChangeSets that are aware if they contain Apex code or not.

For my deployments I will run `-l RunSpecifiedTests -r "not,a,test"` or something similar to work around the issue. You can run a limited set of tests but that limited set of tests doesn't actually have to exist, so when it hits the Apex phase it won't run anything. (I use actual classes, not test classes. Not sure if fictional classes will work)

**Comment by camisotro** [comment]
@aheber as noted upthread, what you are saying here is at odds with the MDAPI documentation: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy_running_tests.htm

It explicitly says that you can specify no test level in a Production deployment, and _"If your package doesn’t contain Apex components, no tests are run by default."_

**Comment by aheber** [comment]
@camisotro, if I'm understanding correctly that statement suggests that if the optional `testLevel` parameter of the `deploy` command is omitted then the platform will decide for itself what should happen regarding tests. Rather than being instructed.
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy.htm

I don't have things setup to test that right now but it makes sense. So a possible solution to this would be to add a "Default" option to the `--testlevel` command argument that would simply leave the `testLevel` attribute off of the deploy command and let the platform decide if it wants to run tests or not.

**Comment by camisotro** [comment]
@aheber Correct. So right now the default for `force:source:deploy` when you specify no `-l` parameter is `NoTestRun`. Whereas the default of MDAPI itself when you specify no `testLevel` is default (which permits no-test deployment of non-code). And it does not seem sfdx offers an option equivalent to this MDAPI option.

**Comment by aheber** [comment]
@clairebianchi can we get this re-opened or would you prefer a new issue specifically as a feature request?

**Comment by camisotro** [comment]
@aheber interestingly enough, `-l RunSpecifiedTests -r "skip"` in fact works. If I specify a real unit test name it will run it, but if I specify a fictional one it just ignores it and succeeds.

**Comment by aheber** [comment]
Correct, that is what I've used in the past. It would be nice to tell the system to be smart and just choose the correct path but my CI setup runs all unit tests on every deploy. I only use that trick when I need to jam something into production in an emergency and don't want the entire library of tests to execute.

**Comment by maelmonnier** [comment]
We had this problem in production today for our first deployment with the sfdx CLI. This deployment does not contain any Apex code, so no tests runs are necessary. It would be nice to change SFDX CLI documentation (https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_force_source_deploy).

**Comment by erocheleau** [comment]
> @camisotro, I believe this is a limitation of the Metadata API and not the CLI. I don't believe you can run a deployment without running some kind of tests. This is different from ChangeSets that are aware if they contain Apex code or not.
> 
> For my deployments I will run `-l RunSpecifiedTests -r "not,a,test"` or something similar to work around the issue. You can run a limited set of tests but that limited set of tests doesn't actually have to exist, so when it hits the Apex phase it won't run anything. (I use actual classes, not test classes. Not sure if fictional classes will work)

Thanks so much for this solution. I've ran into that problem today where I was just trying to deploy a LWC, but it was not letting me because of the above error, this trick of specifying tests that don't exist let me deploy without any issue.
