### ISSUE TITLE
Salesforce CLI docker image comes with unsupported Java version for Apex extension

### ISSUE THREAD

**Issue by pkozuchowski** [forcedotcom/cli#2571]
### Summary
When you open sfdx project in Dev Container using latest salesforce/cli docker image, you will see notification that Java 11 is not supported (even though it should be per docs).

### Steps To Reproduce
1) Create .devcontainers/devcontainer.json file in the root of your project with the following body:
```json
{
    "name": "Salesforce",
    "image": "salesforce/cli:latest-full",
  
    "customizations": {
        "vscode": {
            "extensions": [
                    "salesforce.salesforcedx-vscode-expanded"
            ]         
        }
    }
}
```
2) Install Docker on your machine and DevContainers extension on VS Code
3) In command pallete select: Open in Dev Container and select your project folder
4) Wait until everything loads

### Expected result
You should be able to work on the project, since per documentation Apex extension requires Java 11 or 17

### Actual result
Apex extension reports unsupported Java version
![image](https://github.com/forcedotcom/cli/assets/4470967/17fb545c-d4c2-4a27-a13a-5c8fcca59a7b)

**Comment by mshanemc** [comment]
I'll ask the vscode ext folks.

**Comment by mshanemc** [comment]
According to them, [that error](https://github.com/forcedotcom/salesforcedx-vscode/blob/3ec05ff126dd8ab8b72bfb26b6ba775c9a1efa8d/packages/salesforcedx-vscode-apex/src/requirements.ts#L70
) is thrown when the JAVA_HOME value isn’t an absolute path.   Yours seems to be, though?

Maybe what's happening
1. you have the container, which includes java
2. you also have your own java locally at C:/ProgramFiles (that's not in the container) and that's what VSCode is complaining about?

can you start the container, and try `which java` to see where it ended up, and then try the java.home setting in vscode to use that?  

as you can see, I have no idea how all this works.

**Comment by pkozuchowski** [comment]
I'm not sure if extension team fixed something, but I don't see the issue anymore :)
