### ISSUE TITLE
Getting "Could not infer a metadata type" for something other than what is being retrieved.

### ISSUE THREAD

**Issue by kaushalgautam** [forcedotcom/cli#2577]
### Summary
When retrieving custom metadata using the org browser or the Salesforce CLI (sf or sfdx), I get this strange error: Could not infer a metadata type

![image](https://github.com/forcedotcom/cli/assets/27900104/52beb38b-6bbb-44c0-ab6c-87d7355d1d8e)

It would have been understandable if I was getting an error for the metadata that I was trying to retrieve. but that's not the case as you can see in the screenshot - the error is not about the requested resource. 

### Steps To Reproduce

- I cannot provide repo link because this is a client project, I can share steps to reproduce but since the project structure won't be the same, I am not sure if that would help. The issue is with retriveing certain metadata types using the retrieve commands (from CLI or Org browser, or right click)

### Expected result
custom metadata file should have been retrieved. 

### Actual result
Got an error saying Could not infer a metadata type - for another file in my project

### System Information
CMD

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.17.14",
  "nodeVersion": "node-v20.9.0",
  "osVersion": "Windows_NT 10.0.22621",
  "rootPath": "C:\\Program Files\\sf\\client",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.1 (core)",
    "@oclif/plugin-commands 3.0.6 (core)",
    "@oclif/plugin-help 6.0.5 (core)",
    "@oclif/plugin-not-found 3.0.3 (core)",
    "@oclif/plugin-plugins 4.1.7 (core)",
    "@oclif/plugin-search 1.0.6 (core)",
    "@oclif/plugin-update 4.1.3 (core)",
    "@oclif/plugin-version 2.0.6 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.2 (core)",
    "@oclif/plugin-which 3.0.8 (core)",
    "@salesforce/cli 2.17.14 (core)",
    "apex 2.3.20 (core)",
    "auth 2.8.26 (core)",
    "data 2.6.3 (core)",
    "deploy-retrieve 1.20.0 (core)",
    "info 3.0.1 (core)",
    "limits 3.0.1 (core)",
    "login 2.0.1 (core)",
    "marketplace 1.0.2 (core)",
    "org 2.11.8 (core)",
    "schema 3.0.1 (core)",
    "settings 2.0.2 (core)",
    "sobject 0.2.15 (core)",
    "source 2.11.0 (core)",
    "telemetry 3.1.0 (core)",
    "templates 55.5.18 (core)",
    "trust 3.0.2 (core)",
    "user 2.3.42 (core)"
  ]
}
```

**Comment by mshanemc** [comment]
Does your project contain `Default_Navigation2.xml` ?  If so, where did that file come from?

It looks like the project is supposed to use the CLI's source format (because force-app, etc) but that file (and maybe others) don't have the correct file endings.    (should be `.navigationMenu-meta.xml`)

I just did what the instructions are telling you do to (go look in the registry and see what the file ending for stuff in `/navigationMenus` should be)

**Comment by mshanemc** [comment]
If you're wondering, "why won't the CLI let me retrieve things into a dirty project" it's because we have to match files you retrieve to know whether you've already got a copy. When you've got invalid files, that makes it hard.

**Comment by mshanemc** [comment]
If ALL your files are ending with `.xml` there's a good chance you should have run `sf project convert mdapi` first.

**Comment by kaushalgautam** [comment]
Hi @mshanemc - thanks for your replies and sorry for the delayed response (IST hours). Indeed it seems like there was one file that was not yet converted to source format. Strange thing is that everything else was in source format and I was not very clear about Default_Navigation2.xml so couldn't identify it. In any case, thanks for clearing my doubt. Have a happy thanksgiving! :)
