### ISSUE TITLE
Failure to do force:mdapi:convert with certain metadata types

### ISSUE THREAD

**Issue by FernandoPicazo** [forcedotcom/cli#258]
### Summary
When doing a source conversion on metadata retrieved from our Salesforce or I received the following error 

> Invalid CEN header

This appears to affect the conversion capabilities for the following metadata types.

1. AuraDefinitionBundles 
2. EmailTemplates
3. LightningComponentBundle
4. CustomTab
5. TopicsForObjects
6. Triggers
7. CustomPageWebLink
8. WorkFlow

#### Log Output
```
{"name":"sfdx","hostname":"Fernandos-MacBook-Pro-2.local","pid":14837,"log":"Org","level":60,"msg":"Invalid CEN header (bad signature)","time":"2019-12-22T04:31:12.420Z","v":0}
{"name":"sfdx","hostname":"Fernandos-MacBook-Pro-2.local","pid":14837,"log":"MdapiConvertCommand","level":60,"msg":"Invalid CEN header (bad signature)","time":"2019-12-22T04:31:12.420Z","v":0}
{"name":"sfdx","hostname":"Fernandos-MacBook-Pro-2.local","pid":14837,"log":"SourceWorkspaceAdapter","level":60,"msg":"Invalid CEN header (bad signature)","time":"2019-12-22T04:31:12.420Z","v":0}
```

### Steps To Reproduce:

1. Create metadata api project structure with package xml at root containing any of the previous types of metadata
2. Run `sfdx force:mdapi:convert -r mdapi-dir -d sfdx-out-dir`

### Expected result

Expected a full source conversion from metadata api format to sfdx source format.

### Actual result

Only partial conversion resulting in several missing metadata types.

### Additional information

Still doing some troubleshooting to verify that all of the types listed above actually failed to convert or if the only one of them was the point of failure.

For now I can manually patch my scripts to manually copy over these files since it seems none of them are actually changed through the source conversion.

For now I have verified that EmailTemplates metadata type crashes the same way.

Will update with more details

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

> sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

> @oclif/plugin-commands 1.2.3 (core)
> @oclif/plugin-help 2.2.1 (core)
> @oclif/plugin-not-found 1.2.3 (core)
> @oclif/plugin-plugins 1.7.8 (core)
> @oclif/plugin-update 1.3.9 (core)
> @oclif/plugin-warn-if-update-available 1.7.0 (core)
> @oclif/plugin-which 1.0.3 (core)
> @salesforce/sfdx-trust 3.0.5 (core)
> analytics 1.2.1 (core)
> generator 1.1.1 (core)
> salesforcedx 47.9.0 (core)
> ├─ salesforcedx-templates 47.9.0 (core)
> └─ salesforce-alm 47.10.0 (core)
> 
> sfdx-cli 7.36.0 (core)

**OS and version**:
Mac OS High Sierra v10.13.6

**Comment by clairebianchi** [comment]
@FernandoPicazo we are unable to reproduce this error. Would you please submit a case with customer support if you are still encountering this issue. They should be able to help you fix any setup issues you might have.
