### ISSUE TITLE
String replacements do not activate when creating 2GP package versions

### ISSUE THREAD

**Issue by zenibako** [forcedotcom/cli#2587]
### Summary
When creating a package version using `sf package version create`, the resulting package does not use the `replacements` property in `sfdx-project.json` to replace strings in metadata components.

### Steps To Reproduce
[Sample repository to reproduce from](https://github.com/zenibako/2gp-packaging)
1. Check out the sample repository.
2. Start a new terminal session in the project directory. Make sure you have a Dev Hub specified.
3. (Optional) Set an environment variable for `SECRET` using random text (e.g. `123`). You can do this in `bash` using `export SECRET=123`.
4. Create a new unlocked package using `sf package create --name "2GP Packaging Unlocked" --package-type Unlocked`
5. Create a new package version using `sf package version create -p "2GP Packaging Unlocked" --installation-key-bypass --wait 10 --code-coverage`

### Expected result
If the environment variable was **not set**, an error should be thrown prompting the user to set the variable for creating the package version.
If the environment variable was **set**, then the package versioning process should proceed as expected and succeed. Specified string replacements should take place and result in the metadata components including the correct strings.

### Actual result
Regardless of whether the environment variable was set, the package versioning process proceeds without doing the string replacement.

For the sample repository, I have an assert for the test which detects a merge field string to block package versioning if detected. It should fail with this error:
```
Version create.... Create version status: Error
Error (1): Multiple errors occurred: 
(1) Apex Test Failure: Class.SecretsController_TEST.getSecret: line 13, column 1 System.AssertException: Assertion Failed: Merge field value found instead of replaced value.: Same value: {{ SECRET }}
```

### System Information
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.19.8",
  "nodeVersion": "node-v18.16.1",
  "osVersion": "Darwin 23.1.0",
  "rootPath": "/Users/chandleranderson/.nvm/versions/node/v18.16.1/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.2 (core)",
    "@oclif/plugin-commands 3.0.7 (core)",
    "@oclif/plugin-help 6.0.7 (core)",
    "@oclif/plugin-not-found 3.0.4 (core)",
    "@oclif/plugin-plugins 4.1.8 (core)",
    "@oclif/plugin-search 1.0.8 (core)",
    "@oclif/plugin-update 4.1.3 (core)",
    "@oclif/plugin-version 2.0.7 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.3 (core)",
    "@oclif/plugin-which 3.0.10 (core)",
    "@salesforce/cli 2.19.8 (core)",
    "apex 3.0.6 (core)",
    "auth 3.0.7 (core)",
    "data 3.0.1 (core)",
    "deploy-retrieve 2.1.3 (core)",
    "info 3.0.3 (core)",
    "limits 3.0.2 (core)",
    "marketplace 1.0.6 (core)",
    "org 3.0.7 (core)",
    "packaging 1.27.2 (user)",
    "schema 3.0.4 (core)",
    "settings 2.0.6 (core)",
    "sobject 1.0.2 (core)",
    "source 2.11.4 (core)",
    "telemetry 3.1.2 (core)",
    "templates 56.0.2 (core)",
    "trust 3.0.4 (core)",
    "user 3.0.4 (core)",
    "@salesforce/sfdx-scanner 3.15.0 (user)"
  ]
}
```

**Comment by mshanemc** [comment]
set `SF_APPLY_REPLACEMENTS_ON_CONVERT` in the env.  Ex:

`SF_APPLY_REPLACEMENTS_ON_CONVERT=true sf package version create`...

**Comment by zenibako** [comment]
Thank you for the response, @mshanemc! Is there any plan to update the documentation to specify this capability? The conversion from source to MDAPI during packaging is opaque to the end user, so clarifying this env var's compatibility would make sense.

**Comment by jshackell-sfdc** [comment]
@zenibako : Yep, we plan to update the docs with this info. Cheers!
