### ISSUE TITLE
AVG Antivirus detects as powershell virus commands that require opening a browser window

### ISSUE THREAD

**Issue by MyOwnByte** [forcedotcom/cli#2588]
### Summary
AVG Antivirus detects as powershell virus commands that require opening a browser window (e.g. sf force org open, authorize org)

### Steps To Reproduce
- AVG free Antivirus installed
- Latest Salesforce CLI for windows 64 installed (@salesforce/cli/2.19.8 win32-x64 node-v20.9.0)
- Execute: sf force org open --target-org _AliasOfTheOrgHere_

### Expected result
Default browser opens the org

### Actual result
AVG Antivirus warning message is displayed and browser is not opened
![CLIAVG](https://github.com/forcedotcom/cli/assets/87585535/8bc7df71-0480-4d65-93a4-8b585bcd3458)

### System Information
Using windows command prompt:
sf version --verbose --json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.19.8",
  "nodeVersion": "node-v20.9.0",
  "osVersion": "Windows_NT 10.0.22621",
  "rootPath": "C:\\Users\\bt\\AppData\\Local\\sf\\client\\2.19.8-adb35cd",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.2 (core)",
    "@oclif/plugin-commands 3.0.7 (core)",
    "@oclif/plugin-help 6.0.7 (core)",
    "@oclif/plugin-not-found 3.0.4 (core)",
    "@oclif/plugin-plugins 4.1.8 (core)",
    "@oclif/plugin-search 1.0.8 (core)",
    "@oclif/plugin-update 4.1.3 (core)",
    "@oclif/plugin-version 2.0.7 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.3 (core)",
    "@oclif/plugin-which 3.0.10 (core)",
    "@salesforce/cli 2.19.8 (core)",
    "apex 3.0.6 (core)",
    "auth 3.0.7 (core)",
    "data 3.0.1 (core)",
    "deploy-retrieve 2.1.3 (core)",
    "info 3.0.3 (core)",
    "limits 3.0.2 (core)",
    "marketplace 1.0.6 (core)",
    "org 3.0.7 (core)",
    "packaging 1.27.2 (core)",
    "schema 3.0.4 (core)",
    "settings 2.0.6 (core)",
    "sobject 1.0.2 (core)",
    "source 2.11.4 (core)",
    "telemetry 3.1.2 (core)",
    "templates 56.0.2 (core)",
    "trust 3.0.4 (core)",
    "user 3.0.4 (core)"
  ]
}

### Additional information
 - This behavior doesn't happen in old versions of CLI (e.g. 2.3.8)

**Comment by mdonnalley** [comment]
@MyOwnByte This seems specific to your antivirus software. If you need a workaround for `sf org open`, you can use the `--url-only` flag to get the url and copy/paste that into the browser yourself.
