### ISSUE TITLE
Unable to perform Quick Deploy using 15 character deployment job Id

### ISSUE THREAD

**Issue by rajeswaropsera** [forcedotcom/cli#2591]
### Summary
We are getting an error while trying to run below quick deploy command using the 15 character job id. The command works fine when the 18 character id is provided. We have verified that Quick Deploy option is also visible in Salesforce under the Deployment Status page.
This behaviour is replicable from _sf_ cli version **2.11.8** onwards.
This was not the case using _sfdx_ cli command and we were able to perform quick deploy using either the 15 or 18 character job id.
`sfdx force:source:deploy -u <username> -q <job-id-15-character>`

This is breaking some of the automated pipelines we have created, and the error message that cli throws is causing confusion for all. 

### Steps To Reproduce
1. Connect CLI to the Org
2. Setup project
3. Run the below command using a successfully validated job Id.
`sf project deploy quick -o <username> -i <job-id-15-character>`

### Expected result
```
Deploy ID: <job-id-18-character>

Deployed Source
===============================================================================
| State     Name                  Type         Path
| ───────── ───────────────────── ──────────── ────────────────────────────────
|

Successfully deployed (<deployed-job-id-18-character>).
```

### Actual result
`Error (1): No job found for ID: <job-id-15-character>`

### System Information
```
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.19.8",
  "nodeVersion": "node-v19.6.0",
  "osVersion": "Darwin 23.1.0",
  "rootPath": "/opt/homebrew/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.2 (core)",
    "@oclif/plugin-commands 3.0.7 (core)",
    "@oclif/plugin-help 6.0.7 (core)",
    "@oclif/plugin-not-found 3.0.4 (core)",
    "@oclif/plugin-plugins 4.1.8 (core)",
    "@oclif/plugin-search 1.0.8 (core)",
    "@oclif/plugin-update 4.1.3 (core)",
    "@oclif/plugin-version 2.0.7 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.3 (core)",
    "@oclif/plugin-which 3.0.10 (core)",
    "@salesforce/cli 2.19.8 (core)",
    "apex 3.0.6 (core)",
    "auth 3.0.7 (core)",
    "data 3.0.1 (core)",
    "deploy-retrieve 2.1.3 (core)",
    "info 3.0.3 (core)",
    "limits 3.0.2 (core)",
    "marketplace 1.0.6 (core)",
    "org 3.0.7 (core)",
    "packaging 1.27.2 (core)",
    "schema 3.0.4 (core)",
    "settings 2.0.6 (core)",
    "sobject 1.0.2 (core)",
    "source 2.11.4 (core)",
    "telemetry 3.1.2 (core)",
    "templates 56.0.2 (core)",
    "trust 3.0.4 (core)",
    "user 3.0.4 (core)",
    "sfdmu 4.30.0 (user)"
  ]
}
```
### Additional information

- Below is the command and the error message snapshot when using _sf_ cli command
![image](https://github.com/forcedotcom/cli/assets/111528109/289858fa-9f45-4021-b060-7d307434658e)

- Salesforce Deployment Status page, showing the job id 
![image](https://github.com/forcedotcom/cli/assets/111528109/3b5c4dd3-080d-47e6-a745-224a66c73d50)

- Below is the snapshot of successful run using _sfdx_ cli command
![image](https://github.com/forcedotcom/cli/assets/111528109/ade3340f-f378-4a7f-b6d2-2781ed48ef42)

- Below is the snapshot of successful run using _sf_ cli command after providing 18 character job Id
![image](https://github.com/forcedotcom/cli/assets/111528109/76b8a8b9-350b-4d93-95cb-20734824c670)

**Comment by mdonnalley** [comment]
@rajeswaropsera I was unable to reproduce this with the following and sf 2.21.1

- clone [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc) repo
- `sf org create scratch --alias gh2591 --set-default --edition developer`
- `sf project deploy validate -d force-app` (copied 18 char id from output)
- `sf project deploy quick -i <ID>` (used first 15 chars from 18 char id in previous step)

Can you provide any more details on how I might be able to reproduce it? Thanks!

**Comment by rajeswaropsera** [comment]
@mdonnalley We are able to reproduce the same using v 2.21.1 as well, with multiple Orgs as well.
Please find below the snapshot, where first scenario command was provided with 15 character ID (incorrect response), and second with 18 character ID (expected result)

![image](https://github.com/forcedotcom/cli/assets/111528109/89f81354-285c-4304-b296-b1dc9688c7c3)

I went ahead and tried with some dummy ID as well, and looks like the error response seems to be the same (highlighted one)

![image](https://github.com/forcedotcom/cli/assets/111528109/ed0bc1c1-57e2-42ba-8f24-67299dfb7139)

**Comment by mdonnalley** [comment]
@rajeswaropsera two questions: 

1. How are you validating the deploy?
2. After validating the deploy, do you see the 18 character deploy id listed in `.sf/deploy-cache.json`?

**Comment by cristiand391** [comment]
I was able to repro this on latest sf:

1) clone dreamhouse and create scratch org
2) validate deployment:  `sf project deploy validate --async --source-dir force-app`
3) now remove the entry for this ID in the cache (`~/.sf/deploy-cache.json`) (this is what would happen in you validate a deploy but quick deploy it in different CI jobs)
4) try to quick deploy it using the ID step 2 but remove the last 3 char: `sf project deploy quick --target-org <org> --job-id <15-char-ID>`, you get the `No job found for ID` err.

If do step 4 with `force source deploy` it works with the 15-char-ID:
`sf force source deploy --target-org <org> --validateddeployrequestid <15-char-ID>`

So the bug happens when you try to quick deploy to an org with a 15-char deploy ID **and** it's not in the local cache. `plugin-deploy-retrieve` is trying to resolve the short ID (15) to the long one (18) but the API doesn't seem to require that (`plugin-source` doesn't do that).
