### ISSUE TITLE
npm dependency to be set to current version and higher

### ISSUE THREAD

**Issue by hungrypipo** [forcedotcom/cli#2592]
The two dependencies:
@salesforce/plugin-trust
@oclif/plugin-plugins

Are set to a specific version based on NodeJS LTS which is great, just need the setting to be that and higher

so instead of 
"npm": "9.9.1"

do this
"npm": "^9.9.1"

The reason is our environment is controlled so the NodeJS version will be updated for us before we have a chance to get a newer artifact to support that newer version.  This is because it's a Jenkins pipeline where we install the cli during each pipeline run so the NodeJS will update before we get a new cli artifact into our repository and update our Jenkins scripts.

**Comment by mdonnalley** [comment]
@hungrypipo Thanks for the issue - I'm going to close this though since there's already an open discussion based on your previous issue: https://github.com/forcedotcom/cli/discussions/2585
