### ISSUE TITLE
sfdx plugins: topic doesn't accept --json flag

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#26]
<!--

### Summary

Most of the sfdx commands accept --json as a flag to return command's output as json.  Except the plugins: topic

### Steps To Reproduce:

1.  sfdx plugins --json

### Expected result

json of what plugins/version are installed, whether it's via package or local code link

**Comment by clairebianchi** [comment]
@mshanemc Please fill out a feature or bug request and provide more detail

**Comment by mshanemc** [comment]
have you ever gotten an empty issue before?  I totally filled out all the feature stuff and don't know where it went

**Comment by clairebianchi** [comment]
That is super strange! No, I have never gotten an empty one before, but this repo as only been available for about a month.

**Comment by ImJohnMDaniel** [comment]
@clairebianchi and @mshanemc -- did this issue ever go anywhere?  I ran into the same need and was about to open a new feature request but this ticket came up in the suggestion box.

If the feature request already exists, please let me know.  Otherwise, I will add a new feature request.

Cheers!

**Comment by clairebianchi** [comment]
@ImJohnMDaniel can you please create a new feature request. Sorry this question got lost in the pre-holiday hubbub

**Comment by ImJohnMDaniel** [comment]
@clairebianchi -- I just opened feature request #267 

Let me know if you need anything else.

Cheers!
