### ISSUE TITLE
Unable to deploy to production

### ISSUE THREAD

**Issue by SalesforceBobLightning** [forcedotcom/cli#2601]
Summary
I can't deploy to production anymore. 

Command:

>sf project deploy start -d "./force-app/main/default/classes/x.cls" -l RunSpecifiedTests -t xTest -r -w 33 --verbose -o x-prod --ignore-errors 

Error:

> Error (1): INVALID_OPERATION: rollbackOnError option must be true on a production org

Steps To Reproduce:
Try to use `sf project deploy start`
Expected result
Being able to deploy.

Actual result

> Error (1): INVALID_OPERATION: rollbackOnError option must be true on a production org

Additional information

@salesforce/cli/2.20.6 win32-x64 node-v20.10.0

{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.20.6",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\Robert\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.2 (core)",
    "@oclif/plugin-commands 3.0.7 (core)",
    "@oclif/plugin-help 6.0.7 (core)",
    "@oclif/plugin-not-found 3.0.4 (core)",
    "@oclif/plugin-plugins 4.1.8 (core)",
    "@oclif/plugin-search 1.0.8 (core)",
    "@oclif/plugin-update 4.1.4 (core)",
    "@oclif/plugin-version 2.0.8 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.4 (core)",
    "@oclif/plugin-which 3.0.11 (core)",
    "@salesforce/cli 2.20.6 (core)",
    "apex 3.0.8 (core)",
    "auth 3.0.8 (core)",
    "data 3.0.2 (core)",
    "deploy-retrieve 2.2.0 (core)",
    "info 3.0.5 (core)",
    "limits 3.0.4 (core)",
    "marketplace 1.0.7 (core)",
    "org 3.0.9 (core)",
    "packaging 1.27.3 (core)",
    "schema 3.0.6 (core)",
    "settings 2.0.9 (core)",
    "sobject 1.0.2 (core)",
    "source 3.0.1 (core)",
    "telemetry 3.1.3 (core)",
    "templates 56.0.3 (core)",
    "trust 3.0.6 (core)",
    "user 3.0.6 (core)"
  ]
}

**Comment by SalesforceBobLightning** [comment]
Here is the full CLI version information

{
"architecture": "win32-x64",
"cliVersion": "@salesforce/cli/2.20.6",
"nodeVersion": "node-v20.10.0",
"osVersion": "Windows_NT 10.0.19045",
"rootPath": "C:\Users\Robert\AppData\Roaming\npm\node_modules\https://github.com/salesforce\cli",
"shell": "cmd.exe",
"pluginVersions": [
"@oclif/plugin-autocomplete 3.0.2 (core)",
"@oclif/plugin-commands 3.0.7 (core)",
"@oclif/plugin-help 6.0.7 (core)",
"@oclif/plugin-not-found 3.0.4 (core)",
"@oclif/plugin-plugins 4.1.8 (core)",
"@oclif/plugin-search 1.0.8 (core)",
"@oclif/plugin-update 4.1.4 (core)",
"@oclif/plugin-version 2.0.8 (core)",
"@oclif/plugin-warn-if-update-available 3.0.4 (core)",
"@oclif/plugin-which 3.0.11 (core)",
"@salesforce/cli 2.20.6 (core)",
"apex 3.0.8 (core)",
"auth 3.0.8 (core)",
"data 3.0.2 (core)",
"deploy-retrieve 2.2.0 (core)",
"info 3.0.5 (core)",
"limits 3.0.4 (core)",
"marketplace 1.0.7 (core)",
"org 3.0.9 (core)",
"packaging 1.27.3 (core)",
"schema 3.0.6 (core)",
"settings 2.0.9 (core)",
"sobject 1.0.2 (core)",
"source 3.0.1 (core)",
"telemetry 3.1.3 (core)",
"templates 56.0.3 (core)",
"trust 3.0.6 (core)",
"user 3.0.6 (core)"
]
}****

**Comment by SalesforceBobLightning** [comment]
`sf doctor` results:

=== Running all diagnostics

pass - salesforcedx plugin not installed
pass - no linked plugins
pass - [@salesforce/plugin-source] sourceApiVersion matches apiVersion
pass - [@salesforce/plugin-source] default target DevHub max apiVersion matches default target org max apiVersion
pass - [@salesforce/plugin-source] sourceApiVersion matches default target org max apiVersion
pass - using latest or latest-rc CLI version

**Comment by mdonnalley** [comment]
@SalesforceBobLightning do you see the same error if you use an older version of the CLI?

**Comment by SalesforceBobLightning** [comment]
@mdonnalley - I get the same error with `stable-rc` and `nightly` and `stable`

**Comment by SalesforceBobLightning** [comment]
@mdonnalley - how do I use an **older** version of the CLI?

**Comment by mdonnalley** [comment]
If you're using `npm`, then you can do `npm install -g @salesforce/cli@<version>`. If you're using the installers then you can use `sf update --version <version>`

`sf update --available` will list out all the recent versions of `sf`

**Comment by SalesforceBobLightning** [comment]
Thanks @mdonnalley - is there a version you'd recommend I try?

**Comment by mdonnalley** [comment]
No - I'm just trying to get a sense of whether or not this error started happening after a CLI update. If it's happening across all versions, then it's likely a server-side issue but if it only happens on 2.20.6 and newer, then it's more likely to be a CLI issue.

**Comment by SalesforceBobLightning** [comment]
@mdonnalley - OK - Where do I find a list of valid previous versions to try?

**Comment by mdonnalley** [comment]
`sf update --available`

**Comment by mshanemc** [comment]
you can't use the `--ignore-errors` flag (what the metadata API calls rollbackOnError) on a prod org

**Comment by cristiand391** [comment]
Closing as this is working as designed

> rollbackOnError: Indicates whether any failure causes a complete rollback (true) or not (false). If false, whatever actions can be performed without errors are performed, and errors are returned for the remaining actions. This parameter must be set to true if you’re deploying to a production org. The default is false.

https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_rest_deploy.htm?q=rollbackOnError

passing the flag `--ignore-errors` makes  it set `rollbackOnError` to `false`.
