### ISSUE TITLE
sf project deploy report missing objects for non-cached deploy

### ISSUE THREAD

**Issue by quinnpatrick** [forcedotcom/cli#2603]
### Summary
When a user creates a deployment that includes a CustomField and a different user runs a deploy report (using the job-id & target-org options #2300), there are objects missing from the report.  There may be other objects that are not included, but I have noticed this mainly with CustomFields.

### Steps To Reproduce
User A creates a deployment with a custom field included.
- sf project deploy validate -o **_ORG_** -x **_pkgfile_** -l RunLocalTests

User B runs the deployment report with the deployment ID from User A.
- sf project deploy report -i **_deployid_**-o **_ORG_**

### Expected result
The Validated Source section of the report should look the same no matter who created the deployment (i.e. all objects included).

### Actual result
When User A (the originator of the deploy) runs the "sf project deploy report" the custom field is included.
![image](https://github.com/forcedotcom/cli/assets/22944383/bcd3ab19-fe3c-4d9a-aa11-1e3ecee6281b)
When User B (NOT the originator of the deploy) runs the "sf project deploy report" the custom field is not included.
![image](https://github.com/forcedotcom/cli/assets/22944383/470ebd9d-f47c-4b3f-8572-762d9f97c34f)
When User B (NOT the originator of the deploy) runs the "sf project deploy report" with "--json" the custom field is included.
![image](https://github.com/forcedotcom/cli/assets/22944383/80a07aab-4dfd-4a62-be15-54776cdd5e53)

### System Information
Which shell or terminal are you using? bash - via Code Builder
```json
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.20.6",
  "nodeVersion": "node-v20.9.0",
  "osVersion": "Linux 4.14.255-322-265.538.amzn2.x86_64",
  "rootPath": "/home/codebuilder/.local/share/sf/client/2.20.6-336b6b0",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.2 (core)",
    "@oclif/plugin-commands 3.0.7 (core)",
    "@oclif/plugin-help 6.0.7 (core)",
    "@oclif/plugin-not-found 3.0.4 (core)",
    "@oclif/plugin-plugins 4.1.8 (core)",
    "@oclif/plugin-search 1.0.8 (core)",
    "@oclif/plugin-update 4.1.4 (core)",
    "@oclif/plugin-version 2.0.8 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.4 (core)",
    "@oclif/plugin-which 3.0.11 (core)",
    "@salesforce/cli 2.20.6 (core)",
    "apex 3.0.8 (core)",
    "auth 3.0.8 (core)",
    "data 3.0.2 (core)",
    "deploy-retrieve 2.2.0 (core)",
    "info 3.0.5 (core)",
    "limits 3.0.4 (core)",
    "marketplace 1.0.7 (core)",
    "org 3.0.9 (core)",
    "packaging 1.27.3 (core)",
    "schema 3.0.6 (core)",
    "settings 2.0.9 (core)",
    "sobject 1.0.2 (core)",
    "source 3.0.1 (core)",
    "telemetry 3.1.3 (core)",
    "templates 56.0.3 (core)",
    "trust 3.0.6 (core)",
    "user 3.0.6 (core)",
    "sfdx-plugin-prettier 1.0.5 (user)",
    "sfdx-plugin-source-read 1.2.0 (user)"
  ]
}
```

**Comment by iowillhoit** [comment]
Hey @quinnpatrick, It looks like this is happening because the CustomField is being `Created` and does not exist on User B's machine. I would guess that we are resolving the `Path` for results coming back from the server and omitting them if they are not found locally. We could handle this better, I'll get a ticket created. Thanks for submitting this!
