### ISSUE TITLE
SFDX CLI Docker: ModuleLoadError: [MODULE_NOT_FOUND] require failed to load 

### ISSUE THREAD

**Issue by limlynette** [forcedotcom/cli#2609]
### Summary

The latest sfdx cli docker image salesforce/cli:latest-full is encountering the error "ModuleLoadError: [MODULE_NOT_FOUND] require failed to load " during sf plugins installation.

### Steps To Reproduce
1. Use latest docker image sfdx cli "salesforce/cli:latest-full"
2. Run command "sf plugins install packaging"

### Expected result

> Successfully validated digital signature for @salesforce/plugin-packaging.
Finished digital signature check.
Installing plugin packaging@latest... yarn add v1.22.21
Installing plugin packaging@latest... info No lockfile found.Installing plugin packaging@latest... [1/4] Resolving packages...Installing plugin packaging@latest... [2/4] Fetching packages...Installing plugin packaging@latest... [3/4] Linking dependencies...Installing plugin packaging@latest... [4/4] Building fresh packages...Installing plugin packaging@latest... success ....
Done in 45.06s.Installing plugin packaging@latest... Refreshing user plugins...Installing plugin packaging@latest... installed v1.27.8
Successfully installed @salesforce/plugin-packaging v1.27.8

### Actual result

> Successfully validated digital signature for @salesforce/plugin-packaging.
Finished digital signature check.
Installing plugin packaging@latest... yarn add v1.22.21
Installing plugin packaging@latest... info No lockfile found.Installing plugin packaging@latest... [1/4] Resolving packages...Installing plugin packaging@latest... [2/4] Fetching packages...Installing plugin packaging@latest... [3/4] Linking dependencies...Installing plugin packaging@latest... [4/4] Building fresh packages...Installing plugin packaging@latest... success ...
Done in 14.70s.Installing plugin packaging@latest... Refreshing user plugins...Installing plugin packaging@latest... installed v1.27.9
Successfully installed @salesforce/plugin-packaging v1.27.9
 ›   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load 
 ›   /root/.local/share/sf/node_modules/@salesforce/plugin-packaging/lib/comman
 ›   ds/package/version/create.js: Cannot find module 'glob'
 ›   Require stack:
 ›   - /root/.local/share/sf/node_modules/@salesforce/plugin-packaging/node_mod
 ›   ules/@salesforce/packaging/lib/package/packageProfileApi.js
 ›   - /root/.local/share/sf/node_modules/@salesforce/plugin-packaging/node_mod
 ›   ules/@salesforce/packaging/lib/package/packageVersionCreate.js
 ›   - /root/.local/share/sf/node_modules/@salesforce/plugin-packaging/node_mod
 ›   ules/@salesforce/packaging/lib/package/packageConvert.js
 ›   - /root/.local/share/sf/node_modules/@salesforce/plugin-packaging/node_mod
 ›   ules/@salesforce/packaging/lib/package/package.js
 ›   - /root/.local/share/sf/node_modules/@salesforce/plugin-packaging/node_mod
 ›   ules/@salesforce/packaging/lib/package/index.js
 ›   - /root/.local/share/sf/node_modules/@salesforce/plugin-packaging/node_mod
 ›   ules/@salesforce/packaging/lib/exported.js
 ›   - /root/.local/share/sf/node_modules/@salesforce/plugin-packaging/lib/comm
 ›   ands/package/version/create.js
 ›   - /usr/local/lib/nodejs/lib/node_modules/@salesforce/cli/node_modules/@ocl
 ›   if/core/lib/module-loader.js
 ›   - /usr/local/lib/nodejs/lib/node_modules/@salesforce/cli/node_modules/@ocl
 ›   if/core/lib/help/index.js
 ›   - /usr/local/lib/nodejs/lib/node_modules/@salesforce/cli/node_modules/@ocl
 ›   if/core/lib/flags.js
 ›   - /usr/local/lib/nodejs/lib/node_modules/@salesforce/cli/node_modules/@ocl
 ›   if/core/lib/cli-ux/styled/table.js
 ›   - /usr/local/lib/nodejs/lib/node_modules/@salesforce/cli/node_modules/@ocl
 ›   if/core/lib/cli-ux/styled/index.js
 ›   - /usr/local/lib/nodejs/lib/node_modules/@salesforce/cli/node_modules/@ocl
 ›   if/core/lib/cli-ux/index.js
 ›   - /usr/local/lib/nodejs/lib/node_modules/@salesforce/cli/node_modules/@ocl
 ›   if/core/lib/index.js
 ›   Code: MODULE_NOT_FOUND

### System Information

> {
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.23.0",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Linux 5.15.0-1050-aws",
  "rootPath": "/usr/local/lib/nodejs/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.3 (core)",
    "@oclif/plugin-commands 3.0.7 (core)",
    "@oclif/plugin-help 6.0.8 (core)",
    "@oclif/plugin-not-found 3.0.5 (core)",
    "@oclif/plugin-plugins 4.1.10 (core)",
    "@oclif/plugin-search 1.0.8 (core)",
    "@oclif/plugin-update 4.1.5 (core)",
    "@oclif/plugin-version 2.0.9 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.6 (core)",
    "@oclif/plugin-which 3.0.12 (core)",
    "@salesforce/cli 2.23.0 (core)",
    "apex 3.0.9 (core)",
    "auth 3.0.12 (core)",
    "data 3.0.6 (core)",
    "deploy-retrieve 2.2.6 (core)",
    "info 3.0.8 (core)",
    "limits 3.0.6 (core)",
    "marketplace 1.0.11 (core)",
    "org 3.1.2 (core)",
    "packaging 1.27.9 (core)",
    "schema 3.0.8 (core)",
    "settings 2.0.9 (core)",
    "sobject 1.0.6 (core)",
    "source 3.0.6 (core)",
    "telemetry 3.1.6 (core)",
    "templates 56.0.4 (core)",
    "trust 3.2.0 (core)",
    "user 3.1.1 (core)"
  ]
}

**Comment by mshanemc** [comment]
yeah, we're doing a patch for that--it's not just affecting the docker image

**Comment by iowillhoit** [comment]
Thanks @limlynette, this is a known issue. We will be starting a patch of `latest-rc` and `latest` within the hour to fix it. 

I do want to point out that within the past few weeks we switched to to bundling `plugin-packaging` with the CLI. You will no longer need to manually install it, it should be available after installing the CLI

**Comment by gadamson-upco** [comment]
I am also seeing this issue on a CI server when trying to check for whether a package is installed in a target org.
Failing command is `sf package installed list --json`

It is using the tarball sf package, details as follows:
```
@salesforce/cli/2.21.7 linux-x64 node-v20.10.0
community 3.0.5
packaging 1.27.9
```

Downgrading to 2.20.6 did not resolve the issue. Also tried specifically installing version 1.27.7 of the packaging plugin (these versions are what I had running successfully on my local machine).

Interestingly, there are no errors for me locally, even after updating to the same same versions (but installed via npm):
```
@salesforce/cli/2.21.7 darwin-arm64 node-v20.10.0
community 3.0.5
packaging 1.27.9
```

Any workarounds while waiting for the fix? Downgrade further?

**Comment by gadamson-upco** [comment]
Never mind, I see a new 1.27.10 of packaging and the issue seems to be resolved 👍

**Comment by iowillhoit** [comment]
Ok this should be fixed now. Both `latest` (`2.21.8`) and `latest-rc` (`2.22.7`) have been patched
