### ISSUE TITLE
Unable to specify config for linter

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#261]
### Summary

When running sfdx force:lightning:lint and trying to specify custom eslint config, it tries to to fetch config from folder that is being scanned.

### Steps To Reproduce:

`sfdx force:lightning:lint --config=./.eslintrc.js ./myns/main/default/aura`

### Actual result

```
Applying custom rules from .eslintrc.js
ERROR running force:lightning:lint:  Cannot find module 'myns/main/default/aura/.eslintrc.js'
```

### Additional information

Putting config into aura folder doesn't work either

Versions:

`sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3`
```
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.8
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)

sfdx-cli 7.36.0 (core)
```

`Catalina 10.15.2 (19C57)`

**Comment by sjurgis** [comment]
Removing .js doesn't work either.

**Comment by clairebianchi** [comment]
@sjurgis thank you for reaching out. @ntotten can you please take a look

**Comment by cristiand391** [comment]
closing this since the `force:lightning:lint` command no longer exists.
