### ISSUE TITLE
Unable to use salesforce/cli docker slim image

### ISSUE THREAD

**Issue by carlosabella** [forcedotcom/cli#2613]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
I am trying to use the slim docker image from docker hub ([2.23.4-slim](https://hub.docker.com/layers/salesforce/cli/2.23.4-slim/images/sha256-fe368110ee30a3f4ce9df2f8fc72d45f21df597a2dfda37020741a9e7cf7cf1f?context=explore))

And when I execute simply: sf -v 
I get this error: /usr/local/sf/bin/sf: line 45:    21 Segmentation fault      "$NODE" "$DIR/run" "$@"

I can't use it in my daily work. 

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

Having docker engine installed in Mac OS Sonoma 14.2
docker pull salesforce/cli:2.23.4-slim
docker run --name salesforce -it salesforce/cli:2.23.4-slim

In the container terminal 
root@0dcf76c916aa:/# 
Write sf -v

### Expected result

@salesforce/cli/2.21.8 darwin-x64 node-v20.10.0

### Actual result

/usr/local/sf/bin/sf: line 45:    21 Segmentation fault      "$NODE" "$DIR/run" "$@"

### System Information

I am using Mac OS Sonoma 14.2. Terminal is zsh

This does not apply because I can't install the cli in the docker image

**Comment by iowillhoit** [comment]
Interesting, we have not changed in that Dockerfile for a long time. Are you seeing this on any other Docker-slim versions? The "verify" step for `2.23.4` just passed yesterday https://github.com/salesforcecli/cli/actions/runs/7250635676/job/19751675906#step:3:25

**Comment by carlosabella** [comment]
Thanks for answering @iowillhoit . I have just retry this (just in case):
docker pull salesforce/cli:2.23.4-slim
docker run -it salesforce/cli:2.23.4-slim
Once I am in the container terminal I execute:
sf version 
And I get the error: /usr/local/sf/bin/sf: line 45:    21 Segmentation fault      "$NODE" "$DIR/run" "$@"

Certainly I can see the "verify" step passes. And the command: java --version works perfectly. 

Any further idea? Thanks for helping

**Comment by cristiand391** [comment]
@carlosabella 

I'm on macos sonomia 14.2 too and can't repro this:
<img width="1777" alt="Screenshot 2024-01-02 at 11 24 33" src="https://github.com/forcedotcom/cli/assets/6853656/b9567eb9-4fb1-4d65-800d-86211724f304">

does the previous slim images work for you?

**Comment by carlosabella** [comment]
@cristiand391 Thanks for the help. 
Yes it happens with previous images also. Today I could dig a bit more and I found the following:
The error says: 
![image](https://github.com/forcedotcom/cli/assets/4191627/20426f97-010a-4d39-99f0-3c368d980eea)
So I checked the path: /usr/local/sf/bin/sf 
And I opened the "sf" file. What I found is the following: 

`#!/usr/bin/env bash
set -e
echoerr() { echo "$@" 1>&2; }

get_script_dir () {
  SOURCE="${BASH_SOURCE[0]}"
  # While $SOURCE is a symlink, resolve it
  while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$( readlink "$SOURCE" )"
    # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  echo "$DIR"
}
DIR=$(get_script_dir)
CLI_HOME=$(cd && pwd)
XDG_DATA_HOME=${XDG_DATA_HOME:="$CLI_HOME/.local/share"}
CLIENT_HOME=${SF_OCLIF_CLIENT_HOME:=$XDG_DATA_HOME/sf/client}
BIN_PATH="$CLIENT_HOME/bin/sf"
if [ -z "$SF_REDIRECTED" ] && [ -x "$BIN_PATH" ] && [[ ! "$DIR/sf" -ef "$BIN_PATH" ]]; then
  if [ "$DEBUG" == "*" ]; then
    echoerr "$BIN_PATH" "$@"
  fi
  SF_BINPATH="$BIN_PATH" SF_REDIRECTED=1 "$BIN_PATH" "$@"
else
  export SF_BINPATH=${SF_BINPATH:="$DIR/sf"}
  if [ -x "$(command -v "$XDG_DATA_HOME/oclif/node/node-custom")" ]; then
    NODE="$XDG_DATA_HOME/oclif/node/node-custom"
  elif [ -x "$(command -v "$DIR/node")" ]; then
    NODE="$DIR/node"
  elif [ -x "$(command -v "$XDG_DATA_HOME/oclif/node/node-20.10.0")" ]; then
    NODE="$XDG_DATA_HOME/oclif/node/node-20.10.0"
  elif [ -x "$(command -v node)" ]; then
    NODE=node
  else
    echoerr 'Error: node is not installed.' >&2
    exit 1
  fi
  if [ "$DEBUG" == "*" ]; then
    echoerr SF_BINPATH="$SF_BINPATH" "$NODE" "$DIR/run" "$@"
  fi
  "$NODE" "$DIR/run" "$@"
fi`

What the command is showing as output is precisely what is in the last line of the code. But I can't understand why the execution of the command is getting to that line. 

Anyone can help here? 

Thanks a lot.

**Comment by carlosabella** [comment]
Hi again @iowillhoit @cristiand391,
I found the problem. 

The problem was not in the image or the sf cli, the problem was in docker engine in MAC. There is a bug in Docker engine for mac. There are some issues with the "Virtualization Framework". I had it enabled by default. I had to change the file sharing implementation for containers and uncheck the Virtualization Framework. After that, it worked perfectly. 
![image](https://github.com/forcedotcom/cli/assets/4191627/3b8131ae-cfbc-4cff-a2f0-31c563d0a753)

Here is the issue in docker: https://github.com/docker/for-mac/issues/6824
Here is an article in stackoverflow: https://stackoverflow.com/questions/76735062/segmentation-fault-in-node-js-application-running-in-docker

Thank you very much for the help and sorry for the inconvenience due to it wasn't an "sf cli" problem.

You can close the issue.
