### ISSUE TITLE
--edition partner-developer restricted pick list field error

### ISSUE THREAD

**Issue by Kevmo92** [forcedotcom/cli#2614]
### Summary

Trying to create a partner developer org using the --edition flag.

### Steps To Reproduce

This command will create an org:

```bash
sf org create scratch --edition developer
```

This command will throw an error:

```bash
sf org create scratch --edition partner-developer
Error (1): Edition: bad value for restricted picklist field: partner-developer
```

### Expected result

A partner developer org is created

### Actual result

An error is thrown:

```
Error (1): Edition: bad value for restricted picklist field: partner-developer
```

### System Information

```json
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.21.8",
  "nodeVersion": "node-v18.18.2",
  "osVersion": "Darwin 22.6.0",
  "rootPath": "/Users/kevinwatson/.fnm/node-versions/v18.18.2/installation/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.2 (core)",
    "@oclif/plugin-commands 3.0.7 (core)",
    "@oclif/plugin-help 6.0.7 (core)",
    "@oclif/plugin-not-found 3.0.4 (core)",
    "@oclif/plugin-plugins 4.1.9 (core)",
    "@oclif/plugin-search 1.0.8 (core)",
    "@oclif/plugin-update 4.1.4 (core)",
    "@oclif/plugin-version 2.0.8 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.5 (core)",
    "@oclif/plugin-which 3.0.11 (core)",
    "@salesforce/cli 2.21.8 (core)",
    "apex 3.0.8 (core)",
    "auth 3.0.10 (core)",
    "data 3.0.5 (core)",
    "deploy-retrieve 2.2.3 (core)",
    "info 3.0.7 (core)",
    "limits 3.0.5 (core)",
    "marketplace 1.0.10 (core)",
    "org 3.1.1 (core)",
    "packaging 1.27.2 (user)",
    "schema 3.0.8 (core)",
    "settings 2.0.9 (core)",
    "signups 1.4.22 (user)",
    "sobject 1.0.5 (core)",
    "source 3.0.3 (core)",
    "telemetry 3.1.4 (core)",
    "templates 56.0.4 (core)",
    "trust 3.1.2 (core)",
    "user 3.1.0 (core)"
  ]
}
```

### Additional information

Your own --help shows that partner-developer is a valid option.

```bash
DEFINITION FILE OVERRIDE FLAGS
  -e, --edition=<option>     Salesforce edition of the scratch org. Overrides the value of the "edition" option in the definition file, if set.
                             <options: developer|enterprise|group|professional|partner-developer|partner-enterprise|partner-group|partner-professional>
```

I'm able to create a partner developer org using the -f so it doesn't seem like a permissions issue:

```json
{
  "orgName": "test",
  "country": "US",
  "edition": "Partner Developer",
  "description": "Test",
  "hasSampleData": true,
  "language": "English",
  "settings": {
    "apexSettings": {
      "enableCompileOnDeploy": false,
      "enableAggregateCodeCoverageOnly": true
    },
    "chatterSettings": {
      "enableChatter": true
    },
    "currencySettings": {
      "enableMultiCurrency": true
    },
    "languageSettings": {
      "enableTranslationWorkbench": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    }
  },
  "features": []
}
```

**Comment by Kevmo92** [comment]
Our DevHub is a PBO, which is why I'm able to create a partner developer edition org with the `-f` flag. This doc https://developer.salesforce.com/docs/atlas.en-us.pkg1_dev.meta/pkg1_dev/isv_partner_scratch_org_editions.htm mentions I should be able to use this edition. I only get the error when using the `--edition` flag.

**Comment by iowillhoit** [comment]
Hey @Kevmo92, this does look like a bug. That error message is coming back from the server, you can see the POST if you run the command with the `--dev-debug` flag. 

If I clone `plugin-org`, change [that flag value](https://github.com/salesforcecli/plugin-org/blob/db6a8e9f4bd5ee38b3f85ac15fcf5431122febca/src/commands/org/create/scratch.ts#L77) to `partner developer` (no hyphen), build it with `yarn build`, then run `../plugin-org/bin/run.js org create scratch --edition "partner developer"`, I get a completely different error message:

> You don't have permission to create Partner Edition organizations

This is expected since my current dev-hub is not configured for partner orgs, but at least the edition validation is satisfied. I'll get a ticket created and we'll get it resolved. Thanks for reporting it!

**Comment by Kevmo92** [comment]
@iowillhoit Thanks for taking a look! I need to remember the `--dev-debug` flag in the future, that's a super helpful flag.

**Comment by cristiand391** [comment]
Thanks for reporting this, we got it fixed in sf 2.23.20 (current RC), will be promoted to stable next week.

**Comment by shetzel** [comment]
This is now in sf v2.23.20, the current production CLI.

**Comment by Kevmo92** [comment]
@shetzel @cristiand391 @iowillhoit Thank you 🚀
