### ISSUE TITLE
Unable to push Lightning Tab profile settings

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#263]
### Summary

This is intermittent and seems to happen much more often in CI rather than on dev machine for some reason.
Once in a while when pushing source to a fresh org, error below appears.
**Doesn't happen with permsets tho.**

### Steps To Reproduce:

1.  Create lightning tab at `main/default/tabs/WelcomeLightning.tab-meta.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<CustomTab xmlns="http://soap.sforce.com/2006/04/metadata">
    <auraComponent>WelcomeTab</auraComponent>
    <label>Welcome</label>
    <description>Provides an overview of the product-name functionality, as well as links to the documentation.</description>
    <mobileReady>false</mobileReady>
    <motif>Custom51: Apple</motif>
</CustomTab>
```
2. Add lightning tab to profile:
```
    <tabVisibilities>
        <tab>WelcomeLightning</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
```

Or ...

```
    <tabVisibilities>
        <tab>WelcomeLightning</tab>
        <visibility>Hidden</visibility>
    </tabVisibilities>
```

### Expected result

Source gets pushed.

### Actual result

`myns/main/default/profiles/Some User.profile-meta.xml    You can't edit tab settings for WelcomeLightning, as it's not a valid tab. (0:0)`

### Additional information

Has been happening for quite a few releases if not months.
Latest Catalina & sfdx

**Comment by clairebianchi** [comment]
@sjurgis Is this only happening with CI or in development as well. Can you share your scratch def file?

**Comment by sjurgis** [comment]
CI Config:
```
{
    "orgName": "travis_ciorg",
    "edition": "Developer",
    "hasSampleData": "false",
    "features": ["AuthorApex"],
    "settings": {
        "orgPreferenceSettings": {
            "s1DesktopEnabled": true,
            "s1EncryptedStoragePref2": false,
            "chatterEnabled": true
        },
        "accountSettings": {
            "enableAccountTeams": true
        },
        "opportunitySettings": {
            "enableOpportunityTeam": true
        }
    },
    "adminEmail": "[redacted]@gmail.com"
}
```
Dev
```
{
    "orgName": "Some random generated name",
    "edition": "Developer",
    "hasSampleData": "true",
    "features": ["AuthorApex"],
    "settings": {
        "orgPreferenceSettings": {
            "s1DesktopEnabled": true,
            "s1EncryptedStoragePref2": false,
            "chatterEnabled": true
        },
        "accountSettings" : {
            "enableAccountTeams" : true
        },
        "opportunitySettings" : {
            "enableOpportunityTeam" : true
        }
    },
    "adminEmail": "[redacted]@gmail.com"
}
```

So the only differences are hasSampleData, email and name (tends to stay same whereas dev org names are randomized).

TBH I don't think it's a bug with CLI itself but with Metadata API. Could be like labels are getting confused with API names or smth.

**Comment by clairebianchi** [comment]
@sjurgis are you using source:deploy or mdapi:deploy?

**Comment by sjurgis** [comment]
@clairebianchi  sorry if misleading, but I'm using `force:source:push`.

**Comment by clairebianchi** [comment]
@sjurgis thank you. I'll have someone dig into it.

**Comment by clairebianchi** [comment]
Hi, I have passed the information on the MDAPI team and they are going to take a look at the issue

**Comment by clairebianchi** [comment]
Hi, This is a bug with the MDAPI team. They have added it to their backlog and are working on prioritizing it. They do not track their work in Github so I am going to close this Issue here.
