### ISSUE TITLE
Incosistent sharingModel with SharingRule deployment

### ISSUE THREAD

**Issue by marcosboger** [forcedotcom/cli#2639]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
When deploying changes in SharingModel of an Object but also with changes in sharingRules which causes recalculation, deploy goes through even though the SharingModel changes are not applied.

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

Repo to reproduce: https://github.com/marcosboger/SFDX-Issue

1- First deploy the metadata in the "deploying" folder on any Org of your choice. The CLI.txt files contain the deployment command. It should change the sharingModel for User object and also add a Sharing Rule criteria based to User also. It should go through fine.
2- Try to deploy the metadata in the "deployingWithBug" folder on that same Org. The CLI.txt also contains the command. The sharingRule deletion will happen, but the sharingModel change won't go through.

Extra step: If you remove the --predestructivechanges from the command in step 2, the sharingModel change will go through normally, making it seem like the problem happens if there are sharingRule recalculation and sharingModel changes in the same deployment

### Expected result
Either the sharingModel change should go through also and deploy finish with success or the sharingModel change shouldn't go through, deploy is rolled back and finishes with failure.

### Actual result
Even though sharingModel change doesn't go through, deploy finishes with success, which is inconsistent behavior

### System Information

Command Prompt or Bash

I've tested in different CLI versions and didn't find any that would work. Currently using the one below

```json
{
"cliVersion": "@salesforce/cli/1.69.0",
"architecture": "wsl-x64",
"nodeVersion": "node-v21.5.0",
"pluginVersions": [
"@oclif/plugin-autocomplete 2.1.4 (core)",
"@oclif/plugin-commands 2.2.10 (core)",
"@oclif/plugin-help 5.2.7 (core)",
"@oclif/plugin-not-found 2.3.21 (core)",
"@oclif/plugin-plugins 2.3.2 (core)",
"@oclif/plugin-search 0.0.14 (core)",
"@oclif/plugin-update 3.1.6 (core)",
"@oclif/plugin-version 1.2.1 (core)",
"@oclif/plugin-warn-if-update-available 2.0.30 (core)",
"@oclif/plugin-which 2.2.16 (core)",
"apex 2.2.2 (core)",
"auth 2.7.7 (core)",
"data 2.3.6 (core)",
"deploy-retrieve 1.8.2 (core)",
"env 2.1.2 (core)",
"functions 1.21.2 (core)",
"info 2.5.1 (core)",
"limits 2.3.8 (core)",
"login 1.2.2 (core)",
"org 2.4.6 (core)",
"schema 2.3.3 (core)",
"settings 1.4.2 (core)",
"sobject 0.1.8 (core)",
"telemetry 2.1.3 (core)",
"templates 55.4.4 (core)",
"trust 2.4.4 (core)",
"user 2.3.3 (core)"
],
"osVersion": "Linux 5.15.133.1-microsoft-standard-WSL2",
"shell": "bash",
"rootPath": "/mnt/c/Users/boger.md/AppData/Local/Programs/sfdx/sf"
}
```

**Comment by marcosboger** [comment]
{
  "cliVersion": "@salesforce/cli/1.69.0",
  "architecture": "wsl-x64",
  "nodeVersion": "node-v21.5.0",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.1.4 (core)",
    "@oclif/plugin-commands 2.2.10 (core)",
    "@oclif/plugin-help 5.2.7 (core)",
    "@oclif/plugin-not-found 2.3.21 (core)",
    "@oclif/plugin-plugins 2.3.2 (core)",
    "@oclif/plugin-search 0.0.14 (core)",
    "@oclif/plugin-update 3.1.6 (core)",
    "@oclif/plugin-version 1.2.1 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.30 (core)",
    "@oclif/plugin-which 2.2.16 (core)",
    "apex 2.2.2 (core)",
    "auth 2.7.7 (core)",
    "data 2.3.6 (core)",
    "deploy-retrieve 1.8.2 (core)",
    "env 2.1.2 (core)",
    "functions 1.21.2 (core)",
    "info 2.5.1 (core)",
    "limits 2.3.8 (core)",
    "login 1.2.2 (core)",
    "org 2.4.6 (core)",
    "schema 2.3.3 (core)",
    "settings 1.4.2 (core)",
    "sobject 0.1.8 (core)",
    "telemetry 2.1.3 (core)",
    "templates 55.4.4 (core)",
    "trust 2.4.4 (core)",
    "user 2.3.3 (core)"
  ],
  "osVersion": "Linux 5.15.133.1-microsoft-standard-WSL2",
  "shell": "bash",
  "rootPath": "/mnt/c/Users/boger.md/AppData/Local/Programs/sfdx/sf"
}

**Comment by marcosboger** [comment]
### System Information

Command Prompt or Bash

I've tested in different CLI versions and didn't find any that would work. Currently using the one below

```json
{
"cliVersion": "@salesforce/cli/1.69.0",
"architecture": "wsl-x64",
"nodeVersion": "node-v21.5.0",
"pluginVersions": [
"@oclif/plugin-autocomplete 2.1.4 (core)",
"@oclif/plugin-commands 2.2.10 (core)",
"@oclif/plugin-help 5.2.7 (core)",
"@oclif/plugin-not-found 2.3.21 (core)",
"@oclif/plugin-plugins 2.3.2 (core)",
"@oclif/plugin-search 0.0.14 (core)",
"@oclif/plugin-update 3.1.6 (core)",
"@oclif/plugin-version 1.2.1 (core)",
"@oclif/plugin-warn-if-update-available 2.0.30 (core)",
"@oclif/plugin-which 2.2.16 (core)",
"apex 2.2.2 (core)",
"auth 2.7.7 (core)",
"data 2.3.6 (core)",
"deploy-retrieve 1.8.2 (core)",
"env 2.1.2 (core)",
"functions 1.21.2 (core)",
"info 2.5.1 (core)",
"limits 2.3.8 (core)",
"login 1.2.2 (core)",
"org 2.4.6 (core)",
"schema 2.3.3 (core)",
"settings 1.4.2 (core)",
"sobject 0.1.8 (core)",
"telemetry 2.1.3 (core)",
"templates 55.4.4 (core)",
"trust 2.4.4 (core)",
"user 2.3.3 (core)"
],
"osVersion": "Linux 5.15.133.1-microsoft-standard-WSL2",
"shell": "bash",
"rootPath": "/mnt/c/Users/boger.md/AppData/Local/Programs/sfdx/sf"
}
```

**Comment by marcosboger** [comment]
> Hello @marcosboger 👋
> 
> It looks like you're using an outdated version of Salesforce CLI. `sf` (v1) is in "maintenance mode" as of July 12, 2023. We highly recommend you move from `sf` (v1) to `sf` (v2) ASAP.
> 
> Moving to `sf` (v2) is easy and takes just two commands. Find all the information [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm).
> 
> After you move to the latest version of `sf` (v2), run your command again and provide the output of `sf version --verbose --json`.

```json
{
"cliVersion": "@salesforce/cli/1.69.0",
"architecture": "wsl-x64",
"nodeVersion": "node-v21.5.0",
"pluginVersions": [
"@oclif/plugin-autocomplete 2.1.4 (core)",
"@oclif/plugin-commands 2.2.10 (core)",
"@oclif/plugin-help 5.2.7 (core)",
"@oclif/plugin-not-found 2.3.21 (core)",
"@oclif/plugin-plugins 2.3.2 (core)",
"@oclif/plugin-search 0.0.14 (core)",
"@oclif/plugin-update 3.1.6 (core)",
"@oclif/plugin-version 1.2.1 (core)",
"@oclif/plugin-warn-if-update-available 2.0.30 (core)",
"@oclif/plugin-which 2.2.16 (core)",
"apex 2.2.2 (core)",
"auth 2.7.7 (core)",
"data 2.3.6 (core)",
"deploy-retrieve 1.8.2 (core)",
"env 2.1.2 (core)",
"functions 1.21.2 (core)",
"info 2.5.1 (core)",
"limits 2.3.8 (core)",
"login 1.2.2 (core)",
"org 2.4.6 (core)",
"schema 2.3.3 (core)",
"settings 1.4.2 (core)",
"sobject 0.1.8 (core)",
"telemetry 2.1.3 (core)",
"templates 55.4.4 (core)",
"trust 2.4.4 (core)",
"user 2.3.3 (core)"
],
"osVersion": "Linux 5.15.133.1-microsoft-standard-WSL2",
"shell": "bash",
"rootPath": "/mnt/c/Users/boger.md/AppData/Local/Programs/sfdx/sf"
}
```

**Comment by marcosboger** [comment]
### System Information

Command Prompt or Bash

I've tested in different CLI versions and didn't find any that would work. Currently using the one below

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.21.8",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\boger.md\\AppData\\Local\\sf\\client\\2.21.8-474381d",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.2 (core)",
    "@oclif/plugin-commands 3.0.7 (core)",
    "@oclif/plugin-help 6.0.7 (core)",
    "@oclif/plugin-not-found 3.0.4 (core)",
    "@oclif/plugin-plugins 4.1.9 (core)",
    "@oclif/plugin-search 1.0.8 (core)",
    "@oclif/plugin-update 4.1.4 (core)",
    "@oclif/plugin-version 2.0.8 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.5 (core)",
    "@oclif/plugin-which 3.0.11 (core)",
    "@salesforce/cli 2.21.8 (core)",
    "apex 3.0.8 (core)",
    "auth 3.0.10 (core)",
    "data 3.0.5 (core)",
    "deploy-retrieve 2.2.3 (core)",
    "info 3.0.7 (core)",
    "limits 3.0.5 (core)",
    "marketplace 1.0.10 (core)",
    "org 3.1.1 (core)",
    "packaging 1.27.10 (core)",
    "schema 3.0.8 (core)",
    "settings 2.0.9 (core)",
    "signups 1.4.22 (user)",
    "sobject 1.0.5 (core)",
    "source 3.0.3 (core)",
    "telemetry 3.1.4 (core)",
    "templates 56.0.4 (core)",
    "trust 3.1.2 (core)",
    "user 3.1.0 (core)"
  ]
}
```

**Comment by marcosboger** [comment]
### System Information

Command Prompt or Bash

I've tested in different CLI versions and didn't find any that would work. Currently using the one below

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.22.7",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\boger.md\\AppData\\Local\\sf\\client\\2.22.7-453215f",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.3 (core)",
    "@oclif/plugin-commands 3.0.7 (core)",
    "@oclif/plugin-help 6.0.8 (core)",
    "@oclif/plugin-not-found 3.0.5 (core)",
    "@oclif/plugin-plugins 4.1.10 (core)",
    "@oclif/plugin-search 1.0.8 (core)",
    "@oclif/plugin-update 4.1.5 (core)",
    "@oclif/plugin-version 2.0.9 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.6 (core)",
    "@oclif/plugin-which 3.0.12 (core)",
    "@salesforce/cli 2.22.7 (core)",
    "apex 3.0.9 (core)",
    "auth 3.0.12 (core)",
    "data 3.0.6 (core)",
    "deploy-retrieve 2.2.6 (core)",
    "info 3.0.8 (core)",
    "limits 3.0.6 (core)",
    "marketplace 1.0.11 (core)",
    "org 3.1.2 (core)",
    "packaging 1.27.10 (core)",
    "schema 3.0.8 (core)",
    "settings 2.0.9 (core)",
    "signups 1.4.22 (user)",
    "sobject 1.0.6 (core)",
    "source 3.0.3 (core)",
    "telemetry 3.1.6 (core)",
    "templates 56.0.4 (core)",
    "trust 3.2.0 (core)",
    "user 3.1.1 (core)"
  ]
}
```

**Comment by shetzel** [comment]
My guess is that this is a server side error and nothing the CLI is doing wrong, but I'm not able to get the repro steps to work.  Step 1 (the first deploy) results in a failure when I deploy to a scratch org.  This is the error:  `sharedTo not allowed:role - CEO (8:19)`

**Comment by marcosboger** [comment]
Does the "CEO" role exists in the Scratch Org? Maybe it was a missed step on my end, you can change line 9 of `deploying/force-app/delta-package/sharingRules/User.sharingRules-meta.xml` to another existing role in the Scratch Org

**Comment by marcosboger** [comment]
Maybe it is Server side indeed, but where would be the right place to raise this issue then? In Salesforce Support they were not that helpful so far, that's why I searched for help here actually

**Comment by shetzel** [comment]
The good news is, I was able to reproduce the problem.  The bad news is, it's not a CLI bug.  The correct request is made to the metadata API, and the correct response is received and displayed.  The issue is with the server side handling of the User object metadata change.  I issued a similar command that deletes the SharingRule and updates an ApexClass and both changes were made.

Please refer to this issue when speaking with Salesforce Support.  It's possible this is a known limitation with standard objects like User (or maybe all objects) when making changes after destructive changes, particularly changes that require recalculation.

**Comment by marcosboger** [comment]
@shetzel thanks for the help in investigating the issue, I'll continue to tackle it with Salesforce Support

**Comment by iowillhoit** [comment]
Hello @marcosboger, did you end up opening a Support Case for this? We have received a similar case and are trying to connect the dots. Could you please share the case number if you opened one? Thanks!
