### ISSUE TITLE
Forceignore does not support exclamation point "!"

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#2644]
### Summary

[According to the docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm), forceignore should mimic gitignore. Gitignore supports using exclamation points to negate a certain pattern, e.g. for individual files or subdirectories: https://git-scm.com/docs/gitignore
It would be very useful if forceignore could support the same

### Steps To Reproduce
1.  Clone into [dreamhouse-lwc](https://github.com/petter-eikeland/dreamhouse-lwc)
1.  Create scratch org
1.  Try to deploy using `sf project deploy start -d issues/exclamation-ignore-bug`

### Expected result

`Account.TestField1__c` should have been deployed, and `Account.TestField2__c `should be ignored.
Because the following lines were added to .forceignore:
```
issues/exclamation-ignore-bug/objects
!issues/exclamation-ignore-bug/objects/Account/fields/TestField1__c.field-meta.xml
```

### Actual result

Both `Account.TestField1__c` & `Account.TestField2__c `was ignored. No changes was deployed

### System Information

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.24.4",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Darwin 22.6.0",
  "rootPath": "/Users/user/.local/share/sf/client/2.24.4-c9898a2",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.0 (core)",
    "@oclif/plugin-help 6.0.10 (core)",
    "@oclif/plugin-not-found 3.0.8 (core)",
    "@oclif/plugin-plugins 4.1.15 (core)",
    "@oclif/plugin-search 1.0.11 (core)",
    "@oclif/plugin-update 4.1.7 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.14 (core)",
    "@salesforce/cli 2.24.4 (core)",
    "1commerce 0.0.10 (user)",
    "apex 3.0.17 (core)",
    "auth 3.2.0 (core)",
    "community 3.0.12 (user)",
    "data 3.0.14 (core)",
    "deploy-retrieve 3.1.0 (core)",
    "info 3.0.15 (core)",
    "limits 3.1.2 (core)",
    "marketplace 1.0.16 (core)",
    "org 3.2.2 (core)",
    "packaging 2.1.0 (user)",
    "schema 3.1.0 (core)",
    "settings 2.0.15 (core)",
    "signups 2.0.15 (user)",
    "sobject 1.1.0 (core)",
    "source 3.1.3 (core)",
    "telemetry 3.1.9 (core)",
    "templates 56.0.9 (core)",
    "trust 3.3.1 (core)",
    "user 3.2.1 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.1.1 (user)",
    "sfdmu 4.32.2 (user)",
    "sfdx-browserforce-plugin 4.0.0 (user)"
  ]
}
```

**Comment by shetzel** [comment]
The CLI uses this library for the `.forceignore` implementation: https://github.com/kaelzhang/node-ignore

According to this closed issue on their repo, your usecase is working as designed:
https://github.com/kaelzhang/node-ignore/issues/79#issuecomment-1116105384

If you feel there is something we can do about this please reopen.
