### ISSUE TITLE
Publish site not working sometimes.

### ISSUE THREAD

**Issue by suresh-kumarp** [forcedotcom/cli#2649]
### Summary

We use GitHub action to publish our custom sites, but it randomly fails with the below error. Please help us to resolve this issue.
![image](https://github.com/forcedotcom/cli/assets/68844099/ca17e247-2584-4e63-b97b-919e53696c57)

Below is the successful GitHub action which was ran just before the failure one.
![image](https://github.com/forcedotcom/cli/assets/68844099/7115e7a5-4310-4a0f-8902-8e591dec6c41)

### System Information

Ubuntu - 22.04.3 LTS

{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.23.20",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Linux 6.2.0-1018-azure",
  "rootPath": "/opt/hostedtoolcache/node/20.10.0/x64/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.4 (core)",
    "@oclif/plugin-commands 3.1.0 (core)",
    "@oclif/plugin-help 6.0.9 (core)",
    "@oclif/plugin-not-found 3.0.[7](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7545564017/job/20541471388#step:9:8) (core)",
    "@oclif/plugin-plugins 4.1.14 (core)",
    "@oclif/plugin-search 1.0.10 (core)",
    "@oclif/plugin-update 4.1.7 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.[8](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7545564017/job/20541471388#step:9:9) (core)",
    "@oclif/plugin-which 3.0.14 (core)",
    "@salesforce/cli 2.23.20 (core)",
    "apex 3.0.14 (core)",
    "auth 3.1.0 (core)",
    "data 3.0.13 (core)",
    "deploy-retrieve 2.2.12 (core)",
    "info 3.0.13 (core)",
    "limits 3.1.0 (core)",
    "marketplace 1.0.15 (core)",
    "org 3.2.0 (core)",
    "packaging 2.0.1 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.14 (core)",
    "sobject 1.0.7 (core)",
    "source 3.0.[10](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7545564017/job/20541471388#step:9:11) (core)",
    "telemetry 3.1.8 (core)",
    "templates 56.0.8 (core)",
    "trust 3.2.5 (core)",
    "user 3.2.0 (core)",
    "@salesforce/sfdx-scanner 3.[20](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7545564017/job/20541471388#step:9:21).0 (user)"
  ]
}

![image](https://github.com/forcedotcom/cli/assets/68844099/b9b1ba25-b034-48af-a131-aaa159b01d10)

**Comment by suresh-kumarp** [comment]
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.23.20",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Linux 6.2.0-1018-azure",
  "rootPath": "/opt/hostedtoolcache/node/20.10.0/x64/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.4 (core)",
    "@oclif/plugin-commands 3.1.0 (core)",
    "@oclif/plugin-help 6.0.9 (core)",
    "@oclif/plugin-not-found 3.0.[7](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7545564017/job/20541471388#step:9:8) (core)",
    "@oclif/plugin-plugins 4.1.14 (core)",
    "@oclif/plugin-search 1.0.10 (core)",
    "@oclif/plugin-update 4.1.7 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.[8](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7545564017/job/20541471388#step:9:9) (core)",
    "@oclif/plugin-which 3.0.14 (core)",
    "@salesforce/cli 2.23.20 (core)",
    "apex 3.0.14 (core)",
    "auth 3.1.0 (core)",
    "data 3.0.13 (core)",
    "deploy-retrieve 2.2.12 (core)",
    "info 3.0.13 (core)",
    "limits 3.1.0 (core)",
    "marketplace 1.0.15 (core)",
    "org 3.2.0 (core)",
    "packaging 2.0.1 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.14 (core)",
    "sobject 1.0.7 (core)",
    "source 3.0.[10](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7545564017/job/20541471388#step:9:11) (core)",
    "telemetry 3.1.8 (core)",
    "templates 56.0.8 (core)",
    "trust 3.2.5 (core)",
    "user 3.2.0 (core)",
    "@salesforce/sfdx-scanner 3.[20](https://github.com/suresh-kumarp/Medsleuthnic-Salesforce/actions/runs/7545564017/job/20541471388#step:9:21).0 (user)"
  ]
}

**Comment by shetzel** [comment]
That is a server side error and will require the communities server side team for assistance.  I would open a support case for them and/or get help from a public communities forum.

**Comment by shetzel** [comment]
Also, if you're creating the community just before publishing, it's possible that the community is just not ready yet.  If you're not already doing it you might want to first poll for the community to be ready before publishing.

**Comment by shetzel** [comment]
You may want to check out these public communities:
https://trailhead.salesforce.com/trailblazer-community/groups/0F9300000001oDdCAI?tab=discussion&sort=LAST_MODIFIED_DATE_DESC
https://trailhead.salesforce.com/trailblazer-community/groups/0F93A000000HZFqSAO?tab=discussion&sort=LAST_MODIFIED_DATE_DESC
