### ISSUE TITLE
I can't use .tar system specific installer in an Alpine docker image 

### ISSUE THREAD

**Issue by carlosabella** [forcedotcom/cli#2654]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
I want to install Salesforce CLI in a Docker Image using the system-specific installer (.TAR file), instead of using the npm installer. I don't want to depend on system node version to run correctly and safely the SF CLI. 

But when I follow the steps written [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux) to install the .tar file in a linux system. The image is build correctly but when I run any sf command I get this error:

```
------                                                                                              
 > [6/6] RUN sf -v:
0.254 /app/sf/bin/sf: line 44: /app/sf/bin/node: cannot execute: required file not found
------
```

Apparently the binary is built using glibc. The Alpine distro is based on a libc variant called "musl-lib", that is why it does not work properly.
I have checked in Alpine documentation [here](https://wiki.alpinelinux.org/wiki/Running_glibc_programs) and apparently you can fix problems with glibc library by using "gcompat" and "libstdc++" library.

When I put those libraries in the docker file I get a different error:

```
------                                                                                              
 > [6/6] RUN sf -v:
0.295 Error relocating /app/sf/bin/node: fcntl64: symbol not found
------
```

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

**CASE 1:** 
Create a docker file with this content: 
```
FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add --no-cache  \
    curl \
    bash \
    && mkdir -p /app

WORKDIR /app

ARG DOWNLOAD_URL=https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
# install cli from linux tarball with bundled node
RUN curl -s $DOWNLOAD_URL --output sf-linux-x64.tar.xz \
    && mkdir -p /app/sf \
    && tar xJf sf-linux-x64.tar.xz -C /app/sf --strip-components 1 \
    && rm sf-linux-x64.tar.xz

ENV PATH="/app/sf/bin:$PATH"
ENV SF_CONTAINER_MODE true
ENV SFDX_CONTAINER_MODE true
ENV SHELL /bin/bash
RUN sf -v
```
Build the image.

**CASE 2:** 
Create a docker file adding information from Alpine documentation with this content: 
```
FROM alpine:latest

RUN apk update && apk upgrade
RUN apk add --no-cache  \
    curl \
    bash \
    libstdc++ \
    gcompat \
    && mkdir -p /app

WORKDIR /app

ARG DOWNLOAD_URL=https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
# install cli from linux tarball with bundled node
RUN curl -s $DOWNLOAD_URL --output sf-linux-x64.tar.xz \
    && mkdir -p /app/sf \
    && tar xJf sf-linux-x64.tar.xz -C /app/sf --strip-components 1 \
    && rm sf-linux-x64.tar.xz

ENV PATH="/app/sf/bin:$PATH"
ENV SF_CONTAINER_MODE true
ENV SFDX_CONTAINER_MODE true
ENV SHELL /bin/bash
RUN sf -v
```
Build the image.

### Expected result
In both cases: When running last step: RUN sf -v it is expected to see the version of the cli installed. 

### Actual result

**CASE 1:** 
 You get this error:

```
------                                                                                              
 > [6/6] RUN sf -v:
0.254 /app/sf/bin/sf: line 44: /app/sf/bin/node: cannot execute: required file not found
------
```

**CASE 2:** 
 You get this error:
```
------                                                                                              
 > [6/6] RUN sf -v:
0.295 Error relocating /app/sf/bin/node: fcntl64: symbol not found
------
```

### System Information

I am using Mac OS Sonoma 14.2. Terminal is zsh

N/A

**Comment by carlosabella** [comment]
I can't add the information required because the problem is installing the CLI and I can't execute it.

**Comment by shetzel** [comment]
node has an official docker alpine image so maybe that will help: https://github.com/nodejs/docker-node/blob/5ce4dae24d8af4283baa45226b4de1827f128de3/21/alpine3.18/Dockerfile

**Comment by carlosabella** [comment]
Hi @shetzel, thanks for answering here. 

I tried with: 
```
FROM node:alpine3.19
```

And unfortunately I got same results. Thank you.

**Comment by cristiand391** [comment]
@carlosabella _I think_ it's because the official node image for alpine downloads a different node binary for musl:
https://github.com/nodejs/docker-node/blob/5ce4dae24d8af4283baa45226b4de1827f128de3/21/alpine3.18/Dockerfile#L23

our linux tarball bundles the official linux x64 node binary so that would explain why you get the same error.

Your only path would be to install from `npm` (that's pre-installed in the node alpine image), we don't ship linux musl tarballs  (it's not a tier 1 supported platform by node):
https://github.com/nodejs/node/blob/main/deps/uv/SUPPORTED_PLATFORMS.md#supported-platforms

**Comment by carlosabella** [comment]
Understood, thank you all for the help ... I think we can close this thread.
