### ISSUE TITLE
PersonAccount duplicateRules and matchingRules

### ISSUE THREAD

**Issue by MarosSitkoEnehano** [forcedotcom/cli#2656]
### Summary
I would like to report issue similar to [https://github.com/forcedotcom/cli/issues/734](https://github.com/forcedotcom/cli/issues/734) and [https://github.com/forcedotcom/cli/issues/685](https://github.com/forcedotcom/cli/issues/685). '_sf project retrieve start_' do not work correctly as it create account files instead of personAccount

### Steps To Reproduce
Duplicate rule for person account is created in scratch org. When I run  _sf project retrieve start_, duplicateRules folder with file PersonAccount.My_Duplicate_Rule.duplicateRule-meta.xml will be created in my default folder. I move it to package folder.  MatchingRules folder is not created, I received warning
_unpackaged/package.xml :  Entity of type 'MatchingRule' named 'Account.MyMatchingRule' cannot be found`_

I need to download it with Org Browser in VS code and move to correct package folder.

Then I run again _sf project retrieve start_, DuplicateRule is downloaded **again** in my default folder, package folder is ignored, and also warning message for **'...Account.MyMatchingRule' cannot be found**

### System Information
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.24.4",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Darwin 23.1.0",
  "rootPath": "/Users/marossitko/.local/share/sf/client/2.24.4-c9898a2",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.0 (core)",
    "@oclif/plugin-help 6.0.10 (core)",
    "@oclif/plugin-not-found 3.0.8 (core)",
    "@oclif/plugin-plugins 4.1.15 (core)",
    "@oclif/plugin-search 1.0.11 (core)",
    "@oclif/plugin-update 4.1.7 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.14 (core)",
    "@salesforce/cli 2.24.4 (core)",
    "apex 3.0.17 (core)",
    "auth 3.2.0 (core)",
    "data 3.0.14 (core)",
    "deploy-retrieve 3.1.0 (core)",
    "env 3.0.14 (user)",
    "info 3.0.15 (core)",
    "limits 3.1.2 (core)",
    "marketplace 1.0.16 (core)",
    "org 3.2.2 (core)",
    "packaging 2.1.0 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.15 (core)",
    "sobject 1.1.0 (core)",
    "source 3.1.3 (core)",
    "telemetry 3.1.9 (core)",
    "templates 56.0.9 (core)",
    "trust 3.3.1 (core)",
    "user 3.2.1 (core)",
    "sfdx-browserforce-plugin 4.0.0 (user)"
  ]
}
```

**Comment by mshanemc** [comment]
Have you got a sample repro for this?   [I'm pretty sure that's a bug in SDR; I'd like to have your repro project for testing purposes as I try to fix it]

**Comment by MarosSitkoEnehano** [comment]
> Have you got a sample repro for this? [I'm pretty sure that's a bug in SDR; I'd like to have your repro project for testing purposes as I try to fix it]

it's client's org, I can not share, but I will try to prepare project for replicate in next days

**Comment by WillieRuemmele** [comment]
We've confirmed that this a server-side issue and have alerted the necessary teams.

**Comment by ddavila-TSC-SSIC** [comment]
This is still happening
