### ISSUE TITLE
 After updating Salesforce CLI to 59.13.0, receive this error 'Your installed Salesforce CLI version is no longer supported. Uninstall Salesforce CLI and install the latest version'

### ISSUE THREAD

**Issue by jcochran67** [forcedotcom/cli#2657]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

[### Summary
After Update Salesforce CLI to the latest version (59.13.0) restart VS Code. 
receive this error 'Your installed Salesforce CLI version is no longer supported. Uninstall Salesforce CLI and install the latest version'

### Steps To Reproduce
Update Salesforce CLI to the latest version (59.13.0) restart VS Code. 

### Expected result
Expected no error and still able to use the CLI commands

### Actual result
Error is received 'Your installed Salesforce CLI version is no longer supported. Uninstall Salesforce CLI and install the latest version' and can not use the CLI commands

### System Information
cmd.exe

"cliVersion": "@salesforce/cli/1.49.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v16.17.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.0 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.12 (core)",
    "@oclif/plugin-not-found 2.3.3 (core)",
    "@oclif/plugin-plugins 2.1.1 (core)",
    "@oclif/plugin-search 0.0.1 (core)",
    "@oclif/plugin-update 3.0.2 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "deploy-retrieve 1.6.4 (core)",
    "env 1.5.5 (core)",
    "functions 1.14.2 (core)",
    "generate 1.0.21 (core)",
    "info 2.1.8 (core)",
    "login 1.1.3 (core)",
    "settings 1.0.7 (core)",
    "sobject 0.0.17 (core)",
    "telemetry 2.0.2 (core)",
    "trust 2.0.4 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Program Files\\sfdx\\client\\sf"]

```json
PASTE_VERSION_OUTPUT_HERE
```
### Additional information

[https://github.com/forcedotcom/salesforcedx-vscode/issues/5348
![Annotation 2024-01-19 103923](https://github.com/forcedotcom/cli/assets/22800420/57727b62-da2b-4da2-834e-a4a771c1201b)
](url)

**Comment by jcochran67** [comment]
{
  "cliVersion": "sfdx-cli/7.172.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v16.17.1",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 1.3.1 (core)",
    "@oclif/plugin-commands 2.2.0 (core)",
    "@oclif/plugin-help 5.1.14 (core)",
    "@oclif/plugin-not-found 2.3.3 (core)",
    "@oclif/plugin-plugins 2.1.1 (core)",
    "@oclif/plugin-update 3.0.2 (core)",
    "@oclif/plugin-version 1.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.6 (core)",
    "@oclif/plugin-which 2.1.0 (core)",
    "alias 2.1.5 (core)",
    "apex 1.2.0 (core)",
    "auth 2.2.13 (core)",
    "community 2.0.3 (core)",
    "config 1.4.21 (core)",
    "custom-metadata 2.0.1 (core)",
    "data 2.1.4 (core)",
    "generator 2.0.5 (core)",
    "info 2.1.9 (core)",
    "limits 2.0.5 (core)",
    "org 2.2.7 (core)",
    "packaging 1.9.4 (core)",
    "schema 2.1.10 (core)",
    "signups 1.2.7 (core)",
    "source 2.0.17 (core)",
    "telemetry 2.0.2 (core)",
    "templates 55.1.0 (core)",
    "trust 2.0.4 (core)",
    "user 2.1.10 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.0.1 (core)",
    "salesforce-alm 54.8.1 (core)"
  ],
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "C:\\Program Files\\sfdx\\client"
}

**Comment by shetzel** [comment]
This issue is for the VS Code extension, but you are updating from a very old version of the CLI to the latest version so you need to follow these instructions:  https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm

Also, to ensure a complete uninstall before installing sf v2 follow these steps: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm
