### ISSUE TITLE
Features not being enabled in Scratch Org when release is Preview

### ISSUE THREAD

**Issue by maaaaarco** [forcedotcom/cli#266]
### Summary
Using the same scratch org configuration file, features are **not** automatically enabled upon Org creation when setting `release=Preview`

This is the configuration file I'm using:
```
{
  "orgName": "MyOrg",
  "edition": "Developer",
  "features": [
    "AuthorApex",
    "ContactsToMultipleAccounts",
    "DebugApex",
    "DefaultWorkflowUser",
    "MultiCurrency",
    "PlatformEncryption",
    "EventLogFile",
    "RetainFieldHistory"
  ],
  "settings": {
    "orgPreferenceSettings": {
      "s1DesktopEnabled": true,
      "territoryManagement2Enable": true,
      "s1EncryptedStoragePref2": false
    },
    "opportunitySettings": {
      "enableOpportunityTeam": true
    },
    "securitySettings": {
      "sessionSettings": {
        "forceRelogin": false
      }
    },
    "mobileSettings": {
      "enableLightningOnMobile": true,
      "enableS1EncryptedStoragePref2": false
    }
  }
}
```

### Steps To Reproduce:

1.  Create a Scratch Org using the configuration file provided, without specifing the `release` version
1.  After the Org is created verify that the _Contacts to Multiple Accounts_ feature is enabled. Same for _MultiCurrency_.
1. Create a Scratch Org using the configuration file provided, specifing `release=Preview` 
1. After the Org is created verify that  _Contacts to Multiple Accounts_ or _MultiCurrency_ features are not enabled.

### Expected result
When specifying the `release=Preview`  the features listed in the configuration file should be enabled upon Org creation

### Additional information

**SFDX CLI Version**: sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3

**SFDX plugin Version**
@oclif/plugin-autocomplete 0.1.5
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)

sfdx-cli 7.36.0 (core)

**OS and version**: MacOs Mojave

**Comment by clairebianchi** [comment]
@maaaaarco, I believe this is a known issue that the Scratch org team is working on fixing. @rrmehta2 can you please confirm

**Comment by anirudhbora** [comment]
@clairebianchi , Hi any update on this, is it fixed?
