### ISSUE TITLE
Extract deeply nested (more than 1 level) plan

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#2663]
> from Shane, debugging info:

The code here https://github.com/salesforcecli/plugin-data/blob/3036c362566026b0d67ce66feb7e925087fa72b8/src/api/data/tree/exportApi.ts#L334-L335 `delete record[key];` will remove the child record.  It should have, instead, looked through each `childRecords`'s fields to see if any of them `hasNestedRecords`.  Probably should also be a recursive function itself, modifying the `objects`.

The CLI's code is what's preventing it from handling more than 2 levels of object.  The API and SOQL support up to 5 these days.

### Discussed in https://github.com/forcedotcom/cli/discussions/2359

<div type='discussions-op-text'>

<sup>Originally posted by **mnunezdm** March 28, 2019</sup>
**Is your feature request related to a problem? Please describe.**

Extracting data with the `sfdx force:data:tree:export` only allows to extract one level of nested elements. I think it would be great to extract deeply nested plans like for example: `Account->Case->Task`

I managed to manually extract the data in two steps, manually edit the data plan, and insert them using the `sfdx force:data:tree:import -p`

**Describe the solution you'd like**

Ability to, for example, retrieve a list of queries and make the plan automatically for example:

```
$ sfdx force:data:tree:export -p -q "SELECT Id, Name (SELECT Origin FROM Cases) FROM Account"
                                    "SELECT Id, (SELECT Id FROM Tasks), (SELECT Id FROM Events) FROM Case"
```

**Describe alternatives you've considered**

NA

**Additional context**

This is the workaround I did: https://salesforce.stackexchange.com/questions/240042/sfdx-forcedatatreeexport-beyond-1-level-deep/255711#255711
</div>

**Comment by jshackell-sfdc** [comment]
This issue is fixed in CLI version 2.30.8.
