### ISSUE TITLE
Unable to create users with sfdx command - getting a JWT error

### ISSUE THREAD

**Issue by subashniprasannasagecom** [forcedotcom/cli#2665]
Using the latest salesforce/cli version -- the cli version we tried is [2.24.4 and [1.86.7-legacy.0] when we create user we are getting the JWT token error 
Command we run 
first, we authenticate to the scratch org created using JWT 

  echo "Authenticating to the org"
          sf org login jwt --client-id=${{ secrets.SAGE_PEOPLE_DEVHUB_CONSUMER_KEY }} --username=${{ needs.Build_time_scratch_org.outputs.sysadminusername }}  --instance-url ${{ needs.Build_time_scratch_org.outputs.instanceUrl }} --jwt-key-file ./server.key --set-default
sf org display --target-org ${{ needs.Build_time_scratch_org.outputs.sysadminusername }} --json

Upon success of org display we tried to create users 

sf org create user --json username=${username} profileName="Standard User" firstName=${firstname} lastName=${lastname} --target-org ${sysadmin} > user.json

Error details 
{
  "code": 1,
  "context": "CreateUserCommand",
  "commandName": "CreateUserCommand",
  "message": "Error authenticating with JWT.\nErrors encountered:\nuser hasn't approved this consumer\nuser hasn't approved this consumer\nuser hasn't approved this consumer\nuser hasn't approved this consumer\nuser hasn't approved this consumer",
  "name": "SfError",
  "status": 1,
  "stack": "SfError: Error authenticating with JWT.\nErrors encountered:\nuser hasn't approved this consumer\nuser hasn't approved this consumer\nuser hasn't approved this consumer\nuser hasn't approved this consumer\nuser hasn't approved this consumer\n    at SfError.wrap (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/core/lib/sfError.js:79:20)\n    at catchCreateUser (file:///usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-user/lib/commands/org/create/user.js:244:23)\n    at getNewUserAuthInfo (file:///usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-user/lib/commands/org/create/user.js:227:[16](https://github.com/Sage-People/sage-people-time/actions/runs/7628914834/job/20781602785#step:7:17))\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async CreateUserCommand.run (file:///usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-user/lib/commands/org/create/user.js:71:33)\n    at async CreateUserCommand._run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:304:22)\n    at async Config.runCommand (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:4[17](https://github.com/Sage-People/sage-people-time/actions/runs/7628914834/job/20781602785#step:7:18):[25](https://github.com/Sage-People/sage-people-time/actions/runs/7628914834/job/20781602785#step:7:26))\n    at async run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:85:16)",
  "exitCode": 1,
  "warnings": [
    "The --target-dev-hub flag is deprecated and is no longer used by this command. The flag will be removed in API version 57.0 or later."
  ]
}

this was all working correctly before .. we have seen this happening for the last 1 week only ..
This is breaking our CI completely

**Comment by subashniprasannasagecom** [comment]
I have updated the cli version to the ticket

**Comment by shetzel** [comment]
Was your org recently updated to a hyperforce instance?  If so, creating users with JWT auth won't work due to server side changes, not CLI changes.  If this is the case you should switch to use auth url.

**Comment by subashniprasannasagecom** [comment]
@shetzel  shetzel the way we do is we use JWT to authenticate to dev hub so u are saying that will not work going forward

**Comment by shetzel** [comment]
@subashniprasannasagecom - I'm saying it will not work if your org is on hyperforce.  Recent CLI versions will output an error message stating if this is the case.  If it is, and you need to create users in a scratch org from the CLI, you'll need to switch to use the auth url method.  That's outside of the CLI's control since it's server side.  But the first thing to do is find out if you're on a hyperforce instance.  https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000BsIhCSAV

**Comment by subashniprasannasagecom** [comment]
yes my org is hyperforce server .. is there any workaround for this ..as it is run in CI

**Comment by mshanemc** [comment]
@subashniprasannasagecom 

1. you can't use JWT with that command on hyperforce.  
2. if you need the command, do it without JWT.  You can use `sf org login sfdx-url` from CI just fine.  That's your only option.
