### ISSUE TITLE
"plugins" topic should support "--json" flag

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#267]
**Is your feature request related to a problem? Please describe.**
* relates to issue #26 

**What are you trying to do**
* The absence of the flag complicates the automation on a build job when trying to determine what plugins are currently installed

**Describe the solution you'd like**
* The `--json` flag is added to the `sfdx plugins` command
* The execution of the command produces output in JSON format that can be consumed by a script

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by clairebianchi** [comment]
@ImJohnMDaniel do you mean the `sfdx plugins` topic?

**Comment by ImJohnMDaniel** [comment]
Yes, @clairebianchi, i did mean `plugins` topic.  Good catch!  I have updated the ticket accordingly

**Comment by mshanemc** [comment]
That topic is part of oclif and not the Salesforce CLI (that's why it doesn't inherit the `json` flag automatically)

the repo is here if you want to make it happen before we get to it, or at least get it on their issues list
https://github.com/oclif/plugin-plugins

**Comment by mshanemc** [comment]
same problem here: https://github.com/forcedotcom/cli/issues/279

**Comment by iowillhoit** [comment]
This has been merged into plugin-plugins https://github.com/oclif/plugin-plugins/pull/609
It is currently available in the `nightly` versions of the clis
