### ISSUE TITLE
Replace Strings does not work on the CustomLabels.labels-meta.xml file

### ISSUE THREAD

**Issue by mpaul1** [forcedotcom/cli#2675]
### Summary
"Replace Strings in Code Before Deploying" feature does not find and replace values in the CustomLabels.labels-meta.xml file.  I suceeded with other metadata files types, but not custom labels.

### Steps To Reproduce
Custom Label file data:
`   <labels>`
`        <fullName>Docs_CabinetId</fullName>`
`        <language>en_US</language>`
`        <protected>false</protected>`
`        <shortDescription>Docs_CabinetId</shortDescription>`
`        <value>AB-123456</value>`
`    </labels>`

These statements at the end of the sfdx-project.json file do not result in AB-123456 being replaced with CD-987654 in the custom label deployed to the org.
"replacements": [
    {
      "filename": "src/Core/main/default/labels/CustomLabels.labels-meta.xml",
      "stringToReplace": "AB-123456",
      "replaceWithEnv": "ENVVAR_NEWDOCCABID",  
    },

When running this command in my local bash console:
ENVVAR_NEWDOCCABID=CD-987654 sf project deploy start --metadata CustomLabel

### Expected result
When running that command with that sfdx-project.json and CustomLabel file configuration, I would expect AB-123456 to be replaced with CD-987654 when the deployment completed successfully to the org.

### Actual result
The value is not changed after successful deployment.
Additionally, running sf project convert source --output-dir mdapiOut --source-dir src/Core/main/default/labels, reviewing the output customlabel metadata file also does not show the properly replaced new value.

### System Information
GNU bash, version 5.2.21(1)-release (x86_64-pc-msys)
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.25.7",
  "nodeVersion": "node-v21.6.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\MPaul001\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.17 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.25.7 (core)",
    "apex 3.0.18 (core)",
    "auth 3.3.2 (core)",
    "data 3.0.16 (core)",
    "deploy-retrieve 3.2.0 (core)",
    "info 3.0.17 (core)",
    "limits 3.1.4 (core)",
    "marketplace 1.0.16 (core)",
    "org 3.3.5 (core)",
    "packaging 2.1.1 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.17 (core)",
    "sobject 1.1.2 (core)",
    "source 3.1.5 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.10 (core)",
    "trust 3.3.2 (core)",
    "user 3.2.3 (core)",
    "sfdmu 4.32.2 (user)"
  ]
}

**Comment by mshanemc** [comment]
for your `convert` command you'd need to set the env `SF_APPLY_REPLACEMENTS_ON_CONVERT ` for the Replacements to occur (see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm)

[they're automatic on deploys, but not on convert, to keep secrets out of the filesystem]

I'm not able to replicate this locally, so I'm guessing that it's related to your use of windows (fine) with GNU bash (not supported/tested).  So, I'm going to need your help to figure out what's going on.

Can you try the `SF_APPLY_REPLACEMENTS_ON_CONVERT=true sf project convert source --output-dir mdapiOut --source-dir src/Core/main/default/labels` to see if convert is happening as expected?  You'd need to set `ENVVAR_NEWDOCCABID` too.
