### ISSUE TITLE
Error when updating Salesforce CLI from command line

### ISSUE THREAD

**Issue by gsnortland** [forcedotcom/cli#2678]
### Summary
Running sf update updates Salesforce CLI to current version but shows an error when it completes.

### Steps To Reproduce
Open terminal window in VsCode.
Run $ sf update

### Expected result
After it completes, it should show success.

### Actual result
Sf appears to be updated to latest version but it shows an error.  "Error: EPERM: operation not permitted, unlink 'C:\users\8909879\AppData\Local\sf\client\2.17.14-31db5eb\bin\node.exe
Code: EPERM
The batch file cannot be found."

### System Information

```json
@salesforce/cli/2.25.7 win32-x64 node-v20.10.0
```
### Additional information
![MicrosoftTeams-image](https://github.com/forcedotcom/cli/assets/13258634/fe56c2c3-047a-4c8c-9419-416b1190f652)

**Comment by NerioVillalobos** [comment]
Hi @gsnortland 

I recommed use command " npm update -g @salesforce/cli" to update

Regards,

**Comment by mshanemc** [comment]
@gsnortland does the file `C:\users\8909879\AppData\Local\sf\client\2.17.14-31db5eb\bin\node.exe` actually exist?  If so, are the permissions on it set so that it can't be deleted?

Did it upgrade you to the new version and then fail to clean up the old one, or does the error happen before the new one installed?

---

> I recommed use command " npm update -g @salesforce/cli" to update

that works for npm-based installations.  @gsnortland installed via the windows installer.  Don't cross the streams

**Comment by Rihan9** [comment]
not resolved. Github actions, mind your business lol.

**Comment by NerioVillalobos** [comment]
I think they are diverting the error, I did everything they indicated and I put the image back, but it still doesn't work for me.

nervill@DESKTOP-L91RLI8:~$ node -v
v22.1.0
.nervill@DESKTOP-L91RLI8:~$ whereis node
.node: /usr/bin/node /usr/include/node /home/nervill/.nvm/versions/node/v22.1.0/bin/node /mnt/c/Program .Files/nodejs/node.exe /usr/share/man/man1/node.1.gz
.nervill@DESKTOP-L91RLI8:~$ sf --version
 .›   Warning: @salesforce/cli update available from 2.63.9 to 2.64.8.
.@salesforce/cli/2.63.9 wsl-x64 node-v22.1.0
.nervill@DESKTOP-L91RLI8:~$ npm update -g @salesforce/cli

added 89 packages, removed 10 packages, and changed 695 packages in 4m

122 packages are looking for funding
  run `npm fund` for details
.nervill@DESKTOP-L91RLI8:~$ sf --version
.@salesforce/cli/2.64.8 wsl-x64 node-v22.1.0
.nervill@DESKTOP-L91RLI8:~$

![image](https://github.com/user-attachments/assets/f66e301f-ba0b-489c-963c-d4698988c0be)

![image](https://github.com/user-attachments/assets/b6ca96bd-90d0-4be1-9ddd-8fc777caee4c)

**Comment by Rihan9** [comment]
launch the update inside the old sfdx version like this:
```
C:\users\8909879\AppData\Local\sf\client\2.17.14-31db5eb\bin>sf update
```

and you should be able to perform the update. but this is NOT a solution, just a workaround

**Comment by NerioVillalobos** [comment]
Hi @Rihan9 , how are you? Do you notice that you are running it in Powershell and I am running it in WSL2 Ubuntu within Windows?
