### ISSUE TITLE
Add the option to output ux.startSpinner in stdout instead of stderr

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/cli#268]
**Is your feature request related to a problem? Please describe.**
I'm using `this.ux.startSpinner()` in my custom sfdx plugins, and noticed that the output is written to `stderr`. It looks like this is because of the default value in the [underlying oclif method set to stderr](https://github.com/oclif/cli-ux/blob/06ef95fe483e6c19c53f6b4273e24d4b30432f99/src/action/base.ts#L30).
Our CI is failing if anything is written to `stderr `(which I think makes sense), so I can't use `this.ux.startSpinner()`  anymore.

**What are you trying to do**
Continue using spinner in my custom sfdx plugins output, but outputing it to `stdout `instead of `stderr`.

**Describe the solution you'd like**
As it's unlikely I can change the default behavior of oclif (not sure why it defaults to stderr though, would be hapy to know if I'm missing something obvious), I would like to have in the [sfdx library](https://github.com/forcedotcom/cli-packages/blob/f67acada84ea39c7b8d572fa817b24e03da6f496/packages/command/src/ux.ts#L152) the same options that we have in the [oclif one](https://github.com/oclif/cli-ux/blob/06ef95fe483e6c19c53f6b4273e24d4b30432f99/src/action/base.ts#L29).
This way, I would be able to output to stdout with something like this:
`this.ux.startSpinner("Whatever I'm doing", null, { stdout: true });`

**Describe alternatives you've considered**
So far, I've been importing and using `cli-ux` directly, even though I need to manage the json flag manually (not outputing when --json is used):
```
if (!this.flags.json) {
    cli.action.start("Whatever I'm doing", null, { stdout: true });
}

```

**Comment by clairebianchi** [comment]
@FabienTaillon how are you starting your spinner? In the Oclif docs it looks like you can do what you want, see: https://oclif.io/docs/spinner

I am wondering if this is a bug and its not working.

**Comment by FabienTaillon** [comment]
@clairebianchi oclif allows it, but not the SDX CLI library. I would like to add the same option [here](https://github.com/forcedotcom/cli-packages/blob/f67acada84ea39c7b8d572fa817b24e03da6f496/packages/command/src/ux.ts#L152).

Benefit is that I won't have to handle the `--json` flag myself to avoid the ouput when json is returned.

To be honest I don't really get why this is ouputed in stderr by default in oclif, but I don't think we can change that ?

I could do the PR myself if you think it makes sense to add these options to the [sfdx ux library](https://github.com/forcedotcom/cli-packages/blob/f67acada84ea39c7b8d572fa817b24e03da6f496/packages/command/src/ux.ts).

**Comment by ImJohnMDaniel** [comment]
+1 to @FabienTaillon ‘s suggestion.

**Comment by FabienTaillon** [comment]
@clairebianchi I did a Pull Request for this issue [here](https://github.com/forcedotcom/cli-packages/pull/107).

**Comment by clairebianchi** [comment]
Cool, I'll have someone take a look at it in the next week

**Comment by FabienTaillon** [comment]
I'm closing the issue as the PR was merged and published.
