### ISSUE TITLE
Invalid SFDX auth URL when running org:login:sfdx-url

### ISSUE THREAD

**Issue by SarathKL** [forcedotcom/cli#2683]
### Summary
 Invalid SFDX auth URL. Must be in the format xxx

### Steps To Reproduce
running the following command gives below error
sfdx org:login:sfdx-url --alias devorg --sfdx-url-file .\authFile.txt

error : Invalid SFDX auth URL. Must be in the format "force://<clientId>:<clientSecret>:<refreshToken>@<instanceUrl>".  Note that the SFDX auth URL uses the "force" protocol, and not "http" or "https".  Also note that the "instanceUrl" inside the SFDX auth URL doesn't include the protocol ("https://").

### Expected result
authenicate the salesforce org

### Actual result
getting error

### System Information
{
  "cliVersion": "@salesforce/cli/2.10.2",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.19044",
  "shell": "cmd.exe",
  "rootPath": "C:\\Program Files\\sf\\client",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.8 (core)",
    "@oclif/plugin-commands 2.2.25 (core)",
    "@oclif/plugin-help 5.2.19 (core)",
    "@oclif/plugin-not-found 2.4.1 (core)",
    "@oclif/plugin-plugins 3.7.1 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.3 (core)",
    "@oclif/plugin-version 1.3.10 (core)",
    "@oclif/plugin-warn-if-update-available 2.1.0 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.10.2 (core)",
    "apex 2.3.15 (core)",
    "auth 2.8.17 (core)",
    "data 2.5.9 (core)",
    "deploy-retrieve 1.18.0 (core)",
    "info 2.6.43 (core)",
    "limits 2.3.34 (core)",
    "login 1.2.31 (core)",
    "marketplace 0.2.2 (core)",
    "org 2.10.8 (core)",
    "schema 2.3.26 (core)",
    "settings 1.4.29 (core)",
    "sobject 0.2.7 (core)",
    "source 2.10.34 (core)",
    "telemetry 2.3.3 (core)",
    "templates 55.5.12 (core)",
    "trust 2.6.13 (core)",
    "user 2.3.32 (core)"
  ]
}

sample authFile.txt file content-
force://PlatformCLI::5AepxxxxxxxxbMcH.yOaAxxxxxk4Om8@abcd-p-dev-ed.develop.my.salesforce.com

**Comment by mshanemc** [comment]
Thanks for reporting this.  We have an existing issue about it https://github.com/forcedotcom/cli/issues/2629 but your sample file contents help give us more things to try. I'm going to close this issue and send you over to that one.

```
sample authFile.txt file content-
force://PlatformCLI::5AepxxxxxxxxbMcH.yOaAxxxxxk4Om8@abcd-p-dev-ed.develop.my.salesforce.com
```

None of us have been able to reproduce this yet on our machines or even in tests that run on windows.  As a workaround, are you able to try the json equivalent, where you put { "sfdxAuthUrl" : "force://PlatformCLI::5AepxxxxxxxxbMcH.yOaAxxxxxk4Om8@abcd-p-dev-ed.develop.my.salesforce.com" } ?

I'm wondering if you've got whitespace in the file somewhere that's causing this?

**Comment by SarathKL** [comment]
I am sure there are no whitespace in the file. I was getting same error when i try it in a github action as well.

Tried the json format, same error...

**Comment by mshanemc** [comment]
Please continue the thread over on the original one https://github.com/forcedotcom/cli/issues/2629

The person who opened that said they've got it resolved, potentially as a result of windows updates?
