### ISSUE TITLE
sf_x64.exe is not signed

### ISSUE THREAD

**Issue by hansliss** [forcedotcom/cli#2685]
### Summary
sf_x64.exe can not be installed on a secured corporate computer because it is unsigned.

### Steps To Reproduce
Download sf_x64.exe and try to check the signature in "Properties".

### Expected result
sf_x64.exe should have a signature, like sf_x86.exe has.

### Actual result
sf_x64.exe lacks a signature, and can therefore not always be run.

### System Information
{
  "cliVersion": "N/A",
  "architecture": "win32-x64",
  "nodeVersion": "N/A",
  "pluginVersions": [
  ],
  "osVersion": "Windows_NT 10.0.19045",
  "shell": "cmd.exe",
  "rootPath": "N/A"
}
The sf_x86.exe installer has version 2.26.10.0. The sf_x64.exe installer has no version information.

### Additional information

![sf_x64_properties](https://github.com/forcedotcom/cli/assets/1109520/5feb152f-c540-4aa8-9575-aa5a30506316)
![sf_x86_properties](https://github.com/forcedotcom/cli/assets/1109520/d768e4f0-1e85-42df-8ca1-212429cb32ad)

**Comment by hansliss** [comment]
> Hello @hansliss 👋 It looks like you didn't include the full Salesforce CLI version information in your issue. Please provide the output of `version --verbose --json` for the CLI you're using (`sf` or `sfdx`).
> 
> A few more things to check:
> 
> * Make sure you've provided detailed steps to reproduce your issue.
>   
>   * A repository that clearly demonstrates the bug is ideal.
> * Make sure you've installed the latest version of Salesforce CLI. ([docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_update_cli.htm))
>   
>   * Better yet, try the `rc` or `nightly` versions. ([docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_rc.htm))
> * Try running the `doctor` command to diagnose common issues.
> * Search GitHub for existing related issues.
> 
> Thank you!

Not applicable - can not install.

**Comment by mshanemc** [comment]
Where are you getting the exe file from?  I just downloaded the one from https://developer.salesforce.com/tools/salesforcecli# and all the signatures seem to be in place.

I gotta debug some other windows problem today, so I'll try it from a windows box just to be sure.

```
osslsigncode verify ~/Downloads/sf-x64.exe
Current PE checksum   : 00000000
Calculated PE checksum: 02F03EC0
Warning: invalid PE checksum

Message digest algorithm  : SHA256
Current message digest    : A903572FB2D67EA38A16CCCB0E5DD2AE109D453577A04B2CFE001FE77D20D1E3 
Calculated message digest : A903572FB2D67EA38A16CCCB0E5DD2AE109D453577A04B2CFE001FE77D20D1E3 

Signature Index: 0  (Primary Signature)
Signer's certificate:
	Signer #0:
		Subject: /C=US/ST=California/L=San Francisco/O=Salesforce, Inc./OU=Code Signing/CN=Salesforce, Inc.
		Issuer : /C=US/O=DigiCert, Inc./CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1
		Serial : 02B4F49456A536E9654008D47B00827B
		Certificate expiration date:
			notBefore : May  2 00:00:00 2023 GMT
			notAfter : May  1 23:59:59 2024 GMT

Number of certificates: 2
	Signer #0:
		Subject: /C=US/ST=California/L=San Francisco/O=Salesforce, Inc./OU=Code Signing/CN=Salesforce, Inc.
		Issuer : /C=US/O=DigiCert, Inc./CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1
		Serial : 02B4F49456A536E9654008D47B00827B
		Certificate expiration date:
			notBefore : May  2 00:00:00 2023 GMT
			notAfter : May  1 23:59:59 2024 GMT
	------------------
	Signer #1:
		Subject: /C=US/O=DigiCert, Inc./CN=DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1
		Issuer : /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Trusted Root G4
		Serial : 08AD40B260D29C4C9F5ECDA9BD93AED9
		Certificate expiration date:
			notBefore : Apr 29 00:00:00 2021 GMT
			notAfter : Apr 28 23:59:59 2036 GMT

Message digest algorithm: SHA256

Authenticated attributes:
	Microsoft Individual Code Signing purpose
	Message digest: 650E2B57C70AF02C6FE951174200D7DB2B46995C72D4F56673F4892ECE596A73 

The signature is timestamped: Jan 24 07:56:48 2024 GMT
Hash Algorithm: sha256
Timestamp Verified by:
		Issuer : /C=US/O=DigiCert, Inc./CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA
		Serial : 0544AFF3949D0839A6BFDB3F5FE56116

CAfile: /etc/ssl/cert.pem
TSA's certificates file: /etc/ssl/cert.pem
TSA's CRL distribution point: http://crl3.digicert.com/DigiCertTrustedG4RSA4096SHA256TimeStampingCA.crl
Connecting to http://crl3.digicert.com/DigiCertTrustedG4RSA4096SHA256TimeStampingCA.crl
Timestamp Server Signature CRL verification: ok
Timestamp serial number: 526379BC7C1A1489AE7B1B4A1C5ADE5D
Timestamp Server Signature verification: ok
Signature verification time: Jan 24 07:56:48 2024 GMT
CRL distribution point: http://crl3.digicert.com/DigiCertTrustedG4CodeSigningRSA4096SHA3842021CA1.crl
Connecting to http://crl3.digicert.com/DigiCertTrustedG4CodeSigningRSA4096SHA3842021CA1.crl
Signature CRL verification: ok
Signature verification: ok

Number of verified signatures: 1
Succeeded

```

**Comment by hansliss** [comment]
Thanks for your reply! That's odd, that's where I downloaded it from, and I see the signature on another computer. This is clearly not an issue with the file, but with the computer, which is unexpected. Sorry about that. I'll close this.

**Comment by mshanemc** [comment]
We've had a few other issues with signing pipeline lately, so I definitely thought this could be real.  Thanks for confirming!
