### ISSUE TITLE
Cannot create user on Scratch org without ApiEnabled

### ISSUE THREAD

**Issue by thvd** [forcedotcom/cli#2686]
### Summary
When we run 
```shell
sf org create user --set-alias something@amce.com.acc  \
  --definition-file ./config/users/user-amce-landelijk.json \
  -o acme-preview
``` 

We get the error: 
`Error (1): API is disabled for this User`.

### Steps To Reproduce

1. Create a user with the command above. 
1. Use a profile without APIEnabled. (for the to be created user).
```xml
<userPermissions>
    <enabled>false</enabled>
    <name>ApiEnabled</name>
</userPermissions>

```
3. This is not the "User user" user, but the new user to be created!

### Expected result
1. The user is created.

### Actual result
In API Version 59 this does work fine. But in 60 (Spring 24) this is boken with the error `Error (1): API is disabled for this User`.

### System Information
`@salesforce/cli/2.26.10 darwin-x64 node-v20.11.0`

### Additional information
```json

{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.26.10",
  "nodeVersion": "node-v20.11.0",
  "osVersion": "Darwin 23.2.0",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.21 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@provartesting/provardx 0.3.2 (user)",
    "@salesforce/cli 2.26.10 (core)",
    "apex 3.0.20 (core)",
    "auth 3.3.3 (core)",
    "data 3.0.17 (core)",
    "deploy-retrieve 3.2.6 (core)",
    "dev 2.1.1 (user)",
    "info 3.0.18 (core)",
    "limits 3.1.5 (core)",
    "marketplace 1.0.18 (core)",
    "omnistudio-migration-tool 1.3.0 (user)",
    "org 3.3.8 (core)",
    "packaging 2.1.3 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.19 (core)",
    "signups 2.0.15 (user)",
    "sobject 1.1.3 (core)",
    "source 3.1.6 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.11 (core)",
    "trust 3.3.2 (core)",
    "user 3.2.4 (core)",
    "sfdx-hardis 4.10.2 (user)"
  ]
}


```

**Comment by thvd** [comment]
After some more digging, i found out that:
- API version 59: if you don't specify the APIEnabled setting, by default it's enabled (true)
- API version 60: if you don't specify the APIEnabled setting is disabled (false)

**Comment by mshanemc** [comment]
The created user will need API access (the first thing the CLI does after the user is created is to authenticate as that user, which will require use of the API).

It's possible the new release (60) changes something with the way Profile security works (default disabled) because at Salesforce things tend to drift toward "more secure by default" which is what this sounds like.

I'm going to close the issue since there's nothing to be done but updating your Profiles
