### ISSUE TITLE
Failing to install sf cli using npm install

### ISSUE THREAD

**Issue by nnamacha** [forcedotcom/cli#2689]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
We are failing to install sf cli using npm getting  the error ERESOLVE could not resolve

### Steps To Reproduce
We ran the command **npm install @salesforce/cli**
> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### Expected result

Successful installation
### Actual result

Got the error
### System Information

When in bash find attached log file
[2024-02-02T14_04_11_620Z-debug-0.log](https://github.com/forcedotcom/cli/files/14141328/2024-02-02T14_04_11_620Z-debug-0.log)

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by nnamacha** [comment]
![Uploading image (3).png…]()

**Comment by mshanemc** [comment]
You're trying to install the CLI to use it, or trying to install it as a dependency for developing another npm package?

If the normal way, use `npm install -g @salesforce/cli`.  Directions are here https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_npm

If you're trying to add it to a project's dependencies...maybe `--force` or --legacy-peer-deps and makes sure you're on a recent node/`npm` version.  https://stackoverflow.com/questions/64573177/unable-to-resolve-dependency-tree-error-when-installing-npm-packages
