### ISSUE TITLE
force:mdapi:deploy progress bar not working correctly when tests executing

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/cli#269]
### Summary
The new MDAPI progress bar displays incorrect information when tests are executing as part of a deployment and no further progress updated on the bar. 

```
MDAPI PROGRESS | ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 86/825 Files
```

86 represents the number of components that were deployed. This number doesn't change as tests are executed. There is a brief flash where 86 changes to the test number but immediately returns to display 86/825.

825 represents the number of components deployed (86) plus the number of tests to execute (739).

### Steps To Reproduce:

```
sfdx force:mdapi:deploy -c -l RunSpecifiedTests -r 'Test1,Test2,...TestN' --verbose -d ./mdapi-pkg
```
### Expected result

Progress bar should continue updating as tests are executed and number should increase until it reaches the total.

### Actual result

Progress bar does not move forward and number displayed remains as 86/825, until the entire deployment is completed, then the progress bar is updated as follows:

```
MDAPI PROGRESS | ████████████████████████████████████████ | 820/820 Files
```

Total number changed from 825 to 820 but I think that is due to `destructiveChangesPre.xml` and `destructiveChangesPost.xml` being included in my deployment. When I look at the Deployment Status page I can see the number of components deployed changed to 81/81 and tests run is 739/739, so the numbers match up.

### Additional information

Maybe Progress should show files and tests seperately.

e.g
```
MDAPI PROGRESS | █████████░░░░░░░░░░░░░░░░ | 86/86 Files | 203/739 Tests
```

**SFDX CLI Version**: `sfdx-cli/7.41.0-86eabb70b5 linux-x64 node-v10.15.3`

**SFDX plugin Version**
```@oclif/plugin-autocomplete 0.1.5
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.14.0 (core)
├─ salesforcedx-templates 47.15.0 (core)
└─ salesforce-alm 47.13.0 (core)

sfdx-cli 7.41.0 (core)
sfdx-waw-plugin 1.5.0
```

**OS and version**:  Ubuntu 16.04.6 LTS

**Comment by clairebianchi** [comment]
@alan-morey you are correct that the progress bar denominator updates after all the components are deployed and adds the tests but the bar should update as tests are run. We will take a look.

**Comment by clairebianchi** [comment]
@alan-morey  We have a fix for this, it will go out next week

**Comment by alan-morey** [comment]
Progress Bar updates correctly now.
