### ISSUE TITLE
Error (1): We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: structuredClone is not defined

### ISSUE THREAD

**Issue by gian-ribo** [forcedotcom/cli#2695]
### Summary
trying this command sfdx auth:jwt:grant, I recieve this error:

Error (1): We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: structuredClone

### Steps To Reproduce
I execute a script in where I try to atuthenticate to my org using this command:
sf org login jwt --client-id "$CONSUMER_KEY" --jwt-key-file "JWT/server.key" --username "$USERNAME" 

### Expected result
Successfully authorized USERNAME with org ID OrgId

### Actual result
Error (1): We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: structuredClone

### System Information
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.26.10",
  "nodeVersion": "node-v16.20.1",
  "osVersion": "Linux 4.14.291-218.527.amzn2.x86_64",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.21 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.26.10 (core)",
    "apex 3.0.20 (core)",
    "auth 3.3.3 (core)",
    "data 3.0.17 (core)",
    "deploy-retrieve 3.2.6 (core)",
    "info 3.0.18 (core)",
    "limits 3.1.5 (core)",
    "marketplace 1.0.18 (core)",
    "org 3.3.8 (core)",
    "packaging 2.1.3 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.19 (core)",
    "sobject 1.1.3 (core)",
    "source 3.1.6 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.11 (core)",
    "trust 3.3.2 (core)",
    "user 3.2.4 (core)"
  ]
}

**Comment by mshanemc** [comment]
Node 16 isn't supported.  18 fixes this.  See https://github.com/forcedotcom/cli/issues/1985
