### ISSUE TITLE
Metadata API request failed: Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by nnamacha** [forcedotcom/cli#2697]
### Summary
When trying to retrieve components from the org we are getting the error Metadata API request failed: Cannot read properties of null (reading 'split'). However the actual component will be retrieved.

### Steps To Reproduce

Use the retrieve from org option on vs code
![image (5)](https://github.com/forcedotcom/cli/assets/1133995/e35d8c0d-5b6a-437d-8601-cfd527de890d)

### Expected result
Successfully retrieval without the error

### Actual result
Successfully retrieval with error

### System Information

{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.26.10",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Program Files\\sf\\client",
  "shell": "C:\\Users\\AB030QD\\AppData\\Local\\Programs\\Git\\usr\\bin\\bash.exe",
  "pluginVersions": [
    "@copado/copado-cli 3.1.0 (user)",
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.21 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.26.10 (core)",
    "apex 3.0.20 (core)",
    "auth 3.3.3 (core)",
    "data 3.0.17 (core)",
    "deploy-retrieve 3.2.6 (core)",
    "info 3.0.18 (core)",
    "limits 3.1.5 (core)",
    "marketplace 1.0.18 (core)",
    "org 3.3.8 (core)",
    "packaging 2.1.3 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.19 (core)",
    "sobject 1.1.3 (core)",
    "source 3.1.6 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.11 (core)",
    "trust 3.3.2 (core)",
    "user 3.2.4 (core)",
    "sfdx-git-delta 5.34.0 (user)"
  ]
}
has context menu

**Comment by mshanemc** [comment]
@nnamacha are you able to reproduce this with just the CLI command, or is it a problem only with vscode?

**Comment by mshanemc** [comment]
@nnamacha I see where this error is happening and there's a fix for it.    
https://github.com/forcedotcom/source-deploy-retrieve/pull/1236.

**Comment by nnamacha** [comment]
@mshanemc  How can I install the fix?

**Comment by mshanemc** [comment]
It's in `nightly` https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_rc.htm?q=nightly

tomorrow afternoon that becomes RC
