### ISSUE TITLE
Getting an error when trying to spin up a scratch org

### ISSUE THREAD

**Issue by mpdeglau** [forcedotcom/cli#270]
### Summary

When trying to create a scratch org I get the error `The request to create a scratch org failed with error code: C-1033`

### Steps To Reproduce:

1.  sfdx force:org:create --setdefaultusername -s -a scratchName -f config/project-scratch-def.json

### Expected result
Expect a new scratch org to be created.

### Actual result

Receive the error:
The request to create a scratch org failed with error code: C-1033.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.41.0 darwin-x64 node-v10.15.3 (I was on a 7.37.1 and updated to 41 and still received the error)

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.2.2 (core)
generator 1.1.2 (core)
salesforcedx 47.14.0 (core)
├─ salesforcedx-templates 47.15.0 (core)
└─ salesforce-alm 47.13.0 (core)

sfdx-cli 7.41.0 (core)
sfpowerkit 1.31.3
**OS and version**:
Mac Catalina

**Comment by vineetpuranik** [comment]
We are also seeing the same error with the exact error code today when our CI job is trying to create scratch orgs.

![image](https://user-images.githubusercontent.com/40868710/72551781-687d5100-384a-11ea-990f-4b3bf42ccd3f.png)

**Comment by mpdeglau** [comment]
It was caused by 
https://status.salesforce.com/generalmessages/366
