### ISSUE TITLE
An error occurs everytime an sfdx command is run.

### ISSUE THREAD

**Issue by azanatta** [forcedotcom/cli#2703]
Note: Our DevHub org has been updated to Spring '24 today.

### Summary
An error occurs everytime an sfdx command is run. The DevHub org has been updated to Spring '24 today.

### Steps To Reproduce
Run any sf command (e.g. scratch org creation)

### Actual result
A generic error is returned:
```
sf org create scratch --edition developer --alias testOrg

Error (1): A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance

Try this:

See https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_error_codes.htm for information on error code C-9999.
```

### System Information
**full** output of the `sf version --verbose --json` command:

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.27.6",
  "nodeVersion": "node-v20.11.0",
  "osVersion": "Windows_NT 10.0.22631",
  "rootPath": "C:\\Users\\zanaa\\AppData\\Local\\sf\\client\\2.27.6-2617cbc",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.23 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.27.6 (core)",
    "apex 3.0.22 (core)",
    "auth 3.3.6 (core)",
    "data 3.0.18 (core)",
    "deploy-retrieve 3.2.9 (core)",
    "info 3.0.19 (core)",
    "limits 3.1.6 (core)",
    "marketplace 1.0.20 (core)",
    "org 3.3.10 (core)",
    "packaging 1.22.2 (user)",
    "schema 3.1.0 (core)",
    "settings 2.0.21 (core)",
    "sobject 1.1.6 (core)",
    "source 3.1.8 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.12 (core)",
    "trust 3.3.4 (core)",
    "user 3.2.6 (core)"
  ]
}
```

**Comment by azanatta** [comment]
I know that a C-9999 is a generic serverside error that Salesforce is returning and sfdx cli has nothing to do with it, but I'm still  posting this to get a confirmation that the Salesforce's orgs update to Spring '24 has nothing to do with this issue returned by the cli.

**Comment by cesarParra** [comment]
I'm facing the same issue when I try to create a new scratch org.

**Comment by holapancho** [comment]
I'm experiencing the same issue, this is the error thrown creating a new scratch org using `--dev-debug` command:

```
{
   "code":1,
   "actions":[
      "See https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_error_codes.htm for information on error code C-9999."
   ],
   "context":"EnvCreateScratch",
   "commandName":"EnvCreateScratch",
   "data":{
      "username":"...",
      "orgId":"...",
      "scratchOrgInfoId":"..."
   },
   "message":"A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance",
   "name":"RemoteOrgSignupFailed",
   "status":1,
   "stack":"RemoteOrgSignupFailed: A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance\n    at checkScratchOrgInfoForErrors (/Users/franciscorojas/.local/share/sf/client/2.27.6-2617cbc/node_modules/@salesforce/core/lib/org/scratchOrgErrorCodes.js:63:19)\n    at async pollForScratchOrgInfo (/Users/franciscorojas/.local/share/sf/client/2.27.6-2617cbc/node_modules/@salesforce/core/lib/org/scratchOrgInfoApi.js:308:16)\n    at async scratchOrgCreate (/Users/franciscorojas/.local/share/sf/client/2.27.6-2617cbc/node_modules/@salesforce/core/lib/org/scratchOrgCreate.js:168:17)\n    at async EnvCreateScratch.run (file:///Users/franciscorojas/.local/share/sf/client/2.27.6-2617cbc/node_modules/@salesforce/plugin-org/lib/commands/org/create/scratch.js:164:72)\n    at async EnvCreateScratch._run (/Users/franciscorojas/.local/share/sf/client/2.27.6-2617cbc/node_modules/@oclif/core/lib/command.js:304:22)\n    at async Config.runCommand (/Users/franciscorojas/.local/share/sf/client/2.27.6-2617cbc/node_modules/@oclif/core/lib/config/config.js:417:25)\n    at async run (/Users/franciscorojas/.local/share/sf/client/2.27.6-2617cbc/node_modules/@oclif/core/lib/main.js:85:16)",
   "exitCode":1,
   "warnings":[
      "Record types defined in the scratch org definition file will stop being capitalized by default in a future release.\nSet the `org-capitalize-record-types` config var to `true` to enforce capitalization."
   ]
}
```

Version in use: `@salesforce/cli/2.27.6 darwin-x64 node-v20.11.0`

**Comment by azanatta** [comment]
I have created a Salesforce case (internal number: #46265556 - not publicly reachable, but you can mention it if you create a case too).

**Comment by azanatta** [comment]
They identified the issue as a bug and made it public: 
https://issues.salesforce.com/issue/a028c00000yx0wjAAA/~

**Comment by Jucamola** [comment]
I don't know if it will work for you, but we changed the edition to enterprise in the config file as a workaround and it works

**Comment by bacasystems-IT** [comment]
The bug seems to have been fixed that blocked scratch org creation but i think there is a new secondary bug. 

`Admin: You may not modify the permission Allow user to train and generate models for Object Detection. (Retired) while editing a Standard Profile`

I did some digging and found the API name of the permission that was referenced in the error and I searched in VS code and i dont have the "PermissionsAllowObjectDetectionTraining" permission anywhere in vscode, so I'm thinking there is a new bug.

**Comment by cesarParra** [comment]
@bacasystems-IT I ran into that last week when doing some preliminary testing for Spring 24. The permission I had to remove was called "AllowObjectDetectionTraining". See if you can find it under that name.

**Comment by bacasystems-IT** [comment]
@cesarParra, yeah i tried that...  Nothing in VS code by that name at all. and the app actually doesn't have any System Permissions in either of the two packaged perm sets all.

<img width="400" alt="Screenshot 2024-02-14 at 7 51 36 AM" src="https://github.com/forcedotcom/cli/assets/41757560/acfc26b9-3fc1-4f2d-b59b-f6c509f1927a">

**Comment by mshanemc** [comment]
closing this because the scratch org signups problem is behaving now.  

@bacasystems-IT if you've got a new bug, please open a new issue with all the specifics, probably including your scratch-def
