### ISSUE TITLE
"is not recognized as an internal or external command, operable program or batch file." This isssue comes while trying to authorize an org in vscode

### ISSUE THREAD

**Issue by Mohan-kumar-U-P** [forcedotcom/cli#2718]
Steps to reproduce:
1. Create project with manifest.
2. Auhtorize an org.
Issue comes
![vscode error](https://github.com/forcedotcom/cli/assets/106507956/0f5d5a8f-6ae5-4723-8b3e-68078a154234)

**Comment by Mohan-kumar-U-P** [comment]
im using the latest version of cli.
Output of verbose:
![image](https://github.com/forcedotcom/cli/assets/106507956/d5aa6e9e-2ae7-41af-9c86-696b401a9aef)
output of doctor command:
![image](https://github.com/forcedotcom/cli/assets/106507956/87f3291d-3ec3-4997-b894-0561153bfc9f)

**Comment by mdonnalley** [comment]
@Mohan-kumar-U-P can you provide the ouput of `sf version --verbose --json?` Thanks!

**Comment by Mohan-kumar-U-P** [comment]
@mdonnalley  This is the output of `sf version --verbose --json?`
![image](https://github.com/forcedotcom/cli/assets/106507956/00e19ff5-b644-4b10-b93f-aa5089bf8d5d)

**Comment by mdonnalley** [comment]
@Mohan-kumar-U-P I suggest uninstalling (following [these instructions](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm)) and then reinstalling the CLI

**Comment by Mohan-kumar-U-P** [comment]
Not worked, same issue coming
![image](https://github.com/forcedotcom/cli/assets/106507956/fbd2ae1f-69f6-4831-bed5-f1b6237f9199)

**Comment by iowillhoit** [comment]
Hello @Mohan-kumar-U-P, 

How are you installing the CLI? I see that you are still using the old version (`7.209.6`). That version is no longer supported. The current version of the Salesforce CLI is `sf` version `2`. The current latest release is `2.29.5`

Assuming that you installed the CLI from an installer, complete _every_ step [listed here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm#:~:text=You%20Installed%20on%20Windows%20Using%20the%20Installer) To be clear, all of these steps:
```
These steps uninstall both sfdx (v7) and sf (v1 and v2):

Select Start > Control Panel > Programs > Programs and Features.
Select @salesforce/cli, and click Uninstall.

Inside your home directory, delete these two directories:
.config\sfdx
.config\sf

If Salesforce CLI is still installed, delete these directories:
%LOCALAPPDATA%\sfdx
%LOCALAPPDATA%\sf
```

Once you have completely uninstalled (and manually cleaned up directories), download and install the new installer from here https://developer.salesforce.com/tools/salesforcecli

**Comment by Mohan-kumar-U-P** [comment]
My cli version is 2.1.7

**Comment by shetzel** [comment]
Salesforce CLI version 2.1.7 was a nightly release from July 18, 2023.  https://github.com/salesforcecli/cli/releases/tag/2.1.7

Again, please follow the instructions from this response: https://github.com/forcedotcom/cli/issues/2718#issuecomment-1965477468

You should also unset any entries in your PATH environment variables that would point to CLI v7.209.6.

**Comment by shetzel** [comment]
Re-open if there are more details or if the problem still occurs.  This is definitely an installation issue.
