### ISSUE TITLE
[Error] FieldService : externalized text label not found, section: 'SchedulingWorkspaceFilter' missing

### ISSUE THREAD

**Issue by GodertC** [forcedotcom/cli#2719]
Summary
I am encountering an error when trying to create a scratch org with Field Service enabled in the new Spring 24 release.
[Error] FieldService : externalized text label not found, section: 'SchedulingWorkspaceFilter' missing 
I have the following features and settings enabled, and everything works when I remove the settings for fieldService (except that fieldService is disabled).

Steps To Reproduce
Create a scratch with fieldService enabled

Expected result
The scratch should be created without issue and fieldService should be enabled.

Actual result
The scratch fails to create because of an error in the fieldService settings.

System Information
Github CLI is running bash with newest version of the CLI.

`
@salesforce/cli/2.27.6 linux-x64 node-v18.19.0
@oclif/plugin-autocomplete 3.0.5 (core)
@oclif/plugin-commands 3.1.1 (core)
@oclif/plugin-not-found 3.0.9 (core)
@oclif/plugin-plugins 4.1.23 (core)
@oclif/plugin-search 1.0.12 (core)
@oclif/plugin-update 4.1.8 (core)
@oclif/plugin-version 2.0.11 (core)
@oclif/plugin-warn-if-update-available 3.0.9 (core)
@salesforce/cli 2.27.6 (core)
apex 3.0.22 (core)
auth 3.3.6 (core)
deploy-retrieve 3.2.9 (core)
limits 3.1.6 (core)
org 3.3.10 (core)
packaging 2.1.4 (core)
schema 3.1.0 (core)
sobject 1.1.6 (core)
source 3.1.8 (core)
telemetry 3.1.10 (core)
templates 56.0.12 (core)
trust 3.3.4 (core)
user 3.2.6 (core)

`

**Comment by mdonnalley** [comment]
@GodertC This is likely an issue with the metadata api - your best bet is to file a support ticket so that it'll get routed to the appropriate team

**Comment by GodertC** [comment]
This was fixed after the full rollout
