### ISSUE TITLE
VR-0003 Error on scratch org creation

### ISSUE THREAD

**Issue by johnzhao9** [forcedotcom/cli#272]
### Summary

_Short summary of what is going on or to provide context_.

Trying to create a `release:"Preview"` scratch org receives this error:
```
{
    "status": 1,
    "name": "RemoteOrgSignupFailed",
    "message": "The request to create a scratch org failed with error code: VR-0003.",
    "exitCode": 1,
    "commandName": "OrgCreateCommand",
    "stack": "RemoteOrgSignupFailed: The request to create a scratch org failed with error code: VR-0003.\n    at signup.retrieveScratchOrgInfo (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/org/scratchOrgInfoApi.js:316:21)",
    "warnings": []
}
```
We suspect this error means that it couldn't find the next release (Summer '20) which is expected, because our DevHub is already on Spring '20, but we've never seen this VR-0003 error before (it was X-0002 before the better error messages came through), so we'd appreciate any confirmation that this is indeed what we thought it is.

### Steps To Reproduce:
1. Confirm PBO / DevHub org is on Spring '20

1.  Make a scratch org config file like this:
```
{
"edition":"Enterprise",
"release":"Preview",
"orgName":"testprevew"
}
```
1.  Run `sfdx force:org:create -d 1 -f test.json`

### Expected result
The scratch org gets created
 
### Actual result
An error like this:
```
ERROR running force:org:create: The request to create a scratch org failed with error code: VR-0003.
```
 
### Additional information

_ 
**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.41.0-2a5f766389 linux-x64 node-v10.15.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.14.0 (core)
├─ salesforcedx-templates 47.15.0 (core)
└─ salesforce-alm 47.13.0 (core)

sfdx-cli 7.41.0 (core)

```
**OS and version**:
```
root@e34a70d0ef2b:/#  cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by clairebianchi** [comment]
@johnzhao9 I am passing your question on to the Scratch org team. @rrmehta2 would you please take a look

**Comment by johnzhao9** [comment]
@clairebianchi Thank you!

**Comment by gitmatheus** [comment]
@johnzhao9 please double-check if your `dev hub` is a pre-release org (GS0). If so, that might be the problem. Please use a non-pre-release org as your `dev hub`, and set the scratch org `release` to `preview`.

**Comment by johnzhao9** [comment]
@toadgeek Got it, that resolves it, thank you very much!

**Comment by JodieM** [comment]
Thanks, I had this too. This was helpful.

**Comment by gitmatheus** [comment]
Nice! Glad it helped!

**Comment by ankushsalesforce** [comment]
I faced this same error and to resolve it I removed this "release":"Preview" from my 'project-scratch-def.json' file as my Prod instance has been updated to latest release available.
