### ISSUE TITLE
Issue with package creation including list views filtered on recordtype

### ISSUE THREAD

**Issue by GodertC** [forcedotcom/cli#2723]
### Summary
Creating a package with list views for knowledge that have a recordtype filter I get the following error:
(1) Knowledge__kav.Archived_Articles_x: Could not resolve list view column: RECORDTYPE

### Steps To Reproduce

Create a package with knowledge list views that include a recordtype filter

### Expected result
successfull recordtype creation

### Actual result
error as stated above

### System Information
zsh and latest salesforce cli version.

**Comment by GodertC** [comment]
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.27.6",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Darwin 22.5.0",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.23 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.27.6 (core)",
    "apex 3.0.22 (core)",
    "auth 3.3.6 (core)",
    "data 3.0.18 (core)",
    "deploy-retrieve 3.2.9 (core)",
    "info 3.0.19 (core)",
    "limits 3.1.6 (core)",
    "marketplace 1.0.20 (core)",
    "org 3.3.10 (core)",
    "packaging 2.1.8 (user)",
    "schema 3.1.0 (core)",
    "settings 2.0.21 (core)",
    "signups 1.4.22 (user)",
    "sobject 1.1.6 (core)",
    "source 3.1.8 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.12 (core)",
    "trust 3.3.4 (core)",
    "user 3.2.6 (core)"
  ]
}

**Comment by mdonnalley** [comment]
@GodertC I would take a look at the [Metadata Coverage Report](https://developer.salesforce.com/docs/metadata-coverage/60) to see if all your metadata is supported for packaging.

If it's not supported, then you're not going to be able to package it

But if everything is supported, then I would try to see if you can successfully deploy it. If you're unable to deploy it, then it's likely an issue with your metadata.

**Comment by GodertC** [comment]
Listviews are packageable and I can deploy the metadata succesfully.

**Comment by mdonnalley** [comment]
Thanks for the update. One thing you can try to help debug is use the `--preserve` flag on `package version create` which will save all your converted metadata into a temp dir. You can take a look at that to see if everything is as expected

If it is, then I'd suggest opening a support case since this isn't a CLI issue.

**Comment by thvd** [comment]
@GodertC  did you find out what caused this? We have similar problems for some of our scratch orgs when deploying to the scratch org.
