### ISSUE TITLE
Sf validate command ( without Test ) is not working as expected

### ISSUE THREAD

**Issue by thunderpycode** [forcedotcom/cli#2727]
I am running : **sf project deploy validate -d force-app -o target-org**

Even without mentioning test-level, tests are running in above command. 
<img width="778" alt="image" src="https://github.com/forcedotcom/cli/assets/45660126/4acacd16-1613-4abd-b866-48eb2f8edbd1">

**Org-Status**
![image](https://github.com/forcedotcom/cli/assets/45660126/3be783bc-6898-49b9-9416-9007dc979148)

**Verbose Output**
[verbose.log](https://github.com/forcedotcom/cli/files/14307674/verbose.log)

**Comment by thunderpycode** [comment]
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.17.14",
  "nodeVersion": "node-v20.9.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\asrivast6\\AppData\\Local\\sf\\client\\2.17.14-31db5eb",
  "shell": "C:\\Users\\asrivast6\\AppData\\Local\\Programs\\Git\\usr\\bin\\bash.exe",
  "pluginVersions": [
    "@mshanemc/plugin-streaming 1.1.7 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\shane-sfdx-plugins\\node_modules\\@mshanemc\\plugin-streaming",
    "@mshanemc/sfdx-sosl 1.1.0 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\shane-sfdx-plugins\\node_modules\\@mshanemc\\sfdx-sosl",
    "@oclif/plugin-autocomplete 3.0.1 (core)",
    "@oclif/plugin-commands 3.0.6 (core)",
    "@oclif/plugin-help 6.0.5 (core)",
    "@oclif/plugin-not-found 3.0.3 (core)",
    "@oclif/plugin-plugins 4.1.7 (core)",
    "@oclif/plugin-search 1.0.6 (core)",
    "@oclif/plugin-update 4.1.3 (core)",
    "@oclif/plugin-version 2.0.6 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.2 (core)",
    "@oclif/plugin-which 3.0.8 (core)",
    "@salesforce/cli 2.17.14 (core)",
    "@salesforce/command 5.3.9 (link) C:\\Users\\asrivast6\\node_modules\\@salesforce\\command",
    "apex 2.3.20 (core)",
    "auth 2.8.26 (core)",
    "data 2.6.3 (core)",
    "deploy-retrieve 1.20.0 (core)",
    "dev 2.1.12 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\plugin-dev",
    "env 2.1.21 (user)",
    "info 3.0.1 (core)",
    "limits 3.0.1 (core)",
    "login 2.0.1 (core)",
    "marketplace 1.0.2 (core)",
    "org 2.11.8 (core)",
    "packaging 1.27.10 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\plugin-packaging",
    "schema 3.0.1 (core)",
    "settings 2.0.2 (core)",
    "sobject 0.2.15 (core)",
    "source 2.11.0 (core)",
    "telemetry 3.1.0 (core)",
    "templates 55.5.18 (core)",
    "trust 3.0.2 (core)",
    "user 2.3.42 (core)",
    "lightning-flow-scanner 2.15.0 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\lightning-flow-scanner",
    "sfdx-mohanc-plugins 0.0.356 (link) C:\\Users\\asrivast6\\Desktop\\sfdx-mohanc-plugins",
    "shane-sfdx-plugins 4.43.0 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\shane-sfdx-plugins"
  ]
}

**Comment by thunderpycode** [comment]
<img width="770" alt="image" src="https://github.com/forcedotcom/cli/assets/45660126/29630f9e-cb2f-4ccf-bd23-ed98fe03f451">

**Comment by thunderpycode** [comment]
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.28.6",
  "nodeVersion": "node-v20.11.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\asrivast6\\AppData\\Local\\sf\\client\\2.28.6-cb38ecf",
  "shell": "C:\\Users\\asrivast6\\AppData\\Local\\Programs\\Git\\usr\\bin\\bash.exe",
  "pluginVersions": [
    "@mshanemc/plugin-streaming 1.1.7 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\shane-sfdx-plugins\\node_modules\\@mshanemc\\plugin-streaming",
    "@mshanemc/sfdx-sosl 1.1.0 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\shane-sfdx-plugins\\node_modules\\@mshanemc\\sfdx-sosl",
    "@oclif/plugin-autocomplete 3.0.7 (core)",
    "@oclif/plugin-commands 3.1.2 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.10 (core)",
    "@oclif/plugin-plugins 4.2.1 (core)",
    "@oclif/plugin-search 1.0.13 (core)",
    "@oclif/plugin-update 4.1.10 (core)",
    "@oclif/plugin-version 2.0.12 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.10 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.28.6 (core)",
    "@salesforce/command 5.3.9 (link) C:\\Users\\asrivast6\\node_modules\\@salesforce\\command",
    "apex 3.0.22 (core)",
    "auth 3.3.11 (core)",
    "data 3.0.19 (core)",
    "deploy-retrieve 3.2.11 (core)",
    "dev 2.1.12 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\plugin-dev",
    "env 3.0.17 (user)",
    "info 3.0.21 (core)",
    "limits 3.1.7 (core)",
    "marketplace 1.0.20 (core)",
    "org 3.3.11 (core)",
    "packaging 1.27.10 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\plugin-packaging",
    "schema 3.1.1 (core)",
    "settings 2.0.22 (core)",
    "sobject 1.1.9 (core)",
    "source 3.1.10 (core)",
    "telemetry 3.1.11 (core)",
    "templates 56.0.13 (core)",
    "trust 3.3.6 (core)",
    "user 3.2.7 (core)",
    "lightning-flow-scanner 2.15.0 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\lightning-flow-scanner",
    "sfdx-mohanc-plugins 0.0.356 (link) C:\\Users\\asrivast6\\Desktop\\sfdx-mohanc-plugins",
    "shane-sfdx-plugins 4.43.0 (link) C:\\Users\\asrivast6\\AppData\\Roaming\\npm\\node_modules\\shane-sfdx-plugins"
  ]
}

**Comment by mdonnalley** [comment]
@thunderpycode `sf project deploy validate` is always going to run tests since it needs tests to be run in order to get a validated deploy. The default test is level is `RunLocalTests`

**Comment by thunderpycode** [comment]
@mdonnalley but why sfdx do not work the same?

**Comment by mdonnalley** [comment]
The same is true for the sfdx variants of the deploy commands. `sf project deploy validate` was made to be more explicit about this requirement

Take a look at the description for the `--validateddeployrequestid` flag on `sfdx force source deploy`. You'll see that there's still a requirement to run tests in order to validate a deploy

```
  -q, --validateddeployrequestid=<value>  Deploy request ID of the validated deployment to run a Quick Deploy.

    Deploying a validation helps you shorten your deployment time because tests aren’t rerun. If you have a recent successful validation, you can deploy the validated components without running tests. A validation doesn’t save any components in the org. You use a
    validation only to check the success or failure messages that you would receive with an actual deployment. To validate your components, add the -c | --checkonly flag when you run "force mdapi deploy". This flag sets the checkOnly="true" parameter for your deployment.
    Before deploying a recent validation, ensure that the following requirements are met:

    1. The components have been validated successfully for the target environment within the last 10 days.

    2. As part of the validation, Apex tests in the target org have passed.

    3. Code coverage requirements are met.

    * If all tests in the org or all local tests are run, overall code coverage is at least 75%, and Apex triggers have some coverage.

    * If specific tests are run with the RunSpecifiedTests test level, each class and trigger that was deployed is covered by at least 75% individually.
```

**Comment by thunderpycode** [comment]
@mdonnalley And just FYI , it's happening in sandbox not production.

**Comment by thunderpycode** [comment]
@mdonnalley please reopen the case

**Comment by mdonnalley** [comment]
I'd like to keep the issue closed since the command is working as designed but there's an ongoing [discussion](https://github.com/forcedotcom/cli/discussions/2688) related to this if you'd like to follow that or add your thoughts there.
