### ISSUE TITLE
Error when pushing metadata to scratch org with multiple package directories

### ISSUE THREAD

**Issue by ricxsar** [forcedotcom/cli#273]
### Summary

I have a repository with 3 package directories. Visual Code detected the both metadata on those directories when issuing `force:source:status`.

When I'm trying to issue a push `force:source:push`, all metadata on those directories is included on the generated `package.xml` however some of metadata files are not included on the push and of course it will throw an error .

![image](https://user-images.githubusercontent.com/8968902/72576176-d76daf00-3909-11ea-9714-4555f005441f.png)
![image](https://user-images.githubusercontent.com/8968902/72576202-e8b6bb80-3909-11ea-81a6-ada94278bf94.png)

```
"packageDirectories": [
    {
        "path": "force-app",
        "default": true,
        "package": "npsp-sample",
        "versionName": "ver 0.1",
        "versionNumber": "0.1.0.NEXT",
        "dependencies": [
            ...
        ]
    },
    {
        "path": "npsp/pre/account_opportunity_record_types",
        "default": false,
        "package": "npsp-pre",
        "versionName": "ver 0.1",
        "versionNumber": "0.1.0.NEXT",
        "dependencies": [
            ...
        ]
    },
    {
        "path": "npsp/post/first",
        "default": false,
        "package": "npsp-post",
        "versionName": "ver 0.1",
        "versionNumber": "0.1.0.NEXT",
        "dependencies": [
            ...
        ]
    }
]
```
![image](https://user-images.githubusercontent.com/8968902/72577409-a2fbf200-390d-11ea-9002-6216d76a0fef.png)
![image](https://user-images.githubusercontent.com/8968902/72577426-b0b17780-390d-11ea-83ba-29c1003fa0bd.png)

### Steps To Reproduce:

1.  Create a project with 3 source directories
1.  Push the metadata to a scratch org.

### Expected result

It should only generate the metadata along with the metadata files

### Actual result

It generated a `package.xml` with missing metadata files

### Additional information

It will be amazing if we can choose what are the source directories we want to push like:
`sfdx force:source:push --path=force-app` so that the metadata on that directory will only be pushed

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.42.0-619ba58869 win32-x64 node-v10.15.3`
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.15.0 (core)
├─ salesforcedx-templates 47.16.0 (core)
└─ salesforce-alm 47.14.0 (core)

sfdx-cli 7.42.0 (core)
texei-sfdx-plugin 1.3.0
```
**OS and version**:
Windows 10

**Comment by clairebianchi** [comment]
@ricxsar the CLI currently does not support this use case, see https://github.com/forcedotcom/cli/issues/223
We are actively working on supporting multiple package directories in one SFDX project, we are hoping to launch this in the CLI before Summer 20
