### ISSUE TITLE
Package version create error- Admin: You may not modify the permission Allow user to train and generate models for Object Detection. (Retired) while editing a Standard Profile

### ISSUE THREAD

**Issue by ppbntl19** [forcedotcom/cli#2733]
Getting same issue while creating the package version.

Removed  "AllowObjectDetectionTraining" -Still same issue

```
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.30.5",
  "nodeVersion": "node-v20.7.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\Loaner\\AppData\\Roaming\\nvm\\v20.7.0\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.9 (core)",
    "@oclif/plugin-commands 3.1.4 (core)",
    "@oclif/plugin-help 6.0.13 (core)",
    "@oclif/plugin-not-found 3.0.11 (core)",
    "@oclif/plugin-plugins 4.2.3 (core)",
    "@oclif/plugin-search 1.0.15 (core)",
    "@oclif/plugin-update 4.1.13 (core)",
    "@oclif/plugin-version 2.0.12 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.11 (core)",
    "@oclif/plugin-which 3.1.0 (core)",
    "@salesforce/cli 2.30.5 (core)",
    "apex 3.0.24 (core)",
    "auth 3.3.12 (core)",
    "data 3.1.0 (core)",
    "deploy-retrieve 3.2.15 (core)",
    "info 3.0.26 (core)",
    "marketplace 1.0.24 (core)",
    "org 3.3.13 (core)",
    "packaging 1.25.0 (user)",
    "schema 3.1.3 (core)",
    "settings 2.0.26 (core)",
    "sobject 1.1.12 (core)",
    "source 3.1.14 (core)",
    "telemetry 3.1.12 (core)",
    "templates 56.0.15 (core)",
    "trust 3.3.9 (core)",
    "user 3.2.10 (core)",
    "@salesforce/sfdx-scanner 3.18.0 (user)",
    "sfdmu 4.32.1 (user)"
  ]
}
```      
          

`Admin: You may not modify the permission Allow user to train and generate models for Object Detection. (Retired) while editing a Standard Profile`

I did some digging and found the API name of the permission that was referenced in the error and I searched in VS code and i dont have the "AllowObjectDetectionTraining" permission anywhere in vscode, so I'm thinking there is a new bug.

_Originally posted by @bacasystems-IT in https://github.com/forcedotcom/cli/issues/2703#issuecomment-1943688907_
            

![image](https://github.com/forcedotcom/cli/assets/11989749/d3b65140-86fc-4909-be56-dd2bf5d28def)

**Comment by mdonnalley** [comment]
@ppbntl19 I would contact support to open a case. It would be rare for a CLI bug to cause the packaging commands to show that `Multiple errors occurred` message. That said, since your error is related to Profiles, you might try using the [`scopeProfiles`](https://help.salesforce.com/s/articleView?id=release-notes.rn_packaging_scope_profiles.htm&release=248&type=5) property to see if that helps.

**Comment by bacasystems-IT** [comment]
@ppbntl19  I actually have a Sev1 case with support and i was able to find the way to fix it. Can you please open a case for it. I'd recommend a sev 2 case. Tell them to reference Case 46282932 and W-15049996, The solution on how to work around is in that case and the support team can connect the cases and there is 100% a bug

**Comment by ppbntl19** [comment]
Worked after moving to a minor version increment.

**Comment by horpeyjay** [comment]
```
<userPermissions>
        <enabled>true</enabled>
        <name>AllowObjectDetectionTraining</name>
 </userPermissions>
```
    
    Find something in the profile you're working on and remove it. It should work
