### ISSUE TITLE
Getting progress bar in non-tty environment

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#274]
Our CI system has started having this output:

```
sfdx force:source:deploy -u TestEnvironment --testlevel RunLocalTests -x manifest/package.xml --checkonly

Job ID | 0Af7A00000Ou3DfSAJ
7SOURCE PROGRESS | ████████████████████████████████████████ | 0/0 Files7SOURCE PROGRESS | █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 22/978 Files7SOURCE PROGRESS | █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
```

This isn't a tty interface so this progress bar makes no sense, and I also don't understand why we started getting a progress bar out of nowhere.

each run is a clean install, here's the version:
```
sfdx-cli: Updating CLI... already on latest version: 7.42.1-e41dbeb8d9
```

**Comment by aheber** [comment]
Agreed, should have a different behavior in non-tty. My CI system doesn't report lines until a `\n` is received so dancing with the `\r` is ignored. This means that my logs are full of progress bars but also means I have no sense of progress until the action is finished.

**Comment by clairebianchi** [comment]
@AndrewRayCode we will take a look at this issue.

We launched the progress bar 2 weeks ago but it should not be affecting you in this way

**Comment by gdman** [comment]
FYI, I've raised a bug relating to progress bars in non-tty environments in the underlying library here: https://github.com/oclif/cli-ux/issues/137. In our CI environment we don't get any kind of progress bar - just deployment started, deployment finished. We are using force:mdapi:deploy but I assume it's the same for force:source:deploy.

**Comment by clairebianchi** [comment]
Please see my comment in https://github.com/forcedotcom/cli/issues/271

**Comment by mshanemc** [comment]
closing because #271 is closed
