### ISSUE TITLE
Unable to retrieve CMSComponent source

### ISSUE THREAD

**Issue by kvijay460** [forcedotcom/cli#275]
### Summary

Unable to retrieve CMSConnectSource using API Version 47 on our Sandbox.
Our Sandbox is residing in CS8.

### Steps To Reproduce:

1. sfdx force:source:retrieve -m CMSConnectSource

### Expected result

Get CMS Connect Source metadata

### Actual result

ERROR running force:source:retrieve:  Cannot read property 'metadataName' of undefined
Unable to retrieve CMSConnectSource

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version:**
sfdx --version
sfdx-cli/7.41.0 win32-x64 node-v10.16.3

**SFDX plugin Version:**
sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.2.2 (core)
generator 1.1.2 (core)
salesforcedx 47.14.0 (core)
├─ salesforcedx-templates 47.15.0 (core)
└─ salesforce-alm 47.13.0 (core)

sfdx-cli 7.41.0 (core)

**OS and version**:
Microsoft Windows 10

**Comment by clairebianchi** [comment]
@kvijay460 this sounds like the same issue as outlined here https://github.com/forcedotcom/cli/issues/151. We are having a hard time reproducing this error, would you be able to give us more information about your project setup?
