### ISSUE TITLE
Mismatched version in @salesforce/plugin-config plugin manifest. Expected: 1.2.1 Received: 1.1.6

### ISSUE THREAD

**Issue by kbojisoft** [forcedotcom/cli#2750]
Hi! I am  reviving an issue even when just trying to run sfdx update, I have uninstalled and re-installed both VS Code and the SF plugins to no avail:

>sfdx update
(node:11084) Warning: Mismatched version in @salesforce/plugin-config plugin manifest. Expected: 1.2.1 Received: 1.1.6
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
 »   Warning: Attempting to contact update site...
sfdx-cli: Updating CLI... !
 »   Error: S3 host is not reachable.

![Issues](https://github.com/forcedotcom/cli/assets/25655078/33f73cf8-2e38-4760-b91e-cf9e3390d16c)

**Comment by kbojisoft** [comment]
I can provide the output but the same error will result:

> sfdx version --verbose --json
(node:15356) Warning: Mismatched version in @salesforce/plugin-config plugin manifest. Expected: 1.2.1 Received: 1.1.6
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.     
sfdx-cli/7.82.0-52018670a1 win32-x64 node-v12.18.3

**Comment by iowillhoit** [comment]
Hello @kbojisoft, that version of the `sfdx` CLI is[ over 3 years old](https://github.com/forcedotcom/cli/blob/b01f255d5c0f54263253a33e0b7550541dfdd682/releasenotes/sfdx/v50.md?plain=1#L84) and your version of Node has been EOL for almost two years. 

Please completely uninstall the CLI using the steps [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm), this involves some manual deletion of directories. Then update your Node version to at least Node 18 and then reinstall the new `sf` CLI from https://developer.salesforce.com/tools/salesforcecli

**Comment by kbojisoft** [comment]
That worked, thank you! <3
