### ISSUE TITLE
.forceigore in submodules overrides parent

### ISSUE THREAD

**Issue by alastairbrownfairsailcom** [forcedotcom/cli#2758]
### Summary
The .forceignore in the routt folder should be respected when deploying source that includes a submodule. Instead, the .forceignore in the submodule supercedes the one in the root and therefore files matching a pattern that should be excluded are deployed to the org.

### Steps To Reproduce

1. Create an sf project with a namespace
2. Import force-di as a submodule https://github.com/apex-enterprise-patterns/force-di
3. Add force-di as a package in sfdx-project.json
4. Edit .forceignore in root folder to ignore test suite in force-di submodule
5. Create scratch org
6. Deploy source to scratch org

Repository not provided because namespace needs to be linked to devhub in order to reproduce the issue

### Expected result
Deployment should have succeeded because the test suite form the submodule should have been ignored

### Actual result
Deployment fails because classes referenced in test suite to not include the namespace prefix

### System Information
using zsh

src % sf version --verbose --json
{
  "cliVersion": "@salesforce/cli/2.7.11",
  "architecture": "darwin-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Darwin 23.2.0",
  "shell": "zsh",
  "rootPath": "/usr/local/lib/sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.6 (core)",
    "@oclif/plugin-commands 2.2.24 (core)",
    "@oclif/plugin-help 5.2.18 (core)",
    "@oclif/plugin-not-found 2.4.0 (core)",
    "@oclif/plugin-plugins 3.3.2 (core)",
    "@oclif/plugin-search 0.0.22 (core)",
    "@oclif/plugin-update 3.2.0 (core)",
    "@oclif/plugin-version 1.3.9 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.49 (core)",
    "@oclif/plugin-which 2.2.32 (core)",
    "@salesforce/cli 2.7.11 (core)",
    "apex 2.3.12 (core)",
    "auth 2.8.14 (core)",
    "data 2.5.7 (core)",
    "deploy-retrieve 1.17.6 (core)",
    "info 2.6.40 (core)",
    "limits 2.3.32 (core)",
    "login 1.2.28 (core)",
    "marketplace 0.1.1 (core)",
    "org 2.10.5 (core)",
    "packaging 1.22.2 (user)",
    "schema 2.3.24 (core)",
    "settings 1.4.27 (core)",
    "sobject 0.2.6 (core)",
    "source 2.10.32 (core)",
    "telemetry 2.3.1 (core)",
    "templates 55.5.10 (core)",
    "trust 2.6.7 (core)",
    "user 2.3.31 (core)"
  ]

```
### Additional information
sf project list ignored --source-dir ./src/force-di
Found the following ignored files:
force-di/.execanon
force-di/.forceignore
force-di/.git
force-di/.github/ISSUE_TEMPLATE/bug_report.md
force-di/.github/ISSUE_TEMPLATE/feature_request.md
force-di/.github/workflows/deploy.and.test.yml
force-di/.github/workflows/manage.sf.api.versions.yml
force-di/.gitignore
force-di/force-di/test/testSuites/force_di_teststuite.testSuite-meta.xml
alastair.brown@UKC02D649YML85 src % sf project list ignored --source-dir force-di
Found the following ignored files:
force-di/.execanon
force-di/.forceignore
force-di/.git
force-di/.github/ISSUE_TEMPLATE/bug_report.md
force-di/.github/ISSUE_TEMPLATE/feature_request.md
force-di/.github/workflows/deploy.and.test.yml
force-di/.github/workflows/manage.sf.api.versions.yml
force-di/.gitignore
force-di/force-di/test/testSuites/force_di_teststuite.testSuite-meta.xml


BUT the test suite isn't ignored

sf project deploy start -o XXXXXXX
Deploying v59.0 metadata to tYYYYYYYYYY@example.com using the v60.0 SOAP API.
Deploy ID: 0AfQz000004THzFKAW
Status: Failed | ████████████████████████████████████████ | 9/9 Components (Errors:1) | 0/0 Tests (Errors:0)

Component Failures [2]
=============================================================================
| Type  Name                Problem                                           
| ───── ─────────────────── ───────────────────────────────────────────────── 
| Error force_di_teststuite No classes found for di_BindingConfigWrapperTest. 
| Error force_di_teststuite No classes found for di_BindingConfigWrapperTest.

**Comment by alastairbrownfairsailcom** [comment]
Latest stable version of sf installed bu the problem is still there.

sf version --verbose --json                         
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.30.8",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Darwin 23.2.0",
  "rootPath": "/Users/alastair.brown/.local/share/sf/client/2.30.8-d9ea14b",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.9 (core)",
    "@oclif/plugin-commands 3.1.4 (core)",
    "@oclif/plugin-help 6.0.13 (core)",
    "@oclif/plugin-not-found 3.0.11 (core)",
    "@oclif/plugin-plugins 4.2.5 (core)",
    "@oclif/plugin-search 1.0.16 (core)",
    "@oclif/plugin-update 4.1.13 (core)",
    "@oclif/plugin-version 2.0.12 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.12 (core)",
    "@oclif/plugin-which 3.1.0 (core)",
    "@salesforce/cli 2.30.8 (core)",
    "apex 3.0.25 (core)",
    "auth 3.3.13 (core)",
    "data 3.1.1 (core)",
    "deploy-retrieve 3.2.16 (core)",
    "info 3.0.27 (core)",
    "limits 3.1.10 (core)",
    "marketplace 1.0.25 (core)",
    "org 3.3.14 (core)",
    "packaging 1.22.2 (user)",
    "schema 3.1.3 (core)",
    "settings 2.0.27 (core)",
    "sobject 1.1.13 (core)",
    "source 3.1.15 (core)",
    "telemetry 3.1.13 (core)",
    "templates 56.0.16 (core)",
    "trust 3.3.10 (core)",
    "user 3.2.11 (core)"
  ]
}

**Comment by alastairbrownfairsailcom** [comment]
I have recreated the issue here https://github.com/alastairbrownfairsailcom/sf-cli-forceignore-issue

The DoNotDeploy.cls is ignored by the .forceignore in the project root directory but this is overridden by the .forceignore in the my-submodule folder. 

This demonstrates that the issue is not linked to namespaces or submodules. However, it does prevent the use of submodules, which is the problem i am facing.

**Comment by shetzel** [comment]
This is per the design of the `@salesforce/source-deploy-retrieve` library, which traverses up from each metadata file looking for a `.forceignore` file, and stops when it finds one (and uses it).  This happens during metadata resolution.  With the command you used, (`sf project deploy start`) a `ComponentSet` is built starting with the package directory paths defined in `sfdx-project.json`.  It traverses down each path looking for metadata components to add to the `ComponentSet`, and for each metadata component it will traverse up for a forceignore file to use.

**Comment by alastairbrownfairsailcom** [comment]
Unfortunately that prevents the overriding of forceignore in submodules. I dont want to change anything in the submodule because i dont own it. This feels like backwards logic. .forceignore should be additive working down the tree, not up. Or at least there should be an option to change the behaviour.

**Comment by alastairbrownfairsailcom** [comment]
The documentation for forceignore suggests that it mimics the behaviour of gitignore. this is the behaviour that i need.

**Comment by shetzel** [comment]
>The documentation for forceignore suggests that it mimics the behaviour of gitignore.

That's in reference to the contents of the `.forceignore`, although I agree it's not clear.

>I dont want to change anything in the submodule because i dont own it.

Why is it added as a packageDirectory in your sfdx-project.json?  Is it only to include that metadata in 1 deployment?  Could you instead remove that entry from sfdx-project.json and deploy it separately?

I agree with you that the behavior of multiple `.forceignore` files in a project is not documented anywhere.  That should be addressed at a minimum.  I also agree that supporting multiple `.forceignore` files in the same way multiple `.gitignore` files works would be a better, more intuitive experience.  However, the library used for this (`@salesforce/source-deploy-retrieve`) doesn't assume the current working directory of a project so I don't think this feature would be easy to support.  I think we should move this to a discussion so that more people in the community can add their thoughts and we can prioritize it there.

**Comment by shetzel** [comment]
The documentation is being updated with how things currently work to make it more clear.

I've created this discussion for the feature: https://github.com/forcedotcom/cli/discussions/2777
