### ISSUE TITLE
Source Progress bar causes output truncation

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#276]
### Summary

Upon appearance of Source Progress bar, the remaining console output gets truncated to the window with (instead of wrapped into new line). Even output from non-sfdx commands (such as cat) gets truncated after, say, `sfdx force:source:push` (I believe the progress bar is used elsewhere).

### Steps To Reproduce:

See screenshot - note last command output was truncated.
<img width="1007" alt="Screen Shot 2020-01-21 at 5 16 38 PM" src="https://user-images.githubusercontent.com/7092409/72775523-8fd18500-3c73-11ea-8bdd-1864b524123f.png">

### Expected result

Output is wrapped just as before.

### Actual result

Output is truncated (which hides important information from compile failure and causes corrupted output for remaining commands during shell session.

### Additional information

Latest Catalina, sfdx, iterm, oh-my-zsh...
My default is iTerm + zsh, but I've tested with Terminal + bash and results were the same.

`iTerm 3.3.7`

`sfdx-cli/7.42.1-e41dbeb8d9 darwin-x64 node-v10.15.3`

```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.15.0 (47.15.0)
├─ salesforcedx-templates 47.16.0
└─ salesforce-alm 47.14.0

sfdx-cli 7.42.1 (core)
```

`Catalina 10.15.2 (19C57)`

**Comment by sjurgis** [comment]
Given other issues with progress bar, perhaps we can get env variable to disable it?

**Comment by clairebianchi** [comment]
@sjurgis Thank you for letting us know, we will take a look

**Comment by pogilvie** [comment]
@clairebianchi.   Could we please have an option to turn off the progress bar and revert back to the previous text only display?

**Comment by agoganian** [comment]
@clairebianchi Ditto, Please add an option to disable the progress bar. We're redirecting output to a log file

**Comment by clairebianchi** [comment]
We are fixing the truncation issue now and hopefully will have a fix by next week. If you run the command with --json you will not see the progress bar. What output are you using in your log file, the output form --json should provide you with the details you need.

**Comment by clairebianchi** [comment]
we have a fix for this issue and it will go out in next week's release
