### ISSUE TITLE
MODULE_NOT_FOUND] ModuleLoadError Plugin

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#2764]
### Summary

I just installed sfdx to check if the stuff I did in `@oclif/core` was working, and then I started seeing these error messages, even when just running `sf --version` or `sf --help`

<img width="1346" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/971aea26-b693-40db-8196-466b6c4fb280">
<img width="1354" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/5f5880b0-9756-49f0-b3c7-96893c6318a6">

I repeated the above steps 2 times and got the same result in both.

### Steps To Reproduce

1. install nvm v0.39.3
2. install node v18.18.0 with nvm
3. in a new terminal session, run `which sfdx`. If the result is `~/.nvm/versions/node/v18.18.0/bin/sfdx`, then do 4, else jump to 5
4. run `npm uninstall @salesforce/cli -g` or any other command to uninstall everything related to sfdx. You just want to make sure you no longer sees `~/.nvm/versions/node/v18.18.0/bin/sfdx` when running `which sfdx` or `which sf`
5. run `npm install @salesforce/cli -g` as described [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_npm)
6. run `sf --version` and verify that the error messages appear

Since in step 5 I got no error, and I did an instalattion from scratch, I believe sf package is probably missing dependencies.

### Expected result

no `MODULE_NOT_FOUND] ModuleLoadError Plugin` should appear when running sf/sfdx commands

### Actual result

multiple `MODULE_NOT_FOUND] ModuleLoadError Plugin` error messages appear, no matter which sf/sfdx command I use

### System Information

shell: `zsh`
os info: `Darwin 149877447b5f 23.4.0 Darwin Kernel Version 23.4.0: Tue Feb 13 23:56:07 PST 2024; root:xnu-10063.101.14~5/RELEASE_ARM64_T8103 arm64`

````json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.30.8",
  "nodeVersion": "node-v18.18.0",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/allanoricil/.nvm/versions/node/v18.18.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.9 (core)",
    "@oclif/plugin-commands 3.1.4 (core)",
    "@oclif/plugin-help 6.0.13 (core)",
    "@oclif/plugin-not-found 3.0.11 (core)",
    "@oclif/plugin-plugins 4.2.5 (core)",
    "@oclif/plugin-search 1.0.16 (core)",
    "@oclif/plugin-update 4.1.13 (core)",
    "@oclif/plugin-version 2.0.12 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.12 (core)",
    "@oclif/plugin-which 3.1.0 (core)",
    "@salesforce/cli 2.30.8 (core)",
    "apex 3.0.25 (core)",
    "auth 2.8.20 (link) /Users/allanoricil/plugin-auth",
    "data 3.1.1 (core)",
    "deploy-retrieve 3.2.16 (core)",
    "info 3.0.27 (core)",
    "limits 3.1.10 (core)",
    "marketplace 1.0.25 (core)",
    "org 3.3.14 (core)",
    "packaging 2.1.10 (core)",
    "schema 3.1.3 (core)",
    "settings 2.0.27 (core)",
    "sobject 1.1.13 (core)",
    "source 3.1.15 (core)",
    "telemetry 3.1.13 (core)",
    "templates 56.0.16 (core)",
    "trust 3.3.10 (core)",
    "user 3.2.11 (core)"
  ]
}
````

### Additional information

node, npm and nvm versions

<img width="1345" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/bb20f727-47ac-40d4-8ddf-6505c36af826">

after displaying these error messages, commands echo the expected output

<img width="1174" alt="image" src="https://github.com/forcedotcom/cli/assets/55927613/4859390e-ed34-4578-bb52-31eb73ce94db">

**Comment by AllanOricil** [comment]
@iowillhoit seems similar

https://github.com/forcedotcom/cli/issues/2609

**Comment by mdonnalley** [comment]
@AllanOricil Based on the error message, it looks like plugin-auth is linked to your local (based on the `Users/allanoricil/plugin-auth` file path). Since it's complaining about missing dependencies, the solution might just be to ensure the deps for plugin-auth are installed using `yarn install`

**Comment by AllanOricil** [comment]
@mdonnalley oh I forgot to unlink that dependency. I thought npm would unlink it automatically when uninstallIng a package.  Thanks for seeing that 😅
