### ISSUE TITLE
spawn EPERM error on Windows if user does not have powershell access

### ISSUE THREAD

**Issue by brytonpilling** [forcedotcom/cli#2768]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
When attempting to authorise and org on a machine that does not have Powershell access receive a spawn EPERM(1) error.

### Steps To Reproduce

Attempt the command 'sf org login web' (you do not even need any further parameters) on a machine that does not have permission to run powershell, and the error spawn EPERM(1) is received.

### Expected result
Web browser should open and allow an org to be authorised.

### Actual result
spawn EPERM (1) error message

### System Information
cmd.exe

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.30.8",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\c9003736\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.9 (core)",
    "@oclif/plugin-commands 3.1.4 (core)",
    "@oclif/plugin-help 6.0.13 (core)",
    "@oclif/plugin-not-found 3.0.11 (core)",
    "@oclif/plugin-plugins 4.2.5 (core)",
    "@oclif/plugin-search 1.0.16 (core)",
    "@oclif/plugin-update 4.1.13 (core)",
    "@oclif/plugin-version 2.0.12 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.12 (core)",
    "@oclif/plugin-which 3.1.0 (core)",
    "@salesforce/cli 2.30.8 (core)",
    "apex 3.0.25 (core)",
    "auth 3.3.13 (core)",
    "data 3.1.1 (core)",
    "deploy-retrieve 3.2.16 (core)",
    "info 3.0.27 (core)",
    "limits 3.1.10 (core)",
    "marketplace 1.0.25 (core)",
    "org 3.3.14 (core)",
    "packaging 2.1.10 (core)",
    "schema 3.1.3 (core)",
    "settings 2.0.27 (core)",
    "sobject 1.1.13 (core)",
    "source 3.1.15 (core)",
    "telemetry 3.1.13 (core)",
    "templates 56.0.16 (core)",
    "trust 3.3.10 (core)",
    "user 3.2.11 (core)"
  ]
}
```
### Additional information
Error seems to be in the @salesforce/plugin-auth/node_modules/open/index.js file, lines 171,172,173, where the command is set to powershell without checking if powershell is accessible by the user. This appears to be the cause of the issue. Unsure whether there is an option to set this to CMD if powershell is blocked?

**Comment by shetzel** [comment]
This has been reported in the past.  Unfortunately, that's not code we own.  It's the `open` library on npmjs.  See this issue report on their github repo: https://github.com/sindresorhus/open/issues/205

There might be something in that issue thread to workaround it or somehow use cmd.exe instead.  Getting powershell access is the quickest way forward though.

**Comment by shetzel** [comment]
The CLI currently uses open v9.1.0 and v10.1.0 was just released, and it looks like it addresses this.  If you want to try it out temporarily, you could modify that file you mentioned so that line 172 looks like this:

`${process.env.SYSTEMROOT || process.env.windir || 'C:\\Windows'}\\System32\\WindowsPowerShell\\v1.0\\powershell';`

**Comment by shetzel** [comment]
The library will be updated in the next CLI release candidate being promoted tomorrow, but I don't think this will solve the problem for you.  The best solution is to get access to powershell.

**Comment by brytonpilling** [comment]
Thanks Shetzel! Certainly appreciate you looking into this one. I've requested Powershell access for the device in question - so that will likely fix the issue. If I get time I'll look into whether there is anyway for me to identify if powershell access is available and submit a fix to the open library on github.

**Comment by Saipraneeth-hub** [comment]
Hi Team,

Greetings!

Can anyone confirm whether we can try downgrading to v7.10.1 since this version is available on the node's official site which includes npm of 4.2.0. We are not able to find the exact version of node v7.1.0.

As one of my customers is from the banking sector, so according to RBI guidelines they are restricted from accessing the PowerShell. So they can't give access to the PowerShell due to company policies.

On a similar issue: https://github.com/sindresorhus/open/issues/205 shared it shows one of the users has tried "downgrading to v7.1.0, and it works without giving access to PowerShell".

Thank You!

**Comment by cristiand391** [comment]
@Saipraneeth-hub that comment referst to v7.10.1 of the `open` library, not the CLI or node.
.
![Screenshot 2024-03-22 at 10 44 38](https://github.com/forcedotcom/cli/assets/6853656/dafeeb43-aed0-4cfc-af34-00407b3290ec)

sfdx is deprecated and installing a 4y old version will probably not work as expected and/or even might include vulnerable dependencies.
