### ISSUE TITLE
sf org resume sandbox doesn't authenticate to sandbox any more

### ISSUE THREAD

**Issue by azlam-abdulsalam** [forcedotcom/cli#2772]
### Summary

I  have been using sf org resume sandbox in the pipelines to authenticate to a sandbox created in an async manner for a while, especially in the context of a pipeline.  Staring yesterday, I am seeing almost all sandbox created yesterday (12/03/2024) is failing to authenticate to 

### Steps To Reproduce
1. In the first system, authenticate to Devhub using ```sf org login sfdx-url```
2. Create a sandbox using ```sf org create sandbox -n <nameOfSandbox>  -c <clonedFrom> --target-org devhub --async ```
3. Wait for till the sandbox is getting created
4. In another system, authenticate to Devhub using ```sf org login sfdx-url```
5 Execute ```sf org sandbox resume -n <nameOfSandbox>  --target-org devhub```
5. Notice it fails to authenticate

```
sfdx org resume sandbox -n 733615374 -o devhub
 Field         Value                                    
 ───────────── ──────────────────────────────────────── 
 Id            0GRPD0000001HA54AM                       
 SandboxName   733615324                                
 Status        Completed                                
 LicenseType   DEVELOPER                                
 SandboxInfoId 0GQPD0000001Ggb4AE                       
 Created Date  2024-03-13T00:17:29.000+0000             
 CopyProgress  100%                                     
 SourceId      0GQPD0000000aTl4AI                       
 Description   CI Sandboxes Auto Provisioned 
 SandboxOrg    00DVZ000000CwJZ                          
 Description   CI Sandboxes Auto Provisioned 
---------------------
Sandbox Create Stages
✓ - Pending
✓ - Processing
✓ - Activating
… - Authenticating
Run "sf org resume sandbox --job-id 0GRPD0000001HA55BM -o <devhubUser> " to check for status.
If the org is ready, checking the status also authorizes the org for use with Salesforce CLI.
Error: Process completed with exit code 68. 

```

### Expected result
Sandboxes should be successfully authenticated

### Actual result
Sandboxes are not getting authenticated, 

### System Information

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.25.7",
  "nodeVersion": "node-v20.9.0",
  "osVersion": "Darwin 23.3.0",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.17 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.25.7 (core)",
    "apex 3.0.18 (core)",
    "auth 3.3.2 (core)",
    "data 3.0.16 (core)",
    "deploy-retrieve 3.2.0 (core)",
    "info 3.0.17 (core)",
    "limits 3.1.4 (core)",
    "marketplace 1.0.16 (core)",
    "org 3.3.5 (core)",
    "packaging 2.1.1 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.17 (core)",
    "sobject 1.1.2 (core)",
    "source 3.1.5 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.10 (core)",
    "trust 3.3.2 (core)",
    "user 3.2.3 (core)",
    "sfdx-hardis 4.10.0 (user)"
  ]
}

```
### Additional information
- Adding a json flag displays it as an AuthExchangeError
- This seems to be specific to some orgs, as this behavior is not seen in other orgs

**Comment by azlam-abdulsalam** [comment]
Yes its the same behaviour with 2.30.8,  this looks like a backend issue, have seen few success
```
 sf version --verbose --json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.30.8",
  "nodeVersion": "node-v20.9.0",
  "osVersion": "Darwin 23.3.0",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.9 (core)",
    "@oclif/plugin-commands 3.1.4 (core)",
    "@oclif/plugin-help 6.0.13 (core)",
    "@oclif/plugin-not-found 3.0.11 (core)",
    "@oclif/plugin-plugins 4.2.5 (core)",
    "@oclif/plugin-search 1.0.16 (core)",
    "@oclif/plugin-update 4.1.13 (core)",
    "@oclif/plugin-version 2.0.12 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.12 (core)",
    "@oclif/plugin-which 3.1.0 (core)",
    "@salesforce/cli 2.30.8 (core)",
    "apex 3.0.25 (core)",
    "auth 3.3.13 (core)",
    "data 3.1.1 (core)",
    "deploy-retrieve 3.2.16 (core)",
    "info 3.0.27 (core)",
    "limits 3.1.10 (core)",
    "marketplace 1.0.25 (core)",
    "org 3.3.14 (core)",
    "packaging 2.1.10 (core)",
    "schema 3.1.3 (core)",
    "settings 2.0.27 (core)",
    "sobject 1.1.13 (core)",
    "source 3.1.15 (core)",
    "telemetry 3.1.13 (core)",
    "templates 56.0.16 (core)",
    "trust 3.3.10 (core)",
    "user 3.2.11 (core)",
  ]
}
```

**Comment by azlam-abdulsalam** [comment]
I think this might have to do with sandboxes spinned from a cloned sandbox, investigating..

**Comment by shetzel** [comment]
There should be some useful debug output.  Can you set `SF_LOG_LEVEL=trace` and then run the resume command with `--dev-debug` and capture the output?  If it's happening in both 2.30.8 and 2.25.7 then I think you're probably correct about this being serverside, but let's see what the debug output provides.

**Comment by azlam-abdulsalam** [comment]
@shetzel  I will get this done shortly, Looks like AuthInfo.create is the one failing with auth code exchange error

**Comment by shetzel** [comment]
@azlam-abdulsalam - if you're willing to debug the code on your machine you can follow these instructions:

Here are some steps to debug CLI commands. The instructions are specific to the auth:web:login command but you can generalize to any command. In your shell: `export NODE_OPTIONS=--inspect-brk` Open a chrome tab to: chrome://inspect (alternatively, use your preferred JS debugger and that config) run the auth:web:login command In the chrome debugger tab, click the “inspect” link. It should stop in the main entry point and give you some clues as to where the files are to put some breakpoints. Stepping through at this level will not be very productive so I would look at the file location and use it to search for a more accurate location to put breakpoints. E.g., in my case, I have an npm install of the CLI so I added `debugger;` to line 147 of webOAuthServer.js (the executeOauthRequest function) at this location: ~/.nvm/versions/node/v20.11.0/lib/node_modules/@salesforce/cli/node_modules/@salesforce/core/lib/webOAuthServer.js. Then when the debugger stops at the initial entry point, resume the script and it should open a browser tab to your login url and stop at your debugger; statement in webOAuthServer.js. Now you can step through.

**Comment by azlam-abdulsalam** [comment]
@shetzel  this is now resolved, seems like flaky Oauth Exchange from backend, a retry on the call back would be nice. It is currently hard to reproduce :(, I am closing it.
