### ISSUE TITLE
Jenkins worker has been upgraded to EKS 1.25 version on Amazon Linux 2023. Salesforce pipelines (that leverage the Jenkins worker) are failing

### ISSUE THREAD

**Issue by Rg682** [forcedotcom/cli#2775]
Jenkins worker has been upgraded to EKS 1.25 version on Amazon Linux 2023. Salesforce pipelines (that leverage the Jenkins worker) are failing

ERROR running auth:jwt:grant:  We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here's the error:Error Authentication with JWT config due to: error 25066067 :DSo Support routines:dlfcn_load:could not load the shared library

**Comment by Rg682** [comment]
The Salesforce CLI version used is 
sfdx-cli-v7.158

Steps to reproduce.    Recently the Jenkins worker has been upgraded to EKS 1.25 version. While we start the Salesforce Pipeline that uses this jenkins worker  for deploying the code to a sandbox, it fails with the mentioned error

ERROR running auth:jwt:grant: We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here's the error:Error Authentication with JWT config due to: error 25066067 :DSo Support routines:dlfcn_load:could not load the shared library

**Comment by shetzel** [comment]
That CLI version is from July 7, 2022.  You need to update to the latest version.  Here's something related to that error that might help you: https://github.com/orgs/nodejs/discussions/43184
