### ISSUE TITLE
The version number in the release notes does not match with the actual version of sf

### ISSUE THREAD

**Issue by chfosli** [forcedotcom/cli#2776]
In the release notes: 2.32.10 - https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md
The actual version: 2.32.8 - https://www.npmjs.com/package/@salesforce/cli?activeTab=versions

Same issue with 2.31. Looks fine for 2.30 and back.

**Comment by chfosli** [comment]
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.32.8",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\F158102\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.12 (core)",
    "@oclif/plugin-commands 3.2.0 (core)",
    "@oclif/plugin-help 6.0.17 (core)",
    "@oclif/plugin-not-found 3.0.14 (core)",
    "@oclif/plugin-plugins 4.3.2 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.0 (core)",
    "@oclif/plugin-version 2.0.14 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.13 (core)",
    "@oclif/plugin-which 3.1.3 (core)",
    "@salesforce/cli 2.32.8 (core)",
    "apex 3.0.26 (core)",
    "auth 3.3.21 (core)",
    "community 3.0.4 (user)",
    "data 3.1.7 (core)",
    "deploy-retrieve 3.2.27 (core)",
    "info 3.0.28 (core)",
    "limits 3.1.13 (core)",
    "marketplace 1.0.26 (core)",
    "org 3.4.1 (core)",
    "packaging 2.1.11 (core)",
    "schema 3.1.7 (core)",
    "settings 2.0.31 (core)",
    "sobject 1.1.17 (core)",
    "source 3.1.18 (core)",
    "telemetry 3.1.15 (core)",
    "templates 56.0.21 (core)",
    "trust 3.3.16 (core)",
    "user 3.3.1 (core)"
  ]
}

**Comment by jshackell-sfdc** [comment]
Eagle eyes, @chfosli !  Thanks for letting us know, I've updated the notes. 

I start writing the release notes before the RC goes out, and make a guess as to the final version number. But as you can see, I'm not always correct and I don't always remember to update the final version.  Happily, the `sf whatsnew` command, which prints out the release notes, looks for the closest match for the major/minor versions, and can handle incorrect patch numbers.  But still, we should reflect reality in the RNs, so I'll try to remember to fix it when the RC actually goes out. Cheers!
