### ISSUE TITLE
ERROR Cannot read property 'metadataName' of undefined on VsCode

### ISSUE THREAD

**Issue by MatiasRosbaco** [forcedotcom/cli#278]
Summary

I'm trying to retrieve source from org to manifest and I get the error Cannot read property 'metadataName' of undefined I'm retrieving by doing right click on manifest and selecting the option retrieve source in manifest from org and also from the sfdx force:source:retrieve

I used the extension salesforce package.xml generator to create the package.xml file

I already tried to do the command --loglevel debug because I read this should fix the issue.

command: sfdx force:source:retrieve --manifest manifest\package.xml --loglevel debug

Steps To Reproduce:

1.  Create project with manifest
2.  Configure package.xml 
3. run retrieve source

Expected result

Retrieve source from org.

 Actual result

Get the error described above

 Additional information

I'll post the package.xml code as an answer because it's 500 lines long.

Salesforce cli version: sfdx-cli/7.42.1-e41dbeb8d9 win32-x86 node-v10.15.3
Vscode version: latest version to date, can't find version.
OS: Windows 10 64 bits 
Plugins: @oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.15.0 (core)
├─ salesforcedx-templates 47.16.0 (core)
└─ salesforce-alm 47.14.0 (core)

sfdx-cli 7.42.1 (core)
PS D:\Program Files (x86)\Microsoft VS Code\Uat 3>

**Comment by MatiasRosbaco** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>*</members>
		<name>ApexClass</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexComponent</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexPage</name>
	</types>
	<types>
		<members>*</members>
		<name>ApexTrigger</name>
	</types>
	<types>
		<members>*</members>
		<name>AppMenu</name>
	</types>
	<types>
		<members>*</members>
		<name>AutoResponseRules</name>
	</types>
	<types>
		<members>*</members>
		<name>Certificate</name>
	</types>
	<types>
		<members>*</members>
		<name>CleanDataService</name>
	</types>
	<types>
		<members>*</members>
		<name>Community</name>
	</types>
	<types>
		<members>*</members>
		<name>ConnectedApp</name>
	</types>
	<types>
		<members>*</members>
		<name>ContentAsset</name>
	</types>
	<types>
		<members>*</members>
		<name>CorsWhitelistOrigin</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomApplication</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomApplicationComponent</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomFeedFilter</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomHelpMenuSection</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomLabels</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomMetadata</name>
	</types>
	<types>
		<members>Account</members>
		<members>AccountContactRelation</members>
		<members>AccountContactRole</members>
		<members>Activity</members>
		<members>Asset</members>
		<members>AssetRelationship</members>
		<members>AssistantProgress</members>
		<members>AuthorizationForm</members>
		<members>AuthorizationFormConsent</members>
		<members>AuthorizationFormDataUse</members>
		<members>AuthorizationFormText</members>
		<members>Banco__c</members>
		<members>Caja__c</members>
		<members>Campaign</members>
		<members>CampaignMember</members>
		<members>Case</members>
		<members>CaseContactRole</members>
		<members>Catalog_Line_Item__c</members>
		<members>Catalog_Order__c</members>
		<members>Catalog_Template__c</members>
		<members>Certificacion__c</members>
		<members>Certificacion_detalle__c</members>
		<members>ChatterActivity</members>
		<members>Cheque__c</members>
		<members>Cobro_unidad__c</members>
		<members>CollaborationGroup</members>
		<members>CollaborationGroupMember</members>
		<members>CommSubscription</members>
		<members>CommSubscriptionChannelType</members>
		<members>Concepto__c</members>
		<members>Contact</members>
		<members>ContactPointTypeConsent</members>
		<members>ContentVersion</members>
		<members>Contract</members>
		<members>ContractContactRole</members>
		<members>Contrato__c</members>
		<members>Control_documentacion__c</members>
		<members>Cronograma_entrega_items_OC__c</members>
		<members>Cuenta_bancaria__c</members>
		<members>DataUseLegalBasis</members>
		<members>DataUsePurpose</members>
		<members>DuplicateRecordItem</members>
		<members>DuplicateRecordSet</members>
		<members>EmailMessage</members>
		<members>EngagementChannelType</members>
		<members>Event</members>
		<members>ExchangeUserMapping</members>
		<members>Expensa__c</members>
		<members>Expensa_gasto_general__c</members>
		<members>Expensa_unidad__c</members>
		<members>ExpressionFilter</members>
		<members>ExpressionFilterCriteria</members>
		<members>ExternalEventMapping</members>
		<members>Factura__c</members>
		<members>Factura_item__c</members>
		<members>FeedItem</members>
		<members>ForecastingAdjustment</members>
		<members>ForecastingCategoryMapping</members>
		<members>ForecastingOwnerAdjustment</members>
		<members>ForecastingQuota</members>
		<members>ForecastingTypeToCategory</members>
		<members>Formula_mayor_costo__c</members>
		<members>Gantt__c</members>
		<members>Hipoteca__c</members>
		<members>Historico_Unidad__c</members>
		<members>Hito__c</members>
		<members>Idea</members>
		<members>Image</members>
		<members>Indicador__c</members>
		<members>Indicador_valor__c</members>
		<members>Individual</members>
		<members>Informe_avance__c</members>
		<members>Intereses_del_publico__c</members>
		<members>Item_orden_de_compra__c</members>
		<members>Lead</members>
		<members>Lote__c</members>
		<members>MC4SF__MC_Campaign_Hourly_Stats__c</members>
		<members>MC4SF__MC_Campaign__c</members>
		<members>MC4SF__MC_Interest_Group__c</members>
		<members>MC4SF__MC_Interest_Grouping__c</members>
		<members>MC4SF__MC_List__c</members>
		<members>MC4SF__MC_Merge_Variable__c</members>
		<members>MC4SF__MC_Query_Filter__c</members>
		<members>MC4SF__MC_Query__c</members>
		<members>MC4SF__MC_Static_Segment__c</members>
		<members>MC4SF__MC_Subscriber_Activity__c</members>
		<members>MC4SF__MC_Subscriber__c</members>
		<members>Macro</members>
		<members>MacroAction</members>
		<members>MacroInstruction</members>
		<members>MacroUsage</members>
		<members>Moneda__c</members>
		<members>Moneda_cotizacion__c</members>
		<members>Movimiento_de_caja__c</members>
		<members>Objetivo_De_venta__c</members>
		<members>Objetivo_del_mes__c</members>
		<members>Obra__c</members>
		<members>Opportunity</members>
		<members>OpportunityCompetitor</members>
		<members>OpportunityContactRole</members>
		<members>OpportunityLineItem</members>
		<members>Orden_de_compra__c</members>
		<members>Orden_de_compra_detalle_certificado__c</members>
		<members>Orden_de_compra_entrega__c</members>
		<members>Orden_de_compra_plan_de_pago__c</members>
		<members>Orden_de_pago__c</members>
		<members>Order</members>
		<members>OrderItem</members>
		<members>OrgMetricScanResult</members>
		<members>OrgMetricScanSummary</members>
		<members>Pago_factura__c</members>
		<members>Pagos_hipoteca__c</members>
		<members>PartnerRole</members>
		<members>PartyConsent</members>
		<members>PersonAccount</members>
		<members>Plan_de_pago_historico__c</members>
		<members>Planificacion_avance__c</members>
		<members>Presupuesto_base__c</members>
		<members>Presupuesto_detalle__c</members>
		<members>Pricebook2</members>
		<members>PricebookEntry</members>
		<members>Product2</members>
		<members>ProfileSkill</members>
		<members>ProfileSkillEndorsement</members>
		<members>ProfileSkillUser</members>
		<members>PromptAction</members>
		<members>Propietarios_adicionales__c</members>
		<members>Proyecto_comercializador__c</members>
		<members>Proyecto_publico_target__c</members>
		<members>Proyecto_punto_de_interes__c</members>
		<members>Publico_target__c</members>
		<members>Publico_target_interes__c</members>
		<members>Punto_de_interes__c</members>
		<members>QuickText</members>
		<members>QuickTextUsage</members>
		<members>Quote</members>
		<members>QuoteLineItem</members>
		<members>Recibo__c</members>
		<members>Recommendation</members>
		<members>RecordAction</members>
		<members>RecordMergeHistory</members>
		<members>Remito__c</members>
		<members>Responsable__c</members>
		<members>Rubro__c</members>
		<members>Scorecard</members>
		<members>ScorecardAssociation</members>
		<members>ScorecardMetric</members>
		<members>Site</members>
		<members>SocialPersona</members>
		<members>SocialPost</members>
		<members>Solution</members>
		<members>StreamActivityAccess</members>
		<members>StreamingChannel</members>
		<members>Tarea__c</members>
		<members>Task</members>
		<members>Topic</members>
		<members>TopicAssignment</members>
		<members>Unidad__c</members>
		<members>Unidad_arreglo__c</members>
		<members>User</members>
		<members>WorkBadge</members>
		<members>WorkBadgeDefinition</members>
		<members>WorkThanks</members>
		<name>CustomObject</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomObjectTranslation</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomPageWebLink</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomPermission</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomSite</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomTab</name>
	</types>
	<types>
		<members>*</members>
		<name>DataCategoryGroup</name>
	</types>
	<types>
		<members>*</members>
		<name>DelegateGroup</name>
	</types>
	<types>
		<members>*</members>
		<name>DuplicateRule</name>
	</types>
	<types>
		<members>*</members>
		<name>EclairGeoData</name>
	</types>
	<types>
		<members>EmailToSalesforce</members>
		<name>EmailServicesFunction</name>
	</types>
	<types>
		<members>Case</members>
		<name>EscalationRules</name>
	</types>
	<types>
		<members>*</members>
		<name>ExternalDataSource</name>
	</types>
	<types>
		<members>*</members>
		<name>ExternalServiceRegistration</name>
	</types>
	<types>
		<members>*</members>
		<name>FlexiPage</name>
	</types>
	<types>
		<members>*</members>
		<name>Flow</name>
	</types>
	<types>
		<members>*</members>
		<name>FlowCategory</name>
	</types>
	<types>
		<members>*</members>
		<name>FlowDefinition</name>
	</types>
	<types>
		<members>*</members>
		<name>GlobalValueSet</name>
	</types>
	<types>
		<members>*</members>
		<name>GlobalValueSetTranslation</name>
	</types>
	<types>
		<members>*</members>
		<name>Group</name>
	</types>
	<types>
		<members>*</members>
		<name>HomePageComponent</name>
	</types>
	<types>
		<members>*</members>
		<name>HomePageLayout</name>
	</types>
	<types>
		<members>*</members>
		<name>InstalledPackage</name>
	</types>
	<types>
		<members>*</members>
		<name>Layout</name>
	</types>
	<types>
		<members>LeadConvertSettings</members>
		<name>LeadConvertSettings</name>
	</types>
	<types>
		<members>Rosbacopartners</members>
		<name>Letterhead</name>
	</types>
	<types>
		<members>*</members>
		<name>LightningBolt</name>
	</types>
	<types>
		<members>*</members>
		<name>LightningComponentBundle</name>
	</types>
	<types>
		<members>*</members>
		<name>LightningExperienceTheme</name>
	</types>
	<types>
		<members>news</members>
		<name>ManagedContentType</name>
	</types>
	<types>
		<members>*</members>
		<name>MatchingRules</name>
	</types>
	<types>
		<members>*</members>
		<name>NamedCredential</name>
	</types>
	<types>
		<members>*</members>
		<name>NetworkBranding</name>
	</types>
	<types>
		<members>*</members>
		<name>PathAssistant</name>
	</types>
	<types>
		<members>*</members>
		<name>PermissionSet</name>
	</types>
	<types>
		<members>*</members>
		<name>PlatformCachePartition</name>
	</types>
	<types>
		<members>*</members>
		<name>PostTemplate</name>
	</types>
	<types>
		<members>*</members>
		<name>Profile</name>
	</types>
	<types>
		<members>*</members>
		<name>ProfilePasswordPolicy</name>
	</types>
	<types>
		<members>*</members>
		<name>ProfileSessionSetting</name>
	</types>
	<types>
		<members>*</members>
		<name>Queue</name>
	</types>
	<types>
		<members>*</members>
		<name>QuickAction</name>
	</types>
	<types>
		<members>*</members>
		<name>RecommendationStrategy</name>
	</types>
	<types>
		<members>*</members>
		<name>RecordActionDeployment</name>
	</types>
	<types>
		<members>MC4SF__MailChimpOAuth</members>
		<members>MC4SF__MailChimp_DataCenter_1</members>
		<members>MC4SF__MailChimp_DataCenter_10</members>
		<members>MC4SF__MailChimp_DataCenter_11</members>
		<members>MC4SF__MailChimp_DataCenter_12</members>
		<members>MC4SF__MailChimp_DataCenter_13</members>
		<members>MC4SF__MailChimp_DataCenter_14</members>
		<members>MC4SF__MailChimp_DataCenter_15</members>
		<members>MC4SF__MailChimp_DataCenter_16</members>
		<members>MC4SF__MailChimp_DataCenter_17</members>
		<members>MC4SF__MailChimp_DataCenter_18</members>
		<members>MC4SF__MailChimp_DataCenter_19</members>
		<members>MC4SF__MailChimp_DataCenter_2</members>
		<members>MC4SF__MailChimp_DataCenter_20</members>
		<members>MC4SF__MailChimp_DataCenter_21</members>
		<members>MC4SF__MailChimp_DataCenter_22</members>
		<members>MC4SF__MailChimp_DataCenter_23</members>
		<members>MC4SF__MailChimp_DataCenter_24</members>
		<members>MC4SF__MailChimp_DataCenter_25</members>
		<members>MC4SF__MailChimp_DataCenter_26</members>
		<members>MC4SF__MailChimp_DataCenter_27</members>
		<members>MC4SF__MailChimp_DataCenter_28</members>
		<members>MC4SF__MailChimp_DataCenter_29</members>
		<members>MC4SF__MailChimp_DataCenter_3</members>
		<members>MC4SF__MailChimp_DataCenter_30</members>
		<members>MC4SF__MailChimp_DataCenter_4</members>
		<members>MC4SF__MailChimp_DataCenter_5</members>
		<members>MC4SF__MailChimp_DataCenter_6</members>
		<members>MC4SF__MailChimp_DataCenter_7</members>
		<members>MC4SF__MailChimp_DataCenter_8</members>
		<members>MC4SF__MailChimp_DataCenter_9</members>
		<members>googleapis</members>
		<name>RemoteSiteSetting</name>
	</types>
	<types>
		<members>*</members>
		<name>ReportType</name>
	</types>
	<types>
		<members>*</members>
		<name>Role</name>
	</types>
	<types>
		<members>*</members>
		<name>SamlSsoConfig</name>
	</types>
	<types>
		<members>*</members>
		<name>Scontrol</name>
	</types>
	<types>
		<members>Account</members>
		<members>Actions</members>
		<members>Activities</members>
		<members>Address</members>
		<members>Analytics</members>
		<members>Apex</members>
		<members>AppExperience</members>
		<members>Archive</members>
		<members>Blockchain</members>
		<members>BusinessHours</members>
		<members>Campaign</members>
		<members>Case</members>
		<members>Chatter</members>
		<members>ChatterEmailsMD</members>
		<members>Communities</members>
		<members>Company</members>
		<members>ConnectedApp</members>
		<members>Content</members>
		<members>Contract</members>
		<members>Currency</members>
		<members>Deployment</members>
		<members>DevHub</members>
		<members>Discovery</members>
		<members>EAC</members>
		<members>EmailAdministration</members>
		<members>EmailIntegration</members>
		<members>EmailTemplate</members>
		<members>EncryptionKey</members>
		<members>EnhancedNotes</members>
		<members>Essentials</members>
		<members>Event</members>
		<members>ExperienceBundle</members>
		<members>ExternalServices</members>
		<members>FileUploadAndDownloadSecurity</members>
		<members>FilesConnect</members>
		<members>Flow</members>
		<members>Forecasting</members>
		<members>Formula</members>
		<members>GoogleApps</members>
		<members>Ideas</members>
		<members>Industries</members>
		<members>InvocableAction</members>
		<members>IsvHammer</members>
		<members>Language</members>
		<members>LeadConfig</members>
		<members>LightningExperience</members>
		<members>Macro</members>
		<members>MapsAndLocation</members>
		<members>Mobile</members>
		<members>MyDomain</members>
		<members>Name</members>
		<members>Notifications</members>
		<members>ObjectLinking</members>
		<members>OmniChannel</members>
		<members>Opportunity</members>
		<members>Order</members>
		<members>Org</members>
		<members>OrgPreference</members>
		<members>Pardot</members>
		<members>PardotEinstein</members>
		<members>PartyDataModel</members>
		<members>PathAssistant</members>
		<members>Picklist</members>
		<members>PlatformEncryption</members>
		<members>Privacy</members>
		<members>Product</members>
		<members>Quote</members>
		<members>RecordPage</members>
		<members>RetailExecution</members>
		<members>Schema</members>
		<members>Search</members>
		<members>Security</members>
		<members>Sharing</members>
		<members>Site</members>
		<members>SocialCustomerService</members>
		<members>SocialProfile</members>
		<members>Survey</members>
		<members>SystemNotification</members>
		<members>Trailhead</members>
		<members>TrialOrg</members>
		<members>UserEngagement</members>
		<members>UserInterface</members>
		<members>UserManagement</members>
		<members>Voice</members>
		<members>WorkDotCom</members>
		<name>Settings</name>
	</types>
	<types>
		<members>*</members>
		<name>SharingRules</name>
	</types>
	<types>
		<members>*</members>
		<name>SiteDotCom</name>
	</types>
	<types>
		<members>*</members>
		<name>StandardValueSetTranslation</name>
	</types>
	<types>
		<members>*</members>
		<name>StaticResource</name>
	</types>
	<types>
		<members>*</members>
		<name>SynonymDictionary</name>
	</types>
	<types>
		<members>*</members>
		<name>TopicsForObjects</name>
	</types>
	<types>
		<members>*</members>
		<name>Workflow</name>
	</types>
	<version>47.0</version>
</Package>

**Comment by MatiasRosbaco** [comment]
[package.zip](https://github.com/forcedotcom/cli/files/4097596/package.zip)

**Comment by mshanemc** [comment]
Can you verify this still happens on current versions?  I can't figure out how to replicate it , and we swapped the retrieve command's library so it should be very different (you might get a good error message now).
