### ISSUE TITLE
SF SFDX cli do not retrieve new metadata from scratch org.

### ISSUE THREAD

**Issue by viktor-saranchuk** [forcedotcom/cli#2782]
### Summary

The issue looks similiar to https://github.com/forcedotcom/salesforcedx-vscode/issues/1175

### Steps To Reproduce:

1.  Create Project, DevHub org, Scratch org
2. Create field in Custom Object and try retrieve it via sf or sfdx

Record Types and Layouts with references to the field retrieved.

the commands I used

`sf project retrieve start -m CustomField:Channel__c.EPRNumberStatus__c`
`sfdx force:source:retrieve -m CustomField:Channel__c.EPRNumberStatus__c`
`sf project retrieve start`

the last one retrieve Record Types and Page Layouts with reference and not the field itself.

To solve it I created an empty file with name in the object's fields folder EPRNumberStatus__c.field-meta.xml
and retrieved it via plugin.
But the bug persists. I hope you will solve it.

### Expected result

The field is retrieved

### Actual result

Warning: Nothing retrieved

### Additional information

**Salesforce Extension Version in VS Code**: do not use extension

**SFDX CLI Version**: @salesforce/cli/2.32.8 win32-x64 node-v20.11.1

**OS and version**: Microsoft Windows 11 Enterprise (10.0.22631 Build 22631)
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/40137179/c141b416-b99b-48cb-9b63-7c26160a646e)

**VS Code version**: 1.87.2
![image](https://github.com/forcedotcom/salesforcedx-vscode/assets/40137179/e5dd9214-0eb0-4659-9c4e-b425a70932c1)

**Comment by daphne-sfdc** [comment]
Hi @viktor-saranchuk, I'm transferring this issue over to the CLI team, as it's an issue with the CLI and not the Salesforce Extensions for VSCode.

**Comment by shetzel** [comment]
@viktor-saranchuk - I tried to reproduce this with CLI v2.41.8 but it retrieves the CustomField just fine.  Are there more details to reproduce this?  I would check your `.forceignore` file to see if there are entries that would prevent certain things from being retrieved.

**Comment by kented** [comment]
In case it helps anyone, I was encountering this issue and was eventually able to retrieve the metadata I needed by executing the following in a unix terminal: 
```
touch <metadata-path>
sf project retrieve start -d <metadata-path> --ignore-conflicts
```
