### ISSUE TITLE
Cannot deploy Active User Access Policies

### ISSUE THREAD

**Issue by petter-eikeland** [forcedotcom/cli#2784]
### Summary
When trying to deploy an Active User Access Policy that I just retrieved using SF CLI, I get the following error: 
```
Component Failures [1]
==================================================================================================
| Type  Name Problem                                                                   Line:Column 
| ───── ──── ───────────────────────────────────────────────────────────────────────── ─────────── 
| Error Test You cannot set a policy as active without at least 1 filter and 1 action.
```
It is unclear whether this is a MDAPI or SF CLI issue as the filter and action are both present in the metadata. 

### Steps To Reproduce
[dreamhouse-lwc](https://github.com/petter-eikeland/dreamhouse-lwc/tree/main/issues/user-access-policy-deploy-bug)
1. Deploy this directory to a scratch org or sandbox with User Access Policies enabled

Alternatively:
1. Enable User Access Policies https://help.salesforce.com/s/articleView?id=sf.users_enable_access_policy.htm&type=5

1. Create an empty Permission Set Group (Name = PSG) and custom field on User (NeedsAccess__c)

1. Create a user Access Policy (name = Test) assigning PSG if User.Profile = Standard User and NeedsAccess__c=True and activate it

1. Retrieve using SF CLI

1. Duplicate User Access Policy (name = Test2)

1. Deploy the duplicated User Access Policy (name = Test2)

### Expected result
User Access Policy successfully created

### Actual result
```
Component Failures [1]
==================================================================================================
| Type  Name Problem                                                                   Line:Column 
| ───── ──── ───────────────────────────────────────────────────────────────────────── ─────────── 
| Error Test You cannot set a policy as active without at least 1 filter and 1 action.
```
And this was when deploying the exact same User Access Policy as retrieved. 

### System Information

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.34.6",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/peikeland/.local/share/sf/client/2.34.6-368594f",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.0 (core)",
    "@oclif/plugin-help 6.0.18 (core)",
    "@oclif/plugin-not-found 3.0.14 (core)",
    "@oclif/plugin-plugins 4.3.8 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.0 (core)",
    "@oclif/plugin-version 2.0.14 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.14 (core)",
    "@oclif/plugin-which 3.1.5 (core)",
    "@salesforce/cli 2.34.6 (core)",
    "1commerce 0.0.10 (user)",
    "apex 3.0.31 (core)",
    "auth 3.3.26 (core)",
    "community 3.0.27 (user)",
    "data 3.1.11 (core)",
    "deploy-retrieve 3.2.35 (core)",
    "info 3.0.33 (core)",
    "limits 3.1.14 (core)",
    "marketplace 1.0.29 (core)",
    "org 3.5.0 (core)",
    "packaging 2.1.12 (user)",
    "schema 3.1.9 (core)",
    "settings 2.0.31 (core)",
    "signups 2.0.29 (user)",
    "sobject 1.1.20 (core)",
    "source 3.1.22 (core)",
    "telemetry 3.1.17 (core)",
    "templates 56.0.23 (core)",
    "trust 3.3.17 (core)",
    "user 3.3.4 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.2.0 (user)",
    "sfdmu 4.33.4 (user)",
    "sfdx-browserforce-plugin 4.1.0 (user)"
  ]
}
```

### Additional information

Since the Filters and Action are both present in the metadata, I assume this could be both be an SF CLI issue and a MDAPI issue.

**Comment by petter-eikeland** [comment]
It is possible to first deploy it by setting `<status>Design</status>`.
And then activating it by updating the status to Active and deploying it again

**Comment by petter-eikeland** [comment]
Response from Salesforce Support:

"You cannot set a policy as active without at least 1 filter and 1 action", this issue has been identified as a bug at our end and will be fixed soon, for now as a workaround product team sudeployingo deploy the "User Access Policy" with the status "Design", So please try to deploy the User Access Policy with the status 'Design' instead of 'Active'."

**Comment by TonyWhiteSMS** [comment]
So this error occurs when you try to deploy to an env that already has the active rule, even though it is not being modified.  So if you want to do a full deployment from GIT and run tests for example as part of a CI process it will fail.

Or post refresh you want to do a full deployment to an org that has the rule already it will also fail unless you deactivate the User Access policy.

**Comment by petter-eikeland** [comment]
Hi @TonyWhiteSMS. Bug was "fixed", according to Salesforce Support:
"from the summer 24 release we will no longer error for deploying Active user access policies and instead automatically set the Status field to DESIGN"

**Comment by TonyWhiteSMS** [comment]
Hmm well guess I might need to raise a case with SF
<img width="1282" alt="image" src="https://github.com/forcedotcom/cli/assets/12590114/ce9bdc43-e88a-4e4c-b408-436553d34306">
This was run from a GitHub action using the SF CLI:
`sf project deploy start --manifest ./package/package/package.xml  --test-level RunSpecifiedTests --tests GlobalUtilityTest --target-org *** --wait 10000  --verbose --json > deploy-result.json`

**Comment by TonyWhiteSMS** [comment]
Deactivated it in the org, try again and get a new error:
insufficient access rights on cross-reference id

**Comment by TonyWhiteSMS** [comment]
Case raised with SF and they are again investigating this issue.

Workaround atm is to disable it in the org before deployment.

**Comment by TonyWhiteSMS** [comment]
Well the answer I have just been given is that it is by design, so no use checking in User Access Policies for deployment.

> We got a confirmation from product team that-
> 
> This is by design, user access policies cannot be deployed in Active state,
> We don't allow editing criteria for an Active user access policy, so it must be deactivated first. When it comes to deployments, they must be deployed in an inactive state and then activated.

**Comment by petter-eikeland** [comment]
It is just annoying. Why shouldn't we be allowed to deploy it in an active state? Or edit the criterias? Same with Duplicate Rules. Should data & access integrity be compromised just because they don't "allow" updating evaluation criterias...

**Comment by TonyWhiteSMS** [comment]
Yep, flows are the same, we have the option to deploy them as active in production, sandboxes deploy as active by default.
