### ISSUE TITLE
❗️❗️ `sf org login web` command may fail when used with Google Chrome `v123`

### ISSUE THREAD

**Issue by VivekMChawla** [forcedotcom/cli#2785]
We have received reports that a recent update to Google Chrome (Chromedriver `v123`) may cause issues when authorizing orgs using the `sf org login web` command in combination with Google Chrome.  

The error reported is `Error (1): Invalid request method: OPTIONS`, which occurs after executing `sf org login web`. 

As a workaround, affected users can temporarily switch to a different browser while we investigate the issue. For example, if Chrome is your default browser, you can modify the `sf org login web` command as follows:
```
sf org login web -b firefox -a NewAuthenticatedOrg
```
Thanks for your patience as we work on a fix.

**Comment by cristiand391** [comment]
We got a fix for this in latest-rc sf v2.34.7, see install instructions if you want to give it a try:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_rc.htm

or wait until it's promoted to stable next Wednesday.

**Comment by mshanemc** [comment]
This is resolved since 2.34.7 is now latest.  If you have the issue, update your CLI.
