### ISSUE TITLE
salesforce-alm package is deprecated 

### ISSUE THREAD

**Issue by svishalkumar06** [forcedotcom/cli#2787]
Hi,

Previously we were using sfdx-cli V7 Now we have migrated to @salesforce/cli V2 version.

So previously we were using a salesforce-alm and salesforcedx packages in sfdx-cli.

But In V2 version of salesforce cli those  salesforce-alm and salesforcedx packages are deprecated. So what is the replacement for those functionalities ?

We were using following functionality from salesforce-alm package -

getting getMetadataTypeFromSourcePath from require('salesforce-alm/dist/lib/source/metadataTypeFactory')
getting metadataRegistry from require('salesforce-alm/dist/lib/source/metadataRegistry')
getting srcDevUtil from require('salesforce-alm/dist/lib/core/srcDevUtil')

How should we use these functionality in new salesforce cli package (@salesforce/cli) ?

**Comment by svishalkumar06** [comment]
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.17.14",
  "nodeVersion": "node-v20.11.0",
  "osVersion": "Windows_NT 10.0.22000",
  "rootPath": "C:\\Users\\vishal.r.kumar.singh\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.1 (core)",
    "@oclif/plugin-commands 3.0.6 (core)",
    "@oclif/plugin-help 6.0.5 (core)",
    "@oclif/plugin-not-found 3.0.3 (core)",
    "@oclif/plugin-plugins 4.1.7 (core)",
    "@oclif/plugin-search 1.0.6 (core)",
    "@oclif/plugin-update 4.1.3 (core)",
    "@oclif/plugin-version 2.0.6 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.2 (core)",
    "@oclif/plugin-which 3.0.8 (core)",
    "@salesforce/cli 2.17.14 (core)",
    "apex 2.3.20 (core)",
    "auth 2.8.26 (core)",
    "data 2.6.3 (core)",
    "deploy-retrieve 1.20.0 (core)",
    "dev 2.1.12 (user)",
    "info 3.0.1 (core)",
    "limits 3.0.1 (core)",
    "login 2.0.1 (core)",
    "marketplace 1.0.2 (core)",
    "org 2.11.8 (core)",
    "schema 3.0.1 (core)",
    "settings 2.0.2 (core)",
    "sobject 0.2.15 (core)",
    "source 2.11.0 (core)",
    "telemetry 3.1.0 (core)",
    "templates 55.5.18 (core)",
    "trust 3.0.2 (core)",
    "user 2.3.42 (core)"
  ]
}

**Comment by svishalkumar06** [comment]
Hi, 

We have not upgraded our node project to the ESM Module, we are using the Common JS Module for now for that reason we are using salesforce cli version 2.17.14.

We are using V2 commands and cli So please suggest us how can we use salesforce-alm libraries in V2 Salesforce cli.

**Comment by cristiand391** [comment]
Hey, for the first two you should use the SDR library:
https://github.com/forcedotcom/source-deploy-retrieve

and sfdx-core for the last one:
https://github.com/forcedotcom/sfdx-core

note that salesforce-alm was used by commands back then and there might not be 1-1 equivalients in SDR/sfdx-core

**Comment by svishalkumar06** [comment]
@cristiand391 Can you suggest If we continue to use salesforce-alm libraries in our project as there is no 1-1 equivalents replacement Is there will be an issue in the future?

**Comment by cristiand391** [comment]
@svishalkumar06 I would suggest moving to SDR and sfdx-core. 
If you can't find a speicfic replacement in the libraries you can post here and we might be able to help: https://github.com/forcedotcom/cli/discussions/categories/q-a

> Is there will be an issue in the future?

yeah, outdated dependencies might start to notice in the future (salesforce-alm was using SDR v7, we are at SDR v10 now), also could break in any node update if it was using a deprecated API.
