### ISSUE TITLE
CLI Error

### ISSUE THREAD

**Issue by Allamyrat0906** [forcedotcom/cli#2788]
I downloaded salesforce  CLI for windows 
and installed 
but  after finished setup i get error this "PATH not updated ?
"

**Comment by cristiand391** [comment]
questions:
1) can you share a screenshot of where do you get the error?
2) have you checked the `update PATH` checkbox when installing it?
3) have you tried uninstalling and reinstalling it again?

**Comment by AllanOricil** [comment]
if your error message was something like this [this](https://github.com/forcedotcom/cli/issues/1500), you will have to manually add the cli bin path in the PATH env var, after removing enough characters from PATH.
