### ISSUE TITLE
"sfdx commands --json" returns incorrect flag types

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#279]
### Summary

Flags either say their type is boolean or option, regardless of what type the actually are.

### Steps To Reproduce:

1.  `sfdx commands --json`

### Expected result
flag types from https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_customize_parameters_types.htm

example: scrolling down to apex:file:execute 
``` json
"apexcodefile": {
        "name": "apexcodefile",
        "type": "filepath",
        "char": "f",
        "description": "path to a local file containing Apex code",
        "hidden": false,
        "required": false
      }
```
### Actual result

``` json
"apexcodefile": {
        "name": "apexcodefile",
        "type": "option",
        "char": "f",
        "description": "path to a local file containing Apex code",
        "hidden": false,
        "required": false
      }
```
### Additional information

osx/catalina
$ sfdx version
sfdx-cli/7.41.0 darwin-x64 node-v12.14.0
$ sfdx plugins
@mshanemc/sfdx-migration-automatic 0.2.1 (link) /Users/shane.mclaughlin/code/sfdx-migration-automatic
@oclif/plugin-autocomplete 0.1.5
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

salesforcedx 48.0.9 (pre-release)
├─ salesforcedx-templates 48.0.7
└─ salesforce-alm 48.0.9

shane-sfdx-plugins 4.14.5 (link) /Users/shane.mclaughlin/code/shane-sfdx-plugins

**Comment by clairebianchi** [comment]
@mshanemc thank you for the heads up we will take a look

**Comment by iowillhoit** [comment]
See https://github.com/oclif/core/pull/717#issuecomment-1648479654
