### ISSUE TITLE
Unable to Retrieve Manually Created Groups and Queues Using Source

### ISSUE THREAD

**Issue by mgalalm** [forcedotcom/cli#2793]
### Summary
When attempting to retrieve manually created groups and queues using the source, I encountered an issue. Unlike other components, these groups and queues are not retrievable.

This inconsistency is causing a hindrance in our workflow. We need to ensure consistency in retrieving components via source. Any insights or workaround for this would be greatly appreciated.

### Steps To Reproduce

I've tried using the command with the source directory:

```sh
sf project retrieve start --source-dir sfdx-source
```

However, this doesn't seem to work for groups and queues. Interestingly, when I use the meta command:

```sh
sf project retrieve start -m Group
```

It works as expected.

I've even removed the .forceignore file just in case if any rule blocks pulling them,  but unfortunately, it didn't resolve the issue.

### Expected result
When using the command sf project retrieve start --source-dir sfdx-source, all manually created groups and queues should be retrieved along with other components specified in the source directory.

### Actual result
Manually created groups and queues are not retrieved when using the command sf project retrieve start --source-dir sfdx-source. However, using the meta command sf project retrieve start -m Group successfully retrieves the groups, indicating an inconsistency in retrieval behavior.

### System Information

```json
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.33.3",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.0 (core)",
    "@oclif/plugin-help 6.0.18 (core)",
    "@oclif/plugin-not-found 3.0.14 (core)",
    "@oclif/plugin-plugins 4.3.5 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.0 (core)",
    "@oclif/plugin-version 2.0.14 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.14 (core)",
    "@oclif/plugin-which 3.1.4 (core)",
    "@salesforce/cli 2.33.3 (core)",
    "apex 3.0.30 (core)",
    "auth 3.3.23 (core)",
    "data 3.1.9 (core)",
    "deploy-retrieve 3.2.31 (core)",
    "dev 1.3.2 (user)",
    "info 3.0.31 (core)",
    "limits 3.1.13 (core)",
    "marketplace 1.0.27 (core)",
    "org 3.4.3 (core)",
    "packaging 2.1.12 (core)",
    "schema 3.1.7 (core)",
    "settings 2.0.31 (core)",
    "sobject 1.1.18 (core)",
    "source 3.1.20 (core)",
    "telemetry 3.1.16 (core)",
    "templates 56.0.21 (core)",
    "trust 3.3.16 (core)",
    "user 3.3.3 (core)",
    "forcediff 0.0.1 (link) /Users/mgalal2/sfdx_diff_package"
  ]
}
```

**Comment by jhgihub0** [comment]
I work with @mgalalm 

This is the CLI we are currently using

@salesforce/cli/2.32.8 linux-x64 node-v20.11.1

@oclif/plugin-autocomplete 3.0.12 (core)
@oclif/plugin-commands 3.2.0 (core)
@oclif/plugin-help 6.0.17 (core)
@oclif/plugin-not-found 3.0.14 (core)
@oclif/plugin-plugins 4.3.2 (core)
@oclif/plugin-search 1.0.20 (core)
@oclif/plugin-update 4.2.0 (core)
@oclif/plugin-version 2.0.14 (core)
@oclif/plugin-warn-if-update-available 3.0.13 (core)
@oclif/plugin-which 3.1.3 (core)
@salesforce/cli 2.32.8 (core)
apex 3.0.26 (core)
auth 3.3.21 (core)
data 3.1.7 (core)
deploy-retrieve 3.2.27 (core)
info 3.0.28 (core)
limits 3.1.13 (core)
marketplace 1.0.26 (core)
org 3.4.1 (core)
packaging 2.1.11 (core)
schema 3.1.7 (core)
settings 2.0.31 (core)
sobject 1.1.17 (core)
source 3.1.18 (core)
telemetry 3.1.15 (core)
templates 56.0.21 (core)
trust 3.3.16 (core)
user 3.3.1 (core)

**Comment by WillieRuemmele** [comment]
Hey @mgalalm or @jhgihub0 

2 questions

1. What `Group` are you referring to? and could you provide some more specific instructions on how you're creating this in the org.

I'm assumming that you're creating a `Setup > Public Groups`, and if that's the case, I was able to retrieve it
```bash
 ➜  sf project retrieve preview

No conflicts found.

No files will be deleted.

Will Retrieve [1] files.
 Type  Fullname Path 
 ───── ──────── ──── 
 Group test          

No files were ignored. Update your .forceignore file if you want to ignore certain files.
➜  testing  hub:(GLOBAL - DevHub) scratch:(test-dgcayheaxtuh@example.com)
 ➜  sf project retrieve start  
Retrieving v59.0 metadata from test-dgcayheaxtuh@example.com using the v60.0 SOAP API
Preparing retrieve request... Succeeded

Retrieved Source
======================================================================
| State   Name Type  Path                                              
| ─────── ──── ───── ───────────────────────────────────────────────── 
| Created test Group force-app/main/default/groups/test.group-meta.xml 
```
2. I created a `Queue` in the org, and was able to retrieve it successfully
```bash
 ➜  sf project retrieve preview                   

No conflicts found.

No files will be deleted.

Will Retrieve [1] files.
 Type  Fullname Path 
 ───── ──────── ──── 
 Queue test          

No files were ignored. Update your .forceignore file if you want to ignore certain files.
➜  testing  hub:(GLOBAL - DevHub) scratch:(test-dgcayheaxtuh@example.com)
 ➜  sf project retrieve start  
Retrieving v59.0 metadata from test-dgcayheaxtuh@example.com using the v60.0 SOAP API
Preparing retrieve request... Succeeded

Retrieved Source
======================================================================
| State   Name Type  Path                                              
| ─────── ──── ───── ───────────────────────────────────────────────── 
| Created test Queue force-app/main/default/queues/test.queue-meta.xml 

```

this is using
```bash
 ➜  sf -v                    
@salesforce/cli/2.36.7 darwin-arm64 node-v18.18.2
```

If you can provide more steps to consistently reproduce this, that would be most helpful

**Comment by mgalalm** [comment]
Hi @WillieRuemmele. Yes that's how we created it. Unfortunately, we don't have source tracking enabled. Nevertheless, we can still retrieve any new components except for Group and Queue. So, we use the --source-dir flag in this case. I'm not sure if source tracking is covering up the issue here.

**Comment by WillieRuemmele** [comment]
hmmm, and you've verified your `.forceignore` entries aren't accidentally excluding them? You can check with `sf project list ignored`

**Comment by mgalalm** [comment]
Hi, yes, I removed the entire file `.forceignore` completely, to rule it out

```sh
$ sf project list ignored
No ignored files found in paths:
sfdx-source
```

**Comment by WillieRuemmele** [comment]
yeah, shoot. Then what command are you running trying to retrieve them?

**Comment by mgalalm** [comment]
We use this command 
`sf project retrieve start --source-dir sfdx-source`

**Comment by WillieRuemmele** [comment]
I'm creating a non source-tracked org, and will try again

**Comment by WillieRuemmele** [comment]
@mgalalm - to retrieve metadatat that doesn't exist in your project (yet) - try using the `--metadata` flag
```bash
 ➜  sf project retrieve start --metadata Group               
Retrieving v60.0 metadata from test-ihwer0kbcvd9@example.com using the v60.0 SOAP API
Preparing retrieve request... Succeeded

Retrieved Source
======================================================================
| State   Name Type  Path                                              
| ─────── ──── ───── ───────────────────────────────────────────────── 
| Created test Group force-app/main/default/groups/test.group-meta.xml 
➜  dreamhouse-lwc git:(main) ✗  hub:(DevHub) scratch:(test-ihwer0kbcvd9@example.com)
 ➜  sf project retrieve start --metadata Queue
Retrieving v60.0 metadata from test-ihwer0kbcvd9@example.com using the v60.0 SOAP API
Preparing retrieve request... Succeeded

Retrieved Source
======================================================================
| State   Name Type  Path                                              
| ─────── ──── ───── ───────────────────────────────────────────────── 
| Created test Queue force-app/main/default/queues/test.queue-meta.xml 
```

it worked for me this way

**Comment by mshanemc** [comment]
`--source-dir` means, "I'm gonna point to some files, retrieve those from the org."  It doesn't mean, "here are some files, retrieve other files like them".

Like Willie says, if you're trying to retrieve something you don't have locally yet, use `--metadata` to tell it what type and or which things of that type.
