### ISSUE TITLE
`sfdx force:source:push` will not push changes to detail object alone in M-D relationship

### ISSUE THREAD

**Issue by davidmreed** [forcedotcom/cli#28]
### Summary

Given an object `Project__c` with a master-detail relationship to Account (relationship field name `Account__c`), with a local project tree and scratch org in sync with one another:

Make a local change to the file `Project__c.object`, such as changing the label of the Name field.

Issue 

    $ sfdx force:source:push

Receive in response

> PROJECT PATH                                                          ERROR
───────────────────────────────────────────────────────────────────
force-app/main/default/objects/Project__c/Project__c.object-meta.xml  Cannot set sharingModel to ControlledByParent on a CustomObject without a MasterDetail relationship field

Note that the sharingModel is set to ControlledByParent and the master-detail relationship field is present both in the source tree and in the scratch org - it's just not being pushed in this operation because that field is not changed.

**SFDX CLI Version**: confirmed in 6.50.0 and 6.51.1 (linux-x64) node-v10.15.0

**OS and version**: GalliumOS (Ubuntu derivative) 16.04

**Comment by clairebianchi** [comment]
@davidmreed Thank you for filing this bug. We are now aware and I have passed it on to the correct internal team.

**Comment by jefersonchaves** [comment]
Is there any update when this might get fixed? Seems this is related to [this](https://help.salesforce.com/articleView?id=000232550&type=1) which is a really bad workaround.

**Comment by ChuckJonas** [comment]
guessing that's a no... This is why we can't have nice things.

**Comment by jefersonchaves** [comment]
Hi, @clairebianchi: would you happen to know where this is being tracked?

**Comment by jairzh** [comment]
Temporarily to rename the master-detail field label on the child object to fix the push issue.

**Comment by yippie** [comment]
Why is this closed? I am hitting this issue as well that if any change happens to the object definition, push fails unless you also  update the master detail field so it has changes as well.

sfdx-cli/7.81.0-7b953c80d1 darwin-x64 node-v12.18.3
@mavens/mic-cli-plugin 10.0.0-0 (link) /Users/kaiamundsen/workspace/MedInfoCloud-CLI-Plugin
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-scanner 2.4.0
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.6.0 (core)
├─ schema 1.0.1 (core)
├─ custom-metadata 1.0.10 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.6.0 (core)
├─ apex 0.1.4 (core)
└─ templates 50.1.0 (core)
sfdmu 3.7.21
sfdx-cli 7.81.0 (core)
texei-sfdx-plugin 1.9.1

**Comment by gadamson-upco** [comment]
Seeing the same issue here. Any modifications to the object fails with 
> Cannot set sharingModel to ControlledByParent on a CustomObject without a MasterDetail relationship field

sfdx-cli/7.85.1-2fb9e41053 darwin-x64 node-v12.18.3

**Comment by jclark-dot-org** [comment]
For those encountering this (annoying, lingering) error, another workaround that doesn't require you to make a temporary change to your MD field is to push all source.  

Assuming you only have local changes (`sfdx force:source:status` doesn't show any remote changes), you can clear tracking status (`sfdx force:source:tracking:clear`) and then push (`sfdx force:source:push -f`).  Note that you must use `-f` to force the push since the system has no tracking info to check and assumes everything is out of sync.  This method is slow, since you have to push all source, but it doesn't require any changes to your source.

**Warning** Don't run `sfdx force:source:clear` if there are remote changes you don't want to lose.  Pull them first, or use a different workaround.

**Comment by DougJod** [comment]
Looks like the issue is being tracked here:
https://trailblazer.salesforce.com/issues_view?id=a1p3A000001SGSDQA4
