### ISSUE TITLE
Unable to Deploy CRM Analytics Dashboard - Invalid JSON Format

### ISSUE THREAD

**Issue by hmandsager** [forcedotcom/cli#2803]
### Summary
I created an analytics template in VSCode and successfully deployed to a scratch org. I then created a sample dashboard within Analytics Studio, copied the JSON file from Analytics studio, created a new file in the  and pointed `template-info.json` to this new dashboard. Attempting to push using either the CLI or VSCode failed with the same error.

```
Unable to load definition [waveTemplates/test/dashboards/mainDashboard.json] due to a parse/format error. The provided value is improperly formatted. Error: Invalid Json Format: Location[line -1:column -1] - Unrecognized field [label] in type [AssetReferenceInputRepresentation], not marked as ignorable (1:1)
```

I believe it has something to do with the `steps` object inside of the `state` object of `mainDashboard.json`. Specifically, if I go through the `datasets` object and remove `label` the error changes to point towards `url` as an unrecognized field. Going through the documentation it appears that Analytics Studio produced a file where `datasets` is a [AssetReferenceRepresentation](https://developer.salesforce.com/docs/atlas.en-us.bi_dev_guide_rest.meta/bi_dev_guide_rest/bi_resources_appendix.htm#AssetReferenceRepresentation) while the CLI seems to think it should be of type [AssetReferenceInputRepresentation](https://developer.salesforce.com/docs/atlas.en-us.bi_dev_guide_rest.meta/bi_dev_guide_rest/bi_resources_appendix.htm#AssetReferenceInputRepresentation)

### Steps To Reproduce
Here is a .zip of the example repo: [analytics-test.zip](https://github.com/forcedotcom/cli/files/14886616/analytics-test.zip)

1. Unzip file and connect to your SF developer edition org.
2. Run `sf project deploy start` or `SFDX: Push Source to Default Org` through VSCode
3. Validate that `testDashboard` successfully deploys by updating `template-info.json` to below:
```json
  "dashboards": [
    {
      "label": "testDashboard",
      "name": "testDashboard_tp",
      "condition": "${Variables.Overrides.createAllDashboards}",
      "file": "dashboards/testDashboard.json"
    }
```
### Expected result

Successfully deploys template to the scratch org

### Actual result
```
Unable to load definition [waveTemplates/test/dashboards/mainDashboard.json] due to a parse/format error. The provided value is improperly formatted. Error: Invalid Json Format: Location[line -1:column -1] - Unrecognized field [label] in type [AssetReferenceInputRepresentation], not marked as ignorable (1:1)
```

### System Information
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.35.6",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Darwin 23.2.0",
  "rootPath": "/Users/hmandsager/.local/share/sf/client/2.35.6-3a4a215",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.2 (core)",
    "@oclif/plugin-help 6.0.20 (core)",
    "@oclif/plugin-not-found 3.1.1 (core)",
    "@oclif/plugin-plugins 5.0.1 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.2 (core)",
    "@oclif/plugin-version 2.0.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/cli 2.35.6 (core)",
    "apex 3.1.0 (core)",
    "auth 3.5.0 (core)",
    "data 3.2.2 (core)",
    "deploy-retrieve 3.4.0 (core)",
    "env 3.0.25 (user)",
    "functions 1.23.0 (user)",
    "info 3.1.0 (core)",
    "limits 3.2.0 (core)",
    "marketplace 1.1.0 (core)",
    "org 3.6.0 (core)",
    "packaging 2.2.0 (core)",
    "schema 3.2.0 (core)",
    "settings 2.1.0 (core)",
    "signups 2.1.0 (user)",
    "sobject 1.2.0 (core)",
    "source 3.2.0 (core)",
    "telemetry 3.1.17 (core)",
    "templates 56.1.0 (core)",
    "trust 3.4.0 (core)",
    "user 3.4.0 (core)"
  ]
}
```

**Comment by WillieRuemmele** [comment]
Thanks for providing the zip, that's super helpful. I was able to create a new org, and run `sf project deploy start` and saw the same error

**Comment by WillieRuemmele** [comment]
hey @hmandsager can I ask how you created the `mainDashboard.json`? If I change your project to use and deploy the `testDashboard` it works, I'm wondering if there's something wrong with your local file that's causing the server to interpret it as that wrong metadata type

**Comment by hmandsager** [comment]
I copy and pasted the JSON from an Analytics Studio dashboard. I tried:
1. Outright copying the JSON which failed
2. Taking the `testDashboard.json` as a base and incrementally adding objects from Main Dashboard. That's how I determined the `steps` object was the cause of the error.

I've attached the JSON from analytics studio
[analytics_studio_dashboard.json](https://github.com/forcedotcom/cli/files/14887780/analytics_studio_dashboard.json)

**Comment by WillieRuemmele** [comment]
I'm wondering if one of those incremental additions has transformed it. From the CLI's perspective, everything is getting built and deployed to the server correctly.  Is there any way to create these dashboards in the org and then `project retrieve` them?

**Comment by hmandsager** [comment]
Even just copying and pasting the the json in its entirety causes the error...incremental was to just try and drill down to which part seemed to be the issue. Using `sf project retrieve start` brought down the dashboard as a `.wlens` file so a unsure if that's the same. Not finding a ton of documentation on best practices here but assumed I could copy the JSON between Analytics Studio and an app template.

**Comment by WillieRuemmele** [comment]
the file's suffix plays an important role, even if it's a json structure keeping the same suffix will be required when retrieving/deploying

**Comment by hmandsager** [comment]
I was able to create a template from an app and run `sf project retrieve` which looked correct. Still odd that the dashboard JSON can't be copied but maybe that is expected.

**Comment by WillieRuemmele** [comment]
sounds like you've solved the issue then? I'll close this issue, but if you're still seeing errors, we can reopen :)
