### ISSUE TITLE
New decompose retrieve throws error of `Unexpected child metadata` in sharing rules and permission sets

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#2804]
### Summary

First of all, love this new functionality! Have expected it since a while ago, for us this reduces A LOT the work necessary to build deltas for deployments. Hope it gets integrated with the `retrieve this source from org` soon

When running it for permission sets and sharing rules, an error of unexpected metadata is launched after the correct retrieval and decomposition of all the metadata. This is not happening with workflows, and i could not try to do it in custom labels due to ammount of labels in the org

### Steps To Reproduce

Activate the new functionality of decompose sharings and permission sets
Try to retrieve

### Expected result

Output the list of metadata retrieved

### Actual result

Error

### System Information

zsh

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.36.8",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/miguelnunezdiaz-montes/.local/share/sf/client/2.36.8-fa01960",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.2 (core)",
    "@oclif/plugin-help 6.0.20 (core)",
    "@oclif/plugin-not-found 3.1.1 (core)",
    "@oclif/plugin-plugins 5.0.5 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.3 (core)",
    "@oclif/plugin-version 2.0.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/cli 2.36.8 (core)",
    "apex 3.1.3 (core)",
    "auth 3.5.1 (core)",
    "data 3.2.4 (core)",
    "deploy-retrieve 3.5.3 (core)",
    "info 3.1.2 (core)",
    "limits 3.2.1 (core)",
    "marketplace 1.1.0 (core)",
    "org 3.6.3 (core)",
    "packaging 2.3.0 (core)",
    "schema 3.2.0 (core)",
    "settings 2.1.2 (core)",
    "sobject 1.2.1 (core)",
    "source 3.2.2 (core)",
    "telemetry 3.1.17 (core)",
    "templates 56.1.0 (core)",
    "trust 3.5.1 (core)",
    "user 3.4.3 (core)"
  ]
}
```

### Additional information

```shell
❯ sf project retrieve start -m SharingRules:Case           
Retrieving v59.0 metadata from ssasalesforceplat@repsol.com using the v60.0 SOAP API
Preparing retrieve request... MetadataTransferError
Error (1): Metadata API request failed: Unexpected child metadata [/Users/miguelnunezdiaz-montes/work/AP_SALESFORCE/force-app/main/default/sharingRules/Case/sharingCriteriaRules/CPSGL_sh_NegocioInternoEES.sharingCriteriaRule-meta.xml] found for parent type [SharingRules]
```

**Comment by WillieRuemmele** [comment]
Hey @mnunezdm - I'm glad your enjoying the new functionality, or at least trying to 😉. Did you start by removing all of your permission sets / sharing rules files locally, then add the preset to your `sfdx-project.json`, and then run `sf project retrieve`?

the two formats aren't interoperable

**Comment by mnunezdm** [comment]
That was it!
