### ISSUE TITLE
Getting error Type error:Messages.importMessagesDirectoryFromMetaUrl Is not a function

### ISSUE THREAD

**Issue by Tanvidh** [forcedotcom/cli#2809]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.
 Command:sf org login jwt  --instance-url xxx --jwt-key-file xxx --client-id xxx --username --alias 

### Expected result

Connection successful 
### Actual result

Type error:Messages.importMessagesDirectoyFromMetaUrl is not a function
### System Information

Sf version:2.34.7
Npm:9.9.3
Node js :20.11.1

Tried changing different nodejs and npm version but still it's giving this error.It was working fine previously suddenly started giving error

```json
SFDX & Node Version :: @salesforce/cli/2.37.1 linux-x64 node-v20.11.1

GIT Delta Version :: sfdx-git-delta 5.34.0 (link)

/apps/external/5/jenkins-node-home/workspace/vi_Tanvi_try_and_error_new_PR-35/node_modules/sfdx-git-delta

 

Uninstalled JIT Plugins:   

community 3.1.0   

custom-metadata 3.2.1   dev 2.2.0   

devops-center 1.2.9  

env 3.0.25   

functions 1.23.0   

signups 2.1.2

@salesforce/sfdx-plugin-lwc-test 1.2.0

 @salesforce/sfdx-scanner 3.23.0

 

```

**Comment by Tanvidh** [comment]
Hi ,
Please find the details of sf --version --verbose command
SFDX & Node Version :: {

     "architecture": "linux-x64",

     "cliVersion": "@salesforce/cli/2.37.1",

     "nodeVersion": "node-v20.12.1",

     "osVersion": "Linux 4.18.0-513.18.1.el8_9.x86_64",

     "rootPath": "/apps/external/5/jenkins-node-home/workspace/vi_Tanvi_try_and_error_new_PR-36/node_modules/@salesforce/cli",

     "shell": "ksh",

     "pluginVersions": [

       "@oclif/plugin-autocomplete 3.0.13 (core)",

       "@oclif/plugin-commands 3.2.2 (core)",

       "@oclif/plugin-help 6.0.20 (core)",

       "@oclif/plugin-not-found 3.1.1 (core)",

       "@oclif/plugin-plugins 5.0.5 (core)",

       "@oclif/plugin-search 1.0.20 (core)",

       "@oclif/plugin-update 4.2.3 (core)",

       "@oclif/plugin-version 2.0.16 (core)",

       "@oclif/plugin-warn-if-update-available 3.0.15 (core)",

       "@oclif/plugin-which 3.1.7 (core)",

       "@salesforce/cli 2.37.1 (core)",

       "apex 3.0.23 (core)",

       "auth 3.3.11 (core)",

       "data 3.2.4 (core)",

       "deploy-retrieve 3.5.3 (core)",

       "info 3.1.2 (core)",

       "limits 3.2.1 (core)",

       "marketplace 1.1.0 (core)",

       "org 3.6.0 (core)",

       "packaging 2.3.0 (core)",

       "schema 3.2.0 (core)",

       "settings 2.1.2 (core)",

       "sobject 1.2.1 (core)",

       "source 3.2.2 (core)",

       "telemetry 3.1.17 (core)",

       "templates 56.1.0 (core)",

       "trust 3.5.1 (core)",

       "user 3.4.3 (core)"

     ]

   }

**Comment by Tanvidh** [comment]
Hi,
content is updated

**Comment by WillieRuemmele** [comment]
Hey @Tanvidh can you provide the output of `sf version --verbose --json`? What command are you running? All Commands? can you please provide more helpful information so that way we can help you 😄

**Comment by Tanvidh** [comment]
Hi,
SFDX & Node Version :: {

     "architecture": "linux-x64",

     "cliVersion": "@salesforce/cli/2.37.1",

     "nodeVersion": "node-v20.12.1",

     "osVersion": "Linux 4.18.0-513.18.1.el8_9.x86_64",

     "rootPath": "/apps/external/5/jenkins-node-home/workspace/vi_Tanvi_try_and_error_new_PR-36/node_modules/@salesforce/cli",

     "shell": "ksh",

     "pluginVersions": [

       "@oclif/plugin-autocomplete 3.0.13 (core)",

       "@oclif/plugin-commands 3.2.2 (core)",

       "@oclif/plugin-help 6.0.20 (core)",

       "@oclif/plugin-not-found 3.1.1 (core)",

       "@oclif/plugin-plugins 5.0.5 (core)",

       "@oclif/plugin-search 1.0.20 (core)",

       "@oclif/plugin-update 4.2.3 (core)",

       "@oclif/plugin-version 2.0.16 (core)",

       "@oclif/plugin-warn-if-update-available 3.0.15 (core)",

       "@oclif/plugin-which 3.1.7 (core)",

       "@salesforce/cli 2.37.1 (core)",

       "apex 3.0.23 (core)",

       "auth 3.3.11 (core)",

       "data 3.2.4 (core)",

       "deploy-retrieve 3.5.3 (core)",

       "info 3.1.2 (core)",

       "limits 3.2.1 (core)",

       "marketplace 1.1.0 (core)",

       "org 3.6.0 (core)",

       "packaging 2.3.0 (core)",

       "schema 3.2.0 (core)",

       "settings 2.1.2 (core)",

       "sobject 1.2.1 (core)",

       "source 3.2.2 (core)",

       "telemetry 3.1.17 (core)",

       "templates 56.1.0 (core)",

       "trust 3.5.1 (core)",

       "user 3.4.3 (core)"

     ]

   }
Please find the output of sf  version --verbose 
   Command.Iam executing this using Jenkins pipeline.And getting error for sf org login jwt command.

**Comment by WillieRuemmele** [comment]
are you seeing this locally, or just in jenkins?  I'm wondering if it's happening due to using the `ksh` shell, which isn't one of our officially supported, or tested shells.

**Comment by Tanvidh** [comment]
Hi ,
This is the one we are getting in Jenkins.But before few months we were able to run this successfully.Any sf org command is giving this error .I don't think this can be the problem of ksh shell as it was running successfully

**Comment by WillieRuemmele** [comment]
hmm, that method is defined [here](https://github.com/forcedotcom/sfdx-core/blob/e39f17981733a8185ec13b1cacc4aea31f164f3c/src/messages.ts#L315) - I'm sure this has been happening after an uninstall/reinstall, especially since it's in CI. How are you installing the CLI?

**Comment by Tanvidh** [comment]
Hi,
Iam installing using  yarn add command.
The Jenkins environment is having npm and NVM installed with all the environment variables set.
Everytime a build is run it is getting freshly installed.
Therefore no problem of uninstalling and installing again.Is this a code problem or do I need to update to some other version of cli?

**Comment by WillieRuemmele** [comment]
Can you try installing with `npm`? e.g `npm install -g @salesforce/cli`? 

I wasn't seeing any errors while using `yarn add`, but it just wasn't working for me
```bash
 ➜  yarn add @salesforce/cli
yarn add v1.22.22
.
.
.
✨  Done in 5.21s.
➜  npm 
 ➜  sf -v
zsh: command not found: sf
```

```bash
 ➜  yarn global add @salesforce/cli 
yarn global v1.22.22
.
.
.
success Installed "@salesforce/cli@2.36.8" with binaries:
      - sf
      - sfdx
✨  Done in 21.78s.
➜  npm 
 ➜  sf -v
zsh: command not found: sf
```


I don't believe this to be a code problem. If you run `which sf` and open that directory, navigate to path similar to `node_moduels/@salesforce/core/lib/messages.js` and ensure that method exists that will be the proof. This is certainly a strange bug

**Comment by Tanvidh** [comment]
Hi,
I checked in the path and can't find the method .I tried installing using npm install and still can't find the method in the specified path .Can you please suggest something.?

**Comment by Tanvidh** [comment]
Is their any dependency on any plugin which I can install separately to resolve this?

**Comment by mshanemc** [comment]
Can you look in node_moduels/@salesforce/core/package.json and see what the version is?

FYI: `yarn add` will typically add the package (sf) into your local project's package json.  Make sure to use `yarn global add` like Willie did to put it in your global yarn.  That *could* be the cause of the bug.

**Comment by Tanvidh** [comment]
Hi,
Now the issue is resolved thanks for your help

**Comment by mshanemc** [comment]
oh, good!  Did anything change (updating the CLI, reinstall, node version, `yarn **global** add` etc) that fixed it?  For the next person who finds this?
