### ISSUE TITLE
add path erroe

### ISSUE THREAD

**Issue by zerommc** [forcedotcom/cli#2817]
![Snipaste_2024-04-11_17-58-46](https://github.com/forcedotcom/cli/assets/49937307/ae4f50ec-6923-484a-816a-1d6ba6ec817c)
![image](https://github.com/forcedotcom/cli/assets/49937307/1668d82a-d52a-4d88-9a96-2bceefd0ec28)

**Comment by WillieRuemmele** [comment]
Hi @zerommc it looks like `sf` is trying to add a directory, which is now longer than your $PATH variable's maximum length, you might try

- increasing the limit https://superuser.com/questions/1385854/how-do-i-bypass-restrictions-on-the-length-of-the-path-variable
- installing in a directory with a shorter name
- manually adding this dir to your $PATH
