### ISSUE TITLE
Inconsistent .sf config file locations

### ISSUE THREAD

**Issue by dschach** [forcedotcom/cli#2819]
### Summary
My sf config files are located in `~<username>/.sf` which includes a file called `config.json`, `sf.json`, and others. sf also has files in `~<username>/.local/share/sf`.

The latest release notes for `2.37.4` say to put the plugin allowlist file into `$HOME/.config/sf`

However, there is no folder for me in that location, and it seems like a mistake to spread sf config files across multiple directories. Of note, `sf` items are also in `.local/share/sf` - maybe this is where the allowlist file should go, since it's where the plugins are listed?

Is this a bug in the documentation? Or is it a "bug" in the execution and a poor design choice?

If I'm totally wrong and `$HOME` is not my user directory in MacOS, then why are `sf` files being stored outside my user directory? So I'm assuming that this `.sf/config` folder doesn't exist.

### Steps To Reproduce

Look in your own `sf` configuration files and find a folder (hidden in MacOS) called `.sf` in your user directory. Also find plugin configuration in `.local/share/sf`.

### Expected result
The allowList should be placed in the `.sf` folder or the `.local/share/sf` folder. (Probably the latter, as it contains the plugins JSON.)

### Actual result
The documentation says to put it in `config/.sf` (a folder that does not exist). 

Should the documentation or the CLI be changed? That's up to you!

### System Information

(Installed VSCode and sf cli today on fresh machine - this is as pure as it gets.)

MacOS
zsh in VSCode

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.36.8",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/<username>/.local/share/sf/client/2.36.8-fa01960",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.2 (core)",
    "@oclif/plugin-help 6.0.20 (core)",
    "@oclif/plugin-not-found 3.1.1 (core)",
    "@oclif/plugin-plugins 5.0.5 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.3 (core)",
    "@oclif/plugin-version 2.0.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/cli 2.36.8 (core)",
    "apex 3.1.3 (core)",
    "auth 3.5.1 (core)",
    "data 3.2.4 (core)",
    "deploy-retrieve 3.5.3 (core)",
    "info 3.1.2 (core)",
    "limits 3.2.1 (core)",
    "marketplace 1.1.0 (core)",
    "org 3.6.3 (core)",
    "packaging 2.3.0 (core)",
    "schema 3.2.0 (core)",
    "settings 2.1.2 (core)",
    "sobject 1.2.1 (core)",
    "source 3.2.2 (core)",
    "telemetry 3.1.17 (core)",
    "templates 56.1.0 (core)",
    "trust 3.5.1 (core)",
    "user 3.4.3 (core)"
  ]
}
```
### Additional information

If the new release will create this `.config/sf folder`, then that's interesting - is that part of a longer-term plan?

**Comment by WillieRuemmele** [comment]
Hi @dschach  - There's different config files for different purposes. This config file is an OCLIF level config file for the CLI as a whole. This is the correct place for it. It's alright if it doesn't exist, you can create one, and then when installing plugins, OCLIF will look in that location, for the `sf` cli config file, and use it correctly
