### ISSUE TITLE
sfdx force:lightning:lint --exit does not return exit code 1 on failure

### ISSUE THREAD

**Issue by jamesmelville** [forcedotcom/cli#282]
### Summary

We use sfdx force:lightning:lint as part of our CI process, and it is designed to fail if any components fail linting. Since a few weeks (earliest example under sfdx-cli/7.37.1 linux-x64 node-v13.5.0) the linting has been failing but the exit code has remained 0.

### Steps To Reproduce:

Create an aura component which fails `sfdx force:lightning:lint`. E.g. a controller which uses a fat arrow function.

```
sfdx force:lightning:lint . --exit --json
{
    "name": "LintError",
    "exitCode": 1,
    "data": "<removed>"
}
echo Exit Code is %errorlevel%
Exit Code is 0
```

### Expected result

Command exits with exit code 1

### Actual result

Command exits with exit code 0

### Additional information

![image](https://user-images.githubusercontent.com/1859629/73097719-b8f64d80-3edf-11ea-9646-1e1c3bd70507.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.43.1 linux-x64 node-v13.7.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.4.1 (core)
generator 1.1.2 (core)
salesforcedx 47.16.0 (core)
├─ salesforcedx-templates 47.17.0 (core)
└─ salesforce-alm 47.15.0 (core)

sfdx-cli 7.43.1 (core)
**OS and version**:
Docker Engine Version: 18.09.6
Kernel Version: Linux 2fe3cb7ec042 4.15.0-1052-aws #54-Ubuntu SMP Tue Oct 1 15:43:26 UTC 2019 x86_64 Linux

**Comment by clairebianchi** [comment]
@ntotten can you take a look at this issue?

**Comment by clairebianchi** [comment]
I have passed this issue onto the team that owns the lightning:lint command

**Comment by cristiand391** [comment]
closing this since the `force:lightning:lint` command no longer exists.
