### ISSUE TITLE
Impossible to connect to an org via CLI - blocking issue

### ISSUE THREAD

**Issue by Iosif10** [forcedotcom/cli#2820]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### System Information

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by Iosif10** [comment]
Hello,

After I run this commands, I cannot see the new connection.

sf org logout -o ioan.predescu@nn-group.com -p
sf org login web -a Que_SO_2 -r https://test.salesforce.com/
sf org list

If uninstalled/reinstalled sf cli, same.

Please help me soon since this is a blocker for me.

Thank you,
Iosif

**Comment by Iosif10** [comment]
Hello,

Here there are your requirements.

Thank you,
Iosif

**Comment by Iosif10** [comment]
![Screenshot 2024-04-12 at 10 05 39](https://github.com/forcedotcom/cli/assets/33493678/0e19c03a-0fa3-481c-befb-b4d91dc70ae5)
![Screenshot 2024-04-12 at 10 03 58](https://github.com/forcedotcom/cli/assets/33493678/c859201d-0194-410c-a1ad-ea12845f062b)

**Comment by WillieRuemmele** [comment]
Hi @Iosif10 - did this start happening after an upgrade? I've been running variations of these commands and they've all worked, and showed the correct connections

**Comment by Iosif10** [comment]
No. in fact this problem is from some months ago for my machine. but only now I cannot work around it..

**Comment by WillieRuemmele** [comment]
how were you working around it before?
if you find your orgs username in `~/.sfdx/` try renaming it (add `.bak` as a suffix) to keep it as a back-up, and then try logging in again. If it recreates the file, the auth information should be present, if not, something is going wrong while saving the information

**Comment by Iosif10** [comment]
[1713005507680-diagnosis.json](https://github.com/forcedotcom/cli/files/14967125/1713005507680-diagnosis.json)

my workaround was to create the scratch org from my machine. the problem now is that I have to work with a colleague on his scratch org where he invested a lot of time in creating testing data. 

i cannot find my org username in sf org list

**Comment by WillieRuemmele** [comment]
did you find your orgs username in `~/.sfdx/`? or `~/.sf`?

**Comment by WillieRuemmele** [comment]
did you find your orgs username in `~/.sfdx/`? or `~/.sf`?

**Comment by Iosif10** [comment]
> did you find your orgs username in `~/.sfdx/`? or `~/.sf`?

I can find it in the sfdx file, but not in SF

I ve logged out from all orgs. i ve authenticated back the devhub and a new org (scratch org)

in the org list, only the devhub appears. but in the sfdx, the SO is there also.

**Comment by Iosif10** [comment]
> how were you working around it before? if you find your orgs username in `~/.sfdx/` try renaming it (add `.bak` as a suffix) to keep it as a back-up, and then try logging in again. If it recreates the file, the auth information should be present, if not, something is going wrong while saving the information

I ve tried it, and yes, it recreates the file
