### ISSUE TITLE
@salesforce/cli/2.37.4 sf project retrieve start error

### ISSUE THREAD

**Issue by jhgihub0** [forcedotcom/cli#2832]
We have a non DX project that still uses the old folder structure.  The package.xml and source files are in a folder called ./src

We use this command to retrieve the metadata

```
sf org login web --alias OrgAlias --instance-url https://test.salesforce.com  
sf project retrieve start --target-org OrgAlias  --manifest ./src/package.xml --target-metadata-dir ./ --wait 90
```

With @salesforce/cli/2.34.7 linux-x64 node-v20.11.1 and older versions this worked fine.

As of @salesforce/cli/2.37.4 linux-x64 node-v20.12.1, we get the error

```
Preparing retrieve request... Error
Error (1): This directory does not contain a valid Salesforce DX project.
```

**Comment by jhgihub0** [comment]
sf version --verbose --json
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.37.4",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.2 (core)",
    "@oclif/plugin-help 6.0.20 (core)",
    "@oclif/plugin-not-found 3.1.2 (core)",
    "@oclif/plugin-plugins 5.0.7 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.4 (core)",
    "@oclif/plugin-version 2.0.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/cli 2.37.4 (core)",
    "apex 3.1.4 (core)",
    "auth 3.5.5 (core)",
    "data 3.2.5 (core)",
    "deploy-retrieve 3.5.6 (core)",
    "info 3.1.3 (core)",
    "limits 3.2.1 (core)",
    "marketplace 1.1.1 (core)",
    "org 4.0.4 (core)",
    "packaging 2.3.0 (core)",
    "schema 3.2.1 (core)",
    "settings 2.1.2 (core)",
    "sobject 1.2.2 (core)",
    "source 3.2.3 (core)",
    "telemetry 3.1.18 (core)",
    "templates 56.1.1 (core)",
    "trust 3.5.4 (core)",
    "user 3.4.3 (core)"
  ]
}

**Comment by jhgihub0** [comment]
I did some more research on the command

`sf project retrieve start --target-org OrgAlias  --manifest ./src/package.xml --target-metadata-dir ./ --wait 90`

The last time it worked was with salesforce/cli/2.36.1

After salesforce/cli/2.36.2 it fails

**Comment by mshanemc** [comment]
yep, that's a bug.  I'll get you a fix

**Comment by mshanemc** [comment]
we patched latest-rc with this fix.  You can update now to verify the change

**Comment by jhgihub0** [comment]
Seems 2.39.4 fixed the issue.  Thank you.
