### ISSUE TITLE
Data Cloud Scratch Org Creation - No DC Setup Menu

### ISSUE THREAD

**Issue by mvogelgesang** [forcedotcom/cli#2838]
### Summary

When creating a Data Cloud scratch org (I have the appropriate CDP Scratch Org permission in my DevHub), I get varying behavior in my scratch org that seems to result from the lack of a space between a json key and value. 

### Steps To Reproduce

- Have Create Data Cloud Scratch Org permissions on DevHub
- Create a scratch definition file with the following contents:
```json
{
  "orgName": "kam company",
  "edition": "Developer",
  "features": ["CustomerDataPlatform","EnableSetPasswordInApi"],
  "settings": {
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    },
    "customerDataPlatformSettings": {
      "enableCustomerDataPlatform":true
    }
  }
}
```
- `sf org create scratch -a dcNoMenu -d -f config/myScratchOrgDefjson -v DEVHUB --wait 10 -y 10`
- Assign CDPAdmin permission to user `sf org assign permset -n CDPAdmin`
- Open org `sf org open`
- Go to Data Cloud Setup
- Observer lack of Setup menu

To create a scratch org with a full Data Cloud Setup menu, apply the following change to the scratch definition file and repeat scratch org creation process. 

```diff
{
  "orgName": "kam company",
  "edition": "Developer",
  "features": ["CustomerDataPlatform","EnableSetPasswordInApi"],
  "settings": {
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    },
    "customerDataPlatformSettings": {
-      "enableCustomerDataPlatform":true
+      "enableCustomerDataPlatform": true
    }
  }
}
```

### Expected result

Behavior not to be different when using scratch definition with our without a space between the key and value. If well formatted JSON is required, formatting prior to consumption may provide a safer developer experience. 

### Actual result

When a space between the key/value was not present, the scratch org did not provision as expected resulting in missing menu items. 

### System Information

- zsh
- @salesforce/cli/2.37.4 darwin-arm64 node-v20.11.0
- MacOS Sonoma 14.4.1
- My DevHub org Id is `00DHs000000PMYmMAO`

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.37.4",
  "nodeVersion": "node-v20.11.0",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/mvogelgesang/.nvm/versions/node/v20.11.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.2 (core)",
    "@oclif/plugin-help 6.0.20 (core)",
    "@oclif/plugin-not-found 3.1.2 (core)",
    "@oclif/plugin-plugins 5.0.7 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.4 (core)",
    "@oclif/plugin-version 2.0.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/analytics 1.4.11 (user)",
    "@salesforce/cli 2.37.4 (core)",
    "apex 3.1.4 (core)",
    "auth 3.5.5 (core)",
    "community 3.0.18 (user)",
    "data 3.2.5 (core)",
    "deploy-retrieve 3.5.6 (core)",
    "functions 1.23.0 (user)",
    "info 3.1.3 (core)",
    "limits 3.2.1 (core)",
    "marketplace 1.1.1 (core)",
    "org 4.0.4 (core)",
    "packaging 2.3.0 (core)",
    "schema 3.2.1 (core)",
    "settings 2.1.2 (core)",
    "signups 2.1.0 (user)",
    "sobject 1.2.2 (core)",
    "source 3.2.3 (core)",
    "telemetry 3.1.18 (core)",
    "templates 56.1.1 (core)",
    "trust 3.5.4 (core)",
    "user 3.4.3 (core)",
    "@salesforce/sfdx-scanner 3.23.0 (user)"
  ]
}

```
### Additional information

Two orgs shown, the background org has a full Data Cloud Setup menu while the foreground lacks any setup menu content. In both instances, I assigned the Data Cloud Admin (CDPAdmin) permission set to my logged in user. In some instances, I have progress indicators under "Are you ready to set up Data Cloud?" but that has been inconsistent behavior. 

![image](https://github.com/forcedotcom/cli/assets/4053083/a90a87e2-2d9b-43c7-b081-752c857de414)

**Comment by mshanemc** [comment]
I can't reproduce this.  with or without the space, I see the same results in the org.

Any chance you could try it again?  Maybe it's one org having a bad day and not related to the scratch-def file

**Comment by RupertBarrow** [comment]
> Maybe it's one org having a bad day

Ha ! 😂
Do you have a calendar with those days, so that we can plan to avoid them ? 😉

**Comment by mvogelgesang** [comment]
@mshanemc I think this is environment specific. I tested again today using my devhub and could reporduce it. Using a colleagues devhub, I was not able to replicate. 

When running today, I was using the following scratch definition file where I would add/remove the space as needed. One thing I noticed when doing this is that if I ran Prettier against the file, a space would automatically be added- this is not something that I have enabled "on save". 

```json
{
  "orgName": "my company",
  "edition": "Developer",
  "features": [
    "EnableSetPasswordInApi",
    "CustomerDataPlatform",
    "EinsteinGPTForDevelopers"
  ],
  "settings": {
    "customerDataPlatformSettings": {
      "enableCustomerDataPlatform":true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true,
      "enableUsersAreLightningOnly": true,
      "enableLexEndUsersNoSwitching": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    },
    "securitySettings": {
      "enableAdminLoginAsAnyUser": true,
      "passwordPolicies": {
        "expiration": "Never",
        "historyRestriction": "0"
      },
      "sessionSettings": {
        "sessionTimeout": "TwelveHours"
      }
    }
  }
}
```

## From my DevHub

- `00D7i000001HC6NEAW` - ✅  created with a space in the settings, can see data cloud setup menu as expected
- `00D8I000001UmXHUA0` - ❌  created without a space in settings, see's empty data cloud setup menu

## From Colleagues DevHub

- `00DDC000001978M` - ✅  created with a space in the settings, can see data cloud setup menu as expected
- `00D03000000rNoV` - ✅  created without a space in settings, can see data cloud setup menu

**Comment by mshanemc** [comment]
yeah, mine was auto-fixing on save, too, and I had to turn that off just to replicate your issue (still couldn't).  

I'm going to mark this as owned by another team since I can't replicate it without your weird devHub.  You'll need to open a regular Salesforce case to try to get their attention.  Be sure to give them the orgIDs of the dev hub, too.

**Comment by eltoroit** [comment]
I have used the `config/project-scratch-def.json` file [mentioned above](https://github.com/forcedotcom/cli/issues/2838#issuecomment-2077824333) and I was able to create the scratch org, but there are some tabs missing, including the "Identity Resolution".

Is there a better file?

**Comment by mvogelgesang** [comment]
@eltoroit The missing tabs bug has been patched as a part of the Summer '24 release. Can you verify that your scratch org environment is on the latest release?
