### ISSUE TITLE
sf project deploy into production expecting test classes to run when when not deploying classes

### ISSUE THREAD

**Issue by nnamacha** [forcedotcom/cli#2839]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
sf project deploy into production expecting test classes to run even when we are not deploying classes

### Steps To Reproduce

run the command sf project deploy start --metadata Flows:Myflow

### Expected result
No need to specify test classes run

### Actual result
Test classes expected

### System Information

Using Bash

```json
$ sf version --verbose --json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.29.5",
  "nodeVersion": "node-v20.11.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\ab0247z\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "C:\\Users\\ab0247z\\AppData\\Local\\Programs\\Git\\usr\\bin\\bash.exe",
  "pluginVersions": [
    "@copado/copado-cli 3.1.0 (user)",
    "@oclif/plugin-autocomplete 3.0.8 (core)",
    "@oclif/plugin-commands 3.1.3 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.10 (core)",
    "@oclif/plugin-plugins 4.2.2 (core)",
    "@oclif/plugin-search 1.0.14 (core)",
    "@oclif/plugin-update 4.1.11 (core)",
    "@oclif/plugin-version 2.0.12 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.10 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.29.5 (core)",
    "apex 3.0.23 (core)",
    "auth 3.3.11 (core)",
    "data 3.0.20 (core)",
    "deploy-retrieve 3.2.14 (core)",
    "info 3.0.24 (core)",
    "limits 3.1.8 (core)",
    "marketplace 1.0.22 (core)",
    "org 3.3.12 (core)",
    "packaging 2.1.7 (core)",
    "schema 3.1.3 (core)",
    "settings 2.0.24 (core)",
    "sobject 1.1.11 (core)",
    "source 3.1.13 (core)",
    "telemetry 3.1.11 (core)",
    "templates 56.0.14 (core)",
    "trust 3.3.8 (core)",
    "user 3.2.8 (core)",
    "dependencies-cli 2.0.1 (user)",
    "sfdx-git-delta 5.34.0 (user)",
    "sfdx-hardis 4.5.1 (user)",
    "sfdx-plugin-source-read 1.2.0 (user)"
  ]
}

```

**Comment by mshanemc** [comment]
can you say more than `Test classes expected`?

What's the error that you're getting?

**Comment by mshanemc** [comment]
FYI, `Flow` is sometimes a special case, depending on the flow being deployed and your org's settings.  
https://help.salesforce.com/s/articleView?id=sf.flow_distribute_deploy_active.htm&type=5

Is that the only non-Apex type you see this "behavior" with?
