### ISSUE TITLE
Windows cannot install with Node.js 20.18.2 security patch breaks child_process.spawn()

### ISSUE THREAD

**Issue by nwcm** [forcedotcom/cli#2843]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

```
yarn global add @salesforce/cli
Corepack is about to download https://registry.yarnpkg.com/yarn/-/yarn-1.22.22.tgz.

Do you want to continue? [Y/n] y
yarn global v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@salesforce/cli > @salesforce/plugin-info > marked-terminal@4.2.0" has incorrect peer dependency "marked@^1.0.0 || ^2.0.0".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
[3/3] ⠂ @salesforce/cli
[-/3] ⠂ waiting...
error C:\Users\xx\AppData\Local\Yarn\Data\global\node_modules\@salesforce\cli: Command failed.
Exit code: 1
Command: node ./scripts/post-install-release-notes.js
Arguments:
Directory: C:\Users\xx\AppData\Local\Yarn\Data\global\node_modules\@salesforce\cli
Output:
node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
          ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at file:///C:/Users/xx/AppData/Local/Yarn/Data/global/node_modules/@salesforce/cli/scripts/post-install-release-notes.js:24:17
    at new Promise (<anonymous>)
    at main (file:///C:/Users/xx/AppData/Local/Yarn/Data/global/node_modules/@salesforce/cli/scripts/post-install-release-notes.js:14:9)
    at file:///C:/Users/xx/AppData/Local/Yarn/Data/global/node_modules/@salesforce/cli/scripts/post-install-release-notes.js:44:7 {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}
```

### Steps To Reproduce

1. install nodejs 20.18.2
2. attempt to install @salesforce/cli via npm or yarn

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### System Information

```json
{}
```

**Comment by mshanemc** [comment]
duplicate of https://github.com/forcedotcom/cli/issues/2822 (pinned issue).
