### ISSUE TITLE
source:deploy:report - Git Bash for Windows

### ISSUE THREAD

**Issue by jlyon-nlg** [forcedotcom/cli#285]
### Summary

Deploy Job Reports are not displayed in Git Bash for Windows

### Steps To Reproduce:

1.  sfdx force:source:deploy -u [username] -x [manifest] // ==> outputs job id
1.  sfdx force:source:deploy:report -u [username] -i [jobid] // ==> outputs job id

### Expected result

During step 2, it should report out the job success/fail/in-progress status as well as any error details that go with a failure.

### Actual result

Only the JobId is printed.

### Additional information

![deploy-report-git-bash](https://user-images.githubusercontent.com/56881370/73264759-2254b580-4199-11ea-879c-6e18098e7e02.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.43.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.4.1 (core)
generator 1.1.2 (core)
salesforcedx 47.16.0 (core)
├─ salesforcedx-templates 47.17.0 (core)
└─ salesforce-alm 47.15.0 (core)

sfdx-cli 7.43.1 (core)

**OS and version**:
win32-x64 (Windows 10), node-v10.16.3

**Comment by clairebianchi** [comment]
@jlyon-nlg did this just start happening? We do not officially support Git Bash for Windows. It is possible that you are seeing this issue due to the introduction of the progress bar on deploy operations. Would you please try disabling the progress bar by setting:

SFDX_USE_PROGRESS_BAR = false

**Comment by justin-lyon** [comment]
Thanks @clairebianchi 

This started after the sfdx-cli release with the progress bar, yes. I'll try deactivating the progress bar. 

Additionally, I've found that regardless of the terminal I'm using (git bash for windows, windows cmd, or linux terminal) that `force:source:deploy --checkonly` will only report back a job Id on success, and will only report that a failure occurred - not the actual error details - if there is an error.

Whereas `force:source:deploy` without the `--checkonly` flag will report back individual files on success, and will report back individual errors on failure.

**Comment by clairebianchi** [comment]
@jlyon-nlg thank you, we actually have a fix for that issue going into this week's release. The update will go out on Thursday.
