### ISSUE TITLE
ERROR running sf org create user: Error authenticating with JWT config due to: user hasn't approved this consume

### ISSUE THREAD

**Issue by salesforcebinge** [forcedotcom/cli#2857]
### Summary
This exactly points to the issue raised with SFDX [Issue 1028](https://github.com/forcedotcom/cli/issues/1028)

### Steps To Reproduce
I created a workflow/ github action where I am performing a series of tasks.

1) Authenticate to DevHub via JWT
2) Create scratch org
3) Create a user in the scratch org and authenticate

![image](https://github.com/forcedotcom/cli/assets/74901059/93df1b90-4272-441a-beb8-d3ba2ac7918c)

### Expected result 
user created and has the correct profile

### Actual result
creation of the users failed with error

### System Information
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.25.7",
  "nodeVersion": "node-v21.6.1",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/opt/homebrew/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.5 (core)",
    "@oclif/plugin-commands 3.1.1 (core)",
    "@oclif/plugin-help 6.0.12 (core)",
    "@oclif/plugin-not-found 3.0.9 (core)",
    "@oclif/plugin-plugins 4.1.17 (core)",
    "@oclif/plugin-search 1.0.12 (core)",
    "@oclif/plugin-update 4.1.8 (core)",
    "@oclif/plugin-version 2.0.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.9 (core)",
    "@oclif/plugin-which 3.0.15 (core)",
    "@salesforce/cli 2.25.7 (core)",
    "apex 3.0.18 (core)",
    "auth 3.3.2 (core)",
    "data 3.0.16 (core)",
    "deploy-retrieve 3.2.0 (core)",
    "info 3.0.17 (core)",
    "limits 3.1.4 (core)",
    "marketplace 1.0.16 (core)",
    "org 3.3.5 (core)",
    "packaging 2.1.1 (core)",
    "schema 3.1.0 (core)",
    "settings 2.0.17 (core)",
    "sobject 1.1.2 (core)",
    "source 3.1.5 (core)",
    "telemetry 3.1.10 (core)",
    "templates 56.0.10 (core)",
    "trust 3.3.2 (core)",
    "user 3.2.3 (core)"
  ]

**Comment by salesforcebinge** [comment]
Update: the error changes now and suggests to authorize the org with either web or sfdx-auth-url. So does this mean the user creation cannot happen with JWT authentication? I might need to test the behavior with an org not on Hyperforce yet. 
![image](https://github.com/forcedotcom/cli/assets/74901059/96a6643e-4fd5-4c84-956c-2afb978f8266)

**Comment by mdonnalley** [comment]
Hyperforce orgs don't work well with JWT, which is why we immediately exit and advise that you use `org login web` or `org login sfdx-url` instead.

Some other issues where we explain this:
https://github.com/forcedotcom/cli/issues/2665
https://github.com/forcedotcom/cli/issues/2479
https://github.com/forcedotcom/cli/issues/2575
