### ISSUE TITLE
How to push source to Scratch org if project code exceeds 50mb limit?

### ISSUE THREAD

**Issue by mlamrib** [forcedotcom/cli#286]
**Is your feature request related to a problem? Please describe.**
When trying to push an org to salesforce, the 50MB limit is making our lives miserable. Please remove the size limitation and allow developers to be productive. We have to resort to all sorts of workarounds that are not well proven. At the very least, SF should provide and document the workarounds step by step. 

**What are you trying to do**
I was trying to push an org that is about 400MB in size. It has about 40MB of static resources. But the rest are just a bunch of classes, and other SF objects. 

**Describe the solution you'd like**
As a developer, I should be able to call "sfdx force:source:push" and expect to get a 'success' message. SF should handle everything under the hood. 

**Describe alternatives you've considered**
I've considered the solution in this topic (https://github.com/forcedotcom/cli/issues/109), but it still doesn't work for me because my issue isn't just static resources. 

**Additional context**
SalesForce, please consider removing the size limits. It makes developing on your platform a real pain! Please check around and see if any other development platform has this size limitation (specifically, traditional development platforms: .net/java/etc).

**Comment by sjurgis** [comment]
Lack of roadmap by sfdx team for lifting such limits is a bit disappointing.

**Comment by clairebianchi** [comment]
@mlamrib I am passing your feedback on to the team that owns scratch orgs. I am sorry you are encountering this issue

**Comment by kfidelak94** [comment]
@mlamrib You should be able to get past the 50MB limit by enabling use of the REST API for Metadata API deploy operations (including source:push) in the CLI.  This is done by setting the "restDeploy=true" config variable in the CLI as follows:  
$ sfdx force:config:set restDeploy=true
More information on this can be found here:  https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_rest_deploy_enable_cli.htm

Note that this lifts the 50MB zipfile size limit, but the file count limit on the deploy still applies, which is currently 10,000 files.  

We expect to make REST deploy the default within the CLI in a future release.  For now it can be enabled via the environment variable as shown above.

**Comment by 0ptaq0** [comment]
Are there any plans to increase 10 000 metadata components limit as well for force:source:push/deploy?
