### ISSUE TITLE
Using sf package command with --flags-dir results in error

### ISSUE THREAD

**Issue by veaux** [forcedotcom/cli#2864]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary

Using `sf package` command with `--flags-dir` results in error:
**Flag --package can only be specified once**

### Steps To Reproduce

1. Create a `package `file in a `flag-values` directory and populate it with the Id of a package to install
2. Run the command `sf package install --flags-dir ./flag-values`

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### Expected result

Command should have retrieved package Id from file and installed package into the default org

### Actual result

`Error (1): Flag --package can only be specified once`

### System Information

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.39.6",
  "nodeVersion": "node-v20.12.2",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\Darrell\\AppData\\Local\\sf\\client\\2.39.6-6819d56",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.16 (core)",
    "@oclif/plugin-commands 3.3.1 (core)",
    "@oclif/plugin-help 6.0.21 (core)",
    "@oclif/plugin-not-found 3.1.6 (core)",
    "@oclif/plugin-plugins 5.0.14 (core)",
    "@oclif/plugin-search 1.0.23 (core)",
    "@oclif/plugin-update 4.2.7 (core)",
    "@oclif/plugin-version 2.0.17 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.8 (core)",
    "@salesforce/cli 2.39.6 (core)",
    "apex 3.1.9 (core)",
    "auth 3.6.3 (core)",
    "community 3.2.8 (user)",
    "data 3.3.2 (core)",
    "deploy-retrieve 3.6.6 (core)",
    "dev 2.3.0 (user)",
    "info 3.2.3 (core)",
    "limits 3.3.4 (core)",
    "marketplace 1.2.4 (core)",
    "org 4.1.3 (core)",
    "packaging 2.4.0 (core)",
    "schema 3.3.4 (core)",
    "settings 2.2.1 (core)",
    "signups 2.2.4 (user)",
    "sobject 1.3.6 (core)",
    "source 3.3.3 (core)",
    "telemetry 3.3.4 (core)",
    "templates 56.2.4 (core)",
    "trust 3.6.6 (core)",
    "user 3.5.2 (core)",
    "mo-dx-plugin 0.3.2 (user)",
    "sfdmu 4.33.17 (user)"
  ]
}
```

**Comment by mdonnalley** [comment]
@veaux Can you share the contents of the `package` file? As well as the debug output from running

```
DEBUG=sf:@salesforce/cli:hooks:preparse sf package install --flags-dir ./flag-values
```

Thanks!

**Comment by veaux** [comment]
With the newest version I no longer see this issue can close.
