### ISSUE TITLE
CustomObject created on v61 can't be retrieved with source tracking

### ISSUE THREAD

**Issue by ChristianMenzinger** [forcedotcom/cli#2867]
### Summary
Creating a new CustomObject in Summer'24 (v61) in a source tracked environment (scratch org) can't be retrieved with 
`sf project retrieve start`

### Steps To Reproduce
- Create a new scratch org with Summer'24 (`"release": "preview"`)
- Create a new custom object in the Salesforce Setup
- run command `sf project retrieve preview` -> will display all changes including the CustomObject
- run command `sf project retrieve start` -> will fail to retrieve the CustomObject 

NOTE: 
the "Fullname" of the CustomObject is lacking of `__c` hence the error in the retrieval
see screenshot below

> **IMPORTANT**
https://github.com/ChristianMenzinger/v61CustomObjectIssue

NOTE: empty project which only contains Layout and Profiles, which have been successfully retrieved

### Expected result
CustomObject is also retrieved by CLI

### Actual result
CLI throws an error `Entity of type 'CustomObject' named 'TestObject1' cannot be found`

### System Information
zsh 5.9 (x86_64-apple-darwin23.0)

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.40.7",
  "nodeVersion": "node-v20.12.2",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/christianmenzinger/.local/share/sf/client/2.40.7-bde121f",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.16 (core)",
    "@oclif/plugin-commands 3.3.1 (core)",
    "@oclif/plugin-help 6.0.21 (core)",
    "@oclif/plugin-not-found 3.1.7 (core)",
    "@oclif/plugin-plugins 5.0.18 (core)",
    "@oclif/plugin-search 1.0.23 (core)",
    "@oclif/plugin-update 4.2.9 (core)",
    "@oclif/plugin-version 2.0.17 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.16 (core)",
    "@oclif/plugin-which 3.1.8 (core)",
    "@salesforce/cli 2.40.7 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.5 (core)",
    "data 3.3.2 (core)",
    "deploy-retrieve 3.6.8 (core)",
    "info 3.2.4 (core)",
    "limits 3.3.4 (core)",
    "marketplace 1.2.4 (core)",
    "org 4.1.5 (core)",
    "packaging 1.26.4 (user)",
    "schema 3.3.4 (core)",
    "settings 2.2.3 (core)",
    "sobject 1.3.6 (core)",
    "source 3.3.5 (core)",
    "telemetry 3.3.4 (core)",
    "templates 56.2.4 (core)",
    "trust 3.6.7 (core)",
    "user 3.5.4 (core)"
  ]
}
```
### Additional information
<img width="955" alt="v61issue_cli" src="https://github.com/forcedotcom/cli/assets/16044068/d8d0b494-fa53-4043-bff7-304d25af0b0c">

**Comment by mshanemc** [comment]
this wasn't a CLI bug, but the people responsible for it say they've git it fixed.

**Comment by vctqs1** [comment]
@ChristianMenzinger I got the same issue, How you resolve it, could you share it please?
