### ISSUE TITLE
Cannot retrieve namespaced objects via wildcard

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#2875]
### Summary

I need to retrieve Profiles with object settings (CRUD) for a number of namespaced (managed) managed objects.  The [docs][1] for `project retrieve start` state, `Wildcards ('*') supported as long as you use quotes, such as 'ApexClass:MyClass*'`, however, every attempt to fetch these objects using wildcard fails. 

[1]: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_project_commands_unified.htm#cli_reference_project_retrieve_start_unified

### Steps To Reproduce

This can be tested in any org with a managed packed installed; I am specifically trying work with Salesforce CPQ (namespace SBQQ).

(A) Try to retrieve profiles with all object settings:
```
sf project retrieve start --metadata 'CustomObject:*' --metadata 'Profile:*'
```

(B) Try to specify the namespace:
```
sf project retrieve start --metadata 'CustomObject:SBQQ.*' --metadata 'Profile:*'
```

### Expected result
Metadata for all Objects (including Namespaced objects) are retrieved, and Profiles are retrieved with Object permissions.

### Actual result
Only local namespace objects are retrieved.

In the case of Repro (B), a message is shown after the local objects are fetched:

```
=====================================================================================
| File                   Problem
| ───────────────────────────────────────────────────────────────────────────────────
| unpackaged/package.xml Entity of type 'CustomObject' named 'SBQQ.*' cannot be found
```

### System Information

SHELL:  zsh (oh my zsh) on Mac OS Sonoma

SF CLI Version Info:
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.41.8",
  "nodeVersion": "node-v21.4.0",
  "osVersion": "Darwin 23.3.0",
  "rootPath": "/Users/jclark/.nvm/versions/node/v21.4.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.17 (core)",
    "@oclif/plugin-commands 3.3.2 (core)",
    "@oclif/plugin-help 6.0.21 (core)",
    "@oclif/plugin-not-found 3.1.8 (core)",
    "@oclif/plugin-plugins 5.0.19 (core)",
    "@oclif/plugin-search 1.0.23 (core)",
    "@oclif/plugin-update 4.2.11 (core)",
    "@oclif/plugin-version 2.0.18 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.16 (core)",
    "@oclif/plugin-which 3.1.9 (core)",
    "@salesforce/cli 2.41.8 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.9 (core)",
    "data 3.3.4 (core)",
    "deploy-retrieve 3.6.13 (core)",
    "info 3.2.7 (core)",
    "limits 3.3.5 (core)",
    "marketplace 1.2.5 (core)",
    "org 4.1.8 (core)",
    "packaging 2.4.2 (core)",
    "schema 3.3.6 (core)",
    "settings 2.2.6 (core)",
    "sobject 1.4.1 (core)",
    "source 3.3.9 (core)",
    "telemetry 3.3.5 (core)",
    "templates 56.2.5 (core)",
    "trust 3.6.8 (core)",
    "user 3.5.5 (core)"
  ]
}
```

**Comment by iowillhoit** [comment]
Hey @jclark-dot-org, can you try using `__` instead of `.` in your retrieve? For example:

`sf project retrieve start --metadata 'CustomObject:SBQQ__*'`

If you run `sf org list metadata --metadata-type CustomObject` on an org that contains some namespaced objects, you'll see the `__` used to in the `fullName`

**Comment by jclark-dot-org** [comment]
@iowillhoit Thanks, I can confirm that works.  I've also confirmed that `--metadata 'CustomObject:*__*' --metadata 'CustomObject:*'` gets all Standard and Custom Objects in all namespaces, which is a little odd, but it works.  If would be great if these details could be added to the Docs, on the reference page for `project retrieve` as well.

**Comment by iowillhoit** [comment]
Thanks @jclark-dot-org, I opened a ticket to mention this in the `project deploy` and `project retrieve` docs.
