### ISSUE TITLE
"sfdx force:user:display -u some@user.com" displays expired authentication token

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#288]
### Summary

The command above works correct for about an hour or so until the token expires. 

### Steps To Reproduce:
Consider the getUser.sh script below.
```
#!/bin/bash
# Enables easy creation of test users 
# Prints login URL 
# Pass -u username to login as specific user after creation
set -e
frontdoor='/secur/frontdoor.jsp?sid='
random=$(cat -n /usr/share/dict/words | grep -w $(jot -r 1 1 $n) | cut -f2)
function create {
  userinit=$(sfdx force:user:create --setalias $random --json)
  username=$(echo $userinit | jq -r '.result.fields.username')
  echo 'Created user' $username  
}
function assign {
  # assign some permsets
}
function get {
  userdetail=$(sfdx force:user:display -u $username --json)
  usertoken=$(echo $userdetail | jq -r '.result.accessToken')
  userinstance=$(echo $userdetail | jq -r '.result.instanceUrl')
  echo $userinstance$frontdoor$usertoken  
}
while getopts ":u" opt; do
  case $opt in
    u)
      username=$2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done
if [ ! -z "$username" ];
  then
    get
  else
    create
    get
    assign
fi
```

`./getUser.sh` will generate a new user and serve a login url for that user
Try `./getUser.sh -u new@username.org` after several hours when token expired and login link won't work.

### Expected result

Fresh token is issued

### Actual result

Stale token is displayed.

### Additional information

Sfdx / Catalina latest. The issue has been around for over 2 years.

**Comment by mshanemc** [comment]
I just ran through the steps and script and the frontdoor url worked fine.  I'm closing the issue...re-open if you still have the problem.
