### ISSUE TITLE
Picklist values not retrieved for Entitlement object

### ISSUE THREAD

**Issue by kmelessanakis** [forcedotcom/cli#2883]
### Summary
When retrieving the Entitlement object picklist values are not brought over from the org. This issue was reproduced in two unrelated orgs.

### Steps To Reproduce

Retrieve the object either from the org browser or through a package retrieve

### System Information

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.42.6",
  "nodeVersion": "node-v20.12.2",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/km****************/.local/share/sf/client/2.42.6-2b3c407",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.18 (core)",
    "@oclif/plugin-commands 3.3.4 (core)",
    "@oclif/plugin-help 6.0.22 (core)",
    "@oclif/plugin-not-found 3.1.9 (core)",
    "@oclif/plugin-plugins 5.0.21 (core)",
    "@oclif/plugin-search 1.0.24 (core)",
    "@oclif/plugin-update 4.2.12 (core)",
    "@oclif/plugin-version 2.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.19 (core)",
    "@oclif/plugin-which 3.1.10 (core)",
    "@salesforce/cli 2.42.6 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.11 (core)",
    "data 3.3.5 (core)",
    "deploy-retrieve 3.6.14 (core)",
    "info 3.2.8 (core)",
    "limits 3.3.7 (core)",
    "marketplace 1.2.5 (core)",
    "org 4.1.10 (core)",
    "packaging 2.4.4 (core)",
    "schema 3.3.6 (core)",
    "settings 2.2.6 (core)",
    "sobject 1.4.2 (core)",
    "source 3.3.12 (core)",
    "telemetry 3.3.7 (core)",
    "templates 56.2.7 (core)",
    "trust 3.6.11 (core)",
    "user 3.5.8 (core)",
    "sfdx-decomposer 3.3.10 (user)",
    "sfdx-git-delta 5.40.0 (user)"
  ]
}
```

**Comment by iowillhoit** [comment]
To pull the values for a Picklist that is on a Standard Object (eg: Account > Type), you need to run `sf project retrieve start -m StandardValueSet:AccountType`.

A list of supported Standard Value Sets can be found here:
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/standardvalueset_names.htm

(Sidenote: If you find a standard value set on that list ^ that is not working, we will likely need to add it to this registry [stdValueSetRegistry.json](https://github.com/forcedotcom/source-deploy-retrieve/blob/d242e16c4c7fe77b76ba3a64cda348fa04fae9bb/src/registry/stdValueSetRegistry.json))

You can confirm if a Standard Value Set is supported by running:
`sf data query -q "SELECT Id, MasterLabel, Metadata FROM StandardValueSet WHERE MasterLabel = 'EntitlementType'" --use-tooling-api`

In your case, you can run `sf project retrieve start -m StandardValueSet: EntitlementType`. It looks like the other picklist `EntitlementStatus` is not supported. If you need support for that, I believe you would have to open a support case for it to be assigned to the team that owns that metadata type.

**Comment by RupertBarrow** [comment]
Hi @iowillhoit , you're always putting out really detailed responses in these Github issues : thanks so much for that.
It could be very profitable to put all of these together in some kind of Knowledge base of best practices, or CLI tricks, because they are so valuable. 

> To pull the values for a Picklist that is on a Standard Object (eg: Account > Type), you need to run `sf project retrieve start -m StandardValueSet:AccountType`.
> 
> A list of supported Standard Value Sets can be found here: [developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/standardvalueset_names.htm](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/standardvalueset_names.htm)
> 
> (Sidenote: If you find a standard value set on that list ^ that is not working, we will likely need to add it to this registry [stdValueSetRegistry.json](https://github.com/forcedotcom/source-deploy-retrieve/blob/d242e16c4c7fe77b76ba3a64cda348fa04fae9bb/src/registry/stdValueSetRegistry.json))
> 
> You can confirm if a Standard Value Set is supported by running: `sf data query -q "SELECT Id, MasterLabel, Metadata FROM StandardValueSet WHERE MasterLabel = 'EntitlementType'" --use-tooling-api`
> 
> In your case, you can run `sf project retrieve start -m StandardValueSet: EntitlementType`. It looks like the other picklist `EntitlementStatus` is not supported. If you need support for that, I believe you would have to open a support case for it to be assigned to the team that owns that metadata type.
