### ISSUE TITLE
sf package1 version create exits instead of returning in 2.42.6

### ISSUE THREAD

**Issue by epavlic-revenue** [forcedotcom/cli#2884]
### Summary

`sf package1 version create` exits instead of returning.

For example, `package_version_create_result=$(sf package1 version create --package-id <my-package-id> --managed-released --name $PACKAGE_NAME --json --wait 180)` will now exit the terminal instead of waiting and returning.

This breaks CI builds.

### Expected result

`sf package1 version create` should return

### Actual result

`sf package1 version create` exits

### System Information
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.42.6",
  "nodeVersion": "node-v20.5.1",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/opt/homebrew/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.18 (core)",
    "@oclif/plugin-commands 3.3.4 (core)",
    "@oclif/plugin-help 6.0.22 (core)",
    "@oclif/plugin-not-found 3.1.9 (core)",
    "@oclif/plugin-plugins 5.0.21 (core)",
    "@oclif/plugin-search 1.0.24 (core)",
    "@oclif/plugin-update 4.2.12 (core)",
    "@oclif/plugin-version 2.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.19 (core)",
    "@oclif/plugin-which 3.1.10 (core)",
    "@salesforce/cli 2.42.6 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.11 (core)",
    "data 3.3.5 (core)",
    "deploy-retrieve 3.6.14 (core)",
    "devops-center 1.2.0 (user) published 259 days ago (Mon Sep 11 2023) (latest is 1.2.13)",
    "info 3.2.8 (core)",
    "limits 3.3.7 (core)",
    "marketplace 1.2.5 (core)",
    "org 4.1.10 (core)",
    "packaging 2.1.0 (user) published 139 days ago (Mon Jan 08 2024) (latest is 2.4.5)",
    "schema 3.3.6 (core)",
    "settings 2.2.6 (core)",
    "sobject 1.4.2 (core)",
    "source 3.3.12 (core)",
    "telemetry 3.3.7 (core)",
    "templates 56.2.7 (core)",
    "trust 3.6.11 (core)",
    "user 3.5.8 (core)",
    "sfdx-ext 0.1.4 (user) published 567 days ago (Mon Nov 07 2022)"
  ]
}
```

**Comment by iowillhoit** [comment]
Hey @epavlic-revenue, you have a user installed version of `plugin-packaging`. 
See in version logs: `"packaging 2.1.0 (user) published 139 days ago (Mon Jan 08 2024) (latest is 2.4.5)",`

Run `sf plugins uninstall @salesforce/plugin-packaging` to uninstall your user installed version and fall back to the bundled version. Afterward, you'll see something like this in the `sf version --verbose --json` command:
`"packaging 2.4.5 (core)",`

If you are still seeing this issue when the latest version of the `packaging` plugin. Please provide the full debug output by adding the `--dev-debug` flag to your command. Like so:

`sf package1 version create --package-id <my-package-id> --managed-released --name $PACKAGE_NAME --json --wait 180 --dev-debug`

Thanks

**Comment by epavlic-revenue** [comment]
@iowillhoit I'm seeing the same issue on the CI system, which does not have any user plugins.

**Comment by iowillhoit** [comment]
Ok, please provide the debug logs and we'll review

**Comment by epavlic-revenue** [comment]
It happens consistently locally and in the CI when a command like `package_version_create_result=$(sf package1 version create --package-id <my-package-id> --managed-released --name <my-package-name> --json --wait 180)` is executed.

`--dev-debug` masks the issue.

Honestly, this is something that can also be tested on your end. As a client, having to prove an issue in the hopes that it might be addressed in a couple of weeks or months is not an enjoyable experience.

In less than a month, I found and reported 3 confirmed issues with basic documented commands and options being ignored or mishandled. I'm not looking to be unpaid QA.

**Comment by mshanemc** [comment]
@epavlic-revenue thanks for reporting it.  

We're asking for repro help because we *do* test it and aren't able to reproduce this bug (there is another server-side bug I can reproduce with `package1` that the packaging team is aware of (W-15837641) and I hope that when they fix it, that fixes your problem).

I agree the command shouldn't exit without returning the error, but that's not reproducible.

If someone else can provide repro steps, debug logs, etc, we can reopen this.

**Comment by epavlic-revenue** [comment]
@mshanemc Apparently, the issue is caused when a name (stored in an environment variable here) contains spaces. The script was unchanged apart from upgrading `sf` to 2.42.6. With `SF_LOG_LEVEL=trace` and `DEBUG=sf`, `sf` shows that name is split over a multiple `args` when calling and providing a name without quotes:

`package_version_create_result=$(sf package1 version create --package-id <my-test-package-name-id>  --managed-released --name $PACKAGE_NAME --json --wait 180)`         

```
  sf                      ARGS: +0ms
  sf                         0: /usr/local/bin/node +0ms
  sf                         1: /home/circleci/.local/bin/sf +0ms
  sf                         2: package1 +0ms
  sf                         3: version +0ms
  sf                         4: create +0ms
  sf                         5: --package-id +0ms
  sf                         6: 0336F000000B3Oh +0ms
  sf                         7: --managed-released +0ms
  sf                         8: --name +0ms
  sf                         9: My +1ms
  sf                        10: Test +0ms
  sf                        11: Package +0ms
  sf                        12: Name +0ms
  sf                        13: --json +0ms
  sf                        14: --wait +0ms
  sf                        15: 180 +0ms

Exited with code exit status 2
CircleCI received exit code 2
```

When calling quoted, the command works normally:

`package_version_create_result=$(sf package1 version create --package-id <my-test-package-name-id> --managed-released --name "$PACKAGE_NAME" --json --wait 180)`

```
sf                      ARGS: +0ms
  sf                         0: /usr/local/bin/node +0ms
  sf                         1: /home/circleci/.local/bin/sf +0ms
  sf                         2: package1 +0ms
  sf                         3: version +0ms
  sf                         4: create +0ms
  sf                         5: --package-id +0ms
  sf                         6: 0336F000000B3Oh +0ms
  sf                         7: --managed-released +0ms
  sf                         8: --name +0ms
  sf                         9: My Test Package Name +0ms
  sf                        10: --json +0ms
  sf                        11: --wait +0ms
  sf                        12: 180 +0ms
```

**Comment by mshanemc** [comment]
I'm glad you found your issue.

That would have **never** worked with spaces.  CLI commands that have values with spaces have always required quotes around them (see https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_project_commands_unified.htm?q=quotes) otherwise, how would you be able to tell the end of the value vs the start of the next flag?
