### ISSUE TITLE
Please revert the progress bar

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#289]
It looks like the progress bar has caused numerous issues, the most interrupting of which seems to be truncating or dropping output that developers rely on to get information back from SFDX. The "workaround" of adding `--json` is not human friendly so it is not a workaround. On top of that, the progress bar itself apparently doesn't report the correct progress.

These issues have been open for at least two weeks now and not addressed. Could you please revert it until the issues can be addressed?

**Comment by clairebianchi** [comment]
@AndrewRayCode see my comment in https://github.com/forcedotcom/cli/issues/271
We hope to have the change out next week

**Comment by AndrewRayCode** [comment]
CC @clairebianchi @ntotten if we can help prioritize a revert, or if that's not an option, can we get some visibility into why this has blocked core functionality for five weeks now? Will there be a post mortem available for consumers of this library to understand how this issue has been ongoing for so long? I feel in the dark about understanding how this library is updated when there are critical issues. Could you also provide instructions for how to downgrade sfdx as a workaround until a fix is in place?

See
https://github.com/forcedotcom/cli/issues/274
https://github.com/forcedotcom/cli/issues/276
https://github.com/forcedotcom/cli/issues/271

![Screen Shot 2020-02-13 at 5 59 53 PM](https://user-images.githubusercontent.com/79215/74494738-a93caa00-4e8a-11ea-9f0b-5c638484687d.png)

**Comment by ntotten** [comment]
The fix for this was released two weeks back. You can see the info in the release notes: https://developer.salesforce.com/media/salesforce-cli/releasenotes.html

You can set an env variable `SFDX_USE_PROGRESS_BAR=false` to disable.

**Comment by AndrewRayCode** [comment]
@ntotten that does not work, this appears to be still broken

Command we're running:

> SFDX_USE_PROGRESS_BAR=false sfdx force:source:deploy -u OurEnvironment --testlevel RunLocalTests -x manifest/package.xml

Which has this output:

![Screen Shot 2020-02-14 at 12 01 06 PM](https://user-images.githubusercontent.com/79215/74563464-b5277b00-4f21-11ea-96c2-ffc4f10286b9.png)

It's the latest sfdx:

> sfdx-cli: Updating CLI... already on latest version: 7.45.1-bc18d49798

And not sure if this is relevant:

> Installing plugin salesforcedx... yarn add v1.21.1

Additionally, forcing end users to switch output type is not a fix, and is something sfdx itself should handle. All other cli tools like this detect TTY environments and don't add progress indicators that don't work in TTY environments automatically.

Again as this has been broken for so long it would be great to get more visibility into priority and understand how reverts / rollbacks happen

**Comment by clairebianchi** [comment]
@AndrewRayCode Do you have a specific version of salesforcedx plugin installed manually? You can check by running `sfdx plugins`. Can you please run `sfdx plugins:uninstall salesforcedx` and then run `sfdx plugins --core`? 

We fixed the TTY environment issue, the progress bar should not show up for the TTY environment. The environment var is for teams that still wanted to see the old-style output in TTY environments. If you are seeing the progress bar in TTY environments then you are likely on an older version of the saelsforcedx plugin even if you have updated the Salesforce CLI.

**Comment by AndrewRayCode** [comment]
This is in a system that on every run does:

> wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
(then installs)

and then does
> sfdx update

and then does
> sfdx plugins:install salesforcedx@latest

it fully updates on every run

**Comment by clairebianchi** [comment]
@AndrewRayCode  can you send me the output of when you run `sfdx plugins --core`?

**Comment by amphro** [comment]
We made the fix to TTY here: https://github.com/oclif/cli-ux/commit/9f57d7f0427fed2239f39ac37be71cf9ed38f3ef however it looks like we might not be depending on that version in the toolbelt. Sorry for the confusion @AndrewRayCode - well get that updated by next Thursday. 

I did verify that `SFDX_USE_PROGRESS_BAR` is in there though. After an npm install on salesforcedx@latest, I see:

```
node_modules/salesforce-alm/dist/lib/mdapi/mdapiDeployReportApi.js:        // if SFDX_USE_PROGRESS_BAR is true use progress bar, if not use old output
node_modules/salesforce-alm/dist/lib/mdapi/mdapiDeployReportApi.js:        this.useProgressBar = kit_1.env.getBoolean('SFDX_USE_PROGRESS_BAR', true);
```

Maybe there is a bug in there but it seems to work on my end. Any additional information would help.

On a side note, you don't need to run `sfdx update` OR the `plugin:install`. The wget is pointing to the most up-to-date archive which has salesforcedx bundled in it. It would probably save some time in your CI.

**Comment by sjurgis** [comment]
This is the ridicilous output I get with progress bar disabled (iTerm/oh-my-zsh):

<img width="791" alt="Screen Shot 2020-02-28 at 2 31 46 PM" src="https://user-images.githubusercontent.com/7092409/75502219-0f066580-5a37-11ea-88ca-cf7f56da4e17.png">

@clairebianchi please reopen the ticket...

**Comment by ntotten** [comment]
@sjurgis We aren't reverting the progress bar, the feedback has been overwhelmingly positive. Feel free to open a new issue explaining your problem.
