### ISSUE TITLE
cli is unable to retrieve StandardValueSet:WorkOrderStatus

### ISSUE THREAD

**Issue by i-m-anas** [forcedotcom/cli#2891]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary

Unable to retrieve `WorkOrderStatus` using cli.

### Steps To Reproduce
Tried following commands
1.  sf project retrieve start -m StandardValueSet:WorkOrderStatus
2. sf project retrieve start -x ~/Downloads/package-StandardValueSet.xml
3. sfdx force:source:retrieve -m StandardValueSet:WorkOrderStatus
4. sfdx force:source:retrieve -x ~/Downloads/package-StandardValueSet.xml

### Screenshots
1. Issue
![image](https://github.com/forcedotcom/cli/assets/41505610/505ab96e-9d7b-476b-825c-2662514a23ff)
2. cli version
<img width="526" alt="image" src="https://github.com/forcedotcom/cli/assets/41505610/db97aa4a-fa21-4d61-8923-f3f3135071d8">

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### Expected result

Created `WorkOrderStatus.standardValueSet-meta.xml`

### Actual result

```bash
unpackaged/package.xml Metadata API received improper input. Please ensure file name and capitalization is correct. Load of metadata from db failed for metadata of type:StandardValueSet and file name:71. 
```
### System Information

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.42.6",
  "nodeVersion": "node-v20.12.2",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/mars/.local/share/sf/client/2.42.6-2b3c407",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.18 (core)",
    "@oclif/plugin-commands 3.3.4 (core)",
    "@oclif/plugin-help 6.0.22 (core)",
    "@oclif/plugin-not-found 3.1.9 (core)",
    "@oclif/plugin-plugins 5.0.21 (core)",
    "@oclif/plugin-search 1.0.24 (core)",
    "@oclif/plugin-update 4.2.12 (core)",
    "@oclif/plugin-version 2.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.19 (core)",
    "@oclif/plugin-which 3.1.10 (core)",
    "@salesforce/cli 2.42.6 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.11 (core)",
    "data 3.3.5 (core)",
    "deploy-retrieve 3.6.14 (core)",
    "info 3.2.8 (core)",
    "limits 3.3.7 (core)",
    "marketplace 1.2.5 (core)",
    "org 4.1.10 (core)",
    "packaging 1.26.3 (user) published 243 days ago (Fri Sep 29 2023) (latest is 2.4.5)",
    "schema 3.3.6 (core)",
    "settings 2.2.6 (core)",
    "sobject 1.4.2 (core)",
    "source 3.3.12 (core)",
    "telemetry 3.3.7 (core)",
    "templates 56.2.7 (core)",
    "trust 3.6.11 (core)",
    "user 3.5.8 (core)",
    "sfdx-git-delta 5.40.0 (user) published 13 days ago (Thu May 16 2024)"
  ]
}
```

**Comment by cristiand391** [comment]
I'm unable to repro this:

retrieve with manifest:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>WorkOrderStatus</members>
        <name>StandardValueSet</name>
    </types>
    <version>60.0</version>
</Package>
```
![Screenshot 2024-05-30 at 3 48 05 PM](https://github.com/forcedotcom/cli/assets/6853656/efe96215-1172-4ec8-8cfe-540cd7de9c86)

retrieve with `-m StandardValueSet:WorkOrderStatus`
![Screenshot 2024-05-30 at 3 48 33 PM](https://github.com/forcedotcom/cli/assets/6853656/02fe38c4-73df-43ca-b4aa-47dc7d95261f)

are you able to repro this on a new scratch org? The error comes from the Metadata API so it's very likely related to your org.

**Comment by i-m-anas** [comment]
Interesting! I tried it with multiple orgs. but to be honest, all the sbx are copied from production so the same issue might have cascaded to them.
Let me test it with scratch org.

**Comment by i-m-anas** [comment]
I have validated this, it is not because of `cli`. 
This was caused due to the missing `Status Category` value on `Status` picklist in `Work Order`.
Thanks for looking into it @cristiand391
