### ISSUE TITLE
force:source:deploy needs  -l, --testlevel TESTLEVEL flag

### ISSUE THREAD

**Issue by aheber** [forcedotcom/cli#29]
**Is your feature request related to a problem? Please describe.**
I would like to use the `force:source:deploy` command to push to a production org, or to a sandbox but enforce unit test execution. I'm unable to find a way to do so now.

**What are you trying to do**
Use the `force:source:deploy` command to delivery minor changes to Production without having to convert all the source, strip out the thousands of pieces I don't want to push, manually trim the generated package.xml, and finally push with `force:mdapi:deploy`

**Describe the solution you'd like**
Adding in the --testlevel flag would allow this command to target Production orgs and let me do small pushes, often required pre-deployment to the source I'm trying to delivery with CI when there is a dependency that can't be pushed in the same package due to limitation with the deployment infrastructure dependency resolution/order of operations.

**Describe alternatives you've considered**
I convert to MDAPI format, then trim down the resulting output. Usually it requires deleting dozens of directories and trimming all but a small amount from the generated package.xml so it is scoped correctly.

**Comment by clairebianchi** [comment]
@aheber Thank you for the feedback. We will be adding this functionality to the Source:deploy command before we make the command GA. I can not give an exact timeline but my hope is to have the functionality done by end of April.
