### ISSUE TITLE
Auth info isolation

### ISSUE THREAD

**Issue by cerbaire** [forcedotcom/cli#290]
**Is your feature request related to a problem? Please describe.**

I would like to execute sfdx commands without authorizing an org. I use the -u flag with passing an access token instead of a username. But when I execute this command I get an error "The service and account specified in key.json do not match the version of the toolbelt.". When I call "force:auth:sfdxurl:store" before, it works perfectly.

**What are you trying to do**
I am trying to integrate SFDX CLI in a backend service. I don't want to store customers critical data on filesystem.  I worst cases, I would like to be able to isolate AuthInfo from different customers to different folders. Storing them inside hard coded $HOME/.sdfx is not a good solution for me. So sfdx:store is not a solution. 

**Describe the solution you'd like**
In order of priority :
1. Understand why using access token instead of username is not working
2. Be able to initialize the toolbelt (key.json) without authorizing an org
3. Ability to be able to override storage location of AuthInfo will be a good option (override $HOME/.sfdx folder)

**Describe alternatives you've considered**
I tried to not authorize an org and use access token with -u flag. After deleting all files in $HOME/.sfdx except key.json, it seems to work correctly. 
I wonder what is the proper way to initialize this file and ensure it is the best way to solve my problem. Maybe consider adding a - - initialize-toolbelt command?

**Comment by clairebianchi** [comment]
@cerbaire you should be able to do this, we will take a look.

**Comment by cerbaire** [comment]
As I have no official recommandation on this point I decided to take the content of an existing key.json file :
{"service":"sfdx","account":"local","key":"...."}
And set the key attribute value to a generated one.
I do that each time that file does not exist.
Then I can execute any command using my session id.

**Comment by WillieRuemmele** [comment]
Hi @cerbaire I believe this is already possible by following these steps:

1. create a new org
2. run `sfdx force:org:display` and take note of the access token, and the instance url
3. run `sfdx force:config:set instanceUrl=<instance url from above>`
4. You should now be able to delete the scratch org username's folder from within the `~/.sfdx/` folder
5. run a command with `-u '<access token>'`

If this doesn't satisfy your workflow please let me know
