### ISSUE TITLE
On upgrading to SF CLI - 2.37.4 in Jenkins pipeline (used to deploy to different environments), When running the sf login command, getting the error "reason: write EPROTO 0018D41C417F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number"

### ISSUE THREAD

**Issue by Sreelekha804** [forcedotcom/cli#2907]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
We are updating to sf cli (2.37.4) from sfdx cli (7.158.1) in the jenkins pipeline which uses the LINUX cli.
On testing using the new sf cli, we are getting the below error when running sf login command.
 
Command used: sf org login jwt -i **** -o **** -f /tmp/workspace/CRM/Salesforce_CLI_Dev_Testing/sfdxHotfixRc/server.key -r https://test.salesforce.com --set-default

error: request to https://test.salesforce.com//services/oauth2/token failed, reason: write EPROTO 0018D41C417F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

All these variables are set:
                            export NODE_EXTRA_CA_CERTS=/usr/lib/jvm/jre-1.8.0/lib/security/cacerts
                            export NODE_TLS_REJECT_UNAUTHORIZED=0
                            export PATH="${sfdxPath}:$PATH"
                            # npm config set https-proxy https://${snow_usr}:${snow_pwd}@${proxyValue}.mycompany.com:8080
                            # npm config set proxy https://${snow_usr}:${snow_pwd}@${proxyValue}.mycompany.com:8080
                            export HTTP_PROXY="http://${proxyValue}..mycompany.com:8080"
                            export HTTPS_PROXY="https://${proxyValue}..mycompany.com:8080"
                            export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
### Expected result
Currently the pipeline uses sfdx cli v7.158.1, we are able to login successfully and execute all the command to deploy into sandbox.

### Actual result
On testing with new sf cli, we are getting the ssl certificate error.
error: request to https://test.salesforce.com//services/oauth2/token failed, reason: write EPROTO 0018D41C417F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
 
### System Information

```json
14:58:59  + echo 'Executing SF version for pipeline->PipelineSalesforceValidationRC .....'
14:58:59  Executing SF version for pipeline->PipelineSalesforceValidationRC .....
14:58:59  + sf version --verbose --json
14:59:00  {
14:59:00    "architecture": "linux-x64",
14:59:00    "cliVersion": "@salesforce/cli/2.37.4",
14:59:00    "nodeVersion": "node-v20.11.1",
14:59:00    "osVersion": "Linux 5.10.214-202.855.amzn2.x86_64",
14:59:00    "rootPath": "/opt/sf",
14:59:00    "shell": "bash",
14:59:00    "pluginVersions": [
14:59:00      "@oclif/plugin-autocomplete 3.0.13 (core)",
14:59:00      "@oclif/plugin-commands 3.2.2 (core)",
14:59:00      "@oclif/plugin-help 6.0.20 (core)",
14:59:00      "@oclif/plugin-not-found 3.1.2 (core)",
14:59:00      "@oclif/plugin-plugins 5.0.7 (core)",
14:59:00      "@oclif/plugin-search 1.0.20 (core)",
14:59:00      "@oclif/plugin-update 4.2.4 (core)",
14:59:00      "@oclif/plugin-version 2.0.16 (core)",
14:59:00      "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
14:59:00      "@oclif/plugin-which 3.1.7 (core)",
14:59:00      "@salesforce/cli 2.37.4 (core)",
14:59:00      "apex 3.1.4 (core)",
14:59:00      "auth 3.5.5 (core)",
14:59:00      "data 3.2.5 (core)",
14:59:00      "deploy-retrieve 3.5.6 (core)",
14:59:00      "info 3.1.3 (core)",
14:59:00      "limits 3.2.1 (core)",
14:59:00      "marketplace 1.1.1 (core)",
14:59:00      "org 4.0.4 (core)",
14:59:00      "packaging 2.3.0 (core)",
14:59:00      "schema 3.2.1 (core)",
14:59:00      "settings 2.1.2 (core)",
14:59:00      "sobject 1.2.2 (core)",
14:59:00      "source 3.2.3 (core)",
14:59:00      "telemetry 3.1.18 (core)",
14:59:00      "templates 56.1.1 (core)",
14:59:00      "trust 3.5.4 (core)",
14:59:00      "user 3.4.3 (core)"
14:59:00    ]
14:59:00  }
14:59:00  + sf doctor
14:59:01  === Running all diagnostics
14:59:01  
14:59:01  pass - salesforcedx plugin not installed
14:59:01  pass - no linked plugins
14:59:01  pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
14:59:02  warn - [@salesforce/plugin-auth] CLI supports v2 crypto
14:59:02  unknown - using latest or latest-rc CLI version
14:59:02  
14:59:02  Wrote doctor diagnosis to: /tmp/workspace/CRM/Salesforce_CLI_Dev_Testing/sfdxValidationRC/1717613941336-diagnosis.json
14:59:02  
14:59:02  === Suggestions
14:59:02  
14:59:02    * Check https://github.com/forcedotcom/cli/issues for CLI issues posted by the community.
14:59:02    * Check http://status.salesforce.com for general Salesforce availability and performance.
14:59:02    * Your current installation of Salesforce CLI, including all the plugins you've linked and installed, doesn't yet support v2 crypto. All plugins and libraries must use at least version 6.7.0 of `@salesforce/core` to support v2 crypto. You're generally still able to successfully authenticate with your current CLI installation, but not if you generate a v2 crypto key.
14:59:02    * Couldn't determine latest CLI version due to:
14:59:02  (node:614) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
14:59:02  npm ERR! cb() never called!
14:59:02  
14:59:02  npm ERR! This is an error with npm itself. Please report this error at:
14:59:02  npm ERR!     <https://npm.community>
14:59:02  
14:59:02  npm ERR! A complete log of this run can be found in:
14:59:02  npm ERR!     /home/moddel/.npm/_logs/2024-06-05T18_59_02_477Z-debug.log
14:59:02  
14:59:03  + '[' v2 == v2 ']'
14:59:03  + echo 'SFDX Version used is -> v2.37.4'
14:59:03  SFDX Version used is -> v2.37.4
14:59:03  + echo 'SF_USER_NAME -> **** | SF_SECRET_TEXT -> ****'
14:59:03  SF_USER_NAME -> **** | SF_SECRET_TEXT -> ****
14:59:03  + export SF_USE_GENERIC_UNIX_KEYCHAIN=true
14:59:03  + SF_USE_GENERIC_UNIX_KEYCHAIN=true
```
### Additional information
Full Error :
12:02:15  + '[' v2 == v2 ']'
12:02:15  + echo 'SFDX Version used is -> v2.37.4'
12:02:15  SFDX Version used is -> v2.37.4
12:02:15  + echo 'SF_USER_NAME -> **** | SF_SECRET_TEXT -> ****'
12:02:15  SF_USER_NAME -> **** | SF_SECRET_TEXT -> ****
12:02:15  + export SF_USE_GENERIC_UNIX_KEYCHAIN=true
12:02:15  + SF_USE_GENERIC_UNIX_KEYCHAIN=true
12:02:15  + sf org login jwt -i **** -o **** -f /tmp/workspace/CRM/Salesforce_CLI_Dev_Testing/sfdxValidationRC/server.key -r https://test.salesforce.com --set-default
12:02:16  (node:617) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
12:02:16  (Use `node --trace-warnings ...` to show where the warning was created)
12:02:17  Error (1): We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here���s the error: Error authenticating with JWT.
12:02:17  Errors encountered:
12:02:17  request to https://test.salesforce.com//services/oauth2/token failed, reason: write EPROTO 00485F395E7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
12:02:17  
12:02:17  request to https://login.salesforce.com/services/oauth2/token failed, reason: write EPROTO 00485F395E7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
12:02:17  
12:02:17  request to https://test.salesforce.com//services/oauth2/token failed, reason: write EPROTO 00485F395E7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:
12:02:17

**Comment by Sreelekha804** [comment]
we can't upgrade cli to v2.44.8 at this time due to our company's new technology process

**Comment by Sreelekha804** [comment]
Below is the sf version --verbose --json and sf doctor:

+ echo 'Executing SF version for pipeline->PipelineSalesforceValidationRC .....'
Executing SF version for pipeline->PipelineSalesforceValidationRC .....
+ sf version --verbose --json
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.37.4",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Linux 5.10.214-202.855.amzn2.x86_64",
  "rootPath": "/opt/sf",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.13 (core)",
    "@oclif/plugin-commands 3.2.2 (core)",
    "@oclif/plugin-help 6.0.20 (core)",
    "@oclif/plugin-not-found 3.1.2 (core)",
    "@oclif/plugin-plugins 5.0.7 (core)",
    "@oclif/plugin-search 1.0.20 (core)",
    "@oclif/plugin-update 4.2.4 (core)",
    "@oclif/plugin-version 2.0.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.7 (core)",
    "@salesforce/cli 2.37.4 (core)",
    "apex 3.1.4 (core)",
    "auth 3.5.5 (core)",
    "data 3.2.5 (core)",
    "deploy-retrieve 3.5.6 (core)",
    "info 3.1.3 (core)",
    "limits 3.2.1 (core)",
    "marketplace 1.1.1 (core)",
    "org 4.0.4 (core)",
    "packaging 2.3.0 (core)",
    "schema 3.2.1 (core)",
    "settings 2.1.2 (core)",
    "sobject 1.2.2 (core)",
    "source 3.2.3 (core)",
    "telemetry 3.1.18 (core)",
    "templates 56.1.1 (core)",
    "trust 3.5.4 (core)",
    "user 3.4.3 (core)"
  ]
}
+ sf doctor
=== Running all diagnostics
  
pass - salesforcedx plugin not installed
pass - no linked plugins
pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
warn - [@salesforce/plugin-auth] CLI supports v2 crypto
unknown - using latest or latest-rc CLI version

Wrote doctor diagnosis to: /tmp/workspace/CRM/Salesforce_CLI_Dev_Testing/sfdxValidationRC/1717613941336-diagnosis.json

Suggestions

  * Check https://github.com/forcedotcom/cli/issues for CLI issues posted by the community.
  * Check http://status.salesforce.com for general Salesforce availability and performance.
  * Your current installation of Salesforce CLI, including all the plugins you've linked and installed, doesn't yet support v2 crypto. All plugins and libraries must use at least version 6.7.0 of `@salesforce/core` to support v2 crypto. You're generally still able to successfully authenticate with your current CLI installation, but not if you generate a v2 crypto key.
  * Couldn't determine latest CLI version due to:
(node:614) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/moddel/.npm/_logs/2024-06-05T18_59_02_477Z-debug.log

+ '[' v2 == v2 ']'
+ echo 'SFDX Version used is -> v2.37.4'
SFDX Version used is -> v2.37.4
+ echo 'SF_USER_NAME -> **** | SF_SECRET_TEXT -> ****'
SF_USER_NAME -> **** | SF_SECRET_TEXT -> ****
+ export SF_USE_GENERIC_UNIX_KEYCHAIN=true
+ SF_USE_GENERIC_UNIX_KEYCHAIN=true

**Comment by cristiand391** [comment]
7.158.1 is ~2 years old, probably was using node 14 or 16.

node v17 bumped OpenSSSL to 3.0 which might be related:
https://nodejs.org/en/blog/release/v17.0.0
https://github.com/forcedotcom/cli/issues/1857#issuecomment-1367905338

suggestion:
update to latest sfdx (v7.209.6) which includes node v18, if you get the same failure then it's likely because of the openssl change. See if `NODE_OPTIONS='--openssl-legacy-provider'` works.

**Comment by Sreelekha804** [comment]
Thanks Chris. We are upgrading to sf v2.37.4 and are using the newer sf cli commands. This version is using the node- v20.11.1".

We tried with the change NODE_OPTIONS='--openssl-legacy-provider', We still see the same error for sf org login jwt 

Error (1): We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here���s the error: Error authenticating with JWT.
14:40:58  Errors encountered:
14:40:58  request to https://test.salesforce.com//services/oauth2/token failed, reason: write EPROTO 00B8D545FD7E0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:354:

We are getting a different error in sf doctor though:
14:40:56  Wrote doctor diagnosis to: /tmp/workspace/CRM/Salesforce_CLI_Dev_Testing/sfdxValidationRC/1717699255820-diagnosis.json
14:40:56  
14:40:56  === Suggestions
14:40:56  
14:40:56    * Check https://github.com/forcedotcom/cli/issues for CLI issues posted by the community.
14:40:56    * Check http://status.salesforce.com for general Salesforce availability and performance.
14:40:56    * Couldn't determine latest CLI version due to:
14:40:56  node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
14:40:56  
14:40:56  + openssl version
14:40:56  OpenSSL 1.1.1g  21 Apr 2020
14:40:56  + '[' v2 == v2 ']'
14:40:56  + echo 'SFDX Version used is -> v2.37.4'
14:40:56  SFDX Version used is -> v2.37.4
14:40:56  + echo 'SF_USER_NAME -> **** | SF_SECRET_TEXT -> ****'
14:40:56  SF_USER_NAME -> **** | SF_SECRET_TEXT -> ****

Before using the NODE_OPTIONS='--openssl-legacy-provider' sf doctor output looked like:
 + sf doctor
[2024-06-06T18:25:09.959Z] === Running all diagnostics
[2024-06-06T18:25:09.959Z] 
[2024-06-06T18:25:09.959Z] pass - salesforcedx plugin not installed
[2024-06-06T18:25:09.959Z] pass - no linked plugins
[2024-06-06T18:25:09.959Z] pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
[2024-06-06T18:25:10.213Z] warn - [@salesforce/plugin-auth] CLI supports v2 crypto
[2024-06-06T18:25:10.467Z] unknown - using latest or latest-rc CLI version
[2024-06-06T18:25:10.467Z] 
[2024-06-06T18:25:10.467Z] Wrote doctor diagnosis to: /tmp/workspace/CRM/Salesforce_CLI_Dev_Testing/sfdxValidationRC/1717698309842-diagnosis.json
[2024-06-06T18:25:10.467Z] 
[2024-06-06T18:25:10.467Z] === Suggestions
[2024-06-06T18:25:10.467Z] 
[2024-06-06T18:25:10.467Z]   * Check https://github.com/forcedotcom/cli/issues for CLI issues posted by the community.
[2024-06-06T18:25:10.467Z]   * Check http://status.salesforce.com for general Salesforce availability and performance.
[2024-06-06T18:25:10.467Z]   * Your current installation of Salesforce CLI, including all the plugins you've linked and installed, doesn't yet support v2 crypto. All plugins and libraries must use at least version 6.7.0 of `@salesforce/core` to support v2 crypto. You're generally still able to successfully authenticate with your current CLI installation, but not if you generate a v2 crypto key.
[2024-06-06T18:25:10.467Z]   * Couldn't determine latest CLI version due to:
[2024-06-06T18:25:10.467Z] npm ERR! cb() never called!
[2024-06-06T18:25:10.467Z] 
[2024-06-06T18:25:10.467Z] npm ERR! This is an error with npm itself. Please report this error at:
[2024-06-06T18:25:10.467Z] npm ERR!     <https://npm.community>
[2024-06-06T18:25:10.467Z] 
[2024-06-06T18:25:10.467Z] npm ERR! A complete log of this run can be found in:
[2024-06-06T18:25:10.467Z] npm ERR!     /home/moddel/.npm/_logs/2024-06-06T18_25_10_394Z-debug.log
[2024-06-06T18:25:10.467Z] 
[2024-06-06T18:25:11.822Z] + ls -ltr /home/moddel/.npm/_logs/
[2024-06-06T18:25:11.822Z] total 8
[2024-06-06T18:25:11.822Z] -rw-r--r-- 1 moddel moddel 476 Jun  6 14:21 2024-06-06T18_21_51_297Z-debug.log
[2024-06-06T18:25:11.822Z] -rw-r--r-- 1 moddel moddel 476 Jun  6 14:25 2024-06-06T18_25_10_394Z-debug.log
[2024-06-06T18:25:11.822Z] + cat /home/moddel/.npm/_logs/2024-06-06T18_21_51_297Z-debug.log /home/moddel/.npm/_logs/2024-06-06T18_25_10_394Z-debug.log
[2024-06-06T18:25:11.822Z] 0 info it worked if it ends with ok
[2024-06-06T18:25:11.822Z] 1 verbose cli [ '/opt/node-v8.17.0-linux-x64/bin/node',
[2024-06-06T18:25:11.822Z] 1 verbose cli   '/opt/node/bin/npm',
[2024-06-06T18:25:11.822Z] 1 verbose cli   'view',
[2024-06-06T18:25:11.822Z] 1 verbose cli   '@salesforce/cli',
[2024-06-06T18:25:11.822Z] 1 verbose cli   'dist-tags.latest' ]
[2024-06-06T18:25:11.822Z] 2 info using npm@6.13.4
[2024-06-06T18:25:11.822Z] 3 info using node@v8.17.0
[2024-06-06T18:25:11.822Z] 4 verbose npm-session f506dba647a9af28
[2024-06-06T18:25:11.822Z] 5 timing npm Completed in 395ms
[2024-06-06T18:25:11.822Z] 6 error cb() never called!
[2024-06-06T18:25:11.822Z] 7 error This is an error with npm itself. Please report this error at:
[2024-06-06T18:25:11.822Z] 8 error <https://npm.community>
[2024-06-06T18:25:11.822Z] 0 info it worked if it ends with ok
[2024-06-06T18:25:11.822Z] 1 verbose cli [ '/opt/node-v8.17.0-linux-x64/bin/node',
[2024-06-06T18:25:11.822Z] 1 verbose cli   '/opt/node/bin/npm',
[2024-06-06T18:25:11.822Z] 1 verbose cli   'view',
[2024-06-06T18:25:11.822Z] 1 verbose cli   '@salesforce/cli',
[2024-06-06T18:25:11.822Z] 1 verbose cli   'dist-tags.latest' ]
[2024-06-06T18:25:11.822Z] 2 info using npm@6.13.4
[2024-06-06T18:25:11.822Z] 3 info using node@v8.17.0
[2024-06-06T18:25:11.822Z] 4 verbose npm-session 29ed78e6017f63f5
[2024-06-06T18:25:11.822Z] 5 timing npm Completed in 392ms
[2024-06-06T18:25:11.822Z] 6 error cb() never called!
[2024-06-06T18:25:11.822Z] 7 error This is an error with npm itself. Please report this error at:
[2024-06-06T18:25:11.822Z] 8 error <https://npm.community>

**Comment by Sreelekha804** [comment]
We made a change to the environment variable HTTPS_PROXY, from **https:** to **http:**
 
The environment variable looks:
export NODE_EXTRA_CA_CERTS=/usr/lib/jvm/jre-1.8.0/lib/security/cacerts
export NODE_TLS_REJECT_UNAUTHORIZED=0
export PATH="${sfdxPath}:$PATH"
export HTTP_PROXY="http://${proxyValue}.fhlmc.com:9400"
export HTTPS_PROXY="**http:**//${proxyValue}.fhlmc.com:9400"
 
With this change, sf org login jwt command works as expected.

**Comment by Jugal-asymbl** [comment]
Hey @Sreelekha804 
We need to update salesforce CLI version in our jenkins environment. I know that this is not the right thread to post this but we need help on this urgently.
Can you please help us?
Thanks
