### ISSUE TITLE
Required --manifest Parameter with the metadata dir tag 

### ISSUE THREAD

**Issue by DilipJainFL** [forcedotcom/cli#2909]
> **Note** 
Currently I am using the Latest SF CLI V2 -  **@salesforce/cli/2.42.6 wsl-x64 node-v20.14.0** ,  and facing one issue with the deployment when utilizing the --metdata dir tag to deploy a single package (Zip) file.  
** I have use case to use the metadata dir only with the project***
** Also I am using the purge on delete tag to delete data from Recycle bin as well.**
But when I am passing the parameters and tags using the below command 
`sf project deploy start -o username --metadata-dir ${buildZip} -g -w 1665 --single-package --post-destructive-changes build/destructiveChangesPost.xml --verbose --purge-on-delete`
![image](https://github.com/forcedotcom/cli/assets/138577410/bafdb917-1cfc-4c4e-ba5d-13fcf35b8fad)

*** Now When adding the --manifiest to handle the above error receving one more error that can not use the manifest with --metadata dir**
`sf project deploy start -o ${env.bamboo_sf_username} --metadata-dir ${buildZip} -g -w ${env.bamboo_sf_maxWaitMillis} --single-package --manifest package.xml --post-destructive-changes build/destructiveChangesPost.xml --verbose --purge-on-delete`

![image](https://github.com/forcedotcom/cli/assets/138577410/7097f846-1ae7-4e75-b027-2efa87c6cd60)

### Summary
In summarizaed words would like to deploy a zip with purge on delete using the SF CLI with metdata dir tag. leveraging the first command added above.

**Comment by DilipJainFL** [comment]
Updated the description  -  
here is the version  -  @salesforce/cli/2.42.6 wsl-x64 node-v20.14.0

**Comment by cristiand391** [comment]
`--purge-on-delete` requires `--manifest`.

You can pass a manifest or a zip file, but not both.

**Comment by DilipJainFL** [comment]
If you check the first message I have tried to use the only with zip but then it was asking for the --purge-on-delete requires manifest file. 
![image](https://github.com/forcedotcom/cli/assets/138577410/318fe760-7f0c-4189-8cdc-a83a708eb196)

**Comment by cristiand391** [comment]
> If you check the first message I have tried to use the only with zip but then it was asking for the --purge-on-delete requires manifest file.

that's what I mentioned above, you can pass a manifest or a zip file but not both.

`--purge-on-delete` only works when deploying with`--manifest`.

**Comment by DilipJainFL** [comment]
Thanks for the Reply.  
But When I am trying with the similar SFDX command It is working fine  -  
`sfdx force:mdapi:deploy -u username -f ${buildZip} -g -w 1665 -s -l NoTestRun --purgeondelete --verbose`

**Comment by shetzel** [comment]
Looks like a bug.  We'll change the command so that `--purge-on-delete` does not require `--manifest`.

**Comment by chulai** [comment]
@shetzel, I agree this seems to be a bug. My thoughts:

--purgeondelete works with METADATA API FORMAT using sfdx force:mdapi:deploy.
--purge-on-delete does not work with METADATA API FORMAT using sf project deploy start.
--metadata-dir flag is used with sf-style command to deploy with METADATA API FORMAT.
--purge-on-delete flag should not require --manifest. This is a SOURCE FORMAT FLAGS that doesn't apply to METADATA API FORMAT deployments.
--purge-on-delete flag should not require --pre-destructive-changes or --post-destructive-changes either if --metadata-dir includes a zip file of metadata formatted files to deploy. This zip file should include a package.xml file, and any destructiveChangesPre.xml or destructiveChangesPost.xml files.

**Comment by DilipJainFL** [comment]
@mshanemc Could you please share details about the completions for this ticket and what is solution to resolve the issue. 
I'm able to use the below command 
`sf project deploy start -o username --metadata-dir build_1.zip -g -w 35791 --single-package --purge-on-delete --verbose`
but It's not throwing any error but It's not deleting the components from the org. 

Please share the details about this. 
Thanks!

**Comment by mshanemc** [comment]
Does your zip file include at least one destructiveChangesPre|Post file?  Want to provide a sample project that replicates your issue?

docs now say
> Deploy all metadata formatted files in the "MDAPI" directory; items listed in the MDAPI/destructiveChangesPre.xml and MDAPI/destructiveChangesPost.xml manifests are immediately eligible for deletion rather than stored in the Recycle Bin:

**Comment by DilipJainFL** [comment]
Yes It have the post file. 
![image](https://github.com/user-attachments/assets/2cb047bc-1c6f-4c69-bb2e-2d173bec0e82)

**Comment by DilipJainFL** [comment]
@mshanemc Could you please share any general example that worked for you in the dev environment.
