### ISSUE TITLE
asynchronous force:source:retrieve process like force:mdapi:retrieve 

### ISSUE THREAD

**Issue by cerbaire** [forcedotcom/cli#291]
**Is your feature request related to a problem? Please describe.**
I have implemented a process to check some operations results from soap operations. SFDX CLI with - - json parameter seems to be fully compatible with force:mdapi asynchronous operation. 
But for force:source:retrieve, it seems not possible to switch to asynchronous mode to get a jobid that we can then report with force:source:retrieve:report. 

**What are you trying to do**
I am trying to migrate soap call to metadata api to SFDX CLI call, but source:retrieve process migration is not straightforward. 

**Describe the solution you'd like**
I would like the force:source:retrieve process behave the same way than force:mdapi:retrieve :
1. Asynchronous mode
2. Report method
3. Same basic json response status properties to check execution of the process. 

**Describe alternatives you've considered**
I tried to develop some specific code for source retrieve but I prefer to have generic code independent of opertion type. 

**Additional context**
At a simple solution, it would be great to have the same basic response status information result that mdapi:retrieve, added to the current inboundFiles information.

**Comment by clairebianchi** [comment]
@cerbaire if you add `--wait 0` to the command it will make it asynchronous. This is not currently documented. I will make sure we update that soon.

**Comment by cerbaire** [comment]
@clairebianchi 
When I execute the following command:
sfdx force:source:retrieve -x D:/sfdxProject/package.xml -u 00D5J...Bfy_ --json --verbose --wait 0 2>&1
I get the following error
{
    "status": 1,
    "name": "InvalidFlagNumericBoundsError",
    "message": "Expected minutes greater than or equal to 1 but received 0",
    "exitCode": 1,
    "commandName": "SourceRetrieveCommand",
    "stack": "InvalidFlagNumericBoundsError: Expected minutes greater than or equal to 1 but received 0\

Also I can't find how to ensure I have the latest version of SFDX CLI.
sfdx --version
sfdx-cli/7.46.1-3d2451fad8 win32-x64 node-v10.15.3
But release notes says latest version is 47.18.0 !?
https://developer.salesforce.com/media/salesforce-cli/releasenotes.html

**Comment by clairebianchi** [comment]
@cerbaire run sfdx plugins --core, this will give you the version of both the CLI as well as the salesforcedx plugin which has all the force commands.

**Comment by cerbaire** [comment]
@clairebianchi  thanks for your response. Any idea why --wait 0 parameter return this error ?

**Comment by clairebianchi** [comment]
@cerbaire Just to be sure I understand this is the command you are running:
`sfdx force:source:retrieve -x D:/sfdxProject/package.xml -u 00D5J...Bfy_ --json --verbose --wait 0`
This should make it async. If you could update your CLI to the most recent version and confirm with the command I send before and try again. If you are still seeing the error I will have someone on my team take a look.

**Comment by cerbaire** [comment]
@clairebianchi Yes, it is the command I execute. Please find below another test with the callstack.
I don't think it is related, but please note that none of my orgs are authorized. I have also shorten the session id in the provided command line.

sfdx --version
sfdx-cli/7.45.1-bc18d49798 win32-x64 node-v10.15.3
sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.0 (core)
generator 1.1.2 (core)
salesforcedx 47.18.0 (core)
├─ salesforcedx-templates 47.19.0 (core)
└─ salesforce-alm 47.16.0 (core)

sfdx-cli 7.45.1 (core)
sfdx update
sfdx-cli: Updating CLI from 7.45.1-bc18d49798 to 7.47.0-0e5d18732f... done

sfdx --version
sfdx-cli/7.47.0-0e5d18732f win32-x64 node-v10.15.3

sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.2.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.3.0 (core)
└─ salesforce-alm 48.3.0 (core)

sfdx-cli 7.47.0 (core)

sfdx force:source:retrieve -x D:/sfdxProject/package.xml -u 00D5J00...AiUd --wait 0 --json
{
  "status": 1,
  "name": "InvalidFlagNumericBoundsError",
  "message": "Expected minutes greater than or equal to 1 but received 0",
  "exitCode": 1,
  "commandName": "SourceRetrieveCommand",
  "stack": "InvalidFlagNumericBoundsError: Expected minutes greater than or equal to 1 but received 0\n    at validateBounds (C:\\Users\\simon\\AppData\\Local\\sfdx\\client\\7.47.0-0e5d18732f\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\command\\lib\\sfdxFlags.js:355:15)\n    at Object.option [as parse] (C:\\Users\\simon\\AppData\\Local\\sfdx\\client\\7.47.0-0e5d18732f\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\command\\lib\\sfdxFlags.js:145:39)\n    at Parser._flags (C:\\Users\\simon\\AppData\\Local\\sfdx\\client\\7.47.0-0e5d18732f\\node_modules\\@oclif\\parser\\lib\\parse.js:152:49)\n    at Parser.parse (C:\\Users\\simon\\AppData\\Local\\sfdx\\client\\7.47.0-0e5d18732f\\node_modules\\@oclif\\parser\\lib\\parse.js:113:28)\n    at Object.parse (C:\\Users\\simon\\AppData\\Local\\sfdx\\client\\7.47.0-0e5d18732f\\node_modules\\@oclif\\parser\\lib\\index.js:25:27)\n    at SourceRetrieveCommand.parse (C:\\Users\\simon\\AppData\\Local\\sfdx\\client\\7.47.0-0e5d18732f\\node_modules\\@oclif\\command\\lib\\command.js:83:41)\n    at SourceRetrieveCommand.init (C:\\Users\\simon\\AppData\\Local\\sfdx\\client\\7.47.0-0e5d18732f\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:204:44)",
  "warnings": []
}

**Comment by clairebianchi** [comment]
@cerbaire I am incredibly sorry, --wait 0 works on source:deploy but not retrieve. I always get questions about deploy but not retrieve and just read the wrong word. We have this on our roadmap for next quarter.
