### ISSUE TITLE
Unable to deploy package.xml.INVALID_OPERATION: Too many files in zip

### ISSUE THREAD

**Issue by parasharsumedh5** [forcedotcom/cli#2910]
### Expected result
Deployment should be successful.
Package.xml contains around 3.7k components and when SFDX_MDAPI_TEMP environment variable is set temp files are generated of size 17.9 MB.

### Actual result
Deployment fails with error : INVALID_OPERATION: Too many files in zip

### System Information

```
@salesforce/cli/2.44.8 darwin-x64 node-v20.13.1
@oclif/plugin-autocomplete 3.0.18 (core)
@oclif/plugin-commands 3.3.4 (core)
@oclif/plugin-help 6.0.22 (core)
@oclif/plugin-not-found 3.1.10 (core)
@oclif/plugin-plugins 5.1.3 (core)
@oclif/plugin-search 1.0.24 (core)
@oclif/plugin-update 4.2.14 (core)
@oclif/plugin-version 2.1.2 (core)
@oclif/plugin-warn-if-update-available 3.0.19 (core)
@oclif/plugin-which 3.1.10 (core)
@salesforce/cli 2.44.8 (core)
apex 3.1.13 (core)
auth 3.6.17 (core)
data 3.4.3 (core)
deploy-retrieve 3.8.3 (core)
info 3.3.3 (core)
limits 3.3.9 (core)
marketplace 1.2.8 (core)
org 4.1.14 (core)
packaging 2.4.5 (core)
schema 3.3.9 (core)
settings 2.2.7 (core)
sobject 1.4.6 (core)
source 3.3.18 (core)
telemetry 3.3.11 (core)
templates 56.2.9 (core)
trust 3.7.3 (core)
user 3.5.11 (core)
```

```
SF ENV. VARS.
SF_BINPATH,/Users/****/.local/share/sf/client/bin/sf
SF_AUTOUPDATE_DISABLE,true
SF_DISABLE_AUTOUPDATE,true
SF_UPDATE_INSTRUCTIONS,Use "npm update --global @salesforce/cli" to update npm-based installations.
```

```
Windows: false
Shell: zsh
Channel: stable
```
---
### Diagnostics
:white_check_mark: pass - salesforcedx plugin not installed
:white_check_mark: pass - no linked plugins
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.yarnpkg.com
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org/
:white_check_mark: pass - using latest or latest-rc CLI version
:white_check_mark: pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
:white_check_mark: pass - [@salesforce/plugin-deploy-retrieve] default target DevHub max apiVersion matches default target org max apiVersion
:x: warn - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches default target org max apiVersion
:white_check_mark: pass - can access: https://test.salesforce.com
:white_check_mark: pass - can access: https://appexchange.salesforce.com/services/data
:white_check_mark: pass - [@salesforce/plugin-auth] CLI supports v2 crypto
:white_check_mark: pass - can access: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64-buildmanifest

**Comment by shetzel** [comment]
>Deployment fails with error : INVALID_OPERATION: Too many files in zip

That error comes from the server and means there are over 10,000 files in the zip file sent with the deploy.  The `SF_MDAPI_TEMP_DIR` environment variable can be used to see all the files within the zip, but doesn't cause the failure.  It's only to help debug problems.  If you unset that env var you'll see the same error.

See this doc:
https://developer.salesforce.com/docs/atlas.en-us.salesforce_app_limits_cheatsheet.meta/salesforce_app_limits_cheatsheet/salesforce_app_limits_platform_metadata.htm?_ga=2.267468238.151983424.1719251687-125335880.1718988572
