### ISSUE TITLE
Salesforce CLI Update warning

### ISSUE THREAD

**Issue by avaHitesh-github** [forcedotcom/cli#2918]
### Summary
I've updated the SF CLI to latest version, verbose detailed shared below

### Steps To Reproduce
1. Update to latest Salesforce CLI
2. Install latest commerce plugin using `sf plugins:install @salesforce/commerce `
3. Run the command: `sf commerce:store:create -n b2bstore01 -o b2b -b b2bbuyer@gmail.com -u b2b_june_v1 -v devhub`
4. Receives the warning: `Warning: @salesforce/cli update available from 2.11.8 to 2.45.6`

### Expected result
Warning shouldn't be there

### Actual result
Receives the warning: `Warning: @salesforce/cli update available from 2.11.8 to 2.45.6`

### System Information
zsh shell

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.45.6",
  "nodeVersion": "node-v20.13.1",
  "osVersion": "Darwin 23.5.0",
  "rootPath": "/Users/hitesh.godha@avalara.com/.local/share/sf/client/2.45.6-3aaf41e",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.1.2 (core)",
    "@oclif/plugin-commands 4.0.2 (core)",
    "@oclif/plugin-help 6.1.0 (core)",
    "@oclif/plugin-not-found 3.2.2 (core)",
    "@oclif/plugin-plugins 5.2.2 (core)",
    "@oclif/plugin-search 1.1.1 (core)",
    "@oclif/plugin-update 4.3.3 (core)",
    "@oclif/plugin-version 2.2.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.4 (core)",
    "@oclif/plugin-which 3.2.1 (core)",
    "@salesforce/cli 2.45.6 (core)",
    "@salesforce/commerce 250.1.0 (user) published 176 days ago (Tue Dec 19 2023)",
    "apex 3.1.14 (core)",
    "auth 3.6.17 (core)",
    "community 3.2.18 (user) published 0 days ago (Thu Jun 13 2024)",
    "data 3.4.3 (core)",
    "deploy-retrieve 3.8.4 (core)",
    "info 3.3.4 (core)",
    "limits 3.3.10 (core)",
    "marketplace 1.2.10 (core)",
    "org 4.1.19 (core)",
    "packaging 2.4.5 (core)",
    "schema 3.3.10 (core)",
    "settings 2.3.0 (core)",
    "sobject 1.4.8 (core)",
    "source 3.3.21 (core)",
    "telemetry 3.3.12 (core)",
    "templates 56.2.9 (core)",
    "trust 3.7.4 (core)",
    "user 3.5.11 (core)",
    "@salesforce/sfdx-scanner 4.2.0 (user) published 15 days ago (Tue May 28 2024) (latest is 3.25.0)",
    "sfdmu 4.33.17 (user) published 41 days ago (Thu May 02 2024)"
  ]
}
```
### Additional information
NA

**Comment by shetzel** [comment]
Typically, this means you have multiple CLI's installed.  E.g., a version installed with an installer and a version installed via npm.  Please follow these steps to completely uninstall: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

After you uninstall, typing `which sf` should not return anything.  Then you can install the CLI using the desired method and continue.

**Comment by avaHitesh-github** [comment]
Thanks for the help @shetzel !
