### ISSUE TITLE
force:mdapi:listmetadata with multiple metadata types

### ISSUE THREAD

**Issue by cerbaire** [forcedotcom/cli#292]
**Is your feature request related to a problem? Please describe.**
When I call the force:mdapi:listmetadata function, I am not able to pass multiple metadatatypes to -m parameter. 

**What are you trying to do**
I tried using comma separator as well as pipe, semicolon, and enclose the whole value with quotes, but none of these combinations is working

**Describe the solution you'd like**
Using soap call, you can have up to 3 metadatypes in the header to limit the number of API call. I would like to achieve the same with SFDX CLI. 

**Describe alternatives you've considered**

**Additional context**

**Comment by clairebianchi** [comment]
@cerbaire I will pass your feature request on to the team that owns this command, Thank you for your feedback.
