### ISSUE TITLE
Package subscriber ID exists in Dev Hub org, but no subscriber package version record found in scratch org

### ISSUE THREAD

**Issue by epavlic-revenue** [forcedotcom/cli#2921]
### Summary

`sf package install --package <version-id> --wait 30` outputs `The subscriber package version <version-id> is invalid, no subscriber package version record found`.

`sf package1 version list --target-org dev-hub` lists the `<version-id>`.

Trying to install manually gives a different error:

> The AppExchange Application or component you have selected is not yet available on your instance of salesforce.com. Please check back in a few days to retry the installation.

The version in question was packaged 1 day ago.

### Expected result

If a package version exists in the `sf package1 version list --target-org dev-hub` it should be propagated to Salesforce instances in under a day.

### Actual result

Package version appears not to have been propagated, and the error message is confusing.

### System Information
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.42.6",
  "nodeVersion": "node-v20.5.1",
  "osVersion": "Darwin 23.5.0",
  "rootPath": "/opt/homebrew/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.18 (core)",
    "@oclif/plugin-commands 3.3.4 (core)",
    "@oclif/plugin-help 6.0.22 (core)",
    "@oclif/plugin-not-found 3.1.9 (core)",
    "@oclif/plugin-plugins 5.0.21 (core)",
    "@oclif/plugin-search 1.0.24 (core)",
    "@oclif/plugin-update 4.2.12 (core)",
    "@oclif/plugin-version 2.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.19 (core)",
    "@oclif/plugin-which 3.1.10 (core)",
    "@salesforce/cli 2.42.6 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.11 (core)",
    "data 3.3.5 (core)",
    "deploy-retrieve 3.6.14 (core)",
    "devops-center 1.2.10 (user) published 34 days ago (Thu May 09 2024) (latest is 1.2.14)",
    "info 3.2.8 (core)",
    "limits 3.3.7 (core)",
    "marketplace 1.2.5 (core)",
    "org 4.1.10 (core)",
    "packaging 2.4.4 (core)",
    "schema 3.3.6 (core)",
    "settings 2.2.6 (core)",
    "sobject 1.4.2 (core)",
    "source 3.3.12 (core)",
    "telemetry 3.3.7 (core)",
    "templates 56.2.7 (core)",
    "trust 3.6.11 (core)",
    "user 3.5.8 (core)"
  ]
}
```

**Comment by epavlic-revenue** [comment]
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.45.6",
  "nodeVersion": "node-v20.5.1",
  "osVersion": "Darwin 23.5.0",
  "rootPath": "/opt/homebrew/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.1.2 (core)",
    "@oclif/plugin-commands 4.0.2 (core)",
    "@oclif/plugin-help 6.1.0 (core)",
    "@oclif/plugin-not-found 3.2.2 (core)",
    "@oclif/plugin-plugins 5.2.2 (core)",
    "@oclif/plugin-search 1.1.1 (core)",
    "@oclif/plugin-update 4.3.3 (core)",
    "@oclif/plugin-version 2.2.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.4 (core)",
    "@oclif/plugin-which 3.2.1 (core)",
    "@salesforce/cli 2.45.6 (core)",
    "apex 3.1.14 (core)",
    "auth 3.6.17 (core)",
    "data 3.4.3 (core)",
    "deploy-retrieve 3.8.4 (core)",
    "devops-center 1.2.10 (user) published 34 days ago (Thu May 09 2024) (latest is 1.2.14)",
    "info 3.3.4 (core)",
    "limits 3.3.10 (core)",
    "marketplace 1.2.10 (core)",
    "org 4.1.19 (core)",
    "packaging 2.4.5 (core)",
    "schema 3.3.10 (core)",
    "settings 2.3.0 (core)",
    "sobject 1.4.8 (core)",
    "source 3.3.21 (core)",
    "telemetry 3.3.12 (core)",
    "templates 56.2.9 (core)",
    "trust 3.7.4 (core)",
    "user 3.5.11 (core)"
  ]
}
```

**Comment by shetzel** [comment]
Is it a 1GP or 2GP package?  Looks like you're mixing the commands.  `package1` are commands for 1GP.  `package` are commands for 2GP.

**Comment by epavlic-revenue** [comment]
@shetzel It's a 1GP package, and `package install` should be for either 1GP or 2GP. It used to work for 1GP, and it still does for older versions (for example, on my instance two versions or more behind last work, while the last one and the one before last do not). `package1` has only `version` `create`, `display`, `list`.

**Comment by shetzel** [comment]
Is this issue about the error message that you'd like improved or about propagation?  The CLI team can enhance the error message but propagation is controlled by the server.  Customer support could look into the propagation delays.

**Comment by epavlic-revenue** [comment]
@shetzel If that's the distribution of responsibilities, I'm happy for the error message to be made clearer — `The subscriber package version <version-id> is invalid` is not true, as the version has been valid for a day.

**Comment by dschibster** [comment]
Chiming in to say that this is also happening for me in Scratch Org Pooling. Over the weekend a new version of vlocity_cmt was released, which failed to install on scratch orgs with the exact same error message. As far as I'm able to see, the previous package version can get installed just fine, the CI pipeline I use didn't fail at the time the other one did, but keeps on running.
