### ISSUE TITLE
Programmatic error: cannot use savepoint that are rolled back" during Path Assistant Metadata Deployment

### ISSUE THREAD

**Issue by adityasfdev** [forcedotcom/cli#2925]
When deploying Path Assistant metadata to one of my Salesforce sandboxes, which was retrieved from another development sandbox using Workbench, I encountered the following errors using the sf project deploy start --metadata-dir delta/. -w AliasName -w 10 command.

1. java.lang.IllegalStateException: Programmer error: Cannot use savepoints that are rolled back Savepoints info - this savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savepoint name = SP_23000. Given savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savepoint name = . Field info: entity name = PathAssistantStepInfo, field name = DeveloperName.
2. An unknown exception has occurred.

please help me to figure out what's going on and how to figure it out

**Comment by adityasfdev** [comment]
sf project deploy start --metadata-dir delta/. -o SFDC-QAFull -w 10 --verbose --json
{
  "status": 1,
  "result": {
    "checkOnly": false,
    "completedDate": "2024-06-14T11:43:32.000Z",
    "createdBy": "0056f00000ANUm2",
    "createdByName": "SFDC Deployment",
    "createdDate": "2024-06-14T11:43:28.000Z",
    "details": {
      "componentFailures": [
        {
          "changed": false,
          "componentType": "PathAssistant",
          "created": false,
          "createdDate": "2024-06-14T11:43:32.000Z",
          "deleted": false,
          "fileName": "zip/pathAssistants/ARS_Lighting.pathAssistant",
          "fullName": "ARS_Lighting",
          "problem": "java.lang.IllegalStateException: Programmer error: Cannot use savepoints that are rolled back
Savepoints info - this savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savep
oint name = SP_23598. Given savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back
savepoint name = . Field info: entity name = PathAssistantStepInfo, field name = DeveloperName.",
          "problemType": "Error",
          "success": false
        },
        {
          "changed": false,
          "componentType": "PathAssistant",
          "created": false,
          "createdDate": "2024-06-14T11:43:32.000Z",
          "deleted": false,
          "fileName": "zip/pathAssistants/Forklift.pathAssistant",
          "fullName": "Forklift",
          "problem": "java.lang.IllegalStateException: Programmer error: Cannot use savepoints that are rolled back
Savepoints info - this savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savep
oint name = SP_23601. Given savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back
savepoint name = . Field info: entity name = PathAssistantStepInfo, field name = DeveloperName.",
          "problemType": "Error",
          "success": false
        },
        {
          "changed": false,
          "componentType": "PathAssistant",
          "created": false,
          "createdDate": "2024-06-14T11:43:32.000Z",
          "deleted": false,
          "fileName": "zip/pathAssistants/Racking.pathAssistant",
          "fullName": "Racking",
          "problem": "An unknown exception has occurred.",
          "problemType": "Error",
          "success": false
        }
      ],
      "componentSuccesses": [
        {
          "changed": true,
          "componentType": "",
          "created": false,
          "createdDate": "2024-06-14T11:43:32.000Z",
          "deleted": false,
          "fileName": "zip/package.xml",
          "fullName": "package.xml",
          "success": true
        }
      ],
      "runTestResult": {
        "numFailures": 0,
        "numTestsRun": 0,
        "totalTime": 0,
        "codeCoverage": [],
        "codeCoverageWarnings": [],
        "failures": [],
        "flowCoverage": [],
        "flowCoverageWarnings": [],
        "successes": []
      }
    },
    "done": true,
    "id": "0AfEa00000CRDQXKA5",
    "ignoreWarnings": false,
    "lastModifiedDate": "2024-06-14T11:43:32.000Z",
    "numberComponentErrors": 3,
    "numberComponentsDeployed": 0,
    "numberComponentsTotal": 3,
    "numberTestErrors": 0,
    "numberTestsCompleted": 0,
    "numberTestsTotal": 0,
    "rollbackOnError": true,
    "runTestsEnabled": false,
    "startDate": "2024-06-14T11:43:29.000Z",
    "status": "Failed",
    "success": false,
    "files": [
      {
        "error": "java.lang.IllegalStateException: Programmer error: Cannot use savepoints that are rolled back Save
points info - this savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savepoint
 name = SP_23598. Given savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back save
point name = . Field info: entity name = PathAssistantStepInfo, field name = DeveloperName.",
        "problemType": "Error",
        "fullName": "ARS_Lighting",
        "type": "PathAssistant",
        "state": "Failed",
        "filePath": "zip/pathAssistants/ARS_Lighting.pathAssistant"
      },
      {
        "error": "java.lang.IllegalStateException: Programmer error: Cannot use savepoints that are rolled back Save
points info - this savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savepoint
 name = SP_23601. Given savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back save
point name = . Field info: entity name = PathAssistantStepInfo, field name = DeveloperName.",
        "problemType": "Error",
        "fullName": "Forklift",
        "type": "PathAssistant",
        "state": "Failed",
        "filePath": "zip/pathAssistants/Forklift.pathAssistant"
      },
      {
        "error": "An unknown exception has occurred.",
        "problemType": "Error",
        "fullName": "Racking",
        "type": "PathAssistant",
        "state": "Failed",
        "filePath": "zip/pathAssistants/Racking.pathAssistant"
      }
    ]
  },
  "warnings": []
}

**Comment by adityasfdev** [comment]
please find the updated information
sf project deploy start --metadata-dir delta/. -o SFDC-QAFull -w 10 --verbose --json
{
  "status": 1,
  "result": {
    "checkOnly": false,
    "completedDate": "2024-06-14T11:43:32.000Z",
    "createdBy": "xxxxxxxxxxxx",
    "createdByName": "xxxxxxxxxxxx",
    "createdDate": "2024-06-14T11:43:28.000Z",
    "details": {
      "componentFailures": [
        {
          "changed": false,
          "componentType": "PathAssistant",
          "created": false,
          "createdDate": "2024-06-14T11:43:32.000Z",
          "deleted": false,
          "fileName": "xxxxxxxxxxxx",
          "fullName": "xxxxxxxxxxxx",
          "problem": "java.lang.IllegalStateException: Programmer error: Cannot use savepoints that are rolled back
Savepoints info - this savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savep
oint name = SP_23598. Given savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back
savepoint name = . Field info: entity name = PathAssistantStepInfo, field name = DeveloperName.",
          "problemType": "Error",
          "success": false
        },
        {
          "changed": false,
          "componentType": "PathAssistant",
          "created": false,
          "createdDate": "2024-06-14T11:43:32.000Z",
          "deleted": false,
          "fileName": "xxxxxxxxxxxx",
          "fullName": "xxxxxxxxxxxx",
          "problem": "java.lang.IllegalStateException: Programmer error: Cannot use savepoints that are rolled back
Savepoints info - this savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savep
oint name = SP_23601. Given savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back
savepoint name = . Field info: entity name = PathAssistantStepInfo, field name = DeveloperName.",
          "problemType": "Error",
          "success": false
        },
        {
          "changed": false,
          "componentType": "PathAssistant",
          "created": false,
          "createdDate": "2024-06-14T11:43:32.000Z",
          "deleted": false,
          "fileName": "zxxxxxxxxxxxx",
          "fullName": "xxxxxxxxxxxx",
          "problem": "An unknown exception has occurred.",
          "problemType": "Error",
          "success": false
        }
      ],
      "componentSuccesses": [
        {
          "changed": true,
          "componentType": "",
          "created": false,
          "createdDate": "2024-06-14T11:43:32.000Z",
          "deleted": false,
          "fileName": "zip/package.xml",
          "fullName": "package.xml",
          "success": true
        }
      ],
      "runTestResult": {
        "numFailures": 0,
        "numTestsRun": 0,
        "totalTime": 0,
        "codeCoverage": [],
        "codeCoverageWarnings": [],
        "failures": [],
        "flowCoverage": [],
        "flowCoverageWarnings": [],
        "successes": []
      }
    },
    "done": true,
    "id": "xxxxxxxxxxxx",
    "ignoreWarnings": false,
    "lastModifiedDate": "2024-06-14T11:43:32.000Z",
    "numberComponentErrors": 3,
    "numberComponentsDeployed": 0,
    "numberComponentsTotal": 3,
    "numberTestErrors": 0,
    "numberTestsCompleted": 0,
    "numberTestsTotal": 0,
    "rollbackOnError": true,
    "runTestsEnabled": false,
    "startDate": "2024-06-14T11:43:29.000Z",
    "status": "Failed",
    "success": false,
    "files": [
      {
        "error": "java.lang.IllegalStateException: Programmer error: Cannot use savepoints that are rolled back Save
points info - this savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savepoint
 name = SP_23598. Given savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back save
point name = . Field info: entity name = PathAssistantStepInfo, field name = DeveloperName.",
        "problemType": "Error",
        "fullName": "xxxxxxxxxxxx",
        "type": "PathAssistant",
        "state": "Failed",
        "filePath": "xxxxxxxxxxxx"
      },
      {
        "error": "java.lang.IllegalStateException: Programmer error: Cannot use savepoints that are rolled back Save
points info - this savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back savepoint
 name = SP_23601. Given savepoint: savepoint id = , savepoint name = . Rolled-back savepoint id = , rolled-back save
point name = . Field info: entity name = PathAssistantStepInfo, field name = DeveloperName.",
        "problemType": "Error",
        "fullName": "xxxxxxxxxxxx",
        "type": "PathAssistant",
        "state": "Failed",
        "filePath": "xxxxxxxxxxxx"
      },
      {
        "error": "An unknown exception has occurred.",
        "problemType": "Error",
        "fullName": "xxxxxxxxxxxx",
        "type": "PathAssistant",
        "state": "Failed",
        "filePath": "xxxxxxxxxxxx"
      }
    ]
  },
  "warnings": []
}

**Comment by shetzel** [comment]
Sorry you are experiencing issues during deployment, but this is not a CLI issue.  It's a problem reported by the specific metadata type during validation (as part of the metadata deploy).  You'll have to search around for how to solve that problem or create a support case.
