### ISSUE TITLE
Invalid JSON output of salesforcecli/cli test report

### ISSUE THREAD

**Issue by webmatrixxxl** [forcedotcom/cli#2929]
### Summary
Invalid JSON output of salesforcecli/cli test report.

`sf apex run test --class-names SomeClassTest --target-org myOrg  --code-coverage --result-format human --synchronous --detailed-coverage --output-dir ./.tests/apex`

<img width="698" alt="image" src="https://github.com/forcedotcom/cli/assets/3726238/a3f78178-bfd5-494b-9487-9b4ba0d05bb7">

### Steps To Reproduce

I just run the command.

### Expected result
JSON should be valid

### Actual result
JSON is NOT valid

### System Information

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.45.6",
  "nodeVersion": "node-v18.20.2",
  "osVersion": "Darwin 23.5.0",
  "rootPath": "/Users/user/.nvm/versions/node/v18.20.2/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.1.2 (core)",
    "@oclif/plugin-commands 4.0.2 (core)",
    "@oclif/plugin-help 6.1.0 (core)",
    "@oclif/plugin-not-found 3.2.2 (core)",
    "@oclif/plugin-plugins 5.2.2 (core)",
    "@oclif/plugin-search 1.1.1 (core)",
    "@oclif/plugin-update 4.3.3 (core)",
    "@oclif/plugin-version 2.2.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.4 (core)",
    "@oclif/plugin-which 3.2.1 (core)",
    "@salesforce/cli 2.45.6 (core)",
    "apex 3.1.14 (core)",
    "auth 3.6.17 (core)",
    "data 3.4.3 (core)",
    "deploy-retrieve 3.8.4 (core)",
    "info 3.3.4 (core)",
    "limits 3.3.10 (core)",
    "marketplace 1.2.10 (core)",
    "org 4.1.19 (core)",
    "packaging 2.4.5 (core)",
    "schema 3.3.10 (core)",
    "settings 2.3.0 (core)",
    "sobject 1.4.8 (core)",
    "source 3.3.21 (core)",
    "telemetry 3.3.12 (core)",
    "templates 56.2.9 (core)",
    "trust 3.7.4 (core)",
    "user 3.5.11 (core)",
    "@salesforce/sfdx-scanner 3.25.0 (user) published 21 days ago (Tue May 28 2024)"
  ]
}
```

**Comment by WillieRuemmele** [comment]
Hi @webmatrixxxl - are you still experiencing this issue? I was unable to reproduce it using the latest version of the CLI, and with your version specified, and using node 18.20.2 and 20.12.2... even more, that key isn't in any of my results...

**Comment by webmatrixxxl** [comment]
@WillieRuemmele the issue is not present in `@salesforce/cli/2.46.6`.

The field `userId` is no longer in the `test-result.json` file. Not sure if this is expected but the JSON is now valid.
