### ISSUE TITLE
Cannot create property 'caller' on string 'incorrect header check'

### ISSUE THREAD

**Issue by sfs-nathan** [forcedotcom/cli#2938]
### Summary
I recently started with a clean Mac Studio and was installing the latest of everything. I don't remember the exact order of operations, but I believe that upon installing Node (via brew install node) that two errors started occurring. What I do know is that at one point during my install, I was able to properly save/deploy a class to my sandbox using VSCode and then upon installing Node, I started to receive two errors:

>(node:30077) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

This^ one was *resolved* by moving down to node@20

> Error (10): Cannot create property 'caller' on string 'incorrect header check'

I cannot move past this^ error, at the moment.

Both seem to have appeared roughly around the time I installed NodeJS via the installer here: https://nodejs.org/en/download/prebuilt-installer

I also ran the doctor (below), which said something about auth being a fail.

### Steps To Reproduce

There is no direct repo for this issue, as I believe it has to do exclusively with software/plugin versions, given that I was able to deploy once mid-installation.

### System Information
Using ZSH:

❯ sf version --verbose --json
>{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.46.6",
  "nodeVersion": "node-v20.15.0",
  "osVersion": "Darwin 23.5.0",
  "rootPath": "/opt/homebrew/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.1.2 (core)",
    "@oclif/plugin-commands 4.0.2 (core)",
    "@oclif/plugin-help 6.2.1 (core)",
    "@oclif/plugin-not-found 3.2.3 (core)",
    "@oclif/plugin-plugins 5.2.4 (core)",
    "@oclif/plugin-search 1.1.2 (core)",
    "@oclif/plugin-update 4.3.5 (core)",
    "@oclif/plugin-version 2.2.3 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.5 (core)",
    "@oclif/plugin-which 3.2.2 (core)",
    "@salesforce/cli 2.46.6 (core)",
    "apex 3.1.18 (core)",
    "auth 3.6.21 (core)",
    "data 3.4.6 (core)",
    "deploy-retrieve 3.9.4 (core)",
    "info 3.3.6 (core)",
    "limits 3.3.12 (core)",
    "marketplace 1.2.12 (core)",
    "org 4.2.1 (core)",
    "packaging 2.4.6 (core)",
    "schema 3.3.11 (core)",
    "settings 2.3.1 (core)",
    "sobject 1.4.11 (core)",
    "source 3.4.2 (core)",
    "telemetry 3.4.0 (core)",
    "templates 56.2.11 (core)",
    "trust 3.7.5 (core)",
    "user 3.5.13 (core)"
  ]
}

❯ sf plugins inspect @salesforce/cli
>└─ @salesforce/cli
   ├─ version 2.46.6
   ├─ homepage https://github.com/salesforcecli/cli
   ├─ location /opt/homebrew/lib/node_modules/@salesforce/cli
   ├─ commands
   │  ├─ [removed... not necessary...]
   └─ dependencies
      ├─ @inquirer/select ^2.3.5 => 2.3.5
      ├─ @oclif/core 4.0.4 => 4.0.4
      ├─ @oclif/plugin-autocomplete 3.1.2 => 3.1.2
      ├─ @oclif/plugin-commands 4.0.2 => 4.0.2
      ├─ @oclif/plugin-help 6.2.1 => 6.2.1
      ├─ @oclif/plugin-not-found 3.2.3 => 3.2.3
      ├─ @oclif/plugin-plugins 5.2.4 => 5.2.4
      ├─ @oclif/plugin-search 1.1.2 => 1.1.2
      ├─ @oclif/plugin-update 4.3.5 => 4.3.5
      ├─ @oclif/plugin-version 2.2.3 => 2.2.3
      ├─ @oclif/plugin-warn-if-update-available 3.1.5 => 3.1.5
      ├─ @oclif/plugin-which 3.2.2 => 3.2.2
      ├─ @salesforce/core ^7.2.0 => 7.3.12
      ├─ @salesforce/kit ^3.1.0 => 3.1.3
      ├─ @salesforce/plugin-apex 3.1.18 => 3.1.18
      ├─ @salesforce/plugin-auth 3.6.21 => 3.6.21
      ├─ @salesforce/plugin-data 3.4.6 => 3.4.6
      ├─ @salesforce/plugin-deploy-retrieve 3.9.4 => 3.9.4
      ├─ @salesforce/plugin-info 3.3.6 => 3.3.6
      ├─ @salesforce/plugin-limits 3.3.12 => 3.3.12
      ├─ @salesforce/plugin-marketplace 1.2.12 => 1.2.12
      ├─ @salesforce/plugin-org 4.2.1 => 4.2.1
      ├─ @salesforce/plugin-packaging 2.4.6 => 2.4.6
      ├─ @salesforce/plugin-schema 3.3.11 => 3.3.11
      ├─ @salesforce/plugin-settings 2.3.1 => 2.3.1
      ├─ @salesforce/plugin-sobject 1.4.11 => 1.4.11
      ├─ @salesforce/plugin-source 3.4.2 => 3.4.2
      ├─ @salesforce/plugin-telemetry 3.4.0 => 3.4.0
      ├─ @salesforce/plugin-templates 56.2.11 => 56.2.11
      ├─ @salesforce/plugin-trust 3.7.5 => 3.7.5
      ├─ @salesforce/plugin-user 3.5.13 => 3.5.13
      ├─ @salesforce/sf-plugins-core 10.0.1 => 10.0.1
      └─ ansis ^3.2.0 => 3.2.0

❯ sf doctor --command "project retrieve preview"
>=== Running command with debugging
>
>sf project retrieve preview --dev-debug
>
>=== Running all diagnostics
>
>pass - salesforcedx plugin isn’t installed
pass - you don't have any linked plugins
pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org
pass - [@salesforce/plugin-trust] can ping: https://registry.yarnpkg.com
pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org/
pass - using latest or latest-rc CLI version
pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
warn - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches default target org max apiVersion
pass - can access: https://test.salesforce.com
pass - can access: https://appexchange.salesforce.com/services/data
pass - can access: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64-buildmanifest
fail - [@salesforce/plugin-auth] CLI supports v2 crypto
>
>Wrote command stdout log to: /Users/nathan/Development/sf/innerFrame--dev/1719234717698-command-stdout.log
Wrote command debug log to: /Users/nathan/Development/sf/innerFrame--dev/1719234717698-command-debug.log
Wrote doctor diagnosis to: /Users/nathan/Development/sf/innerFrame--dev/1719234717698-diagnosis.json
>
>=== Suggestions
>
>  * Check https://github.com/forcedotcom/cli/issues for CLI issues posted by the community.
>  * Check http://status.salesforce.com for general Salesforce availability and performance.
>  * using npm registry https://registry.npmjs.org/ from npm config
>  * The sourceApiVersion in sfdx-project.json doesn't match the max apiVersion of the default target org. As a result, you're not using the latest features available in API version 61.0. The version mismatch isn't a problem, as long as it's the behavior you actually want.
>  * Your current installation of Salesforce CLI, including all the plugins you've linked and installed, doesn't yet support v2 crypto. All plugins and libraries must use at least version 6.7.0 of `@salesforce/core` to support v2 crypto. You're generally still able to successfully authenticate with your current CLI installation, but not if you generate a v2 crypto key.

Here is the /*-command-debug.log:
>2024-06-24T13:11:58.084Z sf:telemetry Usage acknowledgement file already exists
2024-06-24T13:11:58.085Z sf:telemetry Using telemetry logging file /var/folders/nz/pzbqqdbj6wvg7j98t90np42r0000gn/T/sf-telemetry/telemetry-84b6fb9a028bb4bdc6e1531e08da67c0a568d066.log
2024-06-24T13:11:58.119Z sf:telemetry Setting up process exit handler
Error (10): Cannot create property 'caller' on string 'incorrect header check'
>
>*** Internal Diagnostic ***
>
>TypeError: Cannot create property 'caller' on string 'incorrect header check'
    at Object.statusMatrix (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/isomorphic-git/index.cjs:14122:16)
    at async ShadowRepo.getStatus (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@salesforce/source-tracking/lib/shared/local/localShadowRepo.js:131:31)
    at async SourceTracking.ensureLocalTracking (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@salesforce/source-tracking/lib/sourceTracking.js:332:9)
    at async Promise.all (index 1)
    at async SourceTracking.getConflicts (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@salesforce/source-tracking/lib/sourceTracking.js:397:9)
    at async getConflictFiles (file:///opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-deploy-retrieve/lib/utils/previewOutput.js:195:16)
    at async Promise.all (index 1)
    at async RetrieveMetadataPreview.run (file:///opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-deploy-retrieve/lib/commands/project/retrieve/preview.js:42:67)
    at async RetrieveMetadataPreview._run (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:302:22)
    at async Config.runCommand (/opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:424:25)
******
>
>2024-06-24T13:11:59.089Z sf:telemetry Spawning "/opt/homebrew/Cellar/node@20/20.15.0/bin/node /opt/homebrew/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-telemetry/processes/upload.js /Users/nathan/Library/Caches/sf /var/folders/nz/pzbqqdbj6wvg7j98t90np42r0000gn/T/sf-telemetry/telemetry-84b6fb9a028bb4bdc6e1531e08da67c0a568d066.log"

**Comment by shetzel** [comment]
This is essentially a duplicate of [Issue with project deploy start in CI pipeline](https://github.com/forcedotcom/cli/issues/2926)

Until isomorphic-git fixes the issue in their code you cannot use NodeJS equal to or greater than v22.3.0.  Please see the comments in that issue report.

The deprecation warning you're seeing is not an error causing problems.

**Comment by sfs-nathan** [comment]
Yes! You are 100% right, I had tried searching and hadn't found that one. Thank you!

**Comment by sfs-nathan** [comment]
(you'll notice I'd already downgraded: ```node-v20.15.0```)

**Comment by AlejandroSanchezTKSG** [comment]
I'm having the same issue
