### ISSUE TITLE
Non-printable characters observed when CLI command output is redirected to text file

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#2951]
### Expected result
No extra, non-printable characters should be included in a text file if I redirect the command output to a file

### Actual result
Various non-printable characters are seen in the document.  These include:
* `esc[1m`
* `esc[2m`
* `esc[22m`
* `esc[4m`
* `esc[24m`

These characters are not observed in the console itself if the command output is not redirected.

### Steps to reproduce
* Execute the following command: `sf package create -h > package-create-info.txt`
* Open the text file in VSCode
* Observe the non-printable characters

This issue has been seen on several of the commands when redirecting output to a text file.

### System Information

```
CLI:
@salesforce/cli/2.50.5 win32-x64 node-v21.1.0

Plugin Version:
@dx-cli-toolbox/sf-toolbox-aep-utils 0.7.5 (user)
@dx-cli-toolbox/sfdx-toolbox-package-utils 0.8.4 (user)
@dx-cli-toolbox/sfdx-toolbox-utils 0.1.2 (user)
@oclif/plugin-autocomplete 3.1.6 (core)
@oclif/plugin-commands 4.0.6 (core)
@oclif/plugin-help 6.2.5 (core)
@oclif/plugin-not-found 3.2.10 (core)
@oclif/plugin-plugins 5.3.4 (core)
@oclif/plugin-search 1.2.2 (core)
@oclif/plugin-update 4.4.7 (core)
@oclif/plugin-version 2.2.6 (core)
@oclif/plugin-warn-if-update-available 3.1.8 (core)
@oclif/plugin-which 3.2.6 (core)
@salesforce/cli 2.50.5 (core)
apex 3.2.4 (core)
auth 3.6.33 (core)
community 3.2.11 (user)
data 3.5.5 (core)
deploy-retrieve 3.9.13 (core)
info 3.3.17 (core)
limits 3.3.17 (core)
marketplace 1.2.17 (core)
org 4.3.4 (core)
packaging 2.7.0 (core)
schema 3.3.19 (core)
settings 2.3.8 (core)
signups 2.3.3 (user)
sobject 1.4.19 (core)
source 3.5.3 (core)
telemetry 3.6.1 (core)
templates 56.3.2 (core)
trust 3.7.13 (core)
user 3.5.17 (core)
sfdmu 4.33.17 (user)
```

```
SF ENV. VARS.
SF_AUTOUPDATE_DISABLE,true
SF_DISABLE_AUTOUPDATE,true
SF_UPDATE_INSTRUCTIONS,Use "npm update --global @salesforce/cli" to update npm-based installations.
```

```
Windows: true
Shell: C:\Users\MyHomeDir\AppData\Local\Programs\Git\usr\bin\bash.exe
Channel: stable
```
---
### Diagnostics
:white_check_mark: pass - salesforcedx plugin isn’t installed
:white_check_mark: pass - you don't have any linked plugins
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.yarnpkg.com
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org/
:white_check_mark: pass - using latest or latest-rc CLI version
:white_check_mark: pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
:white_check_mark: pass - can access: https://appexchange.salesforce.com/services/data
:white_check_mark: pass - can access: https://test.salesforce.com
:white_check_mark: pass - can access: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64-buildmanifest
:x: fail - [@salesforce/plugin-auth] CLI supports v2 crypto
:white_check_mark: pass - [@salesforce/plugin-auth] CLI using stable v1 crypto

**Comment by ImJohnMDaniel** [comment]
Here is an example of what I am seeing
[package-create.txt](https://github.com/user-attachments/files/16145205/package-create.txt)

**Comment by cristiand391** [comment]
this should be fixed on latest.
