### ISSUE TITLE
The action target HealthCloudGA_HealthCloudPsl of type PermissionSetLicense does not exist.

### ISSUE THREAD

**Issue by pavanisista** [forcedotcom/cli#2955]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary

Trying to assign the [HealthCloudPSL] to all the active users with standard user profile but the deployment is failing with the error "The action target HealthCloudGA_HealthCloudPsl of type PermissionSetLicense does not exist."
Other [PSL] from the Core are working fine, this issue is with the package one.

We created new org, and able to replicate the [same error](https://asinfal-guscaseinv.lightning.force.com/lightning/setup/InboundChangeSet/page?address=%2Fchangemgmt%2FmonitorDeploymentsDetails.apexp%3FasyncId%3D0AfWs00000HuFVd%26retURL%3D%252Fchangemgmt%252FinboundChangeSetDetailPage.apexp%253Fcid%253D0EPWs00000001ov)

### Steps To Reproduce
1. Create User Policy with HealthCloudPSL
2. Upload to production
3. Deploy the Change list

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

### System Information

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by pavanisista** [comment]
Trying from Sandbox/Prod, release version - 250

**Comment by pavanisista** [comment]
One observation: If Permission set license is the standard one, it is working fine but if the PSL have the custom permissions it is failing
<img width="1614" alt="Screenshot 2024-07-16 at 9 10 28 AM" src="https://github.com/user-attachments/assets/760f4969-f899-4b15-957b-e9a1fdbc0646">

**Comment by mshanemc** [comment]
This is not CLI related (evidence: it fails with change sets, too).

**Comment by danielsousa98** [comment]
Hi, have you been able to solve the issue? I am also in trouble with this but regarding a Permission from Salesforce Maps
