### ISSUE TITLE
"force:mdapi:deploy -d src" does not respect .dot folders or .forceignore and packs .git into zip

### ISSUE THREAD

**Issue by pkozuchowski** [forcedotcom/cli#296]
### Summary
sfdx force:mdapi:deploy does not respect .forceignore and packs .git subfolders into release package.

I have a project where git repository was created inside src folder (using old metadata format).
Issuing "sfdx force:mdapi:deploy -d src" will pack the .git subfolder into release zip package.
Then deployment fails because package is too big.

$ sfdx force:mdapi:deploy -c -u dev-d src -w -1
ERROR running force:mdapi:deploy:  Maximum size of request reached. Maximum size of request is 52428800 bytes.

### Steps To Reproduce:

1.  Have sources in old metadata format
1.  Create repository in the src folder
1.  Create lots of commits, to make repository size big enough to trigger the issue
1. Try to deploy or validate sources using sfdx force:mdapi:deploy

### Expected result
Commands ignore all folders starting with .dot or respects .forceignore

### Actual result
Command zips .git repository into release zip package and fails

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.45.1-bc18d49798 win32-x64 node-v10.15.3

**OS and version**:
Windows	10.0.18362

**Comment by clairebianchi** [comment]
@amorek I have sent this to the mdapi team to take a look

**Comment by mshanemc** [comment]
CLI teams owns the mdapi commands now, and we don't plan to change this.  It wouldn't make sense for the zip option (we won't unzip the files).

It could be done for a -d like your example, but we're not going to.  I'd recommend scripting around the git subfolder issue (either copy only what you want to a new folder for -d OR stash and restore your git folder) OR use the source commands and source format
