### ISSUE TITLE
force:org:create

### ISSUE THREAD

**Issue by pedroguntin** [forcedotcom/cli#298]
When I execute the command
sfdx force:org:create -f earlyon.json -u caswota@greenxolutions.com -v CASW -a test
I got:
ERROR running force:org:create:  location is not defined

I'm connected properly to my org CASW, the config is good: defaultusername  CASW   Global

My colleague doesn't have this issue... I've tried on another computer and another org and it's the same problem.

I appreciate your help.

Thanks,

### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:
1. connect to my org: sfdx force:auth:web:login -s -r https://login.salesforce.com -a CASW
2. create the scratch org: sfdx force:org:create -f earlyon.json -u caswota@greenxolutions.com -v CASW -a test

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.45.1-bc18d49798 win32-x64 node-v10.15.3
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
sfdx-cli/7.45.1-bc18d49798 win32-x64 node-v10.15.3
**OS and version**:
Windows 10

**Comment by clairebianchi** [comment]
@pedroguntin I have passed this on to the team that owns scratch orgs

**Comment by mshanemc** [comment]
this is an old issue, and nearly all the code for org creation has been replaced, including the source of that "location not defined" error.  If you're still able to reproduce this, please open another issue.
