### ISSUE TITLE
manifest generated by sf project generate manifest --from-org retrieves unavailable metadata records

### ISSUE THREAD

**Issue by GuntherRoskams** [forcedotcom/cli#2989]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI =>  I use the docker image (salesforce/cli:latest-slim, so I assume it is the lastest version :))
> - You've searched both open and closed issues for related posts => nothing relevant found
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
Use case:
I'm creating a script to pull the complete metadata content from an org. During the tests, we are facing an error during the retrieve of the ContentAsset component. All other components went fine, except the ContentAsset.

While I generate a manifest file from a Salesforce Org (production or sandboxes), the command generates "unavailable components" . I receive a list of ContentAsset members, which are not reachable for the user.

Below the part with the members for the metadata component ContentAsset. 

<types>
        <members>Afbeelding_20221025_123738</members>
        <members>Afbeelding_20221028_081802</members>
        <members>Afbeelding_20221103_073159</members>
        <members>Afbeelding_20221103_073159_1</members>
        <members>Afbeelding_20221103_073159_2</members>
        <members>Afbeelding_20221103_073159_3</members>
        <members>Afbeelding_20221108_130018</members>
        <members>Afbeelding_20221108_132411</members>
        <members>Afbeelding_20221108_135407</members>
        <members>Afbeelding_20221118_102445</members>
        <members>Afbeelding_20221129_121326</members>
        <members>Afbeelding_20221130_095904</members>
        <members>Afbeelding_20221212_081539</members>
        <members>Afbeelding_20230104_084841</members>
        <members>Afbeelding_20230104_132715</members>
        <members>Afbeelding_20230104_134746</members>
        <members>Afbeelding_20230105_090402</members>
        <members>Afbeelding_20230105_092527</members>
        <members>Afbeelding_20230105_093158</members>
        <members>Afbeelding_20230105_094739</members>
        <members>Afbeelding_20230105_122218</members>
        <members>Afbeelding_20230105_124754</members>
        <members>Afbeelding_20230105_135616</members>
        <members>Afbeelding_20230106_091344</members>
        <members>Afbeelding_20230110_080449</members>
        <members>Afbeelding_20230110_082350</members>
        <members>Afbeelding_20230110_094625</members>
        <members>Afbeelding_20230112_125320</members>
        <members>Afbeelding_20230112_131611</members>
        <members>Afbeelding_20230124_093215</members>
        <members>Afbeelding_20230124_123959</members>
        <members>Afbeelding_20230124_132247</members>
        <name>ContentAsset</name>
    </types>

If I try to retrieve the content of one of these files, I receive the error unpackaged\contentassets\Afbeelding_20230124_132247.asset-meta.xml: Expected source files for type 'ContentAsset'

Or the issue is the creation of the package.xml manifest (which don't create the files), or the problem is the gathering of the content of the ContentAsset file.

If I remove the ContentAsset part in the XML and runs the command to retrieve the source code for the manifest, the script runs without any error. 

### Steps To Reproduce

I cannot provide you a repo, due to the fact these are customer orgs, and I'm facing the issue on several orgs (especially orgs with ContentAsset records)

After the generation of the manifest file, I want to retrieve the content of each member, with the command 
```powershell
sf project retrieve start -m ContentAsset:Afbeelding_20230124_132247 -o myCustomerOrg -c
``` 
which should result in a file in the sf folder structure. Unfortunately, the command returns an error and the request failed
**unpackaged\contentassets\Afbeelding_20230124_132247.asset-meta.xml: Expected source files for type 'ContentAsset'**

Further analys gives me that some of the ContentAsset files are Private, but also content assests, created in a public library returns the same error. And I'm logging in with a System Admin user, without restrictions (I can see the file in the Salesforce screens)
Some of the ContentAsset can be loaded. Most of the time these files are created and used in Lighting Applications. For some reason, older files are not supported as a ContentAsset file, or could not loaded as an asset file (it looks like the file is missing somewhere, or not linked)

Steps to reproduce:
- have an org with old files, which are available via a SOQL query (I queried the records and received the results, so I do have read access on these files with the user)
- Create a manifest file with the command 

```powershell
sf project generate manifest --from-org your-org-alias -d manifest
``` 
- Open the manifest file and check if you 'll find some ContentAsset files
- Try to retrieve one of the ContentAsset files with the command 

```powershell
sf project retrieve start -m ContentAsset:Afbeelding_20230124_132247 -o your-org-alias
``` 
- Retrieve the Error (MetadataTransferError): Metadata API request failed: unpackaged\contentassets\Afbeelding_20230124_132247.asset-meta.xml: Expected source files for type 'ContentAsset'

### Expected result
I should receive the asset file in the Salesforce SF structure, or the file could not be found. no exception at all

### Actual result
an error, which blocks my whole script to download the metadata from an org

### System Information

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.55.6",
  "nodeVersion": "node-v20.16.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\roskagu\\AppData\\Local\\sf\\client\\2.55.6-648ad30",
  "shell": "powershell",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.0 (core)",
    "@oclif/plugin-commands 4.0.11 (core)",
    "@oclif/plugin-help 6.2.8 (core)",
    "@oclif/plugin-not-found 3.2.16 (core)",
    "@oclif/plugin-plugins 5.4.4 (core)",
    "@oclif/plugin-search 1.2.5 (core)",
    "@oclif/plugin-update 4.5.3 (core)",
    "@oclif/plugin-version 2.2.10 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.11 (core)",
    "@oclif/plugin-which 3.2.10 (core)",
    "@salesforce/cli 2.55.6 (core)",
    "apex 3.3.4 (core)",
    "auth 3.6.47 (core)",
    "data 3.6.0 (core)",
    "deploy-retrieve 3.9.27 (core)",
    "info 3.3.28 (core)",
    "limits 3.3.24 (core)",
    "marketplace 1.2.22 (core)",
    "org 4.4.6 (core)",
    "packaging 2.7.4 (user) published 30 days ago (Tue Jul 23 2024) (latest is 2.8.0)",
    "schema 3.3.22 (core)",
    "settings 2.3.11 (core)",
    "sobject 1.4.28 (core)",
    "source 3.5.12 (core)",
    "telemetry 3.6.6 (core)",
    "templates 56.3.11 (core)",
    "trust 3.7.22 (core)",
    "user 3.5.23 (core)"
  ]
}
```

**Comment by GuntherRoskams** [comment]
I just see that the metadata part was messed up.

```
<types>
        <members>Afbeelding_20221025_123738</members>
        <members>Afbeelding_20221028_081802</members>
        <members>Afbeelding_20221103_073159</members>
        <members>Afbeelding_20221103_073159_1</members>
        <members>Afbeelding_20221103_073159_2</members>
        <members>Afbeelding_20221103_073159_3</members>
        <members>Afbeelding_20221108_130018</members>
        <members>Afbeelding_20221108_132411</members>
        <members>Afbeelding_20221108_135407</members>
        <members>Afbeelding_20221118_102445</members>
        <members>Afbeelding_20221129_121326</members>
        <members>Afbeelding_20221130_095904</members>
        <members>Afbeelding_20221212_081539</members>
        <members>Afbeelding_20230104_084841</members>
        <members>Afbeelding_20230104_132715</members>
        <members>Afbeelding_20230104_134746</members>
        <members>Afbeelding_20230105_090402</members>
        <members>Afbeelding_20230105_092527</members>
        <members>Afbeelding_20230105_093158</members>
        <members>Afbeelding_20230105_094739</members>
        <members>Afbeelding_20230105_122218</members>
        <members>Afbeelding_20230105_124754</members>
        <members>Afbeelding_20230105_135616</members>
        <members>Afbeelding_20230106_091344</members>
        <members>Afbeelding_20230110_080449</members>
        <members>Afbeelding_20230110_082350</members>
        <members>Afbeelding_20230110_094625</members>
        <members>Afbeelding_20230112_125320</members>
        <members>Afbeelding_20230112_131611</members>
        <members>Afbeelding_20230124_093215</members>
        <members>Afbeelding_20230124_123959</members>
        <members>Afbeelding_20230124_132247</members>
        <members>Afbeelding_20231122_102359</members>
        <members>Afbeelding_20231122_103729</members>
        <members>Afbeelding_20240313_100302</members>
        <members>Afbeelding_20240621_102920</members>
        <members>Afbeelding_20240704_102240</members>
        <members>Afbeelding_20240704_102501</members>
        <members>Afbeelding_20240704_102653</members>
</types>
``` 

But,... I found the issue...
I created the package.xml file from the production environment of the same customer, we don't have the issue there.
With deeper analysis, if the ContentAsset doesn't have a file, the display went in an error (or it should be something like that :))
![Crazy Salesforce Error](https://github.com/user-attachments/assets/6c011ff3-35bb-444f-bf25-76ee2f433774)

And we can't get the content of the ContentAsset (and goes in error)

So, shouldn't be reasonable to remove the exception when the file from the ContentAsset couldn't be found (And add it into the part with the warnings) ?

**Comment by cristiand391** [comment]
> So, shouldn't be reasonable to remove the exception when the file from the ContentAsset couldn't be found (And add it into the part with the warnings) ?

@GuntherRoskams that's already the case when the record isn't associated to a file (see screenshot below), sf will warn but not retrieve it. I think in your case those records have an associated file that can't be accessed.

![Screenshot 2024-08-26 at 12 07 43 PM](https://github.com/user-attachments/assets/7fd7d854-25c4-420e-a6f4-fbb0153fa16a)

you can check the ID of the associated document with this query:
```
sf data query -q 'select developername,masterlabel,ContentDocumentId from contentasset'
```

**Comment by GuntherRoskams** [comment]
Hi @cristiand391, 

In that case, can you explain me why the script has been interrupted ?

sf project retrieve start -x manifest/package.xml -o connected-org -c
Retrieving v61.0 metadata from ***  using the v61.0 SOAP API
Error (MetadataTransferError): Metadata API request failed: unpackaged/contentassets/Hasselt_heeft_het_logo_zwart_lores.asset-meta.xml: Expected source files for type 'ContentAsset' 

If I remove the ContentAsset part in my package.xml file, the script runs like a charm...

**Comment by cristiand391** [comment]
> In that case, can you explain me why the script has been interrupted ?
sf project retrieve start -x manifest/package.xml -o connected-org -c
Retrieving v61.0 metadata from *** using the v61.0 SOAP API
Error (MetadataTransferError): Metadata API request failed: unpackaged/contentassets/Hasselt_heeft_het_logo_zwart_lores.asset-meta.xml: Expected source files for type 'ContentAsset'

because that ContentAsset record has an associated file that can't be accessed (the CLI expects a matching file or if it doesn't then it will not be retrieved (see my screenshot above).

if you run the following query:
```
sf data query -q 'select developername,masterlabel,ContentDocumentId from contentasset'
```

do you see the document ID of the ContentAsset that can't be retrieved?

**Comment by RupertBarrow** [comment]
Is this a duplicate of #2745 ?

**Comment by GuntherRoskams** [comment]
@cristiand391 I see the ContentDocumentIds. Now, I see the issue. The linked Content document Ids are from the Production environment, and not the Id's from the test environment. But my question is still: Is it possible to mention this use case as a warning and not as an error like Error (MetadataTransferError): Metadata API request failed: unpackaged\contentassets\Hasselt_heeft_het_logo_zwart_lores.asset-meta.xml: Expected source files for type 'ContentAsset'. The script is interrupted and the transaction isn't executed.

@RupertBarrow I saw this issue as well, but it wasn't solved, but closed. So, I opened a new issue

**Comment by cristiand391** [comment]
> But my question is still: Is it possible to mention this use case as a warning and not as an error like Error (MetadataTransferError): Metadata API request failed: unpackaged\contentassets\Hasselt_heeft_het_logo_zwart_lores.asset-meta.xml: Expected source files for type 'ContentAsset'. The script is interrupted and the transaction isn't executed.

No, the error is thrown by the Metadata API and the library expects `ContentAsset` to always have a content file and an xml. 
Even adding some workaround to allow you to retrieve it, it would likely fail on deploy (unless we build a fake content just for this, which could open people to other unexpected scenarios).

**Comment by iowillhoit** [comment]
Closing as stale
