### ISSUE TITLE
sf login issue

### ISSUE THREAD

**Issue by GlowikM** [forcedotcom/cli#2992]
I tried connect to sandbox environment using cli

I'm up to date:
@salesforce/cli/2.55.6 win32-x64 node-v20.16.0

Using below command 
sf org login web --instanceurl https://test.salesforce.com

![2024-08-22_10-33-39](https://github.com/user-attachments/assets/9831ae57-463c-40b1-9492-c948037b11e2)

Error from sf log:
{"level":50,"time":1724397948280,"name":"sf:oclif","msg":"AuthCodeUsernameRetrievalError: Could not retrieve the username after successful auth code exchange.\nDue to: request to https://abb-ability--dev.sandbox.my.salesforce.com/services/oauth2/userinfo failed, reason: unable to get local issuer certificate\n    at SfCommandError.from (file:///C:/Users/PLMIGLO1/AppData/Local/sf/client/2.55.6-648ad30/node_modules/@salesforce/sf-plugins-core/lib/SfCommandError.js:39:16)\n    at LoginWeb.catch (file:///C:/Users/PLMIGLO1/AppData/Local/sf/client/2.55.6-648ad30/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:316:47)\n    at LoginWeb._run (C:/Users/PLMIGLO1/AppData/Local/sf/client/2.55.6-648ad30/node_modules/@oclif/core/lib/command.js:305:29)\n    at async Config.runCommand (C:/Users/PLMIGLO1/AppData/Local/sf/client/2.55.6-648ad30/node_modules/@oclif/core/lib/config/config.js:424:25)\n    at async run (C:/Users/PLMIGLO1/AppData/Local/sf/client/2.55.6-648ad30/node_modules/@oclif/core/lib/main.js:95:16)\n    at async file:///C:/Users/PLMIGLO1/AppData/Local/sf/client/2.55.6-648ad30/bin/run.js:15:1"}

**Comment by GlowikM** [comment]
Hi bellow all information after using command version --verbose --json after using update nightly and problem still occurring

{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.57.1",
  "nodeVersion": "node-v20.16.0",
  "osVersion": "Windows_NT 10.0.22631",
  "rootPath": "C:\\Users\\PLMIGLO1\\AppData\\Local\\sf\\client\\2.57.1-8af5fb6",
  "shell": "powershell",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.0 (core)",
    "@oclif/plugin-commands 4.0.11 (core)",
    "@oclif/plugin-help 6.2.8 (core)",
    "@oclif/plugin-not-found 3.2.16 (core)",
    "@oclif/plugin-plugins 5.4.4 (core)",
    "@oclif/plugin-search 1.2.5 (core)",
    "@oclif/plugin-update 4.5.3 (core)",
    "@oclif/plugin-version 2.2.10 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.11 (core)",
    "@oclif/plugin-which 3.2.10 (core)",
    "@salesforce/cli 2.57.1 (core)",
    "apex 3.4.2 (core)",
    "api 1.2.0 (core)",
    "auth 3.6.48 (core)",
    "data 3.6.1 (core)",
    "deploy-retrieve 3.11.1 (core)",
    "info 3.3.29 (core)",
    "limits 3.3.25 (core)",
    "marketplace 1.2.22 (core)",
    "org 4.5.1 (core)",
    "packaging 2.8.0 (core)",
    "schema 3.3.24 (core)",
    "settings 2.3.13 (core)",
    "sobject 1.4.29 (core)",
    "source 3.5.14 (core)",
    "telemetry 3.6.7 (core)",
    "templates 56.3.12 (core)",
    "trust 3.7.23 (core)",
    "user 3.5.25 (core)"
  ]
}

**Comment by cristiand391** [comment]
that's a network error (CLI is failing after trying to do request.

Are you behind a proxy/firewall? See:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_firewall.htm?q=network
