### ISSUE TITLE
when I try sfdx force:org:list, got an MaxListenersExceededWarning error

### ISSUE THREAD

**Issue by daniel3Github** [forcedotcom/cli#30]
### Summary

When I use the sfdx force:org:list command, I always get an error: 
-- (node:51109) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 value listeners added. Use emitter.setMaxListeners() to increase limit

### Steps To Reproduce:

1.  sfdx force:org:list
### Expected result

List all the org infos.

### Actual result
got an error.
Error information: (node:51109) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 value listeners added. Use emitter.setMaxListeners() to increase limit

### Additional information
sfdx force:alias:list command works correctly.

**SFDX CLI Version**: sfdx-cli/6.52.2-c6cdc99881 (darwin-x64) node-v8.9.4

**OS and version**: masOS Mojave 10.14.2

**Comment by clairebianchi** [comment]
@daniel3Github can you run sfdx plugins --core to get the version salesforcedx that you are on?  I am filing a bug, but I am unable to reproduce the error so any other information would be helpful.

How many orgs are you currently authenticated into?
Does the CLI perform as expected when you run other org commands, such as org:open?
When did this issue start happening?

**Comment by daniel3Github** [comment]
@clairebianchi  the version info: 
@salesforce/plugin-generator 1.0.1 (core)
@salesforce/sfdx-trust 2.0.1 (core)
builtins 1.0.0 (core)
salesforcedx 45.2.0 (core)

I run the sfdx force:alias:list and get 7 orgs.
yes, the sfdx force:org:open works as expected.
I ran into this issue several days ago.

**Comment by daniel3Github** [comment]
Update: it works as expected after I marked a scratch org for deletion with  force:org:delete  command.

**Comment by ChuckJonas** [comment]
I'm still seeing this issue (running 7.42.1-e41dbeb8d9)

**Comment by kacrouse** [comment]
I see this issue only when the CLI has been installed [via the downloaded pkg](https://developer.salesforce.com/tools/sfdxcli) (or homebrew). It does not show up when it's been installed through npm.

It seems that the node versions might be different between the two? When running `sfdx -v` on the pkg version, it prints:
```
sfdx-cli/7.42.1-e41dbeb8d9 darwin-x64 node-v10.15.3
```
While running on the npm version, it appears that it's using the local version of node. Does the pkg version ship with it's own node binary?

**Comment by jayree** [comment]
@ChuckJonas try to install the latest version of the plugin salesforcedx:

`sfdx plugins:install salesforcedx@latest` 

Even if the latest version is the core version `47.15.0`, the error is gone for now on my side.

**Comment by MattB-R** [comment]
@jayree Thank you! Fixed my issue. Much appreciated.

**Comment by AndrewRayCode** [comment]
What's the difference between `sfdx update` and `sfdx plugins:install salesforcedx@latest` ? The first one doesn't seem to fix this issue

**Comment by AndrewRayCode** [comment]
I guess it doesn't matter, this error still occurs:

```
$ sfdx --version
sfdx-cli/7.42.1-e41dbeb8d9 darwin-x64 node-v10.15.3

$ sfdx force:source:deploy -l RunLocalTests -m 'ApexClass:SomeClass' -u MySalesforce --checkonly
(node:81553) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by ChuckJonas** [comment]
I still see the error after running both....

FYI looks like theres a more recent issue now #216
