### ISSUE TITLE
Single package -s / --singlepackage parameter is documented but not available

### ISSUE THREAD

**Issue by thegogz** [forcedotcom/cli#300]
### Summary

The [documentation]([https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_mdapi.htm]) for force:mdapi:deploy refers to the `-s` / `--singlepackage` parameter but when running the command it is unexpected see below

```
$ sfdx force:mdapi:deploy -f ./src/batch.zip -w 100 -s
ERROR running force:mdapi:deploy:  Unexpected argument: -s
See more help with --help
```

### Steps To Reproduce:

1.  Create a zip directory of a metadata project
1.  Run `sfdx force:mdapi:deploy -s -f <path-to-zip>`

### Expected result

Single package deployment is successful

### Actual result

- Errors with `Unexpected argument: -s`
- Without -s deploy fails as it expects multiple packages

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.45.1 win32-x64 node-v10.14.1`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
$ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.0 (core)
generator 1.1.2 (core)
mo-dx-plugin 0.2.4
salesforcedx 47.18.0 (core)
├─ salesforcedx-templates 47.19.0 (core)
└─ salesforce-alm 47.16.0 (core)
```

**OS and version**:
Windows 7 x64

**Comment by alan-morey** [comment]
@thegogz Where did you see this documented, when I run `sfdx force:mdapi:deploy -h` I don't see it documented:
```
$ sfdx force:mdapi:deploy -h
deploy metadata to an org using Metadata API

USAGE
  $ sfdx force:mdapi:deploy [-c] [-d <directory> | -f <filepath>] [-w <minutes>] [-l 
  NoTestRun|RunSpecifiedTests|RunLocalTests|RunAllTestsInOrg] [-r <array>] [-o] [-g] [-q <id>] 
  [-u <string>] [--apiversion <string>] [--verbose] [--json] [--loglevel 
  trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL]

OPTIONS
  -c, --checkonly
      validate deploy but don’t save to the org

  -d, --deploydir=deploydir
      root of directory tree of files to deploy

  -f, --zipfile=zipfile
      path to .zip file of metadata to deploy

  -g, --ignorewarnings
      whether a warning will allow a deployment to complete successfully

  -l, --testlevel=(NoTestRun|RunSpecifiedTests|RunLocalTests|RunAllTestsInOrg)
      deployment testing level

  -o, --ignoreerrors
      ignore any errors and do not roll back deployment

  -q, --validateddeployrequestid=validateddeployrequestid
      request ID of the validated deployment to run a Quick Deploy

  -r, --runtests=runtests
      tests to run if --testlevel RunSpecifiedTests

  -u, --targetusername=targetusername
      username or alias for the target org; overrides default target org

  -w, --wait=wait
      wait time for command to finish in minutes (default: 0)

  --apiversion=apiversion
      override the api version used for api requests made by this command

  --json
      format output as json

  --loglevel=(trace|debug|info|warn|error|fatal|TRACE|DEBUG|INFO|WARN|ERROR|FATAL)
      [default: warn] logging level for this command invocation

  --verbose
      verbose output of deploy results

DESCRIPTION
  Specify the location of the files to deploy as a .zip file or by the root of the directory 
  tree containing the files. To check the status of a deployment, specify its job ID. To run 
  quick deploy of a recently validated package, use --validateddeployrequestid with the 
  validated ID.

  To wait for the command to finish running no matter how long the deployment takes, set 
  --wait to -1: "sfdx force mdapi:deploy -w -1 ...".

COMMANDS
  force:mdapi:deploy:cancel  cancel a metadata deployment
  force:mdapi:deploy:report  check the status of a metadata deployment
```
**SFDX CLI Version:** sfdx-cli/7.45.1-bc18d49798 linux-x64 node-v10.15.3


I have been waiting for `-s --singlepackage` flag support, reported issue https://github.com/forcedotcom/cli/issues/4 over year ago for this :disappointed:

**Comment by thegogz** [comment]
@alan-morey in the docs on the website https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_mdapi.htm 

You're right when I run -h locally in the CLI I get the same output though...

**Comment by clairebianchi** [comment]
@thegogz @alan-morey, Would you two please update to the latest version of the CLI and let me know if you still don't see the -s flag? I see it in 48.2.0. This was released in version 48 of the CLI. The command reference guide is updated by API version, if you toggle back to V47 you will see that the parameter is not there, sorry for the confusion.

**Comment by alan-morey** [comment]
@clairebianchi I've upgraded to latest version, I see the `-s` flag is available for `force:mdapi:deploy` and it works as expected in my tests :+1: 

Maybe https://developer.salesforce.com/media/salesforce-cli/releasenotes.html should be updated to reflect when this flag was added?
