### ISSUE TITLE
CLI not using latest api version

### ISSUE THREAD

**Issue by Bartheleway** [forcedotcom/cli#3004]
### Summary
When no version is specified (because optional), CLI is supposed to retrieve by itself the latest version available.
This doesn't seems to work. I have seen it broken in docker container which is really hard to debug.

### Steps To Reproduce

I don't really know how to reproduce as navigating through the CLI code didn't help me understand why it doesn't get latest version nor where are located some of the warning message I am getting.

### Expected result
If no version is specified always use the latest version available.

### Actual result
Sometimes using a previous version probably taken from some cache which never gets refreshed.

### Additional information
The CLI is running inside a docker container. No config has been done to cache the `.sfdx/[username].json` file (which stores the `instanceApiVersion` cached property).

I can even see a `Removing .sf/` and `Removing .sfdx/` in the log of the CI which should remove these. Which means maybe there is some sort of env variable cached?

My project & CLI installation **has none** of the mentioned method to setup version done: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_apiversion.htm

Here are the some tests and error message I got:
- Without specifying anything
  - `Warning: Deprecated config name: apiVersion. Please use org-api-version instead.`
  - `"warnings": ["API version not found or not supported, using '60' instead"]`
- Specifying an env variable `SF_ORG_API_VERSION` to `61.0`
  - `WARNING: apiVersion configuration overridden at "61.0"`
  - `Warning: Deprecated config name: apiVersion. Please use org-api-version instead.`
  - `"warnings": ["API version not found or not supported, using '60' instead"]`
- Specifying a `sourceApiVersion` in `sfdx-project.json` to `61.0`
  - `Warning: Deprecated config name: apiVersion. Please use org-api-version instead.`
  - Found out that it did use the given 61.0 and my deployment worked

Looking at the CLI sourcecode:
- CLI seems to put the retrieve version in [cache](https://github.com/forcedotcom/sfdx-core/blob/935535a08bca5af9e4d56118ccbbaf1babee192c/src/org/connection.ts#L234)
- CLI seems to never refresh its cache, storing a `instanceApiVersionLastRetrieved` but never considering it expires

### System Information
Docker container triggered by Gitlab pipeline (equivalent to Github actions or CI).

Docker container is a "debian-slim" with:

```json
{
  "cliVersion": "@salesforce/cli/2.57.7",
  "architecture": "linux-x64",
  "nodeVersion": "node-v20.17.0",
  "osVersion": "Linux 5.15.153.1-microsoft-standard-WSL2",
  "shell": "bash",
  "rootPath": "/usr/lib/node_modules/@salesforce/cli",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.2 (core)",
    "@oclif/plugin-commands 4.0.13 (core)",
    "@oclif/plugin-help 6.2.10 (core)",
    "@oclif/plugin-not-found 3.2.18 (core)",
    "@oclif/plugin-plugins 5.4.6 (core)",
    "@oclif/plugin-search 1.2.7 (core)",
    "@oclif/plugin-update 4.5.5 (core)",
    "@oclif/plugin-version 1.3.10 (link) /opt/sfdx-cli-enhanced/node_modules/@oclif/plugin-version",
    "@oclif/plugin-warn-if-update-available 3.1.13 (core)",
    "@oclif/plugin-which 3.2.12 (core)",
    "@salesforce/cli 2.57.7 (core)",
    "apex 3.4.5 (core)",
    "api 1.2.1 (core)",
    "auth 3.6.51 (core)",
    "data 3.6.3 (core)",
    "deploy-retrieve 3.12.0 (core)",
    "info 3.4.2 (core)",
    "limits 3.3.27 (core)",
    "marketplace 1.2.24 (core)",
    "org 4.5.4 (core)",
    "packaging 2.8.0 (core)",
    "schema 3.3.26 (core)",
    "settings 2.3.15 (core)",
    "sobject 1.4.32 (core)",
    "source 3.5.16 (core)",
    "telemetry 3.6.10 (core)",
    "templates 56.3.14 (core)",
    "trust 3.7.25 (core)",
    "user 3.5.26 (core)"
  ]
}
```

**Comment by shetzel** [comment]
Hi @Bartheleway - can you let me know what the output of `sf doctor` states, especially with the environment variables and the diagnostic tests for API version.  It can also be helpful to run the command with `--dev-debug` which has some output around discovering API versions.  The doctor command can also handle that for you with: `sf doctor --command "the command you are running"`.  Which command are you running by the way?

**Comment by Bartheleway** [comment]
Because my issue is in a docker container, it is really hard to get this kind of information.

I think I find out from where the `60.0` comes from. In fact my job is generating an XML file which is then used with `sf project deploy validate` command to deploy it to the org. This XML file contains `<version>60.0</version>`.

This file is generated from [sfdx-git-delta](https://github.com/scolladon/sfdx-git-delta) plugins. I believe they are handling the get max api version a bit differently than you. I will check with them 😃

**Comment by shetzel** [comment]
Yes the version from a manifest will be used in that case.  Here is a doc that will hopefully make this less confusing (because it is confusing): https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_apiversion.htm
