### ISSUE TITLE
Lighting-dev plugin : Error (1): The requested resource does not exist

### ISSUE THREAD

**Issue by elliot41** [forcedotcom/cli#3010]
### Summary

I am launching the command : sf lightning dev app

This error appears : Error (1): The requested resource does not exist

### Expected result

Open the local dev server with the default org application

### Actual result

Error message

### Additional information

**VS Code Version**: 
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**SFDX CLI Version**: @salesforce/cli/2.42.6 win32-x64 node-v20.14.0
**plugin lightning dev version **: lightning-dev 1.1.0

**Comment by elliot41** [comment]
sf version --verbose --json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.42.6",
  "nodeVersion": "node-v20.14.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\elcather\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.18 (core)",
    "@oclif/plugin-commands 3.3.4 (core)",
    "@oclif/plugin-help 6.0.22 (core)",
    "@oclif/plugin-not-found 3.1.9 (core)",
    "@oclif/plugin-plugins 5.0.21 (core)",
    "@oclif/plugin-search 1.0.24 (core)",
    "@oclif/plugin-update 4.2.12 (core)",
    "@oclif/plugin-version 2.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.19 (core)",
    "@oclif/plugin-which 3.1.10 (core)",
    "@salesforce/cli 2.42.6 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.11 (core)",
    "data 3.3.5 (core)",
    "deploy-retrieve 3.6.14 (core)",
    "info 3.2.8 (core)",
    "lightning-dev 1.1.0 (user) published 22 days ago (Sun Aug 18 2024)",
    "limits 3.3.7 (core)",
    "marketplace 1.2.5 (core)",
    "org 4.1.10 (core)",
    "packaging 1.17.3 (user) published 472 days ago (Fri May 26 2023) (latest is 2.8.4)",
    "schema 3.3.6 (core)",
    "settings 2.2.6 (core)",
    "signups 1.4.20 (user) published 470 days ago (Sat May 27 2023) (latest is 2.5.14)",
    "sobject 1.4.2 (core)",
    "source 3.3.12 (core)",
    "telemetry 3.3.7 (core)",
    "templates 56.2.7 (core)",
    "trust 3.6.11 (core)",
    "user 3.5.8 (core)",
    "@salesforce/sfdx-scanner 3.12.0 (user) published 495 days ago (Tue May 02 2023) (latest is 4.5.0)",
    "sfdmu 4.33.17 (user) published 130 days ago (Thu May 02 2024) (latest is 4.36.0)",
    "sfdx-git-delta 5.43.0 (user) published 4 days ago (Wed Sep 04 2024)"
  ]
}

**Comment by elliot41** [comment]
Still have the issue with the updated config : 

sf version --verbose --json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.57.7",
  "nodeVersion": "node-v20.14.0",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\elcather\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.2 (core)",
    "@oclif/plugin-commands 4.0.13 (core)",
    "@oclif/plugin-help 6.2.10 (core)",
    "@oclif/plugin-not-found 3.2.18 (core)",
    "@oclif/plugin-plugins 5.4.6 (core)",
    "@oclif/plugin-search 1.2.7 (core)",
    "@oclif/plugin-update 4.5.5 (core)",
    "@oclif/plugin-version 2.2.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.13 (core)",
    "@oclif/plugin-which 3.2.12 (core)",
    "@salesforce/cli 2.57.7 (core)",
    "apex 3.4.5 (core)",
    "api 1.2.1 (core)",
    "auth 3.6.51 (core)",
    "data 3.6.3 (core)",
    "deploy-retrieve 3.12.0 (core)",
    "info 3.4.2 (core)",
    "lightning-dev 1.1.0 (user) published 22 days ago (Sun Aug 18 2024)",
    "limits 3.3.27 (core)",
    "marketplace 1.2.24 (core)",
    "org 4.5.4 (core)",
    "packaging 1.17.3 (user) published 472 days ago (Fri May 26 2023) (latest is 2.8.4)",
    "schema 3.3.26 (core)",
    "settings 2.3.15 (core)",
    "signups 1.4.20 (user) published 470 days ago (Sat May 27 2023) (latest is 2.5.14)",
    "sobject 1.4.32 (core)",
    "source 3.5.16 (core)",
    "telemetry 3.6.10 (core)",
    "templates 56.3.14 (core)",
    "trust 3.7.25 (core)",
    "user 3.5.26 (core)",
    "@salesforce/sfdx-scanner 3.12.0 (user) published 495 days ago (Tue May 02 2023) (latest is 4.5.0)",
    "sfdmu 4.33.17 (user) published 130 days ago (Thu May 02 2024) (latest is 4.36.0)",
    "sfdx-git-delta 5.43.0 (user) published 4 days ago (Wed Sep 04 2024)"
  ]
}

**Comment by Ewaken** [comment]
Hello @elliot41, I think we have to open an issue on the plugin-lightning-dev repo from now.
![image](https://github.com/user-attachments/assets/3a795dd3-79a7-48e9-ae57-83cf4b183dca)

**Comment by elliot41** [comment]
Not an issue, i forced the apiversion of sf to 62.0, it works now.
