### ISSUE TITLE
sf project deploy start --metadata  CustomField:Account.ABNs__c --test-level RunLocalTests  Giving me error that account object is missing form package 

### ISSUE THREAD

**Issue by PiusSe** [forcedotcom/cli#3017]
Currently using @salesforce/cli/2.57.7 linux-x64 node-v20.16.0 Version

**Comment by iowillhoit** [comment]
Closing due to lack of information. Provide all the details in our Issue Template.
You can use `sf doctor --create-issue` to collect some info automatically
