### ISSUE TITLE
Frequent AuthDecryptError on all connected orgs

### ISSUE THREAD

**Issue by dpr-nh** [forcedotcom/cli#3018]
### Summary
While working, I'm deploying frequently to a sandbox and will be running the same deploy command multiple times. At some point I will get this error seemingly at random:
```shell
Error (2): Parsing --target-org 
        Failed to decipher auth data. reason: Unsupported state or unable to authenticate data.
See more help with --help
```

After this happens, I check my connected orgs using `sf org list` and see that every single one has the same `AuthDecryptError` status. It's not just the org I was working on, it's all my connected orgs getting disconnected at the same time.

This problem happens multiple times a day. I'm not sure if this is a bug with the sf CLI or Salesforce itself, hoping you can point me in the right direction.

### Steps To Reproduce
I honestly do not know how to reproduce this. It happens what seems totally randomly.

### System Information

```json
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.44.8",
  "nodeVersion": "node-v20.11.0",
  "osVersion": "Linux 6.10.8-200.fc40.x86_64",
  "rootPath": "/home/dpr/.nvm/versions/node/v20.11.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.18 (core)",
    "@oclif/plugin-commands 3.3.4 (core)",
    "@oclif/plugin-help 6.0.22 (core)",
    "@oclif/plugin-not-found 3.1.10 (core)",
    "@oclif/plugin-plugins 5.1.3 (core)",
    "@oclif/plugin-search 1.0.24 (core)",
    "@oclif/plugin-update 4.2.14 (core)",
    "@oclif/plugin-version 2.1.2 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.19 (core)",
    "@oclif/plugin-which 3.1.10 (core)",
    "@salesforce/cli 2.44.8 (core)",
    "apex 3.1.13 (core)",
    "auth 3.6.17 (core)",
    "community 2.3.14 (user) published 382 days ago (Sat Aug 26 2023) (latest is 3.2.30)",
    "data 3.4.3 (core)",
    "deploy-retrieve 3.8.3 (core)",
    "info 3.3.3 (core)",
    "limits 3.3.9 (core)",
    "marketplace 1.2.8 (core)",
    "org 4.1.14 (core)",
    "packaging 2.4.5 (core)",
    "schema 3.3.9 (core)",
    "settings 2.2.7 (core)",
    "sobject 1.4.6 (core)",
    "source 3.3.18 (core)",
    "telemetry 3.3.11 (core)",
    "templates 56.2.9 (core)",
    "trust 3.7.3 (core)",
    "user 3.5.11 (core)"
  ]
}
```

**Comment by iowillhoit** [comment]
This looks similar to this issue: https://github.com/forcedotcom/cli/issues/2174

Are you using KWallet? 

Update to the latest version of the CLI (currently `2.58.7`) and try setting this env var: `SF_USE_GENERIC_UNIX_KEYCHAIN=true`
Details here: https://github.com/forcedotcom/cli/issues/2174#issuecomment-2306647063

**Comment by shetzel** [comment]
I would run `sf doctor` as well and note the diagnostic tests around v2 crypto.  Changing the encryption key without complete support from all installed plugins may cause decryption problems.

**Comment by dpr-nh** [comment]
Hi @iowillhoit,

I'm not using KWallet.
I've updated my CLI and set the env variable. I'll let you know if I get the problem again.

**Comment by dpr-nh** [comment]
Haven't had the problem since so either updating or setting the env variable fixed the issue.

**Comment by 0cv** [comment]
Bug is still here but setting `SF_USE_GENERIC_UNIX_KEYCHAIN` is indeed workarounding successfully the issue  ...
