### ISSUE TITLE
Unable to deploy the custom fields in standard object in sf using package.xml 

### ISSUE THREAD

**Issue by PiusSe** [forcedotcom/cli#3020]
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    
    <types>
        <members>Case.ancb__c</members>
        <name>CustomField</name>
    </types>
    
    <version>61.0</version>
</Package>

When trying to deploy the custom fields in standard fields getting below error . but when tried with custom fields in custom objects deployment is success . 

SF command  sf project deploy start  --manifest manifest/package.xml

Cli version : @salesforce/cli/2.58.7 linux-x64 node-v20.11.1
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.58.7",
  "nodeVersion": "node-v20.11.1",
  "osVersion": "Linux 6.1.106-116.188.amzn2023.x86_64",
  "rootPath": "/home/codebuilder/.npm-packages/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.2 (core)",
    "@oclif/plugin-commands 4.0.13 (core)",
    "@oclif/plugin-help 6.2.10 (core)",
    "@oclif/plugin-not-found 3.2.18 (core)",
    "@oclif/plugin-plugins 5.4.6 (core)",
    "@oclif/plugin-search 1.2.7 (core)",
    "@oclif/plugin-update 4.5.5 (core)",
    "@oclif/plugin-version 2.2.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.13 (core)",
    "@oclif/plugin-which 3.2.12 (core)",
    "@salesforce/cli 2.58.7 (core)",
    "apex 3.4.8 (core)",
    "api 1.2.1 (core)",
    "auth 3.6.54 (core)",
    "data 3.6.5 (core)",
    "deploy-retrieve 3.12.3 (core)",
    "info 3.4.3 (core)",
    "limits 3.3.29 (core)",
    "marketplace 1.2.25 (core)",
    "org 4.5.7 (core)",
    "packaging 2.8.2 (core)",
    "schema 3.3.26 (core)",
    "settings 2.3.16 (core)",
    "sobject 1.4.33 (core)",
    "source 3.5.18 (core)",
    "telemetry 3.6.10 (core)",
    "templates 56.3.17 (core)",
    "trust 3.7.27 (core)",
    "user 3.5.29 (core)",
    "@salesforce/sfdx-scanner 4.5.0 (user) published 15 days ago (Tue Aug 27 2024)",
    "sfdx-plugin-source-read 1.2.0 (user) published 323 days ago (Tue Oct 24 2023)"
  ]
}

Error Case.AllOpenCases                             Not in package.xml             
| Error Case.All_ARC_Pays                             Not in package.xml             
| Error Case.All_Application_Support_Cases            Not in package.xml             
| Error Case.All_Basic_Deduction_Cases                Not in package.xml             
| Error Case.All_CE_Cases                             Not in package.xml             
| Error Case.All_Cases                                Not in package.xml             
| Error Case.All_Compos_GL_TRUE                       Not in package.xml             
| Error Case.All_Contractor_Pay_Cases                 Not in package.xml             
| Error Case.All_Converga_Cases                       Not in package.xml             
| Error Case.All_Courier_Post_Pays                    Not in package.xml             
| Error Case.All_EIS_Admin_Cases                      Not in package.xml             
| Error Case.All_Holidays_Act                         Not in package.xml             
| Error Case.All_Investigation_Cases_created_by_CS    Not in package.xml  

    <types>
        <members>Case_Transfer_Queue_Routing_IDs__c.XX__x</members>
        <members>Case_Transfer_Queue_Routing_IDs__c.XXX__x</members>
        <members>Case.ancb__c</members>
        <name>CustomField</name>
    </types>
    
    <version>61.0</version>
</Package>

**Comment by iowillhoit** [comment]
Hello @PiusSe, I am able to deploy a Custom Field on a Standard Object with a manifest. Maybe I am not understanding the issue.

Steps:
- I created a Custom Field named `ancb` on the Standard Object `Case`
- I created a package.xml with just that Custom Field
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Case.ancb__c</members>
        <name>CustomField</name>
    </types>
    <version>61.0</version>
</Package>
```
- I deployed to a scratch org using that manifest `sf project deploy start --manifest package.xml`
- The Custom Field was updated in the org

Screenshot:
![Image](https://github.com/user-attachments/assets/b698ab03-fc45-473f-9bdb-63a815c1a775)

Can you please provide use with a github repository (with detailed steps) that allows us to easily reproduce this issue? The [Dreamhouse sample app](https://github.com/trailheadapps/dreamhouse-lwc) is a good starting point

**Comment by PiusSe** [comment]
> Hello @PiusSe, I am able to deploy a Custom Field on a Standard Object with a manifest. Maybe I am not understanding the issue.
> 
> Steps:
> 
> * I created a Custom Field named `ancb` on the Standard Object `Case`
> * I created a package.xml with just that Custom Field
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <Package xmlns="http://soap.sforce.com/2006/04/metadata">
>     <types>
>         <members>Case.ancb__c</members>
>         <name>CustomField</name>
>     </types>
>     <version>61.0</version>
> </Package>
> ```
> 
> * I deployed to a scratch org using that manifest `sf project deploy start --manifest package.xml`
> * The Custom Field was updated in the org
> 
> Screenshot: ![Image](https://private-user-images.githubusercontent.com/1715111/366965868-b698ab03-fc45-473f-9bdb-63a815c1a775.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzY2NjAsIm5iZiI6MTcyNjE3NjM2MCwicGF0aCI6Ii8xNzE1MTExLzM2Njk2NTg2OC1iNjk4YWIwMy1mYzQ1LTQ3M2YtOWJkYi02M2E4MTVjMWE3NzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMjEyNjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhiMzkyMTFlYjc1OTJkNWZkYTdiMmIwZjBlYWEwMTdhNmM5MDJmY2NmMjNiYzlhMDQ4ZTc1NDU3NmY3MGZmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-6Da5AQIL7-kD8UfsmoMdiOxlsYUePBQcxE97f_TyZY)
> 
> Can you please provide use with a github repository (with detailed steps) that allows us to easily reproduce this issue? The [Dreamhouse sample app](https://github.com/trailheadapps/dreamhouse-lwc) is a good starting point

i AM USING 62.0 SOAP API AND CLI VERSION IS "cliVersion": "@salesforce/cli/2.58.7",. wHAT IS YOURS?

**Comment by iowillhoit** [comment]
I am also using version `2.58.7`. In my previous post I was using the `61.0` soap API. 
I just tried it again using the `62.0` version and it also worked for me. 

![Image](https://github.com/user-attachments/assets/a7a3f478-e485-46eb-bd99-59069cc74676)
