### ISSUE TITLE
Metadata API request failed: request to https://***.my.salesforce.com/services/Soap/m/61.0 failed, reason: connect ECONNREFUSED 22.113.58.131:8080'

### ISSUE THREAD

**Issue by Tanvidh** [forcedotcom/cli#3021]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.
sf project deploy start command giving issue as

name": "MetadataTransferError",

   "message": "Metadata API request failed: request to https://***.sandbox.my.salesforce.com/services/Soap/m/61.0 failed, reason: connect ECONNREFUSED [22.113.58.131:8080](http://22.113.58.131:8080/)",

> use `sf doctor --create-issue` to automatically fill the required information
[diagnostics_file692024.txt](https://github.com/user-attachments/files/16997567/diagnostics_file692024.txt)

### Expected result

Deployment or Validation should be run

### Actual result

Metadata API request failed: request to https://***.sandbox.my.salesforce.com/services/Soap/m/61.0 failed, reason: connect ECONNREFUSED [22.113.58.131:8080](http://22.113.58.131:8080/)",

### System Information
zsh

Verbose output:
architecture": "linux-x64",

   "cliVersion": "@salesforce/cli/2.57.7",

   "nodeVersion": "node-v20.16.0",

   "osVersion": "Linux 4.18.0-553.8.1.el8_10.x86_64",

   "rootPath": [/apps/external/4/downloaded_tools/.nvm/versions/node/v20.16.0/lib/node_modules/@salesforce/cli](mailto:/apps/external/4/downloaded_tools/.nvm/versions/node/v20.16.0/lib/node_modules/@salesforce/cli),

   "shell": "ksh",

   "pluginVersions": [

     "@oclif/plugin-autocomplete 3.2.2 (core)",

     "@oclif/plugin-commands 4.0.13 (core)",

     "@oclif/plugin-help 6.2.10 (core)",

     "@oclif/plugin-not-found 3.2.18 (core)",

     "@oclif/plugin-plugins 5.4.6 (core)",

     "@oclif/plugin-search 1.2.7 (core)",

     "@oclif/plugin-update 4.5.5 (core)",

     "@oclif/plugin-version 2.2.11 (core)",

     "@oclif/plugin-warn-if-update-available 3.1.13 (core)",

     "@oclif/plugin-which 3.2.12 (core)",

     "@salesforce/cli 2.57.7 (core)",

     "apex 3.4.5 (core)",

     "api 1.2.1 (core)",

     "auth 3.6.51 (core)",

     "data 3.6.3 (core)",

     "deploy-retrieve 3.12.0 (core)",

     "info 3.4.2 (core)",

     "limits 3.3.27 (core)",

     "marketplace 1.2.24 (core)",

     "org 4.5.4 (core)",

     "packaging 2.8.0 (core)",

     "schema 3.3.26 (core)",

     "settings 2.3.15 (core)",

     "sobject 1.4.32 (core)",

     "source 3.5.16 (core)",

     "telemetry 3.6.10 (core)",

     "templates 56.3.14 (core)",

     "trust 3.7.25 (core)",

     "user 3.5.26 (core)"

   ]

}
```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by iowillhoit** [comment]
Hey @Tanvidh, 
If you close an old issue and open a new issue, please link to the old one for context.
Including it here: https://github.com/forcedotcom/cli/issues/2919

I don't have any additional info other than what Cristian and Steve have already provided. Your `sf doctor` diagnosis file includes the following (I removed unrelated lines):
```
{
  "testName": "[@salesforce/plugin-trust] can't ping: https://registry.npmjs.org",
  "status": "fail"
},
{
  "testName": "[@salesforce/plugin-trust] can't ping: https://registry.yarnpkg.com",
  "status": "fail"
},
{
  "testName": "[@salesforce/plugin-trust] can't ping: https://nexus.barcapint.com/nexus/content/groups/barclays-npm-read",
  "status": "fail"
},
{
  "testName": "can't access: https://appexchange.salesforce.com/services/data",
  "status": "fail"
},
{
  "testName": "can't access: https://test.salesforce.com",
  "status": "fail"
},
{
  "testName": "can't access: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64-buildmanifest",
  "status": "fail"
}
```

You clearly have some sort of network configuration that is causing these issues. Please review the suggestions and documentation linked in your previous issue again.

**Comment by Tanvidh** [comment]
Hi @iowillhoit ,
Proxy settings are correct.We tried to debug using wireshark tool.But didn't find any issue.
Can you please suggest something?

**Comment by Tanvidh** [comment]
@shetzel  @iowillhoit  -Can you please help us to debug the root cause of the issue.As we are getting this issuesince long time and yet we didn't find any root cause for this?

**Comment by shetzel** [comment]
@Tanvidh - the root cause of the issue is that something in your environment is not allowing the connection to the endpoints listed above.  That is not a CLI issue.  If it's not proxy settings then maybe it's firewall settings.  https://test.salesforce.com is not down so this is clearly something specific to your environment and you'll need to troubleshoot it.

**Comment by Tanvidh** [comment]
![image](https://github.com/user-attachments/assets/1355884d-7312-4c18-bbc8-285d20e64f50)
@iowillhoit @shetzel 
There is no connectivity issue and we are getting 500 error when there is a POST request containing the zip file for the environment from sf cli side.Can you please help in this case

**Comment by shetzel** [comment]
>Proxy settings are correct
Is there a proxy involved?  I don't see any use of proxy environment variables if so.  That may be the issue.

At this point I would open a support case.  We don't see any indication of a CLI issue.

**Comment by Tanvidh** [comment]
@iowillhoit , @shetzel -We already have opened the ticket but they said it's not related to Salesforce
