### ISSUE TITLE
SF commands failing with "Destination URL not reset. The URL returned from login must be set

### ISSUE THREAD

**Issue by alecdorner** [forcedotcom/cli#3026]
### Summary
sf commands using the [Use an Existing Access Token](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_auth_existing_access_token.htm) are failing with the "Destination URL not reset. The URL returned from login must be set" error.

### Steps to Reproduce:
1. Get the access token from any sandbox org you are logged in
2. Run any SF command using the access token as the --target-org parameter

### Expected Result
1. The command is successful in using the access token

### Actual Result
1. The command fails noting an error "Destination URL not reset. the URL returned from login must be set"

### System Information
@salesforce/cli 2.42.6 (core)
@oclif/plugin-autocomplete 3.0.18 (core)
@oclif/plugin-commands 3.3.4 (core)
@oclif/plugin-help 6.0.22 (core)
@oclif/plugin-not-found 3.1.9 (core)
@oclif/plugin-plugins 5.0.21 (core)
@oclif/plugin-search 1.0.24 (core)
@oclif/plugin-update 4.2.12 (core)
@oclif/plugin-version 2.1.2 (core)
@oclif/plugin-warn-if-update-available 3.0.19 (core)
@oclif/plugin-which 3.1.10 (core)
apex 3.1.11 (core)
auth 3.6.11 (core)
data 3.3.5 (core)
deploy-retrieve 3.6.14 (core)
info 3.2.8 (core)
limits 3.3.7 (core)
marketplace 1.2.5 (core)
org 4.1.10 (core)
packaging 2.4.4 (core)
schema 3.3.6 (core)
settings 2.2.6 (core)
sobject 1.4.2 (core)
source 3.3.12 (core)
telemetry 3.3.7 (core)
templates 56.2.7 (core)
trust 3.6.11 (core)
user 3.5.8 (core)

Uninstalled JIT Plugins:
community 3.2.10
custom-metadata 3.3.7
dev 2.3.1
devops-center 1.2.10
env 3.0.30
functions 1.23.0
signups 2.3.1
@salesforce/sfdx-plugin-lwc-test 1.2.0
@salesforce/sfdx-scanner 3.24.0

**Comment by WillieRuemmele** [comment]
Hi @alecdorner -

did you set the `org-instance-url` config like required in step 3 of the posted link?

before I set that I was seeing the same error, once I set it, using the access token began to work as expected

**Comment by alecdorner** [comment]
@WillieRuemmele oh goodness, I definitely missed that step and that cleared up the issue. Thank you!
