### ISSUE TITLE
The new progress bar is not showing progress details in CI servers logs (ex. Jenkins)

### ISSUE THREAD

**Issue by reda-benhemmouche** [forcedotcom/cli#303]
### Summary

The new status bar make progress invisible in CI server (Jenkins).

![image](https://user-images.githubusercontent.com/45465976/74540319-d9925000-4f3f-11ea-935b-e390ec17501f.png)
In addition, the status bar doesn't what kind of progress. There 2 process in metadata validation: 
1. Component validation 
1. Apex Execution

### Steps To Reproduce:

1.  Update sfdx to the version that contains status bar

### Expected result

The sfdx should update show progress in text format. most of logger in CI server doesn't support dynamic dynamic status bar.
Example with

![image](https://user-images.githubusercontent.com/45465976/74540085-743e5f00-4f3f-11ea-9742-de099cf7a48f.png)

### Actual result

No information about the progress in CI server
See exemple of Jenkins the most popular CI server:

![image](https://user-images.githubusercontent.com/45465976/74539888-20cc1100-4f3f-11ea-920e-9dc1cd0a80af.png)

### Additional information

N/A

**SFDX CLI Version**:
sfdx-cli/7.45.1-bc18d49798 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.0 (core)
generator 1.1.2 (core)
salesforcedx 47.18.0 (core)
├─ salesforcedx-templates 47.19.0 (core)
└─ salesforce-alm 47.16.0 (core)

sfdx-cli 7.45.1 (core)
sfdx-essentials 1.6.5
sfpowerkit 1.38.1

**OS and version**:
mac os x : 10.13.6

**Comment by clairebianchi** [comment]
@reda-benhemmouche the progress bar is for human-readable output and not for CI, I recommend running your commands with --json when running in a CI environment

**Comment by reda-benhemmouche** [comment]
it was fixed in Spring'20 using:

`SFDX_USE_PROGRESS_BAR=false sfdx force:source:deploy`

more details here : https://releasenotes.docs.salesforce.com/en-us/spring20/release-notes/rn_sf_cli_progress_bar.htm
