### ISSUE TITLE
Getting "unauthorized: incorrect username or password" when pulling image since latest update

### ISSUE THREAD

**Issue by jc22zhao** [forcedotcom/cli#3037]
### Summary
I'm trying to pull the docker image from: "https://registry-1.docker.io/v2/salesforce/cli/manifests/latest-full" using "salesforce/cli:latest-full" and until the most recent update on September 27, 2024, it was working fine. However, I noticed that today since 4:30pm (EDT) i have been receiving unauthorized: incorrect username or password error.

> [!TIP]
> use `sf doctor --create-issue` to automatically fill the required information

### Expected result
image should be pulled

### Actual result
unauthorized error

### Additional information
![image](https://github.com/user-attachments/assets/ddd56d08-d83e-4abe-b317-25c21281eab0)

```json
PASTE_VERSION_OUTPUT_HERE
```

**Comment by WillieRuemmele** [comment]
This looks like it's an issue with your docker authentication rather than the salesforce cli. See https://forums.docker.com/t/unauthorized-incorrect-username-or-password/35677
