### ISSUE TITLE
Invalid scope:Mine Error When Deploying ListView with MetaData API

### ISSUE THREAD

**Issue by pgumiela-wbd** [forcedotcom/cli#3039]
### Summary
This bug report is related to the following known issue:
https://issues.salesforce.com/issue/a028c00000qQ8ldAAC/invalid-scopemine-error-when-deploying-listview-with-metadata-api

I know it's archived, but we've asked SF Support to reopen it (Case #468724021) because it's still the case after 10 years and adds a lot of unnecessary overhead in maintaining List Views. 

### Steps To Reproduce
The steps are briefly mentioned in the known issue. It can be easily reproduced by creating a List View with Everything Scope on a sandbox/scratch org, retrieving it locally, changing the scope to Mine and trying to deploy it back. It'll throw the following error:
>  Invalid scope:Mine, not allowed on: object name

### Expected result
Changing the scope to Mine or creating a new List View with Mine scope should be possible.
### Actual result
It is not possible to create a new List View with the scope Mine or change the scope to Mine on an existing List View.

### System Information
```
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.59.6",
  "nodeVersion": "node-v20.11.0",
  "osVersion": "Windows_NT 10.0.22631",
  "rootPath": "...",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.3 (core)",
    "@oclif/plugin-commands 4.0.14 (core)",
    "@oclif/plugin-help 6.2.11 (core)",
    "@oclif/plugin-not-found 3.2.20 (core)",
    "@oclif/plugin-plugins 5.4.7 (core)",
    "@oclif/plugin-search 1.2.8 (core)",
    "@oclif/plugin-update 4.5.6 (core)",
    "@oclif/plugin-version 2.2.12 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.15 (core)",
    "@oclif/plugin-which 3.2.13 (core)",
    "@salesforce/cli 2.59.6 (core)",
    "apex 3.4.9 (core)",
    "api 1.2.1 (core)",
    "auth 3.6.56 (core)",
    "data 3.6.5 (core)",
    "deploy-retrieve 3.12.7 (core)",
    "info 3.4.6 (core)",
    "limits 3.3.30 (core)",
    "marketplace 1.2.25 (core)",
    "org 4.5.8 (core)",
    "packaging 2.8.10 (user) published 1 days ago (Sat Sep 28 2024)",
    "schema 3.3.29 (core)",
    "settings 2.3.19 (core)",
    "sobject 1.4.35 (core)",
    "source 3.5.19 (core)",
    "telemetry 3.6.12 (core)",
    "templates 56.3.18 (core)",
    "trust 3.7.27 (core)",
    "user 3.5.29 (core)",
    "sfdmu 4.36.3 (user) published 10 days ago (Thu Sep 19 2024)",
    "sfdx-essentials 2.12.0 (user) published 1020 days ago (Tue Dec 14 2021)",
    "sfdx-git-delta 5.45.0 (user) published 9 days ago (Fri Sep 20 2024)",
    "sfdx-hardis 5.0.7 (user) published 4 days ago (Wed Sep 25 2024)",
    "texei-sfdx-plugin 2.7.0 (user) published 19 days ago (Tue Sep 10 2024)"
  ]
}
```

**Comment by WillieRuemmele** [comment]
@pgumiela-wbd - I understand the frustration of working with the metadata api, and all of it's limitations. Unfortunately there's nothing that the CLI team can do, we send the data, and the server responds. This will need to be fixed by the feature team. I'll pass along this request, but unfortunately can't help ☹️
