### ISSUE TITLE
Inconsistent behaviour between SfError and SfdxError

### ISSUE THREAD

**Issue by jasmine-anzx** [forcedotcom/cli#3045]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI. ✅
> - You've searched both open and closed issues for related posts.  ✅
> - You've used the `doctor` command to diagnose common issues.  ✅
> - You understand that GitHub Issues don't adhere to any agreement or SLA.  ✅
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.  ✅

### Summary

Behavior between SfError and SfdxError are inconsistent, causing a sfdx plugin to stop working when converted to sf cli.
### Steps To Reproduce
```
const writeStream = fs.createWriteStream(folder + `/filename.json`);
writeStream.write('abcdef');
writeStream.on('error', (err) => {
      throw new SfError(ErrorUtils.getMessage(err, 'Unknown error'), 'FileCreationError', undefined, 1);
});
writeStream.end();
throw new SfError(messages.getMessage('error.FieldsNotAssigned'));
```
- Execute the code above
- When SfError is thrown, the writing of `filename.json` is rolled back, causing the file to be empty
- However, if replacing with `throw new SfdxError(messages.getMessage('error.FieldsNotAssigned'));` in an sfdx command, then the file is not empty

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
> Apologies I can't provide the repo since as it's against my employer's policy
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

> [!TIP]
> use `sf doctor --create-issue` to automatically fill the required information

### Expected result

Throwing SfError should not roll back the execution of `writeStream.write()`
### Actual result

Throwing SfError rolled back the execution of `writeStream.write()`
### System Information

zsh

```
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.60.13",
  "nodeVersion": "node-v20.17.0",
  "osVersion": "Darwin 23.6.0",
  "rootPath": "/Users/nguyen18/.local/share/sf/client/2.60.13-0cbb3a0",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.4 (core)",
    "@oclif/plugin-commands 4.0.15 (core)",
    "@oclif/plugin-help 6.2.12 (core)",
    "@oclif/plugin-not-found 3.2.21 (core)",
    "@oclif/plugin-plugins 5.4.9 (core)",
    "@oclif/plugin-search 1.2.9 (core)",
    "@oclif/plugin-update 4.5.9 (core)",
    "@oclif/plugin-version 2.2.13 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.17 (core)",
    "@oclif/plugin-which 3.2.14 (core)",
    "@salesforce/cli 2.60.13 (core)",
    "apex 3.4.10 (core)",
    "api 1.2.2 (core)",
    "auth 3.6.62 (core)",
    "code-analyzer 5.0.0-alpha.2 (user) published 12 days ago (Wed Sep 25 2024) (latest is 5.0.0-alpha.1)",
    "data 3.6.7 (core)",
    "deploy-retrieve 3.12.11 (core)",
    "dev 2.4.2 (user) published 40 days ago (Tue Aug 27 2024)",
    "info 3.4.9 (core)",
    "limits 3.3.32 (core)",
    "marketplace 1.2.26 (core)",
    "org 4.5.10 (core)",
    "packaging 2.8.7 (core)",
    "schema 3.3.32 (core)",
    "settings 2.3.21 (core)",
    "sobject 1.4.38 (core)",
    "source 3.5.21 (core)",
    "telemetry 3.6.15 (core)",
    "templates 56.3.21 (core)",
    "trust 3.7.31 (core)",
    "user 3.5.31 (core)",
    "@salesforce/sfdx-scanner 4.6.0 (user) published 12 days ago (Wed Sep 25 2024)",
    "anzx-sf-plugin 1.0.0 (link) /Users/nguyen18/dev/salesforce-plugin"
  ]
}
```

**Comment by mdonnalley** [comment]
@jasmine-anzx I'd be surprised if this had something to do with the difference between `SfdxError` and `SfError` - you get the same behavior even if you use a plain `Error`

I think you need to make your code asynchronous. Something like this:

```js
async function write(folder) {
  return new Promise((resolve, reject) => {
    const writeStream = fs.createWriteStream(folder + `/filename.json`);
    writeStream.write('"abcdef"');
    writeStream.on('error', (err) => {
      reject(new SfError('Unknown error', 'FileCreationError', undefined, 1));
    });
    writeStream.on('finish', () => {
      resolve();
    })
    writeStream.end();
  })
}
```
