### ISSUE TITLE
Unable to create v61.0 package after DevHub has updated to v62.0

### ISSUE THREAD

**Issue by simonwatson** [forcedotcom/cli#3046]
Our DevHub has been upgraded to Winter 25 (62.0), but we'd like to create packages that can still be installed in Summer 24 (v61.0) orgs. I have done this before in previous release windows, but this time around I see an error during package creation: `Warning: (1) package.xml: Invalid version specified:62.0`

I have:
- specified `-f config/project-scratch-def.json` to the `sf package version create` command
- added `"release": "previous"` to `config/project-scratch-def.json`
- ensured that `sfdx-project.json` has `"sourceApiVersion": "61.0"` in it (I've also tried removing this property completely)

Am I missing something?

### System Information
```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.60.13",
  "nodeVersion": "node-v20.15.0",
  "osVersion": "Darwin 23.6.0",
  "rootPath": "/Users/simon/.nvm/versions/node/v20.15.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@muenzpraeger/sfdx-plugin 0.5.0 (user) published 1609 days ago (Tue May 12 2020)",
    "@oclif/plugin-autocomplete 3.2.4 (core)",
    "@oclif/plugin-commands 4.0.15 (core)",
    "@oclif/plugin-help 6.2.12 (core)",
    "@oclif/plugin-not-found 3.2.21 (core)",
    "@oclif/plugin-plugins 5.4.9 (core)",
    "@oclif/plugin-search 1.2.9 (core)",
    "@oclif/plugin-update 4.5.9 (core)",
    "@oclif/plugin-version 2.2.13 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.17 (core)",
    "@oclif/plugin-which 3.2.14 (core)",
    "@salesforce/cli 2.60.13 (core)",
    "apex 3.4.10 (core)",
    "api 1.2.2 (core)",
    "auth 3.6.62 (core)",
    "data 3.6.7 (core)",
    "deploy-retrieve 3.12.11 (core)",
    "dev 1.3.3 (user) published 331 days ago (Sat Nov 11 2023) (latest is 2.4.2)",
    "info 3.4.9 (core)",
    "limits 3.3.32 (core)",
    "marketplace 1.2.26 (core)",
    "org 4.5.10 (core)",
    "packaging 2.8.7 (core)",
    "schema 3.3.32 (core)",
    "settings 2.3.21 (core)",
    "signups 2.0.13 (user) published 282 days ago (Sat Dec 30 2023) (latest is 2.5.21)",
    "sobject 1.4.38 (core)",
    "source 3.5.21 (core)",
    "telemetry 3.6.15 (core)",
    "templates 56.3.21 (core)",
    "trust 3.7.31 (core)",
    "user 3.5.31 (core)",
    "@salesforce/sfdx-scanner 4.3.0 (user) published 103 days ago (Tue Jun 25 2024) (latest is 4.6.0)",
    "sfdx-plugin-cli 1.5.0 (link) /Users/simon/git/axsy/sfdx-plugin-cli"
  ]
}
```

**Comment by mdonnalley** [comment]
>Warning: (1) package.xml: Invalid version specified:62.0 

This looks like a warning, not an error. Are you able to provide the full command that you're using and the entire output (with the `--dev-debug` flag)? I'm wondering if something else might be the real issue

**Comment by simonwatson** [comment]
@mdonnalley: thanks for taking a look at this. I'm running `sf package version create -p 0Ho1G0000004CBdSAM -x --code-coverage -f config/project-scratch-def.json` to create the package version. Here's a zip of the `--dev-debug` output:
[debug.txt.zip](https://github.com/user-attachments/files/17290308/debug.txt.zip)

The output of `sf package:version:create:report -i 08cUh0000000n2LIAQ` is:
```
=== Package Version Create Request

 Name                          Value              
 ───────────────────────────── ────────────────── 
 ID                            08cUh0000000n2LIAQ 
 Status                        Error              
 Package Id                    0Ho1G0000004CBdSAM 
 Package Version Id                               
 Subscriber Package Version Id                    
 Tag                                              
 Branch                                           
 Created Date                  2024-10-08 09:13   
 Installation URL                                 
 Created By                    00537000000M7OBAA0 
 Converted From Version Id     ID Unavailable     

=== Errors

Warning: (1) package.xml: Invalid version specified:62.0
```

**Comment by mdonnalley** [comment]
@simonwatson thanks for the details! This functionality is owned by another team so I'll let them know that you reported this issue. In the meantime, you might get better help if you create a support case and/or post a question in one of these trailblazer communities:
- [Unlocked Packages](https://trailhead.salesforce.com/trailblazer-community/groups/0F93A000000Lg5USAS?tab=discussion&sort=LAST_MODIFIED_DATE_DESC)
- [Managed Packages](https://partners.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HXAq)

**Comment by simonwatson** [comment]
I'm closing this issue because, with all our orgs updated to Winter 25, this issue is no longer relevant.
