### ISSUE TITLE
Impossible to deploy to production

### ISSUE THREAD

**Issue by Bartheleway** [forcedotcom/cli#305]
### Summary

After updating to 7.46.1-3d2451fad8, I can't deploy to production anymore. It's asking for a `rollbackOnError` which is not documented.

### Steps To Reproduce:

1.  Try to use `force:mdapi:deploy` or `force:source:deploy`

### Expected result

Being able to deploy.

### Actual result

Stuck because of error : `INVALID_OPERATION: rollbackOnError option must be true on a production org`

### Additional information

sfdx-cli/7.46.1-3d2451fad8 win32-x64 node-v10.15.3

**Comment by PJakober** [comment]
I'm facing the same issue. 
`sfdx version` outputs the same as for @Bartheleway:
sfdx-cli/7.46.1-3d2451fad8 win32-x64 node-v10.15.3

**Comment by Bartheleway** [comment]
For now I deploy with Workbench after using `force:source:convert`.

It looks like the issue has already been solved twice #251 and #61 in the past. Don't you think it's time to write a test to avoid releasing the cli with this error again ?

**Comment by maaaaarco** [comment]
same here...

**Comment by alanjaouen** [comment]
Impacted by this issue here too
`sfdx-cli/7.46.1-3d2451fad8 linux-x64 node-v10.15.3`

**Comment by ghost** [comment]
Running in CI Job:

17-Feb-2020 12:08:59 | sfdx-cli: Updating CLI...
-- | --
17-Feb-2020 12:09:12 | sfdx-cli: Updating CLI from 7.33.2-045d48473e to 7.46.1-3d2451fad8... done
17-Feb-2020 12:09:13 | sfdx-cli: Updating CLI... done
17-Feb-2020 12:09:15 | Successfully authorized nnedkov@rfa.coca-cola.com with org ID 00Dd0000000fSbwEAE
17-Feb-2020 12:09:20 | ERROR running force:source:deploy:  INVALID_OPERATION: rollbackOnError option must be true on a production org

When I remove the sfdx update line it works against production.

**Comment by amphro** [comment]
I opened an investigation but it probably won't get looked at for a few hours. I'll post here when I have an update.

**Comment by manwe651** [comment]
This is affecting us.

**Comment by amphro** [comment]
This was due to an attempt to remove deprecated code. Obviously not all of the code removed was deprecated. We did have tests for this, but those were removed too. Sorry for the inconvenience. We are working on pushing out a fix shortly.

**Comment by amphro** [comment]
We released CLI `7.46.2`. Please let me know if it resolves the issue.

**Comment by PJakober** [comment]
@amphro Thanks for looking into this. It's working again for me :)

**Comment by Bartheleway** [comment]
Thanks I confirm this solve the issue on my side as well.

**Comment by SalesforceBobLightning** [comment]
I am using `@salesforce/cli/2.20.6 win32-x64 node-v20.10.0` and I am getting the same error

> Error (1): INVALID_OPERATION: rollbackOnError option must be true on a production org
