### ISSUE TITLE
End of line is not respected by "sfdx force:source:retrieve or deploy" command

### ISSUE THREAD

**Issue by mos-nabih** [forcedotcom/cli#306]
### Summary
We are using [prettier](https://developer.salesforce.com/tools/vscode/en/user-guide/prettier/) code formatter, which by [default](https://prettier.io/docs/en/options.html#end-of-line) preserves line ending.

However when we commit, deploy and then retrieve, ending lines are removed from my local files, creating large diffs.

That happens on APEX, AURA and LWC files.

### Steps To Reproduce:

1. Create an apex class `MyCls` with an empty line at the end.
1. Commit this class locally using git. 
1. Deploy the class to a sandbox using `sfdx force:source:deploy`.
1. Retrieve the class from the sandbox using `sfdx force:source:retrieve`.
1. Run git diff.

### Expected result

The retrieved apex class should not have been changed. 

### Actual result

Ending line is removed from the apex class creating an unnecessary diff.

### Additional information

**SFDX CLI Version**: 
```
sfdx-cli/7.45.1 darwin-x64 node-v12.16.0
```

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@salesforce/sfdx-diff 0.0.5
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.0 (core)
dependencies-cli 2.0.1
generator 1.1.2 (core)
salesforcedx 47.18.0
├─ salesforce-alm 47.16.0
└─ salesforcedx-templates 47.19.0

sfdx-cli 7.45.1 (core)
```
**OS and version**:
```
macOS Mojave
10.14.6
```

**Comment by clairebianchi** [comment]
@mostafa-anm we are having the mdapi team take a look at this issue.

**Comment by dieffrei** [comment]
+1

**Comment by alexferrari88** [comment]
this is still happening. Any news?

**Comment by jdgirald** [comment]
@mostafa-anm I had the same issue. I have added this to the prettier config file to prevent the diffs:
`{
      "files": "*.{cls,trigger}",
      "options": {
          "apexInsertFinalNewline": false
      }
    }`
