### ISSUE TITLE
creating an object in the UI, then changing the startsWith property in the UI, and then pulling, causes an unsolvable tracking issue

### ISSUE THREAD

**Issue by defabien** [forcedotcom/cli#3069]
### Summary
creating an object in the UI, then changing the startsWith property in the UI, and then pulling, causes an unsolvable tracking issue

unpackaged/package.xml Entity of type 'CustomObject' named 'Invoice' cannot be found 

so instead of it trying to pull 'Invoice__c', it tries to pull 'Invoice' and keeps failing

### Steps To Reproduce
- create object Invoice__c in the salesforce UI
- change startsWith Invoice__c property in the salesforce UI (IMPORTANT: don't retrieve up until here)
- retrieve via sf cli
- get unpackaged/package.xml Entity of type 'CustomObject' named 'Invoice' cannot be found 

### Expected result
no 'unpackaged/package.xml Entity of type 'CustomObject' named 'Invoice' cannot be found' error

### Actual result
'unpackaged/package.xml Entity of type 'CustomObject' named 'Invoice' cannot be found' error

### System Information
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.62.6",
  "nodeVersion": "node-v20.17.0",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/fabien/.local/share/sf/client/2.62.6-7a5c386",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.5 (core)",
    "@oclif/plugin-commands 4.1.3 (core)",
    "@oclif/plugin-help 6.2.14 (core)",
    "@oclif/plugin-not-found 3.2.22 (core)",
    "@oclif/plugin-plugins 5.4.14 (core)",
    "@oclif/plugin-search 1.2.11 (core)",
    "@oclif/plugin-update 4.6.3 (core)",
    "@oclif/plugin-version 2.2.14 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.18 (core)",
    "@oclif/plugin-which 3.2.15 (core)",
    "@salesforce/cli 2.62.6 (core)",
    "apex 3.5.1 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.65 (core)",
    "data 3.7.0 (core)",
    "deploy-retrieve 3.12.17 (core)",
    "info 3.4.9 (core)",
    "limits 3.3.32 (core)",
    "marketplace 1.2.26 (core)",
    "org 4.6.0 (core)",
    "packaging 2.8.11 (core)",
    "schema 3.3.34 (core)",
    "settings 2.3.23 (core)",
    "signups 2.5.21 (user) published 13 days ago (Sat Oct 05 2024) (latest is 2.5.23)",
    "sobject 1.4.41 (core)",
    "source 3.5.21 (core)",
    "telemetry 3.6.15 (core)",
    "templates 56.3.22 (core)",
    "trust 3.7.33 (core)",
    "user 3.5.32 (core)"
  ]
}

**Comment by iowillhoit** [comment]
Hey @defabien I am not seeing this issue. I am also using version `2.62.6`. What is the exact command you are using to `retrieve`? Are you able to replicate this with a copy of [Dreamhouse](https://github.com/trailheadapps/dreamhouse-lwc)?

 https://github.com/user-attachments/assets/b59ef09d-bb12-4087-8c40-06ffef4bcdd2

**Comment by defabien** [comment]
Hi @iowillhoit,

The command I am using is 

```shell
sf project retrieve start -o spr-so-dev -c
```

**Comment by defabien** [comment]
@iowillhoit I will try to make a screencapture like you did!
