### ISSUE TITLE
Pulling a connected app with an appmenu item causes the cli to hang

### ISSUE THREAD

**Issue by laurakolker** [forcedotcom/cli#307]
### Summary

_Short summary of what is going on or to provide context_.

If I create a Connected App in a scratch org and it has the following status:
STATE       FULL NAME                     TYPE          PROJECT PATH
──────────  ────────────────────────────  ────────────  ────────────
Remote Add  Connector_Name  ConnectedApp
Remote Add  AppSwitcher                   AppMenu

Then attempting to pull with sfdx force:source:pull will hang. 
You can workaround this by adding a reference to AppSwitcher.AppMenu in the .forceignore file, but hanging is non-ideal. 

### Steps To Reproduce:

1.  Create a scratch org
1.  Create a connected app
1. sfdx force:source:pull

### Expected result
Either pulling whatever appropriate xml should be pulled, or an error explaining what the user is expected to do, or .forceignore pre-populated with AppSwitcher.appMenu if this is an unsolveable problem.

### Actual result

CLI hangs forever until you Ctrl-C out of there

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.45.1-bc18d49798 linux-x64 node-v10.15.3)

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
salesforcedx 47.18.0 (core)
├─ salesforcedx-templates 47.19.0 (core)
└─ salesforce-alm 47.16.0 (core)
sfdx-cli 7.45.1 (core)

**OS and version**:
Ubuntu PopOs 19.10

**Comment by clairebianchi** [comment]
@laurakolker  We will take a look

**Comment by mdonnalley** [comment]
@laurakolker I wasn't able to reproduce this issue. Do you mind updating your version of the CLI to the latest and confirming that you're still experiencing this?

**Comment by laurakolker** [comment]
You're right. I'm not able to reproduce the issue with version sfdx-cli/7.48.0-a71f8c6899 linux-x64 node-v10.15.3
Thanks for following up. :)
