### ISSUE TITLE
'upsert bulk' and 'record create' into certain low-level objects such as GroupMember does not work

### ISSUE THREAD

**Issue by OscarTheGrinch** [forcedotcom/cli#3072]
# Version information
```
# Platform
Windows 10 x64, PowerShell 7.2.16

# Salesforce CLI version
@salesforce/cli/2.62.6 win32-x64 node-v20.5.1
```

# Goal
I want to create GroupMember records in an org by inserting GroupMember records via the CLI. I want to be able to do this for CI/CD and backup purposes.

# Steps to reproduce

## Preparation

In any org, create two or more public groups. Do not make any group a member of another group yet.

Attempt the following:

## Option A) Upsert bulk

Prepare a CSV file as follows:

|       Id       |     GroupId    | UserOrGroupId  |
|-----------|---------------|-------------------|
|      #N/A  |  00G#####  |    00G#####       |

Where GroupId points to group A, and UserOrGroupId posts to group B, which should become a member of group A.

Running the command:
```
sf data upsert bulk -f ./preparedCSV.csv -i Id -s GroupMember -o orgName
```

results in:
```
InvalidJob : No create/update access for object:GroupMember
```

## Option B)

Running the command:
```
sf data create record -o orgName -s GroupMember -v "GroupId='00G#####', UserOrGroupId='00G#####'"
````

where GroupId points to group A, and UserOrGroupId posts to group B, which should become a member of group A

results in
```
Creating record for GroupMember... Error
Error (1): Group ID: id value of incorrect type: 00GQI000004pFqo2AE
```

# Expected behavior

One of the two options results in GroupMember records being created for the listed groups, effectively making one group a member of the other.

# Additional info

When using the exact same CSV as an input for 'Salesforce Inspector Reloaded > Data Import' the upload succeeds without any issues, proving that I do in fact have create/update access on the object, and the GroupId value is of the correct type. It seems the three methods (upsert bulk, create record, inspector) use three distinct APIs, with the one from Inspector being more flexible when it comes to supported objects?

This problem also seems to affect other technical/low-level objects as well.

**Comment by OscarTheGrinch** [comment]
Full version info, as requested by the bot:
```
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.62.6",
  "nodeVersion": "node-v20.5.1",
  "osVersion": "Windows_NT 10.0.19045",
  "rootPath": "C:\\Users\\GerardvK\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "cmd.exe",
  "pluginVersions": [
    "@jayree/sfdx-plugin-org 1.2.77 (user) published 3 days ago (Fri Oct 18 2024)",
    "@jayree/sfdx-plugin-source 1.3.81 (user) published 3 days ago (Fri Oct 18 2024)",
    "@oclif/plugin-autocomplete 3.2.5 (core)",
    "@oclif/plugin-commands 4.1.3 (core)",
    "@oclif/plugin-help 6.2.14 (core)",
    "@oclif/plugin-not-found 3.2.22 (core)",
    "@oclif/plugin-plugins 5.4.14 (core)",
    "@oclif/plugin-search 1.2.11 (core)",
    "@oclif/plugin-update 4.6.3 (core)",
    "@oclif/plugin-version 2.2.14 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.18 (core)",
    "@oclif/plugin-which 3.2.15 (core)",
    "@salesforce/cli 2.62.6 (core)",
    "apex 3.5.1 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.65 (core)",
    "data 3.7.0 (core)",
    "deploy-retrieve 3.12.17 (core)",
    "info 3.4.9 (core)",
    "limits 3.3.32 (core)",
    "marketplace 1.2.26 (core)",
    "org 4.6.0 (core)",
    "packaging 2.8.11 (core)",
    "schema 3.3.34 (core)",
    "settings 2.3.23 (core)",
    "signups 2.5.21 (user) published 16 days ago (Sat Oct 05 2024) (latest is 2.5.23)",
    "sobject 1.4.41 (core)",
    "source 3.5.21 (core)",
    "telemetry 3.6.15 (core)",
    "templates 56.3.22 (core)",
    "trust 3.7.33 (core)",
    "user 3.5.32 (core)",
    "sfdx-git-delta 5.48.0 (user) published 3 days ago (Fri Oct 18 2024) (latest is 5.49.0)"
  ]
}
```

**Comment by iowillhoit** [comment]
It makes sense that the `upsert` fail since GroupMember is not updatable:
```shell
sf sobject describe --sobject groupmember --json | jq '.result.updateable'
# false
```

One of our engineers (@cristiand391) just added new `sf data import bulk` command to the CLI. It is available in the `latest-rc` (`stable-rc`) build and will be in `latest` on October 30th. 

Using that command we are able to get this working:
`sf data import bulk --file test.csv --sobject groupmember --wait 10`

Cristian also shared a few ways to check on the results:
`sf data bulk results --job-id THE_JOB_ID`
or
`sf api request rest services/data/v62.0/jobs/ingest/THE_JOB_ID/successfulResults`

**Comment by OscarTheGrinch** [comment]
@iowillhoit thanks for the response. I will try this out today or else later this weekend, and will let you know if this update resolves my issue.

**Comment by OscarTheGrinch** [comment]
@iowillhoit this update seems to work, and resolves my issue. Thanks to the both of you (including @cristiand391)!
