### ISSUE TITLE
Edits not reflected in Local Dev server

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#3076]
### Summary

While running a dev sever with `sf lightning dev app`, the server starts and the page loads in my browser, but edits to local LWC html files are not reflected in the running page.

### Steps To Reproduce

I'm trying to work with a `lightning__RecordPage`-targeted LWC while is present on my Opportunity Lightning page.  These are the steps I followed:

1. Install CLI and Local Dev plugin
2. Enable Local Dev in sandbox
3. Run the dev server:  `sf lightning dev app -n LightningSales`
4. Navigate to Opportunities tab (present in the LightningSales app), click an opportunity, select the tab within the page where my LWC is placed.
5. Make simple edits to the LWC HTML file, such as changing the `title` attribute of a `lightning-card` element. 

### Expected result
Edits should be seen in the running page.

### Actual result
No changes are reflected in the running page.

### Additional information
The plugin runs with no errors, and no command line output when files are modified (no idea if that is expected).  It opens the app in the browser using an url that appears to include local dev server info, e.g., 

```
https://orgname--full.sandbox.lightning.force.com/lightning/r/Opportunity/006WC000007PagzYAC/view?0.aura.ldpServerUrl=ws%3A%2F%2Flocalhost%3A8081&0.aura.ldpServerId=1I9WC0000000BZl0AM&0.aura.mode=DEVPREVIEW
```

I tried a full uninstall/reinstall of the plugin and the CLI, with no luck.

### System Information
using `zsh` on Mac OS 14.6.1

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.62.6",
  "nodeVersion": "node-v20.17.0",
  "osVersion": "Darwin 23.6.0",
  "rootPath": "/Users/jclark/.nvm/versions/node/v20.17.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.5 (core)",
    "@oclif/plugin-commands 4.1.3 (core)",
    "@oclif/plugin-help 6.2.14 (core)",
    "@oclif/plugin-not-found 3.2.22 (core)",
    "@oclif/plugin-plugins 5.4.14 (core)",
    "@oclif/plugin-search 1.2.11 (core)",
    "@oclif/plugin-update 4.6.3 (core)",
    "@oclif/plugin-version 2.2.14 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.18 (core)",
    "@oclif/plugin-which 3.2.15 (core)",
    "@salesforce/cli 2.62.6 (core)",
    "apex 3.5.1 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.65 (core)",
    "data 3.7.0 (core)",
    "deploy-retrieve 3.12.17 (core)",
    "info 3.4.9 (core)",
    "lightning-dev 1.9.0 (user) published 10 days ago (Fri Oct 11 2024)",
    "limits 3.3.32 (core)",
    "marketplace 1.2.26 (core)",
    "org 4.6.0 (core)",
    "packaging 2.8.11 (core)",
    "schema 3.3.34 (core)",
    "settings 2.3.23 (core)",
    "sobject 1.4.41 (core)",
    "source 3.5.21 (core)",
    "telemetry 3.6.15 (core)",
    "templates 56.3.22 (core)",
    "trust 3.7.33 (core)",
    "user 3.5.32 (core)"
  ]
}
```

**Comment by mmablom** [comment]
I have also experienced this issue, with two different causes I can find:

1. Apparently Lighting Web Security has to be enabled for Local Dev to work. I was trying in an org where it was turned off and after a lot of trying finally figured out this must have been the cause. After enabling it (and refreshing) it started working. This is not mentioned anywhere in the documentation as far as I could find.
2. Changes only seem to be picked up in the default directory structure, for instance `force-app/main/default/lwc`. In most projects we have multiple directories under `main`, to organize metadata for different domains. Edits in LWCs under directories other than `default` do not get picked up by Local Dev. 
I tested this with 2 components on the same page, one from `default` and one from another directory. Changing the first instantly refreshed the component on the page, while changing the second did nothing.

**Comment by jclark-dot-org** [comment]
Thanks @mmablom, that's a great catch - I thought I had LWS enabled in this org, but it was not; correcting that and hard-refreshing has fixed the issue.  This sounds like a documentation bug.  I'll leave this open so the issue can be tracked.

Regarding item #2 of @mmablom's comment, I'd like to ask that the team consider that a bug.  It doesn't affect this project, but I have a big project with multiple unlocked packages, each in its own top-level directory (siblings to force-app).  These directories are all spelled out in the `sfdx-project.json`, so it shouldn't be too hard for the dev server to know which directory(s) to monitor.

**Comment by iowillhoit** [comment]
Hey @jclark-dot-org, the CLI team does not own this plugin/command. I found an existing issue here https://github.com/salesforcecli/plugin-lightning-dev/issues/185 that looks the same as item # 2 above ^

A PR was just opened for this https://github.com/salesforcecli/plugin-lightning-dev/pull/206 so hopefully a fix will be published soon! If you have any more questions, open an Issue over on their repo.
