### ISSUE TITLE
"Cannot read properties of undefined" error in project retrieve start

### ISSUE THREAD

**Issue by poypoyan** [forcedotcom/cli#3078]
### Expected result
Just typing `sf project retrieve start` results in the error `TypeError: Cannot read properties of undefined (reading 'error')`.

### Actual result

No error or more informative error if there's any.

### System Information

```
CLI:
@salesforce/cli/2.63.7 win32-x64 node-v20.17.0

Plugin Version:
@oclif/plugin-autocomplete 3.2.6 (core)
@oclif/plugin-commands 4.1.3 (core)
@oclif/plugin-help 6.2.15 (core)
@oclif/plugin-not-found 3.2.22 (core)
@oclif/plugin-plugins 5.4.15 (core)
@oclif/plugin-search 1.2.12 (core)
@oclif/plugin-update 4.6.4 (core)
@oclif/plugin-version 2.2.15 (core)
@oclif/plugin-warn-if-update-available 3.1.19 (core)
@oclif/plugin-which 3.2.16 (core)
@salesforce/cli 2.63.7 (core)
apex 3.5.4 (core)
api 1.3.1 (core)
auth 3.6.68 (core)
data 3.7.1 (core)
deploy-retrieve 3.14.0 (core)
info 3.4.12 (core)
limits 3.3.33 (core)
marketplace 1.2.26 (core)
org 4.7.0 (core)
packaging 2.8.12 (core)
schema 3.3.36 (core)
settings 2.3.24 (core)
sobject 1.4.42 (core)
source 3.5.21 (core)
telemetry 3.6.16 (core)
templates 56.3.24 (core)
trust 3.7.34 (core)
user 3.5.33 (core)
```

```
SF ENV. VARS.
SF_AUTOUPDATE_DISABLE,true
SF_BINPATH,C:\Program Files\sf\bin\\sf.cmd
SF_DISABLE_AUTOUPDATE,true
SF_UPDATE_INSTRUCTIONS,Use "npm update --global @salesforce/cli" to update npm-based installations.
```

```
Windows: true
Shell: cmd.exe
Channel: stable
```
---
### Diagnostics
:white_check_mark: pass - salesforcedx plugin isn’t installed
:white_check_mark: pass - you don't have any linked plugins
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.yarnpkg.com
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org/
:white_check_mark: pass - using latest or latest-rc CLI version
:x: warn - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
:white_check_mark: pass - can access: https://appexchange.salesforce.com/services/data
:white_check_mark: pass - can access: https://test.salesforce.com
:white_check_mark: pass - can access: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64-buildmanifest
:white_check_mark: pass - [@salesforce/plugin-auth] CLI supports v2 crypto
:white_check_mark: pass - [@salesforce/plugin-auth] CLI using stable v1 crypto

**Comment by SoftCreatR** [comment]
I can confirm that.

**Comment by shetzel** [comment]
We will patch the current production version (2.63.7) and release candidate with the fix.  Thanks for reporting and apologies about the regression!

**Comment by iowillhoit** [comment]
These have been patched!
- `latest` `2.63.8`
- `latest-rc` `2.64.7`
