### ISSUE TITLE
sf package version create return Cannot read properties of undefined (reading 'success')

### ISSUE THREAD

**Issue by jesusmcantero** [forcedotcom/cli#3081]
### Summary
Every time I run the command sf package version create I got this error Cannot read properties of undefined (reading 'success'). I've tried multiple times changing parameters of the commands and installing sfdx. That command in other computer works with the same repository.
### Steps To Reproduce
Run the following command:
`sf package version create --package "test" \
--target-dev-hub dev_hub-ipfolio \
--installation-key-bypass \
--tag "$(git rev-parse HEAD)" \
-b "$(git rev-parse --abbrev-ref HEAD)" \
--skip-ancestor-check \
--skip-validation \
--verbose \
--wait 300 \
--json`
Will produce the error in the section Actual result

### Expected result
The command run successfully and the package version is created 

### Actual result
`{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'success')",
  "exitCode": 10,
  "context": "PackageVersionCreateCommand",
  "stack": "TypeError: Cannot read properties of undefined (reading 'success')\n    at SfCommandError.from (file:///Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@salesforce/sf-plugins-core/lib/SfCommandError.js:39:16)\n    at PackageVersionCreateCommand.catch (file:///Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:316:47)\n    at PackageVersionCreateCommand._run (/Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:306:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Config.runCommand (/Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:424:25)\n    at async run (/Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:95:16)\n    at async file:///Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/bin/run.js:15:1",
  "cause": "TypeError: Cannot read properties of undefined (reading 'success')\n    at PackageVersionCreate.packageVersionCreate (/Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@salesforce/packaging/lib/package/packageVersionCreate.js:572:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async PackageVersion.create (/Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@salesforce/packaging/lib/package/packageVersion.js:100:30)\n    at async PackageVersionCreateCommand.run (file:///Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@salesforce/plugin-packaging/lib/commands/package/version/create.js:217:24)\n    at async PackageVersionCreateCommand._run (/Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:302:22)\n    at async Config.runCommand (/Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:424:25)\n    at async run (/Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:95:16)\n    at async file:///Users/user/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli/bin/run.js:15:1",
  "warnings": [
    "Skipping validation suppresses errors that usually surface during package version creation. Instead, these errors surface at a later stage, such as installation or post-installation. If you encounter errors that are difficult to debug, retry package version creation without the --skip-validation parameter."
  ],
  "code": "10",
  "status": 10,
  "commandName": "PackageVersionCreateCommand"
}`

### System Information
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.63.8",
  "nodeVersion": "node-v20.9.0",
  "osVersion": "Darwin 23.6.0",
  "rootPath": "/Users/jesusmanuel.cantero/.nvm/versions/node/v20.9.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.6 (core)",
    "@oclif/plugin-commands 4.1.3 (core)",
    "@oclif/plugin-help 6.2.15 (core)",
    "@oclif/plugin-not-found 3.2.22 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.12 (core)",
    "@oclif/plugin-update 4.6.4 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.19 (core)",
    "@oclif/plugin-which 3.2.16 (core)",
    "@salesforce/cli 2.63.8 (core)",
    "apex 3.5.4 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.68 (core)",
    "data 3.7.1 (core)",
    "deploy-retrieve 3.15.3 (core)",
    "info 3.4.12 (core)",
    "limits 3.3.33 (core)",
    "marketplace 1.2.26 (core)",
    "org 4.7.0 (core)",
    "packaging 2.8.12 (core)",
    "schema 3.3.36 (core)",
    "settings 2.3.24 (core)",
    "sobject 1.4.42 (core)",
    "source 3.5.21 (core)",
    "telemetry 3.6.16 (core)",
    "templates 56.3.24 (core)",
    "trust 3.7.34 (core)",
    "user 3.5.33 (core)"
  ]
}

**Comment by jesusmcantero** [comment]
Similar issue occurs when running the command sf org create snapshot. Updating node.js to the lts and upgrading sfdx to the latest version didn't fix the issue.

**Comment by iowillhoit** [comment]
Hey @jesusmcantero, I am not seeing this with either command. Which makes me think it could be something with your installation. Could you please check to see if you have multiple versions of `sf` installed with `which -a sf`? 

It is also worth trying to completely uninstalling the CLI and reinstalling a fresh copy. https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm  

Note that even if you installed with `npm` some of the config directories at the top could still exist and need cleaned up.
