### ISSUE TITLE
Failed to retrieve metadata from connected salesforce sandbox

### ISSUE THREAD

**Issue by jhomannc-qic** [forcedotcom/cli#3082]
Hi, i am receiving error when i attempt to retrieve metadate from connected salesforce sandbox.

Error msg: Failed to retrieve metadata. Status: FAILED Message: RangeError Maximum call stack size exceeded
‌
![image](https://github.com/user-attachments/assets/59a5ba61-192f-4cee-8722-331dd79d227b)

Illuminated Cloud 2 Plugin version: v2.3.3.5

Webstorm Version: 2024.1.5

salesforce/cli/2.36.8 win32-x64

node-v23.0.0

 "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.63.8",
  "nodeVersion": "node-v23.0.0",
  "osVersion": "Windows_NT 10.0.22631",
  "rootPath": "C:\\Users\\jhomannc\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "powershell",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.6 (core)",
    "@oclif/plugin-commands 4.1.3 (core)",
    "@oclif/plugin-help 6.2.15 (core)",
    "@oclif/plugin-not-found 3.2.22 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.12 (core)",
    "@oclif/plugin-update 4.6.4 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.19 (core)",
    "@oclif/plugin-which 3.2.16 (core)",
    "@salesforce/cli 2.63.8 (core)",
    "apex 3.5.4 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.68 (core)",
    "data 3.7.1 (core)",
    "deploy-retrieve 3.15.3 (core)",
    "info 3.4.12 (core)",
    "limits 3.3.33 (core)",
    "marketplace 1.2.26 (core)",
    "org 4.7.0 (core)",
    "packaging 2.8.12 (core)",
    "schema 3.3.36 (core)",
    "settings 2.3.24 (core)",
    "sobject 1.4.42 (core)",
    "source 3.5.21 (core)",
    "telemetry 3.6.16 (core)",
    "templates 56.3.24 (core)",
    "trust 3.7.34 (core)",
    "user 3.5.33 (core)"

**Comment by iowillhoit** [comment]
Hey @qic-carreon, a few questions for you:

- Does this also occur outside of VSCode? Do you see the same error if you run it in Powershell directly?
- Can you try updating to `2.63.9`? We had some memory issues in `2.63.8` that we patched yesterday
- Can you confirm that you don't have multiple versions of the cli installed? `where sf`
- We have noticed some issues with Node 23 on Windows in our tests. Does this still occur in Node 22 (LTS)?

Thanks!

**Comment by jhomannc-qic** [comment]
Thanks for your tips. I was able to resolve by downgrading CLI version.
