### ISSUE TITLE
"sf project deploy start" with "--source-dir" doesn't work as expected

### ISSUE THREAD

**Issue by mikhail-ivanov-tr** [forcedotcom/cli#3089]
### Summary
When I run the command `sf project deploy start --ignore-conflicts --concise --target-org <OrgAlias> --source-dir <PathToSourceSubDir>`, it deploys all components of the folder, instead of only changed components, every time I run the command. But if I remove the `--source-dir` parameter and run the command `sf project deploy start --ignore-conflicts --concise --target-org <OrgAlias>`, the source tracking works as expected.

### Steps To Reproduce

Run `sf project deploy start --ignore-conflicts --concise --target-org <OrgAlias> --source-dir <PathToSourceSubDir>`

### Expected result
Only changed components should be pushed to the ScratchOrg.

### Actual result
All components pushed to the ScratchOrg.

### Additional information
![image](https://github.com/user-attachments/assets/09affca2-883d-42d7-9625-1e1969f13c00)

### System Information
```
CLI:
@salesforce/cli/2.64.8 win32-x64 node-v20.17.0

Plugin Version:
@oclif/plugin-autocomplete 3.2.6 (core)
@oclif/plugin-commands 4.1.3 (core)
@oclif/plugin-help 6.2.16 (core)
@oclif/plugin-not-found 3.2.22 (core)
@oclif/plugin-plugins 5.4.15 (core)
@oclif/plugin-search 1.2.12 (core)
@oclif/plugin-update 4.6.6 (core)
@oclif/plugin-version 2.2.15 (core)
@oclif/plugin-warn-if-update-available 3.1.20 (core)
@oclif/plugin-which 3.2.16 (core)
@salesforce/cli 2.64.8 (core)
apex 3.5.4 (core)
api 1.3.1 (core)
auth 3.6.70 (core)
data 3.8.1 (core)
deploy-retrieve 3.13.1 (core)
info 3.4.13 (core)
lightning-dev 1.9.0 (user)
limits 3.3.36 (core)
marketplace 1.3.0 (core)
org 4.7.2 (core)
packaging 2.8.12 (core)
schema 3.3.37 (core)
settings 2.3.24 (core)
sobject 1.4.42 (core)
source 3.5.21 (core)
telemetry 3.6.17 (core)
templates 56.3.24 (core)
trust 3.7.35 (core)
user 3.5.33 (core)
```

```
SF ENV. VARS.
SF_AUTOUPDATE_DISABLE,true
SF_BINPATH,C:\Users\Mikhail\AppData\Local\sf\client\bin\sf
SF_DISABLE_AUTOUPDATE,true
SF_UPDATE_INSTRUCTIONS,Use "npm update --global @salesforce/cli" to update npm-based installations.
```

```
Windows: true
Shell: powershell
Channel: stable
```
---
### Diagnostics
:white_check_mark: pass - salesforcedx plugin isn’t installed
:white_check_mark: pass - you don't have any linked plugins
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.yarnpkg.com
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org/
:white_check_mark: pass - using latest or latest-rc CLI version
:white_check_mark: pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
:white_check_mark: pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches default target org max apiVersion
:white_check_mark: pass - can access: https://test.salesforce.com
:white_check_mark: pass - can access: https://appexchange.salesforce.com/services/data
:white_check_mark: pass - can access: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64-buildmanifest
:white_check_mark: pass - [@salesforce/plugin-auth] CLI supports v2 crypto
:white_check_mark: pass - [@salesforce/plugin-auth] CLI using stable v1 crypto

**Comment by cristiand391** [comment]
hey 👋🏼 

This is working as designed, you only get local changes to deploy if you don't specify any of the following flags:
```
--source-dir
--manifest
--metadata
```
passing any of these 3 flags will get you all components inside the folder/manifest/metadata specifier.

https://github.com/salesforcecli/plugin-deploy-retrieve/blob/9edb1e5fa0de1e3ee486ba766d01b2a87bced4fb/src/utils/deploy.ts#L78
