### ISSUE TITLE
sfdx package creation commands are not running 

### ISSUE THREAD

**Issue by shaliniv66** [forcedotcom/cli#3091]
Run-sf package version create --package "yext" --installation-key “pass123”  --definition-file config/default-project-scratch-def.json --code-coverage --wait 20
Error:Installing plugin packaging... -
error An unexpected error occurred: "https://registry.yarnpkg.com/@salesforce%2fplugin-packaging: self-signed certificate 
Installing plugin packaging... failed
    JitPluginInstallError: Could not install @salesforce/plugin-packaging
    Code: JitPluginInstallError

Tried the steps in -https://github.com/forcedotcom/cli/issues/2540 but still getting the above error.

**Comment by shaliniv66** [comment]
Sorry,
{
  "cliVersion": "@salesforce/cli/1.86.7-legacy.0",
  "architecture": "win32-x64",
  "nodeVersion": "node-v18.15.0",
  "osVersion": "Windows_NT 10.0.22631",
  "shell": "cmd.exe",
  "rootPath": "C:\\Users\\shalini.varadati\\AppData\\Local\\sfdx\\client\\7.209.6-8ba3197\\sf",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 2.3.1 (core)",
    "@oclif/plugin-commands 2.2.17 (core)",
    "@oclif/plugin-help 5.2.11 (core)",
    "@oclif/plugin-not-found 2.3.26 (core)",
    "@oclif/plugin-plugins 3.1.6 (core)",
    "@oclif/plugin-search 0.0.18 (core)",
    "@oclif/plugin-update 3.1.22 (core)",
    "@oclif/plugin-version 1.3.6 (core)",
    "@oclif/plugin-warn-if-update-available 2.0.41 (core)",
    "@oclif/plugin-which 2.2.22 (core)",
    "@salesforce/cli 1.86.7-legacy.0 (core)",
    "apex 2.3.4 (core)",
    "auth 2.8.4 (core)",
    "data 2.4.5 (core)",
    "deploy-retrieve 1.13.5 (core)",
    "info 2.6.30 (core)",
    "limits 2.3.23 (core)",
    "login 1.2.15 (core)",
    "org 2.9.19 (core)",
    "schema 2.3.17 (core)",
    "settings 1.4.17 (core)",
    "sobject 0.1.32 (core)",
    "source 2.10.22 (core)",
    "telemetry 2.2.1 (core)",
    "templates 55.5.2 (core)",
    "trust 2.4.27 (core)",
    "user 2.3.20 (core)",
    "aap-dx 1.0.0 (link) C:\\Users\\shalini.varadati\\Documents\\rel10"
  ]
}
Tried the above steps still getting error:Installing plugin packaging... -
error An unexpected error occurred: "https://registry.yarnpkg.com/@salesforce%2fplugin-packaging: self-signed certificate 
Installing plugin packaging... failed
    JitPluginInstallError: Could

**Comment by shetzel** [comment]
You should completely uninstall your current sfdx/sf installations with these instructions: 
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

Then install the latest version of the CLI:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_windows
