### ISSUE TITLE
Json Parse Error on Authorizing a Dev Hub Org

### ISSUE THREAD

**Issue by biswajith-s-pso-maxval** [forcedotcom/cli#3092]
### Expected result
Trying to add/authorize a DevHub org

### Actual result
but getting Json Parse Error after filling in UserName and password

### Additional information
![JsonParseError](https://github.com/user-attachments/assets/7816fbeb-a58e-40a4-9af3-38765085211b)

### System Information

```
CLI:
@salesforce/cli/2.64.8 win32-x64 node-v20.17.0

Plugin Version:
@oclif/plugin-autocomplete 3.2.6 (core)
@oclif/plugin-commands 4.1.3 (core)
@oclif/plugin-help 6.2.16 (core)
@oclif/plugin-not-found 3.2.22 (core)
@oclif/plugin-plugins 5.4.15 (core)
@oclif/plugin-search 1.2.12 (core)
@oclif/plugin-update 4.6.6 (core)
@oclif/plugin-version 2.2.15 (core)
@oclif/plugin-warn-if-update-available 3.1.20 (core)
@oclif/plugin-which 3.2.16 (core)
@salesforce/cli 2.64.8 (core)
apex 3.5.4 (core)
api 1.3.1 (core)
auth 3.6.70 (core)
data 3.8.1 (core)
deploy-retrieve 3.13.1 (core)
info 3.4.13 (core)
lightning-dev 1.9.0 (user)
limits 3.3.36 (core)
marketplace 1.3.0 (core)
org 4.7.2 (core)
packaging 2.9.0 (user)
schema 3.3.37 (core)
settings 2.3.24 (core)
sobject 1.4.42 (core)
source 3.5.21 (core)
telemetry 3.6.17 (core)
templates 56.3.24 (core)
trust 3.7.35 (core)
user 3.5.33 (core)
sfdmu 4.36.7 (user)
sfdx-essentials 2.12.0 (user)
sfdx-git-delta 5.49.0 (user)
sfdx-hardis 5.5.0 (user)
texei-sfdx-plugin 2.8.1 (user)
```

```
SF ENV. VARS.
SF_AUTOUPDATE_DISABLE,true
SF_BINPATH,C:\Users\biswajith.s_maxval\AppData\Local\sf\client\bin\sf
SF_DISABLE_AUTOUPDATE,true
SF_UPDATE_INSTRUCTIONS,Use "npm update --global @salesforce/cli" to update npm-based installations.
```

```
Windows: true
Shell: powershell
Channel: stable
```
---
### Diagnostics
:white_check_mark: pass - salesforcedx plugin isn’t installed
:white_check_mark: pass - you don't have any linked plugins
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.yarnpkg.com
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org/
:white_check_mark: pass - can access: https://appexchange.salesforce.com/services/data
:white_check_mark: pass - can access: https://test.salesforce.com
:white_check_mark: pass - can access: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64-buildmanifest
:x: fail - [@salesforce/plugin-auth] CLI supports v2 crypto
:white_check_mark: pass - [@salesforce/plugin-auth] CLI using stable v1 crypto
:white_check_mark: pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
:white_check_mark: pass - using latest or latest-rc CLI version

**Comment by biswajith-s-pso-maxval** [comment]
In the terminal it shows the following:
Error (1): Unexpected token 'NUL' , "NULNULNULNULNULNUL"... is not valid JSON

One weird observation for me since I am new, when I copy paster the above message, it only comes till:
Error (1): Unexpected token '
, so I had to type the remaining part inside the quotes

**Comment by cristiand391** [comment]
I'm not able to repro with `org login web`, a few questions:

1. are you able to repro the issue with a different hub/org?
2. was it working on a previous `sf` version on your machine?
3. what's the exact command you are running?

**Comment by biswajith-s-pso-maxval** [comment]
Hi Team,
After complete uninstallaion of sfsx cli, and all associated temporary
userdata files, removing environment variables, and then reinstalling it,
it is working now.
