### ISSUE TITLE
 sfdx force:source:retrieve -m ManagedContentType fail

### ISSUE THREAD

**Issue by cerbaire** [forcedotcom/cli#310]
### Summary

I'm trying to retrieve source for ManagedContentType metadata

### Steps To Reproduce:

1. sfdx force:source:retrieve -m ManagedContentType -u 00D5J...ffSV
ERROR running force:source:retrieve:  Cannot read property 'metadataName' of undefined

### Expected result

Expect the metadata to be retrieve in the source folder

### Actual result

ERROR running force:source:retrieve:  Cannot read property 'metadataName' of undefined

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**
sfdx-cli/7.46.1-3d2451fad8 win32-x64 node-v10.15.3

**SFDX plugin Version**
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.0 (core)
generator 1.1.2 (core)
salesforcedx 48.1.2
├─ salesforcedx-templates 48.1.0
└─ salesforce-alm 48.1.0

sfdx-cli 7.46.1 (core)

**OS and version**:
Windows 10 1909

**Comment by shetzel** [comment]
This is the same issue as https://github.com/forcedotcom/cli/issues/151.  Please follow that thread for updates.

**Comment by rvwatch** [comment]
FYI, I'm also taking a look at this type, but as of now, it is NOT supported by Source Tracking. Only MDAPI. 

https://developer.salesforce.com/docs/metadata-coverage/48
