### ISSUE TITLE
sf org list does not list all scratch orgs on newly refreshed windows

### ISSUE THREAD

**Issue by andy-nagare** [forcedotcom/cli#3102]
### Summary
sf org list does not show all scratch orgs on newly installed computer even though DevHub is set.

### Steps To Reproduce
1. Have a DevHub
2. Create an Active Scratch Org for 7 days
4. Go to a new computer or re-install windows to completely remove VSCode and history
5. Install CLI
6. Install JDK 21 from Oracle
7. Install VSCode
8. Install Salesforce Extension Pack
9. Set JDK path
10. In VSCode terminal, run sf org login web --set-default-dev-hub --alias [YourDevHub]
11. sf org list ( and tried sf org list --clean, --skip-connection-status --all )
14. Try on another computer that has never used VSCode and CLI before, repeat the steps above

### Expected result
It should list the active scratch orgs that are currently linked to the default active DevHub

### Actual result
It does not list ANY active scratch orgs that are currently linked to the default active DevHub; it only shows the DevHub itself.

{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.65.8",
  "nodeVersion": "node-v20.18.0",
  "osVersion": "Windows_NT 10.0.22631",
  "rootPath": "C:\\Program Files\\sf\\client",
  "shell": "powershell",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.7 (core)",
    "@oclif/plugin-commands 4.1.5 (core)",
    "@oclif/plugin-help 6.2.16 (core)",
    "@oclif/plugin-not-found 3.2.24 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.13 (core)",
    "@oclif/plugin-update 4.6.8 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.20 (core)",
    "@oclif/plugin-which 3.2.16 (core)",
    "@salesforce/cli 2.65.8 (core)",
    "apex 3.5.5 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.70 (core)",
    "data 3.9.0 (core)",
    "deploy-retrieve 3.15.4 (core)",
    "info 3.4.15 (core)",
    "limits 3.3.37 (core)",
    "marketplace 1.3.2 (core)",
    "org 5.0.2 (core)",
    "packaging 2.8.12 (core)",
    "schema 3.3.39 (core)",
    "settings 2.4.2 (core)",
    "sobject 1.4.44 (core)",
    "telemetry 3.6.18 (core)",
    "templates 56.3.26 (core)",
    "trust 3.7.38 (core)",
    "user 3.6.0 (core)"
  ]
}

**Comment by cristiand391** [comment]
this is working as designed, `sf org list` only shows orgs are authenticated to.

**Comment by andy-nagare** [comment]
@cristiand391 

But in the situation that I described, how do developers resume authenticating the scratch org that they used to authenticated on the old machines?  Or if new developers need to continue the work on the scratch org that they never authenticated to, and the previous developer is now departed from the team, how do the new developers authenticate these scratch orgs, IF the scratch org was created with generated user without resetting password?

Also, I am the developer who is authenticated to use DevHub, so I thought sf org list should be able to check my permission to list the same scratch orgs that I can see in my DevHub Active Scratch Orgs.

So in the scenario above, how do we handle this?

**Comment by cristiand391** [comment]
@andy-nagare 

> But in the situation that I described, how do developers resume authenticating the scratch org that they used to authenticated on the old machines?

users should generate a password for it via `sf org generate password` and authenticate on the new machine with `sf org login web`.

> Or if new developers need to continue the work on the scratch org that they never authenticated to, and the previous developer is now departed from the team, how do the new developers authenticate these scratch orgs, IF the scratch org was created with generated user without resetting password?

Going from memory/docs, when we create a `ScratchOrgInfo` record we get a one-time auth code to authorize you when you run `sf org create scratch`. If you didn't reset/create a password for it I think you can't get the access to the org.

> Also, I am the developer who is authenticated to use DevHub, so I thought sf org list should be able to check my permission to list the same scratch orgs that I can see in my DevHub Active Scratch Orgs.
So in the scenario above, how do we handle this?

I think it's because the one-time code auth code that, even if you have access to the `ScratchOrgInfo` records in your hub, you wouldn't be able to authenticate to those scratch orgs witouth a password.
docs:
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_scratchorginfo.htm

simplified example of how it works (old blog post but I don't think much has changed):
https://jsforce.github.io/blog/posts/20170629-salesforce-dx-with-jsforce.html

I'll double check with my team next week to confirm.

**Comment by andy-nagare** [comment]
Thank you for your quick reply and thanks for closing the ticket.

> @andy-nagare
> 
> > But in the situation that I described, how do developers resume authenticating the scratch org that they used to authenticated on the old machines?
> 
> users should generate a password for it via `sf org generate password` and authenticate on the new machine with `sf org login web`.

> 
> > Or if new developers need to continue the work on the scratch org that they never authenticated to, and the previous developer is now departed from the team, how do the new developers authenticate these scratch orgs, IF the scratch org was created with generated user without resetting password?
> 
> Going from memory/docs, when we create a `ScratchOrgInfo` record we get a one-time auth code to authorize you when you run `sf org create scratch`. If you didn't reset/create a password for it I think you can't get the access to the org.
> 
> > Also, I am the developer who is authenticated to use DevHub, so I thought sf org list should be able to check my permission to list the same scratch orgs that I can see in my DevHub Active Scratch Orgs.
> > So in the scenario above, how do we handle this?
> 
> I think it's because the one-time code auth code that, even if you have access to the `ScratchOrgInfo` records in your hub, you wouldn't be able to authenticate to those scratch orgs witouth a password. docs: https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_scratchorginfo.htm
> 
> simplified example of how it works (old blog post but I don't think much has changed): https://jsforce.github.io/blog/posts/20170629-salesforce-dx-with-jsforce.html
> 
> I'll double check with my team next week to confirm.
