### ISSUE TITLE
Deploying changes to  ContextDefinition does not update ContextDefinitionVersion

### ISSUE THREAD

**Issue by robertwheelerprodly** [forcedotcom/cli#3105]
### Expected result

Trying to deploy changes for a ContextDefinition type mainly the ContextDefintionVersion portion.  

### Actual result

Deploying to a sandbox it shows that the file has successfully been deployed with a status of changed.  When pulling the file from the sandbox the result shows changed and when opening the file it still shows the original version as if the deployment was not successful.  If the change is to the ContextDefinition then it will update, but if a change to the ContextDefinitionVersion is not changed.  

### Additional information

![Screenshot 2024-11-11 at 5 15 15 PM](https://github.com/user-attachments/assets/64f68343-1a26-48f6-abba-7600dd16b686)
![Screenshot 2024-11-11 at 5 16 10 PM](https://github.com/user-attachments/assets/0ff0171f-07b9-4f71-95b4-03dff8db7500)
![Screenshot 2024-11-11 at 5 25 19 PM](https://github.com/user-attachments/assets/7b31aeb9-81a2-4b9c-bec1-a187eeafa261)

### System Information

```
CLI:
@salesforce/cli/2.65.8 darwin-x64 node-v20.17.0

Plugin Version:
@oclif/plugin-autocomplete 3.2.7 (core)
@oclif/plugin-commands 4.1.5 (core)
@oclif/plugin-help 6.2.16 (core)
@oclif/plugin-not-found 3.2.24 (core)
@oclif/plugin-plugins 5.4.15 (core)
@oclif/plugin-search 1.2.13 (core)
@oclif/plugin-update 4.6.8 (core)
@oclif/plugin-version 2.2.15 (core)
@oclif/plugin-warn-if-update-available 3.1.20 (core)
@oclif/plugin-which 3.2.16 (core)
@salesforce/cli 2.65.8 (core)
apex 3.5.5 (core)
api 1.3.1 (core)
auth 3.6.70 (core)
data 3.9.0 (core)
deploy-retrieve 3.15.4 (core)
env 3.0.33 (user)
functions 1.23.0 (user)
info 3.4.15 (core)
limits 3.3.37 (core)
marketplace 1.3.2 (core)
org 5.0.2 (core)
packaging 2.8.12 (core)
schema 3.3.39 (core)
settings 2.4.2 (core)
signups 2.5.23 (user)
sobject 1.4.44 (core)
telemetry 3.6.18 (core)
templates 56.3.26 (core)
trust 3.7.38 (core)
user 3.6.0 (core)
sfdx-plugin-source-read 1.3.0 (user)
```

```
SF ENV. VARS.
SF_BINPATH,/Users/rwheeler/.local/share/sf/client/bin/sf
SF_AUTOUPDATE_DISABLE,true
SF_DISABLE_AUTOUPDATE,true
SF_UPDATE_INSTRUCTIONS,Use "npm update --global @salesforce/cli" to update npm-based installations.
```

```
Windows: false
Shell: zsh
Channel: stable
```
---
### Diagnostics
:white_check_mark: pass - salesforcedx plugin isn’t installed
:white_check_mark: pass - you don't have any linked plugins
:x: unknown - using latest or latest-rc CLI version
:white_check_mark: pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
:white_check_mark: pass - can access: https://test.salesforce.com
:white_check_mark: pass - can access: https://appexchange.salesforce.com/services/data
:white_check_mark: pass - can access: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64-buildmanifest

**Comment by robertwheelerprodly** [comment]
Is there anything else I need to add here, this is a problem for me since trying to deploy a newer version of the ContextDefinitionVersion

**Comment by WillieRuemmele** [comment]
hi @robertwheelerprodly - could you provide some steps to create the ContextDefinition + CDV, and any perms, settings, that are required to create an org with it?

**Comment by robertwheelerprodly** [comment]
I believe it is part of Revenue Cloud, which I don't think I can just turn
on.  We are an ISV so I have an org that has it enabled would providing
access to that organization be helpful?

We have a template org provided by Salesforce to create these environments.  We are just copying the default ContextDefinition files that are created from that template.  If I really need to provide steps I would need to get those steps from anther individual.  I can provide a copy of one of the xml files if that is necessary. I am looking forward to response.

**Comment by robertwheelerprodly** [comment]
I have added an update if I am going down the wrong path, please let me
know.

**Comment by robertwheelerprodly** [comment]
I have tried creating a scratch developer org and enterprise org.  I look
for the Feature of Revenue Lifecycle Management and it is not available.  I
found https://help.salesforce.com/s/articleView?id=001176943&type=1 it
requires a Revenue Lifecycle Management license.  I cannot create an
instance without intervention from Salesforce support.

**Comment by WillieRuemmele** [comment]
we'll try to get an org setup with this license, but it may take some time

**Comment by robertwheelerprodly** [comment]
I understand it is a special case, so thank you for the response and update.  Also if there is any other information or anything else I could possibly assist with please let me know.

**Comment by shetzel** [comment]
Hi @robertwheelerprodly - the quickest way to a solution for this problem is to open a support case.  This is a server side problem versus a CLI issue.  Tell the Support rep that the owning server side team is called, "CS - Harmony" in the Context Service cloud.  They will open an investigation for that team to triage and fix.

**Comment by robertwheelerprodly** [comment]
Thank you for all help in regards to this issue.
