### ISSUE TITLE
Error (InvalidIdLengthError): Parsing --job-id

### ISSUE THREAD

**Issue by Faizahamed-dev** [forcedotcom/cli#3106]
i am using the command for deployment status , i tried with two command still i am getting status_output=$(sf project deploy report -i "$deploy_id" -u "${SALESFORCE_USERNAME}" --wait 0 --json) as well status_output=$(sf project deploy report -i "$deploy_id" -u "${SALESFORCE_USERNAME}" --wait 0 --use-most-recent). i am getting an error Error (InvalidIdLengthError): Parsing --job-id The id must be 15 or 18 characters. See more help with --help . i am using salesforce/cli/2.67.4 .pls tell me how to fix

**Comment by Faizahamed-dev** [comment]
output below and i am using sf version with latest 
{
  "name": "InvalidIdLengthError",
  "message": "Parsing --job-id \n\tThe id must be 15 or 18 characters.\nSee more help with --help",
  "exitCode": 2,
  "context": "DeployMetadataReport",
  "stack": "InvalidIdLengthError: Parsing --job-id \n\tThe id must be 15 or 18 characters.\nSee more help with --help\n    at SfCommandError.from (file:///usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/sf-plugins-core/lib/SfCommandError.js:39:16)\n    at DeployMetadataReport.catch (file:///usr/local/lib/node_modules/@salesforce/cli/node_modules/@salesforce/sf-plugins-core/lib/sfCommand.js:316:47)\n    at DeployMetadataReport._run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/command.js:306:29)\n    at async Config.runCommand (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/config/config.js:425:25)\n    at async run (/usr/local/lib/node_modules/@salesforce/cli/node_modules/@oclif/core/lib/main.js:95:16)\n    at async file:///usr/local/lib/node_modules/@salesforce/cli/bin/run.js:15:1",
  "cause": "undefined",
  "warnings": [],
  "code": "InvalidIdLengthError",
  "status": 2,
  "commandName": "DeployMetadataReport"
}

**Comment by cristiand391** [comment]
are you able to print the deploy ID and see if it's 15/18-char?
