### ISSUE TITLE
Deployment error table is missing Metadata type. Inconsistent naming of table headers.

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/cli#3110]
### Summary
When I get error in SF CLI for metadata verification then it is inconsistent with what I can see in SF gui.
<img width="753" alt="2024-11-13_14h46_33" src="https://github.com/user-attachments/assets/5d10556f-681b-4d1e-8cbd-f436b24a2c6e">

In example above seeing only error in CLI I am confused what it is about as object was already deleted.
When I check for the error in deployment verification status in GUI I see additional "Type" column with value "Tab" now I understand that there is something wrong with tab metadata related to deleted object. 

Please add "Metadata Type" column in CLI so it is clear what error is about. 
Also Line and Column value is missing in this example. I know that it might be not relevant in case of the tab metadata but still it is inconsistent with GUI. 

### Steps To Reproduce
Unable to provide exact steps. In my case I had and object and custom tab. Then object was deleted.

### Expected result
As developer which is using mainly VSCode and CLI I see clear error message in CLI so I know what it is about.

### Actual result
I am missing information about which metadata type error is shown and where (line and column).

### System Information

```json
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.65.8",
  "nodeVersion": "node-v22.11.0",
  "osVersion": "Windows_NT 10.0.22631",
  "rootPath": "C:\\Users\\pwozn\\AppData\\Roaming\\npm\\node_modules\\@salesforce\\cli",
  "shell": "powershell",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.7 (core)",
    "@oclif/plugin-commands 4.1.5 (core)",
    "@oclif/plugin-help 6.2.16 (core)",
    "@oclif/plugin-not-found 3.2.24 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.13 (core)",
    "@oclif/plugin-update 4.6.8 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.20 (core)",
    "@oclif/plugin-which 3.2.16 (core)",
    "@salesforce/cli 2.65.8 (core)",
    "apex 3.5.5 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.70 (core)",
    "data 3.9.0 (core)",
    "deploy-retrieve 3.15.4 (core)",
    "info 3.4.15 (core)",
    "limits 3.3.37 (core)",
    "marketplace 1.3.2 (core)",
    "org 5.0.2 (core)",
    "packaging 2.8.12 (core)",
    "schema 3.3.39 (core)",
    "settings 2.4.2 (core)",
    "sobject 1.4.44 (core)",
    "telemetry 3.6.18 (core)",
    "templates 56.3.26 (core)",
    "trust 3.7.38 (core)",
    "user 3.6.0 (core)",
    "@salesforce/sfdx-scanner 4.7.0 (user) published 14 days ago (Tue Oct 29 2024)",
    "sfdmu 4.36.7 (user) published 14 days ago (Tue Oct 29 2024)",
    "sfdx-git-delta 5.49.3 (user) published 1 days ago (Tue Nov 12 2024)"
  ]
}
```

**Comment by WillieRuemmele** [comment]
@PawelWozniak - I put up a PR to repurpose the `TYPE` column, to show the metadata type, as for the missing line/column info, that isn't returned for every metadata type / error in the API 😦

**Comment by PawelWozniak** [comment]
@WillieRuemmele Thank you for your work, that will help all developers.

**Comment by WillieRuemmele** [comment]
This has been released into `latest` this week 🚀
