### ISSUE TITLE
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.dir

### ISSUE THREAD

**Issue by THLG-MGP** [forcedotcom/cli#3111]
### System Information

```
CLI:
@salesforce/cli/2.66.7 win32-x64 node-v22.11.0

Plugin Version:
@oclif/plugin-autocomplete 3.2.8 (core)
@oclif/plugin-commands 4.1.7 (core)
@oclif/plugin-help 6.2.16 (core)
@oclif/plugin-not-found 3.2.25 (core)
@oclif/plugin-plugins 5.4.15 (core)
@oclif/plugin-search 1.2.14 (core)
@oclif/plugin-update 4.6.10 (core)
@oclif/plugin-version 2.2.15 (core)
@oclif/plugin-warn-if-update-available 3.1.21 (core)
@oclif/plugin-which 3.2.17 (core)
@salesforce/cli 2.66.7 (core)
apex 3.5.6 (core)
api 1.3.1 (core)
auth 3.6.72 (core)
data 3.11.2 (core)
deploy-retrieve 3.15.8 (core)
info 3.4.17 (core)
limits 3.3.38 (core)
marketplace 1.3.4 (core)
org 5.1.2 (core)
packaging 2.9.0 (core)
schema 3.3.40 (core)
settings 2.4.4 (core)
sobject 1.4.44 (core)
telemetry 3.6.19 (core)
templates 56.3.28 (core)
trust 3.7.39 (core)
user 3.6.2 (core)
aura-helper-sf 1.3.2 (user)
```

```
SF ENV. VARS.
SF_ACCESS_TOKEN,00D24000000JOOb!AQEAQFRbmmjk_EQHU6Q7uMrG_d8Y9ZRar8cRxtNHyw9bbVnhccS0O4v9VX4fjaEx8BmXpWJp9Rkjn7VwlE64AvtV3hLAa.3L
SF_AUTOUPDATE_DISABLE,true
SF_BINPATH,C:\Users\ThierryLeGot\AppData\Local\sf\client\bin\sf
SF_DISABLE_AUTOUPDATE,true
SF_UPDATE_INSTRUCTIONS,Use "npm update --global @salesforce/cli" to update npm-based installations.
```

```
Windows: true
Shell: powershell
Channel: stable
```
---
### Diagnostics
:white_check_mark: pass - salesforcedx plugin isn’t installed
:white_check_mark: pass - you don't have any linked plugins
:white_check_mark: pass - can access: https://test.salesforce.com
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.yarnpkg.com
:white_check_mark: pass - [@salesforce/plugin-trust] can ping: https://registry.npmjs.org/
:white_check_mark: pass - using latest or latest-rc CLI version
:white_check_mark: pass - can access: https://appexchange.salesforce.com/services/data
:white_check_mark: pass - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches apiVersion
:x: warn - [@salesforce/plugin-deploy-retrieve] sourceApiVersion matches default target org max apiVersion
:white_check_mark: pass - can access: https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-win32-x64-buildmanifest
:x: fail - [@salesforce/plugin-auth] CLI supports v2 crypto
:white_check_mark: pass - [@salesforce/plugin-auth] CLI using stable v1 crypto

**Comment by THLG-MGP** [comment]
The context: 
I updated Salesforce CLI this morning, and since, I have this error
[DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.dir

Previously, my Salesforce CLI version was @salesforce/cli/2.65.8 win32-x64 node-v20.17.0

Now the version is : @salesforce/cli/2.66.7 win32-x64 node-v22.11.0
It seems this version was released on November 13th (yesterday).

Can you help me to bypass this error ?
FYI, I'm not a "node" user, just a powershell guy that uses Salesforce CLI

Many thanks.
Kind Regards.

**Comment by cristiand391** [comment]
sorry, closing as dup of https://github.com/forcedotcom/cli/issues/2535
It's just a warning, it's safe to ignore for now.

In pwsh you can remove it by running this:
```pwsh
$env:NODE_OPTIONS='--disable-warning=DEP0040'
```

We'll disable the warning on the CLI-level and patch the release.

**Comment by THLG-MGP** [comment]
Hi Cristian,
Many thanks for the tip.

Have a nice day.
Kind Regards.
