### ISSUE TITLE
Validation rule error messagess containing line breaks get "translated" with two whitespaces on deployment

### ISSUE THREAD

**Issue by svenfinitiv** [forcedotcom/cli#3114]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
We have some validation rules with line breaks, retrieve and deploy work so far, but when a flow hits this validation and should show the error, only an empty text is displayed. The default record page shows the original error message.

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

Given:
* Translations enabled
* A validation rule with a multi line error message
* No extra tranlsation for the given error message
* A flow using an UpdateRecord that violates the constraint of the validation rule and shows Flow.FaultMessage on an error screen
* All is deployed to another org using sf project retrieve start and sf project deploy start

Steps:
* Run the flow and check the output of the FaulMessage
* Edit the record using the default edit page and check the error message

> [!TIP]
> use `sf doctor --create-issue` to automatically fill the required information

### Expected result
* The validation rule, the flow and the translation are properly part of the source package
* After deployment the translation workbench does not show any translation for the error message
* Both the flow and the standard edit page show the correct error message

### Actual result
* The object translation metadata file contains whitespaces surrounding the comment with the master error message
* The translation workbench shows two whitespaces when editing the translation of the error message
* The translation cannot be saved
* The flow shows two whitespaces instead of the error message

### System Information
```json
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.66.7",
  "nodeVersion": "node-v22.11.0",
  "osVersion": "Darwin 24.0.0",
  "rootPath": "/Users/svenkretschmann/.local/share/sf/client/2.66.7-5567872",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.8 (core)",
    "@oclif/plugin-commands 4.1.7 (core)",
    "@oclif/plugin-help 6.2.16 (core)",
    "@oclif/plugin-not-found 3.2.25 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.14 (core)",
    "@oclif/plugin-update 4.6.10 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.21 (core)",
    "@oclif/plugin-which 3.2.17 (core)",
    "@salesforce/cli 2.66.7 (core)",
    "apex 3.5.6 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.72 (core)",
    "data 3.11.2 (core)",
    "deploy-retrieve 3.15.8 (core)",
    "info 3.4.17 (core)",
    "limits 3.3.38 (core)",
    "marketplace 1.3.4 (core)",
    "org 5.1.2 (core)",
    "packaging 1.26.4 (user) published 398 days ago (Mon Oct 16 2023) (latest is 2.9.0)",
    "schema 3.3.40 (core)",
    "settings 2.4.4 (core)",
    "signups 2.6.1 (user) published 16 days ago (Sat Nov 02 2024) (latest is 2.6.3)",
    "sobject 1.4.44 (core)",
    "telemetry 3.6.19 (core)",
    "templates 56.3.28 (core)",
    "trust 3.7.39 (core)",
    "user 3.6.2 (core)",
    "@salesforce/sfdx-plugin-lwc-test 1.2.1 (user) published 44 days ago (Fri Oct 04 2024)",
    "@salesforce/sfdx-scanner 4.7.0 (user) published 20 days ago (Tue Oct 29 2024)"
  ]
}
```

**Comment by WillieRuemmele** [comment]
hi @svenfinitiv - is this an error in the org, or with the CLI? It sounds like you're able to deploy these translations (or lack of) and error message files ok, but when they're seen in the org, in a flow, they're not displayed correctly?

If that's true, what is the difference between your local translation file, and what is written by a `project retrieve start` of that file?

**Comment by svenfinitiv** [comment]
Hi @WillieRuemmele,

there is no issue with the CLI per se, as we can retrieve and deploy the "empty" translations, but when using these in the org, the symptoms occur.

Regarding the differences:

When retrieving from the source sandbox, we get this result, take note of the line breaks before and after the comment:

```
    <validationRules>
        <errorMessage>
            <!-- This is a multiline error message
The seconde line includes some details. -->
        </errorMessage>
        <name>RequireImportanFieldToBeSet</name>
    </validationRules>
```

After deploying to the target sandbox and reretrieving from there, we get this result:

```
    <validationRules>
        <errorMessage></errorMessage>
        <name>RequireImportanFieldToBeSet</name>
    </validationRules>
```

**Comment by WillieRuemmele** [comment]
@svenfinitiv - I would suggest raising a case directly with Salesforce
