### ISSUE TITLE
sf org login command for authentication always comes with a deprecation waring in GitLab pipeline script

### ISSUE THREAD

**Issue by shabu74** [forcedotcom/cli#3121]
### Summary
Salesforce CLI command for authentication always comes with a deprecation waring "Closing a FileHandle object on garbage collection is deprecated. Please close FileHandle objects explicitly using FileHandle.prototype.close(). In the future, an error will be thrown if a file descriptor is closed during garbage collection." in GitLab pipeline script

### Steps To Reproduce

> **IMPORTANT**
Execute sf org login sfdx-url command

### Expected result
Successful authentication with out any warning

### Actual result
Successful authentication, but with a deprecation warning and other warnings too

### Additional information
![image](https://github.com/user-attachments/assets/38a069df-2755-42fe-919d-694e5b608dab)

### System Information

```json
{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.66.7",
  "nodeVersion": "node-v22.11.0",
  "osVersion": "Linux 6.8.0-1017-aws",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.8 (core)",
    "@oclif/plugin-commands 4.1.7 (core)",
    "@oclif/plugin-help 6.2.16 (core)",
    "@oclif/plugin-not-found 3.2.25 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.14 (core)",
    "@oclif/plugin-update 4.6.10 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.21 (core)",
    "@oclif/plugin-which 3.2.17 (core)",
    "@salesforce/cli 2.66.7 (core)",
    "apex 3.5.6 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.72 (core)",
    "data 3.11.2 (core)",
    "deploy-retrieve 3.15.8 (core)",
    "info 3.4.17 (core)",
    "limits 3.3.38 (core)",
    "marketplace 1.3.4 (core)",
    "org 5.1.2 (core)",
    "packaging 2.9.0 (core)",
    "schema 3.3.40 (core)",
    "settings 2.4.4 (core)",
    "sobject 1.4.44 (core)",
    "telemetry 3.6.19 (core)",
    "templates [56](https://gitlab.service.nsw.gov.au/salesforce/caresnsw/-/jobs/11933380#L56).3.28 (core)",
    "trust 3.7.39 (core)",
    "user 3.6.2 (core)"
  ]
}
```
Initially I used node 19. I got only deprecation warning. As per your advice, I used node 22, I got other warnings too. Please don't suggest anything, if it is not working perfectly.

**Comment by mcarvin8** [comment]
Think you have the same issue I've been seeing in GitLab as well - https://github.com/forcedotcom/cli/issues/3094

I also saw the punycode deprecation warning once recently too, but not as often as the garbage collection one.

**Comment by shabu74** [comment]
Yes. I just saw your issue. It's the same issue.

**Comment by mcarvin8** [comment]
I have seen this punycode deprecation warning once in a sandbox repo but it was on the `sf project deploy start` command, not the `sf org login` command.

![image](https://github.com/user-attachments/assets/df301e12-ce27-4612-84c5-a6ea9841b1b0)

This one was weird to me since I've only seen this issue once with the same version of the CLI and we've had this CLI version for a month now in our pipeline builds. I'm assuming it may be related to `SF_USE_GENERIC_UNIX_KEYCHAIN` but I haven't seen that issue in our production repo.

```
```dockerfile
FROM artifacts.platform.avalara.io/docker/ubuntu

# Set Salesforce CLI Environment Variables 
# https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm
ENV SF_AUTOUPDATE_DISABLE=true \
    SF_USE_GENERIC_UNIX_KEYCHAIN=true \
    SF_DOMAIN_RETRY=300 \
    SF_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_CREATE=true \
    SF_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true \
    SF_DISABLE_DNS_CHECK=true \
    SF_DISABLE_SOURCE_MEMBER_POLLING=true \
    SF_HIDE_RELEASE_NOTES=true \
    SF_HIDE_RELEASE_NOTES_FOOTER=true \
    SF_SKIP_NEW_VERSION_CHECK=true \
    SF_CONTAINER_MODE=true \
    SF_CI_HEARTBEAT_FREQUENCY_MS=60000

# Install Salesforce CLI and other required software (git, python3, jq, curl, nodejs)
# Print Salesforce CLI version in format accepted for Salesforce CLI bugs on GitHub
RUN apt-get update && apt-get install -y curl jq git python3 && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/* && \
    npm install --global @salesforce/cli@2.65.8 && \
    sf version --verbose --json

```

**Comment by WillieRuemmele** [comment]
the `PUNYCODE` warnings are known, should be non-blocking, and we're working on removing that dependency from our tree... it just takes a while since it's a very low-level root dependency

**Comment by shabu74** [comment]
Hi @WillieRuemmele, I have created this ticket not to raise PUNYCODE warning. This ticket is for sf login command deprecation warning. So, why you have closed this as completed?

**Comment by cristiand391** [comment]
@shabu74 isn't this a duplicate of https://github.com/forcedotcom/cli/issues/3094?

I was able to repro it using the generic keychain implementation, we have a WI to track the fix ⬆️
