### ISSUE TITLE
project deploy command hooks

### ISSUE THREAD

**Issue by gitfish** [forcedotcom/cli#3122]
> **Note** 
> Before you submit your issue, make sure that:
> - You're using the latest version of Salesforce CLI.
> - You've searched both open and closed issues for related posts.
> - You've used the `doctor` command to diagnose common issues. 
> - You understand that GitHub Issues don't adhere to any agreement or SLA.
>   - If you require immediate assistance, use official channels such as Salesforce Customer Support.

### Summary
Project commands don't appear toe be triggering lifecycle hooks - e.g. `project deploy start` doesn't trigger the `predeploy` hook. Looking at the source from https://github.com/salesforcecli/plugin-deploy-retrieve it appears that these are only fired from the delete command. I just wanted to mostly check whether it's likely support will be added back in for these or just switch to an alternative approach (or whether one already exists).

### Steps To Reproduce

> **IMPORTANT**
> Provide a repository that's configured to reproduce the issue. If you are unable to provide a repo, please explain why not. The more info we have from the start, the faster we can resolve your issue.
> We may close your issue if you don't include proper instructions.
>
> - Generate a project with `sf project generate` or fork [dreamhouse-lwc](https://github.com/trailheadapps/dreamhouse-lwc).
> - Provide detailed step-by-step instructions on how to reproduce the issue.

- install a plugin that has a predeploy hook
- run `sf project deploy start`

> [!TIP]
> use `sf doctor --create-issue` to automatically fill the required information

### Expected result

predeploy hook runs

### Actual result

predeploy hook does not run

### System Information

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.66.7",
  "nodeVersion": "node-v20.12.2",
  "osVersion": "Darwin 24.1.0",
  "rootPath": "/Users/mfisher/npm/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.8 (core)",
    "@oclif/plugin-commands 4.1.7 (core)",
    "@oclif/plugin-help 6.2.16 (core)",
    "@oclif/plugin-not-found 3.2.25 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.14 (core)",
    "@oclif/plugin-update 4.6.10 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.21 (core)",
    "@oclif/plugin-which 3.2.17 (core)",
    "@salesforce/cli 2.66.7 (core)",
    "apex 3.5.6 (core)",
    "api 1.3.1 (core)",
    "auth 3.6.72 (core)",
    "data 3.11.2 (core)",
    "deploy-retrieve 3.15.8 (core)",
    "info 3.4.17 (core)",
    "limits 3.3.38 (core)",
    "marketplace 1.3.4 (core)",
    "org 5.1.2 (core)",
    "packaging 2.9.0 (core)",
    "schema 3.3.40 (core)",
    "settings 2.4.4 (core)",
    "sobject 1.4.44 (core)",
    "telemetry 3.6.19 (core)",
    "templates 56.3.28 (core)",
    "trust 3.7.39 (core)",
    "user 3.6.2 (core)"
  ]
}

```

**Comment by WillieRuemmele** [comment]
Hey @gitfish - we've moved hooks mostly into the [SDR](https://github.com/search?q=repo%3Aforcedotcom%2Fsource-deploy-retrieve+predeploy+language%3ATypeScript&type=code) library, you can search for the other hooks

**Comment by gitfish** [comment]
Cool - looks like they've just moved to a new hook name (with scoped prefix) - thanks for the pointer.

**Comment by tehnrd** [comment]
@gitfish Do you have an example of one of these predeploy hooks working? I can't seem to figure it out and documentation on hooks is a bit sparce.

**Comment by gitfish** [comment]
@tehnrd will try and put an example together for you when I get a sec.
