### ISSUE TITLE
Full Deployment is Triggered when using dotenv files instead of single file[Custom label]

### ISSUE THREAD

**Issue by pjha06** [forcedotcom/cli#3126]
when i run the below command to deploy customlabels it triggers full deployment of all components under force-app/main/default folder
dotenv -e .envINT -e .envQA sf project deploy start --target-org Whpnarcsint --source-dir force-app\main\default\labels\CustomLabels.labels-meta.xml

Please find attached ZIP file containing metadata where replacements will be done,sfdx-project.jsona nd .env files

[consolidatedfiles.zip](https://github.com/user-attachments/files/17845504/consolidatedfiles.zip)

Also if you could help me with some videos or materials to test the String replacements without actually doing deployment.

**Comment by pjha06** [comment]
Please find cli version details:{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.58.7",
  "nodeVersion": "node-v20.17.0",
  "osVersion": "Windows_NT 10.0.22631",
  "rootPath": "C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.58.7-ed27925",
  "shell": "powershell",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 25.5.3 (user) published 362 days ago (Sat Nov 25 2023)",
    "@oclif/plugin-autocomplete 3.2.2 (core)",
    "@oclif/plugin-commands 3.3.4 (user) published 194 days ago (Sat May 11 2024) (latest is 4.1.10)",
    "@oclif/plugin-help 5.2.17 (user) published 467 days ago (Sat Aug 12 2023) (latest is 6.2.18)",
    "@oclif/plugin-not-found 3.2.18 (core)",
    "@oclif/plugin-plugins 5.4.6 (core)",
    "@oclif/plugin-search 1.2.7 (core)",
    "@oclif/plugin-update 4.5.5 (core)",
    "@oclif/plugin-version 2.2.11 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.13 (core)",
    "@oclif/plugin-which 3.2.12 (core)",
    "@salesforce/cli 2.58.7 (core)",
    "apex 3.4.8 (core)",
    "api 1.2.1 (core)",
    "auth 3.6.54 (core)",
    "data 3.6.5 (core)",
    "deploy-retrieve 3.12.3 (core)",
    "info 3.4.3 (core)",
    "limits 3.3.29 (core)",
    "marketplace 1.2.25 (core)",
    "org 4.5.7 (core)",
    "packaging 1.22.1 (user) published 469 days ago (Thu Aug 10 2023) (latest is 2.9.3)",
    "schema 3.3.26 (core)",
    "settings 2.3.16 (core)",
    "signups 2.5.12 (user) published 81 days ago (Sun Sep 01 2024) (latest is 2.6.3)",
    "sobject 1.4.33 (core)",
    "source 3.5.18 (core)",
    "telemetry 3.6.10 (core)",
    "templates 56.3.17 (core)",
    "trust 3.7.27 (core)",
    "user 3.5.29 (core)",
    "@salesforce/sfdx-scanner 4.6.0 (user) published 57 days ago (Tue Sep 24 2024) (latest is 4.7.0)",
    "lightning-flow-scanner 2.34.0 (user) published 88 days ago (Sun Aug 25 2024) (latest is 2.36.0)",
    "sfdx-git-delta 5.49.0 (user) published 33 days ago (Sat Oct 19 2024) (latest is 5.49.4)"       
  ]
}

**Comment by pjha06** [comment]
{
  "architecture": "win32-x64",
  "cliVersion": "@salesforce/cli/2.67.7",
  "nodeVersion": "node-v22.11.0",
  "osVersion": "Windows_NT 10.0.22631",
  "rootPath": "C:\\Users\\Prabhatkumar_Jha\\AppData\\Local\\sf\\client\\2.67.7-3acb081",
  "shell": "powershell",
  "pluginVersions": [
    "@dxatscale/sfpowerscripts 25.5.3 (user) published 362 days ago (Sat Nov 25 2023)",
    "@oclif/plugin-autocomplete 3.2.8 (core)",
    "@oclif/plugin-commands 3.3.4 (user) published 194 days ago (Sat May 11 2024) (latest is 4.1.10)",
    "@oclif/plugin-help 5.2.17 (user) published 467 days ago (Sat Aug 12 2023) (latest is 6.2.18)",
    "@oclif/plugin-not-found 3.2.25 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.14 (core)",
    "@oclif/plugin-update 4.6.10 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.21 (core)",
    "@oclif/plugin-which 3.2.17 (core)",
    "@salesforce/cli 2.67.7 (core)",
    "apex 3.6.2 (core)",
    "api 1.3.2 (core)",
    "auth 3.6.73 (core)",
    "data 3.11.3 (core)",
    "deploy-retrieve 3.15.11 (core)",
    "info 3.4.18 (core)",
    "limits 3.3.39 (core)",
    "marketplace 1.3.4 (core)",
    "org 5.1.4 (core)",
    "packaging 1.22.1 (user) published 469 days ago (Thu Aug 10 2023) (latest is 2.9.3)",
    "schema 3.3.40 (core)",
    "settings 2.4.4 (core)",
    "signups 2.6.1 (user) published 19 days ago (Sat Nov 02 2024) (latest is 2.6.3)",
    "sobject 1.4.45 (core)",
    "telemetry 3.6.20 (core)",
    "templates 56.3.29 (core)",
    "trust 3.7.41 (core)",
    "user 3.6.2 (core)",
    "@salesforce/sfdx-scanner 4.7.0 (user) published 22 days ago (Tue Oct 29 2024)",
    "lightning-flow-scanner 2.36.0 (user) published 5 days ago (Sat Nov 16 2024)",
    "sfdx-git-delta 5.49.0 (user) published 33 days ago (Sat Oct 19 2024) (latest is 5.49.4)"
  ]
}

**Comment by WillieRuemmele** [comment]
hi @pjha06 - I'm unsure about why it would deploy more than what was specified in the filepath, but for testing string replacements, see [this](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_string_replace.htm) and specifically Test String Replacements towards the bottom

I'd add `--dev-debug` flag to your command, which will enable logging, and maybe provide some hints to why it's deploying the entire dir
