### ISSUE TITLE
Sf project deploy quick successfully triggers Deployment in org but returns error 10

### ISSUE THREAD

**Issue by Radops-rv** [forcedotcom/cli#3128]
### Summary
Sf cli version 2.67.7 linux-x64 node-v22.11.0

Running sf project deploy --job-id after successfull validation and the deployment is triggered in the org successfully but the cli is returning "Error (10): Cannot read properties of undefined (reading 'getField')" which shows up as failed build on my pipeline when the build has actually gone through successfully. This issue started happening after I updated from sf cli 2.50.2 to 2.67.7 .

### Steps To Reproduce

sf org login jwt -i --username -f -d -r (successfull)
Sf project deploy validate -x -o (successfull)
sf project deploy quick --job-id (failed)

### Expected result
Should return a successful build

### Actual result
Returning: "Error (10): Cannot read properties of undefined (reading 'getField')"

### Additional information
![Screenshot_20241127_164248_Teams](https://github.com/user-attachments/assets/388e0dea-6dbf-4fec-bb02-3002750a4650)

### System Information
bash

```json
@salesforce/cli/2.67.7 linux-x64 node-v22.11.0
```

**Comment by Radops-rv** [comment]
I have added the full output of the sf --version --verbose --json

Here is the output again:
@salesforce/cli/2.67.7 linux-x64 node-v22.11.0

**Comment by WillieRuemmele** [comment]
Hi @Radops-rv - 

firstly, the output of `sf version --verbose --json` should look like 
```bash
➜  sf version --verbose --json               
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.69.4",
  "nodeVersion": "node-v22.10.0",
  "osVersion": "Darwin 23.6.0",
  "rootPath": "/Users/william.ruemmele/.nvm/versions/node/v22.10.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.10 (core)",
    "@oclif/plugin-commands 4.1.11 (core)",
    "@oclif/plugin-help 6.2.18 (core)",
    "@oclif/plugin-not-found 3.2.29 (core)",
    "@oclif/plugin-plugins 5.4.17 (core)",
    "@oclif/plugin-search 1.2.16 (core)",
    "@oclif/plugin-update 4.6.13 (core)",
    "@oclif/plugin-version 2.2.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.23 (core)",
    "@oclif/plugin-which 3.2.19 (core)",
    "@salesforce/cli 2.69.4 (core)",
    "apex 3.6.4 (core)",
    "api 1.3.2 (core)",
```

secondly, after creating a validated quick deployment, I ran the command, and I couldn't reproduce the error

```bash
 ➜  sf project deploy quick --job-id 0Af8G00001dREv4SAG
Deploy ID: 0Af8G00001dREwgSAG
Deploy URL: https://ruby-ruby-830-dev-ed.scratch.my.salesforce.com/lightning/setup/DeployStatus/page

Deployed Source
```

**Comment by Radops-rv** [comment]
Hi, thanks for looking into it. 

{
  "architecture": "linux-x64",
  "cliVersion": "@salesforce/cli/2.67.7",
  "nodeVersion": "node-v22.11.0",
  "osVersion": "Linux 6.8.0-1019-aws",
  "rootPath": "/var/lib/jenkins/.local/share/sf/client/2.67.7-3acb081",
  "shell": "bash",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.8 (core)",
    "@oclif/plugin-commands 4.1.8 (core)",
    "@oclif/plugin-help 6.2.16 (core)",
    "@oclif/plugin-not-found 3.2.25 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.14 (core)",
    "@oclif/plugin-update 4.6.10 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.21 (core)",
    "@oclif/plugin-which 3.2.17 (core)",
    "@salesforce/cli 2.67.7 (core)",
    "apex 3.6.2 (core)",
    "api 1.3.2 (core)",
    "auth 3.6.73 (core)",
    "data 3.11.3 (core)",
    "deploy-retrieve 3.15.11 (core)",
    "info 3.4.18 (core)",
    "limits 3.3.39 (core)",
    "marketplace 1.3.4 (core)",
    "org 5.1.4 (core)",
    "packaging 2.9.0 (core)",
    "schema 3.3.40 (core)",
    "settings 2.4.4 (core)",
    "sobject 1.4.45 (core)",
    "telemetry 3.6.20 (core)",
    "templates 56.3.29 (core)",
    "trust 3.7.41 (core)",
    "user 3.6.2 (core)"
  ]
} 
 
So I'm using a connected app (consumer key) to deploy to a Salesforce org /sandbox, and not through a lightning url, infact my orgs Salesforce admin specifically asked me not to use the lightning link for this purpose. So I'm using https://xyz.my.salesforce.com url after the -r flag while running the "org login jwt" command. Could this be where the issue is turning up? 

Again this entire process was running without any issues for almost a year before I upgraded the sf cli a couple of weeks ago. And the Deployment is still being completed successfully at the org. It's just that I'm not getting the correct output in the command line

Here's a screenshot of the issue: 
![tmp_ef3451be-1822-4cd1-9807-95432e0fe75b](https://github.com/user-attachments/assets/9206e173-c560-4248-b3fc-f834ff1f8344)

**Comment by WillieRuemmele** [comment]
ahh, you're running `sf --version --verbose`, it should be `sf version --verbose`, there's a "version" command we need the info from

that's a strange auth mechanism, which could be where this comes from. Do you need to provide the `-r` flag when auth'ing?

irregardless, that's still a runtime error that we should be able to detect with our tools, I think it might be related to that auth requirement

**Comment by Radops-rv** [comment]
Yeah I realised it was sf version not --version 30 seconds after posting the comment xD.

Ok, so are you suggesting I run the org login jwt command without the -r flag? Or use some other auth mechanism entirely. I'll try running it without the -r flag and update here. Sorry I'm a bit iffy about the Salesforce side of things I'm primarily the DevOps person at this organisation and this is one of my Deployment pipelines.

Thanks again for your help.

**Comment by WillieRuemmele** [comment]
haha, no worries 😄 

if the command works without the `-r` flag, don't use it

**Comment by Radops-rv** [comment]
So yes you were right it's still authorising without the -r flag so I'll be getting rid of it, but on running the sf project deploy quick I'm running into the same  "Error (10): Cannot read properties of undefined (reading 'getField')" and it's still also successfully deploying to the org when I check through the console.

**Comment by WillieRuemmele** [comment]
so, following the flow, I can see the error is coming from this [method](https://github.com/salesforcecli/plugin-deploy-retrieve/blob/main/src/commands/project/deploy/quick.ts#L96) call, where the `Org` is undefined, which shouldn't even be possible in this scenario... 

when you're authing to the org, do you set it as default? you might try passing in `-o <your org>` to the `deploy quick` command to see if that helps

**Comment by Radops-rv** [comment]
@WillieRuemmele adding the -o flag and org to the quick deploy command worked perfectly. That was some amazing troubleshooting from your end. 

Thanks so much for your help.

**Comment by WillieRuemmele** [comment]
@Radops-rv - something _is_ going wrong here, you shouldn't need to specify the `target-org` if you've set it as default when auth'ing to it, but I'm glad that worked for now
