### ISSUE TITLE
Need to know whether a Metadata type supports wild card (*) character

### ISSUE THREAD

**Issue by vignaesh01** [forcedotcom/cli#313]
**Is your feature request related to a problem? Please describe.**
When I run force:mdapi:describemetadata command, the results should include whether a metadata type supports wild card (*) character or not.

**What are you trying to do**
 I am using force:mdapi:describemetadata call to get the metadata type information. I am using this logic to build the package.xml automatically in [Salesforce package.xml generator extension for vs code](https://marketplace.visualstudio.com/items?itemName=VignaeshRamA.sfdx-package-xml-generator)
When the user selects a metadata type, if the metadata type supports wild card ( * ) , instead of adding all the list of components using <member> tag, i would just add <member>*</member> while generating the package.xml file.

**Describe the solution you'd like**
While running force:mdapi:describemetadata command, the results should include whether a a particular metadata type supports wild card (*) character along with other details like xmlName, inFolder etc.

**Describe alternatives you've considered**
Currently i manually go through each and every page of the Metadata API developer guide docs to find out whether a metadata type support wild card (*) or not and maintain this list. This is very time consuming.

**Additional context**
You can find the source code here [Github repo](https://github.com/vignaesh01/sfdx-package-generator)

**Comment by kfidelak94** [comment]
I created work item W-7294252 to track this feature request.

**Comment by vignaesh01** [comment]
Thank you

**Comment by andreyshestakov-phsa** [comment]
This [link](https://www.asagarwal.com/salesforce-metadata-types-that-do-not-support-wildcard-characters-in-package-xml/) has a list on metadata types that don't support wildcards:

**Comment by kyunussov** [comment]
For the time being you can use a list of metadata types that do not support wildcard:

 Apex Sharing Reason
 Assignment Rule
 Auto-Response Rule
 Bot Version
 Business Process
 Button or Link
 Compact Layout
 Custom Report Type
 Dashboard
 Dashboard Folder
 Dataflow
 Document
 Document Folder
 Email Folder
 Email Template
 Embedded Service Flow Config
 Escalation Rule
 Experience Bundle
 Feed Filter
 Field Set
 Knowledge Action
 Lead Convert Settings
 List View
 Managed Content Type
 Muting Permission Set
 Prompt
 Record Type
 Redirect Whitelist Url
 Report
 Report Folder
 S-Control
 Send Action
 Settings
 Standard Field
 Standard Value Set
 Validation Rule
 Workflow Email Alert
 Workflow Field Update
 Workflow Outbound Message
 Workflow Rule
 Workflow Task
