### ISSUE TITLE
sf deploy metadata throws Error while deploying destructive changes. 

### ISSUE THREAD

**Issue by SourabhMulay** [forcedotcom/cli#3130]
### Summary
I am using "sf deploy metadata" to deploy the destructive changes in org, It throws the error when I have an empty destructiveChanges.xml file which is an expected behaviour But suppose I am executing the command as a part of continuous integration/ Pipeline then I may have destructive Changes or may not. So when I do not have anything to delete I will keep the destructiveChanges.xml as

destructiveChanges.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
      <version>62.0</version>
</Package>
``` 

and this is where when using below command it throws an error and failed to execute further commands.

command:
```shell
sf deploy metadata --manifest manifest/destructiveChanges/package.xml  -o <OrgAlias> --pre-destructive-changes manifest/destructiveChanges/destructiveChanges.xml
```

it throws: Error (NothingToDeploy): No local changes to deploy.

It should be a warning but it throws an error for empty file. I did tried using placeholder or random component with --ignore-warnings flag but it might be possible that when I mis-spell any class or component name it'll ignore rather than giving me an error.

### Steps To Reproduce

Provided all the details in summery.

1. Download salesforce CLI.
2. authorise the org first and provide alias using "sf org web login --alias myorg".
3. create a folder with package.xml and destructiveChanges.xml file.
4. keep destructiveChanges.xml as same as package.xml and try running above command.
5. It will throw an error "No local changes to deploy."

### Expected result
I know that it's an expected result that cli throws an error of no local changes to deploy. But What should be steps to be care of or any implementation suggestion to avoid running or to skip the command if the destructiveChanges.xml is empty.

### Actual result
It throws an error. "No local changes to deploy." as expected.

### Additional information

package.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>62.0</version>
</Package>
```

destructiveChanges.xml

```xml
Empty File:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>62.0</version>
</Package>

With Placeholder:
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>NoClassExistWithTheName</members>
        <name>ApexClass</name>
    </types>
    <version>62.0</version> <!-- Use the version that is compatible with your Salesforce org -->
</Package>
```

### System Information
Bash or Vs Code Terminal.

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.67.7",
  "nodeVersion": "node-v22.11.0",
  "osVersion": "Darwin 23.6.0",
  "rootPath": "/Users/saurabh.mulay/.local/share/sf/client/2.67.7-3acb081",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.8 (core)",
    "@oclif/plugin-commands 4.1.8 (core)",
    "@oclif/plugin-help 6.2.16 (core)",
    "@oclif/plugin-not-found 3.2.25 (core)",
    "@oclif/plugin-plugins 5.4.15 (core)",
    "@oclif/plugin-search 1.2.14 (core)",
    "@oclif/plugin-update 4.6.10 (core)",
    "@oclif/plugin-version 2.2.15 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.21 (core)",
    "@oclif/plugin-which 3.2.17 (core)",
    "@salesforce/cli 2.67.7 (core)",
    "apex 3.6.2 (core)",
    "api 1.3.2 (core)",
    "auth 3.6.73 (core)",
    "data 3.11.3 (core)",
    "deploy-retrieve 3.15.11 (core)",
    "devops-center 1.2.26 (user) published 25 days ago (Sun Nov 03 2024)",
    "info 3.4.18 (core)",
    "limits 3.3.39 (core)",
    "marketplace 1.3.4 (core)",
    "org 5.1.4 (core)",
    "packaging 2.9.0 (core)",
    "schema 3.3.40 (core)",
    "settings 2.4.4 (core)",
    "signups 2.6.1 (user) published 25 days ago (Sat Nov 02 2024) (latest is 2.6.6)",
    "sobject 1.4.45 (core)",
    "telemetry 3.6.20 (core)",
    "templates 56.3.29 (core)",
    "trust 3.7.41 (core)",
    "user 3.6.2 (core)",
    "@salesforce/sfdx-scanner 4.7.0 (user) published 29 days ago (Tue Oct 29 2024)"
  ]
}

```

**Comment by shetzel** [comment]
Using a destructive changes manifest as you have above does not cause any deployment problems.  However, deploying an empty manifest (the package.xml as in your example above) is user error and will throw an error by design.  An error will cause a non-zero exit code from the command so that scripts will not continue.  Changing this behavior would cause regressions from lots of customers who depend on this behavior.

**Comment by SourabhMulay** [comment]
Thanks @shetzel !!!

**Comment by zaclummys** [comment]
@shetzel Is there any possibility to add an argument like `--allow-nothing-to-deploy`?
Current customers would not break.
