### ISSUE TITLE
Need a CLI command to get the Current API version of the connected org

### ISSUE THREAD

**Issue by vignaesh01** [forcedotcom/cli#314]
**Is your feature request related to a problem? Please describe.**
I would be nice to get the current API version of the connected Salesforce org using a CLI command

**What are you trying to do**
I am auto generating package.xml file inside vs code using the [Salesforce package.xml generator extension for vs code](https://marketplace.visualstudio.com/items?itemName=VignaeshRamA.sfdx-package-xml-generator) . After every release i have to manually update the API version in source code. It would be nice to get it dynamically from a CLI command.

**Describe the solution you'd like**
Need a CLI command to get the Current API version. Eg: sfdx force:org:apiversion

**Describe alternatives you've considered**
Manually updating the API version aftet every Salesforce release.

**Additional context**
[Gitbub repo](https://github.com/vignaesh01/sfdx-package-generator)

**Comment by keirbowden** [comment]
You can create a simple plugin to get this information, outside of the plugin wrapping it's really just a couple of lines:

`    const conn = this.org.getConnection();`
`    const apiVersion = await conn.retrieveMaxApiVersion();`

There's an example of a command that does this in my [bbsfdx](https://www.npmjs.com/package/bbsfdx) plugin - you can find the source for the command at : https://github.com/keirbowden/bbsfdx/blob/master/src/commands/bb/maxapi.ts

(I've only tested with MacOS, but I can't see any reason why another OS would cause problems, as it's only accessing Salesforce through the API).

**Comment by cristiand391** [comment]
FWIW, I wrote a plugin to help make calls to Salesforce APIs easier from the CLI and have an alias for this to always get latest from the org :

```
requires `jq`:

sfdx env api --method GET 'services/data' --target-org <org-username> | jq '.[-1].version'
"57.0"
```

https://github.com/cristiand391/sf-plugin-api#install
