### ISSUE TITLE
Getting some random log format for the project retrieve start command from the stdout

### ISSUE THREAD

**Issue by lakshmi2506** [forcedotcom/cli#3141]
`───────────── Retrieving Metadata ──────────────

 ◼ Preparing retrieve request
 ◼ Sending request to org
 ◼ Waiting for the org to respond
 ◼ Done

 Status: ◜
 Elapsed Time: 0ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 ✔ Preparing retrieve request 48ms
 ⣾ Sending request to org 0ms
 ◼ Waiting for the org to respond
 ◼ Done

 Status: ◜
 Elapsed Time: 0ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ⣾ Sending request to org 53ms
 ◼ Waiting for the org to respond
 ◼ Done

 Status: ◜
 Elapsed Time: 103ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ⣾ Sending request to org 86ms
 ◼ Waiting for the org to respond
 ◼ Done

 Status: ◠
 Elapsed Time: 109ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ⣽ Sending request to org 161ms
 ◼ Waiting for the org to respond
 ◼ Done

 Status: ◠
 Elapsed Time: 188ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ⣽ Sending request to org 230ms
 ◼ Waiting for the org to respond
 ◼ Done

 Status: ◠
 Elapsed Time: 206ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣾ Waiting for the org to respond 16ms
 ◼ Done

 Status: Pending
 Elapsed Time: 287ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣾ Waiting for the org to respond 44ms
 ◼ Done

 Status: Pending
 Elapsed Time: 318ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣾ Waiting for the org to respond 51ms
 ◼ Done

 Status: Pending
 Elapsed Time: 348ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣽ Waiting for the org to respond 102ms
 ◼ Done

 Status: Pending
 Elapsed Time: 368ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣻ Waiting for the org to respond 201ms
 ◼ Done

 Status: Pending
 Elapsed Time: 469ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣻ Waiting for the org to respond 227ms
 ◼ Done

 Status: Pending
 Elapsed Time: 499ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⢿ Waiting for the org to respond 255ms
 ◼ Done

 Status: Pending
 Elapsed Time: 525ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⢿ Waiting for the org to respond 284ms
 ◼ Done

 Status: Pending
 Elapsed Time: 555ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⢿ Waiting for the org to respond 313ms
 ◼ Done

 Status: Pending
 Elapsed Time: 581ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⡿ Waiting for the org to respond 341ms
 ◼ Done

 Status: Pending
 Elapsed Time: 608ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⡿ Waiting for the org to respond 365ms
 ◼ Done

 Status: Pending
 Elapsed Time: 638ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣟ Waiting for the org to respond 392ms
 ◼ Done

 Status: Pending
 Elapsed Time: 668ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣟ Waiting for the org to respond 421ms
 ◼ Done

 Status: Pending
 Elapsed Time: 695ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣟ Waiting for the org to respond 450ms
 ◼ Done

 Status: Pending
 Elapsed Time: 721ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣯ Waiting for the org to respond 477ms
 ◼ Done

 Status: Pending
 Elapsed Time: 748ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣯ Waiting for the org to respond 503ms
 ◼ Done

 Status: Pending
 Elapsed Time: 779ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣷ Waiting for the org to respond 531ms
 ◼ Done

 Status: Pending
 Elapsed Time: 811ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣷ Waiting for the org to respond 557ms
 ◼ Done

 Status: Pending
 Elapsed Time: 843ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣷ Waiting for the org to respond 586ms
 ◼ Done

 Status: Pending
 Elapsed Time: 870ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣾ Waiting for the org to respond 612ms
 ◼ Done

 Status: Pending
 Elapsed Time: 896ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣾ Waiting for the org to respond 632ms
 ◼ Done

 Status: Pending
 Elapsed Time: 932ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣽ Waiting for the org to respond 676ms
 ◼ Done

 Status: Pending
 Elapsed Time: 958ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣽ Waiting for the org to respond 711ms
 ◼ Done

 Status: Pending
 Elapsed Time: 990ms

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ⣽ Waiting for the org to respond 736ms
 ◼ Done

 Status: Pending
 Elapsed Time: 1.02s

[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[1A[2K[G
 ────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 57ms
 ✔ Sending request to org 245ms
 ✔ Waiting for the org to respond 752ms
 ✔ Done 0ms

 Status: Succeeded
 Elapsed Time: 1.03s

Retrieved Source
┌─────────┬─────────┬──────────────┬───────────────────────────────────────────────────────────────────┐
│ State   │ Name    │ Type         │ Path                                                              │
├─────────┼─────────┼──────────────┼───────────────────────────────────────────────────────────────────┤
│ Created │ Contact │ SharingRules │ force-app/main/default/sharingRules/Contact.sharingRules-meta.xml │
└─────────┴─────────┴──────────────┴───────────────────────────────────────────────────────────────────┘
`

Can someone help me avoid this extra logs and just get the stdout as 

────────────── Retrieving Metadata ──────────────

 Retrieving v62.0 metadata from 00DE200000AUcq5!AQEAQBA39P2ysR26vwOdSPP1h1n1N1O9
 BKdUUTxVL9SqtcgdOei66mvoEeZTnwoX15ds0lyaXX63VR_QCd3sWr7VJ.WNPaxc using the
 v62.0 SOAP API

 ✔ Preparing retrieve request 10ms
 ✔ Sending request to org 393ms
 ✔ Waiting for the org to respond 464ms
 ✔ Done 0ms

 Status: Succeeded
 Elapsed Time: 884ms

Retrieved Source
┌─────────┬─────────┬──────────────┬───────────────────────────────────────────────────────────────────┐
│ State   │ Name    │ Type         │ Path                                                              │
├─────────┼─────────┼──────────────┼───────────────────────────────────────────────────────────────────┤
│ Changed │ Account │ SharingRules │ force-app/main/default/sharingRules/Account.sharingRules-meta.xml │
│ Changed │ Contact │ SharingRules │ force-app/main/default/sharingRules/Contact.sharingRules-meta.xml │
│ Changed │ Lead    │ SharingRules │ force-app/main/default/sharingRules/Lead.sharingRules-meta.xml    │
└─────────┴─────────┴──────────────┴───────────────────────────────────────────────────────────────────┘

How to avoid the extra polling or some unreadable text in between and just get the consice information like previous SFDX commands.

**Comment by lakshmi2506** [comment]
```
sh-5.1$ sf version --verbose
 CLI Version:
        @salesforce/cli/2.66.7

 Architecture:
        linux-arm64

 Node Version:
        node-v18.20.4

 Plugin Version:
        @oclif/plugin-autocomplete 3.2.8 (core)
        @oclif/plugin-commands 4.1.7 (core)
        @oclif/plugin-help 6.2.16 (core)
        @oclif/plugin-not-found 3.2.25 (core)
        @oclif/plugin-plugins 5.4.15 (core)
        @oclif/plugin-search 1.2.14 (core)
        @oclif/plugin-update 4.6.10 (core)
        @oclif/plugin-version 2.2.15 (core)
        @oclif/plugin-warn-if-update-available 3.1.21 (core)
        @oclif/plugin-which 3.2.17 (core)
        @salesforce/cli 2.66.7 (core)
        apex 3.5.6 (core)
        api 1.3.1 (core)
        auth 3.6.72 (core)
        data 3.11.2 (core)
        deploy-retrieve 3.15.8 (core)
        info 3.4.17 (core)
        limits 3.3.38 (core)
        marketplace 1.3.4 (core)
        org 5.1.2 (core)
        packaging 2.9.0 (core)
        schema 3.3.40 (core)
        settings 2.4.4 (core)
        sobject 1.4.44 (core)
        telemetry 3.6.19 (core)
        templates 56.3.28 (core)
        trust 3.7.39 (core)
        user 3.6.2 (core)

 OS and Version:
        Linux 6.10.4-linuxkit

 Shell:
        bash

 Root Path:
        /app/node_modules/@salesforce/cli
```

**Comment by lakshmi2506** [comment]
Tried with the latest version as well 

```
sh-5.1$ sf version --verbose
 CLI Version:
        @salesforce/cli/2.68.6

 Architecture:
        linux-arm64

 Node Version:
        node-v18.20.4

 Plugin Version:
        @oclif/plugin-autocomplete 3.2.10 (core)
        @oclif/plugin-commands 4.1.10 (core)
        @oclif/plugin-help 6.2.18 (core)
        @oclif/plugin-not-found 3.2.28 (core)
        @oclif/plugin-plugins 5.4.17 (core)
        @oclif/plugin-search 1.2.16 (core)
        @oclif/plugin-update 4.6.13 (core)
        @oclif/plugin-version 2.2.16 (core)
        @oclif/plugin-warn-if-update-available 3.1.23 (core)
        @oclif/plugin-which 3.2.19 (core)
        @salesforce/cli 2.68.6 (core)
        apex 3.6.3 (core)
        api 1.3.2 (core)
        auth 3.6.75 (core)
        data 3.11.4 (core)
        deploy-retrieve 3.15.13 (core)
        info 3.4.21 (core)
        limits 3.3.40 (core)
        marketplace 1.3.6 (core)
        org 5.2.4 (core)
        packaging 2.9.3 (core)
        schema 3.3.42 (core)
        settings 2.4.6 (core)
        sobject 1.4.46 (core)
        telemetry 3.6.23 (core)
        templates 56.3.30 (core)
        trust 3.7.43 (core)
        user 3.6.3 (core)

 OS and Version:
        Linux 6.10.4-linuxkit

 Shell:
        bash

 Root Path:
        /app/node_modules/@salesforce/cli
```

**Comment by mdonnalley** [comment]
@lakshmi2506 what terminal are you using?

As a workaround, you can set `CI=true` in your environment to get the less fancy CI output

**Comment by lakshmi2506** [comment]
@mdonnalley  It is /bin/zsh terminal. And when you say `CI=true`, export CI="true". Is that ok?

**Comment by mdonnalley** [comment]
>And when you say CI=true, export CI="true". Is that ok?

Yes that works

**Comment by lakshmi2506** [comment]
Thank you it worked.
