### ISSUE TITLE
sf org create user fails with DUPLICATE_COMM_NICKNAME

### ISSUE THREAD

**Issue by epavlic-revenue** [forcedotcom/cli#3142]
### Summary

When I run:
- `sf org create user --definition-file config/my-user.json --set-unique-username`, and
- username is specified in the definition file

Then, I get an exception:
> DUPLICATE_COMM_NICKNAME, Duplicate Nickname.<br>Another user has already selected this nickname.<br>Please select another.: [CommunityNickname]

Setting the `CommunityNickname` directly also results in the exception
```
sf org create user --definition-file config/my-user.json --set-unique-username CommunityNickname=some-uuid
```

Removing the username from the definition file results in successful creation of users.  

### Steps To Reproduce

1. Create a definition file with a username set.
2. Run `sf org create user --definition-file config/my-user.json --set-unique-username`

### Expected result
Create a user with a unique community nickname

### Actual result
Throws an exception

### System Information

```json
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.68.6",
  "nodeVersion": "node-v20.17.0",
  "osVersion": "Darwin 24.1.0",
  "rootPath": "/Users/ipavlic/.nvm/versions/node/v20.17.0/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.2.10 (core)",
    "@oclif/plugin-commands 4.1.10 (core)",
    "@oclif/plugin-help 6.2.18 (core)",
    "@oclif/plugin-not-found 3.2.28 (core)",
    "@oclif/plugin-plugins 5.4.17 (core)",
    "@oclif/plugin-search 1.2.16 (core)",
    "@oclif/plugin-update 4.6.13 (core)",
    "@oclif/plugin-version 2.2.16 (core)",
    "@oclif/plugin-warn-if-update-available 3.1.23 (core)",
    "@oclif/plugin-which 3.2.19 (core)",
    "@salesforce/cli 2.68.6 (core)",
    "apex 3.6.3 (core)",
    "api 1.3.2 (core)",
    "auth 3.6.75 (core)",
    "data 3.11.4 (core)",
    "deploy-retrieve 3.15.13 (core)",
    "devops-center 1.2.10 (user) published 213 days ago (Thu May 09 2024) (latest is 1.2.26)",
    "info 3.4.21 (core)",
    "limits 3.3.40 (core)",
    "marketplace 1.3.6 (core)",
    "org 5.2.4 (core)",
    "packaging 2.9.3 (core)",
    "schema 3.3.42 (core)",
    "settings 2.4.6 (core)",
    "sobject 1.4.46 (core)",
    "telemetry 3.6.23 (core)",
    "templates 56.3.30 (core)",
    "trust 3.7.43 (core)",
    "user 3.6.3 (core)"
  ]
}
```

**Comment by mdonnalley** [comment]
@epavlic-revenue I think the error coming from the server might be misleading here. 

The `--set-unique-username` simply appends the org id to the configured username (e.g. `user@example.com` -> `user@example.com.00de200000auwtdmad`

So if you run `sf user create` multiple times with the same config, it's going to fail because you're attempting to create a second user with the exact same username as the first

**Comment by epavlic-revenue** [comment]
@mdonnalley Even on a *fresh scratch org*, just based on a fact that that username was used in a *previous scratch org* makes it impossible to create one user. My guess is that the un-appended username is used to create the `CommunityNickname`.

**Comment by epavlic-revenue** [comment]
Thanks!
