### ISSUE TITLE
Unable to send command switches to Jest Runner.

### ISSUE THREAD

**Issue by jefersonchaves** [forcedotcom/cli#315]
### Summary

SFDX LWC Test Runner not respecting `--` to send commands to the next command mismatching what `npm run` and `lwc-jest` does.

This works, for instance:
`npm run test:unit -- -- --ci --reporters=default --reporters=jest-junit `

### Steps To Reproduce:

1.  Run `sfdx force:lightning:lwc:test:run -- -- -- --ci --reporters=default --reporters=jest-junit`

### Expected result

Jest runner is informed that is running on Continuous Integration, should run default reporter and JUnit reporter.

### Actual result

Error: `Unexpected arguments: --, --ci, --reporters=default, --reporters=jest-junit`

### Additional information

**SFDX CLI Version**:
sfdx-cli/7.47.0-0e5d18732f darwin-x64 node-v10.15.3

**SFDX plugin Version**:
@oclif/plugin-autocomplete 0.1.5
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.0
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.2.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.3.0
└─ salesforce-alm 48.3.0

sfdx-cli 7.47.0 (core)

**OS and version**:
macOS Catalina 10.15.3 (19D76)

**Comment by clairebianchi** [comment]
@jefersonchaves I have notified the team that owns this command and they are taking a look

**Comment by ntotten** [comment]
The command `force:lightning:lwc:test:run` is really for simple use cases. You should continue to use `lwc-jest` directly for more complicated scenarios as you are doing with your `test:unit` script.

**Comment by jefersonchaves** [comment]
Hi @ntotten 

I'm not sure if my use case is really considered a complicated scenario because all it is doing is telling jest to run continuous integration mode and setting up two reporters. I think this is a pretty common use case for Continuous Integration.

Would you consider adding native flags for running `sfdx force:lightning:lwc:test:run` in Continuous Integration environment?
