### ISSUE TITLE
Ignoring General Warnings During Salesforce Deployment

### ISSUE THREAD

**Issue by DilipJainFL** [forcedotcom/cli#3151]
### Summary
While executing the deployment general warnings are getting displayed as error. Deployment tool - Bamboo This is general salesforce cli, not related to any specific org.

### Steps To Reproduce

1. Try to deploy or retrieve the changes in case your cli is not updated you will see the warning as highlighted below.

![Screenshot 2024-12-13 160252](https://github.com/user-attachments/assets/11b480cd-b951-490d-b6d7-6d7854a15ac9)

**Comment by DilipJainFL** [comment]
here is the Version -  2.62.6

**Comment by iowillhoit** [comment]
Hey @DilipJainFL, is this "update warning" actually causing issues? We generally only support the latest version of the CLI. Updating the CLI to the latest version will remove that warning.

**Comment by mcarvin8** [comment]
This environment variable is newer, but you should be able to set this environment variable in your deployment environment to disable the new version checks. My org sets this in our containers.

`SF_SKIP_NEW_VERSION_CHECK=true`

![image](https://github.com/user-attachments/assets/967ccafe-f49c-4361-bea9-848ee231ac53)


https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm

**Comment by DilipJainFL** [comment]
I'm still encountering issues with setting the version in the Salesforce CLI. Additionally, I would like to hide the warnings that appear in the CLI. These warnings are usually displayed as standard errors in the Pipeline CLI configuration, which causes confusion between actual errors and warnings.


![Image](https://github.com/user-attachments/assets/f309af9e-2c65-43a1-932b-cfd242233037)

**Comment by chulai** [comment]
@DilipJainFL it looks like SF_SKIP_NEW_VERSION_CHECK is available as an Environment Variable (https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm)  but not as a Configuration Variable (https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_config_values.htm#sfdx_dev_cli_config_values). I guess another issue should be created for that.

Anyway, this worked for me and applies only to the command running:
$ SF_SKIP_NEW_VERSION_CHECK=true sf --version

To set it globally, this works:
$ export SF_SKIP_NEW_VERSION_CHECK=true
$ sf --version

**Comment by VivekMChawla** [comment]
@chulai - `SF_SKIP_NEW_VERSION_CHECK` is only meant to be an Environment Variable.  By design, it is not a Configuration Variable, so no need to open an issue for that.

If you believe this is would be a desirable feature change, please post an idea to the discussions board and share a detailed description of your use case.  Thank you!

**Comment by chulai** [comment]
@VivekMChawla, I got a reply for this matter at https://github.com/forcedotcom/cli/issues/3193#issuecomment-2613488991 by @cristiand391 and I understand why this has not been implemented as a 'Configuration Variable' and I'm ok with it.

Thanks!
