### ISSUE TITLE
sfdx force:source:retrieve does not retrieve CustomField

### ISSUE THREAD

**Issue by cerbaire** [forcedotcom/cli#317]
### Summary

I would like to retrieve CustomField without retrieving the whole CustomObject.

### Steps To Reproduce:

1.  Create a package.xml with the following content (support the CustomObject and the CustomField exist) :
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>Car__c.Position__c</members>
		<members>Car__c.description</members>
		<name>CustomObject</name>
	</types>
	<version>48.0</version>
</Package>
1.  Launch the retrieve command:
sfdx force:source:retrieve -x package.xml -u 00D5J000000lzM8!AQoAQF...vECXdcWO0Ug --json

### Expected result

I expect to have in the subfoler "force-app\main\default\objects" a folder "Car__c\fields" with the file "Position__c.field-meta.xml" inside

### Actual result

The subfoler "force-app\main\default\objects" is empty

### Additional information
**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.46.3-4cf515d568 win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.0 (core)
generator 1.1.2 (core)
salesforcedx 48.1.5 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.1.0 (core)
└─ salesforce-alm 48.1.1 (core)

sfdx-cli 7.46.3 (core)
**OS and version**:
Windows 10

**Comment by clairebianchi** [comment]
@cerbaire we are investigating internally

**Comment by clairebianchi** [comment]
@cerbaire This is working as expected, but you should definitely receive a warning. So we are going to add a warning when you perform those actions

Here is the MDAPI documentation https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/customfield.htm
