### ISSUE TITLE
force:source:push fails with conflicts even when none exist

### ISSUE THREAD

**Issue by rhobkirkcertinia** [forcedotcom/cli#318]
### Summary

When pushing an Apex class that is dependent upon another managed package's global API, the file will fail to push stating that "we couldn’t push your source due to conflicts" even when no conflict exists. So even when the file has only been edited locally it will fail to push with conflicts. By adding the "-f" option, the file will push as expected, however this shouldn't be necessary since no conflict exists.

### Steps To Reproduce:

1. Create a 1GP managed package containing a global API that you can use for testing
1. Create an SFDX project and create a new org
1. Install the 1GP managed package in the org
1. Create an Apex Class locally in your SFDX project and add a method but don't invoke the global API yet
1. Push using "sfdx force:source:push" - NOTE - no conflict occurs
1. Add a new method that invokes the global API previously mentioned
1. Push using "sfdx force:source:push" -- NOTE - conflict occurs despite nothing changing in the org. Since no conflict actually exist, the push should work
1. Push using "sfdx force:source:push -f" -- NOTE - this works as expected, however shouldn't be necessary

### Expected result

_Push should have worked without the "-f" option_

### Actual result

_Push failed due to (non existent) conflict_.

### Additional information

Versions affected: 7.45.1, 7.46.1

**OS and version**:
Mac OS

**Comment by jclark-dot-org** [comment]
I am observing the same thing when referencing a managed package field in my code.  My repro steps:

1.  Create a scratch org and install the current release of the Financial Service Cloud managed package (`FinServ` namespace).

2.  Create an apex class with no reference to the `FinServ` namespace.  Save, push, edit, Save, push.  No conflicts are reported.

3.  Add a reference to the `FinServ` Namespace.  Save, push, edit, save, push.  Conflict reported.

4.  Remove the reference to `FinServ`, AND remove the `packageVersions` section of the class's `-meta.xml` file that references the namespace (if present).  Save, push, conflict, but subsequent edits will have no conflict.

I've found that pulling the class adds the namespace ref in the `meta.xml`, and once it is there, you have to remove it to avoid the conflict; but removing it makes no difference if the code also references the namespace.

For reference, my use of the namespace in Apex is a simple field ref:
```
List<Account> accounts = [
    SELECT Id, RecordTypeId, FinServ__SourceSystemId__c 
      FROM Account 
     WHERE Id = :accountId
];
// some error checking removed for clarity
Account a = accounts[0];
if (a.FinServ__SourceSystemId__c == null) {
   // ... SNIP
}
```

**Comment by mdonnalley** [comment]
@rhobkirkffdc are you still experiencing this issue on the latest version of the CLI?
