### ISSUE TITLE
sfdx auto update Warning breaks json parsing

### ISSUE THREAD

**Issue by danielepiccone** [forcedotcom/cli#320]
### Summary

I have some automation that instruments sfdx to perform some tasks and checks the output of the command by parsing the json output.

### Steps To Reproduce:

1.  Install sfdx (not the latest version)
1.  sfdx force:auth:list --json 2>&1 | jq .status

### Expected result

In case no organization is found the command output is 

```json
{
    "status": 1,
    "name": "NoAuthInfoFound",
    "message": "No authorization information can be found.",
    "exitCode": 1,
    "commandName": "AuthListCommand",
    "stack": "NoAuthInfoFound: No authorization information can be found.\n    at Function.create (/usr/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:141:16)\n    at Function.listAllAuthFiles (/usr/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/authInfo.js:253:41)",
    "warnings": []
}
```

and the result of this command should be 1

### Actual result

```sh
/ # sfdx force:auth:list --json 2>&1 | jq .status
parse error: Invalid numeric literal at line 1, column 5
```

removing the json parsing it is evident that the first line is printed on stderr along with the json:

```
 ›   Warning: sfdx-cli update available from 7.45.1 to 7.47.0.
{
    "status": 1,
    "name": "NoAuthInfoFound",
    "message": "No authorization information can be found.",
    "exitCode": 1,
    "commandName": "AuthListCommand",
    "stack": "NoAuthInfoFound: No authorization information can be found.\n    at Function.create (/usr/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:141:16)\n    at Function.listAllAuthFiles (/usr/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/authInfo.js:253:41)",
    "warnings": []
}
```

### Additional information

It is not an option for us to upgrade sfdx everywhere every time this happens to fix the issue.

There should be a configuration parameter to prevent this situation to happen.

edit:
The same behaviour happens with these env variables set:
```
SFDX_LOG_LEVEL=error
SFDX_AUTOUPDATE_DISABLE=true
SFDX_DISABLE_TELEMETRY=true
```

**SFDX CLI Version**
sfdx-cli/7.45.1 linux-x64 node-v10.19.0

**SFDX plugin Version**
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 47.18.0 (core)
├─ salesforcedx-templates 47.19.0 (core)
└─ salesforce-alm 47.16.0 (core)

sfdx-cli 7.45.1 (core)
```

**OS and version**:
alpine linux - Linux 5699923ad596 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux
mac osx - Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by clairebianchi** [comment]
@danielepiccone you can ignore warnings with this command:

# ignoring stderr so the jq parsing always works
SFDX_JSON_TO_STDOUT=true sfdx force:org:display -s --json 2> /dev/null | jq

See our blog on using CLI output: https://developer.salesforce.com/blogs/2020/02/using-salesforce-cli-output-and-scripting.html

**Comment by danielepiccone** [comment]
Thank you!
