### ISSUE TITLE
Error running force:source:retrieve: XML parse errors reported

### ISSUE THREAD

**Issue by jeremyhiggs** [forcedotcom/cli#322]
### Summary

With recent versions of SFDX and Salesforce, I am receiving XML parse errors (without any details) when trying to retrieve source from the production instance.

### Steps To Reproduce:

1. Authenticate with production
2. sfdx force:source:retrieve --manifest "manifest/package.xml" --verbose --apiversion=46.0

### Expected result

It should have retrieved the source!

### Actual result

Using specified username x@x.com

ERROR running force:source:retrieve:  XML parse errors reported

### Additional information

_Feel free to attach a screenshot_.

Package.xml (it contains custom objects, so won't work for anyone else without removing them.)

[package.xml.zip](https://github.com/forcedotcom/cli/files/4265941/package.xml.zip)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.48.0-a71f8c6899 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
apexlink 0.5.0
etcopydata 0.5.7
generator 1.1.2 (core)
salesforcedx 48.3.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.4.0 (core)
└─ salesforce-alm 48.4.0 (core)

sfdx-cli 7.48.0 (core)
sfdx-retrieve-deploy-companion 1.0.6
texei-sfdx-plugin 1.3.2

**OS and version**:

MacOS 10.15.3

**Comment by jeremyhiggs** [comment]
Using the same package.xml with sfdx force:mdapi:retrieve works fine.

**Comment by jeremyhiggs** [comment]
![Screenshot 2020-02-28 at 1 13 45 PM](https://user-images.githubusercontent.com/182224/75522598-2d1a9880-5a2c-11ea-9cd3-3a090d85c247.png)

It seems to partially retrieve the source, but encounter a problem within or after the installedPackages files. This is the status of the git repo folder after the error.

**Comment by clairebianchi** [comment]
@jeremyhiggs can you run the command with --dev-debug and send us the output. We have a feeling this issue has to do with a specific metadata type. We are also going to take a look at the error message and make some updates to make it more helpful in the future.

**Comment by jeremyhiggs** [comment]
sfdx:core TRACE Setup child 'SourceRetrieveCommand' logger instance +0ms
  sfdx:force:source:retrieve init version: @oclif/command@1.5.19 argv: [ '--targetusername=x@x.com', '--verbose', '--apiversion=46.0' ] +0ms
  sfdx:SourceRetrieveCommand INFO Running command [SourceRetrieveCommand] with flags [{"targetusername":"x@x.com","verbose":true,"apiversion":"46.0","loglevel":"warn","wait":{"quantity":33,"unit":0}}] and args [{}] +0ms
  sfdx:core TRACE Setup child 'Org' logger instance +34ms
  sfdx:core TRACE Setup child 'AuthInfo' logger instance +4ms
  sfdx:core TRACE Setup child 'crypto' logger instance +2ms
  sfdx:crypto DEBUG retryStatus: undefined +0ms
  sfdx:core TRACE Setup child 'keyChain' logger instance +4ms
  sfdx:keyChain DEBUG platform: darwin +0ms
  sfdx:AuthInfo INFO Updated auth info for username: x@x.com +0ms
  sfdx:AuthInfo INFO Returning fields for a connection using OAuth config. +2ms
  sfdx:core TRACE Setup child 'connection' logger instance +72ms
  sfdx:connection DEBUG request: {"method":"GET","url":"https://_company_.my.salesforce.com/services/data","headers":{"content-type":"application/json","user-agent":"sfdx toolbelt:"}} +0ms
  sfdx:connection DEBUG <request> method=GET, url=https://_company_.my.salesforce.com/services/data +2ms
  sfdx:connection DEBUG elappsed time : 1634msec +2s
  sfdx:connection DEBUG <response> status=200, url=https://_company_.my.salesforce.com/services/data +1ms
  sfdx:connection DEBUG response for org versions: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] +3ms
Using specified username x@x.com

ERROR running force:source:retrieve:  Missing one of the following parameters: manifest metadata sourcepath packagenames
*** Internal Diagnostic ***

MissingRequiredParam: Missing one of the following parameters: manifest metadata sourcepath packagenames
    at Function.create (/Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/@salesforce/core/lib/sfdxError.js:141:16)
    at SourceRetrieveCommand.validate (/Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/salesforce-alm/dist/lib/source/sourceRetrieveCommand.js:43:36)
    at SourceRetrieveCommand.execLegacyCommand (/Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/salesforce-alm/dist/ToolbeltCommand.js:145:38)
    at SourceRetrieveCommand.run (/Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/salesforce-alm/dist/commands/force/source/retrieve.js:27:27)
******

  sfdx:SourceRetrieveCommand ERROR [ '\u001b[1mERROR running force:source:retrieve: \u001b[22m',
  sfdx:SourceRetrieveCommand   '\u001b[31mMissing one of the following parameters: manifest metadata sourcepath packagenames\u001b[39m',
  sfdx:SourceRetrieveCommand   '\u001b[31m\u001b[39m\n\u001b[31m*** Internal Diagnostic ***\u001b[39m\n\u001b[31m\u001b[39m\n\u001b[31mMissingRequiredParam: Missing one of the following parameters: manifest metadata sourcepath packagenames\u001b[39m\n\u001b[31m    at Function.create (/Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/@salesforce/core/lib/sfdxError.js:141:16)\u001b[39m\n\u001b[31m    at SourceRetrieveCommand.validate (/Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/salesforce-alm/dist/lib/source/sourceRetrieveCommand.js:43:36)\u001b[39m\n\u001b[31m    at SourceRetrieveCommand.execLegacyCommand (/Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/salesforce-alm/dist/ToolbeltCommand.js:145:38)\u001b[39m\n\u001b[31m    at SourceRetrieveCommand.run (/Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/salesforce-alm/dist/commands/force/source/retrieve.js:27:27)\u001b[39m\n\u001b[31m******\u001b[39m\n\u001b[31m\u001b[39m' ] +2s
  lazy-require saving type cache to /Users/jhiggs/Library/Caches/sfdx/module-types.json +3s
  lazy-require no changes to save +0ms
  sfdx:analytics Spawning "/Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/bin/node /Users/jhiggs/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/@salesforce/plugin-analytics/processes/upload /Users/jhiggs/Library/Caches/sfdx /var/folders/zv/plqt4mzj65x_zt7lq5cc_00c0000gn/T/sfdx-analytics/analytics-58ef95507839e149e9e8870bb442684ae05bec80.log" +2s

**Comment by jeremyhiggs** [comment]
Do you have any insights into how to fix this?

**Comment by nramyasri-sf** [comment]
@jeremyhiggs, is there a possibility to share the source code? Or, could you please create a salesforce support ticket and let us know the case number so we can investigate this further?Thank you.

**Comment by jeremyhiggs** [comment]
Would you need the source code for the manifest? I can do that.
[package.xml.zip](https://github.com/forcedotcom/cli/files/4375202/package.xml.zip)

**Comment by amphro** [comment]
Hey @jeremyhiggs - your debug output is a different error than the one you posted about. It is for `ERROR running force:source:retrieve: Missing one of the following parameters: manifest metadata sourcepath packagenames` when means you ran it without the manifest params. We need the debug output for when you receive `ERROR running force:source:retrieve: XML parse errors reported`

In addition, the package.xml is not enough. We need the source that is causing the XML parse error. So we would either need a ZIP of your entire source, OR a simple repository that reproduces the problem with a scratch org create, deploy, then retrieve.
