### ISSUE TITLE
sfdx no longer shows which tests failed in output

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#326]
### Summary

Running `SFDX_USE_PROGRESS_BAR=false sfdx force:source:deploy` does not show you which tests failed

### Steps To Reproduce:

1.  Run `SFDX_USE_PROGRESS_BAR=false sfdx force:source:deploy ... --testlevel RunLocalTests --checkonly`

### Expected result

Tests failed are included int he output

### Actual result

Lots of messages like:

```
Status:  InProgress
jobid:  0Df7A00000P6CgVSEE
Component errors:  0
Components checked: 2087
Components total:  2087
Tests errors:  5
Tests completed:  505
Tests total:  941
Check only: true
```

Followed by:

```
Status:  Failed
jobid:  0Af7A00000P6CgVSAV
Completed:  2020-02-29T02:05:27.000Z
Component errors:  0
Components checked:  2073
Components total:  2073
Tests errors:  5
Tests completed:  505
Tests total:  941
Check only: true
```

### Additional information

This is happening as of Friday, February 28th, where we cloned this URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

And according to the output from our test run:

sfdx-cli/7.48.0-a71f8c6899 linux-x64 node-v10.15.3
sfdx-cli: Updating CLI... already on latest version: 7.48.0-a71f8c6899

The CLI used to show test errors in the stdout. It no longer does. It looks like this is also reported here in an issue that was erroneously closed: https://github.com/forcedotcom/cli/issues/283

This was also reported by a user in another closed issue: https://github.com/forcedotcom/cli/issues/289

**Comment by AndrewRayCode** [comment]
Also note that the `jobid` listed in the test output is not **the jobid shown on the deployment status list.** This can make it difficult to find which job your tests ran as, especially on a team where multiple users are running tests. I had tests run on Friday and due to other activity, I'm not sure which job to look at to see the test output.

There may be a hack / workaround to find the job somehow, but sfdx used to output failed tests, and now that has gone away without us changing any configuration. I hope you can understand my frustration that our test infrastructure has stopped working properly with **no configuration changes by us** (and other users have had the same issue). We do not have stable builds because as far as I can tell there's not a way to lock down the sfdx version (I would love to find out I'm wrong and there's an easy way to install a specific cli version!)

**Comment by ntotten** [comment]
Automation infrastructure should always use a stable version and should have automatic updates turned off. See: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_supported_versions.htm

Additionally, if you install via nodejs you can install a specific version: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_npm

**Comment by AndrewRayCode** [comment]
Thank you, I will experiment with older versions. However, I'm not sure how to reconcile these two statements:

> Salesforce supports only the most current versions of the Salesforce CLI and the salesforcedx plug-in.

vs

> Automation infrastructure should always use a stable version and should have automatic updates turned off.

if i understand the first statement correctly, at any time the locked version of sfdx could fail?

**Comment by clairebianchi** [comment]
@AndrewRayCode, we have fixed this issue, it will go into next weeks release. Thank you for your feedback.
