### ISSUE TITLE
Deleting a field will also delete related metadata (Layouts, Profiles...) from local repo

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/cli#329]
### Summary

Deleting a field will also delete related metadata (Layouts, Profiles...) from local repo

### Steps To Reproduce:

* Create a Scratch Org
* Create a custom field, add it to several layouts and profiles
* Pull all changes
* Delete the custom field
* Pull the changes

### Expected result

The custom field is deleted, and layouts/profiles are updated with the custom field removed.

### Actual result

Everything is deleted from the local repo, both the field and the related metadata.

### Additional information

```
salesforcedx 48.3.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.4.0 (core)
└─ salesforce-alm 48.4.0 (core)

sfdx-cli 7.48.0 (core)
```

**Comment by FabienTaillon** [comment]
I also created case #25828661 for this.

**Comment by clairebianchi** [comment]
@FabienTaillon Thank you for submitting this. Vlad on our side has created an internal issue and is investigating.

**Comment by FabienTaillon** [comment]
@clairebianchi looks like this one is fixed ?

**Comment by dieffrei** [comment]
We got the same problem!

**Comment by FabienTaillon** [comment]
Yes, I got it again on another project (after thinking it was fixed)

**Comment by mshanemc** [comment]
Not reproducible using current CLI nightly version.

![Screenshot 2023-10-04 at 3 00 37 PM](https://github.com/forcedotcom/cli/assets/4261788/c2e40af7-1efa-44a5-a194-49057d727e98)
![Screenshot 2023-10-04 at 3 00 46 PM](https://github.com/forcedotcom/cli/assets/4261788/8e996219-0967-40cd-8320-c5485337c5ce)
