### ISSUE TITLE
LWC retrive issue with sfdx 

### ISSUE THREAD

**Issue by vijaykumar8448** [forcedotcom/cli#33]
I am not able to retrieve my LWC components from org to local on windows machine . I ran below commands but both failed 
 
sfdx force:source:retrieve -m LightningComponentBundle
 
or 
 
sfdx force:source:retrieve -m LightningComponentBundle:helloWorld

**Comment by shetzel** [comment]
This will be fixed in the next patch release of the salesforcedx plugin (2/21/19).  Thanks for your patience!

**Comment by ThiruManoj** [comment]
This is not fixed in this release. I am still facing the same issue.

**Comment by FabienTaillon** [comment]
I tried today after running sfdx update (salesforcedx 45.3.4 (core)), and it's now working fine :)

**Comment by Richman7** [comment]
***.js-meta.xml file not retrieved when retrieving component for the first time.** I've updated to salesforcedx plugin version 45.3.4 and tried to retrieve an lwc component that was created on a different computer. I was unable to retrieve the lwc component by its name from my Sandbox environment. I was able to retrieve the component.html and component.js files using a package.xml file to retrieve all LightningComponentBundles. I can also retrieve all lwc components using 'sfdx force:source:retrieve -m LightningComponentBundle'. In both cases, this does retrieve the *.js-meta.xml files from other lwc components that were already on this computer, but not the component.js-meta.xml file for the component I was trying to retrieve to this computer for the first time. I had to get the LightningComponentBundle using Workbench (with the exact same package.xml) to also retrieve the component.js-meta.xml file for this component.
Additionally, I am not able to retrieve any component using 'sfdx force:source:retrieve -m LightningComponentBundle:componentName' for any of my lwc components. I am able to retrieve the lwc component by right-clicking the folder in VS Code and selecting 'SFDX: Retrieve Source from Org', but only after I have added the component.js-meta.xml file to the folder (and possibly after deploying the folder with the component.js-meta.xml file in the folder).

**Comment by shetzel** [comment]
I reproduced the issue and am working on a fix now.  I'm hopeful to get this into the next patch release this Thursday.  My apologies for the incomplete fix!

**Comment by shetzel** [comment]
This should be fixed with the patch release tomorrow.  Closing this issue.  Thanks for reporting and for patiently awaiting the fixes.

**Comment by santiagobermudezparra** [comment]
i have this issue with AuraDefinitionBundle 
1)sfdx -v:
          sfdx-cli/7.19.0-c5be43915c win32-x64 node-v10.15.3
2)sfdx plugins:
no plugins installed

**Comment by elvisleonm** [comment]
SfdxError: You must specify the Aura bundle folder, not an individual component.

**Comment by sajidpeerjade** [comment]
I still same error while retrieving AuraDefinitionBundle
sfdx-cli 7.82.0 (core)
