### ISSUE TITLE
force:package:install:report --json returning invalid json

### ISSUE THREAD

**Issue by dalden1981** [forcedotcom/cli#330]
### Summary

Attempting to retrieve the results of a package install by sfdx force:\package:install:report --json.  The output starts 'ERROR:  Encountered errors installing the package!,Installation errors:' instead of valid JSON.

### Steps To Reproduce:

1.  Install package using sfdx force:package:install [attributes withheld]
1.  Attempt to get the report for the install (in JSON) by sfdx force:package:install:report --json [other attributes withheld]

### Expected result

Output in valid JSON that can be parsed by scripting language.

### Actual result

Invalid JSON that cannot be parsed.

### Additional information
SFDX CLI Version: sfdx-cli/7.48.0 win32-x64 node-v12.13.0

SFDX plugin Version:
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.3.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforce-alm 48.4.0 (core)
└─ salesforcedx-templates 48.4.0 (core)

sfdx-cli 7.48.0 (core)

OS and version:
Windows 10

**Comment by clairebianchi** [comment]
HI @dalden1981 can you give us more information on what flags you are using with the command? Also, passing this information onto the Packaging team that own this command.

**Comment by dalden1981** [comment]
@clairebianchi I just included the parameters for TARGETUSERNAME, PACKAGE, NOPROMPT, and JSON for the package install.  For the install report TARGETUSERNAME, REQUESTID, and JSON.

**Comment by shetzel** [comment]
I can't reproduce this in CLI v2.14.6 and plugin-packaging v1.26.4.  The output of: `sf package install report -i 0Hf... --json` is valid JSON.  E.g.,
```
{
  "code": 1,
  "context": "Report",
  "commandName": "Report",
  "message": "Encountered errors installing the package! Installation errors: \n1) (Broker__c) Custom object tab already exists in package ....",
  "name": "PackageInstallError",
  "status": 1,
  "stack": "PackageInstallError: Encountered errors installing the package! Installation errors: \n1) (Broker__c) Custom object tab already exists in package ...",
  "exitCode": 1,
  "warnings": []
}
```
