### ISSUE TITLE
Enterprise scratch org creation v48, enable Report and Folder Sharing

### ISSUE THREAD

**Issue by lpbearden** [forcedotcom/cli#332]
### Summary
When creating an enterprise edition scratch org with v48 of the CLI Report and Folder Sharing is disabled by default. This seems to be due to the removal of orgPreferenceSettings, specifically `"analyticsSharingEnable": true`. To enable it, you must manually deploy orgSettings using api version 46 after creating the scratch org.

### Steps To Reproduce:

1.  Create Enterprise edition scratch org.
1.  Push code to new scratch org.

### Expected result

Code should push to the scratch org without issue, as it did in previous versions of the CLI.

### Actual result

```
Error  sfdxsrc/GRSbasic/profiles/GRS Basic.profile-meta.xml                                            Permission EditReports depends on permission(s): RunReports
Error  sfdxsrc/common/profiles/GRS Business User.profile-meta.xml                                      Permission EditReports depends on permission(s): RunReports
Error  sfdxsrc/common/profiles/GRS Developer.profile-meta.xml                                          Permission EditReports depends on permission(s): RunReports
Error  sfdxsrc/common/profiles/GRS System.profile-meta.xml                                             Permission EditReports depends on permission(s): RunReports
Error  sfdxsrc/common/permissions/IntegrationPermissionSets/Deploy_Integration.permissionset-meta.xml  Permission ModifyAllData depends on permission(s): EditPublicReports, EditReports, ManageDashboards
```

### Additional information
The issue occurred in v47, but was remedied by allowing `"analyticsSharingEnable": true` to still work in that version. Now with v48, there is no way to automatically turn on Report and Folder Sharing when creating scratch orgs. Here are some trailblazer community threads detailing the issue. 

[Thread 1](https://success.salesforce.com/0D53A00004h5uxn)
[Thread 2](https://success.salesforce.com/0D53A00004QIjWD)
[Thread 3](https://success.salesforce.com/0D53A00004cwZso)

**Comment by yippie** [comment]
PLEASE FIX.

To make it worse, this setting is forced on/true in all Salesforce orgs created in the last 6 years and if anyone turns it on they can never turn it off.

There must be a way to develop with this on as it is a dead setting that arguable should never be off in a scratch org.

**Comment by lpbearden** [comment]
To close the loop on this @yippie the setting needed in your scratch org definition file is this:
``` 
"analyticsSettings": {
    "enableAnalyticsSharingEnable": true
}
```

It doesn't seem to be surfaced anywhere but we found it after opening a case.

**Comment by yippie** [comment]
> To close the loop on this @yippie the setting needed in your scratch org definition file is this:
> 
> ```
> "analyticsSettings": {
>     "enableAnalyticsSharingEnable": true
> }
> ```
> 
> It doesn't seem to be surfaced anywhere but we found it after opening a case.

That is correct, that is the setting needed, however, it has been deprecated and does not work in the scratch def anymore. However, Enterprise scratch orgs have this setting OFF and Salesforce has removed the API to turn it on because the setting is dead and has been forced ON for all new orgs in the last 7 years.

The real issue is that Enterprise scratch orgs are created with this setting default OFF. An org configuration that is, for all practical purposes, completely dead.

**Comment by lpbearden** [comment]
I agree that it should be on by default. 

The above setting though is not deprecated as it is in the new format for settings. If you use the above command you get no deprecation warning unlike the old value of:
    ```"orgPreferenceSettings": {
        "analyticsSharingEnable": true
    }```

**Comment by yippie** [comment]
well look at that, when was that added? in v47 when they first deprecated orgPreferenceSettings there was no migration path for analyticsSharingEnable

**Comment by apschwartz** [comment]
I see this issue is closed, but I am not sure why.  In v47 I was able to automatically enable Folder Sharing in an Enterprise Scratch org by putting  "features": ["EinsteinAnalyticsPlus"] in my scratch def json file.  However as of v48 it appears this no longer enables Folder Sharing and causes new metadata incompatibilities when we try to push to our Sandboxes that don't have EinsteinAnalyticsPlus enabled.

Was a solution found here to automatically enable Folder Sharing in a v48 Enterprise Scratch org?

@yippie @lpbearden

**Comment by veaux** [comment]
@apschwartz The answer should be what was posted by @lpbearden. This works as of v48 even though as said not documented. The setting you used for EinsteinAnalyticsPlus requires a separate license. If all you are trying to do is enable Enhanced Folder sharing use the setting posted here by @lpbearden.

**Comment by dieffrei** [comment]
Are you guys completely sure about the solution of "Permission EditReports depends on permission(s): RunReports".
It didn't fixed this issue in our case.
