### ISSUE TITLE
Issue creating scratch org with enablePardotEnabled setting

### ISSUE THREAD

**Issue by damiepsz3** [forcedotcom/cli#333]
### Summary

I've been creating scratch org with the same config file for the last 6 months and was working perfectly. Since last week I'm unable to deploy the settings of the project. It seems the issue is directly related to Pardot.

### Steps To Reproduce:

1.  Use the following scratch def json file:
`{
  "orgName": "AFS Intercultural Programs",
  "edition": "Developer",
  "features": [
    "Communities",
    "ContactsToMultipleAccounts",
    "ProcessBuilder",
    "Sites"
  ],
  "settings": {
    "pardotSettings": {
      "enablePardotEnabled": true
    },
    "nameSettings": {
      "enableMiddleName": true
    },
    "communitiesSettings": {
      "enableNetworksEnabled": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "partyDataModelSettings": {
      "enableConsentManagement": true
    }
  }
}`

2. run `sfdx force:org:create -s -f config/project-scratch-def.json -a afsdamianfork -d 30 --json`

### Expected result

Scratch org created with the shape specified in the def file.

### Actual result

The following text:
`{
  "status": 1,
  "name": "ProblemDeployingSettings",
  "message": "Failed to deploy settings to scratch org.",
  "exitCode": 1,
  "commandName": "OrgCreateCommand",
  "stack": "ProblemDeployingSettings: Failed to deploy settings to scratch org.\n    at ALMError (/Users/damiepsz3/.local/share/sfdx/client/7.49.1-2b6ba86a25/node_modules/salesforce-alm/dist/lib/core/almError.js:50:19)\n    at settings.createDeployDir.then.catch.err (/Users/damiepsz3/.local/share/sfdx/client/7.49.1-2b6ba86a25/node_modules/salesforce-alm/dist/lib/core/scratchOrgApi.js:672:37)\nOuter stack:\n    at Function.wrap (/Users/damiepsz3/.local/share/sfdx/client/7.49.1-2b6ba86a25/node_modules/salesforce-alm/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at OrgCreateCommand.catch (/Users/damiepsz3/.local/share/sfdx/client/7.49.1-2b6ba86a25/node_modules/salesforce-alm/dist/ToolbeltCommand.js:246:46)",
  "warnings": []
}`

Or without the --json flag:
![image](https://user-images.githubusercontent.com/5541348/76018344-bd5e4f00-5efe-11ea-9730-959e62eb2694.png)

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.49.1-2b6ba86a25 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.4.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.5.0 (core)
└─ salesforce-alm 48.6.0 (core)

**OS and version**: MacOS 10.15.3

**Comment by clairebianchi** [comment]
@damiepsz3 This sounds like an issue with that Pardot setting. Would you please create a case with Salesforce Support?

**Comment by adamerstelle** [comment]
I just ran into this issue as well (and have reviewed #322 to see if it would help). I have a support ticket with Partner Support...will see how it goes and will post back when I'm up and running.

**Comment by mz1173** [comment]
For anyone still running into this, I was able to get around this error by adding Pardot to the features array. It's worth noting that Pardot is not a documented feature in the [sfdx docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file_config_values.htm). 

Here is the relevant part of my config:
`{
  "orgName": "Salesforce - Dev Org",
  "edition": "Developer",
  "features": ["Pardot"],
  "settings": {
    "pardotSettings": {
      "enablePardotEnabled": true,
      "enablePardotAppV1Enabled": true,
      "enableEngagementHistoryDashboards": true,
      "enableB2bmaAppEnabled": false,
      "enableProspectActivityDataset": false
    }
  }
}`

**Comment by ekapner** [comment]
Right now, the Pardot feature is indicated as not public in our internal report - so that means that we don't include it in the public-facing documentation. I can check with the team to see if that designation is in error.

**Comment by dinhphieu** [comment]
Checking in 2024, has anyone found a better way to enable Pardot in scratch orgs?

We're currently following @mz1173's solution (btw thanks a lot for that!) but orgs are failing 7 times out of 10 with:
>A scratch org creation was rejected due to A fatal signup error occurred. Please try again. If you still see this error, contact Salesforce Support for assistance

We have a "non-so-sane" retry method to try until it succeeds, but obviously it's not a good long-term solution, and neither a short-term one I believe

I have a closed case #41836046-SF slightly related to this, where we're creating orgs based on a snapshot with Pardot enabled which caused 100% fails, if anyone in the core team is interested to take a look at
