### ISSUE TITLE
Unable to explicitly target Aura bundles in .forceignore

### ISSUE THREAD

**Issue by toddhalfpenny** [forcedotcom/cli#335]
I'm trying to be very specific in my forceignore (so I don't pull down things from sratch orgs that I don't want - e.g. all the bits created if I create a community declaratively), but in doing so I've realised I can't specifically target Aura bundles, and as such I open up some dangerous wildcarding.

For example;
Version: sfdx-cli/7.48.0-a71f8c6899 linux-x64 node-v10.15.3

I can target everything else with filename.extension type syntax (e.g `Default_Navigation.navigationMenu`), but for Aura I have to just supply the name of the directory of the component (e.g. `loginForm` - which is one of the components auto generated by Salesforce). 

If I use `loginForm` though this also means anything else starting with `loginForm` to be ignored (e.g. loginForm.cls, or loginFormUpdated.page).

I might be missing some trick to specifically target Aura bundles, but my GoogleFu is failing me.

**Comment by clairebianchi** [comment]
@toddhalfpenny I would recommend posting your question in the [SFDX Trailblazer community ](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1)
