### ISSUE TITLE
Attempting to push unchanged connected app metadata fails

### ISSUE THREAD

**Issue by laurakolker** [forcedotcom/cli#336]
### Summary

If you create a connected app in a scratch org and pull it, then attempt to push that pulled metadata to a different scratch org the push fails. I discovered from this forum post that the problem is the pulled metadata includes a consumer key and this isn't allowed to be pushed:
https://salesforce.stackexchange.com/a/236246
The error is a little opaque, especially if you're new to sfdx, and are still getting the hang of what the different commands are actually doing. It took a couple of rounds of internet research to interpret it:
So, you _can_ workaround this bug by simply removing the consumerkey from the metadata.

### Steps To Reproduce:

1.  Create a connected app in a scratch org
1.  Pull changes: $ sfdx force:source:pull
1. Make a new scratch org: $ sfdx force:org:create -s -f config/project-scratch-def.json -a testconsumerkeybug
1. Push unchanged metadata to new org: $ sfdx force:source:push

### Expected result

Either (1) pull the connected app metadata without the consumer key or (2) if there's a user story for keeping the consumer key in the pulled metadata, then a more action oriented error would be helpful. Something like: "You are trying to push a connected app with the consumerkey specified, but that's not allowed. Remove the consumerkey field from the xml file before pushing."
In short, its pretty confusing that unchanged metadata you've pulled isn't allowed to be pushed, so some kind of additional clues in the error handling would be really great, if that's on purpose.

### Actual result

See screenshot of terminal output
![consumerkey-output](https://user-images.githubusercontent.com/5496196/76101614-b6861980-5f9c-11ea-860a-cf4031e43426.png)

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
$ sfdx --version
sfdx-cli/7.48.0-a71f8c6899 linux-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
$ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.3.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.4.0 (core)
└─ salesforce-alm 48.4.0 (core)

sfdx-cli 7.48.0 (core)
**OS and version**:
Ubuntu PopOS 19.10

**Comment by clairebianchi** [comment]
@laurakolker, thank you for the feedback. Sounds like the documentation on connected apps needs to be improved. I am going to take that back to our doc team.

**Comment by jshackell-sfdc** [comment]
We've added a troubleshooting topic about this to the SFDX Dev Guide -- it should be published soon!  Thx.
