### ISSUE TITLE
Maximum Call Stack Size Exceeded Exception

### ISSUE THREAD

**Issue by highered1** [forcedotcom/cli#338]
### Summary

Running sfdx force:source:convert results in a "Maximum call stack size exceeded" exception message.

### Steps To Reproduce:

1. Edit the package.xml file to refer to a Workflow that does not exist in the Workflow metadata source directory (this may work with other objects--have not checked).
1. Run sfdx force:source:convert -d mdapi_converted -x manifest/package.xml

### Expected result

The user should see the following message: "Source was successfully converted to Metadata API format and written to the location: .../mdapi_converted"

### Actual result

No files written to the destination location and the following message: "Maximum call stack size exceeded"

### Additional information

**SFDX CLI Version**: sfdx-cli/7.49.1-2b6ba86a25 darwin-x64 node-v10.15.3

**SFDX plugin Version**: 48.4.1 (core)

**OS and version**: Mac OS Catalina 10.15.2

I was on the process of fixing deployment errors when this started to happen. Usually this meant editing the package.xml file and/or editing metadata to review references to fields that refer to unavilable managed packages and so on. This is similar to issue #280 which was closed without resolution. 

What causes this issue is a mismatch between the package.xml file and the source metadata it references. In my case, a reference to a workflow in the package.xml file that does not exist in the source directory in .../default/workflows/, will result in a "Maximum call stack size exceeded" exception message. 

Due to the fact that the exception message doesn't contain any details about where the conversion process failed, I spent over a day tracking this problem down. This could be resolved by including the line number in the package.xml file and/or the missing metadata file information in the exception message.

Update 3/9/20: Upgraded JDK to [11.06+10.](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot) No change. 
Update 3/10/20: I found the cause of the issue and can reproduce it. Edited the details accordingly.

**Comment by clairebianchi** [comment]
@highered1 Thank you for digging into the error message. I am putting a ticket on our backlog to get this updated with better information

**Comment by mshanemc** [comment]
this is fixed since we switched to the new plugin-source
