### ISSUE TITLE
Unable to source:retrieve MutingPermisionSet

### ISSUE THREAD

**Issue by bingwang0** [forcedotcom/cli#339]
### Summary

_A Muting Permission Set in a Permission Set Group in a sandbox cannot be retrieved by source:retrieve  _.

### Steps To Reproduce:

1.  Create a Muting Permission Set in a sandbox
2.  Try retrieving it by sfdx force:source:retrieve -m "MutingPermissionSet:permission_set_api_name"
3.  The command failed with "cannot read property 'metadataName' of undefined"
4.  Org Browser can see the permission set but retrieving it ended up with the same result (not surprisingly)

<img width="914" alt="Screen Shot 2020-03-08 at 11 49 35 PM" src="https://user-images.githubusercontent.com/3876018/76355693-24a74500-62eb-11ea-851b-4bfa2d97853b.png">

### Additional information - Environment

**SFDX CLI Version**:
7.49.1
**SFDX plugin Version**:
48.4.1
**OS and version**:
Windows 10

**Comment by anthonyberan** [comment]
Verifies it fails with force:source:pull as well.
![image](https://user-images.githubusercontent.com/6894510/76487108-8d231e80-63de-11ea-8484-55eaec7a6eb2.png)

### Additional Information - Environment
**SFDX CLI Version:**
7.49.1
**SFDX plugin Version:**
48.4.1
**OS and version**
Mac 10.14.6

**Comment by clairebianchi** [comment]
@bingwang0  we are going to investigate thank you

**Comment by FabienTaillon** [comment]
I assume it's not that easy to have a "CLI supported" column in the Metadata Coverage Report ?

**Comment by clairebianchi** [comment]
@FabienTaillon sadly no, we have had internal discussions, but it is a lot more work than it would seem.

**Comment by FabienTaillon** [comment]
Also, MutingPermissionSet is listed as supported by the Metadata API, so letting aside the CLI, shouldn't this mean that it should be documented [here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_types_list.htm), and available through at least a package.xml ?

Or is it just a bug on the API side, it's listed as available in the Metadata API but it's not ?

**Comment by SalesforcePetr** [comment]
Hi there, when do you plan to support muted permission sets please? This ticket is a sleeping beauty ;-)

**Comment by Daniel-Dragon** [comment]
Going on 9 months now, is there an update on this? We just got bit by the gap in functionality.

**Comment by SCWells72** [comment]
Hey, @clairebianchi. Any ETA on this by chance?

**Comment by maxlawrence** [comment]
Another voice to add to the chorus! If Permission Set Groups (and the Muting inherent to them) are something Salesforce wants to make easy to work with via CLI, we need to be able to get them out of sandboxes effectively!

**SFDX CLI Version:**
7.82.0
**SFDX plugin Version:**
50.8.0
**OS and version:**
Windows 10

**Comment by mdonnalley** [comment]
We're working on a fix for this now and plan to have it included in our next release

**Comment by steals** [comment]
Is this fix for `retrieve|pull` only command or the `deploy|push` will also be fixed?

**Comment by ytiq** [comment]
As for a side note. I used MutingPermissionSets on project and we put them in separate metaDataApi folder and used mdapi:deploy /retrive for them

**Comment by mshanemc** [comment]
Given the fix, and the comments (seems to work for all operations) I'm closing this one.  Someone reopen if you still see problems with mutingPermSets

**Comment by rajesh-kemisetti** [comment]
I’m seeing this issue still reproducible and I have re tried after doing sfdx update and seeing the Same error.
 I see the issue was closed but it’s not clear whether it was fixed and if it worked for anyone.

**Comment by dieffrei** [comment]
@mshanemc can you reopen this issue?
I agree with @rajesh-kemisetti this issue still happening even updating to the latest cli version.
CC: @clairebianchi

**Comment by shetzel** [comment]
@rajesh-kemisetti @dieffrei - what version of the salesforcedx plugin are you using?  If you're pinned to an old version you won't get the updates.  Multiple people on the team can not reproduce this issue after following the steps from the original post.  If there are different steps to reproduce this please post what they are.  Another option for `force:source:retrieve` and `force:source:deploy` is to use the VS Code extension which currently (but not for long) uses a different library for those commands.

**Comment by dieffrei** [comment]
@shetzel thank you for fast reply.

Indeed, in our docker image We had an out-of-update cli version.
After update to the latest version, got the error fixed.
Thank you

CC: @rajesh-kemisetti

**Comment by rajesh-kemisetti** [comment]
@shetzel I am still seeing this issue. Below screen shot shows the CLI version and the package that just has the muted perm set and the retrieval doesn't work. I tried running the command in VS code via ctrl+shift+p and also with the terminal and got the same error

![image](https://user-images.githubusercontent.com/18335231/122237345-4186dc80-ce8d-11eb-9d15-bfceb2db9fa9.png)

CC: @dieffrei
