### ISSUE TITLE
force:source:pull on Scratch Org with Community causes ERROR:  Metadata API received improper input

### ISSUE THREAD

**Issue by BrettMN** [forcedotcom/cli#34]
### Summary

I create a scratch org, then enable Communities, create a community, then try `sfdx force:source:pull` through the CLI or the VSCode command palette.  It results in the following Error:

> ERROR:  Metadata API received improper input. Please ensure file name and capitalization is correct. Load of metadata from db failed for metadata of type:AppMenu and file name:AppSwitcher.

### Steps To Reproduce:

1. create a scratch org
1. enable Communities
1. create a community
1. try `sfdx force:source:pull` through the CLI or the VSCode command palette
1. get error

### Expected result

No error and to pull the changes from the scratch org

### Actual result

Error `ERROR:  Metadata API received improper input. Please ensure file name and capitalization is correct. Load of metadata from db failed for metadata of type:AppMenu and file name:AppSwitcher.`

### Additional information

![screen shot 2019-02-16 at 9 48 56 pm](https://user-images.githubusercontent.com/3488212/52908122-b2257c00-3234-11e9-9880-381b25add0f6.png)

**VS Code Version**:
Version 1.32.0-insider (1.32.0-insider)

**SFDX CLI Version**:
sfdx-cli/6.53.0-67a9cbb60c (darwin-x64) node-v8.9.4

**OS and version**:
macOS Mojavie
10.14.3

**Comment by clairebianchi** [comment]
@BrettMN We are looking into this issue, thank you for bringing it to our attention.

**Comment by clairebianchi** [comment]
@BrettMN, this is a known issue with App Switcher. Here is the Know Issue with a documented workaround: https://success.salesforce.com/issues_view?id=a1p300000008e2HAAQ

**Comment by BrettMN** [comment]
Hi @clairebianchi thanks for the response.  Unfortunately the issue you linked to talks about it only occurring when a connected app is installed and the work around is to uninstall the Package associated with the Connected app before trying to pull the source.  

Problem is I don't have a Connected app:
<img width="1411" alt="screen shot 2019-02-23 at 2 39 37 pm" src="https://user-images.githubusercontent.com/3488212/53291469-649b9880-3779-11e9-9af2-40bdae008d09.png">

And I don't have any installed packages:
<img width="1063" alt="screen shot 2019-02-23 at 2 39 48 pm" src="https://user-images.githubusercontent.com/3488212/53291470-67968900-3779-11e9-8013-91bf05d4df83.png">


I have a scratch org created with the following definition:
```
{
    "orgName": "WIPDeveloper.com",
    "edition": "Developer",
    "features": [
        "Communities"
    ]
}
```

Than I then created a community in.

Do you have any workarounds that would apply in to this scenario? 

And maybe we could reopen this issue?

**Comment by clairebianchi** [comment]
@kfidelak94 do you have any insight into this issue?

**Comment by BrettMN** [comment]
@clairebianchi should I assume this issue is dead and create a new issue?

**Comment by kfidelak94** [comment]
@BrettMN This issue is in fact fixed in Summer'19.  The KI description is written more narrowly than the actual issue actually is; sorry this is confusing/misleading.   I believe another workaround is to put these component types into the .forceignore file to get around the error during source:pull.

**Comment by BrettMN** [comment]
thanks @kfidelak94 adding the following to my `.forceignore` allowed me to pull the changes from the scratch org. 

```
AppMenu
AppSwitcher
```

**Comment by muenzpraeger** [comment]
I recommend to always keep an eye on the `.forceignore` in the sample apps. We keep them always up-to-date with what we think are good recommendations, as well as to workaround bugs like this one.

https://github.com/trailheadapps/lwc-recipes/blob/master/.forceignore

**Comment by BrettMN** [comment]
Maybe the example apps could have explanations for why things are in the `. forceignore ` a person outside Salesforce might think they are project specific and not recommended workarounds for bugs/issues
