### ISSUE TITLE
plugins:install not properly installing from github

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#342]
### Summary

Using github to install a private pluging does not fully/properly install the plugin. After install, we must run `sfdx plugins:link ~/.local/share/sfdx/node_modules/MavensCLI` to be able to use the plugin

### Steps To Reproduce:

1.  Create an SFDX plugin
1.  Compile with pre-pack
1.  check compiled code into a private github repo
1.  Make sure cli/plugin is fully unlinked from the development repo (or use a new machine)
1.  Make sure testing machine has git cli authenticated to Github using https 
1.  Run `sfdx plugins:install https://github.com/<user>/<gitRepo>`
1.  Attempt to run the plugin using `sfdx <my>:<command>`

### Expected result

Custom plugin runs

### Actual result

Error: Cannot find module '~/.local/share/sfdx/node_modules/<my plugin module>'
    at Function.resolve (~/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at fetch (~/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/@oclif/config/lib/plugin.js:107:31)
    at Plugin.findCommand (~/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/@oclif/config/lib/plugin.js:125:21)
    at Object.load (~/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/@oclif/config/lib/plugin.js:58:72)
    at Config.runCommand (~/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/@oclif/config/lib/config.js:149:27)
    at Main.run (~/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/@oclif/command/lib/main.js:21:27)
    at Main._run (~/.local/share/sfdx/client/7.48.0-a71f8c6899/node_modules/@oclif/command/lib/command.js:44:31)

### Additional information
 Running `sfdx plugins:link ~/.local/share/sfdx/node_modules/<my plugin module>` after running plugin:install fixes this error

Seems to only happen in macOS. Linux based CI dockers do not require plugins:link to be run

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.49.1-2b6ba86a25 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.4.1
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.5.0
└─ salesforce-alm 48.6.0

sfdx-cli 7.49.1 (core)
**OS and version**: macOS 10.15.3 Catalina

**Comment by clairebianchi** [comment]
@yippie can you try the clone URL with the .git at the end of the URL? That should work.

**Comment by yippie** [comment]
I am using the clone URL
`sfdx plugins:install https://github.com/mavens/P-TOOL-MavensCLI.git#master`
that is the exact command I am using

**Comment by amphro** [comment]
It's a bug that the install doesn't show the error but in general, this is a problem with setup, usually auth into a private repo. All we are doing is a `yarn add`. Here is what I get:

```
-> yarn add https://github.com/mavens/P-TOOL-MavensCLI.git#master
...
remote: Repository not found.
fatal: repository 'https://github.com/mavens/P-TOOL-MavensCLI.git/' not found
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

I'm assuming it is private. You can try to run the add to see what kind of error you get.

**Comment by yippie** [comment]
Yes, it is a private repo,

Running `yarn add https://github.com/mavens/P-TOOL-MavensCLI.git#master` runs successfully and give me no errors and I find my package in the node_modules folder after.

'sfdx plugins:install' Does run successfully and installs the package into `~/.local/share/sfdx/node_modules/` successfully. After that, my commands are half recognized. My cli plugin namespace and commands are recognized and output, but running one errors.

`sfdx plugins:link ~/.local/share/sfdx/node_modules/MavensCLI` is then needed to fix the commands. It appears that the install command is not running the full link step for some reason.

It is also important to note, this is only an issue on macOS. Ubuntu does not have this issue, we are installing our plugin in our CI process without issue, only on our local dev machines do we have to add the second manual link step

**Comment by amphro** [comment]
That is a lot of useful information. Thanks.

**Comment by goto-dev-null** [comment]
Is this going to be addressed? It seems like SFDX is just doing some matching to determine if the param is a URL or a yarn package, just adjust it to accept the branch....

Another way to reproduce with ssh:
`sfdx plugins:install "ssh://git@github.com/salesforcecli/plugin-user#master"`
Result:
`error An unexpected error occurred: "https://registry.yarnpkg.com/@sh:%2f/git: Request \"https://registry.yarnpkg.com/@sh:%2f/git\" returned a 405".`

**Comment by AllanOricil** [comment]
@amphro In my case I created an Image with the plugin already installed. When the image run in Github Action, the plugin is not available. When I run the same image locally, the plugin is available. Could it be related? 

https://github.com/forcedotcom/cli/issues/1273

**Comment by mshanemc** [comment]
I'm able to install `sfdx plugins:install https://github.com/mshanemc/sfdx-sosl` on macos (a public repo).

Does it work now?  Or is it limited to private repos?

**Comment by goto-dev-null** [comment]
@mshanemc But can you supply a branch like `sfdx plugins:install https://github.com/mshanemc/sfdx-sosl#master`?

**Comment by goto-dev-null** [comment]
Not the original author but my question still stands. Shall I create a new issue or can this one be reopened?
