### ISSUE TITLE
sfdx force:source:pull does not retrieve changes to permission sets

### ISSUE THREAD

**Issue by jeremyhiggs** [forcedotcom/cli#343]
### Summary

After creating a new field, sfdx force:source:pull does not retrieve changes to the permission sets.

### Steps To Reproduce:

1.  Add a field to an existing object
1.  sfdx force:source:pull

### Expected result

Apart from the object field and object translations, the permission sets should have also been marked as changed remotely, and pulled.

### Actual result

No (reported) change to the permission set. A force:source:retrieve does capture these (but takes a LOT longer).

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
7.50.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
[~]$ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
etcopydata 0.4.4
generator 1.1.2 (core)
salesforcedx 48.5.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.6.0 (core)
└─ salesforce-alm 48.7.0 (core)

sfdx-cli 7.50.0 (core)
sfdx-retrieve-deploy-companion 1.0.6
texei-sfdx-plugin 1.2.0

**OS and version**:
macOS Catalina 10.15.3

**Comment by shetzel** [comment]
@jeremyhiggs - I don't understand the problem based on the repro steps.  Permission sets are a separate entity from custom objects.  If I change a permset and pull, the permset is retrieved.  If I add a field to that custom object and pull, the new field is retrieved.  Just by adding a new field to the custom object doesn't change anything about the permset.

Feel free to reopen with different repro steps or to clarify, but as is this is working as designed.

**Comment by jeremyhiggs** [comment]
> Just by adding a new field to the custom object doesn't change anything about the permset.

It does, and you can demonstrate that by doing `sfdx force:source:retrieve` and looking at the changes. Adding a new field would automatically add that field to the existing permission sets. force:source:retrieve picks up those changes, but force:source:pull does not.

**Comment by shetzel** [comment]
I just did that and there is no change in the permset.  To be clear this is what I did:
1. Create a custom object with 2 fields.
2. source:pull --> object and fields are retrieved
3. create a permset that adds read perms to the field on that custom object
4. source:pull --> permset is retrieved
5. add a new field to the custom object
6. source:pull --> field is retrieved
7. source:retrieve -p <path_to_permset_file> --> retrieves the permset that is exactly the same as before.

To me, the results of step 7 make sense based on the permset that I created and how I understand them to work.  I.e., you have to explicitly set the perms on any new fields.  Maybe there is a difference between how we setup our permission sets?

**Comment by jeremyhiggs** [comment]
Here's the steps that I would take:
1. Create a custom object
2. Create a permset (i.e. the object and permset exist before adding new fields)
...
3. Add a new field "foo__c" to the custom object, no changes to the permset through the web UI
4a. source:retrieve would return a permset that has fieldPermissions for "foo__c" automatically added, along with new object field files for foo__c
4b. source:pull would return only the new object field files for foo__c

As the fieldPermissions are added automatically to existing permsets as a result of creating a new custom field, should force:source:pull not also retrieve those permset changes?

I'll give an example. In a scratch org, I'm creating a new field on an object, using the web UI.

force:source:pull results in:
```
sfdx force:source:pull --targetusername="ecoenergy_scratch" --apiversion=46.0
=== Pulled Source
STATE    FULL NAME                        TYPE          PROJECT PATH
───────  ───────────────────────────────  ────────────  ────────────────────────────────────────────────────────────────────────────────
Add      Transaction__c.Test__c           CustomField   force-app/main/default/objects/Transaction__c/fields/Test__c.field-meta.xml
Changed  Transaction__c                   CustomObject  force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
Changed  Transaction__c-Charge Layout     Layout        force-app/main/default/layouts/Transaction__c-Charge Layout.layout-meta.xml
Changed  Transaction__c-Fee Layout        Layout        force-app/main/default/layouts/Transaction__c-Fee Layout.layout-meta.xml
Changed  Transaction__c-Coupon Layout     Layout        force-app/main/default/layouts/Transaction__c-Coupon Layout.layout-meta.xml
Changed  Transaction__c-Payment Layout    Layout        force-app/main/default/layouts/Transaction__c-Payment Layout.layout-meta.xml
Changed  Custom Standard User             Profile       force-app/main/default/profiles/Custom Standard User.profile-meta.xml
Changed  Custom Company Communities User  Profile       force-app/main/default/profiles/Custom Company Communities User.profile-meta.xml
Changed  Admin                            Profile       force-app/main/default/profiles/Admin.profile-meta.xml
```
(No permset changes are pulled down)

`force:source:retrieve -p force-app/main/default/permissionsets` (after doing a git reset) resulted in no changes to the permsets, which is what you had mentioned above.

However, `force:source:retrieve` with a manifest results in the modified permsets being retrieved.

The diff to one of the permsets:
![Screenshot 2020-03-26 at 9 21 50 AM](https://user-images.githubusercontent.com/182224/77609987-489d9400-6f43-11ea-85c3-1bd2e98d338d.png)

(The Case field is not related to this issue.)

So it seems that both force:source:pull and force:source:retrieve do not retrieve the permset changes after a new field is created.

**Comment by shetzel** [comment]
> As the fieldPermissions are added automatically to existing permsets as a result of creating a new custom field..
You mean based on seeing them in the UI?  I don't see them when retrieved via the metadata API, which is what all the retrieval commands (source:pull, source:retrieve, mdapi:retrieve) use to get the data.  I see your screenshot and I've tried many times to reproduce without success.  In the end, all deploys and retrieves use a manifest.  I.e., `sfdx force:source:retrieve -p path/to/file` builds a manifest that is sent via the SOAP API.  If you set the `SFDX_MDAPI_TEMP_DIR` env var to a known location you can see the generated manifests and constructed mdapi format files.

Regardless, the permset should behave the same way with our without those field permissions set to false since that is the default.  If you were setting perms on those fields in the UI for the permset and they were not pulling then that would be a much bigger problem.

I did all this using api version 48.0.  Maybe there is a difference between 48.0 and 46.0?  I mention that because I see you overrode the apiVersion in the pull command example you provided.  Or maybe if you have a `sourceApiVersion` set for your project that is causing the difference between what we are seeing.
