### ISSUE TITLE
Validation and progress bar

### ISSUE THREAD

**Issue by maaaaarco** [forcedotcom/cli#347]
### Summary
When validating a package using the command `force:source:deploy -c` if there's already another deployment in progress this happens:

<img width="498" alt="Screenshot 2020-03-19 at 13 57 30" src="https://user-images.githubusercontent.com/8080936/77070154-04157400-69ea-11ea-82d4-275d3019045f.png">

Even the message _Successfully validated the deployment_ is wrong, since the validation request is waiting for the other deployment to finish.

### Steps To Reproduce:

1.  Start a deployment in your Sandbox
1.  While the deploy is running, start a validation request
1. You should get the same weird behavior 

### Expected result

Progress bar stays idle until the other deployment finish and the message _Successfully validated the deployment_  only appears after the validation is completed.

### Actual result

Progress bar does not refresh on the same line. Message _Successfully validated the deployment_  is displayed before the validation finishes

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.50.0-9030e49cbb darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.5.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.6.0 (core)
└─ salesforce-alm 48.7.0 (core)

sfdx-cli 7.50.0 (core)

**OS and version**:
MacOs Mojave

**Comment by mshanemc** [comment]
W-7354540

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9300126](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MQz4YAG/view)
