### ISSUE TITLE
Include flow coverage in force:apex:test:run or force:apex:test:report output

### ISSUE THREAD

**Issue by mkreth** [forcedotcom/cli#350]
**Is your feature request related to a problem? Please describe.**
Coverage of flows by Apex unit tests is currently hard to determine and track. Tracking flow coverage should be as easy as tracking Apex code coverage.

**What are you trying to do**
The output of force:apex:test:run and force:apex:test:report should include both code coverage and flow coverage. Flow coverage should also be written to the output file of the Apex test run results similarly to the code coverage results. This would allow to parse flow coverage output and create a flow coverage report, e.g. in a CI tool.

**Describe the solution you'd like**
When running sfdx force:apex:test:run from a CI tool, I'd like to find flow coverage results in the output file or even in a separate output file similar to the code coverage results. This could then be transformed into a format suitable to be presented in a build tool, e.g. in a Jenkins dashboard.

**Describe alternatives you've considered**
Writing a separate sfdx plugin could be an option but would duplicate existing code - as the json output of a force:source:deploy execution already contains code and flow coverage results. Hopefully this can be reused.
Another alternative would be to write a separate tool executed right after executing apex unit tests with sfdx. The separate tool would simply query FlowCoverage records and write them to a file. Again, this would need to duplicate code to authenticate, to query FlowCoverage records and to output flow coverage.

**Comment by clairebianchi** [comment]
@mkreth Thank you for the feedback I am passing it over to the PM that owns force:apex:test:run.

**Comment by smaddox-sf** [comment]
Hi @mkreth  - Thanks for the feedback on the difficulties tracking flow test coverage.  We don't foresee incorporating Flow coverage directly into the Apex commands.  We'll think about this feedback & ways to better expose Flow test coverages in the future.
