### ISSUE TITLE
Issues to Retrieve Metadata

### ISSUE THREAD

**Issue by quanlin-guo** [forcedotcom/cli#351]
I created a new scratch org: https://sandbox-connect-innovation-6455-17108659e75.cs18.force.com/

Here is my project-scratch-def.json 
{
        "orgName": "Knowledgebase + Chatbot",
        "edition": "Enterprise",
        "hasSampleData": "true",
        "features": ["ServiceCloud","Chatbot","CPQ","Communities","Knowledge","LiveAgent","LightningServiceConsole","LiveMessage","WavePlatform"],
        "settings": {
                "lightningExperienceSettings": {
                        "enableS1DesktopEnabled": true
                },
                "mobileSettings": {
                        "enableS1EncryptedStoragePref2": false
                },
                "communitiesSettings": {
                        "enableNetworksEnabled": true
                },
                "omniChannelSettings": {
                        "enableOmniChannel": true
                },
                "liveAgentSettings": {
                        "enableLiveAgent": true
                }
        }
}

Then I created a Customer Service Community: CharlieCustomerService
Then I want to retrieve the metadata and got errors: 

sfdx force:source:pull

We can’t retrieve the specified metadata object: Audience. Certain metadata types, like Audience are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
ERROR running force:source:pull:  Entity type 'WaveApplication' is not available in this organization
Entity type 'WaveDataflow' is not available in this organization
Entity type 'WaveDashboard' is not available in this organization
Entity type 'WaveDataset' is not available in this organization
Entity type 'WaveXmd' is not available in this organization
make: *** [pull] Error 1

**Comment by rvwatch** [comment]
This is the same issue as #151. Please follow that thread for updates.

**Comment by amphro** [comment]
This seems like it is more an issue with `ERROR running force:source:pull: Entity type 'WaveApplication' is not available in this organization` more than the error on Audience type right @quanlin-guo ? I'm removing the duplicate for now.

**Comment by amphro** [comment]
The audience support is tracked in #470

**Comment by erocheleau** [comment]
For the specific errors for :

```
Entity type 'WaveApplication' is not available in this organization
Entity type 'WaveDataflow' is not available in this organization
Entity type 'WaveDashboard' is not available in this organization
Entity type 'WaveDataset' is not available in this organization
Entity type 'WaveXmd' is not available in this organization
```

I have found that you can add these lines in your `.forceignore` to tell the sfdx-cli to stop caring about it.

```
**.wds
**.wapp
**.wdf
**.wdash
**.xmd
```

These seem to all be the specific extensions for the files of the broken metadata types that are erroring out... Good luck!

**Comment by nvuillam** [comment]
I have the same issue with **sfdx-cli/7.124.0 win32-x64 node-v14.18.0** , on a sandbox with tracking activated

Items are ignored in .forceignore, but the source:pull crashes because of those items anyway

![image](https://user-images.githubusercontent.com/17500430/140761773-d305beb6-ad29-4d2a-923d-47ed9ba4acf1.png)

Did anyone find a working workaround ?

**Comment by jparlin339** [comment]
I'm also still having this issue with this as well...

- sfdx-cli/7.126.0 darwin-x64 node-v14.17.1
- M1 MacBook Pro gen 1 (Apple Silicon)

`ERROR running force:source:pull:  Entity type 'WaveDataset' is not available in this organization`

**Comment by jparlin339** [comment]
> I have the same issue with **sfdx-cli/7.124.0 win32-x64 node-v14.18.0** , on a sandbox with tracking activated
> 
> Items are ignored in .forceignore, but the source:pull crashes because of those items anyway
> 
> ![image](https://user-images.githubusercontent.com/17500430/140761773-d305beb6-ad29-4d2a-923d-47ed9ba4acf1.png)
> 
> Did anyone find a working workaround ?

I fixed it! Make sure you have a Permission Set / Profile permissions setup for Wave Analytics!

**Comment by shetzel** [comment]
problem in the original post has been fixed for a while now
