### ISSUE TITLE
Push Not Changing Username References

### ISSUE THREAD

**Issue by IvanDavidHarris** [forcedotcom/cli#354]
### Summary

Note: this seems similar to #224, which is closed but there is no known issue [here](https://success.salesforce.com/issues_index?page=11&tag=Salesforce+DX). I was assuming it has therefore been fixed. Perhaps a regression?

When pushing changes from a Salesforce DX project to a scratch org and the changes include username references in queues and Omni-Channel presence configurations, the push fails with "In field: userName - no User named test-3y80vuxftjeu@example.com found".

### Steps To Reproduce:

1.  Setup Omni-Channel in a new scratch org. Use queue-based routing, include a queue and a presence configuration.
1.  Pull the changes into a Salesforce DX project.
1. Push the changes to a new scratch org.

### Expected result

The documentation [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_push_md_to_scratch_org.htm) states "push command replaces the username with the scratch org’s administrator username", so the push should have succeeded and the username reference should have been updated.

### Actual result

```
TYPE   PROJECT PATH                                                                   PROBLEM
─────  ─────────────────────────────────────────────────────────────────────────────  ──────────────────────────────────────────────────────────────────────
Error  force-app/main/default/presenceUserConfigs/Expert.presenceUserConfig-meta.xml  In field: userName - no User named test-3y80vuxftjeu@example.com found
Error  force-app/main/default/queues/Cases.queue-meta.xml                             In field: userName - no User named test-3y80vuxftjeu@example.com found
ERROR running force:source:push:  Push failed.
```

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

`sfdx-cli/7.52.0-c5ad5c3eff darwin-x64 node-v10.15.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

```
@oclif/plugin-autocomplete 0.1.5
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.7.1
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.7.0
└─ salesforce-alm 48.8.0

sfdx-cli 7.52.0 (core)
```

**OS and version**:

macOS Catalina Version 10.15.3

**Comment by clairebianchi** [comment]
@IvanDavidHarris this is an issue with the metadata not the CLI. I am going to pass this information on to that team, but it would also be beneficial for you to submit a case through support. Thank you for your feedback.
