### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by jmAlive** [forcedotcom/cli#357]
**Is your feature request related to a problem? Please describe.**
Yes, the version control of Profiles is not as broken down down as the objects are.

As a team of developers, we are running into lots os merge conflicts and unnecessary overhead with profiles not being broken down as objects are. 

**What are you trying to do**
A description of the outcome you are hoping to achieve 
As a team of 20 developers, we would like to easily transition from manually updating profiles, having a workaround for profiles, and use instead the SFDX known breaking down of metadata format for profiles. This will allow a large team to collaborate easier throuh git.

**Describe the solution you'd like**
We'd like the Profiles to be broken down as the objects are broken down into very different folder structure. Similar to how objects are broken down in SFDX.

**Describe alternatives you've considered**

Some other way of having a team of 20 collaborate and version control profiles.

**Additional context**

**Comment by clairebianchi** [comment]
@jmAlive to be transparent we no plans to plan to breakdown profiles at this time. We believe the path forward is to use Perm sets and Perm set groups, which work better with source formate and version control. If you would like to provide more details on how you are using Profiles and why you would be unable to migrate to permsets please add it here and I can pass it on to the team that owns this strategy.

**Comment by daveespo** [comment]
@clairebianchi  -- you can't set default Record Types and Page Layout Assignment via Perm Set ... that's the main reason we need to maintain unwieldy Profiles in source control for SFDX/scratch org projects
