### ISSUE TITLE
Workaround for Salesforce CLI Installation Error on macOS Catalina

### ISSUE THREAD

**Issue by clairebianchi** [forcedotcom/cli#359]
The Salesforce CLI Mac installer doesn’t work as expected on macOS Catalina or beyond. Why? These newer macOS versions require notarized digital certification. Salesforce CLI is built on Node.js, which currently doesn’t have a notarized certification with Mac. When you download the .pkg installer and double-click the file, you see an error message.

*How to Resolve the Error*

First, if you haven’t already, download (https://developer.salesforce.com/tools/sfdxcli) the CLI .pkg file.

Next, do one of the following:

* Right-click the .pkg file and select *Open*.
* Open System Preferences > Security & Privacy > General. On the displayed alert, click *Open Anyway*:

The Node.js community is aware of the issue and working to remedy it. If you would like to track this issue, read about the progress in Github (https://github.com/nodejs/node/issues/29216).

**Comment by amphro** [comment]
Fixed as of [49.6](Catalina)
