### ISSUE TITLE
Updates on quick actions default fields are not detected by force:source:pull

### ISSUE THREAD

**Issue by berardo** [forcedotcom/cli#36]
### Summary

Changes made on default fields of custom quick actions in the source code are able to be pushed to a scratch org however, the opposite is not true. On-the-fly updates on pre-existing custom actions are not tracked by sfdx, ending up with No results found.

### Steps To Reproduce:

1.  Create a new Email Quick Action for any Object (my example: Lead)
1. Add some default fields. E.g. htmlBody, textBody, Subject ...
1.  Optional: Add it to any page layout just to help you test the change
1. Pull your code (sfdx force:source:pull): This will create a file like Object.QuickActionName.quickAction-meta.xml
1. Make local changes in this file
1. Push it (sfdx force:source:push). Your changes will be reflected on your box
1. Make changes in your scratch-org (I've tested adding new default values for other fields and changing the value for existing ones)
1. Pull your code again and see: No Results Found
1. Repeat the process locally and push - Confirm that your changes made declaratively are gone

### Expected result

It should detect declarative changes.

### Actual result

It does not detect changes when pulling.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/6.53.0-67a9cbb60c (darwin-x64) node-v8.9.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@salesforce/plugin-generator 1.0.1 (core)
@salesforce/sfdx-trust 2.0.1 (core)
builtins 1.0.0 (core)
salesforcedx 45.0.12 (pre-release)

**OS and version**:
MacOS High Sierra

**Comment by clairebianchi** [comment]
@berardo We are looking into this issue internally.

**Comment by paulchensfdc** [comment]
Is this issue still happening?  I can see the correct result in Step 8: Pull your code again and see: No Results Found --> I see the correct changes reflected in my force:source:pull
