### ISSUE TITLE
How to workaround "The command line is too long." during SFDX SOQL execution

### ISSUE THREAD

**Issue by peternoges** [forcedotcom/cli#360]
Hello, I have a ~16k character sfdx soql statement to run in vscode.  

The SOQL is formatted fine.  I expected to see results. Instead I see in the "Output" tab the message "The command line is too long."

This is odd because Salesforce defines the maximum SOQL length as 100k per https://help.salesforce.com/articleView?id=000333028&language=en_US&type=1&mode=1

How can I run my 16k character soql statement in SFDX?

**Comment by amphro** [comment]
It is the command length of your shell. There is no way to work around it other than trying to find a shell that has a longer command length. 

We could use this as a feature request to support reading queries from a file rather than the command line.

**Comment by peternoges** [comment]
Thanks.  Yes please.  Let me know if I should submit a new record.  Otherwise go ahead with the feature request based on this.
Its reasonable to expect me, in visualstudio code, to paste a long ( <= 100k character) SOQL Statement into a file and regardless of saving the file I would expect to have a SFDX command pallete option for running a soql query using that long text.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9036554](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000008mJQYAY/view)

**Comment by peternhale** [comment]
fix in version 7.162.0 of sfdx-cli
