### ISSUE TITLE
Sometimes Instance URL has trailing "/" intermittently when running force:org:display

### ISSUE THREAD

**Issue by Julian88Tex** [forcedotcom/cli#361]
### Summary

Command `sfdx force:org:display --json` sometimes provides the "instanceUrl" with a trailing and other times it does. Appears to be about 50/50 from anecdotal testing.

### Steps To Reproduce:

1.  Create 4 scratch orgs using `sfdx force:org:create` with different aliases
1.  Run `sfdx force:org:display --json -u <username>` for each of the aliases

### Expected result

The instanceUrl's value will either always have a trailing `/` or will never have a trailing `/`.

i.e. https://ruby-energy-5366-dev-ed.cs26.my.salesforce.com/ & https://power-force-9974-dev-ed.cs91.my.salesforce.com/

### Actual result

This is intermittent (perhaps dependent on instance like cs26 vs cs91) but depending on random chance some will have `/` and others won't

i.e. https://ruby-energy-5366-dev-ed.cs26.my.salesforce.com/ & https://power-force-9974-dev-ed.cs91.my.salesforce.com

### Additional information
<img width="961" alt="Screenshot 2020-04-02 16 55 40" src="https://user-images.githubusercontent.com/459099/78310442-d6a8ea00-7502-11ea-9a39-ca1495486228.png">

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.52.0-c5ad5c3eff darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**: macOS 10.15.4 (19E266)

**Comment by amphro** [comment]
Ya, I  consider this a bug and something we noticed a little while ago. FYI @shetzel

**Comment by Julian88Tex** [comment]
> Ya, I consider this a bug and something we noticed a little while ago. FYI @shetzel

@amphro @shetzel thanks yeah I assume this isn't a bug in CLI as much as however the CLI is being served, but it would be nice for the CLI to standardize it for us, so from that perspective it would be a feature I suppose.

**Comment by mshanemc** [comment]
This **should** be fixed in the new open-source version.  You can try it early, here: https://github.com/forcedotcom/cli/issues/835

**Comment by mshanemc** [comment]
I'm closing this--reopen or log another issue if you see any more trailing slashes.
