### ISSUE TITLE
Error on mdapi:deploy asking for location of "server.key"

### ISSUE THREAD

**Issue by cumulus-robert** [forcedotcom/cli#363]
### Summary

Similar to #124. I experienced a similar issue in January. The root cause was OS variables vs. SFDX vs. Jenkins. Jenkins scripts needed to be updated to specify OS environment variables so SFDX could work as designed.

Between 10/2019 and 01/2020, an SFDX version was released changing certain behavior causing prior scripts to fail. No OS or other environmental change at that time. Last week, I had to re-build my Jenkins server. I used all my previous documentation from prior issue. In that, I am using SFDX version 47.15.0. This version is from January/February and was last known good version for scripts.

Jenkins works, but for only 24 hours. After 24 hours, I start to get this:

sfdx force:mdapi:deploy --wait 120 -c --deploydir /opt/bitnami/jenkins/jenkins_home/workspace/TAN-pipe_prod_validate/mdapi --targetusername robert.brown@xxxx.com --testlevel RunLocalTests
ERROR running force:mdapi:deploy: We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: ENOENT: no such file or directory, open '/opt/bitnami/jenkins/jenkins_home/workspace/TAN-pipe_prod_validate@tmp/secretFiles/ef828807-fd4d-41a0-87da-554870598fce/server.key'

### Steps To Reproduce:

1. Create Jenkins Multi-Branch Pipeline connected to a Bitbucket Git Repository
2. Wait 24 Hours for Groovy scripts to fail
3. Delete Jenkins Multi-Branch Pipeline created, create another. Groovy scripts work again.

### Expected result

I shouldn't have to delete and recreate Jenkins jobs daily. This should just work.

### Actual result

Daily my scripts begin to produce this failure:

sfdx force:mdapi:deploy --wait 120 -c --deploydir /opt/bitnami/jenkins/jenkins_home/workspace/TAN-pipe_prod_validate/mdapi --targetusername robert.brown@xxxx.com --testlevel RunLocalTests
ERROR running force:mdapi:deploy: We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Here’s the error: ENOENT: no such file or directory, open '/opt/bitnami/jenkins/jenkins_home/workspace/TAN-pipe_prod_validate@tmp/secretFiles/ef828807-fd4d-41a0-87da-554870598fce/server.key'

### Additional information

I am a partner supporting multiple organizations. This Jenkins instance is currently connected to 3 instances of salesforce.com. 

**SFDX version**:
robert@jenkins-4-vm:~$ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 47.15.0 (47.15.0)
├─ salesforcedx-templates 47.16.0
└─ salesforce-alm 47.14.0

**OS and version**:
Linux version 4.9.0-12-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.210-1 (2020-01-20)

**Comment by cumulus-robert** [comment]
I should also note that the default install of SFDX does not work. It immediately produces this failure. Going back to 47.15.0 lets me at least be able to have a semi-workable solution.

**Comment by cumulus-robert** [comment]
Just a small update. After a few days of working with this, it appears I don't have to delete the whole pipe, but just the branch which effectively just deletes a folder in the OS. When branch is recreated and ultimately rediscovered by Jenkins, it auto recreates the folder with an assumed new and unestablished base folder environment for SFDX. This still really seems like an environmental issue, but impact is not as large for me as initially outlined. It was much more impactful to delete pipe because recreating auto triggered all the scripts for the pipe. At least I can delete and recreate only the impacted branch.

Because there seems to be so much unknown around this (I'm getting ping ponged across other areas of support i.e. Jenkins, Bitnami), I've created a community topic with Bitnami, the VM stack used by Google Console (https://community.bitnami.com/t/jenkins-environment-reset-daily/78327/4). While initially they pushed back, I'm going to try and push them to look at this from an OS perspective. All the feedback I've gotten from you is this is related to OS environment variables. Perhaps all this will do is eliminate an OS issue. It does seem odd that current version of SFDX just doesn't work post install, but when I revert to a previous version, something sort of does work. This leads me to believe it's less OS/Jenkins related and more SFDX related.

As of this morning, I continue to have to delete and recreate things to keep my Jenkins instance running.

**Comment by cumulus-robert** [comment]
Is there a version before 47.0.15 can go to where this isn't an issue. Perhaps a version from October 2019? This is too much to manage with a ***continuous*** integration strategy.

**Comment by cumulus-robert** [comment]
I don't want to muddy the waters, but this morning I started receiving a similar error in Visual Studio:
...
```
[Error - 8:43:20 AM] (node:43862) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/Users/cumulusvision/sourcetree/ga/force-app/main/default/customMetadata'
[Error - 8:43:20 AM] (node:43862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 906)
[Error - 8:43:20 AM] (node:43862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 906)
```
...

It does seem like something is going on with SFDX here. This kind of solidifies to me the issue is with SFDX as this error can be produced in two separate OS environments. I'm using MacOS and Jenkins is Debian.

What is being done to address this? Is there any potential workaround besides going back to ANT for a reliable continuous integration solution using Jenkins?

**Comment by pawan22sfdl** [comment]
Hi Guys I am Using Below Jenkins file with groovy script

I am stuck since many days on this step please help

Jenkins File :- 

#!groovy
import groovy.json.JsonSlurperClassic
node {

    def BUILD_NUMBER=env.BUILD_NUMBER
    def RUN_ARTIFACT_DIR="tests/${BUILD_NUMBER}"
    def SFDC_USERNAME

    def HUB_ORG=env.HUB_ORG_DH
    def SFDC_HOST = env.SFDC_HOST_DH
    def JWT_KEY_CRED_ID = env.JWT_CRED_ID_DH
    def CONNECTED_APP_CONSUMER_KEY=env.CONNECTED_APP_CONSUMER_KEY_DH
    

    println 'KEY IS' 
    println JWT_KEY_CRED_ID
    println HUB_ORG
    println SFDC_HOST
    println CONNECTED_APP_CONSUMER_KEY
    def toolbelt = tool 'toolbelt'

    stage('checkout source') {
        // when running in multi-branch job, one must issue this command
        checkout scm
    }

    withCredentials([file(credentialsId: JWT_KEY_CRED_ID, variable: 'jwt_key_file')]) {
        stage('Deploye Code') {
            if (isUnix()) {
                rc = sh returnStatus: true, script: "${toolbelt} force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --username ${HUB_ORG} --jwtkeyfile ${jwt_key_file} --setdefaultdevhubusername --instanceurl ${SFDC_HOST}"
            }else{
			rr = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:logout --username ${HUB_ORG}"      
                        rc = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --username ${HUB_ORG} --jwtkeyfile \"${jwt_key_file}\" --setdefaultdevhubusername --instanceurl ${SFDC_HOST}"
            }
            if (rc != 0) { error 'hub org authorization failed' }

			println rc
			
			// need to pull out assigned username
			if (isUnix()) {
				       rmsg = sh returnStdout: true, script: "${toolbelt} force:mdapi:deploy -d manifest/. -u ${HUB_ORG}"
			}else{		   			   
           	   	     	       rmsg = bat returnStdout: true, script: "\"${toolbelt}\" force:mdapi:deploy -d manifest/. -u ${HUB_ORG}"
			}
			  
            printf rmsg
            println('Hello from a Job DSL script!')
            println(rmsg)
        }
    }
}

Error I am getting 

**C:\Program Files (x86)\Jenkins\workspace\DevPawanPOC>"C:\Program Files\Salesforce CLI\bin\sfdx" force:auth:jwt:grant --clientid 3MVG973QtA4.tpvnY0mvJs_efl7RdBhWv3V6yQI7S6MDB9vulPykFSaXuF_w9c_lD.SaLkl.epaxA.YeklB.K --username ***************************** --jwtkeyfile "****" --setdefaultdevhubusername --instanceurl https://test.salesforce.com 
Successfully authorized ******************  with org ID ************************
[Pipeline] echo
0
[Pipeline] bat
ERROR running force:mdapi:deploy:  ENOENT: no such file or directory, open 'C:\Program Files (x86)\Jenkins\workspace\DevPawanPOC@tmp\secretFiles\***********\privatekey.key'

C:\Program Files (x86)\Jenkins\workspace\DevPawanPOC>"C:\Program Files\Salesforce CLI\bin\sfdx" force:mdapi:deploy -d manifest/. -u **************************************** 
323 bytes written to C:\windows\TEMP\..zip using 839.898ms
Deploying C:\windows\TEMP\..zip...
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE**

**Comment by cumulus-robert** [comment]
Hi @pawan22sfdl - 

What worked for me to solve this issue in January was to include the setting of the Home variable inside the script itself. This may work for you as well. I'd try that first since that was my solution in in January and SFDC may point you that direction first any way. Here's what I did to solve it.

In your script, enclose everything inside a withEnv bracket. So ...


`withEnv(["HOME=${env.WORKSPACE}"]) {
    withCredentials([file(credentialsId: JWT_KEY_CRED_ID, variable: 'jwt_key_file')]) {
        stage('Deploye Code') {
            if (isUnix()) {
                rc = sh returnStatus: true, script: "${toolbelt} force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --username ${HUB_ORG} --jwtkeyfile ${jwt_key_file} --setdefaultdevhubusername --instanceurl ${SFDC_HOST}"
            }else{
    		rr = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:logout --username ${HUB_ORG}"      
                        rc = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --username ${HUB_ORG} --jwtkeyfile \"${jwt_key_file}\" --setdefaultdevhubusername --instanceurl ${SFDC_HOST}"
            }
            if (rc != 0) { error 'hub org authorization failed' }

    		println rc
    		
    		// need to pull out assigned username
    		if (isUnix()) {
    			       rmsg = sh returnStdout: true, script: "${toolbelt} force:mdapi:deploy -d manifest/. -u ${HUB_ORG}"
    		}else{		   			   
           	   	     	       rmsg = bat returnStdout: true, script: "\"${toolbelt}\" force:mdapi:deploy -d manifest/. -u ${HUB_ORG}"
    		}
    		  
            printf rmsg
            println('Hello from a Job DSL script!')
            println(rmsg)
        }
    }
}`

Try this first. It may work based on what version of SFDX you're on. My current issue is, this solution would still work had I not needed to rebuild Jenkins and perform a fresh install of tools. If it doesn't work, then you may be experiencing the same thing I am where script is setting the environment variables locally, but SFDX is failing to recognize that in some shape or form.

**Comment by cumulus-robert** [comment]
@pawan22sfdl I just noticed you're on Windows ... I'm on Linux. Not sure if setting Home variable will make a different in a Windows machine. But worth a shot.

**Comment by cumulus-robert** [comment]
@clairebianchi I've noticed a trend now working with this incident for a couple weeks now. It seems the first org I connected to consistently works. Any other org, I have to delete and recreate the branch on daily basis for SFDX to work. So, right now, for Company A, I'm connected to their partial sandbox consistently. But for Company A, I have to delete and recreate branches on continuous integration for a separate developer sandbox, or even Production. As well Company B, C, D .... I have to delete and recreate everything every day.

Is there focus being spent on this? Any idea when this can no longer be a thing? Any progress on this?

**Comment by cumulus-robert** [comment]
With the recent symptom discovery of a single instance working consistently, and knowing SFDX has OS environmental opportunities with Jenkins, I added an SFDX log out command to the end of the Jenkins groovy scripts yesterday. For once in two weeks, for a single org, I have not had to delete a folder this morning in an instance other than the separate instance partial sandbox mentioned in a previous comment. I'll check again tomorrow, but this looks promising.

I checked the groovy Jenkins example and while I do see the feedback from January incorporated, I don't see any reference to SFDX requiring a log out in the script. Perhaps adding this will save a lot of time and frustration for people. This likely could have been solved 14 days ago for me. I went here first, 14 days ago. (https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ci_jenkins_code.htm)

Or, at least a mention about SFDX relying on OS environment variables and Jenkins changes environment variables such as HOME. This is helpful information from an SFDX _application_ perspective when trying to understand/troubleshoot where a problem is occurring without any kind of application support. I know you're not in the CI business, but the more information the better for partners like myself supporting multiple salesforce instances. I will sell solid solutions all day long, as long as I can support them. I think this Jenkins CI is a great value add and use it for delivery, but am struggling selling SFDX as the solution paired with Jenkins because of these issues.

From my perspective, this should be a hit the ground running type of procedure/solution. It simply does not make sense how much difficulty I've had operating Jenkins with SFDX for the last 8 months when I haven't had a single issue with my Jenkins/ANT solution for the last 7 years. I support the SFDX application and value it's offering, it just seems like it might be premature for continuous integration if there's opportunity for things to fail like this more than once in such a short period of time without proper application support.

**Comment by cumulus-robert** [comment]
I confirm this issue is resolved. I would highly recommend updating documentation to include more information. The resolution here was to include a logout command for SFDX.

**Comment by pawan22sfdl** [comment]
@cumulus-robert can you share script exactly where you added logout command?
It will be helpful

**Comment by pawan22sfdl** [comment]
Hello @cumulus-robert 
I am using below script :-

#!groovy
import groovy.json.JsonSlurperClassic
node {

    def BUILD_NUMBER=env.BUILD_NUMBER
    def RUN_ARTIFACT_DIR="tests/${BUILD_NUMBER}"
    def SFDC_USERNAME

    def HUB_ORG=env.HUB_ORG_DH
    def SFDC_HOST = env.SFDC_HOST_DH
    def JWT_KEY_CRED_ID = env.JWT_CRED_ID_DH
    def CONNECTED_APP_CONSUMER_KEY=env.CONNECTED_APP_CONSUMER_KEY_DH
    

    println 'KEY IS' 
    println JWT_KEY_CRED_ID
    println HUB_ORG
    println SFDC_HOST
    println CONNECTED_APP_CONSUMER_KEY
    def toolbelt = tool 'toolbelt'

    stage('checkout source') {
        // when running in multi-branch job, one must issue this command
        checkout scm
    }

   withEnv(["HOME=${env.WORKSPACE}"]) {
   
   withCredentials([file(credentialsId: JWT_KEY_CRED_ID, variable: 'jwt_key_file')]) {
        stage('Deploye Code') {
            if (isUnix()) {
                rc = sh returnStatus: true, script: "${toolbelt} force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --username ${HUB_ORG} --jwtkeyfile ${jwt_key_file} --setdefaultdevhubusername --instanceurl ${SFDC_HOST}"
            }else{
			rr = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:logout --username ${HUB_ORG}"      
                        rc = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --username ${HUB_ORG} --jwtkeyfile \"${jwt_key_file}\" --setdefaultdevhubusername --instanceurl ${SFDC_HOST}"
            }
            if (rc != 0) { error 'hub org authorization failed' }

			println rc
			
			// need to pull out assigned username
			if (isUnix()) {
				       rmsg = sh returnStdout: true, script: "${toolbelt} force:source:deploy -x manifest/package.xml -u ${HUB_ORG}"
			}else{		   			   
           	   	     	       rmsg = bat returnStdout: true, script: "\"${toolbelt}\" force:source:deploy -x manifest/package.xml -u ${HUB_ORG}"
			}
			  
            printf rmsg
            println('Hello from a Job DSL script!')
            println(rmsg)
        }
    }
}

Getting this error 

ERROR running force:source:retrieve:  ENOENT: no such file or directory, open 'C:\Program Files (x86)\Jenkins\workspace\DevPawanPOC@tmp\secretFiles\1316084c-01dc-455c-af8e-823e0367be45\privatekey.key'
C:\Program Files (x86)\Jenkins\workspace\SFDXPOC>"C:\Program Files\Salesforce CLI\bin\sfdx" force:source:retrieve -x manifest/package.xml -u pawan.x.kumar@prudential.com.pcgdev 
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE


why even after using above technique i am failing to get answer?

@clairebianchi please help and @cumulus-robert you too...its quite urgent

**Comment by cumulus-robert** [comment]
Hi @pawan22sfdl I can appreciate your frustration having my own solution dependent on my own technical knowledge for support and also waiting 14 days for a solution that I ultimately did a hit and miss to figure out on my own. The SFDX application team really is the best to provide this guidance, IMHO. I'm just another member of the community, like yourself. Also, SFDX is a standalone application with no SLA for support. They will do what they can.

What I did was add a new stage at the end and outside of all the script stages:

`stage("SFDX Logout"){                        
                        rc = sh returnStatus: true, script: "sfdx force:auth:logout -p --all"
                        if (rc != 0) {
                            error 'SFDX Logout failed'
                        }
                    }`

Robert

**Comment by pawan22sfdl** [comment]
@cumulus-robert thanks ,,,,, but if i put logout outside of script how instance will login again to deploy?
I am little bit confused.

**Comment by aheber** [comment]
@cumulus-robert,

Any sense of why you would need a logout? Is this re-using the environment so there are session details from the previous run on the filesystem?

If so, is there any way to force a clean environment? I've been using JWT auth for nearly two years and haven't run into these problems. Each of my runs is on an individual Docker instance that gets burned after the run so maybe there is some difference there?

**Comment by cumulus-robert** [comment]
@aheber I would LOVE to know the answer to that question. I only had to add the log out after a recent Jenkins rebuild and re-install of 3rd party tools (SFDX). Since October, I've had to revise working scripts 2 times to support SFDX application changes. I now have auto update turned off. First to set environment variables within the script itself. This was because in December SFDX auto updated and my scripts all of a sudden started failing in January. And this week, I added the log out commands and while my scripts did work since January, I had to delete and recreate folders on the server daily after the rebuild in order for script to flow without error. I was even careful to set the SFDX version to last known working version from January. I still do not know the answer to the question: Why is it that since October 2019 I've had so many issues with SFDX and Jenkins but my 7 year ANT and Jenkins solution is still running strong. The common denominator to me is SFDX and while extremely frustrating (because I have business running on this), I am attributing it to a growing and evolving application.

Yes, SFDX uses environment variables. I've given feedback to the team to update their documentation to support this feedback in previous comments. It would make the incident management process much easier. I had questions out to three forums this time. Jenkins, Bitnami and SFDX.

Even with this closure, Jenkins free-style projects don't work with SFDX. Only groovy scripts work at this time for me. There is still a permissions issue with the Jenkins user on an out of box Jenkins install and SFDX. I'm sure I can figure it out, but getting groovy scripts working continuously was the priority.

@pawan22sfdl I think you have to organize the log out in a way that will support your script. Perhaps add it after your deploy and ensure the order in your script to always log in before a log out.

**Comment by pawan22sfdl** [comment]
**Why I am getting this error , like below , why my system is searching the server key in a location which is not even existing ?? 
I am using below groovy script and i added a logout function and then a login function and then deploy still its failing not working can some one help please** 

ERROR running force:source:deploy:  We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Hereâ€™s the error: ENOENT: no such file or directory, open 'C:\Program Files (x86)\Jenkins\workspace\DevPawanPOC@tmp\secretFiles\1316084c-01dc-455c-af8e-823e0367be45\privatekey.key'

C:\Program Files (x86)\Jenkins\workspace\SFDXPROJECT_>"C:\Program Files\Salesforce CLI\bin\sfdx" force:source:deploy -x manifest/package.xml -u pawan.x.kumar@prudential.com.pcgdev  --wait 20 
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**GROOVY SCRIPT**

#!groovy

import groovy.json.JsonSlurperClassic

node {

 

    //def BUILD_NUMBER=env.BUILD_NUMBER

    //def RUN_ARTIFACT_DIR="tests/${BUILD_NUMBER}"

    def SFDC_USERNAME

 

    def HUB_ORG='***********'
    def SFDC_HOST = 'https://test.salesforce.com'
    def JWT_KEY_CRED_ID = '********'
    def CONNECTED_APP_CONSUMER_KEY='********'

    println 'KEY IS'

    println JWT_KEY_CRED_ID

    println HUB_ORG

    println SFDC_HOST

    println CONNECTED_APP_CONSUMER_KEY

    def toolbelt = tool 'toolbelt'

 

    stage('checkout source') {

        // when running in multi-branch job, one must issue this command

        checkout scm
        println 'Successfull checkout'

    }

 

    withEnv(["HOME=${env.WORKSPACE}"]) {

                withCredentials([file(credentialsId: JWT_KEY_CRED_ID, variable: 'jwt_key_file')]) {
                    println 'Successfull login'

        stage('Deploye Code') {
            println 'Deploy start'

            if (isUnix()) {

                //rc = sh returnStatus: true, script: "${toolbelt} force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --username ${HUB_ORG} --jwtkeyfile ${jwt_key_file} --setdefaultdevhubusername --instanceurl ${SFDC_HOST}"
                 rc = sh "sfdx force:auth:jwt:grant --clientid $CONNECTED_APP_CONSUMER_KEY --username $HUB_ORG --jwtkeyfile $jwt_key_file --instanceurl $SFDC_HOST"
				 println 'login success'
            }else{
				println 'Successfull checkout 22'
				rr = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:logout --username ${HUB_ORG}"  
				rc = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --username ${HUB_ORG} --jwtkeyfile \"${jwt_key_file}\" --setdefaultdevhubusername --instanceurl ${SFDC_HOST}"
			}

            if (rc != 0) { error 'hub org authorization failed' } 

			println rc
			println 'Deploy start2'

			// need to pull out assigned username

			if (isUnix()) {

								   //rmsg = sh returnStdout: true, script: "${toolbelt} force:mdapi:deploy -d DevSandbox/. -u ${HUB_ORG}"
								   rmsg = sh "sfdx force:mdapi:deploy -d output --targetusername $HUB_ORG --wait 20"
									println 'Deploy succes'

			}else{                                                                       
                 rr = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:logout --username ${HUB_ORG}"  
				 rc = bat returnStatus: true, script: "\"${toolbelt}\" force:auth:jwt:grant --clientid ${CONNECTED_APP_CONSUMER_KEY} --username ${HUB_ORG} --jwtkeyfile \"${jwt_key_file}\" --setdefaultdevhubusername --instanceurl ${SFDC_HOST}"
				 rmsg = bat returnStdout: true, script: "\"${toolbelt}\" force:source:deploy -x manifest/package.xml -u ${HUB_ORG}  --wait 20"

			}        
            
            if (rc != 0) { error 'hub org authorization failed' } 

			println rc
			println 'Deploy start2'			

            printf rmsg

            println('Hello from a Job DSL script!')

            println(rmsg)

        }

    }

}

}

//stage("SFDX Logout"){ rc = sh returnStatus: true, script: "sfdx force:auth:logout -p --all" if (rc != 0) { error 'SFDX Logout failed' } }

**Comment by cumulus-robert** [comment]
Hi Pawan –

 

Try submitting the log out command outside of Jenkins. The root cause of my issue has to do with SFDX and it’s interaction Operating System Environment Variables. This meant for me SFDX must be caching something or something was stuck at that level. If you force a log out by going to command prompt first and then run Jenkins job, you’re essentially giving Jenkins a blank slate to commence a fresh log in / log out via script. This is what I had to do to make mine work. Log in to the server command line and perform a log out manually. Then trigger Jenkins scripts again.

 

Remember, Jenkins is a standalone server application based on an Operating System. There are so many variables to consider. The biggest here is I’m on Linux and you’re on Windows. The two will fundamentally interact differently from an OS perspective. This very likely is not an SFDX issue, but more an issue of how SFDX CLI interacts with your computer and Jenkins. 

 

An alternative to Jenkins could be a Docker type of solution that runs scripts and purges environment right away thus never introducing environment variables as an issue. If you’re focused on Jenkins being the solution like me, then we have to work through operating system / desktop issues to support continuous integration.

 

Robert

**Comment by cumulus-robert** [comment]
@clairebianchi Here's a technical response from Bitnami, the Jenkins VM package I use. This may be helpful for you in the future:


I'm not sure I fully understand which environment variable is causing the issue. From the error message/opt/bitnami/jenkins/jenkins_home/workspace/TAN-pipe_prod_validate@tmp/secretFiles/ef828807-fd4d-41a0-87da-554870598fce/server.key

It seems that the workspace is set correctly, Then we have a temporary folder that may probably be deleted after some time. Could it be that Jenkins is deleting that folder and therefore the file not being accessible? It is very strange that it happens just after 24 hours. If it was a OS issue, I believe the issue should have appeared sooner. I don't see any cronjob specified there so I believe that it is something that Jenkins should be doing.

It may be worth considering that Jenkins is a standalone server vs. a throwaway Docker instance where this issue likely doesn't occur.
