### ISSUE TITLE
errors with sfdx pulling report sub folders

### ISSUE THREAD

**Issue by Vincent-Ip** [forcedotcom/cli#367]
### Summary

Error using `sfdx force:source:pull` when retrieving Report Sub Folders (Report Folders that are created within a report folder). 
**Entity of type 'Report' named 'ReportFolder/ReportSubFolder' cannot be found.** 

This is probably also affecting `sfdx force:package:version:create`.  I was seeing error messages like the following:
**Entity Report and member ReportFolderName/ReportSubFolderName did not resolve to an id while serializing Released Entity State**

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)
1. Create a scratch org and push in all the code.
1. Open scratch org and go to the Reports App in the App Switcher
1. Create a single level Report folder (to make sure that report pull is working ok)  (Folders > All Folders.  then click New Folder.  Create a folder named "ReportFolder"
1. `sfdx force:source:pull`   (this works!)
1. Go back to scratch org and create a sub folder in ReportFolder (in Folder "ReportFolder" create a new Folder named "ReportSubFolder")
1. `sfdx force:source:pull` -> returns this error: **Entity of type 'Report' named 'ReportFolder/ReportSubFolder' cannot be found**

### Expected result

Success source pull with ReportFolder and ReportSubFolder create in the project report folder

### Actual result

Error message:
**Entity of type 'Report' named 'ReportFolder/ReportSubFolder' cannot be found**

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.53.0-839fc82926 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
sfdx-cli 7.53.0 (core)

Not sure if you need all the plugin info, so i'll include it here:
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.8.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.8.0 (core)
└─ salesforce-alm 48.8.0 (core)

sfdx-cli 7.53.0 (core)

**OS and version**:
macOS Catalina
version 10.15.3

**Comment by nramyasri-sf** [comment]
@Vincent-Ip , this is a bug.It apparently happens when you try to pull/retrieve empty sub-folders.

**Comment by Vincent-Ip** [comment]
> @Vincent-Ip , this is a bug.It apparently happens when you try to pull/retrieve empty sub-folders.

fyi: I did a test of this and I created a report in the subfolder to see if I could get back the folder / subfolder and report, but I still get the the same error 

**"Entity of type 'Report' named 'folder/subFolder' cannot be found"**

**Comment by mshanemc** [comment]
cf: W-7503240

**Comment by richclark808** [comment]
Still an issue btw when you try and create a package version with report subfolders, hit this same one today and the subfolder was not empty. Issue remains despite moving the report and deleting the subfolder. very odd.

**Comment by victorabraham** [comment]
Noticing this issue. `sfdx force:package:version:create` fails with error `Entity Report and member ManagementLevelReports/PeopleDashboardReports did not resolve to an id while serializing Released Entity State` where there are report subfolders.

**Comment by albertogugliotta** [comment]
Having exact same issue running `sfdx force:package:version:create`

**Comment by ianpadrick** [comment]
Did anyone ever figure this out? We can't deploy a 2GP package if it contains report sub folders?

**Comment by ori-sweep** [comment]
Bumping this up.
I am trying to package report folder and a sub folder but no luck, getting this error:
`Entity Report and member folder/subfolder did not resolve to an id while serializing Released Entity State`

Any workaround here?

**Comment by mshanemc** [comment]
I'm going to close this issue because the `pull` command work correctly now with subfolders

I opened #2039 to cover the packaging portion of this.  The CLI team can't fix it, you should all open support cases so the packaging team can prioritize fixing it.
