### ISSUE TITLE
Sfdx force:auth:jwt:grant not storing the authorized Dev HUb details in the current project

### ISSUE THREAD

**Issue by harshanandam** [forcedotcom/cli#369]
### Summary

All the commands after the Dev Hub authorization using JWT flow fails with error message:

"We couldn't create this sandbox or scratch org because the associated Dev Hub isn't authorized. Authorize the Dev Hub and try again"

### Steps To Reproduce:

1.  Have a JWT key file and set up the Connected App on yor Dev Hub.
2. Execute the below command from SFDX project 
sfdx force:auth:jwt:grant --clientid <<Consumer Key from Connected App>> --jwtkeyfile C:\Users\Lenovo\JWT\server.key --username <<Username>> --setdefaultdevhubusername --setalias my-hub-org --json

Above command returns the result as below:
{
  "status": 0,
  "result": {
    "orgId": "OrgId",
    "accessToken": "<<access_token>>",
    "refreshToken": "<<refresh_token>>",
    "instanceUrl": "<<domain_url>>",
    "loginUrl": "https://login.salesforce.com",
    "username": "<<username>>",
    "clientId": "PlatformCLI"
  }
}

3. Now execute the below commands and you will see the issue.
sfdx force:org:list

No org is listed with Connected Status.

And if I execute the command to create scratch org it fails with below:

sfdx force:org:create -v my-hub-org -f config/project-scratch-def.json --json
{
  "status": 1,
  "name": "DevhubNotAuthorized",
  "message": "We couldn't create this sandbox or scratch org because the associated Dev Hub isn't authorized. Authorize the Dev Hub and try again.",
  "exitCode": 1,
  "commandName": "OrgCreateCommand",
  "stack": "DevhubNotAuthorized: We couldn't create this sandbox or scratch org because the associated Dev Hub isn't authorized. Authorize the Dev Hub and try again.\n    at Function.create (C:\\Users\\Lenovo\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:141:16)\n    at OrgCreateCommand.resolveHubOrgContext (C:\\Users\\Lenovo\\AppData\\Local\\sfdx\\node_modules\\salesforce-alm\\dist\\commands\\force\\org\\create.js:47:40)",
  "warnings": []
}

### Expected result
DEVHUB should be authorized and can be used with other commands

### Actual result

Authorzed dev hub is not stored on the local project.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):  sfdx-cli/7.53.0-839fc82926 win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.8.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.8.0
└─ salesforce-alm 48.8.0

sfdx-cli 7.53.0 (core)

**OS and version**: Windows 10.

**Comment by harshanandam** [comment]
Seems like if we already authorize then the next authorization will not be stored with different alias.

**Comment by craigdor** [comment]
> Seems like if we already authorize then the next authorization will not be stored with different alias.

Even with the same alias, subsequent authorizations do not seem to be stored. Is that a bug, or by design?
