### ISSUE TITLE
Multiple object folders. Only one gets converted / deployed (alphabetic order)

### ISSUE THREAD

**Issue by ennoucas** [forcedotcom/cli#370]
Hello, 

I have a folder structure like that: 
```
force-app
|-- main
     |-- default
           |-- objects
                 |-- Opportunity
                       |-- fields
                            |-- Field1__c.field-meta.xml
|--xApp1
    |-- objects
          |-- Opportunity
               |-- fields
                     |-- Field2__c.field-meta.xml
```
In this example, only Field1 will be deployed.
If renaming xApp1 by app1, only Field2 will be deployed. 

Is this suppose to happen ? 

SFDX Version: sfdx-cli/7.53.0-839fc82926 
sfdx-project.json : 
- packageDirectory --> force-app
- version: v48

Command lines used:
`sfdx force:source:convert` and `sfdx force:source:deploy`

Thank you

**Comment by rvwatch** [comment]
https://github.com/forcedotcom/cli/issues/379

**Comment by clairebianchi** [comment]
@ennoucas We are working on supporting multiple packages in the same SFDX project. A branch of that work is available publicly, see: https://github.com/forcedotcom/cli/issues/379

Please test that out to see if it fixes your issue.
