### ISSUE TITLE
SFDX: Authorize an Org doesn't open browser for OAuth

### ISSUE THREAD

**Issue by matteobosc** [forcedotcom/cli#371]
### Summary 

I created a new project using the command SFDX: Create Project with Manifest. When I run the command SFDX: Authorize an Org choosing the Sandbox option it doesn't open the browser for OAuth, the banner of the command is still there and the command prompt doesn't show any error.

![image](https://user-images.githubusercontent.com/43987657/72826972-2f921180-3c7a-11ea-9a6b-f3e2371ca83c.png)

It's not a Java issue, I can use other sfdx commands fine for project already authorized.

It's not a proxy issue, I can open links from command line through VSC.

This problem is very annoying, I can't use VSC for new projects.

### Steps To Reproduce:

1.  Create a new project using the command SFDX: Create Project with Manifest.
2.  Run the command SFDX: Authorize an Org choosing the Sandbox option.

### Expected result

The command should open the default browser for OAuth

### Actual result

The command doesn't open the default browser for OAuth

### Additional information

**VS Code Version**:

1.41.1

**SFDX CLI Version**:

sfdx-cli/7.36.0-b1c4e9c7c8 win32-x64 node-v10.15.3

**Salesforce Extension Pack Version**:

47.15.0

**OS and version**:

Windows 10 Enterprise 1903 Build 18362.592

**Comment by thegogz** [comment]
> > Same issue for every dev in our business (that's 50+ developers across multiple projects)
> > Chrome: Version 79.0.3945.79 (Official Build) (64-bit)
> > OS: Win 7 and Win 10
> > Workaround does work but is far from ideal
> 
> Hi, the problem is not coming from your browsers. After dealing with this error, I found that we have to add "C:\Windows\System32" path to your environment variables. Remember to restart your Visual Studio Code or your computer if it is still not working. Good luck!

System32 is already in the PATH on my machine, have tried this with some of the other devs on our team and same result. this does not appear to be the solution.

**Comment by banderson5144** [comment]
I am having the same issue as well. Latest version of SFDX, Chrome, running on WIndows 7

**Comment by PradeepSinghAppirio** [comment]
I am also facing the same issue with latest version of SFDX on windows 10. Tried all the above solutions but none of them worked.

**Comment by amphro** [comment]
We can't reproduce on Windows 10 enterprise using `sfdx-cli/7.80.0-b979aae708 win32-x64 node-v12.18.3`. It seems like this is a configuration thing so any additional help in finding out what could cause this to fail would help.

If you run something like `Start "https://www.googl.com"` in the terminal does it work?

**Comment by murarigokul** [comment]
Me too Facing same issue.. 
Using sfdx-cli/7.82.0-3d0c527ac6 win32-x64 node-v12.18.3
Default browser is set to edge. Start "https://www.google.com" is opening from VS code terminal.
Trusted domains in VS code is disabled. Its opening all pages.
But still facing this issue. 
"sfdx force:auth:web:login --setalias fd --instanceurl https://test.salesforce.com --setdefaultusername" is running, and not opening browser to login.

**Comment by git-training-archie** [comment]
It says the following so I typed 'y' and it launched Chrome. I guess the command no longer works?

![image](https://user-images.githubusercontent.com/63224051/104731827-3e20e500-5777-11eb-8e29-ef672655d83b.png)

**Comment by KosinskiPatrykPG** [comment]
> It says the following so I typed 'y' and it launched Chrome. I guess the command no longer works?
> 
> ![image](https://user-images.githubusercontent.com/63224051/104731827-3e20e500-5777-11eb-8e29-ef672655d83b.png)

Yes, I found that the newest version of Salesforce CLI doesn't have auth commends. As a workaround you should downgrade you Salesforce CLI. It is not easy because I couldn't find old exe file so you have to install node.js then use npm functions:
1. Uninstall Salesforce CLI
2.  Install https://nodejs.org/en/download/
2. In command line install one of the previous version(  for example:7.82.0) using npm: **npm install sfdx-cli@7.82.0 --global**

**Comment by NisargSharma** [comment]
Same issue with me! I'm using ubuntu 18.04 OS and whenever I'm trying to run sfdx commands from vs code or my terminal window, it doesn't launch the default browser! I also tried changing the default browser to Firefox but nothing works.

OS: Ubuntu 18.04 (x64)
SFDX Version: sfdx-cli/7.84.2-a2868a68d5 linux-x64 node-v12.18.3
VS Code Version: 1.52.1

Any help would be appreciated.

**Comment by anirudhbora06** [comment]
two ways you can try:-

1.add 'C:\Windows\System32' to path variable
or
2.
Open sfdx-project.json file and change the sfdcLoginUrl property to https://test.salesforce.com
In the terminal run command :=> sfdx force:auth:device:login
It will give you the code and URL.
Hit the URL in the browser and enter the code.
It will ask credentials. Enter your credentails and complete the process.
You will see Login Successful message in terminal.
set the org as default.

**Comment by NisargSharma** [comment]
> two ways you can try:-
> 
> 1.add 'C:\Windows\System32' to path variable
> or
> 2.
> Open sfdx-project.json file and change the sfdcLoginUrl property to https://test.salesforce.com
> In the terminal run command :=> sfdx force:auth:device:login
> It will give you the code and URL.
> Hit the URL in the browser and enter the code.
> It will ask credentials. Enter your credentails and complete the process.
> You will see Login Successful message in terminal.
> set the org as default.

Thanks a lot for the help @anirudhbora06! It worked for me!

**Comment by mitchspano** [comment]
This is happening for me on Big Sur OS

**Comment by OlenaHryhorets** [comment]
> 2.
> Open sfdx-project.json file and change the sfdcLoginUrl property to https://test.salesforce.com
> In the terminal run command :=> sfdx force:auth:device:login
> It will give you the code and URL.
> Hit the URL in the browser and enter the code.
> It will ask credentials. Enter your credentails and complete the process.
> You will see Login Successful message in terminal.
> set the org as default.

Thanks a lot @anirudhbora06!!! Worked for me! (Linux18.04  VSC1.53.2   Chrome)

**Comment by SwagataRay** [comment]
@ElenaGrigorets 

Thanks for you suggestion. It worked for me!!

**Comment by mshanemc** [comment]
@W-7217999@

**Comment by kelleytaylor2021** [comment]
my data had been tempered with out my authorization



![Screenshot_20210703-053236.png](https://user-images.githubusercontent.com/86329200/124355838-13610680-dbc8-11eb-997c-a04fb97e7801.png)

**Comment by harshada121** [comment]
> Me too Facing same issue.. Using sfdx-cli/7.82.0-3d0c527ac6 win32-x64 node-v12.18.3 Default browser is set to edge. Start "https://www.google.com" is opening from VS code terminal. Trusted domains in VS code is disabled. Its opening all pages. But still facing this issue. "sfdx force:auth:web:login --setalias fd --instanceurl https://test.salesforce.com --setdefaultusername" is running, and not opening browser to login.

is your issue fixed?

**Comment by diihowns** [comment]
Olá, pessoal tudo bem?

Resolve fazer a instalação do Salesforce CLI junto ao VScode no meu computador pessoal,  porém me deparei com esse mesmo problema, no sistema operacional Linux Mint.

Para correção desse problema é nescessário, desistalar totalmente o Salesforce CLI, depois baixar os arquivos novamente para fazer uma instalação limpa.

Acredito que esse erro seja causado pela instalação via NPM, faça a instalação dessa maneira

Baixa o  Salesforce - CLI pelo site oficial :

https://developer.salesforce.com/tools/sfdxcli#

Depois execute as seguintes linhas de comando 1 de cada vez : 

wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

mkdir sfdx

tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1

./sfdx/install


Fiz a instalação do DX  usando linha de comando : sudo apt-get install DX, pode ser que tenha ajudado, caso, consiga deixa um comentário, não se esqueça de reiniciar  o computador após fazer  todo o processo.
