### ISSUE TITLE
sfdx force:source:deploy taking upwards of 5mins to deploy LWC

### ISSUE THREAD

**Issue by nebc-jasonfung** [forcedotcom/cli#372]
### Summary

When deploying LWC to a non-scratch org using `sfdx force:source:deploy` it taking upwards of 5mins to deploy a few lines of code.

For non LWC, it deploys in a few seconds

### Steps To Reproduce:

1.  Create a new LWC and make simple changes to it
1.  Use `sfdx force:source:deploy` to deploy your changes to the authorised org

### Expected result

It should take a few seconds for the changes deploy to your org, just like it does for Apex classes etc.

### Actual result

Taking upwards of 5mins to deploy

### Additional information

![image](https://user-images.githubusercontent.com/47176130/79441843-aa47a000-7fcf-11ea-907b-06f413656d14.png)

**SFDX CLI Version**:
`sfdx-cli/7.53.0-839fc82926 win32-x64 node-v10.15.3`

**SFDX plugin Version**:
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core) 
@oclif/plugin-help 2.2.3 (core)     
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.8.0
├─ salesforcedx-templates 48.8.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
└─ salesforce-alm 48.8.0

sfdx-cli 7.53.0 (core)
```

**OS and version**:
Windows 10 Pro 10.0.18363 Build 18363

**Comment by ennoucas** [comment]
Same here. It happened as soon as I created separate js files for my LWC to be loaded as modules.

**Comment by shetzel** [comment]
Yeah this is interesting bug.  It wasn't 5 mins for me but it's unacceptably too long.  We'll track it down and get it into a patch release asap.  Thank you for reporting.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9300113](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MQy1YAG/view)
