### ISSUE TITLE
sfdx force:user:permset:assign returns exit code 0 even if it fails

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/cli#373]
### Summary

`sfdx force:user:permset:assign` command returns exit code 0 even if it fails.
Thus, CI jobs are successful even though something failed.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Setup Dreamhouse scratch org
2.  Try to assign a permset that doesn't exist, for instance:
`sfdx force:user:permset:assign --permsetname Texei`

### Expected result

The command fails and exit with code 1.

### Actual result

The command fails but exit with code 0.

### Additional information

Another failing CLI command (for instance `sfdx force:source:push`) will fail with exit code 1, but `sfdx force:user:permset:assign` returns exit code 0:

![image](https://user-images.githubusercontent.com/2465122/79444103-0237d400-7fdb-11ea-8383-18ff3c99994e.png)

```
salesforcedx 48.8.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.8.0 (core)
└─ salesforce-alm 48.8.0 (core)
```

**Comment by clairebianchi** [comment]
@FabienTaillon We have a fix and it will be going out this week.
