### ISSUE TITLE
sfdx force:source:retrieve -p  always retrieves source in default dir

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#374]
### Summary
I'm using `source:deploy` and `source:retrieve` for non-source-tracked orgs like sandboxes.
Running `sfdx force:source:deploy --sourcepath  force-app/customdir/Class.cls`  correctly deploys the source.
However `sfdx force:source:retrieve --sourcepath force-app/customdir/Class.cls` retrieves the source in the wrong directory (i.e. the default one: force-app/default/main)

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1. Leave `sfdx-project.json` as is
1.  Move `PagedResult.cls`   and  `PagedResult.cls-meta.xml` in a new directory under `force-app`
     (e.g. `force-app/customdir`)
1. Make some edits to `PagedResult.cls` and deploy it. 
1. Retrieve again `PagedResult.cls` running  `sfdx force:source:retrieve -p force-app/customdir/PagedResult.cls` 
     
### Expected result
I would expect that `PagedResult.cls` remains unchanged as I've retrieved the source immediatly after deploying it.

### Actual result
New files `PagedResult.cls`   and  `PagedResult.cls-meta.xml` are created in `force-app/main/default/classes` default directory, duplicating the existing ones in `force-app/customdir/`.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.53.0-839fc82926 linux-x64 node-v10.15.3`

**OS and version**:
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by shetzel** [comment]
I'm not able to reproduce this.  Could you please post the result of running `sfdx plugins --core`

**Comment by ghost** [comment]
Here it is, thanks for the reply :
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.8.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.8.0
└─ salesforce-alm 48.8.0

sfdx-cli 7.53.0 (core)

**Comment by ghost** [comment]
Dears,  have you any update on this?
This issue prevents from organizing source code while working with non source-tracked orgs.
I' ve tried with a different installation of sfdx in another machine, but the problem seems to remain:
`sfdx-cli/7.63.0-c897e8bb1a linux-x64 node-v10.20.1`
Thank you for your help

**Comment by ghost** [comment]
Upgrading to sfdx-cli/7.81.0-7b953c80d1 linux-x64 node-v12.18.3
solved this issue.
Thanks!!
