### ISSUE TITLE
Error  shape/settings/FieldService.settings  FieldService  Not available for deploy for this organization

### ISSUE THREAD

**Issue by manisfdcsfdx** [forcedotcom/cli#376]
### Summary

Scratch org creation failed in latest version of CLI

### Steps To Reproduce:
use below scratch org definition
````
{
  "orgName": "manisfdcsfdx",
  "edition": "Enterprise",
  "features": ["Communities", "ServiceCloud", "API", "Sites", "AddCustomApps:30", "AddCustomTabs:30", "ForceComPlatform"],
  
  "settings": {
    "communitiesSettings": {
      "enableNetworksEnabled": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    }
  }
      
}
````
Run below CLI command:
sfdx force:org:create -f config/project-scratch-def.json -s -d 7 -a testcreate

### Expected result

Scratch org should be created without any issue

### Actual result
scratch org creation failed with below error 
Error  shape/settings/FieldService.settings  FieldService  Not available for deploy for this organization 
### Additional information
![image](https://user-images.githubusercontent.com/44075423/79928349-0f930980-8486-11ea-8148-d98237d64418.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.54.4-8ff9ba9cc5
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
dependencies-cli 2.0.1 (link) C:\Plugin\dependencies-cli
generator 1.1.2 (core)
salesforcedx 48.10.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.8.0 (core)
└─ salesforce-alm 48.10.0 (core)

**OS and version**:
Windows 10

**Comment by manisfdcsfdx** [comment]
issue resolved after deleting AppData\Local\Temp\shape\settings in my machine.

**Comment by manisfdcsfdx** [comment]
This issue still exist. deleting AppData\Local\Temp\shape\settings is just workaround. i was able to reproduce the issue and find the actual root cause.

**Background**:
FSL setting and package will not work in enterprise scratch properly [issue](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1SAG&fId=0D53A00004TfnnESAR) .  As a workaround we use developer edition for project which depends on FSL, other projects are in Enterprise edition.

**package_1** (depends on FSL)

````
{
  "orgName": "manisfdcsfdx",
  "edition": "Developer",
  "features": ["Communities", "ServiceCloud", "API", "Sites", "AddCustomApps:30", "AddCustomTabs:30", "ForceComPlatform","FieldService"],
  "settings": {
    "communitiesSettings": {
      "enableNetworksEnabled": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "fieldServiceSettings": {
       "fieldServiceOrgPref": true
     }
  }
}
````
create scratch org
sfdx force:org:create -f config/project-scratch-def.json -s -d 7 -a package_1_org

Scratch org will be created.

**Package_2**
````
{
  "orgName": "manisfdcsfdx",
  "edition": "Enterprise",
  "features": ["Communities", "ServiceCloud", "API", "Sites", "AddCustomApps:30", "AddCustomTabs:30", "ForceComPlatform"],
  "settings": {
    "communitiesSettings": {
      "enableNetworksEnabled": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    }
  }
}
````
create scratch org
sfdx force:org:create -f config/project-scratch-def.json -s -d 7 -a package_1_org

cli throws below error
![image](https://user-images.githubusercontent.com/44075423/79953854-decfc600-84bf-11ea-8bc6-93910639bdb9.png)


Everytime we create a scratch org cli is not deleting Temp\shape folder. As a result shape generated for package_1_org was not cleared. when package_2_org creation is attempted, new shape is added to the existing folder where all the settings exist and causing the problem.

**WorkAround**:
deleting AppData\Local\Temp\shape\settings\FieldService.settings - **Windows**
Go to terminal. --> type open $TMPDIR --> Go to Shape --> settings folder-->Delete FieldService.settings  - **MAC**

**Comment by clairebianchi** [comment]
@manisfdcsfdx thank you for reporting. @rrmehta2 can you take a look at this issue?

**Comment by albertinsyd** [comment]
Hi @clairebianchi and Rohit - I too am having apparently the same problem.   Other features enable correctly but not this one.

![image](https://user-images.githubusercontent.com/21653618/97103190-0158cb00-16ff-11eb-9ed3-b6fc3df9ed2e.png)

Pure speculation but I'm wondering if the activation is checking for full FSL licence (which we don't have) and hence refusing to activate work orders?  All the other features I can enable in the scratch org definition (which is using shape) and after creation I can log in via UI and enable this one.  Just not through the definition.

Thanks!!

scratch org def:
{
  "orgName": "Salesforce",
  "sourceOrg": "-redacted-",
  "settings": {
    "surveySettings": {
      "enableSurvey": true
    },
    "fieldServiceSettings": {
      "enableWorkOrders": true
    },
    "knowledgeSettings": {
      "enableKnowledge": true
    },
 ... etc ...

**Comment by jonathanwiesel** [comment]
Same happened to me using `OrderManagement` feature

**Comment by jonathanwiesel** [comment]
Any update on this?

**Comment by Vladislav987** [comment]
Hi @jonathanwiesel , @manisfdcsfdx  was right. I had a problem with OrderManagement, but I use this setting on another project. And when I deleted the setting from AppData\Local\Temp\shape\settings I stopped getting this error.

**Comment by jonathanwiesel** [comment]
Hi @Vladislav987, indeed that's a feasible workaround, I mean if there's an update on the resolution of the real issue, since the CLI shouldn't be trying to use a setting that is not specified in the supplied scratch org definition file

**Comment by Caitlyn-Mills** [comment]
Confirming that this issue still exists as I have just encountered it.

**Comment by Aravindh04** [comment]
@Caitlyn-Mills  Is this occuring in macOS as well?

**Comment by Caitlyn-Mills** [comment]
@Aravindh04 Yeah that is where I had the issue

**Comment by cristiand391** [comment]
I couldn't repro this on latest sf.
We've rewritten the scratch org create logic in 2022 and currently creates the zip file in memory, I think the previous one was writing it in the tmp dir without cleaning up.
