### ISSUE TITLE
DevelopmentWave feature - Impossible to access Scratch Org

### ISSUE THREAD

**Issue by maaaaarco** [forcedotcom/cli#377]
### Summary
When adding the feature _DevelopmentWave_ to the scratch org configuration file the CLI is not able to open the Scratch Org in the browser anymore (after it creates successfully).

This is our config file:
`{
  "orgName": "Test",
  "edition": "Developer",
  "features": [
    "DevelopmentWave"
  ]
}`

### Steps To Reproduce:
1. Using the config file provided above, create a new scratch org
1. Wait until the org is created successfully
1. If you are in VSCode click the button to open the Scratch Org in a new browser tab or through the CLI run the `force:org:open` command
1. You are not able to access the org and the browser redirects you to the login.salesforce.com page

Eventually you can use this template for Analytics development: https://github.com/forcedotcom/sfdx-analytics
You will have the same behavior. 

### Expected result
After the Scratch Org is created I should be able to access it through the browser

### Actual result
Unable to access the Scratch Org in the browser.

### Additional information
**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.54.4-8ff9ba9cc5 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.10.1 (48.10.1)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.8.0
└─ salesforce-alm 48.10.0

sfdx-cli 7.54.4 (core)

**OS and version**:
MacOS Mojave, 10.14.6

**Comment by clairebianchi** [comment]
@maaaaarco  I have contacted the team that owns Scratch org creation

**Comment by maaaaarco** [comment]
@clairebianchi maybe this can help... If I create the Scratch Org using the config file I attached, then take a snapshot of it (we are part of the pilot) and create another Scratch using that snapshot that it's all good.

**Comment by maaaaarco** [comment]
@clairebianchi is there any news on this one? It's still happening...

**Comment by PavloShchur** [comment]
I have the same problem. Scratch org is active and expired. Few days ago I was able to log in but now not. Does anybody have any ideas?

**Comment by maaaaarco** [comment]
@clairebianchi this is still a thing in Summer 20

**$ sfdx --version**
sfdx-cli/7.66.2-4f159a1d07 darwin-x64 node-v12.13.0

**$ sfdx plugins --core**
@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/analytics 0.21.0
@salesforce/lwc-dev-server 2.5.0
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.2.3 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforcedx-templates 48.32.0 (core)
├─ custom-metadata 1.0.7 (core)
└─ salesforce-alm 49.3.0 (core)
sfdx-cli 7.66.2 (core)

**Comment by mshanemc** [comment]
works for me
