### ISSUE TITLE
Salesforce CLI install not recognized on MacOS Catalina

### ISSUE THREAD

**Issue by mckennammj** [forcedotcom/cli#382]
Update:
It turns out the problems were with my OS. My HomeBrew was very messed up and it took a lot of Brew Doctor and fixing to get everything squared away. My Salesforce CLI and the extensions with VSCode now work perfectly. Sorry for the false alarm here. Thanks!

Original:
Hello,

### Summary
I have tried multiple different methods of installation of the Salesforce CLI to use in VSCode but I keep getting the error that it is not installed.

Questions: 
1. What is the way to install the CLI so I can use it in VSCode?
2. What is the CLI path so I can add it to environmental variables?
3. What else am I missing?

Thank you all for your help.

### Steps To Reproduce:

1. Install VSCode

2. I tried installing the Salesforce Extension Pack https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode

3. Open VSCode and use Cmd + S + P and then run SFDX: Create Project
 > See Actual Result

4.  I tried manual installation https://developer.salesforce.com/tools/sfdxcli

5. Open VSCode and use Cmd + S + P and then run SFDX: Create Project
 > See Actual Result

Neither worked. All of the support threads I found are for Windows. I cannot find where the CLI lives in MacOS for me to add it as an environmental variable, if that is the problem.

### Expected result
New Project is Created

### Actual result

14:14:08.906 sfdx force:project:create --projectname codeU --outputdir /Users/mike/Downloads --template standard
14:14:08.910 sfdx force:project:create --projectname codeU --outputdir /Users/mike/Downloads --template standard
 ended with error spawn sfdx ENOENT
Salesforce CLI is not installed. Install it from https://developer.salesforce.com/tools/sfdxcli

### Additional information
MacOS Catalina v10.15.4

VSCode:
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z (1 wk ago)
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

SFDX:
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)

sfdx-cli 7.36.0 (core)

XCode:
Version 11.4 (11E146)

Printenv:

COLORFGBG=12;8
ITERM_PROFILE=Default
XPC_FLAGS=0x0
LANG=en_US.UTF-8
PWD=/Users/mike
SHELL=/usr/local/bin/zsh
TERM_PROGRAM_VERSION=3.2.3
TERM_PROGRAM=iTerm.app
PATH=/Users/mike/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
COLORTERM=truecolor
TERM=xterm-256color
HOME=/Users/mike
TMPDIR=/var/folders/sj/qzxb0nfx0sz6wf4zn4482jrr0000gn/T/
USER=mike
XPC_SERVICE_NAME=0
LOGNAME=mike
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
SHLVL=1
OLDPWD=/Users/mike
ZSH=/Users/mike/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LC_CTYPE=en_US.UTF-8
_=/usr/bin/printenv

**Comment by shetzel** [comment]
You used the MacOS installer then right?  That should have handled everything for you.  You can either uninstall and try again, or you can do `which sfdx` and add the location to your path.  You may want to update anyway since the latest CLI version is `7.56.1`
