### ISSUE TITLE
 Error: Channel "stable" not found. - When trying to update from Windows PowerShell

### ISSUE THREAD

**Issue by leonardopmacedo** [forcedotcom/cli#389]
sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.10.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.8.0 (core)
└─ salesforce-alm 48.10.0 (core)

sfdx update                                                                                        
sfdx-cli: Updating CLI... |
 Error: Channel "stable" not found.

**Comment by clairebianchi** [comment]
@leonardopmacedo are you behind a firewall or proxy? Or do you have any SFDX environment variables set?

**Comment by leonardopmacedo** [comment]
No, I am not under a firewall. But this morning I managed to update.

**Comment by cropredy-twa** [comment]
I ran into this today and resolved it by noticing there was a pending Windows Update (so I did `Start Menu | Restart`).  `sfdx update` then worked fine

**Comment by saikiran2304** [comment]
> No, I am not under a firewall. But this morning I managed to update.

How did you did this Leonardo?

I am facing the same issue
