### ISSUE TITLE
sfdx-cli  force error: Value is undefined

### ISSUE THREAD

**Issue by ytiq** [forcedotcom/cli#390]
### Summary

When running any force command [error is displayed](https://imgur.com/a/3yvtZYh)

### Steps To Reproduce:

1. Install latest version of sfdx on Windows and 
2. try running any force command. 
Tried running `sfdx plugins:install sfdx-cli@7.26.0` to downgrade cli, but it didn't work.

### Expected result

when running `sfdx force:org:list` list of orgs should be displayed

### Actual result

[error is displayed](https://imgur.com/a/3yvtZYh)

**SFDX CLI Version**: sfdx-cli/7.56.1-2773b53bf5 win32-x64 node-v10.15.3
**SFDX plugin Version**: salesforcedx 48.12.1
**OS and version**: Windows 10

**Comment by ytiq** [comment]
Found an issue - adding any additional parameters to .sfdx\sfdx-config.json will cause force commands to fail.

Is it possible to fix it?

example of json file
{
    "defaultdevhubusername": "test",
    "defaultusername": "test1",
    "test": "test"
}

**Comment by amphro** [comment]
FWIW, you should never directly modify the contents of that file.
