### ISSUE TITLE
Command failed with ENOENT: npm root -g --prefix /root/.sfdx/.yo-repository

### ISSUE THREAD

**Issue by cerbaire** [forcedotcom/cli#391]
Install: 
curl https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz -o "sfdx.tar.xz" && mkdir sfdx && tar -xvJf sfdx.tar.xz >/dev/null 2>&1 -C sfdx --strip-components=1 && \
    cd sfdx && \
    ./install && \
    cd .. && \
    rm -rf sfdx && \
    rm sfdx.tar.xz

root@65469579c4-l97lz:~# sfdx force:project:create -n myProject --json
{
    "status": 1,
    "name": "Error",
    "message": "Command failed with ENOENT: npm root -g --prefix /root/.sfdx/.yo-repository --loglevel error\nspawnSync npm ENOENT",
    "exitCode": 1,
    "commandName": "Project",
    "stack": "Error: Command failed with ENOENT: npm root -g --prefix /root/.sfdx/.yo-repository --loglevel error\nspawnSync npm ENOENT\n    at Object.spawnSync (internal/child_process.js:990:20)\n    at Object.spawnSync (child_process.js:601:24)\n    at Function.module.exports.sync (/usr/local/lib/sfdx/node_modules/salesforcedx-templates/node_modules/execa/index.js:169:25)\n    at Object.runPackageManager (/usr/local/lib/sfdx/node_modules/salesforcedx-templates/node_modules/yeoman-environment/lib/util/repository.js:114:18)\n    at Object.get nodeModulesPath [as nodeModulesPath] (/usr/local/lib/sfdx/node_modules/salesforcedx-templates/node_modules/yeoman-environment/lib/util/repository.js:40:36)\n    at Function.assign (<anonymous>)\n    at new Environment (/usr/local/lib/sfdx/node_modules/salesforcedx-templates/node_modules/yeoman-environment/lib/environment.js:257:30)\n    at Function.createEnv (/usr/local/lib/sfdx/node_modules/salesforcedx-templates/node_modules/yeoman-environment/lib/environment.js:113:12)\n    at Project.<anonymous> (/usr/local/lib/sfdx/node_modules/salesforcedx-templates/lib/utils/templateCommand.js:40:32)\n    at Generator.next (<anonymous>)\nOuter stack:\n    at Function.wrap (/usr/local/lib/sfdx/node_modules/salesforcedx-templates/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/sfdxError.js:151:27)\n    at Project.catch (/usr/local/lib/sfdx/node_modules/salesforcedx-templates/node_modules/@salesforce/command/lib/sfdxCommand.js:255:67)",
    "warnings": []
}

root@65469579c4-l97lz:~# sfdx --version
sfdx-cli/7.56.1-2773b53bf5 linux-x64 node-v10.15.3
root@65469579c4-l97lz:~# sfdx --version
sfdx-cli/7.56.1-2773b53bf5 linux-x64 node-v10.15.3
root@65469579c4-l97lz:~# sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.12.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.10.0 (core)
└─ salesforce-alm 48.12.0 (core)

sfdx-cli 7.56.1 (core)
root@65469579c4-l97lz:~# sfdx update
sfdx-cli: Updating CLI... already on latest version: 7.56.1-2773b53bf5
root@65469579c4-l97lz:~#

**Comment by skostojohn** [comment]
I am getting a similar error trying to create a new class via the cli.  Running 7.57.1-dbf54fc584 on Ubuntu 18.04.

![image](https://user-images.githubusercontent.com/2495345/81623779-526f3f80-93a9-11ea-992e-9f972b5272b1.png)


Any advice would be great - thank you!

**Comment by ulistaerk** [comment]
Same Issue on Windows x64 with current version

C:\Users\Enigma\Workspace VS Code>sfdx update
sfdx-cli: Updating CLI... already on latest version: 7.57.1-dbf54fc584

C:\Users\Enigma\Workspace VS Code>sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.13.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.10.0 (core)
└─ salesforce-alm 48.14.0 (core)

sfdx-cli 7.57.1 (core)

C:\Users\Enigma\Workspace VS Code>sfdx force:project:create -n test --loglevel=trace
ERROR running force:project:create:  Command failed with exit code 1: npm root -g --prefix C:\Users\Enigma\Workspace VS Code\.yo-repository --loglevel error
Der Befehl "npm" ist entweder falsch geschrieben oder konnte nicht gefunden werden.

**Comment by ulistaerk** [comment]
The Ubuntu-Tarball is also broken as @cerbaire reported:
```
https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

./sfdx-cli-v7.57.1-dbf54fc584-linux-x64/bin/sfdx force:project:create -n foo
ERROR running force:project:create:  Command failed with ENOENT: npm root -g --prefix /home/enigma/sfdx/.yo-repository --loglevel error
spawnSync npm ENOENT
```

I also noticed that the directory-structure under Windows seems to be quite strange, is this a problem? 
![wrong-directories](https://user-images.githubusercontent.com/1297888/81699473-b22c2000-9467-11ea-980a-93046a7f8c10.PNG)

**Comment by ulistaerk** [comment]
@skostojohn 
Scott, you can use the package version, that seems to work for my Ubuntu 18:
- sudo apt-get install build-essential (dunno if required)
- Download and execute https://deb.nodesource.com/setup_10.x
- sudo apt-get install nodejs
- sudo npm install --global sfdx-cli

**Comment by clairebianchi** [comment]
This was fixed this week. Can you please update your CLI and try again. Thank you for reporting this issue.

**Comment by cerbaire** [comment]
Thx. I do have this bug anymore with the version as of today.
But I have a new one #409.
