### ISSUE TITLE
Missing sfdx url on linux machines force:org:display --verbose

### ISSUE THREAD

**Issue by mystery124** [forcedotcom/cli#395]
### Summary

I'm trying to get sfdx ulr on linux machine and I'm failed. Work pefectly fine on Windows PC. It's seems like either --verbose doesn't work on Linux or refresh token is not there as it's also not present .sfdx cataloge.
I'm trying to use CI and docker to manage scratch orgs. Therefore I need to have option to create and use scratch orgs in separete jobs/builds.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Create any scratch org
1.  execute follwing command:
sfdx force:org:display  --verbose -u <username for created scratch org>

### Expected result

sfdxURL should be display in the results

### Actual result

sfdxURL is missing

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/13795259/81296708-98a76480-9072-11ea-99bf-f654a573db32.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.56.1-2773b53bf5 linux-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.12.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.10.0 (core)
└─ salesforce-alm 48.12.0 (core)

sfdx-cli 7.56.1 (core)

**OS and version**:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by mystery124** [comment]
> ### Summary
> I'm trying to get sfdx ulr on linux machine and I'm failed. Work pefectly fine on Windows PC.
> I'm trying to use CI and docker to manage scratch orgs. Therefore I need to have option to create and use scratch orgs in separete jobs/builds.
> 
> ### Steps To Reproduce:
> **Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)
> 
> _**NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem._
> 
> 1. Create any scratch org
> 2. execute follwing command:
>    sfdx force:org:display  --verbose -u
> 
> ### Expected result
> sfdxURL should be display in the results
> 
> ### Actual result
> sfdxURL is missing
> 
> ### Additional information
> _Feel free to attach a screenshot_.
> ![image](https://user-images.githubusercontent.com/13795259/81296708-98a76480-9072-11ea-99bf-f654a573db32.png)
> 
> **SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
> sfdx-cli/7.56.1-2773b53bf5 linux-x64 node-v10.15.3
> 
> **SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
> @oclif/plugin-autocomplete 0.1.5 (core)
> @oclif/plugin-commands 1.2.3 (core)
> @oclif/plugin-help 2.2.3 (core)
> @oclif/plugin-not-found 1.2.3 (core)
> @oclif/plugin-plugins 1.7.9 (core)
> @oclif/plugin-update 1.3.9 (core)
> @oclif/plugin-warn-if-update-available 1.7.0 (core)
> @oclif/plugin-which 1.0.3 (core)
> @salesforce/sfdx-trust 3.0.7 (core)
> analytics 1.7.1 (core)
> generator 1.1.2 (core)
> salesforcedx 48.12.1 (core)
> ├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
> ├─ salesforcedx-templates 48.10.0 (core)
> └─ salesforce-alm 48.12.0 (core)
> 
> sfdx-cli 7.56.1 (core)
> 
> **OS and version**:
> Distributor ID: Ubuntu
> Description: Ubuntu 18.04.4 LTS
> Release: 18.04
> Codename: bionic

**Comment by amphro** [comment]
@mystery124 - is the dev hub authenticated by the JWT flow? Scratch org auth follows that of the dev hub and we don't have a refresh token for JWT auth, so we can't generate an sfdx url.

**Comment by mystery124** [comment]
@amphro actually that's the case. I use CI tool to create a scratch org and JWT flow to auth to the Dev Hub. I didn't know that it's expected. So if the scratch org is created on CI/CD tool the only way to access it outside of that tool (ie. on my local machine) is to use credentials?

**Comment by amphro** [comment]
Correct, to a certain extent. The biggest problem is we don't store the client secret for JWT configurations but we need that for the oauth flow. You have three options:

1. Set the environment variable `SFDX_CLIENT_SECRET` of the connect app. This will have the CLI try to authenticate the scratch org using oauth, which will give you a refresh token, which will make it so you can get the auth url.
1. Put the JWT cert on your local box and authenticate to the scratch org using the `force:auth:jwt:grant` flow.
1. Generate a password for that scratch org on the CI machine that is already authed, and use that password to go through the `force:auth:web:login` flow.

Hope that helps.
