### ISSUE TITLE
sfdx force:org:list does not display scratch org under scratch org list

### ISSUE THREAD

**Issue by kvor** [forcedotcom/cli#398]
### Summary

Scratch orgs are shown in Hub/Org list and not in scratch org.

### Steps To Reproduce:

1.  Run sfdx force:auth:web:login -r https://test.salesforce.com -a kv0508
2. Run sfdx force:org:list 
3. scratch org is shown under Org list

### Expected result

scratch org should be displayed under scratch org list.

### Actual result

scratch org is shown under Org list

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.57.1-dbf54fc584 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
sfdx plugins --core
**OS and version**:
MacOS 10.15.4

**Comment by nramyasri-sf** [comment]
@kvor , I am unable to reproduce this. Is this still an issue? Are there any further details you could provide that could potentially help me reproduce this?When you go into the auth file of any scratch org thats being displayed in the org list, what fields do you see?

Also, any logs that could provide info on the errant behavior of the command  would also be helpful.

**Comment by kvor** [comment]
@nramyasri-sf  Yes it is still reproducible (sfdx cli 48.14.3). Scratch orgs are displayed in Hub Org list. I am not sure how you are trying to reproduce it. You should try to connect to multiple Sandboxes, Production Orgs and scratch orgs.

This is a scratch org info which we see it Org list and not in Scratch org list
```
      {
        "username": "test-q4jmdmnvzqsz@example.com",
        "orgId": "00D210000003ZSIEA2",
        "accessToken": "xxx",
        "instanceUrl": "https://site-inspiration-3834-dev-ed.cs26.my.salesforce.com",
        "loginUrl": "https://test.salesforce.com/",
        "clientId": "PlatformCLI",
        "alias": "kv0508",
        "lastUsed": "2020-05-15T05:33:11.519Z",
        "connectedStatus": "Connected"
      },
```
So, from this scratch org info many json attributes are missing.

And this is another scratch org where multiple users of same scratch org are now displayed Scratch org list

```
      {
        "username": "test.ipxxx+0511-8deaac0eb7d7@xxx",
        "orgId": "00D8A000000C4A4UAK",
        "accessToken": "xxx",
        "instanceUrl": "https://momentum-force-2xxx-dev-ed.cs45.my.salesforce.com",
        "loginUrl": "https://CS45.salesforce.com",
        "clientId": "PlatformCLI",
        "createdOrgInstance": "CS45",
        "created": "1589092101000",
        "devHubUsername": "xxxx",
        "scratchAdminUsername": "0511-8deaac0eb7d7@xxx",
        "userProfileName": "IP xxx",
        "userId": "0058A000004Pp9QQAS",
        "expirationDate": "2020-05-25",
        "lastUsed": "2020-05-11T10:12:05.067Z",
        "status": "Active",
        "isExpired": false
      }
  {
        "username": "0511-8deaac0eb7d7@xxx",
        "orgId": "00D8A000000C4A4UAK",
        "accessToken": "xxx",
        "instanceUrl": "https://momentum-force-2xxx-dev-ed.cs45.my.salesforce.com/",
        "loginUrl": "https://CS45.salesforce.com",
        "clientId": "PlatformCLI",
        "createdOrgInstance": "CS45",
        "created": "1589176822631",
        "devHubUsername": "xxx",
        "isDevHub": false,
        "expirationDate": "2020-05-25",
        "alias": "0511",
        "lastUsed": "2020-05-12T09:16:18.081Z",
        "status": "Active",
        "isExpired": false,
        "signupUsername": "0511-8deaac0eb7d7@xx",
        "createdBy": "xxx",
        "createdDate": "2020-05-11T06:00:10.000+0000",
        "devHubOrgId": "00D30000001GuvSEAS",
        "attributes": {
          "type": "ScratchOrgInfo",
          "url": "/services/data/v48.0/sobjects/ScratchOrgInfo/2SR4Q000000HjyFWAS"
        },
        "orgName": "IPxxx",
        "edition": "Developer",
        "connectedStatus": "Unknown"
      }
```

It seems that something was changed in last 2 versions and breaks force:org:list response.

**Comment by kvor** [comment]
@clairebianchi Is there any status update on this?

**Comment by mshanemc** [comment]
@kvor the short answer is that we add scratch orgs to the scratch org list when they're created from a hub using `org:create` (and the auth files include information about the hub so future `org:list` can ask the hub about the org's status.

If you do what you did (web:auth to an org that you got login credentials for) there's not an easy way for the CLI to know that it is a scratch org OR which hub created it (possibly even a hub that CLI isn't auth'd to) so it's treated like a non-scratch org.

**Comment by toddhalfpenny** [comment]
I'm also seeing scratch orgs not being listed in `sfdx force:org:list`.

I have just created one with this `sfdx force:org:create -s -f config/project-scratch-def.json --json -d 30 -a  my-scratch` and the org was created and can be seen in our dev hub.

I can also run commands using the alias `my-scratch`, but it's just not appearing in the `list` results. For example if I run `sfdx force:org:display -u my-scratch` then I see the details.

Currently using *sfdx-cli/7.92.0-88320113e7 linux-x64 node-v14.15.4*

Happy to do further commands/digging if it helps @mshanemc .

In fact I've noticed that other active scratch orgs (but not all) are also missing :/

**Comment by toddhalfpenny** [comment]
Ah I wonder if this is related to #940, could be.

**UPDATE**: Yes, installing the *org* plugin as recommended in #940 fixed it.
`sfdx plugins:install org`.
After running this I see three scratch orgs that I had but were not being listed. Pretty sure all 3 had passwords generated for them.
