### ISSUE TITLE
Add single package support to metadata deploy command

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/cli#4]
**Is your feature request related to a problem? Please describe.**
We are unable to deploy zip files that contain a single package as there is no `--singlepackage` flag.

```
$ sfdx force:mdapi:deploy -c -f build/src-package.zip -u alan -w -1
Deploying /home/alan/repos/salesforce/build/src-package.zip...

Deployment finished in 1000ms

=== Result
Status: Failed
jobid: 0Afc000001XMXCxCAP
Completed: 2018-08-23T22:16:08.000Z
Component errors: 0
Components checked: 0
Components total: 0
Tests errors: 0
Tests completed: 0
Tests total: 0
Check only: true

=== Component Failures [1]
TYPE FILE NAME PROBLEM
───── ────────────────── ─────────── ────────────────────
Error labels/package.xml package.xml No package.xml found

ERROR: The metadata deploy operation failed.
```

The Ant Migration Tool provides the single package parameter that can be used with the `sf:deploy` target.

> `singlePackage` - Optional. Defaults to false. Declares that the zipFile or deployRoot parameter points to a directory structure with a single package, as opposed to a set of packages.
>
> &ndash; [Ant Migration Tool Guide : Deploying Changes to a Salesforce Org](https://developer.salesforce.com/docs/atlas.en-us.daas.meta/daas/forcemigrationtool_deploy.htm)

Another scenario where this is a problem, is when we retrieve a package using `sfdx force:mdapi:retrieve --singlepackage`, the zip file retrieved is not deployable using `sfdx force:mdapi:deploy` due to missing flag. This breaks symmetry of these commands.

**What are you trying to do**
We are currently using a mix of Ant Migration Tool and `sfdx`. The zip files we create as part of our build process are single package zip files, these are currently deployable using `ant`, however, we are unable to deploy the same zip file with `sfdx` due to missing flag. Having this flag available would really help us to transition away from `ant` and use `sfdx`.

**Describe the solution you'd like**
Add support for the `--singlepackage` flag to the `sfdx force:mdapi:deploy` command, so that it is possible to deploy zip package in this format and also add symmetry between `sfdx force:mdapi:deploy` and `sfdx force:mdapi:retrieve`

**Describe alternatives you've considered**
As a work around, we can unzip the single package and use the `--deploydir` flag for deploy but this is cumbersome.

**Comment by clairebianchi** [comment]
@alan-morey Thank you for the feedback the team that owns the MDAPI commands has this work scheduled for the latter half of 2019. Thank you for the feedback.
