### ISSUE TITLE
Unable to deploy 'Quote' related changes using force:source:deploy

### ISSUE THREAD

**Issue by bishwambharsen** [forcedotcom/cli#40]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:

**Comment by bishwambharsen** [comment]
Parent entity failed to deploy. This is the error being thrown by the CLI when I am trying to create a package version or deploy to another sandbox. Unable to handle Quote.

**Comment by clairebianchi** [comment]
@bishwambharsen we will investigate, thank you for letting us know

**Comment by shetzel** [comment]
@bishwambharsen - I'm not able to reproduce that error.  However, you didn't include exact repro steps or fill out the issue template so I can't be sure it's not a bug. Aafter making local changes to the quote I tried `sfdx force:source:deploy -p force-app/main/default/objects/Quote` to a new org and it worked fine.  If you are still having problems with this please complete the issue template and reopen.
