### ISSUE TITLE
Omnichannel not activated when specified in the scratch definition file 

### ISSUE THREAD

**Issue by mohametso** [forcedotcom/cli#404]
When creating the scratch org the omnichannel that supposed to be activated, is not 
I'm Using Mac OS Catalina
And the CLI version is:  sfdx-cli/7.57.1-dbf54fc584 darwin-x64 node-v10.15.3

Bellow the extract of our scratch org definition file.

{
  "orgName": "Demo company",
  "edition": "Enterprise",
  "language": "fr",
"features": ["PersonAccounts","Workflow","MarketingUser","SalesUser","Knowledge","ServiceCloud","AdditionalFieldHistory:40","RecordTypes","FieldAuditTrail"],
  "settings": {
    "chatterSettings": {
        "enableChatter": true
    },
    "quoteSettings": {
      "enableQuote": true
    },
    "omniChannelSettings": {
        "enableOmniChannel": true  
    },
    "opportunitySettings": {
      "enableOpportunityFieldHistoryTracking": true   
    },
    "accountSettings": {
      "showViewHierarchyLink": true  
    },
    "enhancedNotesSettings": {
      "enableEnhancedNotes": true,
      "enableTasksOnEnhancedNotes" : true
    },
    "userManagementSettings": {
      "enableNewProfileUI": true
    },
    "surveySettings": {
      "enableSurvey": true 
    },
    "pathAssistantSettings": {
      "pathAssistantEnabled": true 
    }
  }
}

**Comment by clairebianchi** [comment]
@mohametso  I have let the scratch org team know you have encountered this issue

**Comment by cristiand391** [comment]
closing this since it seems it was a related to a specific org. If someone else gets a similar error please log a new issue.
