### ISSUE TITLE
EEXIST: file already exists, mkdir '/projects/sfdxProject/.sfdx/orgs/00D5I000002uMAd!ARAAQE.8pWn93bQ6bFOiqJ8M_6TMuHlTy4I8Idot9j_sx7V94dYH3KqxsaT95IsYKnwuG2dhIbSiRiBlRnBpGhucN0RW.n2.

### ISSUE THREAD

**Issue by cerbaire** [forcedotcom/cli#409]
### Summary

I am retrieving metadata of an org using the following command :
"/usr/local/bin/sfdx force:source:retrieve -x /projects/sfdxProject/package.xml -u 00D5I000002uMAd!ARAAQE.8pWn93bQ6bFOiqJ8M_6TMuHlTy4I8Idot9j_sx7V94dYH3KqxsaT95IsYKnwuG2dhIbSiRiBlRnBpGhucN0RW.n2. --json 2>&1"

I have the following output :
"{"
1:"  "status": 1,"
2:"  "name": "Error","
3:"  "message": "EEXIST: file already exists, mkdir '/projects/sfdxProject/.sfdx/orgs/00D5I000002uMAd!ARAAQE.8pWn93bQ6bFOiqJ8M_6TMuHlTy4I8Idot9j_sx7V94dYH3KqxsaT95IsYKnwuG2dhIbSiRiBlRnBpGhucN0RW.n2.'","
4:"  "exitCode": 1,"
5:"  "commandName": "SourceRetrieveCommand","
6:"  "stack": "Error: EEXIST: file already exists, mkdir '/projects/sfdxProject/.sfdx/orgs/00D5I000002uMAd!ARAAQE.8pWn93bQ6bFOiqJ8M_6TMuHlTy4I8Idot9j_sx7V94dYH3KqxsaT95IsYKnwuG2dhIbSiRiBlRnBpGhucN0RW.n2.'\n    at Object.mkdirSync (fs.js:752:3)\n    at sync (/usr/local/lib/sfdx/node_modules/mkdirp/index.js:71:13)\n    at sync (/usr/local/lib/sfdx/node_modules/mkdirp/index.js:78:17)\n    at Proxy.sync (/usr/local/lib/sfdx/node_modules/mkdirp/index.js:78:17)\n    at StateFile._write (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/core/scratchOrgApi.js:87:16)\n    at StateFile.write (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/core/scratchOrgApi.js:112:14)\n    at scratchOrg.resolveDefaultName.then.then.then.then.typeDefs (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/metadataRegistry.js:554:38)\n    at tryCatcher (/usr/local/lib/sfdx/node_modules/salesforce-alm/node_modules/bluebird/js/release/util.js:16:23)\...
7:"  "warnings": []"
8:"}"

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.58.2-937f666ed4 linux-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.14.3 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.17.0 (core)
└─ salesforce-alm 48.15.0 (core)

sfdx-cli 7.58.2 (core)

**OS and version**:
Linux project-5c88c7bcf6-b5qk4 4.19.76-linuxkit #1 SMP Fri Apr 3 15:53:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mdonnalley** [comment]
@cerbaire Could you provide more detailed steps to reproduce?
