### ISSUE TITLE
sfdx plugins:install not working with Private NPM Registry

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#410]
When running sfdx plugins:install hpe-sfdx-plugins, I receive the following message

![image](https://user-images.githubusercontent.com/55927613/82245811-8ca58780-993b-11ea-94c8-f06289314fe7.png)

If I use the public NPM registry everything works fine. Due to compliance issues I had to migrate my package to a private registry and now I can't install the plugin.
The only thing I changed in the Plugin's package.json was this

![image](https://user-images.githubusercontent.com/55927613/82245946-c4acca80-993b-11ea-9432-be1eb26b3538.png)

I'm also able to install the package without a problem if I use ````npm install hpe-sfdx-plugins```` instead of the sfdx install command.

In the image below I show my global registry (the private one), and after that I install with success the hpe-sfdx-plugins package and then I try to install using ````sfdx plugins:install hpe-sfdx-plugins```` and it does not work.
![image](https://user-images.githubusercontent.com/55927613/82251489-363d4680-9945-11ea-8114-80384f9fcd8a.png)

**Comment by AllanOricil** [comment]
After debugging the code that installs the plugin. I was able to install the plugin from my private registry by changing this file locally

````...\sfdx\client\7.57.1-dbf54fc584\node_modules\@salesforce\sfdx-trust\dist\codeSigning\installationVerification.js````

````javascript
exports.getNpmRegistry = () => {
    return new url_1.URL('http://repo1.core.hpecorp.net/nexus/content/repositories/npm-internal' || exports.DEFAULT_REGISTRY);
};
````

Before that, I tried to setup the SFDX_NPM_REGISTRY env variable and it also fixed my issue. The package started to be located, but a new problem appeared. Sfdx started to look for ALL the dependencies from my private registry.

![image](https://user-images.githubusercontent.com/55927613/82256632-984e7980-994e-11ea-97ab-551f55fe31ae.png)

Then I discarded this solution and opted to hard code my registry directly in that getNpmRegistry line. And this was the result.

![image](https://user-images.githubusercontent.com/55927613/82257113-6558b580-994f-11ea-92f6-a7b7048342e0.png)


I think we need a new way of getting the Metadata of a package from a registry. Could you point me out to the github repository for this change? I can help to fix it if you need.

**Comment by AllanOricil** [comment]
Another finding that I forgot to post here. This verification step SFDX souce code does, does not happen for the command `sfdx plugins:update`. So after I apply my fix and install the plugin for the first time, I no longer need to change anything. I just have to run `sfdx plugins:update` and my plugin, hosted in a private package manager, will update with no problem.

**Comment by AllanOricil** [comment]
@amphro now my hack to publish to a private npm is no longer working. I noticed the line to get the right npm registry has been changed.

**Comment by AllanOricil** [comment]
@amphro Have you guys found a way to enable us to work with both private and public package manager? 

I created this small script to fix that for me 

````js
const fs = require('fs');
const os = require('os');
const path = require('path');
const execSync = require('child_process').execSync;
const HOMEDIR = os.homedir();
const output = execSync('sfdx --version');
const SFDX_VERSION = output.toString().split(' ')[0].split('/')[1];
const OS_SPECIFIC_FILE_PATH_PREFIX = os.platform() === 'win32' ? `/AppData/Local/` : `/.local/share/`;
const FILE_PATH = `${HOMEDIR}${OS_SPECIFIC_FILE_PATH_PREFIX}sfdx/client/${SFDX_VERSION}/node_modules/@salesforce/sfdx-trust/dist/codeSigning/installationVerification.js`;
const file = fs.readFileSync(path.resolve(FILE_PATH));
const newFile = file.toString().replace('process.env.SFDX_NPM_REGISTRY', '"https://repo1.core.hpecorp.net/nexus/content/groups/npm-all"');
fs.writeFileSync(FILE_PATH, newFile, {encoding: 'utf-8'});
````

and then I have one that rollback the changes, because if I leave it like the above then sfdx will try to use our private package manager to locate all the other dependencies and then it fails.

**Comment by amphro** [comment]
If I'm reading this right, you want to install the plugin from your private registry but all the dependencies on the public registry? Is there any reason why you can't have your private registry fall back to the public registry if it doesn't have them. That is how most node package registries work.

The reason why setting SFDX_NPM_REGISTRY doesn't work is because that is also used for the [yarn install](https://github.com/oclif/plugin-plugins/blob/82f84344e2c15978f0ad586060539d489fd122be/src/yarn.ts#L61). That seems like the correct behavior to me.

The code is here: https://github.com/salesforcecli/plugin-trust/ Feel free to create a PR if you think of a solution. I think it would be moving the[ allowlist check](https://github.com/salesforcecli/plugin-trust/blob/main/src/lib/installationVerification.ts#L535) higher up so we never even query the npm metadata. See more about [allowlist](https://github.com/salesforcecli/plugin-trust/#allowlisting).

**Comment by AllanOricil** [comment]
@amphro yes, you are right. The plugin is inside Nexus, and its dependencies come from outside. If I had access to Nexus I could configure it to fall back to the public registry, but I don't. Also, Nexus seems to be used only for internal packages. Any time we want a package from the public registry we need to manually add them to our .npmrc config, for instance. 
But there is a guy called Verdaccio that would do this fall back process to me. I just did not test it at HPE yet. I'm using it for a project and it is very cool. He proxies the requests to registries if it does not find the package locally. So I don't need to keep doing it manually. The only downside is that I need to install it before installing the plugin. 
If I have time I will investigate the code and try to implement a solution.

**Comment by AllanOricil** [comment]
Just to let everyone know that I was able to make it work using Verdaccio. Just install Verdaccio and set SFDX_NPM_REGISTRY to point to your verdaccio instance. Then verdaccio is gonna take care of proxying the requests to the public npm registry when needed and your package/plugin will be private to your organization.

**Comment by smukov** [comment]
I faced similar problems but it was much easier to solve as my plugin had a defined scope (e.g. `@xyz`) and then all that was required to do was to set the registry for that scope in root `.nmprc` file by adding the following line:

`@xyz:registry = add_registry_url_here`

**Comment by ansu0122** [comment]
Regardless of the scope I still can install my plugin only via using http url...
Was the problem resolved?

**Comment by AllanOricil** [comment]
> Regardless of the scope I still can install my plugin only via using http url...
> Was the problem resolved?

@ansu0122 did u try verdaccio?
