### ISSUE TITLE
force:mdapi:listmetadata returns an array or an object depending on the number of results

### ISSUE THREAD

**Issue by rubenef** [forcedotcom/cli#413]
### Summary

When calling force:mdapi:listmetadata the type of the response result varies depending on the number of records returned. A better approach would be to always return an array to guarantee the integrity of response format.

### Steps To Reproduce:

1. Run a list metadata command which returns a single record.

```sfdx force:mdapi:listmetadata -m LeadConvertSettings --json```

```
{
	"status": 0,
	"result": {
		...
		"type": "LeadConvertSettings",
		...
	}
}
```

2. Run a list metadata command which returns multiple records.

```sfdx force:mdapi:listmetadata -m CustomPermission --json```

```
{
	"status": 0,
	"result": [{
		...
		"type": "CustomPermission",
		...
	}, {
		...
		"type": "CustomPermission",
		...
	}]
}
```

### Expected result

```sfdx force:mdapi:listmetadata -m LeadConvertSettings --json```

```
{
	"status": 0,
	"result": [{
		...
		"type": "LeadConvertSettings",
		...
	}]
}
```

### Additional information

**SFDX CLI Version**:

sfdx-cli/7.57.1-dbf54fc584 win32-x64 node-v10.15.3

**OS and version**:

Windows 10.0.18363 Build 18363

**Comment by mshanemc** [comment]
On current versions, the result is always an array
