### ISSUE TITLE
MutingPermissionSet not currently supported by the CLI

### ISSUE THREAD

**Issue by adnan-khanSFDC** [forcedotcom/cli#415]
### Summary
Got this error while doing a retrieve:

RROR running force:source:retrieve:  We can’t retrieve the specified metadata object: MutingPermissionSet. Certain metadata types, like MutingPermissionSet are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type

### Steps To Reproduce:

add a MutingPermissionSet to a sandbox and do a retrieve on it

### Expected result

CLI should pull it

### Actual result

Get error described above in the summary

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.58.2-937f666ed4 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.14.3 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.17.0 (core)
└─ salesforce-alm 48.15.0 (core)

sfdx-cli 7.58.2 (core)
shane-sfdx-plugins 4.28.2

**Comment by clairebianchi** [comment]
@adnan-khanSFDC thank you, I am informing the team that owns this metadata to get it fixed.

**Comment by mshanemc** [comment]
closing...see thread on similar issue https://github.com/forcedotcom/cli/issues/339
