### ISSUE TITLE
force:user:display not showing correct password

### ISSUE THREAD

**Issue by dchiado** [forcedotcom/cli#417]
### Summary

When running `sfdx force:user:display -u username`, the output doesn't display the password correctly after upgrading to sfdx-cli/7.58.2-937f666ed4. It's displaying as a hash instead of the plaintext version.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1. Create a scratch org. Command used:
`sfdx force:org:create -s -f config/project-scratch-def.json -a dreamhouse`
1.  Generate a password for the user. Command used:
`sfdx force:user:password:generate -u dreamhouse --json`
1. Try to display the user info, including the password. Command used:
`sfdx force:user:display -u defaultusername@example.com`

### Expected result

The force:user:display output contains the plaintext password

Password      plaintextpwd
Profile Name  System Administrator
Username      defaultusername@example.com

### Actual result

The output just shows a hash of the password.
Password      a646779e7659a741d01131a4dd3947c2:7f11316ec91fd7e17502aa6a4067fe85
Profile Name  System Administrator
Username      defaultusername@example.com

### Additional information

This only started happening after upgrading to the latest cli version 7.58.2-937f666ed4. The password is displayed fine for the default user when running `force:org:display` but doesn't work for `force:user:display`, whether for the default user or not.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.58.2-937f666ed4 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
altvia 0.0.0 (link) /Users/dylanchiado/dev/repos/scripts/plugins
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.14.3
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.17.0
└─ salesforce-alm 48.15.0

sfdx-cli 7.58.2 (core)

**OS and version**:
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287

**Comment by ajw725** [comment]
same here. i understand hashing passwords, but i thought the whole point of showing the password in the output of this command was so that we could actually log in as the scratch org users we created, and we need the plain text for that.

**Comment by yippie** [comment]
Same issue here!

**Comment by ImJohnMDaniel** [comment]
Same issue here

**Comment by eltoroit** [comment]
Same issue here

**Comment by pserquiz** [comment]
Same issue here. I'm on version sfdx-cli/7.59.0-05e06e37e0

**Comment by Appfrontier** [comment]
Looks like this is resolved in version: 7.68.6-d37008df83

**Comment by dchiado** [comment]
Just confirmed - working fine for me on sfdx-cli/7.68.6-d37008df83. Thanks!
