### ISSUE TITLE
Error in sfdx force:source:retrieve -m ManagedContentType:news

### ISSUE THREAD

**Issue by RajaPaul** [forcedotcom/cli#418]
### Summary
I was trying to get ManagedContentType with sfdx cli and org browser-VSCODE and it was throwing error

### Steps To Reproduce:

Connect an org to VSCODE which has ManagedContentType or create some metadata
Open VSCODE orgbrowser and try to pull that ManagedContentType metadata into source
You will get the following error 
```
Starting SFDX: Retrieve Source from Org

15:28:39.978 sfdx force:source:retrieve -m ManagedContentType:news
ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: ManagedContentType. Certain metadata types, like ManagedContentType are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
15:28:55.51 sfdx force:source:retrieve -m ManagedContentType:news
 ended with exit code 1
```

### Expected result

It should retrieve metadata

### Actual result
Throws error.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.59.0-05e06e37e0 win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
$ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.15.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.17.0 (core)
└─ salesforce-alm 48.16.0 (core)

sfdx-cli 7.59.0 (core)
sfdx-wry-plugin 0.0.11
sfpowerkit 1.45.1-4 (beta)

**OS and version**:
WIN 10

**Comment by AllanOricil** [comment]
And this Metadata type has [coverage](https://developer.salesforce.com/docs/metadata-coverage/48)

![image](https://user-images.githubusercontent.com/55927613/83255755-f11cde00-a1a8-11ea-87fb-242310e3ac3a.png)

**Comment by gwynnebaer** [comment]
Same issue: 
`ERROR running force:mdapi:convert:  An error was encountered processing path: metadata/unpackaged/managedContentTypes/news.managedContentType`

**Comment by clairebianchi** [comment]
@RajaPaul Thank you, we are contacting the team that owns this metadata to get them to fix it.

**Comment by amphro** [comment]
FWIW, "Source Tracking" in the coverage report, not so clearly, means support for source format in the CLI. The reason is without source tracking pull won't work which is what source format was originally for. Now that there is `source:deploy/retrieve` we need to be better about breaking that correlation.

**Comment by ctraxler-avi** [comment]
I am also awaiting this resolution

**Comment by gwynnebaer** [comment]
@clairebianchi - neither of the closed items above resolves this issue. It seems unclear if this was meant to say this issue (418) is resolved or not?

I still have this issue (though the error message from the CLI is more descriptive:)
`We can’t retrieve the specified metadata object: ManagedContentType. Certain metadata types, like ManagedContentType are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type`

**Comment by FabienTaillon** [comment]
Looks like this is coming in Winter '21:
https://trailblazers.salesforce.com/0D54S000006DEtG

**Comment by vaibhavdangar-woolies** [comment]
Hi @FabienTaillon and all,
Trust you are doing good. 

I'm unable to get the below CLI working:
cmd
sfdx force:source:retrieve --apiversion 54.0 -m ManagedContentType -u SF_USERNAME@DOMAIN

log:
[sfdx-log.txt](https://github.com/forcedotcom/cli/files/11096427/sfdx-log.txt)

Also tried SF CLI

cmd
sf retrieve metadata --api-version 54.0 --metadata ManagedContentType -o SF_USERNAME@DOMAIN

log:
[sf-log.txt](https://github.com/forcedotcom/cli/files/11096429/sf-log.txt)

**Comment by FabienTaillon** [comment]
@mdonnalley could you give some input on why it's not planned ? Is it because it's not supported by Source Tracking ?

**Comment by mdonnalley** [comment]
This was closed due to inactivity. Feel free to reopen if it's still an issue with the latest version of `sf`
