### ISSUE TITLE
Timeouts while creating scratch orgs and pushing source files

### ISSUE THREAD

**Issue by SalesforceRocks** [forcedotcom/cli#419]
### Summary

We experience extreme performance issues from time to time when using SFDX. Commands like sfdx force:org:create and sfdx force:source:push take an extremely long time or time out. It makes it impossible for us to use SFDX from time to time and since we are a Salesforce PDO/Platinum partner this really hurts our business.

The current issue started around 12.00 am Central European Time May 26th 2020 and it still doesn't work as expected (it's now 6.00 pm). This issue has occurred numerous times now. Unfortunately it is hard to replay since the issue comes and goes. 

### Steps To Reproduce:

Creating a scratch org with the following command takes a long time or results in a time out:

sfdx force:org:create -f config/project-scratch-def.json -a Companyinfo4

Time out message:
ERROR running force:org:create:  Socket timeout occurred while listening for results. 

Try this: 
You may consider increasing the --wait parameter value to increase timeout.

At the same time pushing source to an existing scratch org takes an extreme long time or times out. Command:

sfdx force:source:push -u Companyinfo

The org id of this scratch org is: 00D3N0000000ulOUAQ 

This problem has nothing to do with a certain code base, therefore we don't have provisioned a repository.

### Expected result

Pushing the metadata to a net new scratch org should take max. 5 minutes (and on average 2 minutes). Right now it takes 20.

Creation of a scratch org should be done within max 1 min (normally it takes 20 secs now 10 minutes or times out).

### Actual result

We got time outs and extreme performance issues. See above.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.59.0-05e06e37e0 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 47.15.0 (47.15.0)
├─ salesforcedx-templates 47.16.0
└─ salesforce-alm 47.14.0

sfdx-cli 7.59.0 (core)

**OS and version**:
MacOs Catalina 10.15.4

**Comment by clairebianchi** [comment]
@SalesforceRocks in order for us to help debug this you will need to file a case with support. We are unable to dig into your specific org issues without permissions which we get from support.
