### ISSUE TITLE
Cannot read property 'getWorkspaceElements' of undefined

### ISSUE THREAD

**Issue by rahulgawale** [forcedotcom/cli#420]
### Summary

I am using SFDX CLI with VS code, when I try to retrieve the changes from the Salesforce Org by right-clicking the `package.xml` -> `SFDX: Retrieve Source in Manifest From Org`. 
I got this error.
```
ERROR running force:source:retrieve:  Cannot read property 'getWorkspaceElements' of undefined
17:31:43.683 sfdx force:source:retrieve --manifest c:\Users\rahul.gawale\Documents\Textible\Textible\manifest\package.xml
 ended with exit code 1
```

### Steps To Reproduce:

I have this version of SFDX CLI = sfdx-cli/7.59.0-05e06e37e0 win32-x64 node-v10.15.3
I am facing this issue for multiple orgs. I have gone through [this issue](https://github.com/forcedotcom/cli/issues/78) and none of the options work for me.

I have this package.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>AuraDefinitionBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>LightningComponentBundle</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <types>
        <members>*</members>
        <name>PermissionSet</name>
    </types>
    <version>45.0</version>
</Package>
```

However, if I remove the below code from the p I get no error and refresh works successfully.
```
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
```

### Expected result

Refresh from org should work and I should be able to fetch all the metadata mentioned in the package.xml

### Actual result

Getting this error

```
ERROR running force:source:retrieve:  Cannot read property 'getWorkspaceElements' of undefined
17:31:43.683 sfdx force:source:retrieve --manifest c:\Users\rahul.gawale\Documents\Textible\Textible\manifest\package.xml
 ended with exit code 1
```

### Additional information

**SFDX CLI Version**: sfdx-cli/7.59.0-05e06e37e0 win32-x64 node-v10.15.3

**SFDX plugin Version**: sfdx-cli 7.59.0 (core)

**OS and version**: Windows 8 64 bit

**Comment by shetzel** [comment]
@rahulgawale 
Please see this issue: https://github.com/forcedotcom/cli/issues/345 .  If you could see my last post on that issue thread and follow the instructions it would help us, preferably with a small retrieve size (perhaps just the apex class) so the debug output size is more manageable.  If you modify the file I mentioned it should get you past the issue.  If you could please grab debug output from the problem (after updating that file) so we can put in a proper fix it would be greatly appreciated.

Is that apex class in your local project or would it be a new addition?
