### ISSUE TITLE
Include namespace in "sfdx force:org:display" result

### ISSUE THREAD

**Issue by toddhalfpenny** [forcedotcom/cli#422]
**Is your feature request related to a problem? Please describe.**
As far as I can see, the only way to get the namespace of an (scratch) org is to log into it.

**What are you trying to do**
Get the namespace of a (scratch) org from the CLI.

**Describe the solution you'd like**
Be great if the namespace was returned for a `sfdx force:org:display` call

**Describe alternatives you've considered**
Creating a plugin to do this using the soql `SELECT NamespacePrefix FROM Organization;`, or perhaps it's already available via `this.createOrg()`?

**Additional context**
n/a

**Comment by mshanemc** [comment]
@toddhalfpenny This **should** be added in the new open-source version.  You can try it early, here: https://github.com/forcedotcom/cli/issues/835

**Comment by mshanemc** [comment]
shipped it https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md#5140-march-18-2021---cli-7920
