### ISSUE TITLE
(incorrect) success status code reported for cancelled builds

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#425]
### Summary

If a test run (`deploy --checkonly`) is cancelled, sfdx reports a **successful** status code.

### Steps To Reproduce:

1. Deploy
1. Cancel the deploy

### Expected result

sfdx returns an error status code

### Actual result

sfdx returns a successful status code

### Additional information

sfdx as a tooling utility is useful to run tests in an automated system. It's the behavior of all cli test tools to only return a successful code if all tests pass. sfdx is the only tool I'm aware of that does not follow this convention and discards the the test result when returning a status.

**Comment by clairebianchi** [comment]
@AndrewRayCode we are talking a look, thanks for flagging

**Comment by MuriloKakazu** [comment]
This might be the same issue? https://github.com/forcedotcom/cli/issues/37

**Comment by mshanemc** [comment]
closed (duplicated of 237, also closed)
