### ISSUE TITLE
(incorrect) status code returned for timed out builds

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#426]
### Summary

If a test run (`deploy --checkonly`) takes longer than the timeout to complete, sfdx reports a **successful** status code.

### Steps To Reproduce:

1. Deploy
1. Have the deploy take longer than the timeout

### Expected result

sfdx returns an error status code

### Actual result

sfdx returns a successful status code

### Additional information

sfdx as a tooling utility is useful to run tests in an automated system. It's the behavior of all cli test tools to only return a successful code if all tests pass. sfdx is the only tool I'm aware of that does not follow this convention and discards the the test result when returning a status.

**Comment by MuriloKakazu** [comment]
In case anyone is also having this problem, there are some ways around it, one shown here: https://github.com/forcedotcom/cli/issues/461#issuecomment-653224404

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9125774](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000AeSFYA0/view)

**Comment by mshanemc** [comment]
closely related to https://github.com/forcedotcom/cli/issues/461

**Comment by mshanemc** [comment]
this got fixed in the new source-plugin.  It returns exitCode `69` for incomplete/timeout statuses for source commands
