### ISSUE TITLE
Using SFDX_MDAPI_TEMP_DIR Environment Variable does not keep metadata

### ISSUE THREAD

**Issue by mhosveolia** [forcedotcom/cli#428]
When setting SFDX_MDAPI_TEMP_DIR using export SFDX_MDAPI_TEMP_DIR=/c/.../metadata I see the temporary folder, package.xml, package folder get created then deleted as soon as a pull command is completed

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1. Set SFDX_MDAPI_TEMP_DIR using export SFDX_MDAPI_TEMP_DIR=/c/.../DreamHouse-sfdx/metadata
1.  Create new scratch Org
2. Push dreamhouse to sandbox
3. Make a change (add description to a field in Broker object)
4. use sfdx force:source:pull
5.  See temp folder getting created in metadata folder
6. pull command completes
7. Temp folder is deleted

I have also tried this with sfdx force:source:retrieve and
SFDX_MDAPI_TEMP_DIR=/c/..../DreamHouse-sfdx/metadata sfdx force:source:pull

### Expected result

Temp folder contains folder with package.xml and metadata

### Actual result

Temp folder is populated and then deleted.

### Additional information

I have tried this on multiple windows machines

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.60.0-e2bb2907cb win32-x86 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.16.2 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.18.0 (core)
└─ salesforce-alm 48.17.0 (core)

sfdx-cli 7.60.0 (core)
sfpowerkit 1.45.1
**OS and version**:
Windows 10 Pro x64 version:1809

**Comment by clairebianchi** [comment]
Thank you @mhosveolia we are taking a look

**Comment by shetzel** [comment]
@mhosveolia - what shell are you using?  If it's not the standard Windows command prompt or Powershell, it's probably not supported.  See this: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_considerations.htm

**Comment by mhosveolia** [comment]
@shetzel -  That was the problem.  I was using Git Bash and when I switched to command prompt it started working correctly.  Thanks!
