### ISSUE TITLE
sfdx cli network and certificate issues

### ISSUE THREAD

**Issue by s-jly** [forcedotcom/cli#429]
### Summary

- Running `sfdx-update` it returns 'Error: S3 Host is not reachable'.
- Running `sfdx force:auth:web:login --setalias test` it returns 'ERROR running force:auth:web:login:  self signed certificate in certificate chain'

### Steps To Reproduce:

Run above commands in terminal.

### Expected result

- sfdx is updated
- sfdx will login successfully

### Actual result

- sfdx does not update
- sfdx goes to a blank page

### Additional information
Additional Troubleshooting steps
- Restarting computer
- Swapping different network connections
- [Node Settings](https://salesforce.stackexchange.com/questions/236875/error-self-signed-certificate-in-certificate-chain-on-sfdx-forceauthweblo)

**SFDX CLI Version**: sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3

**OS and version**: Mojave 10.14.6

**Comment by bavinash83** [comment]
I am still facing this issue 
aburugur009233:~ aburugur$ sfdx force:auth:web:login --setalias test
ERROR running force:auth:web:login:  self signed certificate in certificate chain
aburugur009233:~ aburugur$ 
aburugur009233:~ aburugur$ sfdx version
sfdx-cli/7.36.0-b1c4e9c7c8 darwin-x64 node-v10.15.3
aburugur009233:~ aburugur$
