### ISSUE TITLE
 Unable to retrieve lwc files

### ISSUE THREAD

**Issue by babos47** [forcedotcom/cli#43]
### Summary
Hi,
i'm not able to retrieve LWC from Project created with manifest.
I tried many alternatives from this below  but i'm still face the same issue.
#33 

### Steps To Reproduce:

1. command : sfdx force:source:retrieve -m LightningComponentBundle
1. or Retrieve Source in Manifest from Org

### Actual result

![image](https://user-images.githubusercontent.com/5557554/53736702-c7ccaf80-3e8a-11e9-9a5a-235e6e0d3672.png)

### Additional information

SFDX CLI Version : **sfdx-cli/6.55.1-be0b3dc4c4**

**SFDX plugin Version**  : 
@salesforce/plugin-generator 1.0.1 (core)
@salesforce/sfdx-trust 2.0.1 (core)
builtins 1.0.0 (core)
salesforcedx 45.0.12 (pre-release)

**OS and version**: Windows 10

**Comment by shetzel** [comment]
You are on the pre-release version of the salesforcedx plugin.  That bug is fixed in the latest release (i.e., not pre-release).  Please uninstall the pre-release version (sfdx plugins:uninstall salesforcedx) and then update to the latest version (sfdx plugins:update salesforcedx).

**Comment by ThiruManoj** [comment]
Thanks it is working!!
