### ISSUE TITLE
Package as a snap like the Heroku CLI

### ISSUE THREAD

**Issue by sigmavirus24** [forcedotcom/cli#431]
**Is your feature request related to a problem? Please describe.**

I'd like to use the Salesforce DX CLI on my Fedora laptop to test out integrations I'm building. The [installation page][] only offers a download for Ubuntu and Debian. The Heroku (a Salesforce company) CLI is packaged and distributed via [snap][] which allows it to be managed and distributed across any linux distribution that supports snapcraft.

[installation page]: https://developer.salesforce.com/tools/sfdxcli#
[snap]: https://developer.salesforce.com/tools/sfdxcli#

**What are you trying to do**

Develop against Salesforce from a non-Ubuntu/Debian distribuion of Linux

**Describe the solution you'd like**

I'd like to see a download for other distributions of linux or a distribution via [snapcraft][snap]

**Describe alternatives you've considered**

I've considered attempting to build the CLI myself on Fedora but I'm neither confident there are instructions nor that the necessary source code is fully available

**Additional context**

N/A

**Comment by lurnforks** [comment]
The information on the installation page should be updated as it can easily be installed on Fedora:

```bash
wget -cO - https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xz
cd sfdx-linux-amd64
sudo ./install
```

**Comment by mccheesy** [comment]
The information on the installation page should be updated as it can easily be installed on Fedora:

```bash
wget -cO - https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xz
cd sfdx-linux-amd64/sfdx-cli*
sudo ./install
```

**Comment by amphro** [comment]
We likely aren't going to support snap for the CLI. As mentioned, just downloading the archive directly will work.
