### ISSUE TITLE
Scratch Org not appearing locally and it can't be deleted by the Creator

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#432]
### Summary
Somehow I have two Scratch Orgs that are not showing up locally when using `sfdx force:org:list --all` and I can't even delete them. But I know they are alive because an Administrator queried and showed them to me.

Here you can see that I don't have any Scratch Org created
![image](https://user-images.githubusercontent.com/55927613/84035116-31434400-a993-11ea-8724-d06b12454e6b.png)

These are the Scratch Orgs that are alive and I can't see locally
![image](https://user-images.githubusercontent.com/55927613/84034945-f214f300-a992-11ea-8726-223c1ac09982.png)

Here you can see I tried to delete them using the username. But I could not.
![image](https://user-images.githubusercontent.com/55927613/84034992-03f69600-a993-11ea-9155-f4e8f279a488.png)

<b>OBS</b>: I am using the DEV HUB where my username is allan.oricil@hpe.com and it is set as my default.

### Steps To Reproduce:
Don't know how to reproduce it.

**Repository to reproduce:**
It does not need a repository.

### Expected result
All the Scratch Orgs that I own should appear locally.

### Actual result
Some Scratch Orgs that I own are not appearing.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.60.0-e2bb2907cb win32-x64 node-v10.15.3

**OS and version**:
![image](https://user-images.githubusercontent.com/55927613/84035518-cb0af100-a993-11ea-83de-77462dd73de2.png)

**Comment by shetzel** [comment]
`force:org:list` displays all orgs the Salesforce CLI has created or authenticated to.  If you did not create or authenticate those scratch orgs with that CLI then it won't be listed.  This could happen if you use 2 different CLI installations or if there are multiple developers using the devhub to create scratch orgs.
https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_org.htm#cli_reference_list

**Comment by AllanOricil** [comment]
@shetzel could you give me more details so I can reproduce? Based on what you said, the problem was caused because I used two different sfdx versions. If so, why this is not a bug? 
On my team, each developer has its own account to the Dev Hub, and nobody can access somebody else's account. So it wouldn't be possible another developer to create those 2 extra (missing) scratch orgs on my name. If you look at the SOQL print screen I'm listed as the owner as well.
We need more details. I hope you can help. Thank you.
