### ISSUE TITLE
CLI does not correctly receive BASH variables for path-based deployment

### ISSUE THREAD

**Issue by JeffDanger** [forcedotcom/cli#434]
### Summary

I am writing a script for BitBucket pipelines to take the diff between our `feature` and `develop` branches, transform it into a comma-delimited list of files, and feed it to `sfdx force:source:deploy`.

The documentation says that any list of files containing spaces should be wrapped in double quotes.  When I write such a string to a variable, and pass that variable as an argument, I get an error as though the quotes are being ignored

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Run the following command:
        changes=`echo "force-app/main/default/layouts/Broker__c-Broker Layout.layout-meta.xml" | sed '/^force-app/!d' | tr '\n' ',' | sed 's/,$/\n/' | sed 's/^/"/;s/$/"/'`
1.  `echo $changes` to verify you have a quote-wrapped string
1. `sfdx force:source:deploy -p $changes`

### Expected result

The layout should be deployed

### Actual result

And error is given saying 

>  Unexpected arguments: Layout.layout-meta.xml"

### Additional information

Building this on BitBucket pipelines with this docker image: docker.io/salesforce/salesforcedx@sha256:8068fa616df3c3428b446004151b8b88dab328625273aacadce45e66c3eebc05

**Comment by reachsaiv** [comment]
@JeffDanger did you find any workaround for this? 
I am getting the same error while building the pipelines in bitbucket.

**Comment by clairebianchi** [comment]
@JeffDanger can you please update to the latest CLI and try again? We believe we have fixed this issue.
