### ISSUE TITLE
Can't install from `npm i -g sfdx-cli`

### ISSUE THREAD

**Issue by Confirm4Crit** [forcedotcom/cli#436]
Summary
Can't install from NPM anymore :(

Steps To Reproduce:
Run npm i -g sfdx-cli
Watch it error out
Expected result
Cli to update/install

Actual result
➜  ~ npm i -g sfdx-cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/REDACTED/.npm/_logs/2020-06-11T16_36_00_214Z-debug.log
Additional information:

Looks like [this may have happened before?](https://github.com/forcedotcom/cli/issues/304)

SFDX CLI Version(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.61.0 darwin-x64 node-v13.11.0

SFDX plugin Version(to find the version of the CLI plugin run sfdx plugins --core): salesforcedx 48.17.0 (core)

OS and version:
Catalina 10.15.2

**Comment by fushen16** [comment]
Hi, We have been running into a similar issue from our ADO cicd pipeline. How soon can this issue be fixed?

Here is the error message:

2020-06-11T17:01:20.3132732Z npm ERR! Cannot read property 'match' of undefined
2020-06-11T17:01:20.3132968Z npm verb exit [ 1, true ]
2020-06-11T17:01:20.3133165Z npm timing npm Completed in 49363ms
2020-06-11T17:01:20.3133308Z 
2020-06-11T17:01:20.3133537Z npm ERR! A complete log of this run can be found in:
2020-06-11T17:01:20.3133857Z npm ERR!     C:\npm\cache\_logs\2020-06-11T17_01_20_131Z-debug.log

Our environment is windows.
npm@6.14.4
node@v10.21.0
sfdx-cli@7.62.1.0

**Comment by shetzel** [comment]
Thanks for reporting.  We rolled back to the previous version so `npm install sfdx-cli` should work now.  Apologies!

**Comment by fushen16** [comment]
Thanks for getting it rolled back in time for our critical deployment activity. I was about to alter our pipeline to use the prior version of sfdx-cli.  -Fulin
