### ISSUE TITLE
cmdt topic not working in Autocomplete (48.18.1)

### ISSUE THREAD

**Issue by idanblich** [forcedotcom/cli#437]
### Summary

Post update CLI into 48.18.1 , autocomplete is not working with the new topic ```cmdt```

### Steps To Reproduce:

1.  Update CLI ``` sfdx update```
2. Verify CLI is on  48.18.1 (core) ```sfdx plugins --core```
3. install autocomplete if not already install ```sfdx plugins:install @oclif/plugin-autocomplete```
4. Run ```sfdx autocomplete```
5. RUN ```printf "$(sfdx autocomplete:script zsh)" >> ~/.zshrc; source ~/.zshrc```
6. RUN ```compaudit -D```
7. Verify autocomplete is working with any sfdx command 
8. In Terminal try to autocomplete ```sfdx force:cm``` (with tab press)  

### Expected result

Autocomplete to work with the new topic ```cmdt```

### Actual result

Autocomplete is not work with the new topic ```cmdt```

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.62.1-309fe6da17 darwin-x64 node-v10.20.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.1.1
├─ @oclif/plugin-update 1.3.9
└─ @oclif/plugin-help 2.2.1

@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.9.1 (core)
apexlink 0.9.1
generator 1.1.2 (core)
salesforce-alm 48.6.1-14 (mpd)
salesforcedx 48.18.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.18.0 (core)
└─ custom-metadata 1.0.0 (core)

sfdx-cli 7.62.1 (core)
sfdx-falcon 0.0.93
sfdx-git-packager 0.2.1
sfdx-jayree 1.10.1

**OS and version**:
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101

**Comment by shetzel** [comment]
@idanblich - please run `sfdx autocomplete --refresh-cache`.  That should fix it.

**Comment by idanblich** [comment]
@shetzel Working 👍
1. Run   ``` sfdx autocomplete --refresh-cache```
2.  Close Terminal 
3. Open Terminal
