### ISSUE TITLE
Unable to update Salesforce CLI, SHA1 Mismatch

### ISSUE THREAD

**Issue by pranayjswl007** [forcedotcom/cli#438]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:
sfdx update

```
sfdx-cli: Updating CLI from 7.61.0-af69066d0d to 7.62.1-309fe6da17... !
(node:3964) [EPERM] Error: EPERM: operation not permitted, lstat 'C:\Users\pranay.jaiswal\AppData\Local\sfdx\client\7.62.1-309fe6da17.partial.57922\sfdx-cli
-v7.62.1-309fe6da17-windows-x64\node_modules\prettier\parser-glimmer.js'
Error: SHA mismatch: expected d3d52ffb826c808f103015975239c9327073127bfae3fb822aec86cc2190adb3 to be c6919430fd21ddebcdb1b371774eddbf9b956eaee3d725717c641b8
065469413
    at IncomingMessage.stream.on (C:/Users/pranay.jaiswal/AppData/Local/sfdx/node_modules/@oclif/plugin-update/lib/tar.js:32:32)
```
**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:

**Comment by shetzel** [comment]
@pranayjswl007 Does this still happen for you?
