### ISSUE TITLE
Unable to create package version with custom object and master-detail field on Account on Pardot-enabled Dev Hub

### ISSUE THREAD

**Issue by shillem** [forcedotcom/cli#439]
### Summary

`sfdx force:package:version:create` fails when run against a Pardot-enabled Dev Hub Org if the code contains a custom object with a master-detail field on the standard object Account.

### Steps To Reproduce:

Use a Pardot-enabled Dev Hub org (*B2BMA Integration User* should be present among the profiles!).

1. Create a custom object with a *master-detail* field that points to the Account object.
1. Create the package (`sfdx force:package:create`)
1. Create the package version (`sfdx force:package:version:create`)

### Expected result

The package should be created.

### Actual result

The package version creation fails at *Verifying metadata* step.
The error message complains about *B2BMA Integration User*, that permissions to read all the custom objects records depends on the permission to read all the account records.

### Additional information
Package can be created if `--skipvalidation` is used or if the master-detail field is changed to simple lookup field.

**SFDX CLI Version**
sfdx-cli/7.62.1-309fe6da17

**SFDX plugin Version**
48.18.1

**OS and version**:
macOS 10.15.5

**Comment by shillem** [comment]
I just wanted to say that I solved the problem by deleting the .sfdx folder under my project. Something cached in there was causing the problem. After deleting that folder the command completed with no errors.

**Comment by shillem** [comment]
I had to prepare a new version of this Unlocked package and the problem came back but this time I'm unable to work around it.

The error that the package throws is the following:
```

Request in progress. Sleeping 30 seconds. Will wait a total of 900 more seconds before timing out. Current Status='Queued'
Request in progress. Sleeping 30 seconds. Will wait a total of 870 more seconds before timing out. Current Status='Initializing'
...
Request in progress. Sleeping 30 seconds. Will wait a total of 720 more seconds before timing out. Current Status='Verifying dependencies'
...
Request in progress. Sleeping 30 seconds. Will wait a total of 450 more seconds before timing out. Current Status='Verifying metadata'
ERROR running force:package:version:create:  B2BMA Integration User: L'autorizzazione Leggi tutte le Economic_Document__c dipende dalle autorizzazioni: Leggi tutte le Account
```

This is the sfdx-project.json part defining the package:

```
            "path": "economics-app",
            "package": "Economics",
            "versionNumber": "1.1.1.NEXT",
            "default": false,
            "definitionFile": "config/extended-schema-def.json",
            "dependencies": [
                {
                    "package": "Vosh Utils@1.0.11"
                },
                {
                    "package": "Utils",
                    "versionNumber": "1.1.0.LATEST"
                },
                {
                    "package": "Extended Schema",
                    "versionNumber": "1.1.3.LATEST"
                }
            ]
```
The `config/extended-schema-def.json` is as follows:

```
{
    "settings": {
        "quoteSettings": {
            "enableQuote": true
        }
    }
}
```
The generated folder for the package is as follows:

```
/var/folders/ld/4l0nzg3s1b5btm9b_zfhb4w80000gn/T/0Ho3X000000PBDHSA4-6469b8a45d1c8a6cd76683eab14d4bb149421a9c
├── md-files
│   ├── classes
│   │   ├── BudgetTriggerHandler.cls
│   │   ├── BudgetTriggerHandler.cls-meta.xml
│   │   ├── EconomicDocumentRollupper.cls
│   │   ├── EconomicDocumentRollupper.cls-meta.xml
│   │   ├── EconomicDocumentRollupperTest.cls
│   │   ├── EconomicDocumentRollupperTest.cls-meta.xml
│   │   ├── EconomicDocumentTriggerHandler.cls
│   │   ├── EconomicDocumentTriggerHandler.cls-meta.xml
│   │   ├── EconomicsTest.cls
│   │   └── EconomicsTest.cls-meta.xml
│   ├── flexipages
│   │   ├── Budget_Record_Page.flexipage
│   │   ├── Economic_Document_Record_Page.flexipage
│   │   └── Economic_Document_Row_Record_Page.flexipage
│   ├── layouts
│   │   ├── Budget__c-Budget\ Account\ Layout.layout
│   │   ├── Budget__c-Budget\ Zone\ Layout.layout
│   │   ├── Economic_Document_Row__c-Economic\ Document\ Row\ Layout.layout
│   │   ├── Economic_Document__c-Invoice\ Layout.layout
│   │   └── Economic_Document__c-Order\ Layout.layout
│   ├── objects
│   │   ├── Budget__c.object
│   │   ├── Economic_Document_Row__c.object
│   │   └── Economic_Document__c.object
│   ├── package.xml
│   ├── permissionsets
│   │   ├── Economics_Reader.permissionset
│   │   └── Partner_Economics_Reader.permissionset
│   ├── profiles
│   │   ├── Admin.profile
│   │   ├── B2BMA\ Integration\ User.profile
│   │   ├── CPQ\ Integration\ User.profile
│   │   ├── Chatter\ External\ User.profile
│   │   ├── Chatter\ Free\ User.profile
│   │   ├── Chatter\ Moderator\ User.profile
│   │   ├── ContractManager.profile
│   │   ├── Guest\ License\ User.profile
│   │   ├── Identity\ User.profile
│   │   ├── MarketingProfile.profile
│   │   ├── Minimum\ Access\ -\ Salesforce.profile
│   │   ├── Partner\ Community\ User.profile
│   │   ├── Partners\ Profile.profile
│   │   ├── ReadOnly.profile
│   │   ├── Sales\ User.profile
│   │   ├── SolutionManager.profile
│   │   └── Standard.profile
│   └── triggers
│       ├── BudgetTrigger.trigger
│       ├── BudgetTrigger.trigger-meta.xml
│       ├── EconomicDocumentTrigger.trigger
│       └── EconomicDocumentTrigger.trigger-meta.xml
├── package-version-info
│   ├── package.zip
│   ├── package2-descriptor.json
│   └── settings.zip
└── package-version-info.zip

9 directories, 49 files
```
The presence of a master-detail field on my custom object - `Economic_Document__c.Account__c` - pointing to the Account object clashes with the `B2BMA Integration User.profile`. `force:package:version:create` fails because that profiles doesn't have `View All` on `Account` which is strange because it has `View All` System Permission?!? I don't have control over B2BMA Integration User.profile. In my org it's completely locked and I cannot edit it or anything.

If I give a look at that autogenerated profile I see the following:

```
<?xml version="1.0" encoding="UTF-8"?><Profile xmlns="http://soap.sforce.com/2006/04/metadata">
<layoutAssignments>
     ...
</layoutAssignments>
<objectPermissions>
        <allowCreate>false</allowCreate>
        <allowDelete>false</allowDelete>
        <allowEdit>false</allowEdit>
        <allowRead>true</allowRead>
        <modifyAllRecords>false</modifyAllRecords>
        <object>Economic_Document__c</object>
        <viewAllRecords>true</viewAllRecords>
    </objectPermissions>
    ....
```
It gives the profile a `viewAllRecord=true` on that custom object, but not on `Account`. But so does the `Admin.profile`(admin has also `modifyAllRecords` enabled).

Is this a sfdx problem or a Salesforce problem?

**Comment by shetzel** [comment]
@shillem - can you please post the output of running `sfdx plugins --core`

**Comment by shillem** [comment]
> @shillem - can you please post the output of running `sfdx plugins --core`

```
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.3 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.12.0 (core)
├─ data 0.4.6 (core)
├─ apex 0.2.0 (core)
├─ custom-metadata 1.0.12 (core)
├─ org 1.6.5 (core)
├─ templates 51.3.1 (core)
├─ schema 1.0.6 (core)
├─ limits 1.2.0 (core)
├─ user 1.2.10 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.23 (core)
sfdx-cli 7.101.0 (core)
telemetry 1.2.0 (core)
```

**Comment by shetzel** [comment]
@shillem - thank you.  Suggestion from the packaging team:
I think the best way to figure this out would be to use the -r preserve flag on the package version create command, which will save the zip that gets sent to the server on the file system. If the profiles look right in that zip, then it's probably a serverside issue and requires a support case.

**Comment by shillem** [comment]
@shetzel that's what I showed in the comment before, the structure of the zip that gets created on my local machine. I also showed what the B2B Profile looks like inside, where it states that it has the permission to view all the records for the object `Economic_Document__c`. I'm confused regarding what my next step should be now. Should I open a support case?

**Comment by shetzel** [comment]
@shillem yes please open a support case since this will have to be fixed serverside.  The plugin is doing the correct thing.  Thanks for the excellent, detailed issue.  Very helpful!
