### ISSUE TITLE
Unable to create a new version of a Unlocked Package with chained dependencies 

### ISSUE THREAD

**Issue by sfvb** [forcedotcom/cli#441]
### Summary

I previously created a bug report under:
[https://github.com/forcedotcom/sfdx-core/issues/242](https://github.com/forcedotcom/sfdx-core/issues/242)
but maybe it is better placed here?

I have an unlocked package Pack1, which is the dependency of an unlocked package Pack2. Both Pack1 and Pack2 are the dependencies of a an unlocked package Pack3.
I can create new versions of Pack1 and Pack2, but if I want to create a new version of Pack3, then I get the error message:
`An error occurred while trying to install a package dependency, ID PACK2: The package you're installing depends on package 'PACK1', version '0.1'. Install package 'PACK1' in the target org before you install package 'PACK2'.`

I do not think I am able to manually install dependencies in this process and it should be done automatically.

**This worked perfectly until two week ago, where I used it last.**

### Steps To Reproduce:

I can give you my package Ids and sfdx-project.json, but otherwise I do not know to reproduce the bug without a huge amount of work.

In my org, I can run:
`sfdx force:package:version:create -p Pack3  -k kueche123 --definitionfile config/project-scratch-def.json --wait 10`

### Expected result

New package version is created.

### Actual result

An Error is thrown:

`An error occurred while trying to install a package dependency, ID PACK2: The package you're installing depends on package 'PACK1', version '0.1'. Install package 'PACK1' in the target org before you install package 'PACK2'.`

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.62.1-309fe6da17 darwin-x64 node-v10.20.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 3.0.0 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.9.1 (core)
generator 1.1.2 (core)
salesforcedx 48.18.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ custom-metadata 1.0.0 (core)
├─ salesforcedx-templates 48.18.0 (core)
└─ salesforce-alm 48.19.0 (core)

sfdx-cli 7.62.1 (core)

**OS and version**:
MacOs Mojave 10.14.6

**Comment by clairebianchi** [comment]
@sfvb Thanks for reaching out. I have notified the packaging team. They will need you to submit a customer case.
