### ISSUE TITLE
Cannot push source that relies on Contract.settings-meta.xml settings.

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#442]
### Summary

When pushing source to a scratch org, the `autoCalculateEndDate` value "false" in `Contract.settings-meta.xml` will not be used, causing the push to fail if any code or no-code automation tries to modify `Contract.endDate`.

### Steps To Reproduce:

**Repository to reproduce:** [contract-end-date-test](https://github.com/jclark-dot-org/contract-end-date-test)

1.  Clone the repo and `cd` into the project root directory
2.  `./createOrgFailPush`
3.  Note that the push command in the script failed to push with an error that Contract.EndDate is not writeable, even though `force-app/main/default/settings/Contract.settings-meta.xml` contains `<autoCalculateEndDate>false</autoCalculateEndDate>`:
    
    ```
    TYPE   PROJECT PATH                                     PROBLEM
    ─────  ───────────────────────────────────────────────  ───────────────────────────────────────────────         
    Error  force-app/main/default/classes/ContractTest.cls  Field is not writeable: Contract.EndDate (6:18)         
    ERROR running force:source:push:  Push failed.          
    ```
    
4.  `./preDeployContractSettingsAndPush`
5.  Note that the push command in this script succeeds, because `Contract.settings-meta.xml` was previously deployed via `sfdx force:source:deploy`.

### Expected result

It should be possible to push code that modifies `Contract.EndDate` in the same `force:source:push` that sets `autoCalculateEndDate` to "false" in `Contract.settings-meta.xml`.  In terms of the demo repo, the first script (`./createOrgFailPush`) should have successfully pushed the source to the scratch org.

### Actual result

The push fails unless the Contract setting `autoCalculateEndDate` is already set to false prior to the push, either by changing manually in the org or by pre-deploying the `Contract.settings-meta.xml` file.

### Additional information

**SFDX CLI Version** 

    sfdx-cli/7.60.0-e2bb2907cb darwin-x64 node-v10.15.3

**SFDX plugin Version** 
```
salesforcedx 48.16.2
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.18.0
└─ salesforce-alm 48.17.0
```
**OS and version**:
Mac OS 10.14.5

**Comment by jclark-dot-org** [comment]
Please note:  if you cloned the demo repo in the first 30 minutes this ticket was open, please pull changes - the wrong versions of the two demo scripts were originally included in the demo repo; this has been fixed.

**Comment by clairebianchi** [comment]
@jclark-dot-org thank you for reporting, we are sending this information to the metadata team

**Comment by mshanemc** [comment]
There are lots of Settings that need to deploy before other metadata can deploy.

Everything in the metadata API under Settings can be added to your scratch org definition file, so that the org is ready to deploy to after it's created.

You'd do something like

```json
...,
settings: {
  ...,
  contractSettings: {
    autoCalculateEndDate: false
  }
}
```

This is not a bug.
