### ISSUE TITLE
Ability to see sfdx force:source:deploy status only at certain interval

### ISSUE THREAD

**Issue by pramodgavade** [forcedotcom/cli#443]
**Is your feature request related to a problem? Please describe.**
Right now **sfdx force:source:deploy** status  is logged to terminal every 5 (not sure about current default value) seconds or so. If we can have an ability to log this status after x minutes, it will be very helpful. It will be similar to **pollWaitMillis** paramter of Ant metadata deployment.

**What are you trying to do**
Minimize the number of times status has been logged in ongoing deployment. For larger deployments, seeing status every 5 or so (not sure about current default value) seconds is too messier

**Describe the solution you'd like**
Additional parameter for for force:source:deploy command

**Describe alternatives you've considered**
Not aware about any alternative (I might be wrong though)

**Additional context**
n/a

**Comment by shetzel** [comment]
@pramodgavade - if you provide `-w 0` it will make the command asynchronous and you can use the `force:source:deploy:report` command.  Will that work for your usecase?
