### ISSUE TITLE
Add -w | --wait flag to sfdx force:community:create or dispatch event to a webhook

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#445]
### Summary
The command `sfdx force:community:create`  returns Success but the community is never created

The script bellow shows how I am using this command. Right now it is in a infinite loop because the response says my community will be created but It never happens. I was using it few days ago without a problem. I have waited for about 15 min already and nothing happened.

````javascript
output.communityCreation = await spawn(`sfdx force:community:create --name "${communityDetails.name}" --templatename "${communityDetails.templateName}" --urlpathprefix "${communityDetails.urlpathprefix}" --description "${communityDetails.description}" -u ${this.flags.targetusername} --json`);
this.ux.logJson(output.communityCreation);
do{
        const queryResult = await spawn(`sfdx force:data:soql:query -q "SELECT Id, Name, Status FROM Network" -u ${this.flags.targetusername} --json`);
        const stringQueryResult = JSON.stringify(queryResult);
        isCommunityCreated = stringQueryResult.includes('UnderConstruction');
}while(!isCommunityCreated)
````

This is the output that I get when running the following code.

![image](https://user-images.githubusercontent.com/55927613/84922515-e1186000-b0bd-11ea-91f8-9e5dae9f3f6d.png)

Ideas:
Could you add a -w to wait the community creation and also ensure the community creation is fine?

or

dispatch an event to a webhook to notify the community creation has finished.

**Comment by shetzel** [comment]
I'll pass this info to the owning team.

**Comment by AllanOricil** [comment]
> I'll pass this info to the owning team.

Thanks @shetzel 
This will help a lot.

**Comment by gavignon** [comment]
I have the same issue, do you have any news on this ?
