### ISSUE TITLE
ERROR running force:source:retrieve:  A default package path string is required for SourceWorkspaceAdapter.

### ISSUE THREAD

**Issue by AlejandroGil29** [forcedotcom/cli#446]
### Summary

Error message appears when I hit 'SFDX: Retrieve source in manifest from org', and besides of that when I open VS code 'Indexing lightning components' stays loading all the time

### Steps To Reproduce:

Please go to this page to reproduce steps to do a 'Retrieve source in manifest from org':
https://techevangel.com/2018/07/26/deploy-retrieve-metadata-using-salesforce-dx-and-vs-code/

### Expected result

Apex classes and all of the components specified in package.xml must be retrieved.

### Actual result

ERROR running force:source:retrieve:  A default package path string is required for SourceWorkspaceAdapter.
12:56:33.864 sfdx force:source:retrieve --manifest 
 ended with exit code 1

### Additional information

Issue happening in W10 with VS Code version: 1.46.0

**Comment by clairebianchi** [comment]
@AlejandroGil29 can you provide the version of your CLI and CLI plugins?
