### ISSUE TITLE
Add --codecoverage option to force:source:deploy command

### ISSUE THREAD

**Issue by arafesthain** [forcedotcom/cli#447]
**What are you trying to do**
In our Continous Integration pipeline it will be great to get **code coverage** during our **validate only** deployment in order to make it fails under a given code coverage treshold.

**Describe the solution you'd like**
Add --codecoverage option to force:source:deploy command

**Describe alternatives you've considered**
Run apex:test:run in a separate command, but as I'm doing a package validation that's not an option.

**Comment by mshanemc** [comment]
this was delivered last June.
https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71530-june-2-2022
