### ISSUE TITLE
force:source:convert ignores directories in forceignore but not files

### ISSUE THREAD

**Issue by ryanrmcintyre** [forcedotcom/cli#448]
### Summary

When running sfdx force:source:convert, the conversion seems to ignore directories specified in the .forceignore file, but not files. Is this intended behavior?

### Steps To Reproduce:

1.  Create some test visual force pages within the project src directory (src/TEST for example)
```
src/TEST
  ├── test1
  │   └── pages
  │       ├── test1.page
  │       ├── test1.page-meta.xml
  │       ├── test2.page
  │       └── test2.page-meta.xml
  └── test3
      └── pages
          ├── test3.page
          └── test3.page-meta.xml
```
1.  create a directory (named destination_folder for this example)
1. add `**/test3/**`, `**test2.page`, `**test2.page-meta.xml` to forceignore file
1. run `sfdx force:source:convert -r src/TEST -d destination_folder`

### Expected result

When opening up the `destination_folder` after conversion, I would expect all intended .forceignore files to be ignored.
```
destination_folder
└── test1
      └── pages
          ├── test1.page
          └── test1.page-meta.xml
```

### Actual result

The intended directories specified in forceignore are ignored, but not the specified files.
```
destination_folder
└── test1
      └── pages
          ├── test1.page
          ├── test1.page-meta.xml
          ├── test2.page
          └── test2.page-meta.xml
```

### Additional information

**SFDX CLI Version**:
sfdx-cli/7.53.0 darwin-x64 node-v10.20.1

**SFDX plugin Version**
7.53.0

**OS and version**:
macOS Catalina 10.15.5

**Comment by clairebianchi** [comment]
@ryanrmcintyre are you still seeing this issue?
