### ISSUE TITLE
The source:retrieve command does not behave the same for the all parameters

### ISSUE THREAD

**Issue by justgrumpy** [forcedotcom/cli#45]
### Summary

The `source:retrieve` command does not behave the same for the [-x MANIFEST], [-m METADATA], and [-p SOURCEPATH] parameters.

### Steps To Reproduce:

1. Start with a `sfdx-project.json` file like the following:
    ```
    {
      "packageDirectories": [
        {
          "path": "force-app",
          "default": true
        },
        {
          "path": "myApp",
          "default": false
        }
      ],
      "namespace": "",
      "sfdcLoginUrl": "https://test.salesforce.com",
      "sourceApiVersion": "45.0"
    }
    ```
1. Have a class in `/myApp/main/default/classes/` called `MyApexClass.cls`
1. Have a class on your sandbox named `MyApexClass` with changes
1. Use the command `sfdx force:source:retrieve -p ./myApp/main/default/classes/MyApexClass.cls`

### Expected result

I expect the class in `/myApp/main/default/classes/`, `MyApexClass.cls`, and its metadata file, `MyApexClass.cls-meta.xml`, to be updated

### Actual result

- Nothing is changed in in `/myApp/main/default/classes/`
- `MyApexClass.cls` and `MyApexClass.cls-meta.xml` are placed in `/force-app/main/default/classes/`
- I now have two copies of each file

### Additional information

I get what I expect when I use the command like either of the following:

- `sfdx force:source:retrieve -x manifest/package.xml`
  - this assumes an appropriate `ApexClass` entry in `package.xml`
- `sfdx force:source:retrieve -m ApexClass:MyApexClass`

`MyApexClass.cls` and `MyApexClass.cls-meta.xml` are updated in `/myApp/main/default/classes/` 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/6.55.1 (windows-x64) node-v10.15.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@salesforce/plugin-generator 1.0.1 (core)
@salesforce/sfdx-trust 2.1.0 (core)
builtins 1.0.0 (core)
salesforcedx 45.4.1 (core)

**OS and version**:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134

**Comment by shetzel** [comment]
@justgrumpy - Thank you for reporting.  I suspect this is due to an optimization done when using the `-p` param where project file traversal is skipped to make single file retrieval faster particularly in very large projects.   We'll prioritize this for a future patch release.

**Comment by douglascayers** [comment]
@shetzel For additional reference, I opened this [org62 chatter post](https://org62.lightning.force.com/lightning/r/0D50M00004LQtmFSAT/view) with @clairebianchi just before TDX19.

**Comment by mshanemc** [comment]
closed long ago, sorry we didn't update.  CF W-5912701
