### ISSUE TITLE
sfdx force:cmdt:record:insert throws Error: Cannot find module 'csvtojson'

### ISSUE THREAD

**Issue by SalesforceRocks** [forcedotcom/cli#450]
### Summary
executing the command sfdx force:cmdt:record:insert throws Error: Cannot find module 'csvtojson'

### Steps To Reproduce:
1. Install sfdx version sfdx-cli/7.63.0-c897e8bb1a darwin-x64 node-v10.20.1 (version 763.0) and sfdx core plugins 48.19.0 (core) on MacOS (only tested on MacOS). 
2. Open a terminal
3. Type sfdx force:cmdt:record:insert or sfdx force:cmdt:record:insert -h

Result: 
Error: Cannot find module 'csvtojson'
    at Function._load (~/.local/share/sfdx/client/7.63.0-c897e8bb1a/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:102:42)
    at require (~/.local/share/sfdx/client/7.63.0-c897e8bb1a/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (~/.local/share/sfdx/client/7.63.0-c897e8bb1a/node_modules/@salesforce/plugin-custom-metadata/lib/commands/force/cmdt/record/insert.js:10:13)
    at Module._compile (~/.local/share/sfdx/client/7.63.0-c897e8bb1a/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

### Expected result
The help of the force:cmdt:record:insert command

### Actual result

Error message (see above)

### Additional information

![2020-06-21_08-42-25](https://user-images.githubusercontent.com/7772898/85329389-b883d200-b4d2-11ea-88c1-aadc03602820.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.63.0-c897e8bb1a darwin-x64 node-v10.20.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
salesforcedx 48.19.0 (core)

**OS and version**:
macOS Catalina 10.15.4

**Comment by SalesforceRocks** [comment]
At the request of Vivek Chawla I admention you both @clairebianchi @amphro. This blocks us using the CLI from uploading custom metadata records. Workaround is to manually insert them or upload them through the custom metadata loader both of which are very error prone and cannot be automated.

**Comment by amphro** [comment]
The team is aware and working on it.

**Comment by SalesforceRocks** [comment]
Thanks @amphro

**Comment by mshanemc** [comment]
that module is now a regular dependency.
