### ISSUE TITLE
.forceignore changes not being picked up

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/cli#451]
### Summary

I am deploying a community to a scratch org, which requires me to deploy the branding assets separately. I'm trying to carry this out by using two different .forceignore files - the first one excludes the contentasset and navigation items and the second one includes them. When I copy the .forceignore file in which should exclude nothing, 90% of the time the next source push doesn't pick up any changes. I've checked the sourcePathInfos.json file and this doesn't have details of the files that should now be deployed.

Is there any way that I can kick the CLI to spot the changes?

### Steps To Reproduce:

**Repository to reproduce:** [forceignore-problem](https://github.com/keirbowden/forceignore-problem)

1. Full details are in the README 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.62.1-309fe6da17 darwin-x64 node-v10.20.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
salesforcedx 48.18.1 (core)
├─ custom-metadata 1.0.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.18.0 (core)
└─ salesforce-alm 48.19.0 (core)

**OS and version**: MacOS 10.15.5

**Comment by keirbowden** [comment]
The workaround I currently have is to delete the sourcePathInfos.json file for the scratch org in question, then run the source push again. This does another full deployment, but as I only have 600 odd components for this project it's bearable.

**Comment by mshanemc** [comment]
@keirbowden we're redoing and open-sourcing the source-tracking code this fall.  I've got this use case as an integration test.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9883375](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000062PFEYA2/view)

**Comment by mshanemc** [comment]
@keirbowden you can try this out on the new beta versions out in RC today.  https://github.com/forcedotcom/cli/issues/1258

**Comment by keirbowden** [comment]
@mshanemc tested with plugin-source 1.3.1 and it works fine!

**Comment by mshanemc** [comment]
closed with new commands GA
