### ISSUE TITLE
CLI is unable to create an enterprise edition - LiveAgent  Not available for deploy for this organization

### ISSUE THREAD

**Issue by alpertovi** [forcedotcom/cli#453]
Trying the create an enterprise org with this definition file:

`{
    "orgName": "Zipari",
    "edition": "Enterprise",
    "features": ["PardotScFeaturesCampaignInfluence"],
    "hasSampleData": false,
    "settings": {
        "caseSettings": {
            "systemUserEmail": "email@domain.com"
        },
        "lightningExperienceSettings": {
            "enableS1DesktopEnabled": true
        },
        "opportunitySettings": {
            "enableOpportunityTeam" : true
        }, 
        "securitySettings": {
            "sessionSettings":{
               "sessionTimeout": "TwelveHours"
            }
        }
    },
    "description": "Enterprise Edition with test data"
}`

Getting this error message:

`TYPE   FILE                               NAME       PROBLEM
─────  ─────────────────────────────────  ─────────  ──────────────────────────────────────────────
Error  shape/settings/LiveAgent.settings  LiveAgent  Not available for deploy for this organization`

**Comment by micha79x** [comment]
Same issue here. I was able to work around that by modifying `project-scratch-def.json` like that:

```
{
  [..]
  "edition": "Enterprise",
  [..]
  "features": [..., "LiveAgent"],
  "settings": {
    "liveAgentSettings": {
      "enableLiveAgent": false
    },
    [..]
}
```

So basically adding feature "LiveAgent" but disabling it at the same time. Quite probably the activation of the feature introduces some additional Standard Objects and other Metadata, so it definitely is not the same as before.

**Comment by yippie** [comment]
This just started happening for me today and I can't create a scratch org. My colleagues have no issues.

This persists across salesforcedx plugins v 48.19.0, 48.22.11, and 49.2.3 all with cli sfdx-cli/7.66.2-4f159a1d07 darwin-x64 node-v12.13.0

**Comment by preddivari** [comment]
@alpertovi Can you please let us know if you are still experiencing this issue? 
We have released a new CLI executable sf (v2) and would like for you to uninstall sfdx and install sf(v2) if you have not done that already. It is not going to break your scripts as sf (v2) is compatible with sfdx in terms of functionality and all of the sfdx commands can still be run via sf(v2)
