### ISSUE TITLE
CLI Timing out and failing despite Sandbox being completed

### ISSUE THREAD

**Issue by MGarfOppLoans** [forcedotcom/cli#455]
### Summary

CLI Timing out and failing despite Sandbox being completed

### Steps To Reproduce:

Create a sandbox using the org create command

### Expected result

Sandbox is authenticated against the CLI

### Actual result

Errors out after sitting in completed for hours

![image](https://user-images.githubusercontent.com/37187888/85786888-4f79a580-b6f0-11ea-94b5-404da375bd1f.png)

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
Latest

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
Latest

**OS and version**
Linux

**Comment by mshanemc** [comment]
The error is unfortunate, but it does work (run `org:status` with `-s` and `-a` to finish getting it hooked up)

**Comment by MGarfOppLoans** [comment]
agreed and we added that retry but its still problematic cause the CI/CD just sits and waits for hours since it thinks it will never finish. A bug that needs to be fixed

**Comment by rrmehta2** [comment]
@MGarfOppLoans My team is investigating ways in which we can fix the issue. Can you please try the workaround mentioned by @mshanemc and tell us if it authorizes the sandbox to the CLI? Thank you.

**Comment by MGarfOppLoans** [comment]
We added the retry and sometimes it doesn't work. It seems to be way more stable this past month or so

**Comment by mshanemc** [comment]
closing this now that `org create sandbox` and `org resume sandbox` are available.
