### ISSUE TITLE
sfdx force:org:display does not work even when defaultusername is set Globally

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#456]
### Summary

I created an empty project with a sfdx-project.json. After that I tried to run  `sfdx force:org:display` and I got the following error.

![image](https://user-images.githubusercontent.com/55927613/85814400-3ac2ff00-b73c-11ea-8dc9-639214af3b47.png)

My sfdx is configured with a Global defaultusername
![image](https://user-images.githubusercontent.com/55927613/85814455-5cbc8180-b73c-11ea-8d71-14b7be2fdae7.png)

I discovered that this happens because when `sfdx-project.json' is empty. 

Why is sfdx using anything from this file if I have already configured the same properties using the global context? 

I think this command should work idependently of the content of `sfdx-project.json' when using the global context.

### Steps To Reproduce:

1. Create an empty folder
2. Run `cd MY_FOLDER`
3. Create an empty file called `sfdx-project.json'
4. Set default username Globally
5. Run `sfdx force:org:display` from inside this folder

### Expected result

Should display the org details

### Actual result

Sfdx throws an error because it is trying to read an empty `sfdx-project.json' even when the defaultusername is set Globally.

### Additional information

![image](https://user-images.githubusercontent.com/55927613/85814725-01d75a00-b73d-11ea-9c2f-4dfb0ccc71df.png)

**Comment by AllanOricil** [comment]
I think this could be a feature and not a bug.

**Comment by mshanemc** [comment]
@AllanOricil can you also give this a spin on the new plugin?  If not, I want to get it fixed.
https://github.com/forcedotcom/cli/issues/835

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10064121](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000ID7cdYAD/view)

**Comment by AllanOricil** [comment]
Sorry, I will test it

**Comment by mshanemc** [comment]
this works now.
