### ISSUE TITLE
sfdx force : package:list --json should not depend on the sfdx-project.json

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#459]
### Summary

Im running `sfdx force:package:list --json`and it returns the following error message. 
![image](https://user-images.githubusercontent.com/55927613/86361945-76922300-bc6c-11ea-96b8-cd95b40d5031.png)

### Steps To Reproduce:

1 - Create a sfdx project
2 - Open sfdx-project.json and break the json structure. You can do it by adding a ',' somewhere in the file
3 - Execute `sfdx force:package:list --json` and you will get the error.

### Expected result

`sfdx force:package:list --json` should display all packages of our devhub when the DevHub is set to Global or Local, disregarding the content of the sfdx-project.json file.

### Actual result

`sfdx force:package:list --json` returns an error because it reads a broken sfdx-project.json
![image](https://user-images.githubusercontent.com/55927613/86361945-76922300-bc6c-11ea-96b8-cd95b40d5031.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

![image](https://user-images.githubusercontent.com/55927613/86362146-beb14580-bc6c-11ea-9fa2-002efaf78aa5.png)

**OS and version**: WIndows 10

**Comment by shetzel** [comment]
Per the owning team, this is working as designed: the command needs the sfdcLoginUrl from sfdx-project.json, so the file must be parsed, and must be valid JSON.

**Comment by AllanOricil** [comment]
> Per the owning team, this is working as designed: the command needs the sfdcLoginUrl from sfdx-project.json, so the file must be parsed, and must be valid JSON.

@shetzel  
But if I set a defaultusername as Global, why this command still needs a sfdx-project.json?
Why they can't get the username from the Global config?

**Comment by shetzel** [comment]
I'm not on the packaging team so I don't know the details about why that
command needs the login url.  However, I can tell you that a command can
define whether it needs to be run from within a SFDX project and that
command is one of them.  If you'd like, I can reopen the github issue and
ask one of the packaging team members to comment with more details.

**Comment by AllanOricil** [comment]
Yes, I would like to open this again. Could you put me in contact with someone of the team?

**Comment by shetzel** [comment]
The `package:list` command actually declares that it doesn't require a project so this appears to be a bug.  Re-opening.

**Comment by AllanOricil** [comment]
> The `package:list` command actually declares that it doesn't require a project so this appears to be a bug. Re-opening.

@shetzel thanks shetzel
