### ISSUE TITLE
Converted source not pushing to scratch orgs

### ISSUE THREAD

**Issue by chandra2ravi** [forcedotcom/cli#46]
i used source convert an try to push to scratch org and getting below error

sfdx force:source:convert -d force-app/main/default  -r force-app/objects 

deleted source -> objects folder and push 
![Screen Shot 2019-03-10 at 9 58 12 AM](https://user-images.githubusercontent.com/93057/54086967-86218600-431c-11e9-89e7-003a8d465e52.png)

**Comment by clairebianchi** [comment]
Hi @chandra2ravi, would you please post your question to the Trailblazer Community: https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1
