### ISSUE TITLE
force:source:deploy ENFILE: file table overflow error

### ISSUE THREAD

**Issue by lukecotter** [forcedotcom/cli#460]
### ENFILE: file table overflow error

Running `sfdx force:source:deploy -p somedir -u someuser` to deploy translations to a scratch org results in the error `ENFILE: file table overflow`.
A file name ending `fieldTranslation-meta.xml` follows the error.

### Steps To Reproduce:

I am not 100% sure what is causing the failure but the folder being deployed has  ~10,500 files, mostly object + field translations.

### Expected result

The deploy should succeed.

### Actual result

The command immediately errors with `ENFILE: file table overflow`

### Additional information
**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

![image](https://user-images.githubusercontent.com/4013877/86374882-f58f5780-bc7c-11ea-93a6-8b8c507f0a13.png)

**OS and version**:
Mac OS 10.15.5

**Comment by clairebianchi** [comment]
@lukecotter would you be able to provide us with a repo where we can replicate this issue?

**Comment by TedHusted** [comment]
@clairebianchi I can confirm the same issue on both Windows and Mac with a large package.

Unfortunately, the packaging code is closed source, and I'd have to check to see what we could do for access.

**Comment by TedHusted** [comment]
For Mac, we see 
ERROR running force:source:convert:  ENFILE: file table overflow, open '/var/folders/x1/p_jj9w0x6nn3xp2tbwy_k92nm6s_65/T/sdx_decomposition_1609793188657/objectTranslations/BundleComponentSetting__c-en_US.objectTranslation-meta.xml'

For Windows, it's slightly different -- EMFILE: too many open files

**Comment by lukecotter** [comment]
I think I solved this on mac by adding `ulimit -n 65536 65536` to my `.zshrc`.

But it was a little time ago so I can't 100% remember.

**Comment by TedHusted** [comment]
@lukecotter - I tried changing the ulimit on my mac, and it didn't help. I also found that with that setting in place, I wasn't able to checkout my repository, as the index pack failed on signal 250. 

@clairebianchi - We also found that it works on Windows WSL (but not native Windows). 

Our repo is proprietary and it would be difficult to offer access. 

Are you aware of any large open Salesforce repos where we could try it on Windows and Mac. 

In production, we usually do this work on a AWS Linux build agent, which works, but it comes up during local testing.

**Comment by mshanemc** [comment]
the new source:deploy doesn't use the temporary files anymore, so I don't think this is still an issue.

Please open a new issue (use the template so we can see your plugin versions) with any additional information it takes to reproduce).
