### ISSUE TITLE
Assign multiple permission sets with force:user:permset:assign

### ISSUE THREAD

**Issue by lukecotter** [forcedotcom/cli#463]
**Is your feature request related to a problem? Please describe.**
Whenever we are assigning permission sets we typically want to do more than one.
Can we extend the `-n | --permsetname` parameter to handle a list of perm set names?

**What are you trying to do**
Assign multiple perm sets with a single command.

**Describe the solution you'd like**
`sfdx force:user:permset:assign -u myorg -n "permset1, permset2"`

**Describe alternatives you've considered**
Calling multiple times but this introduces a small delay between calls and is just not as nice or convenient as the proposal.

**Comment by AllanOricil** [comment]
@lukecotter You could create a sfdx plugin to do it using the standard command.
I created one that installs multiple packages.

````
sfdx hpe:package:install -p 04t1V000000olrcQAA,04t1V000000TYMqQAO,04t1V000000XUr1QAG,04t1P00000027PlQAI,04t1V000000XUVUQA4,04t1V000000XUeWQAW,04t1V000000olt4QAA -u ${this.flags.targetusername} --json

````
If you don't want to make it a plugin, you can just write a node script that will call the sfdx command for you multiple times given a list of permission sets. If you need help send me an e-mail and we can talk. My contact allanoricilcos@outlook.com.

**Comment by lukecotter** [comment]
closed because this has been merged and is available to use 👍🏻
