### ISSUE TITLE
sfdx force:source:push work on Sandbox 

### ISSUE THREAD

**Issue by mohametso** [forcedotcom/cli#466]
Since the last update source:push work on sandbox as deploy. 
This is an issue because this command should work only on scratch org

**Comment by amphro** [comment]
The `source:push` command will work on any source tracked org. I'm guessing you are working on a developer sandbox? See here: https://releasenotes.docs.salesforce.com/en-us/summer20/release-notes/rn_sandboxes_source_tracking.htm . Feel free to open with more info if that isn't the case.
