### ISSUE TITLE
Push Failing After Upgrade

### ISSUE THREAD

**Issue by CXCAlfo** [forcedotcom/cli#469]
### Summary

This morning I created a new Scratch and issued a sfdx force:source:push command to populate with my metadata, it all worked.

This afternoon after VS Updated and I ran SFDX Update it throws errors for the same push into a fresh Scratch.

As it says on my screen - It looks like this is your first time opening an issue in this project and i am getting started.

### Steps To Reproduce:
Create a New Scratch org
issues SFDX force:source:push command

### Expected result

This morning it would work through the push and push 1035 pieces of metadata in a single pass.

### Actual result

It seems to pick the first package directory in sfdx-project.json and try to push that first - 1 component
It then picks the second package directory in sfdx-project.json and try to that - 835 components.

It fails with message Check the order of your dependencies and ensure all metadata is included even though NOTHING has changed except the upgrade.

It appears to be segmenting the push rather than consolidating before push and failing because dependencies are not in order.

### Additional information

_Feel free to attach a screenshot_.

sfdx-cli/7.65.2-0f0403b8cc win32-x64 node-v10.21.0

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.1
├─ salesforcedx-templates 48.18.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ custom-metadata 1.0.5
└─ salesforce-alm 48.23.0
sfdx-cli 7.65.2 (core)

Windows 10

**Comment by CXCAlfo** [comment]
https://github.com/forcedotcom/cli/issues/379

**Comment by ilanbalink** [comment]
Same Issue here.

**Comment by sjurgis** [comment]
Same here. I've moved all of the cross-dependent items into my main folder, ~~yet still at least one lib that has no other cross deps failed to deploy in right order.~~

The use of packageDirectories was really convenient, especially when uploading into packaging org.
Is there better workaround other than moving folders around via bash for uploading into packaging?

Edit: reading into it a bit more, seems like at least some cross-deps can be solved by **structuring packeDirectories in specific order.**

Still would've been nice to see some warning by CLI before this was released or some better error handling. Spent way too much time to trace the issue. Release notes should summarise the changes, not point to some long long discussions.

Edit 2: There's now a warning after latest release:

> Try this:
> Check the order of your dependencies and ensure all metadata is included.ly

Edit 3: There's one minor issue when the first dep got pushed successfully, but second one failed. When pushing second time first dep is in conflict.

**Comment by clairebianchi** [comment]
@CXCAlfo sounds like you will need to change the order of your packages in your project.json file. We now explicitly support multiple packages defined in the same SFDX project but this requires you to order your package directories in the project.json, please see our documentation https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_mpd.htm?search_text=multiple. Thank you for reaching out.
