### ISSUE TITLE
Problem in dashboard retrieve

### ISSUE THREAD

**Issue by vijaykumar8448** [forcedotcom/cli#47]
Not able to retrieve dashboard by sfdx command . I tried with below commands 

 **sfdx force:source:retrieve -x package.xml**  or sfdx force:source:retrieve -m Dashboard:Dashboard_Folder/Dahboard_Name

--------------- 
Version: 1.31.1 (user setup)
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
---------------------------
result is showing like 
=== Retrieved Source
No results found

**Comment by clairebianchi** [comment]
Thank you for reporting this issue. We have added it to our backlog and will update this ticket once it has been fixed.

**Comment by q-jack** [comment]
any news here? I have the same problem

**Comment by nramyasri-sf** [comment]
This has been fixed. Let me know in case you are still facing any issues.
