### ISSUE TITLE
sfdx force:mdapi:convert not converting subtypes of CustomObject

### ISSUE THREAD

**Issue by gdman** [forcedotcom/cli#471]
### Summary

In version 7.65.2/48.22.1 published yesterday, `sfdx force:mdapi:convert` has stopped converting the subtypes of CustomObject (CustomField, ValidationRule, ListView, etc). When converting a CustomObject from MDAPI to Source format the command only outputs the `-object-meta.xml` files not the subfolders (files, validationRules, listViews, etc).

### Steps To Reproduce:

1. Create a src directory with some MDAPI format objects
2. Run `sfdx force:mdapi:convert --rootdir=mdObjects --outputdir=sfdxObjects` to convert those objects into SFDX format

### Expected result

Should be converted with subtypes:
objects/[ObjectName]/fields/[FieldName]-field-meta.xml
objects/[ObjectName]/validationRules/[RuleName]-validationRule-meta.xml
etc.
objects/[ObjectName]/[ObjectName]-object-meta.xml

### Actual result

Only object is converted:
objects/[ObjectName]/[ObjectName]-object-meta.xml

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.65.2

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): 48.22.1

**OS and version**: Reproduced on MacOS and Linux (assumed not OS specific)

Before (working):
![image](https://user-images.githubusercontent.com/678641/87165277-d4a0b500-c2c1-11ea-8da9-34e1aefc1dd8.png)

After (not working):
![image](https://user-images.githubusercontent.com/678641/87165299-dcf8f000-c2c1-11ea-8e96-2ef9d4e8d1d0.png)

**Comment by bobalicious** [comment]
At the risk of being '+1', I have also encountered this issue and had to downgrade to work around.  This issue will block me from taking future upgrades of SFDX.

**Comment by coolbulevar** [comment]
Same for me.

**SFDX CLI Version** (to find the version of the CLI engine run sfdx --version): sfdx-cli/7.65.3-74dd02e949 darwin-x64 node-v10.21.0

**SFDX plugin Version** (to find the version of the CLI plugin run sfdx plugins --core): 48.22.4

**OS and version**: Reproduced on MacOS and Linux

**Comment by nramyasri-sf** [comment]
@coolbulevar, @bobalicious or @gdman , Here is what I tried : 

Execute the following commands in the dreamhouse-sfdx repo : 

1. `sfdx force:source:convert -r force-app/
Source was successfully converted to Metadata API format and written to the location: dreamhouse-sfdx/metadataPackage_1594663415398`

2. Execute : `sfdx force:mdapi:convert -r metadataPackage_1594663415398/ --outputdir=SOURCE`

Here is what I see : 

![image](https://user-images.githubusercontent.com/45364408/87338175-f4262080-c501-11ea-9e75-a431cbb465f3.png)

Here is how my output looks : 

![image](https://user-images.githubusercontent.com/45364408/87338284-2768af80-c502-11ea-9ac3-67244e056963.png)

CLI  version : sfdx-cli/7.65.3 darwin-x64 node-v10.16.3
SFDX Plugin version : 48.22.4

Let me know if there is anything I missed out here that could help reproduce this issue.Thank you.

**Comment by gdman** [comment]
@nramyasri-sf, It's taken the best part of an hour to work out but I've found it...

If the output directory (`--outputdir`) is the same as the package directory it only converts the objects:

![Screenshot 2020-07-13 at 19 57 46](https://user-images.githubusercontent.com/678641/87342422-22782000-c543-11ea-89b1-f8e1a9156833.png)

**Comment by nramyasri-sf** [comment]
Thanks @gdman , that was helpful!
