### ISSUE TITLE
sfdx force:source:status -r ignores deployed metadata

### ISSUE THREAD

**Issue by Kevmo92** [forcedotcom/cli#473]
### Summary

Using `sfdx force:source:deploy -m GlobalValueSet,StaticResource,StandardValueSet` I can deploy the metadata types to my scratch org successfully. When I run `sfdx force:source:status -r` I receive `No results found`. 

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)
1.  create your scratch org in the dreamhouse-lwc project `sfdx force:org:create -f config/project-scratch-def.json -s`
1.  deploy the static resources `sfdx force:source:deploy -m StaticResource`
1.  run `sfdx force:source:status -r`

### Expected result

I should see that the static resources have been added to the org successfully when running sfdx force:source:status -r

### Actual result

```
=== Source Status
No results found
```

### Additional information
sfdx-cli/7.65.2 darwin-x64 node-v12.18.0

```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 47.10.1
├─ salesforcedx-templates 47.11.0
└─ salesforce-alm 47.11.0
sfdx-cli 7.65.2 (core)
```

**Comment by shetzel** [comment]
@Kevmo92 - you are on an old version of the salesforcedx CLI plugin.  (Note version salesforcedx 47.10.1 above).  I would run:
`sfdx plugins:uninstall salesforcedx` and that will get you back to the default core plugin version, which for CLI version 7.65.2 should be 48.22.1.
I could not reproduce this on the latest version of the CLI and salesforcedx plugin.  Please reopen if you can reproduce it on the latest.
