### ISSUE TITLE
force:org:list timeout

### ISSUE THREAD

**Issue by Confirm4Crit** [forcedotcom/cli#474]
### Summary

`force:org:list` seems to timeout.

### Steps To Reproduce:

1. Somehow break an auth against an org.
2. Attempt `sfdx force:org:list`  , it seems like it timesout.
Note that `sfdx force:org:list --skipconnectionstatus` works fine.
I originally thought this was repeatable with un-aliased scratch orgs, doesn't seem to be the case.

### Expected result

A response from `sfdx force:org:list`, with my unauthed org noted with red text, access_invalid, or w.e the warning used to be.

### Actual result

Nothing, seems to just hang against unauthed orgs.

### Additional information

There was one connection that didn't have valid auth, when I deleted it, sfdx force:org:list worked fine.
The debug log for the cli just seemed to be retrying that box over and over again. Repeating chunk of log with `"level":30,"msg":"Access token has expired. Updating...","time":"2020-07-12T17:39:19.285Z","v":0}` against the same org.
( I can provide trace log if needed).

What's weird is, I only knew it didn't have valid auth was due to a moment where I thought I fixed it by running clean, and `force:org:list` came back fine. I made a scratch org, and it started failing again. I remember the sandbox had a red Connected Status, `access_ something`, don't remember the precise status.

Logging out or blocking the CLI via OAuth does not seem to recreate the issue, I'm getting `RefreshTokenAuthError` off of another sandbox, everything is fine. 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.65.2 darwin-x64 node-v13.11.0
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
Is core supposed to dump all plugins?
```
@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.4.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
bbdoc 3.0.2
generator 1.1.3 (core)
salesforcedx 48.22.1 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ custom-metadata 1.0.5 (core)
└─ salesforce-alm 48.23.0 (core)
sfdmu 3.5.3
sfdx-cli 7.65.2 (core)
sfdx-collate 0.5.2
sfdx-ext 0.0.43
sfdx-flowdoc-plugin 0.5.1
sfdx-git-packager 0.3.1
sfdx-jayree 2.0.1
sfpowerkit 1.46.6
shane-sfdx-plugins 4.37.2
```
**OS and version**: MAC 10.15.2 (19C57)

**Comment by Confirm4Crit** [comment]
I haven't been able to repro this using expired scratch org.
Maybe something odd with some scratch orgs sitting on Spring and I had a summer release over the weekend?

**Comment by clairebianchi** [comment]
@Confirm4Crit this is working as expected. That is why we added --skipconnectionstatus
