### ISSUE TITLE
Object Translation failing to be deployed

### ISSUE THREAD

**Issue by ilanbalink** [forcedotcom/cli#477]
### Summary

The translations aren't generated well. Some fields are generated twice and then it isn't possible to deploy.

### Steps To Reproduce:

retrieve ObjectTranslation for specific object/s and try to deploy with sfdx force:source:deploy.
I tried to use sfdx force;source:convert and I'm seeing that fields are copied twice in the metadata of the translation of the object.

### Expected result

sfdx force:source:deploy is deploying translation and sfdx force:source:convert isn't copying twice any fields

### Actual result

sfdx force:source:deploy is failing to deploy object translation and sfdx force:source:convert is copying twice any fields

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.65.2-0f0403b8cc win32-x64 node-v10.21.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ custom-metadata 1.0.4 (core)
└─ salesforce-alm 48.23.0 (core)
sfdx-cli 7.65.2 (core)
**OS and version**:
Windows 10

**Comment by shetzel** [comment]
Bug tracked internally as W-7860597

**Comment by manuelepalmeri** [comment]
Hi, i'm facing tha same issue. Any solution/workaround?

**Comment by danmarpar** [comment]
this also is afecting us: the issue does not happen in older versions of sfdx like 6.54.4

**Comment by ybiyani** [comment]
Any updates? I too am facing this issue.  As a workaround I downloaded the files using workbench and uploaded the files using VS code. (For some reason the retrieved  zip file via workbench fails to deploy via workbench with no package.xml found error)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9299229](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MPu8YAG/view)
