### ISSUE TITLE
"force:org:list --json" doesn't accurately report dev hub status

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#482]
IC uses the `isDevHub` property of an org in the output of `force:org:list --json` to determine whether a given org is configured as a dev hub. However, I've had a number of users provide output of that command that shows the following:

```json
{
  "username": "[redacted]",
  "orgId": "[redacted]",
  "accessToken": "[redacted]",
  "instanceUrl": "https://redacted.my.salesforce.com",
  "loginUrl": "https://redacted.my.salesforce.com/",
  "clientId": "[redacted]",
  "privateKey": "[redacted]",
  "alias": "DevHub",
  "lastUsed": "2020-07-14T20:26:43.555Z",
  "isDefaultDevHubUsername": true,
  "connectedStatus": "Connected",
  "defaultMarker": "(D)"
}
```

Notice that `isDevHub` is completely missing but `isDefaultDevHubUsername=true`. I'm updating IC to infer the former from the latter when not present, but this seems like a bug to me since `isDevHub` is (to my understanding) the authoritative designator for a dev hub org.

**Comment by SCWells72** [comment]
@clairebianchi can you provide any status update on this one? As you can hopefully appreciate, not being able to determine that an org is enabled as a dev org is an impediment to tooling that integrates scratch org creation. There's no definitive way to know which orgs are factories for scratch orgs.

**Comment by clairebianchi** [comment]
Hi @SCWells72, it is on our backlog. Due to some resourcing issues we are having, I can't give you a timeline. I apologize.

**Comment by SCWells72** [comment]
@clairebianchi thanks for getting back. No problem. That tells me what I need to know. I think I'll make it possible for users to optionally choose orgs that aren't listed as dev hubs when creating a scratch org in case they're hitting this bug. Perhaps a "Show all orgs" checkbox with a disclaimer that not all listed orgs are necessarily dev hubs and the operation may fail.

Take care and thanks again for the follow-up.

**Comment by mshanemc** [comment]
This may be fixed in the new open-source version.  You can try it early, here: https://github.com/forcedotcom/cli/issues/835
