### ISSUE TITLE
Retrieval of EntitlementTemplate gives Metadata API received improper input error

### ISSUE THREAD

**Issue by kidjansen** [forcedotcom/cli#485]
### Summary

Retrieval of EntitlementTemplate gives following error:

`Metadata API received improper input. Please ensure file name and capitalization is correct. Load of metadata from db failed for metadata of type:EntitlementTemplate and file name:Support Questions.`

If you run the following SOQL query in that org the exact same name is returned though, including identical capitalization:

`SELECT Name FROM EntitlementTemplate`

It's the only EntitlementTemplate in that org, not sure if other templates would also be affected nor if the capitalization or the space in the name is the cause of the issue.

### Steps To Reproduce:

Can't share repo (customer IP), but you can contact me if needed for screen sharing session (CET/CEST time zone).

1. sfdx force:source:retrieve on a sandbox or production org (probably also scratch orgs, but not tested) that has the EntitlementTemplate in question in the retrieval scope

### Expected result

retrieval of the EntitlementTemplate in the retrieval scope (package.xml)

### Actual result

error: `Metadata API received improper input. Please ensure file name and capitalization is correct. Load of metadata from db failed for metadata of type:EntitlementTemplate and file name:Support Questions.`

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
applicable to both 7.65.3 and 7.65.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ custom-metadata 1.0.4 (core)
└─ salesforce-alm 48.24.1 (core)
sfdx-cli 7.65.4 (core)

**OS and version**:
Windows 10 Pro with all updates

**Comment by clairebianchi** [comment]
@kidjansen This issue is owned by the MDAPI team. I am passing your request on to their PM.
