### ISSUE TITLE
GACK on retrieval of Feed Item Quick Action

### ISSUE THREAD

**Issue by kidjansen** [forcedotcom/cli#486]
### Summary

GACK on retrieval of Feed Item Quick Action

### Steps To Reproduce:

Can't share repo (customer IP), but you can contact me if needed for screen sharing session (CET/CEST time zone).

1.  sfdx force:source:retrieve on the sandbox with the particular feed item quick action

### Expected result

retrieval of the quick action

### Actual result

`Unable to retrieve file for id 09D0Y000008QXw2 of type QuickAction due to an internal error:1047149141-326551 (22752404)`

### Additional information

![image](https://user-images.githubusercontent.com/62748220/87530248-60368f00-c690-11ea-890e-8df573d5da03.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
applicable to both 7.65.3 and 7.65.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ custom-metadata 1.0.4 (core)
└─ salesforce-alm 48.24.1 (core)
sfdx-cli 7.65.4 (core)

**OS and version**:
Windows 10 Pro with all updates

**Comment by mshanemc** [comment]
If it's still happening, please open a new issue with any sort of repro that you're comfortable with.
