### ISSUE TITLE
Knowledge Enabled for Enterprise Scratch Orgs

### ISSUE THREAD

**Issue by atrancandoris** [forcedotcom/cli#489]
### Summary

Knowledge is enabled by default for Enterprise scratch orgs and cannot be disabled.

### Steps To Reproduce:

{
  "orgName": "org name",
  "edition": "Enterprise",
  "features": [],
  "settings": {
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "securitySettings": {
      "passwordPolicies": {
        "enableSetPasswordInApi": true
      }
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    },
    "knowledgeSettings": {
      "enableKnowledge": false,
      "enableLightningKnowledge": false
    }
  }
}

sfdx force:org:create -f config/project-scratch-def.json --setalias sfdxknowledgeissue --durationdays 1 --setdefaultusername

### Expected result

Either 1. Knowledge is not enabled in the first place OR 2. Knowledge is disabled

### Actual result

=== Component Failures [1]
TYPE   FILE                               NAME       PROBLEM
─────  ─────────────────────────────────  ─────────  ─────────────────────────────────────────────────────
Error  shape/settings/Knowledge.settings  Knowledge  Once enabled, Salesforce Knowledge can't be disabled.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.63.0 linux-x64 node-v13.12.0

**SFDX plugin Version**
salesforcedx 48.19.0 (core)

**OS and version**:
FC32

**Comment by clairebianchi** [comment]
@atrancandoris The team that builds Scratch orgs owns this issue. I have passed on your issue to their PM.
