### ISSUE TITLE
Install CLI on Linux root owner perm issue prevents use in Visual Studio Code. 

### ISSUE THREAD

**Issue by eshafferpdx** [forcedotcom/cli#49]
### Summary

Following "Install the CLI on Linux" steps found on [Install the Salesforce CLI](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux) results in directories and files with root ownership which requires sudo to use the tool in terminal and prevents its use in Visual Studio Code application. 

### Steps To Reproduce:

1.  Download or wget tarball ... sfdx-linux-amd64.tar.xz
2. Create an sfdx directory.
    $ mkdir sfdx
3. Unpack tarball:
    $ tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
4. Run the install script. 
    $ ./sfdx/install

### Expected result

Installation of sfdx-cli directories and files with appropriate User permissions to allow both terminal and VSCode use.

### Actual result

Sudo permissions required during install resulting in:
sfdx installed to `/usr/local/bin/sfdx`
ERROR:   Error:   EACCES: permission denied, open '/home/eshaffer/.sfdx/sfdx.log'
              Error parsing plugin /usr/local/lib/sfdx/node_modules/salesforcedx
              'EACCES' : EACCES : permission denied, open '/home/eshaffer/.sfdx/sfdx-config.json' 
sfdx-cli/6.56.0-e3fd846a1f (linux-x64) node-v8.15.1

Screenshot of install terminal showing install errors and 'sfdx force:project:create -n ' errors and 'sfdx --version' and 'sfdx plugins --core' errors. 
![sfdx_cli_install_errors_Screenshot from 2019-03-14 10-08-05](https://user-images.githubusercontent.com/23482412/54391955-9fe80380-4663-11e9-8dbc-407d3e5a4f6d.png)

### Additional information
Using termininal, sudo is required for successful sfdx project:create,  --version, config files, etc. This prevents use of Salesforce CLI Integration in Visual Studo Code. Terminal screenshot and VSCode screenshots with error messages below:
![sfdx_project-create_perm-errors_Screenshot from 2019-03-14 10-21-10](https://user-images.githubusercontent.com/23482412/54392178-34526600-4664-11e9-92a1-e2edf29f5183.png)

![VSCode_proj-create-fail_perm_denied_Screenshot from 2019-03-14 11-59-11](https://user-images.githubusercontent.com/23482412/54392216-47fdcc80-4664-11e9-99d1-17bd3a812def.png)

**SFDX CLI Version**
sfdx-cli/6.56.0-e3fd846a1f (linux-x64) node-v8.15.1

**SFDX plugin Version**:
@salesforce/plugin-generator 1.0.1 (core)
@salesforce/sfdx-trust 2.1.0 (core)
builtins 1.0.0 (core)
salesforcedx 45.5.0 (core)

**OS and version**:
Ubuntu 18.04.2

**Comment by eshafferpdx** [comment]
For what it is worth, I did use chown to take ownership from root of the .sfdx dir and successfully created project with manifest using VSCode. 
     I do not know what implications this may have down the road as I am just starting to use the tool. If no known issues from User owning .sfdx directory, perhaps consider updating the Install the CLI on Linux steps to include $ sudo chown user : user .sfdx .

**Comment by eshafferpdx** [comment]
Inadvertently closed in error, reopened for review and feedback please.

**Comment by clairebianchi** [comment]
We are looking into your question @tnoonan-salesforce to respond

**Comment by tnoonan-salesforce** [comment]
I think you might have node installed globally?

I actually recommend installing node using nvm. Our docs probably should clarify that.

https://github.com/creationix/nvm/blob/master/README.md

**Comment by eshafferpdx** [comment]
Thank you, I have installed node using the referenced README.md.

**Comment by tnoonan-salesforce** [comment]
Did switching to nvm solve your problem?

**Comment by eshafferpdx** [comment]
As a new user of the tool and since I am not a developer I cannot yet say
if it has done so.

**Comment by clairebianchi** [comment]
@eshafferpdx are you still facing this issue?

**Comment by eshafferpdx** [comment]
@clairebianchi thank you for the follow up on this. I have installed in new Ubuntu 19.04 VM using the previous steps with the addition of nvm by @tnoonan-salesforce just before installation of sfdx-cli. 
1. Install VSCode .deb in terminal from Linux install section https://code.visualstudio.com/docs/setup/linux
2. Install nvm from https://github.com/creationix/nvm/blob/master/README.md 
3. Install sfdx-cli from Linux install section https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_linux
![Terminal install sfdx-cli_npm Screenshot from 2019-04-23 15-08-38](https://user-images.githubusercontent.com/23482412/56621184-65697300-65e0-11e9-8ab2-cfd6ae18ba4e.png)

While I cannot be certain of my chosen install order, the process was much cleaner than the previous install. I cannot find any changes to Linux install documentation to date.
Since I am not a developer I am unqualified to test further. Perhaps there are Linux developers who can leverage our progress continue the evaluation.

Thank you both for the assist on this. Feel free to close if you deem appropriate.

**Comment by tnoonan-salesforce** [comment]
Ok good news. Closing.

**Comment by Rokit12** [comment]
somebody with idea to solve this: (node:19029) [EACCES] Error Plugin: sfdx-cli: EACCES: permission denied, open '/home/rokit/.sfdx/sfdx-config.json'
