### ISSUE TITLE
Error while creating Scratch Org from Snapshot

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#490]
### Summary

Im using a snapshot that I created from a Scratch Org with a bunch of packages installed. The snapshot was created with success but once I ran the command to create a Scratch Org from this snapshot, the command threw an error.

![image](https://user-images.githubusercontent.com/55927613/87578956-1ae48280-c6cd-11ea-9ad6-c70b2cdd61d8.png)

**Comment by clairebianchi** [comment]
@AllanOricil This is a question for the team that owns Scratch orgs. I have passed this issue over to them their PM.
