### ISSUE TITLE
Unable to deploy report using force:source:deploy

### ISSUE THREAD

**Issue by gsbasso** [forcedotcom/cli#5]
### Summary

Attempting to deploy report using force:source:deploy -x package.xml

### Steps To Reproduce:
<ol>
<li>Create a report folder MyReportFolder</li>
<li>Create a simple report MyReport and save under MyReportFolder</li>
<li>Create a package.xml file that includes the following content:</li>
<pre>
&lt;types&gt;
    &lt;members&gt;MyReportFolder/MyReport&lt;/members&gt;
    &lt;name&gt;Report&lt;/name&gt;
&lt;/types&gt;
</pre>
<li>Run sfdx command:</li>
<pre>sfdx force:source:deploy -x package.xml</pre>
</ol>

### Expected result

Report should be created/updated in target instance

### Actual result

The following error message is returned:
<pre>The ReportFolder named MyReportFolder/MyReport was not found in the workspace.</pre>

### Additional information

Replacing the forward-slash in the report path with a backward-slash fixes the problem, as in:
<pre>
&lt;types&gt;
    &lt;members&gt;MyReportFolder\MyReport&lt;/members&gt;
    &lt;name&gt;Report&lt;/name&gt;
&lt;/types&gt;
</pre>

**SFDX CLI Version**:
(sfdx --version) sfdx-cli/6.48.0-bfccc40118 (windows-x64) node-v8.9.4
(sfdx force --version) v44.0

**OS and version**:
Windows 7 64-bit

**Comment by clairebianchi** [comment]
@gsbasso Reports are created private by default and therefore are ignored when you deploy. Make your report public and it should work

**Comment by gsbasso** [comment]
The previous comment about private vs. public doesn't make sense in light of the _workaround_ I employed as described in the original post. Specifically, all that was needed was to change the forward-slash character separating the report folder from the report name to a backward-slash. So private vs. public had nothing to do with it.

**Comment by atsutton** [comment]
Thanks @gsbasso - the change to backslash fixed it for me.

**Comment by jhegstrom** [comment]
Try retrieving the ReportFolder metadata using sfdx force:source:retrieve -u username - m ReportFolder:MyReportFolder before you deploy and include the ReportFolder type and members in the package.xml
