### ISSUE TITLE
AuthInfo Error on sfdx force:apex:test:run

### ISSUE THREAD

**Issue by alpha-bytes** [forcedotcom/cli#50]
### Summary

Suddenly, whenever I click the `run test` link in an Apex Unit Test, or run any variants of the `sfdx force:apex:test:run` command, the process exits with an error value (`1`) and prints the message `ERROR:  Cannot create an AuthInfo instance that will overwrite existing auth data.`

I removed authorization for the default org (`sfdx force:auth:logout`) and then authorized it again, and still the same error. 

I am running the current version of sfdx and all plugins: 
```
@salesforce/plugin-generator 1.0.1 (core)
@salesforce/sfdx-trust 2.1.0 (core)
builtins 1.0.0 (core)
salesforcedx 45.4.1
```

What steps can I take to remedy? Obviously I can try uninstalling / reinstalling SFDX but that seems rather brute force for something that was working only a few days ago.

**Comment by dalden-calepa-salesforcedx** [comment]
I also started receiving this error today on certain CLI commands.

**Comment by clairebianchi** [comment]
@alpha-bytes @dalden-calepa-salesforcedx, we just made an update that should fix this. Would you please update your CLI and try again?

**Comment by alpha-bytes** [comment]
This seems to have done the trick - thank you!
