### ISSUE TITLE
Include/Add ux.open to sfdx cli ux

### ISSUE THREAD

**Issue by idanblich** [forcedotcom/cli#500]
As part on my plugin i need to open a web page in a browser. 

oclif/cli-ux provide this option [open.ts](https://github.com/oclif/cli-ux/blob/2ab2aa0a08479402938251e1263ad0f67209ba4c/src/open.ts) but Salesforce cli does not. 

This FR is to Include/Add ux.open in sfdx cli ux

current workaround is :
```
const exec = require("child_process").execSync;
exec(`open ${someurl}`);

```

**Comment by mshanemc** [comment]
we use the `open` library and your plugin can do the same
https://github.com/salesforcecli/plugin-org/blob/main/package.json#L13
https://github.com/salesforcecli/plugin-org/blob/f38bcf86194574e0d90cf6953e1a2916c234ccfe/src/commands/org/open.ts#L17

oclif no longer includes that in ux
