### ISSUE TITLE
Elevated number of push conflicts

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#502]
### Summary

Starting with `48.22.2` the number of source conflicts increased something like 10-50x. Basically I never seen conflicts before as I never do anything in org itself. Now even after force overwritting source the conflicts remain.

### Steps To Reproduce:

Unsure at the moment. I use IC2 and CLI interchangeably to push. Noticed on lwc and aura so far.

**Comment by sjurgis** [comment]
I've outlined one of the fail scenario here:
https://github.com/forcedotcom/cli/issues/469#issuecomment-657969249

**Comment by shetzel** [comment]
Not sure what this issue is about.  Are you using multiple package directories and are now having dependency issues?  Is this a duplicate of #469 ?

**Comment by sjurgis** [comment]
Well I guess there's two issues. One related to dependencies (linked to). The other related to push conflicts. Unsure how to reproduce, but I'm pretty sure others going to have same issue. Let's see if the issue attracts more people I guess.

**Comment by eltoroit** [comment]
I am delivering training (DEX602, a LWC course) and many students on Windows are having conflicts when they do a simple push. But the students who work on Mac do not have this issue. They all use the same repo provided to them.

**Comment by sjurgis** [comment]
@shetzel  So there's definitely issue when one of packageDirectories fails to deploy on second deploy everything is marked as conflict.

**Comment by costonb** [comment]
We started noticing this last week too.  All our developers are on Macs, so can confirm it happens there too.  Creating a new scratch org and the initial push of the codebase goes fine, then any changes we make to lwc or aura components it complains that there is a conflict, even if we haven't touched the org yet beyond the initial code push.  Once we do a force push that component seems fine but we see the error again the next time we change a different file that has not yet been pushed beyond the initial one.

**Comment by sjurgis** [comment]
Still getting them...

**Comment by robertStrunk** [comment]
I am experiencing this issue also. Hopefully my additions to this discussion will provide some new insight. 

I am the only user modifying any metadata in the sandbox org.
I am using VSCode to do it. 
When I deploy my changes to the sandbox, I receive a conflict error. 
When I review the conflicts, there are no actual conflicts. It shows me the changes that I just made. 
I just force override the push to make sure the changes get pushed to the sandbox org. 
The timestamps even show in the conflict section of VSCode that the org metadata's last modified date is older than the last local sync (which would suggest there are no new modifications on the server to get overwritten)

![image](https://user-images.githubusercontent.com/47643610/127497886-5925a0e4-2772-4bba-b912-5e8dec5dc13e.png)

I just took a super quick peek in the https://github.com/forcedotcom/salesforcedx-vscode repo and am curious if there is a localization issue when comparing the timestamps. Based on the randomness I'm wondering if there is some rounding issue based on the number of seconds in the timestamp. Perhaps a look at the [TimeStampConflictChecker](https://github.com/forcedotcom/salesforcedx-vscode/blob/4b140e7e3a5a67ab80cc62f0e3f73496ee74d03d/packages/salesforcedx-vscode-core/src/commands/util/postconditionCheckers.ts#L214) class would be worthwhile.

**Comment by mshanemc** [comment]
the sfdx portion of this has been solved (you can run a source:deploy with `--tracksource`) OR use the newer `sf metadata deploy` with its `resume` companion command

If there's still issues for the vscode conflict detection behaviors, please open an issue on https://github.com/forcedotcom/salesforcedx-vscode
