### ISSUE TITLE
sfdx force:org:create -a SO_ALIAS -f config\snapshot.json  returns error C-1033

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#504]
### Summary

`sfdx force:org:create -a SO_ALIAS -f config\snapshot.json`  returns error C-1033

Last week it was working without any problem. The snapshot we are using is up and running with status Active.

### Steps To Reproduce:

run `sfdx force:org:create -a SO_ALIAS -f config\snapshot.json` to create a scratch from a snapshot. 

### Expected result

It should create the Scratch Org

### Actual result

Error C-1033

### Additional information

Error message
![image](https://user-images.githubusercontent.com/55927613/87955912-476e1500-caa6-11ea-9d87-b7653c8683f7.png)

Snapshots list
![image](https://user-images.githubusercontent.com/55927613/87955929-4c32c900-caa6-11ea-9ba3-18b74e2fd32e.png)

snapshot.json file
![image](https://user-images.githubusercontent.com/55927613/87955975-5bb21200-caa6-11ea-8f9d-d754ce9b5b56.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
![image](https://user-images.githubusercontent.com/55927613/87956032-6ec4e200-caa6-11ea-82e2-c0d551194f56.png)

**OS and version**: 
![image](https://user-images.githubusercontent.com/55927613/87956084-7f755800-caa6-11ea-8c92-87f092a82bfb.png)

**Comment by maaaaarco** [comment]
@AllanOricil was the snapshot created from a Scratch Org in Summer '20? On Sunday new Salesforce major release went live, you should recreate your snapshot.

**Comment by AllanOricil** [comment]
> @AllanOricil was the snapshot created from a Scratch Org in Summer '20? On Sunday new Salesforce major release went live, you should recreate your snapshot.

Thanks @maaaaarco

**Comment by shetzel** [comment]
Correct, org snapshots must be recreated after every SFDC major release.  Thanks @maaaaarco
