### ISSUE TITLE
update of sfdx-cli (npm) throws error

### ISSUE THREAD

**Issue by kvor** [forcedotcom/cli#507]
### Summary

When update sfdx-cli, the following error is thrown:

```
Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/compile.py' -> '/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/binding.gyp'
    at Object.renameSync (fs.js:661:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/scripts/install.js:14:4)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -13,
  syscall: 'rename',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/compile.py',
  dest: '/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/binding.gyp'
}
```

### Steps To Reproduce:

1.  Run  npm update --global sfdx-cli 
2.  The following error is thrown:

```
internal/fs/utils.js:230
    throw err;
    ^

Error: EACCES: permission denied, rename '/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/compile.py' -> '/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/binding.gyp'
    at Object.renameSync (fs.js:661:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/scripts/install.js:14:4)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  errno: -13,
  syscall: 'rename',
  code: 'EACCES',
  path: '/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/compile.py',
  dest: '/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/binding.gyp'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 (node_modules/sfdx-cli/node_modules/dtrace-provider):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: dtrace-provider@0.6.0 install: `node scripts/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

### Expected result

update should finish without error

### Additional information

Please note that /usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/compile.py does not exist in the filesystem.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.66.2 darwin-x64 node-v12.16.2

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.2.3 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.7 (core)
├─ salesforcedx-templates 48.32.0 (core)
└─ salesforce-alm 49.3.0 (core)
sfdx-cli 7.66.2 (core)
```

**OS and version**: Mac OS X v10.15.5

**Comment by AllanOricil** [comment]
@kvor
What happens if you run  `sfdx update` instead of using npm. Could you also try both commands again in a terminal with sudo permissions.

If nothing worked, try this suggestion and tell us the result.

https://stackoverflow.com/questions/38323880/error-eacces-permission-denied

Thanks

**Comment by kvor** [comment]
@AllanOricil npm based installations should be updated with npm.
If you try it, it will throw a warning: `Use "npm update --global sfdx-cli" to update npm-based installations.`

The suggestion you provided is related to permission problems. It is not related to this issue since 
`/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/compile.py` is missing.

**Comment by AllanOricil** [comment]
> @AllanOricil npm based installations should be updated with npm.
> If you try it, it will throw a warning: `Use "npm update --global sfdx-cli" to update npm-based installations.`
> 
> The suggestion you provided is related to permission problems. It is not related to this issue since
> `/usr/local/lib/node_modules/sfdx-cli/node_modules/dtrace-provider/compile.py` is missing.

I found other issues like yours. These have the same error message. All of these posts say that the error is caused when this dependency tries to rename something that it does not have access too.

https://github.com/hexojs/hexo/issues/2785
https://forums.developer.amazon.com/questions/102167/fail-to-install-ask-cli-on-macos-high-sierra-error.html

Try these suggestions

**Comment by kvor** [comment]
@AllanOricil  Update runs under sudo. So changing folder ownership does not help. I have also checked that both files are missing.

@clairebianchi Any plans to check this issue?

**Comment by clairebianchi** [comment]
We are unable to replicate this issue on our side.

**Comment by saurrabhA30013582** [comment]
by the way what was the final solution
