### ISSUE TITLE
Never allow repeated Version number for a Package with the same Package2Id

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#508]
**Is your feature request related to a problem? Please describe.**
I noticed we can create package versions with the same Id.

![image](https://user-images.githubusercontent.com/55927613/88185019-53cfaa80-cc2b-11ea-94d0-e0e215cd2d89.png)

**Describe the solution you'd like**
I would like the CLI to block the creation of a package with the same package version number if it already exists. NPM and Yarn both do that. And, maybe, consider that if that package version exists and the user wants to reuse it, give the option to overwrite it. In npm i can unpublish a version and then publish it again. But I can't ever use the same one.

<b>Possible Implementation:</b>
Before creating the version, retrieve all the versions of that particular package2Id for a particular DevHub, check if the version Im using is in that list. If it is, then block its usage and display a message that it is already being used. If it is not, then proceed with the creation.

**Comment by ImJohnMDaniel** [comment]
@AllanOricil -- Am I reading this correctly?  You built a new version of the package some 6 days later and it had the same version number??  I am curious how that is even possible?  

Also, the image that you posted of the JSON output -- On the second entry, what is the "IsOrgDependent" value?

When you built the two package versions, were you doing anything special?

**Comment by AllanOricil** [comment]
> @AllanOricil -- Am I reading this correctly? You built a new version of the package some 6 days later and it had the same version number?? I am curious how that is even possible?
> 
> Also, the image that you posted of the JSON output -- On the second entry, what is the "IsOrgDependent" value?
> 
> When you built the two package versions, were you doing anything special?

I don't know how it happened too. I never tried to create a package with the same version.
I was not the one who created it. I just found it today while creating an Automation with sfdx plugins. 

Let me update the image of the ouput. Both have the value "No"

![image](https://user-images.githubusercontent.com/55927613/88184796-10753c00-cc2b-11ea-875e-85f70481684f.png)

**Comment by AllanOricil** [comment]
@shetzel could you help me with this one?

**Comment by shetzel** [comment]
Per the packaging team, this is WAD and will not cause issues since you'll get a unique 04t id for each package version.  They recommend using `"versionNumber": "0.1.0.NEXT"` to avoid what you are seeing.
