### ISSUE TITLE
SFDX: Retrieve Source from Org command does not retrieve new files

### ISSUE THREAD

**Issue by vignaesh01** [forcedotcom/cli#51]
I pulled a sandbox using Salesforce CLI extensions for VS Code using sfdx : Retrieve Source in Manifest from Org command. Later when I right clicked on classes folder and selected SFDX: Retrieve Source from Org command, new classes created in sandbox recently does not get retrieved. Only the classes that are already present in the classes folder gets updated. Is this a known issue?

**Command that runs:**

sfdx force:source:retrieve --sourcepath d:\VS Code Workspaces\ENGAGE\uat\force-app\main\default\classes

**Comment by clairebianchi** [comment]
Hi, can you rerun the command and surround the source path with quotes?

**Comment by ruthemmanuelle** [comment]
Hi @vignaesh01 . The `--sourcepath` parameter is designed to retrieve only source that already exists on your local machine. If you want to retrieve new classes, use the `--metadata` parameter instead. The Salesforce Extensions for VS Code docs have more info on how the VS Code functionality works: https://forcedotcom.github.io/salesforcedx-vscode/articles/user-guide/org-development-model#retrieve-source

"NOTE: The retrieval occurs only on metadata that’s nested (in the file tree) under the item you select. For example, if you right-click the classes folder, all Apex classes that currently exist in that directory are retrieved or deployed. Running a retrieve operation on a directory like classes doesn’t retrieve all Apex classes on the org; it retrieves updates only to classes that already exist in the folder. If you want to retrieve a new Apex class, add that class (or all Apex classes) to a package.xml file and retrieve your source using the manifest file. (Or, you can use a terminal to run sfdx force:source:retrieve --metadata ApexClass:YourApexClass.)"
