### ISSUE TITLE
force:source:push Unexpected error with communities using Experience Bundle.

### ISSUE THREAD

**Issue by erocheleau** [forcedotcom/cli#510]
### Summary

Unexpected error occurred when trying to push a community using the Experience Bundle format.
```Error  force-app\main\default\experiences\MyCommunity.site-meta.xml  An unexpected error occurred. Please include this ErrorId if you contact support: 1023426978-162915 (1302355068)```

I have no idea what the problem is so I cannot fix it.

### Steps To Reproduce:

I do not know what the error is, so I cannot really say how to reproduce. I had an existing community, converted it to Experience Bundle (Activating that feature in my organization).
And now when I try to deploy my source code, nothing will deploy with an Unknown error with a cryptic error message.

### Expected result

Source code would deploy in a scratch org.

### Actual result

Unexpected error on force-app\main\default\experiences\MyCommunity.site-meta.xml with an error Id: `1023426978-162915 (1302355068)`

### Additional information

**SFDX CLI Version**

sfdx-cli/7.66.2 win32-x64 node-v12.16.0

**SFDX plugin Version**

```@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.2.3 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 49.3.0 (core)
├─ custom-metadata 1.0.7 (core)
└─ salesforcedx-templates 48.32.0 (core)
sfdx-cli 7.66.2 (core)
```

**OS and version**: Windows 10 x64 command line. Also happens with WSL environment.

**Comment by shetzel** [comment]
I've notified the communities team of the error.  Feel free to contact support with the error ID mentioned.

**Comment by shetzel** [comment]
This issue was already being addressed by the communities team and should be fixed soon (it's under review now).  Thanks for reporting.

**Comment by erocheleau** [comment]
Is there any way to know what the error is? Something I can fix on my side? I reverted to not using experiences and it works for now, but I would much prefer to be able to use Experiences.

**Comment by msrivastav13** [comment]
@erocheleau This is a known issue relating to this https://trailblazer.salesforce.com/issues_view?id=a1p3A0000003vc8QAA.

As @shetzel said it will be soon fixed! 

You can work around this issue, for now, can be found below 

https://github.com/trailheadapps/ebikes-lwc/issues/214
