### ISSUE TITLE
'sfdx plugins:generate -h' does not show helper options, the command accepts -h as a name

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#511]
### Summary

'sfdx plugins:generate -h' does not show helper options, the command accepts -h as a name

![image](https://user-images.githubusercontent.com/55927613/88238102-2b5da580-cc57-11ea-93fe-d5968316c7c7.png)

### Steps To Reproduce:

Just run `sfdx plugins:generate -h`

### Expected result

Should display the helper options

### Actual result

The command starts and accepts -h as the name arg

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 
v7.65.4

**OS and version**:
Windows 10

**Comment by shetzel** [comment]
Thanks for reporting @AllanOricil.  This is a known issue being tracking internally with W-5998680.
