### ISSUE TITLE
Snapshot: Cant create Scratch Org Error Code: C-1033

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#513]
### Summary
I was creating Scratch Orgs without any problem today in the morning. Then in the Afternoon this error started to happen.

![image](https://user-images.githubusercontent.com/55927613/88310844-0d9c4900-cd08-11ea-82e3-6898623abc31.png)

Is it a connection issue?

OS: Windows 10
Sfdx Version: sfdx-cli/7.66.2-4f159a1d07 win32-x64 node-v12.13.0

**Comment by AllanOricil** [comment]
It happened because I was using a Snapshot from the previous Major :/

**Comment by AllanOricil** [comment]
I would like to reopen this as it would be nice to have a better error message.
"You can't create a Scratch Org from a Snapshot after a new Salesforce major release"

**Comment by ekapner** [comment]
I'll open a bug to improve this error message and take a look at all Snapshot error messages to make sure they provide enough information. A new snapshot must be (re)created each release. Snapshots aren't backward compatible.

**Comment by AllanOricil** [comment]
> I'll open a bug to improve this error message and take a look at all Snapshot error messages to make sure they provide enough information. A new snapshot must be (re)created each release. Snapshots aren't backward compatible.

Thank you @ekapner 
More explanatory error messages improve DX and reduce wastes.

**Comment by mshanemc** [comment]
W-8775528

**Comment by mshanemc** [comment]
There's a WI for this.  It belongs to the org signups folks, so CLI team can't fix it, but no need to open a case.

**Comment by rasmuszimmer** [comment]
I am facing a similar issue:

We created a scratch today with "release": "preview" and afterwards created a snapshot for it. The snapshot finished processing and is in State 'Active'. The scratch org we snapshotted from is certainly with Spring 22 on it, however when we try to create a new scratch from the snapshot we get the following:

![image](https://user-images.githubusercontent.com/5746348/151390353-eb66a31c-08b8-42a5-bbb9-addd6fe7a915.png)

**Comment by marsh-mellow** [comment]
I am also getting this error.

![image](https://user-images.githubusercontent.com/25592474/218464984-13ff7b19-7003-499c-8783-054ac724d08a.png)

**Comment by marsh-mellow** [comment]
sfdx-cli/7.187.1 win32-x64 node-v18.13.0

**Comment by arsenykonohov** [comment]
## Spring '23 North American Sandbox Feature Disruption

https://trailblazer.salesforce.com/issues_view?id=a1p4V000003BIYGQA4&title=spring-23-north-american-sandbox-feature-disruption&_ga=2.198371631.1803040757.1674995458-31584125.1674809812&_gac=1.19757386.1674809812.Cj0KCQiAic6eBhCoARIsANlox86CRRbZ6xz2wbOLFnN6MjZH2q-Hssc3OuT1zr_x75v2FT0ObuW5CqsaAuHOEALw_wcB

there is the recipe on how to proceed with scratch org creation
in short you have to add some placeholder in `config/project-scratch-def.json`

<img width="922" alt="Screenshot 2023-02-13 at 16 33 49" src="https://user-images.githubusercontent.com/7955895/218471866-bccfc68d-8614-4b1c-a399-c995e2df1089.png">

as well as u have to update the metadata API version:
- `sfdx config:set apiVersion=56.0 --global `
- set env var `SFDX_API_VERSION=56.0`

> UPD: I passed through this and everything was fine

**Comment by marsh-mellow** [comment]
@arsenykonohov ok that seemd to work thanks for the help!
