### ISSUE TITLE
Create a way of Upgrading a Snapshot after a Salesforce Major Release

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#514]
**Is your feature request related to a problem? Please describe.**
We had a bunch of snapshots created before the last Major release and now we can't recreate them because we don't know their configurations. I tried to create a Scratch Org of one of the snapshots to learn what is inside of it, but it always throws this exception. So, since I can't know what was in the snapshot, there is no way for me to recreate it.

![image](https://user-images.githubusercontent.com/55927613/88313098-e8f5a080-cd0a-11ea-8407-23f52a89e9f8.png)

**What are you trying to do**
Reuse the Snapshot after a Salesforce Major Release

**Describe the solution you'd like**
Create a sfdx command to Upgrade/Update the snapshot After a Major Release. Or make something to not mess with the snapshots. It is really not productive to have to recreate all of them. Also, how would we know what is inside of each one of the snapshots, if we can't create a Scratch Org from them anymore?

**Comment by clairebianchi** [comment]
Passing your feedback on to the Snapshot PM
