### ISSUE TITLE
sfdx force:source:status not working for source tracking sandbox

### ISSUE THREAD

**Issue by CaptainDX** [forcedotcom/cli#517]
I am executing force:source:status with a sandbox with source tracking enabled (I can even query SourceMember tooling api object) but when running this command I get "ERROR running force:source:status:  This command can only be used on orgs that have source tracking enabled, such as sandboxes and scratch orgs."

**Comment by peternoges** [comment]
@CaptainDX  im seeing the same.  Even with these enabled and the sandboxes refreshed afterwards:

Can you post your solution?

![image](https://user-images.githubusercontent.com/7834562/106044869-2b6eb000-6095-11eb-9085-78c73790575d.png)

**Comment by matt-mckinley** [comment]
I have had this issue off and on for months. I can't tell if they actually want us to use the feature.
