### ISSUE TITLE
sfdx force:source:deploy with --sourcepath to a scratch org is throwing Duplicate name errors.

### ISSUE THREAD

**Issue by javierCTL** [forcedotcom/cli#518]
### Summary

For some reason I get unexpected and duplicated errors on something that has been working in our CI for months now.

### Steps To Reproduce:

Deploy anything to a scratch org with this configuration. I'm trying with an object with a bunch of fields and a listview.

```
{
	"orgName": "XXXXXX",
	"edition": "Developer",
	"hasSampleData": true,
	"features": [
		"PersonAccounts",
		"LiveAgent",
		"SocialCustomerService",
		"LightningSalesConsole",
		"LightningScheduler",
		"LightningServiceConsole",
		"Sites",
		"Communities"
	],
	"settings": {
		"liveAgentSettings": {
			"enableLiveAgent": true
		},
		"lightningExperienceSettings": {
			"enableS1DesktopEnabled": true
		},
		"socialProfileSettings": {
			"enableSocialProfiles": true
		},
		"enhancedNotesSettings": {
			"enableEnhancedNotes": true
		},
		"communitiesSettings": {
			"enableNetworksEnabled": true
		}
	}
}
```

Using `sfdx force:source:deploy --wait 50 -g --sourcepath test/objects/SMS__c`

### Expected result

It should succeed after progress is complete.
SOURCE PROGRESS | ████████████████████████████████████████ | 7/7 

### Actual result
I get multiple duplicated errors
SOURCE PROGRESS | █████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 7/31 Components

Error  test/objects/SMS__c/fields/Body__c.field-meta.xml       Duplicate name 'SMS__c.Body__c' specified
Error  test/objects/SMS__c/fields/Date_Sent__c.field-meta.xml  Duplicate name 'SMS__c.Date_Sent__c' specified
Error  test/objects/SMS__c/fields/Lead__c.field-meta.xml       Duplicate name 'SMS__c.Lead__c' specified
Error  test/objects/SMS__c/fields/SID__c.field-meta.xml        Duplicate name 'SMS__c.SID__c' specified
Error  test/objects/SMS__c/fields/Status__c.field-meta.xml     Duplicate name 'SMS__c.Status__c' specified
Error  test/objects/SMS__c/fields/Body__c.field-meta.xml       Duplicate name 'SMS__c.Body__c' specified
Error  test/objects/SMS__c/fields/Date_Sent__c.field-meta.xml  Duplicate name 'SMS__c.Date_Sent__c' specified
Error  test/objects/SMS__c/fields/Lead__c.field-meta.xml       Duplicate name 'SMS__c.Lead__c' specified
Error  test/objects/SMS__c/fields/SID__c.field-meta.xml        Duplicate name 'SMS__c.SID__c' specified
Error  test/objects/SMS__c/fields/Status__c.field-meta.xml     Duplicate name 'SMS__c.Status__c' specified
Error  test/objects/SMS__c/fields/Body__c.field-meta.xml       Duplicate name 'SMS__c.Body__c' specified
Error  test/objects/SMS__c/fields/Date_Sent__c.field-meta.xml  Duplicate name 'SMS__c.Date_Sent__c' specified
Error  test/objects/SMS__c/fields/Lead__c.field-meta.xml       Duplicate name 'SMS__c.Lead__c' specified
Error  test/objects/SMS__c/fields/SID__c.field-meta.xml        Duplicate name 'SMS__c.SID__c' specified
Error  test/objects/SMS__c/fields/Status__c.field-meta.xml     Duplicate name 'SMS__c.Status__c' specified
Error  test/objects/SMS__c/fields/Body__c.field-meta.xml       Duplicate name 'SMS__c.Body__c' specified
Error  test/objects/SMS__c/fields/Date_Sent__c.field-meta.xml  Duplicate name 'SMS__c.Date_Sent__c' specified
Error  test/objects/SMS__c/fields/Lead__c.field-meta.xml       Duplicate name 'SMS__c.Lead__c' specified
Error  test/objects/SMS__c/fields/SID__c.field-meta.xml        Duplicate name 'SMS__c.SID__c' specified
Error  test/objects/SMS__c/fields/Status__c.field-meta.xml     Duplicate name 'SMS__c.Status__c' specified
Error  test/objects/SMS__c/listViews/All.listView-meta.xml     Duplicate name 'SMS__c.All' specified
Error  test/objects/SMS__c/listViews/All.listView-meta.xml     Duplicate name 'SMS__c.All' specified
Error  test/objects/SMS__c/listViews/All.listView-meta.xml     Duplicate name 'SMS__c.All' specified
Error  test/objects/SMS__c/listViews/All.listView-meta.xml     Duplicate name 'SMS__c.All' specified

### Additional information

<img width="1516" alt="Screen Shot 2020-07-24 at 4 12 12 PM" src="https://user-images.githubusercontent.com/35734222/88400298-6fbc8300-cdc8-11ea-96ca-ad5635b5ee04.png">

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

`sfdx-cli/7.66.2-4f159a1d07`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.2.3 (core)
├─ salesforcedx-templates 48.32.0 (core)
├─ salesforce-alm 49.3.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ custom-metadata 1.0.7 (core)
sfdx-cli 7.66.2 (core)
```
**OS and version**:
macOS Catalina Version 10.15.6

**Comment by shetzel** [comment]
Thank you for the detailed report.  A few more things will help us here.

1. What are the contents of `sfdx-project.json`, specifically for packageDirectories?
2. Where are you executing the `source:deploy` command from?  The project root or some other directory?

**Comment by javierCTL** [comment]
Hi @shetzel, thanks a lot for your response.

Your questions made me realize I didn't have the folder I was trying to deploy in the `sfdx-project.json`. Once I added it, it started working properly 🎉  

Thanks again for your help.
