### ISSUE TITLE
Create 'sfdx force:package:version -p PACKAGE --display-metadata --json' to get the content of the package

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#519]
**Is your feature request related to a problem? Please describe.**
Yes. I have a bunch of packages and I cant find what is inside each unless I open an org and install the package

**What are you trying to do**
I'm trying to list the content of my packages without having to install them

**Describe the solution you'd like**

Create `sfdx force:package:version -p PACKAGE --display-metadata --json`, or just`sfdx force:package:version -p PACKAGE --json`, to get the content of the package

**Describe alternatives you've considered**
I can use git API to list the content of a git repository. But Im sure the package version has the files it has as metadata, so it would be good to expose this in the salesforce api and let the us use it from the cli.

**Comment by clairebianchi** [comment]
Passing your feature request on to the Packaging team.
