### ISSUE TITLE
Not able create new project in VS code.

### ISSUE THREAD

**Issue by anushrgowda** [forcedotcom/cli#52]
### Summary

Just followed trailhead instructions of installing packages. All the necessary packages are installed. But running a create command does not results in an error.

### Steps To Reproduce:

1.  Using command palette call SFDX: Create Project.
2.  Enter Project name and select folder.

### Expected result

Project should get created.

### Actual result

Getting an error that says : "SFDX: Create Project failed to run."

### Additional information
This is the output: 

Starting SFDX: Create Project

20:39:09.270 sfdx force:project:create --projectname HelloWorldLightningWebComponent  --outputdir d:\SalesforceDX
 !    'ENOENT': ENOENT: no such file or directory, uv_chdir
20:39:12.54 sfdx force:project:create --projectname HelloWorldLightningWebComponent  --outputdir d:\SalesforceDX ended with exit code 1

**VS Code Version**: 1.31.1

**SFDX CLI Version**: 45.2.0

**OS and version**: Windows 10.

**Comment by clairebianchi** [comment]
@fedegiust does the path you are providing have space in it? If yes put quotes around the path. If this does not work, @ntotten this might be a bug on project:create

**Comment by a-db** [comment]
I'm having this problem as well and there are no spaces in the path.

ERROR running force:project:create:  No data, empty input at 1:1 in ../../../../package.json
...
ended with exit code 1

osx: 10.13.6
sfdx: 7.4.0
vscode: 1.33.1

**Comment by a-db** [comment]
If it helps anyone else, I was able to resolve my issue by deleting the package.json file in my root user directory. This must have there from older versions of the dx tools.

**Comment by kreynen** [comment]
@a-db That was my issue as well, but the package.json was from something unrelated to Salesforce.  If project creation fails 100% of the time when attempting to create a new project in a directory hierarchy that already contains a package.json at a higher level, it really seems like something the plugin should check for and return a usable error vs. just spitting back `SFDX: Create Project failed to run.`
