### ISSUE TITLE
Workflow rule criteria boolean values are saved into the source code metadata in the user's language

### ISSUE THREAD

**Issue by AltiusRupert** [forcedotcom/cli#520]
### Summary

Workflow rule criteria boolean values are saved into the source code metadata in the language of the last user who updated them (eg 'Vrai' in FR) when it should be saved in English.

### Steps To Reproduce:

1. As an Admin (language = EN), create a workflow WF1 on the Contact object.
2. Select Evaluation Criteria = "... when a record is : created, and any time it's edited to subsequently meet criteria"
3. Select Rule criteria - run this rule when "criteria are met"
4. Add 1 criterion : field "DoNotCall", operator = "equals", value ='True'
5. Save the workflow.
6. As a developer (user language in SF = EN), in VS Code, in an SFDX project for this org : verify that the source code in force-app/default/main/workflows/Contact.workflow-meta.xml contains 
        <criteriaItems>
            <field>DoNotCall</field>
            <operation>equals</operation>
            <value>True</value>
        </criteriaItems>

7. In the org, change the admin user's language to French.
8. change the workflow's evaluation criteria : 
field "DoNotCall", operator = "equals", value ='Faux' (French for FALSE)
9. Save
10. As the same developer (user language in SF = EN), retrieve the same file force-app/default/main/workflows/Contact.workflow-meta.xml and verify that it contains
        <criteriaItems>
            <field>DoNotCall</field>
            <operation>equals</operation>
            <value>Faux</value>
        </criteriaItems>

(value in French)

### Expected result

It should contain : 
        <criteriaItems>
            <field>DoNotCall</field>
            <operation>equals</operation>
            <value>False</value>
        </criteriaItems>

(value in English)

### Actual result

        <criteriaItems>
            <field>DoNotCall</field>
            <operation>equals</operation>
            <value>Faux</value>
        </criteriaItems>

(value in French)

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.62.1-309fe6da17 darwin-x64 node-v10.20.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
@salesforce/lwc-dev-server 2.1.1
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10

@salesforce/sfdx-diff 0.0.6
salesforce-alm 48.19.0
sfdx-changeset 0.1.0
sfdx-dce-plugin 0.0.0 (link) /Users/rupert/Workspaces/other/DCE DX/CLIENT-DCE/sfdx-dce-plugin
sfdx-plugin-ci 1.2.1
sfpowerkit 1.45.2
shane-sfdx-plugins 4.28.2

**OS and version**:
Darwin MacBook-Pro-de-Rupert-2.local 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86
MacOS 10.14.6

**Comment by clairebianchi** [comment]
@AltiusRupert This is not something our team can fix. The team that owns the workflow rule will have to fix it, please create a case, that team does not use Github as a support channel.

**Comment by RupertBarrow** [comment]
https://twitter.com/altius_rup/status/1313840378622226432
