### ISSUE TITLE
Unable to create a new version of a Unlocked Package with dependencies

### ISSUE THREAD

**Issue by sfvb** [forcedotcom/cli#521]
I have an unlocked package Pack1, which is the dependency of an unlocked package Pack2, which is the dependency of an unlocked package Pack3.
I can create new versions of Pack1 and Pack2, but if I want to create a new version of Pack3, then I get the error message:
`An error occurred while trying to install a package dependency, ID PACK2: The package you're installing depends on package 'PACK1', version '0.1'. Install package 'PACK1' in the target org before you install package 'PACK2'.`

I do not think I am able to manually install dependencies in this process and it should be done automatically.

This worked perfectly until two week ago, where I used it last.

**Comment by AllanOricil** [comment]
> I have an unlocked package Pack1, which is the dependency of an unlocked package Pack2, which is the dependency of an unlocked package Pack3.
> I can create new versions of Pack1 and Pack2, but if I want to create a new version of Pack3, then I get the error message:
> `An error occurred while trying to install a package dependency, ID PACK2: The package you're installing depends on package 'PACK1', version '0.1'. Install package 'PACK1' in the target org before you install package 'PACK2'.`
> 
> I do not think I am able to manually install dependencies in this process and it should be done automatically.
> 
> This worked perfectly until two week ago, where I used it last.

@sfvb
If you pass a config file for the package version creation command, it will create an "invisible" scratch org, deploy the dependencies of that package and then start the package version creation of your package. But to ensure it works, your package 3 must have the "dependencies" defined inside the "sfdx-project.json".

Could you post here the "sfdx-project.json" of the three packages?

**Comment by clairebianchi** [comment]
@AllanOricil @sfvb I will share this with the packaging team, but if you need immediate assistance please file a customer case

**Comment by AllanOricil** [comment]
@clairebianchi Im ok. I was just trying to help @sfvb but did not get a response. Thank you anyway!
