### ISSUE TITLE
(node:91395) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

### ISSUE THREAD

**Issue by agentgill** [forcedotcom/cli#522]
### Summary

Some sfdx commands are throwing the following

```bash
(node:91395) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
```

### Steps To Reproduce:

1.  sfdx force:data:soql:query --query SELECT Id, Name FROM Account LIMIT 1

or this command
 
1 . sfdx force:data:soql:query -q "SELECT Id, Name FROM Account LIMIT 1" -r csv > account.csv

### Expected result

Return Accounts lists without error - command appears to execute 100% successfully 

### Actual result

Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency

Followed by the output results

### Additional information

sfdx-cli/7.65.2 darwin-x64 node-v14.5.0

@oclif/plugin-autocomplete 0.2.0
dependencies-cli 2.0.1
salesforcedx 48.14.3 (48.14.3)
├─ salesforcedx-templates 48.17.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
└─ salesforce-alm 48.15.0
sfdx-autocmplt 2.2.0
sfdx-cmdt-plugin 0.0.6 (0.0.6)
sfdx-flowdoc-plugin 0.5.1
sfpowerkit 1.46.6
shane-sfdx-plugins 4.37.2

**OS and version**:

Mac 10.15.5

**Comment by mdonnalley** [comment]
That warning only occurs on node 14 and does not affect the command execution. I'm closing this for now since we only support node 12 at the moment
