### ISSUE TITLE
SFDX:Authorize an Org

### ISSUE THREAD

**Issue by sharmavishal94** [forcedotcom/cli#53]
Whenever i execute this command in vscode / Terminal CLI.
I get -
03:37:40.774 sfdx force:auth:web:login --setalias dx_lwc@gmail.com --instanceurl https://login.salesforce.com --setdefaultusername
ERROR:  EACCES: permission denied, open '/home/vishal/.sfdx/key.json'.
03:38:08.511 sfdx force:auth:web:login --setalias dx_lwc@gmail.com --instanceurl https://login.salesforce.com --setdefaultusername ended with exit code 1

**Comment by amphro** [comment]
Why is the owner root? You should `chown` the `.sfdx` folder back to your user otherwise I would imagine you need to `sudo sfdx` which is **not** recommended. If `chown` doesn't resolve the issue, please reopen the issue.

**Comment by sharmavishal94** [comment]
Thanks.
I was running commands as admin.
I created a standard user.
Then ran.
It went smooth :+1:
