### ISSUE TITLE
force:apex:test:run fails with SFDX_IMPROVED_CODE_COVERAGE=true

### ISSUE THREAD

**Issue by jorgjanke** [forcedotcom/cli#530]
### Summary

- we have 500+ tests in the org and run  _force:apex:test:run_ in GitLab
- that worked fine until a few days ago after adding additional code/tests
- the test works fine if SFDX_IMPROVED_CODE_COVERAGE is not set
- from the error message, it seems it hit a size limit

### Steps To Reproduce:

**Repository to reproduce:** 

Cannot reproduce in test repositories as too small.
- export SFDX_IMPROVED_CODE_COVERAGE=true
- sfdx force:apex:test:run --targetusername jjanke@accorto.com.de --wait 25 --resultformat human --codecoverage
- org id 00D80000000bRL6 - access granted

### Expected result

Usual test result

### Actual result

```
Unhandled rejection ERROR_HTTP_431: <h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>
    at HttpApi.getError (/Users/jorg/.local/share/sfdx/client/7.66.2-4f159a1d07/node_modules/jsforce/lib/http-api.js:250:13)
    at /Users/jorg/.local/share/sfdx/client/7.66.2-4f159a1d07/node_modules/jsforce/lib/http-api.js:95:22
    at tryCallOne (/Users/jorg/.local/share/sfdx/client/7.66.2-4f159a1d07/node_modules/promise/lib/core.js:37:12)
    at /Users/jorg/.local/share/sfdx/client/7.66.2-4f159a1d07/node_modules/promise/lib/core.js:123:15
    at flush (/Users/jorg/.local/share/sfdx/client/7.66.2-4f159a1d07/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

ERROR running force:apex:test:run:  Cannot read property 'message' of undefined
```

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.66.2-4f159a1d07 darwin-x64 node-v12.13.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.5.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
isvte-sfdx-plugin 1.1.6
salesforcedx 49.2.3 (core)
├─ salesforcedx-templates 48.32.0 (core)
├─ salesforce-alm 49.3.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ custom-metadata 1.0.7 (core)
sfdx-cli 7.66.2 (core)

**OS and version**:
MacOS 10.15.6 and GitLab runner with Ubuntu

**Comment by amphro** [comment]
dup of #346
