### ISSUE TITLE
An official Javascript SDK

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#531]
While CLI is good for basic CI tasks and day to day use, writing anything more than basic push/pull in bash very quickly becomes very hard.
There's already a package that I use for automating my orgs - [sfdx-node](https://www.npmjs.com/package/sfdx-node). It seems to mostly utilise internal `salesforce-alm` package to expose most of the functions. However, the sfdx-node package is seldom supported and misses key features (that we mostly worked around):
- Inline apex execution - it's super powerful to throw some apex when automating your org, but right now it depends on apex file on filesystem, meaning I needed to add a bit of extra code to delete temp files.
- Simple return from method / output from apex - right now we have to use some regex and parse debug logs to capture specific marker - not reliable to larger logs and plain ugly.
- Arbitrarily call Salesforce's REST API's - I don't know how is this even missing from sfdx by itself? Right now there's no way to get Attachments via sfdx! Sure I could get a token, craft a request, etc. But I feel this is already happening internally and exposing to public would be just a couple of methods.

What I'd love to see is a more polished `salesforce-alm` package (or some shim) that I could rely on and it's delivered by Salesforce.

**Comment by sjurgis** [comment]
Here's another one - tree:import command depends on file in filesystem, while I'd love to be able to just pass object into that command.

**Comment by mshanemc** [comment]
We recommend using the libraries that our CLI plugins are using.

Examples: 
https://github.com/forcedotcom/sfdx-core for orgs, config, auth, etc.
https://github.com/forcedotcom/source-deploy-retrieve for deploy/retrieve
https://github.com/forcedotcom/salesforcedx-apex for apex things

you'll also see a LOT of jsforce v2 used underneath those libraries for more primitive API calls.

Everything in the CLI is open source, so you can look at a command and see exactly which libraries we're using to do that task.
