### ISSUE TITLE
Ignore Jest Test directory when using a non-tracked org

### ISSUE THREAD

**Issue by sgkmills** [forcedotcom/cli#537]
**Is your feature request related to a problem? Please describe.**
When using a non-tracked org, the 'Push-or-deploy-or-save' setting will try to save JEST test files to the org, but it shouldn't.  Since the force:source:deploy command doesn't use the .forceignore file, it isn't ignoring the '__tests__' directory.

**Describe the solution you'd like**
Have the 'force:source:deploy' use the .forceignore file so the files/directories listed in there are not pushed to non-tracked org when you try to save a JEST test file and you have the 'Push-or-deploy-or-save' setting enabled.
**Describe alternatives you've considered**
Turning off the 'Push-or-deploy-or-save' setting and manually deploy the files I need to non-tracked org

**Additional context**

**Comment by lcampos** [comment]
Thanks for opening this @sgkmills . sfdx force:source:deploy command does use the `.forceignore` file, I wonder if this is a bug on how we're using the glob patterns or if it's a configuration issue. Can you provide the `.forceignore` configuration you are using to ignore the jest tests ?

cc @WillieRuemmele

**Comment by sgkmills** [comment]
To followup, I attached my forceignore file.  FYI, I had to change the filename to forceignore.txt to attach it.


[forceignore.txt](https://github.com/forcedotcom/cli/files/5125774/forceignore.txt)

**Comment by Bobnix** [comment]
I am experiencing the same while doing the exercises in the Trailhead module, "Lightning Web Components Tests". My forceignore is the same as @sgkmills. This bug results in every file under `__tests__` attempting to push on save and returning the error "The LightningComponentBundle named COMPONENT_NAME_HERE was not found in the workspace. SourceElementDoesNotExist"

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-10080138](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000JAFR9YAP/view)

**Comment by mshanemc** [comment]
I think this is fixed in the new `source:beta` commands that hit RC today.   @Bobnix @sgkmills  https://github.com/forcedotcom/cli/issues/1258

**Comment by mshanemc** [comment]
closed with new commands GA
