### ISSUE TITLE
force:source:retrieve on a child element in a object is retrieving entire object

### ISSUE THREAD

**Issue by manisfdcsfdx** [forcedotcom/cli#539]
### Summary

When force:source:retrieve command is used with -p <source path to field> is retrieve the entire object instead of retrieve the field alone.

### Steps To Reproduce:

1.  create a simple sfdx source project with just 1 case field
1.  sfdx force:source:retrieve -p <source path to field> -u sandbox

### Expected result

retrieve only the field from org to get any updates from org.

### Actual result

entire case object is being retrieved.

### Additional information

**OS and version**: Windows

**Comment by clairebianchi** [comment]
@manisfdcsfdx please provide a repo where this is reproducible. If you are trying to retrieve a custom field without the custom object it is associated with that is not possible.

**Comment by manisfdcsfdx** [comment]
@clairebianchi Looks like the issue is fixed, we are not able to reproduce it anymore. happy to close.
