### ISSUE TITLE
Help for force:source:deploy shows [object Object] for default wait

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#541]
### Steps To Reproduce:

```
sfdx help force:source:deploy
```

### Expected result

The default wait time to be shown in the help message

### Actual result

```
  -w, --wait=wait
 [default: [object Object]] wait time for command to finish in minutes
```

This probably affects other help messages too

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx --version
sfdx-cli/7.66.2-4f159a1d07 darwin-x64 node-v12.13.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

 sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.4
├─ salesforcedx-templates 48.18.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ salesforce-alm 48.24.0
└─ custom-metadata 1.0.4
sfdx-cli 7.66.2 (core)

**OS and version**:

macOS catalina

**Comment by clairebianchi** [comment]
@AndrewRayCode thank you, we are not seeing this. Let me know if it is still an issue on your end.
