### ISSUE TITLE
sfdx force:source:retrieve -n <package name> doesn't retrieve custom fields

### ISSUE THREAD

**Issue by ilanbalink** [forcedotcom/cli#542]
### Summary

The command sfdx force:source:retrieve -n <package name> doesn't retrieve custom fields;

### Steps To Reproduce:

1. Create a package
2. Add objects and fields into it
3. retrieve the package with sfdx force:source:retrieve -n <package name>

### Expected result
all fields are retrieved in the fields folder in the the <object name> folder 

### Actual result
no fields are retrieved
_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.68.6-d37008df83 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.4.1
├─ salesforce-alm 49.4.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ salesforcedx-templates 48.32.0
└─ custom-metadata 1.0.7
sfdx-cli 7.68.6 (core)
**OS and version**:
WINDOWS 10

**Comment by ilanbalink** [comment]
Any news on this?

**Comment by shetzel** [comment]
Pretty sure this is the same as 611 but keeping it open to verify.  Either way the fix will be in the next patch release.

**Comment by lnoellemorgan-zz** [comment]
Fixed by #611
