### ISSUE TITLE
npm ERR! 404  '@salesforce/ts-types@~1.2.1' is not in the npm registry.

### ISSUE THREAD

**Issue by masrajesh** [forcedotcom/cli#547]
/bin/bash --noprofile --norc /home/vsts/work/_temp/e337471f-02d8-491a-9878-7e04208086f1.sh
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@oclif%2fplugin-warn-if-update-available - Not found
npm ERR! 404 
npm ERR! 404  '@oclif/plugin-warn-if-update-available@~1.7.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'sfdx-cli'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsts/.npm/_logs/2020-08-06T09_52_03_139Z-debug.log
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.5: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@salesforce%2fts-types - Not found
npm ERR! 404 
npm ERR! 404  '@salesforce/ts-types@~1.2.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'salesforce-alm'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by vakaushish** [comment]
facing, similar issue with autocomplete package as well
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@oclif/plugin-autocomplete@0.1.5' ]
2 info using npm@6.14.5
3 info using node@v10.15.0
4 verbose npm-session d8fee653d63900d2
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@oclif%2fplugin-autocomplete 203ms
8 http fetch GET 404 https://registry.npmjs.org/@oclif%2fplugin-autocomplete 56ms
9 silly fetchPackageMetaData error for @oclif/plugin-autocomplete@0.1.5 404 Not Found - GET https://registry.npmjs.org/@oclif%2fplugin-autocomplete - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 480ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@oclif%2fplugin-autocomplete - Not found
12 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
12 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
13 verbose statusCode 404
14 verbose pkgid @oclif/plugin-autocomplete@0.1.5
15 verbose cwd /Users/vakaushish/Documents/projects/lwc-ursus/build-apps-with-lwc
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@oclif/plugin-autocomplete@0.1.5"
18 verbose node v10.15.0
19 verbose npm  v6.14.5
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@oclif%2fplugin-autocomplete - Not found
22 error 404
23 error 404 '@oclif/plugin-autocomplete@0.1.5' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]`

**Comment by keirbowden** [comment]
This was a problem with the npm registry today. It's working for me now.

**Comment by masrajesh** [comment]
thanks @keirbowden
