### ISSUE TITLE
npm install of salesforcedx at v49 bundles salesforcedx-templates at v48

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/cli#548]
### Summary

I've installed the latest Salesforce CLI (api version 49.0) via npm. The bundled templates are at api version 48.0 so files generated are at an earlier API version.

### Steps To Reproduce:

1. Install the latest Salesforce CLI via npm - `npm install --global sfdx-cli`
1. Execute `sfdx force:project:create -n .`

### Expected result

sfdx-project.json generated with API version 49.0

### Actual result

sfdx-project.json generated with API version 48.0

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.68.6 linux-x64 node-v14.5.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.4.1 (core)
├─ salesforcedx-templates 48.32.0 (core)       <-- note v48
├─ salesforce-alm 49.4.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ custom-metadata 1.0.8 (core)
sfdx-cli 7.68.6 (core)

**OS and version**:
Ubuntu 20.04 LTS

**Comment by amphro** [comment]
This has since been updated:
```
salesforcedx 49.10.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 49.4.4 (core)
├─ salesforce-alm 49.11.0 (core)
├─ apex 0.0.9 (core)
└─ custom-metadata 1.0.8 (core)
```
