### ISSUE TITLE
ManagedContentType are not currently supported by the CLI error in VS Code

### ISSUE THREAD

**Issue by rohitbagda77** [forcedotcom/cli#551]
We can’t retrieve the specified metadata object: ManagedContentType. Certain metadata types, like ManagedContentType are not currently supported by the CLI,
please solve this issue

**Comment by clairebianchi** [comment]
Thank you @rohitbagda77  we have notified the team that owns ManagedContentType

**Comment by amphro** [comment]
Removing this tag as it does seem the ManagedContentType is in the CLI. If you are still experiencing the issue, please file a new issue using the template and all the required information to reproduce including a repository and scratch org def.
