### ISSUE TITLE
Download URLs for SFDX archives and installers no longer working

### ISSUE THREAD

**Issue by dangmai** [forcedotcom/cli#552]
### Summary

The download URLs for SFDX archives and installers that are specified in the manifest files at https://developer.salesforce.com/media/salesforce-cli/manifest.json are no longer working for version 7.68.0. They return 403 with Access Denied status now.

I am using those URLs to manage the Arch Linux package for sfdx-cli here: https://aur.archlinux.org/packages/sfdx-cli/ and the build is breaking because of those missing packages.

### Steps To Reproduce:

1.  Go to manifest URL: https://developer.salesforce.com/media/salesforce-cli/manifest.json
1.  Go to any URL in the archives and installers section for version 7.68.0
1.  Notice that the link does not work

### Expected result

The links to those versions should be pointing to an artifact.

### Actual result

The links result in 403.

### Additional information

It looks like older version URLs are still accessible, for example: the Linux archive for version 7.65.6 is still accessible at https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-v7.65.6-23e8b7f47e-linux-x64.tar.xz but version 7.68.0 is not accessible, so maybe it's a bug with this particular version. However I still want to raise it so that it can be fixed for later version (and for this version too if possible). Note also that the downloads section URLs do work, but they don't contain all the packages (e.g. darwin version and Linux ARM version don't exist in that section).

**Comment by amphro** [comment]
I confirmed. We are investigating now.

**Comment by amphro** [comment]
This should now be fixed. Sorry for the issue @dangmai

**Comment by dangmai** [comment]
Great, thank you so much!

**Comment by dangmai** [comment]
Hi, the latest release (7.73.1) is having this issue again, any chance it can be fixed @amphro? Thank you!

**Comment by dangmai** [comment]
Hi @amphro, latest release (7.82.0) is showing the same behavior - could it get fixed please? Thank you!
