### ISSUE TITLE
Package version creation with multiple levels of dependencies is broken

### ISSUE THREAD

**Issue by jmaikeru** [forcedotcom/cli#56]
This is totally borked. A simple use case such as C -> B, B -> A fails on creation of a package version for C. I looked up the documentation regarding dependencies and figured maybe it was too stupid to figure out that A was required during the creation process- as the documentation has something along the lines of C -> B, A and B -> A in terms of dependency declarations.

Turns out this doesn't work either.

```(1) An error occurred while trying to install a package dependency, ID ID-FOR-PACKAGE-B: The package you're installing depends on package 'A', version '0.1'. Install package 'A' in the target org before you install package 'C'.```

It doesn't even help if you install A on the devhub- which leads me to believe that the "compile" for version creation is occurring in a separate universe. How is this supposed to be GA again?

**Comment by clairebianchi** [comment]
@sfdc-db-gmail Please take a look, packaging feedback.

**Comment by joeferraro** [comment]
@clairebianchi is this bug being tracked elsewhere on github?
