### ISSUE TITLE
Error while trying to authorize org

### ISSUE THREAD

**Issue by yahirah** [forcedotcom/cli#560]
### Summary
Since last two days, I have encountered error in both existing and brand new projects, when I get "Cannot read property 'getInstance' of undefined " while trying to authorize an org (sandbox).

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)
1.  Clone the repository.
1.  Try to authorize an org with command "sfdx force:auth:web:login --setalias sandbox --instanceurl https://test.salesforce.com --setdefaultusername --dev-debug"

### Expected result

A browser window with login option should appear.

### Actual result

I got an error "ERROR running force:auth:web:login:  Cannot read property 'getInstance' of undefined"

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.69.0 win32-x64 node-v12.13.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.5.1
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.5.0
├─ custom-metadata 1.0.8
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ salesforcedx-templates 49.2.0
└─ salesforce-alm 49.5.0
sfdmu 3.5.10
sfdx-cli 7.69.0 (core)

**OS and version**:
Windows 10 Pro x64

**Debug log**
[debuglog.txt](https://github.com/forcedotcom/cli/files/5068918/debuglog.txt)

**Comment by atsutton** [comment]
I receive the same error when running "force:org:list" and other commands.

Temporary workaround: install an older version of the CLI. It may cause other problems, but it allowed me to finally start working today:      sfdx plugins:install sfdx-cli@7.26.0

**Comment by nramyasri-sf** [comment]
I would also recommend you to do an uninstall of salesforce-alm plugin : `sfdx plugins:uninstall salesforcedx`,` sfdx update `and see if that resolves the issue.
