### ISSUE TITLE
Setting maxQueryLimit causing all commands to fail 

### ISSUE THREAD

**Issue by scott-arcus** [forcedotcom/cli#561]
### Summary

After setting the maxQueryLimit setting using `$ sfdx force:config:set maxQueryLimit=20000` all subsequent commands fail to run with the error `ERROR running force:org:open:  Value is not defined`.

### Steps to reproduce

1. Install the least version of sfdx on Windows
2. Set the maxQueryLimit with `$ sfdx force:config:set maxQueryLimit=20000`
3. Run another command such as `$ sfdx force:org:open`

### Expected result

Default scratch org should open in my preferred browser.

### Actual result

Error is displayed
`ERROR running force:org:open:  Value is not defined`

### Details

**SFDX CLI version**:  sfdx-cli/7.70.1-3d8a6229fc win32-x64 node-v12.18.3
**SFDX plugin version**: salesforcedx 49.6.1
**OS**: Windows 10

### Additional information

The issue appears to occur as the `$ sfdx force:config:set maxQueryLimit=20000` updates the `.sfdx/sfdx-config.json` file. The same error can be reproduced by manually adding a new value to this file such as `"test":"test"`.

**Comment by nadimdiazr** [comment]
Got into same problem.

**Comment by mshanemc** [comment]
Works when I try the reproduction.  Please re-open if you see it again, preferably with all the output of `sfdx plugins --core`
