### ISSUE TITLE
sfdx force:source:deploy Cannot read property 'record' of undefined

### ISSUE THREAD

**Issue by jfaderanga** [forcedotcom/cli#562]
### Summary

sfdx force:source:deploy -u $deploy_username -l RunLocalTests -p force-app

### Steps To Reproduce:
run it from the command line 

### Expected result

it will start deployment

### Actual result

ERROR running force:source:deploy:  Cannot read property 'record' of undefined

### Additional information

![image](https://user-images.githubusercontent.com/15375136/90239366-7e540280-de7b-11ea-9934-37337b124cdf.png)

--dev-debug

![image](https://user-images.githubusercontent.com/15375136/90239444-a5aacf80-de7b-11ea-84db-43f22ef73886.png)

**Comment by jfaderanga** [comment]
[jaysonfaderanga@ip-172-30-0-21 salesforce]$ sfdx plugins
no plugins installed
[jaysonfaderanga@ip-172-30-0-21 salesforce]$ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.1.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.2.1 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 49.6.1 (core)
├─ salesforce-alm 49.6.0 (core)
├─ salesforcedx-templates 49.2.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ custom-metadata 1.0.8 (core)
sfdx-cli 7.70.1 (core)

**Comment by cesarParra** [comment]
Same issue. Had to downgrade the salesforcedx version to be able to work:
`sfdx plugins:install salesforcedx@49.5.0`

**Comment by jfaderanga** [comment]
awesome thanks @cesarParra , your suggestion works, hopefully they fixed it in the upcoming versions, for now I remove the update script and keep the 49.5.0..

**Comment by wdci-dev** [comment]
I got the same error this afternoon when trying to perform "sfdx force:source:retrieve". Managed to get around it by following the same downgrade path.

**Comment by firatesmer** [comment]
I had the same issue and downgrading the plugin worked. Thanks @cesarParra.

**Comment by sjurgis** [comment]
Same here, downgrade helped.
Seems kinda lot of failures these days.

**Comment by amphro** [comment]
Dup of #564.
