### ISSUE TITLE
sfdx force:source:retrieve doesn't retrieve CSS Library components

### ISSUE THREAD

**Issue by adamOsieckiBtn** [forcedotcom/cli#563]
### Summary

It's not possible to retrieve lwc component without *.js file

### Steps To Reproduce:

1. I create and deploy CSS Library component: 
cssLibrary
   ├──cssLibrary.css
   └──cssLibrary.js-meta.xml
(https://releasenotes.docs.salesforce.com/en-us/summer20/release-notes/rn_lwc_css_share.htm)
2. Retrieve this component

sfdx force:source:retrieve -m LightningComponentBundle:cssLibrary

### Expected result

Component should be retrieved

### Actual result

ERROR running force:source:retrieve:  Cannot read property 'fileName' of undefined

### Additional information

_Feel free to attach a screenshot_.

![image](https://user-images.githubusercontent.com/36951505/90245874-c5b6a080-de33-11ea-9ab4-0074656b45cc.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.70.1-3d8a6229fc win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

salesforcedx 49.6.1 (core)
├─ salesforcedx-templates 49.2.0 (core)
├─ salesforce-alm 49.6.0 (core)
├─ custom-metadata 1.0.8 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)

**Comment by KevinGossentCap** [comment]
I confirm the problem, even with latest stable cli package
sfdx-cli/7.74.1 win32-x64 node-v12.18.4
salesforcedx 49.10.0 (core)
├─ templates 49.9.1 (core)
├─ custom-metadata 1.0.10 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ apex 0.0.9 (core)
└─ salesforce-alm 49.11.0 (core)
sfdx-cli 7.74.1 (core)

**Comment by KevinGossentCap** [comment]
Same result with latest pre-release version
salesforcedx 50.0.5 (pre-release)
├─ salesforcedx-templates 49.5.0
├─ salesforce-alm 50.0.5
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
└─ custom-metadata 1.0.10
sfdx-cli 7.74.1 (core)

**Comment by shetzel** [comment]
This will be fixed in the next CLI patch release.  ref: W-7868812

**Comment by SCWells72** [comment]
FYI, this is almost fixed in 7.75.0, but I'm still seeing one issue with it. It's not pulling down the component's `meta.xml` file when the style-only LWC component is retrieved.

**Comment by shetzel** [comment]
Thanks @SCWells72 - It's being retrieved but just not copied to the project properly.  I'll get it fixed asap.  Probably not this Thursday but the following.  Sorry about that.

**Comment by SCWells72** [comment]
@shetzel that's totally fine. Just trying to make sure you're all aware of any remaining loose ends. Thanks for the update!

**Comment by clairebianchi** [comment]
the internal ticket we are tracking W-7868812

**Comment by shetzel** [comment]
I'm trying to get the fix for this into the next latest-rc.  It's very close, and I'll let you know when you can try it in the RC.

**Comment by shetzel** [comment]
The fix for this will be in the release this Thursday.  salesforcedx v50.6.0, sfdx-cli v7.81.0.  You can try it early using the release candidate.  `sfdx plugins:install salesforcedx@latest-rc`.  Thanks for your patience!

**Comment by shetzel** [comment]
This is now fixed with CLI v7.81.0 and salesforcedx v50.6.0
