### ISSUE TITLE
ERROR running force:source:retrieve:  Cannot read property 'getInstance' of undefined

### ISSUE THREAD

**Issue by quygiengtmobile** [forcedotcom/cli#564]
### Summary

received Error:
ERROR running force:source:retrieve:  Cannot read property 'getInstance' of undefined

on all sfdx cmd: example: sfdx force:source:retrieve

### Steps To Reproduce:

1.  This is step 1.  sfdx force:source:retrieve
and received an error.

### Expected result

expected no error

### Actual result
ERROR running force:source:retrieve:  Cannot read property 'getInstance' of undefined
### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.47.3

**SFDX CLI Version**: 49.4.0

**OS and version**: MacOS 10.15.6

**Comment by lcampos** [comment]
@chriswill @dhaniksahni @quygiengtmobile I'm wondering if this is a new issue or a previously existing one, have you tried downgrading to a previous CLI version ?

**Comment by amphro** [comment]
This is due to having unnecessary plugins installed. We still aren't sure why the node_module resolution is getting messed up because the `getInstance` **is** there until it goes into the overwritten plugin code. 

You should be able to do `sfdx plugins` to see what you have installed and do `sfdx plugins:uninstall salesforcedx` or whatever the offending plugins is.

See #555 for more details. 

Notice in the thread you should not reinstall those plugins unless targeting old plugin versions.

**Comment by ghost** [comment]
Thank you!  I've been searching for a solution for this for several days now. 

Just some background to assist others: I'm not sure what triggered the `Cannot read property 'getInstance' of undefined` error initially, but one day it was working, the next day it wasn't. I did not upgrade the CLI, it has been running version 7.69.0-c7be45ae22 for several weeks now. I checked for an update today, which updated it to `sfdx-cli/7.70.1-3d8a6229fc`. The update didn't help, but after finding this post I did the following to resolve the issue:
`sfdx plugins:uninstall salesforcedx`

@amphro Are you saying there is no need to reinstall the salesforcedx plugin? Are they part of the sfdx core package now?

**Comment by quygiengtmobile** [comment]
Hi All,
I fixed this issue by clear all cli cache and data then install again.

**Comment by chriswill** [comment]
I fixed this issue by following steps in #555 

`sfdx plugins:uninstall salesforcedx`

**Comment by aman993** [comment]
Make sure your .sfdx folder has a sfdx-config.json file. If it is present try removing it and adding it again and authorize an org. the file should contain a json structure as follows:
{
    "defaultusername": "org alias name"
}
Authorize an org again and you should be good.

I tried the same and it redirected me to salesforce log in page and now the error does not come anymore.

**Comment by amphro** [comment]
| @amphro Are you saying there is no need to reinstall the salesforcedx plugin? Are they part of the sfdx core package now?

Correct. They have been bundled with the CLI since the beginning. You only need to install it if you want to hardcode to a specific version.

Closing this.
