### ISSUE TITLE
ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: Audience. Certain metadata types, like Audience are not currently supported by the CLI.

### ISSUE THREAD

**Issue by Sakthes** [forcedotcom/cli#571]
When I run the command in VSC, I have this error : 
 sfdx force:source:retrieve -m Audience
 ended with exit code 1

ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: Audience. Certain metadata types, like Audience are not currently supported by the CLI.

**Comment by JeffDanger** [comment]
This also appears to be affecting deployment as well as retrieval.

**Comment by Sakthes** [comment]
Is there a solution to retrieve and deploy Audience metada?

**Comment by amphro** [comment]
I want to keep all audience problems under #470
