### ISSUE TITLE
force:source:retrieve should honor the .forceignore file

### ISSUE THREAD

**Issue by loganm** [forcedotcom/cli#58]
**Is your feature request related to a problem? Please describe.**
We are running an org-based project with SFDX. Our manifest is setup to track all roles, but this also brings in the partner portal roles which are system managed and cannot be changed or deployed.

To ignore these roles would mean making a massive whitelist of every other role, and having to edit that list when roles are created or changed.

**Describe the solution you'd like**
If force:source:retrieve honored the .forceignore file, we could add `**PartnerUser.role` to the file, and keep the roles as a wildcard in the manifest.

**Comment by shetzel** [comment]
@loganm - the `source:retrieve` and `source:deploy` commands already honor the .forceignore file.  I just tested it with roles and it works as expected.  **.role will ignore all roles.  Your example should also work.  I tested with wildcarding all roles in the package.xml and ignoring **PartnerUser.role in the .forceignore file and it worked.

**Comment by loganm** [comment]
Hey @shetzel. Thanks, I had another crack and it worked as expected! I jumped the gun on this report.

I think I already had the files in my force-app directory, and re-running the source:retrieve wasn't clearing old files out. It seems so obvious now.
