### ISSUE TITLE
"SFDX: Retrieve This Source from Org" works only on default package dir

### ISSUE THREAD

**Issue by wrone** [forcedotcom/cli#588]
### Summary

I have multiple package directories. When I execute "SFDX: Retrieve This Source from Org" on components that are not in the default dir, nothing happens, I don't see any errors, but this feature works on components that are located in the default dir.

In the same time, when I press "SFDX: Diff File Against Org", it works on components from both dirs, default and non-default ones. Shouldn't "retrieve" behave the same way?

If I'm not mistaken, this was working fine several days ago.

### Steps To Reproduce:

1. This is my sfdx-project.json
```
{
  "packageDirectories": [
    {
      "path": "org-unpackaged",
      "default": true
    },
    {
      "path": "org-base"
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "49.0"
}
```
1. Retrieve components using "Org Browser"
1. All components are retrieved to default dir, move some of them to non default (org-base) dir
1. Execute "SFDX: Retrieve This Source from Org" on the class that is located in the non-default (org-base) dir

### Expected result

Class that is located in the non default dir (C:\VSC workspace\service-salesforce-uk\org-base\main\default\classes\Constants.cls) should be retrieved

### Actual result

Nothing happens, no messages, no notification, no errors. The same issue is with the "SFDX: **Deploy** This Source to Org".

"SFDX: Retrieve This Source from Org" on the class that is located in default (org-unpackaged) dir works fine.

### Additional information

**VS Code Version**: 1.48.0
**SFDX CLI Version**: 7.70.1-3d8a6229fc
**OS and version**: Windows 10 Pro, 1909

**Comment by shetzel** [comment]
@wrone - multiple package directories support for the `source:deploy` and `source:retrieve` commands are coming very soon.  You can test them now installing the mpd canary release.  `sfdx plugins:install salesforce-alm@mpd` After installing, re-run your commands.  After testing, run `sfdx plugins:uninstall salesforce-alm` to go back to the core plugin version.

**Comment by wrone** [comment]
@brpowell, just checked the permissions, everything seems identical.

@shetzel, now I see another error:

- command - sfdx force:source:retrieve --sourcepath "C:\VSC workspace\service-salesforce-uk\org-base\main\default\classes\Constants.cls"
- response - ERROR running force:source:retrieve:  The ApexClass named Constants was not found in the workspace.

I'm sure that the path is correct, I copied it from the file explorer

**Comment by shetzel** [comment]
@wrone - You are executing that command from your project root directory right?  Are you using VS Code for the retrieve or a shell?  For Windows, we officially support the Windows command prompt and powershell.  Are you using one of those shells?  I've tested this scenario many times using `salesforce-alm@mpd` and it works so I'm trying to find the environment differences.

**Comment by wrone** [comment]
Hi @shetzel,

I tried to test it one more time but I'm not able to install salesforce-alm@mpd anymore, shows this error "TypeError: Cannot read property 'dim' of undefined"
![image](https://user-images.githubusercontent.com/9321029/92879624-186c8380-f405-11ea-944c-19a36b2e1320.png)

Last time when I was testing it, I tried to retrieve components using VSC and Bash

**Comment by shetzel** [comment]
Hi - you don't need to install the mpd canary release anymore since the production plugins have been updated with that code.  You should be able to run `sfdx update` and get the plugin version that supports your usecase.  Please reopen this and mention me if you still have a problem after updating.
