### ISSUE TITLE
CLI command length

### ISSUE THREAD

**Issue by sharmavishal94** [forcedotcom/cli#59]
If possible can SFDX CLI commands made Shorter ?
For example in other frameworks like Angular to generate a component we use -
**ng g c 'name';**

Shorter names are easier to remember and are fast. 
sfdx force:lightning:component:create --type lwc --componentname helloWorld --outputdir force-app/main/default/lwc
to - 
**sfdx force:l:c:c --type lwc**

**Comment by dcarroll** [comment]
Interesting suggestion.  While we mull it over you can use and alias in your bash profile. Something like `
alias force:o:d='sfdx force:org:display'
`
Then you can do
`
force:o:d -u myorg
`

**Comment by sharmavishal94** [comment]
Will use alias till then.
