### ISSUE TITLE
force:auth:web:login attempts to spawn powershell from Linux (WSL)

### ISSUE THREAD

**Issue by bowmanjd** [forcedotcom/cli#597]
### Summary

When I use `sfdx force:auth:web:login` in Windows Subsystem for Linux, I receive `Error: spawn powershell.exe ENOENT`, because it attempted to use Windows `powershell` to launch the browser. From Linux.

### Steps To Reproduce:

1. Launch WSL (any distro)
2. Ensure that `/etc/wsl.conf` contains the following:

```text
[interop]
enabled = true
appendWindowsPath = False
```

3. Restart WSL if you changed `/etc/wsl.conf`
4. `sfdx force:auth:web:login -a MyDevHub`
5. Great sadness
6. Undesirable workaround: add Windows Powershell to shell PATH in Linux. Windows Powershell. Necessary for Linux?

### Expected result

There are a couple different results that would be acceptable:
- Use $BROWSER to launch the browser
- Output the url so the user can copy and paste into the browser of her choice
- Use a documented sfdx configuration setting of some sort (maybe there is one already?)

### Actual result

```console
Error: spawn powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn powershell.exe',
  path: 'powershell.exe',
  spawnargs: [
    '-NoProfile',
    '-NonInteractive',
    '–ExecutionPolicy',
    'Bypass',
    '-EncodedCommand',
    'UwB0AGEAcgB0ACAAIgBgACIAaAB0AHQAcABzADoALwAvAGwAbwBnAGkAbgAuAHMAYQBsAGUAcwBmAG8AcgBjAGUALgBjAG8AbQAvAHMAZQByAHYAaQBjAGUAcwAvAG8AYQB1AHQAaAAyAC8AYQB1AHQAaABvAHIAaQB6AGUAPwByAGUAcwBwAG8AbgBzAGUAXwB0AHkAcABlAD0AYwBvAGQAZQAmAGMAbABpAGUAbgB0AF8AaQBkAD0AUABsAGEAdABmAG8AcgBtAEMATABJACYAcgBlAGQAaQByAGUAYwB0AF8AdQByAGkAPQBoAHQAdABwACUAMwBBACUAMgBGACUAMgBGAGwAbwBjAGEAbABoAG8AcwB0ACUAMwBBADEANwAxADcAJQAyAEYATwBhAHUAdABoAFIAZQBkAGkAcgBlAGMAdAAmAHMAdABhAHQAZQA9AGYAMgA0ADMANwA2AGQANwBmADUAMQBiACYAcAByAG8AbQBwAHQAPQBsAG8AZwBpAG4AJgBzAGMAbwBwAGUAPQByAGUAZgByAGUAcwBoAF8AdABvAGsAZQBuACUAMgAwAGEAcABpACUAMgAwAHcAZQBiACYAYwBvAGQAZQBfAGMAaABhAGwAbABlAG4AZwBlAD0AeQAwAE8ARgB0AHMAMQB0AFUAZAA2AGoAcgBBAHEAMwB0ADgAQgBpAEsAWAB3AHkASQB1AGwAcwBPAEkAQwBwAEYAMwBDAFQAdgBtAHkAWQBtAFoARQBgACIAIgA='
  ]
}
```

### Additional information

`sfdx-cli/7.73.1 wsl-x64 node-v14.9.0`

```console
salesforcedx 49.9.2 (core)
sfdx-cli 7.73.1 (core)
```

**OS and version**:
Fedora 32 on WSL 2
`Linux DESKTOP-89373F4 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by bowmanjd** [comment]
Looks like this is an issue with open (aka opn) package on npm.

sindresorhus/open#56
sindresorhus/open#186

**Comment by mnunezdm** [comment]
I managed to solve this issue installing the wslu https://github.com/wslutilities/wslu package

```
sudo apt install gnupg2 apt-transport-https
wget -O - https://access.patrickwu.space/wslu/public.asc | sudo apt-key add -
echo "deb https://access.patrickwu.space/wslu/debian buster main" | sudo tee -a /etc/apt/sources.list
sudo apt update
sudo apt install wslu
```

And setting the browser env variable to wslview

```
export BROWSER=wslview
```

**Comment by bowmanjd** [comment]
Thanks. I used to solve it in a similar way (put a link to Chrome in my PATH and set BROWSER to it.

However, in later versions of `open`, it somehow detects WSL and then searches for Powershell. Is that not what you are seeing?

My current workaround is to put a link to powershell.exe in my Linux PATH. I don't like it at all, and I don't believe this is the right way to treat WSL users. But it works for now.

**Comment by shetzel** [comment]
As you pointed out, the CLI uses the `open` npm lib so it will have the same limitations.  WSL is on the list of known CLI limitations [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_considerations.htm?search_text=shell) so at this time, workarounds are your best bet.

**Comment by mobilizer** [comment]
I can confirm the workarround:

    sudo apt update
    sudo apt install wslu
    export BROWSER=wslview
    export PATH=$PATH:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/
