### ISSUE TITLE
I would like to extract Metadata based on Regex

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#598]
I have an org with metadata that is not packaged. Most of the Metadata is organized with prefixes, like HC. I would like to use a Manifest with the following format to extract, for instance, Apex classes that start with HC.

````xml
<types>
        <members>HC*</members>
        <name>ApexClass</name>
</types>
````

or with regex
````xml
<types>
        <members>/HC.*/</members>
        <name>ApexClass</name>
</types>
````

This would be useful in cases I have a lot of metadata with prefixes and I don't want to expend time using an UI to select each one of them.

**Comment by shetzel** [comment]
Hi Allan.  This would be a feature request for the metadata API, not for the CLI (which just uses the metadata API for deploys/retrieves). If the metadata API made the change to support it then you could do that from the CLI or any other tool that uses the metadata API.  I would suggest using the IdeaExchange to influence the prioritization of this feature.  https://ideas.salesforce.com/s/about
