### ISSUE TITLE
Unable to deploy SharingRuleOwner metadata using force:source:deploy

### ISSUE THREAD

**Issue by gsbasso** [forcedotcom/cli#6]
### Summary

Attempting to deploy a new Contact sharing rule using force:source:deploy -x package.xml

### Steps To Reproduce:
<ol>
<li>Create an owner sharing rule for the Contact object named MyOwnerSharingRule and retrieve metadata</li>
<li>Create a package.xml file that includes the following content:</li>
<pre>
&lt;types&gt;
    &lt;members&gt;Contact.MyOwnerSharingRule&lt;/members&gt;
    &lt;name&gt;SharingOwnerRule&lt;/name&gt;
&lt;/types&gt;
</pre>
<li>Run sfdx command:</li>
<pre>sfdx force:source:deploy -x package.xml</pre>
<li>The following error message is returned:</li>
<pre>The SharingOwnerRule named Contact.MyOwnerSharingRule was not found in the workspace.</pre>
<li>Update the package.xml file as follows:</li>
<pre>
&lt;types&gt;
    &lt;members&gt;Contact.*&lt;/members&gt;
    &lt;name&gt;SharingOwnerRule&lt;/name&gt;
&lt;/types&gt;
</pre>
<li>Run sfdx command:</li>
<pre>sfdx force:source:deploy -x package.xml</pre>
<li>No error is returned but sharing rule is not deployed</li>
</ol>

### Expected result

Sharing rule should appear under Contact Sharing Rules

### Actual result

Either an error is returned or metadata is ignored. See Steps To Reproduce for details.

**SFDX CLI Version**:
(sfdx --version) sfdx-cli/6.48.0-bfccc40118 (windows-x64) node-v8.9.4
(sfdx force --version) v44.0

**OS and version**:
Windows 7 64-bit

**Comment by clairebianchi** [comment]
FYI @kfidelak94

**Comment by rohits13** [comment]
Hi,

I am getting the same issue for all these components **SharingCriteriaRule, SharingOwnerRule, and WorkflowOutboundMessage**. What was the fix?

**SFDX CLI Version** :- sfdx-cli/7.13.0-27dbcb37d3 win32-x86 node-v10.15.3
**OS and version**: Windows 10  64-bit

![image](https://user-images.githubusercontent.com/19818494/60722665-e2469080-9f31-11e9-932a-7dade300f161.png)

**Comment by niv-goldenberg** [comment]
I'm still getting this for SharingCriteriaRule:
sfdx-cli/7.82.1-0 linux-x64 node-v14.16.0
Ubuntu 20.04

No errors and no actual deployment is fired, what was the fix for that?

**Comment by zerkz** [comment]
@clairebianchi Do you have an issue/bug ID for tracking this one? It just popped up in my employer's org again (folks were having issues deploying Sharing rule changes). Currently the only workaround we have is to do `SharingRules` type in package.xml vs. `SharingCriteriaRule` (shown here in the salesforce example package xmls https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm)
