### ISSUE TITLE
force:apex:test:run RunLocalTests or TestSuite not executing all the test

### ISSUE THREAD

**Issue by eyhuellou** [forcedotcom/cli#601]
### Summary

When executing :  sfdx force:apex:test:run -l RunLocalTests -u <soname> --verbose --resultformat human --wait 1000

In a scratch org which contains around 145 test method dispatched in 45 classes, it seems that not all the class are tested.

I am seeing that the number of failed class varies upon one execution from the other.

### Steps To Reproduce:

1) execute in a scratch org which contains a lot of unmanaged test class :
sfdx force:apex:test:run -l RunLocalTests -u <soname> --verbose --resultformat human --wait 1000

1) execute again in a scratch org which contains a lot of unmanaged test class :
sfdx force:apex:test:run -l RunLocalTests -u <soname> --verbose --resultformat human --wait 1000

### Expected result

Have the whole number of unmanaged test class executed

Version : 
sfdx-cli/7.72.0-697e9faee2 darwin-x64 node-v12.18.3
OSX 10.14.6

**Comment by thvd** [comment]
Looks like identical to: https://salesforce.stackexchange.com/questions/262893/any-way-to-get-consistent-test-counts-when-parallel-testing-is-used ?

**Comment by iowillhoit** [comment]
Hello @eyhuellou, we are cleaning up some old issues. I was able to find a closed work item by following the links through this issue (this issue -> stackexchange -> known issue -> reference ID).

If you are still seeing this problem while using most recent version of the `sf` cli (currently `2.26.10`) please open a new issue with an example repository that replicates this issue ([Dreamhouse](https://github.com/trailheadapps/dreamhouse-lwc/) can provide a good starting point).
