### ISSUE TITLE
sfdx force:source:pull retrieve recordtype in the compactLayout folder

### ISSUE THREAD

**Issue by mohametso** [forcedotcom/cli#602]
### Summary
when we run sfdx force:source:pull, the recordtype is pulled in the wrong folder (compactLayout Folder)

### Steps To Reproduce:

Modify  a recordtype
run sfdx force:source:pull 

### Expected result

retrieved in the recordtype foler

### Actual result

retrieved in the compact layout folder

### Additional information

<img width="777" alt="image" src="https://user-images.githubusercontent.com/6200344/92612159-e4d11280-f2b9-11ea-96f7-7ee34a57eb68.png">

**SFDX CLI Version**(sfdx-cli/7.73.2-feef087df8 darwin-x64 node-v12.18.3)

**OS and version**: MACOS Catalina 10.15.1

**Comment by mohametso** [comment]
Hi, it's look like the error occur when we have the same api Name between the recordtype and the CompactLayout. Hope this can help, regards,

**Comment by jclark-dot-org** [comment]
We are seeing the same thing when recordtype and listview have same api name; the recordtype file ends up in the list view directory.

**Comment by dcathcart** [comment]
If it helps, we've seen the same thing happen with the compactLayouts and businessProcesses folders.
We've also seen record types retrieved to the object's 'parent' folder, where the record type name matches the object name, e.g.:
`objects/PersonAccount/PersonAccount.recordType-meta.xml` instead of `objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml`.

Have observed in versions 7.78 and 7.82.

**Comment by hassanalamibmx** [comment]
hello i'm on `sfdx-cli/7.82.1-0 win32-x64 node-v14.15.0`
I have the same issue with a record type that have the same name as a compactLayout, the recordtype is retrieved in the compactLayouts folder

![image](https://user-images.githubusercontent.com/67870478/104011164-fb2aa480-51ad-11eb-9a13-1cc308299fb0.png)

cc @AhmetCelikbasBMX @PhilippePerrin @RoxaneRoche8

**Comment by gadamson-upco** [comment]
We are experiencing a similar problem, but in reverse. If I do a force:source:pull -f followed by a force:source:push -f, all files are in the correct locations, but I receive the following error:

![image](https://user-images.githubusercontent.com/6810264/105561483-afa6e900-5ccb-11eb-9dc0-2ddb03841e1a.png)

The object has compact layouts and record types with the same names.

**Comment by RensVerhagen** [comment]
We are also experiencing this weird behaviour, where recordType-meta.xml files are retrieved in listviews, fields and business process folders...  

![image](https://user-images.githubusercontent.com/20991258/108749367-078d7580-7540-11eb-8541-42328ffff62b.png)

**Comment by kgcabrera-abcbs** [comment]
We are also experiencing this issue with the force:source:retrieve command.

**Comment by BrentHebertZayo** [comment]
We have also been seeing some of this behavior. Are there any work arounds so far? I also see this is close to https://github.com/forcedotcom/cli/issues/714 and will be keeping an eye on both.

**Comment by maaaaarco** [comment]
@BrentHebertZayo  This happens when the RecordType has the same api name of another component... Try to change the name of the compact layout or the record type (if feasible) and it should work.

**Comment by mshanemc** [comment]
merging into #714 which has a lovely repro
