### ISSUE TITLE
Add a command to create developer org

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#604]
**Is your feature request related to a problem? Please describe.**
Right now it's something like over 20 steps before one can create a scratch org. That is super excessive for someone outside of Salesforce ecosystem, especially if you try to repro some bug in a library.

Or perhaps there's a way one can create couple of scratch orgs without a dev hub.

**What are you trying to do**
Create dev / scratch org 

**Describe the solution you'd like**
If you absolutely need lead gen form to be filled - perhaps question / answer prompt like in create-lwc-app could work.
A lot of users have git email address that you could grab for verification email.

**Comment by sjurgis** [comment]
@dcarroll this seems to have gotten 0 attention

**Comment by amphro** [comment]
Although I like the ability to reduce the barrier to entry, this is likely something the CLI team will never do for a variety of reasons. A couple of biggest ones are:

- lack of API
- security
- the way email verifications work today
- developer editions are less desirable than the dev hub trials or trailhead playgrounds, both of which follow similar issues
- this hasn't even got one community thumbs up

The better way to drive this sort of feature would be to create an idea on idea exchange.
