### ISSUE TITLE
force:apex:test:run Should run in a non-blocking manner even when requesting codecoverage be calculated

### ISSUE THREAD

**Issue by dturkel** [forcedotcom/cli#605]
### Summary

This command assumes that because I also want to calculate code coverage that I want those results immediately from the command, forcing me to provide an output format, as well as guess for how long I need to wait (-w).  In a CI/CD context, this is not flexible or valid.  I should be able to run this command and expect it to behave in the same manner as without -- execute and return the Test Run ID information so that I poll or act upon the information later.  Running without the --codecoverage flag runs all tests, but doesn't calculate retrievable coverage.  Stop implying inconsistent behavior.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Pick an org
1.  Execute "sfdx force:apex:test:run --json --verbose -l RunLocalTests -u $USERNAME"
1.  Copy/retain provide Test Run ID (which returns i**mmediately, non-blocking**)
1.  Execute (via whatever tooling you want) "SELECT ApexClassId,CreatedById,CreatedDate,ExtendedStatus,Id,ParentJobId,ShouldSkipCodeCoverage,Status,SystemModstamp,TestRunResultId FROM ApexTestQueueItem"  - queued tests all have "ShouldSkipCodeCoverage" as true
1.  Execute "sfdx force:apex:test:run --json --verbose -l RunLocalTests -u $USERNAME --codecoverage -r human"
1.  **Observe blocking behavior** (can't be run without implying full results being returned
1.  Execute SOQL from above to verify tests are NOT skipping coverage

### Expected result

When running with -codecoverage, I should have the same behavior as running without - command provides a Test Run ID immediately and doesn't block.

### Actual result

The command blocks, expects me to provide an output format and guess at an appropriate wait time to execute.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.73.2-feef087df8 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
$ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.2 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.9.2 (core)
├─ templates 49.4.4 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
├─ salesforce-alm 49.10.0 (core)
└─ apex 0.0.9 (core)
sfdx-cli 7.73.2 (core)

**OS and version**:
Windows 10

**Comment by bonkoirala** [comment]
Facing the same issue. Even if I provide a wait time of only 2 minutes (cant put any less than that), the command still blocks upcoming code and does not even provide a testRunId on completion.

**Comment by iowillhoit** [comment]
This is fixed in the most recent version of `sf` (currently `2.13.9`). I was able to follow your steps and observed that running the `sfdx force:apex:test:run --json --verbose -l RunLocalTests -u $USERNAME --codecoverage -r human` command now immediately returns a run id.

```sh
$ sfdx force:apex:test:run -l RunLocalTests --code-coverage -r human
# Run "sf apex get test -i 707Da00001lqqIA -o test-gat0eit6jlvh@example.com" to retrieve test results
# Run with --synchronous or increase --wait timeout to wait for results.
```

**Comment by dturkel** [comment]
Thank you!
