### ISSUE TITLE
Custom Page Web Link incorrect suffix when pulled down using force:sourc:retrieve

### ISSUE THREAD

**Issue by jjulicher** [forcedotcom/cli#606]
### Summary

As per the [Custom Page Web Link Apex Doc](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/custompageweblink.htm) the expected file suffix is weblink-meta.xml but when retrieved using the source format it is custompageweblink-meta.xml 

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/jjulicher/dreamhouse-lwc)

1. clone repo https://github.com/jjulicher/dreamhouse-lwc
2. sfdx force:source:deploy -p force-app -u yourSandbox
3. sfdx force:source:retrieve -m CustomPageWebLink -u yourSandbox
 
### Expected result

I would have expected the CustomPageWebLink 'SalesforceSupport' to download as 'SalesforceSupport.weblink' under the weblinks folder as per the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/custompageweblink.htm) . 

### Actual result

The file was download as 'SalesforceSupport.custompageweblink-meta.xml'

### Additional information

**SFDX CLI Version** sfdx-cli/7.72.0-697e9faee2 win32-x64 node-v12.18.3

**OS and version**: Windows 10 Version 1903 18362 1049

**Comment by jjulicher** [comment]
Is there any documentation on the differences between source format and MDAPI format?

**Comment by TWood-IRL** [comment]
@jjulicher, i know you've been waiting a while for an answer for this..  
you can get around this using 

sfdx force:source:retrieve -m "CustomPageWebLink:name_Of_webLink"

**Comment by mshanemc** [comment]
We modified it to
1) use the correct suffix
2) support the old suffix if you were already using it in your project

https://github.com/forcedotcom/source-deploy-retrieve/blob/ad4883b6e68a5a8530c3918d795181b07d1608da/src/registry/registry.json#L427

Please reply if it's still not working for you.
