### ISSUE TITLE
error in help for package:install

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#608]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  `sfdx force:package:install -h`.

### Expected result

the help text

### Actual result

the help text plus an error
![Screen Shot 2020-09-11 at 2 50 54 PM](https://user-images.githubusercontent.com/4261788/92967054-34d8e200-f43e-11ea-8876-9a1e99ad76d5.png)

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.74.1 darwin-x64 node-v12.14.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
$ sfdx plugins --core
@mshanemc/sfdx-migration-automatic 0.3.1 (link) /Users/shane.mclaughlin/code/sfdx-migration-automatic
@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/analytics 0.17.0 (link) /Users/shane.mclaughlin/code/sfdx-analytics-plugin
@salesforce/lwc-dev-server 2.5.1
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
evergreen 0.27.1
└─ evergreen-build 0.18.0
generator 1.1.3 (core)
salesforcedx 49.10.0
├─ templates 49.9.1
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ custom-metadata 1.0.10
├─ apex 0.0.9
└─ salesforce-alm 49.11.0
sfdx-cli 7.74.1 (core)
shane-sfdx-plugins 4.39.2 (link) /Users/shane.mclaughlin/code/shane-sfdx-plugins

**OS and version**:
osx catalina 10.15.6

**Comment by mshanemc** [comment]
same error at the bottom of `sfdx force:source:tracking:reset -h`

**Comment by clairebianchi** [comment]
@mshanemc are you still seeing this. I don't see this

**Comment by mshanemc** [comment]
yes.  If it works for you, this may be a local config problem on my end perhaps.

Here's the output from --dev-debug where the error is happening:

Error: EEXIT: 0
    at Object.exit (/Users/shane.mclaughlin/.local/share/sfdx/node_modules/@oclif/errors/lib/index.js:18:11)
    at PackageInstallCommand.exit (/Users/shane.mclaughlin/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/node_modules/@oclif/command/lib/command.js:54:36)
    at PackageInstallCommand._help (/Users/shane.mclaughlin/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/node_modules/@oclif/command/lib/command.js:126:21)
    at PackageInstallCommand.init (/Users/shane.mclaughlin/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:197:18)
    at PackageInstallCommand._run (/Users/shane.mclaughlin/.local/share/sfdx/node_modules/salesforce-alm/node_modules/@salesforce/command/lib/sfdxCommand.js:92:13)
    at Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)
    at Main.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at Main._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at Object.run (/usr/local/lib/node_modules/sfdx-cli/dist/cli.js:32:20)
  lazy-require saving type cache to /Users/shane.mclaughlin/Library/Caches/sfdx/module-types.json +383ms
  lazy-require no changes to save +1ms
  sfdx:analytics Spawning "/usr/local/bin/node /usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-analytics/processes/upload /Users/shane.mclaughlin/Library/Caches/sfdx /var/folders/_k/91sx3d6960v4lpt4jd8n58cc0000gq/T/sfdx-analytics/analytics-0fdb3d6b3d1f041c0c95e628d9d0b5603123f21e.log" +130ms

**Comment by mshanemc** [comment]
I'm not sure what analytics is doing here, either:

sfdx init version: @oclif/command@1.8.0 argv: [ 'force:package:install', '-h' ] +0ms
  @oclif/config runCommand force:package:install [ '-h' ] +3ms
  @oclif/config:salesforce-alm require /Users/shane.mclaughlin/.local/share/sfdx/node_modules/salesforce-alm/dist/commands/force/package/install.js +2s
  sfdx:core TRACE Setup child 'core:config' logger instance +0ms
  sfdx:core TRACE Setup child 'Config' logger instance +91ms
  sfdx:core TRACE Setup child 'Config' logger instance +1ms
  sfdx:Config INFO Reading config file: /Users/shane.mclaughlin/.sfdx/sfdx-config.json +0ms
  sfdx:Config INFO Reading config file: /Users/shane.mclaughlin/code/platformers-projects/PublicComponents/.sfdx/sfdx-config.json +1ms
  @oclif/config start prerun hook +210ms
  sfdx:@salesforce/plugin-analytics:hooks:prerun start /usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/plugin-analytics/lib/hooks/analyticsPrerun.js +0ms
  sfdx:core TRACE Setup child 'Config' logger instance +340ms
  sfdx:core TRACE Setup child 'Config' logger instance +1ms
  sfdx:Config INFO Reading config file: /Users/shane.mclaughlin/.sfdx/sfdx-config.json +0ms
  sfdx:Config INFO Reading config file: /Users/shane.mclaughlin/code/platformers-projects/PublicComponents/.sfdx/sfdx-config.json +2ms
  sfdx:analytics Usage acknowledgement file already exists +0ms
  sfdx:analytics Using analytics logging file /var/folders/_k/91sx3d6960v4lpt4jd8n58cc0000gq/T/sfdx-analytics/analytics-0fdb3d6b3d1f041c0c95e628d9d0b5603123f21e.log +1ms
  sfdx:analytics Error parsing flags +1ms
  sfdx:@salesforce/plugin-analytics:hooks:prerun done +14ms
  @oclif/config prerun hook done +14ms
  sfdx:core TRACE Setup child 'PackageInstallCommand' logger instance +0ms

**Comment by mshanemc** [comment]
one more hint:
`-h` will produce the error.  `--help` work just fine.  :)

**Comment by mshanemc** [comment]
works now.
