### ISSUE TITLE
source:convert with package.xml doesn't create custom fields

### ISSUE THREAD

**Issue by bytefreak** [forcedotcom/cli#611]
### Summary

using force:source:convert with a package.xml (-x manifest/package.xml), the in package.xml listed customfields are not converted. if I use force:source:convert with input directory (-r force-app) it works.

this happens since update from 7.66.2 to 7.71.0.

### Steps To Reproduce:

**Repository to reproduce:** [sfdx-bug-customfields](https://github.com/bytefreak/sfdx-bug-customfields)

1. use repo above
1. use shell scripts to convert metadata to mdapi output based on package.xml and directory (convert-by-*.sh)

### Expected result

generated output in folder mdapi-directory should be the same as in mdapi-package. especially the metadata for custom fields without customObjects should be created for package.xml too.

### Actual result

CustomFields are not generated in mdapi output. 

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.74.1 darwin-x64 node-v12.13.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 49.9.1 (core)
├─ custom-metadata 1.0.10 (core)
├─ apex 0.0.9 (core)
└─ salesforce-alm 49.11.0 (core)
sfdx-cli 7.74.1 (core)

**OS and version**:

 Mac OS Catalina: 10.15.6 (19G2021)

This also happens in out Bitbucket Pipelines docker image where the newest version of sfdx is installed.

**Comment by bytefreak** [comment]
Maybe related to #609 ?

**Comment by flexflo** [comment]
Hi @bytefreak, in my company we also use Bitbucket pipelines and we are having the same issue. We also noticed that after the convert runs the custom fields cannot  be deployed and we see "ERROR running force:source:convert:  The package root directory is empty". 

These are some of the error messages:
An object 'Activity.TaskName__c' of type CustomField was named in package.xml, but was not found in zipped directory
An object 'Activity.TaskType__c' of type CustomField was named in package.xml, but was not found in zipped directory

Do we need to downgrade the CLI version in the docker image? If so, any suggestions on how?

Sorry for @mentioning all the contributors but this seems pretty important since we can't deploy custom fields. Thanks!

FYI @jshackell-sfdc @amphro @clairebianchi @ntotten @dcarroll @mdonnalley @shetzel @rvwatch @nramyasri-sf @ruthemmanuelle

**Comment by dmgerow** [comment]
@flexflo  if you use npm to install your sfdx-cli then it should be easy. I had this issue on the latest version and fixed in my Jenkinsfile by specifying an old version (note this is Jenkins pipeline syntax but should translate to bitbucket)

`tools {nodejs "sfdx-cli@7.66.2"}`

**Comment by flexflo** [comment]
Hi @dmgerow, thanks for the suggestion. Are you using Docker? If so, is it a Windows image?

Thanks!

**Comment by dmgerow** [comment]
@flexflo sorry I am not on docker - I am using Jenkins on an Ubuntu server

**Comment by bytefreak** [comment]
@flexflo of course you can do the same in docker. you need to check how sfdx is installed in docker. I'm using the direct binary download but was not able to find the link to the older version. if it's installed via  npm you can simply request the older version if sfdx (refer to npm manual)

**Comment by shetzel** [comment]
Thanks for reporting.  We'll fix.

**Comment by flexflo** [comment]
> @flexflo of course you can do the same in docker. you need to check how sfdx is installed in docker. I'm using the direct binary download but was not able to find the link to the older version. if it's installed via npm you can simply request the older version if sfdx (refer to npm manual)

Thanks @bytefreak, we are looking into how to do it in Bitbucket Pipelines

**Comment by flexflo** [comment]
> Thanks for reporting. We'll fix.

Thanks for looking into this issue, @shetzel !

**Comment by ilanbalink** [comment]
Maybe related to  #542 ?

**Comment by shetzel** [comment]
The fix will be in the next patch release.  It should also fix #542, #623, #625, #628, and #156

**Comment by shetzel** [comment]
This is now fixed with CLI v7.76.1 and salesforcedx plugin v50.1.1

**Comment by cperes-sprintmind** [comment]
Updated to version 7.115.1 and the same error is happening again.
source:convert with package.xml doesn't create custom fields. Most of them are missing. Just a few are created in CustomFields node.
