### ISSUE TITLE
SFDX project directory requirement is being enforced as a prerun hook

### ISSUE THREAD

**Issue by aly76** [forcedotcom/cli#615]
### Summary

Recent changes to the CLI version 7.74.1 has introduced a SFDX project directory requirement as a prerun hook. This is causing our CICD / plugin to fail whereever it is calling the CLI from outside a SFDX project directory, for commands that you wouldn't expect to be dependent on a project directory:

e.g. 
- Authentication
- Listing orgs
- Listing packages in Dev hub   

### Steps To Reproduce:

Run command from outside SFDX project directory.

### Expected result

Command to execute successfully from any working directory - not necessarily a SFDX project directory.

### Actual result

Commands that you would not expect to be tied to a SFDX project directory are failing to execute from a non-project directories.

### Additional information

(node:17540) [InvalidProjectWorkspace Plugin: sfdx-cli] InvalidProjectWorkspace Plugin: sfdx-cli: This directory does not contain a valid Salesforce DX project
module: @oclif/config@1.17.0
task: runHook prerun
plugin: sfdx-cli

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
CLI Version 7.74.1
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/36793262/93156707-07e14380-f74c-11ea-8168-292d64cedaa8.png)

**Comment by azlam-abdulsalam** [comment]
@amphro  Our pipelines started breaking, mainly on the release orchestration side of things, where we don't checkout the repository, (install an unlocked package or do some org operations, there is no need for a sfdx project here)

**Comment by KevinGossentCap** [comment]
I confirm, it started breaking for anyone upgrading/freshinstalling since this night (morning).
It was working yesterday with same sfdx-cli package version...
an sfdx project folder (sfdx json definition file) is **NOW** mandatory for **everything**, **EVEN for creating a SFDX projet**

2 workarouds
- creating the sfdx-project.json file manually
- force installing salesforcedx@pre-release **which only resolves the project creation problem**, nothing more

**Comment by azlam-abdulsalam** [comment]
@KevinGossentCap its due to the update in @salesforce/core to 2.12.0, released  earlier in the day

**Comment by KevinGossentCap** [comment]
@azlam-abdulsalam do we have any way to force downgrade the module ?

**Comment by azlam-abdulsalam** [comment]
I don't think there is an easy way, as its a depenedency of salesforce-alm and many plugins

**Comment by KevinGossentCap** [comment]
Thanks for your insite @azlam-abdulsalam .
On our side we booked a high priority Case to Salesforce as lots of processes in the CI chain and in our dev work are breaking because of this issue.
Hoping to see a resolution ASAP.

**Comment by fitzman49** [comment]
As a workaround I ended up performing a "touch sfdx-project.json" after installing SFDX CLI from NPM in our CI/CD scripts.  Even though it's a empty file it lets the CLI recognize a project file is there and execute commands.

**Comment by azlam-abdulsalam** [comment]
Its fixed for now, as the latest tag on core is at 2.11.0
