### ISSUE TITLE
instanceUrl Runtime Configuration Value not Honoured

### ISSUE THREAD

**Issue by IvanDavidHarris** [forcedotcom/cli#616]
### Summary

The CLI Parameter Resolution Order (https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_cli_param_resolution.htm) states that file parameters have a higher priority than global and local runtime configuration values.

When the project configuration file parameter `sfdcLoginUrl` is present, it is correctly used. When it is omitted, and the runtime configuration value `instanceUrl` has a URL assigned, it is expected that the runtime configuration value will be used; however, it is not.

The same issue applies to the environment variable `SFDX_INSTANCE_URL`.

### Steps To Reproduce:

1. Create a new SFDX project:  `sfdx force:project:create -n repro_bug`.
1. Change directories to the project folder: `cd repro_bug`.
1. Edit the file `sfdx-config.json`, delete the line `"sfdcLoginUrl": "https://login.salesforce.com",` and save the file.
1. Set the `instanceUrl` runtime configuration value: `sfdx config:set instanceUrl=https://test.salesforce.com/`.
1. Authenticate an org: `sfdx force:auth:web:login`.

### Expected result

When the browser is launched, the URL in the address bar should be `https://test.salesforce.com/`.

### Actual result

The URL in the browser's address bar is `https://login.salesforce.com/`, which is the default if the `sfdcLoginUrl` parameter is not specified in the `sfdx-config.json` file.

### Additional information

**SFDX CLI Version**: sfdx-cli/7.74.1-32db2396ed darwin-x64 node-v12.18.3

**SFDX plugin Version**: sfdx-cli 7.74.1 (core)

**OS and version**: macOS Catalina Version 10.15.6 (19G2021)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9299422](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MQ8tYAG/view)

**Comment by mshanemc** [comment]
you're right.

**Comment by mshanemc** [comment]
fixed in 7.107.0 https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md#71070-june-24-2021
