### ISSUE TITLE
 sfdx force:data:soql:query outputs Querying Data... done  into stderr in windows

### ISSUE THREAD

**Issue by mnunezdm** [forcedotcom/cli#617]
### Summary

When extracting data from a windows machine using the `force:data:soql:query` using the csv format. A message with Querying Data is being printed into the stderr. These breaks our scripts when running them using the windows cli

### Steps To Reproduce:

1.  Launch `sfdx force:data:soql:query -u cross -r csv -q "select id from user limit 5"`

### Expected result

```cmd
C:\Users\miguel>sfdx force:data:soql:query -u cross -r csv -q "select id from user limit 5"
Id
0050N000006DnEXQA0
0050N0000069y2BQAQ
0050N000006AS9vQAG
0050N000006AUEoQAO
0050N000006DnEZQA0
```

### Actual result

```cmd
C:\Users\miguel>sfdx force:data:soql:query -u cross -r csv -q "select id from user limit 5"
Querying Data... done
Id
0050N000006DnEXQA0
0050N0000069y2BQAQ
0050N000006AS9vQAG
0050N000006AUEoQAO
0050N000006DnEZQA0
```

### Additional information

This happens in Git Bash and cmd, but in wsl does not happen

**SFDX CLI Version**: sfdx-cli/7.74.1-32db2396ed win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 49.4.4 (core)
├─ custom-metadata 1.0.10 (core)
├─ salesforce-alm 49.11.0 (core)
└─ apex 0.0.9 (core)
sfdx-cli 7.74.1 (core)

**OS and version**: Windows 10

**Comment by WillieRuemmele** [comment]
Hi @mnunezdm  check out the [announcement](https://github.com/forcedotcom/cli/issues/907) for the new [data](https://github.com/forcedotcom/cli/issues/907) plugin

**Comment by mshanemc** [comment]
I think this is fixed in the new data plugin released 4/1.  If not, re-open or create a new case.
