### ISSUE TITLE
MPD regression: force:source:retrieve deletes Field Translations (CustomObjectTranslation) metadata from local working directory

### ISSUE THREAD

**Issue by daveespo** [forcedotcom/cli#618]
### Summary

We currently track CustomObjectTranslation metadata in source control. Our project is in source format. We push/pull to scratch orgs and deploy/retrieve from DE and the packager org (1GP) using `package.xml`

Up until last week, this worked fine. Today, we see that when we `force:source:retrieve`, all of the FIELD metadata files for the custom object translations are deleted from our local working directory. The "top level" file that defines the translation for the SObject itself is left intact

This **only happens when multiple package directories are present in sfdx-project.json**

### Steps To Reproduce:

**Repository to reproduce:** https://github.com/patronmanager/object.translation.bug.2020.09

 * Clone the above repo
 * Create a scratch org and push the source (`sfdx force:org:create -f config/project-scratch-def.json --setdefaultusername; sfdx force:source:push`)
 * Retrieve using `sfdx force:source:retrieve -x mdapi\package.xml`
 * Expected: the working directory is clean (no dirty files) since all we did was retrieve exactly what we just pushed in
 * Actual: The source files for the 'SampleField' English and Italian translations are deleted

```
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    force-app/main/default/objectTranslations/SampleSObject__c-en_US/SampleField__c.fieldTranslation-meta.xml
        deleted:    force-app/main/default/objectTranslations/SampleSObject__c-it/SampleField__c.fieldTranslation-meta.xml
```

The `force:source:retrieve` reports that it pulled down the data for SampleField and if I inspect the MDAPI package by enabling the SFDX_MDAPI_TEMP_DIR, I see that the MDAPI translation file contains the translation for SampleField

```
<?xml version="1.0" encoding="UTF-8"?>
<CustomObjectTranslation xmlns="http://soap.sforce.com/2006/04/metadata">
    <caseValues>
        <plural>false</plural>
        <value><!-- Sample SObject --></value>
    </caseValues>
    <caseValues>
        <plural>true</plural>
        <value><!-- Sample SObject --></value>
    </caseValues>
    <gender><!-- Masculine --></gender>
    <nameFieldLabel><!-- SampleSObject Name --></nameFieldLabel>
    <startsWith><!-- Consonant --></startsWith>
    <fields>
        <label>Campo Personalizzato</label>
        <name>SampleField__c</name>
    </fields>
</CustomObjectTranslation>
```

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

`sfdx-cli/7.74.1-32db2396ed win32-x64 node-v12.18.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
etcopydata 0.5.12-b (beta)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 49.4.4 (core)
├─ custom-metadata 1.0.10 (core)
├─ apex 0.0.9 (core)
└─ salesforce-alm 49.11.0 (core)
sfdx-cli 7.74.1 (core)
```

**OS and version**:

Windows 10 Pro

**Comment by shetzel** [comment]
This might be the best bug writeup I've ever seen.  Thanks @daveespo we'll get it fixed.

**Comment by ascholl-breakline** [comment]
It seems that with the update to cli vsn 7.98.0, this behavior has been introduced. It does seem that the *.fieldTranslation-meta.xml files are created on the filesystem while the force:source:retrieve command runs, but they're deleted upon completion.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9300225](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MR4yYAG/view)

**Comment by mshanemc** [comment]
This should be fixed by changes some time ago (forgot to update the WI).

Please open a new issue if not.
