### ISSUE TITLE
Support updating package version postinstallurl and releasenotesurl

### ISSUE THREAD

**Issue by jonathanwiesel** [forcedotcom/cli#619]
**Is your feature request related to a problem? Please describe.**
Once a 2GP package version is created you can update several attributes using the `sfdx force:package:version:update` command such as the name, installation key and description, however you cannot update the related release notes URL or post-install URL. therefore you're forced to either create a new version with the missing URLs

**What are you trying to do**
Update the release notes URL and post-install URL of an already created 2GP package version

**Describe the solution you'd like**
Add additional arguments to the `sfdx force:package:version:update` command to grant the ability to update these values.

**Describe alternatives you've considered**
Since the underlying data is located in the [SubscriberPackageVersion object](https://developer.salesforce.com/docs/atlas.en-us.api_tooling.meta/api_tooling/tooling_api_objects_subscriberpackageversion.htm) is not really possible to update the data through the Tooling API since that object is not updatable

**Comment by wmigas** [comment]
it sounds like good idea, but probably first salesforce has to update tooling api. If I good remember `sfdx force:package:version:update` just call tooling API. If you cannot change it via tooling API, then it will not be part of the sfdx cli. 
I assume that it is not editable for a good/security reason. let's assume following scenario.

- Managed packaged has been created and passed security review,
- user change post install url to a website with malware or ads.

**Comment by WillieRuemmele** [comment]
Sorry for not getting back to anyone here, but you're alternative you've described, and @wmigas are correct. The CLI only has access to the APIs you do, so this isn't possible
