### ISSUE TITLE
sfdx retrieve command takes forever when run from VSCode console

### ISSUE THREAD

**Issue by hyalaman** [forcedotcom/cli#623]
The sfdx retrieve command on my side had been slow but off late it is taking more than 10mins for one file. This is causing a lot of problems with productivity. Can someone please let me know how to improve this.

Following is the command I am trying to run from vs code bash terminal
``sfdx force:source:retrieve -u sandbox -m "CustomField:ServiceContract.Region_New__c"

**Comment by shetzel** [comment]
Please use the template when submitting issues.  There is not enough information for anyone to help.

**Comment by hyalaman** [comment]
Sorry new to git.. where can i find the template ?
Following is the command I am trying to run from vs code bash terminal
``sfdx` force:source:retrieve -u sandbox -m  "CustomField:ServiceContract.Region_New__c"`

**Comment by shetzel** [comment]
It's the list of information you fill out when you click "New issue", then "New Bug" that tells us the CLI and plugin versions, OS, shell, repro steps, etc.

Regardless, this specific command, parameter, and metadata type appears to be broken in the latest CLI plugins so we'll fix it.  As a workaround, you can try using the same command but with the `-p` parameter and point it to your custom field file in the project.

**Comment by hyalaman** [comment]
ok got it.. below is my version of the tools. But how can I use the -p param for new retrieves I get this error ?

**ERROR running force:source:retrieve:  The sourcepath "C:\Projects\SFDC\force-app\main\default\objects\SBQQ__QuoteLine__c\fields\CPQ_Scale_Cost_Factor__c.field-meta.xml" is not a valid source file path.**

**SFDX CLI Version** 
sfdx-cli/7.73.2-feef087df8 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.2 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.9.2 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 49.4.4 (core)
├─ salesforce-alm 49.10.0 (core)
└─ apex 0.0.9 (core)
sfdx-cli 7.73.2 (core)

**OS and version**:
![image](https://user-images.githubusercontent.com/49921253/93608853-1d977880-f999-11ea-855c-930740b07bed.png)

**Comment by lnoellemorgan-zz** [comment]
Fixed by #611
