### ISSUE TITLE
postdeploy hook does not fire when the deployment fails

### ISSUE THREAD

**Issue by msrivastav13** [forcedotcom/cli#624]
### Summary

The postdeploy hook does not fire when the force:source:push command fails or force:source:deploy command fails. 

As per the [docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_plugins.meta/sfdx_cli_plugins/cli_plugins_customize_hooks_list.htm), it should fire on deploy success and failures as well

### Steps To Reproduce:

Use the plugin here https://github.com/msrivastav13/add-sound-effects-cli

Install the sfdx plugin here using `sfdx plugins:install add-sound-effects-cli`

1. Open any project like dreamhouse or e-bikes app or lwc-reciepes
2. Make a simple error in one of the metadata files. Remove the XML end tags is one of the easiest way
3. run sfdx force:source: push or sfdx force:source:deploy

### Expected result

1. The console should print 'PostDepoy Hook Running' but prints nothing indicating hook did not fire.

_Describe what should have happened_.

For success use case the hook fires

### Actual result

Hooks do not fire when deploy fails. 

### Additional information

Looks like on error the hook is not emitted for the metadata deploy. Please reach out if more info required

**Comment by shetzel** [comment]
Thanks for filing this @msrivastav13.  Tracked internally as W-8117716

**Comment by msrivastav13** [comment]
@shetzel I have upgraded to CLI version `sfdx-cli/7.75.0-5521f40d11` and the post-deploy hooks now do not fire on success or failure. You can play with https://github.com/msrivastav13/add-sound-effects-cli and watch that no post-deploy hooks fire.

**Comment by msrivastav13** [comment]
This is working as expected in the current release `sfdx-cli/7.76.1-f301d5641f darwin-x64 node-v12.18.3`.

Closing it!!!
