### ISSUE TITLE
Query autofetch seems to be not working

### ISSUE THREAD

**Issue by jonathanwiesel** [forcedotcom/cli#626]
### Summary

When creating a plugin and executing a query that returns rich text fields it returns only 250 records, according to the JSForce docs specifying the `autoFetch: true` option should automatically fetch all records, yet it doesn't (maybe the syntax is different?)

### Steps To Reproduce:

```
const query = `SELECT Id, Text__c FROM Knowledge__kav WHERE PublishStatus = 'Draft'`;
const queryRes = await conn.query<Article>(query, {autoFetch: true, maxFetch: 1000});

console.log(queryRes.records.length); // still 250
console.log(queryRes.done); // still false
console.log(queryRes.nextRecordsUrl); // not empty
```

### Expected result

All records are returned when using the `autoFetch: true` option

### Actual result

Only 250 records are returned representing the first "page" of results.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.74.1 darwin-x64 node-v14.7.0`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

```
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ templates 49.9.1 (core)
├─ apex 0.0.9 (core)
├─ salesforce-alm 49.11.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ custom-metadata 1.0.10 (core)
sfdx-cli 7.74.1 (core)
```

**OS and version**:
`macOS 10.15.6`

**Comment by shetzel** [comment]
Assuming you're using the `Connection` object from sfdx-core, you should just use `conn.autoFetchQuery()` as it's handled for you.  You can't call it as you're doing above.  See the code here: https://github.com/forcedotcom/sfdx-core/blob/develop/src/connection.ts#L268
Docs here: https://forcedotcom.github.io/sfdx-core/classes/connection.html

**Comment by jonathanwiesel** [comment]
Thank you for the clarification @shetzel I was wrongly looking at the `Connection` class from JSForce. 

I also noted that the `conn.sobject().update()` doesn't support the `allowRecursive `attribute for updating a large number of records, is this the place to report it or since is part of the base JSForce dependency it's directly related to that package?

**Comment by shetzel** [comment]
That's JSForce code, so you can report it there.

**Comment by jonathanwiesel** [comment]
Great, just reported there jsforce/jsforce#1068.

Thank you @shetzel, hope it helps future plugin developers
