### ISSUE TITLE
Request Header Fields Too Large

### ISSUE THREAD

**Issue by mattparlane** [forcedotcom/cli#63]
Hi! This is my first time using sfdx and I'm following the official documentation to create a scratch org.

When running `sfdx force:source:push`, I receive the following:

`ERROR:  <h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>.`

### Steps To Reproduce:

1. Pull metadata from existing org
1. Convert metadata to source format
1. Create scratch org
1. `sfdx force:source:push`

I can reproduce this every time. Happy to provide whatever information you need.

### Expected result

Don't know, never done it!

### Actual result

`ERROR:  <h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>.`

```
$ cat sfdx-project.json
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "45.0"
}
$ cat scratch.json
{
  "orgName": "Destiny Rescue",
  "edition": "Developer",
  "features": [],
  "settings": {
      "orgPreferenceSettings": {
          "networksEnabled": false,
          "s1DesktopEnabled": true,
          "s1EncryptedStoragePref2": false,
          "chatterEnabled": false
      },
      "omniChannelSettings": {
          "enableOmniChannel": true
      },
      "caseSettings": {
          "systemUserEmail": "digital@destinyrescue.org"
      }
  }
}
$ sfdx --version
sfdx-cli/6.56.0-e3fd846a1f (darwin-x64) node-v8.15.1
```

**Comment by clairebianchi** [comment]
Would you mind providing us with more information about the org you are working with? Can you provide the request payload? We realize that the error message is confusing and are going to work to fix that but also want to help you get unstuck in the meantime.
