### ISSUE TITLE
Scratch Org is created after TIMEOUT, but it does not have an Alias configured

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#632]
### Summary

I tried to create a Scratch Org (SO) as usual, but today sfdx threw a timeout error while creating. After listing the SOs I noticed it was created, but the alias I passed was not configured in the vscode extension. I think there are three problems, the first is the Timeout while creating the SO, the second is VSCode Extension configuring a new Org entry even after an error message, and the third is sfdx registering this new SO even after the timeout.

In the image below I highlighted the timeout error, and the SO it was created after the create command. You can see the SO does not have an alias.

![image](https://user-images.githubusercontent.com/55927613/93991427-341c4600-fd84-11ea-9a89-e3b71ede4b16.png)

### Steps To Reproduce:

- Create a SO
- While creating the SO, and after receiving the message below, simulate a TIMEOUT connection (I don't know how you will do it, maybe just disable your ethernet cable?) 

````
WARNING: We're deprecating OrgPreferenceSettings. We've added the settings to other metadata types in Winter '20. You can continue to use OrgPreferenceSettings until they are replaced by their corresponding settings in Spring '20. But why wait? Here's exactly what you need to update in the scratch org definition file.

Replace the orgPreferenceSettings section:
{
    "settings": {
        "orgPreferenceSettings": {
            "networksEnabled": true,
            "s1DesktopEnabled": true,
            "s1EncryptedStoragePref2": false
        },
        "omniChannelSettings": {
            "enableOmniChannel": true
        },
        "caseSettings": {
            "systemUserEmail": "sudarshan.reddy@hpe.com"
        }
    }
}
With their updated settings:
{
    "settings": {
        "omniChannelSettings": {
            "enableOmniChannel": true
        },
        "caseSettings": {
            "systemUserEmail": "sudarshan.reddy@hpe.com"
        },
        "communitiesSettings": {
            "enableNetworksEnabled": true
        },
        "lightningExperienceSettings": {
            "enableS1DesktopEnabled": true
        },
        "mobileSettings": {
            "enableS1EncryptedStoragePref2": false
        }
    }
}
For more info on configuring settings in a scratch org definition file see:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs.htm
````

- Verify the SO appeared in VSCode and SFDX without an alias

### Expected result

If sfdx throw an error, the SO should not appear on VSCode or SFDX.

### Actual result

SFDX and VSCODE are showing an SO without an Alias after an Exception happened. This SO can also be accessed without a problem.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.74.1-32db2396ed win32-x64 node-v12.18.3

**OS and version**: Windows 10

**Comment by clairebianchi** [comment]
Are you still facing this issue?

**Comment by AllanOricil** [comment]
Hi @clairebianchi It never happened again.
