### ISSUE TITLE
sfdx force:org:list --clean doesn't clear non connectable orgs (non scratch orgs)

### ISSUE THREAD

**Issue by jonathanwiesel** [forcedotcom/cli#637]
### Summary

I have some orgs that are not connectable anymore, one reason is sandbox refreshes, the output of `force:org:list` usually shows something like this:

```
=== Orgs
     ALIAS                  USERNAME                                      ORG ID              CONNECTED STATUS
───  ─────────────────────  ────────────────────────────────────────────  ──────────────────  ──────────────────────────
                            xxx@xxx.xxx                                   00D1r000000xxxxxxx  RefreshTokenAuthError
```

I was expecting that `sfdx force:org:list --clean` should remove that entry from the list, this however seems to not be the case. 

### Steps To Reproduce:

* Create a new sandbox org
* Authorize it using `sfdx force:auth:web:login`
* Refresh the sandbox
* Run `sfdx force:org:list` should show the authorization being invalid
* Run `sfdx force:org:list --clean`, the invalid connection is still there

### Expected result

Once executing the `sfdx force:org:list --clean` non-connectable orgs should be removed from the list

### Actual result

Non-connectable orgs are still shown.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.74.1 darwin-x64 node-v14.7.0`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 49.9.1 (core)
├─ apex 0.0.9 (core)
└─ salesforce-alm 49.11.0 (core)
sfdx-cli 7.74.1 (core)
```

**OS and version**:
macOS 10.15.6

**Comment by 1ktribble** [comment]
I have this same issue on `sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3`

**Comment by mshanemc** [comment]
This **should** be fixed in the new open-source version.  You can try it early, here: https://github.com/forcedotcom/cli/issues/835

**Comment by mshanemc** [comment]
I'm gonna close the issue now that the new org commands are shipped.

If you're still seeing it, please reopen or open a new one AND supply the output of `sfdx plugins --core`
