### ISSUE TITLE
"JavaScript heap out of memory" when running force:source:retrieve

### ISSUE THREAD

**Issue by mattparlane** [forcedotcom/cli#64]
### Summary

I have an existing org which I'm trying to import with my `package.xml` file. It's a decent sized org but not huge: 160MB of Documents, nothing else significant.

When running `force:source:retrieve`, I get this:

`FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory`

I have tried running with `NODE_OPTIONS=--max-old-space-size=8192` and I have also modified `/usr/local/bin/sfdx` and `/Users/matt/.local/share/sfdx/client/bin/sfdx` to add the parameter to `NODE_FLAGS`, but still no joy.

### Steps To Reproduce:

1. `NODE_OPTIONS=--max-old-space-size=8192 /usr/local/bin/sfdx --dev-debug force:source:retrieve --manifest /Users/matt/sites/fnsf-dx/manifest/package.xml`

### Expected result

Not sure, never run this command. Not expecting an out of memory error though.

### Actual result

Full command debug output: https://gist.github.com/mattparlane/bba2c6ef5ee424bbce99320b0f005fd4

### Additional information

```
MacBook-Pro-3:fnsf-dx matt$ /usr/local/bin/sfdx -v
sfdx-cli/7.1.4-79f97a7df8 darwin-x64 node-v10.15.3

MacBook-Pro-3:fnsf-dx matt$ /usr/local/bin/sfdx plugins --core
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.8.2 (core)
├─ force-language-services 45.9.0 (core)
└─ salesforce-alm 45.11.0 (core)

sfdx-cli 7.1.4 (core)
```

MacOS 10.14.3

**Comment by clairebianchi** [comment]
@mattparlane I have not seen this issue before and we have large orgs on SFDX. Would you mind posting your question to the Trailblazer DX Community (https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1) There are lots of users who may be able to help? If you still experience the problem, we can reopen this issue

**Comment by turalsadik** [comment]
MacBook Pro (15-inch, 2018)
Mem 16 GB 2400 MHz DDR4

Getting this error
My org is probably huge, but first need to get it to measure
