### ISSUE TITLE
"Application" meta-data type not supported

### ISSUE THREAD

**Issue by hartnady** [forcedotcom/cli#642]
### Summary

"Application" meta-data type not supported

### Steps To Reproduce:

From the CLI (any SFDX project with any sandbox or scratch org):
% sfdx force:source:retrieve -m Application
ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: Application. Certain metadata types, like Application are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type

### Expected result

SFDX retrieves Application meta-data type and downloads all App meta-data 

### Actual result

Error message: We can’t retrieve the specified metadata object: Application. Certain metadata types, like Application are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type

### Additional information
 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 
sfdx-cli/7.60.0-e2bb2907cb darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
% sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
evergreen-build 0.12.4
generator 1.1.2 (core)
salesforcedx 48.16.2
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ salesforcedx-templates 48.18.0
└─ salesforce-alm 48.17.0

sfdx-cli 7.60.0 (core)

**OS and version**:
macOS Catalina
10.15.6

**Comment by clairebianchi** [comment]
Thank you for reporting, we are alerting the team that owns this

**Comment by mshanemc** [comment]
Did you mean `CustomApplication` ?

Or something else from https://developer.salesforce.com/docs/metadata-coverage/57
