### ISSUE TITLE
Syntax error: Bad fd number

### ISSUE THREAD

**Issue by dsi0** [forcedotcom/cli#643]
### Summary

When installing sfdx-cli it fails with following error:
` > yarn@1.22.8 preinstall /usr/local/lib/node_modules/sfdx-cli/node_modules/yarn
 > :; (node ./preinstall.js >& /dev/null || true)
 sh: 1: Syntax error: Bad fd number
 npm ERR! code ELIFECYCLE
 npm ERR! errno 2
 npm ERR! yarn@1.22.8 preinstall: `:; (node ./preinstall.js >& /dev/null || true)`
 npm ERR! Exit status 2
 npm ERR! 
 npm ERR! Failed at the yarn@1.22.8 preinstall script.`

### Steps To Reproduce:
1.  Install sfdx-cli from scratch with the latest version

### Expected result

The cli should be installed without any errors

### Actual result

Error:
` > yarn@1.22.8 preinstall /usr/local/lib/node_modules/sfdx-cli/node_modules/yarn
 > :; (node ./preinstall.js >& /dev/null || true)
 sh: 1: Syntax error: Bad fd number
 npm ERR! code ELIFECYCLE
 npm ERR! errno 2
 npm ERR! yarn@1.22.8 preinstall: `:; (node ./preinstall.js >& /dev/null || true)`
 npm ERR! Exit status 2
 npm ERR! 
 npm ERR! Failed at the yarn@1.22.8 preinstall script.`

**Comment by Jana1706** [comment]
We have the same issue. Please help!

**Comment by amphro** [comment]
Can you please provide more information? 

- Your operating system and version
- The exact command you are running
- If you are running `npm`, the version of node and npm you are using
- Provide any debug files or verbose output (as a gist, please don't paste extremely long logs in a comment)

**Comment by dsi0** [comment]
Issue isn't occurring anymore.
