### ISSUE TITLE
force:source:retrieve -n "PackageName" doesn't retrieve Custom Object sub components. 

### ISSUE THREAD

**Issue by jjulicher** [forcedotcom/cli#644]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1. Create a Custom Object named 'TestObject'
1. Create a Custom field on TestObject named TestField type Text(255) 
1. Create a deployment package and name it 'TestRetrieve'. 
1. Click Add custom field 'TestField' to package.
1. Click Add custom object 'TestObject'
1. run ``` sfdx force:source:retrieve -n "TestRetrieve" -u <YourOrgUserName>```
1. CD into TestRetrieve\main\default\objects\TestObject__c\ 

### Expected result

_Describe what should have happened_.

Expected directory 'TestObject__c' to contain a fields folder with a field definition metadata file called 'TestField__c.field-meta.xml 

### Actual result

_Describe what actually happened instead_.

TestObject__c directory just contains TestObject__c.object-meta.xml 

and no field files or any other sub files.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.74.1 wsl-x64 node-v14.11.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**: Windows 10 version 1909 Build 18363.1082   running sfdx under WSL 2 Ubuntu 20.04

**Comment by shetzel** [comment]
Thanks for reporting.  I reproduced this and we'll work on a fix.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9300222](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MR6KYAW/view)
