### ISSUE TITLE
SFDX Extension behind proxy without HTTP_PROXY environment variable set.

### ISSUE THREAD

**Issue by AjManoj** [forcedotcom/cli#646]
### Summary

When setting only proxy in workspace settings and not setting  HTTP_PROXY the extension isn't able to connect to salesforce

### Steps To Reproduce:

1.  Workspace settings
  "http.proxy": "http://proxyurl:8080",
  "http.proxyStrictSSL": false,
  "http.proxyAuthorization": null,
  "http.proxySupport": "on",
2. Retrieve using package xml
    
### Expected result

_Should be able to retrieve_.

### Actual result

Error: connect ETIMEDOUT 13.108.233.69:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.108.233.69',
  port: 443
}
Error: connect ETIMEDOUT 13.108.233.69:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '13.108.233.69',
  port: 443
}
12:46:09.136 sfdx force:source:retrieve --manifest c:\Users\package.xml
 ended with exit code 1  

### Workaround
Create a bat file and put below things to launch if you don't want to setup HTTP_PROXY environment variables
SET NO_PROXY=127.0.0.1;*.<bypassurls>

SET HTTP_PROXY=http://<proxyurl>:8080

SET HTTPS_PROXY=http://<proxyurl>:8080

code -n

**Comment by clairebianchi** [comment]
@AjManoj are you using the VS code SFDX CLI extension? also what is the version of your CLI?
