### ISSUE TITLE
LiveAgent  Not available for deploy for this organization

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#648]
### Summary

Some scratch orgs fail to create with the error:
=== Component Failures [1]
TYPE   FILE                               NAME       PROBLEM
─────  ─────────────────────────────────  ─────────  ──────────────────────────────────────────────
Error  shape/settings/LiveAgent.settings  LiveAgent  Not available for deploy for this organization

ERROR running force:org:create:  Failed to deploy settings to scratch org.

This FREQUENTLY happens for ~ day after Salesforce pushes patches

### Steps To Reproduce:

1. Save scratch def that looks like this;
{
  "orgName": "Medical Information Cloud",
  "edition": "Enterprise",
  "features": [
    "AddCustomApps:30",
    "AddCustomTabs:30",
    "API",
    "AuthorApex",
    "CascadeDelete",
    "DebugApex",
    "PersonAccounts",
    "ServiceCloud"
  ],
  "hasSampleData": "false",
  "language": "en_US",
  "settings": {
    "chatterSettings": {
      "enableChatter": true
    },
    "emailAdministrationSettings": {
      "enableEnhancedEmailEnabled": true
    },
    "enhancedNotesSettings": {
      "enableEnhancedNotes": true
    },
    "entitlementSettings": {
      "enableEntitlements": false
    },
    "forecastingSettings": {
      "enableForecasts": false
    },
    "languageSettings": {
      "enableTranslationWorkbench": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "nameSettings": {
      "enableMiddleName": true,
      "enableNameSuffix": true
    },
    "orderSettings": {
      "enableOrders": false
    },
    "quoteSettings": {
      "enableQuote": false
    },
    "securitySettings": {
      "enableAdminLoginAsAnyUser": true
    }
  }
}
1. Connect to a Summer 20 DevHub
1. Create a new scratch org with release=Preview

### Expected result

Scratch org to create

### Actual result

=== Component Failures [1]
TYPE   FILE                               NAME       PROBLEM
─────  ─────────────────────────────────  ─────────  ──────────────────────────────────────────────
Error  shape/settings/LiveAgent.settings  LiveAgent  Not available for deploy for this organization

ERROR running force:org:create:  Failed to deploy settings to scratch org.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.74.1-32db2396ed darwin-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@mavens/mavens-cli 1.0.0-6 (link) /Users/kaiamundsen/.local/share/sfdx/node_modules/@mavens/mavens-cli
@mavens/mic-cli-plugin 8.1.0-0 (link) /Users/kaiamundsen/workspace/MedInfoCloud-CLI-Plugin
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0
├─ salesforce-alm 49.11.0
├─ custom-metadata 1.0.8
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ templates 49.4.4
└─ apex 0.0.9
sfdmu 3.7.7
sfdx-cli 7.74.1 (core)
texei-sfdx-plugin 1.7.0

**OS and version**:
macOS 10.15.7

**Comment by yippie** [comment]
I should add, the error is not consistent. It happens for me consistently but does not happen to our CI process (running on linux) or some of my colleagues. All of us use the same DevHub and scratch def but some get the error and some don't. I also getting the error attempting to create a package version of one of our unlocked packages.

It seems like this is dependent on what instance the scratch org is being created under.

**Comment by joem5815** [comment]
Experiencing this too, cannot create a scratch org, either getting "Error | shape/settings/LiveAgent.settings | LiveAgent | Not available for deploy for this organization" or "An unknown server error occurred. Please try again. If you still see this error, contact Salesforce support for assistance." Been trying for hours now and the errors just keep alternating between these.

{
    "orgName": "<excluded>",
    "edition": "Enterprise",
    "language": "en_US",
    "settings": {
        "apexSettings": {
            "enableApexCtrlImplicitWithSharingPref": true,
            "enableApexPropertyGetterPref": true,
            "enableAuraApexCtrlAuthUserAccessCheckPref": true,
            "enableAuraApexCtrlGuestUserAccessCheckPref": true,
            "enableMngdCtrlActionAccessPref": true
        },
        "chatterSettings": {
            "enableChatter": true
        },
        "enhancedNotesSettings": {
            "enableEnhancedNotes": true
        },
        "lightningExperienceSettings": {
            "enableS1DesktopEnabled": true
        },
        "mobileSettings": {
            "enableS1EncryptedStoragePref2": false
        },
        "pathAssistantSettings": {
            "pathAssistantEnabled": true
        },
        "userManagementSettings": {
            "enableEnhancedPermsetMgmt": true,
            "enableNewProfileUI": true
        }
    },
    "features": [
        "PlatformEncryption",
        "HealthCloudUser",
        "PersonAccounts",
        "ContactsToMultipleAccounts",
        "ServiceCloud",
        "Knowledge",
        "ForceComPlatform",
        "DebugApex",
        "FieldAuditTrail"
    ]
}

**Comment by rmathewsbeyond** [comment]
Facing similar error. Found a workaround by adding "features": ["LiveAgent"} to the scratch definition the error goes away, and scratch org is successfully created.
But hoping to not use this workaround, but have an actual solution.

**Comment by mshanemc** [comment]
I'm closing this issue (doing some cleanup of old issues that aren't related to CLI).  

If you can still replicate this, open a support case so it gets sent to the correct team
