### ISSUE TITLE
Any command that opens a browser, hangs in command prompt

### ISSUE THREAD

**Issue by banderson5144** [forcedotcom/cli#650]
### Summary

Any time I run a command that opens a browser (i.e. `force:org:open` or `force:auth:web:login`), the command prompt just hangs and does not exit the process. I have to then manually kill the process (Ctrl+C).

### Steps To Reproduce:

1. Run `sfdx force:org:open`

### Expected result

Process opens browser and command prompt is ready for next command

### Actual result

Process opens browser and command prompt is hanging. Need to Terminate batch (Ctrl+C) to run next command

### Additional information

![image](https://user-images.githubusercontent.com/2395774/94878050-45232200-042a-11eb-9aa3-302949f046ce.png)

Windows 7 64 Bit

**Comment by aheber** [comment]
@banderson5144, I've had this problem and still do once in a while. I was able to trace my problems back to SentinalOne, even with all the engines disabled I still saw the problem. Only went away when it was uninstalled.

I was also able to prove mine was unrelated to SFDX and was about asking the command prompt to open something, even just opening the explorer to the `C:` drive caused the problem. I'm on Windows 10 and updating to newer versions of Windows 10 made this happen much less often but I still have occasional problems a few times a month (still have the anti-virus installed).

Don't know if that helps but I can dig up some of my testing notes if this rings any bells for you.

**Comment by banderson5144** [comment]
@aheber this is on my personal machine so no enterprise software in the way.

**Comment by aheber** [comment]
Too bad, hope you can find an answer.

**Comment by clairebianchi** [comment]
@banderson5144 are you still experiencing this issue with the most recent CLI version?

**Comment by banderson5144** [comment]
@clairebianchi  correct yes:

`sfdx-cli/7.81.0 win32-x64 node-v12.19.0` is the version that I am on

**Comment by mshanemc** [comment]
@banderson5144 are you still seeing this on recent releases?

**Comment by banderson5144** [comment]
@mshanemc no, but I also just recently upgraded to Windows 10 so I can't be sure if this is still  happening on Windows 7

**Comment by mshanemc** [comment]
we don't support windows 7 (node dropped support for it since MSFT dropped support for it).  If win10 is good, I'm gonna close.  Thanks for the update.
