### ISSUE TITLE
SFDX force:source:convert fails for sfdx-cli/7.75.0 

### ISSUE THREAD

**Issue by marlisebriedenhann** [forcedotcom/cli#651]
### Summary

Related to the issue [SFDX project directory requirement is being enforced as a prerun hook](https://github.com/forcedotcom/cli/issues/615)

### Steps To Reproduce:

Our cicd pipeline runs the command `sfdx force:source:convert -d unpackaged` 

The command runs at the `/` directory that contains the sfdx directories and files including:
force-app/
sfdx-project.json 

sfdx-project.json specifies 

```
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
:
```

### Expected result
A message indicating that the command ran successfully
```
Source was successfully converted to Metadata API format and written to the location: /unpackaged
```
### Actual result

```
ERROR running force:source:convert:  The package root directory is not a source directory
Failed to run command, exited with 1 
Error: The command exited with status
```

### Additional information
Build Pass - sfdx-cli/7.74.1 linux-x64 node-v14.11.0

Build Fail - sfdx-cli/7.75.0 linux-x64 node-v14.11.0

**Comment by shetzel** [comment]
@marlisebriedenhann - This should be fixed with the latest CLI and plugins.  Please reopen if you're still seeing this.

**Comment by marlisebriedenhann** [comment]
Hi @shetzel 
Thanks for you update.  
I was still experiencing builds failing after updating to the latest sfdx cli, however after doing some more digging I discovered if I make a directory for the sfdx project and set that as the WORKDIR in the dockerfile, then the command `sfdx force:source:convert -d unpackaged` ran without the error reported in this issue.

**Comment by RJ-Cyntexa** [comment]
hi @marlisebriedenhann can you please explain how did you do that?
