### ISSUE TITLE
Custom Labels deployment doesn't work

### ISSUE THREAD

**Issue by IvanLevytskyiDataArt** [forcedotcom/cli#652]
### Summary

Custom Labels deployment doesn't work

### Steps To Reproduce:

1. Create Custom Label metadata file (_CustomLabels.labels-meta.xml_)
<?xml version="1.0" encoding="UTF-8"?>
```
<CustomLabels xmlns="http://soap.sforce.com/2006/04/metadata">
    <labels>
        <fullName>Contact_DuplicateFoundOnRecords</fullName>
        <language>en_US</language>
        <protected>false</protected>
        <shortDescription>Contact_DuplicateFoundOnRecords</shortDescription>
        <value>This record is duplicated in the set of records that are being inserted or updated.</value>
    </labels>
</CustomLabels>
```

2. Create package.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Contact_DuplicateFoundOnRecords</members>
        <name>CustomLabel</name>
    </types>
    <version>49.0</version>
</Package>
```

3. Deploy to any Org

`sfdx force:source:deploy --manifest manifest/package.xml -u %1 -l NoTestRun`

### Expected result

Custom label must be created on specified org.

### Actual result

It doesn't create any custom labels.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.75.0-5521f40d11 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.13.0 (core)
├─ templates 49.9.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
├─ salesforce-alm 49.12.1 (core)
└─ apex 0.1.0 (core)
sfdx-cli 7.75.0 (core)

**OS and version**:
Windows 10 Enterprise

**Comment by shetzel** [comment]
This is now fixed with CLI v7.76.1 and salesforcedx plugin v50.1.1

**Comment by shetzel** [comment]
Let's use #673 to track this.

I added a partial fix for custom labels in the current release candidate. Can you try installing that to see if it unblocks you?
sfdx plugins:install salesforcedx@latest-rc

It's a partial fix because it converts/deploys all custom labels in the project versus just the labels defined in the manifest. Converting/deploying specific labels is coming soon.

**Comment by IvanLevytskyiDataArt** [comment]
@shetzel 
It seems to work as you described. Thank you!

**Comment by shetzel** [comment]
@IvanLevytskyiDataArt - thanks for confirming!
