### ISSUE TITLE
Only First Custom field mentioned in Package.xml is getting deployed. Rest of the fields are ignored.

### ISSUE THREAD

**Issue by rahulkapoor83** [forcedotcom/cli#654]
While deploying multiple custom fields of same object using package.xml it is deploying only the field mentioned on the top. Rest of the fields are ignored.

### Steps To Reproduce:

1.  In my Repository I have two fields which i have deleted from the target org. Below is my package.xml
![image](https://user-images.githubusercontent.com/71480553/95021146-deea0980-068c-11eb-86bd-e7f8d479d8b3.png)

2. When I deploy this package.xml, it is just deploying the first field - Short_Name__c and the second one was ignored.
![image](https://user-images.githubusercontent.com/71480553/95021234-646db980-068d-11eb-8c07-c368413afd3e.png)

### Expected result
Both Custom Fields mentioned in package.xml should get deployed.

### Actual result
Only one custom field mentioned on the top was deployed.
![image](https://user-images.githubusercontent.com/71480553/95021411-7439cd80-068e-11eb-942a-fdaaa3d386e7.png)
![image](https://user-images.githubusercontent.com/71480553/95021428-8ddb1500-068e-11eb-8710-5e8015926087.png)

### Additional information
Version: 1.49.3 (user setup)
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:57:01.595Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362
![image](https://user-images.githubusercontent.com/71480553/95021331-fecdfd00-068d-11eb-92e2-847a62766dfa.png)

This is a major issue and will affect production deployments. Kindly fix this ASAP.

Thanks,
Rahul Kapoor

**Comment by fechanique** [comment]
I think is related to #653

**Comment by mehdicherf** [comment]
I've noticed the same issue, `sfdx force:source:deploy -x` seems to deploy only the first field (or first field per object?) listed in the CustomField type of the package.xml

**Comment by wam-leadclic** [comment]
That's right, the workaround for the moment is including only the CustomObject and not the Child elements.

**Comment by rahulkapoor83** [comment]
@shetzel - Need your inputs here. This is causing issues in our production deployments.

**Comment by shetzel** [comment]
Yes, I'm seeing the same thing.  I'll get a fix asap.  Sorry for the incomplete fix.

**Comment by rahulkapoor83** [comment]
@shetzel - Still with the latest CLI, the issue is not resolved.

**Comment by shetzel** [comment]
Fix will be in the upcoming release this Saturday.

**Comment by girasedinesh** [comment]
Will this fix we released today?

**Comment by mehdicherf** [comment]
@shetzel I can confirm that the issue with fields is gone with the new version (at least I wasn't able to reproduce it when it comes to deploying custom fields). 

However I now face a similar issue with RecordTypes. Could it be the same cause?

**Comment by shetzel** [comment]
@mehdisfdc - I don't see the problem with RecordTypes.  The fix should apply to all child types of CustomObject.  I created 2 record types in an org, pulled them, then made changes and deployed them without a problem.  I also converted them successfully too.
E.g.,
`sfdx force:source:deploy -m RecordType:Schools__c.MyFirstRT,RecordType:Schools__c.MySecondRT`

**Comment by rahulkapoor83** [comment]
@shetzel  Thanks for the fix.
