### ISSUE TITLE
Problem with CSS library components, inconsistent behavior

### ISSUE THREAD

**Issue by KevinGossentCap** [forcedotcom/cli#655]
### Summary

The behavior related to CSS Library components available since Summer20 is inconsistent.
Doing a source:retrieve only retrieves the ".css" file
Doing a source:deploy fails if the css file is not with a ".js-meta.xml" file (surely to at least specify the API version)
Doing a mdapi:convert will produce only the ".css" file which then can't be deployed.

Definitely linked to #563 which is marked as solved in release notes (49.13.0) but ticket still open in issues list

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

### Expected result

needed files are produced for retrieve/pull/convert so that it can be deployed

### Actual result

retrieved/converted component can't be deployed as-is.

### Additional information

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
odaseva-dx 0.0.1 (link) C:\GitRepos\odaseva-dx
salesforcedx 49.13.0 (core)
├─ templates 49.10.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 49.12.1 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.0 (core)
sfdx-cli 7.75.0 (core)

**OS and version**: windows 10 (1903)
node 12.18.4

**Comment by shetzel** [comment]
Thanks @KevinGossentCap.  We'll fix asap.

**Comment by davida-ck** [comment]
Hello @shetzel , will the problem be solved soon?

This impacts all my projects and others have this problem as well (https://github.com/forcedotcom/cli/issues/717)

David

**Comment by Yabe-CK** [comment]
Same for me, this bug is very penalizing and prevents us from working efficiently.

**Comment by shetzel** [comment]
I'm trying to get the fix for this into the next latest-rc. It's very close, and I'll let you know when you can try it in the RC.

Note that "Doing a source:deploy fails if the css file is not with a ".js-meta.xml" file" is expected behavior.  The meta file is required.  The other usecases should definitely work.

**Comment by shetzel** [comment]
The fix for this will be in the release this Thursday.  salesforcedx v50.6.0, sfdx-cli v7.81.0.  You can try it early using the release candidate.  `sfdx plugins:install salesforcedx@latest-rc`

**Comment by davida-ck** [comment]
> The fix for this will be in the release this Thursday. salesforcedx v50.6.0, sfdx-cli v7.81.0. You can try it early using the release candidate. `sfdx plugins:install salesforcedx@latest-rc`

Thank you very much, i will test as soon as it is available

**Comment by shetzel** [comment]
The fix is in CLI v7.81.0 and salesforcedx v50.6.0
