### ISSUE TITLE
SFDX CLI 7.71.0 and higher and multiple package deploys

### ISSUE THREAD

**Issue by jhgihub0** [forcedotcom/cli#657]
We have an issue, which is a continuation of what was mentioned here https://github.com/forcedotcom/cli/issues/379

Our repo has a /sfdx-source/ folder, which contains all the packages to be deployed.  The sfdx-project.json is something like this:

{
    "packageDirectories": [
        {
            "path": "sfdx-source/app-a",
            "default": true,
            "package": "MYAPP-Shared",
            "versionName": "ver 0.1",
            "versionNumber": "0.1.0.NEXT"
        },
        {
            "path": "sfdx-source/app-b",
            "package": "APPB",
            "versionName": "ver 0.1",
            "versionNumber": "0.1.0.NEXT",
            "default": false,
            "dependencies": [
                {
                    "package": "MYAPP-Shared@0.1.0-1"
                }
            ]
        },
        {
            "path": "sfdx-source/app-c",
            "package": "APPC",
            "versionName": "ver 0.1",
            "versionNumber": "0.1.0.NEXT",
            "default": false,
            "dependencies": [
                {
                    "package": "MYAPP-Shared@0.1.0-1"
                }
            ]
        },
        {
            "path": "sfdx-source/app-d",
            "package": "APPD",
            "versionName": "ver 0.1",
            "versionNumber": "0.1.0.NEXT",
            "default": false
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "50.0",
    "packageAliases": {
        "APPB": "0Xo2K000000kf0brBXX",
        "APPC": "0Xo2K000000kf0bwBXX",
        "MYAPP-Shared": "0Xo2K000000kf0c1BXX"
    }
}

With version 7.71.0, my deployment of all 7514 objects runs fine with no issues.

With sfdx-cli/7.74.1 darwin-x64 node-v12.14.1, my deployment works fine, however, instead of deploying all 7514 at once, its splits it into 4 deploys:
- 5221 objects
- 1508 objects
- 725 objects
- 7 objects

With sfdx-cli/7.75.0 darwin-x64 node-v12.14.1, my deployment works fine, however, instead of deploying all 7514 at once, its splits it into 5 deploys:
- 5221 objects
- 1508 objects
- 725 objects
- 7 objects
- 52 objects

How can I go back to the legacy deploy where all 7514 objects gets deployed at once?  Deploying each is a problem, because if one component fails, then we might have some packages deployed, while others are failed.  If any of the packages fails, I don't want any of the packages to be committed.

Thank you.

**Comment by amphro** [comment]
We are likely not going to support the old behavior. The multiple packages deploy mimics how the package install works. Doing one deploy across multiple packages also causes a lot of issues with certain metadata like labels and translations without a lot of additional work on the CLI side (those never really worked even in 7.71.0).

I see you are using packaging so this doesn't really apply, but for people not using packaging, they can just have multiple folders within a single package directory to do one deploy.

> we might have some packages deployed, while others are failed. If any of the packages fails, I don't want any of the packages to be committed

Can you elaborate on that? If `MYAPP-Shared` metadata is installed but then `APPC` package fails, well then you can just deploy `APPC` after the fix that would make the deploys faster. If you have to go back and fix `MYAPP-Shared` then that is the same as just doing it all over again anyways (it will just override the old `MYAPP-Shared`).

**Comment by amphro** [comment]
Closing this for now. If you want to elaborate and fight for it, please feel free to reopen the issue.
