### ISSUE TITLE
SourceDeployCommand return TypeError instead of Missing Metadata File

### ISSUE THREAD

**Issue by alanjaouen** [forcedotcom/cli#658]
### Summary

When using the last version of the cli (sfdx-cli/7.74.1-32db2396ed linux-x64 node-v12.18.3) I have the error 
```
{
  "status": 1,
  "name": "TypeError",
  "message": "Cannot read property 'outboundFiles' of undefined",
  "exitCode": 1,
  "commandName": "SourceDeployCommand",
```
see [sfdx_result.zip](https://github.com/forcedotcom/cli/files/5342012/sfdx_result.zip) for full stack

In the previous version (rollback with `sfdx plugins:install salesforcedx@49.9.2` ), I have this error:
```
{
  "status": 1,
  "name": "Missing Metadata File",
  "message": "Expected metadata file with '-meta.xml' extension at path: /home/runner/work/Salesforce/Salesforce/force-app/main/default/objectTranslations/Quote-en_US/Quote-en_US.objectTranslation-meta.xml",
  "exitCode": 1,
  "commandName": "SourceDeployCommand",
```
see [sfdx_result (2).zip](https://github.com/forcedotcom/cli/files/5342021/sfdx_result.2.zip) for full stack

 **the previous version was very more usefull to debug a deploy.**

### Steps To Reproduce:

Deploy a directory with a missing xml file

### Expected result

A precise error with the path of the expected file

### Actual result

An internal error is throw

**Comment by shetzel** [comment]
Thanks for reporting.  This has been fixed with cli 7.76.1.  Apologies for the regression!
