### ISSUE TITLE
Error Plugin: sfdx-cli retrieve manifest unsuccessful

### ISSUE THREAD

**Issue by murthytumuluri04** [forcedotcom/cli#659]
### Summary

Error Plugin: sfdx-cli retrieve manifest unsuccessful

### Steps To Reproduce:

Click on package.xml and select SFDX:Retrieve Source form Manifest Org

### Expected result

Retrieve Successful. 

### Actual result
`module: @oclif/config@1.17.0
task: runHook postsourceupdate
plugin: sfdx-cli
root: /Users/myname/.local/share/sfdx/client/7.75.0-5521f40d11
See more details with DEBUG=*
13:57:30.412 sfdx force:source:retrieve --manifest /Users/myname/vs code workspace/folername/manifest/package.xml`

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): `sfdx-cli/7.75.0-5521f40d11 darwin-x64 node-v12.18.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
`@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.13.0
├─ custom-metadata 1.0.10
├─ apex 0.1.0
├─ templates 49.10.0
├─ salesforce-alm 49.12.1
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7
sfdx-cli 7.75.0 (core)
sfdx-plugin-prettier 1.0.5`

**OS and version**: `macOS Catalina 10.15.7 (19H2)`

**Comment by clairebianchi** [comment]
@murthytumuluri04 please provide a repo where this issue can be replicated
