### ISSUE TITLE
Internal api's calls timeout parameter

### ISSUE THREAD

**Issue by dieffrei** [forcedotcom/cli#66]
**Is your feature request related to a problem? Please describe.**
Since some network latency on travis-ci our ci pipeline often breaks

**Describe the solution you'd like**
I'd like a way to increase the internal api calls timeout.

**Describe alternatives you've considered**

**Additional context**
Every scratch org creation on our CI pipeline we install around 35 packages, usually at least one fail because network latency:

```Installing package 04t0M : fsl.base
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
ERROR running force:package:install:  getaddrinfo ENOTFOUND page-power-6982-dev-ed.cs88.my.salesforce.com page-power-6982-dev-ed.cs88.my.salesforce.com:443
ERROR running Install:  `sfdx force:package:install --targetusername test-tbeqtkfiomga@example.com --package 04t0M..... --wait 10 --publishwait 10 --noprompt` failed with code 1
```

**Comment by clairebianchi** [comment]
@sfdc-db-gmail, a feature request for the Packaging team
