### ISSUE TITLE
force:source:deploy and force:source:convert commands do not properly manage the wildcard

### ISSUE THREAD

**Issue by aboulika** [forcedotcom/cli#661]
### Summary
When using the **force:source:deploy** or the **force:source:convert** using a manifest which contains wildcard, these commands include metadata which are not listed in the manifest.

Reproduced the issue with at least the following metadata types: **CustomPermission**, **Group**, **Queue**.

It looks like - when using a wildcard - it takes any file which contains the name of the metadata type (more explanations here below).

The same behavior can be observed when using the -m parameter instead of using a manifest with a wildcard.

### Steps To Reproduce:
1.  Create an sfdx project 
1.  Create 2 Apex Classes named **CustomPermissionsReader** and **CustomPermissionsReaderTest**
1.  Create few custom permissions: **FooPermission** and **BarPermission**
1.  Run the following command: `sfdx force:source:convert -m CustomPermission -d ./unpackaged`

### Expected result

In the ./unpackaged folder we should get only the CustomPermission metadata.

### Actual result

The ./unpackaged folder contains all the CustomPermissions, but also includes the Apex Classes **CustomPermissionsReader** and **CustomPermissionsReaderTest**.

The same behavior is also observed with the `force:source:deploy command`.
And it can also be reproduced with other metadata types such as **Group** or **Queue**.

In the result we actually get any metadata which contains the "name of the metadata" in its name.
It can be reproduced with Apex Classes, but also with DelegateGroup and other types of metadata which are neither listed in the manifest passed in parameter of this command.

As long as we pass a manifest containing wildcards using the -x parameter, or using the metadata type in the -m parameter, the same issue is reproduced.

### Additional information

Example of package.xml generated from the `force:source:convert` using the steps described above:
<img width="449" alt="Screenshot 2020-10-08 at 10 30 33" src="https://user-images.githubusercontent.com/12809776/95434268-56e85600-0951-11eb-8bba-fbad5d246798.png">

**SFDX CLI Version**: sfdx-cli/7.74.1-32db2396ed darwin-x64 node-v12.18.3

**SFDX plugin Version**
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.1 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.10.0 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 49.4.4 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ apex 0.0.9 (core)
└─ salesforce-alm 49.11.0 (core)
sfdx-cli 7.74.1 (core)

**OS and version**:
MacOS 10.14.6

**Comment by shetzel** [comment]
The fix for this was supposed to be in last week's release but it slipped through the cracks.  It will be in the next patch release.
