### ISSUE TITLE
source:deploy sfdx@7.75 malfunction 

### ISSUE THREAD

**Issue by kkulig** [forcedotcom/cli#662]
new version of CLI is not taking correctly package. For 190 existing metadata it's taking less than a half of it (around 60)

@7.74.1  - everything is taken and validated
@7.75 - only some subset is taken - hard to tell what exactly.

**Comment by mehdicherf** [comment]
Maybe be related to #654 ?

**Comment by kkulig** [comment]
@mehdisfdc - could be but this is for sure not all. 
Possibly different type than CustomField has the same issue, because when I count entries in package without customFields, the value is still higher than is taken by CLI 7.75

**Comment by shetzel** [comment]
@kkulig - Need more info.  What is the complete command are you running?  What plugins do you have?  (`sfdx plugins --core`). What are the steps to reproduce this?  If you set the `SFDX_MDAPI_TEMP_DIR` environment variable to a directory and inspect the contents after a deploy can you see what's missing?
