### ISSUE TITLE
Error trying to retrieve Source from Manifest

### ISSUE THREAD

**Issue by murthytumuluri04** [forcedotcom/cli#665]
### Summary

When trying to retrieve Source from Manifest with below in VS Code it errors out with below

### Steps To Reproduce:

`sfdx force:mdapi:retrieve --retrievetargetdir /var/folders/xb/h6kpy82n46lc1whxr_xdg4kw0000gn/T/.sfdx/tools/conflicts/myFolder --unpackaged /var/folders/xb/h6kpy82n46lc1whxr_xdg4kw0000gn/T/.sfdx/tools/conflicts/myFolder/package.xml --targetusername murthyDEV`

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

Retrieve Successful

### Actual result

`An error was encountered during conflict detection. ERROR running force:mdapi:retrieve:  Element {http://soap.sforce.com/2006/04/metadata}members invalid at this location in type Package`

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.75.1-5585088c75

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
`@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 50.0.13 (pre-release)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ salesforcedx-templates 49.5.0
├─ apex 0.1.0
├─ custom-metadata 1.0.10
└─ salesforce-alm 50.0.13
sfdx-cli 7.75.1 (core)
sfdx-plugin-prettier 1.0.5`

**OS and version**: MacOS Catalina 10.15.7

**Comment by shetzel** [comment]
Looks like your package.xml isn't schema valid.  I'd inspect it and fix any problems then try again.
