### ISSUE TITLE
accessToken is encrypted on sfdx force:org:list --json, but not on sfdx force:org:display -u ORG_NAME --json

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#666]
### Summary

accessToken is encrypted on `sfdx force:org:list --json`, but not on `sfdx force:org:display -u ORG_NAME --json`

Example:
![image](https://user-images.githubusercontent.com/55927613/95662002-bef29400-0b2b-11eb-81a7-e46648b54c85.png)

### Steps To Reproduce:

1 - Execute `sfdx force:org:display` and check the acccessToken is not encrypted. You can open postman and issue a request with this token.
2 - Execute `sfdx force:org:list`, get the same org from the step 1, and check that the accessToken is encrypted and does not work on any request.

### Expected result

The accessToken should not be encrypted

### Actual result

The accessToken is encrypted when running `sfdx force:org:list` command

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.75.1-5585088c75 win32-x64 node-v12.18.3

OBS: it is not a version issue. I tested on 7.47 and the result is the same.

**OS and version**:  Windows 10

**Comment by mshanemc** [comment]
This **should** be fixed in the new open-source version.  You can try it early, here: https://github.com/forcedotcom/cli/issues/835

**Comment by AllanOricil** [comment]
Yes, I confirm it has been fixed. But I had to install the plugin. It would be good if you could ship this to sfdx that everyone is using.

**Comment by mshanemc** [comment]
That's the plan.  I just want to make sure it's fixing everything we think it is and breaking nothing.

**Comment by AllanOricil** [comment]
@mshanemc good plan! thanks for that

**Comment by mshanemc** [comment]
closing, because `plugin-org` is shipped
