### ISSUE TITLE
Automatically delete scratch orgs that fail to auth

### ISSUE THREAD

**Issue by Brian-Triplett** [forcedotcom/cli#668]
### Summary

Upon creating a scratch org, if the auth fails from the CLI then the scratch org shows up in the Active Scratch Org records in the Dev Hub but not in the `sfdx force:org:list`. 

### Steps To Reproduce:

1.  Create scratch org but trigger a auth failure
1.  The org record will not show locally in the CLI but will in the DevHub in the ActiveScratchOrg records

### Expected result

The scratch org should be deleted on auth failure OR show in the CLI where it will be noticed.

### Actual result

Discrepancies exist between the DevHub and CLI leading to hidden usage of orgs.

### Additional information

See https://trailblazers.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1&fId=0D54S000008fK3N&s1oid=00D4S0000019iJX&s1nid=0DB30000000072L&emkind=chatterCommentNotification&s1uid=0053000000BN9YZ&emtm=1602476442724&fromEmail=1&s1ext=0

**Comment by yippie** [comment]
yes please

**Comment by mshanemc** [comment]
the new `org:scratch:create` includes the ability to resume a scratch org where auth failed.  You can either continue from there, or delete the org, once it's auth'd.

We don't have a good way to delete an org that you're not auth'd to.
