### ISSUE TITLE
filePath = N/A when deploying multiple files (with errors) using source:deploy -p

### ISSUE THREAD

**Issue by gbutt** [forcedotcom/cli#67]
### Summary

_When deploying multiple files with `force:source:deploy` and at least one file has a deploy error, the filePath is N/A in the error results_.

### Steps To Reproduce:

1. Create two apex files (Apex1.cls, Apex2.cls)
1. Change one file (Apex2.cls) so that is will not compile
1. Deploy using force:source:deploy -p Apex1.cls,Apex2.cls --json

### Expected result

_The result filePath should indicate which file has the compile error (Apex2.cls)_.

### Actual result

_filePath is N/A and fullName is missing. There is no indication of which file the error is related to_.

### Additional information

So here's how I'm using sfdx. I have a plugin that finds all changed files via `git status` and deploys them to my org using `sfdx force:source:deploy -p file1,file2,etc --json`. When I deploy a file with a compile error I'd like to know which file has which error so I can fix it quickly. As a workaround, the best I can do is compare a list of all files deployed to those in the result.partialSuccess array and output the complement set. This at least tells me which files I need to check. It would be much better if I knew which error is related to which file.

_Screenshot of JSON when deploying multiple files_.
![image](https://user-images.githubusercontent.com/4119863/54077732-db588b80-4279-11e9-897a-bb7c8f4718cc.png)

The filePath and fullName are available when only a single file is deployed.

_Screenshot of JSON when deploying a single file_.
![image](https://user-images.githubusercontent.com/4119863/54077747-0c38c080-427a-11e9-8cdb-9587ea994033.png)

**SFDX CLI Version**: sfdx-cli/6.56.0 (darwin-x64) node-v11.7.0

**SFDX plugin Version**: salesforcedx 45.5.0 (core)

**OS and version**: OSX Mojave 10.14.3 (18D109)

**Comment by clairebianchi** [comment]
@gbutt can you please upgrade to the most recent version of the CLI? We just updated to V7

**Comment by JSGTrifork** [comment]
@clairebianchi I can confirm that this is still an issue on sfdx-cli/7.93.1-762bca056d linux-x64 node-v14.15.4.

Can we re-open this issue? I've tried the workaround that @gbutt suggests, but it does not seem to do the trick. We have a generated LWC library with 50+ components that we push to Salesforce and debugging errors without filePath, type, columnNumber nor lineNumber is quite a challenge.

```
sfdx force:source:deploy --sourcepath salesforce/main/default/lwc/ --json
{
   "status":1,
   "result":[
      {
         "columnNumber":"0",
         "lineNumber":"0",
         "error":"lightningCommunity__Default is not a flow related target! (0:0)",
         "type":"",
         "filePath":"N/A",
         "problemType":"Error"
      }
   ],
   "name":"DeployFailed",
   "message":"Deploy failed.",
   "exitCode":1,
   "actions":[
      
   ],
   "commandName":"SourceDeployCommand",
   "data":[
      {
         "columnNumber":"0",
         "lineNumber":"0",
         "error":"lightningCommunity__Default is not a flow related target! (0:0)",
         "type":"",
         "filePath":"N/A",
         "problemType":"Error"
      }
   ],
   "stack":"DeployFailed: Deploy failed.\n    at /home/node/.local/share/sfdx/client/7.93.1-762bca056d/node_modules/salesforce-alm/dist/lib/source/sourceApiCommand.js:70:31\n    at async SourceDeployCommand.execLegacyCommand (/home/node/.local/share/sfdx/client/7.93.1-762bca056d/node_modules/salesforce-alm/dist/ToolbeltCommand.js:149:29)\n    at async SourceDeployCommand.run (/home/node/.local/share/sfdx/client/7.93.1-762bca056d/node_modules/salesforce-alm/dist/commands/force/source/deploy.js:32:16)\n    at async SourceDeployCommand._run (/home/node/.local/share/sfdx/client/7.93.1-762bca056d/node_modules/@salesforce/command/lib/sfdxCommand.js:81:40)\n    at async Config.runCommand (/home/node/.local/share/sfdx/client/7.93.1-762bca056d/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/home/node/.local/share/sfdx/client/7.93.1-762bca056d/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/home/node/.local/share/sfdx/client/7.93.1-762bca056d/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/home/node/.local/share/sfdx/client/7.93.1-762bca056d/dist/cli.js:121:21)",
   "warnings":[
      
   ]
}
