### ISSUE TITLE
permset assign doesn't work on aliases despite docs saying it does

### ISSUE THREAD

**Issue by socialsuiteDavid** [forcedotcom/cli#670]
### Summary

According to: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_user.htm
> -o | --onbehalfof ONBEHALFOF
> Comma-separated list of usernames **or aliases** to assign the permission set to.

However this does not work on at least the integration user.

### Steps To Reproduce:

On a new scratchorg an integration user will automatically be created with alias `integ`
1. With a permission set: `MyPermissionSet` available run: `sfdx force:user:permset:assign --permsetname "MyPermissionSet" -o "integ"`

### Expected result

Permission set should be applied to integration user

### Actual result

> Error: The username "integ" was not found for scratch org

### Additional information

works fine if using the full username, though is not useful in my use case.

**SFDX CLI Version**: sfdx-cli/7.75.1-5585088c75 win32-x64 node-v12.18.3

**SFDX plugin Version**:
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/analytics 0.22.0
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.13.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 49.9.1 (core)
├─ custom-metadata 1.0.10 (core)
├─ salesforce-alm 49.12.2 (core)
└─ apex 0.1.1 (core)
sfdx-cli 7.75.1 (core)

**Comment by mshanemc** [comment]
In this context, `alias` does not mean `User.Alias` like https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_user.htm

It means alias like used on [org:create](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_org.htm#cli_reference_force_org_create) or [user:create](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_user.htm)

**Comment by joeythomaschaske** [comment]
I think the docs should be updated as I fell into the same trap
