### ISSUE TITLE
ERROR running force:source:deploy:  Cannot read property 'success' of undefined

### ISSUE THREAD

**Issue by rameshvar-ksolves** [forcedotcom/cli#671]
ERROR running force:source:deploy:  Cannot read property 'success' of undefined
getting the above error while deploying code from VS code to salesforce org.
**SFDX CLI Version**sfdx-cli/7.75.1-5585088c75 linux-x64 node-v12.18.3

**OS and version**: Ubuntu 20.04.1 LTS

**Comment by AndyHaas** [comment]
I am running into the same issue. I have tried different orgs and I have done sfdx update to make sure I was on the latest packages. 
The org I am deploying to is still Summer '20. 

Tests I have ran.
Deploy to Summer '20 get error : Cannot read property 'success' of undefined
Deploy to Winter '21 no error

**Comment by AndyHaas** [comment]
@rameshvar25 what org are you deploying to? Winter '21 or Summer '20?

**Comment by AndyHaas** [comment]
Error Log sfdx force:source:deploy --loglevel TRACE

{"name":"sfdx","hostname":"Haas-Desktop","pid":5576,"log":"SfdxProjectJson","level":40,"msg":"The config file: C:\\Users\\haasa\\.sfdx\\sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2020-10-14T14:41:21.060Z","v":0}
{"name":"sfdx","hostname":"Haas-Desktop","pid":5576,"log":"SfdxProjectJson","level":40,"msg":"The config file: C:\\Users\\haasa\\.sfdx\\sfdx-project.json is not schema valid\nDue to: Validation errors:\nshould have required property 'packageDirectories'","time":"2020-10-14T14:41:21.072Z","v":0}
{"name":"sfdx","hostname":"Haas-Desktop","pid":5576,"log":"SourceDeployCommand","level":50,"msg":"[\n  '\\u001b[1mERROR running force:source:deploy: \\u001b[22m',\n  '\\u001b[31mMissing one of the following parameters: manifest metadata sourcepath validateddeployrequestid\\u001b[39m'\n]","time":"2020-10-14T14:41:21.080Z","v":0}

**Comment by AndyHaas** [comment]
@rameshvar25 
I figured out my issue. My issue was that my username got disabled in the org I was deploying to. I reauth with that org and then I was able to deploy. 

Hope this helps.

**Comment by rameshvar-ksolves** [comment]
@AndyHaas I figured out the issue and fixed that.
actually the issue was due to sfdx plugin, I just updated the CLI and Installed latest  sfdx plugin.
You can use below command to install latest sfdx plugin.
sfdx plugins:install salesforcedx@latest

**Comment by olvina** [comment]
Will vscode update the plugin automatically? Or what are the steps for updating the sfdx plgin?
