### ISSUE TITLE
Open scratch org in any region/pod/datacenter

### ISSUE THREAD

**Issue by sjurgis** [forcedotcom/cli#679]
**Is your feature request related to a problem? Please describe.**
Working in globally distributed team means there are developers scattered all across the world. Right now the scratch orgs open up in same region as your Dev Hub is. That means that for majority of our team we have to work with 200-400ms latency instead of 30. If your app is quite chatty and you've got poor connection it starts to impact ones productivity in orders of 10-20% or more (the silver lining is you catch some performance issues this way tho).
This would be also very useful to test issues when patch releases potentially break something (rare, but nice and easy way to rule it out)

**What are you trying to do**
Open scratch org in region near me (ap9 - Australia).

**Describe the solution you'd like**
CLI option to specify pod, region or pod pool.

Additionally when org is created it should clearly state region/pod and patch version.

**Describe alternatives you've considered**
Occasionally I'll try to create multiple orgs until you hit the release you like. Obvious waste of resources!

**Additional context**
Including Canadas na99, French and German ones would be nice too. Unsure what other pods are out there nowadays (IND1, IND25 and IND35 I'd guess is in India but host doesn't resolve). All I know even dev orgs don't get opened in Australia (I presume AWS cost you more (which is bizarre)).

**Comment by Sheing** [comment]
Upvote!

**Comment by yippie** [comment]
Upvote!!

I am pretty sure this would allow me to work around the issues that some users keep getting liveagent errors when trying to create scratch orgs. I am convinced there is a bad pod out there that has an invalid scratch org template because this comes up every month then goes away but support has been so far un able to track it down.

**Comment by amphro** [comment]
I realize this is a feature so probably not appropriate for a support ticket. It probably belongs in idea exchange, as the signup team uses that mechanism to drive feature requests.
