### ISSUE TITLE
mdapi convert command fails when source has Apex Class

### ISSUE THREAD

**Issue by murthytumuluri04** [forcedotcom/cli#680]
### Summary

mdapi convert command fails when source has Apex Class

### Steps To Reproduce:

1.  Create a new Project with Manifest on VS Code.
1.  Right click on Package.xml and click on Retrieve source from Manifest

### Expected result

Should successfully retrieve and convert

### Actual result

An error was encountered processing path: /var/folders/xb/h6kpy82n46lc1whxr_xdg4kw0000gn/T/.sfdx/tools/conflicts/***/unpackaged/classes/ABC.cls

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): `sfdx-cli/7.74.1-32db2396ed`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) `salesforcedx 50.1.1 (pre-release)`

**OS and version**: Mac Os Catalina

**Comment by shetzel** [comment]
@murthytumuluri04 - I'm not able to reproduce this.  I'm able to run `sfdx force:source:retrieve -x package.xml` and get ApexClasses successfully.  Do you have a repo I can access that reproduces this?  Are there more steps I need to take.  I did this with the latest CLI and plugins, so maybe it was fixed?
