### ISSUE TITLE
[BUG + Feature] Add output errors per record on `sfdx force:bulk:data:upsert -w MINUTES --json` and save in a desired location

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#682]
The output of `sfdx force:bulk:data:upsert -f data.csv -i Id -w 120 --json` does not display errors or the batches Ids. If I just remove `--json` from the command, the output displays every batch(job), with its Id, and what went wrong per record during each batch execution. I don't know if this was WAD or if it is a bug, but it would be good if the results were the same.

Besides that, I think it is a good ideia if we could pass one additional parameter to save the output as a `.json` or `.csv` file. Like, `sfdx force:bulk:data:upsert -f data.csv -i Id -w 120 --json -o errors.csv`. Or if the command could write to `stdout` while we are running it when passing `--json`. Right now if I need to get the errors per record I have to run the command without `--json` to get a result as shown below:

![image](https://user-images.githubusercontent.com/55927613/96375512-52057c80-1171-11eb-959f-5e46bd8907d8.png)

and when I just add `--json`, as I said before, it does not show the errors
![image](https://user-images.githubusercontent.com/55927613/96375529-6d708780-1171-11eb-86a3-ba735d5ba2ab.png)

**Comment by WillieRuemmele** [comment]
Hi @AllanOricil  check out the [announcement](https://github.com/forcedotcom/cli/issues/907) for the new [data](https://github.com/forcedotcom/cli/issues/907) plugin... might've fixed the bug

**Comment by mshanemc** [comment]
I think this is fixed in the new data plugin released 4/1.  If not, re-open or create a new case.
