### ISSUE TITLE
Please add to release notes CLI version like "50.1.1 (October 17, 2020) - CLI 7.76.1"

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/cli#683]
**Is your feature request related to a problem? Please describe.**
When updating sfdx I see version number like 7.76.1, when I am reading changelog I see version number 50.1.1 (October 17, 2020). I am confused because I don't know if it is the same version. 
Additionally there are minor updates of cli that are not mentioned in changelog at all.

**What are you trying to do**
Clearly identify which changes relate to which CLI version.

**Describe the solution you'd like**
I would like to see in changelog description like 50.1.1 (October 17, 2020) - CLI 7.76.1.

**Describe alternatives you've considered**
Alternative is match version number of CLI to 50.x.x schema. As VS Code plugins are already versioned in this way.

**Additional context**
N/A

**Comment by jshackell-sfdc** [comment]
Great idea, thanks!  Let me huddle with the team and pick the best option.

**Comment by jshackell-sfdc** [comment]
We now include the sfdx-cli version with each week's release notes (see [here](https://github.com/forcedotcom/cli/blob/master/releasenotes/README.md#5020-october-22-2020---cli-7771)).  Thx for the suggestion!

**Comment by PawelWozniak** [comment]
Thank you :)
