### ISSUE TITLE
Error message not clear when files are missing - Cannot read property 'success' of undefined

### ISSUE THREAD

**Issue by mattr9124** [forcedotcom/cli#687]
### Summary

This may be a duplicate although I didn't specifically see this case. Running this command fails:

```sfdx force:source:deploy -u SUDEV3 -p force-app/main/default --loglevel=trace --verbose
Using specified username myusername

ERROR running force:source:deploy:  Cannot read property 'success' of undefined
```

I checked sfdx.log, although even at trace level it is unfortunately useless. 

After scratching my head for a while, I decided to try this:
```
sfdx force:source:convert -r force-app/main/default
ERROR running force:source:convert:  Expected file at path: /Users/mrossner/Dev/systemu/deploy/digital-platform-sfcore/force-app/main/default/translations/fr.translation-meta.xml.xml-meta.xml
```

And sure enough I got a more coherent error message. I'm not sure exactly what's missing but I deleted that file just to see if that would fix the issue and it does. Although force:source:deploy should be capable of giving the same error message.

"Cannot read property 'success' of undefined" is a useless generic message, it's the equivalent of someone telling me they got a NullPointerException with no stack trace, I'm completely lost.

### Steps To Reproduce:

If I have some time I can try to make this reproducible with Dreamhouse, although I assume just create an xml file in that location and deploy does not like it.

### Expected result

I should get an error message that actually tells me what went wrong.

### Actual result

I get a useless generic message: ERROR running force:source:deploy:  Cannot read property 'success' of undefined

### Additional information

```sfdx --version
sfdx-cli/7.75.1-5585088c75 darwin-x64 node-v12.18.3```

```sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
b2bcc-sfdx-plugin 0.0.1 (link) /Users/mrossner/Dev/ccrz/B2BCC-SFDX-Plugin
config 1.1.8 (core)
generator 1.1.3 (core)
salesforcedx 49.13.1
├─ templates 49.10.0
├─ custom-metadata 1.0.10
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ apex 0.1.1
└─ salesforce-alm 49.12.2
sfdx-cli 7.75.1 (core)
sfdx-wry-plugin 0.0.11 (link) /Users/mrossner/Dev/sfdx-stuff/sfdx-wry-plugin
```

OS is OSX 10.15.7

**Comment by shetzel** [comment]
This is fixed with the most recent CLI (7.76.1) and salesforcedx plugin (v50.1.1)

**Comment by shetzel** [comment]
run `sfdx plugins:uninstall salesforcedx` then `sfdx update`

**Comment by mattr9124** [comment]
thanks for the quick response. I thought I had already updated, will try that again.
