### ISSUE TITLE
Unable to generate complete code coverage report on unlocked package version

### ISSUE THREAD

**Issue by ar-srinivas** [forcedotcom/cli#688]
### Summary

While creating a unlocked package version we have an option to run code coverage (-c) and the version:report gives the code coverage percentage but not the complete code coverage report by each class level. Is there a way to get the complete code coverage report by each class and test class. 

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Create a unlocked package version giving the code coverage option (-c).
1.  Post version creation, run force:package:version:report to check the code coverage details

### Expected result

Trying a way to get the complete code coverage result

### Actual result

Only code coverage percentage is given on CLI

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):sfdx-cli/7.76.1-f301d5641f win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): @oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-scanner 2.3.0
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 49.9.2 (49.9.2)
├─ templates 49.9.1
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ salesforce-alm 49.10.0
├─ custom-metadata 1.0.10
└─ apex 0.0.9
sfdx-cli 7.76.1 (core)
sfdx-codescan-plugin 1.0.4

**OS and version**: Windows 10

**Comment by mshanemc** [comment]
you'll want to open a case for the packaging team if this is still a problem.

**Comment by shetzel** [comment]
The command now has a `--verbose` flag that shows code coverage details by class.  E.g. `sf package version report -p 04t... --verbose`
