### ISSUE TITLE
Several Settings in orgPreferenceSettings Cause 'ProblemDeployingSettings: Failed to deploy settings to scratch org' Error

### ISSUE THREAD

**Issue by jty-reman** [forcedotcom/cli#69]
### Summary

I have been experimenting with changing from orgPreferences to settings in my Scratch definition file and I have discovered that the presence of any of these options causes an 'ProblemDeployingSettings: Failed to deploy settings to scratch org.' error when creating the scratch org:

"documentContentSearchEnabled": true,
"knowledgeEnabled": true,
"nameSuffixEnabled": true,
"middleNameEnabled": true
"liveAgentEnabled": true,
"chatterProfileEnabled": true

### Steps To Reproduce:

1. Create a scratch-def.json file
2. Add a Settings segement with an orgPreferences segement within it
3. Include any of these options:
- "documentContentSearchEnabled": true,
- "knowledgeEnabled": true,
- "nameSuffixEnabled": true,
- "middleNameEnabled": true
- "liveAgentEnabled": true,
- "chatterProfileEnabled": true
4. issue a force:org:create against the scratch org def

### Expected result

Scratch org is created with those settings applied

### Actual result

Scratch Org Creation doesn't succeed and presents this error:
```
"ProblemDeployingSettings: Failed to deploy settings to scratch org.\n    at ALMError (C:\\Users\\jyoung\\AppData\\Local\\sfdx\\client\\7.1.4-79f97a7df8\\node_modules\\salesforce-alm\\dist\\lib\\core\\almError.js:44:19)\n    at settings.createDep
loyDir.then.catch.err (C:\\Users\\jyoung\\AppData\\Local\\sfdx\\client\\7.1.4-79f97a7df8\\node_modules\\salesforce-alm\\dist\\lib\\core\\scratchOrgApi.js:772:37)\nOuter stack:\n    at Function.wrap (C:\\Users\\jyoung\\AppData\\Local\\sfdx\\client\\7.1.4-79f97
a7df8\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:151:27)\n    at OrgCreateCommand.catch (C:\\Users\\jyoung\\AppData\\Local\\sfdx\\client\\7.1.4-79f97a7df8\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:216:46)"
```
### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.1.4-79f97a7df8 win32-x64 node-v10.15.3

**OS and version**: 
WIndows 10 Pro
Version	10.0.17134 Build 17134

**Comment by clairebianchi** [comment]
@kfidelak94 can you please take a look at this? Looks like an issue with Settings.

**Comment by kfidelak94** [comment]
@jty-reman I wanted to check to see if was still a problem for you?  I can't see your whole scratch definition file above, but from what you listed it looks like the syntax you were using was not correct.  
This document has more information on using settings in the scratch def, and an example:  https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file_config_values.htm

For a few of the ones you were trying to use, they'd look like the following:

"settings": {
      "knowledgeSettings": {
          "enableKnowledge": true
      },
     "nameSettings": {
          "enableNameSuffix": true
    },

Also, in the latest build of the CLI, when you create a scratch org with a Scratch Definition file that uses the older "orgPreferences" syntax, it will provide a conversion helper for you to convert your scratch def file to use the newer "settings" syntax.

**Comment by amilagm** [comment]
If someone is looking into enabling quote via the scratch org def this is how it should look like. Unfortunately the documentation is not clear or accurate on this.


```
  "settings": {    
     ...
    "quoteSettings":{
      "enableQuote": true
    }
  }
```

**Comment by bkwdesign** [comment]
Aren't we supposed to be able to see a "sample scratch definition" from the [MetaData Coverage report](https://developer.salesforce.com/docs/metadata-coverage/44)? 

I found this screenshot featured on this [developer.salesforce.com](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file_config_values.htm) page explaining how to switch from `orgPreferences` to `settings`

![Sample Scratch Definition screenshot from the Metadata Coverage Report](https://developer.salesforce.com/docs/resources/img/en-us/220.0?doc_id=dev_guides%2Fsfdx_dev%2Fscratch_orgs%2Fimages%2Fmetadata_cov_report.png&folder=sfdx_dev)

However I am not finding any such samples when I click on the various Metadata Types.. they all come back with a minimal piece of JSON or none at all. Not like the screenshot above.

This comment has also been posed as a question on stackexchange [here](https://salesforce.stackexchange.com/questions/271614/is-the-metadata-coverage-report-broken-sample-scratch-definitions-for-each-type)

**Comment by bkwdesign** [comment]
> 
> 
> If someone is looking into enabling quote via the scratch org def this is how it should look like. Unfortunately the documentation is not clear or accurate on this.
> 
> ```
>   "settings": {    
>      ...
>     "quoteSettings":{
>       "enableQuote": true
>     }
>   }
> ```

I'm finding the documentation to be quite terrible at the moment. Unlike other experiences I've had in SalesForce
