### ISSUE TITLE
.forceignore stopped working after update to 50.1.1

### ISSUE THREAD

**Issue by Szandor72** [forcedotcom/cli#690]
### Summary

Since my update to latest CLI version, .forceignore stopped working. No entries are respected. I need to manually delete or move files. 

### Steps To Reproduce:

Example (redacted) of my .forceignore

```

#LWC VSCODE SETTINGS 
**/jsconfig.json

**/.eslintrc.json

# LWC Jest
**/__tests__/**

```

### Expected result

no deployment issues, all files in .forceignore will be ignored without any changes to .forceignore

### Actual result

```

Successfully created scratch org: 00D3E0000005DRbUAM, username: test-XXXXXXX@example.com
push source
ERROR running force:source:push:  Unexpected file found in package directory: C:\Users\szand\...\DXProject\main\default\lwc\jsconfig.json

```

### Additional information

sfdx-cli/7.76.1-f301d5641f win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

```
@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.5.1
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-scanner 2.3.0
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
appero 0.0.0 (link) C:\Users\szand\Onedrive\dev\appero-dx-plugin
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 50.1.1 (core)
├─ apex 0.1.1 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.1.1 (core)
└─ custom-metadata 1.0.10 (core)
sfdx-cli 7.76.1 (core)
sfdx-migration-automatic 2.0.1
shane-sfdx-plugins 4.41.2
├─ @mshanemc/plugin-streaming 1.1.7
└─ @mshanemc/sfdx-sosl 1.1.0
texei-sfdx-plugin 1.9.0
```

**OS and version**:
Win 10;  Version	10.0.18363 Build 18363

**Comment by jclark-dot-org** [comment]
Seeing same bug with explicit full path; e.g., `force-app/main/default/lwc/jsconfig.json`

**Comment by shetzel** [comment]
Multiple people are trying to reproduce this on the team without success.  Any additional details that could help us repro this would be greatly appreciated.

**Comment by Szandor72** [comment]
What other information can I provide?

Best I can think of right now is offering a screen share

**Comment by jclark-dot-org** [comment]
Was helping a Windows co-worker troubleshoot; we rolled back to plugin 49.13.1 and the issue went away.  He had previously updated from command line (sfdx update).

**Comment by shetzel** [comment]
Does the problem reproduce for you with another project, for example [ebikes-lwc](https://github.com/trailheadapps/ebikes-lwc)?  Is this only seen on Windows?  @jclark-dot-org - that path looks *nix so are you seeing this on Mac or Linux too or just Windows?  Does the project have multiple package directories?  Does the forceignore file have the new `# .forceignore v2` added to the top?  Does the problem reproduce with just those entries in the forceignore @Szandor72 ?

**Comment by shetzel** [comment]
Are there multiple `.forceignore` files in your projects, or maybe within a parent or child directory that it could possibly be finding/using instead?

**Comment by Szandor72** [comment]
Here's what I found out using
- a new project
- latest CLI
- PowerShell / Win 10 
- adding one single line to `.forceignore`
- no v2 added anywhere

the following `.forceignore` works for me

```
# List files or directories below to ignore them when running force:source:push, force:source:pull, and force:source:status
# More information: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm
#

force-app/main/default/classes

package.xml

# LWC configuration files
**/jsconfig.json
**/.eslintrc.json

# LWC Jest
**/__tests__/**
```

this one doesn't work => please notice trailing slash after `classes`

```
# List files or directories below to ignore them when running force:source:push, force:source:pull, and force:source:status
# More information: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm
#

force-app/main/default/classes/

package.xml

# LWC configuration files
**/jsconfig.json
**/.eslintrc.json

# LWC Jest
**/__tests__/**
```

Calling it a night, thanks everyone.

**Comment by jclark-dot-org** [comment]
@shetzel to answer your questions:

- we have both windows and mac (unix) devs on the project, so we use the unix path convention, which has always worked correctly on both platforms.  This problem was encountered on Windows.  I'm on a Mac but haven't updated to 50.1.1 yet.
- Project does not have multiple package directories
- we are not using `#forceignore v2`.  Do you have a doclink?  I saw the note in the 50.1.1 release notes about the switch to .gitignore rules, but it doesn't mention "v2".  Also, we did not see any warnings from the source commands about rule format.
- there is only one .forceignore in the project

Also, after seeing @Szandor72 's comments I checked our .forceignore; we have no paths with trailing slashes.

User in question reverted to 49.13.1, resolving issue.

**Comment by jshackell-sfdc** [comment]
Re: the header:  I neglected to include info about the .forceignore header in last week's rel notes.  I added a clarification this week: https://github.com/forcedotcom/cli/blob/master/releasenotes/README.md#5020-october-22-2020---cli-7771.  Sorry for the confusion.

**Comment by Thieveryshoe** [comment]
I'm having the same issue.  With a standard, unaltered forceignore file, I receive the warning message, but `sfdx force:source:retrieve --manifest c:\Projects\dev\manifest\package.xml` does succeed.

However, when I add `# .forceignore v2` as the first line of the forceignore file, I receive the following and the command fails.
```
(node:4128) Warning: The .forceignore file doesn't adhere to .gitignore format which will be the default behavior starting in Spring '21 release. More information on .gitignore format here: https://git-scm.com/docs/gitignore. Fix the following lines in your .forceignore and add '# .forceignore v2' to your .forceignore file to switch to the new behavior.
(node:4128) Warning: 	**\.*
ERROR running force:source:retrieve:  Unexpected file found in package directory: c:\Projects\dev\force-app\main\default\lwc\jsconfig.json
09:12:27.53 sfdx force:source:retrieve --manifest c:\Projects\dev\manifest\package.xml
 ended with exit code 1
```

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
auth 1.3.2 (core)
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 50.2.0 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.2.0 (core)
└─ apex 0.1.1 (core)
sfdx-cli 7.77.0 (core)
```

**OS and version:**
Win 10 Pro; Version 1909 Build 18363.720

**Comment by shetzel** [comment]
I think there are multiple issues going on.  We are making some changes to the source-deploy-retrieve library that should fix most of them.  However, it appears that some installations have completely up to date plugins while the referenced libraries are out of date.

Can those on this thread respond with the values of `version` and `dependencies.@salesforce/source-deploy-retrieve` from this file: `C:\Users\<username>\AppData\Local\sfdx\node_modules\salesforce-alm\package.json`
And the value of `version` from this file: `C:\Users\<username>\AppData\Local\sfdx\node_modules\@salesforce\source-deploy-retrieve\package.json`

Those are the file locations for a Windows installer default installation.  They could be other places if you changed the location or installed via npm.

Also verify a CLI version of 7.76.1 or greater and salesforcedx plugin version of 50.1.1 or greater.

**Comment by Thieveryshoe** [comment]
**.\salesforce-alm\package.json**
`"version": "50.2.0"`
`"@oclif/plugin-help": "^2.2.3",` 

**.\source-deploy-retrieve\package.json**
`"version": "1.1.7",`

**CLI Version:**
`-- sfdx-cli@7.77.0`
**Plugin Version:**
`salesforcedx 50.2.0 (core)`

**Comment by Szandor72** [comment]
Excuse my confusion:

I couldn't locate the files at the mentioned location:
In `C:\Users\<username>\AppData\Local\sfdx\node_modules\` there's neither `@salesforce/source-deploy-retrieve` nor `salesforce-arm` 


I found the files in `C:\Users\<username>\AppData\Local\sfdx\client\7.76.1-f301d5641f\node_modules`

**.\salesforce-alm\package.json**
```
"version": "50.1.1"
"dependencies": {
    "@oclif/config": "^1.14.0",
    "@oclif/errors": "^1.2.2",
    "@oclif/plugin-help": "^2.2.3",
    "@salesforce/command": "^3.0.1",
    "@salesforce/core": "^2.13.0",
    "@salesforce/kit": "^1.3.2",
    "@salesforce/plugin-analytics": "^1.12.0",
    "@salesforce/source-deploy-retrieve": "^1.0.18",
    "@salesforce/ts-types": "~1.2.1",
    "adm-zip": "^0.4.13",
    "ansi-styles": "^3.2.1",
    "antlr4": "^4.7.2",
    "archiver": "^1.0.1",
    "bluebird": "^3.5.5",
    "bunyan-sfdx-no-dtrace": "^1.8.2",
    "chalk": "^2.4.2",
    "cli-ux": "^5.4.4",
    "csv-parse": "^4.6.5",
    "debug": "^3.2.6",
    "fast-xml-parser": "^3.17.4",
    "fs-extra": "^4.0.3",
    "gitignore-parser": "^0.0.2",
    "glob": "^7.1.6",
    "heroku-cli-util": "^8.0.12",
    "js2xmlparser": "^3.0.0",
    "jsen": "^0.6.6",
    "jsforce": "^1.9.3",
    "jsonwebtoken": "^8.5.1",
    "klaw": "^2.1.1",
    "lodash": "^4.17.19",
    "mime": "^1.6.0",
    "mkdirp": "^0.5.1",
    "moment": "^2.24.0",
    "open": "^7.2.0",
    "optional-js": "^1.3.1",
    "readline-sync": "^1.4.9",
    "replace": "^1.1.0",
    "request": "^2.88.0",
    "request-promise-native": "^1.0.5",
    "sfdx-faye": "^1.0.9",
    "strip-ansi": "^5.2.0",
    "xml2js": "0.4.19",
    "xmldom-sfdx-encoding": "^0.1.30"
  },

```

**.\source-deploy-retrieve\package.json**
`"version": "1.1.6"`

**CLI Version:**
```
sfdx-cli/7.76.1-f301d5641f win32-x64 node-v12.18.3
├─ salesforce-alm 50.1.1 (core)
```

**Comment by ruwanthalk** [comment]
.\salesforce-alm\package.json
"version": "50.1.1"

.\source-deploy-retrieve\package.json
"version": "1.1.6",

The issue still exists and cannot create new projects

**Comment by NataGonzalez** [comment]
Hi all,
I am also being affected by this issue. None of the mentioned solutions on this thread is working for me. =(
Regards, Natalia

**Comment by vladegikyan** [comment]
Hi, I am also affected with the issue.
I cannot perform **sfdx force:source:retrieve** command

UPD:
Downgrading to **salesforcedx@49.13.1** actually helped

**Comment by johasaa** [comment]
> Here's what I found out using
> 
> * a new project
> * latest CLI
> * PowerShell / Win 10
> * adding one single line to `.forceignore`
> * no v2 added anywhere
> 
> the following `.forceignore` works for me
> 
> ```
> # List files or directories below to ignore them when running force:source:push, force:source:pull, and force:source:status
> # More information: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm
> #
> 
> force-app/main/default/classes
> 
> package.xml
> 
> # LWC configuration files
> **/jsconfig.json
> **/.eslintrc.json
> 
> # LWC Jest
> **/__tests__/**
> ```
> 
> this one doesn't work => please notice trailing slash after `classes`
> 
> ```
> # List files or directories below to ignore them when running force:source:push, force:source:pull, and force:source:status
> # More information: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm
> #
> 
> force-app/main/default/classes/
> 
> package.xml
> 
> # LWC configuration files
> **/jsconfig.json
> **/.eslintrc.json
> 
> # LWC Jest
> **/__tests__/**
> ```
> 
> Calling it a night, thanks everyone.

I did the same now after experiencing the same fault and that did the trick removing all ending '/' in the file for folders to ignore. Suddenly all worked again.

**Comment by shetzel** [comment]
An update to salesforcedx latest-rc made today should hopefully fix these issues.  This will become the default core version shipped with the CLI release planned for this Thursday.
You can try the fixes made in the latest-rc by:
`sfdx plugins:install salesforcedx@latest-rc`

**Comment by cloudpremise** [comment]
I just tested against the RC and it seems to have fixed my issue.

Here is my config:

Windows 7

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 50.3.1 (latest-rc)
├─ salesforce-alm 50.3.1
├─ templates 50.1.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ custom-metadata 1.0.10
└─ apex 0.1.2
sfdmu 3.7.4 (link) D:\Data\repos\SFDX-Data-Move-Utility
sfdx-cli 7.77.0 (core)

**Comment by NataGonzalez** [comment]
Thanks everyone. Running the following command resolved the issue for me too :
`sfdx plugins:install salesforcedx@latest-rc`

**Comment by Nidasfcloudy** [comment]
Thanks All,

Running this command worked for me as well.
sfdx plugins:install salesforcedx@latest-rc

**Comment by amphro** [comment]
This should now be released under `latest`. Thanks to everyone for verifying `latest-rc` fixed the issue.

**Comment by cloudpremise** [comment]
This is broken again....
sfdx-cli/7.81.0-7b953c80d1 win32-x64 node-v12.18.3

I had to manually delete the jsconfig.json file to get my repo to push.  This is happening on Windows and Mac environments.  I tried updateing to @latest-rc but was already on the same version.

**Comment by shetzel** [comment]
@cloudpremise - are you on the core plugins?  I.e., `sfdx plugins --core` reports salesforcedx (core).  If not, `sfdx plugins:uninstall salesforcedx` to get back on the core version.

**Comment by jclark-dot-org** [comment]
@shetzel  I'm seeing the same thing reported by @cloudpremise (on mac).  I'm getting "Unexpected file found in package directory" for the lwc/jsconfig.json file.  Switching to `salesforcedx@49.13.1` fixes it, as does removing the json file.  I switched back to `salesforcedx@latest` without luck.  I tried your instructions for uninstalling the `salesforcedx` plugin; reinstalling (`sfdx plugins:install salesforcedx`, no decorator) puts me back at 50.7.1, but does not report `(core)`:
```
> $ sfdx plugins --core                                                                                                
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.1
├─ schema 1.0.1
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ templates 50.1.0
├─ custom-metadata 1.0.10
├─ salesforce-alm 50.7.1
└─ apex 0.1.4
sfdx-cli 7.81.0 (core)
sfpowerkit 2.4.10
```

`sfdx --version` reports:
```
sfdx-cli/7.81.0-7b953c80d1 darwin-x64 node-v12.18.3
```

**Comment by shetzel** [comment]
@jclark-dot-org - you don't need to reinstall salesforcedx.  It's a core plugin that is bundled with the CLI install.  If you specifically install salesforcedx, even the same version as the core version, it will not output `(core)` next to it.  That said, you're still on a version that should not have the forceignore problem.  I would make sure your forceignore file has the entry to exclude the jsconfig.json file and ensure the version of the source-deploy-retrieve library (mentioned in posts above).

**Comment by banderson5144** [comment]
I am trying to use this pattern:

`force-app/main/default/objects/Namespace__Object__c/fields/Namespace__*`

However when I run this command:

`sfdx force:source:retrieve --sourcepath c:\project\force-app\main\default\objects\Namespace__Object__c`

It returns all the fields even if they contain `Namespace__`

I am running a Windows machine using the following plugin versions:

```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.4.0 (core)
config 1.2.1 (core)
evergreen 0.32.1
└─ evergreen-build 0.20.2
generator 1.1.3 (core)
salesforcedx 50.7.1 (core)
├─ schema 1.0.1 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.7.1 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdmu 3.7.17
sfdx-cli 7.82.1-0 (core)
```

**Comment by cloudpremise** [comment]
@shetzel I just checked and was still on latest-rc

salesforcedx 50.7.0 (latest-rc)
├─ schema 1.0.1
├─ templates 50.1.0
├─ apex 0.1.4
├─ custom-metadata 1.0.10
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
└─ salesforce-alm 50.7.0

I then ran
`sfdx plugins:uninstall salesforcedx
sfdx update`
 
which now reports core versions
salesforcedx 50.7.0 (core)
├─ schema 1.0.1 (core)
├─ salesforce-alm 50.7.0 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ apex 0.1.4 (core)
└─ custom-metadata 1.0.10 (core)

However the problem still exists when i run
`sfdx force:source:push -f`
ERROR running force:source:push:  Unexpected file found in package directory: D:\Data\repos\cloudpremise-sfdx\force-app\main\default\lwc\jsconfig.json

I have verified that my force ignore looks good:
**/jsconfig.json

I also added a secondary forceignore entry:
force-app/main/default/lwc/jsconfig.json

I am unable to push until i manually delete the file.

**Comment by shetzel** [comment]
For those still seeing an issue, please see my Oct 23rd comment and check the dependency file versions.  Run commands appending `--dev-debug` to see debug output that might provide some insights and see stack traces.  Without a reproducer for us we need more information, especially if you are using the latest core plugins.

**Comment by mattkipe** [comment]
@shetzel 

I'm experiencing this issue and I believe that I have recent versions based on your Oct 23rd comment, here's the portion of the debug, I can provide all if needed.

sfdx:SfdxProjectJson TRACE Setup child 'SchemaValidator' logger instance +2ms
  sfdx:SchemaValidator DEBUG Schema loaded for C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@salesforce\schemas\sfdx-project.schema.json +10ms
ERROR running force:source:pull:  Unexpected file found in package directory: C:\Users\someuser\Documents\DxProjects\DRS\ges-esr-request\force-app\main\default\lwc\jsconfig.json
*** Internal Diagnostic ***

UnexpectedFileFound: Unexpected file found in package directory: C:\Users\someuser\Documents\DxProjects\DRS\ges-esr-request\force-app\main\default\lwc\jsconfig.json
    at Workspace.isValidSourcePath (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\lib\source\workspace.js:171:35)
    at SourcePathStatusManager.getNewPathInfos (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\lib\source\sourcePathStatusManager.js:409:28)
    at async SourcePathStatusManager.processChangedDirectory (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\lib\source\sourcePathStatusManager.js:395:31)
    at async SourcePathStatusManager.getSourcePathInfos (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\lib\source\sourcePathStatusManager.js:227:43)
    at async SourceWorkspaceAdapter.init (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\lib\source\sourceWorkspaceAdapter.js:76:31)
    at async Function.create (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@salesforce\kit\lib\creatable.js:31:9)
    at async MdapiPullApi.init (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\lib\source\sourcePullApi.js:55:24)
    at async Function.create (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@salesforce\kit\lib\creatable.js:31:9)
    at async SourcePullCommand.execLegacyCommand (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\ToolbeltCommand.js:149:29)
    at async SourcePullCommand._run (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@salesforce\command\lib\sfdxCommand.js:93:40)
    at async Config.runCommand (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@oclif\command\lib\command.js:43:20)
    at async Object.run (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\dist\cli.js:32:20)
Outer stack:
    at Function.wrap (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\node_modules\@salesforce\core\lib\sfdxError.js:171:27)
    at SourcePullCommand.catch (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\ToolbeltCommand.js:248:46)
    at async SourcePullCommand._run (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@salesforce\command\lib\sfdxCommand.js:97:13)
    at async Config.runCommand (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@oclif\config\lib\config.js:173:24)
    at async Main.run (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@oclif\command\lib\main.js:27:9)
    at async Main._run (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\@oclif\command\lib\command.js:43:20)
    at async Object.run (C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\dist\cli.js:32:20)
******

  sfdx:SourcePullCommand ERROR [
  sfdx:SourcePullCommand   '\u001b[1mERROR running force:source:pull: \u001b[22m',
  sfdx:SourcePullCommand   '\u001b[31mUnexpected file found in package directory: C:\\Users\\someuser\\Documents\\DxProjects\\DRS\\ges-esr-request\\force-app\\main\\default\\lwc\\jsconfig.json\u001b[39m',
  sfdx:SourcePullCommand   '\u001b[31m\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m*** Internal Diagnostic ***\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31mUnexpectedFileFound: Unexpected file found in package directory: C:\\Users\\someuser\\Documents\\DxProjects\\DRS\\ges-esr-request\\force-app\\main\\default\\lwc\\jsconfig.json\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at Workspace.isValidSourcePath (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\salesforce-alm\\dist\\lib\\source\\workspace.js:171:35)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at SourcePathStatusManager.getNewPathInfos (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePathStatusManager.js:409:28)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async SourcePathStatusManager.processChangedDirectory (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePathStatusManager.js:395:31)\u001b[39m\n'
+
  sfdx:SourcePullCommand     '\u001b[31m    at async SourcePathStatusManager.getSourcePathInfos (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePathStatusManager.js:227:43)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async SourceWorkspaceAdapter.init (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceWorkspaceAdapter.js:76:31)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Function.create (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@salesforce\\kit\\lib\\creatable.js:31:9)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async MdapiPullApi.init (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePullApi.js:55:24)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Function.create (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@salesforce\\kit\\lib\\creatable.js:31:9)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async SourcePullCommand.execLegacyCommand (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:149:29)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async SourcePullCommand._run (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:93:40)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Config.runCommand (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Main.run (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Main._run (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Object.run (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\dist\\cli.js:32:20)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31mOuter stack:\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at Function.wrap (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\salesforce-alm\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at SourcePullCommand.catch (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:248:46)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async SourcePullCommand._run (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:97:13)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Config.runCommand (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Main.run (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Main._run (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m    at async Object.run (C:\\Users\\someuser\\AppData\\Local\\sfdx\\client\\7.82.0-3d0c527ac6\\dist\\cli.js:32:20)\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m******\u001b[39m\n' +
  sfdx:SourcePullCommand     '\u001b[31m\u001b[39m'
  sfdx:SourcePullCommand ] +1s

-----------------------------

I've tried adding the jsconfig.json to my .forceignore file in multiple ways.
\force-app\main\default\lwc\jsconfig.json
**/jsconfig.json

**Comment by shetzel** [comment]
@mattkipe - Sorry this is causing a problem.  My guess is it's still version and dependency issues but let's debug a bit.

Can you open this file:
C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\package.json
Let me know the version property value.  Then look for the `@salesforce/source-deploy-retrieve` dependency and let me know the version.

Then open this file:
C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\node_modules\@salesforce\source-deploy-retrieve\package.json
Let me know the version property value.

If you want to debug the code a bit you'll want to open this file:
C:\Users\someuser\AppData\Local\sfdx\client\7.82.0-3d0c527ac6\node_modules\salesforce-alm\dist\lib\source\workspace.js
Then add some `console.log` lines in the `isValidSourcePath` function around line 171.
E.g., log the value of `sourcePath` and `isValid` return value from line 164.  The `isValid` value should be false for jsconfig.json, meaning the forceignore file should prevent it from being included.  Add other log lines as needed to find out why it's throwing that error.
