### ISSUE TITLE
mdapi:deploy vs ant cli

### ISSUE THREAD

**Issue by Kevmo92** [forcedotcom/cli#696]
### Summary

I'm noticing a difference when deploying fields and labels that extend a dependent package's custom object with sfdx force:mdapi:deploy commands and ant cli based commands.

For example, in PackageB I have fields and labels that extend PackageA__Custom.object. When deploying with mdapi:deploy I get an error on the deployment mentioning that I `Cannot add component of type:CustomObject named:PackageA__Custom__c subjectId:someId to another package because it is an installed component.`. However when I deploy the same directory with the ant cli the deployment goes through. 

Is there any documentation explaining the differences between the sfdx force:mdapi:deploy command and deploying with the ant salesforce.jar?

**Comment by mshanemc** [comment]
There should be no differences (it's the same api underneath).

Can you put together a more in-depth repro (looks like you've got namespaced packages there, etc) so we can figure out why it's doing that?
