### ISSUE TITLE
sfdx:force:package:installed:list is throwing TIMEOUT Error

### ISSUE THREAD

**Issue by vmamidala-conga** [forcedotcom/cli#697]
### Summary

force:package:installed:list command is throwing time out error as Your query request was running for too long.

### Steps To Reproduce:

1.  ScratchOrg is created
2. Installed two packages with packageID onScratchORg
3.  To display list of installed packages on the ScratchOrg, the list of installed packages with sfdx:force:package:installed:list -u "Orgname" 

### Expected result

List of installed packages should be displayed

### Actual result

Showing error as 'Your query request was running for too long.'

### Additional information

This command was working until Oct 18th, 2020. I found the errors in the pipeline since Oct 19th in all SFDX pipeline scripts.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

7.62.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
7.62.1

**OS and version**:
Ubuntu 2016

**Comment by ImJohnMDaniel** [comment]
I am seeing the same thing.

**Comment by yippie** [comment]
We hit this ALLL the time when using Salesforce-alm module directly. The timeout is really bad.

**Comment by vmamidala-conga** [comment]
Created a support ticket - https://help.salesforce.com/mysuccesshub?id=supportCases&caseId=5003y00000tqhTOAAY
Reported bug - https://trailblazer.salesforce.com/issues_view?id=a1p4V0000003wa2QAA

**Comment by ImJohnMDaniel** [comment]
@clairebianchi and @amphro  -- Any update from the other team on this issue?  I am hitting this issue multiple times a day.

**Comment by shetzel** [comment]
Not reproducible with the latest CLI and packaging plugin.
