### ISSUE TITLE
Include @sa11y/jest setup in sfdx force:project:create command

### ISSUE THREAD

**Issue by albarivas** [forcedotcom/cli#699]
This is an idea to encourage developers to write accessibility unis tests and thus comply with the accessibility best practices that sa11y is able to detect. We could include @sa11y/jest (https://github.com/salesforce/sa11y/tree/master/packages/jest) as a dependency in package.json and also create the needed config files for its initial setup when using the Salesforce CLI command that creates the basic structure of a project.

Find an example of what needs to be included here:

https://github.com/trailheadapps/visualforce-to-lwc/blob/master/package.json
https://github.com/trailheadapps/visualforce-to-lwc/blob/master/jest.config.js
https://github.com/trailheadapps/visualforce-to-lwc/blob/master/jest-sa11y-setup.js

**Comment by amphro** [comment]
The code for `project:create` lives at https://github.com/forcedotcom/salesforcedx-templates 

I'll let @lcampos and @ntotten - thoughts?

**Comment by lcampos** [comment]
That's a good idea, how stable is that library and who is maintaining it ? Is it a side project or is there an actual team at Salesforce who owns it ?

**Comment by mohanraj-r** [comment]
Thanks @amphro @lcampos 

The `@sa11y/jest` library has been out for about 6 months. It is being used by many teams in Salesforce. The API is pretty stable - we don't expect it to change significantly in the near future (even if it does in the far future it would follow semantic versioning).
It is backed by the accessibility team at Salesforce (I am currently the primary developer working on it).

**Comment by mshanemc** [comment]
Closing the issue here.  Further discussion/PRs belong at https://github.com/forcedotcom/salesforcedx-templates
