### ISSUE TITLE
Metadata retrieve should warn about components that were not retrieved

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/cli#7]
**Is your feature request related to a problem? Please describe.**
When I execute a `mdapi:retrieve` command for single package and unpackaged with a `package.xml` file that specifies a metadata component that does not exist in my org, I get no warnings.

I use the following command for retrieve:

```
$ sfdx force:mdapi:retrieve \
  --verbose \
  --singlepackage \
  --unpackaged package.xml \
  --retrieve retrieved \
  --wait -1 \
  --loglevel warn \
  -u alan
```
With the `--verbose` flag I see a list of all components retrieved but it does not display any warnings about components that were not retrieved.

**What are you trying to do**
I would like to see a warning for any components that were not retreived, so that I can fix my `package.xml` file, if there is a typo, or create the component in my org, if it is missing.

**Describe the solution you'd like**
`mdapi:retrieve` should display warnings when components specified in `package.xml` were not retrieved from the org.

**Describe alternatives you've considered**
When using Ant Migration Tool, to retreive the same `package.xml` I will get warnings displayed in the output:

```
[sf:retrieve] Retrieve warnings (1):
[sf:retrieve] package.xml - Entity of type 'ApexClass' named 'FooBar' cannot be found
```

**Comment by clairebianchi** [comment]
@alan-morey, Thank you for the Feedback. 
FYI: @kfidelak94

**Comment by kfidelak94** [comment]
Thanks @alan-morey, This is good feedback; I've filed W-5845095 to track this internally.

**Comment by alan-morey** [comment]
@clairebianchi Is this fixed? Or just closed because it is being tracked internally?

It would be nice if issues closed in GitHub could reference the fix version where applicable :)
