### ISSUE TITLE
force:org:delete not deleting sandboxes

### ISSUE THREAD

**Issue by 13rettles** [forcedotcom/cli#701]
### Summary

Deleting a developer sandbox via SFDX reports success but the sandbox is never deleted.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Authenticate to production instance
1.  Authenticate to sandbox to delete (alias: SANDBOX)
1. sfdx force:org:delete -u SANDBOX -p

### Expected result

The CLI reports: "Successfully deleted sandbox org SANDBOX." and the sandbox is deleted from Sandboxes list in production.

### Actual result

The CLI reports: "Successfully deleted scratch org SANDBOX." and the sandbox is never deleted from Sandboxes list in production.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.72.0-697e9faee2 linux-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.1.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.0 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.2.1 (core)
analytics 1.12.0 (core)
config 1.1.6 (core)
generator 1.1.3 (core)
salesforcedx 49.8.0 (core)
├─ salesforce-alm 49.8.0 (core)
├─ templates 49.4.4 (core)
├─ custom-metadata 1.0.8 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.72.0 (core)

**OS and version**:
Ubuntu 18.04.5 LTS

**Comment by 13rettles** [comment]
I did update to 7.77.0-112dd7d412 and am still seeing the same issue.

**Comment by Dane86NN** [comment]
I'm seeing the same issue in with our sandboxes. CLI is on the latest version. Our pipeline reports succesful deleted scratchorg (which is actually a developer sandbox):

sfdx force:org:delete -u cicd@nn.nl.PBKW01234 -p
Successfully deleted scratch org cicd@nn.nl.PBKW01234.
Finishing: Delete Sandbox

This is preventing our developers to clean up their development sandboxes. We work with a sandbox per feature model and the limit is 100, therefore the feature is very useful to us. Not every developer is allowed to manage sandboxes in DevHub. Our CICD pipeline does this for them

**Comment by MarcDBehr** [comment]
Getting this today on **sfdx-cli/7.89.2 darwin-x64 node-v12.18.3** for a sandbox that has a status of 'Unknown'

sfdx plugins --core shows:

@dx-cli-toolbox/sfdx-toolbox-package-utils 0.3.3
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.7 (core)
auth 1.4.9 (core)
bbdoc 3.4.6
config 1.2.5 (core)
generator 1.1.5 (core)
osiecki-sfdx-plugins 0.2.2
salesforcedx 51.1.1 (core)
├─ schema 1.0.4 (core)
├─ limits 1.0.4 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ user 1.1.2 (core)
├─ templates 51.3.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.1.1 (core)
sfdmu 3.10.4
sfdx-cli 7.89.2 (core)
sfdx-flowdoc-plugin 0.5.1
sfdx-waw-plugin 1.5.0
sfpowerkit 2.6.5
shane-sfdx-plugins 4.43.0
├─ @mshanemc/plugin-streaming 1.1.7
└─ @mshanemc/sfdx-sosl 1.1.0
telemetry 1.1.1 (core)

**Comment by 13rettles** [comment]
Following up on this. After working with support I was eventually redirected to https://trailblazer.salesforce.com/issues_view?id=a1p3A000000EVPHQA4 I will close this ticket as I understand it is being handled by a different team.
