### ISSUE TITLE
source:retrieve commande reports "No results found" but files are retrieved

### ISSUE THREAD

**Issue by Mchaouche** [forcedotcom/cli#709]
### Summary

 When i try to retrieve an email alert with source:retrieve i get the message: Retrieved Source: No results found, but in the reality the source is retrived and stored in the repo.

### Steps To Reproduce:

1.  Type SFDX force:source:retrieve -m "email alert Name"

### Expected result

 The file is stored in the repo  and a confirmation message: 1 file retrieved

### Actual result

 The file is stored in the repo but the CLI shows this message: No results found

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.57.1-dbf54fc584 win32-x86 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-update 1.3.9
└─ @oclif/plugin-help 2.2.3

@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.7.1 (core)
generator 1.1.2 (core)
salesforcedx 48.13.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforcedx-templates 48.10.0 (core)
└─ salesforce-alm 48.14.0 (core)

**OS and version**:
Windows 10

**Comment by daveespo** [comment]
@amphro  -- for those of that are subscribed to watch this repo, it's pretty annoying to get 2 updates (and they're not grouped together in Gmail) for every new ticket that is filed.

Is this extraneous comment really necessary?

**Comment by mshanemc** [comment]
on the positive side: it reports the results correctly

You do have to retrieve it by `-m Workflow` or -m `Workflow:WorkflowName` and not by the child item types (like `-m WorkflowAlert` or `-m WorkflowTask:foo`)
