### ISSUE TITLE
Unable to use alias contain Point (.) 

### ISSUE THREAD

**Issue by idanblich** [forcedotcom/cli#71]
### Summary

Since the latest cli major release sfdx-cli/7.1.4 , i been having errors when using -u parameter with alias that contain Point (.)

### Steps To Reproduce:

1.  Authenticate to a sandbox org with CLI and set alias for the connection (ex. mySandbox.Alias) ``  sfdx force:auth:web:login -a mySandbox.Alias ``
2. try to login with CLI ``  sfdx force:org:open  -u mySandbox.Alias ``  
### Expected result

login into mySandbox.Alias org

### Actual result

```
ERROR running force:org:open:  No AuthInfo found for name mySandbox.Alias
```

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version** :
``sfdx-cli/7.1.4-79f97a7df8 darwin-x64 node-v10.15.3``

**SFDX plugin Version**
```
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.8.2 (core)
├─ force-language-services 45.9.0 (core)
└─ salesforce-alm 45.11.0 (core)

sfdx-cli 7.1.4 (core)
```

**OS and version**:
MacOS Majava 10.14.4

**Comment by clairebianchi** [comment]
@idanblich Can you please update your CLI version, this issue should go away.

**Comment by idanblich** [comment]
I update my cli  : ``sfdx-cli/7.5.0-e6ca93eee8 darwin-x64 node-v10.15.3``
Preform new auth with sandbox org and still getting error : ``ERROR running force:org:open:  No AuthInfo found for name xx.yy``

**Comment by shetzel** [comment]
@clairebianchi @idanblich - We fixed the ability to set an alias that contains a dot, but there is still a bug with certain commands when consuming these aliases.

**Comment by idanblich** [comment]
@clairebianchi Please reopen this
