### ISSUE TITLE
Allow data to be deleted after partial failure of data:tree:import plan file

### ISSUE THREAD

**Issue by neocolmartin** [forcedotcom/cli#711]
**Is your feature request related to a problem? Please describe.**
If importing a tree plan file and one of the later object imports fails, it's not simple to find the records inserted for the earlier objects to delete them before retrying.

**What are you trying to do**
Use data:tree:export & import with plan files, but I've seen a number of failures (e.g. due to exporting formula field values by mistake). If the child records fail, I want to then delete the parent records before trying again.

**Describe the solution you'd like**
I have 2 options in mind:

1. The preferred solution would be to have a flag something like `--revertonfailure` that automatically deleted any already-committed records when an error occurs. (Obviously this would have to be in a separate transaction, so can't revert any automation that the original inserts triggered.)
2. The simpler solution would be this: when an error occurs, include in the output the IDs of records created in earlier steps. Even better, you could provide the Apex required to delete them (e.g. `delete [SELECT Id FROM ObjectName WHERE Id In (...)];`)

**Describe alternatives you've considered**
In my case the records I'm inserting are the first records for those objects, so I can just delete all records.

**Comment by WillieRuemmele** [comment]
Hi @neocolmartin  check out the [announcement](https://github.com/forcedotcom/cli/issues/907) for the new [data](https://github.com/forcedotcom/cli/issues/907) plugin

**Comment by mshanemc** [comment]
I think this is fixed in the new data plugin released 4/1.  If not, re-open or create a new case.
