### ISSUE TITLE
Unable to deploy meta-xml file with version update

### ISSUE THREAD

**Issue by harsheshshah** [forcedotcom/cli#712]
### Summary

When you make change to meta-xml file to update the version with new Salesforce release, it does not deploy that alone. It gives error to include main class file.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Go to meta xml for the class file - https://github.com/trailheadapps/dreamhouse-lwc/tree/master/force-app/main/default/classes
2. Update the version to latest Salesforce release : ex: 50
3. Use sfdx:deploy to deploy the component (just meta-xml) file

### Expected result

When you try to deploy, it should be successful and Apex class version should change in the org.

### Actual result

It fails with below error:
ERROR running force:source:deploy:  Expected file at path: D:\Jenkins\Nodes\XYZ\Build\release\tmp\force-app\main\default\classes\ClassName.cls
It is expecting change also in class and does not take meta-xml file alone for deployment.

### Additional information

Running this in CLI version 49

**Comment by mshanemc** [comment]
fixed by SDR.
