### ISSUE TITLE
Coverage showed by CLI and the Developer console are different

### ISSUE THREAD

**Issue by flybrain** [forcedotcom/cli#713]
### Summary

76% codecoverage in console, while 57% in cli.
cli command: sfdx force:package:version:create -d force-app -k Envis1234 --codecoverage --wait 20

### Expected result

sfdx force:package:version:create  with --codecoverage flag should show 76% codecoverage.

### Actual result

The codecoverage of cli package command is only 57%.

### Additional information

sfdx-cli/7.77.0-112dd7d412 win32-x64 node-v12.18.3

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 49.13.1 (49.13.1)
├─ templates 49.10.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ apex 0.1.1
├─ custom-metadata 1.0.10
└─ salesforce-alm 49.12.2
sfdx-cli 7.77.0 (core)

Window10

**Comment by yippie** [comment]
@flybrain Run it again (after clearing test data is recommended) I bet you get a different % coverage. Especially at the file level.

Code coverage numbers have been approximate and differer run to run for years with no progress. They are horribly broken and need fixing. Yours is a great example of how bad it can be.

**Comment by amphro** [comment]
Can you try with the `SFDX_IMPROVED_CODE_COVERAGE` environment variable set?

**Comment by flybrain** [comment]
I used this set，but it made no difference.It seems like this set only has effect on&nbsp;
'sfdx force:apex:test:run -w10 -c -r human'.&nbsp;


---Original---
