### ISSUE TITLE
sfdx force:source:deploy is exiting without an error

### ISSUE THREAD

**Issue by rmccu** [forcedotcom/cli#716]
I am trying to run: sfdx force:source:deploy -x manifest\Care\Sprint10\Care-sp10-package.xml --checkonly -u CI

This seems to sit there running for a little bit and then returns without creating the deployment job.
![Screen Shot 2020-10-30 at 9 35 55 AM](https://user-images.githubusercontent.com/5711475/97725092-5eec6f00-1a93-11eb-9700-bf6031d6054c.png)

I am running SFDX version: sfdx-cli/7.74.1-32db2396ed win32-x63 node-v12.18.3

**Comment by rmccu** [comment]
I found out why this was happening. I had a malformed package.xml. It had the content duplicated in it (so 2 package elements). Still, this should throw an error saying the manifest is invalid.

**Comment by amphro** [comment]
I tried with malformed xml and duplicate elements and I couldn't reproduce this. Please provide a sample repository with the metadata and package.xml that reproduces this problem. A scratch org def file also helps.

**Comment by rmccu** [comment]
Here is a malformed package.xml I just used to reproduce the problem:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>CustomLabels</name>
    </types>
    <version>50.0</version>
</Package>
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>CustomLabels</name>
    </types>
    <version>50.0</version>
</Package>
```

NOTE: The package is basically duplicated. This is obviously an invalid/malformed XML file. We had this state due to a bad merge, but didn't know it because sfdx does not throw an error.

I don't have an issue that SFDX doesn't deploy this, but it should emit an error message stating that the manifest is invalid/malformed.

**Comment by rmccu** [comment]
@amphro have you had a chance to look at this?
