### ISSUE TITLE
Remove auto-updating feature from sfdx

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#718]
**Is your feature request related to a problem? Please describe.**
There are occasional issues with sfdx that appear without warning, for example https://github.com/forcedotcom/cli/issues/684. These issues affect users locally as well as CI/CD systems that use sfdx.

**What are you trying to do**
Not have to worry about the sfdx version self upgrading and spontaneously breaking something.

**Describe the solution you'd like**
sfdx to no longer update and make it clear which version it's on. Right now it's confusing because there seem to be core specific libraries that have their own versions, not a clear overall sfdx version.

**Describe alternatives you've considered**
Trying to force lock in a version with reverse engineering the core packages and running specific install commands. Doesn't feel like it's worth it.

**Additional context**
Auto updating doesn't seem appropriate for a CLI tool. It introduces nondeterministic software behavior, and removes the user's ability to triage bugs by downgrading tool versions.

**Comment by amphro** [comment]
You can already turn off auto-updates.

1. If using the installers, set the environment variable: `SFDX_DISABLE_AUTOUPDATE=true` [(doc'ed here)](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_env_variables.htm)
2. If using npm, it doesn't auto-update by default. i.e. `npm install sfdx-cli --global`. You can also hardcode to a specific version: `npm install sfdx-cli@49 --global`

If you want CLI auto-updates but want to prevent certain commands from updating, you can lock to specific versions. `sfdx plugins:install salesforcedx@50.1.0`.
