### ISSUE TITLE
Windows Distro Hash Mismatch Upon Update

### ISSUE THREAD

**Issue by OneStream-Cloud** [forcedotcom/cli#722]
After installing the latest Windows distribution of the CLI (which as of now is version 7.74.1) and then immediately performing an update, I receive the below hash error.

sfdx-cli: Updating CLI from 7.74.1-32db2396ed to 7.78.1-5a65d9dd2f... !
    Error: SHA mismatch: expected 3e94e156fef99e604cdedf53f1241b7afc2223ae8d292b9613c57e45df924b4b to be
    61fa67f9c622d993031ae1ff2f5ae88d14729c20c914e1ff1cc26fa2451909ae

**Comment by rsindall** [comment]
I am getting a similar issue

`sfdx-cli: Updating CLI from 7.78.1-5a65d9dd2f to 7.81.0-7b953c80d1... !
    Error: SHA mismatch: expected 27a77376072ccc0b5ec1f6970c0dbef74fc7c2fd8ba07289bbeacde94f68e15f to be 57baa7998d358aef4c0484aa70284ef09b6a037f6390004d28a170bfe493c82b`

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041


UPDATE:

On my 4th attempt it worked... odd.

**Comment by WillieRuemmele** [comment]
Hi @rsindall sorry for the delayed response, have you seen this issue lately?
