### ISSUE TITLE
sfdx force:org:display throws error when defaultusername is set to an expired org

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#724]
### Summary

I ran `sfdx force:org:display` with a defaultorg that was selected as defaultusername for my vscode project and I got this error that it is not treated.

![image](https://user-images.githubusercontent.com/55927613/98228595-ae79e180-1f50-11eb-8850-abfe8f21733f.png)

Then I ran `sfdx force:org:list` to see if the org was still valid, and it wasn't. 

![image](https://user-images.githubusercontent.com/55927613/98228838-0e708800-1f51-11eb-8210-a47a04715bc6.png)

I concluded that this error happens if you have an expired org selected as your defaultusername when running `sfdx force:org:display`.

Basically this happened because yesterday I created an SO that I discovered it was expired today when I opened my vscode. When I opeed VSCode this org was still selected as default (defaultusername) on sfdx.  So there are two small enhancements we can do, one is to treat the error message on sfdx to show to the user that the org is already expired, and the other is to check if the org status before showing the button on the VSCode Status Bar (the one that shows the local defaultusername), or if the org was expired change the state of the button as shown below by running `sfdx force:org:config defaultusername=`, because that button is listening to changes on the file `.sfdx/sfdx_config.json`, so If I change sfdx defaultusername then the button changes too. We could also make sfdx set defaultusername to null automatically when the org becomes expired.

![image](https://user-images.githubusercontent.com/55927613/98229504-e5042c00-1f51-11eb-8202-9f77446a8639.png)

### Steps To Reproduce:

1. Create a SO that is expired and it can still be seen on sfdx list command
2. Set this expired SO as the defaultusername, you can use sfdx config command for that, since the vscode extension does not show expired ones for you.
3. Run `sfdx force:org:display` using that defaultusername and you will see the non treated error message.

OBS: This will most likely happen when the user open vscode in the next day and the SO is already expired. The user will only notice it after he run display command or list command. 

### Expected result

`sfdx force:org:display` should display an error message saying that the current selected org is expired.

### Actual result

`sfdx force:org:display` is showing a non treated error message when it runs with a expired scratch org set as `defaultusername`

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
![image](https://user-images.githubusercontent.com/55927613/98230962-b4bd8d00-1f53-11eb-9bde-f90bd1e81b81.png)

**OS and version**: Windows 10

**Comment by mshanemc** [comment]
This **should** be fixed in the new open-source version.  You can try it early, here: https://github.com/forcedotcom/cli/issues/835

**Comment by AllanOricil** [comment]
@mshanemc I will try it tomorrow. I have an expired SO that I did not delete that I can use to test it. Thanks again.

**Comment by mshanemc** [comment]
For anyone else wanting to test this issue, one option is to create a
sandbox, auth tot it, then delete the sandbox **from the UI** so that your
CLI doesn't know it's deleted.

Then wait a day or so until the sandbox is really gone and there's no DNS
record for it and you'll see the error on the current CLI and not on the
plugin-org

**Comment by AllanOricil** [comment]
Now I can see a better error message.

![image](https://user-images.githubusercontent.com/55927613/107337997-f4e05e80-6ab2-11eb-82ca-49128a386422.png)
