### ISSUE TITLE
Callout mock does not work at  'sfdx force:package:version:create -d force-app  --codecoverage'

### ISSUE THREAD

**Issue by flybrain** [forcedotcom/cli#729]
### Summary

Callout mock works in console, but does not work at  'sfdx force:package:version:create -d force-app  --codecoverage'.

### Steps To Reproduce:

1.Create callout mock
2.Create callout test and set mock
3.Run test in console, mock works
4.Run the package command 'sfdx force:package:version:create -d force-app  --codecoverage', mock does not work

### Expected result

Package version is created.

### Actual result

The Test throws a callout exception.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.78.1-5a65d9dd2f win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.1.10 (core)
generator 1.1.3 (core)
salesforcedx 49.13.1 (49.13.1)
├─ custom-metadata 1.0.10
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ templates 49.10.0
├─ apex 0.1.1
└─ salesforce-alm 49.12.2
sfdx-cli 7.78.1 (core)
**OS and version**:
Windows 10

**Comment by AllanOricil** [comment]
@flybrain  could you take a print screen showing what you described in the bug? I never noticed it

**Comment by flybrain** [comment]
There's something wrong with the code itself.
