### ISSUE TITLE
Add a --disable-verification-code flag to the sfdx force:org:create command

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#732]
**Is your feature request related to a problem? Please describe.**
Yes, I often see myself having to share a Scratch Org (SO) access to somebody else so they can login and see something. And every time they login for the first time I have to get a Verification Code and share with them.

**What are you trying to do**
Create Scratch Orgs that I can share without the need to share a Verification Code that is sent to my email.

**Describe the solution you'd like**
Add a new flag to the create org command: --disable-verification-cde

**Describe alternatives you've considered**
I created an sfdx extension that deploys metadata for Ip addresses. This disables the verification code for those SO. But it would be good if this could be default by adding that flag I suggested above.

**Additional context**
No

**Comment by AllanOricil** [comment]
@mshanemc I created a plugin that does that and works well. I just had to deploy this metadata to my Scratch Org

This could be deployed automatically when we run `sfdx force:org:create --disable-verification-code` or it could be a Scratch Org configuration

````xml
<?xml version="1.0" encoding="UTF-8"?>
<SecuritySettings xmlns="http://soap.sforce.com/2006/04/metadata">
    <canUsersGrantLoginAccess>true</canUsersGrantLoginAccess>
    <enableAdminLoginAsAnyUser>false</enableAdminLoginAsAnyUser>
    <enableAuditFieldsInactiveOwner>false</enableAuditFieldsInactiveOwner>
    <enableAuraSecureEvalPref>true</enableAuraSecureEvalPref>
    <enableRequireHttpsConnection>true</enableRequireHttpsConnection>
    <isTLSv12Required>false</isTLSv12Required>
    <isTLSv12RequiredCommunities>false</isTLSv12RequiredCommunities>
    <networkAccess>
        <ipRanges>
            <end>255.255.255.255</end>
            <start>254.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>253.255.255.255</end>
            <start>252.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>251.255.255.255</end>
            <start>250.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>249.255.255.255</end>
            <start>248.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>247.255.255.255</end>
            <start>246.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>245.255.255.255</end>
            <start>244.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>243.255.255.255</end>
            <start>242.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>241.255.255.255</end>
            <start>240.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>239.255.255.255</end>
            <start>238.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>237.255.255.255</end>
            <start>236.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>235.255.255.255</end>
            <start>234.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>233.255.255.255</end>
            <start>232.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>231.255.255.255</end>
            <start>230.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>229.255.255.255</end>
            <start>228.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>227.255.255.255</end>
            <start>226.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>225.255.255.255</end>
            <start>224.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>223.255.255.255</end>
            <start>222.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>221.255.255.255</end>
            <start>220.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>219.255.255.255</end>
            <start>218.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>217.255.255.255</end>
            <start>216.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>215.255.255.255</end>
            <start>214.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>213.255.255.255</end>
            <start>212.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>211.255.255.255</end>
            <start>210.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>209.255.255.255</end>
            <start>208.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>207.255.255.255</end>
            <start>206.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>205.255.255.255</end>
            <start>204.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>203.255.255.255</end>
            <start>202.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>201.255.255.255</end>
            <start>200.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>199.255.255.255</end>
            <start>198.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>197.255.255.255</end>
            <start>196.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>195.255.255.255</end>
            <start>194.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>193.255.255.255</end>
            <start>192.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>191.255.255.255</end>
            <start>190.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>189.255.255.255</end>
            <start>188.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>187.255.255.255</end>
            <start>186.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>185.255.255.255</end>
            <start>184.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>183.255.255.255</end>
            <start>182.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>181.255.255.255</end>
            <start>180.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>179.255.255.255</end>
            <start>178.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>177.255.255.255</end>
            <start>176.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>175.255.255.255</end>
            <start>174.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>173.255.255.255</end>
            <start>172.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>171.255.255.255</end>
            <start>170.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>169.255.255.255</end>
            <start>168.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>167.255.255.255</end>
            <start>166.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>165.255.255.255</end>
            <start>164.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>163.255.255.255</end>
            <start>162.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>161.255.255.255</end>
            <start>160.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>159.255.255.255</end>
            <start>158.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>157.255.255.255</end>
            <start>156.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>155.255.255.255</end>
            <start>154.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>153.255.255.255</end>
            <start>152.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>151.255.255.255</end>
            <start>150.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>149.255.255.255</end>
            <start>148.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>147.255.255.255</end>
            <start>146.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>145.255.255.255</end>
            <start>144.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>143.255.255.255</end>
            <start>142.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>141.255.255.255</end>
            <start>140.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>139.255.255.255</end>
            <start>138.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>137.255.255.255</end>
            <start>136.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>135.255.255.255</end>
            <start>134.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>133.255.255.255</end>
            <start>132.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>131.255.255.255</end>
            <start>130.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>129.255.255.255</end>
            <start>128.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>127.255.255.255</end>
            <start>126.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>125.255.255.255</end>
            <start>124.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>123.255.255.255</end>
            <start>122.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>121.255.255.255</end>
            <start>120.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>119.255.255.255</end>
            <start>118.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>117.255.255.255</end>
            <start>116.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>115.255.255.255</end>
            <start>114.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>113.255.255.255</end>
            <start>112.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>111.255.255.255</end>
            <start>110.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>109.255.255.255</end>
            <start>108.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>107.255.255.255</end>
            <start>106.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>105.255.255.255</end>
            <start>104.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>103.255.255.255</end>
            <start>102.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>101.255.255.255</end>
            <start>100.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>99.255.255.255</end>
            <start>98.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>97.255.255.255</end>
            <start>96.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>95.255.255.255</end>
            <start>94.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>93.255.255.255</end>
            <start>92.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>91.255.255.255</end>
            <start>90.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>89.255.255.255</end>
            <start>88.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>87.255.255.255</end>
            <start>86.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>85.255.255.255</end>
            <start>84.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>83.255.255.255</end>
            <start>82.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>81.255.255.255</end>
            <start>80.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>79.255.255.255</end>
            <start>78.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>77.255.255.255</end>
            <start>76.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>75.255.255.255</end>
            <start>74.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>73.255.255.255</end>
            <start>72.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>71.255.255.255</end>
            <start>70.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>69.255.255.255</end>
            <start>68.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>67.255.255.255</end>
            <start>66.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>65.255.255.255</end>
            <start>64.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>63.255.255.255</end>
            <start>62.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>61.255.255.255</end>
            <start>60.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>59.255.255.255</end>
            <start>58.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>57.255.255.255</end>
            <start>56.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>55.255.255.255</end>
            <start>54.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>53.255.255.255</end>
            <start>52.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>51.255.255.255</end>
            <start>50.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>49.255.255.255</end>
            <start>48.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>47.255.255.255</end>
            <start>46.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>45.255.255.255</end>
            <start>44.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>43.255.255.255</end>
            <start>42.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>41.255.255.255</end>
            <start>40.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>39.255.255.255</end>
            <start>38.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>37.255.255.255</end>
            <start>36.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>35.255.255.255</end>
            <start>34.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>33.255.255.255</end>
            <start>32.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>31.255.255.255</end>
            <start>30.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>29.255.255.255</end>
            <start>28.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>27.255.255.255</end>
            <start>26.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>25.255.255.255</end>
            <start>24.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>23.255.255.255</end>
            <start>22.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>21.255.255.255</end>
            <start>20.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>19.255.255.255</end>
            <start>18.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>17.255.255.255</end>
            <start>16.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>15.255.255.255</end>
            <start>14.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>13.255.255.255</end>
            <start>12.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>11.255.255.255</end>
            <start>10.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>9.255.255.255</end>
            <start>8.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>7.255.255.255</end>
            <start>6.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>5.255.255.255</end>
            <start>4.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>3.255.255.255</end>
            <start>2.0.0.0</start>
        </ipRanges>
        <ipRanges>
            <end>1.255.255.255</end>
            <start>0.0.0.0</start>
        </ipRanges>
    </networkAccess>
    <passwordPolicies>
        <complexity>AlphaNumeric</complexity>
        <enableSetPasswordInApi>true</enableSetPasswordInApi>
        <expiration>NinetyDays</expiration>
        <historyRestriction>3</historyRestriction>
        <lockoutInterval>FifteenMinutes</lockoutInterval>
        <maxLoginAttempts>TenAttempts</maxLoginAttempts>
        <minimumPasswordLength>8</minimumPasswordLength>
        <minimumPasswordLifetime>false</minimumPasswordLifetime>
        <obscureSecretAnswer>false</obscureSecretAnswer>
        <questionRestriction>DoesNotContainPassword</questionRestriction>
    </passwordPolicies>
    <sessionSettings>
        <allowUserAuthenticationByCertificate>false</allowUserAuthenticationByCertificate>
        <canConfirmEmailChangeInLightningCommunities>false</canConfirmEmailChangeInLightningCommunities>
        <canConfirmIdentityBySmsOnly>true</canConfirmIdentityBySmsOnly>
        <disableTimeoutWarning>false</disableTimeoutWarning>
        <enableCSPOnEmail>true</enableCSPOnEmail>
        <enableCSRFOnGet>true</enableCSRFOnGet>
        <enableCSRFOnPost>true</enableCSRFOnPost>
        <enableCacheAndAutocomplete>true</enableCacheAndAutocomplete>
        <enableClickjackNonsetupSFDC>true</enableClickjackNonsetupSFDC>
        <enableClickjackNonsetupUser>false</enableClickjackNonsetupUser>
        <enableClickjackNonsetupUserHeaderless>false</enableClickjackNonsetupUserHeaderless>
        <enableClickjackSetup>true</enableClickjackSetup>
        <enableContentSniffingProtection>true</enableContentSniffingProtection>
        <enableLightningLogin>true</enableLightningLogin>
        <enableLightningLoginOnlyWithUserPerm>false</enableLightningLoginOnlyWithUserPerm>
        <enablePostForSessions>false</enablePostForSessions>
        <enableSMSIdentity>true</enableSMSIdentity>
        <enableU2F>false</enableU2F>
        <enableUpgradeInsecureRequests>true</enableUpgradeInsecureRequests>
        <enableXssProtection>true</enableXssProtection>
        <enforceIpRangesEveryRequest>false</enforceIpRangesEveryRequest>
        <forceLogoutOnSessionTimeout>true</forceLogoutOnSessionTimeout>
        <forceRelogin>true</forceRelogin>
        <hasRetainedLoginHints>false</hasRetainedLoginHints>
        <hasUserSwitching>true</hasUserSwitching>
        <hstsOnForcecomSites>true</hstsOnForcecomSites>
        <identityConfirmationOnEmailChange>false</identityConfirmationOnEmailChange>
        <identityConfirmationOnTwoFactorRegistrationEnabled>false</identityConfirmationOnTwoFactorRegistrationEnabled>
        <lockSessionsToDomain>true</lockSessionsToDomain>
        <lockSessionsToIp>false</lockSessionsToIp>
        <lockerServiceCSP>true</lockerServiceCSP>
        <redirectionWarning>true</redirectionWarning>
        <referrerPolicy>true</referrerPolicy>
        <requireHttpOnly>false</requireHttpOnly>
        <requireHttps>true</requireHttps>
        <securityCentralKillSession>true</securityCentralKillSession>
        <sessionTimeout>TwoHours</sessionTimeout>
    </sessionSettings>
    <singleSignOnSettings>
        <enableMultipleSamlConfigs>true</enableMultipleSamlConfigs>
        <enableSamlJitProvisioning>false</enableSamlJitProvisioning>
        <enableSamlLogin>false</enableSamlLogin>
    </singleSignOnSettings>
</SecuritySettings>

````

**Comment by ferferrarazzo** [comment]
You can change the project-scratch-def and use this json:

`{
    "orgName": "Scratch Name",
    "edition": "Developer",
    "hasSampleData": "true",
    "country" : "US",
    "features": ["Communities", "ServiceCloud", "Sites", "PlatformCache", "Knowledge", "LightningServiceConsole"],
    "settings": {
        "knowledgeSettings": {
            "enableKnowledge": true,
            "enableLightningKnowledge": true
        },
        "lightningExperienceSettings": {
            "enableS1DesktopEnabled": true
        },
        "communitiesSettings": {
            "enableNetworksEnabled": true,
            "enableOotbProfExtUserOpsEnable": true
        },
        "apexSettings": {
            "enableCompileOnDeploy" : true
        },
        "securitySettings": {
            "sessionSettings": {
                "sessionTimeout": "TwelveHours"
            },
            "networkAccess": {
                "ipRanges" : [
                    {        
            "description": "All range",
                    "start": "254.0.0.0",
                    "end": "255.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "252.0.0.0",
                    "end": "253.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "250.0.0.0",
                    "end": "251.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "248.0.0.0",
                    "end": "249.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "246.0.0.0",
                    "end": "247.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "244.0.0.0",
                    "end": "245.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "242.0.0.0",
                    "end": "243.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "240.0.0.0",
                    "end": "241.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "238.0.0.0",
                    "end": "239.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "236.0.0.0",
                    "end": "237.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "234.0.0.0",
                    "end": "235.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "232.0.0.0",
                    "end": "233.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "230.0.0.0",
                    "end": "231.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "228.0.0.0",
                    "end": "229.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "226.0.0.0",
                    "end": "227.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "224.0.0.0",
                    "end": "225.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "222.0.0.0",
                    "end": "223.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "220.0.0.0",
                    "end": "221.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "218.0.0.0",
                    "end": "219.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "216.0.0.0",
                    "end": "217.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "214.0.0.0",
                    "end": "215.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "212.0.0.0",
                    "end": "213.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "210.0.0.0",
                    "end": "211.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "208.0.0.0",
                    "end": "209.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "206.0.0.0",
                    "end": "207.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "204.0.0.0",
                    "end": "205.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "202.0.0.0",
                    "end": "203.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "200.0.0.0",
                    "end": "201.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "198.0.0.0",
                    "end": "199.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "196.0.0.0",
                    "end": "197.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "194.0.0.0",
                    "end": "195.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "192.0.0.0",
                    "end": "193.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "190.0.0.0",
                    "end": "191.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "188.0.0.0",
                    "end": "189.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "186.0.0.0",
                    "end": "187.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "184.0.0.0",
                    "end": "185.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "182.0.0.0",
                    "end": "183.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "180.0.0.0",
                    "end": "181.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "178.0.0.0",
                    "end": "179.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "176.0.0.0",
                    "end": "177.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "174.0.0.0",
                    "end": "175.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "172.0.0.0",
                    "end": "173.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "170.0.0.0",
                    "end": "171.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "168.0.0.0",
                    "end": "169.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "166.0.0.0",
                    "end": "167.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "164.0.0.0",
                    "end": "165.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "162.0.0.0",
                    "end": "163.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "160.0.0.0",
                    "end": "161.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "158.0.0.0",
                    "end": "159.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "156.0.0.0",
                    "end": "157.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "154.0.0.0",
                    "end": "155.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "152.0.0.0",
                    "end": "153.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "150.0.0.0",
                    "end": "151.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "148.0.0.0",
                    "end": "149.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "146.0.0.0",
                    "end": "147.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "144.0.0.0",
                    "end": "145.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "142.0.0.0",
                    "end": "143.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "140.0.0.0",
                    "end": "141.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "138.0.0.0",
                    "end": "139.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "136.0.0.0",
                    "end": "137.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "134.0.0.0",
                    "end": "135.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "132.0.0.0",
                    "end": "133.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "130.0.0.0",
                    "end": "131.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "128.0.0.0",
                    "end": "129.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "126.0.0.0",
                    "end": "127.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "124.0.0.0",
                    "end": "125.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "122.0.0.0",
                    "end": "123.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "120.0.0.0",
                    "end": "121.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "118.0.0.0",
                    "end": "119.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "116.0.0.0",
                    "end": "117.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "114.0.0.0",
                    "end": "115.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "112.0.0.0",
                    "end": "113.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "110.0.0.0",
                    "end": "111.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "108.0.0.0",
                    "end": "109.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "106.0.0.0",
                    "end": "107.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "104.0.0.0",
                    "end": "105.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "102.0.0.0",
                    "end": "103.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "100.0.0.0",
                    "end": "101.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "98.0.0.0",
                    "end": "99.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "96.0.0.0",
                    "end": "97.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "94.0.0.0",
                    "end": "95.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "92.0.0.0",
                    "end": "93.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "90.0.0.0",
                    "end": "91.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "88.0.0.0",
                    "end": "89.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "86.0.0.0",
                    "end": "87.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "84.0.0.0",
                    "end": "85.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "82.0.0.0",
                    "end": "83.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "80.0.0.0",
                    "end": "81.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "78.0.0.0",
                    "end": "79.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "76.0.0.0",
                    "end": "77.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "74.0.0.0",
                    "end": "75.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "72.0.0.0",
                    "end": "73.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "70.0.0.0",
                    "end": "71.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "68.0.0.0",
                    "end": "69.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "66.0.0.0",
                    "end": "67.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "64.0.0.0",
                    "end": "65.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "62.0.0.0",
                    "end": "63.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "60.0.0.0",
                    "end": "61.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "58.0.0.0",
                    "end": "59.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "56.0.0.0",
                    "end": "57.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "54.0.0.0",
                    "end": "55.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "52.0.0.0",
                    "end": "53.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "50.0.0.0",
                    "end": "51.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "48.0.0.0",
                    "end": "49.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "46.0.0.0",
                    "end": "47.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "44.0.0.0",
                    "end": "45.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "42.0.0.0",
                    "end": "43.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "40.0.0.0",
                    "end": "41.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "38.0.0.0",
                    "end": "39.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "36.0.0.0",
                    "end": "37.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "34.0.0.0",
                    "end": "35.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "32.0.0.0",
                    "end": "33.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "30.0.0.0",
                    "end": "31.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "28.0.0.0",
                    "end": "29.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "26.0.0.0",
                    "end": "27.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "24.0.0.0",
                    "end": "25.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "22.0.0.0",
                    "end": "23.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "20.0.0.0",
                    "end": "21.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "18.0.0.0",
                    "end": "19.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "16.0.0.0",
                    "end": "17.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "14.0.0.0",
                    "end": "15.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "12.0.0.0",
                    "end": "13.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "10.0.0.0",
                    "end": "11.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "8.0.0.0",
                    "end": "9.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "6.0.0.0",
                    "end": "7.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "4.0.0.0",
                    "end": "5.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "2.0.0.0",
                    "end": "3.255.255.255"
                }
                ,{
            "description": "All range",
                    "start": "0.0.0.0",
                    "end": "1.255.255.255"
                }
            ]
            }
        }
    }
}
`
