### ISSUE TITLE
Typo in Spring '21 warning for Contacts to Multiple Accounts

### ISSUE THREAD

**Issue by FabienTaillon** [forcedotcom/cli#736]
### Summary

When creating a Scratch Org, we're getting the following warning:
`WARNING: Warning: If you're using Contacts to Multiple Accounts, beginning with the Spring ’21 release, the feature isn't automatically enabled. You must manually enable the setting for new scratch orgs. Enable the setting in one of these ways: update the Account Settings page in Setup, add the enableRelateContactsToMultipleAccounts setting to your scratch org definition file, or enable it via Metadata API.`

However there is a typo here, the related setting isn't `enableRelateContactsToMultipleAccounts` but `enableRelateContactToMultipleAccounts` (no __s__ to __Contact__) as described [in the doc](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_accountsettings.htm).

**Comment by ekapner** [comment]
Thanks, @FabienTaillon - I'll reach out to the Tech Writer. Opened a work item and assigned it to the writer.

**Comment by mshanemc** [comment]
I'm closing this issue since it never got fixed and the warning is disappearing in the release
