### ISSUE TITLE
sfdx force:source:deploy:report result is not consistent with meta_deployresult metadata documentation

### ISSUE THREAD

**Issue by alexmodis** [forcedotcom/cli#737]
### Summary

codeCoverageWarnings json key in sfdx force:source:deploy:report result is not consistent with the [documentation here](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deployresult.htm)
If you have several errors it will return an Array
If you have only one error it will return an Object

### Steps To Reproduce:
1) run sfdx force:source:deploy:report --json with several code coverage errors :
2) get result: 
```
"codeCoverageWarnings": [........]
```
3) run sfdx force:source:deploy:report --json with 1 code coverage errors :
4) get result: 
```
"codeCoverageWarnings": {....}
```

### Expected result

codeCoverageWarnings type  should always be an array as specified in metadata documentation.
### Actual result

codeCoverageWarnings type is an Array or an Object depending on number of errors.

### Additional information

**SFDX CLI Version**
sfdx-cli/7.78.1 win32-x64 node-v14.15.0

**OS and version**: ubuntu latest

**Comment by alexmodis** [comment]
@clairebianchi any update on this one ?

**Comment by mshanemc** [comment]
the metadata API returns an object if theres only one.  You can verify this by calling the API directly (ie, not using the CLI)
I wish it would always be an array, too (it would be simpler on our side).

We try to keep the command output consistent with the mdapi shape since it's pretty widely known/used.
