### ISSUE TITLE
Cant install any plugins "error An unexpected error occurred: self signed certificate in certificate chain"."

### ISSUE THREAD

**Issue by idanlahat1** [forcedotcom/cli#738]
### Summary

When trying to install plugins from the terminal I always get:
"error An unexpected error occurred: "https://registry.yarnpkg.com/@salesforce%2fanalytics: self signed certificate in certificate chain".

I tried uninstalling the CLI, and it is the latest version.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1. Run sfdx plugins:install @salesforce/sfdx-diff or sfdx plugins:install @salesforce/analytics
2. Error occurres. 

### Expected result

Should install. 

### Actual result

Error "Successfully validated digital signature for @salesforce/analytics.
Finished digital signature check.
error An unexpected error occurred: "https://registry.yarnpkg.com/@salesforce%2fanalytics: self signed certificate in certificate chain"."

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.78.1-5a65d9dd2f

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) sfdx plugins:install @salesforce/sfdx-diff or sfdx plugins:install @salesforce/analytics

**OS and version**: win 10 64 bit

**Comment by mshanemc** [comment]
there's been a lot of changes to that code, and hopefully you got all your local cert stuff fixed (that's usually what that error means).  

Please open a new issue with a repro if you've still got a way to reproduce it
