### ISSUE TITLE
sfdx force:auth:web:login keeps on running and don't open any browser window

### ISSUE THREAD

**Issue by CK395** [forcedotcom/cli#739]
### Summary

The sfdx command "sfdx force:auth:web:login" is not working as expected. It should open the browser window to login into the salesforce org but it does not. It just keeps on running.

### Steps To Reproduce:

1.  Create a project in vs code using ctrl+shipt+p => SFDX: Create project with manifest
1.  As the project is created try to authorize an org using ctrl+shipt+p => SFDX : Authorize an org 

### Expected result

The browser should have opened a new tab on the specified url like "https://login.salesforce.com"

### Actual result

Nothing happened. The command keeps running in vs code bottom right corner

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**          
![image](https://user-images.githubusercontent.com/44803801/99092192-d7f0d800-25f6-11eb-91fb-345b5e4ef756.png)

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
![image](https://user-images.githubusercontent.com/44803801/99092507-3a49d880-25f7-11eb-9ad5-fe5894021061.png)

**OS and version**:
Windows 10

**Existing Solution Suggestions**
It is been suggested in some solutions that changing the default browser or setting the default browser to Microsoft Edge will resolve this issue.
However the same is not correct in my case as I have tried that but is not working.
I have also tried installing the vs code and cli again but to no luck.

![image](https://user-images.githubusercontent.com/44803801/99092892-cb20b400-25f7-11eb-868f-7ad88b140d6f.png)

**Comment by zerkz** [comment]
check and see if you have a node process using port 1717, kill it, and try again.

**Comment by edralph** [comment]
thanks for the suggestion, running sudo lsof -i :1717 didn't pull anything
up.

**Comment by CK395** [comment]
killing the Process doesn't help either. The issue still persists.

**Comment by mikearthur7b0** [comment]
Are you behind corporate firewall, e.g. on VPN?
Only works for me when disconnected from VPN, but I do get the login page, the sfdx command never completes though after completing login.

**Comment by mshanemc** [comment]
This is fixed in newer releases for both windows and linux.  Please reopen if it's still happening
