### ISSUE TITLE
Retrieving code with manifest - "packageDirectories" error

### ISSUE THREAD

**Issue by smerakm** [forcedotcom/cli#74]
### Summary

I'm trying to retrieve matadata from sandbox using SFDX: Retrieve Source from Org and using package.xml. But I get error:
Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

I have a fresh project created by running SFDX: Create Project with Manifest

When I create a class in this project and retrieve it as single file, it works without issue.

### Steps To Reproduce:

1.  SFDX: Create Project with Manifest
1.  connect a sandbox org
1. right-click on default generated package.xml and run SFDX: Retrieve Source from Org

### Expected result

source metadata are retrieved in ./force-app folder

### Actual result

Error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

### Additional information

my sfdx-project.json file:
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://test.salesforce.com",
  "sourceApiVersion": "45.0"
}

**VS Code Version**:
1.31.1

**SFDX CLI Version**:
sfdx-cli/6.53.0-67a9cbb60c (windows-x64) node-v8.9.4
Salesforce Extension Pack: 45.2.0

**OS and version**:
Windows 10 (64)

**Comment by mubeen-qawi** [comment]
+1 
This is kind of annoying, and surprising since others projects connected to separate instances works seamless. the sfdc-project.json has pretty same configuration in terms of path, and other parameters.

**Comment by batyrch** [comment]
I am going through the same issue.

**Comment by Chameen-WEF** [comment]
me too

**Comment by iandextermaya** [comment]
Does anyone solve this issue?

**Comment by amarkulkarni-RC** [comment]
I'm having the same issue.. Is there any workaround for this? @smerakm

**Comment by jcaughie** [comment]
@smerakm the workaround listed at the bottom of this thread worked for me. [https://developer.salesforce.com/forums/?id=9062I000000IFKyQAO](https://developer.salesforce.com/forums/?id=9062I000000IFKyQAO)

**Comment by monkeyfufu** [comment]
You can right click each individual thing...and deploy that way...   
I have the same problem, sort of.  I started a new project yesterday because of this - and that worked fine.  
I reset my machine (mac killer catallina.) And it worked fine.
I closed it and came back without a restart and the same error.  (or it went to screen or power save and I came back to the error that says we are moving too slow!  really it says your manifest directory isn't listed 
Spring release hurts (OT Alert - As i started out unable to deploy to sandbox....still don't know which checkbox I missed as I could retrieve, just not deploy.)

**Comment by amphro** [comment]
I went through the repro steps on 7.75.0 v50 and it worked. If anyone is still running into this, please update with some new information.

**Comment by hackbac** [comment]
I ran into this problem when I had multiple folders opened in my VS Code Workspace. When I removed all other folders, I found that the project didn't have a default org set. Adding a default org via the Salesforce Extension fixed the issue for me.
