### ISSUE TITLE
Error while running sfdx soql queries thru cli

### ISSUE THREAD

**Issue by ramesh-karanji** [forcedotcom/cli#747]
### Summary
Error while running sfdx soql queries thru cli
sfdx force:data:soql:query 
ERROR running force:data:soql:query:  Cannot find module 'antlr4/index'

Issue started occurring today 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): latest

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): latset

**Comment by alexmodis** [comment]
Same problem here, please patch npm dependencies :)

**Comment by HerrX2000** [comment]
I am experiencing this problem as well. Last working version is 0.70.0 for me.

sfdx -v:
`sfdx-cli/7.81.0 linux-x64 node-v14.15.1`

**Comment by alexiswilliams** [comment]
I'm having the same issue when running any SOQL with SFDX. 
`sfdx force:data:soql:query -q "select ID from RecordType LIMIT 1" -r csv -u MY-ORG`

```
ERROR running force:data:soql:query:  Cannot find module 'antlr4/index'
Require stack:
- /usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/gen/SOQLLexer.js
- /usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/data/soqlParser/index.js
- /usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/data/dataSoqlQueryCommand.js
- /usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/commands/force/data/soql/query.js
- /usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/plugin.js
- /usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js
- /usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/index.js
- /usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js
- /usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/index.js
- /usr/local/lib/node_modules/sfdx-cli/dist/cli.js
- /usr/local/lib/node_modules/sfdx-cli/bin/run
```

Version of SFDX CLI
`sfdx-cli/7.81.0 darwin-x64 node-v15.2.0`

**Comment by shetzel** [comment]
duplicate of #746 
Let's use 746 to track this.  We will release a fix asap.  Looks like we can just remove this dep entirely.
