### ISSUE TITLE
Can't push component and SFDX dont tell me the real reason

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#748]
### Summary
SFDX is not allowing me to push this component and it says it can't find the bundle. Why? On the localdev everything works fine!

![image](https://user-images.githubusercontent.com/55927613/100207350-6884bd80-2eff-11eb-82e4-1375401f78df.png)

![image](https://user-images.githubusercontent.com/55927613/100207737-d8934380-2eff-11eb-8d4e-db3560e3af26.png)

![image](https://user-images.githubusercontent.com/55927613/100207769-e21cab80-2eff-11eb-8bea-e6de96c129a5.png)

The component and that css class are working fine

![image](https://user-images.githubusercontent.com/55927613/100208218-62dba780-2f00-11eb-99e8-3063717bcdf0.png)

## UPDATE
I deleted the .css file and then got this error message
![image](https://user-images.githubusercontent.com/55927613/100210889-645a9f00-2f03-11eb-94c9-181d54f443f6.png)

Then I fixed it by deleting the folder `.sfdx` in the root of that workspace.  But then SFDX complained about the HTML !!!!

![image](https://user-images.githubusercontent.com/55927613/100210745-3ecd9580-2f03-11eb-95fa-9132f0962dea.png)

And I repeat, the component run in the dev console without any problem.

I also tried renaming everything to `dceRadioButtonGroupActions` and the results were the same.

### Steps To Reproduce:

Not sure how would you reproduce it. Any of my colleagues can't issue a source push from my branch because of this error.

### Expected result

The component should be deployed without any problem.

### Actual result

The component is not deployed

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
![image](https://user-images.githubusercontent.com/55927613/100207655-c0bbbf80-2eff-11eb-8cdd-ead7191bc3cc.png)

**OS and version**:
Windows 10

**Comment by AllanOricil** [comment]
A colleague found the problem. It is the name of the `.xml` file. It was missing `.js-meta.` in the name !!!
Guys, everyone that rename their components to something else can make the same mistake as I did of removing that weird sufix in the file name. Does it make sense to have that file named with `.js-meta.xml` if it is the only `.xml` inside the components folder? why not just leave it `.xml` ????
Also, the sfdx messages could be improved for something like this "The component's Metadata description for the component NAME_OF_THE_COMPONENT could not be located. Please verify you have a file with the extension `.js-meta.xml` inside your component's folder" -> This is much more useful then just tell me that you can't find something and not tell me exactly what could not be found.

**Comment by mshanemc** [comment]
I'm gonna mark this closed (user error) but answer some of the questions:

 > Does it make sense to have that file named with .js-meta.xml if it is the only .xml inside the components folder? why not just leave it .xml ????

that's a pretty standard file naming convention in the source format (foo.cls-meta.xml).  There's enough LWC in the world that it won't change without a lot of pain.

> Also, the sfdx messages could be improved for something like this "The component's Metadata description for the component NAME_OF_THE_COMPONENT could not be located. Please verify you have a file with the extension .js-meta.xml inside your component's folder"

I agree.  **MOST**  LWCs get created by using the create command (from CLI or VSCode) which handles all that for you, so it's probably not a common error.  That error comes from the metadata API implementation of LWC, so CLI is the wrong place to improve errors.

You can possibly get that team's attention over here: https://github.com/salesforce/lwc
