### ISSUE TITLE
ERROR running force:source:retrieve:  WARNING: Infinite loop detected.

### ISSUE THREAD

**Issue by jvolkov** [forcedotcom/cli#749]
### Summary

`ERROR running force:source:retrieve:  WARNING: Infinite loop detected.`

Unable to retrieve anything from source org.  Tried several different orgs and metadata types.  Received this error for all of them.

#### Without connecting to remote GitHub repo

1.  Create a brand new sfdx project from VS Code
2.  Auth a sandbox org
3.  Before connecting to any remote repo, retrieve source in manifest
4.  All metadata is successfully retrieved as expected

#### Now with a connection to a remote GitHub repo

1.  Create a brand new sfdx project from VS Code
2.  Auth a sandbox org
3.  Before connecting to any remote repo, retrieve source in manifest
4.  All metadata is successfully retrieved as expected
5.  `git remote add origin` to get remote repo
6.  'git pull' to get repo branch
7.  **Retrieve source in manifest** now errors out with `ERROR running force:source:retrieve:  WARNING: Infinite loop detected.`

![image](https://user-images.githubusercontent.com/1066119/100289199-3722e680-2f2d-11eb-93f0-20f61159ec98.png)

#### Now from Command Prompt (after doing the above)

1.  `>sfdx force:auth:web:login` for the same sandbox org as above
2.  `sfdx force:source:retrieve --json -m SomeMetadataType:SomeName`
3.  Returned more WARNINGS than can count
![image](https://user-images.githubusercontent.com/1066119/100288879-8583b580-2f2c-11eb-99a4-19adb09f6e92.png)
```
WARNING: Flows must be used with a minimum API version of 44.0. Make sure that the sfdx-project.json file is set to use "sourceApiVersion": "44.0" or later, and that you’ve upgraded the flow files per the instructions in the Metadata API Developer Guide: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_visual_workflow.htm#md_flow_upgrade.
```
FYI sfdx-project.json api version is set to 48.0

### Expected result

When connected to a remote repo and sandbox org, expect the retrieve source in manifest to work as it used to.

### Actual result

Receive error: `ERROR running force:source:retrieve:  WARNING: Infinite loop detected.`

### Additional information

**VS Code Version**:  1.51.1

**SFDX CLI Version**:  7.81.0-7b953c80d1 win32-x64 node-v12.18.3

**OS and version**:  Windows_NT x64 10.0.17763

**salesforcedx**: 50.6.0 (core)

**Comment by jvolkov** [comment]
On a related note this command when manually typed is working:

`sfdx force:source:retrieve -m CustomObject:customstuff__c`

But the Org Browser's `Retrieve (Beta)` is failing for the exact same object.

**Comment by mshanemc** [comment]
@jvolkov we changed the library for deploy/retrieve (and in beta, [push/pull] (https://github.com/forcedotcom/cli/issues/1258)).

That should fix the problem.  If it doesn't, please respond.
