### ISSUE TITLE
SFDX Commands take long and fail with ECONNRESET

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/cli#75]
I am unable to do any sfdx CLI commands today. Most of them fail with an  ECONNRESET. error.

<img width="987" alt="sfasc-neo____dev_projects_sfasc-neo__-_____config_dev-scratch-def_json__sfasc-neo__und_projects" src="https://user-images.githubusercontent.com/8180281/55888734-36024180-5bb0-11e9-8523-13860d13b51a.png">

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
7.2.0-179c9078fc

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
Got updated with sfdx update

**OS and version**:
Mac OS X Mojave

**Comment by tnoonan-salesforce** [comment]
Can you try again by adding the --dev-debug?

Also, can you include the output of `sfdx plugins --core`.

**Comment by rsoesemann** [comment]
I was unable to reproduce this the next day.
