### ISSUE TITLE
Flag to allow salesforcedx plugin to perform a source push as a single deployment

### ISSUE THREAD

**Issue by seanong-athena** [forcedotcom/cli#750]
In the current salesforcedx plugin version (50.6.0)
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core) 
@oclif/plugin-help 3.2.0 (core)     
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)  
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.6.0 (core)
├─ schema 1.0.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 50.1.0 (core)
├─ salesforce-alm 50.6.0 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.81.0 (core)
```
And using multiple packageDirectories in the sfdx-project.json
```
{
  "packageDirectories": [
    {
      "path": "common",
      "package": "common",
      "versionNumber": "1.0.0.NEXT"
    },
    {
      "path": "force-app",
      "default": true,
      "package": "origination",
      "versionNumber": "1.0.0.NEXT"
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "48.0"
}
```

When doing a `force:source:push` for the first time, it will deploy the directories in the order specified. See below where there are 225 components, indicating that the common directory is being deployed first. There are errors with the push because there are some metadata in the common directory that depends on the force-app.
```
SOURCE PROGRESS | ██████████████████████████████████████░░ | 215/225 Components
TYPE   PROJECT PATH                                                                           PROBLEM
─────  ─────────────────────────────────────────────────────────────────────────────────────  ───────────────────────────────────────────────────────────────────────────────────────────────────────
Error  common\objects\clcommon__Fee__c\fields\Application__c.field-meta.xml                   referenceTo value of 'orig_Application__c' does not resolve to a valid sObject type (169:13)
Error  common\objects\loan__Loan_Account__c\fields\orig_Application__c.field-meta.xml         referenceTo value of 'orig_Application__c' does not resolve to a valid sObject type (493:13)
Error  common\objects\loan__Loan_Collateral__c\fields\Settlement_Valuation__c.field-meta.xml  referenceTo value of 'common_Collateral_Valuation__c' does not resolve to a valid sObject type (215:13)
Error  common\objects\loan__Loan_Collateral__c\fields\Collateral__c.field-meta.xml            referenceTo value of 'common_Collateral__c' does not resolve to a valid sObject type (179:13)
Error  common\objects\loan__Loan_Collateral__c\fields\Current_LVR__c.field-meta.xml           Field Collateral__r does not exist. Check spelling. (192:13)
Error  common\layouts\loan__Loan_Collateral__c-loan__Loan Collateral Layout.layout-meta.xml   In field: field - no CustomField named loan__Loan_Collateral__c.Collateral__c found (17:26)
Error  common\profiles\FLS Free.profile-meta.xml                                              In field: recordType - no RecordType named orig_App_Approval_Waiver__c.Decision found (2668:29)
Error  common\profiles\FLS Free - Orig Migration.profile-meta.xml                             In field: recordType - no RecordType named orig_App_Approval_Waiver__c.Decision found (5138:29)
Error  common\profiles\FLS Free - Platform.profile-meta.xml                                   In field: recordType - no RecordType named orig_App_Approval_Waiver__c.Decision found (2660:29)
Error  common\profiles\Orig API %28Front End%29.profile-meta.xml                              In field: recordType - no RecordType named orig_App_Approval_Waiver__c.Decision found (2695:29)
ERROR running force:source:push:  Push failed.
```

When the salesforcedx plugin is downgraded to a different version (48.16.2):
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 48.16.2 (48.16.2)
├─ salesforcedx-templates 48.18.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
└─ salesforce-alm 48.17.0
sfdx-cli 7.81.0 (core)
```

Then, when the `force:source:push` is run, it deploys all the packageDirectories as a single deployment (see over 1200 components being deployed). This push works.
```
Job ID | 0Af2O00000bzfAlSAI
SOURCE PROGRESS | █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 24/1237 Components
```

The current workaround for the issue is to downgrade the version of the salesforcedx plugin. We understand that there is the issue where the dependencies are not specified correctly, but fixing this will take some time. In the meantime, we would like to use the latest CLI version if possible.

Is there a flag that we can toggle a deployAll behaviour on the latest CLI version?

**Comment by WillieRuemmele** [comment]
@seanong-athena sorry for the delayed response. So you have a circular dependency in your packages that no matter the order they're specified in the `push` would fail?

**Comment by seanong-athena** [comment]
Hi @WillieRuemmele Yes, they will fail no matter the order - since A depends on B and B depends on A - A will not be able to be pushed successfully.

And, according to the official documentation, this is expected behaviour:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_mpd.htm 

`When you run force:source:push, the CLI deploys the metadata in your multiple package directories in the order that they are listed in the packageDirectories section of your sfdx-project.`

My speculation is that v49 onwards of the CLI was fixed so that it behaves as described in the official documentation. Thus, we have since managed to get around this issue and hence you can close this enhancement request.

**Comment by bobalicious** [comment]
I am now encountering this issue and cannot resolve the circular dependency.

Is there a mechanism that will force the push to take place with all folders deployed at the same time?

**Comment by daveespo** [comment]
This issue is old and the comment from Feb 4, 2021 is no longer true. All package directories are aggregated and pushed in a single deployment UNLESS you explicitly set the `pushPackageDirectoriesSequentially` in sfdx-project.json

https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_mpd.htm

**Comment by bobalicious** [comment]
Thanks.  I suspect it's an issue with VSCode, rather than one with SFDX.
