### ISSUE TITLE
Can't Install specific version of sfdx on linux

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#754]
### Summary
For our CI process, we have SFDX pinned to a specific version (49.10.0) because salesforcedx plugin updates keep breaking our CI process so we want something stable.

However, as of mid last week, installation of salesforcedx@49.10.0 is failing with no error given.

### Steps To Reproduce:

1. Have a linux machine 
  (ous) Kernel Version: Linux 2f93efba8fff 4.15.0-1077-aws #81-Ubuntu SMP x86_64 Linux
1. Install SFDX with the following commands:
`mkdir sfdx
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
            ./sfdx/install
            sfdx
            sfdx plugins --core
            sfdx plugins:install salesforcedx@49.10.0`

### Expected result

salesforcedx plugin vesion 49.10.0 is installed

### Actual result

Install fails and exits with exit code 1 and the following output:

> sfdx plugins:install salesforcedx@49.10.0
> Successfully validated digital signature for salesforcedx.
> Finished digital signature check.
> Installing plugin salesforcedx... yarn add v1.22.10
> Installing plugin salesforcedx... info No lockfile found.Installing plugin salesforcedx... [1/4] Resolving packages...Installing plugin salesforcedx... [2/4] Fetching packages...Installing plugin salesforcedx... info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.Installing plugin salesforcedx... !

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.81.0-7b953c80d1 linux-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.6.0 (core)
├─ schema 1.0.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 50.1.0 (core)
├─ custom-metadata 1.0.10 (core)
├─ apex 0.1.4 (core)
└─ salesforce-alm 50.6.0 (core)
sfdx-cli 7.81.0 (core)

**OS and version**:
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch

**Comment by yippie** [comment]
Some more info:
`yarn global add sfdx-cli`

Fails with:

> error antlr4@4.9.0: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.20.0"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

This is very unexpected as sfdx reports to use 12.18.3 internally and we have been using the docker image `circleci/node:12` for ages now. The errors do seem to correspond with the image being upgraded to node 12.20 though.

**Comment by johnzhao9** [comment]
Running into the same issue here, we were on 49.9.2 for the same reason

**Comment by thvd** [comment]
Isn't this a duplicate of #746?

**Comment by yippie** [comment]
@thvd Not completely as I experienced the issue even after upgrading to Node14. Upgrading to Node14 does NOT fix the issue

**Comment by shetzel** [comment]
@yippie That's because the antlr lib also changed the location of their index.  Can you please try installing the `latest-rc` tag (which will become latest tomorrow morning)?  If that doesn't work please re-open this issue.

**Comment by asegura-copado** [comment]
@shetzel Are there any working links to download specific versions instead of the latest?
