### ISSUE TITLE
What does tooling/sandboxAuth do?

### ISSUE THREAD

**Issue by thebrettbarlow** [forcedotcom/cli#755]
**Is your feature request related to a problem? Please describe.**
I am working on tooling related to sandbox management and found the `sandboxAuth` REST Resource in the Tooling REST API. I found the endpoint in the sfdx source code. Specifically in [salesforce-alm/src/lib/org/sandbox/sandboxOrgApi.ts at line 196](https://github.com/forcedotcom/salesforce-alm/blob/5b9fdc67081cf85958278588b115ae08fcf64f44/src/lib/org/sandbox/sandboxOrgApi.ts#L196)

I cannot find any information about this REST Resource so I am concerned about how stable it is and am unsure about what it is exactly doing.

**What are you trying to do**
Build tooling to orchestrate our sandbox management processes.

**Describe the solution you'd like**
Documentation that explains the `sandboxAuth` REST Resource in the Tooling API.

**Describe alternatives you've considered**
I have sent requests and examined the responses. I will include notes in the additional context section below.

**Additional context**

Full endpoint being used: `/services/data/v50.0/tooling/sandboxAuth`
I am sending a POST

Required scopes in the ConnectedApp:
* Access and manage your data (api)
* Full access (full)
* Perform requests on your behalf at any time (refresh_token, offline_access)

Sample request:

```json
{
    "sandboxName":"sbxname",
    "clientId":"client_id_from_connected_app_goes_here",
    "callbackUrl":"http://localhost:1717/OauthRedirect"
}
```

Sample response:

```json
{
    "authCode":"auth_code_that_is_returned_from_the_api",
    "authUserName":"username_that_can_log_in_to_the_sandbox",
    "instanceUrl":"full_instance_url_including_my_domain",
    "loginUrl":"https://test.salesforce.com"
}
```

It is unclear exactly what `authCode` is. Experimentation proves that it is not a Session Id or a ConnectedApp client_id. Some research suggests that it is used by SFDX in force:auth and force:org:open commands.

After making this POST, authenticate to the sandbox using the same combination of `client_id` and `private_key` that was used to authenticate to the org that made the sandbox. The only difference is the `authUserName` from the response needs to be used because this is the username for the user in the sandbox that was just made.

**Comment by amphro** [comment]
I've asked the sandbox team. They are working on documentation.

**Comment by zerkz** [comment]
@thebrettbarlow I am exploring the same thing you are in terms of sandbox management. I wanted to ask if you could clarify how you authenticated using this endpoint against the target sandbox, using `client_id` and `Private_key`? Was this via just the JWT grant auth flow?

**Comment by zerkz** [comment]
it looks like it's used in part of the sandbox process to actually determine if its truly ready? 

https://github.com/forcedotcom/salesforce-alm/blob/83745351670a701762c6ecc926885564b8853357/src/lib/org/sandbox/sandboxOrg.ts#L153-L168

**Comment by zerkz** [comment]
the caller of `/sandboxAuth` must supply a sandbox that they created/refreshed. Otherwise you will get this. 

```
[
    {
        "message": "User must be sandbox creator to be authorized",
        "errorCode": "INVALID_USERID"
    }
]
```

**Comment by zerkz** [comment]
@amphro We're coming up on a year. Any update on documentation or ticket number we can reference? I think I've figured out what this endpoint does, but would love to hear it from SF's side.

**Comment by mshanemc** [comment]
FYI, @amphro went over to Trailhead world mid 2021.

I don't have any updates for you--the sandbox has chosen not to doc that endpoint.  We've used it multiple years.
https://github.com/forcedotcom/sfdx-core/blob/4e9dbdc95ee86e91a56aac912594009bfbd94770/src/org.ts#L1005 is the current implementation.

`authCode` is part of oauth https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_web_server_flow.htm&type=5

You can see what we do with it here: https://github.com/forcedotcom/sfdx-core/blob/562e947dd4bcd3bd984efe427198bd2e16f30278/src/authInfo.ts#L1024

You can think of it as a code that's embedded in a scratch/sandbox creation response that can be exchanged for a token (but for a limited time only).

**Comment by zerkz** [comment]
@mshanemc Thanks for the info, and the extra color. I'll see if I can get more info through my employers TAM. maybe I will write some docs myself ;), but I will share them here for anyone to unofficially benefit from if I do.
