### ISSUE TITLE
.js-meta.xml file name gets changed to .css-meta.xml

### ISSUE THREAD

**Issue by Paul-Browne** [forcedotcom/cli#761]
### Summary

When retrieving a component eg. `sfdx force:source:retrieve -m LightningComponentBundle:example` the example.js-meta.xml file has the name chaned to `example.css-meta.xml`

### Steps To Reproduce:

1. create a new lightning web component
2. add a .css file to that comp.
3. deploy
4. delete locally
5. retrieve from source `sfdx force:source:retrieve -m LightningComponentBundle:example`

### Expected result

meta xml should be called example.js-meta.xml

### Actual result

meta xml is called example.css-meta.xml

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):

```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.7.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.0 (core)
├─ schema 1.0.1 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
├─ apex 0.1.4 (core)
└─ salesforce-alm 50.7.0 (core)
sfdx-cli 7.82.0 (core)
```
**OS and version**: Mac 10.15.6 (19G2021)

**Comment by jayree** [comment]
@Paul-Browne have you tried to correct the filename, deploy and retrieve it again?

**Comment by RJPalombo** [comment]
@Paul-Browne, I have the same issue. When I manually rename {filename}.css-meta.xml to {filename}.js-meta.xml the source deploy works.

**Comment by rodriguezaaronjoseph** [comment]
I have had the same issue now for several months. I was hoping it'd be fixed soon. For me, the .js-meta.xml file does not change, but I get an incorrect .css-meta.xml file created in the component folder whenever I retrieve the component from the org.

@Paul-Browne , @jayree , @RJPalombo :

Does anyone know who we may be able to escalate this to to get it fixed?

**Comment by rohanshenoy96** [comment]
I got the same issue. Somehow 2 xml files were generated one with `{filename}.css-meta.xml` and another with `{filename}.js-meta.xml`. I deleted the `{filename}.css-meta.xml` file and pushed the code to org and it worked.

**Comment by mayforceconsulting** [comment]
Same problem.  Any updates on this?  Starting to become more prevalent it seems.

**Comment by rohanshenoy96** [comment]
@smaypilot If u have 2xml files. Delete the css.xml file. This solution worked for me

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9299508](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MQEJYA4/view)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9299509](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000MQFVYA4/view)
