### ISSUE TITLE
Can't create a scratch org

### ISSUE THREAD

**Issue by DidZo13** [forcedotcom/cli#762]
I'm getting an error message when I try to create a new scratch org, even if the sfdx project is freshly created with the default project-scratch-def.json file (not modified). The creation works when I delete the settings.
The same process works on another computer.
I already tried to reinstall completely sfdx (and it's config files).

**Error message :**
`Error shape/settings/Case.settings Case Error parsing file: Element {}emailToCaseSettings invalid at this location in type CaseSettings`

**Steps to get the error :**
Set a dev hub :
`sfdx force:auth:web:login --setdefaultdevhubusername`
--> Successful

Create a scratch org :
`sfdx force:org:create -f config\project-scratch-def.json --setalias test2 --durationdays 1 --setdefaultusername`
--> Error

**Comment by WillieRuemmele** [comment]
Hi @DidZo13 sorry for the late response - are you still seeing this issue? If you are could you add `--dev-debug` to the command and paste the output
