### ISSUE TITLE
Error: force:source:delete requires testlevel

### ISSUE THREAD

**Issue by jakobpack** [forcedotcom/cli#766]
### Summary

Using the command _force:source:delete_ throws an error requiring a testlevel parameter, but this command does not accept one.

### Displayed Error:

`ERROR running force:source:delete:  INVALID_OPERATION: testLevel of NoTestRun cannot be used in production organizations`

### Additional information

**SFDX CLI Version**: `7.82.1-0`

**OS and version**: `macOS 11.0.1`

**Comment by WillieRuemmele** [comment]
hi @jakobpack I haven't been able to reproduce this. Are you running this against a scratch org, sandbox, or production org? What metadata or file are you trying to delete?
