### ISSUE TITLE
Support for ARM M1 Mac within SFDX-CLI?

### ISSUE THREAD

**Issue by jeromegv** [forcedotcom/cli#768]
**Is your feature request related to a problem? Please describe.**
Is there any plan to support the new ARM M1 Mac architecture?

**Comment by amphro** [comment]
Yes @jeromegv - we are waiting to receive our M1 Macs so we can start testing. We will open an issue with the results of that testing effort with the known issues, progress, and timelines around supporting it. I will keep this issue open until that happens.

**Comment by amphro** [comment]
I've tested 7.98.0 mac installers on M1 Macs and have found no issues! Consider M1 supported. 

If you run into problems, please run `sfdx -v` and ensure it is on `node-v14.9.0` or higher. If the CLI is past that version and someone is still experiencing a problem, please file a new issue.
