### ISSUE TITLE
Sandbox Deletion Using the CLI is Stated as Successful When the Sandbox is not Deleted

### ISSUE THREAD

**Issue by IvanDavidHarris** [forcedotcom/cli#769]
### Summary

When a sandbox is created using a production org's Setup area, then authorized using the CLI's `force:auth:web:login` command and then deleted using the `force:org:delete` command, the output states that the sandbox has been successfully deleted when it hasn't. The sandbox is correctly removed from the list of CLI authorized orgs though.

This deletion behaviour is by design: _You can delete a sandbox using the CLI if it was authenticated when running org:create, org:clone, or org:status. Other sandboxes that you authenticated using auth:web:login or auth:jwt:grant also appear on the org list, but must be deleted using the sandbox detail page in your production org._ (from https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_create_clone_sandboxes.htm)

However, the successful message is misleading and causes confusion.

Note: Sandboxes created using a production org's Setup area can be correctly authorized using the `force:org:status` command, which creates the JSON file that includes the sandbox's associated production org. `force:org:delete` then deletes the sandbox and removes it from the list of CLI authorized orgs. Maybe this could be added to the documentation?

### Steps To Reproduce:

1.  Create a sandbox using a production org's Setup area.
1.  Authorize the sandbox using `force:auth:web:login` command.
1.  Delete the sandbox using the `force:org:delete` command.

### Expected result

A success message stating that the sandbox has been removed from the list of CLI authorized orgs but it will only have been deleted from the production org if it was authorized using the org:create, org:clone, or org:status commands.

### Actual result

The success message states that the scratch org was successfully deleted.

### Additional information

**SFDX CLI Version**: sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3

**SFDX plugin Version**: sfdx-cli 7.82.0 (core)

**OS and version**: macOS Big Sur Version 11.0.1 (20B29)

**Comment by ekapner** [comment]
Doc improvement opportunity: FYI @jshackell-sfdc @sbudhirajadoc

**Comment by jshackell-sfdc** [comment]
@mshanemc is on it, i reviewed.  Thanks Shane!

**Comment by Dane86NN** [comment]
I have this same issue, however, for me it will not delete sandboxes that are actually created via the CLI (Devhub). We use 1 npa for all the sandbox creation and deletion actions, but since the new release in the sandboxes this not working anymore. 

It will provide the same message as stated in this issue, but sandbox is not deleted

**Did some additional testing, running force:org:status before the delete command fixes our issue.**

**Comment by mshanemc** [comment]
the message is clear now about exactly what the command is doing:
https://github.com/salesforcecli/plugin-org/blob/ecf28350dce14d4837b4e439db14ea44f52f0494/messages/delete.md?plain=1#L49
