### ISSUE TITLE
Retrieve not allowed on channel ActivityEngagementVirtualChannel - HVS in scratch org

### ISSUE THREAD

**Issue by ozanbotanls** [forcedotcom/cli#771]
### Summary

When a scratch org (with HighVelocitySales feature enabled) gets created with the following definition file, attempting to pull (without even changing anything in the org) ends up giving the following error:

`Retrieve not allowed on channel ActivityEngagementVirtualChannel.`

![Screen Shot 2020-12-15 at 3 07 05 PM](https://user-images.githubusercontent.com/57642636/102267073-5fc44d80-3ee7-11eb-9b5b-6f8a95bb787c.png)

### Steps To Reproduce:

1. Create a scratch org with **HighVelocitySales** and **DevelopmentWave** features.
1. Open the org, navigate to **Setup > High Velocity Sales**, and enable the feature. (no way of doing it over a definition file as stated here: _"High Velocity Sales can be deployed in scratch orgs, but the settings for the feature can’t be updated through the scratch org definition file. Instead, configure settings directly in the High Velocity Sales app."_ https://help.salesforce.com/articleView?id=hvs_considerations.htm&type=5)
1. Without doing anything else, run `sfdx force:source:pull`

### Expected result

I should be able to retrieve automatically created metadata of type _WaveDashboard, WaveDataset, WaveDataflow, WaveApplication, WaveXmd_, etc

### Actual result
The following automatically gets added to the org:

STATE /                               TYPE                                                    /                                              PROJECT PATH
Remote Add  / **ActivityEngagementVirtualChannel_LeadChangeEvent**            /         PlatformEventChannelMember
Remote Add  / **ActivityEngagementVirtualChannel_TaskChangeEvent**                    /   PlatformEventChannelMember
Remote Add  / **ActivityEngagementVirtualChannel_EmailMessageChangeEvent**     / PlatformEventChannelMember
Remote Add  / **ActivityEngagementVirtualChannel_ContactChangeEvent**             /    PlatformEventChannelMember
Remote Add  / **ActivityEngagementVirtualChannel_ListEmailChangeEvent**          /     PlatformEventChannelMember

And when you pull;

**If your API Version greater than 46.0**
You will be given an error message saying `Retrieve not allowed on channel ActivityEngagementVirtualChannel.`

**If your API Version less than 47.0**
You will be given an error message saying `Entity type 'PlatformEventChannelMember' is not available in this api version`
(which is explained here: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_platformeventchannel.htm)

### Additional information

**SFDX CLI Version**: 7.82.1-0

**SFDX plugin Version**
@oclif/plugin-autocomplete 0.2.0
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.7.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.9
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-scanner 2.4.0
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.4.5 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.1 (core)
├─ apex 0.1.4 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ schema 1.0.2 (core)
├─ templates 50.1.0 (core)
├─ custom-metadata 1.0.10 (core)
└─ salesforce-alm 50.7.1 (core)
sfdx-cli 7.82.1-0 (core)
sfdx-destruction 1.0.0-beta.3
sfdx-git-delta 4.1.0
shane-sfdx-plugins 4.43.0
├─ @mshanemc/sfdx-sosl 1.1.0
└─ @mshanemc/plugin-streaming 1.1.7

**OS and version**: macOS Big Sur - Version 11.0.1

**Comment by ls-tasos-papadatos** [comment]
I am experiencing the same issue. Any help would be really appreciated 👍

**Comment by ozanbotanls** [comment]
@clairebianchi any suggestions for this?

**Comment by WillieRuemmele** [comment]
could you try running the command with the `--dev-debug` flag and post the output here? That will help us narrow down the issue to a server side, metadata, or cli issue

**Comment by tntwist** [comment]
Hi @WillieRuemmele,
i attached the requested output with the ``--dev-debug`` flag.
[sfdx_error.txt](https://github.com/forcedotcom/cli/files/6375270/sfdx_error.txt)

**Comment by rajnishsongara** [comment]
Dear All, I am also getting same kind of error- Any luck on this?

**Comment by mshanemc** [comment]
That type (ActivityEngagementVirtualChannel) is not in the metadata coverage report.
https://developer.salesforce.com/docs/metadata-coverage/

So if you don't need to use it and it's only causing problems, put it in your forceignore file
