### ISSUE TITLE
ERROR running force:project:create:  Invalid version: "1"

### ISSUE THREAD

**Issue by Swizzle4372** [forcedotcom/cli#775]
### Summary

Unable to create an sfdx project and receive the following error in terminal:
ERROR running force:project:create:  Invalid version: "1"

I've reinstalled the cli multiple times, updated it and its plugins, i've tried reinstalling xcode and the command line tools but nothing has helped.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.0 (core)
├─ schema 1.0.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 50.1.0 (core)
└─ salesforce-alm 50.7.0 (core)
sfdx-cli 7.82.0 (core)

**OS and version**:
macOS Catalina

**Comment by shetzel** [comment]
What's the exact command you're running with all parameters?  Appending `--dev-debug` to your command will provide debug output that might be helpful in determining the problem.

**Comment by Swizzle4372** [comment]
Thanks for your response.  I ran the following command:
sfdx force:project:create --projectname mywork --template standard --dev-debug

And received this huge response.  Had a look to see if there's anything obvious to me, but couldn't get anything useful from it myself!

[log.txt](https://github.com/forcedotcom/cli/files/5734869/log.txt)

**Comment by KevinGossentCap** [comment]
@ministe2003 
I remember having different bad behaviour resulting from #746 
if you update, do you still have the same problem ?

**Comment by brpowell** [comment]
Hi @ministe2003. In the current working directory where you are running the project create command, does somewhere up the path exist a package.json file with the version property specified as `"version": "1"`?

**For example:**

Running `force:project:create` in this directory:
`/Users/steven.hayhurst/Desktop/sfdx/`

When a package.json file exists here:
`/Users/steven.hayhurst/package.json`

and in that file is `"version": "1"`, which is an invalid semver pattern.

There is a weird behavior of the yeoman-generator module that powers the template create commands where it traverses up the current working directory and validates some package.json file it finds. You can either delete this file or set the version to a valid semver number.

**Comment by Swizzle4372** [comment]
> Hi @ministe2003. In the current working directory where you are running the project create command, does somewhere up the path exist a package.json file with the version property specified as `"version": "1"`?
> 
> **For example:**
> 
> Running `force:project:create` in this directory:
> `/Users/steven.hayhurst/Desktop/sfdx/`
> 
> When a package.json file exists here:
> `/Users/steven.hayhurst/package.json`
> 
> and in that file is `"version": "1"`, which is an invalid semver pattern.
> 
> There is a weird behavior of the yeoman-generator module that powers the template create commands where it traverses up the current working directory and validates some package.json file it finds. You can either delete this file or set the version to a valid semver number.

Wow, this is it!  I found a handful of package.json files in the folders above, one was exactly where you predicted and contained that version line.  Deleted the file and the problem has now resolved, fantastic, thank you very much!

**Comment by brpowell** [comment]
Wonderful, glad we got it resolved!
