### ISSUE TITLE
Support the WebStoreTemplate metadata object

### ISSUE THREAD

**Issue by peterTrifecta** [forcedotcom/cli#776]
I did a force pull of source from a scratch org with the B2BCommerce feature enabled and got the following error:

> We can’t retrieve the specified metadata object: WebStoreTemplate. Certain metadata types, like Capricorn_B2B_Store are not currently supported by the CLI.
> File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type

sfdx --version: sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3

I was using a scratch org setup as part of working through the Exercise Guides provided by Salesforce in the "B2B Commerce on Lightning Experience" partner community group.

**Comment by mshanemc** [comment]
this is supported now.  Please open an issue if you have any problems with it.
