### ISSUE TITLE
Incorrect warning message when running sfdx force:org:create command

### ISSUE THREAD

**Issue by steals** [forcedotcom/cli#777]
### Summary

When `sfdx force:org:create command` command is executed the following error message is displayed:

> WARNING: Warning: If you're using Contacts to Multiple Accounts, beginning with the Spring ’21 release, the feature isn't automatically enabled. You must manually enable the setting for new scratch orgs. Enable the setting in one of these ways: update the Account Settings page in Setup, add the enableRelateContactsToMultipleAccounts setting to your scratch org definition file, or enable it via Metadata API.

it mentioned `enableRelateContactsToMultipleAccounts` parameter in scratch org definition file. But the correct name of the parameter is 'enableRelateContactToMultipleAccounts' without `s` in the middle. See https://developer.salesforce.com/docs/atlas.en-us.228.0.api_meta.meta/api_meta/meta_accountsettings.htm

### Steps To Reproduce:

1.  Create an empty project or use the existing one.
2. Add `ContactsToMultipleAccounts` to the list of "features" in the scratch org definition file
3. Run sfdx force:org:create command -f config/project-scratch-def.json

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 
sfdx-cli 7.82.0 (core)

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) 
salesforcedx 50.7.1
├─ schema 1.0.1
├─ templates 50.1.0
├─ salesforce-alm 50.7.1
├─ custom-metadata 1.0.10
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
└─ apex 0.1.4

**OS and version**: MacOS Big Sur

**Comment by mshanemc** [comment]
I'm closing this issue.  That warning disappears in v51 so there's no point fixing the typo.
