### ISSUE TITLE
Support the Audience metadata object

### ISSUE THREAD

**Issue by peterTrifecta** [forcedotcom/cli#778]
I ran a scratch org pull after working on Exercise Guide 2 from the "B2B Commerce on Lighting Experience" partner community group: https://partners.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000LovTSAS and got this error:
> We can’t retrieve the specified metadata object: Audience. Certain metadata types, like B2B_Super_User are not currently supported by the CLI.
> File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type

#776 is similar.

sfdx --version: sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3

**Comment by amphro** [comment]
Dup of #470
