### ISSUE TITLE
Configurable Scratch Org Definitions

### ISSUE THREAD

**Issue by robert-strunk** [forcedotcom/cli#779]
**Is your feature request related to a problem? Please describe.**
Not so much a problem per se, but there are just way too many settings that can be used to shape a scratch org. Reviewing the documentation is a bit much imo. 

**What are you trying to do**
Fully utilize the functionality that Salesforce is extending to us devs to be able to customize a scratch org. 

**Describe the solution you'd like**
I think it would be super awesome and a huge value add to have a UI that is only exposed in the dev hub org that allows a user to build a "default" scratch org definition file. Quite frankly I think it is a bit much to poke around all the settings in the documentation. Would be really nice to build that declaratively in the dev hub and then maybe have that as a default when creating scratch orgs. 
Obviously any local definition files could override if the path is referenced in the command.

Just a random thought.

**Comment by WillieRuemmele** [comment]
This UI would be great, but outside the scope of what our team could provide (plus, we're terrible at designing UI 😉 ) submitting this via a different Salesforce idea intake form (idea exchange) would be your best route
