### ISSUE TITLE
Words that have an accent (E.G. â, ã é ó ú ç) are being transformed into '�' characters

### ISSUE THREAD

**Issue by GuiuGaldino** [forcedotcom/cli#780]
### Summary

Words that have an accent (E.G. â, ã é ó ú ç) are being transformed into '�' characters.

### Steps To Reproduce:

1.  Create a custom metadata.
2. Create a new text field.
3. Retrieve the metadata using force:source:retrieve
3. Create a CSV to insert records to your metadata. It is important to notice that the field must contain words with accent. (Coração, Árvore, Hífen, Caçador).
4. Execute sfdx force:cmdt:record:insert and pass your CSV as parameter. 

### Expected result

the tag <value xsi:type="xsd:string"> should contain the same words of the CSV Column.                                                

### Actual result

Accent character are replaced by �.

### Additional information

_Feel free to attach a screenshot_.

**CSV Value:**
Apenas cotação do valor da prorrogação.

**Metadada created via CLI:**

![image](https://user-images.githubusercontent.com/13954594/103240084-11bf3900-492e-11eb-94fb-f95fc7bcb8df.png)

**sfdx --version:**
sfdx-cli/7.82.0-3d0c527ac6 win32-x64 node-v12.18.3

**SFDX plugin Version**
sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.0 (core)
├─ templates 50.1.0 (core)
├─ schema 1.0.1 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.7.0 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.82.0 (core)

**OS and version**:
Windows 10

**Comment by shetzel** [comment]
I'm assuming the repro steps should include running a retrieval command of some kind.  Does it happen with `force:mdapi:retrieve` as well as `force:source:retrieve` and `force:source:pull`?

**Comment by GuiuGaldino** [comment]
Yes. I'm sorry that I did not add this instruction. I updated the instructions.

**Comment by KevinGossentCap** [comment]
@GuiuGaldino it could help others if you also add which charset you use for your file (utf-8, western, ansi, etc.).
Could help because it really looks like a charset problem and maybe a workaround could be to force the use the right one (utf-8?)

**Comment by GuiuGaldino** [comment]
@KevinGossentCap I tried different chartsets but the results were the same.

**Comment by mshanemc** [comment]
possibly related to also https://github.com/forcedotcom/cli/issues/631

**Comment by cristiand391** [comment]
I'm unable to repro this on macos and latest sf:
@salesforce/cli/2.29.5 darwin-x64 node-v20.10.0

1) create custom md in org
2) retrieve
3) `sf cmdt generate records` (this used to be the `force:cmdt:record:insert`).

![Screenshot 2024-02-16 at 14 28 16](https://github.com/forcedotcom/cli/assets/6853656/0aaf9532-3c49-4a21-88fa-6535ce599c83)

also tried with other accents and they stay the same. If someone else can repro please create a new issue with a repo we can use to reproduce.
