### ISSUE TITLE
Bash autocomplete doesn't work

### ISSUE THREAD

**Issue by surajp** [forcedotcom/cli#784]
### Autocomplete script generated by the CLI, does not work in Bash

_The autocomplete script generated by running `sfdx autocomplete` does not work as expected due to colon (':') being  a CWORD separator_.

### Steps To Reproduce:

**Repository to reproduce:** NA

1.  Run `sfdx autocomplete` and follow the instructions to copy the said command to your `~/.bashrc` file. 
2.  Run `source ~/.bashrc`
3.  Type `sfdx force:light` followed by <TAB><TAB>

### Expected result

_The command should autocomplete and `sfdx force:lightning:` should be output to the terminal_.

### Actual result

_Nothing happens_.

### Additional information

_Typing `sfdx ` followed by <TAB><TAB> seems to work. However, the commands and the flags do not autocomplete. This seems to be an issue with colon being one of the COMP_CWORD separators and other issues with the script. I've managed to get a working version with some tweaks here https://github.com/surajp/dotfiles/blob/master/sfdx.bash . Please make these changes to the script generated by the CLI_.

**SFDX CLI Version** (sfdx-cli/7.82.1-0 linux-x64 node-v12.18.3)

**SFDX plugin Version** (salesforcedx 50.1.1 (pre-release))

**OS and version**: Debian GNU/Linux 10 (buster)

**Comment by maaaaarco** [comment]
I had a similar issue, but was related to another tool... Following this guide I was able to resolve the autocomplete: https://sourabhbajaj.com/mac-setup/BashCompletion/

**Comment by WillieRuemmele** [comment]
@surajp did maaaaarco's suggestion work? I believe this really should be an issue for https://github.com/oclif/plugin-autocomplete. Feel free to close or reassign accordingly

**Comment by surajp** [comment]
@WillieRuemmele I already modified the script to work for me. I've linked to the script as well in my issue description. I've raised this issue so you guys can fix the script generated by `sfdx autocomplete`

**Comment by mshanemc** [comment]
Bash and autocomplete, including your example (well, using spaces instead of colons these days) seems to work fine.

`zsh` has a much richer autocomplete experience, and is worth checking out.

**Comment by surajp** [comment]
Yes, it seems to be working fine now with spaces instead of colons. Flag completion also seems to be working. It doesn't work, however, if you switch the order of the sub-commands. Appreciate the suggestion, to use zsh. I use my own autocomplete script for both bash and powershell that supports instantaneous fuzzy search for commands and flags. The bash script also shows help documentation and example previews in real-time.
