### ISSUE TITLE
sfdx force:user:password:generate - The requested Resource does not exit  API 51.0

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#798]
### Summary

Can't use `sfdx force:user:password:generate` with API 51.0

![image](https://user-images.githubusercontent.com/55927613/104625111-49e3ad00-568c-11eb-89ca-7a2af111092d.png)

When changing to API 50.0 it works

![image](https://user-images.githubusercontent.com/55927613/104625913-2ec56d00-568d-11eb-9e5a-9e6f71def41c.png)

### Steps To Reproduce:

1 - Set sfdx api to 51.0
2 - try to generate user password for a Scratch Org
3 - Set api to 50.0
4 - run the command again
5 - Check it worked

### Expected result

Should create the password

### Actual result

It says the resource does not exist

### Additional information

![image](https://user-images.githubusercontent.com/55927613/104625320-8ca58500-568c-11eb-8879-728e680bdf65.png)

**OS and version**: Windows 10

**Comment by amphro** [comment]
What version is [your instance](https://help.salesforce.com/articleView?id=000317969&type=1&mode=1)?

**Comment by AllanOricil** [comment]
> What version is [your instance](https://help.salesforce.com/articleView?id=000317969&type=1&mode=1)?

51.0

I created the Scratch Org using release:Preview

**Comment by AllanOricil** [comment]
@amphro The instance is CS96

![image](https://user-images.githubusercontent.com/55927613/104709202-88be4500-5716-11eb-8558-98b153fd9d68.png)

**Comment by AllanOricil** [comment]
I can't run the command to create a community. 

![image](https://user-images.githubusercontent.com/55927613/104713074-464b3700-571b-11eb-9a80-c7ce3ad82e07.png)

**Comment by AllanOricil** [comment]
I can't create a community. Same problem

![image](https://user-images.githubusercontent.com/55927613/104713161-5fec7e80-571b-11eb-948b-cc2684eb53f1.png)

**Comment by mshanemc** [comment]
@AllanOricil are you able to see the password policies in your org, specifically whether `Allow use of setPassword() API for self-resets` is checked or unchecked?
https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/admin_password.htm

This setting can't be re-enabled via ui or config/mdapi if it's disabled because v51 of the mdapi deprecates the setting.  https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_securitysettings.htm

**Comment by mshanemc** [comment]
I have an update on this.

This is no longer going to work in v51/Spring21
```
"securitySettings": {
   "passwordPolicies": {
      "enableSetPasswordInApi": true
   }
}
```

It's [now moved to the Features section](https://help.salesforce.com/articleView?id=release-notes.rn_scratch_org_features.htm&type=5&release=230) [only available on scratch orgs]

"features": ["EnableSetPasswordInApi", ....],

**Comment by mshanemc** [comment]
@AllanOricil can you try your org again using the updated scratchDef to make sure it's working?

**Comment by AllanOricil** [comment]
@mshanemc I was gonna try it, but I can't even update sfdx

![image](https://user-images.githubusercontent.com/55927613/106027783-232d6980-60c3-11eb-9975-ea3933cf3cb5.png)

**Comment by AllanOricil** [comment]
@mshanemc  it actually updated, but it threw that error message

![image](https://user-images.githubusercontent.com/55927613/106027949-46581900-60c3-11eb-9816-07bca908da9c.png)

**Comment by AllanOricil** [comment]
Ok, after updating sfdx to 7.84.2, I first configured SFDX to use apiVersion=51.0, then I tried to create a SO with the following configs:

````json
{
  "orgName": "Demo company",
  "edition": "Developer",
  "release": "Preview",
  "features": [
    "Communities", 
    "ContactsToMultipleAccounts",
    "DebugApex",
    "EnableSetPasswordInApi"
  ],
  "settings": {
    "languageSettings": {
      "enableTranslationWorkbench":  true,
      "enableEndUserLanguages": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    },
    "communitiesSettings": {
      "enableNetworksEnabled": true
    },
    "orgPreferenceSettings": {
      "s1DesktopEnabled": true
    }
  }
}

````

But I got this error

![image](https://user-images.githubusercontent.com/55927613/106028311-b1a1eb00-60c3-11eb-9e64-cd93426aba86.png)

**Comment by AllanOricil** [comment]
@mshanemc after changing to apiVersion=50.0 the SO was created with no problem and I was, again, able to generate the password

![image](https://user-images.githubusercontent.com/55927613/106028943-7a800980-60c4-11eb-984d-4e8c6456a850.png)

The problem now is that I can't even create a SO using API v51.0. Before I was able to do it and the only part that was failing was the password generation.

**Comment by mshanemc** [comment]
This was fixed and shipped.  Re-open or open a new issue if you're still seeing it.
