### ISSUE TITLE
Unable to set maxQueryLimit config value

### ISSUE THREAD

**Issue by quinnpatrick** [forcedotcom/cli#799]
### Summary
I'm attempting to change the maxQueryLimit config value.

### Steps To Reproduce:
1.  Execute "sfdx config:set maxQueryLimit=15000"

### Expected result
Numeric value should be saved and visable via "sfdx config:list"

### Actual result
`ERROR running config:set:  Invalid config value. Specify a valid number, for example, 150000`

### Additional information
![image](https://user-images.githubusercontent.com/22944383/104642083-2d397c00-5670-11eb-8bcd-159c9f9d1f7c.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 
`sfdx-cli/7.82.0-3d0c527ac6 win32-x64 node-v12.18.3`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 50.1.0 (core)
├─ salesforce-alm 50.7.0 (core)
└─ schema 1.0.1 (core)
sfdx-cli 7.82.0 (core)
```

**OS and version**:
Windows 10 Enterprise - Version	10.0.19041 Build 19041

**Comment by WillieRuemmele** [comment]
merged into core with https://github.com/forcedotcom/sfdx-core/pull/358 should be available in sfdx-cli latest-rc tomorrow
