### ISSUE TITLE
Add -x, --sandbox flag to force:auth:web:login for sandbox logins

### ISSUE THREAD

**Issue by alan-morey** [forcedotcom/cli#8]
**What are you trying to do**
I would like to be able to specify a `-x, --sandbox` flag instead having to type out `https://test.salesforce.com` for the `-r, --instanceurl` flag, each time I want to authenticate with a sandbox org. 

_Examples:_
```
$ sfdx force:auth:web:login --sandbox --setalias sandbox1
$ sfdx force:auth:web:login -x -a sandbox2
```

**Comment by idanblich** [comment]
+1

**Comment by clairebianchi** [comment]
Thank you for the feedback

**Comment by mshanemc** [comment]
with EnhancedDomains, this becomes a less useful feature (https://test.salesforce.com wouldn't be used, the domain of the sandbox would be, and in some cases has to be used instead)

**Comment by alan-morey** [comment]
Thanks @mshanemc, that makes sense.

Since enabling Enhanced Domains I find that it's always best to provide the sandbox specific URL anyway.

So I always login with the sandbox specific URL as follows:

```
sfdx auth:web:login -a mysandbox -r https://myorg--mysandbox.sandbox.my.salesforce.com
```
