### ISSUE TITLE
Self reference data export

### ISSUE THREAD

**Issue by manujCLI** [forcedotcom/cli#80]
### Summary

I am trying to export data of record which has self reference(lookup), Is it possible to do using sfdx force:data:tree:export command?

Here is a sample command used.
sfdx force:data:tree:export -p -q "select id,Name,test__Object_Type__c,test__Rule_Json__c,test__Enabled__c,External_Id__c,test__Parent_Record_Id__c,test__Rule_Priority__c,(select id,Name,test__Object_Type__c,test__Rule_Json__c,test__Enabled__c,External_Id__c,test__Parent_Record_Id__c,test__Rule_Priority__c from test__Rule__r ) from test__Rule__c "

### Steps To Reproduce:

1.Here is a sample command used.
sfdx force:data:tree:export -p -q "select id,Name,test__Object_Type__c,test__Rule_Json__c,test__Enabled__c,External_Id__c,test__Parent_Record_Id__c,test__Rule_Priority__c,(select id,Name,test__Object_Type__c,test__Rule_Json__c,test__Enabled__c,External_Id__c,test__Parent_Record_Id__c,test__Rule_Priority__c from test__Rule__r ) from test__Rule__c "

### Expected result

records should have been exported

### Actual result

ERROR running force:data:tree:export:  Overriding test__Rule__c reference for a2R0R000000iPLiUAM: existing test__Rule__cRef2, incoming test__Rule__cRef19

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.3.0-94ecf2d5ee win32-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.10.1 (core)
├─ force-language-services 45.10.0 (core)
└─ salesforce-alm 45.13.0 (core)

sfdx-cli 7.3.0 (core)
**OS and version**:
Windows 10

**Comment by clairebianchi** [comment]
@manujCLI the best place to find answers to questions like these is the Salesforce DX Trailblazer community https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1
