### ISSUE TITLE
Deploying project via SFDX spawns new Process Builder versions

### ISSUE THREAD

**Issue by WellWisherCoder** [forcedotcom/cli#800]
### Summary

One problem we encountered is, that when we deploy changes to org via sfdx force:source:deploy, sometimes a new inactive Process Builder version is spawned, even though a Process Builder is not changed. It doesn't happen for every Process Builder, and it's not persistent sometimes a deployment spawns new version of PB every deployment, sometimes it doesnt. The problem results in hitting Maximum flow versions reached error.

### Steps To Reproduce:

Deploy a Flow using sfdx cli to same org or different org having the same flow metadata. NOTE: This issue is happening with certain flows only. I started noticing this issue from 13th JAN 2021, with a flow api version 50.0

### Expected result

No new flow should get created unless the flow metadata file changes

### Actual result

New Flow version got created

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.84.2-a2868a68d5 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.13.3 (core)
├─ schema 1.0.3 (core)
├─ user 1.0.5 (core)
├─ limits 1.0.2 (core)
├─ salesforce-alm 50.13.1 (core)
├─ templates 50.4.0 (core)
├─ custom-metadata 1.0.11 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.84.2 (core)
sfpowerkit 2.4.13

**OS and version**:  WIN 10

**Comment by maaaaarco** [comment]
We had a similar issue... Have you tried retrieve the flow from the Org using the newer API version `--apiversion 50.0` ?
The reason for us was that one of the latest releases added new tags to the Flow metadata type... Not having those tags does not affect the general functionality of your flow but it's enough to spawn new versions...
I believe this has nothing to do with the CLI but more with the Metadata API that the CLI uses for deploy/retrieve.

**Comment by WellWisherCoder** [comment]
Yup, you are right --apiversion 51.0 did the trick. 
had to use sfdx force:config:set apiVersion=51.0 to set the default cli version.
the sfdx-project.json sourceApiVersion did not work, had to change the apiVersion in sfdx-config.json

**Comment by WillieRuemmele** [comment]
@WellWisherCoder I'm glad that fixed your issue! We'll keep this issue open for anyone else that might be seeing this behavior
