### ISSUE TITLE
force:user:permset:assign fails on 7.84.2

### ISSUE THREAD

**Issue by jcory** [forcedotcom/cli#802]
### Summary

The permission set assignment command fails on the latest version of the CLI.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

1.  Follow the "Installing Dreamhouse using a Scratch Org" steps (outlined [here](https://github.com/trailheadapps/dreamhouse-lwc#installing-dreamhouse-using-a-scratch-org))
1.  After successfully pushing the source code, run the following command: `sfdx force:user:permset:assign -n dreamhouse`

### Expected result

The permission set is assigned to the default user.

### Actual result

The command fails with the error `Permission set "d" not found in target org. Do you need to push source?`

### Additional information
![image](https://user-images.githubusercontent.com/20194903/104651068-c1114500-567c-11eb-8b14-d0a13ef9d0dc.png)

I noticed this in a separate repository, and used Dreamhouse for simplicity/replication's sake.

**SFDX CLI Version**:
sfdx-cli/7.84.2-a2868a68d5 darwin-x64 node-v12.18.3

**SFDX plugin Version**:
7.84.2

**OS and version**:
macOS Big Sur (v11.1)

**Tracked under @W-8716914@**

**Comment by amphro** [comment]
@jcory we are trying to identify why the core plugin did not get updated. Until we are able to patch, you can run `sfdx plugins:install user` to fix the issue.

**Comment by mhail** [comment]
Another related issue I have seen with `force:user:permset:assign`  is using the `--onbehalfof` switch causes error `running force:user:permset:assign:  No AuthInfo found for name` + the username specified.

Same version. 7.84.2

EX:
```
sfdx force:user:permset:assign -n B2B_Commerce_User --onbehalfof sbuys-f0f94f12089c@example.com
ERROR running force:user:permset:assign:  No AuthInfo found for name sbuys-f0f94f12089c@example.com
```

 I switched back to `7.82.1-0` via NPM (`npm install sfdx-cli@7.82.1-0 --global`).  until a fix is in for 7.84.x

**Comment by amphro** [comment]
It should be tracked under @W-8716914@

**Comment by amphro** [comment]
Please see #811 - we will make sure this is addressed in the next release.

**Comment by bdovh** [comment]
I think we can use another workaround without having to install any plugin.

Just create a file scripts/apex/assignCurrentUser.apex with a code

PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'PermName'];
List<PermissionSetAssignment> psas = new List<PermissionSetAssignment>();

for (Id uid: new List<Id>{UserInfo.getUserId()}) {
    psas.add(new PermissionSetAssignment(AssigneeId = uid, PermissionSetId = ps.Id));
}
insert psas;
and the bash file assignCurrentUser.sh

code=$(cat scripts/apex/assignCurrentUser.apex)        
echo "${code/PermName/$1}" > temp.apex
sfdx force:apex:execute -f temp.apex
rm temp.apex
and then just execute it

./assignCurrentUser.sh PermissionSetName

**Comment by mohametso** [comment]
Hi this is really  blocking however the workaround works well @bdovh  thanks

**Comment by WillieRuemmele** [comment]
this is fixed in the `latest-rc` release of the cli or v1.0.9 of `plugin-user`
`npm install sfdx-cli@latest-rc --global` or `sfdx plugins:install user`

**Comment by po640938** [comment]
I tried using `sfdx plugins:install user` but now everytime I run an sfdx command I get this:
<img width="1106" alt="Screen Shot 2021-02-11 at 10 21 46 AM" src="https://user-images.githubusercontent.com/47507805/107657346-1710e280-6c53-11eb-8a4a-5743b07efe67.png">
