### ISSUE TITLE
SFDX Auth Url not valid after 14/01 release

### ISSUE THREAD

**Issue by albertocabo** [forcedotcom/cli#805]
### Summary

Today our deployment started failing with the error "force:auth:sfdxurl is not a sfdx command" that is reported in another issue. After modifying "force:auth" to "auth" as a suggested workaround that issue was solved but we then got an error for invalid SFDX auth url. 

`ERROR running auth:sfdxurl:store:  Invalid sfdx auth url. Must be in the format `force://<clientId>:<clientSecret>:<refreshToken>@<loginUrl>`. The instanceUrl must not have the protocol set.`

The url was the same that used to work. I even tested in local where I didn't have updated to the new version and the url still worked. 

### Steps To Reproduce:

`sfdx auth:sfdxurl:store -f credentials/develop-org.json -a targetORG`

### Expected result

Auth succeeded 

### Actual result

`ERROR running auth:sfdxurl:store:  Invalid sfdx auth url. Must be in the format `force://<clientId>:<clientSecret>:<refreshToken>@<loginUrl>`. The instanceUrl must not have the protocol set.`

### Additional information

_Feel free to attach a screenshot_.

sfdx-cli/7.83.0-eba9c6a927 linux-x64 node-v12.18.3

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.9.1 (core)
├─ schema 1.0.1 (core)
├─ limits 1.0.0 (core)
├─ salesforce-alm 50.9.0 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.83.0 (core)

  Ubuntu
  18.04.5
  LTS

**Comment by amphro** [comment]
Please see #811 - we will make sure this is addressed in the next release.
