### ISSUE TITLE
force:user:display missing information and inconsistent

### ISSUE THREAD

**Issue by yippie** [forcedotcom/cli#809]
### Summary

force:user:display no longer returns all information and --json and not return VERY different information

### Steps To Reproduce:

1.  create a scratch org
1. run sfdx force:user:password:generate
1. run `sfdx force:user:display`
1. run `sfdx force:user:display --json'

### Expected result

The two commands to show the same info but in different formats

### Actual result

Can get user info, but not password, if --json is left off. Using --json, get ONLY username and password.

### Additional information
**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 
sfdx-cli/7.84.2-a2868a68d5 darwin-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@mavens/mic-cli-plugin 8.1.0-0 (link) /Users/kaiamundsen/workspace/MedInfoCloud-CLI-Plugin
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-scanner 2.4.0
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.13.3 (core)
├─ schema 1.0.3 (core)
├─ limits 1.0.2 (core)
├─ apex 0.1.4 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.11 (core)
├─ salesforce-alm 50.13.1 (core)
└─ templates 50.4.0 (core)
sfdmu 3.7.21
sfdx-cli 7.84.2 (core)
texei-sfdx-plugin 1.9.2
user 1.0.7

**OS and version**:
macOS Big Sur 11.1

**Comment by amphro** [comment]
@mshanemc do you know if this is resolved in your display refactor?

**Comment by amphro** [comment]
@yippie I haven't tried this yet but did it used to work and no longer does in 7.84?

**Comment by amphro** [comment]
@yippie We are not seeing the same thing. We see ALL information in both cases except we don't see the password in either case. We will fix that under this issue. If you confirm what you are seeing and can provide more information like `--dev-debug` output and contents of the auth file in `~/.sfdx/, we can look into it further.

**Comment by yippie** [comment]
@amphro I am no longer seeing the behavior even though I am still on the same versions. Now I get the same information, including having the password, in both with and without JSON. Was this possibly a server side issue? We have been having all sorts of issues with scratch orgs lately....

**Comment by jayree** [comment]
@yippie are you on the `latest-rc` or `latest` version of the `salesforcedx` plugin?

**Comment by yippie** [comment]
I am on the same versions as is listed in the issue. I did not install latest-rc so I think that means latest

**Comment by amphro** [comment]
Odd. It could be a server thing... I'm not sure. In any case, we will continue to use this issue to track the missing password in some situations.

**Comment by WillieRuemmele** [comment]
this is fixed in the `latest-rc` release of the cli or v1.0.9 of `plugin-user`
`npm install sfdx-cli@latest-rc --global` or `sfdx plugins:install user` and you should be able to see the correct information
