### ISSUE TITLE
Apex Code Coverage results show inaccurate classes

### ISSUE THREAD

**Issue by dobrusia** [forcedotcom/cli#812]
### Steps To Reproduce: 
1. Run Apex Tests for ClassA
2. Review Code Coverage returned by cli
### Expected result

Cli should return code coverage for ClassA.

### Actual result
Cli returns code coverage for ClassB or ClassC that are being used in the trigger or are global constants/utility classes, but not for ClassA.
Another runs return ClassD or another randomly selected, loosely related classes, but rarely actual coverage of **ClassA**.

#### First run

Below example shows run for AwesomeCalculatorTest class, what is a test class dedicated to AwesomeCalculator class. However, the result shows "the class being tested" only utility class calculatorServices, not the actual AwesomeCalculator.

```
=== Apex Code Coverage for Test Run 7071v00008jzm2m
TEST NAME                          CLASS BEING TESTED  OUTCOME  PERCENT  MESSAGE  RUNTIME (MS)
─────────────────────────────────  ──────────────────  ───────  ───────  ───────  ────────────
AwesomeCalculatorTest.testCallout  calculatorServices  Pass     26%               66          


=== Apex Code Coverage by Class
CLASSES             PERCENT  UNCOVERED LINES
──────────────────  ───────  ───────────────
calculatorServices  26%      6,7,8,13,14... 

```

#### Second run
Second run for some reason returns correct class, but does not return dependent classes.
```
=== Apex Code Coverage for Test Run 7071v00008jzm7D
TEST NAME                          CLASS BEING TESTED  OUTCOME  PERCENT  MESSAGE  RUNTIME (MS)
─────────────────────────────────  ──────────────────  ───────  ───────  ───────  ────────────
AwesomeCalculatorTest.testCallout  AwesomeCalculator   Pass     100%              28          


=== Apex Code Coverage by Class
CLASSES            PERCENT  UNCOVERED LINES
─────────────────  ───────  ───────────────
AwesomeCalculator  100%         
```

### Additional information
The behaviour is completely random, I couldn't find any pattern, it is just not reliable. The output is different each time the apex tests are executed. It doesn't matter if you run single method or the entire class, results are still inaccurate.

**SFDX CLI Version**

```
$ sfdx --version
sfdx-cli/7.84.2-a2868a68d5 win32-x64 node-v12.18.3
$ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.14.4 (50.14.4)
├─ schema 1.0.3
├─ limits 1.0.2
├─ user 1.0.7
├─ templates 50.4.0
├─ salesforce-alm 50.14.0
├─ apex 0.1.4
├─ custom-metadata 1.0.11
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7
sfdx-cli 7.84.2 (core)
```
**OS and version**: Windows 10.

**Comment by iowillhoit** [comment]
Hey @dobrusia, we are cleaning up some old issues. I played with this a bit and was unable to replicate the issue. Perhaps I am not understanding the setup needed. If this is still a problem with the latest version of the `sf` CLI (currently `2.26.10`) please open a new issue. Include a repository that is configured to replicate this issue with the exact commands/flags to run. The [Dreamhouse](https://github.com/trailheadapps/dreamhouse-lwc/) sample app is usually a good place to start. Thank you
