### ISSUE TITLE
Running sfdx force:source:pull on a sandbox with source tracking pilot doesn't retrieve networkBranding metadata

### ISSUE THREAD

**Issue by peterTrifecta** [forcedotcom/cli#816]
### Summary

Running sfdx force:source:pull on a sandbox with source tracking pilot doesn't retrieve networkBranding metadata

### Steps To Reproduce:

1. Made changes such as logo, colors, etc., in the Administration | Login & Registration section to a community (in this case it was a community for a B2B Commerce LEX store -- unable to install in a dev org).
2. Run sfdx force:source:pull
3. See no changes.
4. The force-app/main/defaault/networkBranding/cbStore2.networkBranding file contents are simply {}.

5. Next, run sfdx force:source:retrieve -p ./force-app/main/default/networkBranding
6. See the force-app/main/defaault/networkBranding/cbStore2.networkBranding fully populated.

### Expected result
To see that file populate from force:source:pull

### Actual result

force:source:pull shows no changes

### Additional information

_Feel free to attach a screenshot_.
![image](https://user-images.githubusercontent.com/76489814/105519823-e10dbd80-5ca7-11eb-8c09-20d7c4f4acb8.png)

![image](https://user-images.githubusercontent.com/76489814/105519707-bde30e00-5ca7-11eb-8ae0-93b64b637194.png)

sfdx-cli/7.84.2-a2868a68d5 darwin-x64 node-v12.18.3

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.13.3 (core)
├─ user 1.0.5 (core)
├─ schema 1.0.3 (core)
├─ limits 1.0.2 (core)
├─ templates 50.4.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.13.1 (core)
├─ custom-metadata 1.0.11 (core)
└─ apex 0.1.4 (core)
sfdx-1commerce-plugin 0.0.3
sfdx-cli 7.84.2 (core)

Mac OS Catalina version 10.15.7

**Comment by WillieRuemmele** [comment]
Hi @peterTrifecta sorry for the delayed response, can you try running the `pull` command with the  `--dev-debug` flag and posting the output
