### ISSUE TITLE
Accurate error massage swallowed when creating package version

### ISSUE THREAD

**Issue by JayQuerido** [forcedotcom/cli#818]
### Summary

Accurate error message is swallowed in `salesforce-alm` package when creating a package version.

### Steps To Reproduce:

1. Have a package with a static resource defined (via resource-meta.xml), but remove the actual static resource file.
    e.g. sample_data_brokers.resource-meta.xml exists but sample_data_brokers.json is missing
1. Try to build a package using the following command options:
`sfdx force:package:version:create -p DreamhouseLWC -f .\config\project-scratch-def.json -v somedevhub --json -x --skipvalidation -w 12`

### Expected result

Useful error message stating that there is a missing static resource.

### Actual result

`salesforce-alm` package swallows the useful error and replaces it with an error about failing .indexOf() on undefined.

### Additional information

The error handling code in salesforce-alm needs to handle the situation where `error.message` is undefined (as thrown when running the sfdx command).

**SFDX CLI Version**: 7.82.1

**SFDX plugin Version**: saleforce-alm 50.7.1

**OS and version**: Windows 10

**Comment by JayQuerido** [comment]
Aside from the bug being tracked internally at Salesforce, they have also issued this: https://trailblazer.salesforce.com/issues_view?id=a1p4V000001nT1wQAE

**Comment by shetzel** [comment]
This is fixed in the latest CLI, with latest plugin-packaging plugin.  I now see this error message in the JSON output:

```
".../dreamhouse-lwc/force-app/main/default/staticresources/sample_data_brokers.resource-meta.xml: Expected source files for type 'StaticResource'"
```
