### ISSUE TITLE
npm install Object for dependency "@types/lodash" is empty

### ISSUE THREAD

**Issue by Kevmo92** [forcedotcom/cli#819]
### Summary

Cannot npm install sfdx-cli

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  `npm i -g sfdx-cli`

### Expected result

sfdx-cli is installed

### Actual result

```
npm install --global sfdx-cli
npm WARN deprecated @salesforce/plugin-analytics@1.12.2: Deprecated
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! Object for dependency "@types/lodash" is empty.
npm ERR! Something went wrong. Regenerate the package-lock.json with "npm install".
npm ERR! If using a shrinkwrap, regenerate with "npm shrinkwrap".
```

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**:

**Comment by alexmodis** [comment]
@Kevmo92  same error here in my pipeline & locally
Edit : 
node v14.15.0
npm  v6.14.8

I tried to install sfdx 7.85.1, 7.82.1-0 & 7.77.0 getting same error so I guess lodash dependency has changed & is failing now.

Also tried to uninstall sfdx, do npm ci, npm install... but not better.

**Comment by alexmodis** [comment]
Just tried with `yarn add` and everything's fine

**Comment by cdanhowell** [comment]
I can confirm this behavior in GitHub actions.

**Comment by Kevmo92** [comment]
Seems like `npm i -g sfdx-cli` is working again 🤷‍♂️ :magic:

**Comment by alexmodis** [comment]
same thing here...
