### ISSUE TITLE
'Mismatched version in @salesforce/plugin-generator plugin manifest' error with version 7.63.0

### ISSUE THREAD

**Issue by lonegroover** [forcedotcom/cli#823]
### Summary

Whenever we run any 'sfdx' command we get the following error:
    (node:222) Warning: Mismatched version in @salesforce/plugin-generator plugin manifest. Expected: 1.1.4 Received: 1.1.3
    This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be 
    automatically generated when publishing.
This does not seem to affect the operation of the commands.
We are using version 7.63.0 of the CLI due to open issue 470 (https://github.com/forcedotcom/cli/issues/470).

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1. Install sfdx CLI v7.63 using npm: # sudo npm install sfdx-cli@7.63.0 --global
1. Run sfdx any sfdx command, including with no arguments: # sfdx
1. Get the @salesforce/plugin-generator warning/error message

### Expected result

sfdx command should complete without the @salesforce/plugin-generator error/warning message

### Actual result

sfdx command gives the following error/warning message:
    (node:222) Warning: Mismatched version in @salesforce/plugin-generator plugin manifest. Expected: 1.1.4 Received: 1.1.3
    This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be 
    automatically generated when publishing.

### Additional information
This only seems to affect new installs of the CLI.  For example I've had it installed on my laptop for a few months and I don't get the error.
My (error-free) version gives:
CLI Version: sfdx-cli/7.63.0 darwin-x64 node-v14.15.1
Plugin versions:
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.9.1 (core)
generator 1.1.3 (core)
salesforcedx 48.19.0 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ salesforce-alm 48.20.0 (core)
└─ custom-metadata 1.0.10 (core)
sfdx-cli 7.63.0 (core)

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 
7.63.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.9.1 (core)
generator 1.1.4 (core)
salesforcedx 48.19.0 (core)
├─ salesforcedx-templates 48.18.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5 (core)
├─ custom-metadata 1.0.11 (core)
└─ salesforce-alm 48.20.0 (core)
sfdx-cli 7.63.0 (core)

**OS and version**:
MacOs 10.15.7 (19H114)
Ubuntu 18.04.3 LTS (Bionic Beaver)

**Comment by msimonis** [comment]
I am experiencing the same issue with both the latest and latest-rc versions of the cli installed via npm globally. I only started seeing the warning after upgrading to the latest cli version today.

**Comment by amphro** [comment]
This will only happen with npm. There was a new version of the plugin-generator that was published while testing the build. We are looking into why the manifest is off. That warning should have no impact on actual CLI usage though. I'll reset `latest` to 1.1.3.
