### ISSUE TITLE
Updating CLI, many errors (incl SHA mismatch), requires uninstall.

### ISSUE THREAD

**Issue by qwikag** [forcedotcom/cli#830]
### Summary

SFDX update is failing, requires elaborate calls to update properly

### Steps To Reproduce:

1. brand new VSCode and SFDX install.

2. $ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.4.7
config 1.2.1 (core)
generator 1.1.3 (core)
**salesforcedx 50.9.1 (core)**
├─ limits 1.0.0 (core)
├─ schema 1.0.1 (core)
├─ salesforce-alm 50.9.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 50.1.0 (core)
├─ apex 0.1.4 (core)
└─ custom-metadata 1.0.10 (core)
sfdx-cli 7.83.0 (core)

3. $ sfdx --version
sfdx-cli/7.83.0-eba9c6a927 win32-x64 node-v12.18.3

4.$ sfdx update
sfdx-cli: Updating CLI from 7.83.0-eba9c6a927 to 7.84.2-a2868a68d5... \ 26.4 MB/33.2 MB
**It got stuck at 26.4MB DL.**

4.  $sfdx update -v
 »   Warning: Attempting to contact update site...
sfdx-cli: Updating CLI... !
 »   Error: S3 host is not reachable.

5. $ sfdx plugins:install salesforcedx@latest
Successfully validated digital signature for salesforcedx.
Finished digital signature check.
warning salesforcedx > salesforce-alm > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning salesforcedx > salesforce-alm > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning salesforcedx > salesforce-alm > @salesforce/plugin-analytics@1.12.1: This package has been deprecated in favor of https://www.npmjs.com/package/@salesforce/plugin-telemetry
warning salesforcedx > salesforce-alm > @salesforce/plugin-analytics > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning salesforcedx > @salesforce/plugin-templates > yeoman-environment > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning salesforcedx > @salesforce/plugin-templates > yeoman-environment > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
Installing plugin salesforcedx... installed v50.12.0

6. $ sfdx version
sfdx-cli/7.83.0-eba9c6a927 win32-x64 node-v12.18.3

7. $ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.4.7
config 1.2.1 (core)
generator 1.1.3 (core)
**salesforcedx 50.12.0**
├─ schema 1.0.3
├─ limits 1.0.3
├─ custom-metadata 1.0.11
├─ templates 50.1.0
├─ salesforce-alm 50.12.0
├─ apex 0.1.4
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7
sfdx-cli 7.83.0 (core)

8.  $ sfdx update
sfdx-cli: Updating CLI from 7.83.0-eba9c6a927 to 7.84.2-a2868a68d5... !
    **Error: SHA mismatch: expected 48ba09e46cd2176386a17dadbbe37d64c360df849cee1e7996610d478c32250a to be 9c0940c1b42a5f30020075a318a12023c07a614775eb3a06e2abde051687ed23.**

9. $ sfdx plugins:uninstall salesforcedx
Uninstalling salesforcedx... done

10. $ sfdx update
sfdx-cli: Updating CLI from 7.83.0-eba9c6a927 to 7.84.2-a2868a68d5... done
sfdx-cli: Updating CLI... done
sfdx-cli: Updating plugins... done

11. $ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.7
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.13.3 (core)
├─ user 1.0.5 (core)
├─ schema 1.0.3 (core)
├─ limits 1.0.2 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.13.1 (core)
├─ templates 50.4.0 (core)
├─ custom-metadata 1.0.11 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.84.2 (core)

### Expected result

SFDX CLI should update

### Actual result

It fail, requires uninstall of salesforcedx plugin

### Additional information

See various versions above.
Please note this was a brand new install of VSCode and plugins, many errors have occurred.

**OS and version**:
Windows 10 Pro,  Version 10.0.19041
VS Code 1.52.1

**Comment by WillieRuemmele** [comment]
Hi @qwikag there must've been an issue with our S3 host, I'm able to update the cli without any errors. Could you try again now and see if it's working?
