### ISSUE TITLE
Cannot assign permission set to default user

### ISSUE THREAD

**Issue by renatoliveira** [forcedotcom/cli#831]
### Summary

Having a permission set named "Marketplace_Administrator" in the project's folder, the CLI tries to assign a permission set with the first character as its name ("M").

### Steps To Reproduce:

1. Create empty repo.
2. Create a custom tab.
3. Create permission set on org with visibility to a custom tab.
4. Try to use the `force:user:permset:assign` command.

### Expected result

The permission set with the name specified by the `-n` flag should be assigned to the current default user.

### Actual result

The CLI tries to assign a permission set that does not exist, because it tries to reach a permission set with a single character as its name.

### Additional information

```
$ sfdx force:user:permset:assign -n "Marketplace_Administrator"
=== Failures
Username                       Error Message
─────────────────────────────  ───────────────────────────────────────────────────────────────────────
test-jfhcengfwdyi@example.com  Permission set "M" not found in target org. Do you need to push source?
```

Workaround for now is to use an Apex script to assign the permission or open the org and assign it to the "User User" manually.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.84.2-a2868a68d5 linux-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): sfdx-cli 7.84.2 (core)

**OS and version**: Pop! OS 20.04 LTS on a Dell XPS 13.

**Comment by WillieRuemmele** [comment]
Hi @renatoliveira this issue should be fixed in the newest version of the `user` plugin, could you please run `sfdx plugins:install user` and try again?

**Comment by renatoliveira** [comment]
Thank you. I installed the plugin `user` v1.0.13 and it worked. Updating the CLI only does not update the plugins.
