### ISSUE TITLE
unable to deploy sharing rules trought sfdx force:source:deploy command in version 7.82

### ISSUE THREAD

**Issue by dimitrimonge** [forcedotcom/cli#833]
**Summary**

Running sfdx force:source:deploy on a sandbox doesn't deploy sharing rules metadata

**Steps To Reproduce:**

    have sharing criteria rules in your local repository

    Run sfdx force:source:deploy --manifest path/to/manifest.xml

    See no changes.

Expected result

![image](https://user-images.githubusercontent.com/10075113/107025168-52219a80-67a9-11eb-9f9c-e58a547efe0a.png)

Actual result

![image](https://user-images.githubusercontent.com/10075113/107025200-5c439900-67a9-11eb-9622-c1021391901e.png)

**Additional informartion**

Deployment of sharing rules is working with sfdx version 7.45

**Comment by AllanOricil** [comment]
@dimitrimonge It might be an issue caused by an old version of sfdx. Try to update to the latest version: `sfdx-cli/7.84.2-a2868a68d5 win32-x64 node-v12.18.3` and then verify if the bug persists.

**Comment by DougMidgley** [comment]
Hey,
Same issue here using sfdx-cli/7.86.3 win32-x64 node-v15.5.1

> === Deployed Source
> No results found

Files are here inside of the following files
-sharingRules
--Account.sharingRules-meta.xml
--Case.sharingRules-meta.xml

pacakge file is 
```<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Account.CSSCZ_AccountSharingRule</members>
        <members>Case.CSSCZ_CaseSharingRule</members>
        <name>SharingCriteriaRule</name>
    </types>
    <version>51.0</version>
</Package>```

**Comment by mdonnalley** [comment]
@dimitrimonge @DougMidgley could either of you provide a link to a github repo that contains the metadata that replicates this issue?

Thanks

**Comment by dimitrimonge** [comment]
@AllanOricil @DougMidgley @mdonnalley sorry for the delay, I was very busy by a go live last days.
 I found out a work around to make it work.

 You can add the following tag to your manifest : 

```
    <types>
        <members>*</members>
        <name>SharingRules</name>
    </types>
```
You can have the same issue with matching rule that you can solve with same kind of tag : 

```
    <types>
        <members>*</members>
        <name>MatchingRules</name>
    </types>
```
Hope will help

Best regards

**Comment by DougMidgley** [comment]
So when using the SharingRules tag it works, but when using SharingCriteriaRule it does not, even though it is supported in the coverage report ( https://developer.salesforce.com/docs/metadata-coverage/51). The metadata docs (https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_sharingrules.htm)  are contradictory - they provide an example using the Subtype 

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>ObjA__c.*</members>
        <name>SharingCriteriaRule</name>
    </types>
    <types>
        <members>ObjA__c.*</members>
        <name>SharingOwnerRule</name>
    </types>
    <version>51.0</version>
</Package>
```

but also say it cannot be used 

> You can’t retrieve, delete, or deploy manual sharing rules or sharing rules by their type (owner, criteria-based, territory, or guest user).

A further discussion can be found here - https://github.com/scolladon/sfdx-git-delta/issues/99 in detail

**Comment by dimitrimonge** [comment]
@DougMidgley  
it seems working to retrieve metadatas but not to deploy them.
It used to work in version 7.81. 

Hope Salesforce will solve this issue soon but at least we have a work arround :

**Comment by niv-goldenberg** [comment]
I'm still getting this for SharingCriteriaRule:
sfdx-cli/7.82.1-0 linux-x64 node-v14.16.0
Ubuntu 20.04

The workaround will not work for me, since we build the package automatically as part of our CI/CD process. 

Hope that someone in Salesforce can fix it soon...

**Comment by DevopsLabsXD** [comment]
I was able to display the sharing setting changes via SFDX, displaying exclusively the object that was required to modify the sharing setting. When displaying the object in the object's meta file, this information travels:

![image](https://user-images.githubusercontent.com/100947725/210616979-688f958d-1d20-493d-a472-524a3ea16352.png)

On lines 234 and 258 shown in the image is the configuration of the sharing setting within the object

Regards

Nerio Villalobos (DevOps Salesforce & SFI of LabsXD)
labsxd.com
