### ISSUE TITLE
Help us test 3 new org commands 

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#835]
`force:org:open`, `force:org:list`, and `force:org:display` have been rewritten and open-sourced...but they're not bundled into the CLI yet.  

**Before we do that, we'd like your help testing them out.**

## Install
`sfdx update` to make sure you're on the latest version
`sfdx plugins:install org`

## Test
once the plugin is installed, you can use the commands like normal.  Run any scripts you have or commands you use regularly.
Report any issues you see using this repo (the issue-only repo) and just add a note that it's the new `plugin-org`

Any of the other `force:org:` commands (`create`, `delete`, `snapshot`, etc) are not part of this project.

## Uninstall
once you're done testing, or need to switch back to the current version, just uninstall it
`sfdx plugins:uninstall org`

Code is at https://github.com/salesforcecli/plugin-org if you want to see how things are working or contribute a fix.

**Comment by AllanOricil** [comment]
@mshanemc @amphro @WillieRuemmele 

There is a bug. I have another org connected to sfdx that is not being displayed when using `sfdx force:org:list --all` or `sfdx force:org:list --all --json`. This org is a trailhead playground.  In the picture below I show that vscode sees it. Sfdx does not show it, but it knows it exists, as I can use `sfdx force:org:open -u Playground2`


![image](https://user-images.githubusercontent.com/55927613/111994440-af7e6a80-8b0f-11eb-844a-8790c48d73a3.png)


The plugin version is 1.5.0
![image](https://user-images.githubusercontent.com/55927613/111995116-7abee300-8b10-11eb-82a1-d5ba7a5cbdc7.png)
