### ISSUE TITLE
Issue Retreiving Survey Setting in VSCode 

### ISSUE THREAD

**Issue by kamalsomu** [forcedotcom/cli#836]
### Summary

Survey Setting is being retreived in a separate folder named surveySettings (force-app/main/default/surveySettings/Survey.survey-meta.xml) 
instead of settings folder  (force-app/main/default/settings/surveySettings/Survey.survey-meta.xml)

### Steps To Reproduce:

1.  Retreive the settings metadata with wildcard using "SFDX : Retreive Source in Manifest from Org" command.

### Expected result

Survey Setting metadata should be retreived inside the settings folder.

### Actual result

Survey Setting metadata is being retreived in a separate folder named surveySettings

### Additional information

I have attached the screenshot for your reference.
![Survey](https://user-images.githubusercontent.com/11818325/105571574-ebe35380-5d76-11eb-86ce-75e8e2c0e733.png)

**VS Code Version**: 1.52.1

**SFDX CLI Version**: sfdx-cli/7.82.0-52018670a1

**OS and version**: Windows 8

**Comment by lcampos** [comment]
VSCode delegates the retrieve operation to the CLI, can you update to the latest version of the CLI and run this operation again ? There's been a few fixes released lately and I wonder if those take care of what you are experiencing.

**Comment by mdonnalley** [comment]
@kamalsomu what version of the CLI are you running?

**Comment by kamalsomu** [comment]
@lcampos @mdonnalley I was using SFDX CLI Version: sfdx-cli/7.82.0-52018670a1. I have updated the cli. It looks like the issue got fixed. Thank you..
