### ISSUE TITLE
linux-x64 download using older version of sfdx-cli

### ISSUE THREAD

**Issue by ChloeCoon** [forcedotcom/cli#837]
### Summary
About 2 hours ago, the linux download link from manifest.json we use to install sfdx-cli for some github actions started installing version 7.82.0 when it was previously installying 7.85.1. 

### Steps To Reproduce:

1. From https://developer.salesforce.com/media/salesforce-cli/manifest.json, select the downloads > linux-x64 link. 

At time of issue writing, the link was https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

### Expected result

Download URL should give us the correct version of sfdx-cli.

### Actual result

Download URL gives us `sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3`

### Additional information

```
sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3
sfdx-cli/7.82.0-3d0c527ac6 linux-x64 node-v12.18.3
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.7.0 (core)
├─ schema 1.0.1 (core)
├─ salesforce-alm 50.7.0 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.82.0 (core)
```

**Comment by mdonnalley** [comment]
@ChloeCoon The manifest you're using refers to legacy installers which we are now keeping at 7.82.0 and will no longer be updating. I recommend referring to this manifest going forward: https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/manifest.json

**Comment by davisagli** [comment]
@mdonnalley The docs for installing the Salesforce CLI (https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm) link to the manifest that you say is outdated (https://developer.salesforce.com/media/salesforce-cli/manifest.json). Will the docs be updated to recommend https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/manifest.json?

The docs also say "The downloads section lists unversioned URLs for the latest installers, which are especially useful for CI use cases" but I do not see a downloads section in the new manifest. Is there no longer a stable URL that can be used in CI to always get the latest stable release?

**Comment by mdonnalley** [comment]
@davisagli Yes, we plan to update the docs as soon as possible. 

There is still a stable url that you can use in your CI: https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-linux-x64.tar.xz
