### ISSUE TITLE
ERROR running force:org:display:  Must pass a username and/or OAuth options when creating an AuthInfo instance.

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#838]
### Summary

I cant run `sfdx force:org:display` without passing -u flag with a defaultusername selected.

### Steps To Reproduce:

1 - Ensure you have the sfdx extension for vscode
2 - Click on the status bar button to change your defaultusername
3 - run `sfdx force:org:display` without passing the -u flag, as it is already set when you selected the defaultusername in the step 2
4 - Verify that you have this error message

![image](https://user-images.githubusercontent.com/55927613/107270801-4c46e600-6a43-11eb-9154-3925787dc120.png)

5 - Run `sfdx force:org:display` again, without touching in anything else.
6 - Verify that now the command worked.

### Expected result

`sfdx force:org:display` should work when I'm executing it from a sfdx project and I have a defaultusername set.

### Actual result

``sfdx force:org:display` failed right after selecting a defaultusername

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.84.2-a2868a68d5 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) N/A

**OS and version**: Windows 10

**Comment by AllanOricil** [comment]
on previous versions I was able to run `sfdx force:org:display` without passing the -u flag, as it was already set in the local defaultusername

**Comment by mshanemc** [comment]
If you just do step 1, then step 2...can you check with `sfdx config:list` to verify that vscode is setting the defaultusername correctly?

**Comment by AllanOricil** [comment]
@mshanemc 
![image](https://user-images.githubusercontent.com/55927613/107280549-6509c880-6a50-11eb-809a-5f65d0e226bf.png)

**Comment by mshanemc** [comment]
ooh, that's a fun one.  Nice find!
