### ISSUE TITLE
ERROR running force:project:create:  A name parameter is required to create a storage

### ISSUE THREAD

**Issue by codyjbatchelor** [forcedotcom/cli#843]
### Summary

During deployment process we create a new scratch org, and during scratch org creation we are getting intermittent errors -- : ERROR running force:project:create:  A name parameter is required to create a storage

We have had the same process for the past 2 years and some days scratch org creation is fine and some days we get this error randomly.

We are also always using the latest version of SFDX

**Comment by mshanemc** [comment]
We're on it.

**Comment by mshanemc** [comment]
Can you check 2 things
1. What's the name of the project you're trying to create?
2. Is there a package.json anywhere nearby that's getting hit (for example, you're trying to create a project on top of an existing one, or there might be a package.json somewhere in a directory above the one you're trying to create the project from)
