### ISSUE TITLE
ERROR running force:org:create:  getaddrinfo ENOTFOUND speed-force-8109-dev-ed.cs43.my.salesforce.com

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#844]
### Summary

When attempting to create a SO from a devhub that the authentication token is expired this error is thrown.

![image](https://user-images.githubusercontent.com/55927613/107714958-24b38000-6cc6-11eb-8fd5-6ec1c9f7f072.png)

My suggestion is to always refresh the auth token for the devhub before trying to create a SO, and if it is not possible to grab a new token for the devhub, then dont even try to create a SO.

### Steps To Reproduce:

1 - Set the defaultdevhubusername to a devhub that you have not run `sfdx force:org:display` for a while, which caused its auth token to get expired
2 - try to create a SO and verify that sfdx throws the exception shown in the above image
3 - run `sfdx force:org:display -u DEVHUBUSERNAME` or set the selected org using the vscode extension, then click on the button to open the org (this will cause sfdx to get a new auth token)
4 - try to create a SO and this time verify that the error is gone, since now the devhubusername auth token is valid

### Expected result

SO should be created

### Actual result

SO is not created because the devhubusername auth token is expired

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):  sfdx-cli/7.85.1-2fb9e41053 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) N/A

**OS and version**: windows 10

**Comment by mdonnalley** [comment]
@AllanOricil can you provide the entire debug output (using `--dev-debug`)?
