### ISSUE TITLE
Scratch Org Users in nonScratchOrgs result

### ISSUE THREAD

**Issue by aesanch2** [forcedotcom/cli#845]
### Summary

Not sure if this is a regression or a change to the API, but `force:org:list` now returns users created in a scratch org in the `nonScratchOrg` section of the response. These users were previously in the `scratchOrg` response. This has caused some of my scratch org automation to fail.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1. Create a scratch org: `sfdx force:org:create -s -f config/project-scratch-def.json -a dreamhouse`
1. Create a new user in the scratch org: `sfdx force:user:create -a testuser email=me@my.org permsets=DreamHouse`
1. List all the orgs: `sfdx force:org:list --json`

### Expected result

The "org" for `testuser` is displayed in the `scratchOrgs` response.

### Actual result

The "org" for `testuser` is displayed in the `nonScratchOrgs` response.

### Additional information

**SFDX CLI Version**: sfdx-cli/7.85.1-2fb9e41053 darwin-x64 node-v12.18.3

**SFDX plugin Version**: salesforcedx 50.16.1

**OS and version**: macOS 10.15

**Comment by mshanemc** [comment]
This is fixed in the new version of `plugin-org` (coming soon).  You can test it out right now to verify that it's fixed.

https://github.com/forcedotcom/cli/issues/835

**Comment by mshanemc** [comment]
Closing because the fix in `plugin-org` is shipped.
