### ISSUE TITLE
Make Healthcloud relationship cards and Experience Cloud audience available in SFDX

### ISSUE THREAD

**Issue by davidcatindoy** [forcedotcom/cli#849]
11:29:41.291 sfdx force:source:pull
We can’t retrieve the specified metadata object: UIObjectRelationConfig. Certain metadata types, like HSSAccountCard are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
We can’t retrieve the specified metadata object: UIObjectRelationConfig. Certain metadata types, like HSSPhysicianCard are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
We can’t retrieve the specified metadata object: Audience. Certain metadata types, like Providers are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
We can’t retrieve the specified metadata object: Audience. Certain metadata types, like Vendor_Admins are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
We can’t retrieve the specified metadata object: Audience. Certain metadata types, like Provider_Admins are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type

**Comment by mshanemc** [comment]
`Audience`, `UIObjectRelationConfig` made it in.
