### ISSUE TITLE
sfdx force:schema:sobject:describe timeout on Apple Silicon

### ISSUE THREAD

**Issue by pogilvie** [forcedotcom/cli#850]
### Summary

_sobject describe command timeout on new apple laptop with M1 processor other commands are working_.

I'm not seeing this issue on intel Macs running the same versions of OS and CLI.   Note that I'm only have an issue with the object:describe command, other cli commands including push/pull are working fine.

### Steps To Reproduce:

1.  prerequisites: 
- a DX authenticated org
- apple M1 client running macOS Big Sur 11.2.1

2.  verify basic connectivity (command below should work as expected
- sfdx force:schema:sobject:list -u myOrg 
<list of sobjects here>
3. issue
- sfdx force:schema:sobject:describe -s Account -u myOrg

timeout (see below)

### Expected result

JSON describe output from Account

### Actual result
````
Error: read ETIMEDOUT
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'read'
}
````

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.85.1-2fb9e41053 darwin-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

````
oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.15.0 (core)
├─ limits 1.0.3 (core)
├─ schema 1.0.3 (core)
├─ user 1.0.9 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.15.0 (core)
└─ templates 50.4.0 (core)
sfdx-cli 7.85.1 (core)
````

**OS and version**:
Darwin falcon.attlocal.net 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64

**Comment by pogilvie** [comment]
I found that when I reboot my machine describe works the first time and timeout the second time if I repeat the command immediately.   Maybe there's a cache which is not working?

**Comment by pogilvie** [comment]
Describe works if I call JSforce directly.

works ...

````
const 
  creds = require('./creds.json')
  jsforce = require('jsforce')
  c = new jsforce.Connection({ loginUrl: 'https://test.salesforce.com' })

function passwword(creds) {
  return creds.password + creds.token
}

function checkerror(e) {
  if (e) throw(e)
}

c.login(creds.name, passwword(creds), (e, userinfo) => {

  checkerror(e)
  console.log(userinfo)

  c.describe('Account', (e, meta) => {
    checkerror(e)
    console.log(meta)
  })
})
````

broken on M1 but works on Intel with version of OS and sfdx.

````
public async run(): Promise<AnyJson> {

    console.log(this.flags)

    const c = this.org.getConnection();
    const result = await c.describe(this.flags.sobject)

    console.log(result)

    return <AnyJson><unknown>result

  }
````

**Comment by mshanemc** [comment]
@pogilvie there's been a lot of changes to that code and jsforce AND we're producing an Apple-Silicon specific release.

Any chance you're still getting this problem?
