### ISSUE TITLE
force:source:deploy "No results found" on CLI version 7.85.1

### ISSUE THREAD

**Issue by dpuza-formativ** [forcedotcom/cli#855]
### Summary

_Short summary of what is going on or to provide context_.

After "sfdx update" to 7.85.1, "force:source:deploy" has stopped working for us.  Get the message "No results found" and nothing is deployed.

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Run the command: sfdx force:source:deploy -m ApexClass:GeocodingService -u TARGETUSERNAME
1.  A) Got the message "No results found" and nothing was deployed.  B) If not, run the command again and get the message "No results found". 

### Expected result

_Describe what should have happened_.

The specified metadata should have been deployed, like previous versions of the CLI did.

### Actual result

_Describe what actually happened instead_.

Nothing is deployed.  Get the message "No results found".

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.85.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 51.0.2 (latest-rc)
├─ schema 1.0.3
├─ limits 1.0.3
├─ user 1.1.0
├─ custom-metadata 1.0.11
├─ templates 51.1.0
├─ apex 0.1.4
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
└─ salesforce-alm 51.0.1
sfdx-cli 7.85.1 (core)

**OS and version**: Windows 10 Pro 1909

**Comment by ghost** [comment]
We have a similar issue. I cant pull/push to/from a Scratch org retrieve/deploy from a sandbox.

**Comment by mdonnalley** [comment]
Duplicate of https://github.com/forcedotcom/cli/issues/851
