### ISSUE TITLE
force:source:retrieve add append mode or star operator.

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/cli#857]
**What are you trying to do**
Today I tried to download newly created workflow rule by using:
```
sfdx force:source:retrieve -m "WorkflowRule:Case.MyRule"
sfdx force:source:retrieve -m "WorkflowAlert:Case.MyEmailAlert"
```
And found out that those commands are overwriting the same file ```Case.workflow-meta.xml``` so or I have Rule or Alert there.
Then I executed both together ``` -m "WorkflowRule:Case.MyRule, WorkflowAlert:Case.MyEmailAlert" ``` and got both in that file. 
However this still an issue when you have larger number of workflow rules as this will overwrite xml file with only those retrived metadata. 

**Describe the solution you'd like**
I would like to have append mode so in case that I have already ```Case.workflow-meta.xml``` file with some rules by running sfdx command I want to append at the end my newly created WR.

**Describe alternatives you've considered**
As an alternative I would like to use star operator.
```sfdx force:source:retrieve -m "WorkflowRule:Case.*" ```
in order to get all rules in this file so git can figure out what is new. Assuming that order of rules won't be mixed.

**Additional context**
Finally i solved that by using code below which downloaded all WRs with their actions.
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>51.0</version>
    <types>
        <members>Case</members>
        <name>Workflow</name>
    </types>
</Package>
```

The same issue is with Custom Labels where retrieving one is overwriting whole file.

**Comment by WillieRuemmele** [comment]
duplicated and tracked here : https://github.com/forcedotcom/cli/discussions/2363
