### ISSUE TITLE
sfdx force --version not working

### ISSUE THREAD

**Issue by keirbowden** [forcedotcom/cli#86]
### Summary

`sfdx force --version` is documented in the [SalesforceDX Developer's Guide](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_troubleshoot_cli_version.htm?search_text=force%20--version) as the mechanism to get CLI Version Information.

### Steps To Reproduce:

1.  Install the latest CLI and force plugin.
1.  Execute `sfdx force --version`

### Expected result

Information about the Salesforce API version used by the CLI should be displayed. 

### Actual result

ERROR running force:  Unexpected argument: --version
See more help with --help

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.5.0-e6ca93eee8 darwin-x64 node-v10.15.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.12.0 (core)
├─ force-language-services 45.10.0 (core)
└─ salesforce-alm 45.15.0 (core)

sfdx-cli 7.5.0 (core)

**OS and version**:
MacOS Mojave 10.14.4

**Comment by clairebianchi** [comment]
@keirbowden the command is sfdx --version to get the CLI version and sfdx plugins --core for the SFDX plugin version.

That third command is not necessary. I will have it removed from the documentation

**Comment by VivekMChawla** [comment]
@clairebianchi it's a bit of a hassle to evangelists and instructors that this command was removed.  

Telling someone to type `sfdx force --version` to see if they got the big "DX Cloud" in their terminal was one of the best ways to make sure that someone had properly installed the CLI on their local machine.

Even worse (for me) is that I've used this in workbooks and videos about how to use SFDX.  I've also seen it in DF and TDX videos (including the AppX Keynote demo I did at DF'17).  Now those references (and instructions in workbooks) make no sense.

It would be great if we could get that command back. It's a nice bit of candy to have in the CLI.

If we can't get it back, is there another way to get the "DX Cloud" now?

**Comment by amphro** [comment]
That flag never actually did anything. Just do ‘sfdx force‘. If it is documented, that would be the bug.

**Comment by amphro** [comment]
However I do see the bummer about it being in workshops and videos. A couple other customers brought this up, but said it was fine that they could just leave off the version. If you can update your workshops so it doesn't have the --version, that would be ideal. Otherwise, maybe we can consider putting it back

**Comment by Cfh-GitHub** [comment]
@clairebianchi This continues to exist in the documentation: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_troubleshoot_cli_version.htm

Fyi,



> @keirbowden the command is sfdx --version to get the CLI version and sfdx plugins --core for the SFDX plugin version.
> 
> That third command is not necessary. I will have it removed from the documentation

**Comment by clairebianchi** [comment]
Thank you @CfhGithub! Ill get that updates

**Comment by SalesforceLynx** [comment]
As per my last encounter of it today. It is working but without --verion or -v. 

Although in the documentation it still says that `sfdx force --version`. But you'll get the ASCII cloud with just `sfdx force`. It would be nice @clairebianchi if we update the documentation too.
