### ISSUE TITLE
.forceignore Does Not Work as Documented

### ISSUE THREAD

**Issue by JNiedle** [forcedotcom/cli#861]
### Summary

When running `sfdx force:source:retrieve --manifest path/to/package.xml` or `sfdx force:source:retrieve --sourcepath path/to/object/contact`, the .forceignore file is not being respected for managed packages.

### Steps To Reproduce:

1. install an app with a namespace in your developer org such as [smart vCard](https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000ErB7xUAF)
1. Add lines to .forceignore pattern of the managed package's namespace `smartvCard__*`
1. Refresh the metadata for the contact object
1. fields that start with the value smartvCard__ are still retrieved into the package

### Expected result

[Per the .forceignore docs](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm), files matching the patterns in the .forceignore file should be excluded.

### Actual result

Files matching the patterns in the .forceignore are still retrieved into the project

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.85.1-2fb9e41053 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core):
  @oclif/plugin-autocomplete 0.1.5 (core)
  @oclif/plugin-commands 1.3.0 (core)
  @oclif/plugin-help 3.2.1 (core)
  @oclif/plugin-not-found 1.2.4 (core)
  @oclif/plugin-plugins 1.9.5 (core)
  @oclif/plugin-update 1.3.10 (core)
  @oclif/plugin-warn-if-update-available 1.7.0 (core)
  @oclif/plugin-which 1.0.3 (core)
  @salesforce/sfdx-trust 3.6.0 (core)
  alias 1.1.5 (core)
  analytics 1.12.1 (core)
  auth 1.4.6 (core)
  config 1.2.3 (core)
  generator 1.1.3 (core)
  salesforcedx 50.15.0 (core)
  ├─ schema 1.0.3 (core)
  ├─ limits 1.0.3 (core)
  ├─ user 1.0.9 (core)
  ├─ custom-metadata 1.0.11 (core)
  ├─ apex 0.1.4 (core)
  ├─ templates 50.4.0 (core)
  ├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
  └─ salesforce-alm 50.15.0 (core)
  sfdx-cli 7.85.1 (core)

**OS and version**: Win10 20H2

**Comment by mshanemc** [comment]
@JNiedle there's an improved version of the forceignore stuff in progress.  If you're able to, can you check to see if it fixes the problem with packages/namespaces?

it's just a commented line that you add to the file to opt in to the new version.
https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md#5020-october-22-2020---cli-7771

**Comment by JNiedle** [comment]
Hi @mshanemc. I was using the `# .forceignore v2` and had the same result. I confirmed that the `<packagenamespace>__*` pattern worked for gitignore by adding the same pattern to my gitignore where those files were successfully ignored by git.

**Comment by TWood-IRL** [comment]
hi @mshanemc just wanted to check the status of this issue. 

I was encountering something similar for my own project, and came across this which dosent seem to have much activity

**Comment by mshanemc** [comment]
We've switched everything to the v2 version by default.  Does it still happen?

And is the namespace pattern (`foo__*`) the only thing that's not working as expected?
@londoner1234 are you also on windows?
