### ISSUE TITLE
force:source:retrieve cannot retrieve a package version

### ISSUE THREAD

**Issue by CiaranShocks** [forcedotcom/cli#862]
**Is your feature request related to a problem? Please describe.**
I have a managed package which was created sometime ago. Since then numerous developers have made changes in the dev org. I would like to retrieve the unedited code from a specific package version. The package version is still available to install but I cannot retrieve the code base of that version.

**Describe the solution you'd like**
I would like the force:source:retrieve command to have an extra flag when using the [-n PACKAGENAMES] flag so I can specify exactly which version is it that I want to retrieve, defaulting to the most recent. 

**Describe alternatives you've considered**
There are no real alternatives that I have found. I'm not sure it's possible to do this without enhancement of the SFDX CLI

**Comment by AllanOricil** [comment]
@CiaranShocks I think you can go to your git repository and then releases and find the package version you are looking for.  Then you do a checkout on the hash of that release to get the sources for that particular version.

**Comment by CiaranShocks** [comment]
@AllanOricil I probably should have been more specific and mentioned that this use case is for pulling a specific package version from a 1GP managed package in a dev org. There is no git repo or project associated with it.

**Comment by cristiand391** [comment]
@CiaranShocks Thank you for the feature request!
Unfortunately, retrieving a specific package version is not supported by the Metadata API.
I'm going to close this issue for now, please feel free to comment if we have missed something.
