### ISSUE TITLE
ERROR running force:community:create:  The requested resource does not exist

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#865]
### Summary

ERROR running force:community:create:  The requested resource does not exist

![image](https://user-images.githubusercontent.com/55927613/108828757-2aab3a00-75bf-11eb-8507-8efd89b17cbe.png)

### Steps To Reproduce:

No idea how to reproduce

### Expected result

Community should be created if Communities is enabled on a Scratch Org

### Actual result

Community can't be created on a Scratch Org that has Community enabled

### Additional information

Scratch Org configuration
````json
{
  "orgName": "Demo company",
  "edition": "Developer",
  "features": [
    "Communities", 
    "ContactsToMultipleAccounts",
    "DebugApex",
    "EnableSetPasswordInApi"
  ],
  "settings": {
    "languageSettings": {
      "enableTranslationWorkbench":  true,
      "enableEndUserLanguages": true
    },
    "lightningExperienceSettings": {
      "enableS1DesktopEnabled": true
    },
    "mobileSettings": {
      "enableS1EncryptedStoragePref2": false
    },
    "communitiesSettings": {
      "enableNetworksEnabled": true
    },
    "orgPreferenceSettings": {
      "s1DesktopEnabled": true
    }
  }
}

````

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.85.1-2fb9e41053 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
hpe-sfdx-plugins 0.3.2
salesforcedx 50.15.0 (core)
├─ limits 1.0.3 (core)
├─ schema 1.0.3 (core)
├─ user 1.0.9 (core)
├─ apex 0.1.4 (core)
├─ templates 50.4.0 (core)
├─ custom-metadata 1.0.11 (core)
├─ salesforce-alm 50.15.0 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.85.1 (core)
sfdx-dependency-plugin 2.0.1

**OS and version**: Windows 10

**Comment by uip-robot-zz** [comment]
Git2Gus App is installed but the `.git2gus/config.json` doesn't have right values. You should add the required configuration.

**Comment by AllanOricil** [comment]
my mistake. The default so was wrong
