### ISSUE TITLE
Error during installation of Spring 21 Billing Managed Package into Scratch Org

### ISSUE THREAD

**Issue by eyhuellou** [forcedotcom/cli#868]
### Summary

Seems not possible to install last version of Billing Package into a brand new scratch org.

### Steps To Reproduce:

1.  Create a scratch org
2.  Try to install package into scratch Org : sfdx force:package:install -p packageid -u so_alias  -w 40

### Expected result

Complete installation

### Actual result

Waiting for the package install request to complete. Status = IN_PROGRESS
ERROR:  Encountered errors installing the package!,Installation errors: 
1) (FinanceBalanceSnapshot.CreditGLAccount__c) Entité non disponible, Details: L'entité 'FinanceBalanceSnapshot' est introuvable. Pour plus d'informations, contactez le fournisseur.
2) (FinanceBalanceSnapshot.DebitGLAccount__c) Entité non disponible, Details: L'entité 'FinanceBalanceSnapshot' est introuvable. Pour plus d'informations, contactez le fournisseur.
3) (FinanceBalanceSnapshot.FinanceBook__c) Entité non disponible, Details: L'entité 'FinanceBalanceSnapshot' est introuvable. Pour plus d'informations, contactez le fournisseur.
4) (FinanceBalanceSnapshot.FinancePeriod__c) Entité non disponible, Details: L'entité 'FinanceBalanceSnapshot' est introuvable. Pour plus d'informations, contactez le fournisseur.
ERROR running force:package:install:  Installation errors: 
1) (FinanceBalanceSnapshot.CreditGLAccount__c) Entité non disponible, Details: L'entité 'FinanceBalanceSnapshot' est introuvable. Pour plus d'informations, contactez le fournisseur.
2) (FinanceBalanceSnapshot.DebitGLAccount__c) Entité non disponible, Details: L'entité 'FinanceBalanceSnapshot' est introuvable. Pour plus d'informations, contactez le fournisseur.
3) (FinanceBalanceSnapshot.FinanceBook__c) Entité non disponible, Details: L'entité 'FinanceBalanceSnapshot' est introuvable. Pour plus d'informations, contactez le fournisseur.
4) (FinanceBalanceSnapshot.FinancePeriod__c) Entité non disponible, Details: L'entité 'FinanceBalanceSnapshot' est introuvable. Pour plus d'informations, contactez le fournisseur.

### Additional information

Seems linked to the fact that the package needs the presence of Finance Transaction & Finance Balance Snapshot Object (https://help.salesforce.com/articleView?id=000356271&language=en_US&mode=1&type=1)

/!\ Note that CPQ feature has already been included in project-scratch-def.json

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.85.1-2fb9e41053

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**: MACOS

**Comment by uip-robot-zz** [comment]
Git2Gus App is installed but the `.git2gus/config.json` doesn't have right values. You should add the required configuration.

**Comment by eyhuellou** [comment]
Ok problem solved by having an org shape created from DevHub which will indeed contain Finance Transaction & Finance Balance Snapshot Object.

**Comment by eyhuellou** [comment]
Edit : The fact of setting the scratch org def with financeLogging seems to work better than scratch org shape because you sometime have strange behaviour of missing settings with org shape.

So after setting correctly the FinanceLogging features, these two Finance object appears correctly and Billing install perform well.

Scratch Def looks like now :
...
"features": [
    "FinanceLogging",
    "ContactsToMultipleAccounts",
    "CPQ"
  ],
...
