### ISSUE TITLE
Please restore -definitionfile param to force:org:shape:create

### ISSUE THREAD

**Issue by jclark-dot-org** [forcedotcom/cli#873]
**Is your feature request related to a problem? Please describe.**
Salesforce DX is a feature for managing Salesforce Development using source-driven development techniques.  The first v51 release removed an important tool for source-driven development.  From the [releasenotes][1] :

[1]: https://github.com/forcedotcom/cli/tree/main/releasenotes#removed-parameters

> Removed Parameters
> force:org:shape:create --definitionfile
> 
> The definitionfile parameter has been removed from this command. This parameter is part of the org shape feature which is currently in beta. We removed the parameter based on feedback from users that they preferred storing the org shape in the shape source org rather than in a scratch definition file.

This request is intended to provide additional feedback that other users prefer to store org shape in a scratch definition file.  As this parameter was always optional, it should be possible to support both methods.

**What are you trying to do**
When creating a scratch org using Org Share, we need to be able to store that shape information in our source repository along with the rest of the project source.

**Describe the solution you'd like**
Please restore the  `-definitionfile` param to force:org:shape:create. 

**Describe alternatives you've considered**
There is no alternative.

**Additional context**
The scratch definition file is an important, **user-inspectable** part of a source-driven project.  Storing org shape in the source org is opaque and breaks the source-driven model at the heart of SFDX.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-8930603](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000097Nd1IAE/view)

**Comment by azlam-abdulsalam** [comment]
Yes, I agree.. there are many benefits of having that shape definition out.

**Comment by ImJohnMDaniel** [comment]
I agree as well.  This is still a good feature to support.  There are definitely valid use cases where this would be helpful

**Comment by mshanemc** [comment]
I'm going to close this.  The signups team removed those properties from the API, so they're no longer available.  

https://developer.salesforce.com/docs/atlas.en-us.238.0.object_reference.meta/object_reference/sforce_api_objects_shaperepresentation.htm (compare to, for example, v50)
