### ISSUE TITLE
ERROR running force:source:deploy:  Parse error in file /home/runner/.sfdx/***.json on line 1 FILE HAS NO CONTENT

### ISSUE THREAD

**Issue by PreetiSF** [forcedotcom/cli#874]
### Summary

We have git actions to deploy validate in salesforce, We think issue is in one of these commands
  npm install sfdx-cli@7.88.4
  node_modules/sfdx-cli/bin/run --version
  node_modules/sfdx-cli/bin/run plugins --core
  npm install @actions/core
  npm install @actions/github
 node_modules/sfdx-cli/bin/run force:source:deploy -

### Expected result

We should be able to validate in Salesforce

### Actual result

```
We get an error stated below
ERROR running force:source:deploy:  Parse error in file /home/runner/.sfdx/***.json on line 1
FILE HAS NO CONTENT


Could not deploy changes: ERROR running force:source:deploy:  Parse error in file /home/runner/.sfdx/***.json on line 1
FILE HAS NO CONTENT


Error: Process completed with exit code 1.
```

### Additional information
Seems like autorization of org is fine , but cant say 100% Successfully authorized *** with org ID 00D8******

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.88.4 and previously 7.85.1

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) Don't know

**OS and version**: Macintosh

**Comment by peternhale** [comment]
This issue is being tracked via issue #867.

Closing this issue.
