### ISSUE TITLE
Metadata placed in wrong folder when retrieving via manifest 

### ISSUE THREAD

**Issue by dt-snyder** [forcedotcom/cli#875]
### Summary
When pulling some custom objects random files are placed in the wrong folder. It only happens on some objects and not others. Objects I've seen this happen on are User, Lead, Opportunity, and Account.
![image](https://user-images.githubusercontent.com/15711475/109039246-ce611c80-7689-11eb-9190-7077c30d84de.png)

### Steps To Reproduce:

1. Create a Manifest file that contains the above-mentioned objects. 
2. Right-click on Manifest file and select `SFDX: Retrieve Source in Manifest from Org" -> Wait

### Expected result

Files should be placed in their respective folders.

### Actual result

Files are placed in random locations within the SObject Folder Structure.

### Additional information
![image](https://user-images.githubusercontent.com/15711475/109039758-6101bb80-768a-11eb-8d31-b93e5e20823a.png)
![image](https://user-images.githubusercontent.com/15711475/109039800-6bbc5080-768a-11eb-876e-337d0b8ebaea.png)
![image](https://user-images.githubusercontent.com/15711475/109039819-737bf500-768a-11eb-9b90-fe685fad3ac7.png)

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
`sfdx-cli/7.83.1 win32-x64 node-v14.4.0`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.10
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
analytics 1.12.1 (core)
auth 1.4.6 (core)
config 1.2.3 (core)
generator 1.1.3 (core)
salesforcedx 50.12.0 (core)
├─ schema 1.0.3 (core)
├─ limits 1.0.2 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 50.12.0 (core)
sfdx-affirm 2.1.2
sfdx-cli 7.83.1 (core)
```
**OS and version**:
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18363 N/A Build 18363
```

**Comment by peternhale** [comment]
Same being tracked in issue #714.

Closing this issue.
