### ISSUE TITLE
QuickDeploy goes through but instantly crashed for terminal in 7.88.4

### ISSUE THREAD

**Issue by bast-shb** [forcedotcom/cli#876]
### Summary

We use Azure DevOps as a CI/CD pipeline for our Salesforce deployment.

We use the org development model and run our deployment in two steps:
- First we do a force:source:deploy with --checkonly and grab the quick deploy id from the results.
- Second we deploy using force:souce:deploy and the quick deploy id.

On monday we ran the pipeline successfully. However in the evening the same pipeline failed. We always grab the latest version of the sfdx cli, so we identified that the only change for the pipeline between the two deployments were that the cli version had changed from 7.86.3 to 7.88.4 (and a very minor commit in our repo, which was what we were trying to deploy). The error still existed today, we have tried the deployment several times.

Reverting the sfdx cli to 7.86.3 solved the issue.

Here are the exact commands we use for test and deploy ($-variables are pipeline variables):

test: `sfdx force:source:deploy --checkonly --targetusername $(credentials_alias) --json --loglevel fatal  --testlevel RunLocalTests --manifest manifest/package.xml`

deploy: `sfdx force:source:deploy --targetusername $(credentials_alias) --json --loglevel fatal --validateddeployrequestid $(quickDeployId)`

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1. `npm install sfdx-cli --global`
2.  `sfdx force:source:deploy --checkonly --json --loglevel fatal  --testlevel RunLocalTests`
3.  `sfdx force:source:deploy--json --loglevel fatal --validateddeployrequestid <quickdeploy id from previous step>`

### Expected result

The quick deploy goes through.

### Actual result

The quick deployment goes through, but the sfdx cli returns an error.

The CLI returns:
```json
{
  "status": 1,
  "name": "soapenv:Client",
  "message": "Unexpected element {http://soap.sforce.com/2006/04/metadata}id during simple type deserialization",
  "exitCode": 1,
  "commandName": "SourceDeployCommand",
  "stack": "soapenv:Client: Unexpected element {http://soap.sforce.com/2006/04/metadata}id during simple type deserialization\n    at module.exports.HttpApi.getError (/usr/local/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/http-api.js:250:13)\n    at /usr/local/lib/node_modules/sfdx-cli/node_modules/jsforce/lib/http-api.js:95:22\n    at tryCallOne (/usr/local/lib/node_modules/sfdx-cli/node_modules/promise/lib/core.js:37:12)\n    at /usr/local/lib/node_modules/sfdx-cli/node_modules/promise/lib/core.js:123:15\n    at flush (/usr/local/lib/node_modules/sfdx-cli/node_modules/asap/raw.js:50:29)\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)\nOuter stack:\n    at Function.wrap (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at SourceDeployCommand.catch (/usr/local/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/ToolbeltCommand.js:248:46)\n    at async SourceDeployCommand._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at async Config.runCommand (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/usr/local/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/node_modules/sfdx-cli/dist/cli.js:114:21)",
  "warnings": []
}
```

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.88.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): -

**OS and version**: ubuntu-18.04 agent on Azure DevOps

Edited: Formatting and clarifications.

**Comment by mdonnalley** [comment]
Duplicate of https://github.com/forcedotcom/cli/issues/877

**Comment by nikhileshmishra** [comment]
@mdonnalley @bast-shb 

What was the solution for this error ? Is there any other way to resolve apart from forcing sfdx-cli to a previous version

**Comment by bast-shb** [comment]
@nikhileshmishra This has been solved, so if you update sfdx to the latest version it should work :)
