### ISSUE TITLE
Question: Expected behavior with two CustomLabel files in project

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/cli#88]
Question about expected behavior when a project has two CustomLabels.labels-meta.xml files anywhere in the project's packageDirectories.path 

I have a project that has two CustomLabels.labels-meta.xml files; one comes from a framework that we have copied into the project area.  The second comes from the true project folders themselves (outside of the copied framework).  The behavior suggests that the CustomLabels.labels-meta.xml file that is encountered first in the directory structure is used but the second one is ignored.

Is this the expected behavior from the CLI??

**Comment by aheber** [comment]
I have oft wished I could break apart these iterative types of files. It gets very difficult to maintain thousands of custom labels in a single file, especially with different groups merging changes into it.

I have run into various instances where a given file is listed twice in a project among two different directories and I can confirm that DX simply accepts the first. I would generally prefer it to fail for anything it is unable to merge together so I know I need to clean something up.

**Comment by joeferraro** [comment]
Seeing the same behavior and it's maddening

**Comment by ImJohnMDaniel** [comment]
@clairebianchi -- Anything that your team can share on this question?

**Comment by clairebianchi** [comment]
@ImJohnMDaniel, We currently do not have good support for multiple package directory paths. We are working on this in the Fall. This feedback is very helpful. 

Please add how you would like this to be handled. We are looking at both push and pull interactions. Push is mostly on the CLI, you place the metadata where you want it and the CLI should be able to figure out how to push. The Pull is harder as we need to figure out where to put new metadata. This could be done in the CLI by a prompt that has you tell us where each new metadata type should go, or always sending to the default and you move it manually, or letting you specify a package directory in the command for specific files. Let me know what you all think.

**Comment by ImJohnMDaniel** [comment]
@clairebianchi thanks for the update.  I guess I would expect that CLI to find all custom label references and merge them into one file for Metadata API deployment.  

To be honest, having all of the labels in a single file has been a pain over the years.  The MetadataAPI has always supported the CustomLabel attribute but the tools have never really managed it well.  We could hand craft a package.xml with the distinct CustomLabel entries and that helped.  

Ideally it would be great to have a distinct file for each custom label similar to the source format separating each custom field into a distinct file.  Then it would be much easier to manage these labels in source control.

@joeferraro or @aheber -- any other thoughts?

**Comment by aheber** [comment]
The concern I have with splitting the CustomLabel into individual files is that could result in a huge number of files being added to the project. DX's push/pull local change detection scales fairly linearly with the number of files, only being marginally impacted by the size of the file. We already have this problem with the thousands of files we keep in our static resources. I wonder what adding even 5k label files, or reaching the base limit of 10k, would do to the performance of such commands.

I really don't have a much better option. It is almost impossible to "correctly" modify that file locally as manually adding an entry almost always results in incorrectly alphabetizing inside of the file and the next time you push/pull it will be reordered and appear as a change. There is no file in our source that appears changed more often or causes more merge conflicts.

**Comment by ImJohnMDaniel** [comment]
@joeferraro and others.  I believe that I know the workaround here.  It would be to rename the CustomLabel files to something else. 

I am beginning to think that the issue is simply that there are multiple CustomLabels.labels-meta.xml files in the project.  During the `force:source:push` event, the files are copied to the temp folder and it most likely is nothing more than the "first one in wins" scenario.

Rename the CustomLabels.labels-meta.xml files to FooCustomLabels.labels-meta.xml and BarCustomLabels.labels-meta.xml and it should work.

**Comment by amphro** [comment]
The problem with renaming it is `source:pull` will likely shove them all back into the CustomLabels file. This is now supported with [multiple package directories](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_mpd.htm). We likely will never support multiple custom label files in the same package unless there is an overwhelming request from the community. Merging and splitting custom label files is not something we want to do and, as mentioned in Herber's comment, decomposing labels into multiple files is very subjective.
