### ISSUE TITLE
force:data:bulk:upsert in 'Serial' mode

### ISSUE THREAD

**Issue by DanWareing** [forcedotcom/cli#882]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my upsert jobs result in row lock errors. It would be great to have the option to perform them in serial mode. It's currently hard-coded as 'parallel': https://github.com/forcedotcom/salesforce-alm/blob/e5d29bc66cc4babdc6bf5ba935fec17bf485c1f1/src/lib/data/dataBulkUpsertCommand.ts#L49

**What are you trying to do**
Use the bulk api's 'serial' mode

**Describe the solution you'd like**
An additional argument allowing the user to specify 'parallel' or 'serial'

**Describe alternatives you've considered**
We've performed an extensive amount of optimization to avoid row locks altogether, but sometimes performing large updates/ upserts in series is the only option

**Additional context**
N/a

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-8934566](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000097SKIIA2/view)

**Comment by cristiand391** [comment]
This was added in plugin-data@0.6.0, which has been available in sfdx since v7.111.6: https://github.com/salesforcecli/sfdx-cli/commit/76bd752de0f5858e582f47190b3a669f207ebf35
