### ISSUE TITLE
Wrong User Id returned when executing sfdx force:user:create -f "definition file" 

### ISSUE THREAD

**Issue by gorazd-up2go** [forcedotcom/cli#883]
### Summary

When executing command "force:user:create -f" in scratch org the returned result gives false Id from user it created. Instead of getting Id for the user which was created it gives Id of user that executed (User User). 

### Steps To Reproduce:

1.  Create a definition file for user.
2. execute: sfdx force:user:create -f "definition file" 
3. Id returned is not the user id it has created.

### Expected result

Id that is returned should be Id of user that was created.

### Actual result

It returns me Id of "User User" so I think it gives Id of user that is executing the command.

### Additional information

Examples from output:

sfdx force:user:create -f "data/sampleData/users/01_harry-porter.json"
Successfully created user "1614198847563_test-mybmqhby8ovt@example.com" with ID 0051g000005vAqMAAU for org 00D1g0000002MHFEA2.
You can see more details about this user by running "sfdx force:user:display -u 1614198847563_test-mybmqhby8ovt@example.com".

sfdx force:user:create -f "data/sampleData/users/01_dyanna-dayne.json"
Successfully created user "1614198894296_test-mybmqhby8ovt@example.com" with ID 0051g000005vAqMAAU for org 00D1g0000002MHFEA2.
You can see more details about this user by running "sfdx force:user:display -u 1614198894296_test-mybmqhby8ovt@example.com".

So as you can see both new user return same Id (even if you output format is --json). When querying users this is returned:

ID                  FIRSTNAME    LASTNAME
──────────────────  ───────────  ─────────────────────────
0051g000005vAqMAAU  User         User
0051g000005vNpkAAE  Harry        Porter
0051g000005vNpzAAE  Dyanna       Dayne

Example of definition file:
{
  "FirstName": "Harry",
  "LastName": "Porter",
  "Division": "Stars Hollow",
  "Department": "City Administration",
  "LanguageLocaleKey": "en_US",
  "profileName": "Standard User",
  "UserPermissionsSFContentUser": false,
  "permsets": ["TeamUser"]
}

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.88.4-3b2e55c3f1 darwin-x64 node-v14.15.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/lwc-dev-server 2.10.0
├─ @oclif/plugin-update 1.3.10
└─ @oclif/plugin-help 2.2.3
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
auth 1.4.8 (core)
config 1.2.4 (core)
generator 1.1.5 (core)
salesforcedx 51.0.4 (core)
├─ user 1.1.2 (core)
├─ schema 1.0.4 (core)
├─ limits 1.0.4 (core)
├─ apex 0.1.4 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.11 (core)
├─ salesforce-alm 51.0.2 (core)
└─ templates 51.2.0 (core)
sfdx-cli 7.88.4 (core)
telemetry 1.1.1 (core)

**OS and version**:

MacOS 10.15.7

**Comment by FabienTaillon** [comment]
Returned values are initialized with `DefaultUserFields.create()` [here](https://github.com/salesforcecli/plugin-user/blob/main/src/commands/force/user/create.ts#L95).

Created user Id is only available after the user was created a few lines later by `this.user.createUser()` [ here](https://github.com/salesforcecli/plugin-user/blob/main/src/commands/force/user/create.ts#L103).

So I think after the user is created, default user Id value should be overridden with the one from the created user:
`fields.id = this.authInfo.getFields().userId;`

I tried and it works, but I don't understand enough how testing works to fix the tests.

Looking forward to the fix to learn how to do it 🔎

**Comment by gorazd-up2go** [comment]
Hard to say if this override is correct. It maybe could break something else that relies on "Id". 
I took a quick look and found this:
`117:        await this.user.assignPermissionSets(this.authInfo.getFields().userId, permsetArray);`
So perm sets are set with "userId". I deleted scratch org (so I cannot look at it) but if users created get correct perm set then this field is correct.

**Comment by FabienTaillon** [comment]
Yes you're right, `this.authInfo.getFields().userId` is the correct value to use (and is actually the one that is used, which is why the command works), but it's not the one that is returned by the command.

It's actually `fields` that is both [printed](https://github.com/salesforcecli/plugin-user/blob/main/src/commands/force/user/create.ts#L160) and [returned](https://github.com/salesforcecli/plugin-user/blob/main/src/commands/force/user/create.ts#L166) by the command.

All `fields` information have a [default value](https://github.com/salesforcecli/plugin-user/blob/main/src/commands/force/user/create.ts#L95), and they are then overridden in [aggregateFields()](https://github.com/salesforcecli/plugin-user/blob/main/src/commands/force/user/create.ts#L193).

At the end, all informations in `fields`, including `username` are related to the created user, except `id`.

I think the only reason why `id` isn't overridden too is that it's not yet available when this function is called, and not overriding it later may just be an omission.

**Comment by gorazd-up2go** [comment]
I think it is ok to "map" after creation since fields are locally used. Maybe some other fields are affected as well since they are taken over from default user and then never remapped with "maybe" new values. Maybe one consideration using aggregateFields only in other way around.

Regarding tests. Currently they are a bit wrong
test/commands/user/create.test.ts -> line 68
And this is then used to compare response. Basically Id === Id. I think tests should assert something from this line:
stubMethod($$.SANDBOX, User, 'create').callsFake(() => User.prototype);

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9036859](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000008mgyYAA/view)

**Comment by mshanemc** [comment]
Y'all, this is fixed in the latest version of the user plugin.

You can test it early by 
1. `sfdx install:plugins user`
2. update the cli to latest-rc
3. wait until 4/1's release to latest

**Comment by mshanemc** [comment]
released.
