### ISSUE TITLE
unsupported metadata type ManagedContentType

### ISSUE THREAD

**Issue by tejastdj** [forcedotcom/cli#885]
19:24:34.71 sfdx force:source:retrieve --manifest d:\Tejas\CRs\Visualstudio Workspace\CVCFull2\manifest\package.xml
ERROR running force:source:retrieve:  We can’t retrieve the specified metadata object: ManagedContentType. Certain metadata types, like ManagedContentType are not currently supported by the CLI.

**Comment by mshanemc** [comment]
That type is in the current registry.  Please respond if you still have problems with that command on a recent CLI version.

**Comment by vaibhavdangar-woolies** [comment]
Hi @mshanemc , 

I'm unable to get the below CLI working:
**cmd**
 sfdx force:source:retrieve --apiversion 54.0 -m ManagedContentType -u SF_USERNAME@DOMAIN

**log:**
[sfdx-log.txt](https://github.com/forcedotcom/cli/files/11096206/sfdx-log.txt)

**Comment by vaibhavdangar-woolies** [comment]
Also tried SF CLI

**cmd**
sf retrieve metadata --api-version 54.0 --metadata ManagedContentType -o SF_USERNAME@DOMAIN

**log:**
[sf-log.txt](https://github.com/forcedotcom/cli/files/11096273/sf-log.txt)

**Comment by cristiand391** [comment]
Hi @vaibhavdangar-woolies , could you create a new GH issue and follow the bug report template? This one is about a different error.

https://github.com/forcedotcom/cli/issues/new/choose
