### ISSUE TITLE
Inconsistent authentication with auth:jwt:grant

### ISSUE THREAD

**Issue by SanderElsen** [forcedotcom/cli#889]
### Summary

We're setting up some CI/CD pipelines for a new workflow we want to try out but are experiencing very inconsistent authentication results when using auth:jwt:grant.
(testing process in Additional information)

### Steps To Reproduce:

1.  https://trailhead.salesforce.com/en/content/learn/modules/sfdx_travis_ci/sfdx_travis_ci_connected_app
1.  authenticate x ∞

### Expected result

Successful login every time.

### Actual result

Seemingly random auth fails

### Additional information

![image](https://user-images.githubusercontent.com/8928650/109304898-3c9a1080-783d-11eb-8b6a-7f43fd82b58c.png)
To reproduce this we set up a loop to authenticate a couple of times and the problem already shows up.
We've ran the same test with no delay, 10s delay, and 1min delay on 3 different devices, for 6 devhubs, and 2 scratches per hub 
 and all the tests show the same inconsistency.
Results vary from 0/20 failing to 10/20 failing.

**SFDX CLI Version**
sfdx-cli/7.82.1-0 win32-x64 node-v14.13.0
sfdx-cli/7.86.3 darwin-arm64 node-v15.8.0
sfdx-cli/7.89.2-d1d2614d02 win32-x64 node-v14.15.4

**OS and version**:
1x Win10 Version 10.0.18363 Build 18363
2x Mac OS 11

**Comment by AllanOricil** [comment]
@SanderElsen maybe it is because in your simulation you are requesting too fast? What happens if you raise the time between each request? I don't really think this is the problem as the error message is not related, but if it is, then the error message is not right. But try increasing the time between requests and post the results here to see if the number of errors reduces when you increase the time between requests.

**Comment by AllanOricil** [comment]
@SanderElsen nice tests. but I think you should create N different SO to also verify that this problem only happens if you try to auth many times with the same SO. I don't think there will ever be a situation where you will auth to SO so many times in less than a minute.

**Comment by SanderElsen** [comment]
We did some more testing on different devices, turns out the issue is linked only to devices on a certain domain so this is probably an internal issue we have to resolve.
