### ISSUE TITLE
Receiving "The 'path' argument must be of type string. Received type object" during force:source:deploy/retrieve

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#89]
The full thread of discussion is available here for context:

https://success.salesforce.com/0D53A00004MMUPU

but the short version is that on May 10, 2019, I suddenly started to receive this error when deploying/retrieving metadata against my DE org using `force:source:deploy/retrieve`:

```
$ sfdx force:source:deploy -u alias -x manifest/package.xml --json
{
    "status": 1,
    "name": "TypeError [ERR_INVALID_ARG_TYPE]",
    "message": "The \"path\" argument must be of type string. Received type object",
    "exitCode": 1,
    "commandName": "SourceDeployCommand",
    "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received type object\n    at validateString (internal/validators.js:125:11)\n    at Object.join (path.js:427:7)\n    at CustomObjectSubtypeMetadataType.getAggregateMetadataFilePathFromWorkspacePath (c:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeImpl\\customObjectSubtypeMetadataType.js:29:21)\n    at new _SourceLocations (c:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceWorkspaceAdapter.js:31:64)\n    at new SourceWorkspaceAdapter (c:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceWorkspaceAdapter.js:49:28)\n    at SourceDeployApi.doDeploy (c:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceDeployApi.js:35:20)\nOuter stack:\n    at Function.wrap (c:\\Program Files\\Salesforce CLI\\client\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:151:27)\n    at SourceDeployCommand.catch (c:\\Program Files\\Salesforce CLI\\client\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:216:46)",
    "warnings": []
}
```

If you scroll to the bottom of that thread, I confirmed that the problem occurs against this org via the latest build of the Salesforce CLI from both Windows and Mac, and it does not occur against other orgs that I've tried. Whatever is going on seems to be specific to this org which has worked well for me for the past 5-6 years.

The organization ID is `00D610000006x9HEAQ`. I'm happy to provide support access to this organization for reproduction purposes. Just let me know when you're ready for that. Reproduction should be as simple as running:

```
$ sfdx force:source:retrieve -u <alias> -m 'CustomObject:Account'
```

**Comment by clairebianchi** [comment]
@SCWells72 I have added this to our backlog, we are a bit overwhelmed by stuff at the moment but someone will look at this next month.

**Comment by SCWells72** [comment]
@clairebianchi I can only imagine what the past several days have been like for you guys, and with TDX19 next week, I don't see any down-time in your near future! I've worked around this successfully by creating another DE org. Address then whenever you all come up for air. Good luck!

**Comment by renatoliveira** [comment]
I think this might not be fixed yet. Had the same problem running a `force:source:retrieve` command against a production org.

I tried the following command:

```
$ sfdx force:source:retrieve -m Flow
```

And I got the error:

>ERROR running force:source:retrieve:  The "path" argument must be of type string. Received type object

--- 

Managed to retrieve the flow metadata by running the same command against the "flows" folder instead:

```
sfdx force:source:retrieve -p force-app/main/default/flows
```

**Comment by pawelhajduk-ef** [comment]
It happens for me when executing the `sfdx force:source:deploy -p <package_path> -u <username>` command while having an incorrect directory structure in the package for example: 
```
├── CustomObject__c
├── profiles
|   ├── Profile1.profile-meta.xml
|   └── Profile2.profile-meta.xml
```
instead of
```
├── objects
|   └── CustomObject__c
├── profiles
|   ├── Profile1.profile-meta.xml
|   └── Profile2.profile-meta.xml
```

**Comment by andrewpajda** [comment]
Hey guys, 

I am having the same issue when trying to retrieve experienceBundle 

`C:\Users\apajda\Documents\apajda\salesforce>sfdx force:source:retrieve -u apajdaedcc -x extradom-app/main/default/package.xml --json
(node:14996) Warning: The .forceignore file doesn't adhere to .gitignore format which will be the default behavior starting in Spring '21 release. More information on .gitignore format here: https://git-scm.com/docs/gitignore. Fix the following lines in your .forceignore and add '# .forceignore v2' to your .forcei
gnore file to switch to the new behavior.
(node:14996) Warning:   package.xml
{
  "status": 1,
  "name": "TypeError",
  "message": "The \"path\" argument must be of type string. Received undefined",
  "exitCode": 1,
  "commandName": "SourceRetrieveCommand",
  "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received undefined\n    at validateString (internal/validators.js:120:11)\n    at Object.join (path.js:375:7)\n    at ExperienceBundleMetadataType.stripBundlePath (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfd
x-cli\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeImpl\\experienceBundleMetadataType.js:115:21)\n    at ExperienceBundleMetadataType.getRetrievedMetadataPath (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\lib\\source\\metadataTypeImpl\\exper
ienceBundleMetadataType.js:97:33)\n    at SourceWorkspaceAdapter.processMdapiFileProperty (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceWorkspaceAdapter.js:303:82)\n    at C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\n
ode_modules\\salesforce-alm\\dist\\lib\\source\\sourcePullApi.js:166:22\n    at Array.forEach (<anonymous>)\n    at MdapiPullApi._syncDownSource (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourcePullApi.js:158:31)\n    at SourceRetrieve.retrie
veFromManifest (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceRetrieve.js:177:64)\n    at async SourceRetrieve.retrieve (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\lib\\source\\sour
ceRetrieve.js:57:27)\n    at async SourceRetrieveCommand.execute (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\lib\\source\\sourceRetrieveCommand.js:32:16)\n    at async SourceRetrieveCommand.execLegacyCommand (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_
modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:149:29)\n    at async SourceRetrieveCommand.run (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\commands\\force\\source\\retrieve.js:32:16)\n    at async SourceRetrieveCommand._run (C:\\
Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:81:40)\n    at async Config.runCommand (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async Main.run (C:\\Users\\apa
jda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\nOuter stack:\n    at Function.wrap (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:171:27)\n    at SourceRetrieveCommand.catch (C:\\Users\\apa
jda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\salesforce-alm\\dist\\ToolbeltCommand.js:248:46)\n    at async SourceRetrieveCommand._run (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:85:13)\n    at async Config.runComma
nd (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\config\\lib\\config.js:173:24)\n    at async Main.run (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\main.js:27:9)\n    at async Main._run (C:\\Users\\apajda\\AppData\
\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\command\\lib\\command.js:43:20)\n    at async Object.run (C:\\Users\\apajda\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\dist\\cli.js:32:20)",
  "warnings": []
}
`

**Comment by mshanemc** [comment]
no longer reproducible for me on current plugin-source for the example that @pawelhajduk-ef shared 

The error message @SCWells72 sees won't occur with the new plugin (something else might though if the org is somehow broken).  I'll optimistically close this one.
