### ISSUE TITLE
Can't deploy. "That page name is already in use, please choose a different one", but page doesn't exist.

### ISSUE THREAD

**Issue by volkanunsal** [forcedotcom/cli#894]
### Summary

I'm unable to deploy a new version of a component. The deploy error tells me "That page name is already in use, please choose a different one." 

This component does not exist on the target org. (I deleted it.) And even if it did, I don't understand why the CLI is unable to overwrite it.

### Additional information

<img width="1105" alt="Screen Shot 2021-03-03 at 9 36 55 AM" src="https://user-images.githubusercontent.com/151600/109822459-f6f69280-7c04-11eb-83b0-c6ae6a4cf1c4.png">

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

```
sfdx-cli/7.89.2-d1d2614d02 darwin-x64 node-v14.15.4
```

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

```
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.5 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.5 (core)
auth 1.4.8 (core)
config 1.2.4 (core)
generator 1.1.5 (core)
salesforcedx 50.12.0 (50.12.0)
├─ templates 50.1.0
├─ custom-metadata 1.0.11
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ schema 1.0.4
├─ limits 1.0.4
├─ salesforce-alm 50.12.0
└─ apex 0.1.4
sfdx-cli 7.89.2 (core)
telemetry 1.1.1 (core)
```

**OS and version**: Mac OS

**Comment by peternhale** [comment]
@volkanunsal Would you mind providing the command you are using when encountering this error?

**Comment by volkanunsal** [comment]
I was using the VS Code. I’d right click on file and select Deploy.

**Comment by mshanemc** [comment]
That's an error from either VSCode or the server.  If you still see it happen in vscode, open an issue on their repo.

If it's not a VSCode problem, you'll have to open a support case.
