### ISSUE TITLE
During Retrieve extra file created that is unable to be deployed

### ISSUE THREAD

**Issue by Thrantor** [forcedotcom/cli#896]
### Summary

While using the SFDX command:
sfdx force:source:retrieve --manifest c:\Users\thran\Documents\USCG\pr-074696\manifest\package.xml

The location object was retrieve from dev. However, in the objects/Location folder there was a Location.field-meta.xml. But also in the objects/Location/fields directory there was another Location.field-meta.xml file.

This causes problems with the deploy to qa with the error:
An object 'object.Location' of type CustomField was named in package.xml, but was not found in zipped directory

As explored in https://developer.salesforce.com/forums/?id=9062I000000ILUzQAO... it looks like the deployment fails because there are files named the same in different directories under the same object.

I can work around this by adding the topmost file to the gitignore so it's not in the deployed package... But how do we get the retrieve to STOP pulling this file down. Each time my coworkers do the package retrieve they get the file.

And no other object includes an equivalent file.

--

### Steps To Reproduce:

Run a retrieve from our dev or QA box with the attached package.xml and you will see the extra files. I haven't tried this on another unattached org.

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  This is step 1.
1.  This is step 2. All steps should start with '1.'

### Expected result

Only one file should have been retrieved. The one in the fields directory

### Actual result

Two files of the same name were retrieved.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.83.0-eba9c6a927 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.4.3 (1.4.3)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.9.1 (core)
├─ schema 1.0.1 (core)
├─ limits 1.0.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 50.1.0 (core)
├─ salesforce-alm 50.9.0 (core)
├─ custom-metadata 1.0.10 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.83.0 (core)

**OS and version**:

Windows 10
![Screenshot 2021-03-03 124332](https://user-images.githubusercontent.com/5333144/109848334-206fe800-7c1e-11eb-857b-e8c651a10cce.png)

[package-xml.zip](https://github.com/forcedotcom/cli/files/6078045/package-xml.zip)

**Comment by mshanemc** [comment]
I'm trying to reproduce this and not able to.  You're on an older version of the CLI...can you try updating to see if you can still get the issue?

If so, let me know and I can try it on Windows.
