### ISSUE TITLE
Publish web apps built with LWC to Salesforce with single command, like we do on heroku

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#903]
**Is your feature request related to a problem? Please describe.**
No, it is just that it would be cool to have lwc web apps hosted inside salesforce using just one command, the same way we can do when we deploy to Heroku. What do you think?

**What are you trying to do**
deploy lwc web apps to salesforce

**Describe the solution you'd like**
Maybe something like this `sfdx force:lwc:site:deploy` and `sfdx force:lwc:site:publish`

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-8976596](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008ZukZIAS/view)
