### ISSUE TITLE
Retrieve object metadata without retrieving fields, list views and so on with sfdx force:source:retrieve

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#911]
**Is your feature request related to a problem? Please describe.**
Today I had to retrieve only the Object metadata for the Asset object and when I ran `sfdx force:source:retrieve -m "CustomObject:Asset"` it also brought all standard and custom fields and then I had to rollback the changes for the fields I had, and also delete each one of the standard fields, as I did not need to package those.

**What are you trying to do**
retrieve only the Object metadata using `sfdx force:source:retrieve`

**Describe the solution you'd like**
Add an exclude flag that accepts an array of metadata to exclude.

**Describe alternatives you've considered**
I can ignore the fields folder in the .forceignore

**Additional context**
NA

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-8986396](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008ZzhRIAS/view)

**Comment by Thrantor** [comment]
This is a good first step, but we also need to be able to pull the object information and SPECIFIC fields as well. If I've got two developers working and they each are working on the same object but with different fields... if they both use CustomObject of Account it pulls the others fields. But if we don't include the "CustomObject" of Account... the proflles come out all messed up.

We need to be able to have the retrieve command retrieve the object by itself and then the specific fields we request in the package.xml. That way the profiles are correct per person. And when we merge them in source control everything comes out correct.
