### ISSUE TITLE
Mismatched version in @salesforce/plugin-config

### ISSUE THREAD

**Issue by ArielS1** [forcedotcom/cli#914]
Hi,

I uninstalled Salesforce CLI and installed the latest version 7.81.0.0 on Windows 10.

I'm getting warnings since then from Illuminated Cloud 2 CLI:

Salesforce CLI: (node:5352) Warning: Mismatched version in @salesforce/plugin-config plugin manifest. Expected: 1.2.1 Received: 1.1.8This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.(node:5352) Warning: Mismatched version in @salesforce/plugin-alias plugin manifest. Expected: 1.1.3 Received: 1.1.1This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.You acknowledge and agree that the CLI tool may collect usage information, user environment, and crash reports for the purposes of providing services or functions that are relevant to use of the CLI tool and product improvements. 

Salesforce CLI: (node:5944) Warning: Mismatched version in @salesforce/plugin-config plugin manifest. Expected: 1.2.1 Received: 1.1.8This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.(node:5944) Warning: Mismatched version in @salesforce/plugin-alias plugin manifest. Expected: 1.1.3 Received: 1.1.1This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.

Salesforce CLI: (node:10472) Warning: Mismatched version in @salesforce/plugin-config plugin manifest. Expected: 1.2.1 Received: 1.1.8This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.(node:10472) Warning: Mismatched version in @salesforce/plugin-alias plugin manifest. Expected: 1.1.3 Received: 1.1.1This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.

Anything i can do about it?

**Comment by mshanemc** [comment]
I'm going to close this @ArielS1 .  

If you're stilling having the problem, please open a new issue on this repo _because it'll walk you through what's needed to make a great error report (getting the versions of all the parts of the CLI)_
