### ISSUE TITLE
.forceignore v2 warning when ignoring **/README.md

### ISSUE THREAD

**Issue by lukecotter** [forcedotcom/cli#916]
### Summary
.forceignore v2 warning when ignoring **/README.md

Received this warning when trying to run force:source:push, the push is successful I just get a warning.

`(node:3085) Warning: The .forceignore file doesn't adhere to .gitignore format which will be the default behavior starting in Spring '21 release. More information on .gitignore format here: https://git-scm.com/docs/gitignore. Fix the following lines in your .forceignore and add '# .forceignore v2' to your .forceignore file to switch to the new behavior.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3085) Warning:    **/README.md`

The ignore pattern in use was to ignore all README.md files in all dirs.

### Steps To Reproduce:

1. Create a project with a README.md file
1. Add ` **/README.md` to `.forceignore`
1. Use`force:source:push` 
1. You will get the error

### Expected result

Seem like it is a valid ignore pattern based on git ignore, so no warning should be seen.

### Actual result
I get this error instead.

`(node:3085) Warning: The .forceignore file doesn't adhere to .gitignore format which will be the default behavior starting in Spring '21 release. More information on .gitignore format here: https://git-scm.com/docs/gitignore. Fix the following lines in your .forceignore and add '# .forceignore v2' to your .forceignore file to switch to the new behavior.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3085) Warning:    **/README.md`

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
![image](https://user-images.githubusercontent.com/4013877/110872383-98e24300-82c7-11eb-83a1-a38b686206b6.png)

**OS and version**: MacOS Big Sur: 11.2 (20D64)

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9051899](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH00000094efYAA/view)

**Comment by mshanemc** [comment]
https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md#51140-may-27-2021---cli-71030

**Comment by lukecotter** [comment]
I still see the warning when pushing, the push works though. 
forceignore is set to v2.

here is the warning on latest cli
![image](https://user-images.githubusercontent.com/4013877/124088185-99574300-da4a-11eb-81c0-88a0775feb41.png)

and the versions
![image](https://user-images.githubusercontent.com/4013877/124088866-4762ed00-da4b-11eb-9ffa-f562df7ed83b.png)

**Comment by gfmmoreira** [comment]
@lukecotter @mshanemc I am facing the same issue while adding a README.md file to the existing .forceignore configuration file.

The line I am adding is `**/unpackaged/README.md`, which as @lukecotter mentioned seems to be adhering to the gitIgnore format.

**Comment by gfmmoreira** [comment]
@mshanemc I am also facing this issue while adding a `README.md` file to `forceIgnore`.

Below are the lines which are triggering the warning:
```
# Unpackaged
**/unpackaged/README.md
```

The output of sfdx plugins:
```
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-scanner 2.11.0
salesforcedx 52.0.0
├─ data 0.4.11
├─ apex 0.2.2
├─ limits 1.2.1
├─ custom-metadata 1.0.12
├─ schema 1.0.7
├─ user 1.3.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ org 1.6.6
├─ templates 51.5.0
└─ salesforce-alm 52.0.0
```

And the output of sfdx --version:
```
sfdx-cli/7.114.0 darwin-x64 node-v14.17.5
```

The lines seem to be adhering the gitignore format as mentioned by @lukecotter, so no apparent reason for the warning message to appear.
