### ISSUE TITLE
SFDX: Refresh SObject Definitions does not work

### ISSUE THREAD

**Issue by JodieM** [forcedotcom/cli#917]
### Summary

Whenever I run SFDX: Refresh SObject definitions in one org, it does not run. The command just sits there spinning in the status bar. 
I have tried each of the options - Custom, Standard, and All. 
This is a brand new VSCode org created yesterday from a new Partial Sandbox. 
The command works on another org fine. 
I have updated my CLI and all plugins. 
I have disabled all extensions and reanbled them. 
I have restarted VSCode many times.
I have set salesforcedx-vscode-apex.enable-sobject-refresh-on-startup to true

### Steps To Reproduce:

1.  Run SFDX: Refresh SObject definitions

### Expected result

Definitions are updated

### Actual result

The command just keeps running - I have left it for many hours.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.91.0-6a6ed69ebe win32-x64 node-v14.15.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.10 (core)
config 1.2.6 (core)
etcopydata 0.5.7
generator 1.1.5 (core)
salesforcedx 51.3.0 (core)
├─ schema 1.0.4 (core)
├─ limits 1.0.4 (core)
├─ user 1.1.2 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ templates 51.3.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.3.0 (core)
sfdx-cli 7.91.0 (core)
sfdx-flowdoc-plugin 0.5.1
sfdx-migration-automatic 3.0.0
shane-sfdx-plugins 4.43.0
├─ @mshanemc/plugin-streaming 1.1.7
└─ @mshanemc/sfdx-sosl 1.1.0
telemetry 1.1.1 (core)

**OS and version**:
Windows 10

**Comment by mshanemc** [comment]
Hey, @JodieM !

Have you reached out to the VSCode extensions team about it or looked through their issues?  https://github.com/forcedotcom/salesforcedx-vscode/issues

It might still be the CLI's fault somewhere in there, but they may have a better idea of what that command does.

**Comment by JodieM** [comment]
For those playing along at home, here is another ticket on the VSCode repo https://github.com/forcedotcom/salesforcedx-vscode/issues/2406 that states that you must Authorize your org immediately before running Refresh SObject Definitions... I don't know if that's it, but doing it specifically that way and it works now.
