### ISSUE TITLE
Unable to convert single metadata file with sfdx force:mdapi:convert

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#919]
### Summary

After extracting some duplicate rules with mdapi command I needed to convert only one to source format. I tried to do it in several ways as you can see below. At first, I thought the problem was the destination folder, but after converting the whole duplicateRules folder, and using the same destination folder, the conversion worked. So I concluded that the cli does not work with file paths, only with folder paths.

![image](https://user-images.githubusercontent.com/55927613/111171816-2e6a2500-859d-11eb-9911-8d6aa06116f2.png)

If this is working as designed, I would like to convert it to a feature, as this is a command that Im often using. The reason I did not extracted using the source command was because I did not know the metadata name. So I had to extract using the mdapi command passing  package.xml for duplicateRules and using *.

### Steps To Reproduce:

Extract any metadata type

Run `sfdx force:mdapi:convert -r PATH_TO_METADATA_FILE` 

Verify you can't convert the file

Run `sfdx force:mdapi:convert -r PATH_TO_METADATA_TYPE_FOLDER`

Verify you can convert the folder but not a single file

### Expected result

The command should convert single files

### Actual result

The command only converts files if the input is a folder

### Additional information

![image](https://user-images.githubusercontent.com/55927613/111172652-e8619100-859d-11eb-9c88-4b61f6da6461.png)

**Comment by mshanemc** [comment]
Can you try that on the new `force:mdapi:beta:convert` to see if it fixes the problem?

**Comment by AllanOricil** [comment]
Yes, I will try it tomorrow

**Comment by AllanOricil** [comment]
@mshanemc how do I install the beta command?

**Comment by AllanOricil** [comment]
@mshanemc it is still not possible to convert a single file.

![Screenshot 2021-12-04 at 20 55 24](https://user-images.githubusercontent.com/55927613/144728222-e58d9e40-d73b-4d3e-9075-ef0d6290d088.png)

If you print the command parameters, you will see that there `-r` only accepts directories. What I wan't to do is to pass a List of files to convert instead of creating a `package.xml`.

Example:

`sfdx force:mdapi:beta:convert -m "ApexClass:MyClass,ApexClass:MyClass2"`

or

`sfdx force:mdapi:beta:convert -r PATH_TO_METADATA/classes/MyClass.cls`

**Comment by AllanOricil** [comment]
But this does not need to be prioritize, as there is a way of converting a single file creating a `package.xml`

**Comment by shetzel** [comment]
What about using the `-p` / `--metadatapath` param?

**Comment by AllanOricil** [comment]
You are right. It was my mistake. Thanks
