### ISSUE TITLE
Facing issues with deploying the components from the source to the org.

### ISSUE THREAD

**Issue by SethMagner** [forcedotcom/cli#92]
21:21:35.906 sfdx force:source:deploy --sourcepath c:\ISODEV1Local\force-app\main\default\aura\GPS_COMP_MemberSearchResultsContainer\GPS_COMP_MemberSearchResultsContainerHelper.js --json --loglevel fatal ended with exit code 1
 
When tried to run the sfdx command, we are getting the below error. This seems to be happening across all developers. When researched online there were posts to delete the files within our C:\Users\xxxxx\AppData\Local\sfdx\client. We deleted the files and it worked when we retrieved the source from org but then again the same error re-occurred when we tried to deploy back

H:\>sfdx
internal/modules/cjs/loader.js:584
    throw err;
    ^
 
Error: Cannot find module '../dist/versions'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\n217935\AppData\Local\sfdx\client\bin\sfdx.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by clairebianchi** [comment]
This bug has been added to our internal backlog. I will update again when it is fixed.

**Comment by clairebianchi** [comment]
@SethMagner can you send us the version of the CLI you are on? please run the following commands:

sfdx --version
sfdx plugins --core

**Comment by SethMagner** [comment]
Hi @clairebianchi not sure how to pull the version of cli, since the command will not work on systems that have the issue.  Our install is set to auto update, sfdx-cli/7.5.0-e6ca93eee8 win32-x64 node-v10.15.3

The plugins are also set to 
H:\>sfdx plugins --core
@oclif/plugin-commands 1.2.2 (core)
@oclif/plugin-help 2.1.6 (core)
@oclif/plugin-not-found 1.2.2 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.2 (core)
analytics 1.1.2 (core)
generator 1.1.0 (core)
salesforcedx 45.12.0 (core)
├─ force-language-services 45.10.0 (core)
└─ salesforce-alm 45.15.0 (core)

sfdx-cli 7.5.0 (core)

**Comment by SethMagner** [comment]
Along with this issue if you remove the client or bin folder, the sfdx command runs and can be udpated.  Though we see error when running the update, "(Node:15448) [Module_not_found] Error plugin: sfdx-cli:  cannot find module 'C:\Users\xxxxx\AppData\Local\sfdx\client\dist\hooks\lazyRequire.js' module: @oclif/config@1.12.11
task: runhook update

**Comment by SethMagner** [comment]
Hi @clairebianchi do we have any updates?

**Comment by drd0013** [comment]
I just ran into this issue too. Any idea of a fix or workaround? (on mac)

**Comment by drd0013** [comment]
installing via npm seems to have worked, though I didn't remove any existing files before doing so. Hopefully I won't run into conflicts around that

**Comment by clairebianchi** [comment]
@SethMagner sorry for the delay in response, we made updates to the source:deploy command in the .46 release and I am wondering if this has fixed your issue. Would you mind updating and trying again?

**Comment by rasmuszimmer** [comment]
I am suddenly facing similar issue (not sure actually). 

+ /usr/local/salesforce/cli/bin/sfdx update
 ▸    sfdx-cli: update available from 6.51.1-ba7205094b to 7.15.3-c7d407d236
sfdx-cli: Updating CLI...
sfdx-cli: Updating CLI from 6.51.1-ba7205094b to 7.15.3-c7d407d236... finishing up
sfdx-cli: Updating CLI from 6.51.1-ba7205094b to 7.15.3-c7d407d236... done
 ›   Warning: You acknowledge and agree that the CLI tool may collect usage 
 ›   information, user environment, and crash reports for the purposes of 
 ›   providing services or functions that are relevant to use of the CLI tool 
 ›   and product improvements.
sfdx-cli: Updating CLI... already on latest version: 7.15.3-c7d407d236
/usr/local/salesforce/cli/bin/sfdx force:auth:jwt:grant --clientid blabal --jwtkeyfile /home/jenkins/.m2/repository/server.key --username sfdc-jenkins@blabla -a someOrg -r https://test.salesforce.com
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/jenkins/.local/share/sfdx/client/dist/versions.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by ghost** [comment]
@SethMagner @rasmuszimmer Are you still experiencing this issue? I'm unable to reproduce it and believe it was fixed in a previous release. Can you verify if it was fixed or not, thanks.

**Comment by rasmuszimmer** [comment]
Haven't seen it for a good while, and have updated CLI a few times since.

**Comment by harshad22dani** [comment]
I am still getting this error. I think my VSCode is latest one.
Following are the version details found on my terminal

 ****sfdx --version****
sfdx-cli/7.36.0-b1c4e9c7c8 win32-x64 node-v10.15.3
 **sfdx plugins --core**

@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)

sfdx-cli 7.36.0 (core)

**Comment by svadariyagit** [comment]
I am facing the same issue, My SFDX CLI is running on  7.36.0-b1c4e9c7c8.
I tried to upgrade to new version but apparently this is the latest version

**Comment by svadariyagit** [comment]
> @SethMagner @rasmuszimmer Are you still experiencing this issue? I'm unable to reproduce it and believe it was fixed in a previous release. Can you verify if it was fixed or not, thanks.

I am still facing this issue, below is my version details. I hope VS code version does not matter here
sfdx --version
sfdx-cli/7.36.0-b1c4e9c7c8 win32-x64 node-v10.15.3

sfdx plugins --core
@oclif/plugin-commands 1.2.3 (core)
@oclif/plugin-help 2.2.1 (core)
@oclif/plugin-not-found 1.2.3 (core)
@oclif/plugin-plugins 1.7.8 (core)
@oclif/plugin-update 1.3.9 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.5 (core)
analytics 1.2.1 (core)
generator 1.1.1 (core)
salesforcedx 47.9.0 (core)
├─ salesforcedx-templates 47.9.0 (core)
└─ salesforce-alm 47.10.0 (core)

sfdx-cli 7.36.0 (core)

**Comment by lcoffin** [comment]
Our team has been having the same issue as well (the "Cannot find module '../package.json'") since at least mid-December. Removing the latest version of the CLI (removing the "C:\Users\<username>\AppData\Local\sfdx\client" folder) works to get rid of the package.json error, but takes us back to other errors (in particular we can't create a new project...). I hope this can get fixed soon as it's severely limiting our ability to use VS Code.

(And just for reference... the Cannot find module package.json error impacts all use of the CLI -- even just "sfdx --version" -- not just deploying components to the org: retrieving, diffs, etc.)

**Comment by smedirocket** [comment]
So,did this issue got fixed. I am running into this error

**Comment by mshanemc** [comment]
we have this marked internally as fixed/closed.  Updating github to match. W-6162081

If you can still reproduce it, please open a new issue
