### ISSUE TITLE
Add e2e tests with sample packages to avoid introducing regressions

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#920]
It would be nice if you could add e2e tests for every command just to avoid introducing errors such as this one

https://github.com/forcedotcom/cli/issues/884?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE2MjM4ODQ1NDA6NTU5Mjc2MTM%3D&notifications_query=reason%3Aparticipating#issuecomment-799831100

Also add a "badge" on the README to show test status for the current version, so people are aware if they should or not upgrade their sfdx.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9012397](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008aBDBIA2/view)

**Comment by RodEsp** [comment]
Hi @AllanOricil we are currently in the process of improving the e2e tests for the CLI and associated plugins. Including adding more for Windows and running them for every release of every plugin.

You can see the status of the CLI build and each plugins' build already at https://github.com/salesforcecli/status.

**Comment by AllanOricil** [comment]
@RodEsp this is cool. Thank you
