### ISSUE TITLE
Deploy errror

### ISSUE THREAD

**Issue by rsrini3** [forcedotcom/cli#921]
I am trying to deploy an unlocked package using this command: sfdx force:source:deploy  -p

I get this error: 

*** Deploying with REST ***
ERROR running force:source:deploy:
<html>
<body>

<table cellspacing=10>
    <tr>
        <td><span style="font-weight: bold; font-size: 12pt;">Illegal Request</span></td>
    </tr>
    <tr>
        <td>You have sent us an Illegal URL or an improperly formatted request.
        </td>
    </tr>
    <tr>
        <td>

        </td>
    </tr>
</table>

<script type="text/javascript">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken="null";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>

</body>
</html>

Can you please help?

**Comment by tfuda** [comment]
I began hitting this myself after upgrading to version 7.91.0-6a6ed69ebe from 7.85 yesterday. I noticed this "Deploying with REST" message being logged and had not noticed that before. I saw that the release notes for 7.90.2 called out a change to the default behavior from using SOAP to using REST for deployment: [https://github.com/forcedotcom/cli/tree/main/releasenotes#5122-march-4-2021---cli-7902](https://github.com/forcedotcom/cli/tree/main/releasenotes#5122-march-4-2021---cli-7902). So, I set the SFDX_REST_DEPLOY environment variable to false, and this solved my problem. Searches for that error message seem to point to the fact that URLs need to be encoded differently when using the REST API: [REST API - You have sent us an Illegal URL or an improperly formatted request](https://salesforce.stackexchange.com/questions/93976/rest-api-you-have-sent-us-an-illegal-url-or-an-improperly-formatted-request), so I suspect is has something to do with URL encoding.

**Comment by RodEsp** [comment]
Indeed, @tfuda is correct. This is a REST API issue that the CLI is simply surfacing.
You can set the `SFDX_REST_DEPLOY` environment variable to `false` to use the SOAP API.

We're triaging other REST API issues at https://github.com/forcedotcom/cli/issues/860 so you can follow that for more information.

**Comment by rsrini3** [comment]
That worked for me. Appreciate your help

Raghu
