### ISSUE TITLE
SFDX: Retrieve for a static resource file, creates a duplicate nested folder.

### ISSUE THREAD

**Issue by adityababbar** [forcedotcom/cli#926]
### Summary

SFDX: Retrieve for a static resource file, creates a duplicate nested folder.

### Steps To Reproduce:

1.  Open a static resource and go to any file ( e.g. a .js file).
2.  Do a SFDX: Retrieve on that file.

### Expected result

The file should be retrieved with the directory structure of the static resource folder remaining intact.

### Actual result

A duplicate nested folder is created with content refreshed in the sub directory where the file refreshed is located. The content of the file changes to following
<?xml version="1.0" encoding="UTF-8"?>
<StaticResource xmlns="http://soap.sforce.com/2006/04/metadata">
    <cacheControl>Private</cacheControl>
    <contentType>application/x-zip-compressed</contentType>
    <description>Detail page resources (JS/CSS/etc)</description>
</StaticResource>

### Additional information
![image](https://user-images.githubusercontent.com/4994304/109883777-eae0f400-7c49-11eb-8974-285b77b9cb39.png)

**VS Code Version**: 1.53.2

**SFDX CLI Version**: 51.2.0

**OS and version**: Window 10, 10.0.17763 Build 17763

**Comment by mshanemc** [comment]
This works for me in the new plugin-source from the CLI
```
➜  748 sfdx force:source:retrieve -p force-app/main/default/staticresources/test/hi.js 
Preparing retrieve request... done
=== Retrieved Source
FULL NAME  TYPE            PROJECT PATH
─────────  ──────────────  ─────────────────────────────────────────────────────────────
test       StaticResource  force-app/main/default/staticresources/test.resource-meta.xml
test       StaticResource  force-app/main/default/staticresources/test/hi.js
```

If it's a problem in vscode, please open another repro there 
https://github.com/forcedotcom/salesforcedx-vscode
