### ISSUE TITLE
SFDX JWT authorization failing with Jenkins

### ISSUE THREAD

**Issue by anupam081** [forcedotcom/cli#927]
### Summary

i have configured multi pipeline project in jenkins using jenkinsfile and when i am trying to authorize with sfdx auth:jwt:grant, the authorization is failing.
When i am running this command from the command prompt it is successfully authorizing the dev hub

### Steps To Reproduce:

**Repository to reproduce:** [https://github.com/anupam081/CIwithJenkins)

1.  Setup multi pipeline project with jenkins
1.  run the build now 

### Expected result

It should have authorized the dev hub successfully

### Actual result

it is failing with below result
ERROR running auth:jwt:grant:  We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Hereâ€™s the error: We encountered a JSON web token error, which is likely not an issue with Salesforce CLI. Hereâ€™s the error: The service and account specified in key.json do not match the version of the toolbelt.
[Pipeline] error
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: hub org authorization failed
Finished: FAILURE

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.91.0-6a6ed69ebe win32-x64 node-v14.15.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) : 
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.3 (1.4.3)
config 1.2.6 (core)
generator 1.1.5 (core)
salesforcedx 51.3.0
├─ limits 1.0.4
├─ schema 1.0.4
├─ user 1.1.2
├─ custom-metadata 1.0.11
├─ apex 0.1.4
├─ templates 51.3.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
└─ salesforce-alm 51.3.0
sfdx-cli 7.91.0 (core)
telemetry 1.1.1 (core)

**OS and version**: EC2 windows server 2019

**Comment by mshanemc** [comment]
That error is coming from here: https://github.com/forcedotcom/sfdx-core/blob/c13fe4fed1c258d206a40606054db2262cb70ee1/messages/encryption.json#L17

called from here: 
https://github.com/forcedotcom/sfdx-core/blob/c13fe4fed1c258d206a40606054db2262cb70ee1/src/keyChainImpl.ts#L505

which is **typically** an error with the key.json file.  It might be read/write collision.  Is the auth command being run only once for the multi-pipelines, or might more than one process be trying to perform the same operation simultaneously?

**Comment by anupam081** [comment]
> lti-pipelines, or might more than one process be trying to perform the same operation simultaneously?

The jenkins files is used and the auth command is called only once in the start when the  pipeline is build.
Please check the jenkins file in the repo ( https://github.com/anupam081/CIwithJenkins/blob/main/Jenkinsfile ) in the issue.

I also notices that the sfdx cli version is showing me 7.91 when checking it from command prompt, when i checked from the jenkinsfile the version is showing as 7.83

**Comment by mshanemc** [comment]
What command(s) are you using to get the CLI installed/updated into your jenkins machine?  

I'm **guessing** the problem may be related to that old CLI version.

**Comment by anupam081** [comment]
I installed using the installer which I installed on my Jenkins server and then have
set the path in toolbelt for Jenkins.

**Comment by mshanemc** [comment]
can you try either 1) installing it from npm instead of the installer or 2) adding the `sfdx update` command post-install so it gets to something more recent?

**Comment by anupam081** [comment]
> can you try either 1) installing it from npm instead of the installer or 2) adding the `sfdx update` command post-install so it gets to something more recent?

Hi
Tried both..
when i run "sfdx plugins --core" on command prompt i get below result, which shows i am on the current version of sfdx.
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.5.1 (core)
config 1.2.7 (core)
generator 1.1.5 (core)
salesforcedx 51.5.0 (core)
├─ limits 1.0.4 (core)
├─ schema 1.0.4 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ org 1.5.0 (core)
├─ templates 51.3.0 (core)
├─ user 1.2.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.3 (core)
sfdx-cli 7.93.1 (core)
telemetry 1.1.1 (core)


when i run "sfdx plugins --core" from jenkinsfile i get below result, seems jenkins is not picking the sfdx updates
C:\Windows\system32\config\systemprofile\AppData\Local\Jenkins\.jenkins\workspace\Hoaela_voila>sfdx plugins --core 
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.6.0 (core)
â”œâ”€ salesforce-alm 50.6.0 (core)
â”œâ”€ templates 50.1.0 (core)
â”œâ”€ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
â”œâ”€ custom-metadata 1.0.10 (core)
â”œâ”€ schema 1.0.1 (core)
â””â”€ apex 0.1.4 (core)
sfdx-cli 7.81.0 (core)

And i am getting the same error when authorizing with JWT.

**Comment by anupam081** [comment]
Hi 
Any update on this issue?

**Comment by mshanemc** [comment]
If you could get your jenkins to install or update to the current version it would work.

**Comment by anupam081** [comment]
Hi 
I tried below but still i am getting the same error:
 - Upgraded jenkins to the latest version
- removed the custom tool plugs and used the installation url in the jenkins file
- uninstalled and reinstalled jenkins in another folder
- Upgraded by SFDX CLI to version 103.

**Comment by mshanemc** [comment]
sorry this got buried and I didn't check back...did you get it figured out?

**Comment by anupam081** [comment]
Yes reinstalling fixed the problem.

**Comment by shashi202012** [comment]
[anupam081](https://github.com/anupam081) how you have fixed the error. Can you please tell me
