### ISSUE TITLE
sfdx force:source:deploy does not work with ExperienceBundle and manifest/package.xml file (-x)

### ISSUE THREAD

**Issue by peterknolle** [forcedotcom/cli#931]
### Summary
source deploy with package.xml and ExperienceBundle does not deploy

`sfdx force:source:deploy -x myPackage.xml -u user@user.org`

https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_experiencebundle.htm

### Steps To Reproduce:

1. Enable the ExperienceBundle metadata type https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_experiencebundle.htm
2. Create a myPackage.xml file with 
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>CommunityMdName</members>
        <name>ExperienceBundle</name>
    </types>
    <version>51.0</version>
</Package>
```

3. Run `sfdx force:source:deploy -x myPackage.xml -u user@user.org`
### Expected result
The experience bundle is deployed

### Actual result
Nothing was deployed

### Additional information
https://salesforce.stackexchange.com/questions/337331/how-to-deploy-parts-of-experiencebundle-from-source-with-package-xml-x-option

Running with export `SFDX_MDAPI_TEMP_DIR=metadata` and I see the generated package.xml does not contain the ExperienceBundle and the experiences source directory is not in the generated `sfdx_sourceDeploy_pkg_161615915123` directory.

**Comment by aheber** [comment]
@peterknolle, I'm curious about this one. I use experience bundles as well and use the `force:source:deploy -x/--manifest` and do have items deployed that way. Curious what the differences are in our setup that are causing you're not to build.

Maybe a silly question but are you using the experience name with the trailing `1`? I see a lot of people, myself often included, providing the base format of the experience name and DX will run without included the metadata because it couldn't resolve it to actual metadata name. Just throwing out ideas.

**Comment by peterknolle** [comment]
@aheber - Do you also include Sites, Network, etc? I only have the ExperienceBundle.

**Comment by aheber** [comment]
@peterknolle, in that process no I don't. I include the other items when building scratch orgs but when I'm using a manifest I'm just pushing in a delta of changes and those base metadata almost never change. Let me see if I can dig up a manifest file from one of those deltas to confirm.

**Comment by aheber** [comment]
OK, I've confirmed on my own machine (Windows 10) that I can take a sample package.xml both with `<members>*</members>` as well as `<members>community1</members>` and it correctly builds the experiences into the deployment package, no supporting metadata necessary.

For what it is worth, my typical use case for this is also using `sfdx-git-delta` and we push against scratch org snapshots (beta).

![image](https://user-images.githubusercontent.com/2173116/111801008-21e21700-8892-11eb-8def-a3a029b8bb6c.png)

```
sfdx --version
sfdx-cli/7.90.2-b8f9206a5c win32-x64 node-v14.15.4

sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.10 (core)
config 1.2.6 (core)
generator 1.1.5 (core)
salesforcedx 51.1.1 (core)
├─ limits 1.0.4 (core)
├─ schema 1.0.4 (core)
├─ user 1.1.2 (core)
├─ custom-metadata 1.0.11 (core)
├─ apex 0.1.4 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ templates 51.3.0 (core)
└─ salesforce-alm 51.1.1 (core)
sfdx-cli 7.90.2 (core)
sfdx-devops 0.4.1
sfdx-heber 0.0.2
sfdx-typegen 0.6.2
sfpowerkit 2.7.8
shane-sfdx-plugins 4.43.0
├─ @mshanemc/sfdx-sosl 1.1.0
└─ @mshanemc/plugin-streaming 1.1.7
telemetry 1.1.1 (core)
```

**Comment by peterknolle** [comment]
@aheber OK. That's good. It must be a configuration/bug/api-version on my end. In the meantime, I can just convert it to metdata using the force:source:convert command with a package.xml file, then back to source and deploy from that.

sfdx-cli/7.92.0-88320113e7 darwin-x64 node-v14.15.4

11:37 $ sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.10 (core)
config 1.2.6 (core)
generator 1.1.5 (core)
salesforcedx 51.0.2 (latest-rc)
├─ limits 1.0.3
├─ schema 1.0.3
├─ user 1.1.0
├─ apex 0.1.4
├─ custom-metadata 1.0.11
├─ templates 51.1.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
└─ salesforce-alm 51.0.1
sfdx-1commerce-plugin 0.0.3
sfdx-cli 7.92.0 (core)
sfdx-git-delta 4.2.2
telemetry 1.1.1 (core)
![image](https://user-images.githubusercontent.com/3515617/111806360-46e18480-88a8-11eb-808e-bcec20f4a6c7.png)

**Comment by peterknolle** [comment]
Closing. Seems to be something specific to me.

**Comment by shetzel** [comment]
@peterknolle - Just pointing out that the version of your salesforcedx plugin has become outdated with the version of the CLI you have.  Maybe that's what you want but in case it isn't you can `sfdx plugins:uninstall salesforcedx` to go back to the salesforcedx plugin version bundled with v7.92.0 of the CLI.
