### ISSUE TITLE
sfdx force:org:list --all --json output is missing a Trailhead playground environment

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#933]
### Summary

I have one org connected to sfdx that is not being displayed in the output when running `sfdx force:org:list --all` or `sfdx force:org:list --all --json`. This org is a trailhead playground.  In the picture below I show that vscode sees it. Even if sfdx does not show it, it knows it exists, as I can use `sfdx force:org:open -u Playground2`.

![image](https://user-images.githubusercontent.com/55927613/111994440-af7e6a80-8b0f-11eb-844a-8790c48d73a3.png)

The plugin version is 1.5.0
![image](https://user-images.githubusercontent.com/55927613/111995116-7abee300-8b10-11eb-82a1-d5ba7a5cbdc7.png)

### Steps To Reproduce:

No idea.

### Expected result

If I can open the org using `sfdx force:org:open -u ALIAS` the org should also be shown in the `sfdx force:org:list --all --json` output

### Actual result

One org is missing in the output

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): does not matter

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core): org v1.5.0 

**OS and version**: windows 10

**Comment by AllanOricil** [comment]
Related https://github.com/forcedotcom/cli/issues/835

**Comment by mshanemc** [comment]
I can't reproduce it (auth'd to a THPG, and I see it in my `org:list`).  Does it happen to any other orgs, or another playground?

If you run `force:org:display` and/or open up the auth file itself (`~/.sfdx/[username].json`) does anything look different from that of another file for an org that does show up? 

does it show up in `alias:list` ?

**Comment by AllanOricil** [comment]
It does not happen to any other org or playground.

When I ran `force:org:display -u Playground2`

![image](https://user-images.githubusercontent.com/55927613/112061569-95b44600-8b56-11eb-9b25-6213db08f7db.png)

The Playground2 credentials are there.

![image](https://user-images.githubusercontent.com/55927613/112061710-cac09880-8b56-11eb-8ad6-680551e96c11.png)


Here is the output of `sfdx force:org:list --all --json`. You will see that even with a file inside `~/.sfdx` I don't have it listed

![image](https://user-images.githubusercontent.com/55927613/112062208-841f6e00-8b57-11eb-9b35-188a74f865a1.png)


And it shows up in the `sfdx alias:list` ouput

![image](https://user-images.githubusercontent.com/55927613/112062640-1758a380-8b58-11eb-9999-325a31ffb379.png)

**Comment by mshanemc** [comment]
Is there anything unusual about the auth file (in ~/.sfdx/) for that playground when you compare it to other orgs that do appear?

**Comment by AllanOricil** [comment]
@mshanemc  To make it easier to debug, I shared with you a private repository with the content of  `~/.sfdx`.

**Comment by jamesmelville** [comment]
@mshanemc might not be the same issue - but please see my ticket #940 where the org disappears from the list on adding `userId` and `password` to the auth file when setting a scratch org password, and restored to the list when they're removed.

**Comment by mshanemc** [comment]
I'm pretty sure it's the same issue and I know what it is.  I'm going to close this issue in favor of #940.  Please follow there.

**Comment by AllanOricil** [comment]
It is definitely not correlated, as I have not generated password for my Playground2. But whatever, you do what you think is right.

**Comment by jamesmelville** [comment]
@AllanOricil ignoring the point about setting a password - does the JSON file from your org (`~/.sfdx/username.json`) include the properties `userId` and `password`, and if so does removing them restore the org to the output of `force:org:list`?

**Comment by AllanOricil** [comment]
@jamesmelville let me try it!

**Comment by AllanOricil** [comment]
I removed both `userId` and `password` and then ran `sfdx force:org:list --all --json` and the org is still missing.

![image](https://user-images.githubusercontent.com/55927613/112196056-8985c280-8c02-11eb-9052-8acf99952f5f.png)

**Comment by jamesmelville** [comment]
So those properties were present and you removed them leaving valid JSON? Sorry - not sure I can help further with this - unless it was your list command being cached and just a case of waiting? Otherwise @mshanemc might be able to explain why he thought it was the same issue and otherwise re-open this?

**Comment by AllanOricil** [comment]
Yes, those two keys were present, and even after removing those nothing changed.
