### ISSUE TITLE
"sfdx force:source:deploy --sourcepath my/path/to/files" command is not working as expected.

### ISSUE THREAD

**Issue by JMercie** [forcedotcom/cli#934]
### Summary

When runing the command in the title of this issue, output an html with title of "internal server error" and local code is not deployed to the sandbox org.

Here is the HTML that outputs:

```html
<html>
<head><title>An internal server error has occurred</title></head>
<body>


<div style="display:none;" id="errorTitle">An internal server error has occurred</div>
<div style="display:none;" id="errorDesc">An error has occurred while processing your request. The salesforce.com support team has been notified of the problem. If you believe you have additional information that may be of help in reproducing or correcting the error, please contact <a href="https://help.salesforce.com/apex/hthome">Salesforce Support</a>. Please indicate the URL of the page you were requesting, any error id shown on this page as well as any other related information. We apologize for the inconvenience. <br/><br/>Thank you again for your patience and assistance. And thanks for using salesforce.com!</div>
<table cellspacing=10>
<tr><td><span style="font-weight: bold; font-size: 12pt;">An internal server error has occurred</span></td></tr>
<tr><td>
An error has occurred while processing your request. The salesforce.com support team has been notified of the problem. If you believe you have additional information that may be of help in reproducing or correcting the error, please contact <a href="https://help.salesforce.com/apex/hthome">Salesforce Support</a>. Please indicate the URL of the page you were requesting, any error id shown on this page as well as any other related information. We apologize for the inconvenience. <br/><br/>Thank you again for your patience and assistance. And thanks for using salesforce.com!
<br><br>
Error ID: 532018934-1114435 (1534884652)
</td>
</tr>
<tr><td>
<br clear="all"><br><br>


</td></tr>
</table>

</td></tr>
</table>



</body>
</html>
```

### Steps To Reproduce:

1.  This is step 1.  Open vscode.
1.  This is step 2.  Go to a file in your package directory you want to deploy to your authorized organization.
1.  This is step 3.  Right click on the file, then select the option "SFDX: Deploy this source to org."

### Expected result

sourpath files deploy succesfully to the authorized organization.

### Actual result

Throws an error containing the html descripted in the summary. 

### Additional information

I install the cli via npm. The error start ocurring when I update the sfdx cli from version 7.80.0 to 7.92.0.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):  sfdx-cli/7.92.0 linux-x64 node-v14.16.0

**OS and version**:  Ubuntu 20.04

**Comment by mshanemc** [comment]
can you set try to use the soap API instead by setting `SFDX_REST_DEPLOY=false` in the environment?

The change to use the newer REST metadata api has caused some bugs when it doesn't return valid json.

**Comment by JMercie** [comment]
> can you set try to use the soap API instead by setting `SFDX_REST_DEPLOY=false` in the environment?
> 
> The change to use the newer REST metadata api has caused some bugs when it doesn't return valid json.

This do the magic trick!  for using the command in vscode, also want  to add that using directly the command in the command line, will allow you to perform the deploy with REST api but the gui of vscode wont perform it with REST. Thanks a lot @mshanemc !

**Comment by pkozuchowski** [comment]
I'm observing similar issue:
```
$ sfdx force:mdapi:deploy -u uat -w -1 -d deploy/03_23_21/src --checkonly
*** Deploying with REST ***
ERROR running force:mdapi:deploy: 
<html>
<body>

<table cellspacing=10>
    <tr>
        <td><span style="font-weight: bold; font-size: 12pt;">Illegal Request</span></td>
    </tr>
    <tr>
        <td>You have sent us an Illegal URL or an improperly formatted request. 
        </td>
    </tr>
    <tr>
        <td>
            
        </td>
    </tr>
</table>



<!-- Body events -->
<script type="text/javascript">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken="null";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>

</body>
</html>


<!--
...................................................................................................
...................................................................................................
...................................................................................................
...................................................................................................
-->
```

edit:
It works with --soapdeploy parameter

**Comment by mshanemc** [comment]
Yes!  The `mdapi:deploy` command has a soap option, but `source:deploy` doesn't.  That's why you either need to force it to use REST via environment variable or config:set.

We're working with the metadata team to get this resolved without manual steps.

**Comment by jclark-dot-org** [comment]
@mshanemc This is still broken without the manual workaround, correct?  If so, could I suggest leaving this ticket open, perhaps flagging 'owned by another team' if the work is with the metadata team?  The default search in github is 'is:open'; some folks may miss the workaround if the ticket is closed.
