### ISSUE TITLE
Workflow rule or workflow rule alert does not work fine for SFDX CLI 7.83 version but works fine with 7.73 version.

### ISSUE THREAD

**Issue by chiranjeebee** [forcedotcom/cli#937]
### Summary

Workflow rule or workflow rule alert does not work fine for SFDX CLI 7.83 version but works fine with 7.73 version.

### Steps To Reproduce:

1.  Deploy any work flow rule to salesforce.
2. Package .xml file below.
![image](https://user-images.githubusercontent.com/66773678/112112391-78758b00-8bdb-11eb-82c7-3051887d3bdd.png)

### Expected result

![image](https://user-images.githubusercontent.com/66773678/112112438-8aefc480-8bdb-11eb-8d48-920950f20e98.png)

### Actual result

![image](https://user-images.githubusercontent.com/66773678/112112476-98a54a00-8bdb-11eb-8e65-7110696a76f8.png)

### Additional information

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.4 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 50.9.1 (core)
├─ schema 1.0.1 (core)
├─ limits 1.0.0 (core)
├─ templates 50.1.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ custom-metadata 1.0.10 (core)
├─ salesforce-alm 50.9.0 (core)
└─ apex 0.1.4 (core)
sfdx-cli 7.83.0 (core)

**Comment by mshanemc** [comment]
Those are some older versions.  Are you able to upgrade the CLI to latest, and reproduce the issue?

If so, there are some current deployment issues.  The workaround is described here: https://github.com/forcedotcom/cli/issues/942

If that doesn't solve the problem, can you please let us know so we can find the bug?

**Comment by chiranjeebee** [comment]
> Those are some older versions. Are you able to upgrade the CLI to latest, and reproduce the issue?
> 
> If so, there are some current deployment issues. The workaround is described here: #942
> 
> If that doesn't solve the problem, can you please let us know so we can find the bug?

Thanks for the reply. I have tried with higher versions like 7.81, 7.83 and the latest 7.92 version as well. Still same issue persists.

![image](https://user-images.githubusercontent.com/66773678/112269516-758f9e80-8c9e-11eb-8621-bba473a839a3.png)

I have tried setting restdeploy config as false as mentioned in #942. No luck.
As per my observation it only works with 7.73. I am looking for a fix in specific 7.83 CLI version.

**Comment by ar-srinivas** [comment]
I am facing the same issue even with "WorkflowRule" metadata type. Please let us know if there is an ETA for the fix or if any version(>7.83) supports this.

**Comment by ar-srinivas** [comment]
This issue still exist even on the latest version 7.98.0. Do we have any ETA for the fix or any alternate way to deploy the workflowrules using force:source:deploy. Tried with setting the restDeploy true and false and end up with the same issue.

![image](https://user-images.githubusercontent.com/30531295/115822952-0b942180-a423-11eb-8479-65f4dd95de7e.png)
![image](https://user-images.githubusercontent.com/30531295/115822991-1fd81e80-a423-11eb-9380-a712ca77ae76.png)
