### ISSUE TITLE
Cannot exclude List Views with .forceignore after CustomObject retrieval

### ISSUE THREAD

**Issue by jcarmignani** [forcedotcom/cli#938]
### Summary

_Short summary of what is going on or to provide context_.

I would like to exclude from metadata retrieve all the List Views that are fetched while using:
` sfdx force:source:retrieve -m "CustomObject:Account"`

### Steps To Reproduce:
Insert the following lines in the .forceignore file:
`# Exclude listViews
**listViews
**.listView-meta.xml
**.listView`

Then retrieve the Account object:
` sfdx force:source:retrieve -m "CustomObject:Account"`

Then check that the listViews folder is still there and the metadata for listViews as well:
![image](https://user-images.githubusercontent.com/11173517/112115268-494e2200-8bb9-11eb-8c21-8881e656ae8d.png)

### Expected result

listViews folders should be empty or all listViews folder should be removed from the SFDX Project
### Actual result

_Describe what actually happened instead_.
listViews folders are still there and nothing is changed despite adding some listViews patterns as part of the .forceignore file

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.81.0-7b953c80d1 win32-x64 node-v12.18.3

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.4.3 (1.4.3)
config 1.2.1 (core)
generator 1.1.3 (core)
odaseva-dx 0.0.0
salesforcedx 51.3.0 (latest-rc)
├─ salesforce-alm 51.3.0
├─ limits 1.0.4
├─ user 1.1.2
├─ schema 1.0.4
├─ custom-metadata 1.0.11
├─ apex 0.1.4
├─ templates 51.3.0
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7
sfdx-cli 7.81.0 (core)
**OS and version**:
![image](https://user-images.githubusercontent.com/11173517/112115673-beb9f280-8bb9-11eb-882d-71ddfa6731eb.png)

**Comment by mshanemc** [comment]
@jcarmignani that's a very old version the cli.  Can you verify it doesn't work with a newer version?

There's also an opt-in for using a newer version of the .forceignore 

finally, try these changes:
**listViews => `**/listViews`
**.listView-meta.xml => `**/listView-meta.xml`

ignore syntax in v2 follows git: https://git-scm.com/docs/gitignore

**Comment by jcarmignani** [comment]
@mshanemc I have updated my version of the CLI using following command:
`sfdx update`

Then I have modified my .forceignore file as you suggest:
![image](https://user-images.githubusercontent.com/11173517/114048049-7faec100-988a-11eb-9653-5f9ec7da0bfa.png)

Eventually I have retrieved Metadata using the following manifest:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    
    <types>
        <members>Account</members>
        <members>Contact</members>
        <members>User</members>
        <members>*</members>
        <name>CustomObject</name>
    </types>
    <version>51.0</version>
</Package>`

I am still facing the same issue with the List Views:
![image](https://user-images.githubusercontent.com/11173517/114048331-bf75a880-988a-11eb-947c-51c4c55db427.png)

Any suggestion?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9959024](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000BJyQMYA1/view)

**Comment by WillieRuemmele** [comment]
hi @jcarmignani ​ I was able to add a listview to the `.forceignore` and see it be ignored. It is different than how they mention it though.

by adding

`force-app/main/default/objects/*/listViews/*.*.*`

I was able to ignore all listviews from all objects

and by adding

`force-app/main/default/objects/Broker__c/listViews/*.*.*`

I was able to ignore just the custom object Broker__c's list views

**Comment by cristiand391** [comment]
This should be fixed  in latest sfdx v7.130.1 🎉 
Release notes: https://github.com/forcedotcom/cli/tree/main/releasenotes/sfdx#71301-dec-9-2021-stable

**Comment by jcarmignani** [comment]
Thanks for providing a permanent fix to this issue :)
