### ISSUE TITLE
Auth token in the files inside ~/.sfdx are "encrypted"

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#939]
### Summary

When we run `sfdx force:org:list --all --json` it now displays all auth tokens "decrypted" but if I open one of the files inside `~/.sfdx` the auth tokens are still "encrypted". Is it by design?

### Steps To Reproduce:

Open one of the org files inside `~/.sfdx`

### Expected result

Auth tokens should be the same as displayed when run `sfdx force:org:list --json`

### Actual result

Auth tokens are "encrypted"

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 7.92

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)

**OS and version**: W10

**Comment by mshanemc** [comment]
Yes, as designed.  They're all stored encrypted.
If someone needs a token for something, the you use the command to decrypt it.
