### ISSUE TITLE
Deployment Error: You have sent us an Illegal URL or an improperly formatted request

### ISSUE THREAD

**Issue by matthiasriedel1337** [forcedotcom/cli#941]
### Summary

I used to deploy code via 
`sfdx force:source:deploy --sourcepath c:\Users\matth\OneDrive\Dokumente\Code\SF2\force-app\main\default --json --loglevel fatal`
Last successfull deployment doing this was 10.03.2021, 13:44 (i cant tell which sfdx version i had at this time).
Now we recieve an error.

### Steps To Reproduce:

Dont know, Error is Org independant (Sandbox/Production). Error triggers in 100% of my attempts.

### Expected result

Successfull Deployment

### Actual result

`12:47:09.888 sfdx force:source:deploy --sourcepath c:\Users\matth\OneDrive\Dokumente\Code\SF2\force-app\main\default --json --loglevel fatal
 ended with exit code 1
{
  "status": 1,
  "name": "SfdxError",
  "message": "\n<html>\n<body>\n\n<table cellspacing=10>\n    <tr>\n        <td><span style=\"font-weight: bold; font-size: 12pt;\">Illegal Request</span></td>\n    </tr>\n    <tr>\n        <td>You have sent us an Illegal URL or an improperly formatted request. \n        </td>\n    </tr>\n    <tr>\n        <td>\n            \n        </td>\n    </tr>\n</table>\n\n\n\n\n<script type=\"text/javascript\">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken=\"null\";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>\n\t\t\t\n</body>\n</html>\n\n\n\n",
  "exitCode": 1,
  "commandName": "SourceDeployCommand",
  "stack": "SfdxError: \n<html>\n<body>\n\n<table cellspacing=10>\n    <tr>\n        <td><span style=\"font-weight: bold; font-size: 12pt;\">Illegal Request</span></td>\n    </tr>\n    <tr>\n        <td>You have 
sent us an Illegal URL or an improperly formatted request. \n        </td>\n    </tr>\n    <tr>\n        <td>\n            \n        </td>\n    </tr>\n</table>\n\n\n\n\n<script type=\"text/javascript\">function bodyOnLoad(){if(window.PreferenceBits){window.PreferenceBits.prototype.csrfToken=\"null\";};}function bodyOnBeforeUnload(){}function bodyOnFocus(){}function bodyOnUnload(){}</script>\n\t\t\t\n</body>\n</html>\n\n\n\n\n    at Function.wrap (C:\\Users\\matth\\AppData\\Local\\sfdx\\client\\7.92.0-88320113e7\\node_modules\\@salesforce\\core\\lib\\sfdxError.js:169:20)\n    at Request._callback (C:\\Users\\matth\\AppData\\Local\\sfdx\\client\\7.92.0-88320113e7\\node_modules\\salesforce-alm\\dist\\lib\\core\\force.js:587:41)\n    at Request.self.callback (C:\\Users\\matth\\AppData\\Local\\sfdx\\client\\7.92.0-88320113e7\\node_modules\\request\\request.js:185:22)\n    at Request.emit (events.js:315:20)\n    at Request.<anonymous> (C:\\Users\\matth\\AppData\\Local\\sfdx\\client\\7.92.0-88320113e7\\node_modules\\request\\request.js:1154:10)\n    at Request.emit (events.js:315:20)\n    at IncomingMessage.<anonymous> (C:\\Users\\matth\\AppData\\Local\\sfdx\\client\\7.92.0-88320113e7\\node_modules\\request\\request.js:1076:12)\n    at Object.onceWrapper (events.js:421:28)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",    
  "warnings": []
}`

### Additional information

I get this error when i deploy the whole Folder (\force-app\main\default) but not when i deploy individual sub folders (e.g. force-app\main\default\lwc). 

I tried to debug this problem and figured out a way to make it work:
When i attach a debugger and set a breakpoint somewhere after the authentification in force.js 
![grafik](https://user-images.githubusercontent.com/40121944/112143397-1a937400-8bd8-11eb-8824-1bd503cc7f32.png)
and then i continue the application, i dont get the described error response anymore. So i can deploy with
`sfdx force:source:deploy --sourcepath c:\Users\blub\Dokumente\Code\SF2\force-app\main\default --json --loglevel fatal`
simply by delaying the execution of the second POST.

`sfdx-cli/7.92.0-88320113e7 win32-x64 node-v14.15.4

@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-2 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.4.10 (core)
config 1.2.6 (core)
generator 1.1.5 (core)
salesforcedx 51.4.0 (core)
├─ limits 1.0.4 (core)
├─ schema 1.0.4 (core)
├─ apex 0.1.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ templates 51.3.0 (core)
├─ org 1.3.3 (core)
├─ user 1.2.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.4.0 (core)
sfdx-cli 7.92.0 (core)
telemetry 1.1.1 (core)

node version: v14.16.0`

**OS and version**: Win10

**Comment by mshanemc** [comment]
Can you try one of the workarounds from here?  https://github.com/forcedotcom/cli/issues/942 and let us know if that solves it?

**Comment by matthiasriedel1337** [comment]
Yes, switching back to SOAP solved the Issue. Thank you!

After reading some closed Issues i am sorry i opened an issue that has already been solved.
