### ISSUE TITLE
Deployment Problems

### ISSUE THREAD

**Issue by mshanemc** [forcedotcom/cli#942]
If you have a deployment (`source:deploy`, `mdapi:deploy`, `source:push`) that's behaving badly, you **may** be experiencing a bug related to a recent change in how the metadata API is used.

Starting in version 51.0, Salesforce CLI uses REST by default for deployments. Previously it used SOAP by default.  Unfortunately, there's some problems with the REST API version.

## How to change it back to use SOAP Metadata API:

1. if you are using `mdapi:deploy` there is a `--soapdeploy` flag you can add
2. run the following `sfdx config:set restDeploy=false --global` to change it everywhere, or without `--global` to change it at the project level
3. If you're having problems with a CI environment where you can't modify the scripts, you can set `SFDX_REST_DEPLOY=false` in the environment

more information on environment and configuration here: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_config_values.htm

**UPDATE:** The REST by default change has been rolled back in version 51.7 released on April 8th. You can find more information in this [Trailblazer Community post](https://trailblazers.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HTp1) and in the[ CLI Release notes for 51.7](https://github.com/forcedotcom/cli/tree/main/releasenotes#5171-april-8-2021---cli-7961).

**Comment by AllanOricil** [comment]
@mshanemc can I use this flag with `sfdx force:source:deploy` ? I think my issue https://github.com/forcedotcom/cli/issues/950 is related to using the REST api.

**Comment by AllanOricil** [comment]
yes, it works.
