### ISSUE TITLE
sfdx force:org:display generates Cannot read property 'Status' of undefined

### ISSUE THREAD

**Issue by prescod** [forcedotcom/cli#944]
### Summary

I am trying to look at the config of my scratch org. Instead I get a stack trace.

### Steps To Reproduce:

$ sfdx force:org:display --json -u test-qnwe8ybkev6j@example.com

### Expected result

Output of data about scratch org, or clear error message if the org was missing or corrupt.

### Actual result

{
  "status": 1,
  "name": "TypeError",
  "message": "Cannot read property 'Status' of undefined",
  "exitCode": 1,
  "commandName": "OrgDisplayCommand",
  "stack": "TypeError: Cannot read property 'Status' of undefined\n    at OrgDisplayCommand.getScratchOrgInformation (/Users/pprescod/.local/share/sfdx/node_modules/@salesforce/plugin-org/lib/commands/force/org/display.js:78:28)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async OrgDisplayCommand.run (/Users/pprescod/.local/share/sfdx/node_modules/@salesforce/plugin-org/lib/commands/force/org/display.js:32:47)\n    at async OrgDisplayCommand._run (/Users/pprescod/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:93:40)\n    at async Config.runCommand (/Users/pprescod/.local/share/sfdx/client/7.92.0-88320113e7/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/Users/pprescod/.local/share/sfdx/client/7.92.0-88320113e7/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/Users/pprescod/.local/share/sfdx/client/7.92.0-88320113e7/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/pprescod/.local/share/sfdx/client/7.92.0-88320113e7/dist/cli.js:121:21)\nOuter stack:\n    at Function.wrap (/Users/pprescod/.local/share/sfdx/node_modules/@salesforce/command/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at OrgDisplayCommand.catch (/Users/pprescod/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:259:67)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async OrgDisplayCommand._run (/Users/pprescod/.local/share/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:97:13)\n    at async Config.runCommand (/Users/pprescod/.local/share/sfdx/client/7.92.0-88320113e7/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/Users/pprescod/.local/share/sfdx/client/7.92.0-88320113e7/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/Users/pprescod/.local/share/sfdx/client/7.92.0-88320113e7/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/Users/pprescod/.local/share/sfdx/client/7.92.0-88320113e7/dist/cli.js:121:21)",
  "warnings": []
}
### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):

sfdx-cli/7.92.0-88320113e7 darwin-x64 node-v14.15.4

**OS and version**:

MacOS 10.14.6

**Comment by uip-robot-zz** [comment]
Error while creating work item!

**Comment by mshanemc** [comment]
Aside from the bad error messaging, that's a sign that the devhub is not finding information about your scratch org.

Can you confirm that, from the devhub, you can still access the scratch org info?

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9048829](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000913HYAQ/view)

**Comment by prescod** [comment]
Yes, I do see the org in the devhub. 

```
Scratch Org ID
00D1h000000HsGX

Username
test-qnwe8ybkev6j@example.com
```

By now it is probably marked as deleted because I didn't think to keep it alive for investigation.

**Comment by mshanemc** [comment]
It's OK if it's deleted...it would still be in the query.

That error is a result of the SOQL Query that asks the devhub about the org returning **nothing**.  Which I can't reproduce or explain.

If it happens on any other orgs, can you add the info here?

**Comment by prescod** [comment]
Could you perhaps split the ticket into "better error message if SOQL query returns unexpected result" versus the underlying cause in this case?

Would you like me to issue a SOQL query against my devhub?

**Comment by mshanemc** [comment]
We released a patch for this and another issue last night.  If you run `sfdx plugins:install org` you'll get that latest.

It **should** handle the error better, and also print out what hub and org the query is doing.

The query and fields are in here: https://github.com/salesforcecli/plugin-org/blob/6f0d1c4093056b09e2c9fdf5501f83cdd8e9fa1e/src/shared/orgListUtil.ts#L217

In soql that would be asking the hub org:
`select <those fields> from ScratchOrgInfo where ScratchOrg = '<your scratch org id>'`

**Comment by mshanemc** [comment]
@prescod can you try it with the new error output so I can see what it's returning?

**Comment by mshanemc** [comment]
released
