### ISSUE TITLE
Issue while sfdx:retrieve using Windows 7 - Getting Node.js is only supported on Windows 8.1 or higher. Setting the NODE_SKIP_PLATFORM_CHECK environment variable to 1 skips this check, but Node.js might not execute correctly.

### ISSUE THREAD

**Issue by vikyaiyer** [forcedotcom/cli#946]

**Comment by vikyaiyer** [comment]
Sharing the link of [similar issue on Nodejs forum](https://github.com/nodejs/node/pull/33108)

**Comment by mshanemc** [comment]
Salesforce CLI is based on node, which dropped support for Windows 7 when Microsoft stopped supporting it.

https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

You can try the NODE_SKIP_PLATFORM_CHECK.
