### ISSUE TITLE
Retrieve standard object metadata and standard object field metadata by itself so that profiles and permission sets will retrieve properly based on only what is in the package.xml

### ISSUE THREAD

**Issue by Thrantor** [forcedotcom/cli#947]
**Is your feature request related to a problem? Please describe.**
In order to have permission sets and profiles retrieved with object level permissions and data, the object(ex Account) must be in the CustomObject section of the package.xml. However, this also retrieves ALL of the fields, listviews, recordTypes etc for that object. 

This causes trouble when you have two different developers who are working on the same object. When one developer(dev1) adds new fields and the other(dev2) retrieves the object the profiles and permission sets now reference those newly created fields. So, when dev2 tries to deploy or validate the feature branch they are working on... they are missing fields that they know nothing about. And in order for their deployment to work, they have to ADD those new fields to their branch otherwise it won't deploy.

This is a massive pain in the butt. A developer should be able to retrieve the object metadata and then the specific stuff they care about. This way the profile for each dev references only the stuff they are working on. And during merge the files will contain both sets of information.

**What are you trying to do**
Trying to be able to pull profiles and permission sets without pulling fields that may not be ready for deployment. How would I, as dev2, know that they fields created by dev1 are ready to go into the repo or not?

**Describe the solution you'd like**
Separate out the object metadata from the fields, listviews, recordtypes et al. Right now, for custom objects you already have to specify each new field(baring standard fields... name etc). Allow us to add these standard and custom fields individually to our package.xml. That way we can granularly control what the profiles and permission sets will contain.

**Describe alternatives you've considered**
Have an option(command line parameter) that only retrieves profile or permission sets with the custom field specific information in the package.xml. That way the profiles don't contain data the dev isn't expecting.

**Additional context**
I think that is pretty clear. Contact me if needed.

**Comment by mkreth** [comment]
Hi @Thrantor, I'm not Salesforce, just asking to clarify some points: you say dev1 has created new fields and dev2 sees the field permissions for those new fields when pulling profiles/permission sets? Does that mean that dev1 and dev2 are working in the same Salesforce dev environment, e.g. developer sandbox?
From experience, this way of working has always increased the risk of changes having overlaps and the risk of commits on separate feature branches having dependencies that are not obvious until later in the devops process. These kinds of risks can be reduced if developers work in isolated environments - like in individual developer sandboxes or scratch orgs.  This will - on one hand - lead to much better isolation between work from individual developers. On the other hand with individual sandboxes there is an additional need to keep developer sandboxes in sync. And with scratch orgs we need a technical integration environment.
The other way of - with existing tool support - reducing potential overlaps between commits on different feature branches is to control on line level what is going into a commit - e.g. for these large metadata files like profiles and permission sets, to individually control whether to include a changed line into a commit or not.
This pushes the responsibility to the developers and is a bit of a learning curve.

Ultimately, if Salesforce could break down the large monolithic profiles and permission sets metadata files into components this could improve.

**Comment by WillieRuemmele** [comment]
Hi - we've looked into what to do with profiles, long story short, there's not much we can do without major breaking changes https://github.com/forcedotcom/cli/discussions/1785#discussioncomment-4722761
