### ISSUE TITLE
force:org:create doesn't use namespace from sfdx-project.json (or perhaps that entire file) sometimes (metadata format vs. source format?)

### ISSUE THREAD

**Issue by SCWells72** [forcedotcom/cli#948]
I've been working through some IC2 issues with the [NPSP project](https://github.com/SalesforceFoundation/NPSP) lately, many due to the fact that it's a strange hybrid of SFDX and traditional. It has an `sfdx-project.json` file and numerous scratch org definition files under its `orgs` directory, but the actual files are (mostly) in metadata format instead of source format. I say "mostly" because the documents seem to follow the source format conventions rather than metadata format conventions. Otherwise all XML metadata filenames use their metadata type-specific file extensions instead of that plus `-meta.xml`, and there's no metadata decomposition.

So that's the setup. The actual issue I'm reporting here is that if I specify a namespace in the `sfdx-project.json` file that is properly associated with the dev hub against which I'm creating a scratch org, then run `sfdx force:org:create` from the NPSP project directory, the scratch org is **not** created with that (or any) namespace. In fact, if I specify an invalid namespace in `sfdx-project.json` there are no errors, so it seems it's either not consulting that file or it's deciding not to use the namespace from that file for some reason.

On the other hand, if I create a dummy SFDX project using `sfdx force:project:create` such that its `sfdx-project.json` file contains the same namespace and create the scratch org from that project directory, the scratch org is created with the specified namespace.

How does the `sfdx force:org:create` command decide whether/how to use the information in `sfdx-project.json`? Does it also look at the contents of the specified package directories? This disparity in behavior is confusing and seemingly incorrect when the org is created without a namespace.

**Comment by mshanemc** [comment]
For clarity, 
1. clone NPSP
2. change the namespace in the top-level `sfdx-project.json` to something your hub owns
3. `sfdx force:org:create` (with a config file? which one? doesn't matter?)

**Comment by SCWells72** [comment]
@mshanemc hah! Yes, that's the concise version. Try to use `dev.json` if you want...though, that raises another question/problem that we can split off into its own case, but I'll seed the discussion here. Sometimes org creation fails with "failed to deploy settings", and the scratch org is technically created, albeit without the alias and in some indeterminate state as to which (if any) of the settings were applied to the org. There are also zero details about which settings couldn't be applied, so the only recourse is to start with one and build up from there until you isolate which one/s cause the issue. I bring that up because if memory serves, `dev.json` caused that error for me yesterday, though I've used it in the past to create an org successfully.

**Comment by davidmreed** [comment]
Background on the unusual project layout for the Nonprofit Success Pack:

NPSP is built using [CumulusCI](https://cumulusci.readthedocs.io/), Salesforce.org's orchestration layer on top of Salesforce DX. The NPSP project _is_ in Metadata API format. However, it also comes with all of the infrastructure to define and build scratch orgs, because CumulusCI supports building scratch orgs for products in both Metadata API and Salesforce DX source formats.

CumulusCI is the recommended route to build a scratch org for NPSP. Salesforce DX itself will not work without walking through a lot of manual steps, as NPSP includes six managed packages and unmanaged setup that must be deployed prior to pushing source into the org.

**Comment by SCWells72** [comment]
Thanks for the useful context, @davidmreed. I've actually worked over the past few weeks to make IC2 work much better with NPSP as-is...or at least as close to as-is as makes sense given that much of its behavior is delivered as external config/scripts.

The issue I'm hitting now seems to be a recent behavioral change. One month ago I ran the following from the NPSP root project directory with the namespace in `sfdx-project.json` set to one that's in my dev hub's namespace registries:

```
sfdx force:org:create -v devHubUsername -a alias -d 30 -f orgs/dev.json
```

At the time that worked just fine, and I ended up with a scratch org with the specified namespace and configured according to `dev.json`.

Of course, that scratch org has now expired, so I tried to recreate it yesterday the exact same way, but there were issues. First, it failed with "failed to deploy settings" which didn't happen previously, and of course when I tried to create it using no settings, the scratch org was created but without the specified namespace. And again, it doesn't even seem to be looking at that namespace because I can put any invalid value for the namespace value and it happily creates the scratch org with no namespace. Move to any other valid SFDX project and do the same thing, and you end up with a new scratch org with the specified namespace.

I'm trying a few things on the side right now with @mshanemc to see if we can isolate what might have changed. The new REST API deployment changes are certainly a candidate, so I'm going to disable them and see if they're behind all of this. I'll report my findings here shortly.

**Comment by SCWells72** [comment]
Okay, I've figured out what's going on here.

First, changing the CLI to use the SOAP API instead of the REST API for deployment fixed the "failed to deploy settings" issue. It sounds like the REST change is going to be reverted shortly, but in the interim you can find a solution for that in #942.

Second, because of the hybrid SFDX/traditional nature of the NPSP project, IC2 is using the [`plugins` capability of `sfdx-project.json`](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm) to hint to the IDE that even though it looks like an SFDX/source format project, the files are stored in metadata format, e.g.:

```json
{
  "packageDirectories": [
    {
      "path": "src",
      "default": true
    }
  ],
  "namespace": "myNamespace",
  "sourceApiVersion": "48.0",
  "plugins": {
    "illuminatedCloud2": {
      "format": "metadata"
    }
  }
}
```

My understanding was that the `plugins` portion is pretty much ignored by the main CLI commands when processing that file, but it was passed to installed plugins for their own config. IC2 isn't a CLI plugin, but this is a convenient way to express the nature of the project in a centralized, declarative manner.

But...when that clause is present, the contents of that file are silently ignored during org creation. By removing the `plugins` property, the specified namespace is used. When that property is present, the org is created with no namespace.

So...is that a CLI bug? In other words, if another plugin was installed and there was a `plugins` property present in `sfdx-project.json`, would that cause the `force:org:create` command to silently ignore the contents of that file? Before I change how IC2 decides whether a project with an `sfdx-project.json` file is stored in metadata format, I'd like to know whether this is something that should be fixed in the CLI such that the current approach will just work properly.

**Comment by SCWells72** [comment]
Okay, I've figured out the part where the namespace wasn't being set. Because of the hybrid nature of the NPSP project, IC2 wasn't setting the working directory for the CLI when it executes, instead causing that process' working directory to be the `sfdx` script's parent directory. When IC2 properly sets the working directory to be the parent directory of `sfdx-project.json` when executed for the NPSP project, the namespace is set properly even when the `plugins` property is present in `sfdx-project.json`.

It's still strange that the namespace is set properly when a scratch org is created from a non-project working directory if `plugins` is not present but isn't set when `plugins` is present in that same scenario, but since that's a weird use case, I'd say go ahead and resolve this case since the other problem with settings deployment via the REST API is being handled elsewhere.

Thanks!
