### ISSUE TITLE
sfdx update issue

### ISSUE THREAD

**Issue by rajendrasnagar** [forcedotcom/cli#95]
### Summary
Unable to  update using sfdx command + create new lwc

### Steps To Reproduce:

1.  Run 'SFDX update' or 'sfdx force:lightning:component:create —type lwc -n helloWorld -d force-app/main/default/lwc' 
2. You will face issue as attached.

### Expected result
1. SFDX should be updated or component should be created.

### Actual result
1. Error as attached.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**: 1.34.0

**SFDX CLI Version**: Not able to check, as it is giving error for all commands.

**OS and version**: Windows 7

**Comment by clairebianchi** [comment]
@raJSN  we have had issues with the updater between V6 and V7 major versions of the CLI. It is best for you to uninstall the CLI, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm
and the reinstall
Be warned you will have to reinstall any plugins you have, to get a list of your plugins run `sfdx plugins`
