### ISSUE TITLE
source:deploy result error "Illegal Request" for a parent folder but works subFolder by subFolder

### ISSUE THREAD

**Issue by fredtoutsimplement** [forcedotcom/cli#952]
### Summary
source:deploy result error "Illegal Request" for a parent folder but works subFolder by subFolder

### Steps To Reproduce:

**Repository to reproduce:** Private Repo so I cannot share it here

Example 1 resulting an error : 
sfdx force:source:deploy --sourcepath "src/B2B_Core/views"
RESULT ERROR Illegal Request

Example 2 resulting also an error 
sfdx force:source:deploy --sourcepath "src/B2B_Core/views/applications/,src/B2B_Core/views/aura/,src/B2B_Core/views/layouts/,src/B2B_Core/views/lwc/"

Example 3 resulting a SUCCESS
When deploying views subfolders one by one by subfolder it works
"views" is the parent folder of following subfolder
- src\B2B_Core\views\applications
- src\B2B_Core\views\aura
- src\B2B_Core\views\layouts
- src\B2B_Core\views\lwc
So if I execute folder one by one like
sfdx force:source:deploy --sourcepath "src/B2B_Core/views/applications/"
RESULT OK
sfdx force:source:deploy --sourcepath "src/B2B_Core/views/aura/"
RESULT OK
sfdx force:source:deploy --sourcepath "src/B2B_Core/views/layouts/"
RESULT OK
sfdx force:source:deploy --sourcepath "src/B2B_Core/views/lwc/"
RESULT OK

Example 4 resulting a success
B2B_Online_Feature/views has the same folder structure but of course with distinct metada in it
sfdx force:source:deploy --sourcepath "src/B2B_Online_Features/views/"
RESULT OK 

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): 
workstation 1 : sfdx-cli/7.81.0-7b953c80d1 win32-x64 node-v12.18.3
but same error with also the version below
workstation 2 : sfdx-cli/7.93.1-762bca056d win32-x64 node-v14.15.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
workstation 1 $ sfdx plugins --core
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.3 (core)
analytics 1.12.1 (core)
auth 1.5.1
config 1.2.1 (core)
generator 1.1.3 (core)
salesforcedx 51.6.0 (latest-rc)
├─ limits 1.0.4
├─ data 0.4.3
├─ schema 1.0.4
├─ apex 0.1.4
├─ custom-metadata 1.0.11
├─ templates 51.3.0
├─ org 1.6.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
├─ user 1.2.1
└─ salesforce-alm 51.6.6
sfdmu 4.0.0
sfdx-cli 7.81.0 (core)
sfdx-flowdoc-plugin 0.5.1

but the error also occurs with following plugins info
workstation 2 sfdx plugins --core
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.5.1 (core)
config 1.2.7 (core)
generator 1.1.5 (core)
salesforcedx 51.5.0 (core)
├─ schema 1.0.4 (core)
├─ limits 1.0.4 (core)
├─ custom-metadata 1.0.11 (core)
├─ apex 0.1.4 (core)
├─ templates 51.3.0 (core)
├─ org 1.5.0 (core)
├─ user 1.2.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
└─ salesforce-alm 51.6.3 (core)
sfdx-cli 7.93.1 (core)
telemetry 1.1.1 (core)

**OS and version**:
Workstation 1 sys
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042

Workstation 2 
OS Name:               Microsoft Windows 10 Famille
OS Version:             10.0.19042 N/A build 19042

**Comment by mshanemc** [comment]
Have read and tried the steps from this pinned issue (preferably on the machine with the more recent CLI version)? 
https://github.com/forcedotcom/cli/issues/942

If that doesn't work: is there a simplified version of the repo you could provide?  For example, 
- do all 4 folders have to be present, or would 2 suffice to reproduce?
- does the metadata in the folder have to be something specific, or would a hello-world Aura bundle work?
