### ISSUE TITLE
Add refresh token in the sfdx force:org:list response

### ISSUE THREAD

**Issue by AllanOricil** [forcedotcom/cli#956]
**Is your feature request related to a problem? Please describe.**

When the auth token is expired I have to rerun sfdx force:org;display or force:org:list just to grab another token and it takes quite a while for sfdx to execute the command. If I had the refresh token I could do it myself instead of interfacing with the cli.

**What are you trying to do**
Get a new token as fast as possible without using sfdx

**Describe the solution you'd like**
Expose the refresh token in the sfdx force:org:list and sfdx  force:org:display

**Comment by uip-robot-zz** [comment]
Error while creating work item. No valid build found in GUS!

**Comment by AllanOricil** [comment]
Hi @peternhale  is it going to be implemented? If this part is in the auth plugin I can help to implement it.

**Comment by peternhale** [comment]
@AllanOricil, a decision has yet to be made if this enhancement will move forward.

**Comment by AllanOricil** [comment]
No worries. Thanks

**Comment by AllanOricil** [comment]
I thought about this one again and does not seem a good idea. It will open too many doors for a hacker to get access to a production org that is connected to an sfdx. Each developer would become a threat for its company if not working through a secure connection. Even with a VPN somebody could still get access to his computer and do something with it. 

But it is good if we could opt in to get the refresh token in the output, knowing that there is this trade off
