### ISSUE TITLE
Error: ENOENT: no such file or directory, open '..\maxRevision.json'not found error while hitting sdfx push command

### ISSUE THREAD

**Issue by ashuawasthi98** [forcedotcom/cli#959]
Summary
This morning I tried to push on a scratch (Was working fine yesterday, scratch has more than 20 day of lifetime).
and I got this error:
image

The thing is that I don't even have an 'org' folder.
Also I don't know what is maxRevision.json

The command used is:
sfdx force:source:push

Steps To Reproduce:
Wake up in the morning and open VScode
try to sfdx force:source:push
Expected result
push is done

Actual result
Error

Additional information
tryied to update sdfx, create a mock maxRevision.json in the path. Both not worked

VS Code Version: 1.51.1

SFDX CLI Version: sfdx-cli/7.94.3-a4e7c7955b win32-x64 node-v14.15.4

OS and version: Win10

**Comment by peternhale** [comment]
@ashuawasthi98 When did you last run `sfdx update`?

**Comment by ashuawasthi98** [comment]
Hi Peterhale, I ran sfdx update today and I am on the latest cli version.

**Comment by peternhale** [comment]
@ashuawasthi98 Can you run the push again adding flags `--dev-debug --json` and post the results?

**Comment by shetzel** [comment]
maxrevision.json contains remote (in org) source tracking data.  This is specific to the org being pushed to and pulled from.  If the org directory was deleted (that contains both local and remote source tracking data) then source tracking commands lost the context they need to operate properly.  One way that can happen is if you use the source:deploy or source:retrieve commands (which don't work with source tracking) with that same scratch org.  Using those commands in conjunction with push/pull breaks source tracking and you'll need to reset your source tracking state.  One way to do that is to run `force:source:status` and then use the `force:source:tracking:*` commands to get your source tracking state back to what it should be.

**Comment by peternhale** [comment]
@ashuawasthi98 Given Steve's response, have you been able to recover your source tracking state?
