### ISSUE TITLE
unable to connect vs code to developer org

### ISSUE THREAD

**Issue by simranrsaluja** [forcedotcom/cli#96]
whenever i try to authorize an org, getting this error 

Starting SFDX: Authorize an Org

16:12:59.385 sfdx force:auth:web:login --setalias mydev --instanceurl https://login.salesforce.com --setdefaultusername
{ Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs:
   [ '/c',
     'start',
     '""',
     '/b',
     'https://login.salesforce.com//services/oauth2/authorize?response_type=code^&client_id=PlatformCLI^&redirect_uri=http%3A%2F%2Flocalhost%3A1717%2FOauthRedirect^&state=a272a08d10d7^&prompt=login^&scope=refresh_token%20api%20web^&code_challenge=_dUH3iXOA4dcIQjotmy5ZfHwB5FM-1_QdZbyewjd_JI' ] }

**Comment by clairebianchi** [comment]
@simranrsaluja There might be an issue with your version of the CLI can you uninstall, using these directions: https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm 
and then reinstall and see if you are still encountering the issue?
