### ISSUE TITLE
We can’t retrieve the specified metadata object: PicklistValue

### ISSUE THREAD

**Issue by t3fl0n** [forcedotcom/cli#960]
### Summary

I had a deactivated picklist value in my global value set.  When I reactivated it, I got the following error:

`We can’t retrieve the specified metadata object: PicklistValue. Certain metadata types, like |11|1|1|^|11|1|2|^|11|1|3|^|11|1|4|^|11|1|5|^|11|1|6|^|11|1|7|^|11|1|8|^|11|1|9|^|11|1|10|^|11|1|11|^|11|2|1|^ are not currently supported by the CLI.
`
### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Create a Picklist Value Set with more than one value
2. `sfdx force:source:pull`
3. Deactivate one of the values
4. `sfdx force:source:pull`
5. reactivate the deactivated picklist value
6. `sfdx force:source:pull`

### Expected result

The global value set metadata file should pull down without issue

### Actual result

I got this error for my final `sfdx force:source:pull`

`11:38:40.370 sfdx force:source:pull
We can’t retrieve the specified metadata object: PicklistValue. Certain metadata types, like |11|1|1|^|11|1|2|^|11|1|3|^|11|1|4|^|11|1|5|^|11|1|6|^|11|1|7|^|11|1|8|^|11|1|9|^|11|1|10|^|11|1|11|^|11|2|1|^ are not currently supported by the CLI.
File a bug here: https://github.com/forcedotcom/cli/issues and provide the name of the unsupported metadata type
=== Pulled Source
STATE    FULL NAME                     TYPE            PROJECT PATH
───────  ────────────────────────────  ──────────────  ─────────────────────────────────────────────────────────────────────────────────
Changed  V3_Industry                   GlobalValueSet  force-app/main/default/globalValueSets/V3_Industry.globalValueSet-meta.xml`

The globalValueSet did pull down and had the correct info.  I don't have any PicklistValue objects in my project, so maybe it's some new metadata?

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.94.3-a4e7c7955b darwin-x64 node-v14.15.4

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.8 (core)
auth 1.5.1 (core)
config 1.2.7 (core)
generator 1.1.5 (core)
salesforcedx 51.6.0
├─ limits 1.0.4
├─ data 0.4.3
├─ schema 1.0.4
├─ apex 0.1.4
├─ custom-metadata 1.0.11
├─ templates 51.3.0
├─ org 1.6.0
├─ salesforce-alm 51.6.6
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
└─ user 1.2.1
sfdx-cli 7.94.3 (core)
telemetry 1.1.1 (core)

**OS and version**:
MacOS Catalina 10.15.7 (19H524)

**Comment by uip-robot-zz** [comment]
Error while creating work item!

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9125229](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000AdnHYAS/view)

**Comment by acrosman** [comment]
While a fix is in the works, does anyone have a functional work around?

**Comment by t3fl0n** [comment]
@acrosman , as near as I can tell, this is not a blocking issue.  The error pops up, but it's not a real metadata that your code base needs.  I ignored it and kept working on my project.

**Comment by mshanemc** [comment]
I followed the reproduction, and the source is always correct.  The error message seems to occur when it should not and should be ignored.

I'm going to leave this open until we get rid of the message.

**Comment by mshanemc** [comment]
I think this is fixed by https://github.com/forcedotcom/source-tracking/pull/363.  If you're able to repro on current CLI and plugins, please open a new issue with the repro details
