### ISSUE TITLE
Undocumented change of behavior for sfdx force:apex:test:run --synchronous 

### ISSUE THREAD

**Issue by bytefreak** [forcedotcom/cli#963]
### Summary

Using  sfdx force:apex:test:run --synchronous throws since release 51.7.1 (April 8, 2021) - CLI 7.96.1 an error:

ERROR running force:apex:test:run:  Specify a test class or test methods when running tests synchronously

Before the release, all unit tests are executed of target org.

This change is frustrating as it is used in our CI/CD implementation to regularly check for failing unit tests on all orgs.

### Steps To Reproduce:

Use sfdx force:apex:test:run --synchronous on version 51.7.1 and before.

### Expected result

also synchronously should execute all unittests.

### Actual result

an error is thrown.

**Comment by mbirky** [comment]
@bytefreak, I am also experiencing this issue. Did you close this issue because you found a workaround?

**Comment by froucher** [comment]
Same issue for me

**Comment by CsfGitHub** [comment]
I confirm I have the same issue, no WA found

**Comment by bytefreak** [comment]
Update: you can simply remove the --synchronous flag. If you use e.g. -r junit it will be executed synchronously (at least on CLI). biggest downside: if you start the same run again but the first one is not finished, you will get an error that the tests are already running. But at least for our nightly automated test execution, it works.

**Comment by froucher** [comment]
I have open a new issue: #975

**Comment by froucher** [comment]
Thanks @bytefreak about the workaround info.

**Comment by mbirky** [comment]
@bytefreak, thank you for providing the workaround you found.
