### ISSUE TITLE
Strange behaviour regarding enableTranslationWorkbench setted to true

### ISSUE THREAD

**Issue by eyhuellou** [forcedotcom/cli#976]
### Summary

The **enableTranslationWorkbench** default setting setted to true worked fine until recently.
We have now a strange random behaviour when **enableTranslationWorkbench** setted to true. It happens sometimes that the created scratch org has **enableTranslationWorkbench** is still off.

### Steps To Reproduce:

Hard to reproduce. Don't know if this is relevant but one of our scratch was ok on CS128 but not ok for the developer who created a scratch org placed on CS100.

### Expected result

enableTranslationWorkbench always activated when enableTranslationWorkbench setting setted to true.

### Actual result

random behaviour

### Additional information

cli version : sfdx-cli/7.96.0 darwin-x64 node-v15.14.0

Our scratch def : 

{
  "orgName": "SecretCompName",
  "edition": "Enterprise",
  "features": [
    "FinanceLogging",
    "ContactsToMultipleAccounts",
    "CPQ"
  ],
  "settings": {
    "entitlementSettings": {
      "enableEntitlements": false
    },
    "enhancedNotesSettings": {
      "enableEnhancedNotes": true
    },
    "languageSettings": {
      "enableTranslationWorkbench":  true,
      "enableEndUserLanguages": true
    },
    "chatterSettings": {
      "enableChatter": true
    }
  },
  "language": "fr"
}

**Comment by WillieRuemmele** [comment]
Hi @eyhuellou have you tried running the command with the environment variable `SFDX_REST_DEPLOY` set to `false`? This behavior is default in the `latest-rc` release of the CLI, but not `latest` yet. See https://github.com/forcedotcom/cli/issues/942 for more information

That would be my one suggestion, but if it's hard to reproduce it'll be harder to nail down the real issue. Let me know how that goes, and if you see anything else behaving weirdly.
