### ISSUE TITLE
Include command to retrieve Record Counts in CLI limits plugin

### ISSUE THREAD

**Issue by mkreth** [forcedotcom/cli#978]
**Is your feature request related to a problem? Please describe.**
In monitoring of our Salesforce implementation we track trends in e.g. Data Storage consumption using the CLI limits plugin to extract this information and then import it into a tool which allows to plot trends over time. We are also interested in following the trends in number of records for select objects, e.g. the ones that consume the most data storage to allow us to identify needs to act on unexpected data growth.

**What are you trying to do**
Include the record counts (as returned by https://developer.salesforce.com/docs/atlas.en-us.230.0.api_rest.meta/api_rest/resources_record_count.htm) in the monitoring of our Salesforce implementation.

**Describe the solution you'd like**
Include this as a command in the CLI limits plugin with an argument that takes the list of object names.

**Describe alternatives you've considered**
We could call the available REST endpoint (see https://developer.salesforce.com/docs/atlas.en-us.230.0.api_rest.meta/api_rest/resources_record_count.htm) with e.g. curl as well but would have to provide the access token for authorization. This is much less elegant and potentially insecure as we'd have to extract the access token and pass it to the curl command.

**Additional context**
I'd do this as a community contribution if this would be considered a welcome addition.

**Comment by uip-robot-zz** [comment]
Error while creating work item!

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9160085](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000BJQ3YAO/view)

**Comment by WillieRuemmele** [comment]
https://github.com/salesforcecli/plugin-limits/pull/91
