### ISSUE TITLE
lightning:lint --json does not print correct JSON to stdout

### ISSUE THREAD

**Issue by dangmai** [forcedotcom/cli#98]
### Summary

When I use the command `sfdx force:lightning:lint` with the flag `--json`, the result is not correct JSON.

### Steps To Reproduce:

1.  Run the following command:
```bash
sfdx force:lightning:lint "/path/to/aura/dir" --files filename.js --json
```
1.  Here is a sample response that got printed to `stdout`:
```json
[
    {
        "file": "/path/to/aura/dir/filename.js",
        "result": [
            {
                "ruleId": "no-console",
                "severity": 2,
                "message": "Unexpected console statement.",
                "line": 73,
                "column": 14,
                "nodeType": "MemberExpression",
                "source": "             console.log('');"
            }
        ]
    }
]
{
  "status": 0
}
```
This contains two separate JSON responses, but when put together it is not a correct singular JSON response.

### Expected result

I'd expect only the JSON object to be sent to `stdout`, the `status` JSON part should be sent to `stderr`.

### Actual result

Both got sent to `stdout`, so it can't be parsed by a JSON parser.

### Additional information

_Feel free to attach a screenshot_.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.8.1-8f830784cc

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core) salesforcedx 45.16.0 

**OS and version**: Windows 10/8 and Arch Linux

**Comment by clairebianchi** [comment]
Thank you for letting us know. I am informing the team that owns this product.

**Comment by mshanemc** [comment]
This command doesn't exist anymore, so I'm closing the gh issue.
