### ISSUE TITLE
Allow for plugins to be installed with modern npm practices, not bespoke sfdx commands

### ISSUE THREAD

**Issue by AndrewRayCode** [forcedotcom/cli#983]
**Is your feature request related to a problem? Please describe.**
`sfdx` doesn't allow me to install and use a plugin with `npm`. It requires a manual `sfdx plugins:install` step for both users and build tools, which itself doesn't allow for sfdx plugins to be version controlled in `package.json`. The irony is that the plugins all seem to be available on npm.

**What are you trying to do**
Use modern node development practices.

**Describe the solution you'd like**
First class support in `sfdx` to use `npm`, `package.json`, without manual out-of-band steps.

**Describe alternatives you've considered**
**Additional context**
See [this stackoverflow question](https://salesforce.stackexchange.com/q/340976/68098) for workarounds.

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9167431](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000BSGbYAO/view)

**Comment by amphro** [comment]
If your repo is a plugin/cli itself, you can add "dev-plugins" then run `./bin/run <command>`. If you have ever built an oclif plugin, this will look familiar. See this plugin as an [example of adding a dev plugin](https://github.com/salesforcecli/plugin-limits/blob/main/package.json#L74) then [running the command](https://github.com/salesforcecli/plugin-limits/blob/main/package.json#L108) and having everything checked in to source control including [version](https://github.com/salesforcecli/plugin-limits/blob/main/package.json#L19). The same process would work for what you are trying to do.

Outside of that, I'm not sure what your ideal solution would look like. Can you explain more?

Automatically looking for `sfdx <command>` from a plugin is installed from a local package.json is a little weird to me. Generally, the CLI only registers plugins you tell it to with a `plugin:install`. You can technically tell it to know about plugins in a local project by `sfdx plugins:link ./node_modules/<plugin>`. I guess we could have an `sfdx.plugin` section in a local package.json to load plugins from, which also means that those commands are only available in that path.

**Comment by AndrewRayCode** [comment]
Does oclif have some kind of declarative file for saying "here's my plugins" to avoid manual work?

edit: oh wait, maybe this is what you're linking me to, let me try it out
