### ISSUE TITLE
SFDX: Retrieve Source in manifest from Org changing string values into numbers

### ISSUE THREAD

**Issue by damonshaw** [forcedotcom/cli#985]
### Summary

Retrieving from our Prod environment after a release we've noticed thousands of changes, most of them are formatting changes to the XML, replacing `<node/>` with `<node><node/>` etc, while a massive pain to review them all we also noticed that in some cases, string values seem to be being converted into numbers?

like this field filter specifying a specific Profile
![image](https://user-images.githubusercontent.com/13861905/115611712-8afbf500-a33e-11eb-96ef-88cb412312fb.png)

or this picklist value API name
![image](https://user-images.githubusercontent.com/13861905/115611977-de6e4300-a33e-11eb-8a04-f75fc1ea48cd.png)

### Steps To Reproduce:

1.  add a value '0002' to a picklist
1.  retrieve the field from your org

### Expected result

The label and API name should both be '0002'

### Actual result

The label and API name are both '2'

### Additional information
![image](https://user-images.githubusercontent.com/13861905/115613614-b8e23900-a340-11eb-99e7-df9547be50bd.png)

![image](https://user-images.githubusercontent.com/13861905/115613644-c4cdfb00-a340-11eb-95ba-fc761f9fc799.png)

**SFDX CLI Version** sfdx-cli/7.96.0 darwin-x64 node-v15.14.0

**SFDX plugin Version** 51.7.1

**OS and version**: macOS Big Sur 11.2.3

**Comment by damonshaw** [comment]
Somehow the "Experimental: Deploy Retrieve" setting in my VS Code found itself turned on? not sure how that happened but after turning it off things are back to normal
![image](https://user-images.githubusercontent.com/13861905/115619085-943d8f80-a347-11eb-8fe7-faaf8aaa0345.png)

**Comment by WillieRuemmele** [comment]
@damonshaw thanks for bringing this to our attention. cc @brpowell
