### ISSUE TITLE
CLI will not update to 7.97.1 but warns that an update is available

### ISSUE THREAD

**Issue by dcinzona** [forcedotcom/cli#987]
### Summary

When running the cli `sfdx` I get a warning saying sfdx-cli update available from 7.97.0 to 7.97.1, but when I execute `sfdx update` I get a message stating I'm already on the latest version.
```
$ sfdx upgrade
 ›   Warning: sfdx-cli update available from 7.97.0 to 7.97.1.
 ›   Warning: upgrade is not a sfdx command.
Did you mean update? [y/n]: y
sfdx-cli: Updating CLI... already on latest version: 7.97.0-c130e7a
sfdx-cli: Updating plugins... done
```

### Steps To Reproduce:

**Repository to reproduce:** [dreamhouse-lwc](https://github.com/dreamhouseapp/dreamhouse-lwc)

***NOTE:** If your issue is not reproducable by dreamhouse-lwc, i.e. requires specific metadata or files, we **require** a link to a simple Salesforce project repository with a script to setup a scratch org that reproduces your problem.*

1.  Open terminal and run command `sfdx upgrade` (I know this is the wrong command, but it executes a CLI version check)
2.  Press `y` to execute update

### Expected result

SFDX should update to 7.97.1

### Actual result

A message is returned stating I'm on the latest version
``` 
sfdx-cli: Updating CLI... already on latest version: 7.97.0-c130e7a
sfdx-cli: Updating plugins... done 
```

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): `7.97.0-c130e7a`

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
```
 ›   Warning: sfdx-cli update available from 7.97.0 to 7.97.1.
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-scanner 2.8.0
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.1 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.8.0 (core)
├─ data 0.4.3 (core)
├─ apex 0.1.21 (core)
├─ org 1.6.2 (core)
├─ limits 1.0.5 (core)
├─ custom-metadata 1.0.12 (core)
├─ user 1.2.8 (core)
├─ templates 51.3.0 (core)
├─ schema 1.0.5 (core)
├─ salesforce-alm 51.6.11 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.97.0 (core)
sfdx-git-delta 4.4.0
telemetry 1.1.2 (core)
```

**OS and version**: `MacOS BigSur 11.2.3`

**Java Version**: 
```
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

**Comment by WillieRuemmele** [comment]
Hi @dcinzona there was a delayed caching with the `7.97.1` release. `7.98.0` is `latest` now and this issue should go away. Try updating now and let me know how it goes

**Comment by dcinzona** [comment]
It worked - thank you!
