### ISSUE TITLE
sfdx force:org:open -u orgname closes command line (7.97.0-c130e7a)

### ISSUE THREAD

**Issue by SalesforcePetr** [forcedotcom/cli#989]
### Summary

After opening a scratch org via command line, the command line window is shut.

### Steps To Reproduce:

Have an org with an alias, e.g., yourAlias, ready.

1. open command line (CMD in Windows)
1. sfdx force:org:open -u yourAlias

### Expected result

The browser opens with the org. The command line window stays.

### Actual result

The browser opens with the org, but the command line shuts down.

### Additional information

Worked fine until about last week.

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version):
sfdx-cli/7.97.0 win32-x64 node-v15.14.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.1 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.8.0 (core)
├─ data 0.4.3 (core)
├─ apex 0.1.21 (core)
├─ custom-metadata 1.0.12 (core)
├─ limits 1.0.5 (core)
├─ org 1.6.2 (core)
├─ templates 51.3.0 (core)
├─ schema 1.0.5 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 51.6.11 (core)
└─ user 1.2.8 (core)
sfdx-cli 7.97.0 (core)
telemetry 1.1.2 (core)

**OS and version**:
Windows 10 x64

**Comment by WillieRuemmele** [comment]
Hi @SalesforcePetr thanks for pointing this out, it looks like there was a bug with the [open](https://github.com/sindresorhus/open/issues/236) library, we'll rollback which version we use and should publish that soon

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9177239](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000BdzdYAC/view)

**Comment by WillieRuemmele** [comment]
Hi @SalesforcePetr `plugin-org` version `1.6.4` should be released now with a fix. you should be able to `sfdx plugins:install @salesforce/plugin-org` to get the latest before next week's release

**Comment by SalesforcePetr** [comment]
@WillieRuemmele  `sfdx plugins:install @salesforce/plugin-org` helped. Only `sfdx update` didn't help. Thanks!
