### ISSUE TITLE
force:package:version:list should have a username parameter

### ISSUE THREAD

**Issue by DavinCasey** [forcedotcom/cli#99]
From https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_package.htm

**package:version:list**
Lists all package versions in the Dev Hub org.

This doesn't really make sense to me, as it doesn't seem to be all that useful for ISVs for two reasons:

- Firstly, our Dev. Hub. org may not ( / probably isn't) the same org as our packaging org. It's probably our 'production' org where we have Sales, Support, LMA etc.
- Secondly, we probably have multiple package org for our core package and then any number of extension / other packages.

Being able to specify a -u value with force;package:version:list means we'd be able to extract the correct version ID from the correct packaging org. This would be extremely useful in CI for example, where we may want to install a handful of different packages into an org as part of a build.

**Comment by clairebianchi** [comment]
@sfdc-db-gmail can you please take a look at this, it looks like a packaging bug?

**Comment by sfdc-db-gmail** [comment]
@DavinCasey 
For second-generation packages, you can use force:package:version:list and pass info about the user in the hub via the --targetdevhubusername argument.

For first-generation packages, you can use force:package1:version:list against the packaging org and pass info about the user via the --targetusername argument.

@clairebianchi
