### ISSUE TITLE
Specify the Zip name when using force:mdapi:retrieve instead of generic unpackaged.zip filename

### ISSUE THREAD

**Issue by mokchend** [forcedotcom/cli#992]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use  force:mdapi:retrieve . I want to specific the Zip name and locate when automate it on my ci environment 

**What are you trying to do**
automtae force:mdapi:retrieve with multiple package.xml and need ability to specify zip folder location

**Describe the solution you'd like**
Add parameter to allow the creation of a zip file in a specified directory and zip filename

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by uip-robot-zz** [comment]
This issue has been linked to a new work item: [W-9181617](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Bj5LYAS/view)

**Comment by mshanemc** [comment]
delivered May 2022
https://github.com/forcedotcom/cli/blob/main/releasenotes/sfdx/README.md#71500-may-12-2022
