### ISSUE TITLE
sfdx force:source:status is not aware of changes in folder structure. 

### ISSUE THREAD

**Issue by PawelWozniak** [forcedotcom/cli#994]
### Summary

sfdx force:source:status is not aware of changes in folder structure.

### Steps To Reproduce:

1. Have a happy soup project with force-app only
2. extract metadata to separate folder and add it to sfdx-project.json.
```    "packageDirectories": [
        {
            "path": "force-app",
            "default": true
        },
        {
            "path": "extpkg-Overcast",
            "default": false
        }
```
3. Run `sfdx force:source:status --local` to validate if sfdx figure out change.
4. Getting `ERROR running force:source:status:  Expected metadata file at path: D:\git\myProject-sfdx\force-app\main\default\objects\overcast__BackendLanguageForUserLanguage__c\overcast__BackendLanguageForUserLanguage__c.object-meta.xml`
5. This source is located at 
`D:\git\myProject-sfdx\extpkg-Overcast\main\default\objects\overcast__BackendLanguageForUserLanguage__c\overcast__BackendLanguageForUserLanguage__c.object-meta.xml`

When I retrieve metadata with package XML 
```
	<types>
		<members>*</members>
		<name>ApexClass</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomObject</name>
	</types>	
```
It is not creating duplicated metadata so it seems it is aware of the location change. 

I have removed apex.db and it was recreated after starting VSCode but no changes.

### Expected result

sfdx force:source:status should be aware that metadata were moved to different folder.
If it is hard to make it automatic then some command should be available to rebuild structure index. 

### Actual result

sfdx force:source:status is looking for metadata in old location and give error about missing file.

### Additional information

**SFDX CLI Version**(to find the version of the CLI engine run sfdx --version): sfdx-cli/7.98.0 win32-x64 node-v15.14.0

**SFDX plugin Version**(to find the version of the CLI plugin run sfdx plugins --core)
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-diff 0.0.6
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.3 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.8.0 (core)
├─ data 0.4.3 (core)
├─ custom-metadata 1.0.12 (core)
├─ org 1.6.2 (core)
├─ schema 1.0.5 (core)
├─ user 1.2.8 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ limits 1.0.5 (core)
├─ apex 0.1.21 (core)
├─ templates 51.3.0 (core)
└─ salesforce-alm 51.6.11 (core)
sfdx-cli 7.98.0 (core)
sfdx-git-delta 4.4.0
telemetry 1.1.2 (core)

**OS and version**: Windows 10 20H2

**Comment by WillieRuemmele** [comment]
Hi @PawelWozniak could you elaborate more on "extract metadata to separate folder and add it to sfdx-project.json." Are you moving data from within `force-app` to `extpkg-Overcast`? How are you doing that? Are you doing anything else between steps 2 and 3? Can you reproduce the bug with [dreamhouse](https://github.com/trailheadapps/dreamhouse-lwc) and list them in detail?

**Comment by PawelWozniak** [comment]
@WillieRuemmele As I understood from this article https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_mpd.htm you can make additional folders, add them in sfdx-project.json, and sort metadata. Then sfdx should figure out where metadata are stored.

In my case, we have Overcast SAP integration package installed which generated also additional classes, have some objects etc. All of this is rarely or even never modified so I want to keep it separate from force-app. This is a reason why I have created a separate folder extpkg-Overcast and moved metadata there keeping the whole structure /main/default/classes  etc.

I will try with dreamhouse tomorrow.

**Comment by PawelWozniak** [comment]
I was able to reproduce it on dreamhouse. My fork with commits https://github.com/PawelWozniak/dreamhouse-lwc 
Steps:
1. Forked dreamhouse-lwc, checkout to local computer
2. Created scratch org and pushed metadata `sfdx force:source:push`
3. Run `sfdx force:source:status` show no changes. Which is expected at this stage.
4. Created new folder `force-bugcheck` and moved there 4 classes and one object https://github.com/PawelWozniak/dreamhouse-lwc/commit/92145c4f1593832c0926e095991f1411a284040f 
5. Status `sfdx force:source:status --local`
```
D:\dreamhouse-lwc> sfdx force:source:status --local
=== Source Status
STATE          FULL NAME                  TYPE           PROJECT PATH
─────────────  ─────────────────────────  ─────────────  ─────────────────────────────────────────────────────────────────────────────────────────────
Local Deleted  GeocodingService           ApexClass      force-app\main\default\classes\GeocodingService.cls
Local Deleted  GeocodingService           ApexClass      force-app\main\default\classes\GeocodingService.cls-meta.xml
Local Deleted  GeocodingServiceTest       ApexClass      force-app\main\default\classes\GeocodingServiceTest.cls
Local Deleted  GeocodingServiceTest       ApexClass      force-app\main\default\classes\GeocodingServiceTest.cls-meta.xml
Local Deleted  Broker__c                  CustomObject   force-app\main\default\objects\Broker__c\Broker__c.object-meta.xml
Local Deleted  Broker__c.Broker_Compact   CompactLayout  force-app\main\default\objects\Broker__c\compactLayouts\Broker_Compact.compactLayout-meta.xml
Local Deleted  Broker__c.Broker_Id__c     CustomField    force-app\main\default\objects\Broker__c\fields\Broker_Id__c.field-meta.xml
Local Deleted  Broker__c.Email__c         CustomField    force-app\main\default\objects\Broker__c\fields\Email__c.field-meta.xml
Local Deleted  Broker__c.Mobile_Phone__c  CustomField    force-app\main\default\objects\Broker__c\fields\Mobile_Phone__c.field-meta.xml
Local Deleted  Broker__c.Phone__c         CustomField    force-app\main\default\objects\Broker__c\fields\Phone__c.field-meta.xml
Local Deleted  Broker__c.Picture_IMG__c   CustomField    force-app\main\default\objects\Broker__c\fields\Picture_IMG__c.field-meta.xml
Local Deleted  Broker__c.Picture__c       CustomField    force-app\main\default\objects\Broker__c\fields\Picture__c.field-meta.xml
Local Deleted  Broker__c.Title__c         CustomField    force-app\main\default\objects\Broker__c\fields\Title__c.field-meta.xml
Local Deleted  Broker__c.All              ListView       force-app\main\default\objects\Broker__c\listViews\All.listView-meta.xml
```
Which is ok as this stage.
6. Add folder definition to sfdx-project.json 
```
"packageDirectories": [
        {
            "path": "force-app",
            "default": true,
            "package": "DreamhouseLWC",
            "versionName": "Spring '21",
            "versionNumber": "51.0.0.NEXT"
        },
        {
            "path": "force-bugcheck",
            "default": false
        }
    ],
```
Commit https://github.com/PawelWozniak/dreamhouse-lwc/commit/5250d2df08cbd9f815bd41f4140af9e51971754e 
7. sfdx force:source:status --local
`ERROR running force:source:status:  Expected metadata file at path: D:\dreamhouse-lwc\force-app\main\default\objects\Broker__c\Broker__c.object-meta.xml`

Metadata is now in D:\dreamhouse-lwc\force-bugcheck\ instead of D:\dreamhouse-lwc\force-app\
Folder is registered in sfdx-project.json however sfdx force:source:status is looking for this file in old location.

**Comment by WillieRuemmele** [comment]
Hi @PawelWozniak that is a known limitation of working with [multiple package directories](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_mpd.htm) see at the bottom the second bullet under 'Considerations'. This is why we created the `force:source:tracking:reset` and `force:source:tracking:clear` commands.

**Comment by PawelWozniak** [comment]
@WillieRuemmele I understand that documentation says "If you reorganize your local project by creating package directories or moving metadata files between directories, the force:source:status command doesn’t list these changes." so then this error should not appear, missing metadata should be ignored as it was moved.
This error also appears on `push`, if I am forced to do `reset` to recover from this error then I will lose tracking of current changes.
I understand that scenario when you do changes to files and move files to other folder is rare but may happen. 

Possible improvement: 
I assume that cli is keeping somewhere a structure of directories and hashes of files to be able to find out what has changed. Having such information and command like `force:source:rescan` cli could detect moves (if the file wasn't changed) and restore tracking.

**Comment by shetzel** [comment]
@PawelWozniak
Currently, the tracking information is located within your project.  E.g., dreamhouse-lwc/.sfdx/orgs/<org_username>/sourcePathInfos.json for local and maxRevision.json for tracking source changes in the org.

If you are only moving files around as in your usecase you can do the moves, then run:
`sfdx force:source:tracking:clear` followed by `sfdx force:source:tracking:reset` and you are all set.
However, if you've made other changes either locally or remotely then running those commands is a dangerous thing.

So if your issue is about the source commands not handling moves and changes at the same time, you're correct and this is a known outage.  It would be a feature request to add a new command (e.g., rescan) to handle this scenario.  I agree it would be a useful feature and the source plugins should handle this better, either by default or with a command.

We are working on improvements to the source commands this year and source tracking is included in that.  Your usecase is something we'll be addressing as part of that effort.  Renames also provide a challenge that we're hoping to address  as well.

I think we can close this issue and you can reference this internal work item number which will track the feature request: W-9126560. Is this acceptable to you?

**Comment by PawelWozniak** [comment]
Greate I am looking forward to improvements. 
That outcome is fine for me I am closing the issue then.
