### ISSUE TITLE
SFDX package.xml deploy fails to correctly deploy intermediate dashboard folders

### ISSUE THREAD

**Issue by anderg4** [forcedotcom/cli#999]
### Summary

When deploying our package.xml which contains a folder hierarchy for dashboards, the intermediate folder deploys as root folder, meaning that references to them do not work (e.g. from lightning app builder)

### Steps To Reproduce:

package.xml structure
```
	<types>
		<members>MyFolder</members>
		<members>MyFolder/PublicDashboards</members>
		<members>MyFolder/PublicDashboards/my_Example_Dashboard</members>
		<name>Dashboard</name>
	</types>    
```

1.  sfdx force:source:deploy -x manifest/package.xml

### Expected result

Dashboard folders in correct heirarchy:

My Folder
|->Public Dashboards
|->|->My Example Dashboard

### Actual result

package.xml deployment fails on anything using the Dashboard.

Manual deployment of the reports & dashboards (including folders) results in a flattened folder structure.
My Folder
Public Dashboards
|->My Example Dashboard

Manually creating the expected folder structure on every target org resolves the issue, and allows package.xml deployment to continue as expected - however this is not sustainable.

### Additional information

**SFDX CLI Version** 
sfdx-cli/7.97.0 win32-x64 node-v15.14.0

**SFDX plugin Version**
@oclif/plugin-autocomplete 0.3.0 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.2 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.10.0 (core)
@oclif/plugin-update 1.4.0-3 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.6.0 (core)
alias 1.1.9 (core)
auth 1.5.1 (core)
config 1.2.8 (core)
generator 1.1.5 (core)
salesforcedx 51.8.0 (core)
├─ data 0.4.3 (core)
├─ apex 0.1.21 (core)
├─ schema 1.0.5 (core)
├─ custom-metadata 1.0.12 (core)
├─ org 1.6.2 (core)
├─ templates 51.3.0 (core)
├─ limits 1.0.5 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ user 1.2.8 (core)
└─ salesforce-alm 51.6.11 (core)
sfdx-cli 7.97.0 (core)
telemetry 1.1.2 (core)

**OS and version**:
Windows 10
Also MacOS Catalina 10.15.7

**Comment by WillieRuemmele** [comment]
Hi @anderg4 I'm trying to reproduce this bug but haven't been able to yet. I'll walk you through my steps and let me know where I'm going wrong or messing something up.

1. in org A go to the app manager and select Dashboards
2. create new folder `l1`
3. click into `l1` folder and create another folder `l2`
4. click into `l2` folder and create a new dashboard `dash` So the structure is `l1/l2/dash`
5. `pull`/`retrieve` the metadata down into my local project
6. In a new org (org B) with a `package.xml` below 
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>l1</members>
        <members>l1/l2</members>
        <members>l1/l2/dash</members>
        <name>Dashboard</name>
    </types>
    <version>46.0</version>
</Package>
```
`sfdx force:source:deploy -x package.xml -u orgB`
7. Open org B and see the folder structure and dashboards as I'd expect

**Comment by anderg4** [comment]
Hi,

Those steps look largely correct - however that is not what we see.  We have a lightning app page which references the dashboard and a custom tab for it (in a console app, if that matters).  The deployment fails, as the lightning page cannot find the dashboard which it references.  If you manually deploy both the reports and then the dashboard to Org B - it is placed in a flattened structure.  If you correct that structure on Org B manually, the package.xml deployment then succeeds.

package.xml version is 49.0
Source API version in sfdx-project.json is 51.0

To simulate our structure, you need to delete that dashboard from org B, and all the folders.
In org A, you create a lightning app page with the builder which references "dash".

    <types>
        <members>MyApp_Home</members>
        <name>CustomTab</name>
    </types>
    <types>
        <members>f1</members>
        <members>f1/f2</members>
        <members>f1/f2/dash</members>
        <name>Dashboard</name>
    </types>
    <types>
        <members>MyApp_Home</members>
        <name>FlexiPage</name>
    </types>


That flexipage looks like:

    <flexiPageRegions>
        <itemInstances>
            <componentInstance>
                <componentInstanceProperties>
                    <name>dashboardName</name>
                    <value>dash</value>
                </componentInstanceProperties>
                <componentInstanceProperties>
                    <name>hideOnError</name>
                    <value>true</value>
                </componentInstanceProperties>
                <componentName>desktopDashboards:embeddedDashboard</componentName>
            </componentInstance>
        </itemInstances>
        <name>region1</name>
        <type>Region</type>
    </flexiPageRegions>

Geoff Anderson | Solution Architect
T:  0161 819 6308<tel:0161%20819%206308> | M:  07884 015 051<tel:07884%20015%20051>
[interactive investor]<http://www.ii.co.uk/>

**Comment by WillieRuemmele** [comment]
Hi @anderg4 does this only happen when there's a Lightning app page referencing a dashboard? Is it specific to those two objects and being linked together? If you remove that and create a simple folder and dashboard structure, like what I was doing, do you see the same results? I'm trying to figure out if it's related to what's in the dashboard or not.

**Comment by amil-abdallah** [comment]
@WillieRuemmele Is there any chance we could re-open an investigation into this? I am facing similar issues around attempting to deploy a new flexi page that references a custom dashboard.

Issue: I can't deploy a new flexi page to an org that references a custom dashboard.  The error is:

Invalid dashboard Unique Name XXXXXXXXXXX - no dashboards found.

What I am attempting to do:  Build a flexi page with custom dashboard/reports in a scratch org and deploy the flexi page to another org.

Observations: If I build the flexi page in a scratch org where I manually add the dashboards and save the flexipage through Lightning Builder, I am able to source retrieve and source deploy the flexi page without error.  Once it deploys without error, my simple test is creating a copy of the flexi page metadata file and renaming it, then attempt to deploy this clone flexipage.  In theory, there should be no issue if the original deploys fine and it's a unique flexipage api name.  However, when I attempt to deploy the clone I get the error:  Invalid dashboard Unique Name XXXXXXXXXXX - no dashboards found.

Steps to Reproduce:

1. Create Scratch Org
2. Create a custom report and put in it's own folder (i.e. TestReports/TestReport1)
3. Create a custom dashboard that references the custom report created in Step 2 and save it to it's own folder (i.e. TestDashboards/TestDashboard1)
4. Create a custom flexi page that references the dashboard and save it
5. Source Retrieve the associated components' metadata (report folder, report, dashboard folder, dashboard, flexipage)
6. Generate a manifest for the associated components and attempt to deploy to another scratch org

Work Around:
The only work around is to deploy the reports and dashboards + flexi page (without any dashboard/report references) first and  then manually update the flexi page in Lightning Page Builder with the dashboard references.


This is not ideal for CI processes that utilize sfdx scratch org creation for check deployment as it appears the only work around is to actually edit the flexi page in Lightning Page Builder.
